### ISSUE TITLE
Modify seccomp arguments in profile config for more flexibility

### ISSUE THREAD

**Issue by boltronics** [netblue30/firejail#1]
At the time of writing, firejail supports:

```
       seccomp
              Enable default seccomp filter.

       seccomp syscall,syscall,syscall
              Enable seccomp filter and blacklist the system calls in the list on top of default seccomp filter.

       seccomp.drop syscall,syscall,syscall
              Enable seccomp filter and blacklist  the system calls in the list.

       seccomp.keep syscall,syscall,syscall
              Enable seccomp filter and whitelist the system calls in the list.
```

What I actually want is the default seccomp filter, with some additional system calls on top of the default seccomp filter. Additionally, I might want to remove some system calls in the same profile. To facilitate this functionality, I suggest changing the second seccomp usage option to work like follows:

```
       seccomp -syscall,-syscall,-syscall,+syscall,+syscall,+syscall
              Enable seccomp filter and whitelist and/or blacklist additional system calls in the list on top of the default seccomp filter.
```

Regardless of how the information is specified in the profile, it would be very helpful to somehow just say "use the default filter +/- these other system calls". This should cut down the work required for people following the [Firejail Seccomp Guide](https://l3net.wordpress.com/2015/04/13/firejail-seccomp-guide/).

**Comment by netblue30** [comment]
> What I actually want is the default seccomp filter, with some additional system calls on top of the default seccomp filter.

This is exactly what "seccomp syscall,syscall,syscall". It takes the default filter and adds "syscall,syscall,syscall".

>"use the default filter +/- these other system calls"

I'll leave this open as an enhancement for now.

**Comment by boltronics** [comment]
> This is exactly what "seccomp syscall,syscall,syscall". It takes the default filter and adds
> "syscall,syscall,syscall".

Sorry - I wasn't very clear. By "with some additional system calls on top of the default seccomp filter", I meant I wanted to allow additional system calls - so effectively it would unblock something the default filter has blocked. I think that's likely to be a more common scenario, as most people would go with the defaults, and then adjust them if they don't work. If they don't work, permissions will need to be relaxed, not tightened.

**Comment by netblue30** [comment]
I'll have to think about it, thanks.

**Comment by netblue30** [comment]
I am dropping it. It complicates the code to much.
