### ISSUE TITLE
Import revision history from sourceforge

### ISSUE THREAD

**Issue by tbu-** [netblue30/firejail#10]
Maybe you could import the revision history from the SVN repository on SourceForge in order to not lose history.

What do you think about this?

**Comment by tbu-** [comment]
I imported the SVN commit history into a git repository and used `git cherry-pick` to apply the newer commits not present in the the old SVN repository.

You could import it from https://github.com/tbu-/firejail, the master branch, like this:
```
git fetch tbu git://github.com/tbu-/firejail master
git reset --hard FETCH_HEAD
git push origin master -f
```
Note that this will overwrite the current history on GitHub, but since I applied all the commits from here, this should not be a problem.

**Comment by netblue30** [comment]
It is too much trouble, I'll leave it as is. Thanks.

**Comment by tbu-** [comment]
(I already did the work, the only thing left would be to execute the commands I gave you. Feel free to close the issue if you don't want to import the commit history.)

**Comment by netblue30** [comment]
Thanks.

**Comment by ypid** [comment]
Related to http://sourceforge.net/p/firejail/tickets/24/ and https://l3net.wordpress.com/2014/09/19/firejail-a-security-sandbox-for-mozilla-firefox/comment-page-1/#comment-6430.
I agree with @tbu- that you should have imported the SVN history and it is not to late yet :smile:
