### ISSUE TITLE
blacklist /mnt by default

### ISSUE THREAD

**Issue by thewisenerd** [netblue30/firejail#1001]
```/mnt``` directory is not blacklisted by default and this usually has mounted filesystems. should firejail consider blacklisting it by default, and have applications request whitelisting it if (and only if) necessary?

**Comment by netblue30** [comment]
No, we cannot do it. We can only blacklist/whitelist by default directories and files we know about. For example we blacklist /boot because we can access it by default and some of the files there are very bad. For /mnt or /media is different, the user can have mounted there anything.

**Comment by netblue30** [comment]
Added "disable-mnt yes/no" config option in /etc/firejail/firejail.config file.
