### ISSUE TITLE
little scripts to copy/paste and resize firejail --x11 

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#1005]
https://gist.github.com/xahare/f5f9a329223013bc352baae0a13e41d3

**Comment by netblue30** [comment]
I'll grab all of them and put them in the contrib section (https://github.com/netblue30/firejail/tree/master/contrib). I'll include them in the source code archive and have them installed under /usr/lib/firejail.

**Comment by netblue30** [comment]
All set, the files are installed in /usr/lib/firejail directory, thanks.
