### ISSUE TITLE
pass proper DPI to xpra and xephyr

### ISSUE THREAD

**Issue by ibukanov** [netblue30/firejail#1007]
Neither --x11=xpra nor --x11=xephyr report useful DPI information to applications. For example, under xpra xrandr and xdpyinfo reports:
```
~> firejail --x11=xpra xrandr -q 2>/dev/null | grep ' connected'
default connected 8192x4096+0+0 0mm x 0mm
~> firejail --x11=xpra xdpyinfo 2>/dev/null | grep 'resolution'
  resolution:    96x96 dots per inch
```
Under xephyr the situation is slightly better as at least xrandr reports the pixel dimensions matching the size of the xephyr window. Still even there there is no information about the physical size of the pixels:
```
~> firejail --x11=xephyr xrandr -q 2>/dev/null | grep ' connected'
default connected 1360x768+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
~> firejail --x11=xephyr xdpyinfo 2>/dev/null | grep 'resolution'
  resolution:    75x75 dots per inch
```

This results in very tiny fonts and icons on HighDPI applications.

As both xpra and Xephyr accept options to set the DPI it would be nice if firejail set that automatically based on the reported xrandr values for the primary screen.

**Comment by netblue30** [comment]
There is already support for xephyr. In a text editor open /etc/firejail/firejail.config and add a xephyr-extra-params statement at the end - you have some examples in the file. I'll do something similar for xpra.

**Comment by Ryujinra** [comment]
@netblue30 Any update on adding this feature for xpra? I use xpra for X11 forwarding, but without the ability to pass the dpi, fonts are tiny on a HiDPI display. Thanks.

**Comment by chiraag-nataraj** [comment]
You should be able to use `xpra-extra-params --dpi <blah>` to set the DPI for xpra.
