### ISSUE TITLE
Firefox profile: should whitelist ~/.gtkrc-2.0

### ISSUE THREAD

**Issue by blueyed** [netblue30/firejail#101]
Commit 5a52191865c5f0cdbc610b0ad656b919f0dc1605 breaks the theming in Firefox for me.

Adding `~/.gtkrc-2.0` to the whitelist fixes it.

There should be an `include` for GTK applications probably, which should be used for Firefox then, too.

**Comment by netblue30** [comment]
Fixed, thanks!

**Comment by 0nse** [comment]
Shouldn't there also be a whitelist entry for `~/.config/gtk-3.0/settings.ini`? I would follow the idea of @blueyed and put all GTK related files into a separate `include` for all GTK applications.

**Comment by netblue30** [comment]
Yes, I will have to whitelist also ~/.config/gtk-3.0 directory. I could move them in a separate include file, but there are only two of them in this moment: ~/.config/gtk-3.0 and ~/.gtkrc-2.0

**Comment by netblue30** [comment]
fixed!
