### ISSUE TITLE
Creation of blacklisted or read-only files

### ISSUE THREAD

**Issue by SYN-cook** [netblue30/firejail#1011]
In the moment, firejail can blacklist files or set them read-only, if the files already exist. But if a file to be marked as read-only or as blacklisted doesn't exist yet, firejail won't prevent its creation.
 
This is for sure entirely unproblematic in most cases, but I see a problem in particular with the bash configuration file zoo. It is probably safe to assume that on most systems the set of bash configuration files is incomplete. In a Debian home folder, for example, there are by default only `.bashrc`, `.bash_logout` and `.profile`.

Now if a program in a firejail sandbox would create a new `.bash_profile` or `.bash_login` file (both read-only via disable-common.inc) or a new `.bash_aliases` file, it could basically write there anything it wanted... and have it executed on next login. I'm not familiar with other shells, but there might be similar problems, too.

Thus, a nice-to-have feature would be to prevent the creation of blacklisted or read-only files.

For the issue with bash there are several easy workarounds of course: E.g. creating an empty file `~/.bash_aliases` and  renaming `~/.profile` to `~/.bash_profile` solves the problem for a default Debian desktop.

#1010

**Comment by SYN-cook** [comment]
Also, many distributions are shipped without autostart folder... and as long as it doesn't exist, even firejailed applications can make one.

**Comment by netblue30** [comment]
Yes it's a nice feature, I'll mark it as an enhancement, although I have no idea how to do it at this moment.

**Comment by SYN-cook** [comment]
@netblue30, just to provide a little more input here :) 

Do you think it could be helpful to write a warning to the syslog when a blacklisted file from disable-common.inc is freshly created (kernel provides the inotify API for such things)? From an attackers perspective, it would increase the risk of discovery somehow....
Further in this direction - since probably only a small minority of users regularly monitor their syslogs - one could also increase the verbosity and display some kind of message whenever a file from disable-common.inc is newly created. But although I think that would be useful from the perspective of security, I acknowledge that firejail is just as much about being easy to use and not getting in the way, and I'm not sure if we want our users to have making sense of (cryptic) warning messages.

An alternative way to handle this issue would be to employ whitelisting in more profiles. Also this has its downsides (in particular, whitelisting increases the risk of breaking functionality, because everything tends to be more restrictive), but an extensive use of whitelisting would at least be more compatible with the way Firejail works right now. However, in going this way, it would help a lot, IMHO, to have a profile switch like "whitelist everything that is not hidden (in the root of user home)". A very similar discussion about blacklisting, that inspired this comment, is going on in #578

**Comment by chiraag-nataraj** [comment]
In profile files, you can use 
```
mkdir <directory to blacklist>
blacklist <directory to blacklist>
```
which ensures the directory exists and cannot be accessed. If you want to do this for a file, use `mkfile` instead of `mkdir`.
