### ISSUE TITLE
gpg.profile prevents adding ppa

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#1012]
The current gpg.profile prevented adding a ppa on Ubuntu 16.04. I got the following errors:

```
gpg: Fehler beim Erstellen von »/tmp/tmp9y16xntr/secring.gpg«: Fehler beim Öffnen der Datei
gpg: Fehler beim Erstellen von »/tmp/tmp9y16xntr/pubring.gpg«: Fehler beim Öffnen der Datei
```

After commenting `private-tmp` this error message vanished but I got a new one:
```
gpg: Schlüssel C07EE05F von hkp-Server keyserver.ubuntu.com anfordern
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Operation not supported
```
It worked after commenting `net none` and changing the protocol line to
`protocol unix,inet,inet6`.

**Comment by netblue30** [comment]
I put the fixes you suggested in. The same fixes went in gpa.profile and gpg-agent.profile.

There is something you need to do manually: remove /usr/local/bin/gpg and /usr/local/bin/gpa files:
`````
sudo rm /usr/local/bin/gpg /usr/local/bin/gpa
`````
We have to assume that gpg infrastructure is rock solid. No amount of sandboxing could ever fix it. So, I removed them from firecfg list, running firejail on them by default is useless.

Thanks for the bug!
