### ISSUE TITLE
Running steam in firejail shows the login window with the copy of the background

### ISSUE THREAD

**Issue by ekaris** [netblue30/firejail#1014]
I'm using Ubuntu gnome 16.10 amd64 with firejail 0.9.40.1-1 provided from the distro repositories and the latest steam stable version as of today, to note is that if I run "firejail --noprofile steam" it works normally.

**Comment by netblue30** [comment]
Grab the latest version in git and give it a try. There have been quite a number of fixes since 0.9.40.

**Comment by ekaris** [comment]
I have upgraded to the latest stable version 0.9.44 and also newer OS, and it's the same problem, this started with the December steam update.

**Comment by netblue30** [comment]
I have some different problems with the December update, for me Steam is totally broken since the update, doesn't work even without firejail.

**Comment by ekaris** [comment]
That should be a library problem, it's solvable by installing or removing some libraries used by steam

**Comment by netblue30** [comment]
Yes, I guess is a library. I'll do a full reinstall of Ubuntu 16.04 here.

**Comment by bernhardu** [comment]
I see the same issue on Debian Stretch with firejail 0.9.44.4-1.
The login dialog gets drawn properly when starting with a copy of
/etc/firejail/steam.profile that got the  "noroot" line commented out.

**Comment by ekaris** [comment]
Any news about this?

**Comment by netblue30** [comment]
unfortunately not.

**Comment by ekaris** [comment]
It's working for me on ubuntu 17.04
