### ISSUE TITLE
private-dev not working?

### ISSUE THREAD

**Issue by viking777** [netblue30/firejail#1019]
The following profiles which I use all have 'private-dev' in their profile files:
thunderbird, keepassx, evince, opera, vlc, libreoffice. 
However an audit of any of them always gives the warning:
"/dev directory seems to be fully populated. Use --private-dev or --whitelist to restrict the access."

Does this mean that the 'private-dev' option is not working?

**Comment by netblue30** [comment]
I'll look into it.

**Comment by saildata** [comment]
In case it helps confirm/working as expected for this ticket:
I use a slightly modified [launcher for keepassx2](https://github.com/saildata/firejail-jailhouse/blob/master/usr/local/bin/firejail-keepassx2) with `--audit` results;
`GOOD: Access to /dev directory is restricted.`  
I also tested with the original profile with the same audit results (re: `/dev` directory)
Tested on Arch Linux, firejail version 0.9.45

**Comment by viking777** [comment]
Thanks saildata,  works for me also.
That's a hell of a long launcher though!

**Comment by saildata** [comment]
@viking777 glad to hear it resolved the issue! Hopefully it's not a bug, then.

**Comment by Fred-Barclay** [comment]
I can't replicate this today (firejail 0.9.52)... let's close for now and reopen if we need to.
