### ISSUE TITLE
giving lxc a restricted x server or wayland session?

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#1029]
is there an easy way to give an unprivileged lxc a restricted x server or wayland session?

**Comment by netblue30** [comment]
Although I didn't try wayland or an unprivileged firejail, it should be possible. X11 is just a UNIX socket, nothing in seccomp and namespaces should prevent it. The technology is definitely there, maybe there are some obscure details to be hammered out.

Unprivileged LXC uses a SUID program to configure networking, I am not sure how this is playing out with seccomp restricting privileges. I would try LXC without any kind of network namespace and without seccomp to get started.

**Comment by xahare** [comment]
ok, so priviledged :) 

the goal is a container with a gui that doesnt have access to the hosts gui. kinda what firejail does when you turn on private everything and give it xephyr or xpra, but going all the way with it.
