### ISSUE TITLE
Profiles: QuiteRSS is unable to start browser

### ISSUE THREAD

**Issue by genodeftest** [netblue30/firejail#1038]
Steps to reproduce:
1. install firejail 0.9.45 from git master
2. run firecfg as root to create symlinks in `/usr/local/bin`, including the one for quiterss
3. run quiterss
4. in QuiteRSS, try to open any URL in your browser

What happens:
URL doesn't open

What should happen:
URL should open in browser. Works fine if you run `/usr/bin/quiterss` instead of `/usr/local/bin/quiterss`.

You might have to run `unset SESSION_MANAGER` to get quiterss running at all, but that is a [different bug](https://bugzilla.redhat.com/show_bug.cgi?id=1411492).

**Comment by curiosity-seeker** [comment]
Yes, you're right. The culprit is the private-bin line in the profile. I've tried to add other binaries from /usr/bin which could qualify - but so far to no avail. As a workaround I suggest that you create `quiterss.profile` in ~/.config/firejail with the following entries:

```
ignore private-bin
include /etc/firejail/quiterss.profile
```

**Comment by genodeftest** [comment]
Thanks @curiosity-seeker , your workaround works for me ;)

**Comment by chiraag-nataraj** [comment]
Another fix might be blacklisting `/usr/local/bin` so that it's forced to run `/usr/bin/quiterss`?

**Comment by gasull** [comment]
Why was this closed if it is still an issue?  Why not removing [`private-bin quiterss` from the profile](https://github.com/netblue30/firejail/issues/1038#issuecomment-271643509)?

**Comment by SkewedZeppelin** [comment]
@gasull see https://github.com/netblue30/firejail/issues/1718#issuecomment-406819438

**Comment by gasull** [comment]
A [more recent solution](https://github.com/netblue30/firejail/issues/3308#issuecomment-968583131).
