### ISSUE TITLE
ASSERT_PERMS_FD should use fstat() rather than stat()

### ISSUE THREAD

**Issue by setharnold** [netblue30/firejail#1039]
Hello, please note that ASSERT_PERMS_FD() (and thus also ASSERT_PERMS_STREAM()) have a mistake that would lead to a segmentation violation, if they were actually used in the code:

#define ASSERT_PERMS_FD(fd, uid, gid, mode) \
	do { \
		struct stat s;\
		if (stat(fd, &s) == -1) errExit("stat");\   ### should use fstat() instead of stat()
		assert(s.st_uid == uid);\
		assert(s.st_gid == gid);\
		assert((s.st_mode & 07777) == (mode));\
} while (0)

https://github.com/netblue30/firejail/blob/master/src/firejail/firejail.h#L108

Thanks

**Comment by netblue30** [comment]
I've pushd the fix on all 3 branches, thanks.
