### ISSUE TITLE
[Patch] On including <sys/sysmacros.h>

### ISSUE THREAD

**Issue by hartwork** [netblue30/firejail#1042]
Hi!

I noticed that we patch
```
#include <sys/sysmacros.h>
```
into the firejail source code in Gentoo, see https://github.com/gentoo/gentoo/blob/8323924482277778d11fb699aa24303338fabdc8/sys-apps/firejail/files/firejail-0.9.44.2-sysmacros.patch .

Please consider applying that patch upstream. What do you think?
We would no longer have port it forward (as with 0.9.44.4) and could drop the patch count to zero downstream.

Thanks and best, Sebastian

CC: @aidecoe, @vapier

**Comment by netblue30** [comment]
I've pushed the patch on all my 3 branches. I've credited it to Mike Frysinger. If this is incorrect, you let me know. Thanks.

**Comment by vapier** [comment]
hmm, i thought i sent a PR for it, but i guess not.  must of been lost in the shuffle.

**Comment by hartwork** [comment]
Very cool, thank you!
