### ISSUE TITLE
SSH login: Permission denied error

### ISSUE THREAD

**Issue by GiantCrocodile** [netblue30/firejail#1047]
1. start something like your browser in Firejail
2. end Firejail but keep same terminal
3. do 'ssh <user>@<your-server-ip>'

When you enter username and password you get a Permission Denied Error. Once I had also a Permission Denied Error (publickey, password).

**Comment by netblue30** [comment]
This could happen if your terminal is running in a sandbox (the sandbox disables all ssh encryption keys). To see if your terminal is inside a sandbox, run "ls /proc". What do you mean by "end Firejail but keep same terminal"? Give me some more data, how do you run the whole thing?

**Comment by GiantCrocodile** [comment]
Your answer sounds like I triggered a bug in leaving the sandbox @netblue30. I did CTRL + C when I had a sandbox open so I close the sandboxed process (my browser) and stopped running Firejail. After that I expected my terminal in which I did run Firejail to be normal so I can use it with SSH without any problems.

**Comment by netblue30** [comment]
Cannot reproduce.

**Comment by GiantCrocodile** [comment]
Well as I saw this happening multiple times in issues now I don't think it is useful to say 'cannot reproduce' and to close the issue then without any more checking or fixing. If you don't know how to reproduce it - it would be useful to tell us how we can tell you what happens or to gather more information to make it reproducible for you. Otherwise the issue stays unresolved and makes it unusable for the users.

**Comment by netblue30** [comment]
Yes, but you have to give me something to work with. What commands are you using exactly?
