### ISSUE TITLE
Firefox freezes when opened with many tabs

### ISSUE THREAD

**Issue by fuelflo** [netblue30/firejail#1048]
Hey,

I got following problem. When starting FF with firejail, FF freezes, when I had 15+ tabs open on last close and when he restores the session upon start.

firejail 0.9.44.4
Ubuntu 16.10
Firefox 51.0b14

Any ideas how to fix this?
Thx in advance!

**Comment by curiosity-seeker** [comment]
The obvious question is: Have you tried if this also happens if you start Firefox with Firejail?

**Comment by fuelflo** [comment]
No, this only happens when I start FF _with_ firejail. Without FF doesn't freeze in the same situation.

**Comment by GiantCrocodile** [comment]
My firefox froze once I started it with firejail but never again after that. I just had 1 tab open. Not sure if this is related somehow. I wasn't able to type into the URL bar anymore nor to press any button.

**Comment by chiraag-nataraj** [comment]
@fuelflo One thing you can try is to first try `firejail --noprofile firefox` to see if it still happens (which would indicate that one of the basic setup steps firejail does screws with firefox --- unlikely). Assuming that works fine, then comment out most of the profile and slowly uncomment lines until it freezes again. (If I had the same problem, I'd help you debug...unfortunately, that isn't the case).

Side note: There have been a couple of updates to firejail recently as well, so maybe you should update (if possible) before trying all of this.

**Comment by GiantCrocodile** [comment]
After reading this comment here I just tried it again with Firejail 0.9.44.8 and my Firefox 50.1.0 hangs badly. It freezes everytime for some seconds and then it responds again by doing 1 thing like opening a tab and then freezes again and so on. I'm using Linux Mint. After launching it with `firejail --noprofile firefox` all freezes were gone and Firefox runs in Firejail as fast as usually without Firejail.

**Comment by chiraag-nataraj** [comment]
@GiantCrocodile Are you using the default profile?

**Comment by GiantCrocodile** [comment]
Yes I am @chiraag-nataraj!

**Comment by chiraag-nataraj** [comment]
@GiantCrocodile Huh. Seems to work okay for me, even with the default profile...

**Comment by chiraag-nataraj** [comment]
You can try my profile at https://github.com/chiraag-nataraj/firejail-profiles and see if it helps?

**Comment by GiantCrocodile** [comment]
@chiraag-nataraj I will try that later on. Not sure if this helps but I found this in the console when I launch Firefox with Firejail:

```
(firefox:2): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:2): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:2): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:2): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
```

**Comment by chiraag-nataraj** [comment]
That always comes up heh - no idea what it is, but it's harmless.

**Comment by GiantCrocodile** [comment]
Maybe it is related to my modern kernel? I'm using version 4.4. Running Firejail with `--debug` option made it run smooth too. It is just weird!

**Comment by chiraag-nataraj** [comment]
I'm using kernel 4.8.11 😉

**Comment by fuelflo** [comment]
@chiraag-nataraj using firejail version 0.9.44.8 now....still happens.
Thats the output from the console:

> Reading profile /etc/firejail/firefox.profile
> Reading profile /etc/firejail/disable-common.inc
> Reading profile /etc/firejail/disable-programs.inc
> Reading profile /etc/firejail/disable-devel.inc
> Reading profile /etc/firejail/whitelist-common.inc
> Parent pid 2566, child pid 2567
> Blacklist violations are logged to syslog
> Child process initialized
> Redirecting symlink to /usr/bin/firefox
> Warning: cannot switch euid to root
> Warning: cannot switch egid to root
> Warning: cannot switch euid to root
> Warning: cannot switch egid to root
> Warning: an existing sandbox was detected. /usr/bin/firefox will run without any additional sandboxing features
> Child process initialized
> ATTENTION: default value of option force_s3tc_enable overridden by environment.
> ATTENTION: default value of option force_s3tc_enable overridden by environment.

When using --noprofile, FF does not freeze. I'll try commenting out stuff from the profile today and post the results.

**Comment by chiraag-nataraj** [comment]
Note that it's not actually using the firefox profile...at least not in the example you posted the output from. See that `Warning: an existing sandbox was detected. /usr/bin/firefox will run without any additional sandboxing features`? Are you running it from within another sandbox?

**Comment by fuelflo** [comment]
Okay, thanks....that problem was probably caused, because I had a symlink in /usr/local/bin to automatically start all firefox instances with firejail. And while using 'firejail firefox' he called 'firejail firejail firefox' is that possible? However I deleted the link for now and it is running without the sandboxing error.

Concerning the profile....I checked everything and the problem only appears when I have `seccomp` activated.

**Comment by chiraag-nataraj** [comment]
Huh interesting. That's worrying...

**Comment by netblue30** [comment]
> firejail firejail firefox

The first "firejail" disables SUID, so the second "firejail" will be killed immediately by the sandbox.

**Comment by fuelflo** [comment]
@chiraag-nataraj why? if FF would be doing malicious syscalls shouldnt they just be blocked and not nessesarily freeze FF?

@netblue30 any idea how i could continue debugging? `strace -qcf` to see what calls he is making?

**Comment by chiraag-nataraj** [comment]
@fuelflo Well it's worrying because seccomp provides a huge part of the protection for most profiles (unless the program implements its **own** seccomp filter).

**Comment by fuelflo** [comment]
@chiraag-nataraj which FF might have? I'm not a pro and not sure how its implemented, but if you scroll way down on the FF about:support page you find this:

> Sandbox
> Seccomp-BPF (System Call Filtering)	true
> Seccomp Thread Synchronization	true
> User Namespaces	true
> Media Plugin Sandboxing	true

**Comment by chiraag-nataraj** [comment]
Huh...you're right. I think that might be relatively new.

**Comment by chiraag-nataraj** [comment]
Also different - mine (for some reason) disabled user namespaces (but keeps them enabled for privileged processes...?).

**Comment by anatoli26** [comment]
I just tried FJ from this repo (0.9.45) with Firefox 52.0.1 on Ubuntu 16.04 stock and it hanged as @fuelflo described in the initial post. Why this issue was closed? Is there a fix or a workaround?

**Comment by guillaume-uH57J9** [comment]
I reproduce this with Firejail 0.9.48, and Firefox 52.2.0.
There are several tabs opened (some tabs are older than 1 of my young nephews).

These were installed from the Debian testing repository (amd64), contrary to @fuelflo who is using Ubuntu, so that is not Ubuntu specific. 

Nothing in the logs looks like a sandbox violation warning from firejail.
The logs I looked at are "journalctl -f" and "tail -f /var/log/syslog"

Summary of tests conducted: 
* Firejail + Firefox + my profile with many tabs : freeze
* Firefox + my profile with many tabs : okay
* Firejail + Firefox + my profile with many tabs : freeze

**Comment by curiosity-seeker** [comment]
@guillaume-uH57J9 : You didn't tell us if you used extensions in the 3rd case (fresh new profile). And you should also test it with many tabs. 

If it's still okay this suggests that your normal profile is corrupted.

**Comment by guillaume-uH57J9** [comment]
@curiosity-seeker no extension was used in the 3rd case, as the "fresh new profile" imply

I will attempt creating a new profile with many tabs and provide an update.
But am a bit skeptical about "your normal profile is corrupted", since Firefox never freezes when started normally, but repeatedly freeze when started with firejail.

**Comment by vn971** [comment]
"works for me"(C). I do use firefox with firejail, and I never have freezes.

I use a custom profile without blacklists though. (I prefer to always have a whitelist for firejail-ed apps instead.)
My profile also includes the following lines:
```
private-bin firefox,icecat,icecat-bin
seccomp.block-secondary
shell none
private-dev
```

Hope that can help in diagnostics. (You can try those settings in your firefox to see if it'll hang.)
