### ISSUE TITLE
LTS version missing features and profiles?

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1049]
Ubuntu 16.04 LTS repositories contain Firejail LTS version (version 0.9.38 currently), but some features are missing (for example, X11 sandboxing support). Also, some profiles for popular programs are missing (for example, profile for Libre Office).

What would be the easiest way to complement LTS version with missing features and profiles?

Latest Firejail version from GitHub does include Libre Office profile since Jun 2016, LTS version still doesn't. When will Firejail LTS version include these features and profiles (especially X11 sandboxing and Libre Office profile)?

**Comment by netblue30** [comment]
You will need to move to 0.9.44.x, LTS is frozen at version 0.9.38. There will be no new features added to it.

**Comment by rekixex** [comment]
May I ask why? Ubuntu is the most popular Linux Operating System, I think many novice users would be delighted to have more features, at least more profiles, for this easy-to-use yet powerful tool.

Do you suggest to download the deb package or to clone Firejail’s source code from Git repository? Is development version from Git repository stable enough for everyday use?

**Comment by rekixex** [comment]
@netblue30 May I ask why? Ubuntu is the most popular Linux Operating System, I think many novice users would be delighted to have more features, at least more profiles, for this easy-to-use yet powerful tool.

Do you suggest to download the deb package or to clone Firejail’s source code from Git repository? Is development version from Git repository stable enough for everyday use?

**Comment by rekixex** [comment]
@netblue30 May I ask why? Ubuntu is the most popular Linux Operating System, I think many novice users would be delighted to have more features, at least more profiles, for this easy-to-use yet powerful tool.

Do you suggest to download the deb package or to clone Firejail’s source code from Git repository? Is development version from Git repository stable enough for everyday use?

**Comment by rekixex** [comment]
@netblue30 May I ask why? Ubuntu is the most popular Linux Operating System, I think many novice users would be delighted to have more features, at least more profiles, for this easy-to-use yet powerful tool.

Do you suggest to download the deb package or to clone Firejail’s source code from Git repository? Is development version from Git repository stable and secure enough for everyday use?

**Comment by SYN-cook** [comment]
Ubuntu follows a [policy](https://wiki.ubuntu.com/StableReleaseUpdates) for package updates in stable release repos, which effectively freezes firejails version at 0.9.38. You can try your luck and suggest an update or a backport on Ubuntus launchpad... but better don't expect too much.

At the moment, the easiest path to new firejail versions in Ubuntu is probably to add this [PPA](https://launchpad.net/~deki/+archive/ubuntu/firejail). Alternatively you find fresh packages also on [Sourceforge](https://sourceforge.net/projects/firejail/files/firejail/). If you are only after the profiles, you can just take them from Git and copy them to `~/.config/firejail`.

Your question was not pointed at me, please everyone apologize for stepping in.

**Comment by rekixex** [comment]
@SYN-cook I just wanted to say that maybe LTS version could keep getting new features, at least new profiles, considering Firejail's aim to be as simple as possible out-of-the-box.

@netblue30 Is development version from Git repository stable and secure enough for everyday use?

I am considering making a simple script to update Firejail from Git repository. It could look like this:

```
#!/bin/bash

cd ~/firejail
make clean
git pull
make clean && make
sudo make install

exit
```

What do you think? How often should version from Git repository be updated (once a day / once a week)?

**Comment by SYN-cook** [comment]
@rekixex Well, unfortunately that policy is less about package numbers and more about the package contents. But you can try you luck and reach out to the Ubuntu package maintainers.... all you need to do is posting your request on Ubuntu launchpad.

**Comment by Fred-Barclay** [comment]
@rekixex That script looks pretty good. Here's mine for reference (it clones the github repo as well):
```
if [ $EUID != 0 ]; then
	sudo "$0" "$@"
	exit $?
fi

git clone https://www.github.com/netblue30/firejail.git
cd firejail
./configure --prefix=/usr
make
make install-strip
echo "Firejail was updated!"
cd ..
rm -rf firejail
```

I just update whenever I notice that @netblue30 has commited new changes - usually at least several times a week. Beware that this means you may get code that has bugs!

Oh - since you're using Ubuntu I would do this instead:
```
if [ $EUID != 0 ]; then
	sudo "$0" "$@"
	exit $?
fi

git clone https://www.github.com/netblue30/firejail.git
cd firejail
./configure --prefix=/usr
make deb
dpkg -i firejail*.deb
echo "Firejail was updated!"
cd ..
rm -rf firejail
```
That way, apt and dpkg will know about firejail and be able to handle it properly. :smile:
Cheers!
Fred

**Comment by rekixex** [comment]
@Fred-Barclay Tested your script, works flawlessly. Thank you very much! :)

(One warning reported but finished successfully anyway:
`warning: the authors of lintian do not recommend running it with root privileges!`)

Maybe this script could be added to documentation to help users to compile Firejail from the source code? It's more complete than current instructions (https://firejail.wordpress.com/download-2/).

I will post here complete instructions to automate compiling Firejail from the source code just in case someone needs help (applicable to Ubuntu). Feel free to correct it. :)

#create and open a script file

`sudo nano /usr/local/sbin/firejail.sh`

#paste this code inside

```
#!/bin/bash

if [ $EUID != 0 ]; then
	sudo "$0" "$@"
	exit $?
fi

git clone https://www.github.com/netblue30/firejail.git
cd firejail
./configure --prefix=/usr
make deb
dpkg -i firejail*.deb
echo "Firejail was updated!"
cd ..
rm -rf firejail

exit
```

#`Ctrl + X`, then `Y`, then `Enter` (to save a file)

#set file owner and permissions

`sudo chown root:root /usr/local/sbin/firejail.sh`

`sudo chmod 700 /usr/local/sbin/firejail.sh`

#execute a script file and enter a password when required

`sudo /usr/local/sbin/firejail.sh`

#don't forget to execute it again after a few days (maybe once a week is sufficient?) to update Firejail! (You should be able to create desktop / panel launcher to excute a script, depending on your Linux distribution.)

#enjoy using Firejail!

**Comment by curiosity-seeker** [comment]
> (One warning reported but finished successfully anyway:
warning: the authors of lintian do not recommend running it with root privileges!)

That's because the whole script is executed with root privileges, but that's not necessary. This is the script I'm using:
```
rm -rf ~/firejail
git clone https://github.com/netblue30/firejail.git
cd firejail
./configure --prefix=/usr
make
sudo make install
```
It works flawlessly. And note that make deb isn't necessary, IMHO. Until recently I used that script on Ubuntu, and Firejail 0.9.45 was shown in Synaptic.

**Comment by rekixex** [comment]
@curiosity-seeker 

`EDIT: I'm not sure what's the use of the further instructions in your post. They are not necessary - Firejail works just by executing the script.`

You are right, I updated the comment. :)

**Comment by rekixex** [comment]
> EDIT: I'm not sure what's the use of the further instructions in your post. They are not necessary - Firejail works just by executing the script.


You are right, I edited the comment. :)

**Comment by rekixex** [comment]
@curiosity-seeker 

> EDIT: I'm not sure what's the use of the further instructions in your post. They are not necessary - Firejail works just by executing the script.

You are right, I corrected it. :)

**Comment by rekixex** [comment]
@curiosity-seeker 

Thanks for your script. :)

> EDIT: I'm not sure what's the use of the further instructions in your post. They are not necessary - Firejail works just by executing the script.

You are right, I corrected it. :)

**Comment by netblue30** [comment]
Let's make it official! Can you guys push the script in contrib directory (https://github.com/netblue30/firejail/tree/master/contrib). All the scripts in this directory are getting installed in /usr/lib/firejail/. Then, I'll add an option in the interface, something like "firejail --update-deb" and call the script directly from firejail to update the thing. Will this work?

**Comment by rekixex** [comment]
@netblue30 

> I'll add an option in the interface, something like "firejail --update-deb" and call the script directly from firejail to update the thing.

Good idea, I am looking forward to it. :)

**Comment by netblue30** [comment]
all set, the feature is in: --git-install
