### ISSUE TITLE
Symlink handling

### ISSUE THREAD

**Issue by blueyed** [netblue30/firejail#105]
The Vimperator addon uses `~/.vimperatorrc` and `~/.vimperator/`, which should be added to the whitelist.

However, I am using symlinks for those to the file/folder in `~/.dotfiles`, and whitelisting seems to only add the target.

I think it should add both the symlink and the target.

As a side note: adding both the link and the target of the folder will result in an error:

	Whitelisting /home/user/.dotfiles/vimperatorrc
	Whitelisting /home/user/.dotfiles/vimperator
	Whitelisting /home/user/.dotfiles/vimperator
	Error mkdir:whitelist_path(99): File exists

**Comment by blueyed** [comment]
For some reason this also caused the `~/.dotfiles/vimperatorrc` file to get emptied!

That happened at `01:41:34.245112301` (timestamp of the zero-byte file), apparently when starting firefox through firejail on 01:41:34.225 (which ran for a while).  I don't know what whitelist config I was using in that case, but either firejail emptied it (unlikely?), or Vimperator assumed that there is none?! - but that should probably not cause it to create an empty one (but I don't know).

**Comment by netblue30** [comment]
Vimperator is in, I'll fix the simlinks. Thanks.

**Comment by reinerh** [comment]
There is a vimperator-fork called pentadactyl that has similar files/dirs that should be whitelisted: ~/.pentadactylrc and ~/.pentadactyl/

**Comment by blueyed** [comment]
@reinerh 
:+1:

**Comment by netblue30** [comment]
Pentadactyl is in, thanks!

**Comment by netblue30** [comment]
Fixed.
