### ISSUE TITLE
VLC audio issue on the latest release 0.9.44.6.

### ISSUE THREAD

**Issue by mr-blobbyyy** [netblue30/firejail#1050]
No sound at all, tried both audio and video files. VLC error upon opening:
```
Audio output failed:
The audio device "default" could not be used:
No such file or directory.
```
...the video still plays, but no audio. Manually selecting the correct "audio device" within VLC's settings also does nothing (there's quite a few selections if you have a gpu that supports hdmi audio. I don't use this audio method as I have this sound "profile" as "off" within xfce's audio settings -- but VLC apparently still displays these options.)

xfce 4.12
vlc 2.2.2 (xenial repo :rage:)
 
I have a samson mic + audio setup usb using the usb audio driver, listening on headphones. Everything was fine on version 0.9.44.4. Other (non-firejailed apps) are playing audio normally. "Onboard audio" is disabled via the uefi/bios.

**Comment by mr-blobbyyy** [comment]
Ok I seemed to have found a workaround. Using these audio settings (versus selecting them on-the-fly while VLC was opened mentioned previously) is working (remember to restart VLC because apparently VLC settings are not applied until a restart):
![vlc-fjsettins2](https://cloud.githubusercontent.com/assets/19324958/21972098/8d812824-db7c-11e6-8777-b2e883f23d42.png)

Curiously, with these settings if I select "automatic" (or even "pulseaudio") again for the "output module" -- it still works...so the issue here is apparently a problem with ALSA accessing the "default" device specifically. If I select the "default" device for ALSA, the problem reproduces.

P.S. :man_facepalming: about "VCL" -- I can't be bothered making another screenie.

**Comment by mr-blobbyyy** [comment]
Ok I have a dissapointing update, the method above will not work (for me) if another app is using the microphone (even if the mic is muted.) This simply includes loading a game in steam or if you're on the google hangouts page in firefox as the error in VLC turns into this:

```
Audio output failed:
The audio device "sysdefault:CARD=Mic" could not be used:
Device or resource busy.
```
Exiting the page or game will make audio functional again. Very weird.

I also believe I have the relevant terminal errors for the default non-functional configuration:
```
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
alsa audio output error: cannot open ALSA device "default": No such file or directory
core audio output error: module not functional
core decoder error: failed to create audio output
```

**Comment by mr-blobbyyy** [comment]
Update: looks like this issue doesn't affect the LTS version. My mistake probably for thinking it would work on Xenial.

**Comment by nick75e** [comment]
Hi!

I have the same issue with any sandboxed apps (firefox, vlc, spotify)
Did you find a solution?

Linux Mint 17.3, firejail 0.9.44.6

**Comment by peesci** [comment]
I have opened new issue for this bug,please provide your input there:
https://github.com/netblue30/firejail/issues/1054

**Comment by mr-blobbyyy** [comment]
@nick75e yeah, use the most recent LTS firejail 0.9.38.10 for Xenial and Trusty as this issue doesn't affect the LTS version. Although, due to some recent follow-ups, this issue may also be a usb audio driver issue.

**Comment by samhithaaaa** [comment]
> I have opened new issue for this bug,please provide your input there:
> #1054

+1
