### ISSUE TITLE
Firejail prevents qbittorrent from accessing tun0 network interface

### ISSUE THREAD

**Issue by anaknaga** [netblue30/firejail#1051]
Using qbittorrent with its firejail profile prevents qbittorrent from accessing tun0 network interface.

**Comment by netblue30** [comment]
How do you start the sandbox? Also, can you disable "private-dev" line in /etc/firejail/qbittorrent.profile (add a # in front of the line). Another line you can try to disable is "protocol unix,inet,inet6".

Question: why do you need tun0? Are you connecting over a tunnel?

**Comment by anaknaga** [comment]
Thanks, disabling "protocol unix,inet,inet6" did the trick. If not disabled, qbittorrent cannot see any of my network interfaces. I'm indeed connecting through a VPN, and have set tun0 for use in its advanced options.

I'm starting it with a the default profile with the "ln -s /usr/bin/firejail /usr/local/bin/qbittorrent" technique.

**Comment by netblue30** [comment]
Cool!
