### ISSUE TITLE
No sound using pulseaudio after 0.9.44.6 update

### ISSUE THREAD

**Issue by peesci** [netblue30/firejail#1054]
Recently something broke audio when using firejail under pulseaudio.
When playing video with mpv:
> [ao/pulse] Init failed: Connection refused
> [ao] Failed to initialize audio driver 'pulse'
> Could not open/initialize audio device -> no sound.

Similiar report here: https://github.com/netblue30/firejail/issues/1050
also: https://bbs.archlinux.org/viewtopic.php?pid=1684615#p1684615
Affected: firejail version 0.9.44.6 and current git master.

firejail version 0.9.44.4 works fine.

**Comment by olliemath** [comment]
Having this issue in Firefox on Arch - rolling back to 0.9.44.4 works fine.

**Comment by pyamsoft** [comment]
Chiming to confirm the issue on my end as well using 0.9.44.6.

Applications work fine on 0.9.44.6. I can confirm that launching an application like Firefox on the command line with

```
# firefox needs the netlink protocol
$ firejail --noprofile --protocol=unix,inet,inet6,netlink --private firefox
```

and navigating to a site like Youtube produces a popup near the address bar stating that you need to install PulseAudio, even though it is already installed on the system. Other applications that are jailed into private directories also are unable to use PulseAudio.

Downgrading to 0.9.44.4 fixes the PulseAudio issue in all applications.

**Comment by mr-blobbyyy** [comment]
Is everyone having issues using a usb audio device?

**Comment by nick75e** [comment]
No, mine is integrated.
And like everyone else, I downgraded to v0.9.44.4

**Comment by netblue30** [comment]
This is a major screw up! I'll bring in a fix shortly.

**Comment by netblue30** [comment]
Fixed on bugfix branch, also fixed on mainline branch. If nothing else comes up, I'll do a new release tomorrow. Thank you for reporting it.
