### ISSUE TITLE
Firefox Developer Version - 52.0a2 (2017-01-16) (64-bit) not setting as default browser

### ISSUE THREAD

**Issue by manatarms** [netblue30/firejail#1055]
Hello everyone,

I'm using Firejail with FF developer version on Linux Mint 18.1 Cinnamon. I have the FF developer directory in _/usr/lib/firefox-dev_.

For some reason every time I run FF using _firejail /usr/lib/firefox-dev/firefox_ it does a check for setting FF as the default browser (To which I have said yes every time, but it stills does the check). However, when I just run FF developer without Firejail it works perfectly. 

Also FF developer doesn't update when I run it with Firejail. It says FF doesn't have the correct permission. Again, it works perfectly when not running Firejail.

I'm pretty sure I need to do some small changes, any help is appreciated. 

Have a great day,
Thank you

**Comment by pyamsoft** [comment]
Chiming in to say I can confirm this issue, but only on the first launch.

In my case, I launch Firefox with --private=DIRECTORY, so it does save to a location on disk. On the first launch after upgrading from 0.9.44.4 to 0.9.44.6 I noticed the issue about default browsers, but after selecting the default browser once the issue went away.

Downgrading to 0.9.44.4 seems to fix the issue.

**Comment by manatarms** [comment]
I'm trying to add the directory location as a whitelist directory but Firejail says _Error: invalid whitelist path /usr/lib/firefox-dev_. Any idea about what I could do? I think whitelisting this directory will fix the other issues for me.

**Comment by manatarms** [comment]
Managed to fix this by moving my FF folder to \opt. I then whitelisted the opt\firefox-dev folder in firefox.profile . Works fine now.
