### ISSUE TITLE
Firefox without Sound, Qmmp don't play an song

### ISSUE THREAD

**Issue by tuxer66** [netblue30/firejail#1057]
hi

Firefox works, but it don't play any sound, for example on youtube.
Qmmp works too, but i can't start any song

I work with Arch Linux.

**Comment by netblue30** [comment]
PulseAudio got broken in 0.9.44.6. I'll release 0.9.44.8 with a fix tomorrow.

Monitor this discussion: https://github.com/netblue30/firejail/issues/1054

**Comment by telis80** [comment]
I have the same problem with Chromium

**Comment by netblue30** [comment]
All fixed in 0.9.44.8 version.
