### ISSUE TITLE
Feature request: join network namespace created by 'ip netns create'

### ISSUE THREAD

**Issue by zackw** [netblue30/firejail#1058]
The `ip` utility has a subcommand to create persistent network namespaces, and to run processes in these namespaces. It would be really handy if firejail could put processes into network namespaces created in this manner.  I specifically want this because I have scripts that bring up VPN tunnels and associate them with these namespaces, and then run specific programs in those namespaces (so, at the same time, process A can be talking to VPN proxy X, process B to proxy Y, etc) and I'd like to have reliable sandboxing for these processes.

In addition to setting the network namespace itself, `ip netns exec NAMESPACE` puts the process into a fresh mount namespace, and then remounts `/sys` (so that its contents reflect the network namespace) and bind-mounts `/etc/netns/NAMESPACE/whatever` over `/etc/whatever` for all whatever (so, for instance, you can override `/etc/resolv.conf` this way).  And it also does a `vrf_reset()`, which I don't know what that means.

For more information on the `ip` feature:

* [`ip netns` manpage source](https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git/tree/man/man8/ip-netns.8)
* [core implementation of the "put a process into a network namespace" operation](https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git/tree/lib/namespace.c)
* [implementation of the `ip netns` command line](https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git/tree/ip/ipnetns.c)

**Comment by netblue30** [comment]
all merged.
