### ISSUE TITLE
bindmount for /etc/hosts without root

### ISSUE THREAD

**Issue by ibukanov** [netblue30/firejail#1063]
To override an IP address for a host in a jail I use the --bind option to point /etc/hosts to a file with the desired IP mapping. However, it requires that I run firejail as root. It would be nice to have an option to provide a custom context for /etc/hosts without requiring root. This could be similar to --dns that provides a custom /etc/resolve.conf.

**Comment by netblue30** [comment]
You are all set:
`````
       --hosts-file=file
              Use file as /etc/hosts.

              Example:
              $ firejail --hosts-file=~/myhosts firefox
`````
In a profile file use "hosts-file filename".

**Comment by ibukanov** [comment]
This is brilliant :)

I am curious why the code insists that the file should be owned by the user? I.e. what is problematic with mounting a file that is owned by root and world readable?

**Comment by ibukanov** [comment]
Is that restriction that the file must be owned by the user to prevent an accidental exposure of root-owned files that are world-readable but not accessible to the user due to no executable permissions on a file path?

**Comment by netblue30** [comment]
You are right, in this case a simple read access check is enough. All fixed in git.
