### ISSUE TITLE
--x11=xorg "unable to open display" but runs anyway

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#1065]
xlogo does run. this also happens with firefox. 
host is ubuntu 16.04 amd_64 running in virtualbox with guest extensions

```
$ firejail --x11=xorg xlogo
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 4897, child pid 4898
/usr/bin/xauth: (argv):1:  unable to open display ":0".
Child process initialized

Parent is shutting down, bye...
```

**Comment by chiraag-nataraj** [comment]
Huh. I get a "No protocol specified" and "Error: Can't open display: :0" and `xlogo` doesn't launch. I'm running on Debian sid/experimental x86_64.

**Comment by netblue30** [comment]
Working fine for me on Debian stable:
`````
$ firejail --x11=xorg xlogo
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 3363, child pid 3364
Child process initialized
`````

**Comment by netblue30** [comment]
When I run --x11=xorg firefox I get a warning: Xlib:  extension "RANDR" missing on display ":0.0". Other than that, firefox (version 45.6.0) seems to be working fine. It is possible newer firefox versions behave differently, or don't work at all.

**Comment by valoq** [comment]
Is there another window server running?
If X11 access is blocked but e.g. access to a wayland server is available, which is the case on modern gnome desktops, the application will still run, but display this warning.

**Comment by xahare** [comment]
seems a difference between newer and older xorg then. there must be a way to automate testing across a few distros. 

@valoq when using xwayland, couldn't query security extension on display ":0"

**Comment by xahare** [comment]
just confirmed this in ubuntu desktop. only the terminal windows showed in xwd. not the background, any of the desktop/window manager widgets, or file manager that was open. tried again in xterm, and again, only the gnome-terminal windows showed against a black background.

any idea where to go from here? where could the bug be?

```
user@work-terminal:~$ cat rootdump.sh 
xwd -root > root.xwd
user@work-terminal:~$ firejail --x11=xorg ./rootdump.sh 
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 19026, child pid 19027
/usr/bin/xauth: (argv):1:  unable to open display ":0".
Child process initialized

Parent is shutting down, bye...
user@work-terminal:~$ gimp root.xwd 

```
