### ISSUE TITLE
copr repo for firetools

### ISSUE THREAD

**Issue by indolering** [netblue30/firejail#1067]
I would like to run Firetools, but you don't have a copr repo and I don't want them to get out-of-sync.

**Comment by xahare** [comment]
till then, heres an atom feed https://github.com/netblue30/firejail/releases.atom

**Comment by netblue30** [comment]
Coper repos are maintained outside the project. I'll have a new firetools release in the next two weeks, or maybe just a test release, and there will be a rpm package available. In this moment firetools git repo is a war zone, so probably is a good idea to stick with the old release.

**Comment by indolering** [comment]
> Coper repos are maintained outside the project.

😢 

You publish RPMs through SourceForge, is there no way to maintain a stable repo?  What about using [OSE](https://build.opensuse.org/)?

**Comment by netblue30** [comment]
After the next release the repo will be stable enough to be followed live - there are big changes going in at the moment.

**Comment by indolering** [comment]
@netblue30 Awesome, thank you!

**Comment by indolering** [comment]
Did something change?

**Comment by netblue30** [comment]
Almost ready for a new release!
