### ISSUE TITLE
Per directory overlayfs filesystems?

### ISSUE THREAD

**Issue by talwrii** [netblue30/firejail#1071]
I'm happily misusing firejail to sandbox zsh.

One use case is distrusting code that I clone off the internet. For this purpose I create a firejail  where

* Important information is private
* The cloned directory is writeable
* I have read-only access to configuration files for things like git / programming tools

One problem I get is that some of my zsh plugins want to write to files. An ideal solution here would be give them an overlayfs to write into. However, I don't want an overlayfs everywhere  (my experience profiles is that I tend to try to use shells for things that I'm not meant to unless there's something to stop me, so I would happily try to make changes to the overlayfs shell that then get lost).

One solution is the have something like  `--overlay-dir=blah` so that I can turn overlays on and off in a fine-grained fashion.

Opinions?

**Comment by netblue30** [comment]
--overlay-dir will be!
