### ISSUE TITLE
--no-tmpfs option?

### ISSUE THREAD

**Issue by talwrii** [netblue30/firejail#1072]
As part of my quest to misuse firejail for jailing zsh's, I'd quite like to get a zsh that is capable of reading /var/log, this doesn't seem to be possible since a tmpfs is mounted on top of it.

Would it make sense to have a `--no-tmpfs` option to disable default tmpfs mounts.

**Comment by netblue30** [comment]
I'll put something in, thanks.

**Comment by netblue30** [comment]
All set in git:
`````
       --writable-var-log
              Use the real /var/log directory, not  a  clone.  By  default,  a
              tmpfs  is  mounted  on top of /var/log directory, and a skeleton
              filesystem is created based on the original /var/log.

              Example:
              $ sudo firejail --writable-var-log
`````

**Comment by talwrii** [comment]
Awesome :).
