### ISSUE TITLE
Ability to disable process namespaces

### ISSUE THREAD

**Issue by talwrii** [netblue30/firejail#1073]
I'm misusing firejail to jail zsh. It would quite nice if i could get a zsh that lives in the the global process namespace so that ps works etc.

**Comment by netblue30** [comment]
Not possible, all the code expects a process namespace.

**Comment by talwrii** [comment]
Cool cool.

If you think something like this feature is worth having (which is far from clear),  one approach might be to steal the process namespace from /proc/1/ns/pid in the outer scope, which I presume is the default namespace for the machine.

**Comment by valoq** [comment]
You can probably get the process list by using dbus and systemd to start a process outside the sandbox.
If the dbus socket in /run/user/UID/bus is available, it presents a way to escape the sandbox.
