### ISSUE TITLE
Gnome-mplayer profile  issue with private-bin

### ISSUE THREAD

**Issue by acrobat1** [netblue30/firejail#1074]
In Debian stable with firejail 0.9.44.4 the default profile for gnome-mplayer has the **private-bin** argument, however I think this doesn't work properly, because gnome-mplayer can be launched but can' t play anything, it just hangs.

Disabling it with ignore=private-bin solves the issue, and interestingly mplayer does indeed work with the same option (adapted for it, i.e *private-bin mplayer*) : shouldn't gnome-mplayer be just a front-end for mplayer? 

Why this option is apparently working only for mplayer  ?

**Comment by netblue30** [comment]
I commented out private-bin in gnome-mplayer.profile, thanks for the bug.
