### ISSUE TITLE
hide new userspace warning with --quiet

### ISSUE THREAD

**Issue by azimut** [netblue30/firejail#1077]
https://github.com/netblue30/firejail/blob/7d11cf62ca175696c8f5998de42c510924c6dcc3/src/firejail/sandbox.c#L889
```
	fprintf(stderr, "Warning: cannot create a new user namespace, going forward without it...\n");
```

Based on other issues it looks like this needs to be silent too with "--quiet".
Edit: added actual line of the output for future references.

**Comment by netblue30** [comment]
Fixed, thanks for the bug.
