### ISSUE TITLE
Owlboy: Unable to detect controllers

### ISSUE THREAD

**Issue by Krakn** [netblue30/firejail#1080]
# Modified steam.profile

    # TODO:
    #   Fix controller support.

    noblacklist ${HOME}/.local/share/Owlboy
    noblacklist ${HOME}/.config/Owlboy
    include /etc/firejail/disable-common.inc
    include /etc/firejail/disable-programs.inc
    include /etc/firejail/disable-devel.inc
    include /etc/firejail/disable-passwdmgr.inc

    caps.drop all
    netfilter
    nonewprivs
    noroot
    protocol unix,inet,inet6,netlink
    seccomp

With the above configuration I am unable to use controllers in Owlboy (as well as detect them in other games). How can I go about debugging which option is blacklisting the controllers?

     » firejail --noprofile gog-owlboy
    Parent pid 3820, child pid 3821
    Child process initialized
    Firejail detected; attempting to enforce a sandbox...
    No Firejail profile detected!
    Skipping Firejail sandbox...
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    Running
    Controller 0: PS4 Controller
    Controller 1: XInput Controller
    IGLDevice: OpenGLDevice
    OpenGL Device: Gallium 0.4 on AMD POLARIS10 (DRM 3.8.0 / 4.9.6-1-ARCH, LLVM 3.9.1)
    OpenGL Driver: 3.0 Mesa 13.0.3
    OpenGL Vendor: X.Org
    MojoShader Profile: glsl120
    EXT_swap_control_tear unsupported. Fall back to standard VSync.
    EXT_swap_control_tear unsupported. Fall back to standard VSync.

    Parent is shutting down, bye...

I am able to use the controllers when <code>--noprofile</code> is passed.

**Comment by netblue30** [comment]
This is very strange:
`````
firejail --noprofile gog-owlboy
Parent pid 3820, child pid 3821
Child process initialized <<<<<<<<<<<< the sandbox is up and running
Firejail detected; attempting to enforce a sandbox... <<< the game tries to start another firejail sandbox!!!
No Firejail profile detected!
Skipping Firejail sandbox...
cat: gameinfo: No such file or directory
`````
It behaves as if a firejail sandbox is already embedded into the game!

What happens if you start the game without firejail? Start the game without firejail and in a different terminal run "firejail --tree". This will list all the sandboxes running with all the sandboxed processes, maybe the game is already sandboxed. What distro are you using?

**Comment by Krakn** [comment]
https://aur.archlinux.org/packages/gog-owlboy/

It's a wrapper script I created to make sure if there was no $APP.profile, that it would not be sandboxed.

Running without the wrapper:

     » /opt/gog-owlboy/start.sh
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    Running
    Controller 0: PS4 Controller
    Controller 1: XInput Controller
    IGLDevice: OpenGLDevice
    OpenGL Device: Gallium 0.4 on AMD POLARIS10 (DRM 3.8.0 / 4.9.6-1-ARCH, LLVM 3.9.1)
    OpenGL Driver: 3.0 Mesa 13.0.3
    OpenGL Vendor: X.Org
    MojoShader Profile: glsl120
    EXT_swap_control_tear unsupported. Fall back to standard VSync.
    EXT_swap_control_tear unsupported. Fall back to standard VSync.

With firejail:

     » firejail /opt/gog-owlboy/start.sh
    Reading profile /etc/firejail/default.profile
    Reading profile /etc/firejail/disable-common.inc
    Reading profile /etc/firejail/disable-programs.inc
    Reading profile /etc/firejail/disable-passwdmgr.inc
    Warning: user namespaces not available in the current kernel.

    ** Note: you can use --noprofile to disable default.profile **

    Parent pid 4931, child pid 4932
    Warning: /sbin directory link was not blacklisted
    Warning: /usr/sbin directory link was not blacklisted
    Child process initialized
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    Running
    IGLDevice: OpenGLDevice
    OpenGL Device: Gallium 0.4 on AMD POLARIS10 (DRM 3.8.0 / 4.9.6-1-ARCH, LLVM 3.9.1)
    OpenGL Driver: 3.0 Mesa 13.0.3
    OpenGL Vendor: X.Org
    MojoShader Profile: glsl120
    EXT_swap_control_tear unsupported. Fall back to standard VSync.
    EXT_swap_control_tear unsupported. Fall back to standard VSync.

    Parent is shutting down, bye...

Firejail with <code>--noprofile</code> passed:

     » firejail --noprofile /opt/gog-owlboy/start.sh
    Parent pid 4980, child pid 4981
    Child process initialized
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    cat: gameinfo: No such file or directory
    Running
    Controller 0: PS4 Controller
    Controller 1: XInput Controller
    IGLDevice: OpenGLDevice
    OpenGL Device: Gallium 0.4 on AMD POLARIS10 (DRM 3.8.0 / 4.9.6-1-ARCH, LLVM 3.9.1)
    OpenGL Driver: 3.0 Mesa 13.0.3
    OpenGL Vendor: X.Org
    MojoShader Profile: glsl120
    EXT_swap_control_tear unsupported. Fall back to standard VSync.
    EXT_swap_control_tear unsupported. Fall back to standard VSync.

    Parent is shutting down, bye...

Sorry for the confusion!

**Comment by Krakn** [comment]
Was a commit pushed that might fix this?

**Comment by Krakn** [comment]
Tested last night, and the issue still persists.

**Note:** If using a kernel greater than Linux 4.9 (LTS), DS4 controllers will not be detected by the game, even without Firejail.

**Comment by netblue30** [comment]
I'll close it, it is something to do with  the support in the kernel.
