### ISSUE TITLE
firejail X window ID should be unique

### ISSUE THREAD

**Issue by GSI** [netblue30/firejail#1084]
All new firejails have the same X window ID. (Confirmed with firefox, chrome, uzbl.)

Optionally, or by default, firejails should get unique ID's.

(see also https://github.com/uzbl/uzbl/issues/335#issuecomment-275189985)

**Comment by netblue30** [comment]
You are probably right. What tool are you using to extract the ID?

**Comment by GSI** [comment]
I just run `xprop` in a terminal and click the according window.

To get the ID only: `xprop | grep '_NET_WM_PID' | awk '{ print $NF }'`

**Comment by netblue30** [comment]
Thanks, I'll look into it.

**Comment by smitsohu** [comment]
Thanks @GSI, I close this issue, let's keep track in the referenced issue instead
