### ISSUE TITLE
option to expose only whitelisted ip:port:protocol into the sandbox

### ISSUE THREAD

**Issue by ibukanov** [netblue30/firejail#1085]
To restrict the sandbox networking it is nice to allow for the sandbox to reach only single ip:port:protocol outside the sandbox. My use case is to expose http proxy running on my laptop into the sandbox so the only connection to the outside world is through this proxy.

Currently it is possible with --netns and custom iptable rules, but that requires root.

**Comment by netblue30** [comment]
I would try a setup similar to this one: https://firejail.wordpress.com/documentation-2/basic-usage/#routed

1. Create a bridge and set an IP address:
`````
$ sudo brctl addbr br0
$ sudo ifconfig br0 10.10.20.1/24
`````

2. Make sure the bridge traffic is not routed on the network outside:
`````
$ sudo echo "0" > /proc/sys/net/ipv4/ip_forward
`````

3. Start a http proxy on 10.10.20.1

4. You also need a DNS proxy on 10.10.20.1. If you are running on Ubuntu, you already have one - it is probably listening only on 127.0.0.1, so you'll have to reconfigure it.

5. Start the sandbox:
`````
$ firejail --net=br0 firefox
`````
