### ISSUE TITLE
Default ssh profile prevents ProxyJump

### ISSUE THREAD

**Issue by gab50000** [netblue30/firejail#1086]
With the default ssh profile enabled, the following command fails:

```bash
ssh -J host1 host2
```

the error messages are

```
Redirecting symlink to /usr/bin/ssh
Warning: cannot switch euid to root
Warning: cannot switch egid to root
Warning: cannot switch euid to root
Warning: cannot switch egid to root
Warning: an existing sandbox was detected. /usr/bin/ssh will run without any additional sandboxing features
```

**Comment by gab50000** [comment]
I should mention that this behavior only occurs after creating symlinks with firecfg.

I just realized if I type
``
firecfg --profile=/etc/firejail/ssh.profile
``

and then

``
ssh -J host1 host2
``

everything works just fine.

Operating system is Debian Testing (firejail version 0.9.44.8).

**Comment by netblue30** [comment]
Cool! I'll close it for now.

**Comment by altaurog** [comment]
That doesn’t work for me:
```
$ firecfg --profile=/etc/firejail/ssh.profile
Error: invalid command line option
firecfg - version 0.9.44.8
...
```

**Comment by Fred-Barclay** [comment]
@altaurog I believe it's a typo. 😄 Probably what was meant was
`firejail--profile=/etc/firejail/ssh.profile`
