### ISSUE TITLE
Sandboxed daemon cannot mmap to kernel

### ISSUE THREAD

**Issue by xplodwild** [netblue30/firejail#1088]
Hi,

I'm currently trying to sandbox a daemon which mmap a shared library (.so) to kernel memory to save memory in case multiple instances are running. However, when running through firejail, the mmap2 call fails.

strace log when running `firejail --noprofile strace ./bin` as a normal user:

```
open("/var/opt/.../libderp32-linux.so", O_RDONLY|O_CLOEXEC) = 5
read(5, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\3\0\1\0\0\0P\370\3\0004\0\0\0"..., 512) = 512
fstat64(5, {st_mode=S_IFREG|0777, st_size=4647528, ...}) = 0
mmap2(NULL, 4642720, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 5, 0) = -1 EPERM (Operation not permitted)
close(5)  
```

However, when running `sudo firejail --noprofile strace ./bin`, the binary runs fine and the library is mmap'd properly. Similarly, running `./bin` without firejail works fine too.

Am I missing something or is it a firejail bug?
Thanks!

**Comment by netblue30** [comment]
Does it work as "sudo firejail --noprofile ./bin" ?

**Comment by netlor** [comment]
Yes, as mentionned in my issue, it work when ran as `sudo firejail --noprofile ./bin`, `./bin` but not `firejail --noprofile ./bin`

**Comment by xplodwild** [comment]
Yes, as mentionned in my issue, it works with `sudo firejail --noprofile ./bin`, `sudo ./bin`, `./bin`, but not `firejail --noprofile ./bin`

**Comment by chiraag-nataraj** [comment]
@xplodwild Is this still an issue?

**Comment by chiraag-nataraj** [comment]
Going to close for inactivity. @xplodwild, please feel free to re-open if this is still an issue.
