### ISSUE TITLE
A question about noroot and seccomp with >3.5 kernels

### ISSUE THREAD

**Issue by acrobat1** [netblue30/firejail#1091]
I've realized  that the noroot option, according to the man page 
>requires a Linux kernel version 3.8 or newer

and also that the seccomp option , according to [this article](http://www.linux-magazine.com/Issues/2015/173/Firejail) only works with kernel versions above 3.5
>If you specify the additional --seccomp option, Firejail prevents programs in the sandbox from performing a couple of security-critical actions. Among other things, they are not allowed to load kernel modules, manage swap memory, run programs with root privileges (SUID), or restart the system. If an application tries to call one of these system functions, the kernel immediately terminates it. This totally useful safety net is only available as of the Linux kernel version 3.5, however.

Does this mean that with older kernels, such as found in Debian Stable (currently running a 3.16 kernel) , the **noroot** and **seccomp** options found in almost any profiles are in fact ignored - and therefore Firejail is running in a less effective way?

If so, should we consider installing a newer kernel from backports (4.8 is available) to really take advantage of using Firejail?

**Comment by netblue30** [comment]
If you have the 3.16 kernel from wheezy backports, both seccomp and noroot will work. They don't work on the default 3.2 kernel, where they are ignored. The only option that doesn't work on 3.16 kernel is overlayfs - it came in 3.18.

From a security perspective, the most critical feature is seccomp. You want to stay with a kernel 3.5 or newer.

**Comment by reinerh** [comment]
@acrobat1 3.16 is newer than 3.5. :)

**Comment by acrobat1** [comment]
It is... sorry for that...

And @netblue thanks anyways for the explanation.

**Comment by netblue30** [comment]
No problem.
