### ISSUE TITLE
Question: firejail + proxychains/torsocks

### ISSUE THREAD

**Issue by nyancat18** [netblue30/firejail#1093]
how can i use firejail  + proxychains? 

https://github.com/haad/proxychains

example
firejail proxychains firefox

**Comment by netblue30** [comment]
> firejail proxychains firefox

It should work, give it a try.

**Comment by Anyon3** [comment]
Torsocks and Proxychains are 2 differents thing.

If you want a firejail sandbox using tor, add the following argument 

--env=LD_PRELOAD=/usr/lib64/torsocks/libtorsocks.so

**Comment by chiraag-nataraj** [comment]
@nyancat18 Looks like this question was answered, so I'm going to close this. One caveat to keep in mind is that just doing `firejail proxychains firefox` would load the _proxychains_ profile, not the firefox on. You can use `firejail --profile=/path/to/firefox.profile proxychains firefox` to load the proper profile.
