### ISSUE TITLE
[Feature request] Provide easier way to install without root.

### ISSUE THREAD

**Issue by kkimdev** [netblue30/firejail#1094]
Sometimes, user doesn't have a root access so cannot install firejail at system level, but still wants to execute  untrusted software safely.  So I think it's good to provide easier way to install firejail, ideally without root permission and custom compilation.

**Comment by reinerh** [comment]
As user you can't install setuid-root binaries. This means several firejail features would not be working.
Also firejail expects some files in a system wide library directory.
