### ISSUE TITLE
Firefox extension accessing non-whitelisted folder

### ISSUE THREAD

**Issue by mustaqimM** [netblue30/firejail#1095]
I manually added my KeePass folder in KeeFox, ie. ~/.KeePass, and it's able to access it even though Firefox is using the default firejail profile. Is this normal for extensions to be granted unrestricted access?

**Comment by chiraag-nataraj** [comment]
The default profile whitelists ~/.keepassx (at least in the version I have). Or did you actually mean ~/.KeePass? I will try installing the addon to see what happens.

**Comment by mustaqimM** [comment]
@chiraag-nataraj I downloaded the portable version and moved the contents to my own folder: `~/.KeePass`. I didn't whitelist it

**Comment by netblue30** [comment]
This could be a possible problem: https://firejail.wordpress.com/support/frequently-asked-questions/#firefox

The first firefox instance takes over any subsequent instances. You need to make sure you are not already running firefox when you start the sandbox.

**Comment by mustaqimM** [comment]
@netblue30 I only launch a single instance with firejail, firejail is indeed running since I am able to only access the `~/Downloads` folder among [others](https://i.imgur.com/5CHbRmD.png). I cant choose the `~/.KeePass folder from the open dialog in the KeeFox extension but if I manually add [it:](https://i.imgur.com/6bB1eeg.png), then I am able to use it with KeeFox

**Comment by netblue30** [comment]
What distro are you using? Also, give me some links to Firefox addon and keepass portable you have installed, I'll give it a try.

**Comment by mustaqimM** [comment]
@netblue30 I'm currently on Antergos. The addon is [here (1.4.1)](https://addons.mozilla.org/firefox/downloads/latest/keefox/platform:2/addon-306880-latest.xpi?src=search) and the portable KeePass is [here (2.35)](https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.35/KeePass-2.35.zip/download?nowrap)

**Comment by SYN-cook** [comment]
The reason is that Keepass and KeeFox communicate with each other as server and client. Or in other words: KeeFox uses Keepass to access the password store. You should be able to disallow this by launching Firefox with --net=interface. So there is no sandbox escape here.
