### ISSUE TITLE
Firefox 51.0 segfaults with --private-dev option

### ISSUE THREAD

**Issue by acrobat1** [netblue30/firejail#1096]
Firefox 51.0 segfaults when is launched and when it's closed if using the **--private-dev** option 

`firefox[4203]: segfault at 0 ip 00007f5281ee721a sp 00007ffc6a3e1670 error 6 in libxul.so`

To be precise, it does not crash but it throws this error multiple times (using --tracelog) when it starts and when it exits - which I've never seen up to this 51.0 version (64bit).

I've tested with **--noprofile** and it seems consistent in Firejail  0.9.44.8.

**Comment by netblue30** [comment]
I have it running fine here (regular AMD driver from Debian stable). Maybe is because of --tracelog? Build a custom profile like this:
`````
$ mkdir -p ~/.config/firejail
$ echo "ignore private-dev" > ~/.config/firejail/firefox.profile
$ echo "include /etc/firejail/firefox.profile" >> ~/.config/firejail/firefox.profile
`````
I'll keep an eye on it if anybody is seeing the problem, in the worst case we remove private-dev from the profile.

**Comment by acrobat1** [comment]
Hi, sorry for my late reply : in the meantime I've tried with a "vanilla" Firefox 51 installation (=no modifications whatsoever) and this very short command line **firejail   --noprofile --private-dev** and it segfaults , remove the **private-dev** argument and it doesn't.

I too was thinking about --tracelog, but as far as I can see it really is triggered by --private-dev, and it only started with Firefox 51 - I've never seen it before.

Would that test above be comparable to what you were suggesting ?

Do you have any ideas about to why Firefox would do this from version 51.0 but not before ?

BTW, I too am on Debian stable with no weird drivers or custom kernels.

**Comment by acrobat1** [comment]
It just occurred to me that in firejail.config I've set **chroot-desktop no** : could this be the reason of this issue?

**Comment by netblue30** [comment]
That chroot-desktop should make a difference only if you are using --chroot on the command line.

**Comment by acrobat1** [comment]
Well, I'm not using --chroot on the command line .. so , until someone can figure this out, the only thing for me left to do is to run firefox without **--private-dev** option.

BTW, what we exactly lose by dropping **--private-dev** ? Is that a major drawback security-wise ?

**Comment by netblue30** [comment]
Not too much, it is a secondary feature.
