### ISSUE TITLE
Cannot whitelist symlinks that point outside home directory

### ISSUE THREAD

**Issue by lheckemann** [netblue30/firejail#1098]
I'm on NixOS, and I want to whitelist `~/.nix-profile` (symlink to `/nix/var/nix/profiles/per-user/linus/profile`) for read-only access (so the symlink cannot be modified from inside the jail). However, this no longer works in firejail 0.9.44.4; it worked in the previous version I had installed, which I believe was 0.9.44.2.

**Comment by netblue30** [comment]
The directory your link points to, needs to be owned by the regular user starting the sandbox. If it is owned by root, it will refuse to build the link and print a "Error: invalid whitelist path ..." message. You can still make the directory read-only (chmod 511 directory).

**Comment by lheckemann** [comment]
Is it not possible to make the symlink itself visible inside the sandbox? I want it available even though the (final) target is owned by root (and should remain so).

**Comment by netblue30** [comment]
OK, I put a fix on mainline git. Grab the new version, open /etc/firejail/firejail.config and add "follow-symlink-as-user no".

**Comment by lheckemann** [comment]
Awesome, thanks! I'll try it out later.

**Comment by tilpner** [comment]
@netblue30 Could you please reopen this issue?

@lheckemann mentioned on IRC that he hasn't actually tried the fix yet, and it doesn't seem to fix the problem for me

I added `follow-symlink-as-user no` into `/etc/firejail/firejail.config` and `~/.config/firejail/firejail.config`, but firejail still errors with `Error: invalid whitelist path` for anything that links to `/nix/store/*`.

There's no indication firejail even reads those files, possibly because they're both symlinks again. Putting invalid lines into both of them ("foobar") doesn't cause invocations with `--debug` to print anything related.

```shell
» ls -l /etc/firejail/firejail.config
lrwxrwxrwx 1 root root 36 Mar  6 15:13 /etc/firejail/firejail.config -> /etc/static/firejail/firejail.config
» ls -l .config/firejail
lrwxrwxrwx 1 till users 61 Mar  6 16:12 .config/firejail -> /nix/var/nix/profiles/per-user/till/nix-home/.config/firejail
» ls -l .config/firejail/firejail.config
-r--r--r-- 1 root root 3095 Jan  1  1970 .config/firejail/firejail.config
```

Would this cause firejail to not read the config? Unfortunately strace-ing firejail triggers sandbox detection...

**Comment by netblue30** [comment]
I'll try it out.

**Comment by vtpoet** [comment]
Also had this problem. (All my home folders are symlnked to a separate partition.)  Added your PPA and updated. Works now. Thanks!

**Comment by tex** [comment]
@vtpoet what is PPA?
I have the same problem, how to fix it?

**Comment by vtpoet** [comment]
Hi Tex,

You can use the PPA if you're using an Ubuntu-based system. The PPA is here:

https://launchpad.net/~deki/+archive/ubuntu/firejail

If you're using Debian, you can also use the app at the PPA but it's a bit more complicated. For information on what a PPA is, try this:

https://askubuntu.com/questions/4983/what-are-ppas-and-how-do-i-use-them

**Comment by tex** [comment]
Thank you. Unfortunately I'm running NixOs right now.

**Comment by vtpoet** [comment]
Yeah, that's the downside to these niche linux distros. 

If you're really determined, you still might be able to compile the PPA's version on NixOS by using the source code. I've done it myself and it's not hard (once you know how). It's installing all the dependencies and finding a reliable and well-constructed guide that's time consuming.

**Comment by lheckemann** [comment]
Try

```
git clone https://github.com/netblue30/firejail
nix-build -E "with import <nixpkgs> {}; firejail.overrideAttrs (orig: {src = ./firejail;})"
```

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vtpoet** [comment]
Can you reopen this? I bumped into this issue again when I moved my .cache directory to a larger partition. Long story short: My system partition is relatively small so I opt to symbolically link my home folders, including .cache, to a larger partition. (My .cache directory can get to be several gigabytes in size.) Starting up firejail, I get the invalid whitelist error:

```
Error: invalid whitelist path /home/vtpoet/.cache/mozilla/firefox
Error: proc 28004 cannot sync with peer: unexpected EOF
```

**Comment by vtpoet** [comment]
Nevermind. Fixed. Turns out it was a permission problem. When I used root to move the .cache folder, the permissions, naturally enough, were assigned to root. Nothing Chown couldn't fix.
