### ISSUE TITLE
--overlay not working for me on Arch Linux

### ISSUE THREAD

**Issue by tbu-** [netblue30/firejail#11]
Starting with `--overlay`:
```
$ firejail --overlay 
Parent pid 32340, child pid 32341
Warning: /var/lock not mounted
Error mounting /var/tmp:fs_var_tmp(302): No such file or directory
Error: cannot establish communication with the parent, exiting...
```

```
$ uname -r
4.1.4-1-ARCH
```

**Comment by netblue30** [comment]
Can you please run "firejail --debug --overlay" and print the output here? Thanks!

**Comment by tbu-** [comment]
I get:
```
$ firejail --debug --overlay
Command name #bash#
Using the local network stack
Parent pid 24836, child pid 24838
Initializing child process
PID namespace installed
Linux kernel version 4.1
Mounting tmpfs on /tmp/firejail/mnt directory
Mounting OverlayFS
Mounting /dev
Warning: /var/lock not mounted
Mounting tmpfs on /var/tmp
Error mounting /var/tmp:fs_var_tmp(302): No such file or directory
Error: cannot establish communication with the parent, exiting...
```

**Comment by netblue30** [comment]
I'll have to install Arch here and take a look. Thanks for the bug!

**Comment by netblue30** [comment]
I've modified something in the code, it might fix the problem. Give it a try! Thanks.

**Comment by tbu-** [comment]
It partially works. It somehow doesn't mount my home directory though...
```
$ firejail --overlay
Parent pid 31836, child pid 31837
Warning: /var/lock not mounted
Warning: /var/tmp not mounted
Warning: cannot mount tmpfs in top of /var/log
Warning: cannot find /var/run/utmp
Warning: failed to unmount /sys
Child process initialized
$ ls ~
ls: cannot access /home/user: No such file or directory
```

**Comment by netblue30** [comment]
It looks like I still have to install Arch. It will take a couple of days.

**Comment by iiotx** [comment]
I'm using Parabola (Arch derivative) and I'm able to recreate this issue.  I can also confirm that I do not have the same issue with either Ubuntu 14.04 or 15.04.

I've created a stub of firejail's functions, basically only mounting the overlay and chroot.  I cannot see anything in /home even in this stripped version.
http://pastebin.com/frDpxiNZ

% ls -la /home
total 48
drwxr-xr-x  7 root     root      4096 Aug 22 21:25 .
drwxr-xr-x 17 root     root      4096 Aug 20 21:55 ..
drwxr-xr-x  3 root     root      4096 Aug 13 05:13 .ecryptfs
drwx------  2 root     root     16384 Mar 20 22:50 lost+found
drwx------ 43 username username 12288 Aug 23 09:49 username
drwx------ 36 username username  4096 Aug 13 05:11 username.8vIxxhr6
drwx------  2 tester   tester    4096 Aug 22 21:27 tester
% fj-stub
% ls -la /home
total 8
drwxr-xr-x 2 root root 4096 Feb 13  2015 .
drwxr-xr-x 1 root root 4096 Aug 23 06:54 ..
% exit
% sudo fj-stub
% ls -la /home
total 8
drwxr-xr-x 2 root root 4096 Feb 13  2015 .
drwxr-xr-x 1 root root 4096 Aug 23 06:54 ..

There seems to be some fundamental difference on how overlayfs/chroot is working on either 1) Arch or 2) the newest kernel version.

**Comment by netblue30** [comment]
Fixed, thank you for all your input.
