### ISSUE TITLE
Error: cannot access AppImage file

### ISSUE THREAD

**Issue by Gridlocked** [netblue30/firejail#1102]
firejail --appimage Ungoogled_Chromium_Web_Browser-55.0.2883.87.glibc2.15-x86_64.AppImage
Error: cannot access AppImage file

I could be doing something wrong here but based on the documentation.......... when I run that in the termninal it just says there's no access. I can run the appimage on it's own without issue.  I've tried this on two different OS - Mint and Fedora.

**Comment by netblue30** [comment]
Give me a download link to chromium appimage. It could be an appimge type 2 (introduced recently), and there is no support for this type in firejail version you are using. Also, run a "firejail --version".

**Comment by Gridlocked** [comment]
That makes sense this appimage was created only yesterday.   It's firejail version 0.9.44.8

What do I need,  0.9.45 ?

**Comment by netblue30** [comment]
Yes, grab the version from git - it is quite easy, all you need to install is git and the compiler:
`````
$ sudo apt-get install git build-essential
`````
then you compile and install it:
`````
$ git clone https://github.com/netblue30/firejail.git
$ cd firejail
$ ./configure && make && sudo make install-strip
`````

**Comment by Gridlocked** [comment]
No luck with 0.9.45 I may be doing something wrong at my end with the appimage.  How does firejail know the location?

This is the appimage

https://www.dropbox.com/s/ea4shiojgrs5q4v/Chromium-20170214T173634Z.zip?dl=0

**Comment by Gridlocked** [comment]
I just reinstalled the appimage and saw some errors I didn't notice before - is this the issue?  

/tmp/.mount_H09OH4/usr/bin/chromium: line 61: lsb_release: command not found
/tmp/.mount_H09OH4/usr/bin/chromium: line 61: lsb_release: command not found
/tmp/.mount_H09OH4/usr/bin/chromium: line 61: lsb_release: command not found

**Comment by Gridlocked** [comment]
You can see the same result with avidemux which is available as an appimage. While there is no firejail profile for that - it doesn't come back that you need to run it as 'no profile' but instead 'can't access appimage'.

Download Avidemux Linux Universal Binary - 38.00 MB | version: 2.6.18 

https://www.fosshub.com/Avidemux.html

**Comment by Gridlocked** [comment]
I just tried with the Wire messaging appimage available here - https://wire.com/en/download/

Also no go.

**Comment by Gridlocked** [comment]
Is the problem is with firejail or appimage?

**Comment by netblue30** [comment]
Somehow my last message on github got lost! I've tried avidmux from your link. Downloaded the file, and started it with the following command:
`````
$ firejail --appimage avidemux_2.6.15.appImage 
`````
Are you forgetting to add --appimage?

**Comment by netblue30** [comment]
Found my lost message, it went on a different thread!

You are doing something wrong there. I downloaded avidemux appimage you linked to, and run it directly:

$ cd Downloads
$ ls avi*
avidemux_2.6.15.appImage
$ firejail --appimage avidemux_2.6.15.appImage 
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-common.local
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 8475, child pid 8478
Dropping all Linux capabilities and enforcing default seccomp filter
Child process initialized
Directory /home/netblue/.avidemux6/ exists.Good.
Using /home/netblue/.avidemux6/ as base directory for prefs, jobs, etc.
 [isPortableMode] 13:33:40-650  Portable mode
  [ADM_initBaseDir] 13:33:40-650  Portable mode
  [ADM_initBaseDir] 13:33:40-650  Relative to install plugin mode : </run/firejail/appimage/.appimage-8475/usr/lib/ADM_plugins6/>
 *************************
  Avidemux v2.6.15 (0) .
*************************
...

It works just fine. Probably you forgot to put --appimage on firejail command line? Run appimages as they come, just extract them from the zip file if they are a zip file.

**Comment by Gridlocked** [comment]
Yes, user error. Thanks!

**Comment by netblue30** [comment]
No problem!
