### ISSUE TITLE
Arbitrary command line arguments in profile files?

### ISSUE THREAD

**Issue by bunsim** [netblue30/firejail#1105]
It seems like there are certain command-line arguments that cannot be configured in profile files, like `x11=xorg`. Is it possible to specify them in profile files instead of remembering to add the command-line argument every time the command is run? This is especially useful when you symlink firejail into /usr/local/bin to "magically" jail certain commands.

**Comment by netblue30** [comment]
Most commands are already supported in profile files. For example "x11 xorg":
`````
$ man firejail-profile
[...]
      x11    Enable X11 sandboxing.

       x11 none
              Blacklist /tmp/.X11-unix directory, ${HOME}/.Xauthority and file
              specified in ${XAUTHORITY} environment variable.  Remove DISPLAY
              and  XAUTHORITY  environment variables.  Stop with error message
              if X11 abstract socket will be accessible in jail.

       x11 xephyr
              Enable X11 sandboxing with xephyr.

       x11 xorg
              Enable X11 sandboxing with X11 security extension.

       x11 xpra
              Enable X11 sandboxing with xpra.
[...]
`````
If you find a command that is not supported, it is very easy to add it, so just let me know.

**Comment by bunsim** [comment]
Ah, I must have missed it then.

**Comment by netblue30** [comment]
No problem. The idea is to have all --options supported in profiles, if you find one missing let me know.
