### ISSUE TITLE
Temporary specific folders

### ISSUE THREAD

**Issue by throwaway217** [netblue30/firejail#1107]
Is there any way I can have temporary specific folders ? For example an application A needs 3 folders to run  .config/A .cache/A and .local/share/A. I want the last two to behave in a similar way to the home folder in the --private option. This can be done with a simple script I'm just wondering if I can do this with firejail by default.

There's --private-home=.config/A but I can't get it to work.

firejail version 0.9.44.8

Compile time support:
        - AppArmor support is disabled
        - AppImage support is enabled
        - bind support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

**Comment by netblue30** [comment]
I'll try to bring something in using --tmpfs for directories such as ~/.cache/A and ~/.local/share/A.

**Comment by netblue30** [comment]
All done on mainline git:
`````
$ firejail --tmpfs=~/.cache firefox --no-remote
`````

**Comment by throwaway217** [comment]
I've been using this ever since i saw the commit but I forgot about right after.
Thank you.

**Comment by netblue30** [comment]
No problem.
