### ISSUE TITLE
Protect shell startup files

### ISSUE THREAD

**Issue by dbakker** [netblue30/firejail#111]
Firejail currently blocks access to directories such as `~/.ssh` to protect your secrets.

One way an attacker could currently still get to them though is by adding a malicious command to one of the automatically executed files, such as `~/.profile` or `~/.bash_logout`. That command will then get executed *outside of firejail* when you reboot and login to your user account.

Perhaps it would be a good idea to make those kinds of files read only? My list so far:

    # General startup files
    read-only ${HOME}/.xinitrc
    read-only ${HOME}/.xserverrc
    read-only ${HOME}/.profile
    
    # Shell startup files
    read-only ${HOME}/.bash_login
    read-only ${HOME}/.bashrc
    read-only ${HOME}/.bash_profile
    read-only ${HOME}/.bash_logout
    read-only ${HOME}/.zshrc
    read-only ${HOME}/.zlogin
    read-only ${HOME}/.zprofile
    read-only ${HOME}/.zlogout
    read-only ${HOME}/.zsh_files
    read-only ${HOME}/.tcshrc
    read-only ${HOME}/.cshrc
    read-only ${HOME}/.csh_files
    
    # Initialization files that allow arbitrary command execution
    read-only ${HOME}/.mailcap
    read-only ${HOME}/.exrc
    read-only ${HOME}/.vimrc
    read-only ${HOME}/.vim
    read-only ${HOME}/.emacs
    read-only ${HOME}/.tmux.conf
    read-only ${HOME}/.iscreenrc
    read-only ${HOME}/.muttrc
    read-only ${HOME}/.xmonad

    # The user ~/bin directory can override commands such as ls
    read-only ${HOME}/bin

Unfortunately, It's not fullproof. For example, some arbitrary files may be getting sourced from `~/.bashrc` that an attacker can edit. Or an attacker may hide code in a `.git/hooks` file or some other more uncommon initialization file or script.

Another point is that some users may *want* to be able to edit those files within the jail. For that we could considering making it optional and read-only or blacklist these files for known programs (such as firefox and so on).

I'm just throwing this up there because there didn't seem to be any discussion about it so far and it seems like an issue that should be addressed.

**Comment by netblue30** [comment]
Thank you for the patch - merged into etc/disable-common.inc
