### ISSUE TITLE
Question: How can i fix this profile?

### ISSUE THREAD

**Issue by triceratops1** [netblue30/firejail#1112]
with https://github.com/chiraag-nataraj/firejail-profiles/raw/master/kdenlive.profile

i get this log
https://gist.github.com/triceratops1/f34c1b68e535b2c35484810a38a14a70

**Comment by triceratops1** [comment]
firejail version 0.9.44.8

Compile time support:
	- AppArmor support is disabled
	- AppImage support is enabled
	- bind support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

**Comment by netblue30** [comment]
In the log you have:

> mprotect failed in ExecutableAllocator::makeExecutable: Permiso denegado

Grsecurity is killing the executable. I think the application is intentionally doing dynamic machine code generation and just needs an exception. This happens in some programs, usually browsers or Python programs. You would need to disable mprotect feature for your program executable, something like this:
`````
$ sudo paxctl -c /usr/lib/iceweasel/iceweasel
$ sudo paxctl -m /usr/lib/iceweasel/iceweasel
`````
Replace iceweasel above with the full path for your executable.

**Comment by triceratops1** [comment]
@netblue30 i use linux-lts (archlinux)  :)  
no grsec

**Comment by netblue30** [comment]
You are right, it is something different. I was going with this: https://pax.grsecurity.net/docs/mprotect.txt

Try to run the program without a profile:
`````
$ firejail --noprofile application-name
`````
If this is working, we can definitely fix it.

**Comment by liloman** [comment]
> You are right, it is something different. I was going with this: https://pax.grsecurity.net/docs/mprotect.txt

I remember clearing reading this amazing staff long time ago I had even printed it! :dancing_men:  /mprotect() 4 life!

http://phrack.org/issues/60/6.html

Good ol'd times and amazing job indeed ! :)

Sorry for the spam! :cry:

**Comment by netblue30** [comment]
No problem.

**Comment by triceratops1** [comment]
@netblue30 it works (firejail --noprofile --net=none kdenlive)
