### ISSUE TITLE
Warnings still displayed despite of --quiet

### ISSUE THREAD

**Issue by Dupond** [netblue30/firejail#1114]
Hello,

Under Arch (with Firejail version 0.9.44.8), warnings about /sbin et /usr/sbin not being blacklisted are still displayed, even when using the --quiet option...

Thanx for your help !
Best regards,
Dupond

**Comment by netblue30** [comment]
I put a fix on 0.9.44-bugfix branch here: https://github.com/netblue30/firejail/tree/0.9.44-bugfixes

On mainline was already fixed. Thanks.
