### ISSUE TITLE
better self-explaining options (than --private)

### ISSUE THREAD

**Issue by testbird** [netblue30/firejail#1115]
firejail could make the meaning of its options much more clearer by providing a more self-explaining alternative. (e.g. the meaning of the --private options seems not very clear to me all the time.)

What would you think about a scheme along these lines:
--private could have more clearly named alternatives like this:

--persistent-home=/home/$USER (the default, make permanent changes to the settings)
--discardable-home=/home/$USER (starting with some existing settings)
--discardable-home (defaults to =$HOME)
--discardable-home=/home/$USER --home-whitelist=.directory,file,etc, (adding restrictions)
--discardable-home=empty (the legacy --private, resulting in starting with the programs default settings)

NB: Currently there seems to be an inconsistency:
--private provides a *discardable* version of an empty home, but
--private=own_subdir uses ~/own_subdir as *persistent* storage.

**Comment by netblue30** [comment]
You are right, it is not consistent in this moment. It just evolved this way over time, and is kindo of difficult to change it now. I'll look into it.

**Comment by testbird** [comment]
Ah, well, understanable! Good to know you keep the wording in mind.
Once it has matured you may add the new options as mutually exclusive to the old ones, and then use the new ones in explanations.

**Comment by netblue30** [comment]
Absolutely, it will go through a major cleanup before 1.0 release.
