### ISSUE TITLE
Keepass section in browser profiles

### ISSUE THREAD

**Issue by SYN-cook** [netblue30/firejail#1120]
I was playing around with KeePass and browser extensions (KeeFox, PassIFox and ChromeIPass) today, and I found that the following section was obsolete in the Firefox and Chrome profiles:

`# lastpass, keepass`
`# for keepass we additionally need to whitelist our .kdbx password database`
`whitelist ~/.keepass`
`whitelist ~/.config/keepass`
`whitelist ~/.config/KeePass`

Everything worked nicely without... Since Keepass configuration files are blacklisted via disable-passwdmgr.inc, and blacklisting was never disabled, it seems the code in this section was anyways always broken (already before #993). So do I miss something here, or is this section safe to remove? 

We should probably remove these lines if they are not absolutely necessary (I could prepare a pull request. And I would also introduce `noblacklist ~/.lastpass` into the browser profiles, so that LastPass is finally able to write local backups from Firefox).

**Comment by SYN-cook** [comment]
This seems to be related to #1095. My password database is 1) blacklisted and 2) not whitelisted for the browser, still I can use it with the extensions.

Apparently the extensions don't access the password database directly, but communicate with Keepass [via http](https://github.com/pfn/keepasshttp) or [via JSON-RPC](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Technical-%7C-KeePassRPC-detail).

**Comment by SYN-cook** [comment]
I have found only [one extension](https://chrome.google.com/webstore/detail/ckp-keepass-integration-f/lnfepbjehgokldcaljagbmchhnaaogpc) for Chrome that works differently, requires direct access to the password storage and has a notable userbase. 
If we unblacklist and whitelist $HOME/*.kdbx for browsers, it would be mostly for this extension.

**Comment by netblue30** [comment]
Send a pull request, I'll merge it.
