### ISSUE TITLE
Persistent sandboxes

### ISSUE THREAD

**Issue by xrisk** [netblue30/firejail#1121]
So I am trying to create a single persistent sandbox, which I will later `join` on. Is this possible at the moment? I read through the man page and it didn’t seem possible to me.

Something like:

`firejail &` does not work - it immediately quits. (I think it is because the bash process there receives EOF).

Is the solution then to use something like screen/tmux to keep it running?

Maybe you can add a feature for just creating a sandbox without creating any process inside it...

**Comment by netblue30** [comment]
> firejail & does not work - it immediately quits. (I think it is because the bash process there receives EOF)

I'll try to bring something in!

**Comment by chiraag-nataraj** [comment]
Couldn't you just use `firejail sleep inf`? You can use `--profile` to set the actual profile to load and `--name` to set the name.

**Comment by xrisk** [comment]
Thank you! This works just fine.
