### ISSUE TITLE
$HOME not set properly with --user option

### ISSUE THREAD

**Issue by xrisk** [netblue30/firejail#1122]
It appears that whenever I use `--user` option `$HOME` is always set to /root. Is this the correct behaviour? Even if I specify the home directory to be used with `--private=` it is not respected.

**Comment by netblue30** [comment]
You are running a very old version, --user option was removed. Do a software update, there have been all kind of fixes since.

**Comment by xrisk** [comment]
Oh… I just got it from Ubuntu 16.04 default sources.

**Comment by netblue30** [comment]
It's very old. Most of the software in Ubuntu is kept at the version it was when 16.04 was released, and is not getting any updates. Grab a .deb package from here: https://sourceforge.net/projects/firejail/files/firejail/ 

In a terminal run:
`````
$ sudo dpkg -i firejail_0.9.44.8_1_amd64.deb
`````

**Comment by xrisk** [comment]
Hmm. what was the reason for removing `--user` option. Is there something to replace it (I can't find it in manual) or do you recommend me to manually change user before calling firejail?

**Comment by netblue30** [comment]
You can use sudo -u to switch to the proper user:
`````
$ sudo -u username firejail appname
`````
It was like reimplementing sudo in firejail, so I had to take it out.

**Comment by xrisk** [comment]
Thank you for your help.

**Comment by netblue30** [comment]
You're welcome.
