### ISSUE TITLE
allow --net only for sandboxes started (or configured) by root

### ISSUE THREAD

**Issue by testbird** [netblue30/firejail#1123]
Hi netblue, separating this into a proper issue.

Using the SUID firejail, a regular user can access the network even if it is blocked for the host. Using --net is like connecting new boxes to the network.

May be it is possible to only allow to directly configure (non-local) --net configurations for root (and all users with preexisting permissions) and make all others depend on root owned profiles? (Kind of executing part of firejail setup code under NO_NEW_PRIVS, exept when reading a root owned profiles.)

**Comment by netblue30** [comment]
It is already implemented. In a text editor open /etc/firejail/firejail.config and enable restricted-network:
`````
# Enable or disable restricted network support, default disabled. If enabled,
# networking features should also be enabled (network yes).
# Restricted networking grants access to --interface, --net=ethXXX and
# --netfilter only to root user. Regular users are only allowed --net=none.
restricted-network yes
`````

**Comment by testbird** [comment]
I see now. Sorry I missed that.
I am not sure why of if you consider the current default as a secure, though.

**Comment by testbird** [comment]
I tried setting `restricted-network yes`.

However, this breaks sanboxes with network settings preconfigured in /etc/firejail/ (file owner root).

**Comment by netblue30** [comment]
I configured "restricted-network yes", it seems to be working fine on wide range of applications. What problem are you seeing?

**Comment by testbird** [comment]
For example, user root configures networking in /etc/firejail/firefox.profile

With ` restricted-network yes`, regular users can not use networking anymore (even with the configuration that root put into the sytem default .profile.

I think users should be allowed to use the setting from (root owned) profiles, while restricting users from (re)configuring sandboxes with arbitrary network configurations is ok, of course.

**Comment by testbird** [comment]
The idea to make this universally save, was to execute only the system profiles with full suid permissions, and the  comand line and user profiles in a limited (non-suid) user environment.
