### ISSUE TITLE
default-policy.conf to select whitelisting (isolated operation) or blacklisting (integated operation)

### ISSUE THREAD

**Issue by testbird** [netblue30/firejail#1125]
Currently, the default firejail session seems to be based on blacklisting, while some profiles configure whitelisting.

For example, executing firejail produces a shell that has access to $HOME, the network, and X input, which may not be a desired default behavior in all cases.

The .inc files inspired me to suggest a central `default-policy.conf` file.
Let that file get included by all default profiles (instead of directly including `disable-*.inc`), and thus allow to configure the default policy by (un)commenting the inclusion of rules. (The rules file then loads the appropriate `disable-*.inc` files.)

```
## /etc/firejail/default-policy.conf
## Configure the default policy by un-commenting the include line that is desired,
## and commenting out the non-desired include line:

## whitelisting (sandox allows only isolated operation, with additional rules that allow access)
include /etc/firejail/defaults/whitelisting-rules.inc

## blacklisting (sandox allows access to resources, with additional rules that deny access)
#include /etc/firejail/defaults/blacklisting-rules.inc
```

**Comment by netblue30** [comment]
> Currently, the default firejail session seems to be based on blacklisting, while some profiles configure whitelisting.

Yes, mostly browsers are whitelisted, everything else is blacklisted. I'll bring in a default-policy.conf or similar, thanks.

**Comment by chiraag-nataraj** [comment]
@netblue30 This isn't really done at this point. Is this something we actually want to do?

**Comment by SkewedZeppelin** [comment]
Most profiles that can be whitelisted already are

**Comment by Vincent43** [comment]
There is also `/etc/firejail/globals.local` for local administration used by all profiles.

**Comment by rusty-snake** [comment]
IMHO here is nothing to do, should we close?
