### ISSUE TITLE
--netfilter example not in effect

### ISSUE THREAD

**Issue by testbird** [netblue30/firejail#1126]
IIUC this should fail:

```
firejail --net=eth0 --netfilter=/etc/firejail/nolocal.net wget http://mylocal.server/index.html
```

But it succeeds and I found index.html was downloaded.

**Comment by netblue30** [comment]
What's the ip of your local server? I have in the filter something like this:
`````
-A OUTPUT -d 192.168.0.0/16 -j DROP
-A OUTPUT -d 10.0.0.0/8 -j DROP
-A OUTPUT -d 172.16.0.0/12 -j DROP
`````

**Comment by testbird** [comment]
Today I can not reproduce this anymore. Maybe it has only happended when there were stall firejail processes still running (#1128) ?

**Comment by netblue30** [comment]
No problem.
