### ISSUE TITLE
processes not terminated properly

### ISSUE THREAD

**Issue by testbird** [netblue30/firejail#1128]
Finally I found a command that runs firefox sucessfully as a different user within firejail using this command, and it should be easy to reproduce.

The firefox.profile is used through symlinking, and has this added at the beginning:
```
net eth0
x11
nosound
```
Then try
`gksu -l -u webuser -w firefox`

However, the command does not close properly and I have no idea left how to debug this.
```
...
2017-03-05 21:19:16,676 stopping pulseaudio with pid 7846
xpra at :903 has exited.
(EE) Server terminated successfully (0). Closing log file.

got signal SIGTERM, exiting
^C
~ $
```
I noticed the pulseaudio ran despite the option nosound.
And the error is that `Ctrl-C` is needed to get back to the command line.
And sometimes (very strange) killall xpra or firejail seems to catch a process after the Ctrl-C, but not always.

**Comment by netblue30** [comment]
I'll try to reproduce it, thanks.

**Comment by testbird** [comment]
> only sometimes (very strange) killall xpra or firejail seems to catch a process

This I found happens when supplying a filename as parameter like `firefox http://github.com` or `evince ~/my.pdf` 

Independent from this, the shell does not return to the prompt, and I notice `.:*-fakexinerama` files piling up in $HOME.

**Comment by SHOTbyGUN** [comment]
I am unable to cleanly kill firefox after it has crashed under firejail

firefox will eventually crash if
- running whole day
- multiple tabs using flash

Then firefox will become
- unresponsive
- does not respond to SIGTERM
- SIGKILL will create a zombie
- SIGKILL:ing whole tree including firejail, will leave PID:s in system, where is the reaper?
- New firefox instances will run sluggishly and are prone to crash sooner
- Computer cannot shutdown, only 3sec force power off button works.

As I am writing this, I find this firejail option which I will try this next time I have crashes, and then edit this post.

`--shutdown=name|PID
              Shutdown the sandbox identified by name or PID.

              Example:
              $ firejail --name=mygame --caps.drop=all warzone2100 &
              $ firejail --shutdown=mygame

              Example:
              $ firejail --list
              3272:netblue:firejail --private firefox
              $ firejail --shutdown=3272
`
