### ISSUE TITLE
Error: cannot access profile file

### ISSUE THREAD

**Issue by twoDarkMessiah** [netblue30/firejail#1131]
I got following error message, when i tried to load any profiles:

**firejail --profile=start-tor-browser.profile**
Reading profile start-tor-browser.profile
Error: cannot access profile file

firejail version 0.9.45
Compile time support:
        - AppArmor support is disabled
        - AppImage support is enabled
        - bind support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - networking support is enabled
        - git install support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

Kernel:
4.9.13-200.fc25.x86_64
SELinux: enabled

**Comment by netblue30** [comment]
Kind of strange. It finds the profile file, but it cannot access it! Maybe "Error: cannot access profile file" is printed by the browser? Add a --debug to the command (firejail --debug ...) and print it here, and also the profile file.

**Comment by twoDarkMessiah** [comment]
Hey netblue30,
i found the issue. In the profile there were some includes on files that doesn't exist anymore:
```
include /etc/firejail/disable-common.inc 
include /etc/firejail/disable-programs.inc 
include /etc/firejail/disable-passwdmgr.inc 
include /etc/firejail/disable-devel.inc
```
Reason was, that i changed from a rpmfusion packet to "fgit-install.sh". Had to copy the 'etc' dir from git clone. So my fault, but an error output at this point would be really useful. 

Anyway, thanks and keep up your amazing work.

**Comment by netblue30** [comment]
You're welcome!
