### ISSUE TITLE
Possibility to override `whitelist` defined in system-wide profile

### ISSUE THREAD

**Issue by msva** [netblue30/firejail#1135]
Hi!

I think, it will be nice to have option like `noblacklist` for `blacklist`, but having same effect on `whitelist` instead.

So, it will be possible to include system-wide profiles in custom one, but override some `whitelist` directives defined there (for example, `${DOWNLOADS}` or `${HOME}/Downloads`).

May be useful if user do not want to expose whole downloads dir to application, but wants to only whitelist "personal" subdir inside.

**Comment by netblue30** [comment]
I'll bring it in as "nowhitelist".

**Comment by netblue30** [comment]
You can try it out:
`````
       --nowhitelist=dirname_or_filename
              Disable whitelist for this directory or file.
`````
and a "nowhitelist" command for profile files.
