### ISSUE TITLE
Firefox-developer/aurora with Conkeror - chrome.css are blocked

### ISSUE THREAD

**Issue by emacsomancer** [netblue30/firejail#114]
An odd issue which I don't understand.

I run Conkeror ( http://conkeror.org ), a keyboard-centric browser based on xulrunner, and it can also be run with firefox (or pale moon etc.) in the same way.

And, if I run plain Firefox with the conkeror.profile (see recent pull request) which whitelists "~/.conkerorrc" (where user settings are stored) and "~/.conkeror.mozdev.org" (where things like history, chrome etc. are stored; the equivalent of "~/.mozilla") as so:

    exec firejail --profile=/etc/firejail/conkeror.profile firefox --app /usr/share/conkeror/application.ini "$@"

Conkeror works fine, including customised chrome .css stuff.

But if I try the same thing with the Developer version of Firefox (still called "firefox-aurora" in Arch):

    exec firejail --profile=/etc/firejail/conkeror.profile firefox-aurora --app /usr/share/conkeror/application.ini "$@"

Then I lose my chrome.css settings.

If I run Conkeror with firefox-aurora without firejail:

     firefox-aurora --app /usr/share/conkeror/application.ini "$@"

Then everything is fine. So there's something else which needs whitelisting for firefox-aurora, but I'm not sure what it is.  I tried adding "~/.mozilla" to the whitelist, but that didn't make any difference.

**Comment by netblue30** [comment]
I'll give it a try.

**Comment by netblue30** [comment]
Please retest on version 0.9.36. I'll reopen the bug if necessary. Thanks!
