### ISSUE TITLE
tmpfs on top of ~/.cache directory by default

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#1141]
Hi, recent commits https://github.com/netblue30/firejail/commit/e4ec2956367134a003eb9f1cf0f5e58a4c1f9cfc & https://github.com/netblue30/firejail/commit/912bbbeecd68e1931a034f527c33778521747f81implemented new behavior (mounting a tmpfs on top of ~/.cache by default). I already use anything-sync-daemon (https://aur.archlinux.org/packages/anything-sync-daemon/) to do just that. Having it twice breaks liferea's feed icons. Is there a firejail setting to NOT do this by default?

Regards.

**Comment by netblue30** [comment]
I added support to disable it. Open /etc/firejail/firejail.config and set "cache-tmpfs no".
