### ISSUE TITLE
Ability to use a proxy.

### ISSUE THREAD

**Issue by Isaac-bankier** [netblue30/firejail#1142]
Having an argument to be able to specify a proxy would be useful.

**Comment by netblue30** [comment]
What kind of proxy do you need? HTTP?

**Comment by Isaac-bankier** [comment]
HTTP and SOCKS support would be nice.

**Comment by reinerh** [comment]
Is it not sufficient to use the http_proxy environment variable?
`firejail --env=http_proxy=1.2.3.4 ...`

**Comment by Isaac-bankier** [comment]
Sorry I did not know about this option. This works fine. It's fairly easy to forward a SOCKS proxy into a HTTP proxy using privoxy so I'll just do that.

**Comment by netblue30** [comment]
Thanks @reinerh
