### ISSUE TITLE
Failure to firejail a custom AppImage

### ISSUE THREAD

**Issue by hThoreau** [netblue30/firejail#1143]
Good morning,

I'm a Debian Jessie user and, recently, I've tried modifying a Krita AppImage to add a file to it. I was successful in generating a fully functional modified version of it, but running it under firejail returns the following error:
```
thoreau@user:~/Installers$ firejail --appimage krita*
Error mounting appimage: appimage.c:104 appimage_set: Invalid argument
thoreau@user:~/Installers$ 
```
The complete process I've performed form the downloaded files to their final version, I'll describe bellow:

1. The AppImage, I downloaded from [here](http://download.kde.org/stable/krita/3.1.2/krita-3.1.2-x86_64.appimage) into my "Installers" folder, and the file I intended to add, I downloaded from [here](http://www.davidrevoy.com/data/documents/krita-scheme.tar.gz) and extracted the "KritaDarker.colors" file into my "Pictures" folder.

2. Having the [AppImageKit](https://github.com/probonopd/AppImageKit) in my home folder, I then performed the following commands:
```
sudo mount /home/thoreau/Installers/krita-3.1.2-x86_64.appimage /mnt
sudo cp -r /mnt/ krita-3.1.2-x86_64.appimage
cd ~/
sudo chown -R $USER krita-3.1.2-x86_64.appimage
mv /Pictures/KritaDarker.colors krita-3.1.2-x86_64.appimage/usr/share/color-schemes/KritaDarker.colors
./appimagetool-x86_64.AppImage krita-3.1.2-x86_64.appimage
These commands I adapted from the solution presented in this [thread](https://github.com/Ultimaker/Cura/issues/847#issuecomment-285860132) which is a case similar to mine which was presented to me in the appimage IRC.
```
3. Now with the [resulting appimage](https://www.dropbox.com/s/hzflkgsr4kjao6z/krita-3.1.2-x86_64.appimage?dl=0) in hands, I tried running it, saw it worked with the intended modifications, then substituted the original appimage in the Installers folder. And then I tried using it in combination with Firejail, resulting in the error shown above.

Now we are back to where we started. Thank you for listening to my case and any help given.

**Comment by netblue30** [comment]
It is possible AppImageKit switched the format of the archive from ISO to squashfs. Firejail version you have supports only ISO archives. Support for squashfs archives was introduced recently in firejail, and is available only here on mainline git. I would say if you install it, it should fix the problem.
