### ISSUE TITLE
Whitelist  symlinkeddir of origin 

### ISSUE THREAD

**Issue by liloman** [netblue30/firejail#1144]
Hi

```bash
mkdir ~/origin; touch ~/origin/{1..3}.txt
ln -s ~/origin ~/symlinkeddir
```

Then in firefox firejail profile:  
whitelist ~/symlinkeddir/2.txt

And what happens is that:
~/origin/1.txt is blacklisted
~/origin/2.txt is whitelisted
~/origin/3.txt is blacklisted  
But ~/symlinkeddir is blacklisted. 

The desired output will be that ~/symlinkeddir/2.txt would be whitelisted.

I'm not sure but I think this was the behaviour sometime ago.

**Comment by liloman** [comment]
It's working in another PC with Firefox 49. So I presume that it's due Firefox version. ¿? 

So it must be something "strange" in my enviroment. xD 

Cheers!

**Comment by netblue30** [comment]
Seems to be fine here, I'll close it for now.
