### ISSUE TITLE
nogroups option and man page

### ISSUE THREAD

**Issue by SYN-cook** [netblue30/firejail#1148]
I have found a deviation between man page and actual firejail behavior. When I run first `firejail --nogroups`and then the `id` command, the output still shows few supplementary groups:

`uid=1000(user) gid=1000(user) Gruppen=1000(user),65534,29(audio),65534,44(video),65534` 

~~Also I have no idea what's behind gid 65534~~ (that was an easy one - it's group nogroup). 
According to the man page I would expect something more restrictive like:

`uid=1000(user) gid=1000(user) Gruppen=1000(user)`

This is on Debian (Jessie and Stretch) with firejail 0.44.8 and 0.45

**Comment by netblue30** [comment]
It is a bug! --noroot does something similar with --nogroups, but allows audio, video and tty groups. I'll have to clean them up.

65534 is user/group nobody:
`````
$ grep 65534 /etc/passwd
sync:x:4:65534:sync:/bin:/bin/sync
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
statd:x:106:65534::/var/lib/nfs:/bin/false
sshd:x:107:65534::/var/run/sshd:/usr/sbin/nologin
dnsmasq:x:115:65534:dnsmasq,,,:/var/lib/misc:/bin/false
`````
I'll try to find out why is added by default. Anyway, the guy has no permissions whatsoever. I see it used mainly by servers.

**Comment by netblue30** [comment]
Fixed!
