### ISSUE TITLE
terminix renamed to tilix

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#1150]
Hi, just a FYI. Terminix is being renamed to Tilix (https://github.com/gnunn1/tilix). Adding 'blacklist ${PATH}/tilix' to /etc/firejail/disable-common.inc accordingly could help early adopters. No need to remove 'blacklist ${PATH}/terminix' just yet, the move could take a while to trickle-down in all distros.

Regards

**Comment by netblue30** [comment]
Merged, thanks!
