### ISSUE TITLE
Pale Moon profile invalid, line 30 being the problem

### ISSUE THREAD

**Issue by pizzadude** [netblue30/firejail#1161]
Launching Pale Moon with it's default profile fails because of "line 30 being invalid".
What is line 30 in /etc/firejail/palemoon.profile ?

It is this line:
private-opt palemoon

If I comment it out, Pale Moon launches.

It seems this bug was added with this commit:

https://github.com/netblue30/firejail/pull/1089/commits/a5b2d7ff64209e1a6b4d18d97fea74d50dc05091

**Comment by reinerh** [comment]
Which version of firejail are you using?

**Comment by Fred-Barclay** [comment]
And what distro are you using?

**Comment by pizzadude** [comment]
Firejail version is  0.9.44.10. I *was* running Ubuntu Mate 16.04 LTS at the time of this bug report, but I upgraded to 17.04 beta and it has the same issue.

If I run it with the default profile:

firejail palemoon
Reading profile /etc/firejail/palemoon.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Error: line 30 in /etc/firejail/palemoon.profile is invalid

 firejail --debug palemoon
Autoselecting /bin/bash as shell
Command name #palemoon#
Found palemoon profile in /etc/firejail directory
Reading profile /etc/firejail/palemoon.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Checking /usr/local/bin/palemoon
Checking /usr/bin/palemoon
Error: line 30 in /etc/firejail/palemoon.profile is invalid

**Comment by reinerh** [comment]
On Mon, Mar 27, 2017 at 04:55:48AM -0700, PizzaDude wrote:
> Firejail version is  0.9.44.10. I *was* running Ubuntu Mate 16.04 LTS at the time of this bug report, but I upgraded to 17.04 beta and it has the same issue.

private-opt is only supported in the current git snapshot, it is
not yet released. So for now you could keep the private-opt line
commented out.

**Comment by pizzadude** [comment]
@reinerh Okay, thanks. Also, I noticed that your firejail PPA doesn't have the latest stable release, and it doesn't support zesty either. Are you planning on supporting either of those? Thanks. : )

**Comment by reinerh** [comment]
On Mon, Mar 27, 2017 at 05:06:43AM -0700, PizzaDude wrote:
> @reinerh Okay, thanks. Also, I noticed that your firejail PPA doesn't have the latest stable release, and it doesn't support zesty either. Are you planning on supporting either of those? Thanks. : )

Sorry, I forgot to update it, thanks for the reminder. :)
I will update it later and also create one for zesty.

**Comment by pizzadude** [comment]
@reinerh Thanks :D
