### ISSUE TITLE
Midori profile broken on Arch

### ISSUE THREAD

**Issue by tylerswagar** [netblue30/firejail#1167]
Ever since the jump from Midori 0.5.11-4 to 0.5.11-5 on Arch Linux, the browser hasn't launched properly with Firejail enabled.  It doesn't fully render and it quickly freezes before fully launching.

As best I can tell, the only difference between 0.5.11-4 and 0.5.11-5 is a switch from webkitgtk to webkit2gtk.

Here's the output I get, in case that's useful:

Redirecting symlink to /usr/bin/midori
Reading profile /etc/firejail/midori.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Parent pid 8292, child pid 8293
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized
**
GLib:ERROR:gspawn.c:1181:do_exec: assertion failed: (read_null != -1)

(midori4:2): Gtk-WARNING **: Theme parsing error: gtk3.css:2:31: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(midori4:2): Gtk-WARNING **: Theme parsing error: gtk3.css:3:39: The style property GtkButton:default-outside-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(midori4:2): Gtk-WARNING **: Theme parsing error: gtk3.css:4:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(midori4:2): Gtk-WARNING **: Theme parsing error: gtk3.css:5:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(midori4:2): Gtk-WARNING **: Theme parsing error: gtk3.css:6:30: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(midori4:2): Gtk-WARNING **: Theme parsing error: gtk3.css:26:20: The :insensitive pseudo-class is deprecated. Use :disabled instead.
**
GLib:ERROR:gspawn.c:1181:do_exec: assertion failed: (read_null != -1)
**
GLib:ERROR:gspawn.c:1181:do_exec: assertion failed: (read_null != -1)
^C
Parent received signal 2, shutting down the child process...

Parent is shutting down, bye...

Child received signal 15, shutting down the sandbox...

**Comment by netblue30** [comment]
They moved to webkit and gtk3. I put in git a new profile here: https://github.com/netblue30/firejail/blob/master/etc/midori.profile. Give it a try, thanks.

**Comment by tylerswagar** [comment]
Totally works.  Thank you!

**Comment by netblue30** [comment]
Cool, the next version will have it by default.
