### ISSUE TITLE
Setting rlimit-fsize to 4GB fails

### ISSUE THREAD

**Issue by filippog** [netblue30/firejail#1168]
Hi,
we've run into an issue with `rlimit-fsize` in firejail profiles while set to `4294967296` bytes, firejail would refuse to start with failure to set seccomp filter. 
Upon investigation it seems the issue lies with `sscanf` using `%u` to scan the config file value, as far as I can tell, what do you think?

**Comment by netblue30** [comment]
Fixed on mainline, thank you for the bug.
