### ISSUE TITLE
Using --private-bin with iceweasel (information) ?

### ISSUE THREAD

**Issue by acrobat1** [netblue30/firejail#1169]
Since I cannot figure this out, I'm going to ask here: is there a way to use the --private-bin option with Iceweasel/Firefox-esr in Debian? 

The way this is set up is (as we now) a bit confusing, with /usr/bin/firefox being  a script and /usr/bin/iceweasel being a link to /usr/lib/firefox-esr/firefox-esr : neither of them is working for me with **--private-bin** option : how should this be done ?

**Comment by reinerh** [comment]
It was working for me with this command:
`firejail --private-bin=iceweasel,bash iceweasel`
