### ISSUE TITLE
leftovers from 'tmpfs on ~/.cache' in /etc/firejail/firejail.config

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#1171]
Hi, I noticed some recent commits removed the formerly introduced tmpfs on ~/.cache behavior. If this is indeed no longer in the code, there might be another leftover in firejail.config. Latest git checkout still references..

```
# Enable mounting a tmpfs on top of ~/.cache directory, default enabled.
# cache-tmpfs yes
```
I had to change the default to 'no' in relation to https://github.com/netblue30/firejail/issues/1141. Am I correctly assuming the tmpfs on ~/.cache feature is indeed removed from firejail?

Regards.

**Comment by netblue30** [comment]
Fixed, thanks.
