### ISSUE TITLE
--private=directory and pulseaudio (steam, alsa underruns)

### ISSUE THREAD

**Issue by ejrees** [netblue30/firejail#1172]
Private is amazing for steam because it keeps your home directory clean.

`firejail --noprofile --private=~/Steam steam-native`

Audio "works" but then quickly underruns:
```
ALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usable
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
```

Games have completely garbled audio.

The only way I've been able to fix it is either dmix (load-module module-alsa-sink device=dmix) or the old shm fix (enable-shm = yes). Neither being very good solutions.

I've tried multiple sound cards, different fragment/buffer sizes for pulse, enable-memfd, higher cpu priorities, etc.

**Comment by ejrees** [comment]
Huh, I guess I managed to fix it. I switched over to using jack. Seems to work fine now.

**Comment by netblue30** [comment]
No problem.
