### ISSUE TITLE
Firefox can't save bookmarks

### ISSUE THREAD

**Issue by network23** [netblue30/firejail#1173]
When using Firefox with Firejail I can't make new bookmarks. It recognizes all my already existing bookmarks.
When using Firefox without Firejail I can make new bookmarks. The file where all the bookmarks are placed is in `~\.mozilla\[PROFILE_FOLDER]\places.sqlite`

**Comment by netblue30** [comment]
One common issue with firefox is this: https://firejail.wordpress.com/support/frequently-asked-questions/#firefox

Also, if you use --private, it will not save the bookmarks. How do you start firefox?

**Comment by chiraag-nataraj** [comment]
@network23 As long as `~/.mozilla` is whitelisted (which it is if your profile is loading properly), then I'm not sure why you're not able to save new bookmarks. If you run it from the console, do you get any errors?
@netblue30 If @network23 is able to access their bookmarks from previous sessions, then the profile is being loaded, which means `--private` isn't being used.

**Comment by network23** [comment]
I tried a lot of things, starting it without apparmor, firejail --apparmor firefox,
Editing firefox.profile, checking various settings/permissions. Didn't work. Upgraded today to 0.9.44.10 via apt, and it now works :+1: 
Thanks for the comments and this great software :1st_place_medal:
