### ISSUE TITLE
Pulseaudio issue (no sound) when running Firefox in Firejail

### ISSUE THREAD

**Issue by BytesTuner** [netblue30/firejail#1175]
As the title said. I already tried without success those documented fixes:

https://firejail.wordpress.com/support/known-problems/#pulseaudio

I also try to upgrade to the latest version of Firejail (0.9.44.10) with no different results.

...and yes, the sound is working (and I do not have the pulseaudio dialog box) if I start Firefox without firejail.

Additional information:

My pulseaudio version: 9.0

Any suggestions? Thank you!

**Comment by chiraag-nataraj** [comment]
What pulseaudio dialog box are you talking about? One thing you can try is using `firejail --ignore=<something>` or commenting out everything from the firefox profile and slowly uncommenting stuff until you find the offending line.

**Comment by BytesTuner** [comment]
>What pulseaudio dialog box are you talking about?

This one:

https://lut.im/w8qbLWHcHy/GaxukY03tA43GCU0.png


> commenting out everything from the firefox profile and slowly uncommenting stuff until you find the offending line.

I tried that and I have the issue even when all the option are comment out...

I'm really out of ideas on this issue.

**Comment by chiraag-nataraj** [comment]
Huh...I've literally never had that issue. Let's start with the basics: does `firejail --noprofile firefox` work? If so, let's create a new `firejail` profile in `~/.config/firejail/firefox.profile` where we can start adding options. Start with `seccomp` and `caps.drop all` and let's work from there.

**Comment by BytesTuner** [comment]
>Let's start with the basics: does firejail --noprofile firefox work?

Nope and the sound is working perfectly if I start firefox in the terminal with just 'firefox'

**Comment by BytesTuner** [comment]
Here is the error message I get multiple times in the terminal with 'firejail --noprofile firefox'

Client failed to connect to the D-BUS daemon: Failed to connect to socket /run/user/1000/bus

**Comment by chiraag-nataraj** [comment]
> Nope and the sound is working perfectly if I start firefox in the terminal with just 'firefox'

Huh, interesting. Which version of firefox?

> Client failed to connect to the D-BUS daemon: Failed to connect to socket /run/user/1000/bus

Shouldn't really matter (I don't think it has anything to do with the pulseaudio issue).

**Comment by BytesTuner** [comment]
>Which version of firefox?

52.0.1 (64-bit)

**Comment by chiraag-nataraj** [comment]
Hmm...I used to be on that version with no issues. Which distro?

**Comment by BytesTuner** [comment]
OK, I just found my problem. I remember that I was also having a apparmor profile enabled for Firefox. I disable it and tried 'firejail --noprofile firefox' again...and it worked.

The thing is before Firefox 52, I could get sound in Firefox even if I was using both Firejail and apparmor. Apparmor was "connecting" to pulseaudio and Firefox in Firejail was using ALSA. So the sound was working for me with the 2 sandboxes active. However Firefox stopped supporting ALSA in version 52 and that's when my sound problem began...Yeah I should have thought of this sooner. Sorry and thanks for the help!

**Comment by Fred-Barclay** [comment]
@BytesTuner With the apparmor profile disabled, does `firejail firefox` have audio?

**Comment by BytesTuner** [comment]
Yes. Now with Firefox 52, I will have to choose between using Firejail or apparmor. I cannot use both at the same time anymore if I want sound from the browser.

**Comment by chiraag-nataraj** [comment]
Huh...interesting. Glad to see you sorted it out!

**Comment by Hocceruser** [comment]
It is very easy to solve this issue. You just need to add a line 
`/run/firejail/mnt/pulse/client.conf r,`
to /etc/apparmor.d/local/usr.bin.chromium-browser.

Does somebody have an idea how to solve this for ALL users? (Most users will probably not search in GitHub issues if they have a problem with PulseAudio). 
What about what I proposed here: https://github.com/netblue30/firejail/issues/1487#issuecomment-328508519

(It is so easy to solve this, in my opinion it CAN'T be that it remains unsolved for 90 % of the users)
