### ISSUE TITLE
Firejail app cannot communicate with my Yubikey 

### ISSUE THREAD

**Issue by BytesTuner** [netblue30/firejail#1176]
I'm currently testing a new app with firejail that needs to access my Yubikee (connected in a USB port) but cannot see it inside a jail.

Is there a option I could add (or remove) to the app profile that will most likely give access to the Yubikey?

Thank you!

**Comment by Fred-Barclay** [comment]
@BytesTuner 
Could you post the app profile you are currently using?

Thanks!

**Comment by BytesTuner** [comment]
The app I'm testing is the current git version of KeepassXC (the new and most active fork of KeepassX):

https://github.com/keepassxreboot/keepassxc

...and the profile I'm using with it is the default Firejail KeepassX (I obviously customize it with the right keepassxc directory):

https://github.com/netblue30/firejail/blob/master/etc/keepassx.profile

**Comment by chiraag-nataraj** [comment]
The problem is probably the `private-dev` option. You'll want to `whitelist` the appropriate device in `/dev` to ensure KeepassXC sees the yubikey.

**Comment by BytesTuner** [comment]
OK done some more tests and the culprits were:

protocol unix
private-dev

This is my working final profile for keepassxc:

# This file is overwritten during software install.
# Persistent customizations should go in a .local file.

# keepassxc password manager profile
noblacklist ${HOME}/.config/keepassxc
noblacklist ${HOME}/.keepassxc
noblacklist ${HOME}/*.kdbx
noblacklist ${HOME}/Documents/*.kdbx
noblacklist ${HOME}/*.kdb
noblacklist ${HOME}/Documents/*.kdb

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc

caps.drop all
net none
nogroups
nonewprivs
noroot
nosound
#protocol unix
seccomp
shell none

private-bin keepassxc
#private-etc fonts
#private-dev
private-tmp

___________________________________________

I obviously don't mind if someone want to add it to this git.

Important thing: 

The 'net none' option need to be comment out if someone want to use their new KeePassHTTP support for use with PassIFox in Mozilla Firefox and chromeIPass in Google Chrome or Chromium. In my case, I don't use it so I leave it uncommented.

**Comment by Fred-Barclay** [comment]
@BytesTuner I've added the profile, thanks! 5a982a1e5e32be3fd99e7988b2f052d49c1f8a12

Currently private-dev and protocol unix are commented out. I or someone else *might* change this later (I'm not sure it's a good idea to disable this for all users - we don't for the other keypass profiles). If so, you can just copy the profile to ~/.config/firejail and comment out/remove those two lines.

Cheers and thanks for the profile!
Fred

**Comment by BytesTuner** [comment]
> I or someone else might change this later (I'm not sure it's a good idea to disable this for all users - we don't for the other keypass profiles)

It basically all depends which new KeepassXC the user wants to use. The more secure option is to not commented them out. The basic features of KeepassXC will work this way. 

However, some options most be commented out if the user wants to use the new features:

To use KeePassHTTP -> net none must be commented out

To use YubiKey HMAC-SHA1 authentication for unlocking databases -> protocol unix and private-dev must be commented out. If not, the app won't see the Yubikey connected on the computer.

I don't know but maybe it could be a good thing to add this information directly in the profile file...?

>Cheers and thanks for the profile!

No problem. You're welcome! :)

**Comment by Fred-Barclay** [comment]
Good idea - I've added a note for KeePassHTTP.
For YubiKey, that's more of a general firejail knowledge issue than with the keepassxc profile (private-dev should interfere with usb keys in **any** profile) but it's definitely good to know for future reference.

Cheers!

**Comment by Fred-Barclay** [comment]
@chiraag-nataraj Thanks for the help too! :+1:

**Comment by chiraag-nataraj** [comment]
Hehe glad to see you sorted it out! 😄

**Comment by arigit** [comment]
In Fedora 26 under wayland, the following two options didn't work:
--noroot
--private-tmp

If launching via command line, this can help:

firejail --noprofile --net=none --caps.drop=all --nogroups --nonewprivs --nosound --seccomp --shell=none --private-bin=keepassxc

**Comment by Fred-Barclay** [comment]
@arigit disable-common.inc isn't meant to be used as a profile. We use it to blacklist common files that shouldn't be visible inside the sandbox. It would probably be better to use the keepassxc profile (in which case you won't have to specify a profile on the command line - firejail will know to use the keepassxc profile since you're launching keepassxc), or the default profile, which you can specify with `--profile=/etc/firejail/default.profile`.
Cheers!
