### ISSUE TITLE
question: how can i sandbox a DE

### ISSUE THREAD

**Issue by nyancat18** [netblue30/firejail#1178]
how can i sandbox a desktu? (lxde/xfce) ?

just like a docker

**Comment by chiraag-nataraj** [comment]
One easy way is to run it within a restricted login shell. Just keep in mind that anything you launch within that DE would then be jailed by the profile of the _DE_ rather than the profile of the _program_. Why sandbox the entire DE?

**Comment by reinerh** [comment]
I also don't think it's a good idea.
You would have to use a profile that is so permissive that all your programs started inside the DE still work.
Better individually jail your applications.

**Comment by Fred-Barclay** [comment]
Make that three of us who don't think it's a good idea. :wink: Any profile that could jail a DE and still allow all your programmes to work would probably be a very weak profile.

**Comment by netblue30** [comment]
I would stay away, the profile will be too permissive. There is a /etc/firejail/openbox.profile, mainly used or x11=xephyr if you want something to start from if you build your own profile.
