### ISSUE TITLE
vlc profile fail 

### ISSUE THREAD

**Issue by triceratops1** [netblue30/firejail#1179]
i try to run cvlc 
but fail 
https://paste.teknik.io/Raw/7Kbzz

**Comment by Fred-Barclay** [comment]
G'day @triceratops1 
I've added a cvlc profile https://github.com/netblue30/firejail/blob/master/etc/cvlc.profile. Can you copy it into ~/.config/firejail and see if it works for you?
Cheers!

**Comment by triceratops1** [comment]
ok :D

**Comment by triceratops1** [comment]
IT WORKS 


thanks

**Comment by Fred-Barclay** [comment]
No worries, mate. :smile:
