### ISSUE TITLE
Chromium profile broken under current git

### ISSUE THREAD

**Issue by pyamsoft** [netblue30/firejail#118]
Chromium fails to launch because it depends on the usage of perl, which is blacklisted in the chromium script due to the incluson of the the disable-devel.inc file, which blacklists perl.

Most recent commit at time of filing: cc29de3777a4e44cf09b10e5efcc7572400c8e09

**Comment by pyamsoft** [comment]
This is infact caused from ArchLinux's configuration of chromium. The repository package comes with a perl script that is used to launch the browser, and the blacklisting of perl is causing said script to fail.

The issue can be remedied by creating a custom chromium profile which overrides the existing one, and adding a line to noblacklist /usr/bin/perl

This will be closed as it is not a bug in firejail.

**Comment by netblue30** [comment]
Fixed in Firejail - disable-devel.inc is commented out.

**Comment by pyamsoft** [comment]
Wouldn't it be better to instead add the following at the top of  the chromium.profile:

```
# Do not blacklist perl, needed for launcher script
noblacklist /usr/bin/perl
noblacklist /usr/share/perl*
noblacklist /usr/lib/perl*
```

This way users will still benefit from the blacklisting of other devel items, but still be able to utilze the perl script when needed.

**Comment by netblue30** [comment]
I'll keep that in mind, thanks. There will be some more modifications going in there.
