### ISSUE TITLE
[Question?] Modifying Brave profile to allow built-in password manager (keyring-dependent) to actually work

### ISSUE THREAD

**Issue by BurnySnek** [netblue30/firejail#1189]
Hi!
I've managed to tweak firejail profile for Brave to work okay (the one that gets installed by default courtesy of Debian backports is still broken)

However, I can't figure out the right directives to allow it to touch keyring.
Keyring appears necessary for built-in password manager to work, and, well, I need it.

Tried:
adding 
noblacklist ${HOME}/.gnome2/keyrings
noblacklist ${HOME}/.kde4/share/apps/kwallet
noblacklist ${HOME}/.kde/share/apps/kwallet
noblacklist ${HOME}/.local/share/kwalletd
noblacklist ${HOME}/.config/keybase

to my experimental brave profile.

No cigar.

Please help.

**Comment by netblue30** [comment]
Use this profile: https://github.com/netblue30/firejail/blob/master/etc/brave.profile

There is a big fight going on with Brave, recently they enabled a seccomp sandbox inside the browser (https://github.com/netblue30/firejail/issues/1110).

**Comment by BurnySnek** [comment]
@netblue30 
I tried that profile, brave loads and works fine in everything **except** built-in password manager.
Password manager still not working (also, "enter password to decrypt keyring" prompt that usually happens when running brave naked does not show)

**Comment by netblue30** [comment]
What happens if you put a "noblacklist ~/.gnupg" in top of the file?

**Comment by BurnySnek** [comment]
@netblue30 
noblacklist ~/.gnupg + that profile you linked to do the trick!

Thanks! that seems to finally work

**Comment by netblue30** [comment]
Thanks, I updated the profile in git with a "noblacklist ~/.gnupg". Thanks.
