### ISSUE TITLE
palemoon fails too  

### ISSUE THREAD

**Issue by triceratops1** [netblue30/firejail#1193]
firejail palemoon
Reading profile /etc/firejail/palemoon.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Warning: user namespaces not available in the current kernel.
Error: line 30 in /etc/firejail/palemoon.profile is invalid

firejail version 0.9.44.10

**Comment by triceratops1** [comment]
bugfix:   disable private-opt

**Comment by Fred-Barclay** [comment]
G'day @triceratops1 
Private-opt isn't yet supported in firejail 0.9.44. It's only been implemented in the current git snapshot (0.9.45 at the moment). So if you try to use the palemoon profile here on GitHub in firejail 0.9.44, it will fail (as you are experiencing).
Please see https://github.com/netblue30/firejail/issues/1161#issuecomment-289433293

Please comment out the private-opt line in the profile.
