### ISSUE TITLE
application window greys out

### ISSUE THREAD

**Issue by gso** [netblue30/firejail#1196]
Ubuntu 16.04.2
`firejail` version 0.9.44.10
Intel® Core™ Duo CPU T2250 @ 1.73GHz × 2 
2.0 GiB
Intel® 945GM x86/MMX/SSE2

`/usr/bin/firejail --xll=xorg --private=~/Opera-Sandbox /usr/bin/opera --private`

With `--x11=xorg` the application window greys out after a few seconds of the window rendering, an 'Application not responding' - 'Wait' /  'Force Quit' dialogue displaying on exit.

The same issue also when running `firefox` in the sandbox.

With `xpra` the browser window renders OK, however with the following issues, i) the mouse pointer disappears for some reason [edit: this is not a problem with the latest release of `xpra`], ii) `firejail` sometimes hangs at the command line (before the browser window actually renders), though will run OK the second time the command is invoked, and iii) if I switch to a text console and back to X the browser crashes a few seconds later.

This is a low spec. machine, the same command to run a sandboxed browser works without any problems on Lubuntu, Linux Mint Cinnamon and Zorin OS (GNOME 3 desktop by the looks, Ubuntu based dist.).

**Comment by gso** [comment]
A shot in the dark, if I remember correctly `firejail` reported a number of missing extensions on Ubuntu.  Could missing X protocol extensions be something to do with the problem.

**Comment by netblue30** [comment]
X11 security extension disables a number of regular X11 extensions. If your application uses one of them, the application will freeze. For example I start Chromium:
`````
$ firejail --x11=xorg chromium
Reading profile /etc/firejail/chromium.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 1817, child pid 1819
Using authority file /tmp/.tmpXauth-TaWIdm
authorization id is 749
Writing authority file /tmp/.tmpXauth-TaWIdm
Child process initialized
Warning: an existing sandbox was detected. /usr/bin/chromium will run without any additional sandboxing features
Xlib:  extension "RANDR" missing on display ":0.0".
Xlib:  extension "XInputExtension" missing on display ":0.0".
Xlib:  extension "RANDR" missing on display ":0.0".
Xlib:  extension "XInputExtension" missing on display ":0.0".
Xlib:  extension "XInputExtension" missing on display ":0.0".
Xlib:  extension "SHAPE" missing on display ":0.0".
Xlib:  extension "SHAPE" missing on display ":0.0".
`````
The browser comes up, but the mouse doesn't work. On Debian jessie I get about half the programs working (including Firefox), the rest behave strangely.

**Comment by gso** [comment]
The odd thing was that while a program works with the `xorg` server on lubuntu, Mint, Zorin, the same program greys out on Unity.  Could be a resources issue (a low spec. laptop), works fine on Zorin though (GNOME 3).

**Comment by chiraag-nataraj** [comment]
Is this still an issue?

**Comment by chiraag-nataraj** [comment]
I'm going to close this for now. @gso, please feel free to re-open if this is still an issue.
