### ISSUE TITLE
Is there a point in `--net=<ethernet_interface>` if you don't use X11 sandboxing? 

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#1200]
Quick question: Is there a point in `--net=<ethernet_interface>` if you don't use X11 sandboxing? What additional protection would it offer, if any? I'm currently writing a wrapper script for Firefox and for laptops I don't use this option since wlan devices are not supported and I'm wondering if I should use it for my desktop that is always hooked up to ethernet.

Thanks.

**Comment by chiraag-nataraj** [comment]
Well if nothing else, you can setup custom iptables/netfilter rules (see the `--netfilter` option).

**Comment by rieje** [comment]
I found out I couldn't access web GUIs of applications via `127.0.0.1:<port>`, so it won't be useful for my purposes.
