### ISSUE TITLE
Can't whitelist subdirectories

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#121]
I can't whitelist a subdirectory of a directory in my $HOME. That is, whitelisting ~/dir works, but ~/dir/subdir doesn't work. There is no error/warning on firejail invocation, but upon trying to enter the subdirectory, permission is denied.
If I try to also whitelist the parent directory, I get "Error mkdir:whitelist_path(99): File exists". Whitelisting the parent directory only, works.

I discovered this while wanting to whitelist ~/.config/deadbeef and deadbeef curiously failed to start, but started correctly when not whitelisted.

My version is 0.9.32

Example:
```
mkdir -p ~/test/1 ~/test/2
firejail --whitelist=~/test/1
cd ~/test/1
cd ~/test/
```

**Comment by netblue30** [comment]
I would suggest you move to version 0.9.34, it has quite a number of fixes. This is how I start deadbeef on my machine:
`````
$ firejail /opt/deadbeef-0.6.2/deadbeef
`````
It also works with whitelisting:
`````
$ firejail --whitelist=~/.config/deadbeef /opt/deadbeef-0.6.2/deadbeef
`````

**Comment by avoidr** [comment]
Sorry I take so long, I was very busy. I'll test it soon, but I believe you when you say it is fixed.

**Comment by netblue30** [comment]
No problem, give it a try and let me know.

**Comment by avoidr** [comment]
Just updated to 0.9.34
For some reason it still doesn't work. I don't know, do I need to reboot or something?
I get this:
```
$ firejail --whitelist=.config/deadbeef/ deadbeef
Reading profile /etc/firejail/deadbeef.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Parent pid 19653, child pid 19654
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized
starting deadbeef 0.6.2
server_start
INFO: unlink socket: Permission denied
bind: Permission denied

parent is shutting down, bye...
```
I tried some variations of the whitelist path, namely
```
${HOME}/.config/deadbeef/
~/.config/deadbeef/
./.config/deadbeef/
.config/deadbeef/
.config/deadbeef
```
and it all yielded the same result.

**Comment by netblue30** [comment]
You need a full path in --whitelist. Instead of "--whitelist=.config/deadbeef/", put  "--whitelist=~/.config/deadbeef/"

**Comment by avoidr** [comment]
Yeah that's what I tried. They're all equivalent.
Anyway, I'll try fixing it myself. Not sure why it is a problem for me but seemingly no one else, but alright.
