### ISSUE TITLE
feature request, 'xephyr-extra-params -dpi' option

### ISSUE THREAD

**Issue by gso** [netblue30/firejail#1212]
`Xephyr` by the looks is unable to determine DPI, defaulting to 75 dpi, the result being not all but some applications render text in a smaller font than with the correct DPI setting (`openbox` by way of an example).  The [X Server `-dpi` option](https://www.x.org/archive/X11R6.8.0/doc/Xserver.1.html) fixes this.  At a cursory glance it's not possible to set this from within a `Xephyr` display (gamma setting issue).  A 'xephyr-extra-params' setting would be useful:

> -dpi resolution
> sets the resolution for all screens, in dots per inch. To be used when the server cannot determine the screen size(s) from the hardware.

[Edit]  The command to determine the [DPI of a display](https://wiki.archlinux.org/index.php/xorg#Display_size_and_DPI): `xdpyinfo |grep -B2 resolution`

**Comment by netblue30** [comment]
I'll put a fix in for the next release, thanks.

**Comment by netblue30** [comment]
Support is on mainline. Go in /etc/firejail/firejail.config and add an xpra-extra-params statement - there is a dpi example in that file but is commented out. Let me know if you run into problems.
