### ISSUE TITLE
Exceptions to blacklists and 'noexec {HOME}'

### ISSUE THREAD

**Issue by Irvinehimself** [netblue30/firejail#1213]
Okay,I have been struggling with this fo a week or so, and, lacking a dedicated forum, this seems to be the best/only place to ask.

The issue first came up when I was trying to write a very strict Firefox profile that blacklisted basically everything in {Home} except '.mozilla', and 'downloads. Although this example was fairly trivial and of little importance, it became more urgent when I realised that the line 'noexec{HOME}' in the standard GIMP profile prevented Gimp from loading plugins located in '~/.gimp-2.8/plug-ins/'

So, is there a way to add exceptions to a blacklist or 'noexec {DIR}'?

Thanks for a great program.
Irvine

**Comment by chiraag-nataraj** [comment]
For the tight Firefox profile (and others), check out my repo https://github.com/chiraag-nataraj/firejail-profiles!

You can use `ignore noexec` (I think?) to fix that GIMP error.

**Comment by netblue30** [comment]
Plugins seem to be very popular with gimp people, similar to firefox addons. I commented out noexec line in the profile. Thanks for the bug.
