### ISSUE TITLE
Nylas Mail Profile

### ISSUE THREAD

**Issue by mustaqimM** [netblue30/firejail#1215]
```
include /etc/firejail/nylas.local

# nylas mail profile
noblacklist ~/.config/Nylas Mail
whitelist ~/.config/Nylas Mail
noblacklist ~/.nylas-mail
whitelist ~/.nylas-mail
whitelist ${DOWNLOADS}

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc

caps.drop all
netfilter
nonewprivs
nogroups
noroot
protocol unix,inet,inet6,netlink
seccomp

include /etc/firejail/whitelist-common.inc

ignore private-tmp
private-dev
```
@Fred-Barclay I finally got it to work now with the above profile. But I might have added an option that isn't needed, so could you please review it.

**Comment by netblue30** [comment]
Take a look in /home/username/.cache directory if there is a directory created by nylas - something like ~/.cache/nylas or similar.

Some mail clients use to move deleted emails over in ~/.cache. Thunderbird does it this way. We will have to blacklist that directory in disable-programs.inc file. Thanks for the profile.

**Comment by Fred-Barclay** [comment]
@mustaqimM That looks pretty good! I agree with @netblue30: there might be a .cache/nylas directory that would need to be whitelisted.
`ignore private-tmp` shouldn't be necessary.
Also, can you replace the `protocol unix,inet,inet6,netlink` line with `protocol unix,inet,inet6`? I don't know if it'll work but it's worth a try.

**Comment by mustaqimM** [comment]
@netblue30 There isn't one in `cache` because all actions occur in `~/.nylas-mail/`, including downloading of attachments. Nylas doesn't download emails like Thunderbird.
@Fred-Barclay It requires `netlink` or it won't start.

**Comment by Fred-Barclay** [comment]
Thanks! Would you like to open a pull request for this, or would you rather me just copy the profile over?

**Comment by mustaqimM** [comment]
@Fred-Barclay I'm fine with whatever you feel is easier

**Comment by Fred-Barclay** [comment]
It's been added: e08c80d0a9fbf3def45c5957a7048d597de6e966
Thanks @mustaqimM!
