### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#1216]
Since https://github.com/netblue30/firejail/commit/8d8686af26be5d06af681a492ed3a134fb638c56 , building firejail seems broken.  configure works, but `make deb` fails with this error -
```
Makefile:99: *** missing separator.  Stop.
```

I'm building on Lubuntu 14.04

**Comment by netblue30** [comment]
I put a fix in, you can give it a try.

**Comment by laniakea64** [comment]
Fixed, thanks! 😃
