### ISSUE TITLE
Use curly-brackets in filename instead of ()

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#1217]
Hi, just a quick FYI, https://github.com/netblue30/firejail/commit/e08c80d0a9fbf3def45c5957a7048d597de6e966 breaks firejail. This is due to uasge of () instead of {} in the newly added nylas-mail entree in /etc/firejail/disable-programs.inc. An example with mpv is provided below, but I guess all profiles including `disable-programs.inc` will cause firejail to fail.

$ firejail mpv
Reading profile /etc/firejail/mpv.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Error: "$(HOME)/.nylas-mail" is an invalid filename

Regards.

**Comment by Fred-Barclay** [comment]
Oops - my bad. Fixed and pushed.
Thanks for catching that! 🥇
