### ISSUE TITLE
Most KDE4 apps don't work?

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#123]
Even with "--noprofile" most KDE4 apps fail to launch (parent is shutting down, bye...). So i don't even know what to tweak...

for example ktorrent, kmail, akregator, amarok, konsole... (others do work, digikam gwenview, ksysguard ...)

If some special config is needed, then it would be nice to have at least an example of a kde config file in etc. I couldn't find anything on the internet about this.

(up to date 64bits Linux Mint 17.2 KDE 4.14.2, firejail 0.9.34, kernel 3.16.0-38-generic)

**Comment by netblue30** [comment]
I guess I'll have to fix them, thanks for the bug!

**Comment by pirate486743186** [comment]
I got it. It's like with Seafile. These applications "fork children and exit".... 
http://pyther.net/2015/10/sandboxing-seafile-w-firejail/

Behh, the hack with waiter.py seams a bit convoluted.

**Comment by netblue30** [comment]
I'll add a very generic fix for all these programs in the next few days. It will also fix various server programs.

**Comment by pirate486743186** [comment]
oh ok :)

you did noticed my comment in "firejail doesn't show some apps in tree/list" right?

**Comment by netblue30** [comment]
I have a fix in for kde applications. Give it a try! For the tree/list I am still digging.
