### ISSUE TITLE
--no3d in virtual machines?

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#1233]
firejail self-build from https://github.com/netblue30/firejail/commit/e31d453f4ebec9974f7bcaee33cadaa83e12b791
Xubuntu 16.04 VirtualBox guest (under VirtualBox 5.1.18)

My Xubuntu 16.04 VM has VirtualBox Guest Additions installed and 3D acceleration enabled.  But, within that VM, I would like to disable hardware acceleration only for 2048-qt.  So I tried using firejail with the `--no3d` command-line option -
```
firejail --no3d --noprofile 2048-qt
```
And 2048-qt had hardware acceleration enabled. 🙁 

Now as I recall, compared to the "standard" graphics drivers, there is some weirdness in how VirtualBox Guest Additions does 3D acceleration. (I don't know any details, sorry.)  So I'm not sure whether `--no3d` as it is should be expected to work in a VirtualBox VM.

Can firejail be used to disable hardware acceleration for individual programs inside a VirtualBox VM?

**Comment by chiraag-nataraj** [comment]
@laniakea64 Is this still an issue?

**Comment by laniakea64** [comment]
Yes, this is still an issue in self build from https://github.com/netblue30/firejail/commit/9db1effb598027c3facfa009bf4a5bcf90821b00

**Comment by chiraag-nataraj** [comment]
Hmm, this seems to be an issue with `qemu` as well. I suspect this is going to be a problem with any virtualization platform. @netblue30 Do you understand why this is happening?

**Comment by laniakea64** [comment]
`--no3d` appears to be working for me in VirtualBox 6.0.18 VM, Xubuntu 18.04 64-bit guest with firejail 0.9.62 -

```
$ /usr/lib/nux/unity_support_test -p
OpenGL vendor string:   VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
OpenGL version string:  2.1 Mesa 19.2.8

Not software rendered:    yes
Not blacklisted:          yes
GLX fbconfig:             yes
GLX texture from pixmap:  yes
GL npot or rect textures: yes
GL vertex program:        yes
GL fragment program:      yes
GL vertex buffer object:  yes
GL framebuffer object:    yes
GL version is 1.4+:       yes

Unity 3D supported:       yes
$ firejail --version
firejail version 0.9.62

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is disabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

$ firejail --noprofile --no3d /usr/lib/nux/unity_support_test -p
Parent pid 1608, child pid 1609
Child process initialized in 21.98 ms
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: vmwgfx
OpenGL vendor string:   VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 9.0, 256 bits)
OpenGL version string:  3.1 Mesa 19.2.8

Not software rendered:    no
Not blacklisted:          yes
GLX fbconfig:             yes
GLX texture from pixmap:  yes
GL npot or rect textures: yes
GL vertex program:        yes
GL fragment program:      yes
GL vertex buffer object:  yes
GL framebuffer object:    yes
GL version is 1.4+:       yes

Unity 3D supported:       no

Parent is shutting down, bye...
$ 
```
