### ISSUE TITLE
Support whitelisting in overlayfs

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#1234]
firejail self-build from https://github.com/netblue30/firejail/commit/f94b3bb27565a93b6d963bda2daac4b912458861
Xubuntu 16.04

While tweaking profiles, I noticed a significant difference in behavior of the home directory in a `--overlay-tmpfs` sandbox compared to a non-overlay sandbox.

Steps to reproduce:
1) Create a test profile at `~/Documents/Goo.profile` -
```
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc

caps.drop all
seccomp
protocol unix,inet,inet6,netlink
tracelog
noroot

whitelist ~/Downloads

whitelist ~/Documents
read-only ~/Documents

include /etc/firejail/whitelist-common.inc
```
2) Run firejail with the profile -
```
firejail --profile=/home/(you)/Documents/Goo.profile
```
In the sandbox, run these commands -
```
cd
ls -la
exit
```
3) Now run firejail with `--overlay-tmpfs` with that profile -
```
firejail --ignore=noroot --profile=/home/(you)/Documents/Goo.profile --overlay-tmpfs
```
Repeat the same commands in the sandbox.

________

**Expected results:** No difference in behavior inside the sandbox.

**Actual results**: In the non-overlay sandbox, only the whitelisted files/folders are listed.  Whereas in the `--overlay-tmpfs` sandbox, everything in the home directory is listed.

Some bisecting seems to point to https://github.com/netblue30/firejail/commit/567585fe3b2375e0b9dc55dac3672b99aade19f0 as when this difference started.

Is this difference intended?  If so, is there a better way to "restore" the non-overlay behavior than using `blacklist ${HOME}/*` and a lot of `noblacklist`?

**Comment by netblue30** [comment]
This is what I get:
`````
$ firejail --ignore=noroot --profile=p --overlay-tmpfs
Reading profile p
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 2001, child pid 2002
OverlayFS configured in /run/firejail/mnt directory
Dropping all Linux capabilities and enforcing default seccomp filter
Warning: failed to unmount /sys
Warning: whitelist feature is disabled in overlay
Blacklist violations are logged to syslog
Child process initialized
`````

Whitelists are disabled when using overlayfs. I'll try to add support for them in a future version.

**Comment by chiraag-nataraj** [comment]
This seems to be fixed. @laniakea64, please feel free to re-open if you still have this issue.

**Comment by laniakea64** [comment]
I do not see this issue in self build from https://github.com/netblue30/firejail/commit/1e13e50799da55d1d475f89aa28206e347bd4757 .  Thanks for the fix! :smiley:
