### ISSUE TITLE
Pulseaudio 10.0 with Firefox not working with 0.9.44.10 on PCLinuxOS KDE 64-bit

### ISSUE THREAD

**Issue by 360asm** [netblue30/firejail#1237]
Same conditions as:
https://github.com/netblue30/firejail/issues/1175

Firefox is latest 53.0. Problem has existed since compulsory use of pulseaudio in Firefox 52.0.

Have rechecked both workarounds at:
https://firejail.wordpress.com/support/known-problems/#pulseaudio
with no success.

Kernel is:
Linux localhost 4.10.9-pclos1 #1 SMP Sat Apr 8 14:46:39 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Debug provides no mention of sound issues even when the 'Install pulseaudio' message bar comes up when accessing any sound application from inside Firefox.

Is there any other info I can provide?

**Comment by netblue30** [comment]
I'll give it a try.

**Comment by netblue30** [comment]
I downloaded the latest firefox (version 53) from https://www.mozilla.org/en-US/firefox/new/. I installed it under /opt:
`````
$ cd /opt
$ sudo tar -xjvf /home/netblue/firefox-53.0.tar.bz2 
`````

On my Debian stable the sound in firefox doesn't work with or without firejail. The system is setup for ALSA, there is no PulseAudio installed. This is to be expected, since firefox removed ALSA support in version 52.

On a Ubuntu Gnome 17.04 with PulseAudio 10.0 the sound works fine for firefox version 53 under firejail.

Try the version distributed by Mozilla (link above), just in case there is something wrong with the build from your distro. Unpack the archive under /opt or somewhere else outside your home directory.

**Comment by 360asm** [comment]
Hi,

Not sure if you wanted me to reply to the Github thread or direct, so replied direct as you didn't put your reply on the thread. Can move this to the thread if you prefer.

Followed your advice and checking the process tree in firejail tools I get:1291:david:firejail --debug /opt/firefox/firefox 
    1293:david:firejail --debug /opt/firefox/firefox 
        1299:david:/opt/firefox/firefox 
so I guess I am using the version I just unpacked to /opt. Still have the same issue with Firefox displaying the pulseaudio warning on youtube.
Do I need to remove firefox from Synaptic as well? Any other software I need to check?
 

    On Friday, 21 April 2017, 0:45, netblue30 <notifications@github.com> wrote:
 

 I downloaded the latest firefox (version 53) from https://www.mozilla.org/en-US/firefox/new/. I installed it under /opt:$ cd /opt
$ sudo tar -xjvf /home/netblue/firefox-53.0.tar.bz2 
On my Debian stable the sound in firefox doesn't work with or without firejail. The system is setup for ALSA, there is no PulseAudio installed. This is to be expected, since firefox removed ALSA support in version 52.On a Ubuntu Gnome 17.04 with PulseAudio 10.0 the sound works fine for firefox version 53 under firejail.Try the version distributed by Mozilla (link above), just in case there is something wrong with the build from your distro. Unpack the archive under /opt or somewhere else outside your home directory.—

**Comment by 360asm** [comment]
I downloaded, compiled and installed firejail 0.9.46~rc1 into /opt as well. Process tree now reads:
22921:david:/opt/firejail-0.9.46~rc1/bin/firejail --debug /opt/firefox/firefox 
    22923:david:/opt/firejail-0.9.46~rc1/bin/firejail --debug /opt/firefox/firefox 
        22933:david:/opt/firefox/firefox 
so I am definitely running the firefox and firejail you suggested, but am still getting the pulseaudio message and no sound.

**Comment by 360asm** [comment]
I downloaded, compiled and installed firejail 0.9.46rc1 and the process tree is now:
22921:david:/opt/firejail-0.9.46rc1/bin/firejail --debug /opt/firefox/firefox 
    22923:david:/opt/firejail-0.9.46rc1/bin/firejail --debug /opt/firefox/firefox 
        22933:david:/opt/firefox/firefox 
so I am definitely running the firefox and firejail you suggested, but am still getting the pulseaudio message and no sound.

BTW if the directory name has a tilde before the rc1 like this firejail 0.9.46~rc1 then all the text between the first and second instance of the tilde in the directory name is printed as struckout with the tildes not printing like this: firejail 0.9.46~rc1

**Comment by 360asm** [comment]
Firejail and firetools updated in PCLinuxOS repo. Firejail now 0.9.44.10. Firetools now 0.9.46.
I have re-verified both fixes in the .conf files with firefox 53 from the PCLinuxOS repo and the version 53 I downloaded direct from Mozilla as suggested.

The failure with pulseaudio is still a hard bug. Is there anything else I can try or provide for analysis?

**Comment by 360asm** [comment]
Also, the failure to work with pulseaudio leaves no messages in /var/log/syslog or /var/log/messages.

**Comment by netblue30** [comment]
I started downloading PCLinuxOS Mate version - I assume it is the same problem on both Mate and KDE.

**Comment by 360asm** [comment]
Unfortunately can not confirm whether it is present under MATE, only KDE

**Comment by SYN-cook** [comment]
It is probably a stupid question, but only to be sure there is no misunderstanding: Is your Firefox also constrained by Apparmor, like in #1175? 
That is, did you write `apparmor` into your Firejail profile or does running `aa-status` as superuser show an enforced Firefox profile?

**Comment by 360asm** [comment]
Not a stupid question. No, I do not have any apparmor profiles on my system. aa-status comes up as command not found.
Also, the issue I meant to reference in the first post was:No sound using pulseaudio after 0.9.44.6 update · Issue #1054 · netblue30/firejail

  
|  
|  
|  
|   |    |

  |

  |
|  
|    |  
No sound using pulseaudio after 0.9.44.6 update · Issue #1054 · netblue30/f...
 Recently something broke audio when using firejail under pulseaudio. When playing video with mpv: [ao/pulse] In...  |   |

  |

  |

 
I have just downloaded, compiled and tested 0.9.44.4 and I have no sound with that version either. That is with PulseAudio 10.0.
 

    On Friday, 28 April 2017, 6:34, SYN-cook <notifications@github.com> wrote:
 

 It is probably a stupid question, but only to be sure there is no misunderstanding: Is your Firefox also constrained by Apparmor, like in #1175?
That is, did you write apparmor into your Firejail profile or does running aa-status as superuser show an enforced Firefox profile?—

**Comment by netblue30** [comment]
@360asm - grab the latest 0.9.44.10, 0.9.44.6 was badly broken.

Got PCLinuxOS installed. I couldn't get the sound working even when running programs without firejail - for example vlc or firefox. I start Application/Sound/PulseAudio Volume Control, and I can see the meter moving for vlc and firefox streams, but nothing goes out on the speaker.

There is definitely a sound problem with firejail 0.9.46~rc1 and also with the version in git, I'll bring a fix in. 0.9.44.10 should be fine if I manage to get sound stream past PulseAudio Volume Control.
