### ISSUE TITLE
default bind mounts and noexec option

### ISSUE THREAD

**Issue by SYN-cook** [netblue30/firejail#1238]
`noexec /tmp` and `noexec ${HOME}` don't necessarily block execution completely, I see few folders still allowing it:
- ~/.config/pulse
- /tmp/.X11-unix
- ~/.local/share

Since noexec options are being used in profiles, it would be nice to close loopholes for the standard configuration.

~/.local/share can be easily handled in disable-common.inc. And the .X11-unix and pulse folders should be also safe for remounting with a noexec flag.

**Comment by SpotComms** [comment]
Why does 'noexec ${HOME}' not apply to ~/.local/share? Also this will break a few profiles such as Steam, which stores itself there.

**Comment by SYN-cook** [comment]
@SpotComms Did you try running e.g. `findmnt` inside the jail? It would be interesting if you can't reproduce it, I have seen it on different systems.

If besides Steam more programs install themselves to ~/.local/_share_, maybe an alternative implementation could be to tie all remounting works to the noexec options, instead of remounting the folders noexec from the beginning.

**Comment by SpotComms** [comment]
You are correct, I was just wondering why 'noexec ${HOME}' doesn't apply recursively as I assumed it did.

**Comment by SYN-cook** [comment]
@SpotComms On my current setup (I'm on a trip and unfortunately can't try many things), the noexec option is enforced recursively, except for those three folders mentioned in the first comment.... e.g. I go to a random subfolder and try to run an executable, I am told I don't have permissions to do so.

Is it possible for you to execute programs/scripts in subfolders?

**Comment by SpotComms** [comment]
@SYN-cook Okay so while 'findmnt' only shows the 'noexec' option for /home/user and not for any subdirectories, however I cannot execute under ~, ~/.config. I can however execute under ~/.local/share. So yes you are again correct. I created #1242 as an alternative solution.

**Comment by SYN-cook** [comment]
:+1: Cool! So let's see what netblue30 says

**Comment by netblue30** [comment]
I'll play a little bit with noexec on ~/.config/pulse and /tmp/.X11-unix and put them disable-common.inc.
