### ISSUE TITLE
Thunderbird and OpenPGP

### ISSUE THREAD

**Issue by 0nse** [netblue30/firejail#124]
`disable-secret.inc` disables `${HOME}/.gnupg` which is fine for most applications. However, I would whitelist the directory for Thunderbird because mailing is probably one of the most important usecases for GPG. Otherwise, Engimail won't find any keys to sign, encrypt, decrypt and verify signatures.

**Comment by nailarch** [comment]
Same problem with Firefox and ~/Downloads directory.
I had to add "whitelist ~/Downloads" to firefox.profile.

And what about priorities and differences between noblacklist and whitelist options ?

**Comment by netblue30** [comment]
Fixed both Загрузки and .gnupg. Thanks!

Whitelist is applied first - it will mount a tmpfs on your home directory and bring in (mount-bind) only the directories whitelisted.

Then, blacklists are applied. noblacklist disables blacklist statements.

**Comment by Micha-Btz** [comment]
hm, for me it is not working. i have the release 0.9.34 from debian tree and added 
noblacklist ${HOME}/.gnupg
to the thunderbird profile, but firejail disable it anyway.
Disable /home/mdomann/.gnupg
the strange thing is, if i whitelistet it my icedove profil folder is empty, it will create new profiles fpor mail and so on.

**Comment by netblue30** [comment]
You have to add "noblacklist" before "include":
`````
# Firejail profile for Mozilla Thunderbird (Icedove in Debian)
noblacklist ${HOME}/.gnupg
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-devel.inc
`````

This is how it works on the latest version in git:
`````
$ firejail --profile=/etc/firejail/icedove.profile 
Reading profile /etc/firejail/icedove.profile
Reading profile /etc/firejail/thunderbird.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-devel.inc
Parent pid 29473, child pid 29474
Child process initialized
$ ls -l ~/.gnupg
total 36
-rw------- 1 netblue netblue 9188 Nov  5  2014 gpg.conf
-rw------- 1 netblue netblue 1203 Nov  5  2014 pubring.gpg
-rw------- 1 netblue netblue 1203 Nov  5  2014 pubring.gpg~
-rw------- 1 netblue netblue  600 Nov  8 10:06 random_seed
-rw-r--r-- 1 netblue netblue  938 Nov  5  2014 revocation
-rw------- 1 netblue netblue 2581 Nov  5  2014 secring.gpg
-rw------- 1 netblue netblue 1280 Nov  5  2014 trustdb.gpg
$
`````

**Comment by Micha-Btz** [comment]
ok, this way it works. thanks
