### ISSUE TITLE
Firejail and Steam Games

### ISSUE THREAD

**Issue by Alexey2532** [netblue30/firejail#1240]
Hey,
i was trying to run 2 games via 2 different firejails. i got Steam to run twice with the comment
` firejail --noprofile steam`. this worked twice so far and i could have logged in with 2 different accounts.
The probelm is, if i start a the game on one, i can't get it run on another, i get the error 

> You can run only one instance at a time 

This won't let me start the game a second time.
I think the sulution would be to Isolate the game procces or firejail itself. But the Question is, how?
Do you have any idea?

regards,
Alexey

**Comment by reinerh** [comment]
You need to find out how they detect already running instances.
So perhaps you need to block certain protocols like netlink or unix sockets, or use private directories or blacklist certain directories/files. :)
Also you mentioned to run with --noprofile, which doesn't really isolate your processes.

**Comment by daniel11609** [comment]
How can I tell firejail to open a new sandbox... If I run the command firejail steam again it's not opening new instance.

**Comment by daniel11609** [comment]
OK probably just run it in new terminal but I have almost same problem, game already running

**Comment by netblue30** [comment]
I think is the game doing it. As soon as you start the second instance, it detects another instance of the game running and is shutting down.

**Comment by daniel11609** [comment]
Hey netblue... 
Could you tell me how I can start even steam multiple times? Because using firejail steam doesn't seem to work. Only once... 


Am 26. April 2017 13:56:03 MESZ schrieb netblue30 <notifications@github.com>:

**Comment by netblue30** [comment]
Try this: open /etc/firejail/steam.profile in a text editor and comment out all the lines in that file (add a # in front of each line), then try to start two instances of steam. If it works, it means one of the lines there is creating the problem - my guess would be private-tmp.

**Comment by daniel11609** [comment]
# Steam profile (applies to games/apps launched from Steam as well)
#noblacklist ${HOME}/.steam
#noblacklist ${HOME}/.local/share/steam
#include /etc/firejail/disable-mgmt.inc
#include /etc/firejail/disable-secret.inc
#include /etc/firejail/disable-common.inc
#include /etc/firejail/disable-devel.inc
#caps.drop all
#netfilter
#noroot
#seccomp
#protocol unix,inet,inet6


i open up a need terminal and do firejail steam. First time everythings fine, second time im getting this:
$ firejail steam
Reading profile /etc/firejail/steam.profile
Parent pid 5606, child pid 5607

Child process initialized
rm: cannot remove ‘/home/daniel/.steam/steam’: Is a directory
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically

parent is shutting down, bye...
$

**Comment by daniel11609** [comment]
and yea the game checks it after launch a message pops up:
Source - error:
only one instance can run at a time

**Comment by netblue30** [comment]
So I can close it, right?

**Comment by daniel11609** [comment]
But it doesn't work? 

Am 26. April 2017 18:01:58 MESZ schrieb netblue30 <notifications@github.com>:

**Comment by daniel11609** [comment]
It doesn't work? 

Am 26. April 2017 18:01:58 MESZ schrieb netblue30 <notifications@github.com>:
