### ISSUE TITLE
Despite firejail workin on firefox I can acces all files on my hard disk from the browser

### ISSUE THREAD

**Issue by escapeplan4** [netblue30/firejail#1241]
All of the sudden my firejail stopped working as a sandbox for firefox and I can download files from firefox and save it all over the hard drive not only on Download directory on linux mint. I open firefox with default firejail firefox %u

**Comment by reinerh** [comment]
Was there perhaps an (unjailed) firefox already running? Can you please check your process list before you start firefox in firejail?

**Comment by netblue30** [comment]
Also see this: https://firejail.wordpress.com/support/frequently-asked-questions/#firefox

**Comment by Hund** [comment]
I have the same issue with Pale Moon (old fork of Firefox). I've double checked that there's no processes in the background.

**Comment by Hund** [comment]
I just noticed that it is only my remote storage (mounted via sshfs) that I'm able to access, not my local filesystem.

**Comment by netblue30** [comment]
@Hund - Where do you keep your remote storage mounted? Is it in your home directory? Maybe our whitelist/blacklist leaves sshfs filesystems in?

**Comment by Hund** [comment]
In `/media`.

**Comment by netblue30** [comment]
@Hund - blacklist /media: run "firejail --blacklist=/media program-name". You can also add it in a profile file.

**Comment by Hund** [comment]
Sorry, I was wrong. Pale Moon can access everything in `/`.

**Comment by netblue30** [comment]
Yes it can. This is where the filesystem is, including Pale Moon executables. Anyway, most directories are mounted read-only.
