### ISSUE TITLE
Using --trace to generate initial profiles

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#1244]
Petter Reinholdtsen had the idea on the [Debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860942#15) to use the output from the --trace command to generate initial/draft profiles, because it already reports if an application tries to open a file or create a socket.
Maybe an additional tool could parse the trace output and generate a profile out of it.

**Comment by netblue30** [comment]
> Btw, it might be a good idea to add the --trace usage to the EXAMPLES section in the firejail(1) manual page.  If it had been there, I might have used it instead of creating this BTS report. :)

I'll add and example in the man page. We'll build an "autoprofiler", at least something to create a starting point for building a profile.

**Comment by chiraag-nataraj** [comment]
We have the `--build` command-line argument now, so closing this.
