### ISSUE TITLE
Typo in user instructions in some profile files

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#1249]
Hi, there's a typo in some of the profile files.

The bad:
 `# depending on you usage, you can enable some of the commands below:`

The good:
 `# depending on your usage, you can enable some of the commands below:`

Affected files:

* /etc/firejail/akregator.profile
* /etc/firejail/default.profile
* /etc/firejail/dia.profile
* /etc/firejail/fontforge.profile
* /etc/firejail/geany.profile
* /etc/firejail/globaltime.profile
* /etc/firejail/hugin.profile
* /etc/firejail/kcalc.profile
* /etc/firejail/kino.profile
* /etc/firejail/ktorrent.profile
* /etc/firejail/orage.profile
* /etc/firejail/pcmanfm.profile
* /etc/firejail/ristretto.profile
* /etc/firejail/Thunar.profile
* /etc/firejail/xfce4-dict.profile
* /etc/firejail/xfce4-notes.profile

**Comment by Fred-Barclay** [comment]
Fixed, thanks! 😄
