### ISSUE TITLE
Question regarding whitelisting a specific file inside a blacklisted directory.

### ISSUE THREAD

**Issue by throwaway217** [netblue30/firejail#1250]
Is there any way I can specifically whitelist a file inside a blacklisted directory ?
Like for example say I have folder A and file B.
When a program is launched it creates folder A and a bunch of stuff inside it along side B.
Is it possible to make it so that the program can only write, modify and read only the B file and nothing else inside A ?

**Comment by SYN-cook** [comment]
What you could try in a profile:
1. Ensure A and B exist:
```
mkdir A
mkfile A/B
```

2. Don't allow anything new in A:
```
read-only A
read-write A/B
```

3. If A exists and is not empty (e.g. from a previous run), blacklist everything except B:
```
noblacklist A/B
blacklist A/*
```

The question is if your program still runs then.

**Comment by throwaway217** [comment]
It doesn't seem to run but I got the gist of your thought process. I'll make it work.

**Comment by throwaway217** [comment]
How would I go about this if the programs insists on creating the file itself. ?
