### ISSUE TITLE
How do I allow qutebrowser to access its external editor (URxvt with Vim)?

### ISSUE THREAD

**Issue by Hund** [netblue30/firejail#1257]
How do I allow qutebrowser to access its external editor (URxvt with Vim)? Is it possible?

**Comment by cryzed** [comment]
Unless you are using some custom profile accessing/executing other executables should "just work". What is the problem exactly?

**Comment by Hund** [comment]
With qutebrowser you can either just input text in the inputbox, but you can also launch your favourite editor and edit the text there. And when you save and exit the editor, the text get put here.

But when I try to launch my editor I only get the error message `Editor exited with status  127.` in qutebrowser. Which I guess is because the browser is not allowed to execute the binary file URxvt?

**Comment by SYN-cook** [comment]
Could you try to run qutebrowser with the options `--noblacklist=${PATH}/urxvtc` and/or 
`--noblacklist=${PATH}/urxvtcd` and let us know if it worked?

**Comment by Hund** [comment]
That didn't work.

```
14:49:00 ERROR: Editor exited with status 127.
14:49:00 ERROR: Process stderr:
urxvt: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
```

**Comment by SYN-cook** [comment]
Ok, I am sorry, but that output is helpful indeed. Could you then try the following?
```
mkdir ~/.config/firejail
cp /etc/firejail/qutebrowser.profile ~/.config/firejail
```
and in ~/.config/firejail/qutebrowser.profile you comment out `include /etc/firejail/disable-devel.inc`. If that is not enough to get everything running, you can insert at the beginning of the file:
```
noblacklist=${PATH}/urxvtc
noblacklist=${PATH}/urxvtcd
```

**Comment by Hund** [comment]
It works with commenting that line out. :)

**Comment by Hund** [comment]
I just noticed that I can't use aspell via Vim when I launch Vim via qutebrowser. :/

**Comment by SYN-cook** [comment]
You could go back to ~/.config/firejail/qutebrowser.profile and append `whitelist ~/.vimrc` (or whatever the path to your vimrc is) at the end, assuming you have set up automatic spell checking through this file. 

If that does not work, however, I guess it will be best to open a new issue here.

**Comment by Hund** [comment]
That worked! Didn't think of that. :)

**Comment by Hi-Angel** [comment]
So, how do I run an external editor anyway? E.g. in pentadactyl it's <kbd>Control</kbd>-<kbd>i</kbd> for **Insert** mode.

This thread is the first result on Google, and the rest results are also issues, so I suspect it's an undocumented hotkey, yet everyone here seem to know it…

**Comment by Hi-Angel** [comment]
Yay, I occasionally found it [on this page](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc). The hotkey is <kbd>Ctrl</kbd>-<kbd>e</kbd>. Dunno why isn't this page in Google results.
