### ISSUE TITLE
mpv profile not working with if creating /usr/local/bin/mpv wrapper

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#1259]
If I run the command `/usr/bin/firejail --seccomp --profile="${HOME}"/.config/firejail/mpv.profile /usr/bin/mpv <a_video>`, it works. Then, I create the wrapper for /usr/local/bin so calling any instances of `mpv` uses the firejail sandbox automatically:

    #!/usr/local/env sh
    /usr/bin/firejail --seccomp --profile="${HOME}"/.config/firejail/mpv.profile /usr/bin/mpv "$@"

I open a new shell instance and run mpv and it fails to open the video, failing with the following:

```
Reading profile /home/rieje/.config/firejail/mpv.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Warning: user namespaces not available in the current kernel.
Parent pid 22947, child pid 22948
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized
Parent is shutting down, bye...

```

Any ideas what may be the issue? I did the same thing with firefox and it works fine. Seems bizarre that command in the wrapper script does not work but works if I execute it directly on the terminal.

**Comment by netblue30** [comment]
If you have a "private-bin" statement in your profile, comment it out (add a #).

The recommended way to set this up is to use firecfg. Delete your mpv script from /usr/local/bin and run:
`````
$ sudo firecfg
`````
It will create a symbolic link to /usr/bin/firejail and everything will work just fine.
