### ISSUE TITLE
Firejail profile for eye of gnome breaks steam screenshots images

### ISSUE THREAD

**Issue by ekaris** [netblue30/firejail#1267]
Firejail profile for eye of gnome breaks steam screenshots images taken from games and stored in ~/.steam/steam/userdata/

**Comment by Fred-Barclay** [comment]
Thanks for the report! I've added a commit that should fix this. Can you try copying https://raw.githubusercontent.com/netblue30/firejail/ba0e6f5dd6ac18d8a564227a7263f42537c879ee/etc/eog.profile to ~./config/firejail/eog.profile and seeing if you can use eye of gnome to view the screenshots now?

**Comment by ekaris** [comment]
Hi, it doesn't work, the steam screen shots are saved on different folders like ~./ steam/steam/userdata/137833111/760/remote/203160/screenshots
The numbers can change

**Comment by Fred-Barclay** [comment]
Sorry, I had some mistakes in that commit. Can you try this again? https://raw.githubusercontent.com/netblue30/firejail/6262b3078ce98154a14b1481f71fe378c2dc886b/etc/eog.profile

Thanks!

**Comment by ekaris** [comment]
It works now! Thanks

**Comment by Fred-Barclay** [comment]
Awesome! 🎉 
Take care,
Fred
