### ISSUE TITLE
After using firecfg there are lot's of GIMP errors when launching it

### ISSUE THREAD

**Issue by ekaris** [netblue30/firejail#1268]
Here are some:

Failed to open file “/home/biohazard/.gimp-2.8/devicerc”: open() failed: Permissão negada

Failed to open file “/home/biohazard/.gimp-2.8/controllerrc”: open() failed: Permissão negada

Impossível abrir um ficheiro swap de teste. 

Para evitar a perda de dados, verifique a localização e permissões da pasta de swap definida nas suas Preferências (atualmente "/home/ekari/.gimp-2.8").

As mensagens são redirecionadas para stderr.

**Comment by SYN-cook** [comment]
Can you please run
```
mkdir ~/.config/firejail
cp /etc/firejail/gimp.profile ~/.config/firejail
```
and then in ~/.config/firejail/gimp.profile you comment out `ipc-namespace`?

**Comment by ekaris** [comment]
Ownership is good

**Comment by netblue30** [comment]
You might be running into this problem: https://bugs.launchpad.net/ubuntu/+source/gimp/+bug/1246908

I would delete ~/.gimp-2.8 directory and start all over again - unless you have some plugins you installed in that directory.

**Comment by SYN-cook** [comment]
Alternatively, to figure out how is the link with Firejail, you could try to run from the command line simply `/usr/bin/gimp`, and if that works ok try `firejail --noprofile gimp`.

**Comment by ekaris** [comment]
@SYN-cook I followed your commands by order after deleting .gimp and no errors where shown.
@netblue30 Maybe that is the bug, I'm using ubuntu 17.04 but I saw the directory and it was not owned by root

**Comment by SYN-cook** [comment]
Thanks. But you are still running into this issue when launching from a menu? One reason could be that Firejail picks the wrong profile. What you could try
```
mkdir ~/.config/firejail
cp /etc/firejail/gimp.profile ~/.config/firejail/gimp-2.8.profile
```

**Comment by netblue30** [comment]
@SYN-cook is right, it will pick up /etc/firejail/default.profile - this one disables ~/.config/gimp* directories. I put a fix in mainline. Thanks for the bug.
