### ISSUE TITLE
Can't run firefox with firejail outside of /usr/bin

### ISSUE THREAD

**Issue by Isometries** [netblue30/firejail#1272]
My firefox directory is in `/home` and firejail is unable to run it. It outputs:

`bin/bash: /home/user/firefox/firefox: No such file or directory`
The problem is resolved if I put my entire firefox directory into `/usr/bin`, but that prevents self-updating. Placing only the firefox binary gives a XPCOM error.

**Comment by netblue30** [comment]
In /etc/firejail/firefox.profile add a "whitelist ~/firefox" line at the end of the file. Also, if you have in your profile a "noexec ${HOME}", comment it out (add a # in front of the line).

**Comment by Isometries** [comment]
That worked out just fine, although it didn't want to work if I hid the directory by `~/.firefox`. It's alright though, thanks for the simple fix.
