### ISSUE TITLE
cannot find group id

### ISSUE THREAD

**Issue by illenium69** [netblue30/firejail#1273]
firejail --private=steam_one
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 1222, child pid 1223

Child process initialized
groups: cannot find name for group ID 65534

i followed this tutorial http://bit.ly/2puZQ9l
im trying to sandbox steam

**Comment by netblue30** [comment]
Run "firejail --debug --private=steam_one" and put the output here. Also, what distro and what version of firejail are you running?
