### ISSUE TITLE
(firefox:5): dconf-CRITICAL

### ISSUE THREAD

**Issue by xdpFrank** [netblue30/firejail#1274]
firejail firefox   works

firejail --overlay firefox    does not work

mint@mint-i5-intel ~ $ firejail --overlay firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Warning: --overlay and --noroot are mutually exclusive, noroot disabled
Parent pid 1949, child pid 1950
OverlayFS configured in /home/mint/.firejail/1949 directory
Blacklist violations are logged to syslog
Warning: failed to unmount /sys

Child process initialized

(firefox:5): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

Info System:
Kernel: 4.4.0-53-generic i686 (32 bit gcc: 5.4.0)
Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.3)
Distro: Linux Mint 18.1 Serena
firejail 0.9.38.10-0ubuntu0.16.04.1

**Comment by netblue30** [comment]
On a Cinnamon Mint 18.1 here, I don't have the problem you mention when I run "firejail --overlay firefox".

/run/user/1000/dconf is the configuration directory for GTK. As soon as Cinnamon starts, the directory should be created. I wouldn't worry too much about it. It has no impact on your browsing, security, or anything else.

**Comment by xdpFrank** [comment]
Thank you for your message.
Problem is Firefox does not enter the internet (Server not found)

" firejail firefox " I have these problems do not.

[firejail debug.txt](https://github.com/netblue30/firejail/files/999208/firejail.debug.txt)

**Comment by chiraag-nataraj** [comment]
@xdpFrank:
1. Do you still have this problem?
2. I know I've had issues before with disabling `noroot` in the firefox profile (as well as a bunch of others). Since `overlay` disables `noroot`, that might be causing this problem (if you still have it).

**Comment by xdpFrank** [comment]
Thanks su much for the answer.
I do not have the problem anymore.
