### ISSUE TITLE
Startup given processes automatically in firejail

### ISSUE THREAD

**Issue by manushanga** [netblue30/firejail#1275]
I made a pre-loadable library to get the job done.
https://github.com/manushanga/FirejailLoader

PS: mark as enhancement

**Comment by netblue30** [comment]
It is quite interesting, it can replace our symlinks in /usr/local/bin - but I need it under GPL v2. The easiest thing would be for you to create a pull request on firejail, just create a src/floader directory and dump all the files there. I'll integrate it in the main makefile/install/man pages etc. Thanks.

**Comment by manushanga** [comment]
Cool! I'll change the licensing so that it is compatible with firejail's

**Comment by netblue30** [comment]
All merged, I'll start integrating it.
