### ISSUE TITLE
0.9.46 Breaks Profile Links

### ISSUE THREAD

**Issue by pigmonkey** [netblue30/firejail#1276]
After upgrading to 0.9.46, I can no longer use symbolic links to profiles.

For example, I can create a simple profile. This works fine:

```
$ mkdir ~/tmp/firejail
$ cd ~/tmp/firejail
$ echo "include /etc/firejail/disable-common.inc" > test.profile
$ firejail --profile=/home/pigmonkey/tmp/firejail/link.profile bash
Reading profile /home/pigmonkey/tmp/firejail/test.profile
Reading profile /etc/firejail/disable-common.inc
Parent pid 20256, child pid 20258
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 50.43 ms
[pigmonkey@nous firejail]$
```

But as soon as I create a link to the same profile, it fails:

```
$ ln -s ~/tmp/firejail/test.profile ~/tmp/firejail/link.profile
$ firejail --profile=/home/pigmonkey/tmp/firejail/link.profile bash
Error: invalid profile file
```

I have a number of customized profiles in `~/.config/firejail`. However, these are all links to the profiles in my dotfiles repository. All of them are now broken. Everything worked fine in 0.9.44.10.

**Comment by startx2017** [comment]
fixed

**Comment by pigmonkey** [comment]
Thanks. I hope we can get 0.9.46.1 tagged soon.
