### ISSUE TITLE
Whitelisting symbolic links whitelists the source file but not the symlink

### ISSUE THREAD

**Issue by 0nse** [netblue30/firejail#128]
I'm currently running Firejail 0.9.34 from the [AUR](https://aur4.archlinux.org/packages/firejail/). Whenever there is a `whitelist` entry in a profile, the program will basically not be able to access anything.

For  example, Firefox will load with the default GTK theme and not have access to my vimperator configuration, when there is *any* whitelist entry. This sounds reasonable at first, but adding the relevant files—which is now done in the upstream configuration— does not change this behaviour (`~/.vimperator`, `~/.vimperatorrc`, `~/.gtkrc-2.0`, `~/..config/gtk-3.0/settings.ini`). When navigating in Firefox browsing my local disk using `file:///`, I see the file names but cannot access them.

This happens for all programs I have tested so far: Firefox, Chromium and Pidgin. The browsers are still able to load their profiles, probably because these folders  are added as `noblacklist`.

**Comment by netblue30** [comment]
I keep on the main page of the project here on github the current whitelist for Firefox. Only these files/directories are visible in your /home/user directory.

.config/gtk-03 directory was added yesterday in the development version.

Files and dirs in the rest of the system are still visible, most of them are read-only, other are empty files and cannot be opened (blacklist).

**Comment by 0nse** [comment]
Regarding GTK3: Yes, that's correct and I am aware of that. I had manipulated the profile files myself to whitelist it. However, entries that I have put on whitelist (or that already have been, like `~/.vimperatorrc`) are not accessible in Firefox. They are missing in `file:///` and only if I remove _all_ whitelist entries, they become readable again.

I get and like the idea of mounting a new home with fewer contents. But whitelisting anything will not lead to those entries appearing in my program-specific new home directory.

**Comment by netblue30** [comment]
OK, that's a bug, I'll have to fix it, thanks.

**Comment by netblue30** [comment]
Fixed.

**Comment by 0nse** [comment]
I experience this behaviour again in  0.9.38.

**Comment by netblue30** [comment]
What are you trying to do?

**Comment by 0nse** [comment]
I found that I have to whitelist a parent directory in my home directory in which the files are located whose symlinks are whitelisted by the default config. Imagine the following symlink:
```
~/.gtkrc-2.0 -> ~/dotfiles/gtk/.gtkrc-2.0
```
If I don't whitelist `~/dotfiles`, `~/.gtkrc-2.0` cannot be read.

On a sidenote: when that happens, Firefox often removes all contents from that file while starting. Anyways, I could solve my own problem and thus close this ticket. Thanks!
