### ISSUE TITLE
[firecfg 0.9.46] non-admin users can't fix their desktop files

### ISSUE THREAD

**Issue by xenopeek** [netblue30/firejail#1281]
With firecfg 0.9.46 the `--fix` option has been removed. This causes problems for any non-admin user accounts. They can no longer fix their desktop files because firecfg now requires sudo.

When running `sudo firecfg` it creates both the links in /usr/local/bin/ and fixes the desktop files _for the current user account_. For non-admin user accounts `firecfg --fix` could be used in the past to also fix their desktop files. When running firecfg without sudo it replies:

```
Error: cannot set the symbolic links in /usr/local/bin
The proper way to run this command is "sudo firecfg".
```

How then are non-admin user accounts supposed to fix their desktop files?

**Comment by netblue30** [comment]
You are right, we will have to bring it back.

**Comment by netblue30** [comment]
Fixed!
