### ISSUE TITLE
Unable to create a profile containing "overlay-tmpfs"

### ISSUE THREAD

**Issue by jjwo** [netblue30/firejail#1285]
When I create a profile containing `overlay-tmpfs` and then run `firejail application` firejail displays `Error: line 1 in /home/name/.config/firejail/application.profile is invalid` then exits.

However, when I run `firejail --overlay-tmpfs application` without a profile everything works as expected.

I'm running firejail version 0.9.44.8 on Ubuntu 17.04.

**Comment by Fred-Barclay** [comment]
Hi @jjwo 
Can you post the profile you're trying to use?

Also, firejail 0.9.46 has been released (with lots of improvements). If possible, could you upgrade to that?

Thanks!
Fred

**Comment by jjwo** [comment]
Hi @Fred-Barclay
Thanks for your reply. I'm not able to upgrade right now but the release notes suggest that the problem has been fixed in version 0.9.46.
