### ISSUE TITLE
private-dev for firefox/chrome

### ISSUE THREAD

**Issue by msva** [netblue30/firejail#1286]
I noticed, you've removed private-dev from firefox and chromium profiles, with a message that it prevents video calls.

Isn't it only because of `/dev/video[0-9]*` is not present there?
If so, I guess, it can be solved by implementing wildcard whitelisting and adding it in the default profiles. Doesn't it? 😸

**Comment by netblue30** [comment]
I added support for /dev/video* inside private-dev, uncommented private-dev in firefox and chromium profiles.

**Comment by Fred-Barclay** [comment]
@netblue30 Is there still a way to disable video devices inside profiles?

**Comment by msva** [comment]
> @netblue30 Is there still a way to disable video devices inside profiles?

blacklist /dev/videoN in "custom" profile (/etc/firejail/firefox.local or 
~/.config/firejail/firefox)?

// Or does @netblue30 implemented wildcard/regexp in white/blacklist params 
already?

**Comment by Fred-Barclay** [comment]
@msva That would work but I'm not crazy about having to explicitly blacklist video devices in all my profiles that currently have private-dev. 😉 

@netblue30 Would it be possible/wanted to keep the old behavior of private-dev (no video devices) with a new flag? Something like `--private-dev-all`? Or perhaps `--no-video` like the existing `--no-sound`? I could *try* to code it in myself it's something you wouldn't mind having.

**Comment by msva** [comment]
> @netblue30 Would it be possible/wanted to keep the old behavior of
> private-dev (no video devices) with a new flag? Something like
> `--private-dev-all`? Or perhaps `--no-video` like the existing
> `--no-sound`? I could *try* to code it in myself it's something you
> wouldn't mind having.

Actually, I think, it'd be nicer to make private-dev to support lists like 
private-bin and private-etc.
In that case, default behaviour (with no list) would work as before, and for 
the cases where you need exact list of devices you'd be able to specify exact 
list.

Although, I guess, it's anyway possible with whitelist atm

// although, AFAIK, whitelist still does not support wildcards/regexp :'(

**Comment by SYN-cook** [comment]
Being able to prevent software from accessing a webcam seems quite useful. It might even serve as an alternative to taping webcams on notebooks.

**Comment by Fred-Barclay** [comment]
@SYN-cook I've got a working `--novideo` flag. 🎉 I'll test it some more and if it's still working I'll open a PR for it to be reviewed (my C is abysmal so it needs reviewing by someone much more experienced be 😁 )

**Comment by msva** [comment]
> It might even serve as an alternative to taping webcams on notebooks.

Actually, firejail doesn't save you from trojan horses in firmwares (cpu, 
intel's apus (skylake+ needs blob firmware to work properly), bios, whatever).

But, yes, I having idea to combine firejail and, say, mobile OSes for a very 
long time already :)
