### ISSUE TITLE
Firefox crashes with ipc-namespace (or something related)

### ISSUE THREAD

**Issue by msva** [netblue30/firejail#1287]
Unfortunatelly, I've found, that after updating firejail yesterday my firefox started to crash on random events like calling context menu (RMB), moving backwards in history (`Alt`+`⇐`).
A bit of debugging showed that if I comment out `ipc-namespace` crashes disappears.
Also I've noticed, that previously (at the point where all worked) I was using firejail at the state of a1dde3456c4f249202ec9311590526e88a77c42b, but as I see, ipc-namespace was added in the profile in 4f238b75de05d91f200305335da1f019810ac149 (half-a-month before even that), so, I'm bit surprised, how can it brake anything.

Moreover, the commits after a1dde345 looks like unrelated (regarding to commit messages) to the problem.
Maybe, it is some newly introduced feature in the code, and maybe it is somehow related to some updated system libraries.

Anyway, as I said, disabling `ipc-namespace` solves the crashes, and uncommenting it back - also returns crashes.

I'd like to debug it more properly if you'll help me with directions :)

P.S. Firefox's crash looks like that:
```
(firefox:8): Gdk-ERROR **: The program 'firefox' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 4854 error_code 2 request_code 130 (unknown) minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Parent is shutting down, bye...
```

**Comment by SpotComms** [comment]
My apologies, this is the third program that I've added ipc-namespace thats causing issues. Its weird though because I've not actually been able to reproduce any of these issues. @netblue30 can you shed any light as to why ipc-namespace would work for some and not others?

**Comment by msva** [comment]
Moreover, as I said, it worked even on my host, until yesterday's system update (a part of which was firejail update) :)

**Comment by netblue30** [comment]
Fixed - commented out ipc-namespaces.
