### ISSUE TITLE
firejail doesn't exit automatically when running firefox

### ISSUE THREAD

**Issue by zanculmarktum** [netblue30/firejail#1289]
I have `browser.showQuitWarning` set to `true` in `about:config`.

The issue occured when I close firefox when it has more than one tab opened, and then firefox will ask `Do you want Firefox to save your tabs for the next time it starts?`, I clicked `Save and Quit`.

The output of `pgrep -ai fire`:

> 3216 firejail firefox -offline
> 3220 firejail firefox -offline
> 3225 firefox -offline

and then it becomes:
>3216 firejail firefox -offline
>3220 firejail firefox -offline

The firejail process keeps remain in the background and I had to `kill 3216 3220` it, or else it will conflicts with other sandboxed process.

**Comment by netblue30** [comment]
I cannot reproduce it here. Instead of pgrep, can you please run in another terminal "firejail --tree". It will tell us what process is keeping the sandbox open.

**Comment by Anyon3** [comment]
I reproduced this bug 

Firejail doesn't exit automatically when machine-id is used, removing it make the sandbox exit

**Comment by Anyon3** [comment]
Here the log when I quit Firefox, I need to ctrl + c to make firejail exit (see the  ^C in the log) Hope it's help

http://paste.geeknode.org/?bf9a746f7ceca236#OABMyAe0hiegkytXCGdKy0ovSSWTez/p7wnq5de4+M8=

**Comment by netblue30** [comment]
There are other things not working when machine-id is used, among them PulseAudio. I know Firefox uses machine-id to synchronize bookmarks among other things. I'll close the bug it for now.
