### ISSUE TITLE
Provided clementine profile causes library scanning to fail

### ISSUE THREAD

**Issue by Kishore96in** [netblue30/firejail#1292]
The currently included profile for clementine has the following option
```
seccomp
```

The inclusion of this option causes clementine to fail while attempting to scan a music library (scanning is stuck at 0%). Removal of this line allows clementine to scan folders successfully.

**Comment by SYN-cook** [comment]
If I am not mistaken it is ioprio_set which causes the trouble. Can you try replacing `seccomp` with the following long line:

`seccomp.drop mount,umount2,ptrace,kexec_load,kexec_file_load,name_to_handle_at,open_by_handle_at,create_module,init_module,finit_module,delete_module,iopl,ioperm,swapon,swapoff,syslog,process_vm_readv,process_vm_writev,sysfs,_sysctl,adjtimex,clock_adjtime,lookup_dcookie,perf_event_open,fanotify_init,kcmp,add_key,request_key,keyctl,uselib,acct,modify_ldt,pivot_root,io_setup,io_destroy,io_getevents,io_submit,io_cancel,remap_file_pages,mbind,get_mempolicy,set_mempolicy,migrate_pages,move_pages,vmsplice,chroot,tuxcall,reboot,mfsservctl,get_kernel_syms,bpf,clock_settime,personality,process_vm_writev,query_module,settimeofday,stime,umount,userfaultfd,ustat,vm86,vm86old`

**Comment by Kishore96in** [comment]
Can confirm that the above replacement works.

**Comment by Fred-Barclay** [comment]
Thanks for the resport @Kishore96in and for the fix @SYN-cook. It's all merged in now.
