### ISSUE TITLE
Seamonkey fails  

### ISSUE THREAD

**Issue by nyancat18** [netblue30/firejail#1294]
firejail seamonkey
Reading profile /etc/firejail/seamonkey.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Warning: noroot option is not available
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 32474, child pid 32475
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 187.02 ms

Parent is shutting down, bye...

it opens me   a profile manager (seamonkey cant read its    directory)

**Comment by netblue30** [comment]
Probably they changed the place where they keep the configuration.  They used to have it in ~/.mozilla/seamonkey. What version of Seamonkey are you using?

**Comment by nyancat18** [comment]
2.46-3 [installed]

**Comment by netblue30** [comment]
I've found some problems with the profile files and put a fix on mainline. Give it a try, thanks.

**Comment by nyancat18** [comment]
ok
