### ISSUE TITLE
ssh fails when used with Kerberos

### ISSUE THREAD

**Issue by uzytkownik** [netblue30/firejail#1299]
Using ssh fails when using Kerberos login - at least with in-kernel keyring.

**Comment by netblue30** [comment]
Seccomp filter disables all kernel keyring accesses. I would disable seccomp in your case - comment out "seccomp" line in /etc/firejail/ssh.profile. Anyway, the sandbox protects only ssh process on your machine, what happens inside the session on the remote machine is not protected.

**Comment by rusty-snake** [comment]
@uzytkownik I'm closing here due to inactivity, please fell free to reopen if you have more questions.
