### ISSUE TITLE
Using private command doesn't use '.local's, uses main profile.

### ISSUE THREAD

**Issue by snrgabe** [netblue30/firejail#1303]
I'm going to try and explain the best I can, sorry if I confuse you.

I'm trying to get multiple instances of a game running but whenever I attempt to use FireJail as an alternative, I'm hit with 'only run once instance at a time' error. As I know, this isn't FireJail's fault but I'm just trying to explain my issue.

I have a username `gabriel` and I installed steam in the `/home/gabriel/.local/` yada yada, and I'm trying to get it to use a `--private=steam_2`. There is a folder called `steam_2` where I installed steam inside which created it's own `/steam_2/.local/Steam` yada yada, but it's installing the game into `/home/gabriel/.local/`.

Is this an issue with my Steam setup or am I misinterpreting what the `--private` command does?

Command used: `firejail --private=steam_2` 
No errors are returned.

**EDIT:** After some debugging, it's come down to that whenever I use the `--private` command, it isn't enforcing the given direct as it's `${HOME}`. For example, if I use the command `firejail --private=steam_jail` and then use the command, `echo ${HOME}`, it'll return `/home/gabriel` and not `/home/gabriel/steam_jail`. Am I doing something wrong?

**Comment by netblue30** [comment]
> if I use the command firejail --private=steam_jail and then use the command, echo ${HOME}, it'll return /home/gabriel and not /home/gabriel/steam_jail. Am I doing something wrong?

It is normal,  /home/gabriel/steam_jail is mounted on top of /home/gabriel.

Steam uses some unknown mechanism to communicate between two instances of steam running in parallel. It is probably some UNIX socket, and it escapes our sandboxing. There is no way you can get around it, at least for now.

**Comment by snrgabe** [comment]
Oh okay, thanks for the information.
