### ISSUE TITLE
Custom include for dns option

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#1305]
Hi, I want to set the `dns` option for all firejail profiles (system-wide). For now I'm including the option manually in each and every profile file I have under ~/.config/firejail. This works, but I'm bound to forget adding it to newly created profiles sooner rather than later. So I was wondering how I could achieve it in /etc/firejail. Is there a recommended way of doing this?

Regards,
Helle

**Comment by netblue30** [comment]
I added in all profiles a "include /etc/firejail/globals.local" line. Use this file for your settings. The file is not overwritten during software install.
