### ISSUE TITLE
Pushing changes/limitations upstream 

### ISSUE THREAD

**Issue by breznak** [netblue30/firejail#1309]
I'd like to ask about your experience with pushing the improvements (esp. dropped capabilities) from the profiles here into the upstream packages? 

Ideally, there would be no need for this (awesome) tool. 
- I suppose even binary packages can be (tried) contacted 
- and for open-source, opening an issue or even a PR with (some) enhancements could certainly be possible.

**Comment by reinerh** [comment]
Pushing security improvements to upstream projects is of course a good idea.
But it's not possible to put every feature offered by firejail into individual projects, especially as some functionalities require root permissions.

**Comment by SYN-cook** [comment]
About experience: I had a conversation with KDE people regarding Baloo a while ago, and I was told that any work for implementing e.g. a seccomp filter is indeed very welcome. I actually would have done it myself, but I unfortunately don't speak C++.

My guess is: Especially if you are willing to contribute code and time, you will be welcome mostly everywhere.
