### ISSUE TITLE
Set different rights on folders

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#131]
Hi! 
I don't know if you've heard the bad news but our favourite OS is now targeted by [ransomware] (http://arstechnica.com/security/2015/11/new-encryption-ransomware-targets-linux-systems/).
Even though it only targets servers for now, that might change in the future.
So to prevent this, would it be possible to create a new option on folders in order to protect files:
in profile files `permission <octal> <folder>` e.g. `permission 300 ~/Downloads`. It would allow Firefox to download files but prevent badware/scripts from erasing/encrypting personal files.
If feasible, it'd be very useful for browsers.
Thanks.

**Comment by netblue30** [comment]
I'm not to worried about ransomware, the only folder visible in home directory is Downloads and the rest of the system is basically read-only. Making Downloads octal 300 will break several extensions (user downloads a file and plays it in vlc or other player).
