### ISSUE TITLE
Seccomp execve - Operation not permitted launching an app

### ISSUE THREAD

**Issue by EdoardoVignati** [netblue30/firejail#1310]
hi, when I execute `firejail --seccomp.eperm=execve myapp` I notice that firejail blocks the app saying `execvp: Operation not permitted`.
How to execute myapp and block execve syscall after?

**Comment by reinerh** [comment]
Hm, while trying to reproduce it I noticed that it's not working anymore in 0.9.46, though it's still documented in the manpage.

**Comment by startx2017** [comment]
manpage problem - use the regular --seccomp command: "firejail --seccomp=execve:eperm myapp"

Fix: https://github.com/netblue30/firejail/commit/c1d43f41230cdd0bc929c0050f60024fc98fc37b

**Comment by EdoardoVignati** [comment]
`firejail --seccomp=execve:eperm myapp` causes the same problem...seems that firejail recognizes the execution of myapp in the syscall blacklist specified in the command line, so not launching it...possibile?

**Comment by reinerh** [comment]
I can also confirm that the application is not executed if execve is blocked.

**Comment by netblue30** [comment]
Thanks @startx2017, I changed the code and forgot to modify the manual!

Don't use --seccomp=execve, because after installing the seccomp filter the sandbox will try to start the program using execve. We end up with seccomp killing the sandbox.

**Comment by EdoardoVignati** [comment]
Any workaround? Is there another way to spawn myapp?

**Comment by netblue30** [comment]
I don't think there is any workaround.

**Comment by EdoardoVignati** [comment]
Found a solution for seccomp [here](https://stackoverflow.com/questions/40107782/how-to-seccomp-a-subprocess)  if it can be useful
