### ISSUE TITLE
Thunar won't start with basic command 'firejail thunar' (actually, it starts, but not sandboxed)

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1311]
Command `firejail thunar` gives output:

```
Reading profile /usr/local/etc/firejail/thunar.profile
Reading profile /usr/local/etc/firejail/Thunar.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-passwdmgr.inc
Parent pid 17018, child pid 17019
Blacklist violations are logged to syslog
Child process initialized in 56.14 ms

Parent is shutting down, bye...
```

Command `firejail --noprofile thunar` gives output:

```
Parent pid 3835, child pid 3836
Child process initialized in 22.56 ms

Parent is shutting down, bye...
```

In both cases: Firetools shows no processes running, but Thunar window is _still open_.

I didn't even notice this until I started Thunar from the command line. With this behavior, user could perform some risky action without noticing application is not sandboxed. Is this normal behavior?

**Comment by netblue30** [comment]
Thunar is started by your desktop manager when you log in. When you try to start a second instance of Thunar, the instance already running takes over, and your second instance shuts down. All you have to do is to make sure the first instance starts in a sandbox.

Run "sudo ln -s /usr/bin/firejail /usr/local/bin/thunar" in a terminal, logout and login back for the change to take effect. Than run "firejail --tree" to make sure Thunar is sandboxed. On newer systems (Ubuntu 17.04, Arch, Debian testing) this is not necessary. On older systems (Ubuntu 16.04, Debian stable) set the symbolic link as above. What distro are you running?

**Comment by rekixex** [comment]
@netblue30 

> What distro are you running?

Behavior I described occured after I installed Firejail (version from Git repository) on a PC running Xubuntu 16.04.

I installed Firejail in `/usr/local/bin/firejail`. Then I ran `sudo firecfg` (which didn't create symbolic link for Thunar) and `sudo ln -s /usr/local/bin/firejail /usr/local/bin/thunar`, rebooted, but behavior is the same (Firetools shows no processes running whether I start Thunar from the terminal or from the menu).

Like you said, Thunar is started by desktop manager after login: task manager shows process **Thunar --daemon**. From Thunar manpage:

```
--daemon
           Do not terminate the Thunar instance when the last window is closed,
           but keep it running to speed up opening new windows later on. This is
           the default when spawning Thunar as part of the default Xfce session or
           when using D-Bus activation.
```

However, when I terminate Thunar instance running in the background with `thunar -q`, Thunar runs sandboxed when launched _from the terminal_ with `thunar` command (without prefix), but runs out of the sandbox when launched _from the menu_.

I also tried clearing xfce session before reboot. Any suggestions?

**Comment by rekixex** [comment]
@netblue30 

> What distro are you running?

Behavior I described occured after I installed Firejail (version from Git repository) on a PC running Xubuntu 16.04.

I installed Firejail in `/usr/local/bin/firejail`. Then I ran `sudo firecfg` (which didn't create symbolic link for Thunar) and `sudo ln -s /usr/local/bin/firejail /usr/local/bin/thunar`, rebooted, but behavior is the same (Firetools shows no processes running whether I start Thunar from the terminal or from the menu).

Like you said, Thunar is started by desktop manager after login: task manager shows process **Thunar --daemon**. From Thunar manpage:

```
--daemon
           Do not terminate the Thunar instance when the last window is closed,
           but keep it running to speed up opening new windows later on. This is
           the default when spawning Thunar as part of the default Xfce session or
           when using D-Bus activation.
```

However, when I terminate Thunar instance running in the background with `thunar -q`, Thunar runs _sandboxed_ when launched _from the terminal_ with `thunar` command (without prefix), but runs _out of the sandbox_ when launched _from the menu_.

I also tried clearing xfce session before reboot. Any suggestions?

**Comment by rekixex** [comment]
@netblue30 

> What distro are you running?

I experienced this issue on a PC running Xubuntu 16.04 (with Firejail version from Git repository).

I installed Firejail in `/usr/local/bin/firejail`. Then I ran `sudo firecfg` (which didn't create symbolic link for Thunar) and `sudo ln -s /usr/local/bin/firejail /usr/local/bin/thunar`, rebooted, but Firetools shows no processes running whether I start Thunar from the terminal or from the menu.

Like you said, Thunar is started by desktop manager after login: task manager shows process **Thunar --daemon**.

I also tried clearing Xfce session before reboot. Any suggestions?

**Comment by netblue30** [comment]
> Like you said, Thunar is started by desktop manager after login: task manager shows the process Thunar --daemon.

You need the following symlink:
`````
$ sudo ln -s /usr/local/bin/firejail /usr/local/bin/Thunar
`````
Some distros use thunar, other distros use Thunar as the executable.
