### ISSUE TITLE
No sound in Firefox

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1312]
Sound in Firefox worked fine until recently (basic command `firejail firefox`, Firejail version from Git repository, Ubuntu 16.04 LTS).

I have already tried suggested workarounds with no success:
https://firejail.wordpress.com/support/known-problems/#pulseaudio

When I use `--noprofile` argument (`firejail --noprofile firefox`) sound works. Maybe Firefox profile needs some adjustments.

**Comment by rekixex** [comment]
Solved!

I added argument `--whitelist=~/.config/pulse` (firejail --whitelist=~/.config/pulse firefox).

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` (`firejail --whitelist=~/.config/pulse firefox`).

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` when launched Firefox. So, with this command sound in Firefox works:

`firejail --whitelist=~/.config/pulse firefox`

However, sound worked fine in other applications (**vlc** for example) without whitelisting `~/.config/pulse`.

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` when launched Firefox. So, with this command sound in Firefox works:

`firejail --whitelist=~/.config/pulse firefox`

However, sound workes fine in other applications (**vlc** for example) without whitelisting `~/.config/pulse`.

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` when launched Firefox. So, with this command sound in Firefox works:

`firejail --whitelist=~/.config/pulse firefox`

However, sound works fine in other applications (**vlc** for example) without whitelisting `~/.config/pulse`.

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` when launched Firefox. So, with this command sound in Firefox works:

`firejail --whitelist=~/.config/pulse firefox`

However, sound works fine in other applications (**vlc** for example) without whitelisting `~/.config/pulse`.

But what are the security implications of whitelisting `~/.config/pulse`?

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` when launched Firefox. So, with this command sound in Firefox works:

`firejail --whitelist=~/.config/pulse firefox`

However, sound works fine in other applications (**vlc** for example) without whitelisting `~/.config/pulse`.

But what are the security / privacy implications of whitelisting `~/.config/pulse`?

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` when launched Firefox. So, with this command sound in Firefox works:

`firejail --whitelist=~/.config/pulse firefox`

However, sound works fine in other applications (**vlc** for example) without whitelisting `~/.config/pulse`.

What are the security / privacy implications of whitelisting `~/.config/pulse`?

**Comment by rekixex** [comment]
Solved.

I added argument `--whitelist=~/.config/pulse` when launched Firefox. So, with this command sound in Firefox works again:

`firejail --whitelist=~/.config/pulse firefox`

However, sound works fine in other applications (**vlc** for example) without whitelisting `~/.config/pulse`.

What are the security / privacy implications of whitelisting `~/.config/pulse`?

**Comment by SYN-cook** [comment]
Can I ask which Firejail version you are using?

**Comment by rekixex** [comment]
@SYN-cook I forgot to mention, I am using version from Git repository.

May I ask what are the security / privacy implications of whitelisting `~/.config/pulse`? Firefox seems to be the only application which needs this workaround so far.

**Comment by rekixex** [comment]
@SYN-cook I forgot to mention, I am using Firejail version from Git repository.

May I ask what are the security / privacy implications of whitelisting `~/.config/pulse`? Firefox seems to be the only application which needs this workaround so far.

**Comment by netblue30** [comment]
It should work without whitelisting  ~/.config/pulse. There is a bug in most PulseAudio versions, see here: https://firejail.wordpress.com/support/known-problems/#pulseaudio.

I would say run "firecfg --fix-sound", logout and login again and all should be fixed. Also, there should be no security implications in whitelisting ~/.config/pulse.

**Comment by rekixex** [comment]
@netblue30 I tried suggested workarounds from https://firejail.wordpress.com/support/known-problems/#pulseaudio and also `firecfg --fix-sound`, logged out and logged in, rebooted, but Firefox still doesn't play sound without whitelisting `~/.config/pulse`. However, problem doesn't exist with `--noprofile` argument.

Whitelisting `~/.config/pulse` solves the problem for me, so I will close this.

**Comment by SYN-cook** [comment]
@rekixex I can actually reproduce it, with Ubuntu 16.04 and Firejail built from master. 

If not explicitly whitelisted, ~/.config/pulse is not available in the Firefox sandbox, and as a consequence there are plenty `shm_open() failed` errors.

I can also confirm that not all applications have this issue (tried with Totem).

**Comment by SYN-cook** [comment]
@netblue30 You want `whitelist ~/.config/pulse/client.conf` to go to whitelist-common.inc (it works), or do you prefer some kind of fix in the Firejail source?
