### ISSUE TITLE
Also read /etc/hosts when using the firejail hosts-file option

### ISSUE THREAD

**Issue by throwaway217** [netblue30/firejail#1313]
Would it be possible to add a parameter to hosts-file so it can also read /etc/hosts in addition to the new designated hosts file instead of only that file as it is currently ?

**Comment by netblue30** [comment]
Just configuring /etc/hostname would not be enough. Use --hostname= and it will set your hostname the right way.

**Comment by throwaway217** [comment]
I apologize for not making myself more clear.
Let's say I have as /etc/hosts this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts 
And somewhere in my home directory I have this seperate hosts file, let's say in ~/.hosts 
```
0.0.0.0 github.com
0.0.0.0 button.org
```
Now if I add
`hosts-file ~/.hosts` to my aplication profile that application will start using the designated hosts file ignoring /etc/hosts.

I'm wondering if it would be possible to add an option to include /etc/hosts along with the designated hosts file.

I thought this would be a good idea for some reason a few hours ago but now I see that it's just better to just cp /etc/hosts ~/.hosts and then cat second_hosts_file >> ~/.hosts everytime second_hosts_file changes.
