### ISSUE TITLE
trouble with firemon --x11 from scripts.

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#1316]
files are here https://gist.github.com/xahare/7a1931c6d734ba519feff42ae7826c29

ive been using sandfox since i threw it together months ago. as a shell script that calls python scripts, its been fine. 

but when trying to make it a self contained python script, it fails almost every time if another instance is running. firemon will only see the first firejail, not the one just started. on a rare occasion, both will work.

in the bash version, fjdisplay is a python scripted called to find the display number for openbox. in the python version, i just pasted it in. 

i hope theres just something stupid im missing here.

firejail 0.9.46, ubuntu 16.04

**Comment by netblue30** [comment]
I'll give it a try.

**Comment by rusty-snake** [comment]
@xahare still need help?

**Comment by rusty-snake** [comment]
@xahare I'm closing here due to inactivity, please fell free to reopen if you have more questions.
