### ISSUE TITLE
[INFORMATION] Need review about article

### ISSUE THREAD

**Issue by Anyon3** [netblue30/firejail#1318]
Hello,

https://anyon3.github.io/firejail.html

Don't bother about the wrong english syntax, it will be corrected asap, I need to known if the technical part describ on this article or if it need some rewrite / fix, the goal is to explain another way of using Firejail, without the default profile (as explained...)

The tech will not move much so any confirmation or help on the tech syntax will be highly appreciate

Thanks,

**Comment by netblue30** [comment]
It is fine, thanks for the article.
