### ISSUE TITLE
[DOC] Firefox doesn’t open in a new sandbox...

### ISSUE THREAD

**Issue by Anyon3** [netblue30/firejail#1319]
> Firefox doesn’t open in a new sandbox. Instead, it opens a new tab in an existing Firefox
instance
> 
> By default, Firefox browser uses a single process to handle multiple windows. When you start the browser, if another Firefox process is already running, the existing process opens a new tab or a new window. Make sure Firefox is not already running when you start it in Firejail sandbox.

To open a new firefox instance, you can use the following argument --new-instance (with firefox, example : firefox --new-instance)

I think this point should be add on this part of the FAQ. It could be necessary to pass -P argument to select a different profile for each new instance if you handle different FIrefox profile in the same home directory

Hope it's helpful

Thanks,

Edit : I made several test and can confirm --new-instance, no matter if one or more Firefox processus are running, will create a new uniq firefox processus. 

Torbrowser will have the same effect if a Firefox processus is already running. A bigger problem related to TB is : While another processus of Firefox is running and no argument --new-instance was used, TB will keep your session data (history, cookie, cache...) after you close it as long a Firefox processus is running.

**Comment by netblue30** [comment]
all set: https://firejail.wordpress.com/support/frequently-asked-questions/#firefox-dual

**Comment by Anyon3** [comment]
You right, I missed this argument (--no-remote), my bad.

**Comment by netblue30** [comment]
I think --no-remote and --new-instance are equivalent, or the difference between them is very small.  They both do the job.
