### ISSUE TITLE
firefox default profile minor issue

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#132]
need to white list this folder also
~/.cache/mozilla/firefox

**Comment by netblue30** [comment]
Fixed, thanks!

**Comment by pirate486743186** [comment]
also need to white list this for mplayer plugin (doesn't work otherwise)
whitelist ~/.config/gnome-mplayer
and probably this (i didn't use that for ages....)
whitelist ~/.cache/gnome-mplayer/plugin

**Comment by netblue30** [comment]
All done. If you find anything else, just let me know. Thanks.
