### ISSUE TITLE
0.9.44.10 -> 0.9.46: libstdc++.so cannot be loaded

### ISSUE THREAD

**Issue by uzytkownik** [netblue30/firejail#1320]
I run into multiple programs failing to load C++ library under the firejail. Downgrading fixed the problem.

**Comment by netblue30** [comment]
What distribution are you using?

**Comment by uzytkownik** [comment]
Gentoo with gcc 6.3.0.

**Comment by netblue30** [comment]
We had this problem about a year ago on Gentoo and we ended up commenting out "blacklist /usr/bin/gcc" line in /etc/firejail/disable-devel.inc - see #674 and #824. Go in this file and comment out (add a #) to all lines in gcc section of the file. One of them is creating the problem. If you run " find / -name libstdc++.so.6" what does it say?

**Comment by uzytkownik** [comment]
```
# grep libstdc++.so.6 /var/db/pkg/sys-devel/gcc-6.3.0/CONTENTS  | awk '{print $2}'
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/32/libstdc++.so
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/32/libstdc++.so.6
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/32/libstdc++.so.6.0.22
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libstdc++.so
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libstdc++.so.6
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libstdc++.so.6.0.22
/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/32/libstdc++.so.6.0.22.debug
/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libstdc++.so.6.0.22.debug
/usr/share/gdb/auto-load/usr/lib64/gcc/x86_64-pc-linux-gnu/6.3.0/libstdc++.so.6.0.22-gdb.py
/usr/share/gdb/auto-load/usr/lib64/gcc/x86_64-pc-linux-gnu/6.3.0/32/libstdc++.so.6.0.22-gdb.py
```

I commented out all lines in GCC section and it didn't helped.

**Comment by netblue30** [comment]
Does it work if you start the sandboxes with --noprofile? (firejail --noprofile program)

**Comment by bitthief** [comment]
I have also stumbled upon this problem on two different Gentoo Hardened systems trying to run KeePassXC. After some diagnosing (stracing the KeePassXC bin), I found that the issue comes from the fact that KeePassXC was trying to read /etc/ld.so.cache.
The fix was trivial, the keepassxc.profile contains the following line:
`private-etc fonts`
Simply changing it resolved the issue:
`private-etc ld.so.cache,fonts`

**Comment by Fred-Barclay** [comment]
Thanks @bitthief. I've changed the keepassxc profile to contain `ld.so.cache` in private-etc.

@uzytkownik Can you test if adding keepassxc to a profile makes a difference, and if so, can you list which profiles you're having trouble with?
