### ISSUE TITLE
keepassx segfault 

### ISSUE THREAD

**Issue by 8cc** [netblue30/firejail#1321]
Fedora 25 KDE spins, firejail 0.9.44.10 (copr nielsenb/firejail), keepassx 2.0.3.
When try to select a file, segfault.
```
$ firejail keepassx
Reading profile /etc/firejail/keepassx.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Parent pid 4773, child pid 4774
Blacklist violations are logged to syslog
Child process initialized
Qt: Session management error: Could not open network socket
ERROR: Running KSycoca failed.

Parent is shutting down, bye...
```
dmesg
`[199975.701777] keepassx[5132]: segfault at 0 ip 00007f2fead15a09 sp 00007ffdb9aecad0 error 4 in libkio.so.5.14.30[7f2feab26000+2b4000]`

**Comment by netblue30** [comment]
In a text editor open /etc/firejail/kepassx.profile and change "protocol unix" in "protocol unix,inet,inet6". Let me know if is working.

**Comment by 8cc** [comment]
It's not working. Problem persists.

**Comment by netblue30** [comment]
I think is "net none"  in the same file - comment it out. Somehow I missed it!

**Comment by 8cc** [comment]
Comments to "net none" could not help, problem persists.

**Comment by Fred-Barclay** [comment]
@8cc Is the latest version of firejail (0.9.46) available for your distro?

**Comment by 8cc** [comment]
Firejail is available in third-party repositories from the community, but I do not see the latest version. There is also a binary .rpm package with the latest version here: https://sourceforge.net/projects/firejail/files/firejail/

**Comment by Fred-Barclay** [comment]
Hi @8cc,

Go with the binary .rpm from
https://sourceforge.net/projects/firejail/files/firejail/ please, then
see if the problem still exists.

**Comment by 8cc** [comment]
Updated to the latest version through the .rpm , now the program does not start. Tried to change configs, does not help.

**Comment by Fred-Barclay** [comment]
@8cc let me make sure I understand the problem correctly:
 - For firejail 0.9.44.10 through copr nielsenb/firejail, keepassx starts but segfaults when you try to choose a file.'
 - For firejail 0.9.46, keepassx does not start at all
 - When not using firejail (either version), keepassx behaves normally

Is this correct?
Can you post the exact keepassx profile you are using?
Can you run the following and post the output: `firejail --debug keepassx`?

**Comment by 8cc** [comment]
Yes, that right.
I use default configuration in nielsenb/firejail: 
```
# This file is overwritten during software install.
# Persistent customizations should go in a .local file.
include /etc/firejail/keepassx.local

# keepassx password manager profile
noblacklist ${HOME}/.config/keepassx
noblacklist ${HOME}/.keepassx
noblacklist ${HOME}/*.kdbx
noblacklist ${HOME}/*.kdb
 
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc

caps.drop all
net none
nogroups
nonewprivs
noroot
nosound
protocol unix
seccomp
shell none
tracelog

private-bin keepassx
private-etc fonts
private-dev
#private-tmp - mask KDE problems
```
firejail --debug keepassx
and tried to select a file.
```
firejail --debug keepassx on nielsenb/firejail
Autoselecting /bin/bash as shell
Command name #keepassx#
Found keepassx profile in /etc/firejail directory
Reading profile /etc/firejail/keepassx.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Checking /usr/local/bin/keepassx
Checking /usr/bin/keepassx
Checking /etc/fonts
DISPLAY :0, 0
Parent pid 9824, child pid 9825
Initializing child process
PID namespace installed
Mounting tmpfs on /run/firejail/mnt directory
Mounting read-only /bin, /sbin, /lib, /lib32, /lib64, /usr, /etc, /var
Mounting tmpfs on /var/lock
Mounting tmpfs on /var/tmp
Mounting tmpfs on /var/log
Create the new utmp file
Mount the new utmp file
Cleaning /home directory
Sanitizing /etc/passwd, UID_MIN 1000
Sanitizing /etc/group, GID_MIN 1000
Disable /run/firejail/network
Disable /run/firejail/bandwidth
Disable /run/firejail/name
Disable /run/firejail/x11
Mounting tmpfs on /dev
mounting /run/firejail/mnt/dev/snd directory
mounting /run/firejail/mnt/dev/dri directory
Create /dev/shm directory
Copying files in the new etc directory:
running: /run/firejail/mnt/cp -a --parents /etc/fonts /run/firejail/mnt
Mount-bind /run/firejail/mnt/etc on top of /etc
Creating an empty /etc/ld.so.preload file
Copying files in the new home:
Checking /usr/local/bin/keepassx
Checking /usr/bin/keepassx
Mount-bind /run/firejail/mnt/bin on top of /usr/local/bin
Mount-bind /run/firejail/mnt/bin on top of /usr/bin
Mount-bind /run/firejail/mnt/bin on top of /bin
Mount-bind /run/firejail/mnt/bin on top of /usr/games
Mount-bind /run/firejail/mnt/bin on top of /usr/local/games
Mount-bind /run/firejail/mnt/bin on top of /usr/local/sbin
Mount-bind /run/firejail/mnt/bin on top of /usr/sbin
Mount-bind /run/firejail/mnt/bin on top of /sbin
Remounting /proc and /proc/sys filesystems
Remounting /sys directory
Disable /sys/firmware
Disable /sys/hypervisor
Disable /sys/module
Disable /sys/power
Disable /sys/kernel/debug
Disable /sys/kernel/vmcoreinfo
Disable /proc/sys/fs/binfmt_misc
Disable /proc/sys/kernel/core_pattern
Disable /proc/sys/kernel/modprobe
Disable /proc/sysrq-trigger
Disable /proc/sys/vm/panic_on_oom
Disable /proc/irq
Disable /proc/bus
Disable /proc/sched_debug
Disable /proc/timer_list
Disable /proc/kcore
Disable /proc/kallsyms
Disable /usr/lib/modules
Disable /usr/lib/debug
Disable /boot
Disable /proc/kmsg
Disable /home/user/.bash_history
Mounting read-only /home/user/.local/share/applications
Disable /home/user/.config/autostart
Disable /home/user/.config/plasma-workspace/shutdown
Disable /home/user/.config/plasma-workspace/env
Disable /var/spool/cron
Disable /var/spool/anacron
Disable /run/rpcbind.sock
Mounting read-only /home/user/.bashrc
Mounting read-only /home/user/.bash_profile
Mounting read-only /home/user/.bash_logout
Disable /home/user/.ssh
Disable /home/user/.cert
Disable /home/user/.kde/share/apps/kwallet
Disable /home/user/.local/share/kwalletd
Disable /home/user/.gnupg
Not blacklist /home/user/*.kdbx
Not blacklist /home/user/*.kdb
Disable /usr/sbin
Disable /usr/sbin
Disable /usr/local/sbin
Disable /home/user/.kde/share/apps/okular
Disable /home/user/.kde/share/config/okularrc
Disable /home/user/.kde/share/config/okularpartrc
Disable /home/user/.config/vlc
Disable /home/user/.thunderbird
Disable /home/user/.mozilla
Disable /home/user/.purple
Disable /home/user/.cache/gajim
Disable /home/user/.local/share/gajim
Disable /home/user/.config/gajim
Disable /home/user/.cache/mozilla
Disable /home/user/.cache/thunderbird
Disable /tmp/ssh-QhcLXQmUXoo1
Disable /usr/include
Disable /usr/share/perl5
Disable /home/user/.pki/nssdb
Not blacklist /home/user/.keepassx
Not blacklist /home/user/.config/keepassx
Disable /sys/fs
Create the new ld.so.preload file
Blacklist violations are logged to syslog
Mount the new ld.so.preload file
disable pulseaudio
Disable/home/user/.config/pulse
Disable/run/user/1000/pulse/native
Disable/run/user/1000/pulse/native
disable /dev/snd
Network namespace enabled, only loopback interface available
DISPLAY :0, 0
Dropping all capabilities
Set protocol filter: unix
Dual i386/amd64 seccomp filter configured
SECCOMP Filter:
  VALIDATE_ARCHITECTURE
  EXAMINE_SYSCAL
  UNKNOWN ENTRY!!!
  UNKNOWN ENTRY!!!
  UNKNOWN ENTRY!!!
  BLACKLIST 165 mount
  BLACKLIST 166 umount2
  BLACKLIST 101 ptrace
  BLACKLIST 246 kexec_load
  BLACKLIST 320 kexec_file_load
  BLACKLIST 304 open_by_handle_at
  BLACKLIST 303 name_to_handle_at
  BLACKLIST 175 init_module
  BLACKLIST 313 finit_module
  BLACKLIST 174 create_module
  BLACKLIST 176 delete_module
  BLACKLIST 172 iopl
  BLACKLIST 173 ioperm
  BLACKLIST 251 ioprio_set
  BLACKLIST 167 swapon
  BLACKLIST 168 swapoff
  BLACKLIST 103 syslog
  BLACKLIST 310 process_vm_readv
  BLACKLIST 311 process_vm_writev
  BLACKLIST 139 sysfs
  BLACKLIST 156 _sysctl
  BLACKLIST 159 adjtimex
  BLACKLIST 305 clock_adjtime
  BLACKLIST 212 lookup_dcookie
  BLACKLIST 298 perf_event_open
  BLACKLIST 300 fanotify_init
  BLACKLIST 312 kcmp
  BLACKLIST 248 add_key
  BLACKLIST 249 request_key
  BLACKLIST 250 keyctl
  BLACKLIST 134 uselib
  BLACKLIST 163 acct
  BLACKLIST 154 modify_ldt
  BLACKLIST 155 pivot_root
  BLACKLIST 206 io_setup
  BLACKLIST 207 io_destroy
  BLACKLIST 208 io_getevents
  BLACKLIST 209 io_submit
  BLACKLIST 210 io_cancel
  BLACKLIST 216 remap_file_pages
  BLACKLIST 237 mbind
  BLACKLIST 239 get_mempolicy
  BLACKLIST 238 set_mempolicy
  BLACKLIST 256 migrate_pages
  BLACKLIST 279 move_pages
  BLACKLIST 278 vmsplice
  BLACKLIST 161 chroot
  BLACKLIST 184 tuxcall
  BLACKLIST 169 reboot
  BLACKLIST 180 nfsservctl
  BLACKLIST 177 get_kernel_syms
  RETURN_ALLOW
Save seccomp filter, size 880 bytes
noroot user namespace installed
Dropping all capabilities
NO_NEW_PRIVS set
starting application
LD_PRELOAD=(null)
execvp argument 0: keepassx
Child process initialized
monitoring pid 6

ERROR: Running KSycoca failed.
Sandbox monitor: waitpid 6 retval 6 status 11

Parent is shutting down, bye...
```

**Comment by Fred-Barclay** [comment]
Try commenting out `private-bin keepassx`

Can you help me understand what this Ksyscoca is that keeps being referenced in the error message? I can't find it in the Fedora package database https://admin.fedoraproject.org/pkgdb/packages/KSycoca%2A/

**Comment by 8cc** [comment]
Сomment `private-bin keepassx` not help.
[KDE SYstem COnfiguration CAche](https://userbase.kde.org/KDE_System_Administration/Caches#KSycoca).

**Comment by Anyon3** [comment]
Try with firejail in command line without a defined profile 

firejail --machine-id --noprofile --nonewprivs --noroot --caps.drop=all --nosound --private-dev --seccomp --no3d --private-tmp --nogroups --net=none keepassx

Hope it's help

**Comment by 8cc** [comment]
`firejail --machine-id --noprofile --nonewprivs --noroot --caps.drop=all --nosound --private-dev --seccomp --no3d --private-tmp --nogroups --net=none keepassx`

Keepassx started, the file selection dialog appeared, but when try to select: "The specified folder does not exist or was not readable." Perhaps this is not the fault of the firejail.

**Comment by Anyon3** [comment]
Try to remove the argument --nogroups and --nonewprivs (nonewprivs is not required when --seccomp is passed) 

If it's still the same, give a try to keepassxc

**Comment by 8cc** [comment]
> Keepassx started, the file selection dialog appeared, but when try to select: "The specified folder does not exist or was not readable." Perhaps this is not the fault of the firejail.

All the same works. Files are selected when not `--private`.

**Comment by Anyon3** [comment]
you could maybe try to add a directory inside your /home/$user/ like keepassxjail and add --private=~/keepassxjail/ (don't forget to place your kdbx database inside keepassxjail) to increase the security.

**Comment by netblue30** [comment]
> Qt: Session management error: Could not open network socket

What bothers me is you have a password manager crashed by the sandbox when it tries to connect to the network. Why would a password manager try to connect to the network?

Also, make sure you run 0.9.46. In this version a lot of fixes went in for all keepass utilities. You can get an .rpm package from our download page, it was build on CentOS 7, it should work fine on any Fedora distro released after that.

**Comment by Anyon3** [comment]
Looking at the dmesg output, could https://en.wikipedia.org/wiki/KIO explain the connection of his keepassx over the network ?

**Comment by Fred-Barclay** [comment]
> What bothers me is you have a password manager crashed by the sandbox when it tries to connect to the network.

I'm not sure that it's crashed when trying to connect to the network. I get the exact same output on Debian Sid MATE and keepassx works fine in firejail:
```$ firejail keepassx
Reading profile /etc/firejail/keepassx.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Parent pid 6387, child pid 6388
Blacklist violations are logged to syslog
Child process initialized in 75.42 ms
Qt: Session management error: Could not open network socket
```

**Comment by Fred-Barclay** [comment]
I might have a fix in. On a Fedora 25 Gnome VM, keepassx would crash in firejail if `private-bin` did not contain both keepassx and keepassx2, or if it couldn't read /etc/machine-id (which we've been blocking with `private-etc fonts`). I've added keepassx2 to private-bin, and added /etc/machine-id to the sandbox... but it's spoofed with the `machine-id` option so keepassx still can't see your real machine id. 😁 

@8cc Can you try the new profile? It's at https://raw.githubusercontent.com/netblue30/firejail/3a2428bd4ba70e4b4c71b8e7ae7aeee8e027428e/etc/keepassx.profile

**Comment by 8cc** [comment]
> @8cc Can you try the new profile? It's at https://raw.githubusercontent.com/netblue30/firejail/3a2428bd4ba70e4b4c71b8e7ae7aeee8e027428e/etc/keepassx.profile

Profile did not help, firejail 0.9.46.

**Comment by Anyon3** [comment]
I tried the keepassx profile proposed by Fred-Barclay on my Gentoo Hardened and got this 

keepassx: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory

I added a comment to 

private-etc fonts,machine-id

And this fixed the error. Another small thing I spotted is the use of nonewprivs, I may be wrong but according to the man firejail 

This option is enabled by default if seccomp filter is activated

As seccomp is passed in the profile, nonewprivs maybe removed ?

**Comment by netblue30** [comment]
> As seccomp is passed in the profile, nonewprivs can be removed ?

Yes, you can remove it. However, if you remove seccomp, it is a very good idea to bring back nonewprivs.

**Comment by Anyon3** [comment]
Ok thanks for this infos. Most of the profile have nonewprivs and seccomp, this is in case seccomp is not active on the system Linux right ?

**Comment by netblue30** [comment]
> this is in case seccomp is not active on the system Linux right ?

Seccomp and nonewprivs are not enabled by default on any Linux system. Seccomp configuration is very specific to the particular program running.

**Comment by Tanath** [comment]
I was getting this issue until I commented out `memory-deny-write-execute`.
