### ISSUE TITLE
Bug in disable-programs.inc 

### ISSUE THREAD

**Issue by NH3-** [netblue30/firejail#1325]
In the file https://github.com/netblue30/firejail/blob/master/etc/disable-programs.inc it is specified that the following programs should be disable : 

`blacklist ${HOME}./config/gpicview`
`blacklist ${HOME}./local/share/dino`

But the syntax is **incorrect**, indeed, the correct syntax should be :

`blacklist ${HOME}/.config/gpicview`
`blacklist ${HOME}/.local/share/dino`

the dot should be after the slash.

**Comment by Fred-Barclay** [comment]
Thanks, you're right. 👍 
It's been fixed now.
