### ISSUE TITLE
firejail 0.9.46 private-etc broken?

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1327]
I seem to have trouble with the following line in my `mutt` profile:
````
private-etc Muttrc.d,Muttrc,alternatives,resolv.conf,ssl,mime.types
````
which leads to the following output:
````
Reading profile .config/firejail/mutt.profile
Parent pid 12082, child pid 12083
Warning fcopy: skipping /etc/alternatives/rmid, cannot find inode
Warning fcopy: skipping /etc/alternatives/unpack200.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/keytool.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/jjs, cannot find inode
Warning fcopy: skipping /etc/alternatives/unpack200, cannot find inode
Warning fcopy: skipping /etc/alternatives/gnuplot5.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/pack200, cannot find inode
Warning fcopy: skipping /etc/alternatives/pack200.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/jjs.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/rmiregistry.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/js.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/tnameserv.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/gnuplot5, cannot find inode
Warning fcopy: skipping /etc/alternatives/servertool, cannot find inode
Warning fcopy: skipping /etc/alternatives/java-rmi.cgi, cannot find inode
Warning fcopy: skipping /etc/alternatives/rmid.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/orbd, cannot find inode
Warning fcopy: skipping /etc/alternatives/tnameserv, cannot find inode
Warning fcopy: skipping /etc/alternatives/orbd.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/servertool.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/keytool, cannot find inode
Warning fcopy: skipping /etc/alternatives/rmiregistry, cannot find inode
Error fcopy: invalid file /etc/mime.types
Error: failed to run /usr/lib/x86_64-linux-gnu/firejail/fcopy
Error: proc 12082 cannot sync with peer: unexpected EOF
Peer 12083 unexpectedly exited with status 1
````
I did not have this issue with 0.9.44, and do not have this issue with any other `private-*` lines in my profile.

[edit] removing `mime.types` from my profile allows the program to at least load, but I still get the other warnings.

**Comment by chiraag-nataraj** [comment]
Ah, interesting. It seems that some of my `/etc/alternatives/` links are broken, so I guess those warnings make sense. However, it still breaks when I include `mime.types`.

**Comment by Fred-Barclay** [comment]
Can you post your profile here?

**Comment by netblue30** [comment]
I think you removed Java Open JDK using "sudo apt-get remove openjdk...". This removed the package but left broken symlinks in /etc/alternatives. If you do "ls -l /etc/alternative/rmid", this is a symlink pointing nowhere, so firejail cannot set it up in --private-etc. Use "sudo apt-get purge ..." to remove packages, this also cleans up /etc directory.

Do also a "ls -l /etc/mime.types". This looks like a different problem.

**Comment by chiraag-nataraj** [comment]
I got rid of those warnings, so you can ignore those.

Regarding `/etc/mime.types`, I found out that it was (for some reason) owned by me. Changing the permission on it to `root:root` was enough to get it to launch. So I guess the error could be clearer? But I'm going to close this as the issue is resolved 😄

For people coming back here at some point: _check your permissions_ 😛
