### ISSUE TITLE
firejail 0.9.46 private-bin breaks with no errors or warnings

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1328]
In that same mutt profile, I have the following line:
````
private-bin sh,mutt,mutt_dotlock,bash,emacsclient,elinks,gpg,gpg-agent,pinentry,dig,awk
````
This line works perfectly well in 0.9.44 but mutt refuses to launch the editor (emacsclient) in 0.9.46. Commenting out this line fixes the problem.

Why would the binaries needed by mutt change based on the firejail version?

**Comment by Fred-Barclay** [comment]
@chiraag-nataraj Try doing the following:
```
firejail --private-bin=sh,mutt,mutt_dotlock,bash,emacsclient,elinks,gpg,gpg-agent,pinentry,dig,awk
```
Then run mutt. Copy the output here.
Thanks!

**Comment by chiraag-nataraj** [comment]
There's no output. That's what gets me. Mutt supposedly tries to launch the editor and immediately aborts with no explanation whatsoever. No seccomp entry or anything (already checked). I am going to continue investigating.

**Comment by chiraag-nataraj** [comment]
When I use `firejail --trace`, I get the following (it's not much):
````
Reading profile /home/chiraag/.config/firejail/mutt.profile
Parent pid 17829, child pid 17830
Warning: skipping proxychains.conf for private /etc
23:fseccomp:open /run/firejail/mnt/seccomp:3
Child process initialized in 46.21 ms
24:bash:open /dev/tty:3
24:mutt:fopen /proc/filesystems:0x55fdf506b040
24:mutt:access /etc/selinux/config:-1
24:mutt:access /lib/terminfo/r/rxvt-unicode:0
24:mutt:fopen /lib/terminfo/r/rxvt-unicode:0x55fdf50aac60
24:mutt:fopen /home/chiraag/.muttrc/.muttrc.localb:0x55fdf51521b0
24:mutt:fopen /home/chiraag/.muttrc/.muttrc.local:0x55fdf514c310
24:mutt:fopen /home/chiraag/.mutthistory:(nil)
24:mutt:unlink /tmp/user/1000/mutt1000/mutt-chiraag-1000-24-9486865720593099851:0
24:mutt:unlink /tmp/user/1000/mutt1000/mutt-chiraag-1000-24-15104734278847866818:0
24:mutt:unlink /tmp/user/1000/mutt1000/mutt-chiraag-1000-24-9060183403553630014:0
Mailbox is unchanged.

Parent is shutting down, bye...
````
The `unlink` calls are where I try to read an email.

**Comment by chiraag-nataraj** [comment]
Ha. Aha. Ahahahahahaha. Symlinks. So `/usr/bin/emacsclient` -> `/usr/bin/emacsclient.emacs25` and I didn't whitelist that. I guess the link-following policy changed between the two versions?

**Comment by chiraag-nataraj** [comment]
Hmm...so now I have this weird problem where I can manually call it (using `firejail --join` and manually invoking the editor), but it doesn't work from within mutt.

**Comment by chiraag-nataraj** [comment]
Issue fixed. The main thing was the symlink following behavior which changed.
