### ISSUE TITLE
private-etc with custom files

### ISSUE THREAD

**Issue by allo-** [netblue30/firejail#1332]
Would it be possible to create a private-etc with custom files?
This means not copying ``/etc/passwd`` to the jail, but copying ``~/firejail/etc/passwd`` to ``/etc/passwd`` in the jail, so you can i.e. hide which users exist outside of the jail and still have a working passwd file with users like root and the user running firejail (even with changed name, i guess only the uid needs to match inside the jail).
There is ``--bind``, but it works only for root. And I do not need to bind the file, copying it is sufficient (and sometimes even preferable).

**Comment by netblue30** [comment]
This will bring in a lot of security problems.

**Comment by allo-** [comment]
I want to copy a file owned by a non-root user into a jail started by a non-root user. 
I do not see the security issues, can you give an rough example why this could be a problem?

**Comment by netblue30** [comment]
All you have to do is to bring in a different /etc/shadow file and su to root after the sandbox started.

**Comment by allo-** [comment]
OK. I need to look more into the infrastructure. Though it uses user mode jails when not run as root.
