### ISSUE TITLE
private-tmp option in chromium.profile causes URLs to be opened in new Chromium window, potentially corrupts chromium profile and browsing history 

### ISSUE THREAD

**Issue by Saren-Arterius** [netblue30/firejail#1334]
# Environment
OS: Arch Linux
Relevant packages:
- chromium 59.0.3071.86-1
- firejail 0.9.48-1

Customized `/usr/local/bin/chromium`
```
#!/bin/bash
if [ -n "$(ps -aux | grep /usr/bin/chromium | grep -v grep)" ]; then 
	/usr/bin/chromium $1 
else
	firejail --name=chromium /usr/bin/chromium $1 --disk-cache-dir=/tmp/cache &
	sleep 1
	source ~/.config/user-dirs.dirs
	firejail --join=chromium ln -sT /media/d9375f8f-423f-47a8-988f-dd0990c93109/Downloads/ $XDG_DOWNLOAD_DIR
	firejail --join=chromium ln -sT /media/d9375f8f-423f-47a8-988f-dd0990c93109/Pictures/ $XDG_PICTURES_DIR
fi
```
# Expected result
After chromium being wrapped by firejail, executing `xdg-open "https://google.com"` (or clicking links in email client, opening URL shortcut from DE/WM... etc) will open https://google.com in new tab inside the existing firejail wrapped chromium.

# Actual result / Description 
After chromium being wrapped by firejail, executing `xdg-open "https://google.com"`  (or clicking links in email client, opening URL shortcut from DE/WM... etc) will open https://google.com in new Chromium window, and yield the following errors about databases being locked.
```
[22654:22674:0613/225856.840034:ERROR:connection.cc(1954)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA auto_vacuum
[22654:22674:0613/225856.840086:ERROR:connection.cc(1954)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA journal_mode = TRUNCATE
[22654:22759:0613/225856.841769:ERROR:connection.cc(1954)] History sqlite error 5, errno 0: database is locked, sql: PRAGMA auto_vacuum
[22654:22759:0613/225856.841794:ERROR:connection.cc(1954)] History sqlite error 5, errno 0: database is locked, sql: PRAGMA journal_mode = TRUNCATE
...
```
Chromium will alert that chromium storage is corrupted/unstable. This is very annoying. Existing browsing history may lose, and I had my chromium profile really corrupted once because of this issue.

# Known workaround
Comment `private-tmp` out of `/etc/firejail/chromium.profile`.

**Comment by netblue30** [comment]
Fixed, thank you for the bug: https://github.com/netblue30/firejail/commit/62bfa2b2494e6f3b02703d3b8f1c0adebbb6759a
