### ISSUE TITLE
Possible to set runtime limit?

### ISSUE THREAD

**Issue by sknepal** [netblue30/firejail#1337]
Hi, 

I am using firejail to run bash for an online repl. The user might run python, java or other codes on the bash. Is it possible to set runtime limit for these codes so that the user for example, can be stopped from doing infinite loops etc?  Like, kill the python execution as soon as it goes over 2 minutes?

If its not possible via firejail, can you think of any other way? Please let me know. I have no idea how this can be achieved.

Thank you!

**Comment by Ferroin** [comment]
AFAIK, it's not possible with firejail, but it is possible using the ulimit builtin in bash.

For example, the following bash script will run a python script passed to it and cause SIGKILL to be sent if the total CPU time exceeds roughly 2 minutes:
```sh
#!/bin/bash
ulimit -H -t 120
exec /usr/bin/env python $@
```
Similar scripts will work for just about any interpreted language as well as mono and java.

The downside to this is that total CPU time doesn't work like most people expect it.  Put simply:
* If 2 threads in the same process both spend 1 second executing on different CPU's, the process is accounted for 2 seconds of CPU time (one second for each CPU).
* Time spent waiting on I/O may or may not be counted depending on how the I/O is performed at the kernel level.
* Time spent sleeping (for example, time spent in the time.sleep() or signal.pause() functions in Python) is not accounted against CPU time.

Assuming this is a web app, you can also do filtering in the app itself to catch obviously bad stuff like:
```python
while True:
    do_something()
```

**Comment by reinerh** [comment]
Using timeout also works:
`$ timeout timeout 1s firejail sleep 20`

**Comment by sknepal** [comment]
@reinerh I think that would timeout firejail but not the processes that are running on the bash (which is inside the jail). I would just like to timeout the processes, not firejail itself. 

Anyway, I wrote a script to monitor for processes running longer than X seconds and kill them. Put it on crontab so that it runs regularly. That seems to have solved my problem. Thank you for the responses.
