### ISSUE TITLE
Firefox within firejail interfering with pulseaudio 

### ISSUE THREAD

**Issue by ajyotirmay** [netblue30/firejail#1338]
I was using "firejail firefox" on Ubuntu 16.04.2 LTS and whenever I will play a multimedia (e.g. YouTube) in the browser, it will cause pulseaudio module to unload itself. This is the pulseaudio log generated on my system, I don't know if it will be useful in anyway: [pulseaudio log](https://pastebin.com/ENF3XGaj)

**Comment by Fred-Barclay** [comment]
Hi @ajyotirmay,
That sounds like a known problem with pulseaudio. Could you run the following in your terminal, log out and back in, and try again?
`firecfg --fix-sound`

**Comment by netblue30** [comment]
Try this fix: https://firejail.wordpress.com/support/known-problems/#pulseaudio

**Comment by ajyotirmay** [comment]
@netblue30 thanks, toggling "enable-shm" seems to be working fine.
@Fred-Barclay "firecfg --fix-sound" didn't work as "firecfg" was not found on my system.

Looks like the problem was with pulseaudio and not firejail, sorry to bother you guys.
