### ISSUE TITLE
Chromium trying to open another instance if opened in firejail

### ISSUE THREAD

**Issue by Keepco** [netblue30/firejail#1340]
Hello,

I use chromium as my default browser and firejail'ed it. However, if I open a link and I already have started chromium it'll start another instance of chromium instead of creating a new tab in the already running chromium instance, see the attached gif

![chromium](https://user-images.githubusercontent.com/8766773/27256491-a10d3f7e-53b6-11e7-8621-95080e57ced8.gif)

**Comment by netblue30** [comment]
Fixed on mainline, somebody brought it up a few days ago: https://github.com/netblue30/firejail/issues/1334

**Comment by Keepco** [comment]
Sorry, didn't see the issue. Thanks for the fix though!

**Comment by netblue30** [comment]
No problem, let me know if you run into something else.
