### ISSUE TITLE
Firefox and thunderbird are starting as root

### ISSUE THREAD

**Issue by Lemnis-kate** [netblue30/firejail#1344]
Dear people.

With Ubuntu Mate 16.04 the command "firejail firefox &" starts firefox als root.
This could not be right. With thunderbird I have the same problem.
So it can't be the profile.
With Ubuntu 16.04. that problem doesn't exists. 

Thanks for help.

**Comment by Fred-Barclay** [comment]
Hi @Lemnis-kate,
Firejail does start itself as root, but it drops these privileges when running Firefox or other applications. You can check this for yourself by running `ps -aux | grep firefox` inside your terminal.

A better explanation is at https://firejail.wordpress.com/support/frequently-asked-questions/#as-superuser
We have a discussion about it at #258.
