### ISSUE TITLE
private-bin and shells

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#1346]
Hi,

while investigating a failing tar.exp test, I found out that there is an issue with private-bin and shells.
On Debian/Ubuntu tar.exp fails, because bzip2 can't be executed. This probably fails because it can't execute the default shell. In the tar profile it allows "sh", but not for example "bash", "dash" etc, so they are not available in the private bin.
And indeed, after I added dash (my /bin/sh points to dash) to the private-bin line, the test was passing.
Adding all shells to all private-bin lines that require a shell is probably no good solution.

I'm wondering now if the symlink should be resolved and the destination binary be also copied to the private bin?

**Comment by netblue30** [comment]
I added sh,bash,dash in several profiles: https://github.com/netblue30/firejail/commit/81b61d55a3174189d3c810f645f81f0ef48f7db0

I think that's the easiest fix for now. Some time ago somebody put in a patch for private-bin to follow the links. I had to disable it after some time, apparently on some distributions firefox is a symbolic link in /usr/bin directory pointing to the place where firefox was installed, and it was breaking firefox.

I disabled the patch, currently it is a config option in /etc/firejail/firejail config:
`````
# Follow symlink for private-bin command.
# Disabled by default
# follow-symlink-private-bin no
`````

**Comment by reinerh** [comment]
Okay, thanks. I wasn't aware of the config option.
Let's keep your fix then for now.
