### ISSUE TITLE
Disallowing fchmod is incompatible with --nogroups in 0.9.46 and later

### ISSUE THREAD

**Issue by kevinoid** [netblue30/firejail#1348]
Disallowing `fchmod` via `seccomp` with `nogroups` in Firejail 0.9.46 and later results in the following error:

    $ firejail --noprofile --nogroups --seccomp=fchmod:EOPNOTSUPP echo hi
    Parent pid 18320, child pid 18322
    Error chmod: sandbox.c:114 save_nogroups: Operation not supported
    Error: proc 18320 cannot sync with peer: unexpected EOF
    Peer 18322 unexpectedly exited with status 1

I bisected the regression to commit 322ce2c.

Thanks,
Kevin

**Comment by netblue30** [comment]
Thanks for the bug!

**Comment by chiraag-nataraj** [comment]
This was fixed at some point.
