### ISSUE TITLE
Increased cpu usage on certain webpages which contain gifs on qutebrowser, luakit

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#1351]
I've encountered this behaviour on qutebrowser with the webengine backend, with the webkit backend and luakit, all built from master. All folders required by these browsers including .cache/[browser] , .config/[browser] and .local/share/[browser] are noblacklisted, created and whitelisted in their specific profiles.
I've also built firejail from trunk.
Has anyone else been encountering this ? At first I thought it was qutebrowser going bonkers and tried luakit out which was fine until I ported the qutebrowser profile to it.

**Comment by ahsis** [comment]
Animated displayed inline consume a lot of cpu as with webms. Just make a userstyle that hides gifs or wait for qutebrowser to add some sort of content blocking. Firejail probably has nothing to do with this.
