### ISSUE TITLE
Need To Allow Process Fork Whitelisting

### ISSUE THREAD

**Issue by ilikenwf** [netblue30/firejail#136]
I am unable to launch default applications (eg Transgui for transmission) with the current stable release on Archlinux, which makes downloading Linux isos somwhat more troublesome as it requires saving the torrent (or whatever other file) to ~/Downloads and then opening it externally.

At one point, I managed to launch transgui but due to the nature of the sandboxing, the configuration wasn't there since we don't have that directory whitelisted. Is this seccomp.

**Comment by netblue30** [comment]
Transmission doesn't whitelist any file or directory, all directories should be available under /home/user. What exactly is your setup?

**Comment by ilikenwf** [comment]
Firefox running in firejail, while attempting to add a torrent or magnet
link via Firefox's associations, to transmission GUI, which can either be
open or closed.

Both ways no longer work, I'd have to look at my backups and see what
version of Firejail I was running previously, but that version did work
with my filetype associations for opening things.

**Comment by netblue30** [comment]
I use transmission-gtk myself. I have firefox working in a sandbox, and transmission-gtk open in another sandbox. I grab with the mouse the magnet link and release it in the transmission window and it works.

If you click on a torrent or a magnet, firefox associations will instruct the browser to start transmission in the same sandbox. Your sandbox whitelisting should take in account the fact that you intend to run both firefox and transmission. I will investigate further.

**Comment by ilikenwf** [comment]
Ah, nice. I would use gtk if it would stop crashing (unrelated).

I didn't consider dragging - I'll have to try that.

**Comment by netblue30** [comment]
Try transmission-qt, it's the same thing, just another graphic toolkit.

**Comment by ilikenwf** [comment]
Yeah, its what I use, and despite being an xfce user it is more stable.
