### ISSUE TITLE
/usr/bin/dbus-launch inhibits --x11 server exit.  Blacklisting it seems to fix it.

### ISSUE THREAD

**Issue by caoliver** [netblue30/firejail#1378]
I'm not sure if this is documented, but some applications run dbus-launch when they start.  This grabs the containing X server, and that server persists after the desired clients exit.  The work-around I've just started playing with is to blacklist /usr/bin/dbus-launch.  So far, this seems to do the trick, and the server now exits cleanly on application exit.

Example: firejail --net=eth0 --x11 --blacklist=/usr/bin/dbus-launch firefox

**Comment by chiraag-nataraj** [comment]
Yeah, we see this with `gpg-agent` sometimes as well (although on systemd systems, you can just use `writable-run-user` to allow the program to connect to the user's instance of `gpg-agent`).

**Comment by chiraag-nataraj** [comment]
We don't really have a way to fix this at present, since as far as `firejail` is concerned, there's still a process running within the sandbox.

**Comment by Fred-Barclay** [comment]
@chiraag-nataraj Firejail processes from thunderbird always seem to stick around on my system -- maybe this is why? I do have the enigmail extension so it probably calls some gpg stuff.

**Comment by chiraag-nataraj** [comment]
Yeah, if you run `firejail --tree`, you should see what's stuck around - in your case, it's probably `gpg-agent`.
