### ISSUE TITLE
firetools_0.9.46.deb depends on libqt4-svg

### ISSUE THREAD

**Issue by jsm09a** [netblue30/firejail#1382]
I just built a firetools 0.9.46 package for Debian Stretch (from source).  When attempting to install that package, Debian Stretch refuses stating: "firetools depends on libqt4-svg" ... despite the fact that the package was built with the "qt5-default" package installed.  That same firetools deb package seems to install/run OK if "dpkg --force-depends" is used.

Should the debian control file for the firetools package be automatically updated to QT5 by the configure/make process ... or is a manual adjustment of this file required ? (... or perhaps I have more serious issues with my build process ...).

Thanks !

**Comment by reinerh** [comment]
The Debian packaging control file inside firetools currently hardcodes the dependencies: `Depends: libqtgui4, libqt4-svg`

I would recommend building the package from the Debian source (requires devscripts and build-essential), which is more flexible:
```
dget http://httpredir.debian.org/debian/pool/main/f/firetools/firetools_0.9.46-3.dsc
cd firetools-0.9.46
dpkg-buildpackage -us -uc -b
```
It will use Qt5 and have correct dependencies.
