### ISSUE TITLE
Programs with periods in their name fail to use their profile when run via symlink method

### ISSUE THREAD

**Issue by SpotComms** [netblue30/firejail#1383]
Examples: gimp-2.8.profile, idea.sh.profile

Related to #1268

**Comment by netblue30** [comment]
Probably we will have to find another way to extract the name of the application. Currently we go up to the first dot in the name.

**Comment by SpotComms** [comment]
This is the code yea? https://github.com/netblue30/firejail/blob/master/src/firejail/util.c#L557

Why does it ever need to stop at a period? Removing "*ptr2 != '.' &&" fixes this issue. Is there a weird edge case where there will exist a period after the file name? Wouldn't it just be better to split at a ' ' instead?
