### ISSUE TITLE
xdg-open not working for opening links from firejailed pidgin in firejailed chromium

### ISSUE THREAD

**Issue by Harvie** [netblue30/firejail#1386]
Default pidgin setting is to open URLs using xdg-open, but it's apparently blocked by firejail 0.9.48. So i can't click-open any links from firejailed pidgin. I understand that xdg-open may be possible security problem as it allows to launch lot of different stuff depending on system configuration, but can't firejail be somehow inherited on xdg-open process so it will only allow xdg-open to launch browsers when launched from pidgin firejail?

I know that i can probably setup method other than xdg-open in pidgin settings, but this one is default, so its' support is needed to make everything work out of box.

**Comment by netblue30** [comment]
Yes, at this moment it will probably kill xdg-open.

**Comment by Fred-Barclay** [comment]
@Harvie try copying the pidgin profile (/etc/firejail/pidgin.profile, probably) to ~/.config/firejail/, and then replace the `private-bin pidgin` line with `private-bin pidgin,xdgopen,bash,sh,grep,egrep,<browser-name>`, where <browser-name> is firefox, or google-chrome-stable, or whatever browser you want to use.

If that works and you're not using Arch, you can possibly remove bash and sh from the private-bin filter.
