### ISSUE TITLE
Blacklisted directories/files disabled (mounted) multiple times instead of once

### ISSUE THREAD

**Issue by xmikos** [netblue30/firejail#139]
If I look at `--debug` output of firejail, I can see multiple lines like this:

    Disable /usr/bin/xev
    Disable /usr/bin/xev
    Disable /usr/bin/xev
    Disable /usr/bin/xev
    Disable /usr/bin/strace
    Disable /usr/bin/strace
    Disable /usr/bin/strace
    Disable /usr/bin/strace

And of course, if I run `cat /proc/mounts | grep strace` from inside of sandbox, I can see this:

    run /usr/bin/strace tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
    run /usr/bin/strace tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
    run /usr/bin/strace tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
    run /usr/bin/strace tmpfs rw,nosuid,nodev,relatime,mode=755 0 0

So it seems disabled files/directories are mounted multiple times instead of once. I am using Arch Linux, so maybe it is somehow related to Arch which has `/bin`, `/sbin` and `/usr/sbin` symlinked to `/usr/bin` (also `/lib`, `/lib64` and `/usr/lib64` is symlinked to `/usr/lib`).

**Comment by netblue30** [comment]
Fixed.
