### ISSUE TITLE
Okular won't start the second instance - can't open more than one pdf file at the same time

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1391]
OS: Ubuntu 16.04, Firejail version from the git repository

if Okular is already running and you open the second instance, the second instance shuts down with a message:

`Couldn't register name ' "org.kde.okular-2" ' with DBUS - another process owns it already!`

The second instance starts properly without Firejail.

This is the problem because it prevents the user from viewing multiple pdf files at the same time.

**Comment by curiosity-seeker** [comment]
This works for me - see also my remarks [here](https://github.com/netblue30/firejail/issues/725#issuecomment-315777753). I'm also using the Firejail git version.

**Comment by smitsohu** [comment]
For me, running `firejail --ignore=protocol okular` solves the issue. 

What is interesting though, running `firejail --protocol=unix,inet,inet6,netlink okular` doesn't solve it. I don't understand this :)

**Comment by rekixex** [comment]
@smitsohu I gave it a try, but unfortunately it doesn't solve the problem for me.

Interestingly, when I shut down the hanging process (see #725) with Firetools, the process is still running, so I have to shut it down twice.

**Comment by smitsohu** [comment]
@rekixex Hmmm, I can't reproduce it anymore (the solution, the bug is still there).
Please forget about it :-/

**Comment by steinymity** [comment]
@rekixex I am on Debian stable and observed a similar behaviour:

    okular(3)/kdeui (kdelibs): Couldn't register name ' "org.kde.okular-3" ' with DBUS - another process owns it already!

For me, upgrading `firejail-profiles` to version 0.9.52-2 (currently in buster) fixed the issue.

**Comment by smitsohu** [comment]
If you launch several instances of okular, firejail keeps each in its own PID namespace. 

The problem is the following:
1) all names on a bus must be unique,
2) every okular instance tries to register a name on D-Bus that contains its PID,
3) PIDs are unique only _inside_ a namespace.

So when you see this error message, two instances of okular have exactly the same PID inside their sandboxes.... you can easily convince yourself by joining the sandboxes and running top.

**Comment by smitsohu** [comment]
#1784 and this issue are closely related.

Does it work when `join-or-start okular` is added to the profile? I'm away from my workstation and can't test myself in the moment.
