### ISSUE TITLE
Okular plays sound despite the --nosound argument

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#1392]

**Comment by netblue30** [comment]
My guess would be Okular sends a message outside the sandbox and somebody else is playing the sound. I'll try it out.

**Comment by chiraag-nataraj** [comment]
Is this still an issue?

**Comment by chiraag-nataraj** [comment]
@rekixex Are you using pulseaudio or ALSA (or something else)?

**Comment by chiraag-nataraj** [comment]
Going to close since the OP is no longer on Github.
