### ISSUE TITLE
Steam is unable to use its internal web browser

### ISSUE THREAD

**Issue by eomanis** [netblue30/firejail#1396]
I am on Arch Linux x86_64 with the GNOME desktop environment, and I am running Steam in firejail within a persistent sandbox home, using the Steam profile shipped by the distribution:
`/usr/bin/firejail --profile=/etc/firejail/steam.profile --private="/home/myuser/sandboxes/Steam" -- /usr/bin/steam-runtime`

While I can view my Steam library and install and play my games listed in there well enough, I am unable to browse the store, redeem gifts, or generally do anything that involves Steam using its built-in web browser.
The net effect is that any web page that Steam tries to open internally is stuck in the "page is loading" state:
![steam-news-gift](https://user-images.githubusercontent.com/5933155/28386613-673cfc06-6ccc-11e7-9cdb-07c796337b52.png)
![steam-store](https://user-images.githubusercontent.com/5933155/28386621-6c78afbc-6ccc-11e7-9d0a-3806a1fe3598.png)

When I exit Steam, a chain of processes is left behind:
`firejail --> firejail --> steamwebhelper.sh --> steamwebhelper`
![steam-leftover-processes](https://user-images.githubusercontent.com/5933155/28386632-76aef77a-6ccc-11e7-9631-69e3d67d86c3.png)
I can soft-kill the "steamwebhelper" process without problems and then everything is clean again.

I have Firefox and Chromium installed.

**Comment by SpotComms** [comment]
This was fixed a few days ago in upstream here https://github.com/netblue30/firejail/commit/2b99eb43722d91f491cef50b0e93eaf6dae21bbe

just 
`cd .config/firejail && cp /etc/firejail/steam.profile . && sed -i 's/trace/#trace/' steam.profile`
or even better install firejail-git from the AUR

**Comment by Fred-Barclay** [comment]
Thanks @SpotComms

**Comment by eomanis** [comment]
Yeah thanks SpotComms, commenting out the "tracelog" line in the profile solves the issue.
