### ISSUE TITLE
Can't set --defaultgw while using --interface option

### ISSUE THREAD

**Issue by xmikos** [netblue30/firejail#140]
I want to be able to pass my own _veth_ device to firejail by using `--interface=veth_b` option, but I am unable to set default gateway in sandbox. When I use `--defaultgw=some_address`, firejail exits with this error:

    Error: option --defaultgw requires at least one network to be configured

**Comment by xmikos** [comment]
I suppose there will be similar problem with `--ip` option (but at least I can set ip on _veth_ interface before adding it to sandbox, this is not possible with routes).

**Comment by netblue30** [comment]
Fixed --defaultgw. I put --ip and a number of other options on my todo list to go into an future release. Thanks.
