### ISSUE TITLE
Xpra killing emacs daemon on exit

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1400]
When I use `x11 xpra` with e.g. Mutt (something with a temporary xpra instance which is created upon launch), Xpra ends up killing the emacs daemon I start outside of the sandbox when Mutt exits.

- Is this intended behavior?
- If it is, how do I modify it or prevent this from happening?

**Comment by chiraag-nataraj** [comment]
Just to clarify, this does not happen if I start an xpra instance independently and then pass the display as an environment variable to firejail.

**Comment by chiraag-nataraj** [comment]
Even weirder...if I terminate existing Xpra instances, it also kills emacs. So I suppose this isn't a firejail-specific thing (although the temporary nature of the Xpra daemon in that case exacerbates the problem).

**Comment by chiraag-nataraj** [comment]
I will post this to the xpra bug tracker since I don't think this is related to firejail.

**Comment by netblue30** [comment]
Found something funny: if I add my user to tty group it solves the problem. It seems to be fixing the crash on the latest Ubuntu derivatives such as xubuntu. It could be something with the way xorg is set up.

**Comment by chiraag-nataraj** [comment]
Hmmm okay, I will try that.
