### ISSUE TITLE
ARP cache pollution when using net namespaces.

### ISSUE THREAD

**Issue by caoliver** [netblue30/firejail#1406]
On starting a jail with a network namespace, firejail sends an ARP request to determine if the chosen IP address is already in use, but it sends that request with the jail's MAC, but the host's IP.  This pollutes the ARP cache on boxes that are listening to that broadcast with a bogus MAC/IP pair resulting in delays when trying to reach the host via the net.  The free IP for the jail should be determined on the host and communicated to the jail subsequently upon its creation.

**Comment by netblue30** [comment]
I put a fix in, you can give it a try. I'm doing the probing with a IP address of 0.

**Comment by caoliver** [comment]
On Thu, 27 Jul 2017 17:20:25 +0000 (UTC)
netblue30 <notifications@github.com> wrote:

> I put a fix in, you can give it a try. I'm doing the probing with a IP address of 0.

For my initial testing, this seems to work.  I'll put this on the rest of my boxes and see how I go.

BTW: RFC 5227 didn't exist when I was last hacking TCP/IP; thanks for the reading material.

Sorry that I whinge so much, but I suppose that you get lots of whinging people when you write a generally useful tool.  ;-)

Thanks and Cheers!

-- 
Christopher Oliver <current.input.port@gmail.com>

**Comment by netblue30** [comment]
Actually, I've just found about it now. Searching for the original ARP RFC, the new one came up in Google search. Keep an eye on it, we'll reopen it if necessary. Thanks for the bug.
