### ISSUE TITLE
noroot not effective with ssh?

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1413]
So I'm currently trying to sandbox ssh and I'm running into something very interesting.
I use the following profile:
````
private-dev
private-tmp

shell none
x11 none
ipc-namespace
caps
noroot
````
When I start ssh with this profile, I would think that ssh (and anything spawned by it) would not have access to root. However, I am able to log in as usual and use `sudo su` to gain root privileges. Why is is this happening?

[Edit] I know that I'm inside the jail because I can use `top` to note that I can only see the `ssh` process and the `bash` spawned by it.

**Comment by SpotComms** [comment]
The ssh server is sshd not ssh, but you say you're sandboxed. And even then wouldn't the .service default to the full /usr/bin path? Did you edit the sshd .service and create a sshd.profile? Am I missing something?

**Comment by chiraag-nataraj** [comment]
As to your first question, I did not - I still have to manually stop the command when interactively restarting it, but it spawns properly when booting up.

I will try `nonewprivs`, but I don't see why I need that in this profile when I don't need it for any other profiles for it to be effective. Is it because I have to spawn it as root to begin with?

**Comment by chiraag-nataraj** [comment]
Interesting. Using `nonewprivs` indeed worked, and I can't escalate within the `ssh` session. Thanks @SpotComms!
