### ISSUE TITLE
Feature: Easier alternative to list of syscalls for --seccomp: add pre-defined syscall groups 

### ISSUE THREAD

**Issue by topimiettinen** [netblue30/firejail#1417]
It's not so easy to use seccomp feature because there are hundreds of system calls to be managed. I'm proposing to add a simpler way to prepare seccomp filters, where the user can construct the filter by
using predefined system call groups or sets. Systemd uses prefix '@' to distinguish system call groups, for example:
`@debug`: Debugging, performance monitoring and tracing functionality (`ptrace(2)`, `perf_event_open(2)` and related calls) 
`@obsolete`: Unusual, obsolete or unimplemented (`create_module(2)`, `gtty(2)`, ...)
`@privileged`: All system calls which need super-user capabilities
`@default`: built-in default list

For example, a firejail user could simply specify `--seccomp=@privileged` to blacklist all privileged system calls. This is much easier to use than long list of system calls.

As a bonus, I think such seccomp lists would also simplify firejail design, now the lists of syscalls are somewhat duplicated across default/32/64 vs. sandboxing for fcopy etc. The lists can specify other lists, so for example `@default` could contain both `@privileged `and `@obsolete`.

**Comment by netblue30** [comment]
Go for it! @default list will also close #1366

**Comment by topimiettinen** [comment]
Implemented in 34ee8e03.
