### ISSUE TITLE
Websocket and Firejail

### ISSUE THREAD

**Issue by sknepal** [netblue30/firejail#1418]
Hi,

I am using Tornado websocket via a wrapper called Terminado. With xterm.js, I am exposing a sandboxed (using Firejail) terminal to the web. When I expose a normal terminal (without sandboxing), the terminal process gets killed when user closes the connection/browser tab. But, when I expose a Firejailed bash, Firejail process still lingers on even after the user closes his tab and the socket connection is closed. So over time there are like 100s of earlier Firejail process still running on. Is there any solution to this?

Thank you!

**Comment by netblue30** [comment]
I'll take a look, thanks.

**Comment by sknepal** [comment]
I was able to figure out the solution with the help of Terminado's author [here](https://github.com/takluyver/terminado/issues/37). Terminado, by default, terminates the parent process which does not appear to work with Firejail. So I just used subprocess with a call to `firejail --shutdown` and passed the parent PID to it. That seems to shut everything down. Thank you!
