### ISSUE TITLE
mutt + gpg indefinitely hangs

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1422]
Because of pid namespaces, `gpg` is unable to find the running instance of `gpg-agent`, so it creates a new one. Then, since that process is running in the sandbox, the sandbox never closes. I initially thought this was a bug with my profile, but it turns out I have this problem with the default profile as well.

**Comment by chiraag-nataraj** [comment]
Okay, this happened after firejail 0.9.48, because the version I've installed from the repository still works, but the development version I forked to get `xpra` working again ends up breaking this. It's not the `xpra` stuff because not launching `mutt` in the X11 sandbox still produces the same effect/issue.

**Comment by chiraag-nataraj** [comment]
Okay, this is an instance of #725.

**Comment by SpotComms** [comment]
I wonder if we can add "join-or-start gpg" to both gpg.profile and gpg-agent.profile so that they can see each other. I just don't know what effects that'll have cross-user.

**Comment by chiraag-nataraj** [comment]
I don't know if that would solve this case, though, where I start another program which then happens to call `gpg` (rather than me launching it separately).

**Comment by chiraag-nataraj** [comment]
Fixed by using `writable-var-run` to allow access to the systemd-instantiated gpg-agent socket.
