### ISSUE TITLE
[profile request] rambox

### ISSUE THREAD

**Issue by fuelflo** [netblue30/firejail#1425]
Hey,

as the franz messenger is not really maintained anymore I was looking for an alternative and https://github.com/saenzramiro/rambox is quite usable.

Could someone make a profile for rambox?

That would be great!
Cheers

**Comment by fuelflo** [comment]
Okay, I did a quick and dirty fix and at the moment it seems to working for rambox, too.
Maybe someone could have a look remove the unnecessary Franz references and add it to the default profiles?

`## profile madre from Franz profile

# Persistent global definitions go here
include /etc/firejail/globals.local

# This file is overwritten during software install.
# Persistent customizations should go in a .local file.
include /etc/firejail/rambox.local

# Franz profile
noblacklist ~/.config/Rambox
#noblacklist ~/.cache/Franz
noblacklist ~/.pki
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc

caps.drop all
netfilter
nonewprivs
noroot
protocol unix,inet,inet6,netlink
seccomp
#tracelog

whitelist ${DOWNLOADS}
mkdir ~/.config/Rambox
whitelist ~/.config/Rambox
#mkdir ~/.cache/Franz
#whitelist ~/.cache/Franz
mkdir ~/.pki
whitelist ~/.pki

include /etc/firejail/whitelist-common.inc`

**Comment by Fred-Barclay** [comment]
Added in https://github.com/netblue30/firejail/commit/88d919ce9b9d0be693366b25eb1c4f3647c023d3, thanks!
