### ISSUE TITLE
Don't leak user/group information

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#143]
In the case that one uses --private-etc and doesn't include /etc/group, some permissions will be missing for some actions. But one may want to

1. not leak info on users and their groups and permissions (also privacy; users have real names)
2. have a more restricted environment in the sandbox, no unnecessary permissions

I see that you could use --bind, but that only works with root permissions.
Could the temporary groups be done without root permissions?

**Comment by netblue30** [comment]
Let me think about it, probably we can do it without root permission.

**Comment by netblue30** [comment]
Fixed! The sandbox is coming by default with a /home directory with only the current user, and clean /etc/passwd and /etc/group files.
