### ISSUE TITLE
improve debug messages

### ISSUE THREAD

**Issue by Boruch-Baum** [netblue30/firejail#1455]
When I was recently debugging a problem for an ncurses program using `--debug`, I noticed some error messages flashing briefly in the ncurses screen, but it didn't appear among the other debug output when exiting.

Please consider having the debug option output to a file instead of STDERR / STDOUT since those can easily become unreadable. Part of the idea would be to separate the STDERR output of firejail from any STDERR output of the program being sandboxed.

**Comment by chiraag-nataraj** [comment]
You can use `--output=logfile` to send all output to a log file.

**Comment by Boruch-Baum** [comment]
I tried that, and it wasn't acting that way. If it should be acting that way, then I have another issue to open. Stay tuned a few minutes . . .

**Comment by netblue30** [comment]
I think the fix is in, if necessary we'll reopen the issue.

We have now --output and --output-stderr. The last one also redirects stderr to the file. Ncurses programs should work fine now with --output. Thanks.
