### ISSUE TITLE
improve exception handling / dynamic filter customization

### ISSUE THREAD

**Issue by Boruch-Baum** [netblue30/firejail#1456]
How about a feature that instead of firejail enigmatically denying some program some access, that it display a pop-up telling the user what is happening, and allowing the user to optionally permit the access just this once, or permanently?

The advantages include:

1) Letting a user know specifically what the program is trying to do. A user (or a security researcher) might decide that a program qualifies as malware based upon the specific pop-up messages from firejail.

2) Making it easier for users to customize profiles. This will also make it MUCH easier for people to accept and adopt firejail, because (in my experience) currently the program requires patience and frustration-tolerance.

The disadvantages might include:

1) well, it's more work

2) pop-ups maybe implemented differently by different distributions. Firejail could just decide upon one as a hard dependency. That might not always look seamless for users' desktop themes, but it would be easiest.

**Comment by netblue30** [comment]
> firejail enigmatically denying some program some access

It is not fireajil, it is the kernel. What firejail does is to configure seccomp and namespaces in Linux kernel and after that it goes to sleep. When access to a file is denied, only the kernel knows about it.

We do have a --tracelog option that works in user space for files specifically blacklisted. It sends a message to syslog announcing the access attempt, but like anything else in user space you can get around it.

**Comment by Boruch-Baum** [comment]
Oh. That means what I was suggesting would entail a lot more work. Firejail would have to intercept somehow the kernel's complaint, and then act.

**Comment by Ferroin** [comment]
FWIW, I think if you have auditing enabled, you can use that to get info on access denials, and that can't be bypassed.  Doesn't help much of course with the possibility of allowing access, but it least it could improve the logged messages regarding the denied access.
