### ISSUE TITLE
Unable to write mail in mutt (using emacsclient)

### ISSUE THREAD

**Issue by Boruch-Baum** [netblue30/firejail#1457]
For firejail version 0.9.48 in debian, using mutt configured to edit with emacs client, with the command line invocation:

    firejail --debug --noblacklist=/usr/bin/emacsclient --noblacklist=/tmp mutt

When attempting to open an edit buffer, mutt displays an error message about being unable to open emacsclient for a temp file in /tmp, and mangles the ncurses screen display. Upon exiting, the terminal display shows the following additional message:

    emacsclient: could not get terminal name
    emacsclient: error executing alternate editor ""

emacsclient is a popular way of calling emacs, because it connects to an already running instance, saving what can be a wait for us impatient people as emacs loads.

It may even be a good idea to add a profile for emacsclient. Maybe it would be sufficient to just be call to the already-existing emacs profile.

**Comment by chiraag-nataraj** [comment]
Hmmm...I have the same setup (I use emacsclient within mutt). And yet it works for me. Can you post the `mutt` profile you're using?

**Comment by Boruch-Baum** [comment]
No, I'm not going to start redacting all the personal information from that file.

Since my report was four months ago, and you report that it is now working for you, I tried it again. The situation is only slightly better in that the ncurses display isn't being corrupted and upon exit, the terminal display does not need to be reset after exiting mutt. However, for me, mutt still fails to launch the emacsclient.

BTW, in the intervening four months, not only  has firejail been under development  but debian has upgraded its versions of mutt, and has changed the underlying codebase from neomutt back to the original mutt project. I'm using debian's latest-and-greatest version of mutt, 1.9.1 (2017-09-22). At this point, the version of firejail that I have installed is not the latest-and-greatest git development version; it's the debian version 0.9.50.

**Comment by chiraag-nataraj** [comment]
By the mutt profile, I meant the firejail profile, not your mutt configuration. My apologies if there was a misunderstanding. I am on Debian sid/experimental, so I most likely have the same versions of the programs you have. Let's figure this out. Also, another question: are you using emacs in the terminal or in an X11 window?

**Comment by Boruch-Baum** [comment]
1) We're good - there was a misunderstanding, but no need to apologize.

2) There is no mutt profile in my ~/.config/firejail directory, and /etc/firejail/mutt.profile is attached. It needed to renamed to foo.txt in order for github to allow it to be uploaded. Performing a stat on the original shows it was modified last on 2017-09-23 22:18, which matches the time-stamp of the last apt update for the firejail package on my system, so it should be an unmodified version, but have a look.

3) As of today, my firejail version is debian 0.9.50-3, and in a few minutes my mutt version should bump up to  neomutt 20171215+dfsg.1-1 (remember: up until a few weeks ago, debian's version of mutt was really neomutt).

4) My emacs loads as either 'emacs-nox' or 'emacs -nw', and starts an emacs server daemon. The clients run either in a true linux terminal (often within tmux), or in a terminal emulator similar to xterm (and pretty much always within tmux).

**Comment by Boruch-Baum** [comment]
[mutt_profile.txt](https://github.com/netblue30/firejail/files/1568679/mutt_profile.txt)

**Comment by chiraag-nataraj** [comment]
> There is no mutt profile in my ~/.config/firejail directory, and /etc/firejail/mutt.profile is attached. It needed to renamed to foo.txt in order for github to allow it to be uploaded. Performing a stat on the original shows it was modified last on 2017-09-23 22:18, which matches the time-stamp of the last apt update for the firejail package on my system, so it should be an unmodified version, but have a look.

Cool. Just wanted to make sure you're not using a custom profile.

> As of today, my firejail version is debian 0.9.50-3, and in a few minutes my mutt version should bump up to neomutt 20171215+dfsg.1-1 (remember: up until a few weeks ago, debian's version of mutt was really neomutt).

I presume you're following all the default updates, so you probably have mutt version 1.9.2 (compiled on 2017-12-15) and firejail version 0.9.52.

> My emacs loads as either 'emacs-nox' or 'emacs -nw', and starts an emacs server daemon. The clients run either in a true linux terminal (often within tmux), or in a terminal emulator similar to xterm (and pretty much always within tmux).

Okay, so there's the difference. I usually load `emacs` in an X11 window. I also start a server daemon. Let me try loading `emacs` within the terminal instead of using the graphical version and see if it works.

**Comment by chiraag-nataraj** [comment]
I just got `emacs` to load perfectly well in the terminal using my profile. Can you try using the profile I've attached and see what happens?
[mutt.txt](https://github.com/netblue30/firejail/files/1609997/mutt.txt)

**Comment by chiraag-nataraj** [comment]
This updated profile also works (and re-enables a lot of crap I had disabled at some point...)
[mutt.txt](https://github.com/netblue30/firejail/files/1610000/mutt.txt)

**Comment by chiraag-nataraj** [comment]
Hey @Boruch-Baum! Just wondering if you ever had the chance to try the profiles I attached (or if this is still an issue for you).

**Comment by Boruch-Baum** [comment]
Sorry, no, it got to be too much of a hassle, so I dropped firejail from use with mutt, and never got back to testing it.

**Comment by chiraag-nataraj** [comment]
No worries. If you want to debug this further, feel free to reply after testing the profiles :slightly_smiling_face:

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this, but @Boruch-Baum: feel free to re-open if you still have this issue and want to debug further.
