### ISSUE TITLE
option output=logfile mangles screen display for ncurses programs (ie. mutt)

### ISSUE THREAD

**Issue by Boruch-Baum** [netblue30/firejail#1458]
references:
[1] [@chiraag-nataraj's comment to issue 1455](https://github.com/netblue30/firejail/issues/1455#issuecomment-321738549)

For firejail version 0.9.48 in debian, using mutt configured to edit with emacs client, with the command line invocation:

    firejail --debug  --output=~/firejail.log --noblacklist=/usr/bin/emacsclient --noblacklist=/tmp mutt

1] The initial ncurses display in mutt displays partially and mangled.

2] Exiting mutt does not return to a $PS1 prompt until pressing RET.

3] The log file includes a mixture of output from firejail and from what should have been the mutt ncurses display, including control characters.

**Comment by netblue30** [comment]
Bug! I was also redirecting stderr to the output file, and this was breaking ncurses screen. Thanks for the bug, I put a fix in git.
