### ISSUE TITLE
Mutt fails to read mail attachments (using lynx / gnu highlight)

### ISSUE THREAD

**Issue by Boruch-Baum** [netblue30/firejail#1459]
For firejail version 0.9.48 in debian, using mutt configured to edit with emacs client, with the command line invocation:

    /usr/bin/mutt

Attempting to read any email with an inline attachment fails because of some restriction in the default firejail profile for mutt's default pager (lynx) or a custom plug-in (gnu highlight).

Here's some screen output from one email:
~~~~
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [abo-abo/swiper] counsel-find-file-cd-bookmark-action not showing bookmarks (#1135)

[-- Autoview using lynx -restrictions=all -dump -force-html '/tmp/mutt-7506-572869149462463798' --]
Blacklist violations are logged to syslog
^[]0;firejail /usr/bin/lynx -restrictions=all -dump -force-html /tmp/mutt-7506-572869149462463798 ^GParent pid 8501, child pid 8502

Parent is shutting down, bye...
[-- Autoview stderr of lynx -restrictions=all -dump -force-html '/tmp/mutt-7506-572869149462463798' --]
Reading profile /etc/firejail/lynx.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

Can't Access `file://localhost/tmp/mutt-7506-572869149462463798'
Alert!: Unable to access document.

lynx: Can't access startfile
~~~~

And here's how it reacts to an inline patch attachment:
~~~~
[-- Attachment #2: w3m-window-system.patch --]
[-- Type: text/x-diff; charset=us-ascii, Encoding: 7bit, Size: 3.6K --]

[-- Autoview using highlight -Oansi  '/tmp/w3m-window-system.patch' --]
Blacklist violations are logged to syslog
^[]0;firejail /usr/bin/highlight -Oansi /tmp/w3m-window-system.patch ^GParent pid 9521, child pid 9522

Parent is shutting down, bye...
[-- Autoview stderr of highlight -Oansi  '/tmp/w3m-window-system.patch' --]
Reading profile /etc/firejail/highlight.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
highlight: Could not read input file:
/tmp/w3m-window-system.patch
~~~~

**Comment by Boruch-Baum** [comment]
I tried creating empty dummy profiles for mutt, lynx and highlight in my ~/.config/firejail directory, which succeeded in making the attachments visible . . . BUT the emails still display indications that firejail is being used! This may be because internally mutt may not be calling lynx directly.

At the top of the attachment text:
~~~~
[-- Autoview using lynx -restrictions=all -dump -force-html '/tmp/mutt-11915-14238489903687026758' --]
^[]0;firejail /usr/bin/lynx -restrictions=all -dump -force-html /tmp/mutt-11915-14238489903687026758 ^G   
~~~~
And after the end of the attachment text:
~~~~
Parent pid 11952, child pid 11953

Parent is shutting down, bye...
~~~~

**Comment by Boruch-Baum** [comment]
Upon looking a bit deeper, the email attachments are still being slightly mangled, ie. text dropped, and text not diplayed properly.

**Comment by chiraag-nataraj** [comment]
So I don't know exactly what setup you use, but here's what I use, which seems to work pretty well:

* Use a directory under `/tmp/user/1000/` for all of `mutt`'s temporary files (composing emails, reading emails, etc).
* Use an emacs socket that is under `/tmp/user/1000/` as well (so that it's easily accessible by `mutt`).
* Set up my mailcap with the proper programs.

Everything seems to just work with this setup. Mutt is just calling whatever you put in your `.mailcap` (or in `/etc/mailcap` if you don't have a personal one), so if it's using firejail when it shouldn't be, you should look there. I don't see the point of using firejail for that since it's always been run inside of mutt anyway (so it's already jailed).

**Comment by chiraag-nataraj** [comment]
Also, this may be happening because you ran `firecfg`. Without more info, it's hard to debug.

**Comment by chiraag-nataraj** [comment]
@Boruch-Baum I presume you're still having this problem. Have you tried my solution above?

**Comment by Boruch-Baum** [comment]
Hi. No, what I did was drop using firejail for mutt; I need mutt too much too often without that issue, and am investing my time with other projects at this point. I don't remember whether I ran firecfg, but I do remember that I was using the symbolic links created / installed by the package.
