### ISSUE TITLE
Consider whitelisting ~/.config/user-dirs.dirs

### ISSUE THREAD

**Issue by brunonova** [netblue30/firejail#146]
The file `~/.config/user-dirs.dirs` is used by applications to determine the actual names of the Documents, Music, ... folders in the user's locale.

So, consider whitelisting that file by default in the profiles and making it read-only, possibly by adding the following to `whitelist-common.inc`:

```
whitelist ~/.config/user-dirs.dirs
read-only ~/.config/user-dirs.dirs
```

**Comment by netblue30** [comment]
Done!
