### ISSUE TITLE
Cannot execute file with .sh extension in /usr/bin

### ISSUE THREAD

**Issue by icasdri** [netblue30/firejail#1464]
With a (completely) *non-blacklisted* `/usr/bin`:
* a script with `.sh` extension (for instance `/usr/bin/myscript.sh`) with proper execute bit and shebang `#!/bin/sh` will **fail** to execute with `Permission denied`.
* but the *exact same* script named without an `.sh` extension (for instance `/usr/bin/myscript`) will work just fine.

Unfortunately, there are some programs in `/usr/bin` like `IntelliJ IDEA` (`/usr/bin/idea.sh`) that have `.sh` extensions, and thus fail to start inside a firejail.

**Comment by SpotComms** [comment]
I fixed this in master #1383

**Comment by icasdri** [comment]
Ok. Thanks for the fix!
