### ISSUE TITLE
Can't access computer:/// from PCMan File Manager

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1467]
When you navigate to computer:/// location in PCMan File Manager, you get 'Operation not supported'. This prevents access to hard disk partitions from the file manager.

You can use the `--noprofile` argument to workaround the problem.

OS: Ubuntu 16.04, Firejail version from the git repository

**Comment by netblue30** [comment]
I've been able to reproduce it! Go in /etc/firejail/pcmanfm.profile and comment out "net none" line (add a #). I'll put a fix in later today. Thanks for the bug.

**Comment by rekixex** [comment]
@netblue30 No problem. ;)

Maybe you could add to manpage that `--protocol=unix` can be used as alternative, since `--net=none` sometimes causes troubles?

This is currently stated about `--net=none`:

```
--net=none
              Enable  a  new,  unconnected  network  namespace. The only interface
              available in the new namespace is a  new  loopback  interface  (lo).
              Use this option to deny network access to programs that don't really
              need network access.
```

**Comment by Ferroin** [comment]
I would actually suggest adding something along the lines of:
```
'--net=none' has a very high probability of breaking arbitrary desktop applications.  As a result of this, 
unless you really know what you're doing, you probably want '--protocol=unix' instead for graphical
applications.```

**Comment by netblue30** [comment]
Added:

`````
       --net=none
              Enable a new, unconnected network namespace. The only interface
              available in the new namespace  is  a  new  loopback  interface
              (lo).   Use this option to deny network access to programs that
              don't really need network access.

              Example:
              $ firejail --net=none vlc

              Note: --net=none could crush the application on some platforms.
              In these cases, it can be replaced with --protocol=unix.
`````
