### ISSUE TITLE
Skype deletes pulseaudio shm files

### ISSUE THREAD

**Issue by ValdikSS** [netblue30/firejail#147]
Hi!
If I run skype with the bundled profile, it would delete pulseaudio shm files in /dev/shm/ on start and the sound would break for fresh started applications.

**Comment by netblue30** [comment]
This is a known PulseAudio problem. Do like this:
`````
$ mkdir -p ~/.config/pulse
$ cd ~/.config/pulse
$ cp /etc/pulse/client.conf .
$ echo "enable-shm = no" >> client.conf
`````
and restart your computer.
