### ISSUE TITLE
whitelist /dev/serial

### ISSUE THREAD

**Issue by kdalgain** [netblue30/firejail#1474]
Hi,

I use a private instance of Android Studio and whould like to connect a smartphone.

As I understand, the ``private-dev`` directive deny access to ``/dev/serial`` or ``/dev/ttyACM0``. And, a workaround is to use some ``whitelist`` directives.

Thus, I replaced ``private-dev`` with
```
whitelist /dev/dri
whitelist /dev/full
whitelist /dev/log
whitelist /dev/null
whitelist /dev/ptmx
whitelist /dev/pts
whitelist /dev/random
whitelist /dev/shm
whitelist /dev/snd
whitelist /dev/tty
whitelist /dev/urandom
whitelist /dev/zero
whitelist /dev/serial
whitelist /dev/ttyACM0
```

Now, if I plug the mobile and start a _firejail_ session, it seems to work:
```
$ ls /dev/
dri   null  pts     serial  snd  ttyACM0  zero
full  ptmx  random  shm     tty  urandom
```

But it's not the case if I first start a _firejail_ session and next plug the mobile:
```
$ ls /dev/
dri  full  null  ptmx  pts  random  shm  snd  tty  urandom  zero
```

Regards,
Krin D.

**Comment by netblue30** [comment]
Once you start the sandbox, you cannot bring in new files in the whitelist. It is a limitation of the current whitelisting technology.
