### ISSUE TITLE
Question regarding symlinks and firejail

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#1478]
I have most of my personal dotfiles in a single folder for backup ease. Related to this discussion is the result of the following two commands:
```
ln -s ~/.config/pers/wm ~/.config/fontconfig
ln -s ~/.config/pers/app/qute ~/.config/qutebrowser
```
+ the wm folder contains fonts.conf
+ the qute folder contains files that usually are in the qutebrowser profile directory

+ when not using firejail, when launched qutebrowser reads the font configuration right.
+ when using firejail and having .config/fontconfig/ an actual folder containing fonts.conf, qutebrowser reads the font configuration right

My issue appears when ~/.config/fontconfig is a symlink, even though it doesn't appear to be an issue with ~/.config/qutebrowser being one.

Here is the whole profile current profile I use:

```
noblacklist ~/.config/qutebrowser
whitelist ~/.config/qutebrowser
noblacklist ~/.config/pers/app/qute
whitelist ~/.config/pers/app/qute
noblacklist ~/.config/pers/wm
whitelist ~/.config/pers/wm
whitelist ~/dl

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/whitelist-common.inc

hosts-file ~/.tmp/hosts
caps.drop all
dns 208.67.222.222
dns 208.67.220.220
ipc-namespace
machine-id
netfilter
no3d
nogroups
noroot
nonewprivs
nosound
novideo
protocol unix,inet,inet6,netlink
seccomp

private-dev
private-tmp
noexec ${HOME}
noexec /tmp
```

**Comment by chiraag-nataraj** [comment]
Closing this since the user who opened it closed their Github account. If someone wants to re-open, feel free.
