### ISSUE TITLE
Feature: switch/config option to block secondary architectures

### ISSUE THREAD

**Issue by topimiettinen** [netblue30/firejail#1479]
Currently Firejail installs seccomp filters for secondary architectures, but they are not strict, probably to avoid breaking mixed architecture setups or non-native plugins.

Add a feature for a new (opt-in) command line switch and config file option to block secondary architectures entirely. Also block changing Linux execution domain with personality() system call for the primary architecture.

**Comment by netblue30** [comment]
Yes, add them in!
