### ISSUE TITLE
firecfg error if /usr/local/bin does not exist

### ISSUE THREAD

**Issue by MiscDev** [netblue30/firejail#1480]
Some modern distros like [Solus](https://solus-project.com/) do not have a /usr/local directory by [default](https://www.reddit.com/r/SolusProject/comments/6u3txx/no_usrlocal_hierarchy_on_solus/). 

Running `sudo firecfg` results in error messages if /usr/local/bin does not exist. Should firecfg create the folder if it isn't there?

**Comment by SpotComms** [comment]
Even if it creates it, won't it not be in the PATH? So then it'll also have to edit or ask the user to edit /etc/profile. But then where will it place it? And if it does it automatically then there are issues with placement and what not. Adding a firejail specific path could close this and [this](https://github.com/netblue30/firejail/issues/1450#issuecomment-321440484)

**Comment by netblue30** [comment]
I think they already have it in $PATH. This is our bug. Fixed in git: https://github.com/netblue30/firejail/commit/ecf0794d2eae0201e9888e7b9228f8fef3e94fc6
