### ISSUE TITLE
xpra window isn't displaying / xpra-extra-params broken in firejail-git

### ISSUE THREAD

**Issue by cryzed** [netblue30/firejail#1486]
Recently the `x11 xpra` option seemingly has stopped working. The application still seems to be starting correctly, however an actual window is never displayed. With Discord for example, it displays the icon in the tray, however the window can not be brought up by clicking on it.

I'm running Arch Linux with `xpra-winswitch 2.1.1-1` and `firejail 0.9.48-1` in KDE. Disabling the compositor does not make a difference. My user is part of the `xpra` group.

**Comment by SpotComms** [comment]
Is this different from #1405 fixed by #1415?

**Comment by cryzed** [comment]
That works, thank you. I was searching for open issues regarding this problem, that's why I couldn't find it.

**Comment by cryzed** [comment]
@SpotComms before I open a new issue: is it known that enabling the `xpra-extra-params` option is broken? When simply uncommenting the default (--dpi 96) I get the following error:

`firejail: x11.c:996: x11_start_xpra_new: Assertion `server_argv[spos-1] == NULL' failed.`

**Comment by SpotComms** [comment]
> `firejail: x11.c:996: x11_start_xpra_new: Assertion `server_argv[spos-1] == NULL' failed.`

@chiraag-nataraj have you encountered that?

**Comment by chiraag-nataraj** [comment]
@SpotComms Yes I have (see #1404 - I never got any replies and decided to focus on fixing the issue of xpra not attaching instead).

**Comment by VladimirSchowalter20** [comment]
@cryzed `xpra-extra-params` is broken when used with `xpra-attach yes` simultaneously. both options work when used alone. This is bug in firejail I think.

To workaround this you can set  `xpra-attach yes` in `fiejail.config` keep `xpra-extra-params` and set dpi through xpra own config in `/etc/xpra/conf.d/30_picture.conf`

**Comment by VladimirSchowalter20** [comment]
Also with `xpra-attach yes` firejail config some apps lose window theming on my machine. Setting `attach=yes` in xpra.conf works good.

**Comment by xelxebar** [comment]
@ghost
Are you sure setting `attach=yes` in `xpra.conf` does what you want? On my machine it causes the xpra session to remain open after cloing the program window. I have to do a manual `xpra stop` to kill it. This isn't a problem however with `xpra-attach yes` in `firejail.config`.

**Comment by chiraag-nataraj** [comment]
Fixed in 2d3c4e43a14a6ee06f90758a88dfbd57ca394046
