### ISSUE TITLE
Restrictive umask breaks subdirectory whitelisting

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#149]
Allow me to reopen #121 (I don't know if you get notifications for closed issues, I'm new) as I have more info now.

Basically the problem is that when you whitelist a subdirectory, then the topmost directory is owned by root. When whitelisting the topmost directory only, it is owned by the user.
Now with a more restrictive umask, the directory becomes inaccessible, since owned by root and only root has the rights.

```
$ umask 0022
$ firejail --whitelist=.config/
[anon@jail ~]$ ls -ld .config/
drwx------ 22 anon anon 4096 Nov 18 22:20 .config/

$ firejail --whitelist=.config/deadbeef/
[anon@jail ~]$ ls -ld .config/
drwxr-xr-x 3 65534 anon 60 Nov 19 18:48 .config/


$ umask 0077
$ firejail --whitelist=.config/
[anon@jail ~]$ ls -ld .config/
drwx------ 22 anon anon 4096 Nov 18 22:20 .config/

$ firejail --whitelist=.config/deadbeef/
[anon@jail ~]$ ls -ld .config/
drwx------ 3 65534 anon 60 Nov 19 18:48 .config/
```

**Comment by netblue30** [comment]
Yes, this is a bug. Thanks!

**Comment by netblue30** [comment]
I think I've fixed it. Give it a try, and if necessary I'll reopen it. Thanks.

**Comment by avoidr** [comment]
You did fix the bug, but now you ignore umask by setting perms to 0755 regardless. It was enough to just change the owner from root to user, which I think would be better that way. If you could only change the ownership and leave permissions alone, that would be great!

And thanks for the fix nonetheless. You're fast and I like what you do.

**Comment by avoidr** [comment]
This should do it.
```
diff --git a/src/firejail/fs_whitelist.c b/src/firejail/fs_whitelist.c
index fccb827..740bdab 100644
--- a/src/firejail/fs_whitelist.c
+++ b/src/firejail/fs_whitelist.c
@@ -27,12 +27,9 @@
 #include <fcntl.h>
 #include <errno.h>
 
-static int mkpath(const char* path) {
+static int mkpath(const char* path, mode_t mode) {
        assert(path && *path);
        
-       // create directories with a 0755 mode
-       mode_t mode = 0755;
-       
        // create directories with uid/gid as root or as current user if inside home directory
        uid_t uid = getuid();
        gid_t gid = getgid();
@@ -142,7 +139,7 @@ static void whitelist_path(ProfileEntry *entry) {
        }
        
        // create the path if necessary
-       mkpath(path);
+       mkpath(path, s.st_mode);
 
        // process directory
        if (S_ISDIR(s.st_mode)) {       
@@ -417,7 +414,7 @@ void fs_whitelist(void) {
                        struct stat s;
                        if (stat(entry->link, &s) != 0) {
                                // create the path if necessary
-                               mkpath(entry->link);
+                               mkpath(entry->link, s.st_mode);
 
                                int rv = symlink(entry->data + 10, entry->link);
                                if (rv)
```
Sorry for infinitely sucking cocks, but I want to try and commit it or pull request it or omg I'm a newb, lol.

**Comment by netblue30** [comment]
All fine, I had to update the code again and set the "x" bit mode for directories.

**Comment by avoidr** [comment]
Hm, I don't see why, though. The permissions and owners were *exactly* the same as originally, now. I don't see why you'd need to change anything about them.
