### ISSUE TITLE
Better way to investigate syscalls

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1490]
I set up a customized seccomp list for mutt (I know, they break pretty easily) and the new version of Mutt broke it. But when I run it, there is no relevant output in the audit logs (I used `sudo ausearch --raw` since I'm using Debian). I don't understand how that could be happening though...shouldn't any failed syscalls register in the system log?

[Edit] This is even weirder. It seems mutt _hasn't_ been updated, which means firejail's syscall list spontaneously broke with Mutt, for no apparent reason. I'm going to try with the latest commit. Yup, I have this issue with the latest commit as well.

**Comment by netblue30** [comment]
Seccomp whitelist got broken a few days ago, thanks for the bug!
