### ISSUE TITLE
Xonotic doesn't launch with firejail

### ISSUE THREAD

**Issue by pizzadude** [netblue30/firejail#1492]
I run Ubuntu MATE 17.04 with the latest firejail built from git.

I have Xonotic installed from playdeb, but I had the same issue with the "regular" version from Xonotic's website.

If I do "locate xonotic" it resides in:
/usr/bin/xonotic
/usr/games/xonotic
/usr/lib/games/xonotic
/usr/share/games/xonotic

I tried adding "noblacklist /usr/share/games/xonotic" to the firejail profile but that didn't do anything.
I also tried adding "xonotic" to private-bin.

This is the output of "firejail xonotic"
`Reading profile /etc/firejail/xonotic.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 32521, child pid 32522
Warning: skipping asound.conf for private /etc
Child process initialized in 200.18 ms

Parent is shutting down, bye...
`

And here's the output with the --debug flag.
http://paste.ubuntu.com/25380452/

I tried disabling seccomp for the xonotic profile, that did nothing.

Any ideas?

**Comment by SpotComms** [comment]
Could you try disabling both private-bin and private-etc?

**Comment by pizzadude** [comment]
@SpotComms I tried what you suggested and it works.

**Comment by SpotComms** [comment]
Could you do one at a time to figure out which it is?

**Comment by pizzadude** [comment]
The culprit is private-bin.

**Comment by SpotComms** [comment]
Does changing private-bin to the following fix it?

`private-bin xonotic,xonotic-glx,xonotic-sdl,blind-id,dirname,readlink,uname,netstat,grep,ps,ldd`

**Comment by pizzadude** [comment]
Nope.

**Comment by pizzadude** [comment]
I also added darkplaces-glx and darkplaces-sdl to that and it didn't make a difference.

**Comment by SpotComms** [comment]
I had edited it a few seconds after I commented, when you tested did you have `sh` at the end?

**Comment by pizzadude** [comment]
Yeah, I noticed you edited it, so I added the edited version, but it didn't make a difference.

**Comment by SpotComms** [comment]
Could you just gist the entire /usr/bin/xonotic? (assuming its a bash script)

**Comment by pizzadude** [comment]
Hmmm, for some weird reason /usr/bin/xonotic doesn't exist. It showed up in a "whereis" though.

This is /usr/games/xonotic though:

#!/bin/sh
cd /usr/share/games/xonotic
./xonotic-linux-glx.sh $@ -xonotic

And this is xonotic-linux-glx.sh

https://gist.github.com/pizzadude/20f9f873c0a685a1a4bab15a862d5268

**Comment by SpotComms** [comment]
Could you append `cd` to private-bin, hopefully thats it

**Comment by pizzadude** [comment]
No dice.

**Comment by pizzadude** [comment]
It might be because of the contents on xonotic-linux-glx.sh

**Comment by SpotComms** [comment]
TIL Ubuntu uses dash

@pizzadude add dash to private-bin and hf

**Comment by pizzadude** [comment]
It works now but there's no audio.

**Comment by SpotComms** [comment]
Does commenting out private-etc fix audio?

**Comment by pizzadude** [comment]
Yes.

**Comment by SpotComms** [comment]
Append `group,passwd` to private-etc

**Comment by pizzadude** [comment]
That doesn't solve it.

**Comment by netblue30** [comment]
Thanks @SpotComms, all merged.

**Comment by SpotComms** [comment]
@netblue30  audio is still partially broken on some systems, we might just need to comment private-etc
