### ISSUE TITLE
Atril doesn't launch anymore in firejail, but there's a workaround

### ISSUE THREAD

**Issue by pizzadude** [netblue30/firejail#1498]
Atril doesn't launch anymore in firejail, after a recent profile update. I use Ubuntu MATE 17.04. I found a workaround though.
____________________________

Reading profile /etc/firejail/atril.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Parent pid 3385, child pid 3386
Blacklist violations are logged to syslog
Child process initialized in 92.19 ms
/usr/bin/atril: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

Parent is shutting down, bye...
____________________________
If I comment out private-etc and uncomment private-tmp, it runs. I don't think I need to uncomment private-tmp, but I do that anyway. (It's private-etc that's the issue)

**Comment by Fred-Barclay** [comment]
Thanks for the report! What version of firejail are you using? (Check with `firejail --version`).

**Comment by pizzadude** [comment]
firejail --version
firejail version 0.9.50~rc1

Latest from git.

**Comment by Fred-Barclay** [comment]
It should be fixed now. Thanks!
I could replicate it on Lubuntu 17.04 but not on LMDE 2. The private-etc filter was blocking access to ld.so.cache, which possibly newer versions of atril require.

**Comment by pizzadude** [comment]
:)
