### ISSUE TITLE
Setting DISPLAY in --env setting does not work

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1499]
I have an xpra client already running and would like to attach another sandbox to the existing client. As per https://firejail.wordpress.com/documentation-2/x11-guide/, I go ahead and specify `env DISPLAY=:480` in my profile, but it doesn't work. The window opens on the regular display. I get the same behavior if I explicitly pass `DISPLAY=:480 firejail ...`. The difference is that in the first case, with `--debug`, I get a line like `DISPLAY=:0 parsed as 0`, while in the second, I get `DISPLAY=:480 parsed as 480`. The behavior is the same however - I get the new window opening in the normal display.

**Comment by netblue30** [comment]
I have to bring in support to parse --env (ro env in the profile) for DISPLAY variable. BUG!

The regular one when you pass DISPLAY on command line should work fine:
`````
$ DISPLAY=:480 firejail firefox
`````

**Comment by netblue30** [comment]
I have to parse --env (or env in the profile) for DISPLAY. Bug!

DISPLAY=:480 firejail .... should work fine. How do you test to see in what display it was opened?

**Comment by chiraag-nataraj** [comment]
Yeah, never mind - setting the environment variable outside seems to work fine.

**Comment by netblue30** [comment]
I still have to put in a fix for --env, let's mark it as an enhancement for now.
