### ISSUE TITLE
Add --private-home as an alternate name for --private.keep

### ISSUE THREAD

**Issue by pmillerchip** [netblue30/firejail#15]
We now have the options "--private-dev" and "--private-etc", but the equivalent for the $HOME directory is called "--private.keep". This looks different, as it doesn't include the directory name and it uses a dot instead of a minus sign.

A nice little enhancement would be to have a "--private-home" option that is just another name for "--private.keep". Old scripts wouldn't have to change (as "--private.keep" would still work) but it would make the commands more consistent.

**Comment by netblue30** [comment]
It makes sense, I'll clean it up and phase out private.keep in one or two releases.

**Comment by pmillerchip** [comment]
That's great news, thank you!

**Comment by pmillerchip** [comment]
I implemented it and put up a pull request for it. I also made two other pull requests for minor changes, I hope you don't mind!

**Comment by netblue30** [comment]
Thanks, I'm merging them now.

**Comment by pmillerchip** [comment]
That's great, thank you!
