### ISSUE TITLE
test suite errors

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#1502]
The test suite run at https://travis-ci.org/netblue30/firejail actually contains some errors, which didn't cause the build to fail.
Searching for "TESTING ERROR" yields two failures:

```
TESTING: whitelist dev, var(test/fs/whitelist-dev.exp)^M
travis@testing-gce-a2146449-f33b-48e3-abce-c9c1deb696d6:~/build/netblue30/firejai^Mil/test/fs$ TESTING ERROR 0^M 

TESTING: zsh (test/environment/zsh.exp)^M
^[[1m^[[7m%^[[27m^[[1m^[[0m       ^M ^M^M^[[0m^[[27m^[[24m^[[Jtesting-gce-a2146449-f33b-48e3-abce-c9c1deb696d6% ^[[K^[[?1h^[=TESTING ERROR 1^M
```

I don't know what causes the first error, but I assume the second failure is caused by some coloured zsh output, which confuses the test script (I haven't found an easy way so far to turn off colours).

**Comment by netblue30** [comment]
Should be all fixed. The whitelist-dev was actually a bug for Debian wheezy and Ubuntu14.04 - /dev/shm is a symbolic link to /run/shm.

https://github.com/netblue30/firejail/commit/12d64e7151e633f50e86b283c24cf85db7f1db41
