### ISSUE TITLE
build failure on some architectures

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#1504]
It looks like the mmap2 syscall is not available on every architecture.
Because of this some builds are failing, as SYS_mmap2 is used in src/fseccomp/seccomp.c.
See also: [Debian buildd state](https://buildd.debian.org/status/logs.php?pkg=firejail&ver=0.9.50%7Erc1-1).

**Comment by topimiettinen** [comment]
@netblue30 has already committed a fix.

But all of the failing builds also include this warning:
```
../include/seccomp.h:99:3: warning: #warning "Platform does not support seccomp filter yet" [-Wcpp]
```

I'm not sure if it is meaningful even to build the fseccomp tool or any seccomp related code on a platform if support for seccomp is not complete for the platform. For example, near this warning ARCH_NR is defined as 0 for unsupported platforms, breaking VALIDATE_ARCHITECTURE bpf.

**Comment by netblue30** [comment]
Potential fix here:

https://github.com/netblue30/firejail/commit/a93f00cc8e0e3f24a6ea2cbf4beb5572357a4c3d

The second problem is #warning "Platform does not support seccomp filter yet". The code in src/include/seccomp.h looks like this:
`````
#if defined(__i386__)
# define ARCH_NR	AUDIT_ARCH_I386
#elif defined(__x86_64__)
# define ARCH_NR	AUDIT_ARCH_X86_64
#elif defined(__arm__)
# define ARCH_NR	AUDIT_ARCH_ARM
#else
# warning "Platform does not support seccomp filter yet"
# define ARCH_NR	0
#endif
`````

We have seccomp support only for amd64, i386 and arm (probably 32bit). It is possible some platforms don't have seccomp support in Linux kernel. AUDIT_ARCH definitions are in /usr/include/linux/audit.h. I assume __i386__ definitions are coming from glibc.

**Comment by topimiettinen** [comment]
I pushed a3e73427 which should improve the build on several platforms, please test.

**Comment by reinerh** [comment]
@topimiettinen thank you for the fix!
It is currently building, but unfortunately it failed already on arm64: https://buildd.debian.org/status/package.php?p=firejail&suite=experimental

**Comment by reinerh** [comment]
I guess a default value of `""` should fix this issue?

**Comment by topimiettinen** [comment]
Yes, it seems none of the syscalls in that list are available. I'll prepare a fix.

**Comment by topimiettinen** [comment]
It does not work, empty syscall lists are not allowed, but I took a different approach with 9252c4c1.

**Comment by reinerh** [comment]
@topimiettinen Thanks.

Shouldn't the same workaround also be applied to the other SyscallGroupList items in the list?
The compiler already complains at line 86, which is the item before the one you fixed...

**Comment by topimiettinen** [comment]
Yes in theory, but luckily the other groups don't seem to have the problem, there's always at least one syscall known. Unless I fixed the wrong one... We'll see what happens when you rebuild it.

**Comment by reinerh** [comment]
@topimiettinen I just confirmed that in arm64 libc the syscalls mentioned in the @cpu-emulation are all not available.
([checked syscall.h in this .deb](http://ftp.de.debian.org/debian/pool/main/g/glibc/libc6-dev_2.24-17_arm64.deb))

**Comment by topimiettinen** [comment]
I pushed a workaround f883155b for @cpu-emulation and removed the wrong one.

**Comment by reinerh** [comment]
@topimiettinen Thanks, it helped for some architectures.
But I noticed that also all syscalls from the @obsolete and @raw-io group are not available on some architectures (e.g. arm64).

Would it make sense to add the dummy syscall to all groups?

**Comment by reinerh** [comment]
[Here](https://buildd.debian.org/status/logs.php?pkg=firejail&ver=0.9.50-1) are the build results for 0.9.50.

**Comment by topimiettinen** [comment]
Thanks, please test c3acf2d2.

I think other groups shouldn't need any workarounds, they all contain enough common syscalls.

Maybe there are better approaches to solve the build problems. If an architecture does not have seccomp support in Firejail yet, we should disable HAVE_SECCOMP (even if a header file exists) and stop building fseccomp (or build a dummy executable). An empty syscall list could be accepted in some cases, like only for internal use but not in lists given by the user.

**Comment by reinerh** [comment]
Thank @topimiettinen!
The fix was helping ([build state](https://buildd.debian.org/status/logs.php?pkg=firejail&ver=0.9.50-2) (the sh4 error is something unrelated)). I've also cherry-picked it into the 0.9.50-bugfixes branch.
