### ISSUE TITLE
Gnome-terminal stops working after stopping xpra

### ISSUE THREAD

**Issue by hahjortland** [netblue30/firejail#1505]
### Steps to reproduce

1. `xpra start :20`
2. `xpra stop :20`
3. Close all gnome-terminal instances
4. Try to start gnome-terminal. Fails to start!

Tested on Ubuntu 16.04.

### Analysis

xpra starts `/etc/X11/Xsession`,
which runs `/etc/X11/Xsession.d/95dbus_update-activation-env`,
which runs `dbus-update-activation-environment`.
This results in (from ~/.xsession-errors):
```
dbus-update-activation-environment: setting DISPLAY=:20
```
When DBUS spawns gnome-terminal-server, it tries to connect to `DISPLAY=:20`. Since this display number is invalid after xpra has closed, gnome-terminal-server fails to start:
```
$ gnome-terminal
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0:
  Error calling StartServiceByName for org.gnome.Terminal:
  GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited:
  Process org.gnome.Terminal exited with status 10
```

### Workaround

The problem can be prevented by unsetting DBUS_SESSION_BUS_ADDRESS:
```
env -u DBUS_SESSION_BUS_ADDRESS xpra start :20
```

Quick fixes after running `xpra` without this workaround:
* Start `xpra` again, or
* run `gnome-terminal` using the command `gnome-terminal --disable-factory`, or
* fix the invalid `DISPLAY` value with `dbus-update-activation-environment DISPLAY=:0`.

**Comment by netblue30** [comment]
Is this related to firejail?

**Comment by hahjortland** [comment]
No, it's not directly related to firejail. Starting xpra inside an already running desktop session like this is maybe a bit unusual, though.
