### ISSUE TITLE
Cannot run qutebrowser with Firejail due to "No module named PyQt5.QtSql"

### ISSUE THREAD

**Issue by Hund** [netblue30/firejail#1506]
This popups when I run `firejail qutebrowser`:

![2017-08-30-154149_5760x1080_scrot](https://user-images.githubusercontent.com/320498/29876143-3bbc6774-8d9c-11e7-98c8-4471f324896c.png)

Anything I  can do about it?

**Comment by Fred-Barclay** [comment]
G'day @Hund. 
What distro and version of firejail are you using?

**Comment by Hund** [comment]
Duh.. I was tired yesterday I guess. :) I'm running version 0.9.46 of Firejail and I'm on Gentoo Linux.

**Comment by VladimirSchowalter20** [comment]
Maybe try updating to 0.9.48? https://packages.gentoo.org/packages/sys-apps/firejail

**Comment by Hund** [comment]
I updated to 0.9.48 and same issue.

**Comment by SpotComms** [comment]
Do you happen to have that library installed via pip locally? Or is it installed globally/through portage?

**Comment by Hund** [comment]
qutebrowser is installed via portage. I try to stay away from pip as much as I can to avoid any issues. :)

**Comment by VladimirSchowalter20** [comment]
You can try `firejail --noprofile qutebrowser`. If this works then edit `/etc/firejail/qutebrowser.profile` and try commenting out line by line until it works (or comment out everything then uncomment line by line until it breaks). Also take a look if you have any modifications under `/etc/firejail/globals.local`, `/etc/firejail/qutebrowser.local`, `/etc/firejail/whitelist-common.local` or `~/.config/firejail/`

**Comment by Hund** [comment]
This works.

```
$ cat /etc/firejail/qutebrowser.profile
# Persistent global definitions go here
include /etc/firejail/globals.local

# This file is overwritten during software install.
# Persistent customizations should go in a .local file.
include /etc/firejail/qutebrowser.local

# Firejail profile for Qutebrowser (Qt5-Webkit+Python) browser
noblacklist ~/.config/qutebrowser
noblacklist ~/.cache/qutebrowser
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc

caps.drop all
netfilter
nonewprivs
noroot
protocol unix,inet,inet6,netlink
seccomp
tracelog

#whitelist ${DOWNLOADS}
mkdir ~/.config/qutebrowser
#whitelist ~/.config/qutebrowser
mkdir ~/.cache/qutebrowser
#whitelist ~/.cache/qutebrowser
mkdir ~/.local/share/qutebrowser
#whitelist ~/.local/share/qutebrowser
#include /etc/firejail/whitelist-common.inc
```

**Comment by SpotComms** [comment]
So whitelist was breaking it? Are you sure you don't have that library installed via pip?

**Comment by Hund** [comment]
What's the name of the package?

**Comment by netblue30** [comment]
PyQt seems to have a sql use flag. Do you have it enabled?

https://packages.gentoo.org/packages/dev-python/PyQt5

**Comment by Hund** [comment]
That was the issue.  Weird that it worked if I didn't use Firejail?
