### ISSUE TITLE
Slack notification sounds are not played.

### ISSUE THREAD

**Issue by vds** [netblue30/firejail#1507]
Using Slack with the slack profile prevents any notification sound to be played on Ubuntu 16.04

**Comment by SpotComms** [comment]
Can you try commenting `private-etc` and `private-bin` in the profile?

**Comment by vds** [comment]
That fixed the issue. Thanks.

**Comment by SpotComms** [comment]
But which was it?

**Comment by vds** [comment]
I commented out: private-etc fonts,resolv.conf,ld.so.conf,ld.so.cache,localtime and the sound plays again.

**Comment by SpotComms** [comment]
Cool. Could you try replacing it with the following and seeing if it works?

```
private-etc asound.conf,ca-certificates,fonts,group,passwd,pulse,resolv.conf,ssl,ld.so.conf,ld.so.cache,localtime
```

**Comment by vds** [comment]
It works! Thanks.
