### ISSUE TITLE
Thunderbird profile and localhost emails

### ISSUE THREAD

**Issue by vds** [netblue30/firejail#1509]
Trying to access a local Postfix account Thunderbird returns an error: "Unable to locate mail spool file."
Works perfectly without firejail.

**Comment by SpotComms** [comment]
/var/mail is blocked by disable-common.inc

**Comment by vds** [comment]
That did not really help.

**Comment by smitsohu** [comment]
But do you get still the same error, or is it a new one? On my system I got it working with `firejail --noblacklist=/var/mail --noblacklist=/var/spool/mail --writable-var thunderbird`

Thunderbird tries to write new files into /var/mail, but this folder is hard-coded read-only and remounting it as read-write is prohibited, except through the `writable-var` option.

There seems to be a similar issue with claws-mail, that needs `read-write=/var/mail/$USER` for handling localhost mails.

**Comment by DSpammy** [comment]
Same problem exists with claws-mail, too. Local mails can be fetched without firejail only.
