### ISSUE TITLE
[Spotify] Blacklisting too restrictive - firejail 0.9.48

### ISSUE THREAD

**Issue by johnfocker** [netblue30/firejail#1513]
Hi, spotify version 1.0.49.125 on ArchLinux with firejail 0.9.48 would not start and I got 
`/usr/bin/spotify: line 2: /opt/spotify/spotify: Permission denied`

commenting out `blacklist /opt` and appending a `whitelist /opt/spotify` to a local `~/.config/firejail/spotify.profile` did the trick.

**Comment by reinerh** [comment]
How did you install spotify (why did it land in /opt)?
If I understand it correctly, the [AUR build](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spotify) installs it "normally" in /usr.

**Comment by VladimirSchowalter20** [comment]
I think @johnfocker is using this package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spotify-stable which installs spotify to `/opt`

I don't know if this is a general issue as users can install binary to any location they want and adjust that in local profiles.

**Comment by johnfocker** [comment]
Woops my bad. I was indeed using "spotify-stable" instead of the regular "spotify" also in the AUR, which in turn doesn't install to `/opt` as you mentionned @VladimirSchowalter20 
Now using only the default profile and it works like a charm.
Thanks for all the good work guys.
