### ISSUE TITLE
Invalid argument on Libreoffice's Appimage Recipe

### ISSUE THREAD

**Issue by ShouldIPressTheButton** [netblue30/firejail#1514]
Hello,

I created an AppImage using de Recipe from the official AppImage repo: "https://github.com/AppImage/AppImages/tree/master/recipes/libreoffice".

It works well, but when I call firejail with "--appimage", it returns an error "Invalid Argument".

`
~/Applications$ firejail --appimage LibreOffice-5.4.1.glibc2.7-x86_64.AppImage 
Error mounting appimage: appimage.c:104 appimage_set: Invalid argument
`
:( unfortunately, I have no clue how to debug it or to give you more informations.
I already done that for two others AppImage recepies, and it works well !

**Comment by netblue30** [comment]
What version of firejail are you using? At some point appimage change the archive format, so you would need to update firejail.
