### ISSUE TITLE
Please add a .sig file

### ISSUE THREAD

**Issue by elhanan** [netblue30/firejail#1525]
I'm unable to use your public key to verify firejail or firetools because you don't make a .sig file available for download. Is there another way to verify firejail and firetools than using a .sig file? 'sha256sum' merely tells me I downloaded the file without error. But it does not provide any security assurance. So the 'sha256sum's are not enough for me. I need a security assurance that the programs came from you by providing a .sig file along with your public key. Will you please provide me a .sig file or tell me how to use your public key without one?

**Comment by SpotComms** [comment]
Its F951164995F5C4006A73411E2CCB36ADFC5849A7
http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0x2CCB36ADFC5849A7

**Comment by elhanan** [comment]
Thank you, that worked perfectly. Do I need to run sha256sum separately on the .rpm or .deb packages, or does the sha256sum --check on the .asc file do that for me? I've only ever verified packages using .sig files before. So sorry for being in the dark. No wonder searching the GNU docs didn't help me; I was searching for .sig instructions. Thanks again.

**Comment by SpotComms** [comment]
If you open up the .asc in any text editor it'll show you what files it has hashes for

**Comment by elhanan** [comment]
Yes, of course. I knew that. But what I was trying to say was do I have to open it in any text editor to verify it myself, or does the commands you helped me with verify that the hashes of the programs match the ones in the file that I can check manually? So basically, do I need to open that file in a text editor if I already ran those commands?
