### ISSUE TITLE
remount pulseaudio noexec

### ISSUE THREAD

**Issue by smitsohu** [netblue30/firejail#1529]
This is actually an old issue (#1238), sorry for bringing it up again, but I believe with the recent addition of new features it could be interesting to have a second look:

In order to fully leverage the power of the new `memory-deny-write-execute` option in conjunction with `noexec ${HOME}` and `noexec /tmp`, it seems quite desirable to deprive unprivileged users from all remaining locations that still permit execution. As far as I can see, there is only ~/.config/pulse left with an exec flag currently (could /tmp/pulse* be relevant too?).

IMHO it should be safe to remount this folder noexec, nodev, nosuid by default. By closing the last of a kind loophole it would be a significant addition for certain configurations.

**Comment by SpotComms** [comment]
Did #1270 not fix this?

**Comment by smitsohu** [comment]
@SpotComms It was reverted. `~/.config/pulse` is still with exec flag as of now.

**Comment by SpotComms** [comment]
https://github.com/netblue30/firejail/blob/master/etc/disable-common.inc#L312
```
│     ├─/home/user/.config/pulse             ...             ext4        rw,nosuid,nodev,noexec,relatime,...
```

Am I missing something? It looks like its noexec

**Comment by smitsohu** [comment]
This is interesting! Here is what I find inside `firejail --noexec=~ --noexec=/tmp`

```
│     └─/home/ed/.config/pulse         ....         tmpfs           rw,nosuid,mode=755
```

Few days ago I tried in a VM, it was the same.

**Comment by SpotComms** [comment]
Yes I have that too afterwards, but does the first not take precedence?

**Comment by smitsohu** [comment]
In `findmnt` trees it's the last entry we need to look for, so probably you have an exec flag, too. You can easily convince yourself, just place an executable there and try to run it from inside the sandbox

**Comment by SpotComms** [comment]
Yep, you're correct.
I gave it a try but I can still execute in it.
https://github.com/SpotComms/firejail/commit/60ca0235baea6541620ad008f8ee35e60b36cafe
