### ISSUE TITLE
gitg not showing diff

### ISSUE THREAD

**Issue by cryptogun** [netblue30/firejail#1537]
As the title.  
And how to exclude a command from jail?

**Comment by SpotComms** [comment]
On latest from master and gitg 3.26, I cannot reproduce. But if you want to disable it for now just
`rm /usr/local/bin/gitg`

**Comment by cryptogun** [comment]
Thanks for your info.  
Versions here:
```
firejail version 0.9.49
gitg 3.17.1
gitg is already the newest version (3.17.1-1).
GRUB_TITLE=Linux Mint 18 Cinnamon 64-bit
Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
Screen shot:
![screenshot from 2017-09-08 01-27-30](https://user-images.githubusercontent.com/7909326/30176670-ea356ff4-9435-11e7-83b1-363662b72e56.png)

**Comment by cryptogun** [comment]
Update: `mv /usr/local/bin/gitg` and use `/usr/bin/gitg`, diff's out.
Even though sometimes (~50%) GUI output `Loading diff...` and console output `(gitg:10440): GLib-CRITICAL **: Source ID 2384 was not found when attempting to remove it`. `Loading` forever until I click other branches.

**Comment by SpotComms** [comment]
@cryptogun commenting "memory-deny-write-execute" should fix it

**Comment by cryptogun** [comment]
@SpotComms Yeah, That fixed. Thank you.   
P.S. profile path: `/usr/local/etc/firejail/gitg.profile`
