### ISSUE TITLE
All qt5 progragems should whitelist common theming engines

### ISSUE THREAD

**Issue by marcthe12** [netblue30/firejail#1540]
When .config is blocked, several theming engines like qt5ct and kvantum. Whitelisting these programs mean no hideous theme in programs like kate

**Comment by netblue30** [comment]
In what directories are the themes stored? By default for all whitelisted programs we enable ~/.themes and ~/.local/share/themes from /etc/firejail/whitelist-common.inc (https://github.com/netblue30/firejail/blob/master/etc/whitelist-common.inc#L33). We just have to add the new directories in that file.

**Comment by marcthe12** [comment]
For qt, the theming engines are located in usr/lib/qt/plugins/platformthemes. The major one are listed here
For qt5ct, its a meta theme engine, it config is in $XDG_CONFIG_HOME/qt5ct
For qtcurve, from the offical github page states the following dir.
qtc_<name>.themerc in $KDEHOME/share/apps/kstyle/themes/ (usually ~/.kde/share/apps/kstyle/themes/) or copy to <kde install prefix>/share/apps/kstyle/themes/ (usually /usr/share/apps/kstyle/themes/)
the config is $XDG_CONFIG_HOME/qtcurve and $XDG_DATA_HOME/qtcurve
I donot have access to the computer with kvantum on it, although i think /usr/share/kvantum and ~/.config/kvantunum.
There is lxqt, breeze, adwaita-qt and oxygen.
Its probary safe to keep $XDG_CONFIG_HOME and $XDG_DATA_HOME read only
