### ISSUE TITLE
Launch app outside Firejail without re-configuring?

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#1545]
Is it possible to launch an app which has been previously Firejailed through firecfg outside the sandbox for temporary use? In otherwords leave it Firejailed by default, but launch outside sandbox for single use? I tried to de-firejail a single app (Thunderbird) through firectl but firectl isn't found when root.

**Comment by SpotComms** [comment]
You can just run the program in a terminal with the real path.

```
which -a thunderbird #Second one should be the true one, eg. not /usr/bin/local
/usr/bin/thunderbird #Run the program
```
