### ISSUE TITLE
Cannot authenticate SSH with smartcard though gpg-agent because of /run/user/UID/gnupg blacklist

### ISSUE THREAD

**Issue by Ryujinra** [netblue30/firejail#1546]
The following commit blacklists the 'gnupg' directory under /run/user/{UID}: #0c5aa59.

If you are using a OpenPGP smartcard to publickey authenticate, ssh needs access to this directory because it contains the gpg-agent ssh socket (S.gpg-agent.ssh) for accessing the keys on the smartcard.

--noprofile / noblacklist has no effect on this directory/files.

I suppose that an option to disable the blacklisting of this directory in a program's .local file would be the best solution.

**Comment by netblue30** [comment]
You cannot disable it, it is hardcoded in this moment. I'll bring in support to allow you to disable it from a profile file.

**Comment by netblue30** [comment]
I added on mainline --writable-run-user command and profile option. I also included it in ssh and ssh-agent profiles. Thanks for the bug.
