### ISSUE TITLE
[0.9.34] download folder not detected in non english systems [bug]

### ISSUE THREAD

**Issue by KDB2** [netblue30/firejail#155]
Hello,

With the new 0.9.34 version, I have observed that my /home folder is not accessible in Firefox. Only the download folder is being whitelisted (and a few others).
Unfortunately, my system is in French and download doesn't exist as it is called "Téléchargements". As a result, my downloads are stored in a temporary /download folder that I cannot access and are being deleted at the end of my Firefox session. 

You may be able to solve this issue with the ~/.config/user-dirs.dirs file.

Regards and thanks for your efforts,
KDB

**Comment by netblue30** [comment]
Yes, this is a very ugly bug! I'll whitelist Téléchargement for now, until I find out how xdg-user-dirs is working.

**Comment by netblue30** [comment]
Fixed, thanks!

**Comment by KDB2** [comment]
Thanks a lot!

**Comment by netblue30** [comment]
No problem, let me know if you run into something else.
