### ISSUE TITLE
Running Virtualbox with seccomp? 

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#1556]
Is it possible to firejail Virtualbox with seccomp or namespace?

**Comment by netblue30** [comment]
Virtualbox needs to raise privileges in order to start or communicate with its own kernel modules. Seccomp will kill it immediately. Namespaces are working fine and are currently enabled. Also, the home directory is whitelisted, so you have access only to ~/VirtualBox and  ~/Downloads directory.
