### ISSUE TITLE
blacklist clipboard history file

### ISSUE THREAD

**Issue by HighIO** [netblue30/firejail#1562]
some clipboard managers save the entire contents in plain texts
eg,
https://github.com/cdown/clipmenu/     cache in ```/tmp/clipmenu.$major_version.$USER```
https://github.com/erebe/greenclip/      cache in ```~/.cache/greenclip.history``` and ```~/.cache/greenclip.staticHistory```

Access to the cache dir or files should be prohibited by default.
Could you add this to ```/etc/firejail/disable-common.local``` ## History files
```
blacklist /tmp/clipmenu*   
blacklist ${HOME}/.cache/greenclip*
```

**Comment by netblue30** [comment]
All set, thanks.
