### ISSUE TITLE
What happened to the smtube profile?

### ISSUE THREAD

**Issue by pizzadude** [netblue30/firejail#1567]
I did a git pull and noticed this:

"rename smtube.profile => etc/dooble.profile (58%)"

I don't think these are the same program...

Why?

**Comment by SpotComms** [comment]
It wasn't renamed, git just likes to look for similarities. What actually happened was the profile itself was deleted, seems by accident in cbbc90381b41156c16bcb30934a10c843c8298c0. I've restored it in ec55db76707e9749378c4dfa32f82ed72813e455.

**Comment by netblue30** [comment]
My fault. I have no idea how I managed to remove it!
