### ISSUE TITLE
Unable to start Xfce with latest firejail (Arch Linux)

### ISSUE THREAD

**Issue by cjsthompson** [netblue30/firejail#1568]
Hi,

I had to reboot my (Arch Linux) machine today (1 month+ uptime). I was unable to start xfce (from lightdm) until I did a 'firejail --clean'. It used to work fine with 0.9.48 I'm pretty sure. xfce4-session seems to be stuck when firejail is in use. I did give it a try without any /etc/firejail/*.local customizations to be sure it has nothing to do with this. I also tried with the latest git.

I don't know if this is related, but I noticed there are some unkillable firejailed ssh-agent processes that are lingering each time I try to start xfce with firejail active.

Any help to fix this would be greatly appreciated.

**Comment by cjsthompson** [comment]
Only commenting out "shell none" in ssh-agent.profile does not work. But removing the ssh-agent symlink does indeed fix the problem.

**Comment by netblue30** [comment]
I have removed it from firecfg until we figure out what is going on. Delete the symbolic link in /usr/local/bin for now.

**Comment by cjsthompson** [comment]
Ok, thanks.

**Comment by joelazar** [comment]
This bug is still around. Manjaro 17.0.6 xfce, firejail 0.9.50.

**Comment by joelazar** [comment]
Ok, it looks like it is fixed now :) 0.9.52
