### ISSUE TITLE
opsec: Wipe tmpfs on program exit

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#157]
An option to wipe files created by the user, on tmpfs filesystems, to avoid leaving traces in memory. Or wipe the whole tmpfs, because then also "normally" deleted files will be wiped.

Also disable swapping to HDD (--private-dev seems to already be doing this, but maybe make it explicit).

**Comment by netblue30** [comment]
I cannot find any way to disable swap memory for tmpfs. The only way to do it is to disable swapping for all the system.

The filesystem of the processes running in the sandbox is exposed in /proc/PID/root to anybody already inside the system with enough privileges. /proc also exposes the memory of the running processes. I'll have to reject it for now, until some idea how to do it comes along.
