### ISSUE TITLE
Avoid 'exo-open' on xfce desktop

### ISSUE THREAD

**Issue by jockerz** [netblue30/firejail#1570]
I tried run _firejail_-ed xpdf with `--net=none`.
Maybe does same case on another app which lead to open _url_.

When a link on a pdf file clicked, the url will opened successfully on web browser(if the browser has already opened) on new tab.

The web browser will be prevented to connect internet if the _url call_ will open new web browser window.

`--debug`: not give any useful info to the case.

Please give a try for any one. I'm not good at catching bug yet.

**Comment by smitsohu** [comment]
Hey @jockerz. Do you use Firefox? Chances are that you have run into #784. Different issue but related is also #330.

**Comment by smitsohu** [comment]
Still assuming you run Firefox some more possibilities to approach this:
- Running Firefox with `-no-remote` option will stop this behavior. Equally, you can put `export MOZ_NO_REMOTE=1` in ~/.xsessionrc (or wherever you configure your X session), or place `env MOZ_NO_REMOTE=1` inside /etc/firejail/firefox.local.
- What should also work is isolating xpdf (or Firefox) from your main X session by means of Firejail's 
`x11 *` options.

**Comment by jockerz** [comment]
Hi @smitsohu.
Thank you.

Solve this problem by adding `--no-remote` to run Firefox.
