### ISSUE TITLE
allow `writable-run-user` in profiles

### ISSUE THREAD

**Issue by msva** [netblue30/firejail#1572]
It would be nice to allow using `writable-run-user` in profiles (for example, KMail needs it to sign/encrypt/decrypt emails).
Same for firefox/gmail with plugins that allows to connect to the running gpg-agent

**Comment by SpotComms** [comment]
It is allowed and is already used by ssh*.profile. Is there something wrong with it?

**Comment by msva** [comment]
Yeah, sorry, it looks like I accidentally built fj from wrong commit date, so it had that feature as cli option, but did not allow it in profiles.
