### ISSUE TITLE
Firejail causes "Couldn't Initialize the Render Device." error when I try to launch a particular game from Steam

### ISSUE THREAD

**Issue by denizakcal** [netblue30/firejail#1575]
Hello.

There used to be a bootstrapping error with firejail, recently in Debian buster/testing, but now that I updated it, that problem is gone, but another one presented itself.

For instance, when I try to launch the game "Natural Selection 2", it says "Couldn't Initialize the Render Device." (This doesn't happen when Steam is run without firejail.)

I also tried launching the game "Magicka 2," and it works, but the graphics look really bad.

Could this be looked into, please?

I'm using the free-as-in-freedom radeon driver, and the x86_64 version of Debian buster/testing. Let me know if more information is needed.

Edit:
I forgot to explicitly mention that firejail's version is 0.9.50-3.

**Comment by netblue30** [comment]
Try to find out what lines in /etc/firejail/steam.profile are creating the problem. In a text editor comment out everything (add a # in front of the line) and try it out. Then you start uncommenting groups of statements there. In a few iteration you'll get it.

Does it work for other games?

**Comment by denizakcal** [comment]
Hello again, netblue30. :)

The (one and only) line that seems to me to be causing the problem is the following one.:
private-etc asound.conf,ca-certificates,dbus-1,drirc,fonts,group,gtk-2.0,gtk-3.0,host.conf,hostname,hosts,ld.so.cache,ld.so.preload,localtime,lsb-release,machine-id,mime.types,passwd,pulse,resolv.conf,ssl

Also, about it affecting more than one game, I only checked with two games ("Natural Selection 2" and "Magicka 2"), but it affected them both (in different ways). (I probably should have been more clear in emphasizing that the game "Magicka 2" has graphics that look bad only when I was using firejail, so sorry about that.) (I focused more on the game "Natural Selection 2," since it seemed to have a more useful error message.)

Let me know if you need anything else!

**Comment by SpotComms** [comment]
We'll have to comment it for now, I knew it was inevitable that we'd need to.
Fixed in f0420c6b0a5f6dc5643e0a8840111874212b06aa
