### ISSUE TITLE
What happened to the remote desktop feature & tutorial?

### ISSUE THREAD

**Issue by esotericDisciple** [netblue30/firejail#1578]
I thought there was a way to launch linux operating systems stored in separate hard drives/partitions through firejail. I wanted to test it out by launching a nested X Session of Xubuntu 17.04 by running firejail --x11 --chroot=/run/media/Xubuntu-OS-mount-point, but it keeps failing with a error message about a bad "/etc/resolv.conf" file. I also can't find the guide that I remember viewing on the wordpress blog. Does that mean firejail can't do this sort of thing anymore?

**Comment by netblue30** [comment]
The feature is fully supported, this is a bug, thanks. I put a fix in, you can try it out.

**Comment by esotericDisciple** [comment]
Okay, is the fix already applied to the Arch (Manajaro) Linux package?

**Comment by Fred-Barclay** [comment]
@esotericDisciple It won't be in the mainline Arch repo until firejail version 0.9.52 is released. In the meantime you could build firejail from the latest code here on Github with `git clone --depth 1 https://github.com/netblue30/firejail.git && cd firejail && ./configure --prefix=/usr && make && sudo make install-strip`. There is also a firejail-git package in the AUR, though I've not tried it.
