### ISSUE TITLE
Firejail doesn't work with wine+steam on Arch

### ISSUE THREAD

**Issue by trialism** [netblue30/firejail#1580]
Hi,

I wanted to use firejail with my wine installation but I can't use steam with it because it stucks at "Connecting to X's steam account..." due to the lack of internet connection(I do have internet with sandboxed native apps). The logs don't tell much:

```
Reading profile /etc/firejail/wine.profile
Reading profile /etc/firejail/globals.local
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: noroot option is not available
Parent pid 29545, child pid 29546
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 69.19 ms
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
ILocalize::AddFile() failed to load file "public/steambootstrapper_hungarian.txt".
[2017-09-27 21:19:57] Startup - updater built Sep 27 2017 08:06:07
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-09-27 21:19:57] Checking for update on startup
[2017-09-27 21:19:57] Checking for available update...
[2017-09-27 21:19:58] Download skipped: /client/steam_client_win32 version 1506520001, installed version 1506520001
[2017-09-27 21:19:58] Nothing to do
[2017-09-27 21:19:58] Verifying installation...
[2017-09-27 21:19:58] Performing checksum verification of executable files
[2017-09-27 21:19:58] Verification complete
[0927/211958:ERROR:network_change_notifier_win.cc(170)] WSALookupServiceBegin failed with: 8
IPC client is in my process, could/should be using an in-process pipe.[2017-09-27 21:20:00] Background update loop checking for update. . .
[2017-09-27 21:20:00] Checking for available update...
```

I've tried to downgrade firejail(I'm using 0.9.50) versions down to 0.9.44. I've also tried firejail-git from AUR and tried the integrated internet explorer - no internet with that either.

I'd appreciate any hint. Thanks in advance!

(ps: this issue is a 'repost' because my previous temporary account has been deleted with the reported issue without a notice from github. This is why github is a terrible service.)

**Comment by trialism** [comment]
Btw, is firejail+wine supported?

**Comment by trialism** [comment]
Hi, I've installed wine-staging and after I removed the `seccomp` line from the end of /etc/firejail/wine.profile things started to work properly. Is that a security flaw or is there anything we can do to put it back while not breaking wine+steam?

**Comment by Irvinehimself** [comment]
See https://wiki.archlinux.org/index.php/Firejail#Troubleshooting

> Some applications do not work properly with Firejail, and others simply require special configuration .... One example is wine; wine will not work with seccomp in most cases.
