### ISSUE TITLE
Firefox Nightly breaks out of firejail(-0.9.50,-0.9.51)

### ISSUE THREAD

**Issue by trialism** [netblue30/firejail#1584]
Hi,

 I've installed firejail from AUR(firejail-git) and downloaded firefox nightly(58.0a1). I've created a directory `FF_Nightly` then moved the firefox directory there. When I start it as `firejail --private=${HOME}/FF_Nightly ./firefox/firefox`, Firefox 55.0(the installed one) will start instead of Nightly - *and it's using the configuration from another running sandbox*. The same happens when I simply start FFN but I thought firejail would stop it. I have two FF sandboxes with their own config but when I start FFN it'll start with the latest sandbox's config. It seems like FFN breaks out of the jail somehow.

**Comment by trialism** [comment]
This broke my old configurations - when I start them they glitch and show black and white rectangles.

**Comment by SpotComms** [comment]
See #939

**Comment by trialism** [comment]
@SpotComms I can run two different instances of firefox in different sandboxes - I use them now and they both look and behave differently. The problem is with FFN - even if I start it in a different jail it breaks out.

**Comment by SpotComms** [comment]
So I just tested this

```
firejail --private /usr/bin/firefox #starts a new instance
firejail --private /usr/bin/firefox #opens a window in first instance
firejail --private /usr/bin/firefox-nightly #opens a window in first instance
#close first instance, all windows close
```
Even with a new network namespace and ipc-namespace, it still launches a window in the first.

However simply adding `-no-remote` will allow running multiple instances of both firefox and firefox-nightly at the same time.
```
firejail --private /usr/bin/firefox -no-remote
```
Can you give that a go? Also in that case even though it works I think it might still be possible to get back into the context of the other running Firefox instances.

**Comment by trialism** [comment]
@SpotComms You've missed the `--private=${HOME}/FF_Nightly` part.
