### ISSUE TITLE
Regression: Decrypting inside the jail using gpg-agent running outside the jail with cached password doesn't work anymore

### ISSUE THREAD

**Issue by graywolf** [netblue30/firejail#1585]
After upgrading to `0.9.50` from `0.9.48`, my `mutt` setup stopped working. I'm running gpg-agent outside of the jail (it starts on login) and in `0.9.48` I'm using cached password to decrypt stuff needed for sending emails. However, this doesn't work anymore in `0.9.50` since it always asks for password for the first time (which is pain to get to work since there is no tty in jail (`not a tty` from `tty` command). Combined with `private-dev` introduced in `0.9.50` it's hard to make it work.

I've tried both:
1) 48's /etc with 50 firejail - doesn't work
2) 50's /etc with 48 firejail - does work (after commenting out `nodvd` and `notv`)

So the regression is in firejail itself and not in the profiles.

**Comment by netblue30** [comment]
We have a potential fix on mainline git, thanks for the bug!
