### ISSUE TITLE
gnome-ring can't interact with dring

### ISSUE THREAD

**Issue by PharmaceuticalCobweb** [netblue30/firejail#1586]
Hi, I submitted a commit a few days ago to add support for gnome-ring. However, there are some issues currently. When gnome-ring starts it opens both a front-end, graphical environment but also starts a background process/daemon called "dring".

Right now if you open gnome-ring in firejail (using default restrictive settings or the profile I wrote) it will start dring and gnome-ring in two different firejail sandboxes. As a result gnome-ring can't interact with dring and claims that the user doesn't have an account, since it can't see any.

To fix this gnome-ring and dring would need to start in the same firejail sandbox rather than two separate ones. However, I'm not sure how to do that.

**Comment by SpotComms** [comment]
Can you fully close/stop both processes, add the following to the profile file `join-or-start ring` and then try starting it. That should make it so there is only ever one sandbox. If that works, I'll add it to the profile.

**Comment by PharmaceuticalCobweb** [comment]
I added join-or-start ring to my profile and they still start separately. Also tried join-or-start dring.

**Comment by PharmaceuticalCobweb** [comment]
I've also noticed that the dring back-end needs access to /dev/shm in order for any webcam functionality (if you run gnome-ring in the current firejail profile click on the cog labelled settings and click "media" with a webcam installed gnome-ring with output to terminal: "could not open shm area "Ring Daemon_shm_9710_0"" although my webcam's LED indicator does light up). Tried "noblacklist /dev/shm" in gnome-ring.profile but dring still seems incapable of accessing /dev/shm.

So I navigated to /usr/lib/ring and started the dring process manually using "firejail --noblacklist=/dev/shm ./dring" to see if allowing it to access those files fixed webcam functionality. However, when you start gnome-ring with the dring process running manually (in firejail), it will not open with no noteworthy errors. I made sure to pkill both dring and gnome-ring beforehand, it just won't start. Although, if you run dring manually without firejail it does work but webcam functionality is not restored until you run both gnome-ring and dring with --noprofile. As a last ditch attempt I ran dring manually using "firejail --noblacklist=/dev/shm --join-or-start gnome-ring ./dring" however, this also failed to restore webcam functionality.

**Comment by smitsohu** [comment]
> Right now if you open gnome-ring in firejail (using default restrictive settings or the profile I wrote) it will start dring and gnome-ring in two different firejail sandboxes.

Could you check if there is a dring in your /usr/local/bin?

> Tried "noblacklist /dev/shm" in gnome-ring.profile but dring still seems incapable of accessing /dev/shm.

`--noblacklist=/dev/shm` will not help because we don't blacklist this device, it is basically always available inside the sandbox. But you could try with `--ignore=ipc-namespace`, it is supposed to interrupt shared memory IPC.

**Comment by SpotComms** [comment]
@smitsohu afaik /dev/shm is always blacklisted if private-dev is enabled

**Comment by smitsohu** [comment]
@SpotComms Hmmm, it looks I understood it wrong (from reading the documentation). It seems that /dev/shm is private to the sandbox, but if that's right noblacklisting would still not help....

@PharmaceuticalCobweb So if disabling `ipc-namespace` is not sufficient, we might need to disable private-dev too **or** indeed run dring and gnome-ring in the same sandbox.

**Comment by smitsohu** [comment]
@PharmaceuticalCobweb It seems that when gnome-ring starts, it requests via dbus the activation of dring. The expected outcome would be that dring runs without firejail, and only gnome-ring is firejailed.

Normally, to run dring in firejail, it will be necessary to edit a service file in /usr/share/dbus-1/services.

**Comment by smitsohu** [comment]
I didn't test much functionality, but it seems that commenting `private-dev` solves the main issue.

In order to firejail ring daemon, create a file /etc/firejail/gnome-ring.local and put `join-or-start ring` inside. _Before_ gnome-ring is started, execute: `firejail --profile=/etc/firejail/gnome-ring.profile /usr/lib/ring/dring`. dring and gnome-ring should now end up in the same sandbox.

A possible alternative: run `cp /usr/share/applications/gnome-ring.deskop ~/.local/share/applications`. Then replace in ~/.local/share/applications/gnome-ring.desktop the Exec line with `Exec=firejail --profile=/etc/firejail/gnome-ring.profile dbus-launch gnome-ring %u`. In this case part of the Gnome session will be replicated inside the sandbox.
