### ISSUE TITLE
Firejail still running after closing Firefox

### ISSUE THREAD

**Issue by selectiveduplicate** [netblue30/firejail#1589]
I previously wrote about certain warning messages that I receive here: #1576 ...

Just today I've got a pile of those random messages (I had been using it for a long time, so...), and when I closed Firefox, I found that my Firejail session is still running...

![fire_bug](https://user-images.githubusercontent.com/32275394/31196085-5084d90a-a96e-11e7-8a8f-a7bcd785fb59.png)

As you can see the list is quite much, I can't really provide all the messages...

Somewhat similar issue happened before, in that scenario I wasn't able to close Firefox at all and so couldn't open another Firefox session, and finally Firefox crashed...

Right now, I'm writing this post from a normal Firefox session, not a Firejail-sandboxed one, while my previous Firejail session is still running, as seen from the photo...

If any other information is needed in this regard, I'd be happy to provide!

Thanks!

**Comment by SpotComms** [comment]
None of those error messages really matter.

As for why its still running... are you running the non-Firejailed version with `-no-remote`? Because if you aren't, your non-sandboxed Firefox instance is really actually running under the Firejailed instance. Which would explain why its still running.

**Comment by selectiveduplicate** [comment]
No, I'm not running with `-no-remote`( I've never used it actually)... generally I start a sandboxed Firefox with `firejail firefox` and when I close it, Firejail also closes (**parent is shutting down, bye**)... but in this case Firefox didn't close. If I want to start a normal Firefox session, I just launch it from my launcher. Just now I'm running a normal session...

**Comment by netblue30** [comment]
> but in this case Firefox didn't close

In a different terminal run firejail --tree" and put the output of the command here. It will tell us what process in still running in the sandbox.

**Comment by selectiveduplicate** [comment]
Sorry, I miswrote... actually I meant 
>Firejail didn't close

**Comment by netblue30** [comment]
Just run "firejail --tree". Firejail will not close if there is something running inside the sandbox. It will wait for all processes to finish.
