### ISSUE TITLE
Bitlbee profile

### ISSUE THREAD

**Issue by rogshdo** [netblue30/firejail#159]
I would like to create a profile for [bitlbee](https://www.bitlbee.org/) so that I can run it in a jail. Currently I have this, built off of the server.profile and some of the other default profiles I see:

```
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-common.inc
protocol unix,inet,inet6
netfilter
private
private-dev
seccomp
```

This seems to work, but I don't really understand `protocol` or `netfilter`. Could someone more familiar with firejail suggest what a good profile should look like for bitlbee? Thank you!

Also, if a bitlbee profile could be included with firejail by default, that would be great.

**Comment by netblue30** [comment]
I've just added your profile, thanks! This is how it looks:
`````
$ cat /etc/firejail/bitlbee.profile 
# BitlBee profile
noblacklist /sbin
noblacklist /usr/sbin
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-common.inc
protocol unix,inet,inet6
private
private-dev
seccomp
`````

You don't need "netfilter". This option works only if you create a network namespace, and BitlBee will probably not work in a network namespace.

"protocol unix,inet,inet6" describes the protocols allowed by socket system call. There are about 40 of them available, usually you can get away only with unix socket protocol, IPv4 and IPv6. The option is based on seccomp and reduces the attack surface of the kernel.

**Comment by rogshdo** [comment]
Great, thanks!
