### ISSUE TITLE
firejail firefox has no DNS in some? setups

### ISSUE THREAD

**Issue by sie64** [netblue30/firejail#1591]
I have "the same" (or so I believe) setup on two computers but on one the `firejail firefox` stopped working a few weeks/months ago; Firefox opens but has no DNS lookup access. When I join the sandbox with a shell and call `nslookup` it times out, too, which rules out a firefox issue.  I am on firejail version 0.9.50 and the current Mozilla Firefox. I have already tried reinstalling firejail incl. purging of `/etc/firejail`, and adding a new Linux user (and trying the same with that user) but to no avail. There is no relevant information in messages or on stdout/stderr:

```
firejail firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 3854, child pid 3855
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 68.55 ms
```
further error messages clearly stem from the inability to connect to the Internet via DNS.  Direct access to an IP address works!

Both computers run Arch Linux with an up-to-date "hardened" Linux kernel.

**Comment by netblue30** [comment]
There are some problems with our systemd resolver integration. We have a fix on mainline git, you can try it out.
