### ISSUE TITLE
FireJail Idea

### ISSUE THREAD

**Issue by vicsygen** [netblue30/firejail#1592]
Just as a suggestion, not sure if it would be doable, but would it be possible to make a firejail app, have it run like as if it was the home screen, a overlay. Then any selected apps would be fire jailed, or would this not be possible

**Comment by SpotComms** [comment]
You mean a launcher like that included in Firetools?
https://l3net.files.wordpress.com/2015/05/firetools-show.png

Its not really needed anymore since you can just run 'sudo firecfg' once and then launch your applications normally. Any program with a profile will be sandboxed.

**Comment by vicsygen** [comment]
Oh sorry i meant to say a phone app, ive seen the launcher for a linux system

**Comment by SpotComms** [comment]
Both Android and iOS heavily sandbox apps.
If you want FOSS go install CopperheadOS, LineageOS, or Replicant. Stay away from root, Xposed and theme engines and only install apps from F-Droid and you'll be dandy.
