### ISSUE TITLE
Execute commands

### ISSUE THREAD

**Issue by cjconstante** [netblue30/firejail#1595]
Hi.
I am trying to execute more than 1 command with the option -c "", for example "command1; command2" but it just runs the first command. For the next, i get not found message.
If i run 1 command it works, if i add more, the next after the first, fail. There is any way to execute more than 1 command?

Thanks.

**Comment by Fred-Barclay** [comment]
Hi @cjconstante 
Can you give a specific example and output? Thanks!

**Comment by reinerh** [comment]
That's because it interprets the argument as a single command, which of course it can't find.
```
$ firejail --quiet -c "ls; ls"
/bin/bash: ls; ls: command not found
```

**Comment by reinerh** [comment]
@cjconstante Try running the commands without enclosing them in quotes.

**Comment by cjconstante** [comment]
Thanks for the reply. I will try that way.
I found a solution: I created a bash script and there i type the commands i need. In the firejail command i pass -c myscript and it works.

Thanks.
