### ISSUE TITLE
Bug in mate-calc.profile

### ISSUE THREAD

**Issue by NH3-** [netblue30/firejail#1598]
This bug is the dupplicate of #1325 
In the file https://github.com/netblue30/firejail/blob/master/etc/mate-calc.profile it is specified that the following configuration should be accessible : 

`whitelist ${HOME}./config/mate-menu`

But the syntax is **incorrect**, indeed, the correct syntax should be :

`whitelist ${HOME}/.config/mate-menu`

the dot should be after the slash.

**Comment by startx2017** [comment]
Fixed, thank you!
