### ISSUE TITLE
Tor profile

### ISSUE THREAD

**Issue by rogshdo** [netblue30/firejail#160]
Has anyone used firejail to jail Tor? If so, I would be curious to see what your profile looks like! I have seen some discussion of using firejail to run the Tor browser, but I want to run the actual Tor daemon in a jail so that I can proxy other applications through it.

**Comment by avoidr** [comment]
I'll write a profile for Tor today.
I already have one for Tor Browser that I'll just drop here:
```
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
#tmpfs /etc/
private-etc fonts
private-dev
whitelist ~/.torbrowser/
caps.drop all
seccomp
protocol unix,inet,inet6
netfilter
noroot
```
I keep my Tor Browser in ~/.torbrowser/, so I whitelist that.
I keep /etc/fonts/. I don't know if it's relevant to anonymity. If you don't enable JS, which you shouldn't anyway, it should not matter.

Btw, I have not found a way to start Tor Browser directly as an argument to firejail. And that's because the script makes it --detach, so it returns immediately and firejail ends, killing Tor Browser.

**Comment by netblue30** [comment]
For Tor I usually start with the regular firefox profile where I change "whitelist ~/.mozilla" with the place where I keep Tor. Let's say I have it in ~/tor-browser_en-US, this is how I start it:
`````
$ cd ~/tor-browser_en-US
$ firejail --profile=~/tor.profile Browser/start-tor-browser & disown
`````
This takes care of --detach.

Support for running other programs using the gateway is in the works. It involves setting a namespace and bringing in the traffic. This is the open issue: https://github.com/netblue30/firejail/issues/108 - it will be very generic, will work for all kind of other programs.

**Comment by rogshdo** [comment]
Thanks avoidr. Netblue, I'm looking for a profile for Tor, not the Tor Browser.

If I start Tor with firejail, should I also use a Tor chroot like what is described in the Arch wiki or does that not give me anything over what firejail will already do?

https://wiki.archlinux.org/index.php/Tor#Running_Tor_in_a_Chroot

**Comment by avoidr** [comment]
I am currently working on making Tor work.

I'd say chrooting Tor in firejail won't give any extra benefit, because firejail is already more powerful and does more. Not to mention that chroot is not really a security feature and it's possible to break out. Sure you can still chroot, but you'd probably benefit more by hardening the kernel, for example.

**Comment by avoidr** [comment]
So I created a branch for Tor support, but it's incomplete. If you could look at it, @netblue30.
There's a new profile and I mounted /var/lib/tor/ on a new tmpfs to make it writable, but what's missing is that we want to keep the files and not redownload the Tor network consensus every time. I naively thought that I'd just hardlink, but that's impossible across different devices.

Also, I merged in that branch and I'm not sure if that should be done in branches or not.

**Comment by netblue30** [comment]
@rogshdo 

> If I start Tor with firejail, should I also use a Tor chroot like what is described in the Arch wiki or does that not give me anything over what firejail will already do?

The difference is firejail creates the chroot on the fly and applies namespaces and seccomp on top of it. 

@avoidr 
Stay on a branch, I'll merge you when you are done. I'll reopen the issue to keep track of it. 

Thanks.

**Comment by rogshdo** [comment]
@avoidr were you able to make any progress on this?

**Comment by avoidr** [comment]
I were, the difficulty is not the problem. I whitelisted /var/lib/tor/, created a (restrictive) profile and now all that's left to do is copy existing files to the sandbox and then back. But Tor already starts and works correctly. It's just not complete, yet.

I'm sorry I took so long, I had and have shit to deal with. I'll try and complete it by the end of tomorrow's week. Thanks for asking.

**Comment by asyncsatcog** [comment]
I am looking forward to this too. Tor and firejail will be a great combo.

**Comment by rogshdo** [comment]
was any progress made on this?

**Comment by avoidr** [comment]
I am ashamed to say "no". I'm having a really tough time getting motivation to do anything at all. But I seem to get better and I'll fucking get to it soon, once I get some other old shit done, or something. I want to. Yeah. I'm sorry.

**Comment by netblue30** [comment]
No problem, the default Firefox profile will do for now.

**Comment by rogshdo** [comment]
Just checking if there is any progress on this. I'd love to run Tor (not the Tor Browser Bundle) with firejail.

**Comment by netblue30** [comment]
It didn't go anywhere, I guess every tor user has a different view of how the profile should be. This is not necessarily bad.

**Comment by avoidr** [comment]
Sorry guys. I was just afk being all miserable and shit. Shame on fucking me.

**Comment by acrobat1** [comment]
Is the method outlined in [comment 160160384 ](https://github.com/netblue30/firejail/issues/160#issuecomment-160160384) still the way to go, i.e. starting from the default firefox profile and just replacing `whitelist ~/.mozilla` with the path to the actual TOR browser directory?

Do we need some other tweaks too?

**Comment by netblue30** [comment]
Nothing changed in a long time in that area, so try it out. There is also a profile for tor browser here on git on the development version, maybe it will get some fixes before release, I didn't try it yet: https://github.com/netblue30/firejail/blob/master/etc/start-tor-browser.profile

**Comment by chiraag-nataraj** [comment]
For what it's worth, there are a couple of Tor Browser profiles in my repo: https://github.com/chiraag-nataraj/firejail-profiles. As for Tor itself, since I just started using it full-time, I'll look into it!

**Comment by acrobat1** [comment]
Thanks, I'll have a look. In the meantime I've put something together based on the firefox profile with more restrictive options and it (apparently) works but your looks way more refined.

BTW, I' ve also tried to blacklist /usr/bin and it doesn't break anything as far as I can see - but I may be missing something here.

**Comment by chiraag-nataraj** [comment]
Alright, I've uploaded an experimental `tor` profile to the same repository. Give it a whirl and open an issue in that repo if you're having issues!
