### ISSUE TITLE
Unable to save files to symlinked Downloads directory

### ISSUE THREAD

**Issue by TomAshley303** [netblue30/firejail#1601]
I created a link from ~/Downloads to an external hard drive to save my nvme drive from excessive writes and firejail won't save to it.

**Comment by netblue30** [comment]
The directory on the external hard drive has to be owned by your local user. For example, if you have your external hard drive mounted on /mnt, create a Downloads directory there and change the owner:
`````
$ sudo mkdir /mnt/Downloads
$ sudo chown netblue:netblue /mnt/Downloads
`````
Add the symlink:
`````
$ ln -s /mnt/Downloads ~/Downloads
`````
