### ISSUE TITLE
Allow nesting of sandboxes

### ISSUE THREAD

**Issue by marcthe12** [netblue30/firejail#1603]
I believe that we should be able to nest sandboxes. This could allow sandbox of more lower programs

**Comment by SpotComms** [comment]
The permissions required to create the nested sandboxes are dropped upon creating the initial sandbox. Keeping those permissions would allow the programs inside the sandbox to very easily escape.

See https://github.com/netblue30/firejail/issues/1256#issuecomment-298379932
