### ISSUE TITLE
KeepassXC Challenge-Response field is greyed out unless 'private-dev' and 'protocol' are disabled

### ISSUE THREAD

**Issue by Ryujinra** [netblue30/firejail#1605]
KeepassXC has a challenge-response field for unlocking the database with a hardware token. That field is greyed out and authentication is not possible unless protocol and private-dev are commented out in keepassxc.profile (then behaviour is as expected).

**Comment by SpotComms** [comment]
See https://github.com/netblue30/firejail/issues/1553#issuecomment-329915153
