### ISSUE TITLE
youtube-dl domain name resolution does not work if --external-downloader is used

### ISSUE THREAD

**Issue by Ryujinra** [netblue30/firejail#1606]
youtube-dl cannot resolve domain names unless I disable the protocol filter. Does the filter break local DNS resolvers?

UPDATE: This does not appear to be an issue with the DNS resolver, but an issue with --external-downloaders flag in youtube-dl in combination with the protocol filter.

**Comment by SpotComms** [comment]
Which DNS resolver are you using? systemd-resolved? NetworkManager internal? NetworkManager dnsmasq?

If you're using systemd-resolved can you try building from source

**Comment by Ryujinra** [comment]
I am using the NetworkManager. I used the AUR package to build from source and still have the issue. By local DNS resolvers I meant resolvers that are located on the local network.

**Comment by reinerh** [comment]
Strange, for me it's working with the profile from 0.9.50.

**Comment by Ryujinra** [comment]
I found the source of the issue. This only occurs when you use an external downloader. Try doing:

`youtube-dl --external-downloader aria2c [URL]`

**Comment by reinerh** [comment]
Seems to be related to aria2c. With wget and curl it's working.

**Comment by reinerh** [comment]
Name resolution with aria2c doesn't seem to work:
```
$ firejail --profile=/etc/firejail/youtube-dl.profile aria2c https://example.com

10/20 19:18:12 [NOTICE] Downloading 1 item(s)

10/20 19:18:12 [ERROR] CUID#7 - Download aborted. URI=https://example.com
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://example.com
  -> [AbstractCommand.cc:801] errorCode=19 CUID#7 - Name resolution for example.com failed:No address returned

10/20 19:18:12 [NOTICE] Download GID#35dbef234ceece60 not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
35dbef|ERR |        n/a|https://example.com

Status Legend:
(ERR):error occurred.

```

**Comment by veloute** [comment]
i ran into this problem today and found that sending the argument "--async-dns=false" to aria2 fixed the name resolution problem.

**Comment by chiraag-nataraj** [comment]
Is this still an issue?

**Comment by matu3ba** [comment]
@chiraag-nataraj For me it works, also without --async-dns. Should be closed.
