### ISSUE TITLE
noexec ignored

### ISSUE THREAD

**Issue by ltworf** [netblue30/firejail#1608]
I have this profile
```
name myapp
mkdir ${HOME}/.myapp
private ${HOME}/.myapp
noexec ${HOME}/
noexec /tmp
```

However in the private home, the exec permissions are not discarded. I can run binary files from programs running inside firejail with this profile.

**Comment by netblue30** [comment]
Thanks for the bug, all fixed!

**Comment by ltworf** [comment]
Thanks! That was quick!
