### ISSUE TITLE
Mousepad can't access its preferences

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1609]
`GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.`

Uncommenting `private-lib` in Mousepad profile solves the issue.

**Comment by Fred-Barclay** [comment]
Can you try adding `gio` to the private-lib filter?
`private-lib gio`

**Comment by rekixex** [comment]
@Fred-Barclay It works, thanks.

**Comment by Fred-Barclay** [comment]
Awesome! Thanks for the report. The fix is already committed (see 2d61d63d96badfb44c2364599a98586c5e2030db).
