### ISSUE TITLE
Allow blocking gpg agent

### ISSUE THREAD

**Issue by ltworf** [netblue30/firejail#1610]
I have this env var:

```
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
```

If I let a software use unix socket, then it can connect to that, and if I had used my key recently, it could use the agent to do things I don't want it to do.

It would be nice to have a syntax to allow arbitrary variables rather than just ${HOME}, so one could just do `blacklist ${GPG_AGENT_INFO}` to block it.

Also having a ${UID} variable would be nice, and could be used to solve the same problem, so one could block `/run/user/${UID}/gnupg`. and potentially other paths inside there.

**Comment by smitsohu** [comment]
`/run/user/$UID/gnupg` should be blacklisted by default. Is it not working for you?

**Comment by smitsohu** [comment]
:+1: for ${UID}

**Comment by ltworf** [comment]
Ah I am running this proprietary application for work and I am not including the default profile, so the profile I use won't get silent changes from updates of the package.

**Comment by smitsohu** [comment]
The /run/user/$UID/gnupg blacklist was introduced in 0.9.46, but it is hardcoded and not in the profiles.

In case you are running an older version and upgrading is not an option, `blacklist /run/user/*/gnupg` should actually work, too.
