### ISSUE TITLE
Desktop integration does not work with Google Play Music desktop player profile

### ISSUE THREAD

**Issue by semente** [netblue30/firejail#1612]
I can run Google Play Music and listen to music just fine, but some features aren't working such as desktop keyboard shortcuts and GNOME Shell integration.

I'm running firejail version 0.9.50 on a Debian stable (stretch) machine.

Thanks!

PS: @figue do you have this issue?

**Comment by figue** [comment]
Yes I have. Currently I'm launching GPMDP without firejail and Cinnamon desktop integration works just fine, but with firejail that integration is broken. I've tried debugging what's wrong, but I can't find the reason.

Here is a debug output:

https://gist.github.com/figue/f0eb8420309f6e2e6e93b281a510104b

firejail 0.9.50 running in Archlinux, community repository build.

**Comment by SpotComms** [comment]
I doubt its anything to do with avahi, more likely MPRIS.
Can one of you comment out all the options (ignoring whitelist/blacklist/includes) and uncomment them one by one until it breaks?

**Comment by figue** [comment]
Thanks @SpotComms I can confirm that the problem is "noexec /tmp".

https://github.com/netblue30/firejail/blob/master/etc/google-play-music-desktop-player.profile (line 38)

It seems that GPMDP generate some files in /tmp that need to execute. For example:

```
[figue@DESA2338 ~]$ ls -dla /tmp/.*chromium*
-rwxr-xr-x 1 figue users  81690 oct 24 15:58 /tmp/.org.chromium.Chromium.9Zx35g
-rwxr-xr-x 1 figue users 122606 oct 24 15:58 /tmp/.org.chromium.Chromium.gIObAn
-rwxr-xr-x 1 figue users 122606 oct 24 15:58 /tmp/.org.chromium.Chromium.J6VXlY
drwx------ 2 figue users     80 oct 24 15:58 /tmp/.org.chromium.Chromium.KE1WLF
-rwxr-xr-x 1 figue users  20074 oct 24 15:58 /tmp/.org.chromium.Chromium.r6gUnZ
```
Could be safely disabled that option?
Thanks

**Comment by semente** [comment]
Cool, thanks guys!
