### ISSUE TITLE
VLC: machine-id breaks PulseAudio

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#1618]
On Fedora 26 with VLC 3.0 I've made the observation that `machine-id` breaks PulseAudio:

`pulse audio output error: PulseAudio server connection failure: Verbindung verweigert`

After commenting that switch everything works okay.

Can someone confirm this?

**Comment by netblue30** [comment]
Fixed!

Pulse ends up using /etc/machine-id files on some setups. It used to do it all the time on Debian Jessie, now on Stretch it stopped doing it. And if you also have ALSA installed, you never know if the program picks up pulse or alsa. So, it is a full mess! The safe way to go is to remove machine-id from any program using sound.

**Comment by curiosity-seeker** [comment]
> The safe way to go is to remove machine-id from any program using sound.

Yes, indeed! I had also added it to the dragon profile as a test and sound was also broken here.

Thanks for the fix!
