### ISSUE TITLE
Firejail breaks media controls in Plasma taskbar

### ISSUE THREAD

**Issue by rccavalcanti** [netblue30/firejail#1619]
I posted [this bug to KDE](https://bugs.kde.org/show_bug.cgi?id=384837).

Apparently, the cause is that _NET_WM_PID is different from the PID of the jailed program.

    $ pidof vlc
    3466

    $ pidof firejail
    3457

    $ qdbus org.freedesktop.DBus / org.freedesktop.DBus.GetConnectionUnixProcessID \
      org.mpris.MediaPlayer2.vlc
    3466

    $ xprop | grep PID
    _NET_WM_PID(CARDINAL) = 9

**Comment by smitsohu** [comment]
just tried it out in Mate, it is also the reason for #258. Mate labels the titlebar with "as superuser" if _NET_WM_PID indicates root ownership.

**Comment by smitsohu** [comment]
> Apparently, the cause is that _NET_WM_PID is different from the PID of the jailed program.

The reason is that _NET_WM_PID is set to the PID _inside_ the sandbox. Whatever sets _NET_WM_PID, it is not aware of PID namespaces.

**Comment by smitsohu** [comment]
See also #1084

**Comment by smitsohu** [comment]
It looks Gnome have chosen a workaround for Flatpak only: https://bugzilla.gnome.org/show_bug.cgi?id=772615

**Comment by chiraag-nataraj** [comment]
Is this still an issue? I presume it is...

**Comment by rccavalcanti** [comment]
@chiraag-nataraj I'm not using Plasma currently, so I can't say.

**Comment by chiraag-nataraj** [comment]
Okay, I'll close this for now. Please feel free to re-open if you're experiencing this and we'll take a look then.

**Comment by Vincent43** [comment]
This is fixed in [KDE Frameworks 5.61](https://bugs.kde.org/show_bug.cgi?id=384837#c8)
