### ISSUE TITLE
NetworkManager DNS update overrides --dns option

### ISSUE THREAD

**Issue by matthew-nichols** [netblue30/firejail#1621]
If you run `firejail --dns=8.8.8.8` you create a jail with that DNS info. If you then cause NetworkManager to update DNS information (i.e., (dis)connect from WiFi/Ethernet/VPN) the jail will now have the `resolv.conf` from NetworkManager, not from the `--dns` option.

On my system (Debian 9, KDE) `/etc/resolv.conf` is a symbolic link to `/var/run/NetworkManager/resolv.conf` (`/var/run` is a symbolic link to `/run/`).

Running `sudo firejail --dns=8.8.8.8 --noprofile` creates a mount namespace with a tmpfs on `/run/NetworkManager/resolv.conf`. If you then edit `/run/NetworkManger/resolv.conf` in the default namespace with vi (which does an atomic replace that changes the inode, which NetworkManager appears to do) the jail loses that tmpfs mount (`mount | grep resolv.conf`). If you edit with nano the same does not happen.

My firejail version is that from the Debian repositories, 0.9.44.8. I also tried it with the version from backports, 0.9.50, and this behavior appears there as well.

**Comment by netblue30** [comment]
I've been able to reproduce it on Debian 9. In vim you need to set:
`````
:set backupcopy=no
`````
Thanks for the bug!

**Comment by matthew-nichols** [comment]
vim (and NetworkManager) writes a file with a slightly different name and then rename's over the old file. If you change settings in NetworkManager (say, disconnect or reconnect) you will see the inode number change.

**Comment by netblue30** [comment]
Fixed, let me know if there are still problems.
