### ISSUE TITLE
Firejail  failed Firefox Couldn't load XPCOM.

### ISSUE THREAD

**Issue by elpollino** [netblue30/firejail#1623]
Hi guys ,
the Firejail  sandbox is doing well in all applications except in firefox I can not find the solution.
My system requirements . Unknown WJM83ZFYFQTA 999.999.999  x86_64 GNU/Linux
I installed it as it says in source code and everything came out perfect 
`./configure && make && sudo make install-strip`

when I run firefox it mentions this error
`root@WJM83ZFYFQTA:~# firejail --force firefox
Reading profile /usr/local/etc/firejail/firefox.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Warning: noroot option is not available
Parent pid 39, child pid 40
The new log directory is /proc/40/root/var/log
Blacklist violations are logged to syslog
Child process initialized in 8.84 ms
Couldn't load XPCOM.

Parent is shutting down, bye...
`
thank you very much for your help

**Comment by SpotComms** [comment]
Why are you trying to run Firefox as root? Which distro are you on? Is Firefox installed via your package manager?

**Comment by elpollino** [comment]
Hi, thanks for answering this is the information
Firefox root user
Kernel linux-image-999.999.999: amd64
Headers linux-headers-999.999.999: amd64
Distro os, unknown * debian stretch, https://sourceforge.net/projects/sistemas-operativos/
Install Firefox Manually

**Comment by netblue30** [comment]
If you run as regular user instead of root, do you still have the  problem?

**Comment by elpollino** [comment]
I already solved the problem, I need to modify some things and reinstall firefox,
 thank you very much
