### ISSUE TITLE
Software not supported for /31 networks

### ISSUE THREAD

**Issue by tonsimple** [netblue30/firejail#1624]
Tried to use firejail and bring in eth0 using --net=eth0
Got the error in the title.

Any pointers on what to do to work around this?

**Comment by SpotComms** [comment]
/31 is a point-to-point network, using --net checks the arp table to see what addresses are already in use and then tries to assign an address to itself. But in /31 there are only able to be 2 addresses, one that your computer is already using and one in use by the router itself.

A potential workaround could be this https://github.com/netblue30/firejail/issues/1600#issuecomment-335847527

**Comment by ubone** [comment]
bridge might not work for ppp
use a network namespare with `--netns=`
