### ISSUE TITLE
Is it possible to run an appimage game with firejail and save the game data?

### ISSUE THREAD

**Issue by JulianLai** [netblue30/firejail#1626]
`firejail --private --appimage game.appimage` can play the game without problem, but the game data will be lost if I exit the game.

**Comment by reinerh** [comment]
Instead of `--private` use `--private=/some/directory`. The first one uses a temporary filesystem and all changes are discarded at the end of the session. The latter one uses the specified directory as your home directory, so the files inside there will be kept.

**Comment by JulianLai** [comment]
Thank you, I'll try it later.

**Comment by JulianLai** [comment]
It perfectly solves the problem!
