### ISSUE TITLE
Should noexec ${HOME} be changed to noexec ${HOME}/* ? 

### ISSUE THREAD

**Issue by dkwls** [netblue30/firejail#1628]
I have noticed that many profiles contain

`noexec /tmp`
`noexec ${HOME}`

`noexec /tmp` appears to apply recursively but `noexec ${HOME}` does not.

Should `noexec ${HOME}` be changed to `noexec ${HOME}/*` ? 
Also is there any difference between `noexec ${HOME}` and `noexec ~` ?

**Comment by smitsohu** [comment]
Hey @dkwls! 

> noexec /tmp appears to apply recursively but noexec ${HOME} does not.

Can I ask which observation led you to this conclusion?

> Also is there any difference between noexec ${HOME} and noexec ~?

No, they are the same.

**Comment by dkwls** [comment]
Thanks for your reply @smitsohu.

I found that I was able to run scripts contained in ~/bin despite the profile containing `noexec ${HOME}`.

Eventually I was able to isolate the problem. /etc/firejail/vlc.profile contains the following:

`...`
`include /etc/firejail/disable-common.inc`
`...`
`noexec ${HOME}`
`noexec /tmp`


/etc/firejail/disable-common.inc contains:

`...`
`read-only ${HOME}/bin`
`...`


When `read-only ${HOME}/bin` appears before `noexec ${HOME}` as is the case in the default vlc profile (and presumably others) scripts can be executed from ~/bin. If the order is swapped firejail appears to work as expected.

**Comment by dkwls** [comment]
It looks like the root cause is a duplicate of [bug #839](https://github.com/netblue30/firejail/issues/839) but the question about changing `noexec ${HOME}` to `noexec ${HOME}/*` remains.

**Comment by netblue30** [comment]
Leave it as "noexec ${HOME}, I'll try to bring in a fix for it, thanks for the bug.

**Comment by dkwls** [comment]
Thank you.

**Comment by chiraag-nataraj** [comment]
Let's move the discussion of this issue to #2029.
