### ISSUE TITLE
okular: printing is broken

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#1629]
Whenever I try to print a document in Okular, I get the folllowing error:

```
Could not print the document. Detailed error is "Could not find a suitable binary for printing. Make sure CUPS lpr binary is available". Please report to bugs.kde.org
```

If I execute `firejail --debug okular` the output contains:
```
Checking /usr/local/bin/lpr
Checking /usr/bin/lpr
Checking /bin/lpr
Checking /usr/games/lpr
Checking /usr/local/games/lpr
Checking /usr/local/sbin/lpr
Checking /usr/sbin/lpr
Checking /sbin/lpr
Warning: file lpr not found
```
Huh? Strange!

Commenting the `private-bin` line in the profile solves the problem. But why can't lpr be found?

**Comment by smitsohu** [comment]
Hi @curiosity-seeker, sorry for the trouble and thanks for reporting! The likely reason is that lpr for you is a symlink to /etc/alternatives/print. So adding 'alternatives' to the `private-etc` line should fix it.

**Comment by curiosity-seeker** [comment]
Yes, indeed, that fixes the issue! Thank you very much for the quick solution!
