### ISSUE TITLE
Hexchat no write access

### ISSUE THREAD

**Issue by allorder** [netblue30/firejail#163]
Hi, since using firejail 0.9.34-1 for hexchat on debian stable, 
I got this message: 
You do not have write access to /home/allorder/.config/hexchat. Nothing from this session can be saved.

**Comment by netblue30** [comment]
This is a bug! I have no idea how it went in, probably xchat has the same problem.

Workaround: as root, in a text editor open /etc/firejail/disable-common.inc and delete "blacklist ${HOME}/.config/hexchat" line.

I'll put a fix in for the next version, and I'll close the bug when I have it in. Thanks!

**Comment by allorder** [comment]
Thanks!

**Comment by netblue30** [comment]
I have a default hexchat profile in /etc/firejail/hexchat.porfile. Thanks for the bug!
