### ISSUE TITLE
dropbox doesn't seem to update itself when firejailed

### ISSUE THREAD

**Issue by laurento** [netblue30/firejail#1630]
I've noticed dropbox doesn't update itself while running under firejail. The icon on the tray keeps the blue spinning emblem and the contextual menu the "upgrading..." entry.

If I instead run the dropbox application without using firejail everything works as expected. I've tried to look at the dropbox log messages and to run firejail in debug mode but I didn't see anything strange. Please let me know if I can provide any additional information.

**Comment by Fred-Barclay** [comment]
Hi @laurento 
What version of firejail, and what Linux distro, are you running?

I've tried replicating this myself on Ubuntu 17.10, but I can't figure out how to force dropbox to install an old version so I can try updating. 🙁

**Comment by laurento** [comment]
Since I opened the issue here I ran dropbox out the jail to let it upgrade. My current version is v37.4.29 and it has the same issue.

**Comment by Fred-Barclay** [comment]
Closing, thanks!

**Comment by laurento** [comment]
Aaarg! Brand new installation firajail-0.9.4 on Debian Buster (testing) same issue :(

Shall we reopen this issue?

**Comment by Fred-Barclay** [comment]
Yep, reopening!

@laurento please kill dropbox, download https://raw.githubusercontent.com/netblue30/firejail/master/contrib/jail_prober.py, and run
`python3 jail_prober.py dropbox` (you may need to change the dropbox executable path or name -- I don't know what it is :smile: ). Then follow the prompts in the terminal -- enter 'y' if dropbox works correctly and 'n' if it doesn't. Paste the output back here.

(jail_prober.py is an experimental script I wrote -- it works on my end but apologies in advance if it doesn't work for you!).

**Comment by chiraag-nataraj** [comment]
Is this still an issue @laurento?

**Comment by laurento** [comment]
> Is this still an issue @laurento?

Well, last time I've tried (few months ago) the issue was still there. However, I'm now using dropbox via flatpak so I solved using a different kind of confinement :)

**Comment by chiraag-nataraj** [comment]
I guess I'll close this for now then - we can always re-open if it's an issue and they wan to stick with firejail :D

**Comment by chiraag-nataraj** [comment]
Haha I'll re-open it myself since I'm running into the same issue right now :joy:

**Comment by chiraag-nataraj** [comment]
Never mind. I restarted it after it kept spinning and now it says "up to date"...:man_shrugging:

**Comment by chiraag-nataraj** [comment]
Sorry for the noise. I figured out that it didn't actually update.

**Comment by chiraag-nataraj** [comment]
Workaround: Use the control script [here](https://www.dropbox.com/install?os=lnx) and run the `update` operation. If it works, I'll add the workaround label and close this again :stuck_out_tongue_winking_eye:

**Comment by chiraag-nataraj** [comment]
Here's the full workaround:
1. Download [this script](https://www.dropbox.com/install?os=lnx) and put it somewhere you can easily access _within the sandbox_.
2. Edit the `is_dropbox_valid()` function (starts at line `254` I believe) to always `return True` (you don't even need to do much, just ensure that's the first line of the function and you don't even need to touch the rest).
3. Start a sandboxed `dropboxd` instance.
4. Now, run `firejail --join=dropboxd ~/path/to/dropbox.py update`
5. This should update the binary properly.

I just tested this with a `firejail`-ed `dropboxd` and it updated properly! I'm going to close this for now and tag it with the workaround label as stated earlier.

**Comment by cebas** [comment]
Hi, this is still happening to me. 
I have Kubuntu 22.04 and firejail 0.9.70
Is there any way to fix it with local profiles?

**Comment by powerman** [comment]
Still actual.

As a glance `firejail --join=dropbox dropbox-cli update` and then manual restart works around the issue, but it usually starts spinning after a while after restart, so I'm not 100% sure it is actually fixed now.

**Comment by kmk3** [comment]
> Still actual.
> 
> As a glance `firejail --join=dropbox dropbox-cli update` and then manual
> restart works around the issue, but it usually starts spinning after a while
> after restart, so I'm not 100% sure it is actually fixed now.

What firejail version/distribution name/version?

For debugging, you could try commenting lines in dropbox.profile until it works
to see which ones are causing the issue and then post them here.

**Comment by powerman** [comment]
Gentoo Linux. Using default dropbox profile. `globals.local` blacklists a few dirs in `${HOME}`, completely unrelated to dropbox.

```
firejail version 0.9.74

Compile time support:
	- always force nonewprivs support is disabled
	- AppArmor support is disabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file transfer support is enabled
	- IDS support is disabled
	- Landlock support is enabled
	- networking support is enabled
	- output logging is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-lib support is disabled
	- private-cache and tmpfs as user enabled
	- sandbox check is enabled
	- SELinux support is disabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

> For debugging, you could try commenting lines in dropbox.profile until it works
> to see which ones are causing the issue and then post them here.

Sure, I know. But taking in account it starts spinning after a while after start and there is no way to force it start updating immediately - this kind of debugging may take days, if not weeks. Also it's not clear how to undo successful upgrade to force it upgrade again (just remove all files in .dropbox-dist/?).

**Comment by kmk3** [comment]
> > For debugging, you could try commenting lines in dropbox.profile until it
> > works to see which ones are causing the issue and then post them here.
> 
> Sure, I know. But taking in account it starts spinning after a while after
> start and there is no way to force it start updating immediately - this kind
> of debugging may take days, if not weeks. Also it's not clear how to undo
> successful upgrade to force it upgrade again (just remove all files in
> .dropbox-dist/?).

That's unfortunate.

Not sure of a good way to debug it then.

Maybe it would be feasible to analyze the update code and create a separate
script that calls into the update function and/or that allows installing a
specific version.

Similarly to that comment above:

* <https://github.com/netblue30/firejail/issues/1630#issuecomment-495428366>

If that works, maybe it could be published in its own repository to help
improve the experience of other dropbox users.

**Comment by powerman** [comment]
> Similarly to that comment above:

Link "this script" in that comment is useless.
