### ISSUE TITLE
Qt5 do not inherit GTK theme when in a GTK environment [0.9.50]

### ISSUE THREAD

**Issue by johnfocker** [netblue30/firejail#1631]
When using `QT_QPA_PLATFORMTHEME=gtk2` environment variable with `qt5-styleplugins` and loading, for instance, keepassxc (2.2.2 — Qt 5.9.2) with `firejail --noprofile` the GTK theme is loaded.

Running keepassxc with the default firejail profile loads the default Qt5 theme instead and I get:
(not sure which line might be relevant)
```
Reading profile /etc/firejail/keepassxc.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: noroot option is not available
Parent pid 27314, child pid 27315
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 127.45 ms

(keepassxc:7): IBUS-WARNING **: Unable to load /var/lib/dbus/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: nouveau
```

**Comment by netblue30** [comment]
I don't think plugins ever worked, I'll look into it.

**Comment by viking777** [comment]
I have an almost identical error with keepassxc and firejail:

> keepassxc:8): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-U61CB5DNR9: Connection refused
> Qt: Session management error: Could not open network socket
> libGL error: MESA-LOADER: failed to retrieve device information
> libGL error: Version 4 or later of flush extension not found
> libGL error: failed to load driver: i915
> libGL error: failed to open drm device: No such file or directory
> libGL error: failed to load driver: i965

This has occurred since the update from 2.2.4-1 -> 2.3.0-1. The earlier version had no problem with firejail. Using the --noprofile switch allows keepassxc to open normally otherwise it just hangs forever.

**Comment by Vincent43** [comment]
@viking777 can you try this?

**Comment by viking777** [comment]
@Vincent43  I already did try it - no difference.

**Comment by viking777** [comment]
@Vincent43  I had already tried commenting out 'private-tmp' which made no difference, changing that to 'ignore private-tmp' was equally ineffective.
Thanks for the suggestions though.

**Comment by Fred-Barclay** [comment]
@viking777 Is there a line like `export QT_STYLE_OVERRIDE=gtk` in your .bashrc?

Firejail sometimes uses a different .bashrc inside the sandbox than your real one (I don't recall the exact circumstances when this happens just now), so perhaps that's what's going on and QT_STYLE_OVERRIDE=gtk isn't being set inside the sandbox.

**Comment by viking777** [comment]
Thanks for the reply Fred. My .bashrc did not contain that line, so I added it, rebooted and tried again, but no joy, still the same error as above.

I also tried the suggestion in issue 1791 by SkewedZeppelin -  

> should be fixed by commenting net none and blacklist /run/user/*/bus

that didn't work either.

As I mentioned above, it works with the --noprofile switch, so it must be something in the /etc/firejail/keepassxc.profile that is causing it, but I don't know what.

**Comment by viking777** [comment]
I finally got an answer to this. 
I went through the profile line by line commenting out each one in  turn and then attempting to start the program - a very long job! I started at the top and the line that is causing the problem third from the bottom!

Anyway the answer is that in order for it to work you have to comment out the line reading

`memory-deny-write-execute`

I don't know the full consequences of that but it is probably safer than running it with the --noprofile option.
