### ISSUE TITLE
private-bin and symlinks to non-standard paths

### ISSUE THREAD

**Issue by aayla-secura** [netblue30/firejail#1632]
It's kind of common for applications to place their executables in /usr/lib/<program> and install a symlink in /usr/bin (or another location in PATH). Firejail however refuses to use these when private-bin is in force: firejail/fs_bin.c takes the basename of <abs-path> given and looks for such a file in a set of hardcoded paths, resulting in `Warning: file <abs path> not found`. The real executable is present in the sandbox, so it can be called. `follow-symlink-private-bin yes` does not affect this.

Is there a way to make such symlinks work, other than writing a dummy wrapper script that calls the true executable and giving that to private-bin, rather than the symlink?

**Comment by chiraag-nataraj** [comment]
Hmm...on my system, `/usr/bin/firefox` is a symlink to `/usr/lib/firefox/firefox`, and `firejail firefox` with `private-bin` works just fine.

**Comment by aayla-secura** [comment]
Exactly, on my system `/usr/bin/firefox` points to `/usr/lib/firefox/firefox`, but firejail fails to copy the symlink...

**Comment by chiraag-nataraj** [comment]
Huh that's weird. You're using the default profile?

**Comment by aayla-secura** [comment]
No, I have a custom profile, which is mostly similar to the default firefox's with the major differences being

```
whitelist /tmp/runtime-<user>
whitelist /tmp/firefox-esr_<user>
private-tmp
private-etc alternatives,chromium.d,debian_version,firefox,fonts,ld.so.cache,localtime,machine-id,mailcap,mime.types,nsswitch.conf,resolv.conf,ssl
private-bin sh,bash,ls,expr,tempfile,rm,rmdir,mkdir,chmod,install,python,python2,python3,python2.7,python3.5,firefox
```

**Comment by aayla-secura** [comment]
Ok, I figured out that if I give the absolute path to the link as in `private-bin ...,/usr/bin/firefox`, it does not copy it. The function responsible in `firejail/fs_bin.c` is `valid_full_path_file` and I missed a detail when I was first looking at it. So it uses `realpath` to get the canonical path (which would be the link's target in `/usr/lib`), then searches through the standard path for a file with the same basename as the link (which happens to have the same basename as its target, but this is irrelevant here), and finally compares the full path of the file found in one of the standard locations with the path returned by `realpath`... which of course fails.
So with symlinks, I have to give only the basename to `private-bin`. Not sure if it's feasible to fix this and allow full paths for symlinks.

**Comment by netblue30** [comment]
You need to install the latest version here in git - there was a fix earlier regarding symlinks handling in private-bin. For firefox you need the real executable to be under /usr/lib/firefox, otherwise firefox will not work.

A short example for Debian stable:
`````
$ ls -l /usr/bin/firefox*
-rwxr-xr-x 1 root root 113 Sep 28 17:02 /usr/bin/firefox
lrwxrwxrwx 1 root root  30 Sep 28 17:02 /usr/bin/firefox-esr -> ../lib/firefox-
`````
/usr/bin/firefox is a shell script (/bin/sh). The script calls "which" and /usr/bin/firefox-esr. firefox-esr is the symlink pointing to the real executable. This is how I start the sandbox:
`````
$ firejail --private-bin=firefox,firefox-esr,sh,which firefox
`````

**Comment by aayla-secura** [comment]
Yes, as I mentioned in my previous comment, passing a relative name to `private-bin` does copy the symlink, but using the full path fails, i.e.

```
# firejail --quiet --private-bin=/usr/bin/firefox,sh,bash,ls ls -l /usr/bin
-rwxr-xr-x 1 root root 1099016 Nov  7 13:38 bash
-rwxr-xr-x 1 root root  134792 Nov  7 13:38 ls
lrwxrwxrwx 1 root root       9 Nov  7 13:38 sh -> /bin/bash
```

**Comment by netblue30** [comment]
I have a fix in, you can give it a try.

**Comment by aayla-secura** [comment]
Yes, commit b1b1e774a175fe2ee35aa22d02c097e13873a5a9 seems to fix it.

**Comment by netblue30** [comment]
cool! thanks for the bug.
