### ISSUE TITLE
About commenting private-etc in steam.profile

### ISSUE THREAD

**Issue by soredake** [netblue30/firejail#1634]
@SpotComms maybe it's better to find out what exactly the game wants in /etc rather than commenting all private-etc? Because in my case private-etc not breaked any game (yet).

**Comment by SpotComms** [comment]
Yes, I would like to see it enabled again. I still have it enabled in my local profile as I've not seen it break any games. Like I mentioned in https://github.com/netblue30/firejail/issues/1575#issuecomment-332012419 I am not able to repoduce #1575 

I'll try and give it a go again on some other distros sometime soon.
