### ISSUE TITLE
Cannot open files from EncFS

### ISSUE THREAD

**Issue by N-siege** [netblue30/firejail#1645]
I'm unable to open files from a EncFS directory using Firejail's whitelist. Although #1560 solves the problem, I would like to not have to use `allow_root` in EncFS.

Using `--debug-whitelists`:
```
Removed whitelist/nowhitelist path: whitelist ${HOME}/EncFS/Downloads
	expanded: /home/user/EncFS/Downloads
	real path: (null)
	realpath: Permission denied
```

Is possible fix it?

**Comment by netblue30** [comment]
I'll try it out, maybe it's working.

**Comment by netblue30** [comment]
I've found this description in man encfs:

> By default, all FUSE based filesystems are visible only to the user who mounted them. No other users (including root) can view the filesystem contents. 

You need to use allow_root. It applies to all filesystems based on FUSE.
