### ISSUE TITLE
Add p11-kit support

### ISSUE THREAD

**Issue by lhernanz** [netblue30/firejail#1646]
Hi,

I would love to have p11-kit support added in the whitelist-common file. I would propose the following:
```
whitelist ~/.config/pkcs11
read-only ~/.config/pkcs11
```
From their web [https://p11-glue.freedesktop.org/](https://p11-glue.freedesktop.org/):
> This is an effort to use and promote PKCS#11 as glue between crypto libraries and security applications on the open source desktop.

As a security related project, I think it would be of interest for firejail users for it to be supported. The above directory is where the user configuration is stored. All the applications using the p11 library (browsers, ssh, etc.) need to access to those files. This is the reason I am proposing those lines to go to the common file. The configurations file there are not very sensitive, so having global access should not be a huge problem.

Thanks
Regards

**Comment by netblue30** [comment]
Will do!
