### ISSUE TITLE
Mutt cannot get to the email user file

### ISSUE THREAD

**Issue by lhernanz** [netblue30/firejail#1648]
Ubuntu 16.04 running 0.9.50. Mutt cannot get to /var/mail/username as /var/mail is blacklisted in disable-common.inc.
A `noblacklist /var/mail` clause is needed in the mutt profile.

**Comment by Fred-Barclay** [comment]
G'day @lhernanz !
This was added by @smitsohu in a3b053dba9778520708460c37b4fcfc2da95d5c3. You should see this when firejail 0.9.52 is released. 😄 
Cheers!
Fred

**Comment by lhernanz** [comment]
Thanks! 
Next time I will look into master to see if you have already fixed the problem. This project is evolving really fast :)

**Comment by lhernanz** [comment]
I updated to 0.9.52-2. Mutt can get to the spool file now, but only in read-only mode. Probably the reason is the default configuration where var is mounted in read-only mode. Can you add a `writable-var` or similar so that mutt can write into the file?
Thanks
