### ISSUE TITLE
Folder /files is Accessible in Chrome

### ISSUE THREAD

**Issue by cryptogun** [netblue30/firejail#1649]
Isn't whitelist mode the default mode and block anything in the list?
I created a folder `files` under Linux root directory `/` and stored all organized files in it.
Now I found that besides `~/Downloads`, I can access the new folder `/files` in Chrome.
I'd prefer a whitelist mode for all applications.
Tried re-clone and install, no help.

**Comment by chiraag-nataraj** [comment]
The easiest way to resolve this is to create local profiles in `~/.config/firejail`, which will then take precedent. Recently the default profiles were strengthened considerably, especially when it comes to access to files in the home directory. If you want to set up a whitelist mode, you could create `/etc/firejail/globals.local` (which I believe is sourced by most/all profiles) or `/etc/firejail/default.local` (which is sourced by the default profile only). I think the reason this isn't the default is that it has the potential to break many more things by default (right @netblue30?) and the idea is that firejail should be easy and painless to use.

**Comment by curiosity-seeker** [comment]
> I created a folder files under Linux root directory / and stored all organized files in it.
Now I found that besides ~/Downloads, I can access the new folder /files in Chrome.

Yes, this is expected. The `whitelist` switch does not apply to that new folder. `man firejail` explicitly says:

> The top directory could be user home, /dev, /media, /mnt, /opt, /srv, /var, and /tmp.

So to prevent any access to that folder you should create this rule:

`blacklist /files`

in `/etc/firejail/globals.local` as suggested by @chiraag-nataraj

**Comment by cryptogun** [comment]
Got it. My `globals` is under `/usr/local/etc/firejail/`

Maybe I should move my folders to home directory. Because Dropbox failed to start today...

`Error: only directories in user home or /tmp are supported by mkdir`
`Error: invalid whitelist path /files/secret__dropbox/Dropbox`
