### ISSUE TITLE
Whitelist/Backlist with subfolders (mount points - ZFS)

### ISSUE THREAD

**Issue by nicovs** [netblue30/firejail#1650]
In my server setup I have a ZFS filesystem folder structure where each users has his own ZFS filesystem

- /zfspool
- /zfspool/config
- /zfspool/userhomes
- /zfspool/userhomes/user1
- /zfspool/userhomes/user2
- /zfspool/userhomes/user3
- ...

What I would like to achieve is that when a user logs in, he/she can see only his/her  own homefolder (and mount point)
eg, when i ssh into the server as user user2, when the user does an ls on /zfspool/userhomes, he only see's /zfspool/userhomes/user2, but not the other folders.

What I've got this far, with blacklisting is that the users can see all home folders from other users, just not the content, like this:
```
user2@server:~$ ls /zfspool/userhomes
ls: cannot open directory '/zfspool/userhomes/user1': Permission denied
/zfspool/userhomes/user2:
anotherfile.txt file.log folder1 folder2 morefolders morefiles.sh
ls: cannot open directory '/zfspool/userhomes/user3': Permission denied
ls: cannot open directory '/zfspool/userhomes/user4': Permission denied
```

So, how can I achieve only seeing:
```
user2@server:~$ ls /zfspool/userhomes
/zfspool/userhomes/user2:
anotherfile.txt file.log folder1 folder2 morefolders morefiles.sh
```

My login.users:
```
user*:--profile=/etc/firejail/shared_ssh_jail.profile --x11=none --rmenv=PROMPT_COMMAND --shell=/bin/bash -- /bin/bash --login
```

My profile /etc/firejail/shared_ssh_jail.profile:
```
quiet

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

caps.drop all
netfilter
nodvd
nogroups
nonewprivs
noroot
nosound
notv

private
noblacklist ${HOME}/
blacklist /zfspool/c*
blacklist/zfspool/userhomes/*

private-bin sh,bash,mesg,ls,nano,git,git-core,mysql,echo,cp,rm,mv,ln,date,grep,egrep,fgrep,dir,vdir,groups,df,du,python,python3,cat,ps,tail,ping,hostwget,curl,drush,env,wp,which,less,more,tail,head,dig,touch,vi,vim,vim-basic
private-etc group,hostname,localtime,nsswitch.conf,passwd,resolv.conf
private-tmp
```

**Comment by smitsohu** [comment]
If I understand it correctly, would it help to `--whitelist=/zfspool/userhomes/$USER`? This will not work in the profile, only on the commandline.

**Comment by nicovs** [comment]
Hi @smitsohu, i might be able to change my zfspool to /srv eg.
no option to add /data as a whitelistable path? :) (my actual location os /data, not /zfspool. this was as an example.

**Comment by smitsohu** [comment]
>  i might be able to change my zfspool to /srv eg

as a quick solution, at least for trying out if it works for you, it should be sufficient to `sudo mount -o bind /data /srv`. Then you can whitelist in /srv and blacklist /data altogether

**Comment by nicovs** [comment]
@smitsohu : you proposed fix with the mount `mount -o bind /data/userhomes/user2/ /srv/user2/` works like a charm, just need to change my users homedir in /etc/passwd as well.

So... might have a fix 👍

**Comment by nicovs** [comment]
To give more feedback @smitsohu:

login.users:
```
user1:--profile=/etc/firejail/shared_ssh_jail.profile --whitelist=/srv/user2 --x11=none --rmenv=PROMPT_COMMAND --shell=/bin/bash -- /bin/bash --login
user2:--profile=/etc/firejail/shared_ssh_jail.profile --whitelist=/srv/user2 --x11=none --rmenv=PROMPT_COMMAND --shell=/bin/bash -- /bin/bash --login
anotheruser:--profile=/etc/firejail/shared_ssh_jail.profile --whitelist=/srv/anotheruser --x11=none --rmenv=PROMPT_COMMAND --shell=/bin/bash -- /bin/bash --login
```

the profile:

```
blacklist /data*

private-bin sh,bash,mesg,ls,nano,git,git-core,mysql,echo,cp,rm,mv,ln,date,grep,egrep,fgrep,dir,vdir,groups,df,du,python,python3,cat,ps,tail,ping,host,php7.0,php5.6,php7.1,wget,curl,drush,env,wp,which,php,less,more,tail,head,dig,touch,vi,vim,vim-basic,find
private-etc group,hostname,localtime,nsswitch.conf,passwd,resolv.conf
private-opt ls
private-tmp

# Miscellaneous options
seccomp
```

Together with my good old friend autofs :)

/etc/auto.master:
```
+auto.master
/srv     autofs.sshjail
```

/etc/autofs.sshjail
```
* -fstype=bind :/data/userhomes/&
```

**Comment by smitsohu** [comment]
Cool! But it works :) I guess this can be closed then?

**Comment by nicovs** [comment]
just checking some more stuff.... seems it's not 100% yet 🗡

**Comment by nicovs** [comment]
Ok, all checked out and working. Changed the login.users in my comment above. Seems you cannot user `--whitelist=${HOME}` or `--whitelist=~/` but you need to used the full path.

Can be closed

**Comment by smitsohu** [comment]
Closed. Thanks for sharing.
