### ISSUE TITLE
zathura fails to start with default zathura.profile

### ISSUE THREAD

**Issue by Artefact2** [netblue30/firejail#1654]
When using the default zathura.profile, zathura complains about D-Bus and only displays a black window, failing to load the document.

~~~
firejail zathura foo.pdf

Reading profile /etc/firejail/zathura.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: noroot option is not available
Parent pid 26574, child pid 26575
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 72.05 ms

** (zathura:6): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-lJWdxrYETl: Connection refused
~~~

I am using firejail 0.9.50. Any ways to solve or work around this?

**Comment by smitsohu** [comment]
Hi @Artefact2, could you try `firejail --ignore=net zathura foo.pdf`?

**Comment by Artefact2** [comment]
Hi @smitsohu, it does work. But I assume, with those flags, it is no longer prevented from accessing the network?

**Comment by Artefact2** [comment]
`firejail --noblacklist='/run/user/*/bus' zathura foo.pdf` is interesting. The program still complains about a refused connection, but renders the document correctly.

**Comment by smitsohu** [comment]
It's a bug, thanks!

The sandbox is still isolated pretty much from networks owing to `protocol unix`.

**Comment by smitsohu** [comment]
> firejail --noblacklist='/run/user/*/bus' zathura foo.pdf is interesting. The program still complains about a refused connection, but renders the document correctly.

It probably means that you have two dbus-daemon processes running on your system, one using the /run/user/*/bus socket and the other using an abstract socket. You can run `netstat -p | grep dbus-daemon` to get an idea, abstract sockets are prepended there with an @.
With `blacklist=/run/user/*/bus` you shut down connection to one daemon, with `net none` you shut down connection to the other.

The error message in your first post points to an [AT-SPI](https://wiki.linuxfoundation.org/accessibility/atk/at-spi/start) bus, with probably a socket in the abstract namespace. So it might be that zathura is happy with the AT-SPI bus even though the actual session bus is not available under /run/user/$UID/bus.

**Comment by smitsohu** [comment]
Anyways, we will need to comment both `blacklist=/run/user/*/bus` and `net none` in the default profile, because for part of our userbase all D-Bus sockets are abstract, and while `net none` works fine for you, it will break zathura for them.

Creating a file /etc/firejail/zathura.local with
```
net none
noblacklist /run/user/*/bus
```
should solve this issue for you.
