### ISSUE TITLE
Starting different firejailed Firefox versions

### ISSUE THREAD

**Issue by macandchief** [netblue30/firejail#1656]
I guess it's more like a question, not really an issue. I've been using the command `firejail firefox -p --no-remote`, which works fine with the old Firefox version installed on the system.

However there is a new Firefox version in ~/road/to/new/firefox/version. Being in this directory I can start this version via `./firefox -p --no-remote`. My question is: How do I start this new Firefox version in Firejail?

If I simply use firejail firefox in that directory, it simply starts the old version.

**Comment by macandchief** [comment]
Just for the record: When I try to start Firefox from the new versions folder via `firejail firefox`, I get: `Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 26754, child pid 26755
Blacklist violations are logged to syslog
Child process initialized
/bin/bash: ./firefox: No such file or directory

Parent is shutting down, bye...`

**Comment by smitsohu** [comment]
> /bin/bash: ./firefox: No such file or directory

It should work if you copy your new firefox to /opt and launch it from there... I think this would be the recommended way. But if want to keep it in your home folder, try `firejail --whitelist=~/road/to/new/firefox/version ./firefox`.

**Comment by macandchief** [comment]
Thank you, really appreciate. I opted for

firejail /opt/firefox/firefox -p --no-remote

and it works like a charm.
