### ISSUE TITLE
Qbittorrent doesn't remember torrents after restart

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#1665]
When firejailed, qbittorrent works great but if I shut it down and restart it, it forgets all the torrents, so I have to start from scratch with the incomplete ones (remnants are still on drive).

Fedora 27.

**Comment by smitsohu** [comment]
Is it possible you start qbittorrent directly from your browser (open-file-with ... dialog)?

**Comment by netblue30** [comment]
What version of firejail are you using?

**Comment by Futureknows** [comment]
Believe I solved it, I was allowing qbittorent to autostart... the autostart command included the full path so it was launching outside of firejail. When I restart it runs inside of firejail so can't see the unsandboxed prefs. I edited the autostart to launch firejailed. will report back if it isn't solved.

Thanks for suggestions!

**Comment by ald0n** [comment]
Have the same issue. qBit in fj also didn't get the free space on disk. I guess it's changing rules in 3.x and 4.x versions.
