### ISSUE TITLE
Arch Linux Firefox: private-etc and Firefox quantum sound issues

### ISSUE THREAD

**Issue by H2KChicken** [netblue30/firejail#1666]
Noticed that, on Arch Linux, sound would not function when using private-etc.

After troubleshooting, I noticed that adding "machine-id" fixes the problem. I think this may have something to do with the fact that I'm using KDE. After adding "machine-id" to private-etc, sound began to function as expected again.

private-etc passwd,group,hostname,hosts,localtime,nsswitch.conf,resolv.conf,xdg,gtk-2.0,gtk-3.0,X11,pango,fonts,firefox,mime.types,mailcap,asound.conf,pulse,machine-id

Just wanted to bring this to your attention.

**Comment by SpotComms** [comment]
This is already fixed in master. See b7828e463f868e66e1d5fc6fc48328b6437e0504
