### ISSUE TITLE
Running unjailed programs from within jail

### ISSUE THREAD

**Issue by metasyntacticQuux** [netblue30/firejail#1667]
Is there a way to have a jailed program execute unjailed programs with full permissions? I've intentionally jailed my Firefox in such a way that it cannot access my personal documents. I've created a program to handle downloading files, and it works perfectly without firejail. I need it to run outside of the jail when Firefox launches it from within the jail.

**Comment by SpotComms** [comment]
That would allow the jailed program to easily escape. So no. I'm sure there is an issue that describes it some more, but I cannot find one right now.

**Comment by metasyntacticQuux** [comment]
Sorry, I meant whitelisting which programs can be run outside of the jail. Obviously if you can run any program you can do anything.

**Comment by reinerh** [comment]
It's not possible. Once the seccomp filters and other restrictions are in place, they affect all the forked programs.
