### ISSUE TITLE
Error: cannot create ~/.local/application directory

### ISSUE THREAD

**Issue by francoism90** [netblue30/firejail#1670]
```
$ sudo firecfg
Configuring symlinks in /usr/local/bin
Error: cannot create ~/.local/application directory
mkdir: No such file or directory
```
Note: this is on a headless server. Desktop and other PC's it is working fine.

Thanks!

**Comment by netblue30** [comment]
Thanks for the bug, I put a fix in https://github.com/netblue30/firejail/commit/41e2c50dd50f241ef07597a888b249c836fe4de4

**Comment by francoism90** [comment]
@netblue30 Many thanks! :)

**Comment by francoism90** [comment]
@netblue30 Hmm, now getting the following error: `Error: cannot open /usr/share/applications directory: No such file or directory`

**Comment by netblue30** [comment]
No problem, we'll do as many iterations as necessary. New fix on mainline:  https://github.com/netblue30/firejail/commit/49901c87601a0ae9f734854f2dd521541582c046
