### ISSUE TITLE
Cannot start with firejail by default

### ISSUE THREAD

**Issue by qutetemp** [netblue30/firejail#1673]
I cannot get programs to start with firejail as default using sudo ln -s /usr/bin/firejail /usr/local/bin/[program name] but firejail [program name] works just fine.

% echo $PATH
/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

Is it the path oder ?

**Comment by SpotComms** [comment]
Eh, have you tried simply running `sudo firecfg`?

**Comment by qutetemp** [comment]
Yep. That was it. Thank you.
