### ISSUE TITLE
firefox crash - apparmor or protocol entry in the profile

### ISSUE THREAD

**Issue by rahiel** [netblue30/firejail#168]
After some time firefox freezes (unresponsive) and leaves these error messages:
```
(firefox:1): GStreamer-WARNING **: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
libdc1394 error: Failed to initialize libdc1394

(firefox:1): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'

(firefox:1): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(firefox:1): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(firefox:1): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(firefox:1): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
```

This is on Ubuntu 15.10 with firejail 0.9.34. This does not occur on version 0.9.28. It also happens with `firejail --private firefox`.

**Comment by netblue30** [comment]
I've fixed this problem some time ago in the master branch. You need to replace "protocol unix,inet,inet6" with "protocol unix,inet,inet6,netlink" in /etc/firejail/firefox.profile. It has something to do with the video camera.

**Comment by rahiel** [comment]
Changing that line in the profile, I get the same crash. I also compiled
and installed firejail from master and get the same error messages.

**Comment by netblue30** [comment]
If you remove the protocol line from the profile file, do you still get the crash? Also, make sure you are not already running firefox when you start it in the sandbox.

**Comment by rahiel** [comment]
It works now with the firefox profile in master. The problem was a conflict with apparmor, it gave this error:
```
org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.739" (uid=1000 pid=17390 comm="/usr/lib/firefox/firefox ") interface="org.gtk.vfs.MountTracker" member="ListMountableInfo" error name="(unset)" requested_reply="0" destination=":1.6" (uid=1000 pid=1226 comm="/usr/lib/gvfs/gvfsd ") (g-dbus-error-quark, 9)
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Can't find symbol 'glXCreateContextAttribsARB'.
```
Firefox works fine with either apparmor or firejail, but not both. I've disabled apparmor for now.

**Comment by netblue30** [comment]
Question: if you put "protocol unix,inet,inet6" and disable apparmor, does it work?

**Comment by rahiel** [comment]
> Question: if you put "protocol unix,inet,inet6" and disable apparmor, does it work?

Yes it works.

**Comment by netblue30** [comment]
Thanks!
