### ISSUE TITLE
Firejail doesn't pass env TMPDIR variable after update to 0.9.52

### ISSUE THREAD

**Issue by Vincent43** [netblue30/firejail#1682]
```
firejail --quiet --env=TMPDIR=/tmp bash
echo $TMPDIR

firejail --quiet --env=BLAHBLAH=/tmp bash
printenv |grep -i BLAHBLAH
BLAHBLAH=/tmp

```

**Comment by netblue30** [comment]
I cannot reproduce it:
`````
$ firejail --quiet --env=TMPDIR=/tmp bash
$ echo $TMPDIR
/tmp
`````

**Comment by Vincent43** [comment]
I investigated further and it seems that `noroot` option breaks TMPDIR:

```
firejail --noprofile --noroot --env=TMPDIR=/tmp bash
Parent pid 6479, child pid 6480
Child process initialized in 18.72 ms
$ echo $TMPDIR

firejail --noprofile --env=TMPDIR=/tmp bash
Parent pid 6536, child pid 6537
Child process initialized in 21.94 ms
$ echo $TMPDIR
/tmp
```

**Comment by netblue30** [comment]
The problem seems to be --noprofile, without it works fine:
`````
$ firejail --quiet --noroot --env=TMPDIR=/tmp bash
[netblue@debian nodejs]$ echo $TMPDIR
/tmp
`````
I'll try to find out what's going on, thanks for the bug!

**Comment by curiosity-seeker** [comment]
@netblue30 : But as mentioned [here](https://github.com/netblue30/firejail/issues/1594#issuecomment-352261883) the problem also exists with a profile.

**Comment by Vincent43** [comment]
For me it also happens when `noroot` is set in profile. That's why my first report was based on default.profile which has `noroot` enabled.

**Comment by chiraag-nataraj** [comment]
I just ran across this same issue. Do we know what's causing it?

**Comment by Vincent43** [comment]
Someone would have to bisect this between 0.9.50 and 0.9.52.

**Comment by Vincent43** [comment]
Hmm, I tested all firejail versions since 0.9.46 and could reproduce this issue in all of them. That means it isn't related to firejail. I read that [glibc blocks passing TMPDIR variable for setuid apps](https://serverfault.com/questions/478741/sudo-does-not-preserve-tmpdir) but then it should do it without `noroot` as well,  which isn't the case.

This issue is reproducible on Archlinux, don't know about other distros. It could be tied to some specific config or system packages versions.

**Comment by chiraag-nataraj** [comment]
I'm having the issue on Debian as well, so I don't think it's distro-specific. How can I further help debug this?

**Comment by Vincent43** [comment]
It's fixed on my machine with https://github.com/netblue30/firejail/commit/bbaba69f23ae9e181677044b5afb8c29b3eb83b5
