### ISSUE TITLE
Add Figaro's Password Manager 2 to disable-passwdmgr.inc

### ISSUE THREAD

**Issue by atelszewski** [netblue30/firejail#1684]
Hi,

Please add Figaro's Password Manager 2 (https://als.regnet.cz/fpm2/) store directory to /etc/firejail/disable-passwdmgr.inc:
`blacklist ${HOME}/.fpm`

Thanks!

--
Best regards,
Andrzej Telszewski

**Comment by netblue30** [comment]
Thanks, all set: https://github.com/netblue30/firejail/commit/7b15c335c31227917c34a3c535b5e27481cd0d91
