### ISSUE TITLE
firemon and proc hidepid not working for regular user

### ISSUE THREAD

**Issue by atelszewski** [netblue30/firejail#1685]
Hi,

I have /proc mounted with hidepid like that:
`proc on /proc type proc (rw,hidepid=2,gid=2001)`

I have my user added to the "showpid" group like that:
```
$ grep showpid /etc/group
showpid:x:2001:antezu
```
Using htop, I'm able to view other users' processes.

But when I try firemon --tree, I get:
`Error: /proc is mounted hidepid, you would need to be root to run this command`

Is there something wrong on my side or firejail's?

Thanks!

--
Best regards,
Andrzej Telszewski

**Comment by netblue30** [comment]
hidepid will prevent firemon tool to access pid information for root processes. Grab the latest version from git main, and use "firejail --tree" instead. I put some fixes in to allow firejail to access all pid information.  You can also run firemon as root (sudo firemon --tree).

**Comment by atelszewski** [comment]
Hi,

I'm using version 0.9.52.

I tried "firejail --tree" and it works, although it gives some errors at the end and I don't know if they are any relevant:
```
$ firejail --tree
1522:antezu:/usr/bin/firejail /usr/bin/thunderbird 
  1528:antezu:/usr/bin/firejail /usr/bin/thunderbird 
    1587:antezu:/usr/bin/thunderbird 
1524:antezu:/usr/bin/firejail /usr/bin/liferea 
  1532:antezu:/usr/bin/firejail /usr/bin/liferea 
    1690:antezu:/usr/bin/liferea 
(...)
5008:antezu:firejail --tree 

Error: netlink socket problem
Error: failed to run /usr/bin/firemon
```

Anyway, I'm not using this functionality heavily and I'm not going to test the git version.
Mostly, I wanted to signal the possible problem and know what is the solution.

You might close this issue, since I'm satisfied with the reply ;-)

Thanks!

--
Best regards,
Andrzej Telszewski

**Comment by netblue30** [comment]
>Error: netlink socket problem

I put a fix in git for it, thanks!
