### ISSUE TITLE
Add private-etc services to steam.profile

### ISSUE THREAD

**Issue by Q3CPMA** [netblue30/firejail#1688]
Hello,

looks like you'll need it if you don't want Borderlands 2 to crash on you when trying to connect to SHIFT.

https://github.com/flathub/com.valvesoftware.Steam/issues/5
https://github.com/NixOS/nixpkgs/pull/31480

**Comment by SpotComms** [comment]
@Q3CPMA thanks. I've added it, however I'm unable to test. I actually spent an hour or so a few weeks back trying to get BL2 to launch with many different command line arguments, to no avail. I'm not too sure what happened since it worked fine two or so months ago.

**Comment by Q3CPMA** [comment]
On Gentoo, I just had to add this and use the launch option `SSL_CERT_DIR=/etc/ssl/certs` as per https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Borderlands_2
