### ISSUE TITLE
firejail  0.9.52 breaks qbittorrent  4.0.3 (qt5-base  5.10.0)

### ISSUE THREAD

**Issue by trytip** [netblue30/firejail#1690]
` ~ $ firejail qbittorrent
Reading profile /etc/firejail/qbittorrent.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 12775, child pid 12776
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 111.25 ms

Parent is shutting down, bye...
`
worked fine with firejail 0.9.50 which i had to downgrade to for now. not sure what other info you would need.  **firejail --noprofile qbittorrent** works with 0.9.52.  it is broke in arch linux latest xfce and also in mint linux mate 17.3

**Comment by Vincent43** [comment]
Works for me without issues.

**Comment by trytip** [comment]
i made a video showing that firejail 0.9.52 breaks qbittorrent 4.0.3 (qt5-base 5.10.0)
https://youtu.be/JHlWbCu59UY

**Comment by Vincent43** [comment]
I believe you but info that you provided is insufficient to reproduce it on my machine (Archlinux, qt5-base 5.10.0, qbittorrent 4.0.3, firejail 0.9.52.) I see some errors you have on terminal. What's your desktop environment? Can you test in different DE? It works for me inKDE plasma 5.11.4.

**Comment by trytip** [comment]
firejail 0.9.52 also breaks qbittorrent 3.3.16 (qt5 5.2.1) in mint mate 17.3
replacing the /etc/firejail/qbittorrent.profile from 9.50 to 9.52 makes it work.  i get the same errors in both arch/xfce as in mint/mate

for now i will stick with 9.50 until i can figure out why /etc/firejail/qbittorrent.profile works in 9.50 and not in 9.52

**Comment by Vincent43** [comment]
Try disabling options from `/etc/firejail/qbittorrent.profile` one by one until you find those which brakes stuff.

**Comment by trytip** [comment]
issue still remains but if developer has no interest then i closed

**Comment by Fred-Barclay** [comment]
G'day @trytip . This isn't a case of no interest but little time. :smile: I at any rate have already been trying to replicate and fix this, but I haven't been able to duplicate it on my main Arch box. I've already downloaded a Mint 17.3 MATE 64-bit iso but haven't been able to set up a virtual machine for it yet.

I suspect, though, that the line `memory-deny-write-execute` is to blame, since it was added to the qbittorrent profile by me after the release of firejail 0.9.50, and you say that the qbittorrent 0.9.50 profile works even in firejail 0.9.52. `memory-deny-write-execute` is one of those features that can be a bit tricky to implement properly and may cause issues for others even if we don't catch them in testing.

If you don't mind, I've reopened this. It's something we need to get fixed if possible.

**Comment by Vincent43** [comment]
@trytip Developers are waiting for you to provide more info as nobody has reproduced your issue yet and they don't have crystal ball. It's possible that it something specific to your system config. I told you what to do. The ball is on your side.

**Comment by trytip** [comment]
@Fred-Barclay thanx for the interest.  i'm told to provide more info but not sure what else to input i use arch/xfce updated latest and linux mint mate/17.3 arch is qbittorrent 4.0.3 and in mint is 3.3.16 (x64 system for both)

in both systems if i use qbittorrent.profile from 9.50 it works with 9.52.  made a video for the mint session but i can reproduce it identically in arch/xfce
https://youtu.be/Mu6T1J09eWQ

**Comment by Fred-Barclay** [comment]
If you had time to work through the profile from 0.9.52 by commenting out the lines:
```
include /etc/firejail/whitelist-var-common.inc
shell none
private-bin qbittorrent
memory-deny-write-execute
noexec ${HOME}
noexec /tmp
```
and then uncomment them one-by-one, starting qbittorrent each time until you find the line that kills it. That would be a huge help. 😄 
(To comment, add a `#` to the beginning of the line - for instance, `shell none` would become `# shell none`.)

Cheers!
Fred

**Comment by GSF1200S** [comment]
I'm not the OP but I also have firejail and qbittorrent on Arch Linux. I too found that qbittorrent

First I checked when I updated Firejail and then went to a btrfs snapshot prior to that date checking qbittorrent.profile. I commented out the changes in the later profile and it worked, so then went one by one re-enabling them. For me memory-deny-write-execute prevented qbittorrent's interface from showing up, though terminal output didnt suggest anything catastrophic. Firejail's debug output didn't help me right off- I planned to dig through things more when I had time. @Fred-Barclay I can post firejails debug output later when I am home if that would help.

I had one other issue with the later profile- the python search function of qbittorrent didnt work if I had private-bin qbittorrent enabled in the profile- commenting it out saw that feature work again. I don't know if I should file a new bug report for this, whether its a known tradeoff for security, or if a bug report already exists- I haven't had a chance to look.

**Comment by Fred-Barclay** [comment]
Thanks @GSF1200S ! That debug output would certainly be helpful.

> I had one other issue with the later profile- the python search function of qbittorrent didnt work if I had private-bin qbittorrent enabled in the profile- commenting it out saw that feature work again

Can you try adding `python*` to the private-bin filter?

**Comment by GSF1200S** [comment]
> Can you try adding python* to the private-bin filter?

Had to create another private-bin line for python*, but it works fine now.

> That debug output would certainly be helpful.

Going to use a Debian pastebin because it isn't crap, but to clarify I am on Arch with this run: https://paste.debian.net/1002690/

**Comment by Fred-Barclay** [comment]
Okay, can you copy this to ~/.config/firejail/qbittorrent.profile and see if everything works?
```
# Firejail profile for qbittorrent
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/qbittorrent.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.cache/qBittorrent
noblacklist ${HOME}/.config/qBittorrent
noblacklist ${HOME}/.config/qBittorrentrc

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

mkdir ${HOME}/.cache/qBittorrent
mkdir ${HOME}/.config/qBittorrent
mkdir ${HOME}/.local/share/data/qBittorrent
whitelist  ${DOWNLOADS}
whitelist ${HOME}/.cache/qBittorrent
whitelist ${HOME}/.config/qBittorrent
whitelist ${HOME}/.config/qBittorrentrc
whitelist ${HOME}/.local/share/data/qBittorrent
include /etc/firejail/whitelist-common.inc
include /etc/firejail/whitelist-var-common.inc

caps.drop all
machine-id
netfilter
nodvd
nogroups
nonewprivs
noroot
nosound
notv
novideo
protocol unix,inet,inet6,netlink
seccomp
shell none

private-bin qbittorrent,python*
private-dev
private-tmp

noexec ${HOME}
noexec /tmp
```
Thanks!

**Comment by GSF1200S** [comment]
I just edited /etc/firejail/qbittorrent.profile directly (and made sure nothing existed in ~/.config/firejail)- works fine! Application loads, python search functions work, and everything else I tested.

**Comment by Fred-Barclay** [comment]
Awesome, thanks @GSF1200S !

@trytip I think this should get everything so I'll close for now, but feel to comment/reopen if this doesn't work for you (or just to say that it does work). :smile: I would recommend you move back to 0.9.52 (if you haven't already) - you can use the updated, working qbittorrent profile by copying https://raw.githubusercontent.com/netblue30/firejail/281ad508084018c34acef505412450bfde0a6ab7/etc/qbittorrent.profile to ~./config/firejail/qbittorrent.profile (or editing the profile in /etc/).

Cheers and thanks for the report!
Fred

**Comment by trytip** [comment]
thank you @Fred-Barclay  and @GSF1200S the new qbittorrent.profile **works**. i also replaced it in etc/firejail of my ARCH Linux install

thanx again for your patience

**Comment by Fred-Barclay** [comment]
That's great! Cheers!
