### ISSUE TITLE
/usr/bin/string cannot read /proc/*/environ

### ISSUE THREAD

**Issue by elvetemedve** [netblue30/firejail#1692]
### The problem

**strings** cannot read file from **/proc** filesystem.

`strings /proc/1190/environ`

> Reading profile /etc/firejail/strings.profile
> Reading profile /etc/firejail/default.profile
> Reading profile /etc/firejail/disable-common.inc
> Reading profile /etc/firejail/disable-passwdmgr.inc
> Reading profile /etc/firejail/disable-programs.inc
> Parent pid 12877, child pid 12878
> Standard C library installed in 15.13 ms
> Program libraries installed in 4.18 ms
> Installed 23 libraries and 1 directories
> Warning: /sbin directory link was not blacklisted
> Warning: /usr/sbin directory link was not blacklisted
> Blacklist violations are logged to syslog
> Child process initialized in 82.04 ms
> /usr/sbin/strings: '/proc/1190/environ': No such file
> 
> Parent is shutting down, bye...
> 

However the file does exist.
`ls -l /proc/1190/environ`

> -r-------- 1 geza geza 0 Dec 25 14:09 /proc/1190/environ

### Environment

Firejail version: 0.9.52

**Comment by reinerh** [comment]
That's actually a feature, as firejailed programs can't access process information of other processes (they are in a separate namespace).

Instead of trying to open the file from the jailed process, you could pass it the content on stdin.
This should work: `strings < /proc/.../environ`.

**Comment by elvetemedve** [comment]
@reinerh Thanks. I wasn't aware of the consequences of namespaces. I learned someting again. :)

That did the trick actually. Thank you.
