### ISSUE TITLE
please add basilisk browser

### ISSUE THREAD

**Issue by bn0785ac** [netblue30/firejail#1693]
you can just copy&paste pale moon profile

replacing pale moon  with basilisk

pd
its unrelated, but please optimize bnox and dnox profiles (they run, but thay cant use their dirs)
its just copy&paste inox profile (replacing inox with bnox  and dnox)

**Comment by netblue30** [comment]
Basilisk is in, you can try it out.

**Comment by netblue30** [comment]
I think all is fixed here, we'll reopen it if necessary.
