### ISSUE TITLE
Jack audio does not work with private-dev

### ISSUE THREAD

**Issue by aineko** [netblue30/firejail#1694]
Ardour5 (and probably any other app using Jack) needs to connect to the Jack server at /dev/shm/jack*, which is not available with private-dev:

[pid    15] connect(8, {sa_family=AF_UNIX, sun_path="/dev/shm/jack_default_1000_0"}, 110) = -1 ENOENT (No such file or directory)
Cannot connect to server socket err = No such file or directory

If I comment out private-dev in the profile - it works fine.

A similar discussion was happening in #1446.

**Comment by netblue30** [comment]
I have a fix on mainline git, you can try it out. It will autodetect Jack Audio setups, you don't need to change anything in your profiles.
