### ISSUE TITLE
Override globals.local while respecting default firefox.profile?

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1698]
If I'm not mistaken, the order of precedence is `firefox.local > globals.local > firefox.profile`. How to override rules from `globals.local` while respecting `firefox.profile`?

For example, it is possible to override `protocol unix` from `globals.local` with `ignore protocol` in `firefox.local` but then `protocol unix,inet,inet6,netlink` from `firefox.profile` is not honored.

**Comment by Vincent43** [comment]
Add `protocol unix,inet,inet6,netlink` to `firefox.local`

**Comment by rekixex** [comment]
@Vincent43 That came to my mind but I am looking for an automated solution that would cover more than one profile and many rules at once. Thanks anyways.

**Comment by Vincent43** [comment]
What do you want to achieve? Disable network access? If yes, you can try `net none` in `globals.local` then `ignore net` in `appname.local`

**Comment by chiraag-nataraj** [comment]
Let's move discussion of this (issues with `ignore`) to #2039. While this _specific_ case may be solved the way @Vincent43 points out, there are more general issues with the way we approach `ignore`.
