### ISSUE TITLE
Can't launch qBittorrent and okular with firejail aymore

### ISSUE THREAD

**Issue by Alin1agh** [netblue30/firejail#1699]
After last update, can't launch qbittorrent and okular with firejail. (Arch/kde/x64)

[user@machine]: ~>$ firejail qbittorrent
Reading profile /etc/firejail/qbittorrent.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 1892, child pid 1893
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 66.07 ms
Icon theme "gnome" not found.

[user@machine]: ~>$ firejail okular
Reading profile /etc/firejail/okular.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 1980, child pid 1981
Warning: skipping alternatives for private /etc
Warning: skipping cups for private /etc
Private /etc installed in 2.44 ms
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 58.15 ms
Icon theme "gnome" not found.
Icon theme "gnome" not found.
mprotect failed in ExecutableAllocator::makeExecutable: Permission denied
*** stack smashing detected ***: <unknown> terminated

Parent is shutting down, bye...

**Comment by smitsohu** [comment]
Could you create ~/.config/firejail/qbittorrent.profile, paste [this](https://raw.githubusercontent.com/netblue30/firejail/master/etc/qbittorrent.profile) and try it again? 
And ~/.config/firejail/okular.profile and paste [this](https://raw.githubusercontent.com/netblue30/firejail/8b6be0a1a1bde97abc367b0128515b61bb7f2b8e/etc/okular.profile) and try it again?

**Comment by NathanC** [comment]
@smitsohu I just tried appending that above command to `disable-common.inc` for Okular (I was having the same issue as @Alin1agh ), and now I get this:

```
Reading profile /etc/firejail/okular.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: noroot option is not available
Parent pid X, child pid X+1
The new log directory is /proc/X+1/root/var/log
Warning: skipping alternatives for private /etc
Warning: skipping cups for private /etc
Private /etc installed in 5.92 ms
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 41.13 ms
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-'
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.

Parent is shutting down, bye...
```

**Comment by smitsohu** [comment]
@NathanC Thanks for feedback. Assuming your shell is bash, could you

`diff <(firejail --quiet --noprofile printenv) <(firejail --quiet --noprofile --env=QML_DISABLE_DISK_CACHE=1 printenv)`

The only output should be `> QML_DISABLE_DISK_CACHE=1`.

**Comment by Alin1agh** [comment]
qBittorrent works fine, i've followed your instructions.

For okular i did this:

sudo echo "env QML_DISABLE_DISK_CACHE=1" >> /etc/firejail/disable-common.inc and try it again.
I commented env QML_DISABLE_DISK_CACHE=1 in disable-common.inc
[user@machine]: ~>$ diff <(firejail --quiet printenv) <(firejail --quiet --env=QML_DISABLE_DISK_CACHE=1 printenv)
4a5
> QML_DISABLE_DISK_CACHE=1
[user@machine]: ~>$ firejail okular
Reading profile /etc/firejail/okular.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 6118, child pid 6119
Warning: skipping alternatives for private /etc
Warning: skipping cups for private /etc
Private /etc installed in 2.52 ms
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 40.44 ms
Icon theme "gnome" not found.
Icon theme "gnome" not found.
mprotect failed in ExecutableAllocator::makeExecutable: Permission denied
*** stack smashing detected ***: <unknown> terminated

Parent is shutting down, bye...

**Comment by smitsohu** [comment]
@Alin1agh Ok, if Okular doesn't launch with `QML_DISABLE_DISK_CACHE=1` _uncommented_ in /etc/firejail/disable-common.inc, can you navigate to /etc/firejail/okular.profile?

In okular.profile comment everything and then uncomment line after line, checking after each step if Okular starts again. Usually it is a single line which causes the problem, and you will find it quickly this way.

**Comment by smitsohu** [comment]
@Alin1agh Something else you could try quickly is `firejail --ignore=noexec okular`

**Comment by Alin1agh** [comment]
@smitsohu , it works with QML_DISABLE_DISK_CACHE=1 uncommented. I was trying to follow instructions you already gave to @NathanC.
Thank you very much.
