### ISSUE TITLE
blacklist /usr/local/etc/firejail/

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#170]
Only /etc/firejail/ is blacklisted, but for those who install from git, blacklist ${prefix}/etc/firejail/, too.

**Comment by avoidr** [comment]
Also, do not blacklist files under ${prefix} in disable-secret.inc and disable-common.inc
I mean I just assume it is ${prefix}.

**Comment by netblue30** [comment]
I have a fix in for blacklist ${prefix}/etc/firejail/.

> do not blacklist files under ${prefix} in disable-secret.inc and disable-common.inc

What do you mean?

**Comment by avoidr** [comment]
/usr/local/disable-common.inc has the following lines:
```
# etc
blacklist /usr/local/etc/cron.*
blacklist /usr/local/etc/profile.d
blacklist /usr/local/etc/rc.local
blacklist /usr/local/etc/anacrontab
```
But the disable-common.inc in the repo has this:
```
# etc
blacklist /etc/cron.*
blacklist /etc/profile.d
blacklist /etc/rc.local
blacklist /etc/anacrontab
```
I don't see how the /usr/local gets there, but I'd say in the majority of cases stuff like rc.local and cron.* is in /etc and not in /usr/local/etc. So either blacklist both, or just /etc.

**Comment by netblue30** [comment]
You are right, this is a bug! I'll try to bring a fix in.

**Comment by netblue30** [comment]
Fixed, thanks.
