### ISSUE TITLE
Import profile's while ignoring others

### ISSUE THREAD

**Issue by pege16** [netblue30/firejail#1707]
With the `firejail-profiles 0.9.52-2` package a new version of `thunderbird.profile` was added to debian buster. This profile includes the include directive pointing to `firefox.profile`.
(Which I believe isn't very helpful in term's of taking stock of occurring problem's. I'd suggest that only profiles on a higher hierarchy should be included e.g. mozilla.profile)

This messes up my configuration so I like exclude this command in my `.local` profile.
Is there a way to ignore a following line with the ignore command only if a specific value is given?

For example:
> ignore command value_2
> command value_1
> command value_2

Wouldn't execute "command value_2" but "command value_1" would.

**Comment by chiraag-nataraj** [comment]
This seems to work (as per #2039), so I will close this for now. @pege16 If you have issues or if it doesn't seem to work for you, please feel free to re-open.
