### ISSUE TITLE
blacklist glob doesn't affect dotfiles

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#171]
Behaviour is shell specific, I guess, but just wanted to note that it is not obvious that when you intend to blacklist all files in a directory by using a glob, then in fact not all files are blacklisted.

Perhaps you can either put this info in the manpage, or add dotfiles whenever * is seen in the path. The first is probably better. Or maybe both are simply unrelated and it's not firejail's problem.

**Comment by netblue30** [comment]
Fixed, thanks for the bug!
