### ISSUE TITLE
Firefox: access ~/Downloads folder if using --private-home

### ISSUE THREAD

**Issue by damadmai** [netblue30/firejail#1716]
I'm using 
`firejail --private-home=.mozilla firefox %u --no-remote`
for Firefox. So that my firefox profile, history etc. is not changed but my settings are used.

How to achieve making an directory accessible outside this sandbox like ~/Downloads?
Currently this folder is empty and I it not possible to exchange files with the sandbox.
They are lost on terminating the process because the temporary filesystem is deleted.

I know about `firejail {--ls | --get | --put}` but is there a more conveniet way to share a directory?

**Comment by netblue30** [comment]
> is there a more conveniet way to share a directory?

If you are the only one using the computer, you can create a directory outside your home and configure Firefox to use it as Downloads:
`````
$ sudo mkdir /tmp-downloads
$ sudo chown username:username /tmp-downloads
`````
The only thing in Firejail blacklisting files outside the regular Unix file system hierarchy is --apparmor option.

**Comment by chiraag-nataraj** [comment]
@damadmai I actually used to use `private-home` before but found it tedious for exactly this reason. Nowadays, my regular profile does whatever it does (I have many privacy addons), but I also wrote up a little script to create a temporary firefox profile and copy over specific files/folders (see #2031 for the motivation I had for writing this script). The latest version of the script can be found at https://github.com/chiraag-nataraj/firejail-profiles (you can disable the `private-lib` stuff if you so wish, but imo it adds a bit of additional security and _should_ just work OOTB). If you decide to use the script, please open an issue in that repository if you have problems.
