### ISSUE TITLE
whitelisting subpath of blacklisted path

### ISSUE THREAD

**Issue by ormung** [netblue30/firejail#1719]
firejail 0.9.52

Using firefox with the default profile.
In /etc/firefox.local:

```
noblacklist /mnt/stuff
blacklist /mnt
```

or also:

```
noblacklist /mnt/stuff
blacklist /mnt
whitelist /mnt/stuff
```

Neither works. Am I doing something wrong or is it not possible?

**Comment by chiraag-nataraj** [comment]
You should be able to achieve what you want just by `whitelist` - that is, `whitelist /mnt/stuff` means that only that subfolder will be available. Or are you trying to do something else?

**Comment by ormung** [comment]
yes, that's what I'm trying to do. But your suggestion doesn't work either. Maybe a bug?

**Comment by chiraag-nataraj** [comment]
That's probably because there's a `disable-mnt` in the default profile, so you'll want to do a `ignore disable-mnt` in your `firefox.local`.

**Comment by ormung** [comment]
thank'you! now it works well

**Comment by chiraag-nataraj** [comment]
No problem! :slightly_smiling_face:
