### ISSUE TITLE
Can't access internet with Tor Browser

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1724]
I removed `private-etc fonts` from start-tor-browser.profile and the problem is gone.

OS: Ubuntu, Firejail 0.9.52

**Comment by Fred-Barclay** [comment]
@rekixex Can you try adding `hostname,hosts,resolv.conf` to the profile?

**Comment by rekixex** [comment]
@Fred-Barclay I added `private-etc hostname,hosts,resolv.conf` to start-tor-browser.local and the problem is solved, thank you. Can you please add it to start-tor-browser.profile?

**Comment by Fred-Barclay** [comment]
@rekixex Will do!
What Linux distro are you on? I can't replicate this on my Arch box, and I'd like to be able to (some of the lines I had you add to private-etc may be unnecessary, and I'd like to track 'em down and remove them if possible.)
Is this the tor browser bundle from https://www.torproject.org/download/download-easy.html?

**Comment by rekixex** [comment]
@Fred-Barclay Thanks.

> What Linux distro are you on?

Ubuntu 16.04.

> Is this the tor browser bundle from https://www.torproject.org/download/download-easy.html?

Yes.

**Comment by rekixex** [comment]
How important is `private-etc` option? Is it ok to use Tor Browser profile without it?

**Comment by rekixex** [comment]
How important is `private-etc` option? Is it ok to ignore it?

**Comment by Fred-Barclay** [comment]
Hmm... I can't replicate this on a Ubuntu 16.04 VM I just set up. Do you do anything peculiar with your networking?

**Comment by SpotComms** [comment]
This also appears to happen on Fedora. The private-etc line above and the one from firefox.profile both result in no connectivity. I'm not too sure what the issue is, although 826bbf14599f8bf04c4a0452d734cbc596e35a4e might be related.

**Comment by Fred-Barclay** [comment]
@SpotComms Does `private-etc hostname,hosts,resolv.conf` cause no internet connection?

**Comment by SpotComms** [comment]
@Fred-Barclay So in testing I uncovered another issue. The first issue (the one in OP) is Tor Browser not getting access to the Internet, which is fixed by your private-etc line from https://github.com/netblue30/firejail/issues/1724#issuecomment-357578263. But I was testing with the Tor Browser Launcher which was having issues verifying the HTTPS certificate of torproject.org, which is fixed by adding ssl and whatnot to private-etc.

**Comment by Fred-Barclay** [comment]
Great, thanks!
