### ISSUE TITLE
SSH fails, can't access /dev/null

### ISSUE THREAD

**Issue by gea0** [netblue30/firejail#1725]
With version 0.9.52, ssh fails:

```
$ ssh host
Couldn't open /dev/null: Permission denied
```
Which information should i provide to debug this?

**Comment by chiraag-nataraj** [comment]
Can you provide the output of `firejail --debug -- ssh user@host`? You're using the default `ssh` profile, right?

**Comment by chiraag-nataraj** [comment]
@gea0 Could you please provide the debugging output? We can't do much without that.

**Comment by chiraag-nataraj** [comment]
Going to close since there was no response and we can't help debug this without more info. @gea0 please feel free to re-open if you are able to provide more output.

**Comment by danielrocher** [comment]
I confirm this bug

```
firejail --debug -- ssh user@host 2>&1 | grep null
lrwx------ 1 user user 64 Mar 21 22:33 0 -> /dev/null
sbox run: /usr/lib/x86_64-linux-gnu/firejail/fseccomp protocol build unix,inet,inet6 /run/firejail/mnt/seccomp.protocol (null) 
Disable /dev/null (requested /home/user/.adobe)
Disable /dev/null (requested /home/user/.macromedia)
lrwx------ 1 user user 64 Mar 21 22:33 0 -> /dev/null
lrwx------ 1 user user 64 Mar 21 22:33 0 -> /dev/null
lrwx------ 1 user user 64 Mar 21 22:33 0 -> /dev/null
sbox run: /usr/lib/x86_64-linux-gnu/firejail/fseccomp print /run/firejail/mnt/seccomp.protocol (null) 
sbox run: /usr/lib/x86_64-linux-gnu/firejail/fseccomp print /run/firejail/mnt/seccomp.32 (null) 
sbox run: /usr/lib/x86_64-linux-gnu/firejail/fseccomp print /run/firejail/mnt/seccomp (null) 
```

I removed /home/user/.adobe and /home/user/.macromedia, and now it's works fine.

Thanks

**Comment by glitsj16** [comment]
@danielrocher Are you using firejail 0.9.52 too like the OP? It's likely this has been fixed in later versions. With the ssh profile in git master I see the following, which is expected behavior IMHO:

$ ssh host
ssh: Could not resolve hostname host: No address associated with hostname

**Comment by danielrocher** [comment]
Yes, I use Ubuntu 18.04 LTS 64 bits (xfce)

```
$ firejail --version
firejail version 0.9.52

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- bind support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- git install support is disabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

```
$ ssh host
ssh: Could not resolve hostname host: Name or service not known
```

**Comment by glitsj16** [comment]
@danielrocher Thanks for your response. Lots of things have changed since 0.9.52. You might want to install firejail from [this PPA](https://launchpad.net/~deki/+archive/ubuntu/firejail), maintained by @reinerh to keep up with all the security fixes/enhancements.
