### ISSUE TITLE
Frequent permission errors with firejail

### ISSUE THREAD

**Issue by trialism** [netblue30/firejail#1729]
While working with firejail I often see my apps(steam, wine stuff) to crash due to permission errors. From the outside I own the files but when I enter the sandbox with bash I can see that a lot of files and folders randomly are owned by 'root' or 'nobody'. I've never ran firejail with root or changed the owner of these containers. This is a fatal error because I can't change the owner from the inside so, I need to delete the files.
I've seen the errors happening from 0.9.44 to 0.9.52 on arch and manjaro too.

**Comment by chiraag-nataraj** [comment]
Can you give a minimum working example? When I try `firejail bash`, I get put back in my home directory with all of the files owned by me. When I try `firejail --private-home=Downloads` (as an example), I get back a new home directory with all of the files owned by me. 

What profile(s) do you see this with? Maybe there's something in common with all of them that will help us figure out what's going on.

**Comment by trialism** [comment]
This won't happen on first try! firejail does work properly for me most of the time. I'm using steam and steam+wine in firejail and this is a once-in-a-month issue. I don't know what triggers it.

**Comment by chiraag-nataraj** [comment]
Hmm, darn. And you only see this in one profile? Or is that the only profile you (regularly) use?

**Comment by trialism** [comment]
No, I've had this happen with multiple profiles(folders) with the steam and wine profiles. I usually need to delete most of the files because I can't use them anyway.

**Comment by chiraag-nataraj** [comment]
> No, I've had this happen with multiple profiles(folders) with the steam and wine profiles.

I see. To clarify, the first "profiles" ("multiple profiles") refers to _Steam_ profiles, right? (I don't really use Steam, so I have no idea how the terminology works).

> I usually need to delete most of the files because I can't use them anyway.

What do you mean? Which files? The profiles firejail installs?

**Comment by trialism** [comment]
This won't happen on first try! firejail does work properly for me most of the time. I'm using steam and steam+wine in firejail and this is a once-in-a-month issue. I don't know what triggers it.

**Comment by Fred-Barclay** [comment]
Do you ever do something like `sudo steam` or `sudo wine`? (Or `sudo firejail steam` or `sudo firejail wine`, for that matter?)

**Comment by trialism** [comment]
@chiraag-nataraj  by profile folder I mean I use steam like this: `firejail --private=~/.apps/Steam steam` and wine+steam like this: `firejail --private=~/.apps/Wine wine ".wine/dosdevices/c:/Program Files/Steam/Steam.exe"`. So the profiles are folders containing 'faked' home folders.

**Comment by chiraag-nataraj** [comment]
@trialism Ah okay, that makes more sense. Which files get weird permissions? The files in those folders? Other random files?

**Comment by trialism** [comment]
@Fred-Barclay never, I don't use sudo and I only use the root account with pacman and to edit files which require a privilege. I always run firejail with the desktop icons, unless it doesn't start then I start a new terminal for debugging.

**Comment by trialism** [comment]
@chiraag-nataraj it's random I guess. For example with this case: `.bash_history`, `.nv`, `.wine` and the parent dir `..` are owned by 'nobody' and the rest is on my user.

**Comment by chiraag-nataraj** [comment]
So the parent dir being owned by 'nobody' makes sense. But the rest does not. @netblue30, any idea why this might happen?

**Comment by chiraag-nataraj** [comment]
@trialism Is this still an issue for you?

**Comment by trialism** [comment]
@chiraag-nataraj I don't use firejail anymore.

**Comment by jcaesar** [comment]
It's still an issue for me. I can reproduce it by running `firejail --private=$HOME/.bla`, then running weechat in there, exiting weechat and the shell in the jail, and then entering the jail again.

@chiraag-nataraj Can I ask you to reopen this?

**Comment by rusty-snake** [comment]
Can reproduce with e.g ghostwriter.
$ normal shell
% shell in FJ
```
$ mkdir t
$ firejail --private=$HOME/t
% ghostwriter
% ls -l .config
drwxr-xr-x MYUSER … ghostwriter
$ ls -l .config
drwxr-xr-x MYUSER … ghostwriter
$ firejail --private=$HOME/t
% ls -l .config
dr-------- nobody  nobody  … ghostwriter
$ firejail --private=$HOME/t --noprofile
% ls -l .config
drwxr-xr-x MYUSER … ghostwriter
$ firejail --private=$HOME/t --profile=/etc/firejail/disable-programs.inc
% ls -l .config
dr-------- root  root … ghostwriter
```
@jcaesar also with `firejail --private=$HOME/.bla --noprofile`.

It looks like only files that have been blacklisted (in `disable-common.inc` or `disable-programs.inc`) are affected. To fix, use `--noblacklist` or for example weechat `firejail --private=$HOME/.bla --profile=/etc/firejail/weechat.profile`.

**Comment by jcaesar** [comment]
@rusty-snake Using the weechat profile indeed fixes the permission. (My firejail has no `--noblacklist`.) So maybe it's a different bug than the one @trialism saw.

**Comment by rusty-snake** [comment]
@jcaesar I think your FJ has `--noblacklist`, but maybe we'll just talk a little bit past it, I meant that you `--noblacklist=PATH` (where PATH are the files with permission error / See man firejail for --noblacklist).

**Comment by rusty-snake** [comment]
> So maybe it's a different bug than the one @trialism saw.

Because of the `nobody` and `root` this sound for me it sounds like blacklisting to me.
@jcaesar if it was only that :) I would close again.

**Comment by jcaesar** [comment]
>I think your FJ has --noblacklist

Ah, the error message confused me.
```
$ firejail --noblacklist
Error: invalid --noblacklist command line option
$ firejail --thisreallydoesntexist
Error: invalid --thisreallydoesntexist command line option
```

So yeah, please close.
