### ISSUE TITLE
idea: implement a pseudo variable "global" for profiles

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#173]
Somewhat related to #170.

Local user profiles (~/.conf/firejail/) may want to make global profiles more restrictive. So they would include the profiles from /etc/ and then add their own rules. But the global profiles are not always in /etc/, as in the case that firejail has been installed from git.
Have a pseudo variable for profiles in order to allow including the correct global profiles, no matter how it has been installed. Let the variable be called "global" or "globalconf" or something like that. Maybe in bash notation like this: ${globalconf}.

I hope it's clear what I mean.

**Comment by netblue30** [comment]
I can add an option that allows you to set the directory where profiles are stored, something like:
`````
$ firejail --profile-dir=/opt/profiles ...
`````
Would this help in your case?

**Comment by avoidr** [comment]
It would help, if this option was available in the profile, too.
But in this case you'd still need to know *some* path. In the case of some pseudo variable, the executable would be able to take its global config path, that's been hardcoded, since it's aware of that anyway, isn't it?

But, actually, both things can be done.
Let me show some example:
```
# ${GLOBAL} is /etc/firejail or /usr/local/etc/firejail or wherever the prefix was.
# This is immutable.
include ${GLOBAL}/generic.profile

# includes from CWD
include a.profile

profile-dir /opt/firejail
# includes from /opt/firejail
include a.profile

# absolute path, ignore profile-dir
include ~/.conf/firejail/b.profile

# at this point, ${GLOBAL} still points to whatever it was before. The hardcoded prefix.
```
This is what I'm thinking of. The idea is to be able to extend on global profiles without having to know, how firejail has been installed, so local profiles would work on every installation, without having to readjust paths.
