### ISSUE TITLE
Getting Error: "/etc/rc?.d" is an invalid filename when including disable-common.inc in the firejail profile

### ISSUE THREAD

**Issue by mYnDstrEAm** [netblue30/firejail#1732]
Since recently I'm getting the following error when running `firejail firefox-esr`:

Error: "/etc/rc?.d" is an invalid filename

I don't get this error when commenting out the following line:

include /etc/firejail/disable-common.inc

`ls -l` shows that all rc folders in /etc/ have normal filenames.

I'm running Debian 9.

Why am I getting this error? How to reenable disable-common.inc? Is this a bug of some other software? Is this the right place to ask about this?

**Comment by SpotComms** [comment]
Are you on Firejail 0.9.52? As a temporary workaround you could simply comment out the line
`sudo sed -i 's|blacklist /etc/rc?.d|#blacklist /etc/rc?.d|' /etc/firejail/disable-common.inc`

**Comment by mYnDstrEAm** [comment]
Thanks. What parts of disable-common.inc are actually needed given that no additional directories were whitelisted? disable-common.inc seems to be almost exclusively whitelistings and setting some files to be read-only: shouldn't those files be blacklisted/read-only anyway?

Please get the latest version onto the Debian repositories.

**Comment by SpotComms** [comment]
See [here](https://packages.debian.org/search?keywords=firejail) about which versions are packaged in Debian.

As for your question about disable-common, it is very useful and extremely recommended to use, even if you're using a whitelist only profile. Although from how you said it "almost exclusively whitelistings", I'm not too sure what your disable-common is doing.

**Comment by mYnDstrEAm** [comment]
Sorry, I meant to say blacklistings not whitelistings. But why is that? Shouldn't all those files be inaccessible to firefox-esr anyway as long as they aren't whitelisted explicitly in the profile? Is it about disabling the QML image cache?

**Comment by SpotComms** [comment]
@mYnDstrEAm if a file doens't explicitly whitelist anything it can access any and all files that aren't blacklisted. In the case of firefox-esr which is a whitelist profile, it actually can access some of those files (the ones not in ${HOME})
