### ISSUE TITLE
Add support for syscalls 329-332 (pkey_mprotect, pkey_alloc, pkey_free, statx)

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#1737]
These are new syscalls supported by linux kernel. See for example strace: https://sourceforge.net/p/strace/code/ci/master/tree/linux/x86_64/syscallent.h#l332
And also local `build/include/linux/syscalls.h` of your kernel of course.

Please add support for those syscalls to firejail? Thanks!

**Comment by netblue30** [comment]
all set, thanks.
