### ISSUE TITLE
Firefox 59.0b1, pulseaudio

### ISSUE THREAD

**Issue by yourcelf** [netblue30/firejail#1739]
![image](https://user-images.githubusercontent.com/21318/35122106-eab8cc04-fc5a-11e7-9cd8-102cf0b1bb9e.png)

I'm not able to get audio working in Firefox 59.0b1 (Developer Edition), with pulseaudio v8.0 and firejail v0.9.38.10-0ubuntu0.16.04.1 (both the Ubuntu 16.04.3 distro versions).  When I try playing, I get the above error in Firefox: "To play audio, you may need to install the required PulseAudio software."  Audio was working fine in previous versions of Firefox, and it works fine without firejail.  Audio also still works fine with firejail + chromium.  Seems like Firefox changed something in v59 that's breaking firejail's access to PulseAudio.

I've tried the workarounds in https://firejail.wordpress.com/support/known-problems/#pulseaudio without success.  I've been running with `enable-shm = no` in ~/.config/pulse for a while already now and it's worked in previous firefoxes; adding `enable-memfd = yes` to /etc/pulse/daemon.conf seemed to break audio for the whole system.

I tried launching with `firejail --noprofile --debug /path/to/firefox` and no luck.  When I attempt playback, these errors are printed:
```
shm_open() failed: No such file or directory
[Child 43, MediaPlayback #2] WARNING: 7fcb085f8280 Can't get cubeb context!: file /builds/worker/workspace/build/src/dom/media/AudioStream.cpp, line 358
[Child 43, MediaPlayback #2] WARNING: Decoder=7fcb1187e400 [OnMediaSinkAudioError]: file /builds/worker/workspace/build/src/dom/media/MediaDecoderStateMachine.cpp, line 3755
[Child 43, MediaPlayback #2] WARNING: Decoder=7fcb1187e400 Decode error: NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e000b) - OnMediaSinkAudioError: file /builds/worker/workspace/build/src/dom/media/MediaDecoderStateMachine.cpp, line 3453
```

**Comment by chiraag-nataraj** [comment]
Huh...those are really old versions of pulseaudio and firejail. You should try installing the latest release version of firejail (it's at 0.9.52 at this point) and, ideally, the latest version of pulseaudio.

**Comment by chiraag-nataraj** [comment]
Regardless, I'll give it a go on my Debian sid/experimental box and report back. Keep in mind that I'm using the versions of pulseaudio and firejail mentioned above.

**Comment by chiraag-nataraj** [comment]
Worked just fine for me. Here's my firefox profile - you can give it a try if you want and report back.
[firefox.txt](https://github.com/netblue30/firejail/files/1644654/firefox.txt)
I actually have `enable-shm` set to the default of `yes`. Same with `enable-memfd`.

**Comment by yourcelf** [comment]
Upgrading to firejail 0.9.52 seems to have fixed it, thanks.  Relieving that it still works with the distro's  PulseAudio 8.0 and I don't have to try upgrading that against any other dependencies the system has.

Especially for a security app like firejail, it's super nice to be able to use package manager maintained versions to get regular updates.  Ubuntu 16.04 (the current LTS) is stuck on firejail 0.9.38.10-0ubuntu0.16.04.1; I'd guess that's generally tracking but lagging on Firejail's own LTS (currently at 0.9.38.12).  Ubuntu gets a new LTS this April, but until then the mix of bleeding-edge browser with legacy firejail and pulseaudio might not be viable.  I know it'd be a lot of extra work, but a deb repository would help people like me to be able to keep things more current. :)

Thanks very much for your effort to help debug this.
