### ISSUE TITLE
skypeforlinux hangs with white non-responsive window, firejail 0.9.52

### ISSUE THREAD

**Issue by selivan** [netblue30/firejail#1740]
firejail: 0.9.52 (from Ubuntu [ppa: deki/firejail](https://launchpad.net/~deki/+archive/ubuntu/firejail))
skypeforlinux: 8.13.0.2

Skype window show loading process for a short time, then it becomes white non-responsive window. Without firejail it works fine.

Screenshot: 

![image](https://user-images.githubusercontent.com/1208989/35136171-02280448-fcf3-11e7-87b9-eea359a61a7e.png)

It is Electron-based, so I tried using chromium profile with additional whitelist for `${HOME}/.config/skypeforlinux`, but it hangs the same way. 

Is there any way I can debug this, like print what did it stumble upon? `--debug` didn't help much, neither did `--allow-debugges strace ...`

**Comment by selivan** [comment]
I poke it with a stick and found, that without `private-dev` it works.
`--allow-debuggers strace ...` shows, that is uses `/dev/aload*`:

```
[pid   115] open("/dev/aloadC5", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid   115] open("/dev/aloadC6", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid   115] open("/dev/aloadC7", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   115] open("/dev/aloadC8", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   115] open("/dev/aloadC9", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   115] open("/dev/aloadC10", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Is there any way to allow this `/dev/aload*` files for `private-dev`?

Also, you should probably disable `private-dev` in skypeforlinux profile for now.

**Comment by chiraag-nataraj** [comment]
Hmm...I don't even have `/dev/aload*` on my system...are those files created by Skype?

**Comment by selivan** [comment]
@chiraag-nataraj Hmm, I was wrong, my system doesn't have `/dev/aload*` files either. Something about ALSA, I suppose. Here are all files it uses from `/dev`: https://gist.github.com/selivan/926479e48c799cb4b7a37eb741af6c12

Everything seems allowed according to firejail manpage:

- /dev/shm/*
- /dev/urandom
- /dev/snd/*
- /dev/video0
- /dev/null
- /dev/dri
- /dev/disk/by-id

Anyway, it works without `private-dev` and doesn't work with it, I just can't find out why. Any ideas?

**Comment by chiraag-nataraj** [comment]
I'm going to download it and try it out and report back :slightly_smiling_face:

**Comment by chiraag-nataraj** [comment]
Hmm...I'm using the default profile for `skypeforlinux` with `private-dev` uncommented and it just worked for me. Although...I'm not logged in. Let me log in to see what happens.

**Comment by selivan** [comment]
@chiraag-nataraj Yep, when I was playing with chrome profile and forgot to allow `$HOME/.config/skypeforlinux`, it showed me login window. Try to log in.

**Comment by Fred-Barclay** [comment]
See also #1730

**Comment by selivan** [comment]
@Fred-Barclay Tried it with both of `/run/systemd` and `/var/run/systemd`, didn't help. Only removing `nodev` helps.

Btw, I noticed that this whte non-responsive window loads 100% of one of processor cores.

**Comment by smitsohu** [comment]
Hi @selivan, if you want you can try pasting the following into /etc/firejail/skypeforlinux.local
```
ignore private-dev
whitelist /dev/dri
whitelist /dev/full
# whitelist /dev/log
whitelist /dev/null
whitelist /dev/ptmx
whitelist /dev/pts
whitelist /dev/random
whitelist /dev/shm
whitelist /dev/snd
whitelist /dev/tty
whitelist /dev/urandom
whitelist /dev/video0
whitelist /dev/zero
```
Adjust this for your system according to the output of `firejail --quiet --private-dev --nodvd --notv ls -1 /dev`

If that works, the culprit should be /dev/shm.

**Comment by selivan** [comment]
`firejail --quiet --private-dev --nodvd --notv ls -1 /dev` :

```
dri
full
log
null
ptmx
pts
random
shm
snd
tty
urandom
video0
zero
```

`~/.config/firejail/skypeforlinux.profile`:  https://gist.github.com/selivan/cd5742035409fe0571e1507046c71506

`firejail --profile=~/.config/firejail/skypeforlinux.profile /usr/bin/skypeforlinux`

still end up with white non-responsive window after short time(login, I suppose). Moreover, if I comment out `ignore private-dev`, and leave just `whitelist *`, it still hangs, even without `private-dev` in config O_o

**Comment by smitsohu** [comment]
`whitelist /dev/disk` (together with the other whitelisting in /dev) is now the workaround for me.

**Comment by selivan** [comment]
@smitsohu nope, this still doesn't work:

```
private-dev
whitelist /dev/dri
whitelist /dev/full
whitelist /dev/null
whitelist /dev/ptmx
whitelist /dev/pts
whitelist /dev/random
whitelist /dev/shm
whitelist /dev/snd
whitelist /dev/tty
whitelist /dev/urandom
whitelist /dev/video0
whitelist /dev/zero
whitelist /dev/disk

...
```

Btw, man firejail says:

"disc, dri, null, full, zero, tty, pts, ptmx, random, snd, urandom, video, log and shm devices are available.", 

so disc should be available with private-dev.

**Comment by smitsohu** [comment]
`private-dev` and whitelisting in /dev are not compatible. Try it again without `private-dev` please.

Also I think there was a misunderstanding regarding disc. It is an alias for /dev/sr0, /dev/dvd and so on, i.e. for cd and dvd devices.

**Comment by selivan** [comment]
@smitsohu without `private-dev` it works even without any whitelisting. And with whitelisting too. But is sees real /dev, which is no good.

**Comment by selivan** [comment]
@smitsohu it would be much better to have some `private-dev-extended`, including whatever it needs there.

**Comment by smitsohu** [comment]
@selivan 

> without private-dev it works even without any whitelisting. And with whitelisting too, of course. But is sees real /dev, which is no good.

Yes, but with whitelisting only a fraction of /dev is available inside the jail.

> it would be much better to have some private-dev-extended, including whatever it needs there.

@selivan We've had this discussion before, check out #1446. But I wonder how widespread issues with /dev/disk are.

@netblue30 what do you think?

**Comment by bmeh** [comment]
I would like to note that Electron apps (Wire, for example, amongst many others) have not been working for me for a few months now. I am getting "error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory", which could be a problem caused by not having the directory containing the executable and `libnode.so` whitelisted, except it is. At least with a previous version I could just `cd` to the directory that contains `libnode.so` and it would work, but it doesn't work anymore that way either. Additionally, even in this case, the application wouldn't always show up properly, it would just start giving me such errors:

```
[154:0109/161459.161525:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.161653:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.161807:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.161940:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162080:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.162209:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162347:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.162476:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162617:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.162765:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162917:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.163052:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```
And on occasions, it would work as expected, but it's pretty rare.

Aaaaand `steam-native` is broken as well. It has been for a while.

Note: all the applications not working with firejail do work without it.

**Comment by selivan** [comment]
@bmeh you may have to create a new issue for that, this one is about boken skypeforlinux.

**Comment by chiraag-nataraj** [comment]
@selivan Is this still an issue?

**Comment by selivan** [comment]
@chiraag-nataraj Nope, with firejail `0.9.56` and skypeforlinux `8.31.0.92` I don't have this problem.

**Comment by Vincent43** [comment]
Thx for the report.
