### ISSUE TITLE
DNS over ipv6 not working

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#1742]
As of #1722 enhancement, there is now the possibility to specify an ipv6 address for dns inside the sandbox.

The ipv6 address is correctly passed to the sandbox.

`route -6 -n` 

inside the sandbox correctly shows that our ipv6 address is indeed routed to eth0

Doing a 'dig' without specifying a dns works (at least it sends packets, and for whatever reason on my configuration the real dns can't resolve what it is asked to resolve, but that is unrelated to firejail)

... but a 'curl' or the like won't even try to resolve dns. It immediately fails with 'could not resolve host'. Wireshark shows that it is not even trying to send a dns request!

So, sure, forcing request with dig works, but there must be more to make dns over ipv6 work transparently in a sandbox that just accepting an ipv6 address!

**Comment by netblue30** [comment]
Inside the sandbox, take a look at /etc/resolv.conf. The DNS IP should go into this file. There is no difference between IPv4 and IPv6 DNS, if one of the works the other one should also work.

**Comment by chiraag-nataraj** [comment]
Closing since the OP has left Github. If someone thinks we should leave this open, feel free to re-open.
