### ISSUE TITLE
Building rpm - what's going wrong?

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#1746]
I'm trying to figure out why `make rpms` always fails,  and I've hit a bit of a roadblock (granted, my lack of knowlege about rpms isn't contributing to my efforts 😁 ).
Currently building goes something like this:
```$ make rpms
./platform/rpm/mkrpm.sh firejail 0.9.53
configure: WARNING: unrecognized options: --disable-dependency-tracking
configure: WARNING: unrecognized options: --disable-dependency-tracking
1650 blocks
error: Installed (but unpackaged) file(s) found:
...
mv: cannot stat '/tmp/tmp.8utUom6DKC/SRPMS/*.rpm': No such file or directory
mv: cannot stat '/tmp/tmp.8utUom6DKC/RPMS/*/*rpm': No such file or directory
make: *** [Makefile:230: rpms] Error 1
```
The /tmp/tmp.SOMEVALUE/SRPMS and RPMS directories are being created, but no rpm is being build in them.

I've traced the errors back to e470524, at which point the faulty builds begin. This commit removed the man page `firejail-config` from the repo. Generally speaking, building rpms was successful for all earlier commits.

platform/rpm/mkrpm.sh hasn't been edited since before this point, so I believe the problem is not in the rpm portion of the build process. @netblue30 how do you build the .rpms for release on sourceforge?

Full output of build for current state is https://gitlab.com/snippets/1694579
Full output of build for the commit for which the build began failing is https://gitlab.com/snippets/1694580
Full output of the last commit with a good build is https://gitlab.com/snippets/1694581

See also #1583 

Cheers!
Fred

**Comment by netblue30** [comment]
To answer a question from an older thread, I build the official rpm packages on a CentOS 7. First I remove /etc/firejail directory (sudo rm -fr /etc/firejail), I install firejail (sudo make install-strip), then I create the rpm by running platform/rpm/old-mkrpm.sh script. The package is placed by the script in user home directory.

I couldn't get platform/rpm/mkrpm.sh running. It works on some Fedora versions, for me on CentOS it doesn't. The regular ./configure && make && sudo make install works fine on CentOS 6 and 7 and any Fedora.

**Comment by reinerh** [comment]
@Fred-Barclay the firejail-config.5.gz error should have been fixed by b66676c.
I think the other error you are seeing now is another regression that was introduced.

It sounds like it is installing some files (during "make install") that are not added to the packaging, so it aborts the build.
But I'm not an rpm expert, so I'm not really sure...

**Comment by reinerh** [comment]
In the .spec file there is indeed nothing in the %files section that matches those files...

**Comment by reinerh** [comment]
@Fred-Barclay Can you please check if 59fb1d9f improves something?

**Comment by SpotComms** [comment]
@reinerh `./configure && make rpms` works!

**Comment by reinerh** [comment]
@SpotComms thanks for testing. What errors are now still remaining? Can you please post them?

**Comment by Fred-Barclay** [comment]
@reinerh On Fedora 26 (Korora 26 specifically), `./configure --prefix=/usr && make rpms && sudo yum install firejail-0.9.53-1.x86_64.rpm` works perfectly!

**Comment by SpotComms** [comment]
@Fred-Barclay I don't think that RPM is the full thing/proper though. As `./configure && make rpms` completes much quicker than `make` (actually compiling all the programs). I wonder if it is just including the existing /usr/bin/firejail, etc. in it.

**Comment by Fred-Barclay** [comment]
> Setup snap "core" (3748) security profiles (cannot setup seccomp for snap "core": fork/exec /usr/lib/snapd/snap-seccomp: no such file or directory)

Do you mean from a previous installation of firejail? If so, that's not the case here - it's a brand-new Korora install.

**Comment by SpotComms** [comment]
Okay I think it is indeed fixed :+1: , thanks @reinerh.

@Fred-Barclay make rpms wasn't actually outputting any gcc output, so I wasn't sure if it was actually being compiled. But I just compared and `make rpms` does take a few seconds longer than `make`, implying that it is actually compiling everything.

I guess we can close this now.

**Comment by Fred-Barclay** [comment]
> make rpms wasn't actually outputting any gcc output, so I wasn't sure if it was actually being compiled

I believe that's because of the `--quiet` flag in https://github.com/netblue30/firejail/blob/master/platform/rpm/mkrpm.sh#L39. If you remove it you should see everything compiling.

Thanks @reinerh ! 🎉
