### ISSUE TITLE
Enable crontab

### ISSUE THREAD

**Issue by Gimly86** [netblue30/firejail#1747]
Hello All,

I'm using Firejail to make SSH Jail and it work very well.
But after many search, I can't enable cron with firejail.

I don't know if it's due to blacklist file or due to permissions folder.

If anyone have enable cron ?

Thank you for your help !

**Comment by netblue30** [comment]
It is coming from /etc/firejail/disable-common.inc:
`````
$ grep cron etc/*
etc/disable-common.inc:blacklist /var/spool/anacron
etc/disable-common.inc:blacklist /var/spool/cron
etc/disable-common.inc:blacklist /etc/anacrontab
etc/disable-common.inc:blacklist /etc/cron*
etc/disable-common.inc:blacklist ${PATH}/crontab
`````
This file is included by most profiles. You basically have to comment out these lines, or to add some noblacklist statements in your specific profile before this file gets included. You can also try to handle it on the command line.:

Without noblacklist
`````
$ firejail 
[...]
$ cat /etc/crontab
cat: /etc/crontab: Permission denied
`````

WIth noblacklist:
`````
$ firejail --noblacklist=/etc/cron*
[...]
$ cat /etc/crontab
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.
[...]
`````

**Comment by Gimly86** [comment]
Thank you @netblue30
