### ISSUE TITLE
google-play-music-desktop-player symlink: error while loading shared libraries: libnode.so

### ISSUE THREAD

**Issue by semente** [netblue30/firejail#1748]
google-play-music-desktop-player isn't working anymore when using the symlink to firejail as below:

```
ls -l /usr/local/bin/google-play-music-desktop-player
lrwxrwxrwx 1 root staff 17 dez 11 10:26 /usr/local/bin/google-play-music-desktop-player -> /usr/bin/firejail*
```
That cause the following error:

```
$ google-play-music-desktop-player
google-play-music-desktop-player
Reading profile /etc/firejail/google-play-music-desktop-player.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 8258, child pid 8259
Child process initialized in 70.32 ms
/usr/bin/google-play-music-desktop-player: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory

Parent is shutting down, bye...
```

However, it works if you run it using the following forms:

```
# calling it from inside the directory containing the libnode.so file
$ cd /usr/share/google-play-music-desktop-player && google-play-music-desktop-player 
```

or

```
firejail --profile=/etc/firejail/google-play-music-desktop-player.profile google-play-music-desktop-player
```

**Comment by smitsohu** [comment]
Hi @semente, can you please try `firejail --ignore=noroot google-play-music-desktop-player` and let us know if that works?

**Comment by semente** [comment]
Hi @smitsohu! It works but it also works even when I run it using only `firejail google-play-music-desktop-player`. What is not working is when I try to run it using the symlink named `/usr/local/bin/google-play-music-desktop-player` that points to `/usr/bin/firejail`. For some reason it can't load the shared library `libnode.so` that is found on `/usr/share/google-play-music-desktop-player/libnode.so`.

But if I call the symlink from inside the directory `/usr/share/google-play-music-desktop-player/` it works as expected. I guess this shared library is placed in the wrong path... is there anyway to tell Firejail what is the working directory so it can run the software from inside the right directory? Otherwise I think the best is create a wrapper script for it but other users may experience the same issue while trying this Firejail symlink mechanism.

**Comment by smitsohu** [comment]
@semente Could you please confirm the problem is still present in Firejail 0.9.54?

**Comment by semente** [comment]
I can confirm this problem is not present on Firejail 0.9.54, I'm closing the issue.

**Comment by smitsohu** [comment]
Awesome, thanks!
