### ISSUE TITLE
Thunderbird fails to execute child process (Operation not permitted)

### ISSUE THREAD

**Issue by SecT0uch** [netblue30/firejail#1749]
When I launch thunderbird I get the symbolic link warning : 
```$thunderbird
Reading profile /etc/firejail/thunderbird.profile
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 2992, child pid 2993
**Warning cannot create symbolic link /var/run**
Blacklist violations are logged to syslog
Child process initialized in 57.14 ms
```

And then, when I try to open an URL with thunderbird I got this one : 
`** (thunderbird:7): WARNING **: Could not launch default application for URI: Failed to execute child process “firefox” (Operation not permitted)**`

Is it a bug or is there a workaround for that ?

**Comment by smitsohu** [comment]
Hi @SecT0uch What is your distro? Which firejail version do you use? Does it work with `firejail --noprofile thunderbird`?

**Comment by SecT0uch** [comment]
Hi, my distro is Parrot OS (based on Debian), firejail is pre-installed.
```
$ firejail --version
firejail version 0.9.52
```
I get exactly the same error with the `--noprofile` option.

**Comment by smitsohu** [comment]
Thanks. Could you check `sudo aa-status` if an apparmor profile for thunderbird is in enforce mode?

If yes, could you run `sudo aa-disable usr.bin.thunderbird` and try it again?

**Comment by SecT0uch** [comment]
Indeed, thunderbird was in enforced mode.
And yes it works perfectly disabling the AppArmor profile.
I will try to get a clean profile and let you know.

Thanks a lot !
