### ISSUE TITLE
spectre

### ISSUE THREAD

**Issue by HotelBellaMuerte** [netblue30/firejail#1752]
does firejail need be rebuild with antispectre flags

**Comment by netblue30** [comment]
What flags do we need to add?

**Comment by SpotComms** [comment]
@netblue30 I think @bn0785ac is referencing the GCC [retpoline](https://support.google.com/faqs/answer/7625886) [patches](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=c6b72be421ded17e0c156070ba6e90aa6c335ed6) (each different links), they seem to have been merged into GCC 7.3 and add a new `-mindirect-branch={keep/thunk/thunk-inline/thunk-extern}` flag. It mitigates against Spectre variant 2.

> Add -mindirect-branch= option to convert indirect call and jump to call
and return thunks.  The default is 'keep', which keeps indirect call and
jump unmodified.  'thunk' converts indirect call and jump to call and
return thunk.  'thunk-inline' converts indirect call and jump to inlined
call and return thunk.  'thunk-extern' converts indirect call and jump to
external call and return thunk provided in a separate object file.  You
can control this behavior for a specific function by using the function
attribute indirect_branch.

**Comment by SkewedZeppelin** [comment]
Added in e3f64f751ec2caaf4c209f95eefab5bc9166db0e

**Comment by netblue30** [comment]
Thanks @SkewedZeppelin - is there anything else besides -mindirect-branch? I'll try to play with llvm compiler (clang), I'm not sure if anybody is using it.

**Comment by SkewedZeppelin** [comment]
LLVM added a `-mretpoline` option detailed here https://reviews.llvm.org/D41723

**Comment by netblue30** [comment]
Thanks, I'll put the fix in for clang also.

**Comment by chiraag-nataraj** [comment]
Closing because the main fix has already been put in.
