### ISSUE TITLE
Firefox video hangup when switched to full screen

### ISSUE THREAD

**Issue by elvetemedve** [netblue30/firejail#1753]
## The problem
When Firefox plays a video e.g. from Youtube and I swtich to full-screen view, then after a few seconds the video freezes while the audio is keep playing.

## Workaround
When I remove the `noroot` option in the **firefox.profile**, then full-screen works fine.

### Environment
Firefox version: 58
Xorg server: 1.19.6
Firejail version: 0.9.52
OS: Arch Linux with kernel 4.14.15

**Comment by pianoslum** [comment]
I have a similar problem, but for my, Firefox only shows a blank window as soon as I start it. Also, disabling noroot solves the problem.
As some other users mentioned, noroot can cause problem for the proprietary Nvidia drivers. When I start Firefox, I find the following lines in journalclt:

`Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 0: 2D KIND Violation. Coordinates: (0x300, 0x280)
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x500420=0x80000040 0x500434=0x2800300 0x500438=0x2a 0x50043c=0x10017
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 1: 2D KIND Violation. Coordinates: (0x310, 0x280)
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x508420=0x80000040 0x508434=0x2800310 0x508438=0x2a 0x50843c=0x10017
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 2: 2D KIND Violation. Coordinates: (0x320, 0x280)
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x510420=0x80000040 0x510434=0x2800320 0x510438=0x2a 0x51043c=0x10017
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 3: 2D KIND Violation. Coordinates: (0x350, 0x280)
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x518420=0x80000040 0x518434=0x2800350 0x518438=0x2a 0x51843c=0x10017
Jan 29 14:11:47 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 0013, Class 0000902d, Offset 0000010c, Data 00000001
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 0: 2D KIND Violation. Coordinates: (0x300, 0x280)
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x500420=0x80000040 0x500434=0x2800300 0x500438=0x2a 0x50043c=0x10017
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 1: 2D KIND Violation. Coordinates: (0x310, 0x280)
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x508420=0x80000040 0x508434=0x2800310 0x508438=0x2a 0x50843c=0x10017
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 2: 2D KIND Violation. Coordinates: (0x320, 0x280)
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x510420=0x80000040 0x510434=0x2800320 0x510438=0x2a 0x51043c=0x10017
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 3: 2D KIND Violation. Coordinates: (0x350, 0x280)
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x518420=0x80000040 0x518434=0x2800350 0x518438=0x2a 0x51843c=0x10017
Jan 29 14:11:48 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 0013, Class 0000902d, Offset 0000010c, Data 00000001
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 0: 2D KIND Violation. Coordinates: (0x300, 0x280)
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x500420=0x80000040 0x500434=0x2800300 0x500438=0x2a 0x50043c=0x10017
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 1: 2D KIND Violation. Coordinates: (0x310, 0x280)
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x508420=0x80000040 0x508434=0x2800310 0x508438=0x2a 0x50843c=0x10017
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 2: 2D KIND Violation. Coordinates: (0x320, 0x280)
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x510420=0x80000040 0x510434=0x2800320 0x510438=0x2a 0x51043c=0x10017
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception on GPC 3: 2D KIND Violation. Coordinates: (0x350, 0x280)
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x518420=0x80000040 0x518434=0x2800350 0x518438=0x2a 0x51843c=0x10017
Jan 29 14:11:49 pcName kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 0013, Class 0000902d, Offset 0000010c, Data 00000001`

Fixing this would be great, but maybe it's Nvidia's fault...

**Comment by elvetemedve** [comment]
I have the proprietary Nvidia driver installed as well, so it could be related.

**Comment by netblue30** [comment]
Yes, it could be related to nvidia. Probably you'll get the same problem with some 3D accelerated programs.

You can disable noroot globaly - in /etc/firejail/firejail.config add a "userns no" at the end of the file. The impact on security will be minor.

You can also disable it for each individual program by adding files in ~/.config/firejail directory. Firefox example:
`````
$ cat ~/.config/firejail/firefox.profile
ignore noroot
include /etc/firejail/firejail.profile
`````



/firefox.profile as follows:

**Comment by elvetemedve** [comment]
@netblue30 There is typo in the profile you suggested to use (_firejail.profile_). It should be like
```
cat .config/firejail/firefox.profile
ignore noroot
include /etc/firejail/firefox.profile
```
Otherwise it worked well. Thank you.

**Comment by chiraag-nataraj** [comment]
Since the problem seems to be solved, I'm closing this.
