### ISSUE TITLE
cannot start hexchat

### ISSUE THREAD

**Issue by allorder** [netblue30/firejail#1754]
Hello, I did  :
$ firecfg --fix-sound
$ sudo firecfg
& I rebooted.

Since then I cannot start hexchat.

in the terminal :
$ hexchat
Redirecting symlink to /usr/bin/hexchat
Reading profile /etc/firejail/hexchat.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 3002, child pid 3003
Blacklist violations are logged to syslog
Child process initialized
Can't locate File/Spec.pm:   /usr/share/perl5/File/Spec.pm: Permission denied at lib/HexChat.pm line 19.
BEGIN failed--compilation aborted at lib/HexChat.pm line 19.

Parent is shutting down, bye...

Distro: Debian 9.3
firejail : Version: 0.9.44.8-2

**Comment by SpotComms** [comment]
```sed -i 's/private-bin/#private-bin/' /etc/firejail/hexchat.profile```

private-bin will need to be updated with necessary perl names

**Comment by allorder** [comment]
I should run this command or I need to edit something ?

**Comment by SpotComms** [comment]
@allorder you can either run the command or manually edit `/etc/firejail/hexchat.profile` with your favorite editor and comment out `private-bin`.

**Comment by allorder** [comment]
I did it, same error. I also tried:

private-bin hexchat,perl 
private-bin hexchat,perl*

Same error

**Comment by Fred-Barclay** [comment]
@allorder  Do you have any hexchat plugins?

**Comment by allorder** [comment]
@Fred-Barclay Yes

**Comment by Fred-Barclay** [comment]
Can you list which ones? (How did you install them too? - just trying to get a similar setup here so I can debug this more easily)

**Comment by allorder** [comment]
It's one in perl and one in python.

https://files.fm/u/8k4tt73h

**Comment by allorder** [comment]
Thanks! It work ! :)
