### ISSUE TITLE
Requesting help regarding SoulseekQT profile

### ISSUE THREAD

**Issue by qutetemp** [netblue30/firejail#1759]
SoulseekQT is a closed source music piracy program I don't trust at all. Sadly it has some features no other client has at the moment like folder view and it's quite popular especially for obscure stuff. 
I don't trust it at all.

Ideally I would like to achieve a state where after it runs only the my downloads remain.On download it creates a "Soulseek Downloads" folder inside the HOME dir.
I'm thinking overlay with whitelist after getting the latest master is the best idea but I'm honestly kind of confused and I thought it's best to ask before.

Here is the profile I have so far by looking at other software.
http://ix.io/FbJ

**Comment by Vincent43** [comment]
You can use --build [option](https://github.com/netblue30/firejail/blob/master/src/man/firejail.txt#L163): `firejail --build=<app_name>.profile <app_name>` then try to use every feature you need for this app. The copy and/or adjust created profile.

**Comment by qutetemp** [comment]
I've having some trouble regarding folder creation.
For example by default when you download something it sends all the downloads to 

~/Soulseek\ Downloads/downloading/[name of the user you're downloading from]/[name of the folder you're downloading]

and then moves the fully completed downloaded folder to 

~/Soulseek\ Downloads/complete/[name of the user you're downloading from]/[name of the folder you're downloading]

I can't get downloads to show up.

Here's what I added to the profile

mkdir ~/Soulseek Downloads
noblacklist ~/Soulseek Downloads/downloading
whitelist ~/Soulseek Downloads/downloading
noblacklist ~/Soulseek Downloads/complete
whitelist ~/Soulseek Downloads/complete

I think I'm not understanding how to properly use whitelist.

**Comment by SkewedZeppelin** [comment]
Here is a completely untested profile that you can try

```
# Firejail profile for Soulseek
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/Soulseek.local
# Persistent global definitions
include /etc/firejail/globals.local

#noblacklist ${HOME}/Soulseek Downloads

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

mkdir ${HOME}/Soulseek Downloads
whitelist ${HOME}/Soulseek Downloads
include /etc/firejail/whitelist-var-common.inc

caps.drop all
ipc-namespace
netfilter
no3d
nodvd
nogroups
nonewprivs
noroot
nosound
notv
novideo
protocol unix,inet,inet6
seccomp
shell none

private-dev
private-tmp

noexec ${HOME}
noexec /tmp
```

save it to ~/.config/firejail/[program].profile

**Comment by Vincent43** [comment]
@qutetemp use only top directory, i.e:
```
noblacklist ~/Soulseek Downloads
whitelist ~/Soulseek Downloads
```

**Comment by qutetemp** [comment]
Thank you for all the help. 
Here's the final profile in case someone needs it eventually.
http://sprunge.us/icZH

**Comment by spvkgn** [comment]
@qutetemp Could you share profile on gist? sprunge.us is down with 500 Internal Server Error.
