### ISSUE TITLE
private-etc line breaks hardware acceleration in Firefox

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1767]
From firefox.profile:

private-etc iceweasel,ca-certificates,ssl,machine-id,dconf,selinux,passwd,group,hostname,hosts,localtime,nsswitch.conf,resolv.conf,xdg,gtk-2.0,gtk-3.0,X11,pango,fonts,firefox,mime.types,mailcap,asound.conf,pulse

Enabling private-etc line (disabled by default) breaks hardware acceleration. Compositing changes from OpenGL to basic. You can enable OpenGL accelerated layers for testing by setting layers.acceleration.force-enabled to true in about:config (see https://wiki.mozilla.org/Blocklisting/Blocked_Graphics_Drivers#On_X11).

OS: Ubuntu 16.04, Firejail 0.9.52

**Comment by SkewedZeppelin** [comment]
I cannot reproduce this. Are you using mesa (i915/amdgpu/radeon/nouveau)? or the proprietary NVIDIA driver?

**Comment by netblue30** [comment]
There seem to be an /etc/drirc file, maybe this is the one creating the problem. They talk about it here: https://dri.freedesktop.org/wiki/ConfigurationInfrastructure/

Add it to private-etc and give it a try, thanks.

**Comment by rekixex** [comment]
@netblue30 I added drirc to private-etc but it didn't solve the problem. The troubleshooting page shows this: `Unable to load libGL.so.1` The Tor Browser has the same problem when private-etc line is enabled in start-tor-browser.profile

**Comment by smitsohu** [comment]
@rekixex If you append `ld.so.cache` to private-etc, does it work again?

**Comment by rekixex** [comment]
@smitsohu ld.so.cache solved the problem, thanks. 'Unable to load libGL.so.1' was shown even with hardware acceleration disabled. Would you change private-etc line to include `ld.so.cache`?

**Comment by rekixex** [comment]
@smitsohu Can you make the same change for tor browser profiles?

**Comment by SkewedZeppelin** [comment]
@rekixex added

**Comment by rekixex** [comment]
@SkewedZeppelin 'Unable to load libGL.so.1' was shown even with hardware acceleration disabled. I don't see your change in https://github.com/netblue30/firejail/blob/master/etc/start-tor-browser.profile Also, private-bin and private-etc are missing parameters present in https://github.com/netblue30/firejail/blob/master/etc/torbrowser-launcher.profile ?

**Comment by SkewedZeppelin** [comment]
@rekixex see 63d455fbe6cfde2f97137f51b779d44f22cb4675

**Comment by smitsohu** [comment]
@rekixex Thanks for reporting!
