### ISSUE TITLE
Spotify on Gentoo fails to open

### ISSUE THREAD

**Issue by brakenow** [netblue30/firejail#1768]
Works fine without Firejail.

Reading profile /etc/firejail/spotify.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 11875, child pid 11879
Child process initialized in 38.49 ms
/opt/spotify/spotify-client/spotify: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

**Comment by SkewedZeppelin** [comment]
Does commenting out `private-opt` in `/etc/firejail/spotify.profile` fix it? If not can you comment out the other options and see if any of them fix it?

**Comment by brakenow** [comment]
Thanks, but there is no 'private-opt' in the profile. Could try commenting out on random yes.

**Comment by brakenow** [comment]
Got it to work by commenting out 'private-etc fonts,machine-id,pulse,resolv.conf'.

**Comment by smitsohu** [comment]
@brakenow Could you please try if adding `ld.so.cache` to the private-etc line fixes your issue?

**Comment by okcomputerik** [comment]
I had a similar issue on Korora 26, but only when running Spotify with the --private option (in normal mode, i.e. firejail spotify, it would run fine). I commented out "private-etc fonts,machine-id,pulse,resolv.conf" as suggested by brakenow and "firejail --private spotify" worked again.

@smitsohu adding ld.so.cache to private-etc didn't help in my case. Just so you know.... Do let me know if you would like me to try out other stuff...

Thanks!

**Comment by smitsohu** [comment]
@okcomputerik to find out which directories are accessed below /etc, just run `firejail --build spotify`, play some time with it and then exit spotify again (firejail version 0.9.52 or more recent).

It will provide a good starting point for looking further.

**Comment by brakenow** [comment]
Thank you smitsohu!

'private-etc fonts,machine-id,pulse,resolv.conf,ld.so.cache' works. :-D
