### ISSUE TITLE
How to globally block networking, camera, microphone, etc. and allow by exception?

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#1769]
What is the simplest way to do it? I would prefer an automated solution.

**Comment by SkewedZeppelin** [comment]
Add the following lines to /etc/firejail/globals.local

```
net none
nosound
novideo
```

then in all the profiles you don't want it you can either comment out `include /etc/firejail/globals.local` in `/etc/firejail/[program].profile`
or
individually using `ignore [option]` eg. `ignore novideo` in `/etc/firejail/[program].local`.

**Comment by rekixex** [comment]
The problem with `net none` is frequent breakage, would `protocol unix` be better as general option? But `ignore protocol` in `[program].local` also overrides `protocol [options]` from `[program].profile`. For example, `ignore protocol` in `firefox.local` overrides `protocol unix,inet,inet6,netlink` in `firefox.profile`.

Is it possible to override rules from `globals.local` while respecting `firefox.profile` (see #1698 )?

**Comment by rekixex** [comment]
@SkewedZeppelin The problem with `net none` is frequent breakage, would `protocol unix` be better as general option? But `ignore protocol` in `[program].local` also overrides `protocol [options]` from `[program].profile`. For example, `ignore protocol` in `firefox.local` overrides `protocol unix,inet,inet6,netlink` in `firefox.profile`.

Is it possible to override rules from `globals.local` while respecting `firefox.profile` (see #1698 )?

**Comment by SkewedZeppelin** [comment]
I guess I overlooked that part, I do no think there is currently a way to achieve that then.

**Comment by rekixex** [comment]
@SkewedZeppelin Can you somehow add an option to honor `[program].profile` in case of conflicts with `globals.local`?

**Comment by rekixex** [comment]
@SkewedZeppelin Thanks. It would be useful for restrictive environments to have an option to make exceptions for specific applications. Maybe inside `globals.local`, for example like `protocol ignore firefox.profile`.

**Comment by chiraag-nataraj** [comment]
I wonder if it would be easier to basically allow mixing whitelist and blacklist in the same directive (as `systemd` does) - for example, if this were implemented, you could just do `protocol unix,~tcp` (meaning whitelist `unix` and blacklist `tcp`) or something to override whatever is in `globals.local`.

**Comment by chiraag-nataraj** [comment]
@rekixex The solution I came up with worked when I was designing my own profiles, and I guess it might be useful for you as well. I split up the specific predicates I might need to undo later into different files. In my case, I wanted to be able to independently use `noexec` on `~` and `/tmp`. But yeah, right now it's tedious. I think we should move discussion of this to #2039.
