### ISSUE TITLE
qbittorrent: no authentication protocol supported

### ISSUE THREAD

**Issue by bryce-lynch** [netblue30/firejail#1772]
If I try to start qbittorrent when firejail is active (integrated via firecfg) it hangs with the message "Qt: Session management error: None of the authentication protocols specified are supported". If I start it directly from /usr/bin or disabling firejail it works.

Btw, I'd also like to ask: is it possible to stop firejail's debug messages? (I checked /etc/firejail/firejail.config and everything is commented out, no --debug* options specified.) A simple "leafpad" floods the console with 18 lines: Reading profile, Parent pid, child pid, C library installed, process initialized, etc.

**Comment by geo-v** [comment]
1) Disable `memory-deny-write-execute` in qbittorrent.profile

**Comment by bryce-lynch** [comment]
It works now, thank you.

**Comment by bryce-lynch** [comment]
Thanks @smitsohu !
