### ISSUE TITLE
rewrite browser profiles with redirections

### ISSUE THREAD

**Issue by smitsohu** [netblue30/firejail#1773]
We are shipping Firejail with a large number of browser profiles. Many of these browsers are just forks off Firefox and Chromium, with only minor deviations from the original codebase.

In order to ease maintenance, I would like to propose rewriting these profiles with redirections to something like firefox-common.inc and chromium-common.inc. The browser profiles themselves could keep their specific paths (and `private-bin` if necessary).

Should projects begin to deviate more strongly (like Moon browser does already), it is still always possible to switch to a dedicated profile.

**Comment by SkewedZeppelin** [comment]
Here are all the browsers we have profiles for. If I missed any just edit it in.

# Chromium Based
- bnox
- brave
- chromium (chromium-browser)
- dnox
- flashpeak-slimjet
- google-chrome (google-chrome-stable)
- google-chrome-beta
- google-chrome-unstable
- inox
- iridium (iridium-browser)
- opera
- opera-beta
- vivaldi (vivaldi-beta, vivaldi-stable)
- yandex-browser

# Gecko Based
- abrowser
- cliqz
- cyberfox (Cyberfox)
- firefox (firefox-developer-edition, firefox-esr, firefox-nightly, iceweasel)
- icecat
- palemoon
- torbrowser-launcher
- waterfox

# WekKit2Gtk
- epiphany
- surf
- uzbl

# QtWebEngine (cef?)
- qupzilla
- qutebrowser

# Text Based
- elinks
- lynx

# Unknown
- dillo
- netsurf

**Comment by SkewedZeppelin** [comment]
Of note there are 4 email clients that all include firefox.profile for whatever reason:
fossamail, geary, icedove, and thunderbird

**Comment by SkewedZeppelin** [comment]
Here I gave it a go and unified all of the Chromium-based profiles (except brave)

https://github.com/SkewedZeppelin/firejail/commit/0160a93ee20135930de968679811cb2e3e89481c

the Firefox ones might be more tedious, we should also evaluate whether or not we want to keep all of the paths that we currently do in Firefox

**Comment by Fred-Barclay** [comment]
On the note about the email clients, I for one think we ought to not include firefox in their profiles. We already have to do some workarounds (like `ignore private-tmp` and commenting out `machine-id` in the thunderbird profile, all because we also include firefox's profile.)

I'll take a look at the firefox profiles and see if I can get something similar to @SkewedZeppelin

**Comment by SkewedZeppelin** [comment]
@Fred-Barclay I hope you didn't start yet, because I just finished.

Here are all Chromium and Firefox based browsers profiles unified https://github.com/SkewedZeppelin/firejail/commit/06fb454d6c134a7de073353a64db6b8be41425cd

I left out torbrowser for the increased security. We should also consider removing many of the paths in firefox-common.profile

**Comment by Fred-Barclay** [comment]
@SkewedZeppelin no worries. 😁 Thanks!

Would removing all of the paths besides 
```
${HOME}/.cache/mozilla/firefox
${HOME}/.mozilla
${HOME}/.pki
whitelist ${DOWNLOADS}
```
be too far?

**Comment by SkewedZeppelin** [comment]
So these? That'd be great, but I wonder how many people use addons/plugins that depend on them.

```
${HOME}/.cache/gnome-mplayer/plugin
${HOME}/.config/gnome-mplayer
${HOME}/.config/okularpartrc
${HOME}/.config/okularrc
${HOME}/.config/pipelight-silverlight5.1
${HOME}/.config/pipelight-widevine
${HOME}/.config/qpdfview
${HOME}/dwhelper
${HOME}/.kde4/share/apps/kget
${HOME}/.kde4/share/apps/okular
${HOME}/.kde4/share/config/kgetrc
${HOME}/.kde4/share/config/okularpartrc
${HOME}/.kde4/share/config/okularrc
${HOME}/.kde/share/apps/kget
${HOME}/.kde/share/apps/okular
${HOME}/.kde/share/config/kgetrc
${HOME}/.kde/share/config/okularpartrc
${HOME}/.kde/share/config/okularrc
${HOME}/.keysnail.js
${HOME}/.lastpass
${HOME}/.local/share/gnome-shell/extensions
${HOME}/.local/share/okular
${HOME}/.local/share/qpdfview
${HOME}/.pentadactyl
${HOME}/.pentadactylrc
${HOME}/.vimperator
${HOME}/.vimperatorrc
${HOME}/.wine-pipelight
${HOME}/.wine-pipelight64
${HOME}/.zotero
```

**Comment by Fred-Barclay** [comment]
> Like `include /etc/firejail/firefox-common-addons.inc`

Let's do it!

**Comment by smitsohu** [comment]
@Fred-Barclay Ahh, sorry, I had not seen your edit when I posted to the PR.

> The chrome profiles don't have 'em and I don't think we've had any real issues despite them not being there.

Maybe external pdf readers were more popular in Firefox because the built-in reader used to be worse than Chromium's :smile:

But in general I agree, you have a point there.
