### ISSUE TITLE
Unable to whitelist /dev/stdin unless there's a pseudo-terminal

### ISSUE THREAD

**Issue by maz** [netblue30/firejail#1778]
`/dev/stdin` won't appear in `/dev`, even if whitelisted, unless there's a pseudo-terminal allocated.

I'm running `Ubuntu 16.04.3 LTS` with Linux kernel `4.13.0-32-generic`

```
$ firejail --version
firejail version 0.9.52

Compile time support:
	- AppArmor support is disabled
	- AppImage support is enabled
	- bind support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- git install support is disabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

Test case:
In theory, /dev/stdin should be listed in all cases.
```
#!/bin/bash
set -e -x
firejail --noprofile --quiet --whitelist=/dev/stdin -c ls -l /dev
ssh localhost 'firejail --noprofile --quiet --whitelist=/dev/stdin -c ls -l /dev'
ssh -t localhost 'firejail --noprofile --quiet --whitelist=/dev/stdin -c ls -l /dev'
ssh localhost 'firejail --noprofile --quiet --whitelist=/dev/stdin --whitelist=/dev/pts -c ls -l /dev'
```

**Comment by netblue30** [comment]
It seems to be working from a regular xterm:
`````
$ set -e -x
$ firejail --noprofile --quiet --whitelist=/dev/stdin -c ls -l /dev
+ firejail --noprofile --quiet --whitelist=/dev/stdin -c ls -l /dev
total 0
drwx-wx--x 2 root root 60 Feb 19 08:46 pts
lrwxrwxrwx 1 root root 10 Feb 19 08:46 stdin -> /dev/pts/3
`````
We do miss them however in --private-dev, I'll add stdin, stdout and stderr.

**Comment by maz** [comment]
Try the `ssh -t localhost 'firejail --noprofile --quiet --whitelist=/dev/stdin -c ls -l /dev'` command. I found that if I executed the command, from a process that didn't have a pseudoterminal allocated (e.g. using ssh with the `-t` option), then it wouldn't work. I think the problem is that, when there's no pseudoterminal, `/dev/stdin` is a symlink to `/proc/self/fd/0`, and not to `/dev/pts/...`

**Comment by netblue30** [comment]
At least under a regular terminal it is a link to /proc/self/fd/0, so whitelist should duplicate the link, not move it under /dev/pts. It looks like a bug!

**Comment by netblue30** [comment]
I think I have a fix in (https://github.com/netblue30/firejail/commit/dda8b2dbaf85383c787b2e70982346779471a269):

`````
$ ssh -t localhost 'firejail --noprofile --quiet --whitelist=/dev/stdin -c ls -l /dev'
total 0
lrwxrwxrwx 1 root root 15 Mar  6 10:22 stdin -> /proc/self/fd/0
Connection to localhost closed.
`````

You can give it a try, thanks.
