### ISSUE TITLE
Make ~/.bashrc read only?

### ISSUE THREAD

**Issue by tehpenguin** [netblue30/firejail#1782]
I am trying to make bashrc read only to prevent attacks from the bashbunny sudo grabber script. I edited /etc/firejail/firejail.config and added "read-only ~/.bashrc" to the end of the file. I am unable to open any applications and it gives an error code at that line. What is the best way to go about making bashrc and .config read only?

**Comment by Vincent43** [comment]
`/etc/firejail/firejail.config` is used to configure firejail itself. You can only change options which are  already listed there. Don't add anything which isn't listed.

To configure specific apps you can modify `/etc/firejail/<app-name>.profile` , `/etc/firejail/<app-name>.local` or `~/.config/firejail/<app-name>.profile`. So put `read-only ~/.bashrc` into one of those locations.

Alternatively `read-only ~/.bashrc` is already covered in [/etc/disable-common.inc](https://github.com/netblue30/firejail/blob/master/etc/disable-common.inc#L192). So you can add line:
`include /etc/disable-common.inc` to your app profile

**Comment by tehpenguin** [comment]
Thank you Vincent43, this is exactly what I was looking for! A few more questions if you dont mind. Whats the difference between using /etc/firejail/<app-name>.profile , /etc/firejail/<app-name>.local or ~/.config/firejail/<app-name>.profile? Will they all work the same? Also, do I have to add that for every app or is there a way to apply disable-common.inc to everything?

**Comment by Vincent43** [comment]
`/etc/firejail/<app-name>.profile` files are officially provided by firejail package and maintained here at github. They will be overwritten at every firejail update so it isn't advised to modify them.

`/etc/firejail/<app-name>.local` are used as local **additions** on top of official firejail profiles. If you want to add/remove something to official profile which is already provided by firejail you can do it here. `.local` files don't exist by default so you have to create them first.

`~/.config/firejail/<app-name>.profile` files can bu used as **replacement** for official profiles (they will overwrite profile config with the same name in` /etc/firejail/`) or for creating new profiles for apps which doesn't exist yet in firejail.

`/etc/disable-common.inc` is already included in most firejail profiles (if it isn't it usually means it breaks app) so you don't have to add it to official profiles. For new profiles you can add `include /etc/disable-common.inc` or `read-only=~/.bashrc` line to them.

If you want to add some non-standard option to all profiles (i.e. apparmor) you can create `/etc/firejail/globals.local` and add your desired modifications there. All official firejail profiles have `include /etc/firejail/globals.local` line and they will use this modifications automatically. For new profiles add `include /etc/firejail/globals.local` line to their `.profile`.

**Comment by tehpenguin** [comment]
Oh ok that makes more sense. Thank you for your help. So i have copied /etc/firejail/default.profile to ~/.config/firejail/mate-terminal.profile and it includes /etc/disable-common.inc. However I am still able to nano ~/.bashrc. Any idea what I am doing wrong?

**Comment by SkewedZeppelin** [comment]
@tehpenguin does nano say `[ File '.bashrc' is unwritable ]`? or are you actually able to save it and see the changes outside of the sandbox?

**Comment by tehpenguin** [comment]
Changes are able to be saved. It will say it wrote 123 lines.

**Comment by tehpenguin** [comment]
Which means it is still writable, even if its contained in that sandbox

**Comment by SkewedZeppelin** [comment]
That is odd. What distro, kernel, and version of firejail are you running? Also are you a standard user or are you root?

I'm not too sure what .bashrc has to do with a USB attack, but if your goal is to prevent similar USB attacks:
- Blacklist cdc_ether, rndis_host, and usbnet
- Use kernel.deny_new_usb in [linux-hardened](https://github.com/copperhead/linux-hardened) or [USBGuard](https://usbguard.github.io/)

**Comment by tehpenguin** [comment]
I am using Parrot OS, kernel 4.14, Unsure of the firejail version (not at my computer) but its no older than december 2017. This is under a normal user

**Comment by Vincent43** [comment]
Are you sure `mate-terminal `is started from firejail? How do you run `mate-terminal`? It should be: `firejail mate-terminal`. You can check with `firejail --list` (in another terminal) if it's contained. If you want to always run `mate-terminal` from firejail you can do:
`sudo ln -s /usr/bin/firejail /usr/local/bin/mate-terminal` and make sure `mate-terminal` is executed as `mate-terminal` not `/usr/bin/mate-terminal`

**Comment by SkewedZeppelin** [comment]
I've just tested this on ParrotOS Home and am still unable to reproduce it.

I know that they maintain their own patches for Firejail, but for the most part they seem to be fairly sane and don't change that much.

**Comment by idnovic** [comment]
I was thinking, if he runs "nano XYZ & disown" is it still sandboxed???
I know offtopic but parrot launches custom made scripts for most of their applicaitons.
Maybe the terminal is also custom launched.
