### ISSUE TITLE
KDEinit could not launch '/use/local/bin/kate'

### ISSUE THREAD

**Issue by idnovic** [netblue30/firejail#1784]
If I open a file from Dolphin on Plasma 5.12 (Ubuntu 17.10 + kde backports ppa)
Kate displays the file. Everything alright.

But then I close kate and I get this error in an dialog with bell noise

`KDEInit could not launch '/usr/local/bin/kate'`

I do not know what you need to figure it out, suggestions are welcome.

**Comment by idnovic** [comment]
firejail 0.9.52

**Comment by smitsohu** [comment]
Hi @idnovic! Can you please run `firejail --tree` to check if there is a firejailed kdeinit5?

Do you also run Dolphin in Firejail?

**Comment by idnovic** [comment]
`firejail --tree
1899:idnovic:/usr/bin/firejail /usr/bin/baloo_file 
  1904:idnovic:/usr/bin/firejail /usr/bin/baloo_file 
    1945:idnovic:/usr/bin/baloo_file 
8706:idnovic:/usr/bin/firejail /usr/bin/firefox 
  8708:idnovic:/usr/bin/firejail /usr/bin/firefox 
    8715:idnovic:/usr/lib/firefox/firefox 
      8768:idnovic:/usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -intPrefs XYZ...
12915:idnovic:/usr/bin/firejail /usr/bin/dolphin 
  12917:idnovic:/usr/bin/firejail /usr/bin/dolphin 
    12920:idnovic:/usr/bin/dolphin 
12954:idnovic:/usr/bin/firejail /usr/bin/kate -b /home/idnovic/Documents/fonts.conf 
  12955:idnovic:/usr/bin/firejail /usr/bin/kate -b /home/idnovic/Documents/fonts.conf 
    12958:idnovic:/usr/bin/kate -b /home/idnovic/Documents/fonts.conf 
12964:idnovic:firejail --tree 

`

**Comment by idnovic** [comment]
yes dolphin is firejailed
kdeinit5 seems not to be.

**Comment by smitsohu** [comment]
Only for confirmation: If you disable Firejail for Dolphin and Kate (run e.g. `cd /usr/local/bin && sudo rm dolphin kate`), does the issue disappear?

**Comment by idnovic** [comment]
okay, I can reproduce it now. It does not happen with the first file I open but with the 2nd.
1. dolphin > file open > kate = works no error
2. dolphin > 1st file open > kate1(works, leave open) > 2nd file open > kate2(new kate window) (opens file but when I close this window now I get the described error) > 3rd file open not possible(dolphin interaction not possible (like it does not receive inputs) as long as 2nd kate window is opened)

to answer your question, yes the error disappears. With firejail disabled I can open as many files as I want. I differenc is, that all get opened in the same kate window in tabs without firejail. But with firejail the files get opened in new kate instances.

**Comment by smitsohu** [comment]
Thanks. It seems to be some variation of an old KDE [bug](https://bugs.kde.org/show_bug.cgi?id=343673).... only this time it is caused by Firejail.

**Comment by idnovic** [comment]
let me know if you have something to test.
I can live with the error. That said, can you let kate open files in tabs instead of new windows?
I know a new window is more secure( well I think it is if it is a new process) but I did like to have to option.

**Comment by Vincent43** [comment]
You can try opening it in named profile, add `join-or-start <some-name>` to profile.

**Comment by idnovic** [comment]
can you explain it further? Add it to dolphin or kate? And in which file?

**Comment by SkewedZeppelin** [comment]
Add it to kate, then all firejailed kate processes will end up in the same sandbox instance.

**Comment by Vincent43** [comment]
You can check with `firejail --list` to see under which profile kate runs (dolphin's one or its own) then create `/etc/firejail/<kate-or-dolphin>.local` and add above line there.

**Comment by idnovic** [comment]
awesome, thank you all. It works :)
