### ISSUE TITLE
Brackets (adobe editor) can not launch

### ISSUE THREAD

**Issue by idnovic** [netblue30/firejail#1792]
This time I do not have much information.
I think first time launching brackets worked fine.

[brackets editor](http://brackets.io/)
But now I can not launch it with the sandbox enabled.

---
Warning: an existing sandbox was detected. /usr/bin/brackets will run without any additional sandboxing features
monitoring pid 16

Sandbox monitor: waitpid 16 retval 16 status 0
Sandbox monitor: monitoring 19
monitoring pid 19

Sandbox monitor: waitpid 19 retval 19 status 134
Sandbox monitor: monitoring 21
monitoring pid 21

Sandbox monitor: waitpid 21 retval 21 status 0
Sandbox monitor: monitoring 30
monitoring pid 30

Sandbox monitor: waitpid 30 retval 30 status 31

Parent is shutting down, bye...

---

VS Code works fine. Atom not tested.
Please install it yourself or tell me what to do for further debuging.

**Comment by SkewedZeppelin** [comment]
How did you install it? What is the output of `file $(which -a brackets)`? Could you also try commenting all the options and uncommenting one at a time in the profile until it breaks?

**Comment by Fred-Barclay** [comment]
I was able to duplicate on Ubuntu 17.10 - it looks like we needed to add netlink to the protocol list and no longer blacklist chroot with seccomp. Please let us know if this needs further tweaking!

Cheers!
Fred

**Comment by idnovic** [comment]
I added netlink but I dunno how to change the seccomp chroot fix you suggested

**Comment by Fred-Barclay** [comment]
Hi, sorry about that, I was referring to the code change I'd made and wasn't very clear about it. :smile: You can use https://raw.githubusercontent.com/netblue30/firejail/f7ac3a644d2612bbfc9220c119a0e00b837dec2c/etc/brackets.profile
