### ISSUE TITLE
Add falkon  browser profile  

### ISSUE THREAD

**Issue by bn0785ac** [netblue30/firejail#1794]
Falkon  its the update of qupzilla  

we can consider qupzilla as *abandonware*

**Comment by smitsohu** [comment]
Hi @bn0785ac, do you know by chance if there is a migration tool from Qupzilla to Falkon? Or in other words: Does it make sense to give Falkon access to old Qupzilla folders?

**Comment by Kishore96in** [comment]
I have been using this profile for falkon for some time, and I haven't faced any issues. 

```
# Firejail profile for falkon
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.cache/falkon
noblacklist ${HOME}/.config/falkon

noblacklist ~/.cache/fish

noblacklist ~/Documents
noblacklist ~/Pictures
noblacklist ~/Appimages
noblacklist ~/logs
noblacklist ~/Scripts/stylesheets

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

whitelist ${DOWNLOADS}
whitelist ~/.cache/falkon
whitelist ~/.config/falkon
include /etc/firejail/whitelist-common.inc

whitelist ~/.cache/fish #needed to launch fish shell's browser based config tool

#Bunch of miscellaneous directories I've whitelisted
whitelist ~/Documents
whitelist ~/Pictures
whitelist ~/Appimages
whitelist ~/logs
whitelist ~/Scripts/stylesheets

caps.drop all
netfilter
nodvd
noroot
notv
protocol unix,inet,inet6,netlink
seccomp
tracelog
nogroups
nonewprivs

private-dev
#private-tmp # Okular cannot open temporarily downloaded PDFs if this is set.
noexec ${HOME}
noexec /tmp
```
I do not see any option to directly import configs from Qupzilla, and Falkon uses a different config directory, so AFAIK, there would be no need to give falkon access to the Qupzilla config folders. However, there seems to be support to import bookmarks from Firefox, Chrome, and Opera, so perhaps the relevant directories would need to be accessible.

**Comment by Fred-Barclay** [comment]
@Kishore96in can you test the profile in 45e044c275aab65c3f9c97a479733ab1db8f4ed2 ?

**Comment by Kishore96in** [comment]
@Fred-Barclay Most of the common stuff seems to work alright on the profile in the commit you mentioned. I tested launching falkon, playing audio, opening files, and saving files. However, one issue is that the `private-tmp` option interferes with the feature to download a file to `/tmp` and open it with some program, instead of saving it to disk (i.e., the program chosen to open the given file complains it can't access the file). It should probably not be enabled in the falkon profile provided with firejail.

**Comment by smitsohu** [comment]
Thank you everyone!
