### ISSUE TITLE
allow read acces ${HOME}.cache/kioexec/krun/ for webbrowsers

### ISSUE THREAD

**Issue by idnovic** [netblue30/firejail#1795]
If ${HOME}.cache/kioexec/krun/ is not allowed you can not login in some apps that open a website for authentification.

I added
noblacklist ${HOME}.cache/kioexec/krun/
whitelist ${HOME}/.cache/kioexec/krun/
 to firefox.local as quick fix. I think read only is enough.

Apps I have seen this problem: Gitkraken, (another on I can not remember), ...

**Comment by netblue30** [comment]
Thanks for reporting it. I added "whitelist ${HOME}/.cache/kioexec/krun/" at the end of /etc/firejail/whitelist-common.inc, see https://github.com/netblue30/firejail/commit/fc2885266dad00869e888cc49ea98e84a24db66d

Can you remove the two lines you added in firefox.local and give it a try? Thanks.

**Comment by idnovic** [comment]
yes file gets opened in firefox.
Still getting an 1002 error on their site but it does not seem to be casued by firejail.

**Comment by netblue30** [comment]
Ok, I'll close it for now. If you still see problems open a new bug.
