### ISSUE TITLE
Dropbox, multiple issues

### ISSUE THREAD

**Issue by idnovic** [netblue30/firejail#1799]
Dropbox starts 2 times for me instead of 1.
Also tray menu of dropbox choose "Launch dropbox website"
Opens firefox but I get this error

File not found
Firefox can’t find the file at /tmp/XXXXXX

I need help debuging the wrongly dual start. Dropbox 2 times in tray does not make sense.

**Comment by chiraag-nataraj** [comment]
Are you using the default dropbox profile?

**Comment by idnovic** [comment]
I believe so. How do i find out?

**Comment by idnovic** [comment]
ohh, okay now I understand, I did not edit the dropbox profile but made following changes to try to fix it

$ cat /etc/firejail/dropbox.local 
join-or-start dropbox

**Comment by chiraag-nataraj** [comment]
Okay. Let me experiment and get back to you.

**Comment by idnovic** [comment]
the default profile on my side (I removed the commented lines because I dunno how to disable markdown)

$ cat /etc/firejail/dropbox.profile 
include /etc/firejail/dropbox.local

include /etc/firejail/globals.local

noblacklist ${HOME}/.config/autostart
noblacklist ${HOME}/.dropbox
noblacklist ${HOME}/.dropbox-dist

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

mkdir ${HOME}/.dropbox
mkdir ${HOME}/.dropbox-dist
mkdir ${HOME}/Dropbox
mkfile ${HOME}/.config/autostart/dropbox.desktop
whitelist ${HOME}/.config/autostart/dropbox.desktop
whitelist ${HOME}/.dropbox
whitelist ${HOME}/.dropbox-dist
whitelist ${HOME}/Dropbox
include /etc/firejail/whitelist-common.inc

caps.drop all
netfilter
no3d
nodvd
nogroups
nonewprivs
noroot
nosound
notv
novideo
protocol unix,inet,inet6
seccomp
shell none

private-dev
private-tmp

noexec /tmp

**Comment by idnovic** [comment]
I just restarted to claim more information

2922:idnovic:/usr/bin/firejail /usr/bin/baloo_file 
3400:idnovic:/usr/bin/firejail /usr/bin/dropbox start -i 
6885:root:firejail --list 

but it runs 2 times [screenshot](https://imagebin.ca/v/3tqigHNwWRJp)

[process manager](https://imagebin.ca/v/3tqjFFQYN6iI)

**Comment by idnovic** [comment]
I think I used the "binary downloader" included in the repo.
If you install dropbox from repo it downloads the newest version automatically.
The installed dropbox from repo is 2015.10.28 but it seems it is just an downlaoder like the steam installer

**Comment by chiraag-nataraj** [comment]
Hmmm, so I just ran `firejail dropbox start` and it only ran one instance.

**Comment by idnovic** [comment]
if i run the command it only opens once too.
I only have it in autostart once. I dunno how it runs 2 times.
Is it only started once after you restart your desktop/pc?

**Comment by chiraag-nataraj** [comment]
I don't use a desktop environment - I would just put the exact command above in my `~/.xinitrc` and it would (most likely) spawn only once. I don't actually use Dropbox and only downloaded it to test :joy:

**Comment by idnovic** [comment]
good idea, thank you

**Comment by idnovic** [comment]
it seems to be on my end. Even if I deactivate autostart dropbox is "responsible" enough to readd it itself...
