### ISSUE TITLE
The "less" command can't view files when run as root, using firejail.

### ISSUE THREAD

**Issue by ThePythonicCow** [netblue30/firejail#1801]
If I try to view a file, while root, using the firejailed "less" command, it either can't find the file to be viewed, or lacks permission to view it.

The firejailed "less" command works fine for me, when I am not su'd to root.

If the file to be viewed, using less as root, is some /var/log/example.log file, then the firejailed less command fails with EPERM Permission denied

If the file to be viewed, using less as root, is some file owned by an ordinary non-root user, such as /home/example_user/example.txt, then the firejailed less command fails ENOENT No such file or directory.

If I remove the /usr/local/bin/less symlink to firejail, then the "real" /usr/bin/less command runs and works fine.

I have only recently converted to Gentoo, and I have just started running firejail in this setup.

**My Gentoo version**: Gentoo Base System release 2.4.1
**My less -V version**: less 529 (PCRE regular expressions)
**The "firejail --version"**: firejail version 0.9.50

**Comment by netblue30** [comment]
Let's close #1800 and #1801and move the discussion to https://github.com/netblue30/firejail/pull/1802 until we find a fix.
