### ISSUE TITLE
Arch-Linux  -  'steam-native' doesn't read /etc/firejail/steam.profile

### ISSUE THREAD

**Issue by amarildojr** [netblue30/firejail#1807]
Hi there!

After almost a year away from Linux, I'm back. I tried running "Steam Native" and encountered a problem: it doesn't automatically read '/etc/firejail/steam.profile'.

I've been on this for hours. I commented all lines except for the "noblacklist" ones, then I changed all "noblacklist" words to "whitelist". I then added all Steam directories I have, and by the end I just left the "whitelist" lines (none of those 'private', 'tmp' or whatever).

Still, after running "_firejail steam-native_" it says "_rm: cannot remove '/home/amarildo/.steam/steam': Permission denied_". 

And running it with --debug shows:

```
Found default profile in /etc/firejail directory
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

Disable /home/amarildo/.steam
Disable /home/amarildo/.local/share/Steam
Dropping all capabilities
configuring 14 seccomp entries in /run/firejail/mnt/seccomp.protocol
```
As if it's not reading my Steam.profile at all.

EDIT: Then I tried running the default steam.profile, "**firejail --profile=/etc/firejail/steam.profile steam-native**", and it worked.

Is this something the Arch devs must change, or you can change Firejail's code so that it recognizes when "firejail steam-native" runs? Because currently if you run that command, firejail will just apply the default profile to Steam and it will fail to initialize.

Cheers

**Comment by SkewedZeppelin** [comment]
They seem to have changed their steam-native script. It used to just launch /usr/bin/steam with some extra arguments, which was firejailed if you'd ran `firecfg`.

I've added an alias in 66f8903a088ba61304ca909d61860659569b66d5. You can either `yaourt -S firejail-git` or the following
```
mkdir -p .config/firejail
cp /etc/firejail/steam.profile .config/firejail/steam-native.profile
sudo firecfg
```
