### ISSUE TITLE
Firefox can't find user profile when Firejail is restarted

### ISSUE THREAD

**Issue by H2KChicken** [netblue30/firejail#1809]
Hi, I'm wondering if this issue is specific to firejail or if this has to do with something in firefox.

I launch firefox in firejail with a private home directory, using the following command:

firefox -P

Whenever firejail is closed and re-opened, firefox has trouble finding the profile. I've ensured that "profiles.ini" matches, I've ensured that "start with this profile automatically" is unchecked, and results from google have proven ineffective in solving this problem.

As a workaround, I have a series of commands I copy and paste to port my firefox settings and addons to the new profile on each Firejail reboot, but I've been wondering if there's something else that I'm missing (or something else that keeps "changing") that would prevent firefox from finding the profile when Firejail restarts.

OS: Arch Linux
Kernel: 4.15.3-2 Arch
Firefox Version: 58.0.2 (64-bit)

**Comment by Vincent43** [comment]
Do you mean `--private-home` option? If there are other instances running you may need to add `-no-remote` poption like this: `firefox -P -no-remote`

**Comment by H2KChicken** [comment]
I use firefox in openbox, so my commands are:

`firejail --private-home=/path/to/your/profile --x11=xephyr openbox`

Then from xterm, I launch

`firefox -P`

The problem is, if I close and re-open the firejail container that is running firefox, and try to open firefox with `firefox -P` as mentioned, it says it still can't find my profile. The only solution that gets me around this is deleting the profile and re-creating it with `firefox -P`

Am I missing something?

**Comment by Vincent43** [comment]
I'm not familiar with openbox. Can you try reproduce it directly with:
`firejail --private-home=/path/to/your/profile --x11=xephyr firefox -P`

**Comment by H2KChicken** [comment]
Seems to be the same result.

The only workaround seems to be to delete and remake the directory being used for "private-home," then to launch firefox -P through firejail to receive the profile menu again.

(Then closing the profile menu, pasting my .mozilla folder, and relaunching firefox -P (to continue using my old profile)).

**Comment by Vincent43** [comment]
Hm, I can't reproduce it. I do:
`mkdir abc`
`firejail --private=abc firefox -P`
Create profile and close firefox the run it again:
`firejail --private=abc firefox -P`
It shows me profile which I previously created.

Can you try to test above? Did you add something else to firefox profile except `private-home`?

**Comment by H2KChicken** [comment]
I've tried with the above steps with the same result. It's like somethin in firefox breaks the home directory.

My private-home directory is nested in my home directory.
