### ISSUE TITLE
profile configuration - path - special character

### ISSUE THREAD

**Issue by anarchic-system** [netblue30/firejail#181]
While one can use “special” characters in a directory or file name when using `--whitelist` or `--blacklist`[1] or the *whitelist* or *blacklist* options in a profile configuration file, I did not find how to use an exclamation mark[2] character in a directory name.

I added the following line in my *iceweasel.profile*
`whitelist ~/!down`
When running 
`firejail --debug iceweasel`
I get 
`Error: "~/!down" is an invalid file name`
I also tried escaping the *!* character, quoting the path, quoting the whole line; does not work.

When trying on the command line with
`firejail --debug "--whitelist=~/!down" iceweasel`
I get
`zsh: event not found: down`
When trying on the command line with
`firejail --debug "--whitelist=~/\!down" iceweasel`
I get
`Checking filename ~/!down
Error: "~/!down" is an invalid filename`

Using a space in the file name is working[3].
Using accents in the file name is working[4].

What am I missing?

[1]- `man firejail` is providing the sample `firejail "--blacklist=/home/username/My Virtual Machines"`
[2]- U+0021 EXCLAMATION MARK / '!'
[3]- Output of `firejail --debug iceweasel`: `Removed whitelist path: whitelist ~/broap burp`
[4]- Output of `firejail --debug iceweasel`: `Removed whitelist path: whitelist ~/Ümlautißéèùça_marche`

**Comment by netblue30** [comment]
I'm trying to stay away from special chars in filenames. It is a SUID program, I have to protect it somehow.
