### ISSUE TITLE
Firefox and Chromiun not taking input and not appearning in `firejail --list`

### ISSUE THREAD

**Issue by Logmytech** [netblue30/firejail#1810]
I'm running Ubuntu 16.04 on Gnome

1) If non jailed instance of Firefox is open, then the new instance of firejailed Firefox opens just fine. However when I do a `firejail --list` it doesn't appear.

2) If all Firefox instances are closed and I run a firejailed Firefox, then the Firefox doesn't accept Keybaord input. I get IBUS errors and Firefox doesn't accept Keyboard input.

3) The same happens for Chromium

This is the output

```
$ firejail firefox
Reading profile /usr/local/etc/firejail/firefox.profile
Reading profile /usr/local/etc/firejail/firefox-common.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 6628, child pid 6629
Blacklist violations are logged to syslog
Child process initialized in 62.92 ms

(firefox:7): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused

Parent is shutting down, bye...
```

**Comment by SkewedZeppelin** [comment]
See #1579, #1302, and #1204

I don't think we've found a fix yet.

https://github.com/netblue30/firejail/issues/1204#issuecomment-334753154 might help

**Comment by smitsohu** [comment]
Regarding your other issue:

> If non jailed instance of Firefox is open, then the new instance of firejailed Firefox opens just fine. However when I do a firejail --list it doesn't appear.

If it is not in `firejail --list`, we must assume it is not sandboxed. Probably you will find the reason here: https://firejail.wordpress.com/support/frequently-asked-questions/#firefox

**Comment by Fred-Barclay** [comment]
@Logmytech Can you try `GTK_IM_MODULE=xim firejail firefox`?

**Comment by Logmytech** [comment]
I'm using Manjaro now and Firefox is working.

Stale distribution might have been the problem.

**Comment by Munom** [comment]
I have the same problem with a fresh install of Ubuntu 18.04 and the NVIDIA driver.
I have tried GTK_IM_MODULE=xim firejail firefox as suggested by @Fred-Barclay 

This solved it.  No IBUS warnings and Firefox works fine.

**Comment by chiraag-nataraj** [comment]
Since the OP has fixed their problem and the last person to comment deleted their account (so we can't really get in touch with them), I'm going to go ahead and close this.
