### ISSUE TITLE
[private-dev] xsession-errors log is chowned by root

### ISSUE THREAD

**Issue by Vincent43** [netblue30/firejail#1813]
I noticed that in some circumstances `.xsession-errors` log file is getting chowned by root while using firejail. I found that `private-dev` option is causing such issues when using with graphical apps started from file manager on KDE plasma. I didn't bisected it but https://github.com/netblue30/firejail/commit/a9c3a772b74ffdcdb5b871d0fd2b5277bdf88419 https://github.com/netblue30/firejail/commit/dda8b2dbaf85383c787b2e70982346779471a269 https://github.com/netblue30/firejail/commit/b21763636adc4edd63b7991908fffcdb84a048c6 are potential candidates for causing regression.

To reproduce with KDE:

1. Open unsandboxed dolphin `/usr/bin/dolphin`
2. Check `.xsession-errors` attributes:
```
ls -al .xsession-errors
-rw------- 1 user users 12833 Mar 13 14:21 .xsession-errors
```
3. Create or open existing file: `touch aaa.txt`
4. Open it through file manager (executing `kate aaa.txt `from terminal doesn't cause issues)
5. Check `.xsession-errors` attributes again:
```
ls -al .xsession-errors
-rw------- 1 root root 12833 Mar 13 14:25 .xsession-errors
```
I reproduced it with kate, kwrite, okular and gwenview with firejail from git.

**Comment by netblue30** [comment]
Let's mark it as a bug, we need to look into it.

**Comment by Vincent43** [comment]
@netblue30 I bisected it to https://github.com/netblue30/firejail/commit/a9c3a772b74ffdcdb5b871d0fd2b5277bdf88419

**Comment by Fred-Barclay** [comment]
Same here - Fedora 27 Cinnamon.

**Comment by netblue30** [comment]
Thanks guys, reverted back to the old version: https://github.com/netblue30/firejail/commit/ea1ba191efe33edff8e03cd3d2823fec1831847e

@Vincent43: I am thinking about bringing in apparmor by default in a larger number of applications, something like vlc and mpv profiles in this commit: https://github.com/netblue30/firejail/commit/31550dd0b3be41e77aab8f16d65eda42aa500d1c  I would say if you still have apparmor running on your box, just put it in for all applications you have it enabled.

**Comment by Vincent43** [comment]
@netblue30 sorry fot the deleay but I was busy recently. I added more apps in https://github.com/netblue30/firejail/commit/d8b4a633202a13a13c75779d1f40a99d6cc51dfb .

Generally I have apparmor enabled globally in firejail and it's working good. I think we may even add it to default profile. The things which are supposed to break with apparmor currently are apps which are depending on dbus usage and apps which are executing binaries from non-standard directory like `/home`, `/usr/share` or `/etc`.
Those cases can be handled locally through `/etc/apparmor.d/local/firejail-local config`
