### ISSUE TITLE
Not able to make file transfer work

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [netblue30/firejail#1815]
Hi,

It's me again, after your suggestion in this issue : https://github.com/netblue30/firejail/issues/1812

I noticed that I can't seem to make the filetransfer work.
`firejail --list` returns `30973:USER:firejail --private firefox -no-remote -private` and `firejail --ls=30973 /` returns `Error: invalid --ls=30973 command line option`

Same issue with `--get or --put` and no matter the path. Even if I set a name for the jail instead of using the pid.

What am I doing wrong ? I hope it's not again an obvious mistake from me...

**Comment by netblue30** [comment]
What version of firejail do you have? Run a "firejail --version". This also lists all the features enabled in the code, take a look at file transfers.

**Comment by thiswillbeyourgithub** [comment]
Ah. Indeed I had 0.9.38.10.

This explains a lot of the odd behavior I had... Thanks and sorry again for the trouble :)
