### ISSUE TITLE
Add options in profile files

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#182]
Hi!

Can you add `ip`, `defaultgw`, `interface` and `net` (for any interface) in profile files?

Thanks.

**Comment by msva** [comment]
I'd also ask to also add "name" option to profiles interpreter ;)
//thanks in advance

**Comment by netblue30** [comment]
I'll also bring in support for "name", thanks.

**Comment by netblue30** [comment]
I added support for "name".

**Comment by msva** [comment]
Nice, thanks a lot ;)

**Comment by nick75e** [comment]
Since you added `net` in 65eccf88be7efbbc19a6c7e3f9d9396697a55f1f, is there any chance you could also add the other options?

Thanks.

**Comment by netblue30** [comment]
I hope to have all networking options in the next release in a few weeks. So far I have only net and iprange.
