### ISSUE TITLE
Recalibration of D-Bus access

### ISSUE THREAD

**Issue by smitsohu** [netblue30/firejail#1822]
We have three different options that govern whether an app is allowed access to D-Bus or not....

- `apparmor`: reliably shuts down all D-Bus access in Ubuntu and its derivatives
- `net none`: denies access to the session bus in Ubuntu 16.04 (Mint!), Debian Jessie.... in general distributions that were released some time ago. Also kills connection to the accessibility bus.
- `blacklist /run/user/*/bus`: denies access to the session bus in newer distribution releases.

Now that we are adding `apparmor` to many profiles (184ecb305e81942fa9218f14a93f584fbeaff230, 38ffc3f02575ee91fe0dbf92e6b8ebc93095e667, 971c62aa569d9161190705a0012b9ad02546822c, d8b4a633202a13a13c75779d1f40a99d6cc51dfb), I thought it might be a good timepoint to take a step back and reconsider how we want to address the D-Bus issue.

In a number profiles right now only one or two or these three options are enabled, which seems to be, at first glance at least, an inconsistent state. The rigorous approach would be to go through these profiles and either enable them all or comment them all (`net none` obviously can't go to some profiles).... that's IMHO the only way to ensure a smooth and consistent user experience _everywhere_. 

But then, as many Ubuntu (and Mint) users are expected to switch to upcoming Ubuntu 18.04 LTS, the number of people who may run into problems with `net none` should decrease considerably. Also the KDE file chooser works without D-Bus since recently. And finally, given how big a security hole D-Bus is, the ability to change application settings could also be considered minor in comparison (thinking of apps like eog or gedit).

Personally I have a lot of sympathies for a stricter approach to D-Bus. The question is if we are willing to move ahead even if it will cause problems for users with older software. Also I think we should try to combine `apparmor` with `blacklist /run/user/*/bus` (and `net none` where possible) to ensure consistently working profiles.

**Comment by Vincent43** [comment]
Some thoughts:
`net none` affecting dbus is coincidental. It can't be used when application need network access.
`apparmor` isn't available in all distributions so we can't rely on it alone.

**Comment by smitsohu** [comment]
@Vincent43 
> net none affecting dbus is coincidental. It can't be used when application need network access.

That's right, I've updated my original post.

**Comment by Fred-Barclay** [comment]
@smitsohu and @Vincent43 Do you know why net none doesn't stop dbus access on newer distros?

**Comment by smitsohu** [comment]
Replying to myself @smitsohu
> The question is if we are willing to move ahead even if it will cause problems for users with older software.

Turns out this a chiffre mainly for Kubuntu 16.04.... problems with `apparmor` are basically limited to this release (file chooser in KDE apps, Chromium, VLC).

> Also I think we should try to combine apparmor with blacklist /run/user/*/bus (and net none where possible) to ensure consistently working profiles.

A compromise could be that we keep `apparmor` as it is now and **not** enable `blacklist /run/user/*/bus` and `net none` in KDE apps or Chromium or VLC profiles, so that this problem effectively is contained to Kubuntu 16.04.

(actually `blacklist /run/user/*/bus` would be a possible addition to chromium-common.profile, with `env NO_CHROME_KDE_FILE_DIALOG=1` as a workaround)

Which still leaves us with:
> And finally, given how big a security hole D-Bus is, the ability to change application settings could also be considered minor in comparison (thinking of apps like eog or gedit).

If not being able to change configuration is considered an acceptable price for D-Bus isolation, we should uncomment `blacklist /run/user/*/bus` and `net none` in a number of profiles. Indeed we seem to have entered a similar trade-off already with whitelisting, see #1793.

**Comment by smitsohu** [comment]
Maybe it is easier to discuss with a pull request, I will try to compile something.

@Fred-Barclay D-Bus and applications use a socket for communication, and the default location of this socket changed at some point.

Previously it was an abstract socket, which means it did not exist in the filesystem but only as a network resource. Nowadays the socket is bound to a file path (i.e. /run/user/$UID/bus), it does not exist as a network resource anymore (so that `net` is without effect).

I just found this discussion that apparently started it all: https://lists.freedesktop.org/archives/dbus/2014-December/016473.html

**Comment by Fred-Barclay** [comment]
@smitsohu Thanks!
I'm doing some testing with virtual machines and it looks like `apparmor` doesn't stop dbus access, at least on Mint 18.3 and earlier (Ubuntu 14.04 base) since apparmor isn't provided by default.
If so then we probably can't count on `apparmor` stopping dbus for these distros since a majority of users may not have installed apparmor on their systems.

**Comment by smitsohu** [comment]
@Fred-Barclay 
> I'm doing some testing with virtual machines and it looks like apparmor doesn't stop dbus access, at least on Mint 18.3 and earlier (Ubuntu 14.04 base) since apparmor isn't provided by default.

Then it is really only Kubuntu 16.04, other Ubuntu 16.04 flavors don't have these big problems.

I didn't yet travel back in time so far :smile:

**Comment by Fred-Barclay** [comment]
:smile: I did have a typo in that quote - Mint 18.3 is actually a Ubuntu **16.04** derivative. Oops!

**Comment by Vincent43** [comment]
Mint disables apparmor on Ubuntu kernels? Strange.

**Comment by Fred-Barclay** [comment]
@Vincent43 Clearly I need to do a bit more investigation! Apparmor is present on Mint 18.3:
```
user1@Mint183-VM ~ $ dpkg -l | grep apparmor
ii  apparmor                                    2.10.95-0ubuntu2.9                           amd64        user-space parser utility for AppArmor
ii  libapparmor-perl                            2.10.95-0ubuntu2.9                           amd64        AppArmor library Perl bindings
ii  libapparmor1:amd64                          2.10.95-0ubuntu2.9                           amd64        changehat AppArmor library

```
However, 
```
user1@Mint183-VM ~ $ firejail --apparmor
Error: invalid --apparmor command line option
```

and when compiling with `./configure --prefix=/usr --enable-apparmor`
```
checking for unistd.h... yes
checking sys/apparmor.h usability... no
checking sys/apparmor.h presence... no
checking for sys/apparmor.h... no
configure: error: Couldn't find sys/apparmor.h... please install apparmor user space library and development files
```
This is for firejail built from git. I don't know if the firejail in the repos (0.9.38) or 0.9.52 provided on sourceforge have apparmor enabled; probably @reinerh would know.

**Comment by Vincent43** [comment]
I guess you need this for building against apparmor https://packages.ubuntu.com/xenial/libapparmor-dev

**Comment by Fred-Barclay** [comment]
@Vincent43 `dpkg -l` shows installed packages only. It doesn't search the repos. :wink:

**Comment by netblue30** [comment]
Guys, just disregard apparmor for now! It is there in case Canonical decides to upstream their apparmor modifications and bring in proper support to control D-Bus into the kernel. They were supposed to do it two years ago.

@smitsohu:
> A compromise could be that we keep apparmor as it is now and not enable blacklist /run/user/*/bus and net none in KDE apps or Chromium or VLC profiles, so that this problem effectively is contained to Kubuntu 16.04.

Let's go with this proposal. If apparmor breaks, we ask the user to disable it until we find a fix. Disabling apparmor in firejail is very easy - just disable the apparmor profile in the kernel:
`````
$ sudo aa-disable /etc/apparmor.d/firejail-default
`````

The difficult part is to enable it. You would need to build firejail with apparmor support:
`````
$ ./configure --prefix=/usr --enable-apparmor
`````
There is a package you need to install (libapparmor-dev on Debian, apparmor-libapparmor on Arch). The full instructions are here: https://wiki.debian.org/AppArmor/HowToUse (Debian), https://wiki.archlinux.org/index.php/AppArmor (Arch)

**Comment by Vincent43** [comment]
@netblue30 they want to upstream it. Dbus control was supposed to land in linux 4.15 but it was blocked by Linus himself (it would break all existing profiles outside ubuntu/suse which don't handle dbus access). As a workaround they had to bring policy versioning to userspace first (which is ready and was deployed to debian). Linux 4.17 is current target to upstream more things from apparmor.

**Comment by smitsohu** [comment]
Sorry for this commit mess here!
