### ISSUE TITLE
disable-devel.inc does not blacklist python and node

### ISSUE THREAD

**Issue by punksta** [netblue30/firejail#1823]
```
firejail --profile="/etc/firejail/disable-devel.inc" node
firejail --profile="/etc/firejail/disable-devel.inc" npm
firejail --profile="/etc/firejail/disable-devel.inc" yarn
firejail --profile="/etc/firejail/disable-devel.inc" python
firejail --profile="/etc/firejail/disable-devel.inc" python3
firejail --profile="/etc/firejail/disable-devel.inc" javac
firejail --profile="/etc/firejail/disable-devel.inc" java
```

I think there is a lot languages which are missing there. Does it give any security when we have only few of them?

also: there is an option to disable `bash`?

**Comment by Fred-Barclay** [comment]
For python, we tried enabling it in d287140250544a15b07fe2e13e8cd45f398e0d1e, but disabled it in f374c79aa7d8248cc8a44d773f140966030f30a8. The issue with including it in disable-devel.inc is that lots of applications - hexchat, for instance - often need a python shell but **don't** need access to compilers like gcc, which are also blacklisted in disable-devel.inc.

Possibly we could consider a new `disable-interpreters.inc` or something like that with python, ruby, perl, node, and so on. Any thoughts @netblue30 @SkewedZeppelin ?

Anything with a private-bin filter that doesn't include bash will disable it. You could also do something like:
`--blacklist=/bin/bash --blacklist=/usr/bin/bash` but you'd need to make sure you blacklist all the paths to bash.

**Comment by SkewedZeppelin** [comment]
We should add javac, npm, and yarn to disable-devel.inc.

And a disable-interpreters.inc would be nice, with java, python, and node. We should be able to add it to most profiles.

**Comment by Fred-Barclay** [comment]
@SkewedZeppelin ruby, perl, php in disable-interpreters? Php I'm least sure about.

**Comment by punksta** [comment]
java isn't interpretable

**Comment by Fred-Barclay** [comment]
Or maybe `disable-compilers` (to replace `disable-devel`) and `disable-interpreters`. But then java is a bit of a hybrid... I'm going to give myself a headache from overthinking. :smile:

I'm thinking perl, python, ruby, php, node??? in disable-interpreters.
Gcc and all other c or c++ stuff, java, go, rust, openSSL, npm, node??? in disable-devel.

@SkewedZeppelin I'll try and submit a PR for review soon.

**Comment by Fred-Barclay** [comment]
Also is there a reason that we generally blacklist full paths to compilers and interpreters instead of using ${PATH}? We're already using ${PATH} in disable-common, and I suspect we should be using it in disable-devel/interpreters as well.

**Comment by Fred-Barclay** [comment]
@punksta We've added disable-interpreters in #1837 
Cheers!
