### ISSUE TITLE
Youtube video won't start with google-chrome if firejailed

### ISSUE THREAD

**Issue by flurrylol** [netblue30/firejail#1826]
Hi,

I can not run youtube videos under google-chrome whereas it works perfectly if I start google-chrome out of jail.

Firejail version : firejail version 0.9.38.10 
Distribution : ubuntu 16.04 LTS
Google-chrome version : Google Chrome 65.0.3325.162

**Comment by Fred-Barclay** [comment]
@flurrylol Are you using the Nvidia proprietary drivers? If so, try running `firejail --noroot google-chrome-stable` and see if that works.

Reference: see #1753 #1755.

**Comment by flurrylol** [comment]
Yes I am using my Nvidia drivers.
Launching  firejail --noroot google-chrome   or firejail --noroot google-chrome gives this output : 

ERROR:address_tracker_linux.cc(174)] Could not bind NETLINK socket: Address already in use (98)
[5:43:0322/173051.464055:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
Created new window in existing browser session.

But youtube videos indeed work ! Thank you :-)

**Comment by Fred-Barclay** [comment]
That's great! You can create a local copy of the chrome profile with `noroot` ignored so that you don't have to manually start it with `--noroot` every time.
Make .config/firejail/google-chrome-stable.profile with these lines:
```
ignore noroot
include /etc/firejail/google-chrome-stable.profile
```

Alternatively, if you have similar problems for lots of profiles, you may want to disable `noroot` globally:
`sudo sh -c "echo 'ignore noroot' >> /etc/firejail/globals.local"`

**Comment by Vincent43** [comment]
I think 0.9.38.10 doesn't support `/etc/firejail/globals.local` :grinning:

**Comment by Fred-Barclay** [comment]
@Vincent43 You're right! Thanks!

@flurrylol if you need to use the second option in my last post, you'll have to upgrade to the most recent firejail release.

**Comment by flurrylol** [comment]
Well,, to be honest, I'm a bit lazy... so I already had an alias and I just added the argument (noroot) like this : `alias fgc='nohup firejail --noroot google-chrome >/dev/null 2>&1 &`

**Comment by flurrylol** [comment]
Hi,  I was wondering about "upgrade to the most recent firejail release".
If I clone the git-repo and follow installation step of the README.md, everything works fine except that my version is still 0.9.38 (`firejail --version`).
I'm probably missing something...but what ?
