### ISSUE TITLE
Bug at thunderbird-beta

### ISSUE THREAD

**Issue by bn0785ac** [netblue30/firejail#1833]
thunderbird-beta profile doesnt whitelists itself, and i got bizarre logs

[Example](https://p.teknik.io/BknPr)
FIX
just add this to thunderbird-beta profile

`whitelist /opt/thunderbird-beta` #

**Comment by bn0785ac** [comment]
https://p.teknik.io/BknPr

**Comment by SkewedZeppelin** [comment]
Closing after merge of #1835
