### ISSUE TITLE
Keyboard input doesn't work

### ISSUE THREAD

**Issue by Tvax** [netblue30/firejail#1836]
I'm on Ubuntu 17.10

Each time I'm launching an AppImage through Firejail, the keyboard doesn't work. It works fine if I'm launching the app without using Firejails.

The Exec Command:
`Exec=firejail --env=DESKTOPINTEGRATION=appimaged --private --appimage '[..]/app.AppImage'`

**Comment by SkewedZeppelin** [comment]
See #1579, #1302, and #1204

I don't think we've found a fix yet.

**Comment by chiraag-nataraj** [comment]
Is this still an issue @Tvax?

**Comment by Tvax** [comment]
@chiraag-nataraj No it's not!
