### ISSUE TITLE
firejail prevents "w" from showing the user logged in

### ISSUE THREAD

**Issue by Kalle72** [netblue30/firejail#184]
First: Sorry for the next "bug-thing"

Second: The problem ;-)

If I do not use any firejail instance I can view if a user is logged in by "w" ($ denotes the prompt)

$ w
12:12:42 up 8 min,  1 user,  load average: 0,15, 0,20, 0,14
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
karl :0.0      12:10   ?xdm?  16.45s  0.02s /bin/sh /etc/X11/Sessions/Xfce4

or 

$w | grep :0.0 | head -n 1 | awl '{print $1}'
karl

If now a firejail instance is or was running since I logged in into X (xfce) I get
$w
12:23:13 up 19 min,  0 users,  load average: 0,00, 0,04, 0,10
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT

or
$w | grep :0.0 | head -n 1 | awl '{print $1}'
--> no output at all

The big problem for me is that I use a docking-station for which I have a script which determines if a user is logged in or not by checking "w | grep :0.0 | head -n 1 | awl '{print $1}'". Therefore I get now serious problems, because "w" does not show what it should if firejail is or was active in the actual X-session.

So first question: Is it a bug or a feature
Second question: If it is a feature, on which way (by which command) I can ask my machine if a user is logged in and who it is? (In this case would rewrite my skript)

Best regards 
Kalle

**Comment by netblue30** [comment]
Fixed! Thanks for the bug.
