### ISSUE TITLE
firejailed editor can't use sudoedit

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1845]
So in the interest of security, I decided to start sandboxing my editor (`emacs`). For day-to-day stuff, it works really well - I don't have any issues. However, I decided to try to use `sudoedit` to edit a configuration file, and the configuration file showed up blank. I suspected `firejail` was to blame, and looking at the output of `firejail --ls=<pid> /var/tmp` confirmed it - that directory was empty.

As far as I can tell, this is not configurable, which means launching an editor daemon within `firejail` will break `sudoedit`. For example, running `firejail --noprofile --env=TMPDIR=/tmp/user/1000 emacs --daemon` had the same problem - `sudoedit` would show me an empty file.

Would it be a good idea to allow whitelisting `/var/tmp`? Alternatively, is there a way to set the location of the `sudoedit` temp files?

**Comment by Vincent43** [comment]
You can use absolute path in `SUDO_EDITOR` variable, i.e. `SUDO_EDITOR=/usr/bin/emacs`. Then emacs will run unsandboxed when run within  `sudoedit` but it will be sandboxed  when you do day-to-day stuff.

**Comment by chiraag-nataraj** [comment]
Yeah, that's doable. But I'd definitely like to get this working, since the whole point of `sudoedit` is to be able to run the editor as my user, and there's no real reason this shouldn't be possible. For example, I tried using `whitelist /var/tmp` to indicate to `firejail` that it should use the real `/var/tmp` directory, but the mount of `/var/tmp` happens _before_ `firejail` checks the profile options, so `whitelist /var/tmp` basically has no effect. Shouldn't the default mounts be overrideable through the `whitelist` directive when appropriate? Or is this by design?

**Comment by chiraag-nataraj** [comment]
So I looked through `fs_var.c` and `fs.c` a bit, and it seems that you're cleanly mounting `/var/tmp` to support multiple sandboxes (at least that's what the `// update /var directory in order to support multiple sandboxes running on the same root directory` implies?). But cleanly mounting `/var/tmp` seems to be a security measure, since none of the sandboxes have any files in there (I would presume mounting `/var/lock` is much more relevant to this aim). Can we have a setting that disables this (or just honor `whitelist /var/tmp`)?
