### ISSUE TITLE
BleachBit not opening in firejail

### ISSUE THREAD

**Issue by veloute** [netblue30/firejail#1850]
BleachBit doesn't open with the default profile - commenting out memory-deny-write-execute fixed my issue.

**Comment by Fred-Barclay** [comment]
G'day @veloute, and thanks for the report! I've commented it out in 59992a06ced75eeed93b48d0a9778f147e325fcc. 

Can I get the linux distro and desktop environment you're using so we can document this? 
Thanks!
Fred

**Comment by veloute** [comment]
Thanks @Fred-Barclay.
I'm using Xfce on Arch Linux.
