### ISSUE TITLE
Allow machine-id for bibletime.profile

### ISSUE THREAD

**Issue by bryce-lynch** [netblue30/firejail#1857]
It seems machine-id must be included in the private-etc line in bibletime.profile, else the program refuses to start with the following error message (in Arch):

dbus[9]: D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; Failed to open "/etc/machine-id": No such file or directory)

**Comment by Vincent43** [comment]
Can you try if `firejail --machine-id --private-etc=machine-id bibletime` works? Thus way `machine-id` will be avalaible but spoofed.

**Comment by Vincent43** [comment]
Should be fixed with https://github.com/netblue30/firejail/commit/56f55b7b0d4bf419f3d5e25b9ab105add7ee2c9f , thanks for reporting.
