### ISSUE TITLE
conky issues

### ISSUE THREAD

**Issue by mjsurette** [netblue30/firejail#1866]
I have installed Parrot Studio 3.11 on my computer.  It uses firejail version 0.9.52.

I have some problems with my conky script and firejail.

Here is my .config/firejail/conky.profile
---
```
include /etc/firejail/conky.local

include /etc/firejail/globals.local

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

caps.drop all
ipc-namespace
netfilter
no3d
nodvd
nogroups
nonewprivs
noroot
nosound
notv
novideo
protocol unix,inet,inet6,netlink
seccomp
shell none

disable-mnt
private-bin conky,sensors,sed,awk,ip,grep,sh,wget,who,top
private-dev
private-tmp

memory-deny-write-execute
noexec ${HOME}
noexec /tmp
```
---
My conky.conf works as expected under openSUSE Tumbleweed on the same machine.
Running it under Parrot with 
`firejail --noprofile conky `
gives:
---
```
Parent pid 20870, child pid 20871
Child process initialized in 21.18 ms
Warning: an existing sandbox was detected. /usr/bin/conky will run without any additional sandboxing features
conky: desktop window (1000006) is subwindow of root window (119)
conky: window type - normal
conky: drawing to created window (0x2000002)
conky: drawing to double buffer
conky: forked to background, pid is 3

Warning: an existing sandbox was detected. /usr/bin/wget will run without any additional sandboxing features
```
---
The private-bin allows the scripts inside my conky.conf to run, however there must be some other limitations.  Here are the issues I'm having:

who |awk '{print $1}' 
will print my username in a terminal but prints nothing in my conky.conf
who -b |awk '{print $3 "  " $4}'
works in both contexts.

Other issues I'm having problems with are some of the conky built-in variables. 

top and top_mem in particular only report the processes related to conky.  I would like to expand this to all of the current user's processes.

fs_used and fs_free work properly for '/' but report the numbers di gives for '/sys/fs/cgroup' when asked for '/home'

Any guidance on how to remove these restrictions would be very much appreciated.

Mike

**Comment by Fred-Barclay** [comment]
I think Parrot OS automatically starts many programs inside firejail - i.e. running `conky` in Parrot OS is equivalent to running `firejail conky` on OpenSUSE. 
So, when you run `firejail conky` on Parrot OS, you're really running `firejail firejail conky` , thus firejail tries to sandbox another firejail instance, causing the error message about the existing sandbox.

You can check by starting `conky` and then calling `firejail --list`. If you see conky as one of the listed programs, then it's being sandboxed automatically. :smile:

**Comment by mjsurette** [comment]
Yes, Parrot OS does sandbox everything.  I haven't been able to start conky without one.  I like the idea of having everything sandboxed, but not losing functionality.
My concern is about restoring this functionality.  I really can't see how to run conky without the sandboxing it.

Mike

**Comment by smitsohu** [comment]
`who` and `top` providing only limited information inside the sandbox is by design and currently not configurable.

If you prefer to disable firejail just delete /usr/local/bin/conky, which is a symlink pointing to the firejail binary.

**Comment by mjsurette** [comment]
Yes, that does the trick. I would prefer to have it jailed, but life is full comprimises.

Thank you for the help.

Mike
