### ISSUE TITLE
Allow symlinked /opt

### ISSUE THREAD

**Issue by dehnhard** [netblue30/firejail#1871]
Firejail 0.9.52 (Debian Stretch / Backports repository)

First install of Firejail. It works well for me with the default profiles, though I run into a problem with google-chrome, which is caused by the fact that on that system `/opt` is symlinked to `/home/opt` for disk space reasons (`/` is on a fast but small SSD, while `/home` is on a larger HD). So `firejail google-chrome` results in `Error: no suitable /usr/bin/google-chrome executable found` because that path is actually a symlink itself to `/opt/google/chrome/google-chrome` (installed from official Google Debian package), which maps to `/home/opt/google/chrome/google-chrome` in this setup.

I'd like to ask for either:

- A way to tell firejail that `/home/opt` is a valid path for executables. If that's already possible I didn't find it in the documentation or the configuration files.
- Or to have firejail detect that `/opt` is a symlink and automatically allow the target path.

**Comment by Vincent43** [comment]
Try disabling [noexec ${HOME}](https://github.com/netblue30/firejail/blob/master/etc/chromium-common.profile#L34) and [apparmor](https://github.com/netblue30/firejail/blob/master/etc/chromium-common.profile#L21) if you use it.

**Comment by Vincent43** [comment]
Create `/etc/firejail/google-chrome.local` and add `allusers` line inside. You may need to tweak firejail apparmor profile if you use it.

**Comment by dehnhard** [comment]
Thanks for the suggestion, but it still reports the same. 

There seems to be something Chrome Profile specific as in `firejail --allusers bash` that chrome installation is at least executable (although it fails with some chrome sandbox error).

(apparmor is not installed)

**Comment by Vincent43** [comment]
Chrome Profile profile uses `whitelist` under `/home/<user>` which makes `--allusers` ineffective. Try firejail --noprofile --allusers --whitelist=/home/<user>/.bashrc bash to see what I mean. `/home/opt` is really unfortunate choice in that case. I'm afraid you have to choose some other dir to use it with firejail.

**Comment by Vincent43** [comment]
Generally whitelistable directories aren't fixed and are configurable but those directly under `/home`, i.e. `/home/foo`, `/home/bar` other than your user home directory are treated in special way. That's why I wrote that `/home/opt` is unfortunate choice in that case.

**Comment by Vincent43** [comment]
`firejail --ignore=apparmor /alt/foo/bar` would work out of the box.

**Comment by dehnhard** [comment]
Sounds like making those (supposedly hard-coded) directories you mentioned configurable would give much flexibility at (probably) a low cost. The defaults are arguably very sane for any standard Linux, but this would allow adaptability and also easy portability to other file structures (e.g. BSD flavors). But as stated I solved my problem without it and just leave it as an idea.

**Comment by chiraag-nataraj** [comment]
So this is basically yet another vote for being able to whitelist arbitrary directories :+1:

**Comment by chiraag-nataraj** [comment]
Let's move discussion over to #2041
