### ISSUE TITLE
CRONTABS for user

### ISSUE THREAD

**Issue by Gimly86** [netblue30/firejail#1877]
Hello All,

Firejail version :

`~# dpkg -l|grep firejail`
`ii  firejail                             0.9.52-2~bpo9+2                                                    amd64        sandbox to restrict the application environment
`

I use Firejail to made SSH jail and it work fine.
But I want to know how I can allow user to use their own CRONTAB.

I use a custom profile :
`
private-bin crontab`
`noblacklist /var/spool/cron/crontabs/
`

But, when I test the command crontab in shell, I've this error :

`:~$ crontab -e`
`crontabs/testuser/: fdopen: Permission denied`

What I have to do to allow the using of CRONTAB command, please ?

Thanks in advance :)

**Comment by netblue30** [comment]
I have here a profile that works (Debian stable):
`````
quiet
noblacklist ${PATH}/crontab
noblacklist /var/spool/cron
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-interpreters.inc
include /etc/firejail/disable-devel.inc

caps.drop all
private-dev
private-tmp
`````

private-bin and seccomp seem to kill it. At least on Debian crontab seems to be SUID group, it needs to elevate privileges.
