### ISSUE TITLE
program can't create whitelisted file

### ISSUE THREAD

**Issue by rahiel** [netblue30/firejail#188]
Firefox with [keysnail](https://github.com/mooz/keysnail/wiki) will try to create the config file (in `~/.keysnail.js`) if it does not exist. It is whitelisted in the firejail profile, but the config file is created in the temporary filesystem: I can access it from within firefox, but it is not in my real home directory. 

Firefox can access the config if it already exists before starting.

**Comment by netblue30** [comment]
It is a limitation of the current mount-bind technology I use for whitelisting. The file or the directory needs to be created by the user before whitelisting. I am not sure if this will ever get fixed.
