### ISSUE TITLE
Firejailing Darkest Dungeon loses all controls (keyboard and mouse)

### ISSUE THREAD

**Issue by kozross** [netblue30/firejail#1883]
I tried running the GOG version of Darkest Dungeon with the following command:

    firejail --net=none --noprofile ./start.sh

This runs, but inside the game, I have no control at all - no keyboard or mouse commands give any response. Additionally, the game runs considerably slower (to the point of visible audio-video desync).

My Firejail version (as per ``firejail --version``) output is:

```
[koz@Sebastian ~]$ firejail --version
firejail version 0.9.52

Compile time support:
	- AppArmor support is disabled
	- AppImage support is enabled
	- bind support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- git install support is disabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is disabled
```

I'm on Gentoo.

**Comment by Fred-Barclay** [comment]
Try without `--net=none`, like so:
`firejail --noprofile ./start.sh`

**Comment by kozross** [comment]
@Fred-Barclay That works fine.

**Comment by Vincent43** [comment]
If your goal is to disable network access you may try `firejail --protocol=unix --noprofile ./start.sh`

**Comment by kozross** [comment]
@Vincent43 That was my goal, and that works perfectly - I get no issues of any kind. Thank you!
