### ISSUE TITLE
Zathura dbus issue

### ISSUE THREAD

**Issue by InspectorMustache** [netblue30/firejail#1895]
With the default profile zathura fails to start:
```
dbus[5]: D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. 
```
This seems to be the same issue as #1857. Changing zathura.profile as in 56f55b7b0d4bf419f3d5e25b9ab105add7ee2c9f fixes the issue.

**Comment by Vincent43** [comment]
Fixed with https://github.com/netblue30/firejail/commit/3874039e57fec85fe63a4cc5aa186bcb3f032cca . Thx for reporting!
