### ISSUE TITLE
zoom: attachments/calls/preferences

### ISSUE THREAD

**Issue by drzraf** [netblue30/firejail#1896]
I found that the following isn't working in Zoom:

1. attachment: download and preview.
I tried to
`noblacklist /tmp/qtsingleapp-zoom*`
since such (socket) files are used. No success.
Neither did `whitelist ${HOME}/Documents/Zoom` made it work.

Note: using firejail, attachment content is dumped raw inside terminal

2. Call. The "meet" button does not work.

3. Preferences: simply are not saved.

4. Groups: Can't create a chat group of several people

( @WeiGuoZoom / https://github.com/zoom ?)

**Comment by SkewedZeppelin** [comment]
What version of Firejail are you using?

**Comment by drzraf** [comment]
0.9.50 on Debian Stretch

zoom.profile:
```
# Firejail profile for zoom
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/zoom.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.config/zoomus.conf

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-programs.inc

mkdir ${HOME}/.zoom
whitelist ${HOME}/.cache/zoom
whitelist ${HOME}/.zoom
whitelist ${HOME}/Downloads
whitelist ${HOME}/Documents/Zoom
noblacklist /tmp/qtsingleapp-zoom*

include /etc/firejail/whitelist-common.inc

caps.drop all
netfilter
nodvd
nonewprivs
noroot
notv
protocol unix,inet,inet6
seccomp

private-tmp

cpu 0
```

**Comment by smitsohu** [comment]
Can you try it again with `private-tmp` commented out?
Failing that, does `firejail --ignore=whitelist zoom` or `firejail --ignore=blacklist zoom` restore functionality?

**Comment by chiraag-nataraj** [comment]
Is this still an issue @drzraf?

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close for inactivity. @drzraf, please feel free to re-open if you still have this issue and can help us debug further.
