### ISSUE TITLE
Bug: waterfox can't close

### ISSUE THREAD

**Issue by HotelBellaMuerte** [netblue30/firejail#1899]
If i open a sandbox (firejail waterfox)

and i close waterfox, its   firejail parent doesnt close, i can't get rare logs at firejail

PD
firefox and firefox-beta are fine

**Comment by SkewedZeppelin** [comment]
See #725 

I've seen this happen with Steam and Firefox in the past, but haven't actually seen in it a long while.

**Comment by chiraag-nataraj** [comment]
Is this still an issue @HotelBellaMuerte?

**Comment by chiraag-nataraj** [comment]
I'll close this for inactivity. @HotelBellaMuerte, please feel free to re-open if you still have this issue.
