### ISSUE TITLE
Firefox profile 'inaccessible' after commit ac39cb31334c7951a97c4fc9b295c39924cd7427

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#190]
Hi, after the recent commit (ac39cb31334c7951a97c4fc9b295c39924cd7427) on Dec. 10 firefox throws the infamous 'Your Firefox profile cannot be loaded. It may be missing or inaccessible.' message when started within a firejail sandbox. No clue why, but if I comment out the "whitelist /tmp/.X11-unix" line added in the commit to /etc/firejail/firefox.profile, everything starts to work again as expected. This happens both on a Ubuntu (15.10) and an Archlinux box, with the latest firejail from git.

Here's some debug info on the issue:

$ cat ~/.config/firejail/firefox.profile
blacklist ${HOME}/.claws*
blacklist ${HOME}/.config/smtp-cli.auth
blacklist ${HOME}/.config/syncthing
blacklist ${HOME}/.config/transmissio*
blacklist ${HOME}/.encfs.*
blacklist ${HOME}/.local/share/geary
blacklist ${HOME}/Documents
blacklist ${HOME}/Music
blacklist ${HOME}/Pictures/lumix
blacklist ${HOME}/Sync
blacklist ${HOME}/Videos
include /etc/firejail/firefox.profile

$ firejail --private=$HOME /usr/lib/firefox/firefox
Reading profile /home/dirkos/.config/firejail/firefox.profile
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 4293, child pid 4295 [*]

parent is shutting down, bye...

[*] shows the 'Your Firefox profile cannot be loaded. It may be missing or inaccessible.' window..

Full debug output with/without the "whitelist /tmp/.X11-unix" entree:

(1) with (firefox doesn't start):
$ firejail --debug --private=$HOME /usr/lib/firefox/firefox
--> https://gist.github.com/b6900d841c5264c9ef78 [firejail_debug_01.txt]

(2) without (firefox works):
$ firejail --debug --private=$HOME /usr/lib/firefox/firefox
--> https://gist.github.com/0527666192d84498be1a [firejail_debug_02.txt]

Thanks for all your efforts!

**Comment by netblue30** [comment]
Fixed, thanks!
