### ISSUE TITLE
Using two different and separate sandboxes

### ISSUE THREAD

**Issue by amarildojr** [netblue30/firejail#191]
Hello,

I need to separate two instances of the same browser. The first instance is a regular "firejail iceweasel" that I allow to keep all changes and settings to it's profile folder, while the other firejailed Iceweasel must not reatin any changes (cookies, settings, etc) but must use the same profile as the first Iceweasel (this same profile, used by the 2nd Iceweasel, is copied to another folder).

I'm not able to do so, and I couldn't find info on how to get this working. 
I already copied my current /home/amarildo/.mozilla folder into "/home/amarildo/Others/Iceweasel" and tried opening Iceweasel with the following command (while the first sandbox is already running):

> firejail --private=/home/amarildo/Documents/Others/Iceweasel/ --debug iceweasel

However, it's like I've opened Iceweasel on the same sandbox as the first one is running on, and thus the changes on this 2nd sandbox "pass over" the first one to the first Iceweasel.

I also tried like this:

> firejail --private-home=/home/amarildo/Documents/Others/Iceweasel/ --debug iceweasel

And this:

> firejail --private-home=/home/amarildo/Documents/Others/Iceweasel/.mozilla --debug iceweasel

With no success.

How should I proceed?

Thanks!

**Comment by netblue30** [comment]
The second sandbox should run "iceweasel -no-remote":
`````
$ man iceweasel
[...]
       -no-remote
              Don't  connect  to a running Iceweasel instance. This option can
              be necessary in conjunction to several  of  the  options  above,
              that won't have any effect when an Iceweasel instance is running
              unless -no-remote is used at the same time.
[...]
`````
Without -no-remote, Firefox will keep a single instance of the browser running.

**Comment by amarildojr** [comment]
There is no "-no-remote" on my manual, BTW.

**Comment by netblue30** [comment]
I think Mozilla changed the name several times. I have it in 38.5.0.

**Comment by amarildojr** [comment]
My Iceweasel don't even have a manual, hehhehe.

>[amarildo@amarildo ~]$ man iceweasel 
>No manual entry for iceweasel

Have a nice Sunday, netblue.

**Comment by ypid** [comment]
@amarildojr seems you are running Debian. From where did you install iceweasel? The [iceweasel from Jessie](https://packages.debian.org/jessie/iceweasel) includes the man page (`dpkg -L iceweasel | grep man`) …

@netblue30 shouldn’t all that name spacing going on make it very difficult for two instances running in different sandboxes to reach each other (via IPC or whatever) so that `-no-remote` should not be needed in the first place? I tried it with:

```Shell
firejail --private="$HOME/.firejail/homes/iceweasel-55" --private-dev --shell=none --ipc-namespace --nosound --blacklist=/tmp/.X11-unix --debug -- iceweasel
## Second instance
firejail --private --private-dev --shell=none --ipc-namespace --nosound --blacklist=/tmp/.X11-unix --debug -- iceweasel
```

Edit: Seems Firefox is communicating over X (see https://github.com/netblue30/firejail/issues/57). Can someone confirm that? At least doing this:

```Shell
firejail --private --private-dev --shell=none --ipc-namespace --nosound --blacklist=/tmp/.X11-unix --debug -- xpra start :55 --start-child='iceweasel' --no-daemon --exit-with-children --socket-dir=/tmp
xpra attach :55 --socket-dir=/tmp
```

does open a new instance.

**Comment by amarildojr** [comment]
@ypid Yes. I used the Iceweasel from Parabola on Arch.

**Comment by vn971** [comment]
In case of not having firefox `man` page, use `firefox --help`.

**Comment by amarildojr** [comment]
> In case of not having firefox man page, use firefox --help.

Thanks. But I'm on Debian Jessie now, I'll probably stick with it. It does have a manpage of Iceweasel :D
Cheers
