### ISSUE TITLE
chrome flash problem 

### ISSUE THREAD

**Issue by justme55432** [netblue30/firejail#1913]
i use firejail to play safely littlebignake [ it require flash ]
when i use    firejail --noroot google-chrome-stable or firejail  google-chrome-stable

everything seems work fine until i start to play and it very leggy i also get this error in terminal :
WARNING:flash/platform/pepper/pep_module.cpp(63)] SANDBOXED

**Comment by SkewedZeppelin** [comment]
What version of firejail are you using?

**Comment by SkewedZeppelin** [comment]
@justme55432 was the issue unrelated to firejail?
