### ISSUE TITLE
--net=eth0 does not assign ipv6

### ISSUE THREAD

**Issue by the8472** [netblue30/firejail#192]
I have tried `firejail --noprofile --net=eth0 "/sbin/ip addr show"` on an ipv6-enabled network with a public prefix available via router advertisement.

Is there a way to get it to assign a new v6 address to the ethernet besides the v4 one?

**Comment by netblue30** [comment]
There is no support for configuring IPv6 in this moment. I'll add it in a future version.

**Comment by the8472** [comment]
hrrm, it looks like `--netfilter` also does not apply v6 rules. This may be  in a jail with a macvlan device where the device somehow obtains a v6 link-local address one way or another (dhcp client, auto-discovery).

In other words, security may be less tight than expected in some scenarios.

**Comment by netblue30** [comment]
Yes, ipv6 support should also include netfilter, thanks!

**Comment by netblue30** [comment]
Fixed! New options: --ip6, --netfilter6

**Comment by the8472** [comment]
thanks
