### ISSUE TITLE
Allow folder from USB device mounted in /mnt/

### ISSUE THREAD

**Issue by Philippe734** [netblue30/firejail#1925]
I’m using Firejail with Firefox in Ubuntu 18.04 LTS. I need to allow a specific folder in Firejail to set the Downloads folder in Firefox. The folder is on an USB device, mounted at /mnt/stuff/. How to set up Firejail, in order to select the folder /mnt/stuff/ in Firefox (for Downloads)? I tried to add `whitelist /mnt/stuff` in the file `/etc/firejail/whitelist-common.inc` but it’s not working, Firefox can’t access to that folder.

**Comment by Philippe734** [comment]
It's works, thanks !

**Comment by GeoffK59** [comment]
Hi, using Firejail 0.9.54 on Kubuntu 18.04 LTS, I can't access files or more to the point can't see what's in a file on my WD Passport drive attached to my Asus RT-AC86U router, file is bank and I get ark errors etc. where and what file do I edit to allow for this, thank you so much.

**Comment by SkewedZeppelin** [comment]
@GeoffK59 
if it is directly attached to your computer see https://github.com/netblue30/firejail/issues/1925#issuecomment-386812752

if it is connected to your router see #1560

**Comment by GeoffK59** [comment]
@SkewedZeppelin thank you for responding so quickly, yes it's attached to my router.
