### ISSUE TITLE
firejail --list is empty, but firemon shows firejail processes

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1927]
This is really weird, and is probably a product (in some way) of `hidepid=2`.

1. Mount `/proc` with `hidepid=2` (my exact mount options are `nosuid,nodev,noexec,hidepid=2,gid=107`)
2. Launch something through `firejail`: `firejail firefox`
3. Verify that `firejail` is in fact running: `sudo pidof firejail`
4. Verify that `firemon` will show the relevant processes: `sudo firemon`
5. `firejail --list`, `sudo firejail --list`, `firejail --tree`, and `sudo firejail --tree` all show nothing.

This seems to happen both with the current release version (0.9.52) and the current development version (0.9.53).

**Comment by SkewedZeppelin** [comment]
So `firejail --list` should output `Error: /proc is mounted hidepid, you would need to be root to run this command`.

`sudo firecfg --list` should work, but isn't?

**Comment by chiraag-nataraj** [comment]
So I expect `firejail --list` to be blank or give me an error, but I expect `sudo firejail --list` to give me the proper list. `firemon` works as expected (gives me the error as regular user and outputs the processes as root).

**Comment by chiraag-nataraj** [comment]
Currently investigating. Running `firejail --debug --list` seems to list the proper command to call (`/usr/local/bin/firemon --list`), but I'm not getting output from _that_ command.

**Comment by chiraag-nataraj** [comment]
The problem seems to be happening at the `execvp` part of `sbox_run`.

**Comment by chiraag-nataraj** [comment]
`execvp` seems to be failing silently...
Interestingly enough, `firejail` 0.9.52 gives me a netlink socket error:
```
Error: netlink socket problem
Error: failed to run /usr/bin/firemon
```
which doesn't appear in 0.9.53.

**Comment by chiraag-nataraj** [comment]
For some reason, `firemon` seems to act differently when called through `firejail`. Even if `firemon` doesn't have root permissions (which it needs with `hidepid`), it will try to enumerate everything when called through `firejail`, but not when called directly.

**Comment by Vincent43** [comment]
I guess firejail is always dropping some privileges or manipulating something as it always run as root regardless of sudo or not.  It doesn't have to be a bad thing actually.

**Comment by chiraag-nataraj** [comment]
I suspect that is what is going on, since this seems to be a PID namespace of some sort. If so, we should deprecate `firejail --list` and just use `firemon --list` (probably same with `--tree`?).

**Comment by chiraag-nataraj** [comment]
But it's also weird that this is _only_ happening with `hidepid` enabled...

**Comment by Vincent43** [comment]
Without hidepid every user has the same view of processes (unless contained with firejail).

**Comment by chiraag-nataraj** [comment]
Found it. The culprit was dropping capabilities before calling `firemon`.

**Comment by Vincent43** [comment]
I think the solution is to use firemon directly then.

**Comment by chiraag-nataraj** [comment]
Cool :+1: Maybe we should provide a warning if `hidepid` is enabled and `--list` or `--tree` is used?

**Comment by Vincent43** [comment]
It's interesting that when hidepid is enabled and user is in whitelisted group the behavior is quite the opposite:
```
$ firemon
Error: /proc is mounted hidepid, you would need to be root to run this command

$ firejail --list
1111:user::/usr/bin/firejail /usr/bin/firefox 
```

**Comment by chiraag-nataraj** [comment]
Yeah, exactly. That's why I didn't see this bug until I removed my user from the whitelisted group.

**Comment by Vincent43** [comment]
What I presented above is also incorrect as firemon should check if user is in trusted group. I guess when running through firejail, firemon thinks it's root and ignores hidepid.

So, as for now if hidepid is used and user is in trusted group they should use `firejail --list` or `sudo firemon --list` (but using `sudo` misses the point of being in trusted group), and when user isn't in trusted group they should use `sudo firemon --list`.

Adding proper checks to firemon would be valuable.
