### ISSUE TITLE
Hide firejail --list from firejail --list?

### ISSUE THREAD

**Issue by cyrinux** [netblue30/firejail#1928]
Hi,
Thanks for this great project.
Is it possible to hide firejail --list from firejail --list in upstream?
This will simplify scripting this command line.
Regards

**Comment by Vincent43** [comment]
`firejail --list` is a wrapper over `firemon --list` so you can try executing `firemon --list` directly.

**Comment by startx2017** [comment]
Actually it is a bug, got broken some time ago. Small fix in mainline: https://github.com/netblue30/firejail/commit/2a0fb5c1edc4455ec7e4a0396b54433aac59d98e
