### ISSUE TITLE
FJ + Thunderbird + GPG + Keycard

### ISSUE THREAD

**Issue by cyrinux** [netblue30/firejail#1929]
Hi,
I'm running archlinux with hardened kernel and apparmor enabled. 
I use a yubikey for sign with gpg my mail in thunderbird, I speak the day to try to make it working sign in firejail.
The problem seems to be the pinentry program. By default it find my pinentrey-gnome3 which say "No Gcr System Prompter available, falling back to curses" and seems fallback to ncurse but i can see it. For resume I have no prompt for enter card pin and this fail quickly.
Gcr is:
`❯ pacman -Qi gcr
Name            : gcr
Version         : 3.28.0-3
Description     : A library for bits of crypto UI and parsing
Architecture    : x86_64
URL             : https://git.gnome.org/browse/gcr
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : dconf  gtk3  libgcrypt  p11-kit
Optional Deps   : None
Required By     : gnome-keyring  gnome-online-accounts  gvfs  libcryptui  nm-connection-editor
Optional For    : pinentry
Conflicts With  : None
Replaces        : None
Installed Size  : 5.44 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Thu 03 May 2018 01:22:39 AM CEST
Install Date    : Sat 05 May 2018 07:38:59 PM CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature`

If I force pinentry to pinentry-gtk-2 I have not this error but can find the problem.
Do you have an idea?

Regards

**Comment by Vincent43** [comment]
First of all try running `firejail --noprofile thunderbird` and check if it works.

After that look at `/etc/firejail/thunderbird.profile`. Copy it to `~/.config/firejail/thunderbird.profile` and try disabling some options until you find what causes breakage.

**Comment by Vincent43** [comment]
Instead of `include`  you can copy chromium/firefox profile contents into thunderbird profile. This way you can tweak it without modifying chromium/firefox behavior. For better security you may consider resigning from direct opening links from thunderbird in browser and copy-paste links manually instead. That way you may create more fine grained thunderbird profile.

**Comment by cyrinux** [comment]
Thanks @Vincent43 , I see, there is no magic inside ... If I allow dbus, I can't also filter dbus event I imagine :)

**Comment by Vincent43** [comment]
Yeah, dbus support is only on/off. Flatpak filters dbus access so you may try it instead.

**Comment by chiraag-nataraj** [comment]
Closing, as this seems to be resolved? @cyrinux If you have some enhancement requests, please open a new ticket (e.g. filtering specific dbus requests).
