### ISSUE TITLE
Blender with AMD GPU fails under firejail

### ISSUE THREAD

**Issue by RDProjekt** [netblue30/firejail#1931]
When trying to run Blender with the supplied profile and have it use AMD card via OpenCL an error is encountered. The last part of the trace is as follows:

```
9:blender:opendir /sys/module/amdgpu:(nil)
Writing: /tmp/blender.crash.txt
9:blender:fopen64 /tmp/blender.crash.txt:0x7fb669776300
```
Apparently, amdgpu driver or OpenCL libraries try to access the `/sys/module/amdgpu` directory and fail since `/sys/module`  is permanently blacklisted (disabled).

**Comment by netblue30** [comment]
all set, thanks
