### ISSUE TITLE
Includes missing from firejail apparmor profile

### ISSUE THREAD

**Issue by Irvinehimself** [netblue30/firejail#1941]
I just installed `firejail 0.9.54~rc2-1`, and noticed that the `firejail-default` apparmor profile had included `#include <abstractions/base>` but didn't include the required definitions.

I repaired my own personal copy by adding 
```
#include <tunables/home>
#include <tunables/proc>
#include <tunables/kernelvars>
#include <tunables/multiarch>
```

after your `&PID` declaration and will make a comment  on how to fix it at the [firejail-apparmor](https://aur.archlinux.org/packages/firejail-apparmor/) page on the Arch-AUR, but I thought I should inform you as well.

Thanks for the great work
Irvine

**Comment by Vincent43** [comment]
> I just installed firejail 0.9.54~rc2-1, and noticed that the firejail-default apparmor profile had included #include <abstractions/base> but didn't include the required definitions.

There is no #include <abstractions/base> line in [firejail-default](https://github.com/netblue30/firejail/blob/master/etc/firejail-default.)

**Comment by Irvinehimself** [comment]
I apologise profusely, I just re-installed and the offending line is not there. I don't know how my copy got corrupted.

Apologies again, closing.
Irvine
