### ISSUE TITLE
Firefox 60 no menu with Firejail 0.9.54~rc2

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#1942]
I had the problem with Firefox 60 not loading any web pages. I uninstalled 0.9.52 including dpkg --purge and installed Firejail 0.9.54~rc2 and ran firecfg. Now Firefox loads webpages but there is no menu at the top of the screen (File, History, etc.) on up to date Ubuntu 16.04. Those options return when I run /usr/bin/firefox to avoid firejail.

**Comment by smitsohu** [comment]
@ianh83 could you add the following to /etc/firejail/firefox.local and try it again?
```
ignore apparmor
ignore nodbus
```

In general global menus don't work without D-Bus. Is this actually still an issue with 18.04 on Gnome?

**Comment by igor2x** [comment]
The same problem in my case using Ubuntu 16.04 32-bit hardware and Firejail version 0.9.54~rc2.

![firefox](https://user-images.githubusercontent.com/10895030/40013690-91252692-57ae-11e8-96b7-8efb44822f3d.png)

I executed: "firejail --debug firefox &> firefox.txt" see attached firefox.txt file for debug info: [firefox.txt](https://github.com/netblue30/firejail/files/2001927/firefox.txt)

@smitsohu, I added your two commands in newly created file /etc/firejail/firefox.local and menus are displayed fine now.

**Comment by ianh83** [comment]
Well now I'm very confused as I see different behaviour to igor2x.

On my HP Spectre x360 laptop running up to date Ubuntu 16.04 LTS I get the behaviour described by me above - no File, etc., menus with 0.9.54~rc2 but when I run /usr/bin/firefox the menus appear.

When I create /etc/firejail/firefox.local with only the two lines:
ignore apparmor
ignore modbus

and restart firefox as normal, it makes no difference - I still don't get the File, etc menu - I can only get that menu back by bypassing Firejail completely.

On my Dell 7280 running up to date 18.04 (brand new install), I installed 0.9.54~rc2 and ran firefox and can't see a File, etc, menu anywhere - so I ran Firefox without firejail, and additionally removed and purged firejail completely, rebooted and ran Firefox again and I can still see no File, etc, menu in Firefox at all! I never actually took note of whether Firefox on 18.04 even had a File, etc, menu to begin with before installing Firejail so I don't know what's going on.

**Comment by igor2x** [comment]
I have been playing little bit more.
1. Setting both settings and menus displayed.
ignore apparmor
ignore nodbus
2. Setting only first setting and menus **not** displaying.
ignore apparmor
3. Setting only and menus and menus are displayed.
ignore nodbus
My humble conclusion is only second settings is really required.

@ianh83, what kind of Ubuntu 16.04 do you have 64-bit or 32-bit? Execute: "uname -m" command in my case it displays "i686" which indicates 32-bit. I don't know if this is the issue, just saying...

@ianh83, Firefox on Ubuntu 18.04 using Gnome Shell does not use menus by default, that is pure Gnome Shell experience (that I don't like by the way).

**Comment by ianh83** [comment]
@igor2x Sorry I edited my post as I made a typo in  the .local file. I see the same behaviour as you now. I'm on x86_64 on both OSs.

That explains 18.04 - I don't like it either but I see most of the options are available through firefox's own menu button - apart from 'restore previous session' under history, which I can't find but use a lot.

**Comment by Vincent43** [comment]
Instead of using `ignore aparmor` in `firefox.local` you may try adding:
```
include <abstractions/dbus-strict>
include <abstractions/dbus-session-strict>
dbus,
```
to `/etc/apparmor.d/local/firejail-local` and exec `systemctl restart apparmor` or do a reboot.

**Comment by chiraag-nataraj** [comment]
@Vincent43 FWIW, the AppArmor wiki suggests that you should _not_ do a `systemctl restart apparmor`: https://gitlab.com/apparmor/apparmor/wikis/AppArmorInSystemd

**Comment by Vincent43** [comment]
On on latest upstream apparmor release and ubuntu 18.04 `systemctl restart apparmor` is a safe thing to do. I don't know about 16.04. Perhaps reboot will be better.

**Comment by chiraag-nataraj** [comment]
Hmmm, okay. Yeah, I'm not sure - I saw that wiki a while back when I first started experimenting with apparmor and figured it was safer to either use `apparmor_parser -r` or reboot. I suppose it depends on how the service file is shipped (quite possible the issue has been solved and the wiki hasn't been updated!).

**Comment by ianh83** [comment]
I've just noticed that while @smitsohu  's suggestion has fixed the menu not appearing, I have a new issue - sound for videos or audio played via other methods will correctly play through my bluetooth connected speaker but all audio for Youtube videos and other in-browser content comes through the laptop speakers. Should this be opened as a new issue?

**Comment by igor2x** [comment]
Today I have installed firejail 0.9.54 final on Ubuntu 16.04 32-bit hardware and the problem is the same as in 0.9.54~rc2.

@Vincent43, I tried setting your suggestions from https://github.com/netblue30/firejail/issues/1942#issuecomment-388912279 and I get error:
```
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox.local
Error: "<abstractions/dbus-strict>" is an invalid filename
```
Third solution from my reply https://github.com/netblue30/firejail/issues/1942#issuecomment-388907285 solves the problem, so writing:
` ignore nodbus`
in /etc/firejail/firefox.local solves the problem.

**Comment by chiraag-nataraj** [comment]
This seems to be solved. If this affects too many people, we can enable dbus as the default, but for right now, we can just document this.
