### ISSUE TITLE
Mpv - OpenGL doesn't work with the proprietary Nvidia driver

### ISSUE THREAD

**Issue by aidanharris** [netblue30/firejail#1945]
![](https://i.imgur.com/b1KehT5.png)

OS: Gentoo
Kernel: 4.14.40-gentoo

`nogroups` seems to cause this for some reason. Commenting it out as follows fixed my issue:

```
# Firejail profile for mpv
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/mpv.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.config/mpv
noblacklist ${HOME}/.netrc

# Allow python (blacklisted by disable-interpreters.inc)
noblacklist ${PATH}/python2*
noblacklist ${PATH}/python3*
noblacklist /usr/lib/python2*
noblacklist /usr/lib/python3*

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-interpreters.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

include /etc/firejail/whitelist-var-common.inc

apparmor
caps.drop all
netfilter
#nodbus # Commented out so mpv-mpris works
#nogroups # Commented out because the proprietary nvidia driver doesn't play nicely
nonewprivs
noroot
protocol unix,inet,inet6
seccomp
shell none
tracelog

private-bin mpv,youtube-dl,python*,env,dbus*
private-dev
```

I have no issues on my laptop (a Dell XPS 13) which uses Intel graphics so feel free to close this issue (not sure what your stance is on reporting issues with profiles but at least this gives other people that might also have this problem something to search for).

**Comment by SkewedZeppelin** [comment]
Does commenting noroot instead of nogroups also work?

noroot is known to cause issues with the NVIDIA proprietary driver

**Comment by l29ah** [comment]
I experience the same with palemoon, removing nogroups fixed it.

**Comment by chiraag-nataraj** [comment]
I'm actually getting this issue no matter how I call `mpv` (whether inside of firejail or outside of it). The output looks something like this:
```
[vo/gpu] Could not set GLX context!
[vo/gpu/x11] X11 error: BadWindow (invalid Window parameter)
[vo/gpu/x11] Type: 0, display: 0x7f1d1023e200, resourceid: 2600002, serial: 80
[vo/gpu/x11] Error code: 3, request code: 9b, minor code: 4
[vo/gpu/x11] X11 error: GLXBadContextTag
[vo/gpu/x11] Type: 0, display: 0x7f1d1023e200, resourceid: 2600002, serial: 81
[vo/gpu/x11] Error code: a2, request code: 97, minor code: 5
```

**Comment by chiraag-nataraj** [comment]
`mpv -vo vdpau` seems to help for me (whether inside or outside of firejail).

**Comment by g3ngr33n** [comment]
It maybe no related, but I got some error message too using nouveau and i915 (dual gpu) with electrum

```
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
 libGL error: failed to create dri screen
libGL error: failed to load driver: i915
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: i965
QXcbConnection: XCB error: 2 (BadValue), sequence: 598, resource id: 600, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 603, resource id: 600, major code: 130 (Unknown), minor 
....
```
The window login will be buggy (transparent)  and the QXcbConnection error will prompt every seconds as long I don't resize a bit the window using alt+ right mouse click. 

### Parameters used 

> --seccomp \
> --caps.drop=all \
> --machine-id \
> --nonewprivs \
> --no3d \
> --noroot \
> --nogroups \
> --novideo \
> --noprofile \
> --nosound \
> --notv \
> --nodvd \
> --private=~/electrumjail/ \
> --private-dev \
> --private-tmp \
> --disable-mnt \
> --ipc-namespace \
> --netfilter \

Removing noroot, nogroups, novideo, private-dev, private-tmp, no3d doesn't fix this bug.

**Comment by chiraag-nataraj** [comment]
@g3ngr33n Did you comment on the wrong issue? mpv doesn't have a login window or use Qt.

**Comment by chiraag-nataraj** [comment]
Let's document this and close.
