### ISSUE TITLE
0.9.54 compilation fails on RasPi 2

### ISSUE THREAD

**Issue by drgibbon** [netblue30/firejail#1948]
I'm trying to compile Firejail 0.09.54 on a RasPi 2 (kernel 4.14.37), and I'm running into this error during `make`:
```
In file included from ../include/seccomp.h:63:0,
                 from seccomp.c:21:
seccomp.c: In function ‘memory_deny_write_execute’:
seccomp.c:245:35: error: ‘__NR_pkey_mprotect’ undeclared (first use in this function)
   BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, SYS_pkey_mprotect, 0, 5),
                                   ^
seccomp.c:245:35: note: each undeclared identifier is reported only once for each function it appears in
Makefile:6: recipe for target 'seccomp.o' failed
```
I noticed this in the `configure` output:
```
checking for Spectre mitigation support in gcc or clang compiler... gcc: error: unrecognized command line option '-mindirect-branch=thunk'
... not available
```
the gcc version is 5.5.0.

**Comment by reinerh** [comment]
@drgibbon Do you have linux-libc-dev installed?

@netblue30 
```
/usr/include/asm-generic/unistd.h:#define __NR_pkey_mprotect 288
/usr/include/asm-generic/unistd.h:__SYSCALL(__NR_pkey_mprotect, sys_pkey_mprotect)
/usr/include/arm-linux-gnueabihf/asm/unistd.h:#define __NR_pkey_mprotect		(__NR_SYSCALL_BASE+394)
```
I don't think that workaround is required. It looks like a missing library.

**Comment by drgibbon** [comment]
@netblue30 Build now works with latest master :) As for the grep:
```
$ grep pkey_mprotect `find /usr/include/ -name "*.h"`
/usr/include/bits/syscall.h:#define SYS_pkey_mprotect __NR_pkey_mprotect
/usr/include/bits/syscall.h:#define SYS_pkey_mprotect __NR_pkey_mprotect
```
@reinerh I'm not sure what `linux-libc-dev` is, I'm running Slackware ARM (SARPi community).

**Comment by reinerh** [comment]
@drgibbon Sorry, I assumed you were using Raspbian.
linux-libc-dev is a Debian package that ships Linux kernel headers. As you can see in my grep results, they contain the defines for the syscall numbers.
I would expect that a similar package is available in slackware.

**Comment by drgibbon** [comment]
@reinerh Ah, actually my kernel headers package is out of date compared with the kernel I'm running. This is probably the culprit then?

**Comment by reinerh** [comment]
Yes, that could also be the problem, that your header is so old that the syscall define is not included yet.

**Comment by netblue30** [comment]
Reverted, thanks @reinerh

**Comment by drgibbon** [comment]
Confirming that updating the kernel headers gives a successful build on 0.9.54. Sorry for the noise!
