### ISSUE TITLE
[ENHANCEMENT] make "firejail --list" more readable

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [netblue30/firejail#1949]
Hi,

I tend to have firejail execute some pretty long commands and the current display of `firejail --list` makes it quite hard to know at a glance what jails are running (especially with numerous firefox instances with several "--blacklist=" each).

What do you think of this : 
Instead of returning "PID:User:Command", display "NameOfTheJailIfGiven [somekindofspacerliketab] - PID:User:command" with the named jails appearing at the top and then the unnamed.

Thanks for you time :)

**Comment by netblue30** [comment]
We added the name of the sandbox in 0.9.54. It is something like this: "PID:User:Name:Command". 

Example:

`````
1389:netblue:browser:firejail firefox-esr 
20498:netblue:torrent:/usr/bin/firejail /usr/bin/transmission-qt 
`````

**Comment by thiswillbeyourgithub** [comment]
Oh my god I actually did the update just the other day and hadn't noticed... Sorry :/ And thanks :) !
