### ISSUE TITLE
Discord.profile won't launch

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#1952]
The discord.profile included in firejail-0.9.54-1.x86_64 fails to launch the discord.app. 

Have tried manually specifying the profile:

```
firejail --profile=/etc/firejail/discord.profile /usr/bin/Discord

firejail --profile=/etc/firejail/discord.profile /usr/bin/Discord 
Reading profile /etc/firejail/discord.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Parent pid 10661, child pid 10662
Private /etc installed in 9.14 ms
11 programs installed in 10.02 ms
Child process initialized in 61.33 ms
/bin/bash: /usr/bin/Discord: No such file or directory
```

Manually calling the discord-canary.profile manages to launch but Discord immediately crashes.

Fedora 27 and Mint 18.3 exhibit exact same issue.

**Comment by SkewedZeppelin** [comment]
Okay, I made some changes in 1e3939289f53fd84c92f57bd3144a0eec2dcf1e3 if you want to try a build from master to see if that fixes it. Or you can manually download Discord.profile and discord-common.profile and place them in /etc/firejail and try that.

**Comment by Futureknows** [comment]
Thanks, the latest git was still crashing with the latest official Discord. 
I narrowed it down to `private-etc fonts,machine-id` in the discord-common.profile
Removing the private-etc fonts did it.
