### ISSUE TITLE
Running firejail causes user to no longer appear logged in

### ISSUE THREAD

**Issue by asyncsatcog** [netblue30/firejail#196]
I'm experience a super weird issue where anytime I run firejail, I no longer appear to be logged in with `w`. As you can see, I first appear to be logged in on tty7, then I run firejail and immediately exit, and afterwards it looks like I am no longer logged in 

```
$ w
12:13:19 up 21 min,  1 user,  load average: 1.37, 0.81, 0.46
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
me       tty7      12:13   21:48   0.25s  0.08s i3

$ firejail
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Warning: user namespaces not available in the current kernel.

** Note: you can use --noprofile to disable generic.profile **

Parent pid 19464, child pid 19465
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized
[me@laptop ~]$ exit

parent is shutting down, bye...

$ w
12:13:22 up 21 min,  0 users,  load average: 1.34, 0.81, 0.47
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
```

This causes other programs (running on the system normally, not in a jail) to break, because they depend on utmp to determine the logged in user.

I'm running firejail 0.9.34 and Arch Linux.

**Comment by pigmonkey** [comment]
I experienced this same issue on Arch. Upgrading to the latest git version of Firejail fixed it for me.

**Comment by netblue30** [comment]
Yes, try the latest version on master branch.
