### ISSUE TITLE
Cruzin' the net with --net=none

### ISSUE THREAD

**Issue by charliemb2** [netblue30/firejail#1960]
This appears to be a bug, and if it's a bug it is the last bug I thought I've have to report.  

Here's what I'm seeing;  I can cruse the internet fully and without restriction with a Firefox instance started by either:
- $ firejail --net=none firefox  
- $ firejail --noprofile --net=none firefox

The only mitigating factor that I can think of is that I'm also running another instance of firefox unsandboxed by filejail,  if that matters.

Versions:
- firejail version 0.9.38.10   (installed from Synaptic within Mint to stay as safe as recommended)
- Linux Ming 18.3 Sylvia

I didn't see mention of --net=none dysfunction in any other topic

**Comment by reinerh** [comment]
> The only mitigating factor that I can think of is that I'm also running another instance of firefox unsandboxed by filejail, if that matters.

That's exactly the problem. You are only opening another window of the already running instance.
See also: https://firejail.wordpress.com/support/#firefox

**Comment by charliemb2** [comment]
Indeed,  I see only a single instance of firefox in the system monitor.  
I was under the impression that firefox was now sandboxed.  It is in Windows and there I see separate processes.  

Will "firejail --net=none" start working independently of other firefox instances when firefox becomes sandboxed at some point in Linux?

**Comment by SkewedZeppelin** [comment]
`firejail --private --net=none /usr/bin/firefox --no-remote` is what you need if you want to run a new instance

**Comment by charliemb2** [comment]
Thanks SkewedZeppelin - That worked!
