### ISSUE TITLE
0.9.54 no work?

### ISSUE THREAD

**Issue by SergeyDjam** [netblue30/firejail#1963]
1. sudo firecfg
sudo firecfg                              
[sudo] пароль для admin: 
Removing all firejail symlinks:
   firefox removed
...
Adding user admin to Firejail access database in /etc/firejail/firejail.users
/etc/firejail/firejail.users created

2.  cat /etc/firejail/firejail.users 
admin

3. firejail claws-mail
Error: the user is not allowed to use Firejail. Please add the user in /etc/firejail/firejail.users file, either by running "sudo firecfg", or by editing the file directly.
See "man firejail-users" for more details.

4. firejail --allusers --noprofile claws-mail
Error: the user is not allowed to use Firejail. Please add the user in /etc/firejail/firejail.users file, either by running "sudo firecfg", or by editing the file directly.
See "man firejail-users" for more details.

why?

**Comment by SergeyDjam** [comment]
id -u
500

**Comment by reinerh** [comment]
Ok, then it's the same bug as #1964.

**Comment by SergeyDjam** [comment]
I patch mkuid.sh in source and rebuild
sed -i "s/1000/500/" mkuid.sh

is fix problem

**Comment by netblue30** [comment]
Moving the discussion to #1964 and we will detect UID_MIN at run time. Thanks for the bug!
