### ISSUE TITLE
UID_MIN evaluation at runtime

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#1964]
Currently UID_MIN is obtained at build time from /etc/login.defs.
This will break for users of binary distributions that don't compile software themselves, because they can't use firejail with users that have a lower UID.

A Debian user [reported](https://bugs.debian.org/900337) this problem, as his user has a UID of 256, while the default on the build servers is 1000 (which is not guaranteed; the build server could be configured to have a MIN_UID over 9000).

So instead of hardcoding this, I would suggest to obtain that limit at runtime.

(This might also be the reason in #1963.)

**Comment by mestia** [comment]
What is rationale behind this check for UID_MIN? 
Isn't it much better to allow only users defined in the database?

**Comment by netblue30** [comment]
Will do!

> What is rationale behind this check for UID_MIN? Isn't it much better to allow only users defined in the database?

root user is allowed by default, all other system users (numbers below UID_MIN) run the program as is, without any jail.

**Comment by mestia** [comment]
It seems that I misunderstand the concepts of firejail then :). 
Is it possible to use firejail as a standalone "jail" for applications which will not interfere with  users and applications on system level?

Im my case I would like to run as a system user firejail with a custom profile. That used to work before 9.54.
Now I see that firejail is also interfering with other programs, for example with ssh:
```
root@buster64:~# su - www-data -s /bin/bash
No directory, logging in with HOME=/
www-data@buster64:/$ ssh root@localhost
Error: the user is not allowed to use Firejail. Please add the user in /etc/firejail/firejail.users file, either by running "sudo firecfg", or by editing the file directly.
See "man firejail-users" for more details.
Could not create directory '/var/www/.ssh'.
The authenticity of host 'localhost (::1)' can't be established.
```
Which I think is wrong. BTW any hint why ssh tries to run firejail?

**Comment by netblue30** [comment]
All set, commit: https://github.com/netblue30/firejail/commit/ac9283365224ed46ab2087c050ae1e2916a0dbf5

**Comment by reinerh** [comment]
@netblue30 can this be closed, or is there a reason why you reopened it?

**Comment by Vincent43** [comment]
@netblue30 can you confirm above?

**Comment by JulienPalard** [comment]
> But also, as it stands, system users can't be allowed to run firejail even by adding their names to firejail.users.

I can confirm, and I'm in the same position, I'm using firejail from a system user (ID 999), and even by adding it to the firejail.users it won't be allowed to use firejail, which if find sad.

**Comment by Vincent43** [comment]
@nyarvin  @JulienPalard  I assume you are running latest firejail compiled from github , right?

**Comment by Vincent43** [comment]
@nyarvin but the commit which supposed enable runtime checking is from [June 4](https://github.com/netblue30/firejail/commit/ac9283365224ed46ab2087c050ae1e2916a0dbf5) while firejail 0.9.54 release is from [May 16](https://github.com/netblue30/firejail/releases/tag/0.9.54).

Please test latest git snapshot.

**Comment by nyarvin** [comment]
Runtime checking isn't an issue for me; I was commenting on other aspects of this.  (Which maybe should be moved to a separate issue; if so, apologies for putting them here.)

**Comment by Vincent43** [comment]
@nyarvin ok, please open new issue then.
