### ISSUE TITLE
Integrate TorJail

### ISSUE THREAD

**Issue by PowerPress** [netblue30/firejail#1966]
Could you please look at brining Torjail into FireJail? Would love to see built in enhancement to protector Tor.

https://github.com/torjail/torjail

**Comment by netblue30** [comment]
Sure, we'll try to bring it in.

**Comment by rusty-snake** [comment]
> orjail is a tool that lets you create a jail around a program to force its network traffic through Tor. It creates a hostile environment for anything trying to discover your real IP address.

It uses firejail. It is an own project and IMHO forking it is unnecessary.
