### ISSUE TITLE
No sound output from Firefox after upgrading Firejail to 0.9.54

### ISSUE THREAD

**Issue by mi2iec** [netblue30/firejail#1968]
I have just updated Firejail from 0.9.52 to 0.9.54 and now sound no longer works in 
Firefox 60.0.1

If Firejail is started with `--debug`, the following message is printed in the terminal 
while playing a YouTube video:

`[Child 47, MediaPlayback #3] WARNING: 5593d1b04e60 OpenCubeb() failed to init cubeb: file /home/buildozer/aports/testing/firefox/src/firefox-60.0.1/dom/media/AudioStream.cpp, line 388`

`[Child 47, MediaPlayback #3] WARNING: Decoder=5593d17d1c00 [OnMediaSinkAudioError]: file /home/buildozer/aports/testing/firefox/src/firefox-60.0. /dom/media/MediaDecoderStateMachine.cpp, line 3746`

I use Firefox with only ALSA and all Firejail profiles are default. If I remove Firejail or 
downgrade to 0.9.52, sound works again.

How can I get sound working with Firejail 0.9.54?

**Comment by mi2iec** [comment]
I'm using [Alpine LInux](https://alpinelinux.org/). Firefox is no longer built with ALSA support by default, but it's stille possible to enable it at build time with `--enable-alsa` which it seems like many smaller distributions like Alpine Linux do. As far as i know, Firefox has not completely dropped ALSA support, it's just currently unmaintained.

However, as mentioned in the issue, sound works fine with 0.9.52 or if I disable the Firefox profile after updating, so someting must have happened between 0.9.52 and 0.9.54 that breaks the sound.

**Comment by w00x00** [comment]
I have exactly the same issue. Sound is working without firejail or with firejail 0.9.52

**Comment by chiraag-nataraj** [comment]
Let's switch the discussion to #2042.
