### ISSUE TITLE
Chrome - TwitterDeck

### ISSUE THREAD

**Issue by WarDogSniper** [netblue30/firejail#1970]
Missing something in Firejail ( Chome - Chromium - SlimJet )
Can't login to Twitter Tweet Deck and 2 other Private BBS
it does not happen in Firefox (I have applied the fix to profile)
I am sure there are others
the picture link shows what happens on twitter but not the private boards

OS: Ubuntu 18.04 LTS x86_64
Kernel: 4.15.0-22-generic
firejail version 0.9.52

`firejail --dns=209.222.18.222 --dns=209.222.18.218 chromium-browser %U`

https://tweetdeck.twitter.com/
Resaults Photo
https://kek.gg/i/84vB_x.png

**Comment by smitsohu** [comment]
Thanks for the report.

When you start Chromium from a terminal, do you see suspicious warnings or error messages? In order to debug this, can you please try if it works when you run Chromium as `firejail --noprofile --dns=209.222.18.222 --dns=209.222.18.218 chromium-browser %U`?

Possibly this is related to #1950.

**Comment by smitsohu** [comment]
Can you confirm it still doesn't work when you pass the `--noprofile` option? Thanks.

**Comment by WarDogSniper** [comment]
if I run it 
firejail --noprofile chromium-browser %U
it runs all websites with no issue

but if I try and lock it into a certain dns and --noprofile it will not work correctly

**Comment by SkewedZeppelin** [comment]
Can you try with another DNS besides PIA's?

**Comment by WarDogSniper** [comment]
swapped out PIA and tried Google 8.8.8.8 & 8.8.4.4
with the same --noprofile and it came back with the same time zone issue

**Comment by smitsohu** [comment]
I have trouble reproducing it, but let's mark it as a bug

**Comment by WarDogSniper** [comment]
Please Note: it only shows up when using 
https://tweetdeck.twitter.com/

Not twitter.com
there is also a problem streaming some LIVE Streams   I can give you links to the streams that will not wok in firejail.   

I looked at a few of the sources and they seemed to end with a  .ts

**Comment by smitsohu** [comment]
Sorry for the late response, I gave it a try few days ago and still it was working for me. There must be an additional factor somewhere, unfortunately I don't really understand what Chromium is doing to get the time zone.

**Comment by chiraag-nataraj** [comment]
Is this still an issue?

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this due to inactivity, but @WarDogSniper, please feel free to re-open if you have more/updated info.
