### ISSUE TITLE
"namespace support is disabled" in 0.9.54

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#1971]
Running `firejail --version` I noticed

0.9.52 reports user "namespace support is enabled"
0.9.54 reports user "namespace support is disabled"

Firetools confirms namespace is disable in each firejail running 0.9.54

OS Fedora 27 and Mint reproducible.

**Comment by reinerh** [comment]
From where did you get the package? Is it from your distribution or a deb/rpm from firejail?

Also I just see that in platform/rpm/firejail.spec (for building the rpms) userns support is explicitely disabled. Though I don't know why...

**Comment by SkewedZeppelin** [comment]
@reinerh 
It was disabled [here](https://github.com/netblue30/firejail/commit/1bb8fddae5c92dde1ba750f50e80b306dd9cc6a0#diff-c95419737801a34f6c1c0dc5213ff1a9R22) in early 2016.

I tested with it enabled:
- under Fedora 28 it works fine
- under CentOS 7 the message is printed "Warning: cannot create a new user namespace, going forward without it...", and then continues just fine

If its just a minor warning under some systems and there are benefits to having it enabled I see no reason to not enable it again.

**Comment by netblue30** [comment]
CentOS 7 has a kernel 3.10 with a totally broken user namespace, so I disabled it when building rpm packages to be posted on SourceForge as part of the release. It should work fine on newer kernels on Fedora, but you have to compile it yourself.

**Comment by Futureknows** [comment]
Thanks! Can confirm fresh compiled 0.9.55 enables namespace support in Fedora and Ubuntu.
