### ISSUE TITLE
[SOLVED] running chromium from snap in Firejail

### ISSUE THREAD

**Issue by omega3** [netblue30/firejail#1972]
I need support.  Please explain it to me:

firejail version 0.9.18-rc1

Linux distribution: Kubuntu 14.04

firejail --noprofile chromium
Error: invalid --noprofile command line option

So far I used chromium installed from deb (on Ubuntu 14.04) and snadboxed it fith firejail. Chromium is not available from repositories as deb anymore. So, I installed chromium snap package.

So far I used firejail profile:

`firejail --profile=/media/data/backup/jailkonf/.config/jail.profile --seccomp --private=/media/data/backup/jail/ chromium-browser`

It worked. But after installing chromium from snap package I noticed that it has a long entry in startmenu:

`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop /snap/bin/chromium %U`

Combining those two like that:

`firejail --profile=/media/data/backup/jailkonf/.config/jail.profile --seccomp --private=/media/data/backup/jail/ env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop /snap/bin/chromium %U`

doesn't work.

This also doesn't work:

```
`firejail --profile=/media/data/backup/jailkonf/.config/jail.profile --seccomp --private=/media/data/backup/jail/ chromium %U
Reading /media/data/backup/jailkonf/.config/jail.profile
Reading /etc/firejail/disable-mgmt.inc
Reading /etc/firejail/disable-secret.inc
Parent pid 5456, child pid 5457
Interface           IP                  Mask                Status              
lo                  127.0.0.1           255.0.0.0           UP                  
eth0                1__.1__.0.10        255.255.255.0       UP                  

Child process initialized
need to run as root or suid

parent is shutting down, bye... `
```

I want to be able to use my old chromium profile with this snap version. How to do it?

How can I run chromium with firejail?

The second issue: isn't chromium as snap sandboxed anyway? Would running it with firejail make sense?

**Comment by SkewedZeppelin** [comment]
> firejail version 0.9.18-rc1

First things first, please update your Firejail version, that is almost 4 years old (!) and has many known issues and [vulnerabilities](https://firejail.wordpress.com/download-2/cve-status/). Newer versions are available [here](https://sourceforge.net/projects/firejail/files/firejail/). If possible I'd recommend upgrading your distribution as well, so you can use the packaged versions instead of ppas/snaps/etc.

Next you can try running it again, similar to what you used
```
BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop firejail --profile=/media/data/backup/jailkonf/.config/jail.profile --seccomp --private=/media/data/backup/jail/ /snap/bin/chromium
```
however the profiles have changed dramatically since then and won't work, so try the following instead
```
BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop firejail --profile=/etc/firejail/chromium.profile --private=/media/data/backup/jail/ /snap/bin/chromium
```

> The second issue: isn't chromium as snap sandboxed anyway? Would running it with firejail make sense?

Lastly, snaps/flatpaks do provide some sandboxing, however most do not take full advantage and are often not too strict, where as Firejail profiles are typically much stricter.

**Comment by omega3** [comment]
I updated firejail to the newest deb. 
`BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop firejail --profile=/etc/firejail/chromium.profile --private=/media/data/backup/jail/ /snap/bin/chromium`

returns
`Reading /etc/firejail/chromium.profile
Error: cannot open profile file`

**Comment by Vincent43** [comment]
> Lastly, snaps/flatpaks do provide some sandboxing, however most do not take full advantage and are often not too strict, where as Firejail profiles are typically much stricter.
Honestly, it's the opposite. Firejail can't match strictness and granularity of flatpak/snap sandboxing.  The price for that is installing packages out of repos. Don't try using firejail with snap/flatpak.
