### ISSUE TITLE
Xed as default editor using FileZilla doesn't work i.c.m firejail

### ISSUE THREAD

**Issue by French77** [netblue30/firejail#1974]
When i want to view/edit an file using FileZilla,the chosen file does not want to open with xed,this problem occurs with firejail installed
![xed filezilla firejail](https://user-images.githubusercontent.com/3099270/40802486-052b3508-6516-11e8-87fe-0e18945c0ce1.png)

**Comment by chiraag-nataraj** [comment]
This is because of the `private-bin` line in `/etc/firejail/filezilla.profile`. You'll probably want to add to this line so that `/usr/bin/xed` exists within the sandbox.

**Comment by French77** [comment]
Thanks @chiraag-nataraj  adding xed in `private-bin` `filezilla.profile` is the solution for me
![filezilla profile](https://user-images.githubusercontent.com/3099270/40860861-28e83fd2-65e7-11e8-8640-515937765af3.png)
