### ISSUE TITLE
Add support for ipvlan interfaces

### ISSUE THREAD

**Issue by ValdikSS** [netblue30/firejail#1978]
Firejail adds new macvlan interface when `--net` option is specified. While macvlan is a best choice for Ethernet interfaces, it doesn't work with 802.11 Wi-Fi.
Right now there's no easy way to use Wi-Fi with Firejail. Documentation describes routed setup, which @netblue30 recommends to use in #1600.
Linux kernel contains another interface driver which is very similar to macvlan and works with Wi-Fi: ipvlan. Contrary to macvlan, it shares the same MAC address as the master interface, which allows it to be used with 802.11.

@netblue30, is it possible to auto-detect interface type and use either macvlan for Ethernet and ipvlan for 802.11?

Here's how you can create this interface and use it in Firejail:
```
sudo ip link add link wlp3s0 firewifi type ipvlan mode l2; sudo ip link set firewifi up; sudo ip addr add 192.168.0.199/24 dev firewifi
firejail --interface=firewifi --noprofile
```

**Comment by netblue30** [comment]
Let me give it a try, thanks for the idea!

**Comment by netblue30** [comment]
All in mainline, you can try it out, in your case: 
`````
$ firejail --net=wlp3s0 firefox
`````

**Comment by chiraag-nataraj** [comment]
Hmm, I tried something as simple as `firejail --noprofile --net=wlp60s0` and wasn't able to connect with the outside world. Trying to ping a host would resolve but time out with destination unreachable.

**Comment by ValdikSS** [comment]
@netblue30 it indeed doesn't work for some reason. It doesn't add default route, but adding it manually does not fix the issue. Are you sure you set up ipvlan of `type l2`?

**Comment by netblue30** [comment]
Should be all fixed now: https://github.com/netblue30/firejail/commit/b78cc5869307ddb93a7b1795af992356a54d1d21
