### ISSUE TITLE
firejail prevents id.fedoraproject.org redirection in firefox

### ISSUE THREAD

**Issue by covex** [netblue30/firejail#1980]
Using firejail for a long time, the whole time it happens, that when I want to login to some site using id.fedoraproject.org the redirection freezes and on firefox (59) quit, it crashes.

For example, using http://pagure.io/ clicking on Login should redirect you to an id.fedoraproject.org but it does not. Without firejail it works as expected. I did not found anything using firejail debug mode. Not sure what could be causing this.

**Comment by chiraag-nataraj** [comment]
Huh. So I just tried this and it seems to be working with the profile I use. I'll give it a try with the default profile and report back.

**Comment by chiraag-nataraj** [comment]
Okay, so it worked with the default profile as well. I'm also using Firefox 61b8 though, so idk if that is relevant.

Does anything appear in the syslog? It could be that some weird syscall is required (it sounds like the seccomp filter is kicking in and blocking something firefox needs, which forces it to crash).

**Comment by covex** [comment]
OK, here is what I found in the syslog when I clicked at Login:

Jun  5 16:14:34 me audit[8401]: SECCOMP auid=500 uid=500 gid=500 ses=6 pid=8401 comm=4C617A792049646C65 exe="/usr/lib64/firefox/firefox" sig=31 arch=c000003e syscall=250 compat=0 ip=0x7f442d2ffb99 code=0x0
Jun  5 16:14:34 me kernel: audit: type=1326 audit(1528208074.196:3753): auid=500 uid=500 gid=500 ses=6 pid=8401 comm=4C617A792049646C65 exe="/usr/lib64/firefox/firefox" sig=31 arch=c000003e syscall=250 compat=0 ip=0x7f442d2ffb99 code=0x0

**Comment by covex** [comment]
Then when I try to quit firefox it crashes with core dump:
```
Jun  5 16:18:53 me audit[8953]: SECCOMP auid=500 uid=500 gid=500 ses=6 pid=8953 comm="Shutdow~minator" exe="/usr/lib64/firefox/firefox" sig=31 arch=c000003e syscall=101 compat=0 ip=0x7f442110f34f code=0x0
Jun  5 16:18:53 me kernel: audit: type=1326 audit(1528208333.342:3756): auid=500 uid=500 gid=500 ses=6 pid=8953 comm="Shutdow~minator" exe="/usr/lib64/firefox/firefox" sig=31 arch=c000003e syscall=101 compat=0 ip=0x7f442110f34f code=0x0
Jun  5 16:18:53 me kernel: audit: type=1701 audit(1528208333.342:3757): auid=500 uid=500 gid=500 ses=6 pid=8953 comm="Shutdow~minator" exe="/usr/lib64/firefox/firefox" sig=31 res=1
Jun  5 16:18:53 me audit[8953]: ANOM_ABEND auid=500 uid=500 gid=500 ses=6 pid=8953 comm="Shutdow~minator" exe="/usr/lib64/firefox/firefox" sig=31 res=1
Jun  5 16:18:53 me systemd[1]: Started Process Core Dump (PID 8954/UID 0).
Jun  5 16:18:53 me kernel: audit: type=1130 audit(1528208333.362:3758): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-8954-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun  5 16:18:53 me audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-8954-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun  5 16:18:55 me firejail[1]: monitoring pid 309#012
Jun  5 16:18:56 me systemd-coredump[8955]: Process 8953 (Shutdow~minator) of user 500 dumped core.#012#012Stack trace of thread 308:#012#0  0x00007f442110f34f _ZN15google_breakpad17LinuxPtraceDumper14ThreadsSuspendEv (libxul.so)#012#1  0x00007f4421117b72 _ZN12_GLOBAL__N_117WriteMinidumpImplEPKciliPKvmRKNSt7__cxx114listIN15google_breakpad12MappingEntryESaIS7_EEERKNS5_INS6_9AppMemoryESaISC_EEE (libxul.so)#012#2  0x00007f442111a0a4 _ZN15google_breakpad16ExceptionHandler6DoDumpEiPKvm (libxul.so)#012#3  0x00007f442111a100 _ZN15google_breakpad16ExceptionHandler11ThreadEntryEPv (libxul.so)#012#4  0x00007f4421110e7b _ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE (libxul.so)
Jun  5 16:18:57 me audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-8954-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun  5 16:18:57 me kernel: audit: type=1131 audit(1528208337.019:3759): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-8954-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun  5 16:18:57 me firejail[8397]: exiting...
```

**Comment by chiraag-nataraj** [comment]
If you do a `firejail --debug-syscalls | grep 250`, does it give you `keyctl`? Does `firejail --ignore=seccomp firefox` work properly?

**Comment by covex** [comment]
```
$ firejail --debug-syscalls | grep 250
250     - keyctl
```
with --ignore=seccomp the redirection works, no crash.

**Comment by chiraag-nataraj** [comment]
Okay, so my suspicion was correct. This is really weird, though, since it means firefox is performing manipulations of the kernel's keyring... @netblue30, any idea why this could be happening?

**Comment by covex** [comment]
id.fedoraproject.org is a fedora OpenID site serving as a centralized authorization facility for fedora infrastructure. I could imagine it may be trying to search some keys via keyctl. I may ask on fedora lists.
So to solve this, should I add a seccomp.keep keyctl to my firefox profile?

**Comment by chiraag-nataraj** [comment]
> id.fedoraproject.org is a fedora OpenID site serving as a centralized authorization facility for fedora infrastructure. I could imagine it may be trying to search some keys via keyctl.

That doesn't make any sense, since it worked perfectly fine here on Debian (unless you're saying you weren't able to log in? I didn't try that, since I don't have Fedora credentials).

> So to solve this, should I add a seccomp.keep keyctl to my firefox profile?

No, that would _only_ allow `keyctl` :stuck_out_tongue_winking_eye: The easiest is probably to edit `/etc/firejail/firefox-common.profile` to not include `keyctl`.

**Comment by chiraag-nataraj** [comment]
@covex, did removing `keyctl` from the list of syscalls in `/etc/firejail/firefox.profile` work?

**Comment by chiraag-nataraj** [comment]
Try this instead of the `seccomp` line:
```
seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice
```

**Comment by chiraag-nataraj** [comment]
@covex Did you try that `seccomp` line? Did it work?

**Comment by chiraag-nataraj** [comment]
Closing because of no response. @covex, feel free to re-open if you were able to try that `seccomp` line.
