### ISSUE TITLE
Small mistake in the manual

### ISSUE THREAD

**Issue by Javapraca** [netblue30/firejail#199]
I guess there is a small mistake in Firejail's manual (and on webpage: https://l3net.wordpress.com/projects/firejail/firejail1/), in the following fragment (```SECURITY PROFILES``` section):
```
To  disable  default  profile  loading,  use
       --noroot command option. Example:
```
Probably ```--noprofile``` option should be used instead (as it is also in the example).

**Comment by netblue30** [comment]
Fixed, thanks.

**Comment by Javapraca** [comment]
Please fix it also on the webpage :).
