### ISSUE TITLE
webcam works in Firefox although --private-dev was set 

### ISSUE THREAD

**Issue by nemoload** [netblue30/firejail#1991]
In issue #745 `--private-dev` was supposed to disable webcam but it works normally as if it wasn't set

**Comment by chiraag-nataraj** [comment]
This is actually true of `guvcview` as well. I wonder if it's because it's calling to an outside library (`libv4l{1,2}`) rather than enumerating the devices itself?

**Comment by chiraag-nataraj** [comment]
Oh wait...`/dev/video0` is whitelisted in `private-dev`. Add `novideo` in the profile (or `--novideo` on the commandline) to disable the video devices.

**Comment by Fred-Barclay** [comment]
Just to add to @chiraag-nataraj ...
`private-dev` did originally block video devices. They were allowed in 328d523ed62dfcdb205580ce7c126813b592cb7, and the option to block them re-added in https://github.com/netblue30/firejail/pull/1296.
