### ISSUE TITLE
Minor man page fixes/suggestions

### ISSUE THREAD

**Issue by boltronics** [netblue30/firejail#2]
The top of the FIREJAIL-PROFILE(5) and FIREJAIL(1) man pages both say man(5) and man(1) respectively, instead of having the correct name.

Also, I think it's a mistake for the firejail-profile(5) seccomp section to not list the defaults. I assume it's the same as those in --seccomp discussed in firejail(1), but it would be nice if it was explicit and didn't force the user to hunt the list down. I would suggest either duplicating the list, or simply pointing the reader to the firejail(1) --seccomp section.

**Comment by boltronics** [comment]
Also, you have:
```
       caps.drop capability,capability,capability
              Whitelist Linux capabilities filter.
```
which I assume should be:
```
       caps.keep capability,capability,capability
              Whitelist Linux capabilities filter.
```

**Comment by boltronics** [comment]
One other thing is that it's very unclear how the ```include``` arguments work.

The man page simply states:
```
       Include and comment support:

       include other.profile
              Include other.profile file.
```

In a Chromium profile, I have the lines:
```
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc chromium
```
So presumably the ```chromium``` argument disables the ```blacklist ${HOME}/.config/chromium``` line in disable-common.inc, but it's not clear how this works. Is it a regex? A file glob? It appears that adding the full path (ie. ```${HOME}/.config/chromium```) doesn't work, which is surprising.

**Comment by netblue30** [comment]
Thanks, I'll I'll fix them

**Comment by netblue30** [comment]
Fixed! Let me know if you find anything else.

**Comment by boltronics** [comment]
No worries. Looks good, but I need to figure out how to package this before I can properly test. Looks like a few debian files are missing (eg. changelog, rules, compat) and the control file is missing the information on creating a source package as well. I've got it mostly building, but still hitting a snag.

I know there is a package for this in Debian sid, so I might reference that for some pointers, and will get back to this when I have time. Otherwise, feel free to close and I can re-open if I notice something's still not quite right. Thanks!

**Comment by netblue30** [comment]
This is how I build the packages I distribute myself:

$ ./configure --prefix=/usr
$ sudo make deb

**Comment by boltronics** [comment]
Interesting. I didn't notice that mkdeb.sh file - I wasn't looking for it and didn't expect something like that. I believe dpkg-buildpackage is the recommended way to handle this (it's what is documented in the [Debian New Maintainers' Guide](https://www.debian.org/doc/manuals/maint-guide/build.en.html), but your script seems to simply rearrange the directory structure and finally calls ```dpkg-deb -b``` directly.

Might be worth a read: https://raphaelhertzog.com/2010/12/17/do-not-build-a-debian-package-with-dpkg-b/

Happy to open another issue/feature request if you agree. :)

**Comment by netblue30** [comment]
It's not worth it. I hope to get out of the package building soon, Debian guys are taking over the packages.

**Comment by boltronics** [comment]
> I hope to get out of the package building soon, Debian guys are taking over the packages.
It's still useful for people that want to build from source. For example, if I'm going to test your changes, I'm going to want to build a package from git, so I'd just run git-buildpackage or dpkg-buildpackage. and know what I'm building is safe and compliant. Forcing people to create packages from scratch to use the git sources can be a bit much.

IMO, this is an example of a project that gets packaging right:
http://cdemu.sourceforge.net/debian/

If I find the time, would you accept a pull request?

**Comment by netblue30** [comment]
Absolutely! If you send a pull request I'll accept it. Thanks!
