### ISSUE TITLE
Ark does not open zip files

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#2001]
I've noticed that Ark does not open zip files on Fedora 28 KDE. Using firejail-git.

Commenting the `private-bin` line fixes the problem. So it seems that something is missing in that line. I haven't been able so far to find it.

**Comment by chiraag-nataraj** [comment]
Does it work under the release version (0.9.54)? Because just looking at the profiles, there doesn't seem to be anything significantly different in terms of the profile between the current dev version and the current release version.

**Comment by curiosity-seeker** [comment]
Just tested 0.9.54 on Siduction. zip files aren't opened, either.

**Comment by chiraag-nataraj** [comment]
Hmm, okay. You can try commenting out `private-bin` and running `strace`, which might help you catch which binaries are not being included.

**Comment by curiosity-seeker** [comment]
I tried it with

`strace -e trace=file /usr/bin/ark`

but didn't find an executable in the output that wasn't already included (except ldd but that didn't make a difference). 
In journalctl I'm getting the error:

`ark[29214]: Empty filename passed to function`

**Comment by chiraag-nataraj** [comment]
Huh, that's interesting. I wonder why commenting `private-bin` fixes that...normally, seeing that would make me think some files aren't accessible in the sandbox, so it would be more of a `private` or `whitelist` issue...

**Comment by SkewedZeppelin** [comment]
I think I fixed it
can you try with the following?

```
private-bin 7z,ark,bash,dash,lrzip,lsar,lz4,lzop,p7zip,rar,sh,tclsh,unar,unrar,unzip,zip,zipinfo
```

**Comment by curiosity-seeker** [comment]
Thanks - this works! Great. `bash,dash` is not needed here, though.

A general question for future cases: is there a systematic way to find those needed binaries other than the above mentioned `strace -e trace=file ...` ?

**Comment by SkewedZeppelin** [comment]
Awesome, I'll commit that. And I think bash is actually needed from what I saw.

And I just used strace, it was just a bit buried to find that it was needed.

Here were the actual commands I used

```
strace -fv -o test.log ark test.zip
grep "ENOENT" -v test.log | grep "/bin" > bins.txt
```

then I deduplicated bins.txt and sifted through it.
And sure enough tclsh and bash were being passed to execve.

**Comment by curiosity-seeker** [comment]
Thanks - very helpful, indeed!

**Comment by curiosity-seeker** [comment]
I wonder if [perf](http://brendangregg.com/perf.html) is even more helpful here. I think I'll have to do some digging.
