### ISSUE TITLE
[Feature request] Make settings in firejail.config ignorable in profiles

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#2002]
The `Firejail Usage` page [suggests](https://firejail.wordpress.com/documentation-2/basic-usage/#suid) to set

`force-nonewprivs yes`

in /etc/firejail/firejail.config as one measure to mitigate the concerns about Firejail being a SUID application. 

One of the programs affected by this switch is VirtualBox. When I try to start it I'm getting the error:
![grafik](https://user-images.githubusercontent.com/14075215/41418430-33e00620-6fdf-11e8-9bc8-a62c787a94df.png)

Adding `ignore nonewprivs`or `ignore force-nonewprivs` does not work. Hence, I suggest to add such a feature as it would help to harden Firejail in general but would allow exceptions for specific incompatible applications at the same time.

**Comment by chiraag-nataraj** [comment]
One way you can do this is instead put `nonewprivs` in `/etc/firejail/globals.local`. Then, you should be able to use `nonewprivs` in your VirtualBox profile.

**Comment by SkewedZeppelin** [comment]
Adding to @chiraag-nataraj I think the firejail.config is intended to allow system administrators to enforce specific settings to users. Adding support to bypass settings in profiles would also need a new option in the config to allow that.

**Comment by curiosity-seeker** [comment]
> One way you can do this is instead put nonewprivs in /etc/firejail/globals.local.

Yes, you're right. I had forgotten about that. Thanks! 

Nevertheless, the question remains: Wouldn't it make sense to use this setting by default and add an exception for the very few applications affected?

**Comment by SkewedZeppelin** [comment]
> Nevertheless, the question remains: Wouldn't it make sense to use this setting by default and add an exception for the very few applications affected?

Nearly all profiles already use nonewprivs
```
$ grep "redirect" . -RiL | wc -l
385 #number of non-alias profiles
$ grep "nonewprivs" /etc/firejail -R | wc -l
358 #number of profiles with nonewprivs
```

I think the benefit of force-nonewprivs is however different then that of nonewprivs.

**Comment by curiosity-seeker** [comment]
> Nearly all profiles already use nonewprivs

Thanks, I see. I just thought that it might be easier the other way round.

Please feel free to close this issue if it's out of question.

**Comment by chiraag-nataraj** [comment]
So I think the point of the stuff in `firejail.config` is that those are settings which can't be overridden by profiles. Those options are designed to override any profile-specific options you may have. Basically, I guess what I'm trying to get at is that `force-nonewprivs` _isn't_ for the usecase you're describing - the usecase you're describing is solved as I described above :) That being said, we may want to update the docs, since pointing people to `firejail.config` when it's not necessarily meant to be used in this way (as you found out) isn't exactly a good user experience.

**Comment by chiraag-nataraj** [comment]
@netblue30 Can you update the suggested usage on the site?

**Comment by rusty-snake** [comment]
@netblue30  echoing @chiraag-nataraj
