### ISSUE TITLE
[Question] Does Firejail "sudo" commands effective in this special case ?

### ISSUE THREAD

**Issue by Nokia808** [netblue30/firejail#2004]
Hi.

Currently I'm using WineHQ according to this super secure installation guide:
https://forums.fedoraforum.org/showthread.php?313858-Risk-Free-WineHQ-Installation-amp-Usage

Please notice the following about this method:

1) WineHQ binaries ownership & permissions all are changed so that WineHQ are owned by a special user account (WineHQ are isolated totally in special new user account)

2) the special new user account is completely rootless (have no su nor sudo nor PolcyKit power).

My question case is: I like to add additional layer of security by using Firejail. Firejail certainly can never ever be installed from Wine special account because it need sudo to be installed. So, I'm only able to install Firejail from within my 1st user account which I created during fresh installation & have all root powers including su.

But to make Firejail's profile of WineHQ I need the following command:

sudo firecfg --clean && sudo ln -s /usr/bin/firejail /usr/local/bin/wine

the above command is to make WineHQ only sanbox WineHQ not other application.

So, does the above command (or "sudo firecfg" which make WineHQ sandbox all supported application not only Wine) will take effect on WineHQ ? When I run "sudo dnf remove wine" or sudo dnf upgrade wine" from my 1st user account they working. But the Firejail commands that I asking about them deal with sandbox for a package binaries owned by only special user account & not by all accounts on system (Windows application inside my 1st user account can not make use of Wine to run at all).

Best.

**Comment by netblue30** [comment]
firecfg is setting a bunch of symbolic links in /usr/local/bin. Once you run it from your regular account, it is available to all users in the system. You don't need to run it again from your special wineuser account. All you have to do is to add that user to the list in /etc/firejail/firejail.users file. Or you can run "sudo firecfg --add-users wineuser" from your regular account.

**Comment by Nokia808** [comment]
@netblue30 

Thank you for response. O.K, so, "sudo firecfg --add-users wineuser"

But what about "sudo firecfg --clean && sudo ln -s /usr/bin/firejail /usr/local/bin/wine" command ? Is the same applied to this command also ? If yes, then, how it will be ? (where I have to put "--add-users wineuser" ?)

----------------------

By the way, I conclude from the need to add "--add-users wineuser" to firecfg (add that user to the list in /etc/firejail/firejail.users file), that Firejail by default add only the root accounts (su & sudo accounts) after it's installation & do not include other added accounts. Is this correct or I'm wrong ?

**Comment by chiraag-nataraj** [comment]
> But what about "sudo firecfg --clean && sudo ln -s /usr/bin/firejail /usr/local/bin/wine" command ? Is the same applied to this command also ? If yes, then, how it will be ? (where I have to put "--add-users wineuser" ?)

So if I understand you correctly, you're asking if manually symlinking one binary (rather than _all_ as `firecfg` will do) will be subject to the same access restrictions as it would be under `firecfg`. The answer, from what I understand, should be yes. If you _only_ want to (automatically) run `wine` under `firejail`, then do the following steps:

1. `sudo firecfg --clean`
2. `sudo ln -s /usr/bin/firejail /usr/local/bin/wine`
3. `sudo firecfg --add-users wineuser`

and you should be good to go!

**Comment by chiraag-nataraj** [comment]
Closing, since the question seems to be answered. @Nokia808 Please feel free to re-open if you still have questions.
