### ISSUE TITLE
invalid whitelist path if /var/tmp is symlink to /tmp

### ISSUE THREAD

**Issue by msva** [netblue30/firejail#2011]
Hi there!

I've faced sad issue on git HEAD:
if /var/tmp is symlink to /tmp, firejail refuses to start (because it includes `/etc/firejail/whitelist-var-common.inc`), and says:
```
...
Error: invalid whitelist path /var/tmp
Error: proc 1110 cannot sync with peer: unexpected EOF
Peer 1111 unexpectedly exited with status 1
```

Although, there is some checks for `/var/tmp` being a symlink in `fs.c`, it still fails in `whitelist.c`.

Can you fix it, please?

**Comment by smitsohu** [comment]
I've pushed a fix, can you give it a try?
