### ISSUE TITLE
Can't run firefox, chromium through firejail. 

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#2027]
Hi guys, 
Im using  firejail version 0.9.54 on openSUSE Leap 15`

> $  firejail --version
Compile time support:
        - AppArmor support is disabled
        - AppImage support is enabled
        - bind support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled`

I can't seem to run firefox or chromium with firejail. I get this error 

"Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set."
However vlc, gwenview runs okay. 

Here is the full output 

>firejail chromium
Reading profile /usr/local/etc/firejail/chromium.profile
Reading profile /usr/local/etc/firejail/chromium-common.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 25304, child pid 25305
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 52.78 ms
No protocol specified
No protocol specified

(chromium:4):

 Gtk-WARNING **: cannot open display: :0

Parent is shutting down, bye... 

I have tried using the firejail LTS version but no luck. 
Some of other methods i tried are from this post:
https://github.com/netblue30/firejail/issues/1885

I did sudo firecfg --clean + firejail chromium: and still no luck. 

Any idea how I should proceed?

**Comment by Fred-Barclay** [comment]
What happens with `firejail --noprofile chromium` or `firejail --noprofile firefox`?

**Comment by chiraag-nataraj** [comment]
One thing you can also try is using the `chromium` profile that I use. Keep in mind that for various reasons, you should either comment out `private-bin` or run `chromium` as `firejail /usr/lib/chromium/chromium`. Also, note that to install this profile, simply copy both files to `~/.config/firejail/` and rename them to `chromium.profile` and `common.inc` respectively.

[chromium.txt](https://github.com/netblue30/firejail/files/2175966/chromium.txt)
[common.txt](https://github.com/netblue30/firejail/files/2175967/common.txt)

**Comment by chiraag-nataraj** [comment]
@OMslaw04 Were you able to debug the profile to see what was breaking (or use the profile I provided)?

**Comment by OMslaw04** [comment]
@chiraag-nataraj  here is the result with the two files coped to ~/.config/firejail
> $ firejail chromium

> Reading profile /home/ohms/.config/firejail/chromium.profile
Reading profile /home/ohms/.config/firejail/common.inc
Parent pid 21703, child pid 21704
Warning: skipping chromium.d for private /etc
Private /etc installed in 14.09 ms
Warning: skipping emp for private /opt
Private /opt installed in 0.04 ms
11 programs installed in 12.64 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 36.31 ms

> Parent is shutting down, bye...
 

So if i were to comment the `private bin` line I have issue accessing to the X11 files 
error:
`(chromium:9): Gtk-WARNING **: cannot open display: :0`

on the other hand if i uncomment I get this. 
`Reading profile /home/ohms/.config/firejail/chromium.profile`
`Reading profile /home/ohms/.config/firejail/common.inc`
`Parent pid 22080, child pid 22081`
`Warning: skipping chromium.d for private /etc`
`Private /etc installed in 15.19 ms`
`Warning: skipping emp for private /opt`
`Private /opt installed in 0.04 ms`
`11 programs installed in 13.05 ms`
`Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.`
`Child process initialized in 39.13 ms`

`Parent is shutting down, bye...`

I also had to comment `nou2f`from `common.inc`
I tried commenting line by line in `common.inc` but I get this error
`Reading profile /home/ohms/.config/firejail/chromium.profile`
`Reading profile /home/ohms/.config/firejail/common.inc`
`Error: line 22 in /home/ohms/.config/firejail/common.inc is invalid`
which I don't think is the way to go.

**Comment by chiraag-nataraj** [comment]
> here is the result with the two files copied to ~/.config/firejail

Can you use `firejail --debug chromium` and either post or attach the output (if the output is really long, please attach it as a separate file!).

> I also had to comment nou2f from common.inc

Oh yeah sorry about that - I added `nou2f` in `master` and forgot that it's not in `0.9.54` :stuck_out_tongue_winking_eye:

**Comment by OMslaw04** [comment]
@chiraag-nataraj https://pastebin.com/Pn7kJsiT here is the output for `firejail --debug chromium`

**Comment by chiraag-nataraj** [comment]
Can you run `firejail --debug` with `private-bin` commented (so that we get the `cannot open display: :0` error along with firejail's debug output)?

**Comment by OMslaw04** [comment]
https://pastebin.com/8P0AQ3wG
here is the output to `firejail --debug` with `private-bin` commented

**Comment by chiraag-nataraj** [comment]
Yeah, this is really weird. Let's ignore the profile I gave you for the moment and go back to the default profile (the one you were using). Can you go through and comment stuff until it works? That might give us a good idea of where to get started in terms of finding the issue.

**Comment by chewblacka** [comment]
Hi just posting to say I am also running Open Suse Leap 15.0 and firefox in firejail was working fine up until a week or so ago. But now for some reason it conks out with `Permission Denied`:
https://pastebin.com/cKXTt49X
`firejail --debug firefox` gives the following:
https://pastebin.com/HDb9bybF
`firejail --noprofile firefox` works but unsandboxed (as expected).

**Comment by SkewedZeppelin** [comment]
To confirm @chewblacka  and @OMslaw04 you both installed from git/make install, yes?

**Comment by OMslaw04** [comment]
@chiraag-nataraj 
[chromiumprofile.txt](https://github.com/netblue30/firejail/files/2248807/chromiumprofile.txt)

So this is my default profile.

I tried commenting every line and run `firejail chromium`
I would always get

> Reading profile /usr/local/etc/firejail/chromium.profile
Reading profile /usr/local/etc/firejail/chromium-common.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 24824, child pid 24825
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
directory resolved as "Downloads"
Child process initialized in 61.88 ms
No protocol specified
No protocol specified

> (chromium:4): Gtk-WARNING **: cannot open display: :0

> Parent is shutting down, bye...

All of these can't seem to fetch the display.
By default line 18 `#private-bin chromium,chromium-browser,chromedriver` is commented. 
If i were to uncomment I would end up with 
>Reading profile /usr/local/etc/firejail/chromium.profile
Reading profile /usr/local/etc/firejail/chromium-common.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 24813, child pid 24814
1 program installed in 1.49 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
directory resolved as "Downloads"
Child process initialized in 42.08 ms

>Parent is shutting down, bye...

I am so clueless right now.

@SkewedZeppelin yes correct.

**Comment by chiraag-nataraj** [comment]
@OMslaw04 So if you comment out _everything_ in `chromium.profile`, it still doesn't run? That should be the same as `--noprofile` though.

If commenting out _all_ lines works, can you go through and slowly uncomment particular lines (or groups of lines if necessary - e.g. whitelists) to see what breaks it?

**Comment by chewblacka** [comment]
Mods, should I carry on posting in this thread or start my own thread?
I've discovered that if I compile without apparmor support firefox works, so apparmor seems to be the issue. Is it possible that an update to OpenSuse Leap borked something?

**Comment by chiraag-nataraj** [comment]
@chewblacka I had the same issue, and a reboot fixed it (I suspect it has to do with an apparmor upgrade). Can you try `sudo aa-disable firefox`? If you check your logs, you'll probably see something like `apparmor` blocking `firejail` from applying certain things because of the `firefox` apparmor profile (e.g. `nonewprivs`).

**Comment by chiraag-nataraj** [comment]
@OMslaw04 What is the result when you comment out _everything_ in `chromium.profile`?

**Comment by chewblacka** [comment]
thanks @chiraag-nataraj, are you using Open Suse too?
It is definitely to do with apparmor (most likely an upgrade as you say). I compiled without apparmor support and it worked fine. So I recompiled with apparmor support and have added the noapparmor option in the firefox conf. Everything is working ok now.

**Comment by chiraag-nataraj** [comment]
@chewblacka Good to hear. Nope, I'm using Debian sid/experimental, but I have a more "standard" Debian VM which enabled apparmor by default, and I ran into some of these issues.

**Comment by OMslaw04** [comment]
@chiraag-nataraj with everything commented it runs. Like you said it runs like `--noprofile`
@chewblacka I am on OpenSUSE Leap 15 too, I complied with AppArmour and still no luck.

**Comment by uli13** [comment]
I am an openSUSE user too. FIrejail works in Tumbleweed but not in LEAP15 with the same output:
`Gtk-WARNING **: cannot open display: :0 ` 
and for firefox
`Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0`
I am using firejail 0.9.54 and it works with `--noprofile`. I use the standard profile but I commented out apparmor that made firejail work in Tumbleweed but had no effect in Leap15.
The command `aa-disable firefox
Profile for /usr/lib64/firefox/firefox.sh not found, skipping`
Similar for chromium. Any help is appreciated

**Comment by chiraag-nataraj** [comment]
@OMslaw04 Okay. Now go through and re-enable stuff until it breaks. That's how we can figure out _what_ is breaking it.

**Comment by Vincent43** [comment]
For people with apparmor issues, can you try if [this fix](https://github.com/netblue30/firejail/issues/2078#issuecomment-413041131) works for you?

**Comment by chiraag-nataraj** [comment]
@OMslaw04 Can you report back with which thing actually breaks your setup? Then we can fix this :) Or, if your issue is fixed by what @Vincent43 linked to, can you also report back? That way we know this issue is solved.

**Comment by wofwofwof** [comment]
Not sure if it is the same issue, but I had the same problem on gentoo with thunderbird and it was fixed with adding unix to the protocol.

**Comment by chiraag-nataraj** [comment]
Is this still an issue for whoever commented and is still on Github?

**Comment by chiraag-nataraj** [comment]
I'm going to close this for inactivity. If someone is still having this issue, please feel free to re-open it.

**Comment by whussup** [comment]
Hi there!

You just need to export your XAuthority properly. A whitelist entry for the authority file afterwards will grant you access within the sandbox (e.g. --whitelist=/home/user/.xauthxxxxXX) [tested with GrSec/Selinux/Apparmor/su sandbox -> firejail]

Cheers!
