### ISSUE TITLE
Chrome native notifications are broken

### ISSUE THREAD

**Issue by infokiller** [netblue30/firejail#2028]
Chrome supports native Linux notifications for some time ([article](https://www.omgubuntu.co.uk/2017/04/google-chrome-dev-lets-enable-native-desktop-notifications)), and they worked for me before starting it with firejail.
Now it seems that Chrome uses its own notification system, even if I force it to use native Linux notifications.
After doing some testing, I think the issue is that chrome has `nodbus` in its profile (via [chromium-common.profile](https://github.com/netblue30/firejail/blob/master/etc/chromium-common.profile#L25)).

Is there a way for me to disable the `nodbus` command using a local chrome profile (~/.config/firejail/chrome.profile)?
I know that I can rewrite the whole profile locally, but I would much rather have something like:
```
include /etc/firejail/google-chrome.profile
enable-dbus
```

Or something similar.

Thanks!

**Comment by Fred-Barclay** [comment]
Hi @infokiller Yes, you can create the file `/etc/firejail/chrome.local` with the line
```
ignore nodbus
```
and this should allow dbus access in the sandbox and (hopefully) native notifications for Chrome.
However, it's worthwhile noting that dbus can be used to escape the firejail sandbox, so *hypothetically* this lowers your security.  You still have all the other features of firejail, but if the sandbox were successfully escaped then they might have little or no effect.

**Comment by infokiller** [comment]
Thanks a lot @Fred-Barclay!

**Comment by Fred-Barclay** [comment]
UPDATE: I'm sorry, the file name should be `/etc/firejail/chromium-common.local` that way no matter if you use chromium, or google-chrome stable, beta, or unstable, you'll get native notifications.
