### ISSUE TITLE
Question about shell=none

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#203]
Hi!
With versions 0.9.32 and earlier, when I wanted to join an existing firejail session with `shell none`, it would tell me that it's already in use and then deny access. But with 0.9.34, I can join in.
Is it on purpose?

Thanks.

**Comment by netblue30** [comment]
Yes, it will join the sandbox if /bin/bash or /bin/sh is available inside the sandbox. The idea is to provide a way to modify a running sandbox.

**Comment by nick75e** [comment]
Then what does `shell none` actually do?
I thought it was to prevent apps from accessing the shell within the sandbox.
PS: Sorry for the stupid questions but I'm a little lost here

**Comment by netblue30** [comment]
It starts the application directly, without a shell. However, --join creates a new shell in the sandbox. The shell is running in parallel with your application. Your application still runs outside the shell, but it could create a shell of its own.

**Comment by nick75e** [comment]
Now I understand!
Thanks for answering and the release of 0.9.36 btw.
