### ISSUE TITLE
Machine-ID breaks Pulseaudio

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#2037]
This was discussed but a solution isn't clear.
--machine-id flag breaks Pulseaudio so no sound in Tor-browser and other firejails.
Turning off MID spoofing exposes the persistent machine-id (hardware fingerprint) inside the sandbox. 
We are running Pulseaudio 11.1 and this issue persists.
Is there a current solution?

**Comment by Vincent43** [comment]
In which profile `machine-id` breaks Pulseaudio? It works for me in firefox.

**Comment by Futureknows** [comment]
Tor-Browser-Launcher, Brave, Firefox, Chromium pretty much every firejail I launch with --machine-id.

**Comment by chiraag-nataraj** [comment]
I don't even _have_ `/etc/machine-id` available in many of my personal profiles, and sound hasn't broken for me yet.

What do you get if you put in a `private-etc` filter leaving out `machine-id`. For example, this is the one I use with my `firefox` profile: `private-etc hosts,passwd,mime.types,fonts,mailcap,firefox,xdg,gtk-3.0,X11,pulse,alternatives,localtime,nsswitch.conf` (you might also need `resolv.conf` in there depending on your setup).

**Comment by Vincent43** [comment]
Both Chromium and Firefox have sound working while using `machine-id` on Archlinux and KDE for me. What distro and desktop environment are you using?

**Comment by Futureknows** [comment]
I didn't add  *--machine-id *to any profile. I'm issuing firejail commands
as documented *firejail --machine-id firefox*.
Any time I include *--machine-id  *I lose Pulseaudio in any Browser
(Chromium, Brave, Firefox, Tor).
Current Fedora 28 with Cinnamon but I am seeing similar issue on Mint 18.3.

I'm going to figure out private-etc and report back.
Thanks!

**Comment by Futureknows** [comment]
I didn't add  `--machine-id `to any profile. I'm issuing firejail commands as documented `firejail --machine-id firefox`. Any time I include `--machine-id ` I lose Pulseaudio in any Browser (Chromium, Brave, Firefox, Tor). 
Current Fedora 28 with Cinnamon but I am seeing similar issue on Mint 18.3.

I'm going to figure out private-etc and report back.
Thanks!

**Comment by Vincent43** [comment]
> I didn't add --machine-id to any profile. I'm issuing firejail commands as documented firejail --machine-id firefox

It doesn't matter. It has same effect.

**Comment by chiraag-nataraj** [comment]
@Futureknows Did you test the `private-etc` filter? I've turned on `machine-id` on all of my (personal) profiles with no issues so far. What exactly is your `pulseaudio` setup? Is it the default/standard setup? Did you make any changes?

**Comment by chiraag-nataraj** [comment]
(Also, btw, `machine-id` is useful _even_ if you use a `private-etc` filter, since the machine ID is also available at `/var/lib/dbus/machine-id` which is also spoofed by `firejail`)

**Comment by netblue30** [comment]
> --machine-id flag breaks Pulseaudio so no sound in Tor-browser and other firejails.

Somehow pulseaudio ends up reading /etc/machine-id and it will refuse to start if it doesn't find it. Also some part of the dbus code might read it. I don't know why they do that. I'll have to try Arch, maybe they removed it, see @Vincent43 comment above.

**Comment by chiraag-nataraj** [comment]
The same is true for me on Debian - I can get away without having pulse read the machine ID.

**Comment by Futureknows** [comment]
I didn't make any changes to Pulseaudio, it is the default install from Fedora 28 Cinnamon which must have just recently been updated to 12.0, it was 11.1. It is persistent across all apps, I don't get Pulseaudio output from Rhythmbox, VLC or anything firejailed with --machine-id.

I noticed a dbus error when --machine-id is present:
```

(rhythmbox:10): dbind-WARNING **: 17:04:26.792: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-BqrQlHOiVH: Connection refused

(rhythmbox:10): Rhythmbox-WARNING **: 17:04:27.302: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.MediaKeys was not provided by any .service files
```

**Comment by chiraag-nataraj** [comment]
Huh...you probably need `ca-certificates` and `ca-certificates.conf` I guess? That's weird that I don't end up require it...

**Comment by Futureknows** [comment]
Incidentally the problem was similar on my Mint machine and although private-etc doesn't break networking Puslseaudio was still blocked by machine-id.

After digging I applied an older solution
`echo "enable-shm = no" >> ~/.config/pulse/client.conf"`
In addition I applied the same to daemon.conf:
`echo "enable-shm = no" >> ~/.config/pulse/daemon.conf"`

Now audio works along with machine-id everywhere.
