### ISSUE TITLE
Just updating firejail on Fedora 28

### ISSUE THREAD

**Issue by derba** [netblue30/firejail#2038]
I updated from Fedora 27 to 28 using Gnome Software. To avoid Firefox issues I pulled the latest firejail from git.

```
$ git pull
$ git clean -xdf
$ ./configure
$ make -j
$ sudo make install
$ sudo firecfg --clean
$ sudo firecfg
$ firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 13352, child pid 13353
Blacklist violations are logged to syslog
```
Firefox did not work. According to journalctl it crashed at chroot. But that is impossible, #1939 fixed that ages ago.

To my surprise I found /etc/firejail dir with rather old files. Well, I thought those files are in /usr/local/etc/firejail.

```
$ sudo rm -rf /etc/firejail
$ sudo make install
$ sudo firecfg
$ firefox
Error: Firejail configuration file /etc/firejail/firejail.config not found
```
No problem, just copy the profiles in the repo to /etc.
```
$ sudo mkdir /etc/firejail
$ sudo cp etc/* /etc/firejail/
$ firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Error: line 31 in /etc/firejail/firefox-common.profile is invalid
```
That happens to be `nodbus` line. I commented that out. And Firefox works.

**Comment by SkewedZeppelin** [comment]
You probably still have a mix of files, you might want to 

```
sudo make uninstall
sudo dnf remove firejail
sudo rm -rf /etc/firejail /run/firejail /usr/bin/{firejail,firemon,firecfg} /usr/lib/firejail
```

and then to reinstall, use the following instead of `make install`

```
./configure
make rpms
sudo dnf install firejail-0.9.55-1.x86_64.rpm
sudo firecfg
```

**Comment by derba** [comment]
Yes, I realized that I must have 2 firejail versions, as the `nodbus` issue could not occur otherwise. One firejail remained from an installed rpm.

```
$ ls -l `which firefox`
lrwxrwxrwx. 1 root root 17 Jun 21 09:43 /usr/local/bin/firefox -> /usr/bin/firejail
```

While the new firejail is at `/usr/local/bin/firejail`.

Thank you. I removed the old one.

**Comment by derba** [comment]
Thank you, that was it. Another firejail was present from an old rpm installation. I realized that `nodbus` issue could not occur otherwise. For some reason `firecfg --clean` did not remove the symlinks of the old installation, so they pointed to the old instance.
