### ISSUE TITLE
Cannot access profile file

### ISSUE THREAD

**Issue by dmitryvakulenko** [netblue30/firejail#2040]
I get this error message whet firejail try to read profile file in ~/.config/firejail. This is a full log
```bash
 % firejail --debug /opt/Telegram/Telegram
Autoselecting /usr/bin/zsh as shell
Building quoted command line: '/opt/Telegram/Telegram' 
Command name #Telegram#
Found Telegram profile in /home/n0dwis/.config/firejail directory
Reading profile /home/n0dwis/.config/firejail/Telegram.profile
Error: cannot access profile file
```

Profile file are exist and has correct permissions
```bash
 % ls -la /home/n0dwis/.config/firejail                 
total 24
drwxr-xr-x   2 n0dwis n0dwis 4096 июл 13 17:33 .
drwx------. 82 n0dwis n0dwis 4096 июл 13 18:25 ..
-rw-r--r--   1 n0dwis n0dwis  836 июл 13 17:32 slack.profile
-rw-r--r--   1 n0dwis n0dwis  763 июл 13 17:32 stride.profile
-rw-r--r--   1 n0dwis n0dwis  690 июл 13 17:32 Telegram.profile
-rw-r--r--   1 n0dwis n0dwis  653 июл 13 17:32 vivaldi.profile
```

Even more - this trouble happend only on my notebook not on PC! Firejail version (0.9.54), OS (Mint 19) and profile files are same. This began after I updated my Linux Mint 18.3 to 19.

How can I get more information about reasons of this trouble?

**Comment by chiraag-nataraj** [comment]
Can you post (or attach) your `Telegram.profile` here? I suspect it has something to do with an `include` within your profile.

**Comment by dmitryvakulenko** [comment]
I check my profile files - yes you right. Files **disable-mgmt.inc** and **disable-secret.inc** are absent in /etc/firejail.

**Comment by chiraag-nataraj** [comment]
There you go :slightly_smiling_face: They might be in `/usr/local/etc/firejail` if you compiled from the `git` version.

**Comment by dmitryvakulenko** [comment]
No. I installed it from .deb file and the package not contain this files.

**Comment by chiraag-nataraj** [comment]
Hmm, that's weird. Is this from the repositories? Which distro?

**Comment by dmitryvakulenko** [comment]
I downloaded it here https://sourceforge.net/projects/firejail/files/firejail/firejail_0.9.54_1_amd64.deb/download

**Comment by chiraag-nataraj** [comment]
Which distro are you using? Is `firejail` not in the repository?

**Comment by dmitryvakulenko** [comment]
I used Mint 19 (upgraded from 18.3) about week ago. Yes, firejail is in repository but version 0.9.52 and that package don't has this files too.
I think this files left on my PC from previous firejail installation from Mint 18.3.

**Comment by SkewedZeppelin** [comment]
@dmitryvakulenko can you try the following

```
firejail --profile=/etc/firejail/telegram.profile /opt/Telegram/Telegram
```

**Comment by chiraag-nataraj** [comment]
Oh. Right. `disable-mgmt.inc` and `disable-secret.inc` weren't split off from other includes until after 0.9.54, so you can't use those unless you build from git.

**Comment by dmitryvakulenko** [comment]
So I should just remove this files from my profiles, right?

**Comment by dmitryvakulenko** [comment]
@SkewedZeppelin, this command works. Bug is in my profile file.

**Comment by SkewedZeppelin** [comment]
@dmitryvakulenko yes, you should remove any profiles you have in .config/firejail that contain disable-mgmt or disable-secret as those were removed in 0.9.40 (?)

**Comment by dmitryvakulenko** [comment]
Thanks for help!!
