### ISSUE TITLE
Profile autodetection fails when path contains spaces

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#2045]
A Debian user [has reported](https://bugs.debian.org/903831) that firejail doesn't use the correct profile if the path contains spaces.
I was able to confirm that:
```
$ mkdir /tmp/nonexisting\ profile
$ cp /bin/ls /tmp/nonexisting\ profile/
$ firejail --debug /tmp/nonexisting\ profile/ls 
Autoselecting /bin/bash as shell
Building quoted command line: '/tmp/nonexisting profile/ls' 
Command name #nonexisting#
Attempting to find default.profile...
```
It tries to load the profile for the program "nonexisting" and falls back to the default profile.

**Comment by netblue30** [comment]
I'll try to fix it, thanks.
