### ISSUE TITLE
Thunderbird-Chromium Issue

### ISSUE THREAD

**Issue by eirenicon** [netblue30/firejail#2047]
Thunderbird hyperlinking to the default browser does not function correctly. [btw. I am running on the Testing release of manjaro (Linux)].  I receive the following error message:

> Failed to execute default web browser.
> Input/output error.

_I have created the following .local profile for Thunderbird:_

# Firejail profile for Thunderbird Customizations
> noblacklist ${HOME}/Dropbox/Thunderbird
> noblacklist ${HOME}/Desktop
> 
> whitelist ${HOME}/Dropbox/Thunderbird
> whitelist ${HOME}/Desktop

NOTE: everytime I open Thunderbird and attempt a link, it now requests I redefine my Default browser (Chromium).

Any ideas/ help are most appreciated.

**Comment by SkewedZeppelin** [comment]
See https://github.com/netblue30/firejail/issues/1770#issuecomment-364498100

**Comment by eirenicon** [comment]
In my case the problem was with a plugin/ add-on in both firefox and chromium. Once I removed **DuckDuckGo privacy essentials** from the troubled browser, the default browser function worked!

**Comment by chiraag-nataraj** [comment]
Cool! Going to close this then.
