### ISSUE TITLE
Verifying game cache integrity in Steam deletes game files

### ISSUE THREAD

**Issue by SilasLamb** [netblue30/firejail#205]
Disclaimer: New to Linux (Ubuntu) and new to Steam.

I had 4.8/5.5GB of CS:GO downloaded, exited Steam and started it with the Firejail Steam profile. The game finished downloading, I used "VERIFY INTEGRITY OF GAME CACHE..." and this said *all* files could not be verified/were corrupt, immediately deleted them and started re-downloading.

My bandwidth is <50kbps so if someone could test and verify this I'd appreciate it.

Thanks.

Edit: Here's the terminal log in case it helps - http://pastebin.com/raw/AR6gKbrL.

**Comment by SilasLamb** [comment]
Here's the terminal log in case it helps - http://pastebin.com/raw/AR6gKbrL.

**Comment by netblue30** [comment]
Give version 0.9.38 a trey. There have been quite a number of fixes. Thanks.
