### ISSUE TITLE
Android Studio Invalid Config Path

### ISSUE THREAD

**Issue by laserswift** [netblue30/firejail#2050]
Invalid Config Path: Config path '/home/user/.AndroidStudio3.1/config' is invalid.
If you have modified the 'idea.config.path' property please make sure it is correct,
otherwise please re-install the IDE.

Has anyone had this issue in Android Studio with firejail? It's googlable for regular Android Studio installs, but my regular Android Studio starts up fine, and the solutions that mention altering the idea.properties do not work in ending this error.

Could it have to do with the command to launch android studio being a path to studio.sh instead of the more common /usr/bin file? Or, I don't know what.. I'm new to all this.

Thanks.

**Comment by Fred-Barclay** [comment]
@laserswift what version of firejail are you running? (You can check with `firejail --version`).

Also, can you see if it works with `firejail --noprofile /path/to/AndriodStudio`?

Thanks!
Fred

**Comment by laserswift** [comment]
I'm on firejail version 0.9.54.

Wow, am I blind? It mentions in to try --noprofile in the damn output. Thanks.

I'm going to close this and just mess around until I get a more restrictive profile than --noprofile, until it works. Thanks again.

**Comment by Fred-Barclay** [comment]
Just a thought -- can you post how you're calling android studio, and the full terminal output when running it in firejail?

**Comment by laserswift** [comment]
Yea, I really am dumb. I have to explicitly point to the android.studio.profile like so: 

"$ firejail --profile=/etc/firejail/android-studio.profile /home/user/Android/android-studio/bin/studio.sh" 

Otherwise it uses the default.profile which probably doesn't give access to the .AndroidStudio(versionnumber) folder.

I guess I just thought it would automatically use that profile.

However, um, it says that line 35 [here](https://github.com/netblue30/firejail/blob/master/etc/android-studio.profile) is invalid, so I just deleted that line for now.

Thanks.

**Comment by chiraag-nataraj** [comment]
@laserswift That's because you're using firejail 0.9.54. `private-cache` was added in the current git version, so it's not in the a stable release yet.

**Comment by Fred-Barclay** [comment]
@laserswift I've added in a profile redirect so calling `firejail  /home/user/Android/android-studio/bin/studio.sh` should start it with the correct android studio profile, instead of the default, generic profile. Can you copy a83fb9bdf062e705525fa63b9bbd8b43999b4831 to /etc/firejail/studio.sh.profile and let me know if the above command works?

**Comment by laserswift** [comment]
Yep, it works. Thank you.
