### ISSUE TITLE
firejail --tracelog creates empty ld.so.preload file in systems etc folder

### ISSUE THREAD

**Issue by hvhaugwitz** [netblue30/firejail#206]
firejail --tracelog creates an empty ld.so.preload file in systems etc folder:
```
test@debian:~$ ls -l /etc/ld.so.preload
ls: cannot access /etc/ld.so.preload: No such file or directory
test@debian:~$ firejail --version
firejail version 0.9.36
test@debian:~$ firejail --tracelog bash
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 11910, child pid 11911
Blacklist violations are logged to syslog
Child process initialized
[test@debian ~]$ exit
exit

parent is shutting down, bye...
test@debian:~$ ls -l /etc/ld.so.preload
-rw-r--r-- 1 root root 0 Jan  2 06:00 /etc/ld.so.preload
test@debian:~$
```
Is this behaviour intended?

**Comment by netblue30** [comment]
--tracelog requires a special /etc/ld.so.preload file in the filesystem inside the sandbox. If an existing ld.so.preload is not found, Firejail creates an empty one. Inside the sandbox, Firejail will mount the real one on top of it.

**Comment by hvhaugwitz** [comment]
And the empty ld.so.preload file cannot be created temporally? It is a little bit weird that firejail creates permanent config files in /etc out of the blue.

**Comment by netblue30** [comment]
It is kind of ugly, but I don't have a solution in this moment. Cleaning up the file after the sandbox has closed is very difficult, there are some race conditions there.
