### ISSUE TITLE
[cosmetic] `--netfilter6=` and `restricted-network yes`

### ISSUE THREAD

**Issue by yumkam** [netblue30/firejail#2061]
When `restricted-network yes` (or similar compile-time option) is set, `--netfilter=` is rejected (`Error: --netfilter is only allowed for root`), but `--netfilter6=` is not. Fortunately, it is no-op in this case: only `--net=none` is allowed, and `--netfilter6=` is ignored when no bridges are configured (still, it would be better to be consistent, one way or other).

**Comment by startx2017** [comment]
Same problem for --netns and for all netfilter commands in profile files. I'm working on a fix. I intend to remomve --enable-network=restricted from configure.ac script, and clean up the code.

**Comment by startx2017** [comment]
the fix is in, thanks for the bug.
