### ISSUE TITLE
Bugs rpm package heikoada/firejail - Fedora 28

### ISSUE THREAD

**Issue by unixname** [netblue30/firejail#2064]
Hello dears!found a firejail bug
Not found as this amply show.
dnf copy enable heikoada/firejail
dnfinstall firejail
firejail --help
Warning: an existing sandbox was detected. /bin/bash will run without any additional sandboxing features
firejail --private --noprofile=/home/alex/sandbox-seccomp ----caps.drop=all gedit
Warning: an existing sandbox was detected. gedit will run without any additional sandboxing features
I run and get access beyond the specified --private=/home/alex/sandbox sandbox
firejail-version 0.9.52
dnf copy disable heikoada — firejail-disable repository
I delete firetail, after I collect it from the source code of firejail taken from GitHub everything works fine ./configure --prefix= / usr & & & make& & sudo make install-strip. Firewall version installed-version 0.9.55

**Comment by SkewedZeppelin** [comment]
Instead of using an outdated COPR repo or using `make install` I'd recommend the following
```
./configure
make rpms
sudo dnf install firejail-0.9.55-1.x86_64.rpm
sudo firecfg
```

**Comment by unixname** [comment]
Thank you for your help!

**Comment by chiraag-nataraj** [comment]
Seems like this was resolved?
