### ISSUE TITLE
Tor Browser cannot execute with "noroot" and "nogroups" profile

### ISSUE THREAD

**Issue by Joonho365Han** [netblue30/firejail#2066]
Recreating the issue:
- System: Arch Linux (no apparmor, no SELinux, no other sandboxing apps)
- Firejail Version: 0.9.54-1
- Tor Browser Version: 7.5.6-1
- Execute: /usr/bin/firejail --profile=/etc/firejail/tor-browser-en.profile /usr/bin/tor-browser-en
                              OR depending on the distro
                 /usr/bin/firejail --profile=/etc/firejail/tor-browser-en.profile /usr/bin/${YOUR_EXECUTABLE}
- Result: child process will exit without any warning or error messages:
>Reading profile /etc/firejail/tor-browser-en.profile
>Reading profile /etc/firejail/torbrowser-launcher.profile
>Reading profile /etc/firejail/torbrowser-launcher.local
>Reading profile /etc/firejail/disable-common.inc
>Reading profile /etc/firejail/disable-devel.inc
>Reading profile /etc/firejail/disable-interpreters.inc
>Reading profile /etc/firejail/disable-passwdmgr.inc
>Reading profile /etc/firejail/disable-programs.inc
>Reading profile /etc/firejail/whitelist-common.inc
>Reading profile /etc/firejail/whitelist-var-common.inc
>Parent pid 31605, child pid 31606
>Warning: skipping pki for private /etc
>Warning: skipping crypto-policies for private /etc
>Warning: skipping alsa for private /etc
>Private /etc installed in 31.82 ms
>97 programs installed in 61.01 ms
>Warning: cleaning all supplementary groups
>Warning: cleaning all supplementary groups
>Warning: /sbin directory link was not blacklisted
>Warning: /usr/sbin directory link was not blacklisted
>Warning: cleaning all supplementary groups
>Blacklist violations are logged to syslog
>Child process initialized in 141.65 ms
>
>Parent is shutting down, bye...

My  torbrowser-launcher.local:

>#,Firejail,profile,for,torbrowser-launcher
>
>whitelist ${HOME}/.tor-browser-en
>whitelist ${HOME}/Downloads
>whitelist ${HOME}/.uim.d
>
>private-bin /usr/bin/tor-browser-en
>private-etc machine-id,passwd

My exec command:
>/usr/bin/firejail --profile=/etc/firejail/tor-browser-en.profile /usr/bin/tor-browser-en

Considering this happened when I updated Firejail and not Tor Browser, I assume it has something to do with how Firejail changed implementation of "nogroups" and "noroot."

**Comment by chiraag-nataraj** [comment]
I will investigate this and report back.

**Comment by chiraag-nataraj** [comment]
Which version did you upgrade from?

**Comment by Joonho365Han** [comment]
It was upgraded from 0.9.52-1.

**Comment by chiraag-nataraj** [comment]
Okay, thanks.

**Comment by SkewedZeppelin** [comment]
@Joonho365Han are you using the proprietary NVIDIA driver?

**Comment by Joonho365Han** [comment]
@SkewedZeppelin No I'm using Intel HD Graphics 520

**Comment by chiraag-nataraj** [comment]
It's most likely apparmor. Do you have an apparmor profile for torbrowser?

**Comment by Joonho365Han** [comment]
No. I do not use a custom local profile for Tor browser and the profile that came with firejail in this version does not enable apparmor.

**Comment by chiraag-nataraj** [comment]
I'm not talking about the `apparmor` option in `firejail`, which turns on _firejail_'s apparmor profile. I'm talking about a profile for the tor browser that might have been shipped with the tor browser. Even if you don't turn on `apparmor` in `firejail`, if there's a matching profile that's been enabled (and some distros enable apparmor profiles by default), then that will still cause problems. One way you can see this is by looking in the system log (e.g. `journalctl`) to see if you get apparmor messages.

**Comment by Joonho365Han** [comment]
I believe only the TBB (Tor browser bundle) in Tails has AppArmor enabled by default. It also shouldn't be since Apparmor requires kernel modules and parameters to load and I do not have them enabled.

**Comment by Vincent43** [comment]
@Joonho365Han you didn't write what system you use. AppArmor is enabled by default in Ubuntu, Debian (testing, unstable), and openSUSE.

BTW: If you have AppArmor profile for your app it's possibly better to disable firejail rather than AppArmor.

**Comment by Joonho365Han** [comment]
@Vincent43 Right. I realized it was necessary after chiraag just mentioned it. I'm using Arch and I don't have any MAC like Apparmor or SELinux installed that messes with blacklist/whitelist permissions.

**Comment by chiraag-nataraj** [comment]
@Joonho365Han Huh, that's really weird then. Do you get anything showing up in your audit logs?

**Comment by Joonho365Han** [comment]
@chiraag-nataraj No. Nothing even on system journal.

**Comment by Joonho365Han** [comment]
@Vincent43 That's actually not the official firejail package for Arch and it's not maintained since 2017. The official one I'm using is https://www.archlinux.org/packages/community/x86_64/firejail/ and it's up to date with the repo.

**Comment by Vincent43** [comment]
If you are new to Archlinux please read: https://wiki.archlinux.org/index.php/Arch_User_Repository

The package I linked will install the latest git version form github which is [157 commits ahead](https://github.com/netblue30/firejail/releases/tag/0.9.54) of what you currently use. For `*-git` packages the "Last Updated" date doesn't matter as they automatically fetch new commits from git.

**Comment by Joonho365Han** [comment]
@Vincent43 Really? Good to know. I just tried it with the package you linked but it's still producing the same issue.

**Comment by chiraag-nataraj** [comment]
@Joonho365Han How did you install the tor browser bundle?

**Comment by Joonho365Han** [comment]
Via the AUR.

**Comment by Fred-Barclay** [comment]
@Joonho365Han Can you post the commands and terminal output of however you start the TBB inside firejail?
I'm on Arch, and using TBB from the tor website (not the AUR) and using `firejail --profile=/etc/firejail/start-tor-browser.profile ./start-tor-browser.desktop` works fine for me.

Cheers!

**Comment by Joonho365Han** [comment]
@Fred-Barclay I've updated the post with the requested info.

**Comment by chiraag-nataraj** [comment]
@Joonho365Han The profile installed with firejail (from AUR) works fine in my archlinux VM with the tor-browser-en from AUR.

**Comment by chiraag-nataraj** [comment]
@Joonho365Han Have you changed any defaults (with respect to "vanilla" Arch) that might be affecting this?

**Comment by Joonho365Han** [comment]
What do you mean by defaults?

**Comment by chiraag-nataraj** [comment]
@Joonho365Han I'm not really sure, since I only set up an Arch VM to test this (I don't use it on a daily basis). I guess what I mean is do you think anything else about your setup is relevant? Because based on the info you've given us, I was unable to reproduce the issue on my Arch VM.

**Comment by Joonho365Han** [comment]
@chiraag-nataraj Not sure... Does firejail create a custom user to execute in the sandbox?

**Comment by chiraag-nataraj** [comment]
@Joonho365Han Nope, at least not by default.

**Comment by anteg** [comment]
Anyone solved this little problem? =) 
I get 4 Warning: cleaning all supplementary groups when running firefox. The warnings disappear when I comment out 'noroot' from the firejail-common.profille. I have both stopped and disabled apparmor just to see so that it wasnt it creating these.

**Comment by Joonho365Han** [comment]
@anteg So I don't remember exactly when but I updated my entire system, which resolved the issue. I don't remember what version it started to work again. Try out the latest one?
