### ISSUE TITLE
[bug] Whitelisting a file leads to inability to write to it

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#2071]
Currently running firejail 0.9.55. When I whitelist a file (not a directory), I get errors like "Couldn't write to file" (when I whitelisted `~/.config/akregatorrc`). I got similar errors from Google Earth [Pro] as well. I'm going to try to investigate, but just wanted to put this on the radar.

**Comment by chiraag-nataraj** [comment]
Apparently the program gets an `EBUSY` when it tries to rename a temporary file (which it actually writes to) to the actual configuration file. Is there any way to deal with this besides just whitelisting the entire `.config` directory?

**Comment by smitsohu** [comment]
Is this possibly the same as #1793 and #1355?

**Comment by chiraag-nataraj** [comment]
Yes, I think so. This seems to be an issue with certain programs which write a temp file before moving it to the actual location.

**Comment by chiraag-nataraj** [comment]
Closing since this seems to be a dup of some of the others.
