### ISSUE TITLE
Nvida drivers using firejail

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2072]
If I installed Nvidia drivers through firejail and I completly block Nvidia from having access to any of my files and other stuff, would Nvidia work still and would it be impossible for Nvidia to collect any additional information about my computer?

**Comment by chiraag-nataraj** [comment]
It wouldn't be able to send anything to Nvidia during the install, but that says nothing about whether the modules send anything back when they're loaded or running. And no, you can't use firejail to sandbox kernel modules.

That being said, I would just use your distribution packages to install the driver — it's generally much less of a headache.

**Comment by Raj2032** [comment]
" distribution packages to install the driver " What is that exactly?

**Comment by chiraag-nataraj** [comment]
Most distributions have a way to install the Nvidia driver through their package system. For example, Debian has the `nvidia-driver` package. Other distributions have similar ones.

**Comment by Raj2032** [comment]
And how would I know a kernal module won't invade a person's privacy,
especially since this is closed source?

**Comment by chiraag-nataraj** [comment]
You don't know that. But firejail won't protect you against that because it's meant to sandbox _programs_. All of the kernel-based systems it uses are meant to sandbox userspace programs. They don't work on kernel modules.

**Comment by chiraag-nataraj** [comment]
The _only_ thing you can protect in this case is the installation method. And in that sense, I trust the distribution's package manager more than some binary installer.

**Comment by chiraag-nataraj** [comment]
No. What I'm saying is that sandboxing kernel modules is _entirely_ out of the scope of firejail because the kernel technologies it uses (seccomp-bpf filters, capabilities, namespaces) are all designed to sandbox programs, not modules.

**Comment by Raj2032** [comment]
Is there a way to sandbox kernel modules?

**Comment by chiraag-nataraj** [comment]
Nope, not that I'm aware of.

**Comment by Raj2032** [comment]
Oh
