### ISSUE TITLE
Weechat /exec fails with default weechat.profile

### ISSUE THREAD

**Issue by fld** [netblue30/firejail#2075]
The /exec command in Weechat does not function properly with default weechat.profile.

Tested on debian 9.5 64bit / Linux 4.17.12 / Weechat 2.2 / Firejail 0.9.54:

```
% tmpwc="$HOME/.dbgweechat"
% mkdir "$tmpwc"
% firejail --noblacklist="$tmpwc" weechat -d "$tmpwc" -r '/exec -n ls'
```

Weechat shows:
```
1 | Error with command 'ls'
  | exec: end of command 0 ("ls"), return code: 1
``` 
It seems to "Error" with any command I threw at it

To get it working, I modified /etc/firejail/weechat.profile with:
#nonewprivs
#protocol unix,inet,inet6
#seccomp
Uncommenting any of those makes /exec's fail

**Comment by chiraag-nataraj** [comment]
I don't think we should allow a _chat client_ to execute random binaries by default. The predicates you highlight are eminently useful and prevent classes of vulnerabilities and should be enabled by default (unless they hamper the _main_ function of `weechat`, which is...chatting). You are, of course, more than welcome to disable the "problematic" things in the profile.

**Comment by chiraag-nataraj** [comment]
Also, you can use `/etc/firejail/weechat.local` with:
```
ignore nonewprivs
ignore protocol
ignore seccomp
```
to get the desired effect without modifying the files that come with `firejail` (which will be overwritten on update).
