### ISSUE TITLE
Discord won't launch

### ISSUE THREAD

**Issue by chewblacka** [netblue30/firejail#2077]
When running discord in firejail I get 
```
Running 'discord' command through /bin/zsh
execvp argument 0: /bin/zsh
execvp argument 1: -c
execvp argument 2: 'discord'
execvp: No such file or directory
```
If I run:
`execvp /bin/zsh -c discord`  manually I get the same result.

Any ideas how to fix? Many thanks!

**Comment by chewblacka** [comment]
Many thanks.
I commented out the `private-bin` line in `discord-common.profile` but it still does the same thing.

**Comment by chewblacka** [comment]
I think I misunderstood your comment. 
I didn't try appending `zsh` because the first bit failed. But now I did append `.zsh` and it starts up! Or at least begins to start-up, but loops as it tries to update itself but can't access the internet. Any ideas how I can fix this? I've commented out `netfilter` but no difference. Many thanks!

**Comment by chewblacka** [comment]
Ok I managed to figure out that if I comment out the `#private-etc` line in `/etc/firejail/discord-common.profile` then it runs fine. The only slight issue is that the tray icon (where it minimizes to) is invisible.

**Comment by SkewedZeppelin** [comment]
I'm not too sure about the tray issue, but if you replace `private-etc` with the following does it fix networking?

```
private-etc machine-id,localtime,ld.so.cache,ca-certificates,fonts,host.conf,hostname,hosts,resolv.conf,ssl,pki,crypto-policies,xdg
```

**Comment by chewblacka** [comment]
Thanks @chiraag-nataraj ! That fixed it the icon issue!
p.s. I use 2 distros. All the above discussion refered to Ubuntu, where discord works perfectly now.
But my other distro is OpenSUSE and I'm having difficulty getting discord to even start.

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this, since it seems people having issues with OpenSUSE more generally (that discussion should go in the issue @SkewedZeppelin referenced above).

**Comment by ColonelThirtyTwo** [comment]
@chiraag-nataraj I'm having the same issue in Arch Linux with the discord package in AUR
