### ISSUE TITLE
Spotify, Arch: ERROR: ld.so: object 'libcurl.so.3' from LD_PRELOAD

### ISSUE THREAD

**Issue by brakenow** [netblue30/firejail#2080]
A blank window opens, and Xorg freezes. Also with the git version.

**Comment by Vincent43** [comment]
What is your graphic card? Can you try with `firejail --noblacklist=/sys spotify` ?

**Comment by brakenow** [comment]
Thanks. Will try it when I wake up.

**Comment by brakenow** [comment]
It worked! But I still get:

ERROR: ld.so: object 'libcurl.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/usr/share/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /usr/share/spo
ERROR: ld.so: object 'libcurl.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/usr/share/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /usr/share/spo
ERROR: ld.so: object 'libcurl.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0814/084452.829167:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization

Thank you! :-D

**Comment by Vincent43** [comment]
This is fixed in master with https://github.com/netblue30/firejail/commit/516f8d05613931fe866dd8166af9574e6c456309
