### ISSUE TITLE
AppArmor not working in OpenSuse

### ISSUE THREAD

**Issue by chewblacka** [netblue30/firejail#2084]
AppArmor doesn't seem to work with okular in firejail (OpenSUSE Leap 15). 
I get the following warning:

```
Warning: Cannot confine the application using AppArmor.
Maybe firejail-default AppArmor profile is not loaded into the kernel.
As root, run "aa-enforce firejail-default" to load it.
```
But then when I run "aa-enforce firejail-default" I get:

```
Setting /etc/apparmor.d/firejail-default to enforce mode.
ERROR: Path doesn't start with / or variable: firejail-default
```
Any ideas?

**Comment by chiraag-nataraj** [comment]
Try restarting - I've had this issue after upgrading apparmor.

**Comment by chewblacka** [comment]
Restarted. Still the same sadly.

**Comment by chiraag-nataraj** [comment]
Hmm, okay. Maybe someone else who uses OpenSUSE can chime in - I'm on Debian.

**Comment by chewblacka** [comment]
Oops, I've just realized it's not just okular but everything I run in firejail gives that warning about apparmor (I've changed thread title accordingly).

**Comment by chewblacka** [comment]
Weird - I rebooted (after nothing had changed), and it started working!

**Comment by smitsohu** [comment]
For the record: You have probably run into an AppArmor regression, compare this report on the bugtracker https://bugs.launchpad.net/apparmor/+bug/1775591

Guess this has been fixed in the package and rebooting was necessary to finish the update.
