### ISSUE TITLE
Qutebrowser (qtwebengine) needs llvm whitelist

### ISSUE THREAD

**Issue by q3cpma** [netblue30/firejail#2087]
Hello,

Same problem as in https://github.com/netblue30/firejail/issues/1680 (I was this bug's author), the same whitelist (/usr/lib/llvm) did the trick.

Using firejail 0.9.64 on Gentoo.

**Comment by Vincent43** [comment]
Fixed with https://github.com/netblue30/firejail/commit/2ec445ac8dbdd2e6a63e7b3aedd0c0c8fc6b1b45 , thax for reporting.

**Comment by q3cpma** [comment]
This may be a good idea to test other qtwebengine consumers.
