### ISSUE TITLE
Allow system users to use firejail if listed in firejail.users

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#2088]
Continuing where #1964 left off, is there any reason we don't let system users use `firejail` _even if_ they are listed in `/etc/firejail/firejail.users`?

**Comment by netblue30** [comment]
You are right, we should let them - maybe not user nobody, but any other system user.

**Comment by netblue30** [comment]
All set: https://github.com/netblue30/firejail/commit/95deecf1f3128c2fd6984c6b6f4a8f540441188b
