### ISSUE TITLE
Have firecfg install to ${HOME}/bin instead of /usr/local/bin?

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#2089]
If we install to `${HOME}/bin`, we can solve the issues detailed in #1902 and #667.

**Comment by Vincent43** [comment]
`${HOME}/bin` isn't in `PATH` by default on most systems. Moreover prepending it in `PATH` is dangerous as it allows for overwriting i.e. `sudo`, `mount` with something malicious.

**Comment by chiraag-nataraj** [comment]
@Vincent43 Shit. Yeah, you're right. Is there anywhere else we can install it that is per-user?

**Comment by reinerh** [comment]
you could let the user decide where he wants to have them installed (so that he could for example run: `firecfg --bindir ~/.bin`).

**Comment by netblue30** [comment]
> you could let the user decide where he wants to have them installed (so that he could for example run: firecfg --bindir ~/.bin).

I guess that's the best way to go.

**Comment by netblue30** [comment]
all set: https://github.com/netblue30/firejail/commit/fc7a9505c56192b5fc0ca62eb51fa7f0d8b1cef8
