### ISSUE TITLE
A simple tool for profile/policies creation

### ISSUE THREAD

**Issue by avilum** [netblue30/firejail#2095]
I couldn't find a simple tool that defines the syscalls, permissions of a program, etc. 
I created this simple script, based on strace and grep, that get's a list of all the unique syscalls of a binary, on the run.
This way, one can whitelist some flows of a program easily, without disassembling.
I'd be happy to create something bigger then that, a solution for nsjail+firejail policies definitions.

https://github.com/avilum/syscalls

**Comment by chiraag-nataraj** [comment]
@netblue30 I was thinking we could just put a note in the README or something linking to this repo?
