### ISSUE TITLE
Spotify: D-Bus functionality

### ISSUE THREAD

**Issue by cmays90** [netblue30/firejail#2098]
Spotify implements the MPRIS2 interface, which means it needs D-Bus to show pops (such as when a new song starts playing) and for keyboard control of songs (play/pause, skip, etc).

[The ArchWiki has a section written about Spotify's MPRIS2 interface.](https://wiki.archlinux.org/index.php/spotify#MPRIS)

On that note, is it possible to provide a local file that overrides a "noexec" or a "nodbus" command?

**Comment by SkewedZeppelin** [comment]
`echo "ignore nodbus" | sudo tee /etc/firejail/spotify.local`
