### ISSUE TITLE
Firejail breaks evince printing

### ISSUE THREAD

**Issue by matu3ba** [netblue30/firejail#2101]
Ubuntu 18.04.1 LTS
firejail version 0.9.56~rc1
GNOME-Dokumentenbetrachter 3.28.2

`firejail --noprofile evince` does not work as well,
but `sudo firecfg --clean` makes evince possible to print again.

To that regard uncommenting `nodbus` makes no difference (for me).
From the issue #1843 or commit 7a37dc31ab907d55eb88f2fa259f37046952a0c5 only
`-# blacklist /run/user/*/bus` was removed and 
`+# nodbus` added.
Did anybody have issues or can reason about why dbus was not removed in the first place?

**Comment by SkewedZeppelin** [comment]
Can you clarify?
Can you run each of the following and confirm whether you can print on not?

```
firejail /usr/bin/evince
firejail --noprofile /usr/bin/evince
sudo firecfg && sudo -k && evince
```

**Comment by matu3ba** [comment]
The printing dialog opens, however no installed and connected printer device is found.
Running neither of the commands did show up the according printer device.

**Comment by matu3ba** [comment]
Do the following messages help?
GLib-GIO-CRITICAL **: 23:49:32.556: g_dbus_proxy_new_sync: assertion G_IS_DBUS_CONNECTION (connection)' failed
** (evince:161): WARNING **: Connection failed: No authorization
** (evince:161): WARNING **:  Couldn't connect to D-Bus system bus, Connection failed: No authorization

**Comment by Vincent43** [comment]
Is evince confined by AppArmor? You may check with `sudo aa-status`.

**Comment by matu3ba** [comment]
@Vincent43 Thanks alot.
Curiously evince with printing also works with the option `nodbus` enabled (so dbus disabled).
