### ISSUE TITLE
Windows apps installed with Proton don't work (sound issue) [but do work with native Wine]

### ISSUE THREAD

**Issue by alxpettit** [netblue30/firejail#2103]
I am trying to get Steam to work properly under Wine with the new [Proton](https://github.com/ValveSoftware/Proton/). As a test subject, I have Crayon Physics Deluxe. Its audio doesn't work when I run my Steam instance in Firejail.

Here are my [wine.profile](https://gist.github.com/alxpettit/3e00e6d764f18f44fc7498db76d56085) and [steam.profile](https://gist.github.com/alxpettit/2db0fcd3c2de7815a88a27c8b91258ce) respectively.

The especially odd thing about this is that if I try to run Crayon Physics Deluxe directly by doing `firejail wine [long stupid path]/launcher.exe`, audio works fine.

**Comment by Vincent43** [comment]
Try disabling options which are present in steam.profile but not in wine.profile to find the culprit. It may be private-etc, private-dev or nogroups (which is available in both but maybe steam works differently).

**Comment by alxpettit** [comment]
I tweaked `steam.profile` [to also work with wine](https://gist.github.com/alxpettit/137b0bbba6d4dbd8d58d062e776371d0), and ran `firejail --profile=/etc/firejail/steam.profile wine ./launcher.exe`. I am now using steam.profile for both the wine instance and steam. Audio works in wine, but not in steam.

**Comment by alxpettit** [comment]
Steam + Firejail has working sound in other applications, and Steam alone has working sound in all applications,  including Crayon Physics. I'll go ahead and run an strace on to confirm Crayon Physics is being executed in the same way as I am via the shell. Will report back tomorrow! Unless I forget because I'm a twat.

**Comment by SkewedZeppelin** [comment]
@alxpettit before you go stracing, there is another report of Crayon Physics having no sound on this sheet
https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/htmlview

**Comment by alxpettit** [comment]
Ah, sorry for no updates on this issue. I briefly looked at that and then forgot about it. I'm really distracted nowadays -- I'll do more diagnostics and update you.

**Comment by chiraag-nataraj** [comment]
Hey @alxpettit! Did you ever get around to doing more diagnostics?

**Comment by alxpettit** [comment]
@chiraag-nataraj Oh, hies! Unfortunately, I've been distracted with like 30 other projects  (and sadly, this number is not an exaggeration), but the sound is still not working... I just need to know how the entry points are organized... unfortunately, Steam seems to have its shit compiled right into the program launchers for most of this stuff and it's a pretty big pain to reverse engineer. But this notification has prompted me to start on this again! Hopefully I'll make some progress before I forget.

**Comment by chiraag-nataraj** [comment]
@alxpettit No worries! When you're able to test, report back and we can figure out what's going on :)

**Comment by alxpettit** [comment]
@alxpettit Okay, FINALLY ran `launcher.exe`, and the sound is actually working (and yes, did confirm that it's using the same steam profile I was using before). Now I just need to figure out how Steam is launching it differently.

**Comment by alxpettit** [comment]
I should note, I have virtually no knowledge of Proton internals or anything else, so this is going to be pretty difficult to figure out. If you have any ideas, let me know!

**Comment by alxpettit** [comment]
Aaand here's the process tree.

![clusterfuck](https://user-images.githubusercontent.com/28266167/46387957-78921100-c697-11e8-867c-80ad32ef04b9.png)

**Comment by rusty-snake** [comment]
Any progress here?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
