### ISSUE TITLE
Tor Browser fails with curernt tor profile

### ISSUE THREAD

**Issue by t4777sd** [netblue30/firejail#2108]
Tor has updated to quantum. As a result, it suffers the same issues that Firefox suffered when it moved to quantum. It needs the same fixes firefox needed namely:

1) Comment out tracelog

2) Change seccomp to: seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice

**Comment by SkewedZeppelin** [comment]
Already fixed in defb5a48918c9fda82ac9bcf5c8a301e5f60da23
