### ISSUE TITLE
Firefox and native messaging

### ISSUE THREAD

**Issue by alkim0** [netblue30/firejail#2109]
Hi, somewhat recently, firefox started allowing [native apps](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging). However, this requires that another executable be allowed to run in the firefox jail. I'm not quite sure how to do this.

Specifically, I'm trying to use the native app for [tridactyl](https://github.com/tridactyl/tridactyl) which installs a python script to `$HOME/.local/share/tridactyl/native_main.py`. Firefox needs to be able to execute this python script (like a shell script, and not as an argument to the interpreter).

I use firejail with a private directory for firefox: `firejail --private=~/firefox-jail`, and I made sure the python script is installed to the private directory, and I've enabled the `firefox-common-addons.profile` to allow python. However, I'm continuing to get `permission denied` errors. Any suggestions?

**Comment by chiraag-nataraj** [comment]
@alkim0 Did @Vincent43's suggestion work?

**Comment by petRUShka** [comment]
@alkim0, could you please provide whole configuration changes for native to work?

I've added python and have disabled `noexec $HOME` but it doesn't work...

```
noblacklist ${PATH}/python3.7*
noblacklist /usr/lib/python3.7*
```

**Comment by Vincent43** [comment]
@petRUShka you would have to add `noexec` to all dirs except one which isn't much scalable.
