### ISSUE TITLE
Tor Browser stopped working with firejail after a major update

### ISSUE THREAD

**Issue by somospocos** [netblue30/firejail#2110]
I am using firejail-0.9.54 on Slackware64 Linux-14.2 and today Tor Browser updated itself from version 7.5.6 to version 8.0. After this Tor Browser doesn't work anymore when launched through firejail. Once the main window starts, it displays the message:

    Gah. Your tab just crashed.

Same happens for any new opened tab. It works fine without firejail.

**Comment by smitsohu** [comment]
Hi @somospocos, we believe this is already fixed for upcoming 0.9.56.

See defb5a48918c9fda82ac9bcf5c8a301e5f60da23 and 736216cacfe6a818b1ea0255f474089a8fa2f394

General question: Should this go to etc-fixes?

**Comment by TNTBOMBOM** [comment]
This has been reported against TorProject and FF. because it effects both of them and tested by me:

FF 60: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1488078

TBB 8.0:

https://trac.torproject.org/projects/tor/ticket/27407#ticket

**Comment by SkewedZeppelin** [comment]
@TNTBOMBOM 
This is not something that upstream Mozilla can/will fix, this is purely an issue with our profiles.

This issue that has been fixed since 0.9.54 for Firefox and derivatives
and is fixed for Tor Browser in master (future 0.9.56).

What version of Firejail are you running?

**Comment by TNTBOMBOM** [comment]
0.9.44.8 from debian stretch stable repo. if have been fixing that why dont u push ur changed to Debian Repo ??

**Comment by SkewedZeppelin** [comment]
@TNTBOMBOM 0.9.54 is available via stretch-backports

**Comment by TNTBOMBOM** [comment]
@SkewedZeppelin saw that , still bad if its a stable version then its better to be pushed for the stable repo.

**Comment by Vincent43** [comment]
That's not how Debian stable works. They take the last stable firejail version at the point of Debian release and stick with it forever. If you want to have firejail gradually updated to latest version then use backports, testing, unstable or different distro.

**Comment by TNTBOMBOM** [comment]
@SkewedZeppelin @Vincent43 thats great it worked fine with FF , but sadly it break TBB. any idea how to overcome that?

**Comment by Vincent43** [comment]
Fixes for tor browser aren't part of 0.9.54, they will be in 0.9.56. For now you may copy profiles manually:
https://github.com/netblue30/firejail/blob/master/etc/start-tor-browser.profile
https://github.com/netblue30/firejail/blob/master/etc/torbrowser-launcher.profile

**Comment by HundyK** [comment]
Is the Tor fix part of 0.9.56~rc1? I am running into the same problem with the tabs crashing on startup using 0.9.56~rc1.

**Comment by SkewedZeppelin** [comment]
@HundyK the fix for TBB is not in 0.9.56rc1, only master (future 0.9.56 release).

**Comment by chiraag-nataraj** [comment]
Which has now been released! Closing this for now, but please feel free to reopen if you still have this issue after upgrading.

**Comment by TNTBOMBOM** [comment]
after adding profiles to /etc/firejail/torbrowser-launcher as copy/paste from this link: 
https://github.com/netblue30/firejail/blob/master/etc/torbrowser-launcher.profile

result after that, by running `firejail torbrowser-laucher` will give: 

```
user@debian:~$ firejail torbrowser-launcher 
Reading profile /etc/firejail/torbrowser-launcher.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Error: cannot access profile file
user@debian:~$ 
```

**Comment by Fred-Barclay** [comment]
@TNTBOMBOM What version of firejail are you using?
Can you also please run the following and paste the output back here?
`firejail --debug torbrowser-launcher`

Thanks!

**Comment by TNTBOMBOM** [comment]
@Fred-Barclay 

Big Thanks!!!

**Comment by Zypherspace** [comment]
Same problem here as TNTBOMBOM 

```
user@debian:~$ firejail torbrowser-launcher 
Reading profile /etc/firejail/torbrowser-launcher.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
**Error: cannot access profile file**
```

Raw contents of [https://github.com/netblue30/firejail/blob/master/etc/torbrowser-launcher.profile](url) were copied, no file permissions changed. Tried removing the include /etc/firejail/disable-xdg.inc as suggested, same error.

Running latest master from git.

```
firejail --debug torbrowser-launcher
Autoselecting /bin/bash as shell
Building quoted command line: 'torbrowser-launcher' 
Command name #torbrowser-launcher#
Found torbrowser-launcher profile in /usr/local/etc/firejail directory
Reading profile /usr/local/etc/firejail/torbrowser-launcher.profile
Error: cannot access profile file
```

**Comment by Vincent43** [comment]
What system you using?

**Comment by Zypherspace** [comment]
Fedora 29 Cinnamon. It is working on a fresh install of Fed 29 Plasma without any changes to profile. 
I've reinstalled Tor-Browser. TB runs correctly outside Firejail.

**Comment by SkewedZeppelin** [comment]
@Zypherspace please see https://github.com/netblue30/firejail/issues/2038#issuecomment-405096879

**Comment by Zypherspace** [comment]
I tried the full scrub of firejail as detailed in #2038. I followed with a full recursive search and deleted any firejail remnants before reinstalling. Reinstalled with make rpms. Unfortunately I still see the `Gah. Your tab just crashed.` code on Tor-browser. Fedora has been updated several versions on the machine it's got a lot of ragtag symlinks, I'll reinstall a fresh release soon.

**Comment by Futureknows** [comment]
Commenting out seccomp fixed it for me.
