### ISSUE TITLE
firejail AppArmor profile doesn't work

### ISSUE THREAD

**Issue by hardenedfly** [netblue30/firejail#2116]
Here's what happens when I run `sudo aa-enforce firejail-default`:

```
Setting /etc/apparmor.d/firejail-default to enforce mode.

ERROR: Path doesn't start with / or variable: firejail-default

```
I compiled firejail this way:
```

./configure --prefix=/usr --enable-apparmor

make

sudo make install-strip

```

I'm using Arch Linux with a kernel that has AppArmor support enabled, I tested AppArmor with other profiles and it worked properly.

My kernel: `4.18.7.a-1-hardened`

My AppArmor version:`apparmor 2.13.0-4`

**Comment by chiraag-nataraj** [comment]
Try restarting. I've had this issue when apparmor was updated.

**Comment by hardenedfly** [comment]
I did that, The issue remains.

**Comment by hardenedfly** [comment]
I just checked. Regardless of the error, the profile appears in when I run `sudo aa-status` after reloading the `apparmor` service. Does this mean that the profile is loaded but broken or something like that? I mean it still shown the error when running `sudo aa-enforce firejail-default`

**Comment by chiraag-nataraj** [comment]
Ohh. Right, so if the profile is already loaded, I think it gives that error. You'd have to use `sudo apparmor_parser -r /etc/apparmor.d/firejail-default` or something like that to reload a profile that's already loaded.

**Comment by Vincent43** [comment]
`firejail-default` apparmor profile is enforced by default on `apparmor.service` start but it's loaded only on demand by firejail, you don't load it manually.
