### ISSUE TITLE
Firejail - Apparmor problem with missing slash

### ISSUE THREAD

**Issue by wofwofwof** [netblue30/firejail#2118]
Hello,

not sure whats the reason for this problem. I've created an apparmor profile for thunderbird and it runs fine without firejail.

In combination with firejail I get following messages:

`Sep 21 10:43:49 test12 kernel: [377872.848619] audit: type=1400 audit(1537519429.838:168): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib64/thunderbird/thunderbird" name="dev/dri/card0" pid=29762 comm="GLXVsyncThread" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

In the apparmor profile I have following entry:
>   /dev/dri/**  r,

For firejail I use an empty profile. 
The interesting thing is the missing _/_ for _dev/dri/card0_ not sure if this is the reason, still.

cheers

wof

**Comment by Vincent43** [comment]
You need to add `flags=(attach_disconnected)` to your thunderbird apparmor profile, see https://github.com/netblue30/firejail/blob/master/etc/firejail-default#L13 as an example. That being said using both standalone AppArmor confinement with firejail is bad idea as they will block each other as you can see. Choose one.

**Comment by wofwofwof** [comment]
Thanks a lot for the clarification.

cheers
wof
