### ISSUE TITLE
Not really an issue - just letting netblue30 know that Skype-pulseaudio issue is resolved in latest release

### ISSUE THREAD

**Issue by lepasserby** [netblue30/firejail#212]
Hi!
I'm that passerby person with skype and pulseaudio shared-memory issues

I've tested and it's fixed (before testing the new firejail version, I enabled shared memory in pulse and ensured that I'm getting a crash with old firejail version)

Skype performance greatly improved as result.
Thanks a lot :+1:

**Comment by netblue30** [comment]
Thanks, there were quit a lot of PulseAudio fixes in the last release.
