### ISSUE TITLE
nonewprivs exceptions?

### ISSUE THREAD

**Issue by b-misc** [netblue30/firejail#2120]
Is it possible to allow specified exceptions from nonewprivs ("friend")?

What I want to achieve is the following:
Firefox runs in its sandbox. Firefox is allowed to start pass by using the passff add-on. Pass needs access to both .gnupg and .password-store. By adding a pass profile and adding an exception for firefox' nonewprivs, firefox could invoke pass with the pass firejail profile, while all other subprocesses are still restricted by the firefox profile and I wouldn't have to allow firefox access to .gnupg and .password-store.

Would this be a security concern?

Are there better ways to achieve this?

**Comment by Vincent43** [comment]
This has nothing to do with [--nonewprivs](https://github.com/netblue30/firejail/blob/master/src/man/firejail.txt#L1178) option. Also the only possibility to load app with different firejail profile from an existent profile is through dbus escape but I don't know if it's possible in this scenario.

**Comment by b-misc** [comment]
Other idea: use a kind of a pasff, passff-host-daemon and a socket.

Should that work?
I think of splitting passff-host in two binaries, the first ("passff-host-new") invoked by pass, running with firefox' rights. It cannot access .gnupg and .password-store, but is allowed to access a socket.
The second ("passff-host-d") gets started either at login time or whenever firefox is started. It has its own firejail profile and listens for connections by passff-host-new via the socket.

Do you think this will work?
Are there any negative security implications?

(Also posted at https://github.com/passff/passff)

**Comment by chiraag-nataraj** [comment]
@b-misc Yes, a daemon/client model should work. For example, mpd works like this and I can give the client access to the specific socket while sandboxing the daemon separately.

**Comment by Vincent43** [comment]
The problem would be how to restrict access to that socket to `passff-host-new` only and prevent access from everything else.

**Comment by chiraag-nataraj** [comment]
@Vincent43 Right, but if it's a regular socket on the filesystem, that restriction is trivial. Abstract sockets are harder, of course.

**Comment by chiraag-nataraj** [comment]
I don't think we can do much on this end, so I'm going to close this. The easiest way to fix this is to pester the `passff` people to implement a daemon/client model. Until then, you're unfortunately going to have to either allow `firefox` to access `.password-store` (and everything else necessary) or run `pass` externally (what I currently do).
