### ISSUE TITLE
Jailing system services

### ISSUE THREAD

**Issue by Artefact2** [netblue30/firejail#2128]
It seems firejail will not work with system users, even if they are explicitely added to `/etc/firejail/firejail.users`. This makes jailing system services (like tor, i2pd, etc.) that run as their own user problematic.

One workaround is using `firejail sudo -u i2pd i2pd` but that requires weakening a lot of directives (allowing root, setuid, access to the sudo binary, etc). I am also having a hard time getting it to work.

One other workaround is changing the uid of these users to something above 1000, but that sounds like an even worse idea.

Can firejail be made to work for system users at all?

**Comment by SkewedZeppelin** [comment]
If you are running systemd, I would just use the built in hardening capabilities. See https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing for a rundown

**Comment by Vincent43** [comment]
What firejail version do you use? It should be fixed in 0.9.56 with https://github.com/netblue30/firejail/commit/95deecf1f3128c2fd6984c6b6f4a8f540441188b , see https://github.com/netblue30/firejail/issues/2088

**Comment by Artefact2** [comment]
I am still running `0.9.54`. I will play with `asp` to try out the latest version then. Thanks!
