### ISSUE TITLE
Discord fails to open with ENOTFOUND discordapp.com

### ISSUE THREAD

**Issue by hlieberman** [netblue30/firejail#2129]
Hello!

It looks like Discord is having trouble getting to the internet with the default profile in 0.9.56.

Relevant snippet:

```
 [Modules] Checking for host updates.
[Updates] Error fetching https://discordapp.com/api/updates/stable?platform=linux&version=0.0.5: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
[Modules] Host update failed: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
```

**Comment by veloute** [comment]
[this](https://github.com/netblue30/firejail/pull/2131) pr should fix the problem.

**Comment by chiraag-nataraj** [comment]
@hlieberman Looks like this issue should be fixed. Please feel free to re-open if it's not resolved :)
