### ISSUE TITLE
vlc: why is $(DOCUMENTS) blacklisted?

### ISSUE THREAD

**Issue by mr-blobbyyy** [netblue30/firejail#2132]
Any media in the documents folder is not even browsable?

**Comment by Fred-Barclay** [comment]
Generally speaking, we thought it was better to not allow access to documents.

You can change this pretty easily though -- just make a file `/etc/firejail/vlc.local` with the following line:
```
noblacklist ${DOCUMENTS}
```
After saving the file and restarting vlc, you should be able to access any media in your documents folder.

Cheers!
Fred

**Comment by chiraag-nataraj** [comment]
@mr-blobbyyy If @Fred-Barclay's solution doesn't work, please feel free to re-open!
