### ISSUE TITLE
Firefox 62.0.3 on Ubuntu 18.04 with PPA-Version 0.9.56-1

### ISSUE THREAD

**Issue by cron0mat** [netblue30/firejail#2134]
Hi,

I have used firejail from ubuntu repos (0.9.52) with etc fixes and this was running just fine.

I tried now firejail 0.9.56 from Reiners PPA and had problems with firefox again (I can start firefox but after entering website link nothing happens).

Is etc fix not included in to newer firejail versions or do I need to adapt something manually ?

BR

**Comment by chiraag-nataraj** [comment]
Which version of firefox do you have? What does `firejail --debug firefox` output?

**Comment by reinerh** [comment]
@cron0mat Have you also installed the firejail-profiles package (in version 0.9.56)?

**Comment by Vincent43** [comment]
Could be also another _AppArmor breaks firejail_ issue.

**Comment by Vincent43** [comment]
Please post `journalctl |grep DENIED`.

**Comment by cron0mat** [comment]
@Vincent43 : shortened to the time stamp of my test :





[journalctl.txt](https://github.com/netblue30/firejail/files/2447965/journalctl.txt)

**Comment by Vincent43** [comment]
It seems that you use old `firejail-default` apparmor profile (which is known to break firefox). Please check with `cat /etc/apparmor.d/firejail-default`. It should look like https://github.com/netblue30/firejail/blob/0.9.56/etc/firejail-default and is included in [PPA](https://launchpad.net/~deki/+archive/ubuntu/firejail/+files/firejail_0.9.56-1~0ubuntu18.04.0_amd64.deb) . Are you sure that you are using firejail 0.9.56? Check with `firejail --version`.
