### ISSUE TITLE
[Feature] Manage Proxies

### ISSUE THREAD

**Issue by asdfghjz** [netblue30/firejail#2135]
It would be awesome if we could set different proxy settings for different apps :)

**Comment by chiraag-nataraj** [comment]
This _could_ be as simple as setting environment variables, assuming all programs respect them...

**Comment by netblue30** [comment]
Yes, look for environment variables. Probably every program uses a different env var for the proxy.

**Comment by chiraag-nataraj** [comment]
Many will respect `HTTP{,S}_PROXY`. Some require it to be lower-case (`http{,s}_proxy`.

**Comment by SkewedZeppelin** [comment]
Add something like the following to a profile
```
env HTTP_PROXY=http://127.0.0.1:3128
```

I shold note, TorSocks is a ld.preload shim that actually intercepts calls and enforces they route over the proxy, providing a layer of safety. So depending on what application you are using you might not want to use this env method.

**Comment by asdfghjz** [comment]
@SkewedZeppelin How do you add that to a profile? Can I use FireTools or the Config app? Or is there a terminal command?

**Comment by rusty-snake** [comment]
Or `echo "env HTTP_PROXY=http://127.0.0.1:3128" >> $HOME/.config/firejail/PROGRAMM.local`

**Comment by chiraag-nataraj** [comment]
Either way, I think the question has been answered sufficiently thoroughly. I'll go ahead and close, but @asdfghjz, please feel free to re-open if you have additional questions!
