### ISSUE TITLE
Allow for --join to wait until sandbox is ready instead of dying when its not.

### ISSUE THREAD

**Issue by crass** [netblue30/firejail#2139]
My specific use case is that I have a script which first creates an X11 sandbox with WM.  Then it tries to execute a process in that sandbox via `--join`.  However, the sandbox isn't fully setup at this point, so firejail exits with the error `Error: no valid sandbox`.  It would be nice if `--join` would wait until the sandbox is setup.

**Comment by smitsohu** [comment]
It's taken a while, but yes! I think we can do it, possibly the timeout can be configurable in /etc/firejail/firejail.config
