### ISSUE TITLE
Unable to use network namespace with openvpn

### ISSUE THREAD

**Issue by zedniss** [netblue30/firejail#214]
I'm running firejail 0.9.36 on Arch Linux. My wired ethernet device is `enp0s25`.

When I use firejail with a network namespace normally, it works fine:

```
$ firejail --net=enp0s25 --noprofile
Parent pid 7491, child pid 7493

Interface        MAC                IP               Mask             Status
lo                                  127.0.0.1        255.0.0.0        UP
eth0-7491        2a:3f:c1:99:35:61  10.1.10.167      255.255.255.0    UP
Default gateway 10.1.10.1

Child process initialized
[user@host ~]$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0-7491@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 2a:3f:c1:99:35:61 brd ff:ff:ff:ff:ff:ff link-netnsid 0
[user@host ~]$ ping -c 3 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=11.7 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=55 time=11.6 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=55 time=11.8 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 11.610/11.768/11.897/0.118 ms
```

However, if I first launch an openvpn client on my system and then try to use firejail with a network namespace, the network does not work.

```
# first launch openvpn and wait for the initialization sequence to complete, then...
$ firejail --net=enp0s25 --noprofile
Parent pid 10568, child pid 10570

Interface        MAC                IP               Mask             Status
lo                                  127.0.0.1        255.0.0.0        UP
eth0-10568       5e:70:a7:9b:91:6c  10.1.10.21       255.255.255.0    UP

Child process initialized
[user@host ~]$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0-10568@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 5e:70:a7:9b:91:6c brd ff:ff:ff:ff:ff:ff link-netnsid 0
[user@host ~]$ ping -c 3 8.8.8.8
connect: Network is unreachable
```

Is there something special I need to do to use the network namespace on a machine connected to a vpn? I don't know if maybe I need to define a gateway or something?

**Comment by zedniss** [comment]
I've also noticed that a new `tun0` network device appears when the openvpn client connects. I don't know if maybe I am supposed to use that with firejail. Trying to results in an error:

```
$ firejail --net=tun0 --noprofile
Error: the software is not supported for /31 networks
```

**Comment by the8472** [comment]
What's your use-scenario? Do you need the VPN tunnel only to contact certain hosts? do you want the jail to go through the VPN too or over your ethernet?

**Comment by zedniss** [comment]
I use the vpn to tunnel all connections, not just to certain hosts. I want the jail to go through the vpn just like all the non-jailed stuff on the system.

**Comment by the8472** [comment]
then you probably have to setup an empty bridge device and configure fowarding + NAT from the bridge to your default route (which is either ethernet or the tunnel).

Firejail assumes it can bridge into the current network (i.e. get an additional IP), which is not possible with a tun device.

**Comment by zedniss** [comment]
Can you explain how I would do that? I'm new to all of this. thnx.

**Comment by the8472** [comment]
You're using arch. Isn't reading some docs and figuring out how to configure things part of its raison d'etre? :P

**Comment by lepasserby** [comment]
Actually :) making a bridge device go only through tun0 is a bit of a pain. I've done it for my skype-isolation shenanigans. I have a shell script that sets up a bunch of bridge interfaces and configures iptables to do relevant nat-ing. 

I'll post my script here next week, I think

**Comment by netblue30** [comment]
You would need to run OpenVPN in bridge mode, using tap devices. Unfortunately you would need to set bridge mode on both sides of the tunnel, client and server. It would go something like this:

Start the tunnel:
`````
openvpn --remote $CLIENT_IP  --dev tap1 --ifconfig 10.9.8.1 255.255.255.0 # on server
openvpn --remote $SERVR_IP --dev tap1 --ifconfig 10.9.8.2 255.255.255.0 # on client
`````
On client you would create an empty bridge and add the tap1 device to it:
`````
brctl addbr br0
ifconfig br0 up
brctl addif br0 tap1
`````
Do not connect br0 to your regular Ethernet interface, so on the bridge you have only tunnel traffic. Now, you can start firejail on this bridge:
`````
firejail --net=br0 program_and_arguments
`````
I didn't include a number of steps, such as how you encrypt the tunnel or how you do the routing on the server side. In my opinion, if you are only using the VPN for browsing, all this is not worth the trouble. I would just go with the regular tunnel setup run "firejail firefox" on the client side.

**Comment by netblue30** [comment]
discussion moved here: https://github.com/netblue30/firejail/issues/59
