### ISSUE TITLE
Firefox 61.0.1.glibc2.7 Appimage with multi-process windows enabled does not successfully load pages

### ISSUE THREAD

**Issue by crass** [netblue30/firejail#2142]
Using up to date master with #2141 added, the `61.0.1.glibc2.7` firefox appimage displays, with saved tabs when using a pre-existing profile.  However none of the tabs load, including `file:///` urls.  Version `56.0.2.glibc2.3.4` works just fine.  I would presume all the latest profile fixes are in master, is that a wrong assumption?  Has anyone else gotten 61 non-appimage to run?

https://bintray.com/probono/AppImages/Firefox/61.0.1.glibc2.7#files

**Comment by chiraag-nataraj** [comment]
I currently have a non-appimage `62.0.3` running just fine on Debian sid/experimental with a more restrictive profile than the default (mine's [here](https://github.com/chiraag-nataraj/firejail-profiles)).

**Comment by crass** [comment]
I've tried the latest appimage `62.0.2` and get the same symptoms.  I've [disabled multi-process windows (see bottom)](https://support.mozilla.org/en-US/questions/1167673), and now both are working as expected.  Do you have multi-process windows enabled?

**Comment by chiraag-nataraj** [comment]
> Do you have multi-process windows enabled?

Yup, I've had it enabled since they first made it available.

**Comment by crass** [comment]
Ok, I've narrowed it down to [this code](https://github.com/netblue30/firejail/blob/8f788307da137d985647a69f134b7f8e88765326/src/firejail/sandbox.c#L754-L758).  If I remove `arg_appimage` from the conditional and recompile, then the firefox appimage will load content in tabs when mutli-process windows is turned on (ie. work as expected).

@netblue30, so what was the rationale behind including appimages here?  It seems that the decision was made in commit 2399e09e66, but its not clear to me why.  It seems to me that appimages must not be any more strict than the corresponding non-appimage profile (the program will need all the rules of the non-appimage profile plus perhaps some permission unique to appimages).

**Comment by crass** [comment]
After digging deeper, the appimage will load with `enforce_filters` _if_ `chroot` is removed from `@defaults`.  After `strace`ing the appimage, it can be seen that `chroot` and before that `capset` with `CAP_SYS_CHROOT` is being called.  It appears that the sandbox is setting up a user namespace where it is root inside the sandbox, and thus can give itself capabilities.

Does anyone have thoughts on how to solve this? I'm thinking that appimage mode should only use the default seccomp if one wasn't provided.  If one was provided the user clearly wanted to use that one.  Also, in the vast majority of cases, the user will specify a specific profile for an appimage because the command name matching will not generally work for appimages.  So, the user provided profile will have the appropriate seccomp, which may not be as restrictive as the default seccomp.
