### ISSUE TITLE
starting/stopping a jail with --net=br0 causes network hiccups

### ISSUE THREAD

**Issue by the8472** [netblue30/firejail#215]
Symptoms:
- ssh sessions and other network traffic into the box hang for several seconds after closing the jail
- br0 somehow obtains additional SLAAC-addresses

Speculations on causes:
- [the host's end of the veth pair is brought up before adding it to the bridge.](https://github.com/netblue30/firejail/blob/master/src/firejail/network_main.c#L124-L128). maybe it should be added to the bridge first and then brought up
- shutting down the veth pair / network namespace is missing some necessary cleanup steps

**Comment by netblue30** [comment]
I put in the veth pair fix you suggested. I'll have to find a way to shut down the interfaces when the namespace is destroyed.

**Comment by chiraag-nataraj** [comment]
@the8472 Is this still an issue?

**Comment by chiraag-nataraj** [comment]
I'm going to close this for inactivity. @the8472, please feel free to re-open if you have more questions or if this is still an issue.
