### ISSUE TITLE
--build should not assume that firejail's default profile dir is /etc/firejail

### ISSUE THREAD

**Issue by crass** [netblue30/firejail#2150]
The option `--build` is hardcoded to build profiles assuming the firejail profile dir is `/etc/local`, but it may not be if firejail was installed in a non-default location.  It should also use the `${CFG}` macro in the output.

**Comment by reinerh** [comment]
> The option --build is hardcoded to build profiles assuming the firejail profile dir is `/etc/local`

I think you mean `/etc/firejail`?

I agree, it should use the configured sysconfdir instead of hardcoded paths.

**Comment by chiraag-nataraj** [comment]
We should fix this!

**Comment by rusty-snake** [comment]
Since 0.9.60 no `/etc/firejail` in profiles is needed.

Since `--build` is completely outdated anyway, IMHO it is better to remove it from firejail and replace it with an own firebuild program.
