### ISSUE TITLE
All profiles should use ${CFG} instead of hardcoded paths.

### ISSUE THREAD

**Issue by crass** [netblue30/firejail#2151]
I assume this was forgotten when support for the `${CFG}` macro was implemented.  Which is a great feature.

**Comment by reinerh** [comment]
nice, I wasn't aware of that. good idea!

**Comment by crass** [comment]
IMHO, this should be obsoleted by #2156 .

**Comment by crass** [comment]
Closing as path prefix is not used in the distribution profiles anymore.
