### ISSUE TITLE
noinclude directive

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#2153]
So in light of discussions like #2147, we should probably introduce a `noinclude` option that prevents loading of an `include` specified in another included file. Yes, I realize that's confusing, so let me illustrate scenarios in which this may be useful.

1. The aforementioned scenario with an automatic include that you want to prevent (`noinclude whitelist-appimage.inc`).
2. `firefox.profile` includes `firefox-common.profile` which includes `${CFG}/disable-common.inc`. This directive would be useful to disable the `include ${CFG}/disable-common.inc` in `firefox.profile`.

What do people think? Should we do this?

**Comment by chiraag-nataraj** [comment]
Alternatively, conditional commands: `if(appimage) include whitelist-appimage.inc` (for example). The syntax is up for debate, of course.

**Comment by startx2017** [comment]
--noinclude=file is easier to implement for now.

I'll also look into if(condition) ...

**Comment by chiraag-nataraj** [comment]
Is there a specific barrier to using the conditional support to allow conditional includes?

**Comment by Vincent43** [comment]
What about `ignore include xxx.inc`?

**Comment by chiraag-nataraj** [comment]
It doesn't work.
```
$ firejail --ignore='include ${HOME}/.config/firejail/common.inc' --profile=.config/firejail/x-terminal-emulator.profile x-terminal-emulator
Reading profile .config/firejail/x-terminal-emulator.profile
Reading profile /home/chiraag/.config/firejail/common.inc
Parent pid 25214, child pid 25215
Warning: skipping emp for private /opt
Private /opt installed in 0.17 ms
Warning: skipping emp for private /srv
Private /srv installed in 0.08 ms
Child process initialized in 55.38 ms
urxvt: unable to register '""' as scrollback search start hotkey
```
where `~/.config/firejail/x-terminal-emulator` is:
```
ignore nodbus
ignore private-tmp
ignore private-dev
ignore memory-deny-write-execute
ignore noexec ${HOME}
ignore blacklist /usr/local/bin

include ${HOME}/.config/firejail/common.inc

whitelist /tmp/user/1000
whitelist /tmp/.X11-unix/

writable-run-user
keep-dev-shm
```

**Comment by Vincent43** [comment]
I meant maeking `ignore include xxx.inc` work instead of introducing `noinclude`.

**Comment by rusty-snake** [comment]
I'm not a C developer so no idea what I am doing, but this works.
```diff
--- a/src/firejail/profile.c
+++ b/src/firejail/profile.c
@@ -1606,7 +1606,7 @@ void profile_read(const char *fname) {
                }
 
                // process include
-               if (strncmp(ptr, "include ", 8) == 0) {
+               if (strncmp(ptr, "include ", 8) == 0 && !is_in_ignore_list(ptr)) {
                        include_level++;
 
                        // expand macros in front of the include profile file
```

**Comment by rusty-snake** [comment]
@startx2017 ^

**Comment by smitsohu** [comment]
@rusty-snake can you send a pull request (or commit right away?)

**Comment by rusty-snake** [comment]
102f8d1fdca62dd0ca0fb355c1ef926f2594b48b
