### ISSUE TITLE
How do I install 'Firetools'

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2175]
I installed firejail on Manjaro, now I want to install Firetools, how do I do that?

**Comment by reinerh** [comment]
Have you seen this?
https://wiki.manjaro.org/index.php?title=Firejail#GUI

**Comment by Raj2032** [comment]
I did search `pacman -Sy firetools` and it doesn't seem to exist. Where can I download firetools?

**Comment by SkewedZeppelin** [comment]
https://aur.archlinux.org/packages/firetools/

`aurman -S firetools`
or
`yaourt -S firetools`
or
```
wget https://aur.archlinux.org/cgit/aur.git/snapshot/firetools.tar.gz
tar -xzvf firetools.tar.gz
cd firetools
makepkg -s
pacman -U firetools-*
```

**Comment by Raj2032** [comment]
Oh ok thanks man.

Which one would be better to use though, aurman or yaourt?

**Comment by SkewedZeppelin** [comment]
today I learned yaourt and aurman both are no longer in development
you'll have to decide for yourself as I haven't used arch in a while
https://wiki.archlinux.org/index.php/AUR_helpers

**Comment by Raj2032** [comment]
Oh ok, thanks anyways.

**Comment by Raj2032** [comment]
Hey @SkewedZeppelin, first of all aurman and yaourt did not work. When I tried to manually build the package (which worked) I got this error

`error: missing package metadata in firetools-0.9.52.tar.xz
error: 'firetools-0.9.52.tar.xz': invalid or corrupted package`

**Comment by chiraag-nataraj** [comment]
Isn't this an Arch-specific packaaging question at this point?

**Comment by Vincent43** [comment]
Yes, I don't know how we can help further.

Maybe try:
```
git clone https://aur.archlinux.org/firetools.git
cd firetools
makepkg -srcCif
```

**Comment by Raj2032** [comment]
Well I don't know where to get it from if it is not working but thanks for
the tip I will tri it out.

**Comment by rusty-snake** [comment]
@Raj2032 still need help or can we close?

**Comment by Raj2032** [comment]
@rusty-snake I am sorry I missed this message.
