### ISSUE TITLE
Whitelisting a folder is a bit tricky

### ISSUE THREAD

**Issue by CrisBRM** [netblue30/firejail#218]
Wanted to add the folder /home/cris (no, it's not the same as ~/cris ($HOME is /home/home on my machine) so I could fill it with stuff only firefox could access, like my locally hosted startpage, but the options ```whitelist /home/cris/``` and/or ```noblacklist /home/cris``` do not work, as it still can't access my startpage, which is right there.

I have read the man page and I would expect either option to work, so maybe you could shed some light on this.

**Comment by the8472** [comment]
man page says:

>--whitelist=dirname_or_filename

>  Whitelist directory or file. This feature is implemented only for user home, /dev, /media, /opt, /var, and /tmp directories.

Note that it says *user home not */home*

**Comment by CrisBRM** [comment]
In which case shouldn't ```noblacklist``` do what I want?

**Comment by the8472** [comment]
If you're running firejail as non-root it mounts a tmpfs over `/home` and then bind-mounts only that one user back into the tmpfs.
Running as root and then using su to change to that particular user inside the jail might work.

**Comment by CrisBRM** [comment]
Question: would creating a user called cris with the home set to /home/cris fix this issue?

**Comment by the8472** [comment]
if you run the jail under that user, probably.
