### ISSUE TITLE
Allow subdirectories in private-etc

### ISSUE THREAD

**Issue by Artefact2** [netblue30/firejail#2187]
Some programs (like awesome) follow the [XDG base directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and store their system-wide configuration in `/etc/xdg/<program-name>`.

At the moment, `private-etc` cannot copy only `xdg/<program-name>` (it complains about it being an invalid file name). It would be nice if it could, for example:

~~~
private-etc xdg/awesome
~~~

**Comment by rusty-snake** [comment]
#4215
