### ISSUE TITLE
disable-mnt is unintuitive and complicated, suggesting removal or alteration

### ISSUE THREAD

**Issue by Radtoo** [netblue30/firejail#2188]
I just found out about disable-mnt in configuration files in a very ungood way.

I tried whitelisting a subfolder in /media for a firejailed software that invokes a firejailed software that invokes a filejailed software. Which did not work even after gratitous use of whitelisting and noblacklisting, which I tried to do by creating configurations in ${HOME}/.config/firejail that included the configurations in /etc/firejail/.

I eventually became aware that disable-mnt in one of the involved configurations is the problem, which took a while because the directive does not include "media" for grep. And that this directive unintuitively does not seem to respond to noblacklist/whitelist in my configuration files.
But even once I knew, fixing this with my own configuration files in the user home directory (by creating copies of files without the "disable-mnt" directive and then copies of everything that directly or indirectly included those files) was also quite cumbersome.

Maybe I missed a directive that could have disabled "disable-mnt" in a configuration file...? Although even if: Why does the disable-mnt directive even exist? **I feel like getting rid of it and just using blacklisting directives for the respective directories would be far easier - one less thing to be aware of.** Or at least allow overriding it with noblackist / whitelist in configuration files as if it was a set of blacklist directives.

Edit: I just saw that #2149 looks pretty comparable to this bug.

**Comment by Radtoo** [comment]
I see. Thanks, that seems like a fix to the main issues involved.

Although I do not necessarily get why it couldn't simply be one of the /etc/firejail/disable-*.inc ?

**Comment by smitsohu** [comment]
> Maybe I missed a directive that could have disabled "disable-mnt" in a configuration file...? 

Btw, it is always possible to override options with `ignore`, both on the command line and in profiles.

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this, since the original issue was fixed a while ago.

**Comment by Radtoo** [comment]
Sure, thanks for the notice!
