### ISSUE TITLE
[minor bug] tray icon bug for some KDE apps

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#219]
No tray icon on start up for KDE apps after the first app with a tray icon. The first app in firejail seams fine.
In the terminal, it complains about kbuildsycoca4
(probably this is the problem)

"kbuildsycoca4(11) parseLayoutNode: The menu spec file contains a Layout or DefaultLayout tag without the mandatory Merge tag inside. Please fix your file."

If you deactivate and reactivate tray icon in the configuration, it reappears however.

This happens even with --noprofile
Some affected KDE apps: Ktorrent, akregator, amarok, kmail, but not kiten( doesn't seam to use kbuildsycoca4).

firejail 0.9.36 , Linux Mint 17.3 KDE 4.14.2

**Comment by pirate486743186** [comment]
partial workaround for whoever is annoyed by this. In the menu editor, you can chose "place in system tray". This is not the same system tray button as the one of the application it self, but some generic one. For amarok it doesn't work.

**Comment by pirate486743186** [comment]
same in 0.9.38

**Comment by pirate486743186** [comment]
well, the issue is gone in plasma5

**Comment by skomorokh** [comment]
I'm having similar problems with the tray and quasselclient, scudcloud, etc. on Kubuntu 16.04. Haven't had time to troubleshoot this yet. I wonder if it isn't related to dbus though rather than kbuildsycoca4?

**Comment by netblue30** [comment]
Let's keep an eye on it, and after I release the new firejail version in a few days, we'll test again.

**Comment by netblue30** [comment]
Are you still having this problem in 0.9.42~rv2?
