### ISSUE TITLE
add nou2f to all profiles with private-dev

### ISSUE THREAD

**Issue by smitsohu** [netblue30/firejail#2194]
We punched a small hole in `private-dev` to get yubikeys and such working, but it hasn't been closed yet in the profiles that we ship.

I would propose to add `nou2f` to all profiles with `private-dev`, including the browsers and keepassxc. The reason is that /dev/usb can contain devices such as printers and keyboards, and exposing them in the sandbox is usually neither necessary nor desirable.
Imho users who own a yubikey and want to use it with firejail should rather opt-in and disable nou2f themselves.

**Comment by reinerh** [comment]
instead of touching every profile, why not make nou2f the default, and add an "u2f" option which allows it?

**Comment by smitsohu** [comment]
@reinerh It would be way easier to maintain! But if I understand #1446 right, we are going to do this anyway at some point. To avoid confusing semantics, all `private-dev` related options should probably change behavior simultaneously.

**Comment by SkewedZeppelin** [comment]
@smitsohu if you want to go the easy approach, here is a commit that adds nou2f to all profiles in the proper location
https://github.com/SkewedZeppelin/firejail/commit/a17865f33b55d834d38dd8bb4e0f8023e863b679

**Comment by smitsohu** [comment]
@SkewedZeppelin Cool!

It is only me, but I would find "the easy approach" more suitable for what might be a "bugfix" release.

**Comment by SkewedZeppelin** [comment]
Should we comment nou2f in firefox and chromium common?
