### ISSUE TITLE
debug-syscalls, debug-errnos, ... don't work any more

### ISSUE THREAD

**Issue by smitsohu** [netblue30/firejail#2197]
```
smitsohu@smitsohu:~$ firejail --debug-syscalls
execvp: No such file or directory
Error: failed to run /run/firejail/lib/fseccomp
```

**Comment by netblue30** [comment]
Thanks, I'll look into it, some problems with the code I put in two days ago, nothing major.

**Comment by crass** [comment]
@netblue30 this is why I had the mount bind in the main firejail process which was in its own mount namespace.  Why didn't it work for you as it was?

**Comment by netblue30** [comment]
The original pull rq was fine, it passed all the automatic tests, but It was crashing programs you start by clicking on desktop manager menus (probably something to do with fnet). As soon as I removed the mount from main, it started working. I cannot explain it.
