### ISSUE TITLE
Error: --net and --net=none are mutually exclusive

### ISSUE THREAD

**Issue by Zypherspace** [netblue30/firejail#2204]
When `--net` is defined in a profile, including the parameter (i.e. `-net=none`) to a firejail launch string results in:

`Error: --net and --net=none are mutually exclusive`

The only way I have found to override the global profile is to use a `--noprofile` string. It would be useful if the launch parameter would override global or local profiles for granular control.

**Comment by Vincent43** [comment]
Does `--net=xxx --ignore=net` works?

**Comment by Zypherspace** [comment]
Yes that solves it. `--ignore=net --net=none` overrides profile defined net= per instance. Thanks!
