### ISSUE TITLE
Firejail "breaks" ranger

### ISSUE THREAD

**Issue by qazip** [netblue30/firejail#2206]
I am using the latest version of ranger and I create a symbolic link with firecfg.

```
firejail version 0.9.56

Compile time support:
	- AppArmor support is disabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

When using ranger (firejailed) and opening a .mkv file from inside ranger (it opens mpv) there is no sound in mpv. Also, mpv is not properly detached so when closing ranger, mpv is also closed. Both this things do not happen when ranger is not firejailed.

**Comment by Fred-Barclay** [comment]
Hi @qazip 
Can you try starting ranger with `firejail --nosound ranger` and seeing if the sound works?

About detaching mpv... that could be a little problematic. Allowing mpv to detach from firejailed ranger, so to speak, would really mean that mpv can escape the sandbox... but then that means malicious programs might as well. I don't think there's a way around this.

**Comment by SkewedZeppelin** [comment]
See #1261

**Comment by qazip** [comment]
@Fred-Barclay, that doesn't work, but commenting nosound on the profile does work. Sadly, I was more looking into the detachment problem. It's unfortunate that it is not possible..

**Comment by veloute** [comment]
this commit should close this issue  https://github.com/netblue30/firejail/commit/95a8e4fb23a2855b1dd0a83a041354f2b109ef60
