### ISSUE TITLE
Consider migrating from Travis-CI to Github Actions

### ISSUE THREAD

**Issue by Vincent43** [netblue30/firejail#2208]
[Github Actions](https://github.com/features/actions) is new service (beta) for CI. Perhaps it has better intergration than third party services and maybe more features.

**Comment by Fred-Barclay** [comment]
Any particular reason we couldn't use both? It would give us more redundancy if Travis CI goes down.

**Comment by Vincent43** [comment]
Sure we can use both. In case we have to jump ship it will break everything anyway. We may consider create mirror on gitlab.

**Comment by Fred-Barclay** [comment]
> We may consider create mirror on gitlab.

Tried that previously -- IIRC it works well. :smile:

**Comment by netblue30** [comment]
We'll use both of them. TravisCI runs on Ubuntu 14.04, maybe we can get something newer from these guys. The test in Travis covers about 55% of the code (this is the number from 6 months ago), if we get a newer kernel we can bump up the coverage.

**Comment by chiraag-nataraj** [comment]
Let's move the discussion over to #2729.
