### ISSUE TITLE
a kmail profile

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#221]
kmail is not trivial to set up, because it calls akonadi in order to function. So bellow, i propose a profile, the best i could make it. (the commented out parts, definitely brake it). Launching links and encrypting messages worked.

# kmail profile
noblacklist ${HOME}/.gnupg
#include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
blacklist ${HOME}/.pki/nssdb
blacklist ${HOME}/.lastpass
blacklist ${HOME}/.keepassx
blacklist ${HOME}/.password-store
blacklist ${HOME}/.wine
caps.drop all
#seccomp
#protocol unix,inet,inet6
netfilter
noroot
tracelog

**Comment by netblue30** [comment]
Thanks, I'll put it in.

**Comment by netblue30** [comment]
I added the profile, you'll find it in /etc/firejail/kmail.profile, thanks!
`````
# kmail profile
noblacklist ${HOME}/.gnupg
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
blacklist ${HOME}/.pki/nssdb
blacklist ${HOME}/.lastpass
blacklist ${HOME}/.keepassx
blacklist ${HOME}/.password-store
blacklist ${HOME}/.wine
caps.drop all
seccomp
protocol unix,inet,inet6,netlink
netfilter
noroot
tracelog
`````

**Comment by pirate486743186** [comment]
beh... i messed up. Actually i had akonadi not to launch on start up to save memory XD .You could have said so, that there's something strange here :P

Just mention in a comment, that it needs akonadi to launch before kmail, easily scripted with "akonadictl start ; sleep 2 ; firejail kmail". And also "akonadictl stop", when you want it to shut-down. 

Normally it is launched at start up. They are also some other akonadi apps that might confuse some users.
