### ISSUE TITLE
Chromium not starting on 0.9.56

### ISSUE THREAD

**Issue by Tritonio** [netblue30/firejail#2211]
Chromium Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)
does not start with firejail 0.9.56.

Adding

ignore nodbus

to /etc/firejail/chromium.local

lets me start Chromium fine though.

**Comment by chiraag-nataraj** [comment]
Is this still an issue? I believe we fixed this a while back...

**Comment by chiraag-nataraj** [comment]
@Tritonio I'll close this for now, but please feel free to re-open if you still have this issue.
