### ISSUE TITLE
Firefox not able to create crash dump and send crash report after crash

### ISSUE THREAD

**Issue by juxi500** [netblue30/firejail#2212]
Hello, I noticed that when I am running Firefox inside firejail, when Firefox crashes, it is not able to create crash dump and send crash report to Mozilla. Is it intended behaviour or do I have something misconfigured? If you need any more information just let me know.

Thank you very much and have a nice day! :)

**Comment by Vincent43** [comment]
Generally speaking, it's intended.. It may be caused by `apparmor` (if your distro has apparmor support like ubuntu) or maybe `nodbus`. If you need crash report you may try to add `ignore` rule for that options in `firefox.local` or in command line.

**Comment by SkewedZeppelin** [comment]
@Vincent43 I think it is either caps or seccomp, I've seen it happen many times.

**Comment by juxi500** [comment]
> Generally speaking, it's intended.. It may be caused by `apparmor` (if your distro has apparmor support like ubuntu) or maybe `nodbus`. If you need crash report you may try to add `ignore` rule for that options in `firefox.local` or in command line.

I use EL7 so I have SeLinux instead of AppArmor... Ok so if I want to disable nodbus I will try ignore nodbus option...? :)

**Comment by juxi500** [comment]
> @Vincent43 I think it is either caps or seccomp, I've seen it happen many times.

Is it possible to somehow tell caps or seccomp to let Firefox send crash reports or should I disable them?

**Comment by juxi500** [comment]
Well I will try but the "problem" is I can't reliably crash Firefox... :) In my experience it is pretty stable these days... But when I will encounter a crash and I will see something like this in command line I will let you know :)

**Comment by juxi500** [comment]
Today I managed to crash Firefox, with caps, seccomp and nodbus ignored, but still it can not send crash reports.

`$ firejail --ignore=seccomp --ignore=caps --ignore=nodbus /home/user/.opt/firefox-beta/firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox.local
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 10261, child pid 10262
Post-exec seccomp protector enabled
Seccomp list in: @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice, check list: @default-keep, prelist: adjtimex,clock_adjtime,clock_settime,settimeofday,modify_ldt,lookup_dcookie,perf_event_open,process_vm_writev,delete_module,finit_module,init_module,_sysctl,afs_syscall,create_module,get_kernel_syms,getpmsg,putpmsg,query_module,security,sysfs,tuxcall,uselib,ustat,vserver,ioperm,iopl,kexec_load,kexec_file_load,reboot,set_mempolicy,migrate_pages,move_pages,mbind,swapon,swapoff,acct,add_key,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount2,userfaultfd,vhangup,vmsplice,`
`Child process initialized in 77.80 ms
[Parent 7, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 736
ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
427
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
[Child 117, Chrome_ChildThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 736
2018-11-03 13:40:07: minidump.cc:5094: ERROR: Minidump could not open minidump /home/user/.mozilla/firefox/12345678.default/minidumps/07bb2bc7-0418-a12a-3706-2a51fa5f2b47.dmp, error 2: No such file or directory
2018-11-03 13:40:07: minidump.cc:5191: ERROR: Minidump cannot open minidump
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`

`Parent is shutting down, bye...`

Please do you have some ideas what could be the problem?
If you need any more information just let me know.
Have a nice day :)

**Comment by chiraag-nataraj** [comment]
It's most likely the seccomp filter, but I don't know. Is this still an issue?

**Comment by matu3ba** [comment]
@juxi500 Please provide feedback.
Otherwise this should be closed.

**Comment by rusty-snake** [comment]
@juxi500 I'm closing here due to inactivity, please fell free to reopen if you still have this issue.

**Comment by byteit101** [comment]
I was able to reproduce this. I seem to be stuck hitting https://crash-stats.mozilla.org/signature/?product=Firefox&signature=mozilla%3A%3Aa11y%3A%3ADOMtoATK%3A%3AATKStringConverterHelper%3A%3AFinishUTF16toUTF8 every few days, so I'll try adding those flags and reporting back in a few days when I invariably hit that again

**Comment by rusty-snake** [comment]
@byteit101 if @chiraag-nataraj is right, you can find the blocked syscall with `journalctl --grep=SECCOMP`.

**Comment by byteit101** [comment]
hmm, my journalctl was:
Compiled without pattern matching support

but this is what appeared:
```
Feb 11 20:03:45 debian-box audit[29889]: AVC apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box audit[29889]: AVC apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box audit[29889]: AVC apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: kauditd_printk_skb: 138 callbacks suppressed
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:335): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:336): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:337): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:338): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:339): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:340): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:341): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:342): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:343): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box kernel: audit: type=1400 audit(1581469425.641:344): apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box audit[29889]: AVC apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box audit[29889]: AVC apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
Feb 11 20:03:45 debian-box audit[29889]: AVC apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="tracedby" denied_mask="tracedby" peer="firejail-default"
Feb 11 20:03:45 debian-box audit[29889]: AVC apparmor="DENIED" operation="ptrace" profile="firejail-default" pid=29889 comm="firefox-bin" requested_mask="trace" denied_mask="trace" peer="firejail-default"
...
```
(about 150 lines in total of this repeating)

**Comment by rusty-snake** [comment]
You can also try it with `journalctl | grep SECCOMP`, however this error is about AppArmor, has you enabled the debian AA profile for firefox or is it just the firejail one?

**Comment by Vincent43** [comment]
@byteit101 could you show `firejail --version` output?

**Comment by byteit101** [comment]
I think the AA profile was enabled automatically when I upgraded to debian 10

```
~ firejail --version                                                                                       
firejail version 0.9.62

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

**Comment by Vincent43** [comment]
@byteit101 try adding: `ptrace (trace,tracedby) peer=@{profile_name},` line in `/etc/apparmor.d/local/firejail-default`

**Comment by rusty-snake** [comment]
`ptrace` is also blocked by firejails seccomp filter, you should also add `allow-debuggers`.

**Comment by byteit101** [comment]
I added @Vincent43's  ptrace line to apparmor, and running with:
`firejail --ignore=seccomp --ignore=caps --ignore=nodbus firefox` I got the Mozilla crash dialog and was able to send a report!

**Comment by rusty-snake** [comment]
Are all ignores needed? Can you try with `firejail --allow-debuggers --ignore=caps --ignore=nodbus firefox`.

**Comment by byteit101** [comment]
`firejail --ignore=seccomp --ignore=caps --ignore=nodbus firefox` **shows** the dialog
`firejail --allow-debuggers --ignore=caps --ignore=nodbus firefox` **shows** the dialog
`firejail --allow-debuggers firefox` **shows** the dialog
`firejail firefox` **doesn't** show the dialog

**Comment by rusty-snake** [comment]
To summary:
`firejail --allow-debuggers firefox`
or
`firejail --seccomp.drop=@default --ignore=seccomp firefox`
or
 `firejail '--seccomp=!ptrace' firefox`
and
@Vincent43 AA rule for apparmor users

**Comment by byteit101** [comment]
Correct
