### ISSUE TITLE
[Question] Do Apps Automatically use FireJail when Configured?

### ISSUE THREAD

**Issue by asdfghjz** [netblue30/firejail#2215]
Sorry, for my noob questions but, if I config an app in the Configuration Wizard whenever I open the app will it utilize FireJail? Without having to use any commands?

Question 2: Also, can "Jailed" be accessed by non Jailed apps? Like if I wanted to keep some Data safe?
Is this possible?

**Comment by smitsohu** [comment]
> if I config an app in the Configuration Wizard whenever I open the app will it utilize FireJail? Without having to use any commands?

No. The Wizard allows you to run an app in a sandbox, without having to edit configuration files or to type commands in a terminal. But every time you want it sandboxed, you'll have to start it through the Wizard.

It is possible though to run programs always sandboxed. Open a terminal and run `sudo firecfg`, and there you are. It will automatically sandbox all programs for which there is a profile. You can undo this with `sudo firecfg --clean`

> Question 2: Also, can "Jailed" be accessed by non Jailed apps? Like if I wanted to keep some Data safe?

Yes. The sandbox only restricts the processes that are running inside. I think the general recommendation would be rather to rely on encryption for what you want to do. You can then use Firejail as a second defense layer and blacklist the places where you store sensitive data.

**Comment by chiraag-nataraj** [comment]
Looks like this question has been answered, so I'm going to go ahead and close this. @asdfghjz, feel free to re-open if you have more questions in response to @smitsohu's answer.
