### ISSUE TITLE
Warnings with firefox and firejail

### ISSUE THREAD

**Issue by rebirth123** [netblue30/firejail#2216]
Using the latest Firefox from Software Manager on Linux Mint 19 Cinnamon.  I've tried Firejail versions .52, .54 and .56.  I know .52 (the one in the Software manager) has problems with the Firefox version available, but i'm not sure where to problem now lies.  I have tried reinstalling etc.

FF does start up and is showing in both --list and --tree commands, but I'm guessing this isn't normal behaviour.

> $ firejail firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 4748, child pid 4749
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Post-exec seccomp protector enabled
Seccomp list in: @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice, check list: @default-keep, prelist: adjtimex,clock_adjtime,clock_settime,settimeofday,modify_ldt,lookup_dcookie,perf_event_open,process_vm_writev,delete_module,finit_module,init_module,_sysctl,afs_syscall,create_module,get_kernel_syms,getpmsg,putpmsg,query_module,security,sysfs,tuxcall,uselib,ustat,vserver,ioperm,iopl,kexec_load,reboot,set_mempolicy,migrate_pages,move_pages,mbind,swapon,swapoff,acct,add_key,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount2,vhangup,vmsplice,
Child process initialized in 77.68 ms
Warning: an existing sandbox was detected. /usr/bin/firefox will run without any additional sandboxing features
Parent is shutting down, bye...

**Comment by SkewedZeppelin** [comment]
It is probably because you are running firejail twice
run `which firefox`
if you get `/usr/local/bin/firefox` that means you already enabled firejail for it by default
meaning running `firejail firefox` is equivalent to `firejail firejail /usr/bin/firefox`

**Comment by rebirth123** [comment]
Thanks, you're right.  How can I stop this behaviour so I can run firefox and the other apps that it's now using without firejail? I'd prefer to use a separate launcher to start these apps in firejail.

**Comment by Vincent43** [comment]
Use `/usr/bin/firefox` to start app without firejail. Use `firefox` to start app with firejail.

**Comment by rebirth123** [comment]
Caught me whilst editing. :)  Thanks for the alternative method.

**Comment by chiraag-nataraj** [comment]
Seems to be resolved :)
