### ISSUE TITLE
More Portable Like MultiloginApp please

### ISSUE THREAD

**Issue by esotericDisciple** [netblue30/firejail#2217]
Still can't figure out how to run a "firejail --private inox" command that allows for copying over an /.config/inox directory from an external hard drive, so that the end result is the ability to run multiple inox/ungoogled-chromium browsers separately like Multiloginapp or Firefox Containers offers, but also lets me use a custom browser profile, settings, extensions and all, for each one...

**Comment by chiraag-nataraj** [comment]
You might be interested in adapting the `firefox.common` script in [my repository](https://github.com/chiraag-nataraj/firejail-profiles).

**Comment by chiraag-nataraj** [comment]
@esotericDisciple Let's move this discussion to my repository, since that `firefox.common` script is something I created and is not part of `firejail`.
