### ISSUE TITLE
`make install` creates files with wrong permissions when using non-standard umask

### ISSUE THREAD

**Issue by genodeftest** [netblue30/firejail#222]
Steps to reproduce:
1. set umask to something more permissive, e.g. 0077 for both user and root
2. configure, make and sudo make install

What happens:
/usr/local/lib/firejail is not accessible by user. Same is true for most other folders created by `make install`, including /usr/local/share/bash-completion and /usr/local/etc/firejail

Possible solution:
specify `--mode=755` for `mkdir` in Makefile.in
The mkdeb.sh, mkman.sh and mketc.sh files might require additional steps.

**Comment by netblue30** [comment]
Fixed, thanks!

**Comment by genodeftest** [comment]
Thank, that was fast ;)

**Comment by avoidr** [comment]
The same could have probably been achieved by putting "Default umask_override" in /etc/sudoers. This umask thing needs to get more popular.
