### ISSUE TITLE
DNS-Crypt local proxy (127.0.0.1) and --net=eth0

### ISSUE THREAD

**Issue by julien-tmp** [netblue30/firejail#2222]
Hello
I I would like to launch firefox with `firejail --net=eth0 --netfilter=/etc/firejail/nolocal.net --private firefox -no-remote`

Firefox cannot use the DNS anymore and using `--dns=127.0.0.1` does not help. This seems to be due to `--net=eth0`. Adding `--net=lo`  does not seem possible.

What can be done?

**Comment by netblue30** [comment]
Every time you create a network namespace, it brings in a new loopback interface. So the loopback interface you have is different than the regular system loopback. We need a --net=lo, although I have no idea in this moment how we can do it.

**Comment by rusty-snake** [comment]
Duplicate of #108
