### ISSUE TITLE
Errors with Wine running Papers Please

### ISSUE THREAD

**Issue by asdfghjz** [netblue30/firejail#2224]
**Log:**
```
usr@LINUX:~$ firejail wine PapersPlease-1.1.65.msi
Reading profile /etc/firejail/wine.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Parent pid 2963, child pid 2966
Child process initialized
wine: cannot find L"C:\\windows\\system32\\PapersPlease-1.1.65.msi"

Parent is shutting down, bye...
usr@LINUX:~$ 


```

I can assure you it worked without firejail. Although I have only tested this in a VM.

**Comment by crass** [comment]
@asdfghjz You probably need to add `--whitelist="$(pwd)/PapersPlease-1.1.65.msi"`.  There may be other whitelists needed too for wine, as I'm unfamiliar with using wine and firejail.  It does seem odd that `system32` in seems to map to your users `$HOME` dir.

**Comment by reinerh** [comment]
I think it searches in system32 if it can't find the specified file in the current directory (which firejail is preventing).
You could copy the file into your wine C: drive (~/.wine/drive_c/) and run it from there. That should work without any profile changes or additional whitelists.

**Comment by rusty-snake** [comment]
@asdfghjz still a problem?

**Comment by rusty-snake** [comment]
@asdfghjz I'm closing here due to inactivity, please fell free to reopen if you have more questions.
