### ISSUE TITLE
Execute firecfg on every change?

### ISSUE THREAD

**Issue by francoism90** [netblue30/firejail#2226]
To use Firejail as default, one can use `# firecfg` to create symlinks and fix `*.desktop` files.

Would it be useful to have a package manager hook and/or systemd service to allow checking and recreating this on every boot?

```
# firejail@.service -> firejail@archie.service
[Unit]
Description=Creates symbolic links for Firejail

[Service]
Type=oneshot
ExecStart=/usr/bin/firecfg
ProtectSystem=strict
ReadWritePaths=/etc/firejail
ReadWritePaths=/usr/local/bin
ReadWritePaths=/home/%i/.local/share/applications
Environment=SUDO_USER=%i
Environment=HOME=/home/%i

[Install]
WantedBy=multi-user.target
```

Is this concerned as a bad practice?

Thanks.

**Comment by SkewedZeppelin** [comment]
But why?

**Comment by francoism90** [comment]
@SkewedZeppelin When installing new and/or removing applications, entries are getting out-of-dated or not symlinked at all.

**Comment by reinerh** [comment]
For Debian-based systems you could install a trigger in /etc/apt/apt.conf.d/ that will run firecfg each time after you install something with apt (something like `Dpkg::Post-Invoke {"firecfg";}` (untested)).
https://wiki.debian.org/AptConf

**Comment by francoism90** [comment]
@reinerh That's actually a better idea! On Arch Linux pacman hooks are available and can do the same thing. :)

**Comment by SkewedZeppelin** [comment]
@francoism90 feel free to make a PR adding the systemd unit file and the pacman alpm hook to the contrib directory
