### ISSUE TITLE
Signature file on sourceforge.net specifies wrong hash

### ISSUE THREAD

**Issue by genodeftest** [netblue30/firejail#223]
The signature file [firejail-0.9.36.asc](http://sourceforge.net/projects/firejail/files/firejail/firejail-0.9.36.asc) from http://sourceforge.net/projects/firejail/files/firejail/ specifies a line`Hash: SHA1`. This hash is instead a SHA256 hash of the file.

**Comment by netblue30** [comment]
SHA1 line is added by GnuPG in the process of signing the message. I think, when you verify the message it defaults to SHA1 if for some reasons you cannot use the public/private keys.

https://www.gnupg.org/download/integrity_check.html

**Comment by genodeftest** [comment]
I don't know how you get to create this hash, but I am unable to reproduce this. The signature file contains SHA256 hashes but states that it has SHA1 hashes. So the hashes are actually valid SHA256 hashes, but they are incorrectly labeled.

**Comment by netblue30** [comment]
"--digest-algo SHA256" fixed it, thanks for the Fedora link! Next release it will be with SHA256.
