### ISSUE TITLE
transfer.sh wil be shutdown on 30th November

### ISSUE THREAD

**Issue by Vincent43** [netblue30/firejail#2230]
This is relevant for our CI: https://github.com/netblue30/firejail/blob/master/.travis.yml#L15

https://transfer.sh/
https://old.reddit.com/r/commandline/comments/9shdl5/transfersh_will_shutdown_30th_of_november_2018/

**Comment by smitsohu** [comment]
ping @probonopd

**Comment by netblue30** [comment]
I commented the transfer.sh lines out for now.

**Comment by SkewedZeppelin** [comment]
It seems transfer.sh is not shutting down anymore
From https://transfer.sh

> After running and supporting transfer.sh for 4 years on my own, I’m happy to announce we are partnering with Storj Labs to keep the project going. From day one, the transfer.sh code has been open source. Storj has a commitment to open source sustainability and reached out to help us find a way to keep our project alive. Stay tuned for updates on the partnership with Storj, but for now, please continue to enjoy the service!
Blue skies, Remco Verhoef


But as @reinerh mentioned, are people really using these?
