### ISSUE TITLE
[Question] How secure is WINE with the defualt profile?

### ISSUE THREAD

**Issue by asdfghjz** [netblue30/firejail#2233]
**Question**: How secure is WINE with the default profile?

Especially for non-free gaming? What files does WINE require access to?

**Comment by Vincent43** [comment]
I already gave you the answer: https://github.com/netblue30/firejail/issues/2219#issuecomment-434025708

The default profile does what is specified inside it. Nothing more, nothing less: https://github.com/netblue30/firejail/blob/master/etc/wine.profile
