### ISSUE TITLE
Firejailed APPs are not seeing my Network

### ISSUE THREAD

**Issue by thebunnyrules** [netblue30/firejail#2234]
Problem:

No matter what I try, I can't seem to get firejailed app to see my network.
I have a Application Based Firewall called Douane but even when I've completely disabled it, firejail is not seeing the internet.
I'm on Ubuntu 17.10 (gnome 3.26). FJ 0.9.50. user account does not have root privileges but I've tried creating one with sudo priveleges and fj still doesn't see the internet on that one.
I'm on Wayland but the same problem occurs on X11.

What I've Tried:

-using my compiled version of FF (62 which has a custom aa profile that I've been using without a problem in enforce mode), using Ubuntu Apt Installed version of FF (61 which comes with a generic AA profile that ubuntu wrote), Web/epiphany, transmission with a ubuntu18.10.iso torrent which usually has tons of seeders.
-disabling my firewall (douane), removing the firewall service from autostart and rebooting
-disabling apparmor, switching apparmor to complain mode for the apps I'm testing.
-use the firjail --net=<nameOFmyWIFInetwork> option
-I tried using firejail --dns=8.8.8.8 and it gave can't fine /etc/resolv.conf error.
-tried using firetools/fireconfig and selecting firefox+default profile from there. tried making my own custom profile from there.

Firejail Version:

firejail --version
firejail version 0.9.50

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- bind support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- git install support is disabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

**Comment by netblue30** [comment]
Try to move to firejail version 0.9.56 (download the deb file from https://sourceforge.net/projects/firejail/files/firejail/), and we'll take it from there. There were quite a number of fixes since 0.9.50.

**Comment by thebunnyrules** [comment]
I've just installed 0.9.56 as you've suggested. It seems that the problem has been resolved. Thanks for your help!
