### ISSUE TITLE
Question: Firejail vs using Apparmor only? What are some the advantages 

### ISSUE THREAD

**Issue by thebunnyrules** [netblue30/firejail#2248]
Hi, I'm just starting with Firejail. It seems like a really interesting tool and I'm trying to understand it a little more. Not sure if this is the appropriate place to ask but I didn't know where else to post my question.

I'm currently using an AppArmor enforce mode profile that I've heavily modded and tweaked to limit Firefox's access to my system resources, home directory, documents and configuration files... 

I was just wondering what additional security features does firejail offer over running Apparmor alone? What is a SUID sandbox?

**Comment by topimiettinen** [comment]
Firejail uses private mount namespaces to achieve similar access controls compared to Apparmor and capability restrictions are also similar. In addition to those, Firejail can set up system call filtering with seccomp and restrict networking. Then Apparmor can restrict mapping of files to memory which Firejail is not able to do.

Executing SUID programs elevate user's privileges temporarily. This is used in Firejail to for example setup mounts, which is not allowed normally.

**Comment by Vincent43** [comment]
In general you may use AppArmor OR firejail but not both at the same time for the same app as this will lead only for trouble. If you set tight AppArmor profile already then you may stick with it. I assume you know that AppArmor available features vary across kernels versions and distros.

**Comment by topimiettinen** [comment]
I see, maybe the paths of the private mounts used by Firejail do not match what AppArmor expects? Anyway, it should be possible to use Firejail for seccomp and network control, those will not conflict with AppArmor.

**Comment by thebunnyrules** [comment]
I did notice that some things in AppArmor profile were ignored when I ran firejail. Files that I specifically denied access to reading can be accessed. So, I don't think they're complimentary. 

@Vincent43 What do you mean when you say that firejail can be easily circumvented? Can you be more specific with some examples?

**Comment by SkewedZeppelin** [comment]
> What do you mean when you say that firejail can be easily circumvented? Can you be more specific with some examples?

As a user you can simply directly run a known vulnerable application and potentially compromise the computer.
As a malicious program you can abuse DBus or the X server and take control of the computer from there, which you would then use another vulnerable program to elevate privs.

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this as the discussion seems to have died out ;)
