### ISSUE TITLE
[rfe] add option to blacklist all `~/.*` directories

### ISSUE THREAD

**Issue by genodeftest** [netblue30/firejail#225]
In many cases you need to blacklist all but a few "dot" directories in ${HOME}. This is because applications should usually not have access to config files of most other applications. Is there any simple way to do this? If not implementing such a feature would be nice.

A general option for that would be nice, since blacklisting is always risky since whoever wrote the config might have missed something.

With this option one could get rid of most `blacklist` config options, including most of etc/disable-common.inc and etc/disable-secret.inc.

**Comment by genodeftest** [comment]
"Blacklist all but a few" essentially is whitelisting. I meant `~/.*` directories should generally be forbidden, but they can still be whitelisted.

**Comment by the8472** [comment]
Yes, but I mean if you use the whitelist feature then everything else in the home dir is automatically blacklisted, which obviously includes the dot dirs.

**Comment by genodeftest** [comment]
I just want to blacklist the `~/.*` directories. That's why I opened this issue.

An example: Your PDF viewer might need access to some config files in ~/.local and ~/.config, but it doesn't need access to any other `~/.*` folder. It needs access to things like Desktop and Downloads directory, so those should probably be allowed. Since users sometimes have other directories below `${HOME}` with relevant non-config/non-cache data in it, I won't blacklist everything but those two directories.

I haven't figured out how to whitelist all directories in ${HOME} not starting with a `.`. That's what I need.

**Comment by netblue30** [comment]
OK, I'll add a --blacklist-alldotfiles option!

**Comment by netblue30** [comment]
It is working today:
`````
$ firejail --blacklist=.*
`````
All dot files under home are blacklisted.
