### ISSUE TITLE
Symlinks break applications or firejail

### ISSUE THREAD

**Issue by genodeftest** [netblue30/firejail#226]
Steps to reproduce:
1. make sure `firejail firefox` is working
2. exit firefox
3. create a symlink to firefox, e.g. by running `ln --symbolic /usr/bin/firefox foo`
4. run firefox from symlink: `firejail foo`

What happens:
Firefox is not sandboxed. It is not starting either because it cannot access its own config files.

Reason:
Firejail profiles are applied matching executable names. In cases of symlinks the symlink name is the executable name. Some applications make use of that, e.g. vim/vimdiff, bzip2/bunzip2, bzcat/bzip2, …, so disallowing symlinks cannot be done.

Is it possible to follow symlinks before running an application? Note that name resolution depends on the current working directory.

**Comment by netblue30** [comment]
Fixed, thanks!
