### ISSUE TITLE
For --private-tmp expose /tmp/.X11-unix as read-only

### ISSUE THREAD

**Issue by Vincent43** [netblue30/firejail#2269]
Currently in case of `private-tmp` option we mount an empty `/tmp` with [whitelisted `/tmp/.X11-unix`](https://github.com/netblue30/firejail/blob/7c903b45c2f2c7ae2785deedfc03d76a0cda36fd/src/firejail/fs.c#L1564). Additionally we may expose it as read-only. [The read-only mount flag does not prevent using connect() syscall on the socket](https://wiki.archlinux.org/index.php/Systemd-nspawn#Use_an_X_environment).

**Comment by chiraag-nataraj** [comment]
@Vincent43 Is the easiest way to do this to build it in to `--private-tmp` or to just add it to the profiles directly?

**Comment by Vincent43** [comment]
I think it should be built into `--private-tmp` directly.

**Comment by chiraag-nataraj** [comment]
Going to close this as this should now be implemented.
