### ISSUE TITLE
Memory Limit

### ISSUE THREAD

**Issue by silgon** [netblue30/firejail#2270]
Is there a way to limit the memory that a process uses with `firejail (0.9.56-LTS)`. I'm interested in using it with thunderbird. So maybe there is something to be written in the profile? I don't find any documentation about it.

Also, in the man file, I found  `RES    Resident Memory Size (KiB), sandbox non-swapped physical memory.  It is a sum of the RES values for all processes running in the sandbox.` but I have no idea how or where to apply it.

Thanks in advance.

**Comment by smitsohu** [comment]
We have something in Firejail ( `--rlimit-as`), but not in the LTS version.

As an alternative consider [prlimit](http://man7.org/linux/man-pages/man1/prlimit.1.html), it doesn't need any root privileges. The prlimit man pages fails to mention however that limits on RSS are without effect in contemporary kernels.
But something like `prlimit --as=100000000 firejail` should be possible.

**Comment by chiraag-nataraj** [comment]
@silgon, is this still an issue? Were you able to upgrade your firejail to take advantage of the feature?

**Comment by silgon** [comment]
Sorry, I'm not using it anymore, so I couldn't tell. I'll close the issue for now. Thanks for the update. =)
