### ISSUE TITLE
read-only of PATH and LD_LIBRARY_PATH is incomplete

### ISSUE THREAD

**Issue by genodeftest** [netblue30/firejail#228]
[etc/disable-common.inc:120](https://github.com/netblue30/firejail/blob/master/etc/disable-common.inc#L120)
```
# The user ~/bin directory can override commands such as ls
read-only ${HOME}/bin
```
tries to disable changing files in user-controlled folders in ${PATH}. There are several issues with that:
1. ${PATH} not only contains `~/bin`, but also `~/.local/bin` on some platforms (e.g. Fedora 23)
2. ${PATH} can be changed to contain other folders
3. ${LD_LIBRARY_PATH} is as important. Same things apply here.

I've tried changing this line to
```
read-only ${PATH}
```
and
```
read-only ${PATH}/
```
but both solutions don't work.

**Comment by netblue30** [comment]
"read-only ${PATH}" should be working in this moment. I am using for ${PATH} the real PATH environment variable, with /bin, /sbin/, /usr/bin and /usr/sbin added in case they are missing from PATH.

I live out LD_LIBRARY_PATH for now. Probably I'll end up implementing a ${LD_LIBRARY_PATH} in profiles.
