### ISSUE TITLE
Can't access /mnt despite ignore disable-mnt and whitelists

### ISSUE THREAD

**Issue by seonwoolee** [netblue30/firejail#2282]
I'm trying to set up Firejail for VLC. I have media files under /mnt/NAS that I want it to access.

Here's the profile I created:
```
ignore disable-mnt
whitelist /mnt/NAS
whitelist /mnt/NAS/replicate
whitelist /mnt/NAS/replicate/TV
whitelist /mnt/NAS/replicate/Movies
whitelist /mnt/NAS/local/TV
whitelist /mnt/NAS/local/Movies
whitelist /mnt/NAS/local/Plex
```

I get the following output when I use `--debug-whitelists`
```
Reading profile /home/seonwoo/.config/firejail/vlc.profile
Parent pid 9359, child pid 9360
Debug 405: new_name #/mnt/NAS#, whitelist
Removed whitelist/nowhitelist path: whitelist /mnt/NAS
	expanded: /mnt/NAS
	real path: (null)
	realpath: Permission denied
Debug 405: new_name #/mnt/NAS/replicate#, whitelist
Removed whitelist/nowhitelist path: whitelist /mnt/NAS/replicate
	expanded: /mnt/NAS/replicate
	real path: (null)
	realpath: Permission denied
Debug 405: new_name #/mnt/NAS/replicate/TV#, whitelist
Removed whitelist/nowhitelist path: whitelist /mnt/NAS/replicate/TV
	expanded: /mnt/NAS/replicate/TV
	real path: (null)
	realpath: Permission denied
Debug 405: new_name #/mnt/NAS/replicate/Movies#, whitelist
Removed whitelist/nowhitelist path: whitelist /mnt/NAS/replicate/Movies
	expanded: /mnt/NAS/replicate/Movies
	real path: (null)
	realpath: Permission denied
Debug 405: new_name #/mnt/NAS/local/TV#, whitelist
Removed whitelist/nowhitelist path: whitelist /mnt/NAS/local/TV
	expanded: /mnt/NAS/local/TV
	real path: (null)
	realpath: Permission denied
Debug 405: new_name #/mnt/NAS/local/Movies#, whitelist
Removed whitelist/nowhitelist path: whitelist /mnt/NAS/local/Movies
	expanded: /mnt/NAS/local/Movies
	real path: (null)
	realpath: Permission denied
Debug 405: new_name #/mnt/NAS/local/Plex#, whitelist
Removed whitelist/nowhitelist path: whitelist /mnt/NAS/local/Plex
	expanded: /mnt/NAS/local/Plex
	real path: (null)
	realpath: Permission denied
Mounting tmpfs on /mnt directory
```

I don't know why VLC still can't access /mnt/NAS (it can access /mnt, shown as an empty directory). 

If it matters, /mnt/NAS is shared over NFS

**Comment by SkewedZeppelin** [comment]
Version? Distro? Full command? Full profile?

also you do not need these
```
whitelist /mnt/NAS
whitelist /mnt/NAS/replicate
```

**Comment by smitsohu** [comment]
Is /mnt a mountpoint (what does `mountpoint /mnt` say?)

If it is, could you share some more information about it? For example something like `findmnt | grep /mnt | grep -v /mnt/`

**Comment by smitsohu** [comment]
Maybe related to #2114.

**Comment by smitsohu** [comment]
I don't know much about NFS, so this is kind of speculative, but if you mount the NFS with `no_root_squash` option, would it fix the issue?

Note however that this option has [own security implications](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sect-security_guide-securing_nfs-do_not_use_the_no_root_squash_option).

**Comment by seonwoolee** [comment]
Trying `sudo mount 192.168.1.2:/mnt/master /mnt/NAS -t nfs4 -o not_root_squash` results in `mount.nfs4: an incorrect mount option was specified`

**Comment by smitsohu** [comment]
[It seems](https://linux.die.net/man/5/exports) it has to go into /etc/exports (does that make sense?)

**Comment by chiraag-nataraj** [comment]
Is this still an issue? If so, can you check if you have `disable-mnt` enabled in `/etc/firejail/firejail.config`?

**Comment by seonwoolee** [comment]
Yes, `disable-mnt` is enabled in `/etc/firejail/firejail.config`. But despite having `ignore disable-mnt` in `vlc.profile`, I still can't access `/mnt/NAS` when I open VLC with firejail. 

If I disable `disable-mnt` in `/etc/firejail/firejail.config` then it works, but as I understand it `ignore disable-mnt` in `vlc.profile` should be taking care of that.

**Comment by rusty-snake** [comment]
@seonwoolee nope, if you set this in firejail.config you can not ignore it by `ignore`, you need to revert this in `firejail.config` and add `disable-mnt` to your `globals.local`, because then you can do `ignore disable-mnt` in your `vlc.local`.

```
# Disable /mnt, /media, /run/mount and /run/media access. By default access
# to these directories is enabled. Unlike --disable-mnt profile option this
# cannot be overridden by --noblacklist.
# disable-mnt no
```
I think we should add that `--ignore` also didn't work.

**Comment by seonwoolee** [comment]
Gotcha. Thanks.

**Comment by rusty-snake** [comment]
> I think we should add that --ignore also didn't work.

done via 903adee.
