### ISSUE TITLE
"firejail --help" behavior after clean installation

### ISSUE THREAD

**Issue by tobwen** [netblue30/firejail#2283]
# Background
firejail got installed on a clean Debian Stretch system using `make install-strip`
# Expected behavior
`firejail --help` should show help.
# Current behavior
`firejail --help` directly starts firejail and exists it.
# Workaround
`firejail --help --` to reach help for the first time. After that, `firejail --help` works as expected.
# Comments
Perhaps there's something missing in the Makefile?

**Comment by tobwen** [comment]
Sure, the backport works (I used it before, but wanted to try a more recent version). 

Sine it works after using the workaround once, I thought there's only a small part missing in the Makefile, which "initializes" something for the first time.

**Comment by SkewedZeppelin** [comment]
I just did a fresh install of Debian 9.6 into a VM and then installed firejail from git.
Was unable to reproduce.
`firejail --help` worked on the first run, no issue.

More exact steps:
- Boot Debian 9.6 netboot
- Walk through installer
- Chose GNOME
- Finished install
- Logged in, opened GNOME Terminal
- `apt update && apt upgrade`
- `apt install build essential`
- `git clone https://github.com/netblue30/firejail.git`
- `./configure && make`
- `sudo make install-strip`
- Opened a new terminal
- `firejail --help` #worked fine

**Comment by tobwen** [comment]
My workflow is similar:
```
./configure --prefix=/usr/local/stow/firejail
make && make install-strip
stow --dir=/usr/local/stow/ -R firejail
```
I'll close this for now, maybe I did something very wrong. Thanks for trying :-)
