### ISSUE TITLE
firejail always detects a sandbox when running under WSL

### ISSUE THREAD

**Issue by mqudsi** [netblue30/firejail#2284]
I'm unable to use firejail (to test for app compatibility) due to it always thinking it's running in a sandbox anytime I run it under WSL.

```
mqudsi@Blitzkrieg /m/d/r/fish> firejail --shell=build/fish
Warning: shell-related command line options are disregarded - using SHELL environment variable
Warning: an existing sandbox was detected. /bin/bash will run without any additional sandboxing features
mqudsi@Blitzkrieg:/mnt/d/rand/fish$ exit
exit
mqudsi@Blitzkrieg /m/d/r/fish> uname -a
Linux Blitzkrieg 4.4.0-17763-Microsoft #55-Microsoft Sat Oct 06 18:05:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
mqudsi@Blitzkrieg /m/d/r/fish> firejail --version
firejail version 0.9.57
```

**Comment by SkewedZeppelin** [comment]
I don't think WSL actually implements any of the kernel features that firejail needs, because it isn't actually running the Linux kernel.

That being said the error message should probably be tweaked for different cases like this.

**Comment by chiraag-nataraj** [comment]
Let's go ahead and close this as wontfix for now (although apparently WSL 2 will actually run a Linux kernel? That may very well change the situation).

**Comment by erndob** [comment]
To anyone reading this, WSL 2 doesn't work either. At least the 19041 build.

**Comment by agnosticlines** [comment]
Hey sorry to bump this old issue but I've compiled a custom kernel with everything needed for firejail, apparmor, selinux, etc and now running into this, is there any workaround for this?

**Comment by rusty-snake** [comment]
Try to start with `container=lxc`.

**Comment by agnosticlines** [comment]
> Try to start with `container=lxc`.

Yep that works! Although now running into a weird issue where it takes like 20 seconds to launch if I give it a profile, --noprofile is instant, will look into that. Thanks though!
