### ISSUE TITLE
KeepassXC 2.3.4 fails in MX Linux. QXcbConnection: Could not connect to display :0.0

### ISSUE THREAD

**Issue by brakenow** [netblue30/firejail#2289]
firejail keepassxc
Reading profile /etc/firejail/keepassxc.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 5687, child pid 5688
Warning: skipping machine-id for private /etc
Private /etc installed in 3.16 ms
1 program installed in 6.34 ms
Child process initialized in 60.30 ms
QXcbConnection: Could not connect to display :0.0

Parent is shutting down, bye...

**Comment by mxljw** [comment]
> Does `firejail --noprofile keepassxc` work?

Yes, KeePassXC opens under firejail using the --noprofile option

**Comment by rusty-snake** [comment]
@mxljw does `firejail --ignore=private-etc --ignore=private-tmp --ignore=no3d --ignore=machine-id --ignore="net none" --ignore=nodbus --ignore=protocol --ignore=seccomp --ignore=noroot keepassxc`works?
if so try to remove ignore for ignore to figure out which option cause the issue.
if not try to comment all includes in keepassxc.profile

**Comment by rusty-snake** [comment]
@brakenow @mxljw 
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
