### ISSUE TITLE
Proper chroot support for graphical apps

### ISSUE THREAD

**Issue by Alexander--** [netblue30/firejail#229]
Right now one has to go to nontrivial lengths to make chrooted configs work for graphical apps. There is already an example of sandbox app, that has got that right: https://github.com/brain0/appjail. Too bad, it is not very maintained and fails with new versions of some dependencies.

It would be nice, if firejail had an analog of `-X --x11-trusted`  and few other appjail options.

**Comment by netblue30** [comment]
Thanks for appjail link, I'll take a look. I am moving the discussion here: https://github.com/netblue30/firejail/issues/57
