### ISSUE TITLE
Error running Franz appimage

### ISSUE THREAD

**Issue by nemokapetanos** [netblue30/firejail#2290]
Hi,

I get the following error when I run Franz with firejail:
```
firejail --appimage ./franz-5.0.0-beta.19-x86_64.AppImage
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 23310, child pid 23314
Dropping all Linux capabilities and enforcing default seccomp filter
Child process initialized in 75.12 ms
{ Error: EACCES: permission denied, mkdir '/home/nemo/.config/Franz/recipes/temp'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.mkdirsSync (/run/firejail/appimage/.appimage-23310/resources/app.asar/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at Object.emptyDirSync (/run/firejail/appimage/.appimage-23310/resources/app.asar/node_modules/fs-extra/lib/empty/index.js:34:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-23310/resources/app.asar/index.js:38:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-23310/resources/app.asar/index.js:210:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/nemo/.config/Franz/recipes/temp' }

Parent is shutting down, bye...
```

I'm running firejail version 0.9.52 that is packaged with Ubuntu Mate 18.04. What do I need to do to run the Franz appimage in Firejail?

Thanks!

**Comment by smitsohu** [comment]
> firejail --appimage ./franz-5.0.0-beta.19-x86_64.AppImage
Reading profile /etc/firejail/default.profile

Firejail picks the default profile, which leads to ~/.config/Franz being blacklisted. And then this happens:

> Error: EACCES: permission denied, mkdir '/home/nemo/.config/Franz/recipes/temp'

So you would need to start it like: `firejail --appimage --profile=/etc/firejail/franz.profile ./franz-5.0.0-beta.19-x86_64.AppImage`

**Comment by nemokapetanos** [comment]
Thank you for that information! When I ran the command you suggested, I get the following error message:

```
Reading profile /etc/firejail/franz.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 20656, child pid 20659
Dropping all Linux capabilities and enforcing default seccomp filter
Error: --shell=none configured, but no program specified

Parent is shutting down, bye...
AppImage unmounted
```
Which shell do I need to specify? Thanks again for the help!

**Comment by smitsohu** [comment]
It looks like this is a bug that got fixed in version 0.9.54, the relevant commit is 1738bbf7181d6c3b6d9f82bfa5b3f6d21ad503c3

You will need to upgrade your Firejail. For Ubuntu/Mint there is a PPA which should keep you up to date.

**Comment by smitsohu** [comment]
Or, alternatively, if you don't want to upgrade, what should also work is `firejail --appimage --ignore=shell profile=/etc/firejail/franz.profile ./franz-5.0.0-beta.19-x86_64.AppImage`

**Comment by smitsohu** [comment]
> the window title bar it says that I'm running Franz as a superuser - which I think isn't correct. This is probably a Ubuntu Mate bug

yes, it is known bug in Mate.

**Comment by nemokapetanos** [comment]
Thanks for confirming that bug - that's given me some peace of mind :)
