### ISSUE TITLE
Firejail Apparmor Support Not Working (Even Though it's Been Enable During BUILD)

### ISSUE THREAD

**Issue by thebunnyrules** [netblue30/firejail#2291]
Hello,

I'm trying to run firejail with apparmor support. I've tried with both the ubuntu build which comes from the cosmic repo and the latest source from git (0.9.57, libappormor-dev is already install) built with:

`./configure --prefix=/usr --enable-apparmor`

Entering:

`firejail --version `

on both gives:
```

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```
but when I try to run:

`firejail --apparmor firefox`

my apparmor profile is still being ignored. I have aa-enforce running on firefox and it's working perfectly without firejail, so I know it's not the profile or apparmor. 

Any ideas on how I can trouble shoot this? THANKS!!!!

**Comment by Vincent43** [comment]
Which profile is ignored? Generic one from firejail under `/etc/apparmor.d/firejail-default` or firefox specific one from` /etc/apparmor.d/usr.bin.firefox` ?

**Comment by thebunnyrules** [comment]
Hi Vincent, thanks for getting back to me so quickly. I'll play around with  `/etc/apparmor.d/firejail-default`, see what happens and post a follow up. Thanks!

**Comment by Vincent43** [comment]
You may add your own customizations to `/etc/apparmor.d/local/firejail-local` so they will be persistent after firejail update.

**Comment by thebunnyrules** [comment]
So, if I want to add per app policy, should I use a change-hat in the firejail profile?

**Comment by thebunnyrules** [comment]
So, is it possible to do per-application apparmor customization via firejail-d firejail-default or firejail-local?

Does firejail-default support hat change or sub profiles?

I tried to do a change hat inside firejail-default for firefox but it's being ignored. For example
```
....

##########
# We let Firejail deal with mount/umount functionality.
##########
mount,
remount,
umount,
pivot_root,

# Site-specific additions and overrides. See local/README for details.
#include <local/firejail-local>

^firefox {

	deny /home/lapinot/.bash_history rwk,
}
}
```
I also tried `^/opt/firefox.wayland/firefox {...` and also tried `profile firefox {...` but no dice either. I restarted apparmor each time I tried to apply a new change and restarted successfully so there is no syntax error as far as I can tell...

**Comment by Vincent43** [comment]
It's not possible to do per-application modifications. It's one-size-fits-all.

**Comment by chiraag-nataraj** [comment]
Seems like this was answered, so I'll go ahead and close this. @thebunnyrules, pleas feel free to re-open if you have further questions.
