### ISSUE TITLE
Spotify doesn't launch on Arch Linux

### ISSUE THREAD

**Issue by Algebro7** [netblue30/firejail#2292]
I'm using the `spotify` package from the AUR with firejail, no customizations to the firejail profile and I'm getting the following error:

```
$ firejail spotify
Reading profile /etc/firejail/spotify.profile
Reading profile /etc/firejail/globals.local
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 1218, child pid 1219
Warning: skipping pki for private /etc
Warning: skipping crypto-policies for private /etc
Private /etc installed in 24.30 ms
Warning: skipping spotify for private /opt
Private /opt installed in 0.03 ms
5 programs installed in 4.33 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: /sbin directory link was not blacklisted
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 98.02 ms
/usr/local/bin/spotify: line 2: /usr/share/spotify/spotify: Permission denied
```

I tried whitelisting `/usr/share/spotify` but that didn't make any difference. Is there something special I need to do to make this work with the AUR package?

**Comment by polyzen** [comment]
How'd you install Spotify? Works here with the `spotify-stable` AUR package.

**Comment by Algebro7** [comment]
Thanks a bunch for the information--I switched to `spotify-stable` and it's working now.

**Comment by Fred-Barclay** [comment]
In case we see this later -- what version of firejail are you using? I'm using the latest build from git (0.9.57) and `firejail spotify` works without errors (and I have the ordinary spotify package from the AUR, not spotify-stable).

Thanks!

**Comment by polyzen** [comment]
On December 8, 2018 12:50:22 PM EST, Fred Barclay <notifications@github.com> wrote:
>In case we see this later -- what version of firejail are you using?
>I'm using the latest build from git (0.9.57) and `firejail spotify`
>works without errors (and I have the ordinary spotify package from the
>AUR, not spotify-stable).
>
>Thanks!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/netblue30/firejail/issues/2292#issuecomment-445477097

Seems like they used a different install method.

-- 
Best,
polyzen

**Comment by Algebro7** [comment]
I was using the regular `spotify` package as well as `firejail-apparmor`, both from AUR. Looks like firejail version 0.9.56.

**Comment by Fred-Barclay** [comment]
Thanks! As an uneducated guess I'd suspect some incompatibility with `firejail-apparmor`. ;)

**Comment by Vincent43** [comment]
When spotify is used with `--apparmor` option, you need to add `/usr/share/spotify/** ix,` rule in `/etc/apparmor.d/local/firejail-local`.
