### ISSUE TITLE
join option doesn't apply seccomp filter

### ISSUE THREAD

**Issue by smitsohu** [netblue30/firejail#2296]
Terminal one: `firejail --noprofile --seccomp --name=joinme`
Terminal two: `firejail --join=joinme cat /proc/self/status | grep Seccomp`

yields `Seccomp: 0`

Dropping capabilities works fine.

**Comment by netblue30** [comment]
Same problem on LTS branch. I'll look at all the sandbox settings, probably there is more to come.

**Comment by netblue30** [comment]
Ugly bug, it got broken at least one year ago, thanks!
