### ISSUE TITLE
firefox profile and adobe apps

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#230]
will need to whitelist .macromedia and .adobe
They contain important stuff for flash applications ( video settings, flash games, game saves etc...).
also LSOs use these folders :(
I think acrobat reader also uses them, but i'm not using that.

**Comment by netblue30** [comment]
I cannot add support for them by default, but you can modify your profile files to allow it. I assume you need this support in Firefox: include the following four lines in /etc/firejail/firefox.profile (top of the file):
`````
whitelist ~/.macromedia
whitelist ~/.adobe
noblacklist ~/.macromedia
nobalcklist ~/.adobe
`````

**Comment by pirate486743186** [comment]
hmmm, what about having them commented out, with an explanation?
