### ISSUE TITLE
Gwenview and baloo blacklist violation

### ISSUE THREAD

**Issue by francoism90** [netblue30/firejail#2306]
Please see journal:
```
$ journalctl -xe
dec 20 13:41:01 desktop firejail[10320]: blacklist violation - sandbox 10259, exe gwenview, syscall open64, path /proc/sys/kernel/core_pattern
dec 20 13:41:01 desktop firejail[10320]: blacklist violation - sandbox 10259, exe gwenview, syscall open64, path /home/user/.config/baloofilerc
```
Think both permissions are needed to allow indexing.

**Comment by smitsohu** [comment]
Don't worry about it. I'm seeing tons of blacklist violations from Gwenview, and all of it is noise.

In case you don't want Gwenview/Firejail to fill your syslog, just add `ignore tracelog` to /etc/firejail/gwenview.local. It might be a good idea to even comment out `tracelog` in the default Gwenview profile.

**Comment by francoism90** [comment]
@smitsohu Thanks for your reply and the given details. :)
I'll ignore the warning and take a look at `tracelog`.
