### ISSUE TITLE
Can't create run directory without suid-root

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#2310]
I compiled firejail with `--disable-suid` and tried running it, but it fails to start:
```
Error mkdir: util.c:1014 create_empty_dir_as_root: Permission denied
```
It tries to create its runtime hierarchy in `/run/firejail`, which is not possible as unprivileged user.
If this is not supported, it should check the uid and print a more friendly error message if the user is not root.
If an unprivileged user should be able to run it (without suid-root), maybe it can create required directories in the user's home directory.

**Comment by chiraag-nataraj** [comment]
Seems like this was answered. @reinerh, I'll go ahead and close this, but please feel free to re-open if you have further questions.

**Comment by reinerh** [comment]
It was actually more a bug report or feature request than a question...

If firejail does not support being run without suid-flag, then this should be checked and printed.
If only a subset of the features is working without suid, then it should give a better explanation what failed (other than "permission denied") and maybe workaround it if possbile (like falling back to a directory that is actually writable by the user).
