### ISSUE TITLE
Can't open keepassxc attachments while using firejail

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#2311]
Can't open attachments while using firejail version 0.9.56 or master branch on up to date stable Manjaro KDE and keepassxc with default firejail profile, i'm getting  this keepassxc error in console:

`Unable to detect a launcher for 'file:///tmp/tEMESW.New.rtf'` 

thanks

**Comment by rusty-snake** [comment]
@Lockdis Hi.
Works `firejail --noprofile keepassxc`?
Works `firejail --ignore=private-tmp keepassxc`?

**Comment by Lockdis** [comment]
it's working with `firejail --noprofile keepassxc?`
and not working with `firejail --ignore=private-tmp keepassxc`

**Comment by SkewedZeppelin** [comment]
This is expected behaviour.
See https://github.com/netblue30/firejail/issues/1718#issuecomment-406819438

**Comment by Lockdis** [comment]
but even if i disable firejail on Kate i can't launch it from firejailed keepass, is a security mesure?

**Comment by rusty-snake** [comment]
@Lockdis well, note that it is dangerous.
```
$ firejail --ignore=private-bin --ignore=private-etc keepassxc
$ # OR permanent
$ echo -e "ignore private-etc\nignore private-bin" >> ~/.config/firejail/keepassxc.local
```

**Comment by rusty-snake** [comment]
Closing here, because the account starting the topic was deleted and it's not a real bug.
