### ISSUE TITLE
Cherrytree should not connect to any network

### ISSUE THREAD

**Issue by tinmanx** [netblue30/firejail#2317]
I tried posting an issue earlier but something went wrong, so im re-posting this.

as said in the title, cherrytree should not use the network.
It should not have these:
`protocol unix,inet,inet6,netlink`
`netfilter`

Instead it should have this:
`net none`

I have already tried opening cherrytree with these changes but i do not see anywhere in the terminal where it _should_ say something like `Could not open network socket`

Am i not supposed to get some kind of evidence showing that the network socket is closed?  I also tried it with `--net=none` in the command.

**Comment by SkewedZeppelin** [comment]
I just skimmed through its documentation and don't see it needing network access.
I've pushed a commit 28a7d0bcf202ba9e567d6797f3954e3f5bb25483 that makes your changes.

**Comment by tinmanx** [comment]
thanks @SkewedZeppelin 
I just have an question/issue regarding running cherrytree (using my own profile with the new changes you have done in the commit)
Ive noticed a high cpu usage after a while after running cherrytree.

I have the portable version of cherrytree and i also wanted to log any and all errors to a text file so this is my cmd:
`firejail --profile="/media/USB/Profiles/cherrytree.profile" "cherrytree-0.38.6/cherrytree" 2>&1 | ts >> "$Log" &`

1. Is this the correct way of running this with logging it with timestamps?
2. Its been opening and running fine, why do i have high cpu usage after a while? (i see lots of kworkers opening up)
3. If i had to run it `firejail --profile="/media/USB/Profiles/cherrytree.profile" "cherrytree-0.38.6/cherrytree"` without a log, it still doesn't shut down the parent once it opens it up.  Shouldnt this and any app shutdown the parent when it opens the sandbox?

Im trying to understand this. Would appreciate your feedback @SkewedZeppelin
