### ISSUE TITLE
Chromium based apps crash after Check failed: ChrootToSafeEmptyDir()

### ISSUE THREAD

**Issue by probonopd** [netblue30/firejail#2325]
Getting a segfault when trying to run some Chromium for WebEngine based AppImages with Firejail, directly after `Check failed: ChrootToSafeEmptyDir().`

References:
- https://github.com/martinrotter/rssguard/issues/151#issuecomment-338474062
- https://github.com/netblue30/firejail/issues/958
- https://github.com/netblue30/firejail/issues/1306

**Comment by smitsohu** [comment]
Yes, default Firejail seccomp filter and internal QtWebengine sandbox don't play nice with each other, at least when unprivileged user namespaces are enabled (as is the case in Ubuntu and Fedora).

There are already some commits in Firejail master that make it possible to deal with this. f74fa71cf9d549b1607ca5b0c9fb2442e31f72ab by @crass is the primary fix.

In general however, this also means that apps with QtWebengine don't work with the default profile in the moment. They need their own profile with a seccomp filter that doesn't drop the chroot syscall, see the Qutebrowser profile for comparison https://github.com/netblue30/firejail/blob/ae3db84128503c16fd638b5c7bf9408d64ce14ba/etc/qutebrowser.profile#L44

**Comment by smitsohu** [comment]
We believe this has been fixed in 0.9.58. Closing the issue.
