### ISSUE TITLE
Cannot access symlinked config files

### ISSUE THREAD

**Issue by daphniz** [netblue30/firejail#2329]
When I run qutebrowser through firejail, qb cannot access its config
files.  This is because
my ~/.config/ is a symlink to ~/dot/config.  But I can't figure out how to
work with this.  I have tried noblacklisting and whitelisting
~/dot/config/qutebrowser, but to no avail.

**Comment by daphniz** [comment]
I solved it by making ~/.config a directory and symlinking files into
that instead.  But it seems Firejail does not accept it if ~/.config
is a symlink, and I don't know if and if so why that is intended.

Error: user .config is a symbolic link

**Comment by rusty-snake** [comment]
@daphniz to use `~/dot/config` instead of `.config` as your config dir you can also set the env-var `XDG_CONFIG_HOME` like `export XDG_CONFIG_HOME=$HOME/dot/config`
See:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
https://developer.gnome.org/basedir-spec/

**Comment by rusty-snake** [comment]
Or `mount --bind`

**Comment by chiraag-nataraj** [comment]
Seems like the OP found a solution to their issue (although perhaps not entirely ideal). I'll go ahead and close this, but @daphniz, please feel free to re-open if you have more questions or you want to convert this to an enhancement request.
