### ISSUE TITLE
Invalid path $DOWNLOADS - problem with international characters

### ISSUE THREAD

**Issue by xpolish** [netblue30/firejail#233]
Hi,
Programs using DOWNLOADS environment don't starts, if international characters used in path.

$ firejail opera
Parent pid 12119, child pid 12120
Error: invalid whitelist path /home/polish/Stažené

Problems are international characters. If I edit .config/user-dirs.dirs:
XDG_DOWNLOAD_DIR="$HOME/Stažené"
and change "Stažené" to "tmp" firejail works well.

**Comment by netblue30** [comment]
I need you to put back XDG_DOWNLOAD_DIR="$HOME/Stažené", run "firejail --debug opera" and post the output here. Thansk.

**Comment by xpolish** [comment]
Hi,

output follow:

polish@norraena:~$ firejail --debug opera
Command name #opera#
Found opera profile in /etc/firejail directory
Reading profile /etc/firejail/opera.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Using the local network stack
Parent pid 15162, child pid 15163
Initializing child process
PID namespace installed
Mounting tmpfs on /run/firejail/mnt directory
Mounting read-only /bin, /sbin, /lib, /lib32, /lib64, /usr, /etc, /var
Mounting tmpfs on /var/lock
Mounting tmpfs on /var/tmp
Mounting tmpfs on /var/log
Mounting tmpfs on /var/lib/dhcp
Mounting tmpfs on /var/lib/snmp
Mounting tmpfs on /var/lib/sudo
Create the new utmp file
Mount the new utmp file
Cleaning /home directory
Sanitizing /etc/passwd
Sanitizing /etc/group
Disable /etc/firejail
Replaced whitelist path: whitelist /home/polish/.config/opera
extracted Stažené from ~/.config/user-dirs.dirs
Downloads directory resolved as "Stažené"
Error: invalid whitelist path /home/polish/Stažené
Error: cannot establish communication with the parent, exiting...
ESC]0;polish@norraena:

**Comment by netblue30** [comment]
I put in some debug messages. Can you please compile and try the latest git version.

**Comment by xpolish** [comment]
Hello,

Stažené is symbolic link to /data/download/

$ firejail --debug opera
Command name #opera#
Found opera profile in /usr/local/etc/firejail directory
Reading profile /usr/local/etc/firejail/opera.profile
Reading profile /usr/local/etc/firejail/disable-mgmt.inc
Reading profile /usr/local/etc/firejail/disable-secret.inc
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Using the local network stack
Parent pid 6712, child pid 6713
Initializing child process
PID namespace installed
Mounting tmpfs on /run/firejail/mnt directory
Mounting read-only /bin, /sbin, /lib, /lib32, /lib64, /usr, /etc, /var
Mounting tmpfs on /var/lock
Mounting tmpfs on /var/tmp
Mounting tmpfs on /var/log
Mounting tmpfs on /var/lib/dhcp
Mounting tmpfs on /var/lib/snmp
Mounting tmpfs on /var/lib/sudo
Create the new utmp file
Mount the new utmp file
Cleaning /home directory
Sanitizing /etc/passwd
Sanitizing /etc/group
Disable /etc/firejail
Disable /usr/local/etc/firejail
Debug 339: new_name #/home/polish/.config/opera#
Replaced whitelist path: whitelist /home/polish/.config/opera
extracted Stažené from ~/.config/user-dirs.dirs
Downloads directory resolved as "Stažené"
Debug 339: new_name #/home/polish/Stažené#
Debug 381: fname #/data/download#, cfg.homedir #/home/polish#
Error: invalid whitelist path /home/polish/Stažené
Error: cannot establish communication with the parent, exiting...

     Polish

**Comment by netblue30** [comment]
This is why is failing! The link should also be under $HOME. I cannot bring in directories from outside, it would create some very interesting security problems.

**Comment by xpolish** [comment]
Hello,

   you are right. Please add better error description like "Can't using 
$HOME/Donwloads because it is symbolic link outside $HOME."

     Thank you   Polish

**Comment by netblue30** [comment]
Sure, I'll add a description in the man page.
