### ISSUE TITLE
private-opt and private-srv problem

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#2335]
Hello, it is normal that my programs are refusing to start if i use **private-opt** or **private-srv** but  are working if i use **private-opt test**,  **private-srv test** or **blacklist /srv**, **blacklist /opt** ?
using git version

**Comment by SkewedZeppelin** [comment]
iirc yes, if you look there are actually a number of profiles with `private-opt none` because both require arguements

**Comment by Lockdis** [comment]
ho ok thanks,  it was confusing because the others private- do not require argument

**Comment by chiraag-nataraj** [comment]
Going to close since OP left Github and their question seems to have been answered.
