### ISSUE TITLE
JDownloader can't execute web browser

### ISSUE THREAD

**Issue by Tanath** [netblue30/firejail#2336]
When I get a manual captcha and click 'open in web browser' I get an I/O error.

**Comment by SkewedZeppelin** [comment]
This is expected behaviour.
See https://github.com/netblue30/firejail/issues/1718#issuecomment-406819438

**Comment by rusty-snake** [comment]
I'm not sure if its work:`echo "include chromium.profile" >> ~/.config/firejail/JDownloader.local`

Note that this will reduce the security.

**Comment by chiraag-nataraj** [comment]
I don't know about chrome, but firefox detects when it's already running, so one way to get around this is to leave firefox running (ideally in its own sandbox) before starting jdownloader. That way, when it goes to open firefox (which you can set [according to this](https://support.jdownloader.org/Knowledgebase/Article/View/42/14/jd-opens-my-browser-to-display-captchas)), firefox will already be open and you'll be able to solve it.

**Comment by chiraag-nataraj** [comment]
@Tanath Did any of the suggestions work?

**Comment by Tanath** [comment]
@chiraag-nataraj Unfortunately not. Still not using firejail with JDownloader.

**Comment by rusty-snake** [comment]
Try creating `~/.config/firejail/JDownloader.profile`:
```
noblacklist ${HOME}/.jd

# Allow java (blacklisted by disable-devel.inc)
include allow-java.inc

mkdir ${HOME}/.jd
whitelist ${HOME}/.jd

include chromium.profile
```

**Comment by Micha-Btz** [comment]
Make sure, firejail is using your right profile. Mine was always startet through the desktop file and was using the default profile. Test it on your shell.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.

**Comment by Tanath** [comment]
Apologies for the delay. The solution offered by @rusty-snake works for me:
https://github.com/netblue30/firejail/issues/2336#issuecomment-529935962
