### ISSUE TITLE
Is it possible to run multiple firejailed torbrowser instances?

### ISSUE THREAD

**Issue by Zypherspace** [netblue30/firejail#2339]
Would be useful to have multiple tor instances firejailed providing separate circuits/browsers open simultaneously. When attempting with --private torbrowser I get following:
```
/usr/bin/env: ‘./Browser/execdesktop’: No such file or directory
```
Tried whitelisting /usr/bin/env.

**Comment by rusty-snake** [comment]
@Zypherspace see also: https://support.torproject.org/#tbb-36

**Comment by chiraag-nataraj** [comment]
You could probably adapt my method for creating temporary firefox profiles (see the `firefox.common` script in my repo: https://github.com/chiraag-nataraj/firejail-profiles). I'll give it a go later and post back.

**Comment by rusty-snake** [comment]
@Zypherspace closing due to a long period of inactivity, if you have future questions, fell free to re-open.
