### ISSUE TITLE
firejail desktop integration

### ISSUE THREAD

**Issue by rahiel** [netblue30/firejail#234]
Thanks again for firejail!

The new symlink invocation sounds great, it's something I was looking for when I started to use firejail. Are you also interested in making an interface in firejail to manage the symlinks? For example, AppArmor has aa-enforce/aa-disable commands to enforce profiles and aa-status to see which ones are enabled/disabled. If this was then used in a GUI, using would firejail would be very easy.

**Comment by netblue30** [comment]
That's a good idea, I'll build a small tool to manage the symlinks. Thanks.

**Comment by derba** [comment]
I created a generic executable at /usr/local/bin/firejail-wrapper:

```sh
#!/bin/sh
me=`dirname $0`
PATH=`echo $PATH | sed -r "s%^(.*:|)$me:%\1%"`
firejail `basename $0` $@
```

And just added symlinks to it, such as this one:
`ln -s /usr/local/bin/firejail-wrapper /usr/local/bin/firefox`
And voila, Firefox started from command line, Unity, etc, starts in Firejail.

**Comment by rahiel** [comment]
I made a little tool that modifies the desktop files to start the programs with firejail. (It also remodifies them on updates if you install the deb). Its [usage](https://github.com/rahiel/firectl#usage) shows the interface I had in mind.

**Comment by netblue30** [comment]
@rahiel

Thanks, I added a link for Firectl on the main project webpage: https://firejail.wordpress.com/
