### ISSUE TITLE
Firejail for malware analysis/R-E

### ISSUE THREAD

**Issue by aghlhpzm** [netblue30/firejail#2340]
Can firejail be used for any risked work related to forensics/reverse-engineering , or for that kind of work i should stick to VMs ?

It's not an issue i know but i did not find any IRC or forum for Firejail...

**Comment by rusty-snake** [comment]
No.

**Comment by chiraag-nataraj** [comment]
Echoing @rusty-snake, I would either prefer a VM or even a fully dedicated machine (disconnected from the internet by default) to running something of this nature on my personal machine. At the _very_ least, I would use a VM (and probably sandbox the VM itself using firejail!).

I'm going to close this, but feel free to re-open it if you have questions as to why we are making this recommendation.
