### ISSUE TITLE
LTS build out of mainline sources

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#2341]
A Debian user asked me to provide the LTS version in Debian.
But I think that most users are probably more interested in the mainline version.

Would it be possible to build a LTS version out of the mainline sources (i.e. drop all the features that are not available in LTS at build time)?
Or are they too much differing?
In this way an additional binary package for the LTS version could be built.

**Comment by SkewedZeppelin** [comment]
@netblue30 I saw a lot of the features you were completely stripping out. Wouldn't it be easier to make those all configurable at build time with make flags? Allowing LTS to essentially just be a build variant with less attack surface?

**Comment by reinerh** [comment]
> For the next LTS release we'll go mainline-based as you describe. Most of the code is already in mainline, we can have the sync ready by the end of this year. For debian buster you'll be able to release the regular and the LTS versions in two different packages from the same source code.

Debian Buster will be released in a few months, with a [soft freeze](https://release.debian.org/buster/freeze_policy.html) starting in a few weeks.
So buster will probably only ship with the mainline version then.
But thanks for planning to having both releases in the same branch. That will be very useful in the future.

**Comment by reinerh** [comment]
> Debian soft freeze on 2019-02-12 - Then I'll have full mainline releases by the end of this month in both firejail and firetools.

Thanks!
I've just uploaded the release candidate to experimental.

**Comment by netblue30** [comment]
Thanks! I'll have new releases for both firejail and firetools out this weekend.
