### ISSUE TITLE
Regression: Relative profile include silently ignored

### ISSUE THREAD

**Issue by thomasjfox** [netblue30/firejail#2342]
Hello,

I've upgraded an ancient firejail 0.9.47 installation to firejail 0.9.56 LTS.

At first I didn't notice my custom netfilter rules were *silently* no longer applied. It all surfaced when I wanted to show the cool network sandboxing to a coworker and I tried to access the Internet from an "Intranet only" browser... and it worked despite the supposedly active firewall rules :o)

I've poked around profile.c and the issue is probably due to this:

commit 07a01b1f4503ad5681771e2b4c5307db597f81f8
AuthorDate: Tue Oct 9 05:43:06 2018 -0500

    Allow include to search userdir then systemdir for "bare" profile file names.

My firejail invocation and config file layout was like this:

cd $(HOME)/.firejail
firejail --profile=$HOME/.firejail/firefox-intranet.profile

The "firefox-intranet.profile" contains an "include firefox-custom-common.profile" statement which then has statements like "net virbr0".

The problem is that the profile-to-include filename is relative to the current dir and the new code detects it is not an absolute path. Therefore it calls profile_find_firejail() which just searches $(HOME)/.config/firejail and /etc/firejail.

So I moved the profiles to $HOME/.config/firejail and everything started working again. Another workaround was to prefix the filenames with './'

While it's might be a worthwhile security feature not to load a profile from the current working directory, it would be nice to include a profile relative to the path of the profile that contains the "include xyz" statement.

Also, and this is the more important part, it would have been nice if there was any kind of warning if a specified profile can't be found. Even --debug didn't show it.

Proposal:

1. Issue a warning or error if "include xyz" does not find a profile *and* the profile name doesn't end in ".local".

2. Abort with an error if a "netfilter xyz" configuration is given but we are in host network mode. As my second profile wasn't included, firejail didn't see the "net virbr0" statement anymore and defaulted to host networking. I'd rather have it abort in this case than to risk full network access.

Opinions?

**Comment by rusty-snake** [comment]
```
$ echo "include b.profile" > a.profile
$ echo "seccomp" > b.profile
$ firejail --profile=a.profile bash
Reading profile a.profile
Reading profile b.profile
```

**Comment by rusty-snake** [comment]
still an issue?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
