### ISSUE TITLE
Dropping 'mincore' syscall breaks several apps

### ISSUE THREAD

**Issue by Vincent43** [netblue30/firejail#2343]
Recent [commit](https://github.com/netblue30/firejail/commit/ae3db84128503c16fd638b5c7bf9408d64ce14ba) that added `mincore` to default `seccomp` blacklist causes `kodi` fail to start. Perhaps we have to move to `seccomp.drop` filter in kodi profile and omit `mincore` syscall.

`SECCOMP subj==firejail-default (enforce) pid=4792 comm="kodi.bin" exe="/usr/lib/kodi/kodi.bin" sig=31 arch=c000003e syscall=27 compat=0 ip=0x6bf06868d89b code=0x0`

**Comment by Vincent43** [comment]
Fixed by https://github.com/netblue30/firejail/commit/05bbec3375be71cdf7d72cf04634e056cec5c643

**Comment by Vincent43** [comment]
Bad news, mpv have the same issue:
`SECCOMP ses=1 subj==firejail-default (enforce) pid=23615 comm="mpv/vo" exe="/usr/bin/mpv" sig=31 arch=c000003e syscall=27 compat=0 ip=0x6db290aea89b code=0x0`

I wonder if `mincore` isn't too widely used to be in default filter.

**Comment by SkewedZeppelin** [comment]
totem seems broken too

**Comment by SkewedZeppelin** [comment]
We should probably revert it before release to not cause too many issues.

The kernel patch to reduce leakage from the mincore syscall was already backported to all supported kernels anyway.

**Comment by Vincent43** [comment]
I think it's only in 5.0 for now. Perhaps isn't considered much urgent.

**Comment by netblue30** [comment]
I have removed it, thanks!

**Comment by Vincent43** [comment]
@SkewedZeppelin actually the kernel commit [was reverted](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=30bac164aca750892b93eef350439a0562a68647).
