### ISSUE TITLE
Dolphin SMB integration does not function if "protocol" filter is enabled

### ISSUE THREAD

**Issue by Ryujinra** [netblue30/firejail#2348]
Recently, (I do not know precisely which commit), dolphin SMB integration has stopped working.

The error in dolphin is "the protocol has died unexpectedly". This is a symptom of the error in kio or samba which is "Could not determine network interfaces, you must use a interfaces config line". Adding an explicit interface in samba.conf does not fix the issue.

I've traced it back to the "protocol = unix" line in the dolphin profile. "protocol = unix,netlink" gives a different error about being unable to identify the workgroup.

"ignore protocol" fixes the issue.

Thanks.

**Comment by smitsohu** [comment]
Thanks for reporting the issue.

Can you try `protocol unix,inet,inet6,netlink`? If this works, could you please confirm that all of them are required?

**Comment by Ryujinra** [comment]
Needs at least "protocol unix,inet,netlink" to work.

Interestingly, I get the "protocol died unexpectedly" error if I try to open certain files through dolphin with, for example, GwenView. Commenting out "protocol = unix" in gwenview.profile fixes it. I expect that any program with a restrictive protocol filter will have similar problems over SMB, so this might not be a dolphin-exclusive issue.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
