### ISSUE TITLE
Chromium/Firefox file open dialog takes 5 seconds to list the files if jailed :: GTK file open dialog issue?

### ISSUE THREAD

**Issue by jdevelop** [netblue30/firejail#2355]
`firejail 0.9.56-1` on Arch Linux ( `Linux devbox 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux`) and `chromium 71.0.3578.98-3`

With `/etc/firejail/chromium.local` 
```
ignore nodbus
```

I can open a file upload dialog just fine, however the list of the files is populated with a significant delay.

I run Chromium as:

```
#!/bin/bash

ARGS="--force-device-scale-factor=2.0"

/sbin/firejail --debug --profile=/etc/firejail/chromium.profile --join-or-start="chromium" /sbin/chromium $ARGS $*
```

and the content of `/etc/firejail/chromium.profile`:
```
# Firejail profile for chromium
# Description: A web browser built for speed, simplicity, and security
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/chromium.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.cache/chromium
noblacklist ${HOME}/.config/chromium
noblacklist ${HOME}/.config/chromium-flags.conf

mkdir ${HOME}/.cache/chromium
mkdir ${HOME}/.config/chromium
whitelist ${HOME}/.cache/chromium
whitelist ${HOME}/.config/chromium
whitelist ${HOME}/.config/chromium-flags.conf

# private-bin chromium,chromium-browser,chromedriver

# Redirect
include /etc/firejail/chromium-common.profile
```

**Comment by chiraag-nataraj** [comment]
What happens if you re-enable `nodbus`?

**Comment by jdevelop** [comment]
* with `nodbus` enabled - chrome is frozen for 10-15 seconds, can't click anywhere, can't drag the dialog window, can't close it.
* with `nodbus` disabled - chrome is operable, the file dialog shows no files for ~5 seconds, then renders the list of the files.

**Comment by chiraag-nataraj** [comment]
Hmm, I see. Interestingly, `nodbus` works just fine on my system, but I'm on Debian...

Easiest way to debug is to copy the contents of `/etc/firejail/chromium-common.profile` into your local profile, comment everything out, and start uncommenting things until `chromium` breaks again.

**Comment by smitsohu** [comment]
Maybe related to #2258

**Comment by jdevelop** [comment]
Well, in my case it does launch, no matter whether `nodbus` is enabled or not. There's something else going on.

**Comment by jdevelop** [comment]
Just checked with the firefox - it behaves exactly the same, perhaps the issue is not related to chromium, but to the GTK file chooser dialog?

**Comment by Fred-Barclay** [comment]
Similar to #2324 ?

**Comment by rusty-snake** [comment]
@jdevelop still an issue?

**Comment by jdevelop** [comment]
Absolutely not!
