### ISSUE TITLE
Can RPMs or DEBs be installed and tested in --private Firejails?

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#2360]
In other words install then run an app in a Firejail. When you close it, it is uninstalled? Sandboxie on Windows was great for this.

**Comment by SkewedZeppelin** [comment]
I think you technically can, but it is strongly advised against as using virtual machines are a far safer/secure method. There is an issue here somewhere that has more detail.

**Comment by chiraag-nataraj** [comment]
If you really want to:

1. Start a `firejail` with an `overlay`: `sudo firejail --name=tmpinst --overlay-tmpfs`
2. Copy files into the sandbox: `sudo firejail --put=tmpinst /path/to/file/to/copy /root/file`
3. Install whatever you want inside the sandbox
4. When you exit the sandbox, everything is undone.

As @SkewedZeppelin said, though, it's much better to use a VM.

**Comment by chiraag-nataraj** [comment]
@Futureknows I'm going to go ahead and close this, but please feel free to reopen if you would like more info!

**Comment by Raj2032** [comment]
`firejail --overlay-named=jail1 firefox`

So does this create a new directory where firefox will be stored inside?
