### ISSUE TITLE
"desktop.profile"

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#2361]
I noticed a profile called "desktop.profile".
Is this named correctly? The local file it includes is actually named "github-desktop.local", so it suggests that "github-desktop.profile" would be the correct name.
It would also be quite strange if the github-desktop binary was just called "desktop". But I can't check it at the moment.
Can someone please verify if the name is correct?

cc @glitsj16

**Comment by SkewedZeppelin** [comment]
this is https://github.com/desktop/desktop
there appear to be no official binaries for Linux, nor do any distros seem to package it
there are a few unofficial builds of it, one I checked and the binary was `github-desktop`

since there isn't a github-desktop.profile I'm going to assume the file name was an accident, but lets wait for @glitsj16's response

**Comment by glitsj16** [comment]
Hi, I remember this application going through some (file)name changes. At the time I added the profile the binary was named `desktop`, indeed strange and exceptional. For a while now it has been [available in the AUR](https://aur.archlinux.org/packages.php?K=github-desktop&O=0&do_Search=Go) in a few differently named packages for Arch Linux. To confuse things even more, there's https://github.com/shiftkey/desktop and https://snapcraft.io/github-desktop, offering Appimage, Snap, .deb and .rpm's.

@reinerh: You are correct though. The profile should be named `github-desktop.profile`. On top of that, the aforementioned installers now all use the more sensible `github-desktop.desktop` format. Hence the firecfg name also needs changing. If you and @SkewedZeppelin are okay with this, I'll make a PR with the needed changes asap.

Thanks for pointing out this mistake, which was mine indeed.

**Comment by glitsj16** [comment]
Follow-up. I just noticed that the .deb from https://github.com/shiftkey/desktop/releases installs to `/opt/Github Desktop`. I've never used anything from /opt with firejail, so give me some time to boot into Ubuntu 16.04, install the .deb and test an edited profile. I'll report back here, please hold.

**Comment by reinerh** [comment]
Thank you for looking into it. :+1:

**Comment by glitsj16** [comment]
Hi all. After some more testing I came up with the following PR: https://github.com/netblue30/firejail/pull/2362. Please check and/or advise on these changes. I added comments inside the profile to cover 2 possible issues:
* user needs to add preferred location where local repositories are kept;
* binary location might not be in PATH on debian-based distros.

**Comment by glitsj16** [comment]
PR https://github.com/netblue30/firejail/pull/2362 fixes the profile name issue and refactors it as a blacklist profile with additional support for github-desktop appimage.
