### ISSUE TITLE
ark, private-tmp and browsers

### ISSUE THREAD

**Issue by Lockdis** [netblue30/firejail#2368]
the Ark profile is using `private- tmp`, this option breaks "open file" in browsers
![2019-01-24_18-38](https://user-images.githubusercontent.com/45907176/51700512-a7017680-200f-11e9-94e1-1da7a74bcd20.png)

it seems not possible to use `private-tmp folder*` nor `private-tmp` and `noblacklist /tmp/folder*`

should this option be removed from the default profile?

![2019-01-24_18-46](https://user-images.githubusercontent.com/45907176/51701043-d9f83a00-2010-11e9-8866-6871a4bf07ad.png)
![2019-01-24_18-46_1](https://user-images.githubusercontent.com/45907176/51701050-dbc1fd80-2010-11e9-9034-739c65a84b7d.png)

**Comment by Vincent43** [comment]
You may use `ignore private-tmp`.

**Comment by Fred-Barclay** [comment]
Agree with @Vincent43 . It's a tad annoying, but `private-tmp` is worth the benefits.

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this issue, since this is (effectively) intended behavior and a fix was proposed in the OP's case.
