### ISSUE TITLE
Making cgroup feature configurable in firejail.config

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#2371]
Currently some functionality can be globally disabled in /etc/firejail/firejail.config.
Can you please extend it to allow disabling `--cgroup`?
Some users might want to disallow that as it can place the process in a different cgroup with different restrictions.

**Comment by netblue30** [comment]
all set: https://github.com/netblue30/firejail/commit/a061b3f3d43d760f074ad49317f9659717ff7101

**Comment by reinerh** [comment]
Awesome, thanks.
I will probably backport it to Debian's 0.9.58 package, as this was mentioned in a bug report (https://bugs.debian.org/916920) and disable it in the default configuration.

**Comment by netblue30** [comment]
No problem, and thanks for the fix! Somehow I've missed strncmp!
