### ISSUE TITLE
firejail 0.9.58 and youtube-dl issue

### ISSUE THREAD

**Issue by martywd** [netblue30/firejail#2378]
OS:  Linux Mint 19.1 MATE 64-bit
youtube-dl v. 2019.01.27
upgrading firejail from 0.9.56 > 0.9.58

After downloading and installing 'firejail-apparmor_0.9.58_1_amd64.deb' from sourceforge, the 'firejail youtube-dl' <.....> command yields the follow errors:

> ~ $ firejail youtube-dl --help
> Error: execute permission denied for /home/marty/bin/youtube-dl
> Error: no suitable youtube-dl executable found
> ~ $ firejail youtube-dl --version
> Error: execute permission denied for /home/marty/bin/youtube-dl
> Error: no suitable youtube-dl executable found

Permissions for 'youtube-dl':

> -rwx------ 1 marty marty 1733727 Jan 28 14:43 /home/marty/bin/youtube-dl

Purged the 'firejail-apparmor' install and installed 'firejail_0.9.58~rc1_1_amd64.deb'.  No change, same errors when attempting to use 'youtube-dl' with firejail* 0.9.58.

Reverted back to 'firejail_0.9.56_1_amd64.deb' and now the 'firejail youtube-dl' command functions **_without_** errors once again.
.

**Comment by SkewedZeppelin** [comment]
Please try
`firejail --ignore='noexec ${HOME}' /home/marty/bin/youtube-dl`

**Comment by martywd** [comment]
> Please try
> `firejail --ignore='noexec ${HOME}' /home/marty/bin/youtube-dl`
> 

**Yes** that command works for me from the command line.  Actually, 
> `firejail --ignore='noexec ${HOME}' youtube-dl`
>

works as well.  Thanks for the tip!

> noexec before 0.9.58 didn't recursively apply to paths, allowing programs in ~ for example to run when they shouldn't of
> see: [a7164cb](https://github.com/netblue30/firejail/commit/a7164cb38171c0291fac7f3a0767fe8f1c69b02d) and #2375

I'll check those links out, thanks again.

Now to figure out _how_ to enter this 'ignore' into ~/.config/firejail/youtube-dl.profile' so I don't have to add the above switch all the time?

.

**Comment by SkewedZeppelin** [comment]
`echo 'ignore noexec ${HOME}' > ~/.config/firejail/youtube-dl.local`
should work

**Comment by martywd** [comment]
> `echo 'ignore noexec ${HOME}' > ~/.config/firejail/youtube-dl.local`
> should work

Yup, that works.  Thank you again!
.
