### ISSUE TITLE
CentOS 6 support?

### ISSUE THREAD

**Issue by cujanovic** [netblue30/firejail#238]
Is there a plan for CentOS 6 support or it is not possible to run firejail because of libc on CentOS 6?

root@local [~]# rpm -i firejail-0.9.36-1.x86_64.rpm 
error: Failed dependencies:
        libc.so.6(GLIBC_2.14)(64bit) is needed by firejail-0.9.36-1.x86_64                                                                                                                                                                    
        libc.so.6(GLIBC_2.15)(64bit) is needed by firejail-0.9.36-1.x86_64                                                                                                                                                                    
root@local [~]#

Thanks.

**Comment by netblue30** [comment]
You would need a Linux kernel 3.2 or newer installed on the box. There are also some compilation problems due to some header files in glibc. If you get around to compile it and install a new kernel, it should be fine.

**Comment by cujanovic** [comment]
I have a Linux 4 kernel + grsec patch that was build from source. I will try to compile it with some workarounds. Thanks :)

**Comment by h1z1** [comment]
Can you clarify what version of CentOS this was compiled / validated against?  Using 6.6 it appears still broken as it still requires GLIB 2.{14,15} as given above.

[root@mrcoffee ~]# cat /etc/{redhat,centos}-release 
CentOS release 6.6 (Final)
CentOS release 6.6 (Final)
[root@mrcoffee ~]# firejail
firejail: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by firejail)
firejail: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by firejail)
[root@mrcoffee ~]# rpm -qf /lib{,64}/libc.so.6
glibc-2.12-1.166.el6_7.3.i686
glibc-2.12-1.166.el6_7.3.x86_64
[root@mrcoffee ~]# 
[root@mrcoffee ~]# rpm -q firejail --requires
/bin/bash  
/bin/sh  
config(firejail) = 0.9.38-1
libc.so.6()(64bit)  
libc.so.6(GLIBC_2.14)(64bit)  
libc.so.6(GLIBC_2.15)(64bit)  
libc.so.6(GLIBC_2.2.5)(64bit)  
libc.so.6(GLIBC_2.3)(64bit)  
libc.so.6(GLIBC_2.3.4)(64bit)  
libc.so.6(GLIBC_2.4)(64bit)  
libc.so.6(GLIBC_2.7)(64bit)  
libc.so.6(GLIBC_2.8)(64bit)  
libpthread.so.0()(64bit)  
libpthread.so.0(GLIBC_2.2.5)(64bit)  
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)  
rpmlib(PayloadIsXz) <= 5.2-1

[root@mrcoffee ~]# uname -r
4.0.4-1.el6.elrepo.x86_64
[root@mrcoffee ~]# 


Thanks.

**Comment by netblue30** [comment]
No, the download version built on CentOS 7. I'll have to update the web pages, thanks!

**Comment by h1z1** [comment]
Couldn't find the source rpm.  Patched the spec file for libtracelog.so and version.  Recompiled from 0.9.38 source. It worked, the binary however had other problems:

[root@mrcoffee firejail]# firejail 
Error mkdir:fs_build_firejail_dir(69): No such file or directory
[root@mrcoffee firejail]# 

Strace indicated it trying to create /run/firejail and hardcoded..  That directory only exists in CentOS 7.  Silly  replace on them all and rebuilt.

Binary builds and runs.  I can't vouch for anything else it may have broken though.   Patches available but they are fairly trivial.

**Comment by netblue30** [comment]
I'll look into it, thanks!

**Comment by netblue30** [comment]
Fixed!
