### ISSUE TITLE
firejail 0.9.58 breaks many programs (execute permission denied)

### ISSUE THREAD

**Issue by odiferousmint** [netblue30/firejail#2380]
I have no idea why, but I get:

```
Error: execute permission denied [...]
Error: no suitable X executable found
```

for many programs. 0.9.56 is the last version that works.

I have the directory whitelisted, so I have no idea why it would not work whereas 0.9.56 works just fine.

The programs in question are wire and vivaldi. Probably breaks many other programs which I have not tried yet.

Any ideas? What am I missing? Do I need to add something to my local profile to be able to run an executable inside ${HOME}?

Edit: it seems like it runs if I get rid of `noexec ${HOME}`. How come that it works in 0.9.56 but not in 0.9.58 with `noexec ${HOME}` present?

In the meantime I think I found a bug. If I include `disable-programs.inc` that blacklists 2 paths, I will get a permission denied error *even* after I have manually whitelisted and noblacklisted them at the end of the profile file. It seems like as if that `noblacklist` and `whitelist` does not overwrite the previous `blacklist`. This is a bug, right?

**Comment by SkewedZeppelin** [comment]
See https://github.com/netblue30/firejail/issues/2375#issuecomment-458379200

**Comment by netblue30** [comment]
> for many programs.

@odiferousmint what programs are you having problems with noexec home? So far we figured out the browsers, but there could be more.

**Comment by Lockdis** [comment]
everything works for me now, not sure if it's because i have updated firejail today or something else was wrong with my pc, anyways it's fixed for me. thx

**Comment by chiraag-nataraj** [comment]
I'll go ahead and close this, as it looks like the issue has been resolved.

**Comment by odiferousmint** [comment]
> > for many programs.
> 
> @odiferousmint what programs are you having problems with noexec home? So far we figured out the browsers, but there could be more.

I only tested with `wire-desktop` and `vivaldi`.
