### ISSUE TITLE
print.c:209:20: warning: duplicated 'if' condition [-Wduplicated-cond]

### ISSUE THREAD

**Issue by dcb314** [netblue30/firejail#2381]
Source code is

                       else if (bpf->k == offsetof(struct seccomp_data, nr)) {
                                printf("data.syscall-number");
                                syscall_loaded = 1;
                        }
                        else if (bpf->k == offsetof(struct seccomp_data, nr))

**Comment by netblue30** [comment]
Thanks, I'll clean it up.
