### ISSUE TITLE
Issue with Streaming / Streamed YouTube Videos

### ISSUE THREAD

**Issue by aberja** [netblue30/firejail#2383]
When I run `firejail vivaldi` I cannot watch YouTube videos that are streaming or were previously streamed.  I receive a message that states "An error occurred.  Please try again later..."

I can watch non streamed YouTube videos without any issue.  I can also watch the streamed and streaming YouTube vidoes in Vivaldi without firejail.

If I close Vivaldi and run `firejail --noprofile vivaldi` I can watch the streamed and streaming YouTube videos without any issue.

Any thoughts on why I need to use --noprofile and what I need to do to resolve this issue?

Setup:
Mint LMDE 3
Vivaldi version: 2.2.1388.37 (Stable) 64 bit
Firejail version: 0.9.59

**Comment by SkewedZeppelin** [comment]
Are you using the proprietary NVIDIA drivers?

Using --noprofile, provides little to no security benefits.

**Comment by aberja** [comment]
Yes, I'm using proprietary NVIDIA drivers for the GTX1070 video card on my ASUS G752vs laptop.

**Comment by Fred-Barclay** [comment]
Does `firejail --ignore=noroot vivaldi` work?

**Comment by rusty-snake** [comment]
Does `firejail --ignore=private-dev vivaldi` work?

**Comment by Lockdis** [comment]
i'm on manjaro the first time i have launched vivaldi in firejail i was able to play a live stream on youtube then it stopped to works, to fix this i had to install the ffmpegs codecs, (vivaldi-codecs-ffmpeg-extra-bin on aur for precompiled bins) and it works again with firejail vivaldi-stable and default probiles

**Comment by aberja** [comment]
> Does `firejail --ignore=private-dev vivaldi` work?

No that does not resolve the issue.

> it's a problem related to codecs, 

I hear what you are saying but if I run `firejail vivaldi` or any of the other varieties with firejail I receive the codecs message and streaming YouTube videos will not run.

if I just run `vivaldi` , I never receive the codecs issue and the streaming YouTube videos always work.

> edit not sure if it matter but i notice that you have installed version of codecs 70.* will mine are 71.0.3578.98-0

Thanks for the heads-up on the codecs 71 vs 70.  Although I noticed that your screenshot from vivaldi refers to the same 70 codec that I have installed.  I'm assuming your codecs 71.* is coming from the arch repository which I think is always on the bleeding edge :)

**Comment by SkewedZeppelin** [comment]
hmm, can you try `firejail --ignore='noexec ${HOME}' vivaldi`

**Comment by aberja** [comment]
> hmm, can you try `firejail --ignore='noexec ${HOME}' vivaldi`

Unfortunately, that also returns the same codec issue.

**Comment by SkewedZeppelin** [comment]
Can you sudo edit `/usr/local/etc/firejail/vivaldi.profile`, comment all of the lower options and enable one by one until it stops working then?

**Comment by aberja** [comment]
> Can you sudo edit `/usr/local/etc/firejail/vivaldi.profile`, comment all of the lower options and enable one by one until it stops working then?

I need to comment out the following 3 lines to be able to run `firejail vivaldi` without receiving the codecs issue:

```
#whitelist ${HOME}/.cache/vivaldi
#whitelist ${HOME}/.config/vivaldi
#include chromium-common.profile
```
If I uncomment any of the above 3, the codec warning reappears when running `firejail vivaldi`

**Comment by SkewedZeppelin** [comment]
Try
`firejail --ignore='noexec ${HOME}' --whitelist=~/.local/lib/vivaldi vivaldi`

**Comment by aberja** [comment]
>Try
firejail --ignore='noexec ${HOME}' --whitelist=~/.local/lib/vivaldi vivaldi

Yes, Vivaldi runs with no codec issue :)  However, I receive the following:

```
g752vs@g752:~$ firejail --ignore='noexec ${HOME}' --whitelist=~/.local/lib/vivaldi vivaldi
Reading profile /usr/local/etc/firejail/vivaldi.profile
Reading profile /usr/local/etc/firejail/chromium-common.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 17096, child pid 17099
Child process initialized in 72.50 ms
/usr/bin/vivaldi: line 173: /dev/fd/62: No such file or directory
/usr/bin/vivaldi: line 174: /dev/fd/62: No such file or directory
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[6:6:0131/232538.407621:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const base::string16 &, const gfx::Range &)
```

**Comment by netblue30** [comment]
If you disregard the warning, is everything else working?

**Comment by SkewedZeppelin** [comment]
> Do I lose any security benefits starting Vivaldi with the above command?

noexec was partially broken in previous releases (wasn't recursive), so if you've been running like that for however long, then there is no difference.

**Comment by netblue30** [comment]
We have a fix on mainline, you can give it a try.

**Comment by aberja** [comment]
With the fix, I can watch streaming YouTube videos with `firejail vivaldi`.  However, I am getting new error messages (Which don't seem to be creating any issues):

```
g752vs@g752vs:~/firejail$ firejail vivaldi
Reading profile /usr/local/etc/firejail/vivaldi.profile
Reading profile /usr/local/etc/firejail/chromium-common.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 12528, child pid 12529
Child process initialized in 61.44 ms
/usr/bin/vivaldi: line 169: /dev/fd/62: No such file or directory
/usr/bin/vivaldi: line 170: /dev/fd/62: No such file or directory
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[205:205:0207/105517.600833:ERROR:audio_context.cc(52)] Create
[205:205:0207/105517.600922:ERROR:audio_context.cc(130)] AudioContext
[205:205:0207/105517.600951:ERROR:audio_context.cc(146)] document user activation
[205:205:0207/105517.602023:ERROR:audio_context.cc(436)] IsAllowedToStart
[205:205:0207/105517.606874:ERROR:audio_context.cc(52)] Create
[205:205:0207/105517.606973:ERROR:audio_context.cc(130)] AudioContext
[205:205:0207/105517.607005:ERROR:audio_context.cc(146)] document user activation
[205:205:0207/105517.607134:ERROR:audio_context.cc(436)] IsAllowedToStart
[205:205:0207/105518.881401:ERROR:audio_context.cc(206)] resumeContext
[205:205:0207/105518.881589:ERROR:audio_context.cc(436)] IsAllowedToStart
```

**Comment by rusty-snake** [comment]
@aberja is this still an issue and if so, is anything brocken or are this only strange error mesages? Maybe `noautopulse` can fix this (IDK).

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request reopen if you still have this issue.
