### ISSUE TITLE
Retain firejail-local AppArmor customizations

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#2388]
When installing Firejail a fresh copy of [firejail-local](https://github.com/netblue30/firejail/blob/master/etc/firejail-local) gets installed (usually into /etc/apparmor.d/local) by default. While this is fine when users don't add any site-specific additions or overrides to Firejail's [default AppArmor profile](https://github.com/netblue30/firejail/blob/master/etc/firejail-default), this is problematic when they do so. Currently these always seem to get overwritten on each upgrade, causing unnecessary confusion.

This issue usually doesn't show on `Arch Linux`, as the [official repo package](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/firejail) isn't enabling apparmor. Unsure about what happens on RPM-based distros, I have zero-experience with those. But on `Debian/Ubuntu`and friends this should be reproducible.

I only started to use apparmor recently and don't have a lot of experience with it. But it seems to work just fine when enabled on Arch Linux. Am I missing something obvious or is this something we should adress?

**Comment by reinerh** [comment]
Good catch! The Debian package indeed also has this problem.
The /etc/apparmor.d/local/ files are not supposed to be installed by the package itself.
A helper script (generated by [dh_apparmor](https://manpages.debian.org/stretch/dh-apparmor/dh_apparmor.1.en.html)) will create them automatically during installation.
I will fix it in the packaging.
But I think firejail's Makefile should also be changed to not install those files.

**Comment by reinerh** [comment]
Just noticed that it's actually not a big issue on Debian, as the file is marked as a "conffile".
When the user has modified such a file and a package update tries to overwrite it, the user is asked what to do (keep/overwrite/review diff).
But the cleaner way is still to not include it in the package and use dh_apparmor instead.

**Comment by glitsj16** [comment]
@reinerh Thanks for looking into this and for pointing to dh_apparmor. I added a preliminary fix in https://github.com/netblue30/firejail/pull/2390. Tested on Ubuntu 16.04 LTS, but that's with a custom script using checkinstall. Let's hold until someone with actual Makefile skills/experience approves the PR.
