### ISSUE TITLE
Flameshot - error while loading shared libraries

### ISSUE THREAD

**Issue by aberja** [netblue30/firejail#2399]

**Comment by aberja** [comment]
When I try to run flameshot with firejail I receive the following error:
`flameshot: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`

I tried adding `ld.so.cache` to the flameshot.profile, but that does not resolve the issue.

Commenting out the following line does resolve the issue:
`#private-etc fonts,ld.so.conf,resolv.conf,ca-certificates,ssl,pki,crypto-policies`

```
g752vs@g752vs:~$ firejail flameshot
Reading profile /usr/local/etc/firejail/flameshot.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-passwdmgr.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/disable-xdg.inc
Parent pid 22354, child pid 22355
Warning: skipping crypto-policies for private /etc
Private /etc installed in 13.34 ms
1 program installed in 2.00 ms
Child process initialized in 81.53 ms
flameshot: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by SkewedZeppelin** [comment]
@aberja is the following from #2383 still the same?

> Mint LMDE 3
> Firejail version: 0.9.59
> NVIDIA Driver version: 384.130

**Comment by Fred-Barclay** [comment]
@aberja Also does this actively interfere with using Flameshot? I get the same message on my system (also LMDE 3) but flameshot works well as far as I can tell.

If it doesn't actually interfere it's likely this is just cosmetic.

Cheers!
Fred

**Comment by aberja** [comment]
> @aberja is the following from #2383 still the same?
> 
> > Mint LMDE 3
> > Firejail version: 0.9.59
> > NVIDIA Driver version: 384.130

Yes

**Comment by aberja** [comment]
> Also does this actively interfere with using Flameshot?

Yes, Unfortunately Flameshot will not start unless I comment out the line.

**Comment by chiraag-nataraj** [comment]
Add `alternatives` to the `private-etc` line.

**Comment by aberja** [comment]
> Add `alternatives` to the `private-etc` line. 

Appending `,alternatives` to the `private-etc` line resolves the issue

**Comment by chiraag-nataraj** [comment]
@Fred-Barclay, should we add it to the official profile? Come to think of it, should we add `alternatives` to all `private-etc` lines? It _shouldn't_ make anything less secure since they're all symlinks anyway (so as long as the target isn't whitelisted, it'll just be a dangling symlink).

**Comment by Fred-Barclay** [comment]
@chiraag-nataraj Probably add to all. I'll get on it if you haven't already started :smile:

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this since the issue seems to be resolved :)
