### ISSUE TITLE
Duplicate bookmarks in Firefox

### ISSUE THREAD

**Issue by bertradio** [netblue30/firejail#2406]

**Comment by bertradio** [comment]
I run both Firefox and Chrome under firejail. Within Chrome when I try and save a page all my bookmarks are correct. But when I try and save a page in Firefox I see duplicate bookmarks. I am running the latest version of firejail (o.9.28.2). Any idea what might be happening. Evidently the bookmarks are saved somewhere but I cannot find where. I am using Linux Mint 19.1.

![example](https://user-images.githubusercontent.com/47680581/52892695-b9bc2680-3149-11e9-8adb-b6ab4eadb1c1.jpg)

**Comment by smitsohu** [comment]
> I am running the latest version of firejail (o.9.28.2)

Do you mean 0.9.58.2? Version 0.9.28 is very old, unsupported and has lots of known issues (pick a package with the newest version e.g. from [here](https://sourceforge.net/projects/firejail/files/firejail))

Did you try what happens when you run them without firejail?
```
/usr/bin/firefox
/usr/bin/chromium-browser
# or /usr/bin/google-chrome or whatever your path is
```

**Comment by bertradio** [comment]
You are right, that's a typo. I am running 0.9.58.2, the latest.

Everything is fine if I run without firejail - no duplicates. And Chrome is fine with and without firejail. I also run FF and firejail on another computer and there are no duplicates there. So it must have something to do with my installation or config files.

**Comment by bertradio** [comment]
I did a complete uninstall in Synaptic and reinstall so I have unmodified profiles. Now I have this:

![image](https://user-images.githubusercontent.com/47680581/52916570-22181e80-3296-11e9-9c70-a1b4f8697866.png)

Note that the entry for Home (with a capital H) points to my user home. The entires for "home" (small h) point to the home folder in rook which contains my Home.

**Comment by chiraag-nataraj** [comment]
This is because the `private-*` options mount `tmpfs` on top of various directories. Those directories show up as "mounts" in various file managers.

The reason you're seeing differences between firefox and chromium is that the chromium profile is much looser than the firefox one (due to chromium needing tons of privileges to set up its _own_ sandbox). I don't see why that would necessarily affect this, but it is what it is.

Regardless, this isn't really a bug. It's mostly just an artifact of the way whitelisting is implemented.

**Comment by bertradio** [comment]
So I guess I'll have to live with this... unless you know of somewhere in the system I could get rid of the duplicates.

**Comment by chiraag-nataraj** [comment]
Not that I know of, nope. Unless you can configure the file manager not to show you mounted stuff (which would probably be inconvenient in the general use case).

The fundamental problem here is that stuff mounted by firejail (to hide things) appears exactly the same as, say, a flash drive you mounted to copy files. It's using the same subsystems (well...tmpfs versus reading from an actual filesystem, but still...same overall subsystem), which means you can't hide one without hiding the other (and users rarely want to hide mounted flash drives from their sidebar).

**Comment by bertradio** [comment]
Thanks. It's a minor inconvenience that I can live with.

On Sun, Feb 17, 2019, at 12:38, ಚಿರಾಗ್ ನಟರಾಜ್ wrote:
> Not that I know of, nope. Unless you can configure the file manager
> not to show you mounted stuff (which would probably be inconvenient in
> the general use case).> The fundamental problem here is that stuff mounted by firejail (to
> hide things) appears exactly the same as, say, a flash drive you
> mounted to copy files. It's using the same subsystems (well...tmpfs
> versus reading from an actual filesystem, but still...same overall
> subsystem), which means you can't hide one without hiding the other
> (and users rarely want to hide mounted flash drives from their
> sidebar).> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:

  1. https://github.com/netblue30/firejail/issues/2406#issuecomment-464505854

**Comment by glitsj16** [comment]
> I also run FF and firejail on another computer and there are no duplicates there. So it must have something to do with my installation or config files.

@bertradio Have you compared `~/.config/gtk-3.0/bookmarks` yet between both installations? Try shutting down your file-manager, remove any duplicates from that file and see if that helps at all.

**Comment by bertradio** [comment]
Yes. The bookmarks files are identical and there are no duplicates in the bookmark files.

**Comment by chiraag-nataraj** [comment]
Also, fwiw, this randomly stopped happening for me with my `firefox` profile (which you can find [here](https://github.com/chiraag-nataraj/firejail-profiles)).

**Comment by bertradio** [comment]
Thanks. But our systems seem different and it did not work on mine. I'll just live with the problem,

**Comment by rusty-snake** [comment]
I figured out when that happened.
Two condtitions must meet:
 1. `nobus`
 2. access to `/etc/fstab`

```bash
firejail --noprofile zenity --file-selection # NO
firejail --noprofile --nodbus zenity --file-selection # YES
firejail --noprofile --nodbus --private-etc=empty zenity --file-selection # NO
firejail --noprofile --nodbus --private-etc=fstab zenity --file-selection # YES
firejail --noprofile --nodbus --blacklist=/etc/fstab zenity --file-selection # NO
```

***

How could firejail prevent that?

1. Adding `blacklist /etc/fstab` where possible to profiles with `nodbus` 
2. Mounting with `x-gvfs-hide`

```bash
mkdir tmp1 tmp2
sudo mount --bind tmp1 tmp2
zenity --file-selection # tmp2 is shown
sudo umount tmp2
sudo mount -o x-gvfs-hide --bind tmp1 tmp2
zenity --file-selection # tmp2 is hidden
```

***

Disclaimber: I have only tried and worked with GTK/GIO/GVFS.

**Comment by rusty-snake** [comment]
@bertradio Adding this `HAS_NODBUS: blacklist /etc/fstab` to `globals.local` should work.
