### ISSUE TITLE
Start application with *firejail --seccomp* or not?

### ISSUE THREAD

**Issue by Goderw** [netblue30/firejail#241]
Hello,

it isn`t an issue at all, but in the Arch-Linux-Wiki they say that firejail has to start with "firejail --seccomp firefox" for example. In your "wiki" I can read --seccomp isn't neccessary because there is a filter list for firefox anyway.

Well, which setting gives the most protection to start Firefox in this case -> With --seccomp or w/o? 

Thanks for this great invention!!

**Comment by Goderw** [comment]
Additionally:
I have testet both... and in both cases "grep Seccomp /proc/<PID>/status" shows that *seccomp 2* is enabled. So I think I can run "firejail firefox" w/o --seccomp in line!

**Comment by netblue30** [comment]
It is not necessary anymore. I've made it default.
