### ISSUE TITLE
Firecfg claims "symlinks were created", though none working

### ISSUE THREAD

**Issue by rugabunda** [netblue30/firejail#2410]
Using Lubuntu 18.10 LXQT. (Cosmic Cuttlefish)  Depending on your internet speed, you can test to recreate with this pre-made vm in just minutes: https://www.osboxes.org/lubuntu/ what an amazing os. fastest & sexiest ever made imo.

Solution? Must add 'firejail' in .desktop links under /user/share/application after "exec", then firejail loads them fine in terminal, desktop link, start menu, and third party app URL's for browsers; would recommend firecfg does both to avoid such confusion in the future.  Even wget is listed there.

**Comment by rugabunda** [comment]
This also works for browsers loaded from third party applications and windows.

**Comment by SkewedZeppelin** [comment]
> Must add 'firejail' in .desktop links under /user/share/application after "exe

please do not do this

can you post the output of `$PATH`, you might not have /usr/local/bin in yours

**Comment by rugabunda** [comment]
its the only thing that works for me, so I must at the moment do this.

bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory

**Comment by rugabunda** [comment]
/usr/local/bin ls

2048-qt           display        firefox      localc          lomath      pdftotext  soffice              vlc        xpra
ark               dnsmasq        k3b          lodraw          loweb       qlipper    ssh                  wget
chromium-browser  enchant        kcalc        loffice         lowriter    qpdfview   strings              wireshark
cvlc              enchant-lsmod  less         lofromtemplate  lximage-qt  quassel    torbrowser-launcher  xcalc
dig               feh            libreoffice  loimpress       patch       skanlite   transmission-qt      Xephyr
```

firecfg --list

/usr/local/bin/enchant
/usr/local/bin/torbrowser-launcher
/usr/local/bin/lximage-qt
/usr/local/bin/transmission-qt
/usr/local/bin/wget
/usr/local/bin/lomath
/usr/local/bin/patch
/usr/local/bin/xcalc
/usr/local/bin/pdftotext
/usr/local/bin/enchant-lsmod
/usr/local/bin/lodraw
/usr/local/bin/libreoffice
/usr/local/bin/cvlc
/usr/local/bin/2048-qt
/usr/local/bin/k3b
/usr/local/bin/display
/usr/local/bin/soffice
/usr/local/bin/ark
/usr/local/bin/qpdfview
/usr/local/bin/lowriter
/usr/local/bin/Xephyr
/usr/local/bin/firefox
/usr/local/bin/dig
/usr/local/bin/vlc
/usr/local/bin/ssh
/usr/local/bin/quassel
/usr/local/bin/loweb
/usr/local/bin/loffice
/usr/local/bin/strings
/usr/local/bin/skanlite
/usr/local/bin/wireshark
/usr/local/bin/localc
/usr/local/bin/chromium-browser
/usr/local/bin/kcalc
```

still not working

**Comment by rugabunda** [comment]
Oh i notice firejail does check .destkop files, will firecfg --fix do this for me?

**Comment by SkewedZeppelin** [comment]
> will firecfg --fix fix this issue for me

that is for fixing hardcoded program paths

.
.
your $PATH seems fine and firecfg did make the symlinks

are you logged in as root?
what is the output of running eg. `firejail /usr/bin/wget`
what about `which wget`

**Comment by rugabunda** [comment]
it says wget, missing url etc. i am logged on as admin. i ran firejail as sudo, not 'sudo -i' root. 

interestingly yesterday when I ran wget (url large file), using another terminal with firejail --list showed wget was not firejailed. however it is working now. I will test other apps and remove my custom .desktop changes and see what happens now.

**Comment by rugabunda** [comment]
Confirmed, everything is working as intended. I have no idea what the heck happened but its all good now. Just one question o/t from the original question, when I load tor firejail shows tor-browser-launcher is firejailed however once the actual tor browser is opened, it does not say tor-browser or tor.profile is firejailed... are extra steps necessary, or does firejailed tor-browser-launcher cover all child processes the same way?

**Comment by rugabunda** [comment]
updated previous comment for clarity

**Comment by rugabunda** [comment]
Does apparmor firefox set to enforce require running firejail --apparmor firefox? or is this redundant, thank y ou
