### ISSUE TITLE
Feh: Standard config does not allow internet access

### ISSUE THREAD

**Issue by pianoslum** [netblue30/firejail#2414]
The image viewer feh can access pictures in the internet if you pass a url. E.g.:
`feh https://i.imgur.com/FzdARaX.jpg`
However, the current standard config blocks internet access; I found that you have to uncomment
`net none`,
`protocol unix` and
`private-etc feh`
in order to make it work again.

I am not sure what a good standard would be (options in or out), but either way, we should add a comment explaining that these options are needed for web access.
What do you think?

**Comment by chiraag-nataraj** [comment]
> I found that you have to uncomment

I think you meant comment.

In my opinion, there is absolutely _no_ reason an image viewer(!) should have access to the internet by default.

> [...] we should add a comment explaining that these options are needed for web access.

Sure. I would actually go so far as to make a `feh-relaxed.inc` file which isn't included by default. Then, if people want to allow this, they can simply include `feh-relaxed.inc` in their `feh.local` file (even if you want it to have internet access, you don't need to allow access to _all_ of `/etc`).

**Comment by pianoslum** [comment]
Yeah you're right :-)
Regarding private-etc: I agree with you, but there seems to be something that feh needs to access; is there an easy way how to find which this is?

**Comment by chiraag-nataraj** [comment]
Try adding `private-etc hosts,resolv.conf` as another line (they're additive, which means this will be done _in addition_ to `private-etc feh`).

**Comment by pianoslum** [comment]
I tried that, unfortunately it's not enough apparently :-(

**Comment by chiraag-nataraj** [comment]
So it looks like it needs whatever `curl` needs (they list `libcurl4`, on Debian anyway, as a dependency). Aaaand it looks like we commented out `private-etc` in `curl.profile` (probably because something broke lol). But maybe the `private-etc` line there is a starting point?

**Comment by chiraag-nataraj** [comment]
I just tried it and `private-etc feh,resolv.conf,ssl` worked for me. What error does `feh` give you when you try that `private-etc` line?

**Comment by pianoslum** [comment]
There was a symlink in ssl to /etc/certificates, so adding this did the trick:
`private-etc feh,resolv.conf,ca-certificates,ssl`

This might depend on the distribution, I use Arch x64

**Comment by chiraag-nataraj** [comment]
I'm happy to add your line along with `ignore net none` into a `feh-networked.inc` file which people can include if they so choose.

**Comment by pianoslum** [comment]
Thanks for that - I still need to comment `protocol unix`, otherwise it doesn't work .-(

**Comment by rusty-snake** [comment]
@pianoslum or better: `protocol unix,inet,inet6`

**Comment by pianoslum** [comment]
@chiraag-nataraj I would add a PR, but I do not know how to "whitelist" `protocol unix`. Could you give me a hint here?
Otherwise, feh-networkingis still not working :-|
