### ISSUE TITLE
Change window title in sandbox

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#242]
From wordpress:

Hello,
Not sure if this is possible since I’m not sure how each desktop manager handles it, but would it be possible to change the window title for applications sandboxed with firejail? For example, change “app_title” in the taskbar to read “[sandbox_name] app_title” when the program is running inside the sandbox.
Thanks!

**Comment by Goderw** [comment]
Good idea... but I think it is better to simply add a * on both sides of app_tittle , because it is less space intensive (look at audacious in the [sanbox_name] case for example).

Just my 2 cents.

**Comment by netblue30** [comment]
I added support to name the window "Firejail" when running in a terminal. For GUI programs I don't have a solution.
