### ISSUE TITLE
[Tor Browser] ‘./Browser/execdesktop’: No such file or directory

### ISSUE THREAD

**Issue by brainscar** [netblue30/firejail#2429]
Hi,

Thank you for your hard work.
I was wondering if you could help me with the following issue:

**OS:** Manjaro Linux
**Package used:** https://aur.archlinux.org/packages/tor-browser

When I try to run tor browser as such:

`firejail --profile=/etc/firejail/start-tor-browser.profile /home/brainscar/.tor-browser/app/start-tor-browser.desktop`

I get the following error:

`/usr/bin/env: ‘./Browser/execdesktop’: No such file or directory`

This is start-tor-browser.desktop:

```
[Desktop Entry]
Type=Application
Name=Tor Browser
GenericName=Web Browser
Comment=Tor Browser is +1 for privacy and -1 for mass surveillance
Categories=Network;WebBrowser;Security;
Exec=sh -c '"/home/brainscar/.tor-browser/app/Browser/start-tor-browser" --detach || ([ !  -x "/home/brainscar/.tor-browser/app/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser --detach)' dummy %k
X-TorBrowser-ExecShell=./Browser/start-tor-browser --detach
Icon=/home/brainscar/.tor-browser/app/Browser/browser/chrome/icons/default/default128.png
StartupWMClass=Tor Browser
```

Hope you can help.

Thank you.

**Comment by rusty-snake** [comment]
1. `$HOME/.tor-browser/` is not whitelisted, fix: `firejail --whitelist=$HOME/.tor-browser --profile=/etc/firejail/start-tor-browser.profile /home/brainscar/.tor-browser/app/start-tor-browser.desktop`
2. You must execute this in `$HOME/.tor-browser/app/`, fix: `firejail --profile=/etc/firejail/start-tor-browser.profile $HOME/.tor-browser/app/Browser/start-tor-browser --detach`

**Final fix:** `firejail --whitelist=$HOME/.tor-browser --profile=/etc/firejail/start-tor-browser.profile $HOME/.tor-browser/app/Browser/start-tor-browser --detach`

**Comment by smitsohu** [comment]
It will not work if the desktop file is not whitelisted. Can you try:

`firejail --profile=/etc/firejail/start-tor-browser.profile --whitelist=/home/brainscar/.tor-browser/app/start-tor-browser.desktop --read-only=/home/brainscar/.tor-browser/app/start-tor-browser.desktop /home/brainscar/.tor-browser/app/start-tor-browser.desktop`

General question: Are the colon characters in `/etc/firejail/start-tor-browser.desktop.profile` supposed to be there?

**Comment by smitsohu** [comment]
@rusty-snake you won :smile:

**Comment by rusty-snake** [comment]
@smitsohu Yes. I know the issue FJ + TBB well several discussions in german forums, so I'm working on a tutorial right now.

**Comment by SkewedZeppelin** [comment]
@rusty-snake @brainscar  what is wrong with using torbrowser-launcher?


>  Are the colon characters in start-tor-browser.desktop.profile supposed to be there? 

@smitsohu I don't think so

**Comment by rusty-snake** [comment]
@SkewedZeppelin torbrowser-launcher has IMHO some annoying Issues.

**Comment by brainscar** [comment]
Thank you so much @rusty-snake you're awesome. That totally worked.
