### ISSUE TITLE
Firejail only runs as root? OpenSuse

### ISSUE THREAD

**Issue by BARNWEY** [netblue30/firejail#2434]
Hi! I'm currently trying to run firejail on Opensuse Tumbleweed, but I find that I can only run it as root. Given that I use the mate desktop with x11, this is a huge issue for me. I have xpra and zephyr both installed, and all dependencies as well. However, if I try to run firejail without root I get this error:
$ /usr/bin/firejail: Permission Denied

Meanwhile, if I try to run root, I get the error that I can't run firejail as root on x11

Can someone please help me out? I get the feeling that I could use chown on that folder, but then that might cause issues. If someone could please let me know I'd be very grateful. Thank you

**Comment by smitsohu** [comment]
Can you post the output of `ls -l /usr/bin/firejail`

**Comment by Vincent43** [comment]
AFAIK on openSUSE firejail acces is restricted to `firejail` system group. You have to add your user to that group in order to use it.

**Comment by matu3ba** [comment]
@BARNWEY Could you provide feedback?
Otherwise this can be probably closed.
