### ISSUE TITLE
Steam profile blocks gamepad (dualshock 3)

### ISSUE THREAD

**Issue by DevPre24** [netblue30/firejail#2448]
Distro: Arch Linux
Kernel version: 4.20.11-arch2-1-ARCH
Firejail version: 0.9.58.2-1

Description: When starting steam with the included profile my gamepad (Sony Dualshock 3 connected with a usb cable) is not detected by steam.

Escaping the sandbox with:
```firejail --noprofile steam-runtime```
solves the problem but it's not ideal since it leaves open an attack surface. 

Related to: #779

**Comment by Fred-Barclay** [comment]
@DevPre24 Can you make sure that you're using the steam profile by `firejail --profile=/etc/firejail/steam.profile steam-runtime`?

If it still fails, please try each of the following:
`firejail --ignore=protocol --profile=/etc/firejail/steam.profile steam-runtime`

`firejail --ignore=private-dev --profile=/etc/firejail/steam.profile steam-runtime`

**Comment by DevPre24** [comment]
> @DevPre24 Can you make sure that you're using the steam profile by `firejail --profile=/etc/firejail/steam.profile steam-runtime`?

Same result so i'm guessing the correct steam profile is loaded.

> If it still fails, please try each of the following:
> `firejail --ignore=protocol --profile=/etc/firejail/steam.profile steam-runtime`

Same result.

> `firejail --ignore=private-dev --profile=/etc/firejail/steam.profile steam-runtime`

Ignoring "private-dev" the gamepad (wired dualshock 3) is correctly detected and works as expected.

**Comment by rusty-snake** [comment]
@DevPrev24 I'm closing here due to inactivity, please fell free to reopen if you have more questions.
