### ISSUE TITLE
blacklist not working with /run/user/*/gvfs

### ISSUE THREAD

**Issue by Saren-Arterius** [netblue30/firejail#245]
I am using gnome 3.18. It can mount smb share using gvfs.

I am trying to prevent Firefox from access the gvfs. However, after `blacklist /run/user/1000/gvfs`  /run/user/1000/gvfs can still be accessed, while `blacklist /run/user/1000/gdm` produces expected results.

`$ firejail --blacklist=/run/user/1000/gvfs` and `$ firejail --blacklist=/run/user/1000/gdm` also reproduce the problem.

What am I doing wrong here? What can I do to `blacklist /run/user/1000/gvfs` properly?

**Comment by netblue30** [comment]
Fixed! There will be some more testing, but it is basically working. Thanks for the bug.

**Comment by Saren-Arterius** [comment]
Relevant commit: https://github.com/netblue30/firejail/commit/dfdf8603e231b73e502e080176dd763d4ecb43d2
