### ISSUE TITLE
sandbox selected applications upon startup

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2471]
If I were to sandbox selected applications upon startup, how do I set it up in such a way that if I were to click on the shortcut on the DE tasbar (not the firetool taskbar), then how do I get it to launch under firejail?

**Comment by smitsohu** [comment]
You can run `sudo ln -s /usr/bin/firejail /usr/local/bin/PROGRAM`,
for example that would be `sudo ln -s /usr/bin/firejail /usr/local/bin/firefox` for firefox

You can use the firecfg tool to do this for all programs with an existing profile: `sudo firecfg`
With `sudo firecfg --clean` you get back to where you are now.

**Comment by chiraag-nataraj** [comment]
Seems like this was answered, so I'm going to go ahead and close this, but @Raj2032, please feel free to re-open if you have more questions.
