### ISSUE TITLE
How is pulseaudio working for FJ urers

### ISSUE THREAD

**Issue by Zypherspace** [netblue30/firejail#2472]
I have to:
`killall pulseaudio`
at every boot to get fj'ed sandboxes to connect to pulse audio prperly. Even then virtualbox VMs don't.
Running latest Fedora Cinnamon latest distro. Is this common experience?

**Comment by SkewedZeppelin** [comment]
Tested Fedora 29 GNOME, MATE, and Cinnamon: audio works just fine.

are you using HDMI audio output or bluetooth?
have you modified /etc/firejail/globals.local?

**Comment by netblue30** [comment]
You could also run "firecfg --fix-sound" from a terminal. It will set Pulse for your user account with a very general configuration known to work with firejail. After you run the command you need to logout and login again to have the Pulse server restarted.

**Comment by chiraag-nataraj** [comment]
@Zypherspace, is this still an issue for you?

**Comment by rusty-snake** [comment]
@Zypherspace 
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
