### ISSUE TITLE
Whitelist ~/.cache/fontconfig/ by default

### ISSUE THREAD

**Issue by Lymia** [netblue30/firejail#248]
I noticed that some programs like Firefox take forever to launch under firejail, and eat up 100% of a core while launching, while test cases like "firejail bash" didn't.

I investigated a bit, and it seems that white-listing ~/.cache/fontconfig/ makes Firefox launch a lot faster. Without it, I believe Firefox's rebuilding the font cache on every startup.

**Comment by Saren-Arterius** [comment]
also ~/.config/fontconfig/

**Comment by netblue30** [comment]
It is already fixed in git for the next release. Thanks.

**Comment by Lymia** [comment]
Is it? I don't see ~/.cache/fontconfig anywhere in the tree, only ~/.config/fontconfig. It's a different directory.

$ grep -r "fontconfig"
etc/conkeror.profile:whitelist ~/.fontconfig
etc/whitelist-common.inc:whitelist ~/.fontconfig
etc/whitelist-common.inc:whitelist ~/.config/fontconfig

**Comment by netblue30** [comment]
OOPS! I put it in now, thanks!
