### ISSUE TITLE
firejail --zsh complains about insecure directories

### ISSUE THREAD

**Issue by balkierode** [netblue30/firejail#249]
➜  ~  firejail --zsh
    Reading profile /etc/firejail/generic.profile
    Reading profile /etc/firejail/disable-mgmt.inc
    Reading profile /etc/firejail/disable-secret.inc
    Reading profile /etc/firejail/disable-common.inc

    ** Note: you can use --noprofile to disable generic.profile **

    Parent pid 6033, child pid 6034
    Child process initialized
    zsh compinit: insecure directories and files, run compaudit for list.
    Ignore insecure directories and files and continue [y] or abort compinit [n]? y%                                                                                         ➜  ~
    ➜  ~  compaudit
    There are insecure directories and files:
    /usr/share/zsh/functions/Calendar
    /usr/share/zsh/functions/Chpwd
    /usr/share/zsh/functions/Completion
    /usr/share/zsh/functions/Completion/AIX

I guess most likely this has to be fixed in zsh. However I may be wrong. I think the problem is because the files are not owned by root inside the jail. Can it be made to appear as if they are owned by root inside the jail?

    ➜  ~  ls -ld /usr/share/zsh/functions/Calendar
    drwxr-xr-x 2 root root 4096 Nov  4 11:46 /usr/share/zsh/functions/Calendar
    ➜  ~  firejail
    Reading profile /etc/firejail/generic.profile
    Reading profile /etc/firejail/disable-mgmt.inc
    Reading profile /etc/firejail/disable-secret.inc
    Reading profile /etc/firejail/disable-common.inc

    ** Note: you can use --noprofile to disable generic.profile **

    Parent pid 8791, child pid 8792
    Child process initialized
    groups: cannot find name for group ID 65534
    [bala@superadmin-OptiPlex-7010 ~]$ ls -ld /usr/share/zsh/functions/Calendar
    drwxr-xr-x 2 65534 65534 4096 Nov  4 11:46 /usr/share/zsh/functions/Calendar
    [bala@superadmin-OptiPlex-7010 ~]$

**Comment by netblue30** [comment]
The files are indeed owned by root, however the default profile installs a user namespace without root user (--noroot) - this is why root files appear to be owned by that fake user 65534. I think it is a zsh problem.
