### ISSUE TITLE
memory-deny-write-execute: also block memfd_create?

### ISSUE THREAD

**Issue by topimiettinen** [netblue30/firejail#2496]
`memfd_create()` followed by `mmap(,,PROT_EXEC)` (i.e. without `PROT_WRITE`) can be used to create executable memory with any contents and thus avoid `memory-deny-write-execute` protections. Would it be OK to just block `memfd_create()` when `memory-deny-write-execute` is enabled? It would mean some incompatibility and possibly some profiles could break.

If that is not OK, the manual page could just recommend adding `memfd_create()` to seccomp filters manually, or a new flag could be introduced like `memory-deny-write-execute-v2`.

**Comment by Fred-Barclay** [comment]
I think @netblue30 mentioned putting out an rc candidate in the next few weeks. Could we maybe add this idea and try it out? If it causes lots of issues we could fix quickly before releasing an rc2.

**Comment by topimiettinen** [comment]
I opened PR #2504.

**Comment by topimiettinen** [comment]
Closed by 59e3061, let's see if anything breaks.
