### ISSUE TITLE
How to install deb packages inside chroot firejail

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2503]
I downloaded a deb package in my main system, now I want to know how do I run the deb package inside the chroot firejail?

**Comment by smitsohu** [comment]
I assume this is a continuation of #2477?

Just `chroot` into the directory and install the package like you normally do. Once the application is installed, run it with `firejail --chroot=/directory`.

Don't forget to keep chroot environment and application up to date.

**Comment by smitsohu** [comment]
I'm assuming here that you populated the chroot directory with a tool like debootstrap.
DON'T install something in the chroot if all is only bind-mounts.
