### ISSUE TITLE
firejail doesn't detach

### ISSUE THREAD

**Issue by vorticalbox** [netblue30/firejail#2513]
I am running parrotOS and some times when I run a terminal command such as vscodeium . the terminal doesn't detach and just sits in the terminal.

```
└──╼ $vscodium .
Reading profile /etc/firejail/vscodium.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Parent pid 3964, child pid 3966
Child process initialized in 76.81 ms
```

**Comment by smitsohu** [comment]
You mean the sandbox keeps running after you close the main app? It means there is still a process running in the sandbox. Firejail only shuts down when the sandbox is empty.

You could run `firejail -tree` to get an idea what is going on.

**Comment by vorticalbox** [comment]
Normally when you run a command such as for email firefox

The process stops in the terminal window but from time to it just stops at the last part until you close it

**Comment by smitsohu** [comment]
> until you close it

You mean until you close the terminal ... ?

**Comment by vorticalbox** [comment]
Close the app.

normaly the command stops and drops you back into the shell not wait until thwbapp is closed

**Comment by smitsohu** [comment]
> normaly the command stops and drops you back into the shell not wait until thwbapp is closed

Actually this is what I would expect to happen. When you run `firejail firefox` the next time and you drop back right away into the shell, can you check the output of `firejail --list` if [Firefox is indeed sandboxed](https://firejail.wordpress.com/support/#firefox)?

**Comment by chiraag-nataraj** [comment]
@vorticalbox, were you able to check this?

**Comment by vorticalbox** [comment]
I'm afraid not I haven't done any security testing at work that has required me to spin up my VM.

If I have time tomorrow I'll give it a go.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/issues/2698#issuecomment-493028100

> `firejail sh -c "sleep 1m &"` didn't go in background. Not sure how firejail handel stdin/out and fg/bg.

**Comment by chiraag-nataraj** [comment]
@vorticalbox I'm going to go ahead and close this for now, but please feel free to re-open if you're able to test out our suggestion.
