### ISSUE TITLE
[Info] seccomp enhancements in Linux 5.0

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#2514]
Linux 5.0 got seccomp enhancements which might be useful for future Firejail versions:

https://git.kernel.org/torvalds/c/6a21cc50f0c7f87dae5259f6cfefe024412313f6
https://git.kernel.org/torvalds/c/fec7b6690541b8128663a13c9586b1daf42b0a6c

Background:
https://lwn.net/Articles/756233/
https://youtu.be/sqvF_Mdtzgg

But I'm sure you guys are already aware of those changes :-)

**Comment by topimiettinen** [comment]
New sandboxing features could use this for example to check socket addresses for additional firewalling,  to filter ioctls based on the file path of the file descriptor via /proc/PID/fd, or to implement a simple MAC for /proc or /sys by checking path to open() etc.

The enhancements could be used to make seccomp work also on i386, where some set of system calls are multiplexed into one and arguments are passed with a pointer to a structure. Now some of the filters just don't work on i386.

But a big showstopper for most of the above is lack of fd passing. Hopefully that will be added soon.

**Comment by chiraag-nataraj** [comment]
Any progress on this stuff?

**Comment by topimiettinen** [comment]
I don't know if kernel has fd passing yet.

i386 and most other archs got unmultiplexed versions of system calls in end 2018, so there's no need to demultiplex anymore with recent kernels.

**Comment by rusty-snake** [comment]
Can we close here?
