### ISSUE TITLE
noexec ${HOME} breaks Discord

### ISSUE THREAD

**Issue by binaryronin** [netblue30/firejail#2518]
System:
```
Linux 5.0.0-arch1-1-ARCH #1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019 x86_64 GNU/Linux
```
The `discord-common.profile` includes `noexec ${HOME}` which causes Discord to start and then hang with a blank window (background loads but nothing else). Removing `noexec ${HOME}` allows Discord to start normally. I've run the jail via the console and didn't see anything immediately obvious as to why this is happening.

**Comment by Fred-Barclay** [comment]
Can confirm on Debian Stable as well (kernel 4.9).

**Comment by Fred-Barclay** [comment]
Fixed, thanks!
