### ISSUE TITLE
Many firejails aren't whitelisting /home/downloads/

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#2519]
Several generic profiles (VLC, PIX) have become unable to access files in my /home/downloads/ folder. For instance if I try to launch a video in /home/ with VLC it can't access the directory. If I launch VLC without firejail it works as expected. Firefox works as expected in firejail..

I think some permissions got mucked up but I did a full Firejail scrub and reinstall from git. 
Any clues?

**Comment by SkewedZeppelin** [comment]
Is your Downloads forlder named "Downloads", "Загрузки", "Téléchargement" or defined in your ~/.config/user-dirs.dirs?

**Comment by Futureknows** [comment]
Yes "Downloads", `XDG_DOWNLOAD_DIR="$HOME/Downloads"`
I had to restore r/w permissions to home after a Timeshift, I believe this has to do with permissions but only occurs in certain firejails. Globals are default. When I use firestats to explore the file system of those FJed, it shows Download's permissions as root although firejail is running as user with full permissions.

**Comment by FOSSONLY** [comment]
Hm.. it looks like these profiles lacking an "whitelist ${DOWNLOADS}" entry.

**Comment by Futureknows** [comment]
OK, I manually whitelisted using `whitelist ${DOWNLOADS}`

**Comment by SkewedZeppelin** [comment]
VLC and PIX don't have downloads whitelisted because they aren't whitelist profiles.
