### ISSUE TITLE
Tightening unbound and dnscrypt-proxy profiles

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#252]
I've been running unbound and dnscrypt-proxy firejailed for quite some time with

/etc/firejail/disable-common.inc
/etc/firejail/disable-devel.inc
/etc/firejail/disable-secret.inc

added to the default profiles with no negative side effects. Thus, I suggest to add those .inc files to the profiles if nobody objects.

**Comment by netblue30** [comment]
I put it in, let's see what happens!
