### ISSUE TITLE
Block port access

### ISSUE THREAD

**Issue by tinfoil123** [netblue30/firejail#253]
How do I stop a firejailed program from accessing port X?

**Comment by netblue30** [comment]
You need to create a network namespace and install your own iptables filter. Example:

$ firejail --net=eth0 --netfilter=/etc/firejail/nolocal.net firefox

I have some sample netfilters in /etc/firejail/*.net. Take one of them and modify it. It has the same syntax as iptables - in fact I am using iptables-restore to install the filter inside the sandbox.
