### ISSUE TITLE
"browser-disable-u2f no" does not enable U2F for FireFox

### ISSUE THREAD

**Issue by njfox** [netblue30/firejail#2531]
I'm using firejail 0.9.58.2 on Arch Linux with apparmor enabled. I'm using a NitroKey FIDO U2F security key.

The U2F key is not working in FireFox, even after explicitly setting `browser-disable-u2f no` in `/etc/firejail/firejail.config`. The only way to get the key working was to completely comment out the following line in `/etc/firejail/firefox-common.profile`:
```
#?BROWSER_DISABLE_U2F: nou2f
```

More information in the discussion here: #2247

**Comment by njfox** [comment]
Upon further testing, I've noticed that 2 things are required to make the U2F key work in FireFox under firejail:

1. I have to explicitly set `browser-disable-u2f no` in `/etc/firejail/firejail.config`. Is there some security benefit to disabling U2F keys by default? 
2. It doesn't work if I insert the key while FireFox is running. It only works if the key is inserted when FireFox is launched, which is reasonably annoying. This means I have to restart my browser to complete a log-in if my key wasn't inserted when I started FireFox.

**Comment by glitsj16** [comment]
> I have to explicitly set browser-disable-u2f no in /etc/firejail/firejail.config.

@njfox Have you tried `ignore nou2f` in a firefox-common.local file or in your browser start command yet?

**Comment by SkewedZeppelin** [comment]
@glitsj16 afaik `ignore nou2f` won't work since `ignore` matches the whole line which in this case has a conditional prepended to it.

@njfox to confirm, you did uncomment the line in `firejail.config` ?

> It doesn't work if I insert the key while FireFox is running.

That will never work, the sandbox has its state set at start and cannot be changed after.

> Is there some security benefit to disabling U2F keys by default?

Yes. See the reasoning here https://github.com/netblue30/firejail/issues/2194#issue-369906681

**Comment by njfox** [comment]
> @njfox to confirm, you did uncomment the line in firejail.config ?

Here is my firejail config that makes the key work:

```
# Disable U2F in browsers, default enabled.
browser-disable-u2f no
```

**Comment by glitsj16** [comment]
@SkewedZeppelin Thanks for explaining. Now you mention ignore matching the `whole` line I should have known that won't work. I have a few `ignore ignore blah` lines in local overrides and remember being happily surprised firejail is that smart :smile: .
