### ISSUE TITLE
Flameshot raw screenshot issue

### ISSUE THREAD

**Issue by 7twin** [netblue30/firejail#2548]
Executing `flameshot gui -r` which is supposed to just output back the raw screenshot, adds the command at the start when run in firejail, causing all images to be invalid, e.g. the header of the image file turns into `]0;firejail flameshot gui -r` or `]0;firejail /usr/bin/flameshot gui -r `.

**Comment by glitsj16** [comment]
Please test with enabling the `quiet` option, to silence firejail output.

$ firejail --quiet /usr/bin/flameshot gui -r

If that works you can add it (without leading dashes) either in ~/.config/firejail/flameshot.local or /etc/firejail/flameshot.local until fixed.

**Comment by 7twin** [comment]
@glitsj16 that fixed it, thanks! I'll add it as PR for review, so we can close the issue itself and possibly have it merged into the regular non-local flameshot profile - if it doesn't introduce any issues.
