### ISSUE TITLE
Firefox-developer desktop launches regular firefox

### ISSUE THREAD

**Issue by 7twin** [netblue30/firejail#2551]
Having both firefox developer and regular firefox installed; opening firefox-developer from the modified desktop file - opens regular firefox instead.

**Comment by rusty-snake** [comment]
@7twin,
  * How did you install FF and FF-dev?
  * Is the "normal" FF runing when you try to open FF-dev?
  * How the `.desktop` for FF-dev looks?

**Comment by 7twin** [comment]
@rusty-snake

- Both installed via aur helper, so not sure if pulled from official repos or aur (will check that) 
- Yes, the 'regular' Firefox was opened when I tried to open FF-dev
- I'll check the actual .desktop-file in a moment but when I opened it via properties, it had 'firefox' as the command instead of 'firefox-developer-edition', switching that fixed it

**Comment by 7twin** [comment]
@rusty-snake 

- Regular firefox: `extra/firefox 65.0.2-1`
- Firefox-developer: `community/firefox-developer-edition 66.0b13-1`

After I fixed the command from "firefox" to "firefox-developer-edition" in the properties, the script seems to ignore it now and just keep my changes.

**Comment by rusty-snake** [comment]
@7twin Did I understand you right that ff and ff-dev are work at the same time?

**Comment by 7twin** [comment]
@rusty-snake with or without jails?

**Comment by rusty-snake** [comment]
with FJ.

**Comment by 7twin** [comment]
@rusty-snake sadly I don't remember anymore as I have for now wiped FJ, as further explained here: https://github.com/netblue30/firejail/issues/2550#issuecomment-474088414

I'll be sure to update this issue once I am able to test this again though, with the discord profiles being added.

**Comment by chiraag-nataraj** [comment]
I guess I'll close this for now. @7twin, please feel free to re-open if and when you test firejail again.
