### ISSUE TITLE
Trust Certificates

### ISSUE THREAD

**Issue by m2freem** [netblue30/firejail#2578]
I would like to be able to run:
`firejail --private firefox -private -no-remote`
and be able to have certificates that have been added to the trust store still be active.  Certificate is for a trusted root-ca serving internal webpages.  I want to start with a clean slate with only the added certificates.  Is there an easy way to do this?

**Comment by smitsohu** [comment]
If the certificate is to be stored in ~/-mozilla, you could provide a minimal ~/.mozilla template with just the certificate inside and start firefox like
`firejail --private-home=.mozilla firefox -private -no-remote`

**Comment by m2freem** [comment]
Thank you
