### ISSUE TITLE
Extra character in error output

### ISSUE THREAD

**Issue by probonopd** [netblue30/firejail#2593]
```
firejail ./BeingTested.AppImage /run/firejail/appimage/.appimage-8400/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-8400/AppRun)
```

THe extra character ` ` is annoying. What is it?

**Comment by glitsj16** [comment]
That might be part of firejail's verbose output. Does it still show when you add `--quiet` to the command that produced that output (which was?).

**Comment by chiraag-nataraj** [comment]
@probonopd Is this still an issue? (I presume it is, but without more info, we can't really dig in at all...)

**Comment by probonopd** [comment]
Yes, this is still an issue.

We are using Firejail as part of an [automated test script](https://github.com/AppImage/appimage.github.io/blob/2b4324c74670dccd11a91974d940f8b77a47d433/code/worker.sh#L207-L220) for [testing various AppImages](https://github.com/AppImage/appimage.github.io) that is running on [Travis CI](url).

I am now adding `--quiet` to see whether it makes a difference.

**Comment by probonopd** [comment]
Actually Travis CI might be inserting this for some weird reason as I see similar characters in other places too:


```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
[34m[1mclang version[0m
clang version 7.0.0 (tags/RELEASE_700/final)
[34m[1mjq version[0m
jq-1.5
[34m[1mbats version[0m
Bats 0.4.0
(...)
===========================================
============= TRYING TO RUN ===============
===========================================
Dropping all Linux capabilities and enforcing default seccomp filter
]0;firejail ./BeingTested.AppImage /run/firejail/appimage/.appimage-8270
```

Raw log:
https://api.travis-ci.org/v3/job/526070556/log.txt

**Comment by probonopd** [comment]
With `--quiet` I don't get the line in question at all, and hence I also don't get the weird characters.

**Comment by chiraag-nataraj** [comment]
Going to close as the problem was apparently resolved and/or is probably not a firejail bug. @probonopd, please feel free to re-open if you have more questions.
