### ISSUE TITLE
ubuntu 18:10 snap apps dissapeared from search after firejail set up

### ISSUE THREAD

**Issue by punksta** [netblue30/firejail#2597]
I have slack, webstorm and a few other apps installed using snap. Also some of default gnome apps like `gnome-system-monitor` are shipped through snap

After I installed firejail using `apt` and run firecfg, they disappeared from desktop search.

```
which slack
> /snap/bin/slack
```
![image](https://user-images.githubusercontent.com/13404754/54433219-5fa88400-473c-11e9-9b1d-3065ca36e624.png)

also if I run slack from terminal, icon of process looks not found.
![image](https://user-images.githubusercontent.com/13404754/54433456-ed846f00-473c-11e9-9529-c5a2fd4d902d.png)

it might be that firejail is blacklisting some snap folders for gnome desktop environment

**Comment by SkewedZeppelin** [comment]
Can you check in ~/.local/share/applications for .desktop overrides for those programs?

**Comment by punksta** [comment]
@SkewedZeppelin nothing overrides these programs in that path

**Comment by punksta** [comment]
```
snap list
core                     16-2.37.4               6531  stable    canonical✓    core
gnome-3-26-1604          3.26.0.20190228         82    stable/…  canonical✓    -
gnome-calculator         3.30.1                  260   stable/…  canonical✓    -
gnome-characters         3.30.0                  139   stable/…  canonical✓    -
gnome-logs               3.30.0                  45    stable/…  canonical✓    -
gnome-system-monitor     3.30.0                  57    stable/…  canonical✓    -
gtk-common-themes        0.1-16-g2287c87         1198  stable/…  canonical✓    -
intellij-idea-community  2018.3.5                126   stable    jetbrains✓    classic
postman                  6.7.1                   81    stable    postman-inc✓  -
skype                    8.34.0.78               66    stable    skype✓        classic
slack                    3.3.8                   12    stable    slack✓        classic
spotify                  1.1.0.237.g378f6f25-11  34    stable    spotify✓      -
webstorm                 2018.3.5                81    stable    jetbrains✓    classic
```
all these disappeared from default ubuntu search, but still available in terminal

**Comment by punksta** [comment]
`/var/lib/snapd/desktop/applications/` is location for snap's .desktop files

**Comment by punksta** [comment]
fixed after logout
