### ISSUE TITLE
Slack now performs log in only via browser

### ISSUE THREAD

**Issue by viq** [netblue30/firejail#2605]
Slack just changed how their application works, and you can log in to Slack *only* via browser, either requiring opening browser from Slack or opening Slack from browser.

I don't know yet what would be a good way to approach this.

**Comment by chiraag-nataraj** [comment]
Do they provide a URL to click? Or is it a "Click this button" kind of thing?

**Comment by viq** [comment]
It's a click this button that does xdg-open, you can't right click to get
URL

**Comment by glitsj16** [comment]
@viq The slack profile uses `private-bin slack,locale`.

> It's a click this button that does xdg-open...

Have you tried adding xdg-open to private-bin yet? Either in a slack.local file or from the command-line via --private-bin=xdg-open.

**Comment by chiraag-nataraj** [comment]
^ I would second @glitsj16. I suspect adding `xdg-open` to the `private-bin` invocation should help (although you probably need to have your browser already running, since starting the browser inside the `slack` sandbox would require loosening it a lot). @viq, can you try and report back? I would, but I exclusively use the webapp.

**Comment by chiraag-nataraj** [comment]
@viq Did @glitsj16's suggestion work?

**Comment by wellsaid** [comment]
I can confirm the same problem on my system.
I have tried @glitsj16 suggestion by adding xdg-open to /etc/firejail/slack.profile
```
#private-bin slack,locale
private-bin slack,locale,xdg-open
```
But it didn't solved the problem for me

**Comment by glitsj16** [comment]
After some experimenting I could open slack's login in an `already running firefox` by adding the below in /etc/firejail/slack.local (or ~/.config/firejail/slack.local). Making it `start` a new browser session would require crippling the profile to the point of `insecurity`, which is obviously advised against.

```
# Firejail profile for slack
# Persistent local customizations

# login with firefox
noblacklist ${HOME}/.mozilla
whitelist ${HOME}/.mozilla
private-bin firefox

# xdg-open support in a GNOME session
private-bin basename,cut,egrep,grep,head,readlink,sed,tr,which,xdg-mime,xdg-open

# uncomment the below if you need to support other desktop environments and
# finding all the needed commands for private-bin risks loosing all your hair
#ignore private-bin
```

As one can deduce from the added comments, this will take some adjusting when your default web browser is not firefox and you happen to run another desktop environment. Make sure you both noblacklist/whitelist needed `configuration paths` for your default browser and replace 'firefox' with your appropriate `browser command` in the `private-bin` option.

If one peeks inside xdg-open, you'll notice it relies on quite a wide array of commands to find the default handler for opening URL's. This makes it rather complex to create a well-balanced firejail profile that works under all possible environments for an application that relies on another application for login purposes. IMHO this goes against the grain of sandboxing by default, be it via firejail or via similar tools. It would make sense (at least it does for me) if we dropped `private-bin` here to avoid this fine mess.

**Comment by chiraag-nataraj** [comment]
Honestly, it feels better to run it unsandboxed just for initial login if it means we can tighten the sandbox for normal usage.
