### ISSUE TITLE
No /etc/firejail directory created

### ISSUE THREAD

**Issue by firejailfan** [netblue30/firejail#2610]
Hello everybody. 
I am entirely new to Github so bear with me if i sound like a noob. ;) 

I've been using Firejail for quite awhile now and I consider it a must-have essential, period. Always installing from Github and never had any problems until now and I can't find a solution. Here goes.

Yesterday I have installed Firejail for a friend on Peppermint OS 32 bit which broke Firefox 60 and I fixed that thanks to you guys. 
Today I installed a laptop with Lubuntu (Ubuntu 16.04 LTS) 32 bit, installed Firejail of course, wanted to fix Firefox 60, wanted to go to /etc/firejail and it wasn't there. Reinstalled the whole system 3 times, tried another Peppermint OS with Firejail but still no /etc/firejail directory. 

Writing this down has 2 purposes:
1) Letting you know about the issue and
2) Learning to know if this is temporary and/or if it is something that is been worked on.

With kind regards, firejailfan. :)

**Comment by SkewedZeppelin** [comment]
How are you installing?
make install goes into /usr/local/etc/firejail

**Comment by firejailfan** [comment]
Sorry for the incomplete info.
Yes I installed as you stated through `make install` and and `sudo firecfg`. You are right it usually DOES create the /etc/firejail directory but not since today. Yesterday was fine and everything worked as usual. 
All installations were done on Ubuntu 16.04 LTS 32bit CLEAN install and firejail cloned from the Github repository. It's getting late in my part of the world but will continue to install on other distros tomorrow to see what will happen.

**Comment by SkewedZeppelin** [comment]
`make install` will typically go into `/usr/local/` instead of `/` to avoid conflicts with a version installed via package manager

**Comment by firejailfan** [comment]
> `make install` will typically go into `/usr/local/` instead of `/` to avoid conflicts with a version installed via package manager

Aha! See, that's why I ask questions to find things out. Thanks, that answer is crystal clear. 
So said directory also hosts the profile files for applications as in `/etc/firejail` is that correct?

**Comment by Fred-Barclay** [comment]
That sounds right! Also, if you want to use /etc/firejail instead, run `./configure --prefix=/usr` before `make install`.

**Comment by firejailfan** [comment]
Perfect, thanks!
