### ISSUE TITLE
How to stop the specific sandbox (other than send SIGTERM to sandbox)?

### ISSUE THREAD

**Issue by wndkarem32** [netblue30/firejail#2613]
How do I stop the specific sandbox (other than send SIGTERM or "kill <pid>" command to sandbox)?
is there a command like "firejail --kill" or "firejail --stop" ?

**Comment by glitsj16** [comment]
I think you're looking for the `--shutdown` option, it accepts a name or PID. Very convenient in combination with `--name`, as it saves you a PID lookup.

$ firejail --name=foo my-favo-app
...
$ firejail --shutdown=foo

As always, you can add `name foo` to a local override file in ~/.config/firejail/foo.local or in /etc/firejail/foo.local.

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this, since it seems the question was answered :) @wndkarem32, please feel free to re-open if you have more questions related to this.
