### ISSUE TITLE
undocumented location of a profile files

### ISSUE THREAD

**Issue by ohbutgtol** [netblue30/firejail#2637]
Hello. 
Thank for your work, and for you being. 
Let me be short.

**System**: sparkylinux (rolling dist. based  on debian testing)
**Firejail version 0.9.59**
 Firejail installation time 2* march 2019

**Installation method** was by cloning from github:
`git clone https://github.com/netblue30/firejail.git`
`cd firejail`
`./configure && make && sudo make install-strip`
`firecfg --fix-sound`
`sudo firecfg`

**Issue:**
A profile files of firejail had been located  in  /usr/local/etc/firejail/
No installed man files of firejail-profile, no available in the internet manuals and tutorials don’t mention  such possibility
P.S Firejail work fine.  Thank you one more time.

**Comment by glitsj16** [comment]
@ohbutgtol Greetings.

>  A profile files of firejail had been located in /usr/local/etc/firejail/

You can fine tune installation directories by adding options to the ./configure command. Run `./configure --help` for available options. Adding `--prefix=/usr` should take care of this. Perhaps you can take some inspiration from the included shell files to create installable Debian packages:
- [with](https://github.com/netblue30/firejail/blob/master/mkdeb-apparmor.sh) AppArmor;
- [without](https://github.com/netblue30/firejail/blob/master/mkdeb.sh) AppArmor.

As for online man pages, there's the official https://firejail.wordpress.com/ site (look under 'features'). Linux man pages are widely available on the internets, including https://manpages.debian.org/, to name one that should fit your OS.

Hope this helps, regards.

**Comment by curiosity-seeker** [comment]
Adding to @glitsj16 's post, this is how I do it:

```
cd ~
rm -rf ~/firejail
git clone https://github.com/netblue30/firejail.git
cd firejail
./configure --prefix=/usr --enable-apparmor
make
sudo make install

sudo firecfg

sudo chown -c root:firejail /usr/bin/firejail
sudo chmod -c 4750 /usr/bin/firejail
```
The last 2 lines match the suggestions given [here](https://firejail.wordpress.com/documentation-2/basic-usage/#suid) (assuming that the firejail group already exists). I'm doing this although `sudo firecfg` already adds the current user to the Firejail user access databse.

**Comment by chiraag-nataraj** [comment]
Going to close since it looks like the OP's question was answered.
