### ISSUE TITLE
Does "q4wine" need to be sandboxed by Firejail if "WineHQ" is already sandboxed by Firejail

### ISSUE THREAD

**Issue by Nokia808** [netblue30/firejail#2642]
As the title asking.
q4wine is a frontend for WineHQ:
https://q4wine.brezblock.org.ua/

**Comment by veloute** [comment]
after running q4wine, do "firejail --list".
if there's nothing related to wine there, we may have to create a profile for q4wine.

**Comment by Vincent43** [comment]
```
~/.config/firejail/q4wine.profile

noblacklist ${HOME}/.config/q4wine
whitelist ${HOME}/.config/q4wine
include /etc/firejail/wine.profile
```

**Comment by chiraag-nataraj** [comment]
Looks like this was answered! I'll close this for now, but @Nokia808, please feel free to re-open if this didn't work.
