### ISSUE TITLE
Run "WineHQ" profile before launch WineHQ for 1st time or run this profile after 1st launch of WineHQ

### ISSUE THREAD

**Issue by Nokia808** [netblue30/firejail#2643]
Let me more clear. Just by installation of WineHQ & restart PC but still not launching WineHQ, the ~/.wine folder still not created yet. So does this will interfere with Wine profile integration with Wine or not ?

Is it safe to run activate WineHQ profile while ~/.wine folder still not created by 1st launch of WineHQ ?

**Comment by rusty-snake** [comment]
@Nokia808 there shouldn't be a problem to do that.
(https://github.com/netblue30/firejail/blob/master/etc/wine.profile is a blacklisting profile.)

**Comment by chiraag-nataraj** [comment]
Looks like this was answered, so I'll go ahead an close this. @Nokia808, please feel free to re-open if you need further clarification or if something's not working.
