### ISSUE TITLE
Error when running `aa-enforce firejail-default`

### ISSUE THREAD

**Issue by julien-tmp** [netblue30/firejail#2653]
```
- firejail version: 0.9.58.2
 - Linux distribution: Linux Mint LMDE
 - Problem did no exist in December last year
 - firejail withthe `--noprofile` argument: Does not give a warning about networking
```
I have the error below when running `aa-enforce firejail-default` :
```
ERROR: Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
```
Why does this happen and what to do about it?

**Comment by Vincent43** [comment]
What `sudo aa-status` shows?

You may try `sudo apparmor_parser -r /etc/apparmor.d/firejail-default` which is the recommended command for enabling apparmor profile referred in our [manpage](https://github.com/netblue30/firejail/blob/master/src/man/firejail.txt#L2439).

**Comment by julien-tmp** [comment]
Thank you for checking that @Vincent43 
Here is the output:
```
$ sudo aa-status            
apparmor module is loaded.
apparmor filesystem is not mounted.
```
and 
```
$ sudo apparmor_parser -r /etc/apparmor.d/firejail-default
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.

```
It's possible that I have to do that:
https://ubuntuforums.org/showthread.php?t=2164641&p=12741691#post12741691

I don't want to play with grub too much in the following days. I will go back to this after making a backup.

PS: My partitions look like this if it helps
```
sdc       8:32   0   500G  0 disk  
├─sdc1    8:33   0     2M  0 part  
├─sdc2    8:34   0   512M  0 part  
└─sdc3    8:35   0 599G  0 part  
  └─lvm 254:0    0 499G  0 crypt 
    ├─vg0-root
    │   254:1    0    30G  0 lvm   /
    ├─vg0-var
    │   254:2    0    40G  0 lvm   /tmp
    ├─vg0-swap
    │   254:3    0    20G  0 lvm   [SWAP]
    └─vg0-home
        254:4    0 386.4G  0 lvm   /home
```

**Comment by chiraag-nataraj** [comment]
@julien-tmp Did you ever revisit this?

**Comment by julien-tmp** [comment]
Not yet unfortunately. Pretty busy lately. I will try to do it in this month. Do you face the same issue @chiraag-nataraj  ?

**Comment by chiraag-nataraj** [comment]
Nope, the apparmor integration is working fine on my end.

**Comment by Vincent43** [comment]
For some reason AppArmor isn't working on your system, this isn't firejail related.

**Comment by chiraag-nataraj** [comment]
Yeah, looking over your earlier errors, this definitely looks like a non-firejail issue. @julien-tmp, the error [looks like](https://www.linuxquestions.org/questions/linux-security-4/why-is-apparmor-throwing-that-error-4175434956/) something that gets thrown when your kernel doesn't support apparmor. You'll have to look into possibly upgrading your kernel and/or figuring out why apparmor support seems to be disabled in your kernel.

Either way, this isn't a firejail issue, so I'll go ahead and close it, but feel free to keep replying and I'll do the best I can to help you figure it out :)
