### ISSUE TITLE
gajim doesn't let open images

### ISSUE THREAD

**Issue by alexandre1985** [netblue30/firejail#2655]
My firejailed gajim has the gajim's plugins: Image and [URL Image Preview](https://dev.gajim.org/gajim/gajim-plugins/wikis/UrlImagePreviewPlugin). I believe it is a problem with the URL Image Preview.

With it, gajim shows a sent image preview in my chat box. With a right click I can download the image, open the image, or get a link url.

When I click to download the image (with gajim inside firejail) everything works OK, the same with the get link url (it gives a link like this aesgcm://server.domain/upload/xxxxxx/hAsHfiLe.jpg#abcd9876).

But when I click to open the image (it chooses my pc image viewer) it does nothing, doesn't work.

Even with this `gajim.local` file in place
```
noblacklist ${PATH}/deepin-image-viewer
noblacklist ${PATH}/firefox

noblacklist ${PATH}/openssl

noblacklist ${PATH}/exo-open
noblacklist ${PATH}/xdg-open

noblacklist /usr/share/applications/deepin-image-viewer.desktop
noblacklist ${HOME}/.local/share/gajim/downloads/*
```

I have tried to put everything inside the `gajim.local` but still it doesn't let me open the image.
Need help.

With a non-firejailed gajim it works. And when I click to open a image I get this gajim output
```
main.go:63: openFile: "/home/john/.local/share/gajim/downloads/rZs4IFurRAStnaCrSbbykg_a1a3020cd28387ebbaaa2ec595a2f8a9bf528bec.jpg"
main.go:93: desktop file: /usr/share/applications/deepin-image-viewer.desktop
```

**Comment by rusty-snake** [comment]
@alexandre1985 try `echo "private-bin deepin-image-viewer" >> ~/.config/firejail/gajim.local`

**Comment by alexandre1985** [comment]
@rusty-snake It didn't work.
When I click to open the image, firejailed Gajim does download the image to `/home/john/.local/share/gajim/downloads/` but the image it isn't open in `deepin-image-viewer`.

Don't know if this is related but the image link has the protocol aesgcm://

**Comment by rusty-snake** [comment]
@alexandre1985
* exit gajim
* run `firejail --build gajim | grep "private-bin" >> $HOME/.config/firejail/gajim.local` and open an image in deepin-image-viewer from gajim.
* start gajim and try again

**Comment by alexandre1985** [comment]
@rusty-snake I have tried, but it didn't work.
My `gajim.local`, right now, is:
```
private-bin bash,python3.7,
```

**Comment by rusty-snake** [comment]
1. This should already in `gajim.profile`.
2. Which distro?
3. Which firejail version?
4. Does `firejail --noprofile gajim` work?
5. Try to find out the problem only with gajim.profile:
```
mv .config/firejail/gajim.local .config/firejail/gajim.local.disabled
cp /etc/firejail/gajim.profile .
vim gajim.profile # if you wish ;)
# comment private-bin, private-etc, disable-programs, disable-common,
# disable-interpreters, whitelist, whitelist-common
firejail --profile=gajim.profile gajim
```
and uncomment then line by line and test after each time

**Comment by alexandre1985** [comment]
1. Didn't understood
2. Manjaro Linux Deepin
3. 0.9.58.2
4. Yes, the opening of the image does work with `firejail --noprofile`
5. Will do that

**Comment by alexandre1985** [comment]
In `gajim.profile` I commented out:
```
#private-bin python,python3,sh,gpg,gpg2,gajim,bash,zsh,paplay,gajim-history-manager
```
and it solved my issue.

What now?

**Comment by rusty-snake** [comment]
1. bash and python3 are already allowed in gajim.profile

**Comment by alexandre1985** [comment]
of the line:
```
private-bin python,python3,sh,gpg,gpg2,gajim,bash,zsh,paplay,gajim-history-manager
```
I have tried removing each word one by one and it all gave the open image preview error.

When I comment the line all together I can open the image preview (that are in gajim history dialog).

**Comment by rusty-snake** [comment]
@alexandre1985 the other way round, any program is missing, but is confused me that `echo "private-bin deepin-image-viewer" >> ~/.config/firejail/gajim.local` and `firejail --build gajim | grep "private-bin" >> $HOME/.config/firejail/gajim.local` (open an image in deepin-ima… from gajim) didn't work.

**Comment by alexandre1985** [comment]
@rusty-snake it didn't. I have tried it again now... Doesn't open.
Here is my `$HOME/.config/firejail/gajim.local`
```
private-bin deepin-image-viewer
private-bin bash,python3.7,
```

**Comment by rusty-snake** [comment]
@alexandre1985 I don't have an idea anymore, but can you try if it works with another image viewer (e.g. eog org feh).

**Comment by alexandre1985** [comment]
Gajim in able to open the image, checks for the default application for that use case.
Don't know if this helps.
I have disabled the "default application" setting and choose a manual application. There was only a field for the default file manager and I choose mine. Know I'm able to open the image in the defaul file manager, then I open the image on that.
So this is a way around.

**Comment by rusty-snake** [comment]
Alternative you can change the leftclick behavior in the plugin settings.

**Comment by alexandre1985** [comment]
@rusty-snake changing the left click of the plugin didn't help at all

**Comment by rusty-snake** [comment]
I meant more like making one of those options:
1. open in the webbrowser (gajim.profile must be " downgraded)
2. copy URL -> manual past in webbrowser
3. save as -> open manually

**Comment by chiraag-nataraj** [comment]
Going to close this as there seems to be a workaround that works. @alexandre1985, please feel to re-open if you have more questions.

**Comment by shodanx2** [comment]
I seem to have a similar issues.

https links work but aesgcm:// links don't work

![image](https://user-images.githubusercontent.com/10621885/159139355-bc92b903-715e-4939-ba86-6daba87bf5a1.png)

I'm not sure why sometimes gajim exchanges https links and sometimes it is naesgcm:// links
