### ISSUE TITLE
Dropbox will not start with default profile Kubuntu Ubunutu 18.10 firejail version 0.9.54

### ISSUE THREAD

**Issue by Mothsdroyp** [netblue30/firejail#2657]
Dropbox will not start after sudo firecfg on Kubuntu Ubunut 18.10 firejail version 0.9.54.

It seems that the error is due to in the supplied profile below the "include /etc/firejail/disable-interpreters.inc".  Dropbox needs python to run as far as I can tell.

I edited the profile supplied with the firejail version simply by commenting out the include interpreters line and placing the edited profile in ~/.config/firejail/dropbox.profile

I am unsure if this is the optimal solution, but it seems to work for the time being!

```
# Firejail profile for dropbox
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/dropbox.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.config/autostart
noblacklist ${HOME}/.dropbox
noblacklist ${HOME}/.dropbox-dist

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
# COMMENTED OUT THE DISABLE-INTERPRETERS.INC TO GET DROPBOX TO WORK
# include /etc/firejail/disable-interpreters.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

mkdir ${HOME}/.dropbox
mkdir ${HOME}/.dropbox-dist
mkdir ${HOME}/Dropbox
mkfile ${HOME}/.config/autostart/dropbox.desktop
whitelist ${HOME}/.config/autostart/dropbox.desktop
whitelist ${HOME}/.dropbox
whitelist ${HOME}/.dropbox-dist
whitelist ${HOME}/Dropbox
include /etc/firejail/whitelist-common.inc

caps.drop all
netfilter
no3d
nodvd
nogroups
nonewprivs
noroot
nosound
notv
novideo
protocol unix,inet,inet6
seccomp
shell none

private-dev
private-tmp

noexec /tmp
```

**Comment by Mothsdroyp** [comment]
Sorry about the unusual text size in part of the bug report -- unsure why that happened

**Comment by glitsj16** [comment]
> I edited the profile supplied with the firejail version simply by commenting out the include interpreters line and placing the edited profile in ~/.config/firejail/dropbox.profile

When you name the file ~/.config/firejail/dropbox`.local` instead, firejail is smart enough to automatically pick up any options in there and will use them to override whatever is in the system-wide /etc/firejail/dropbox`.profile`. By naming it with a .profile suffix under your ${HOME} dir, you're actually replacing the one in /etc/firejail and you will have to track potential changes to the profile yourself. To avoid all that, you can tackle the python problem in a ~/.config/firejail/dropbox.local file while leaving the rest intact:

```
# Allow python (disabled by disable-interpreters.inc)
noblacklist ${PATH}/python2*
noblacklist ${PATH}/python3*
noblacklist /usr/lib/python2*
noblacklist /usr/lib/python3*
noblacklist /usr/local/lib/python2*
noblacklist /usr/local/lib/python3*
```
That will override what's in /etc/firejail/disable-interpreters.inc more selectively, no need to comment it out completely. It still keeps unneeded interpreters inaccessable, which is considered safer/more secure/less insecure depending on who you ask :smile:
 
> Sorry about the unusual text size in part of the bug report -- unsure why that happened

Use the toolbar options just above the input box to avoid copy-pasted code to mess with the styling.

**Comment by chiraag-nataraj** [comment]
Is this still an issue @Mothsdroyp?

**Comment by chiraag-nataraj** [comment]
Should we modify the shipped dropbox profile to not blacklist python2 or whatever?

**Comment by Mothsdroyp** [comment]
The following lines are also needed in addition to the above noblacklist {HOME}/.dropbox* and noblacklist {HOME}/Dropbox* is also needed.  

# With these additional lines firejail provides excellent security by preventing inadvertent sharing / uploading of files

**Comment by rusty-snake** [comment]
`noblacklist ${HOME}/Dropbox*` is not needed because there is no `blacklist ${HOME}/Dropbox*`.
