### ISSUE TITLE
Fedora 30 Compilation Errors

### ISSUE THREAD

**Issue by SkewedZeppelin** [netblue30/firejail#2661]
Fedora 30 has changed the default compile flags for programs. One new addition is `-fcf-protection` which is marked incompatible with `-mindirect-branch`.

Example:
```
/usr/include/bits/stdio.h: In function 'getchar':
/usr/include/bits/stdio.h:48:1: error: '-mindirect-branch' and '-fcf-protection' are not compatible
   48 | {
      | ^
```

https://github.com/netblue30/firejail/blob/master/configure#L3113
will need to be changed.

**Comment by chiraag-nataraj** [comment]
So how do we do this such that it doesn't affect other distros which haven't (yet?) done this?

**Comment by rusty-snake** [comment]
Maybe something like
```bash
[ -e /etc/fedora-release ] && [ "$(cat /etc/fedora-release)" = "Fedora release 30 (Thirty)" ]
```

**Comment by Vincent43** [comment]
I think it's better to detect if `-fcf-protection` is passed in `CFLAGS`.
