### ISSUE TITLE
'sudo firejail --apparmor' = Root shell

### ISSUE THREAD

**Issue by VltraHeaven** [netblue30/firejail#2662]
Hey, I noticed that when I run 'sudo firejail --apparmor' as my admin user account I get spit into a root shell. My account is a sudoer and is in the 'firejail.users' file. Is this behaviour intended or known? 

Tested on the following systems:
-Linux Pop!OS 
-4.18.0-17-generic #18~18.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
-firejail - version 0.9.52

and

-Linux 4.19.0-kali4-amd64 #1 SMP Debian 
-4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
-firejail - firejail - version 0.9.58.2

**Comment by Vincent43** [comment]
Yes, `sudo` makes you root. If you want use firejail as unprivileged user run `firejail --apparmor` without sudo.
