### ISSUE TITLE
${HOME}/.git-credentials is not covered by default

### ISSUE THREAD

**Issue by dandelionred** [netblue30/firejail#2663]
https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
> Some of these helpers have options. The “store” helper can take a --file <path> argument, which customizes where the **plain-text** file is saved (**the default is ~/.git-credentials**)

Files under `${HOME}/.git-credentials/` have plaintext passwords.

I use 0.9.58.2

**Comment by rusty-snake** [comment]
@dandelionred done. 
63efb45 blacklist `${HOME}/.git-credentials` and `${HOME}/.config/git`.
> If not specified, credentials
           will be searched for from ~/.git-credentials and
           $XDG_CONFIG_HOME/git/credentials, and credentials will be written to
           ~/.git-credentials if it exists, or $XDG_CONFIG_HOME/git/credentials if it
           exists and the former does not.

63efb45 also allow `${HOME}/.git-credentials` and `${HOME}/.config/git` in all profile where `${HOME}/.gitconfig` is allowed.
