### ISSUE TITLE
Broken commit !!

### ISSUE THREAD

**Issue by dandelionred** [netblue30/firejail#2664]
0d42e12f11825f84d6bf6f9c667cd16272a3700c

**Comment by rusty-snake** [comment]
How this is going to be fixed somebody has to tell me. There are two options:

1. https://github.com/rusty-snake/firejail/pull/1 but this will break git blame for these profiles (including disable-programs.inc)

2. someone tells me how to revert this cleanly.

**Comment by SkewedZeppelin** [comment]
I reverted it, there is nothing you can do about git blame unless someone like @netblue30 force pushed it, which is never a good idea, especially with a common/popular repo like this.

**Comment by rusty-snake** [comment]
@SkewedZeppelin Thanks.

Yes, I should be a bit more careful in the future with `git push` (and `git commit` and `git merge` and `git ...`) and look over it before pushing.

The curiosity about this is that it was firejail.
