### ISSUE TITLE
Error: cannot detect login user

### ISSUE THREAD

**Issue by t4777sd** [netblue30/firejail#2668]
When running firecfg under root it outputs the following errors. Any ideas how to trick it into detecting this?

**Comment by glitsj16** [comment]
@t4777sd Something seems to have gone wrong, we can't see any of the error output. Please try again.

**Comment by rusty-snake** [comment]
@t4777sd if you mean the "Error: cannot detect login user":
1. Are the symlinks in /usr/local/bin created?
2. There is no login user if you run firecfg from a root shell.

**Comment by chiraag-nataraj** [comment]
@t4777sd, can you please respond with more information? The error output seems to be completely missing.

**Comment by chiraag-nataraj** [comment]
@t4777sd, I'm going to go ahead and close this for now since we don't have enough info to proceed. Please feel free to re-open this with more info if/when you get the time.
