### ISSUE TITLE
Remove the need for QTWEBENGINE_DISABLE_SANDBOX=1 (appimage)

### ISSUE THREAD

**Issue by probonopd** [netblue30/firejail#2669]
`QTWEBENGINE_DISABLE_SANDBOX=1` may be needed to run Qt applications that use QtWebEngine under Firejail.

At least this is the case for https://appimage.github.io/Galacteek/.

Would it make sense to have Firejail set this environment variable globally? I see it already exists in the source code but is commented out.

**Comment by rusty-snake** [comment]
Currently this is only set for Viber,

Also see [here](https://github.com/netblue30/firejail/pull/2295).

**Comment by probonopd** [comment]
Is it already known under which circumstances QtWebEngine needs this option?

**Comment by Vincent43** [comment]
I would say it should be never added. Firejail sandbox should be tweaked instead.

**Comment by probonopd** [comment]
Listing here which applications needs this:

* GAMS Studio https://github.com/AppImage/appimage.github.io/pull/536
* Plex https://github.com/AppImage/appimage.github.io/pull/132
* Sielo Browser https://github.com/AppImage/appimage.github.io/pull/552

**Comment by smitsohu** [comment]
> Is it already known under which circumstances QtWebEngine needs this option?

Always (given that unprivileged user namespaces are enabled).

It's all about the chroot syscall being included in the default seccomp filter. As this is an increasingly common problem, would it justify a new option?

**Comment by probonopd** [comment]
It would be best if it would not need a special option to be invoked by the user. (If the user has to do something, then `QTWEBENGINE_DISABLE_SANDBOX=1` is fine imho.)

**Comment by Vincent43** [comment]
> It's all about the chroot syscall being included in the default seccomp filter. As this is an increasingly common problem, would it justify a new option?

Maybe tweak `seccomp` rule to allow defining firejail defaults +/- a chosen syscall,
like `seccomp +chroot`?

**Comment by rusty-snake** [comment]
I think we schould implement @Vincent43  idea

**Comment by rusty-snake** [comment]
How future proceed here?

**Comment by Vincent43** [comment]
Adding [this](https://github.com/netblue30/firejail/pull/2927/files#diff-804b7cf50c334c0afd185b5be88e0139R28) to Viber.profile and removing `env QTWEBENGINE_DISABLE_SANDBOX=1` from there should be enough to close this. You may include this in https://github.com/netblue30/firejail/pull/2927 and wait till https://github.com/netblue30/firejail/pull/2926 is merged.

**Comment by probonopd** [comment]
Well, I'd say this ticket can be closed once we don't need `env QTWEBENGINE_DISABLE_SANDBOX=1` anywhere anymore, not just for Viber.

**Comment by Vincent43** [comment]
@probonopd you mean appimage apps? They seem to use `default.profile`. The only fix I see is to remove `chroot` from default seccomp filter.

**Comment by probonopd** [comment]
Yes, I mean AppImage apps. What would the security implications be of what you are suggesting? Would the sandboxing still be effective?

**Comment by Vincent43** [comment]
We just need to allow one additional syscall (`chroot`) which many apps use for self-sandboxing. Everything else will stay intact and app will be protected by both firejail and chrome sandboxing.

**Comment by probonopd** [comment]
Thank you very much.

**Comment by smitsohu** [comment]
@Vincent43 Maybe rather than removing `chroot` from the default seccomp blacklist, we could just remove it from default.profile? (or I understood you wrong and that was what you were saying)

**Comment by Vincent43** [comment]
@smitsohu `chroot` breaks  most electron apps and will ultimately break all of them once they update to latest version. It's no longer suitable default in apps world.
