### ISSUE TITLE
How to automatically get the applications to point to firejail after installation

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2670]
I already installed Firejail on Manjaro KDE. Now I want to set up a system where when I install an application, when I run the application it will automatically open up in firejail, how do I do this?

**Comment by rusty-snake** [comment]
@Raj2032 you know about `firecfg`?

**Comment by Raj2032** [comment]
@rusty-snake Nope, please teach me?

**Comment by rusty-snake** [comment]
https://www.mankier.com/1/firecfg
https://github.com/netblue30/firejail#desktop-integration

**Comment by Raj2032** [comment]
`sudo firecfg` Does this sandbox all the applications?

**Comment by rusty-snake** [comment]
All applications in https://github.com/netblue30/firejail/blob/master/src/firecfg/firecfg.config they are installed, will be sandboxed with the associated profile in https://github.com/netblue30/firejail/tree/master/etc.

**Comment by Raj2032** [comment]
@rusty-snake I think I am ready now, but just one last little question.

> All applications in https://github.com/netblue30/firejail/blob/master/src/firecfg/firecfg.config

Where is the config file located in, which directory?

> with the associated profile in https://github.com/netblue30/firejail/tree/master/etc.

And where is the config file for this located on Linux?

**Comment by rusty-snake** [comment]
On my System: `/usr/lib64/firejail/firecfg.config` and `/etc/firejail`.

**Comment by Raj2032** [comment]
Cool thanks.

**Comment by Raj2032** [comment]
@rusty-snake I am sorry if I am being annoying but I need to understand something. So by default, if I click on chromium on KDE its going to open it up without it being sandboxed, right? By typing in `firetool chromium` it is going to open up chromium in a sandbox, correct?

Now I want by default I want to click on chromium in the taskbar and it will sandbox it without having to use firejail nor firetools. I could have used firecfg but that would make all applications sandboxed. I only want to make chromium sandboxed when I launch it in KDE, what will I type in the console or using firetools?

My next question is with chromium how would I build a custom profile to only allow a specific set if directories it can access using both firejail and firetools?

**Comment by rusty-snake** [comment]
1. firetools is only a GUI-wrapper for firejail.
2. the cmd `firejail chromium` is better
3. > I only want to make chromium sandboxed

`sudo firecfg --clean`
`sudo ln -s /usr/bin/firejail /usr/local/bin/chromium`

**Comment by rusty-snake** [comment]
> My next question is with chromium how would I build a custom profile to only allow a specific set if directories it can access using both firejail and firetools?

1. The chromium profile is a whitelisting profile. ([1](https://github.com/netblue30/firejail/blob/master/etc/chromium.profile), [2](https://github.com/netblue30/firejail/blob/master/etc/chromium-common.profile))
    => I think that this is not needed
2. Profiles for browsers are very difficult because browsers are big software.
 if you didn't write any firejail-profile before, it is maybe better to start writing own firejail-profiles with easyer applications.
3. see `man firejail-profiles` for the syntax for firejail profiles.

**Comment by Raj2032** [comment]
@rusty-snake 

> `sudo firecfg --clean`
`sudo ln -s /usr/bin/firejail /usr/local/bin/chromium`

I literally typed in these two commands, first of all this directory `/usr/local/bin/chromium` didn't seem to exist for me so I typed `/usr/bin/chromium` instead and it created the soft link. But when clicking on Chromium it doesn't sandbox it at all.

Also how can I customize a sandboxed environment for chromium?

**Comment by rusty-snake** [comment]
`sudo ln -s /usr/bin/firejail /usr/local/bin/chromium` should be right. If it doesn't exists, can you past the output from `echo $PATH`.

**Comment by chiraag-nataraj** [comment]
@Raj2032 What was the output from `echo $PATH`?

**Comment by rusty-snake** [comment]
@Raj2032 I'm going to close this for now because of inactivity. Please fell free to reopen if you still have this issue.
