### ISSUE TITLE
Error: --shell=none configured, but no program specified

### ISSUE THREAD

**Issue by flux242** [netblue30/firejail#2671]
I get this error for any app in an **appimage** which has 'shall none' in its firejail profile. As far as this option is removed apps starts normally.

**Comment by flux242** [comment]
$ firejail --version
firejail version 0.9.52

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- bind support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- git install support is disabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

**Comment by rusty-snake** [comment]
Fix: `echo "?HAS_APPIMAGE: ignore shell none" >> ~/.config/firejail/globals.local`

**Comment by flux242** [comment]
@rusty-snake that would be a workaround, thanks. And you mean /etc/firejail/globals.local not the ~/.config/firejail/globals.local one? Because otherwise it won't be included unless the /etc/firejail/globals.local exist and explicitly includes ~/.config/firejail/globals.local. Isn't it?

**Comment by flux242** [comment]
and '?HAS_APPIMAGE: ignore shell none' is reported as invalid

**Comment by rusty-snake** [comment]
@flux242 your right, these feature aren't in your FJ version. I forgot to look at it.
Then you must add it manually for every profile that you use with appimage.
I would advise against `echo "ignore shell none" > /etc/firejail/gloabls.local`.

**Comment by chiraag-nataraj** [comment]
It seems like this problem has been resolved. @flux242, I'll go ahead and close this now, but please feel free to re-open if you have more questions or if this isn't fully resolved.
