### ISSUE TITLE
Using the overlay option

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2675]
For `firejail --overlay` option, is it possible to create a shortcut on the desktop and run the application?

Additionally would the application have access to all other mounted partitions?

**Comment by rusty-snake** [comment]
@Raj2032, you can do something like:
```
cat > ~/Desktop/XY << EOF
#!/bin/bash
firejail --overlay PROGRAM
EOF
chmod +x ~/Desktop/XY
```
oder you create a .desktop file with `Exec=sh -c 'firejail --overlay PROGRAM'`

**Comment by rusty-snake** [comment]
Closing here, because it looks like there's no other questions. Feel free to reopen if there are still questions
