### ISSUE TITLE
[Feature request] Integrate hardened_malloc When Available on System

### ISSUE THREAD

**Issue by ilikenwf** [netblue30/firejail#2689]
I've tested it already with many applications and so far found it to not impact performance or break things so far. Having a flag within firejail configs to enable hardened_malloc would add another level of security, in my opinion.

While it was originally written with Android in mind, it has since been made generic and works well under Linux. I have it working already under Arch: https://aur.archlinux.org/packages/hardened-malloc-git/

**Hardened_Malloc:**

https://github.com/GrapheneOS/hardened_malloc

While it would perform better and otherwise integrate better if integrated into libc, I doubt that such an integration would be easy at this juncture in most distros.

**Comment by ilikenwf** [comment]
I do recognize that using 
```firejail --env=LD_PRELOAD='/usr/lib/libhardened_malloc.so' /path/to/binary```

Will work, but seeing as this is a security feature I wonder about the feasibility of integration somehow.

**Comment by ilikenwf** [comment]
...it does seem to break "man" for some reason.

**Comment by Vincent43** [comment]
I believe this is rather beyond of firejail scope which is to create sandbox, not to fiddle with apps code behavior. Moreover there will be very few users who will have hardened_malloc installed on their systems thus integraion value is quite small. Nevertheless using hardened_malloc is nice idea and I think LD_PRELOAD trick you posted is sufficient.

**Comment by openffchrome** [comment]
`irejail --env=LD_PRELOAD='/usr/lib/libhardened_malloc.so' --x11=xephyr --profile=/home/moi/.config/firejail/firefox.profile openbox --startup firefox`

is this the correct way to use hardened malloc for firefox with xephyr ruining openbox ?

**Comment by ilikenwf** [comment]
Try it and check lsof to see if the firefox process is using the libhardened_malloc.so file...

@netblue30 to be more generic in my request, perhaps an option to allow LD_PRELOAD in the .profile files, if it's owned by root or lives in the /etc/firejail path, but not in the custom user ~/.config/firejail path? That would at least ensure that preloading is only allowed when root wants it to be.

**Comment by openffchrome** [comment]
ho ok, it's working fine, thanks!

**Comment by Vincent43** [comment]
> to be more generic in my request, perhaps an option to allow LD_PRELOAD in the .profile files, if it's owned by root or lives in the /etc/firejail path, but not in the custom user ~/.config/firejail path? That would at least ensure that preloading is only allowed when root wants it to be.

We don't differentiate between root owned and user owned profiles because it wouldn't make sense when user can pass any profile option manually `firejail --foo --profile=xxx`. We could make a on/off switch in `firejail.config` but isn't passing LD_PRELOAD as env variable easier and more user friendly?

**Comment by glitsj16** [comment]
Maybe add a new `disable-hardened_malloc.inc` (or any other suitable name) containing `blacklist /usr/lib/libhardened_malloc*`, so this can be integrated nicely like all other stuff via:
```
...
# Allow hardened_malloc
env LD_PRELOAD=/usr/lib/libhardened_malloc.so
noblacklist /usr/lib/libhardened_malloc*
# whitelist /usr/lib/libhardened_malloc* - for a whitelist profile
...
include disable-hardened_malloc.inc
...
# private-lib ...,libhardened_malloc*,... - for profiles using private-lib
```

**Comment by Vincent43** [comment]
But hardened-malloc is supposed to increase security, what's the point of blackisting it?

**Comment by glitsj16** [comment]
@Vincent43 Using `env LD_PRELOAD=/usr/lib/libhardened_malloc.so` on a system where hardened_malloc isn't available would break firejail profiles. That's why I suggested the above format, so users can enable it not only via the CLI but also inside profile files.

**Comment by Vincent43** [comment]
@ilikenwf FYI from my brief testing it seems that `LD_PRELOAD` trick is incompatible with `noroot` option.

**Comment by glitsj16** [comment]
@Vincent43 I'm using the LD_PRELOAD trick as described in my earlier comment for several months now on a selection of profiles which happen to have the `noroot` option. Haven't experienced anything out of the ordinary yet and I'm regularly double-checking via lsof if things work as expected. In that context I'm eager to learn what you mean with `incompatible` exactly. Can you elaborate on your findings if you find the time?

**Comment by Vincent43** [comment]
@glitsj16 I thought it doesn't work with `noroot` because `lsof` didn't show hardened-malloc usage but it seems that running `lsof` as root shows it. Sorry for the confusion.

**Comment by glitsj16** [comment]
@Vincent43 That caught me too early on, thanks for clearing things up.

For prosperity's sake, here's a command that shows a sorted list of processes using hardened-malloc:

`$ sudo lsof -w +c 0 /usr/lib/libhardened_malloc.so | awk '{print $1}' | sort`

**Comment by Vincent43** [comment]
Closing as there is nothing to do here for firejail. Keep in mind that upstream reccomends to enable hardened_malloc system-wide by [adding it to /etc/ld.so.preload](https://github.com/GrapheneOS/hardened_malloc#traditional-linux-based-operating-systems). Using `env LD_PRELOAD` is meant only for testing.

**Comment by sempervictus** [comment]
@Vincent43: i think that what @glitsj16 proposed is quite rational, does not break backwards compatibility, and does permit _jailed_ programs to run with the hardened allocator when invoked via the symlinks in /usr/local/bin as opposed to their actual binpaths (this is how Arch handles it anyway).
Jails are intended to provide isolation from the rest of the system - in Linux these concepts are constructed from namespaces, but there's no such thing as a memory allocator namespace unless you overlay a filesystem with a different allocator compiled into the libc (but ABI compatible as a thin shim). Allowing users to change a single config line, or possible a couple if they need to re-blacklist it for some apps, once, makes "security easy" and therefore more likely to be implemented.
The /etc/ld.so.preload method is a breaking change - @thestinger can explain what works and what doesnt right now, but there are userspace libraries which do have performance or compatibility issues with it. There are very few, but they exist. i use the allocator quite a bit, its great for phones and for Linux servers (both with linux-hardened or grsec kernels), but it can break with qt apps and the like... so for now it needs to be opt-in, and the approach proposed by @glitsj16 permits doing so easily and in line with current documentation for using firejail.
Any chance of reopening this and taking up the enhancement?

**Comment by Vincent43** [comment]
@sempervictus you are free to add `env LD_PRELOAD=/usr/lib/libhardened_malloc.so` to `<app>. local` or `globals.local` or wherever you like. You don't need fiejail assistance for that.

**Comment by Vincent43** [comment]
The fact that upstream doesn't recommend using `LD_PRELOAD` env is strong argument against officially including that somewhere in firejail as pretending to support things which are not supported by upstream would be dishonest.

**Comment by ilikenwf** [comment]
I also have noticed occasional instability in some applications, so
including it somewhere in firejail is a bad idea.

**Comment by ilikenwf** [comment]
I was saying what I said because many casual users also use firejail, and so I just think defaulting to using hardened_malloc may be a mistake since they aren't capable of tracing said bugs.

Likewise, some applications also already have their own malloc implementations, which can sometimes appear to have issues with corruption as you mentioned, but I find it hard to determine whether or not this is the case when dealing with something like Mozilla...
