### ISSUE TITLE
Atom ain't sandboxed 

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#2692]
Specs- Manjaro(KDE): kernel-4.19.36-1, Firejail-0.9.58.2-1, Atom-1.36.0-2

When I try to run atom from context menu,desktop or menubar, atom is not sanboxed though firejail has already made symlink. Firejail atom does sandbox atom though. How can I fix it?

**Comment by SkewedZeppelin** [comment]
atom.desktop has a hardcoded exec line as `Exec=env /usr/bin/atom`
did you run `firecfg --fix`? if so, maybe firecfg can't handle `Exec` with extra bits like that

**Comment by Neo00001** [comment]
> did you run `firecfg --fix`? if so, maybe firecfg can't handle `Exec` with extra bits like that
yup... firecfg --fix didn't fix it... so there is no way to resolve it,at this moment.

**Comment by SkewedZeppelin** [comment]
You can manually copy `/usr/share/applications/atom.desktop` to `~/.local/share/applcations`
and edit the `Exec` line to be `Exec=atom`

**Comment by Neo00001** [comment]
didn't work...

**Comment by chiraag-nataraj** [comment]
@Neo00001 Can you do a `which atom`?

**Comment by matu3ba** [comment]
Same issue with (surf)[https://surf.suckless.org/] for default path.
A hint to fix the binary location (and the options where to place it exactly) would be useful.

**Comment by chiraag-nataraj** [comment]
How are you installing `surf` though? At least in the default Debian package, it doesn't come with a `.desktop` file...

**Comment by chiraag-nataraj** [comment]
Also, @Neo00001, you should file a bug at https://github.com/atom/atom/issues to tell them to stop using the absolute path in the desktop file.

**Comment by chiraag-nataraj** [comment]
@Neo00001 What is the output of `which atom`?
@matu3ba How are you installing `surf`? As I remarked in my previous comment, the version of `surf` I can install doesn't come with a `.desktop` file, which is what we're talking about here. Does your version of `surf` come with a `.desktop` file (menu entry)?

**Comment by matu3ba** [comment]
@chiraag-nataraj Yes, for a packaged surf that is the case.

**Comment by chiraag-nataraj** [comment]
@matu3ba, which distribution are you running?

**Comment by Neo00001** [comment]
> @Neo00001 What is the output of `which atom`?

Sorry,man. But I've uninstalled atom long ago & don't have any intention to re-install it again.

**Comment by chiraag-nataraj** [comment]
@Neo00001 :man_shrugging: Okay, I guess I'll close this for now. If you ever start using it again (or if someone else is running into this), please feel free to re-open.

@matu3ba, let's move your problem to a new issue.
