### ISSUE TITLE
Signal-desktop cannot run in chroot as user (due to some chroot magic)

### ISSUE THREAD

**Issue by VPNReyMan** [netblue30/firejail#2693]
I created a chroot according to here: https://firejail.wordpress.com/documentation-2/basic-usage/

I then installed signal-desktop. It will run as **root**, but not as **user**. In both cases it will show the application window. However, with the user it will just be blank whereas under root it will display everything correctly.

The application is designed to be run as a user and not root, so it is better if it runs as a user. It appears the only difference between the two is that under user the following is outputted:

**     Warning: dropping all Linux capabilities     **

Signal is based on node webkit or electron or something as it appears to be a chromium browser that runs a webpage. I know that chromium has it's own sandbox. Perhaps it is this sandbox in chromium that causes the issue? However, I am running _without a _profile__ so theoretically it should be working in both cases, right?

For example of commands not working and working:

**NOT WORKING**
firejail --noprofile --debug --chroot=./debian-stretch-amd64 /opt/Signal/signal-desktop

**WORKING**
sudo firejail --noprofile --debug --chroot=./debian-stretch-amd64 /opt/Signal/signal-desktop

**Comment by VPNReyMan** [comment]
It looks like the app is looking in /proc/cpuinfo. I notice that with sudo firejail that /proc/* files are readable. Without running firejail with sudo, then /proc/ is an empty directory in the chroot directory.

Is there any way to make this available?

**Comment by VPNReyMan** [comment]
I tried the --bind command to bind proc, but it says that requires root. Looking here: https://linux.die.net/man/8/linux-user-chroot

That has a --mount-proc and is supposedly meant to be called without root. Is there a way in linux to mount /proc without root inside a chroot?

**Comment by VPNReyMan** [comment]
I mounted /proc to the chroot/proc directory so that a non-root user would have access to those files. Signal still did not run, but it runs under root, so it is something else the firejail sandbox is preventing even though it is running with no profile

**Comment by SkewedZeppelin** [comment]
Why do you want a chroot? There is also an existing signal-desktop profile

just `firejail /opt/Signal/signal-desktop`

**Comment by VPNReyMan** [comment]
chroot is necessary because it does not run on non-debian distributions thus it needs a debian chroot

**Comment by rusty-snake** [comment]
@VPNReyMan wicht distro are you using?

There is an [AUR packages](https://aur.archlinux.org/packages/signal-desktop-bin/) and you can build it by your self (https://github.com/signalapp/Signal-Desktop).

You can also use flatpak `flatpak install flathub org.signal.Signal` or snap (https://snapcraft.io/signal-desktop).

**Comment by chiraag-nataraj** [comment]
Pretty sure they only provide a Debian installer...building from source should totally work on non-Debian distros. You certainly shouldn't need a chroot to install it!

**Comment by chiraag-nataraj** [comment]
@VPNReyMan Did you try either of the options we gave above?

**Comment by chiraag-nataraj** [comment]
@VPNReyMan I'm going to close this for now due to inactivity. If you have a chance to try our suggestions and report back, please feel free to re-open this.
