### ISSUE TITLE
Can't get tor-browser to run with Firejail

### ISSUE THREAD

**Issue by cokeflash** [netblue30/firejail#2706]
Hi!
I can't get tor-browser to run with Firejail.

I edited "torbrowser-launcher.profile".

```
# Persistent local customizations
#include /etc/firejail/torbrowser-launcher.local
# Persistent global definitions
#include /etc/firejail/globals.local

noblacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser	(EXEC file)
noblacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/.config
#noblacklist ${HOME}/.local/share/torbrowser

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

whitelist /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser
whitelist /mnt/tor-browser-tmpfs/tor_browser/Browser/.config
#whitelist ${HOME}/.local/share/torbrowser
include /etc/firejail/whitelist-common.inc

caps.drop all
netfilter
nodvd
nogroups
nonewprivs
noroot
notv
novideo
protocol unix,inet,inet6
seccomp
shell none
tracelog

disable-mnt
private-bin bash,cp,dirname,env,expr,file,getconf,gpg,grep,id,ln,mkdir,python*,readlink,rm,sed,sh,tail,test,tor-browser-en,torbrowser-launcher
private-dev
private-etc fonts
private-tmp

noexec /tmp
```

then edited: `disable-programs.inc`

```
# "tor-browser-tmpfs"
blacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/.cache
blacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/.config
#blacklist ${HOME}/.local/share/torbrowser
```

I typed in terminal...

``$ firejail torbrowser-launcher``

A error appears:
```
Reading profile /etc/firejail/torbrowser-launcher.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 35190, child pid 35191
Private /etc installed in 24.88 ms
TESTING warning: noblacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser not matched by a proper blacklist command in disable*.inc
Blacklist violations are logged to syslog
Child process initialized in 198.33 ms
Error: no suitable torbrowser-launcher executable found

Parent is shutting down, bye...
```

Firejail don't found the EXEC file of tor-browser.
When I typed in terminal `/mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser`... tor-browser starts.

How can I fix that?

Please help, thanks!

**Comment by rusty-snake** [comment]
1. Can you please use codeblock in the future for profiles (its easyer to read).
2. You need to remove `noexec /tmp` and `private-tmp`

**Comment by cokeflash** [comment]
ok, thanks, I'll try it out.

**Comment by cokeflash** [comment]
I renamed my tor-browser-profile to: "start-tor-browser.profile"

When I start "firejail /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser"

I edited: "disable-programs.inc"

# Persistent customizations should go in a .local file.
include /etc/firejail/disable-programs.local

# "t0r_bR0Wser"
blacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/.cache
blacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/.config
#blacklist ${HOME}/.local/share/torbrowser


I got these errors:

Reading profile /etc/firejail/start-tor-browser.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 23374, child pid 23375
Private /etc installed in 27.31 ms
TESTING warning: noblacklist /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser not matched by a proper blacklist command in disable*.inc
Blacklist violations are logged to syslog
Child process initialized in 223.39 ms
Error: no suitable /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser executable found

Parent is shutting down, bye...

What I have do do to fix that? How can I add the exec file "start-tor-browser" so firejail can find it?

Please help, thanks!

**Comment by rusty-snake** [comment]
@cokeflash use the following profile (save as e.g. $HOME/.config/firejail/torbrowser.profile:
```
# Persistent local customizations
include torbrowser.local
# Persistent global definitions
include globals.local

ignore noexec /tmp

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-passwdmgr.inc
include disable-programs.inc
include disable-xdg.inc

include /etc/firejail/whitelist-var-common.inc

caps.drop all
netfilter
nodvd
nogroups
nonewprivs
noroot
notv
novideo
protocol unix,inet,inet6
seccomp
shell none

disable-mnt
private-bin bash,cp,dirname,env,expr,file,getconf,gpg,grep,id,ln,mkdir,python*,readlink,rm,sed,sh,tail,test,tor-browser-en,torbrowser-launcher
private-dev
private-etc fonts
```

and run it with `firejail --profile=torbrowser  /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser`

also which firejail version are you using?

**Comment by rusty-snake** [comment]
Alternative you use my "[HOWTO: Firejailed Tor Browser](https://github.com/rusty-snake/firejailed-tor-browser)". But this is still not fully finish.

**Comment by cokeflash** [comment]
Ok, thanks! I'll try it out.

**Comment by cokeflash** [comment]
# firejail --profile=torbrowser /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser
Error: cannot access profile file

Can I save the torbrowser.profile to /etc/firejail? ...(where firejail stores other profiles...)

**Comment by cokeflash** [comment]
Version:  0.9.52-2

**Comment by cokeflash** [comment]
Copied the torbrowser.profile to /etc/firejail... same error, cannot access profile file.

**Comment by rusty-snake** [comment]
@cokeflash because of your (old) firejail version. I update the profile above again. You can copy it to `${HOME}/.config/firejail/tor-browser.profile` and try executing `firejail --profile=$HOME/.config/firejail/torbrowser.profile /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser`

**Comment by cokeflash** [comment]
Thanks, I'll try it out tomorrow.

**Comment by rusty-snake** [comment]
The file will read as root, so you can set what you want ;)

The issue above was that your firejail version needs absolut paths for profiles.

**Comment by cokeflash** [comment]
I run this command:  # firejail --profile=/etc/firejail/torbrowser.profile /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser

...but FireJail is shutting down :-(

Reading profile /etc/firejail/torbrowser.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 6407, child pid 6408
Child process initialized in 204.06 ms

Parent is shutting down, bye...

Some idea?
I use AppArmor,too in my OS.

**Comment by cokeflash** [comment]
AppArmor is blocking torbrowser with FireJail.

When I run /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser alone, then it works without FireJail.

**Comment by cokeflash** [comment]
[url=https://postimg.cc/5HRmJ7VS][img]https://i.postimg.cc/5HRmJ7VS/App-Armor-denied.png[/img][/url]

**Comment by rusty-snake** [comment]
@cokeflash OK, then remove the `apparmor` line in the profile and try again.

**Comment by cokeflash** [comment]
AppArmor torbrowser denied-message is gone but torbrowser with firejail don't start.

See:
firejail firejail --profile=/etc/firejail/torbrowser.profile /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser
Reading profile /etc/firejail/torbrowser.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 31505, child pid 31506
Child process initialized in 239.04 ms

Parent is shutting down, bye...

**Comment by cokeflash** [comment]
Could it be that AppArmor is blocking Firejail to run TorBrowser? I also have an AppArmor profile for FireJail called 'firejail-default' and for the TorBrowser 'home. tor-browser. firefox' ... 

Do I have to change anything?

**Comment by rusty-snake** [comment]
@cokeflash ok then comment every line in tor-browser.profile and uncomment line for line and try after any uncomment.

Does one of the following work?
`firejail --ignore=private-bin --profile=/etc/firejail/torbrowser.profile /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser`
`firejail --noprofile /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser`

Have you edited /etc/firejail.config?

**Comment by cokeflash** [comment]
No, i don't edited 'firejail.config'.

Must I edit something? Or add something?

My firejail.config:

# This is Firejail system-wide configuration file.  The file contains
# keyword-argument pairs, one per line. Most features are enabled by default.
# Use 'yes' or 'no' as configuration values.


# Number of ARP probes sent when assigning an IP address for --net option,
# default 2. This is a partial implementation of RFC 5227. A 0.5 seconds
# timeout is implemented for each probe. Increase this number to 4 if your
# local layer 2 network uses RSTP (IEEE 802.1w). Permitted values are
# between 1 and 30.
# arp-probes 2

# Enable or disable bind support, default enabled.
# bind yes

# Enable or disable chroot support, default enabled.
# chroot yes

# Use chroot for desktop programs, default enabled. The sandbox will have full
# access to system's /dev directory in order to allow video acceleration,
# and it will harden the rest of the chroot tree.
# chroot-desktop yes

# Disable /mnt, /media, /run/mount and /run/media access. By default access
# to these directories is enabled.
# disable-mnt no

# Enable or disable file transfer support, default enabled.
# file-transfer yes

# Enable Firejail green prompt in terminal, default disabled
# firejail-prompt no

# Follow symlink as user. While using --whitelist feature,
# symlinks pointing outside home directory are followed only
# if both the link and the real file are owned by the user.
# Enabled by default
# follow-symlink-as-user yes

# Force use of nonewprivs.  This mitigates the possibility of
# a user abusing firejail's features to trick a privileged (suid
# or file capabilities) process into loading code or configuration
# that is partially under their control.  Default disabled.
# force-nonewprivs no

# Allow sandbox joining as a regular user, default enabled.
# root user can always join sandboxes.
# join yes

# Enable or disable networking features, default enabled.
# network yes

# Enable or disable overlayfs features, default enabled.
# overlayfs yes

# Remove /usr/local directories from private-bin list, default disabled.
# private-bin-no-local no

# Enable or disable private-home feature, default enabled
# private-home yes

# Enable or disable private-lib feature, default enabled
# private-lib yes

# Enable --quiet as default every time the sandbox is started. Default disabled.
# quiet-by-default no

# Enable or disable restricted network support, default disabled. If enabled,
# networking features should also be enabled (network yes).
# Restricted networking grants access to --interface, --net=ethXXX and
# --netfilter only to root user. Regular users are only allowed --net=none.
# restricted-network no

# Change default netfilter configuration. When using --netfilter option without
# a file argument, the default filter is hardcoded (see man 1 firejail). This
# configuration entry allows the user to change the default by specifying
# a file containing the filter configuration. The filter file format is the
# format of  iptables-save  and iptable-restore commands. Example:
# netfilter-default /etc/iptables.iptables.rules

# Enable or disable seccomp support, default enabled.
# seccomp yes

# Enable or disable user namespace support, default enabled.
# userns yes

# Enable or disable whitelisting support, default enabled.
# whitelist yes

# Enable or disable X11 sandboxing support, default enabled.
# x11 yes

# Screen size for --x11=xephyr, default 800x600. Run /usr/bin/xrandr for
# a full list of resolutions available on your specific setup.
# xephyr-screen 640x480
# xephyr-screen 800x600
# xephyr-screen 1024x768
# xephyr-screen 1280x1024

# Firejail window title in Xephyr, default enabled.
# xephyr-window-title yes

# Xephyr command extra parameters. None by default; these are examples.
# xephyr-extra-params -keybd ephyr,,,xkbmodel=evdev
# xephyr-extra-params -grayscale

# Xpra server command extra parameters. None by default; this is an example.
# xpra-extra-params --dpi 96

# Enable this option if you have a version of Xpra that supports --attach switch
# for start command, default disabled.
# xpra-attach no

# Screen size for --x11=xvfb, default 800x600x24.  The third dimension is
# color depth; use 24 unless you know exactly what you're doing.
# xvfb-screen 640x480x24
# xvfb-screen 800x600x24
# xvfb-screen 1024x768x24
# xvfb-screen 1280x1024x24

# Xvfb command extra parameters.  None by default; this is an example.
# xvfb-extra-params -pixdepths 8 24 32

**Comment by rusty-snake** [comment]
Nope.

**Comment by cokeflash** [comment]
I'll try it out at weekend.

**Comment by cokeflash** [comment]
Not working:

firejail --ignore=private-bin --profile=/etc/firejail/torbrowser.profile /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser

Working:
firejail --noprofile /mnt/tor-browser-tmpfs/tor_browser/Browser/start-tor-browser

Do I edit this line
private-bin bash,cp,dirname,env,expr,file,getconf,gpg,grep,id,ln,mkdir,python*,readlink,rm,sed,sh,tail,test,tor-browser-en,torbrowser-launcher

to

private-bin bash,cp,dirname,env,expr,file,getconf,gpg,grep,id,ln,mkdir,python*,readlink,rm,sed,sh,tail,test,start-tor-browser

**Comment by rusty-snake** [comment]
@cokeflash can you then try uncomment line for line and try after every uncomment (don't forget to save the file aber uncommenting).

**Comment by cokeflash** [comment]
shell none is prevent torbrowser to start with FireJail.

'shell none'

What to do? Remove it? Or edit it?

**Comment by rusty-snake** [comment]
@cokeflash then remove `shell none` from tor-browser.profile or comment it.

PS: Some else issue with starting tor browser or can we close?

**Comment by cokeflash** [comment]
'SOLVED'

...is working :-) Thanks for your help.
