### ISSUE TITLE
can setup an application

### ISSUE THREAD

**Issue by rezohs1234** [netblue30/firejail#2707]
hi i have a big problem when i click on firetools and configuration wizard when i chose an application the application don't start i try many applications many terminal nothing work now i what uninstall firetools and reinstall it for see i something happend can somebody tell me how ?

**Comment by rusty-snake** [comment]
@rezohs1234 more innformatons would be helpfull.

**Comment by rezohs1234** [comment]
nevermind that working i found a solution ok i have question when i install application with Chroot did that protect my system ? because when i do firejail --noprofile --chroot=/chroot/sid the answer is:Error: invalid --chroot=/chroot/sid command line option  i want know how to install an application and run it with firejail application_name without harming my system  i read all the docs search online for tutorial and didn't find the answer can you help me master  id do that before:
sudo mkdir /chroot
$ sudo debootstrap --arch=amd64 sid /chroot/sid
my arch is amd64 i run uname -a before thanks you mister the master !

**Comment by chiraag-nataraj** [comment]
#2728 and/or #2721 may be helpful for you @rezohs1234.

**Comment by rusty-snake** [comment]
@rezohs1234 I'm going to close that for now because of inactivity. Please fell free to reopen if you have more questions.
