### ISSUE TITLE
[help-me-plz] how to install an application and run it with firejail without harming my system

### ISSUE THREAD

**Issue by rezohs1234** [netblue30/firejail#2709]
i search online read the docs and cannot find how to install an appplication without harming my system  can *** somebody help me plz :)  with chroot is that ok or with OverlayFS ?

**Comment by rusty-snake** [comment]
@rezohs1234 I'm not sure I understand you right, but here's what I think you mean:
To just install and run an application (as an example firefox on ubuntu):
```
# Install firefox and firejail
$ sudo apt install firefox firejail
# start firejailed firefox
$ firejail firefox
# make firefox is firejailed by default
$ sudo firefcg
```

If you want to run malware to analyze it, you should use an VM.

**Comment by rezohs1234** [comment]
ok thanks but i found a solution create a vm and create another vm and sanbox the second virtual machine with firejail !

**Comment by chiraag-nataraj** [comment]
Closing as a solution has been found :)
