### ISSUE TITLE
What is the correct way to pass /tmp/.X11-unix into a chroot?

### ISSUE THREAD

**Issue by dandelionred** [netblue30/firejail#2711]
I debootstrapped ubuntu 19.04 into /nas/chroot/disco and installed smplayer inside.

Running this
```
firejail --noprofile --chroot=/nas/chroot/disco smplayer
```
I get this
```
...
qt.qpa.xcb: could not connect to display :0
...
```

As a dirty fix I set up such bind
```
sudo mount --bind /tmp /nas/chroot/disco/tmp
```
and chrooted smplayer can start now.

<br>

Is there some **native to firejail** way to pass /tmp/.X11-unix into a chroot?

<br>

Btw I run xorg with `-nolisten local` so there is no abstract socket. Hence /tmp/.X11-unix is the only way to X.

**Comment by smitsohu** [comment]
Setting an environment variable `FIREJAIL_X11` should work.

**Comment by dandelionred** [comment]
> Setting an environment variable `FIREJAIL_X11` should work.

I'm not sure how to use it
```
$ FIREJAIL_X11=1 firejail --noprofile --chroot=/nas/chroot/disco smplayer
Error: cannot find /tmp/.X11-unix in chroot directory
```

**Comment by smitsohu** [comment]
You need to create an empty `/tmp/.X11-unix` directory as mount point first.

**Comment by dandelionred** [comment]
Thanks, it works now.

Mby the FIREJAIL_X11 tip should be added to https://firejail.wordpress.com/documentation-2/x11-guide/ ?

**Comment by smitsohu** [comment]
To be honest, `FIREJAIL_X11` is quite a dirty solution itself.

In the moment Firejail doesn't help too much in setting up the chroot, but this also means it will not get in your way too much. I think what you described in the original post is "the correct way" actually.

**Comment by dandelionred** [comment]
KK, got it.

**Comment by smitsohu** [comment]
A last note: 

Don't set `FIREJAIL_X11` to `yes`, any other value will work just fine.

**Comment by dandelionred** [comment]
@smitsohu What is wrong with FIREJAIL_X11=yes?

**Comment by smitsohu** [comment]
@dandelionred FIREJAIL_X11=yes is used internally to indicate that an `--x*` option has been parsed; setting it to a value other than yes navigates around possible issues.

Did I already mention it is dirty? :smile:
