### ISSUE TITLE
Is it possible to create a new file virutal filesystem and isolate it from the main operating system?

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2721]
Is it possible to create a new file virtual filesystem and isolate it from the main operating system using firejail?

**Comment by chiraag-nataraj** [comment]
In what context? You could use `--overlay-tmpfs`, for example, depending on what you're trying to do.

**Comment by Raj2032** [comment]
So I want to install an application in a virtual environment, so I wanted to know if you can create a filesystem and this filesystem is isolated and cannot access the main operating system's files and any other resources. Does `--overlay-tmpfs` do what I want it to do?

Also with these virtual file systems, is it stored as a file on the main file system?

**Comment by rusty-snake** [comment]
@Raj2032 you may sould consider to use a VM. If you want to use firejail you can use the `--chroot` option (https://firejail.wordpress.com/documentation-2/basic-usage/#chroot), then you still need to protect the kernel like `firejail --noprofile --seccomp --chroot=/your/chroot program`

**Comment by Raj2032** [comment]
@rusty-snake I don't want to use VM as that is too slow.

Whats the difference between `--overlay-tmpfs` and `--chroot`?

**Comment by rusty-snake** [comment]
> --chroot=dirname
              Chroot the sandbox into a root filesystem. Unlike  the  regular
              filesystem  container, the system directories are mounted read-
              write. If the sandbox is started as  a  regular  user,  default
              seccomp and capabilities filters are enabled.

> --overlay-tmpfs
              Mount  a  filesystem  overlay on top of the current filesystem.
              All filesystem modifications are discarded when the sandbox  is
              closed.  Directories /run, /tmp and /dev are not covered by the
              overlay.  If the sandbox is started as a regular user,  default
              seccomp and capabilities filters are enabled.

> --overlay-named=name
              Mount  a  filesystem  overlay on top of the current filesystem.
              Unlike the regular filesystem container, the system directories
              are  mounted  read-write.  All filesystem modifications go into
              the overlay.  Directories /run, /tmp and /dev are  not  covered
              by the overlay. The overlay is stored in $HOME/.firejail/
              directory.  The created overlay can be reused between  multiple
              sessions.  If the sandbox is started as a regular user, default
              seccomp and capabilities filters are enabled.

**Comment by Raj2032** [comment]
@rusty-snake Thanks man one last question, using firejail chroot, can you have multiple filesystems?

**Comment by rusty-snake** [comment]
@Raj2032 Not sure, but maybe with mount or bind-mount.

**Comment by Raj2032** [comment]
@rusty-snake Thanks

**Comment by chiraag-nataraj** [comment]
@Raj2032 since it seems like your questions were answered, I'll go ahead and close this. Feel free to re-open if you have more questions!
