### ISSUE TITLE
Installing some Linux packages in overlayFS?

### ISSUE THREAD

**Issue by garywill** [netblue30/firejail#2728]
Hello firejail,

I want to try some software on my Linux but don't want to install them to my real system. Installing to firejail overlay FS is an option. 

But I can't use sudo to install in firejail. Running firejail as root is not a good idea, and root in firejail can't use X. 
What I want to do to overlayFS is
1. Installing software as root
1. Running software (GUI) as general user

Is there some way to do that? Does (will) firejail support uid/gid shifting (including FS)?

**Comment by rusty-snake** [comment]
@garywill what about https://firejail.wordpress.com/documentation-2/basic-usage/#overlayfs?

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/issues/1139#issuecomment-306063071
> This is an example using OpenShot video editor:
>
> In a terminal start a overlayfs sandbox (you would need a kernel 3.18 or better):
>
>     $ firejail --name=test --overlay --private --noblacklist=/sbin --noblacklist=/usr/sbin
>
> In a different terminal, join the sandbox as root and install the program - I am using apt-get on Debian:
>
>     $ sudo firejail --join=test
>     Switching to pid 2464, the first child process inside the sandbox changing root to /proc/2464/root
>     Child process initialized in 6.05 ms
>     # apt-get install openshot
>     # exit
>
> Back in the first terminal run the program
>
>     $ openshot
>
> Once you close both sandboxes, overlayfs is disabled and openshot disappears.

**Comment by rusty-snake** [comment]
I think this is answered, @garywill  if not or you have future questions, feel free to reopen.
