### ISSUE TITLE
Provide template for profile creation

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#2730]
It would be great if a template exists one could use for new profile creation - something that has basically everything disabled and provides an easy starting point with comments to tune it.

**Comment by rusty-snake** [comment]
@jose1711 https://gist.github.com/rusty-snake/018ae7c672f15bb45f10eb7626d2da19
I will update it in the next hours to my lastest one.

**Comment by jose1711** [comment]
thank you. could it become part of the repository? maybe `contrib/`?

**Comment by netblue30** [comment]
@rusty-snake 

Make a etc/templates directory on main, and put them there. I am thinking of including them in the source archives and installing them in /usr/share/doc/firejail directory.

**Comment by rusty-snake** [comment]
@netblue30 What do you mean with "main"?

**Comment by jose1711** [comment]
My understanding is that main == master branch

**Comment by netblue30** [comment]
Yes, here on github on the official master branch source code.

**Comment by rusty-snake** [comment]
cb98aea

**Comment by rusty-snake** [comment]
What about
```diff
diff --git a/src/man/firejail-profile.txt b/src/man/firejail-profile.txt
index 8c998997..f9726145 100644
--- a/src/man/firejail-profile.txt
+++ b/src/man/firejail-profile.txt
@@ -74,6 +74,9 @@ Child process initialized
 [...]
 .RE
 
+.SH Templates
+Templates for writing own profiles can be found in /usr/share/doc/firejail.
+
 .SH Scripting
 Scripting commands:

```

**Comment by TheDarkTrumpet** [comment]
I think it'd also benefit to put this in the CONTRIB, at least as a link.  I think most people look at the contrib over the man pages when encountering programs.  That's how I came about adding to the project.

**Comment by netblue30** [comment]
All of them are installed in /usr/share/doc/firejail. It looks something like this:
`````
 ls -l /usr/share/doc/firejail
total 104
-rw-r--r-- 1 root root 15146 Jun  8 14:15 COPYING
-rw-r--r-- 1 root root  4320 Jun  8 14:15 profile.template
-rw-r--r-- 1 root root 30021 Jun  8 14:15 README
-rw-r--r-- 1 root root   967 Jun  8 14:15 redirect_alias-profile.template
-rw-r--r-- 1 root root 40774 Jun  8 14:15 RELNOTES
-rw-r--r-- 1 root root  1859 Jun  8 14:15 syscalls.txt
`````
