### ISSUE TITLE
Profiles for Adobe products missing

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#2731]
Adobe products are known widely to have many (some serious) security issues: https://www.cvedetails.com/product-list/product_type-a/firstchar-A/vendor_id-0/page-1/products-by-name.html?sha=c96eb5386cf7b8259d58e0a5b92ce54b612a9989&order=3&trc=2403

Therefore I believe having profiles for Adobe reader (discontinued by may still be useful when features like form-filling is required), standalone flashplayer or Adobe AIR would be quite useful.

**Comment by rusty-snake** [comment]
Moved to #1139.
@jose1711 please use the issue above for profile request in the future.
