### ISSUE TITLE
[question] - running firefox with profile in RAM

### ISSUE THREAD

**Issue by Edu4rdSHL** [netblue30/firejail#2733]
Hello, I know that it isn't a firejail issue and I've opened it because I was searching for resources but sadly I doesn't found anything.

I'm trying to run Firefox profile in RAM using it script:

```
#!/bin/sh

static=static-$1
link=$1
volatile=/dev/shm/firefox-$1-$USER

IFS=
set -efu

cd ~/.mozilla/firefox

if [ ! -r $volatile ]; then
	mkdir -m0700 $volatile
fi

if [ "$(readlink $link)" != "$volatile" ]; then
	mv $link $static
	ln -s $volatile $link
fi

if [ -e $link/.unpacked ]; then
	rsync -av --delete --exclude .unpacked ./$link/ ./$static/
else
	rsync -av ./$static/ ./$link/
	touch $link/.unpacked
fi
```
What it do is basically put the profile in /dev/shm/firefox-* and symlink $HOME/.mozilla/firefox/profile.xyz to it. I can't get it working still with `noblacklist /dev/shm/firefox-*`, any help will be appreciated.

And sorry for putting it here.

**Comment by smitsohu** [comment]
You may want to have a look at the `--keep-dev-shm` option. If your Firejail doesn't have it, you will need to upgrade to a newer version.

**Comment by glitsj16** [comment]
@Edu4rdSHL There's a dedicated program for doing what you want called `profile-sync-daemon`. See the [Arch Wiki page](https://wiki.archlinux.org/index.php/Profile-sync-daemon) and the [official repo](https://github.com/graysky2/profile-sync-daemon#installation-from-distro-packages) for more info. It should work with firejail out-of-the-box.

**Comment by chiraag-nataraj** [comment]
@Edu4rdSHL, why not use a temporary directory under `/tmp/user/$UID`?

**Comment by Edu4rdSHL** [comment]
Thanks to all. @glitsj16 profile-sync-daemon worked as expected.
