### ISSUE TITLE
Firefox doesn't work with W^X enforced by firejail

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#2744]

**Comment by chiraag-nataraj** [comment]
Which version of Firefox? Which version of firejail?

**Comment by Vincent43** [comment]
This is expected. browsers aren't compatible with W^X.

**Comment by KOLANICH** [comment]
https://jandemooij.nl/blog/2015/12/29/wx-jit-code-enabled-in-firefox/

**Comment by KOLANICH** [comment]
>Which version of Firefox?

The latest one in Ubuntu repo.

>Which version of firejail?

The one built today from git.

**Comment by chiraag-nataraj** [comment]
Okay, but GTK+ and Qt don't like W^X. At all. There's a lot more to this than just the JIT compiler.

**Comment by chiraag-nataraj** [comment]
It doesn't look like we enable W^X for Firefox in the profiles we distribute, so I'm confused as to why you opened this issue, to be honest. The fact that Firefox (and pretty much _every_ graphical program) doesn't work with W^X is a problem to file in _their_ bug trackers, not on here.

This would be more understandable if we mistakenly enabled W^X for Firefox or something, but we're not doing that.

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this since there isn't much we can do about it from our end. Feel free to re-open if I misunderstood something.

**Comment by KOLANICH** [comment]
>The fact that Firefox (and pretty much every graphical program) doesn't work with W^X is a problem to file in their bug trackers, not on here.

Definitely. But we need to track compatibility issues on our side too. Maybe a special issue which head post is updated by a bot reading specially formatted comments in profiles?

>Okay, but GTK+ and Qt don't like W^X.

Yeah, if it is a case, this is surely their bugs.

**Comment by chiraag-nataraj** [comment]
This isn't a compatibility issue, though. There's literally nothing we can do from our end besides disabling the flag for that profile. File bugs upstream and see if they'll change things. I highly suspect they won't :/

**Comment by Vincent43** [comment]
That article is quite dated so it's hard to figure what current status is. [Someone in comments](https://jandemooij.nl/blog/2015/12/29/wx-jit-code-enabled-in-firefox/#comment-2432767666) stated that you have to build firefox with `--disable-ion` (is it still valid?) but the cost is quite high. There are also [some jit related options in config](https://en.wikibooks.org/wiki/Grsecurity/Application-specific_Settings#Firefox_(or_Iceweasel_in_Debian)) you may try disabling.

**Comment by SkewedZeppelin** [comment]
@Vincent43 

> (is it still valid?) 

https://searchfox.org/mozilla-central/source/js/src/devtools/automation/variants/nojit
seems so, who knows if it actually works

**Comment by KOLANICH** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1338207
https://bugzilla.mozilla.org/show_bug.cgi?id=1371877
