### ISSUE TITLE
[suggestion] allow ssh to use netcat to connect to Tor onion services

### ISSUE THREAD

**Issue by caioau** [netblue30/firejail#2750]
Hi, I'm very happy with firejail, keep the good work!

I have an idea to improve the ssh profile

I tried to sshing my home box via Tor Onion service (because my ISP is behind a NAT) but the nc (netcat) has not allowed, I'm with firejail version 0.9.61 (compiled myself) on Ubuntu 18.04, I executed `ssh home` there was an permission denied to run nc, look at my `.ssh/config` file:

```
Host home
   HostName realyLongString.onion
   IdentitiesOnly yes
   IdentityFile ~/.ssh/ssh-key.pub
   Compression yes
   ProxyCommand /bin/nc -X 5 -x 127.0.0.1:9150 %h %p

```

so it will connect to port 9150 (while Tor Browser is running) , I did't the following: added the `ignore blacklist ${PATH}/nc` to the ssh.local, to override the disable-common.inc. Thanks

**Comment by rusty-snake** [comment]
I would prever to only add a comment like:
```
# If you want to use tor, uncomment the next line or put it in your ssh.local
#noblacklist ${PATH}/nc
```

**Comment by rusty-snake** [comment]
Done: e7ba153
