### ISSUE TITLE
Run Firefox on remote X11 server without X11 forwarding

### ISSUE THREAD

**Issue by mikkol554** [netblue30/firejail#2752]
Dears,

I run the Xming X11 server on a Windows computer and have Firefox installed in another Fedora computer in the same network. I normally execute graphical Linux applications by prepending `DISPLAY=<xming host address>:0.0` to `<command name>`. In some cases, I may need to use dbus-launcher to get things working (as with `gnome-shell`, for example).

I do not use SSH X11 forwarding but the Xming server is configured for plain, direct TCP connections from clients instead of being dependent on the SSH connection being alive (and creating overhead).

I cannot run Firefox with firejail using this setup. I only get

>Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.

with

>Error safe_fd: pulseaudio.c:188 pulseaudio_init: Not a directory
>Error: proc 32178 cannot sync with peer: unexpected EOF

The connection does not carry audio nor do I need it for anything.

Ideas?

**Comment by rusty-snake** [comment]
@mikkol554 works it with `firejail --noprofile firefox`?
PS: what firejail version do you use? `firejail --version`

**Comment by mikkol554** [comment]
`DISPLAY=10.168.0.53:0.0 firejail --noprofile firefox`
>Parent pid 4756, child pid 4757
>Error safe_fd: pulseaudio.c:188 pulseaudio_init: Not a directory
>Error: proc 4756 cannot sync with peer: unexpected EOF
>Peer 4757 unexpectedly exited with status 1

`firejail --version`
>firejail version 0.9.57
>
>Compile time support:
>        - AppArmor support is disabled
>        - AppImage support is enabled
>        - chroot support is enabled
>        - file and directory whitelisting support is enabled
>        - file transfer support is enabled
>        - networking support is enabled
>        - overlayfs support is enabled
>        - private-home support is enabled
>        - seccomp-bpf support is enabled
>        - user namespace support is enabled
>        - X11 sandboxing support is enabled

**Comment by smitsohu** [comment]
If you don't need audio, try to add a `nosound` option.

If `pulseaudio --version` returns 10 or higher, you can as an alternative also try the `noautopulse` option. That should work as well and keep the sound going.

**Comment by mikkol554** [comment]
Thank you. Adding `--nosound` does the trick. It runs smoothly on the remote X server without SSH tunneling.
