### ISSUE TITLE
Wiki: Sandboxing Binary Software

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#2755]
Issue for discussions about https://github.com/netblue30/firejail/wiki/Sandboxing-Binary-Software

**Comment by matu3ba** [comment]
The description is consistent for LTS versions, but not newer versions. These are installed to `/usr/local`.
Maybe it would be nice to mention the user to check, if there does exist a profile yet to restrict the programs data access (for example to the default folder).

**Comment by rusty-snake** [comment]
@matu3ba  https://github.com/netblue30/firejail/issues/2748#issuecomment-504639472

**Comment by matu3ba** [comment]
@rusty-snake Did add #2748 command to Profiles and linked there.

**Comment by matu3ba** [comment]
Closing this?

**Comment by Mikaela** [comment]
Would it be OK to add instructions to verify gpg signatures of applications on the page?

For example with Tor Browser it would be adding

* `gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org`
* `gpg --verify tor-browser-linux64-8.5.1_en-US.tar.xz.sig`

With Firefox it would be a bit more tricky digging the signature from https://releases.mozilla.org/pub/firefox/releases/ and key from https://blog.mozilla.org/security/2019/06/13/updated-firefox-gpg-key/

**Comment by rusty-snake** [comment]
Sounds good to me.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/discussions/4449
