### ISSUE TITLE
Firejail does not work with a custom hosts file

### ISSUE THREAD

**Issue by rmrgh** [netblue30/firejail#2758]
When running firejail with a custom hosts file:
`$ firejail --noprofile --private --hosts-file=hosts firefox -no-remote`
it reports the following errors:
```
Parent pid 32480, child pid 32481
Error: invalid /etc/hosts file
Error: proc 32480 cannot sync with peer: unexpected EOF
Peer 32481 unexpectedly exited with status 1
```

My hosts file contains only:
```
127.0.0.1 sample.localhost
```

Even with an empty file, it report the same errors.

**Firejail Version:** 0.9.58
**Linux Distribution:** NixOS 19.03

**Comment by rusty-snake** [comment]
Can't reproduce with firejail 0.9.61 under Fedora 29.
```
$ firejail --private --noprofile --hosts-file=hfile firefox-wayland -no-remote
… No Error about hosts
$ cat hfile
127.0.0.1 some.localhost
```

**Comment by chiraag-nataraj** [comment]
I even just tried `firejail --hosts-file=/dev/null` and it worked.

**Comment by netblue30** [comment]
There could be two reasons it to fail: if the host file is a symbolic link, or if the user doesn't have read access to the file. Also, try to put a full path for the host file, something like "--host-file=/home/username/hostfile". Works fine on 0.9.58, that code didn't change in ages.

**Comment by rmrgh** [comment]
I've tried with a VoidLinux installation with firejail version 0.9.60 and it worked just fine. I think it's something specific for NixOS since the `/etc/hosts` present on it is a symbolic link and can't be directly manipulated (readonly).

**Comment by rmrgh** [comment]
I've tested on my VoidLinux installation by moving the `/etc/hosts` file to a different location and symblinking it back to `/etc/hosts` and the same error showed up.

**Comment by Nudin** [comment]
I got the same issue on Arch with firejail 0.9.62. The file is no symlink and readable by the user.
```
$ touch /home/michi/empty
$ chmod 777 /home/michi/empty
$ firejail --noprofile --hosts-file=/home/michi/empty
Parent pid 87979, child pid 87980
Error: invalid /etc/hosts file
Error: proc 87979 cannot sync with peer: unexpected EOF
Peer 87980 unexpectedly exited with status 1
```

**Comment by Enteee** [comment]
Can confirm the same behavior as @rmrgh  observed on NixOS (symlinked /etc/hosts). Firejail `0.9.64.4` does fail on `firejail --hosts-file=/dev/null` with:

```
Error: dumpable process
Remove read permission on fseccomp executable
Warning: cleaning all supplementary groups
Error: invalid /etc/hosts file
Error: proc 13962 cannot sync with peer: unexpected EOF
Peer 13963 unexpectedly exited with status 1
```

**Comment by deliciouslytyped** [comment]
@Enteee thanks,  I ran into the same issue. 

Low key note that copying the script into a config wont work if you use spaces because the source file uses tabs, it causes a small bit of confusion as to why the patch isn't applying.

**Comment by dunesong** [comment]
Had the same issue. In my case, /etc/hosts was not owned by root. Correcting that fixed the issue.

`sudo chown root:root /etc/hosts`

**Comment by smitsohu** [comment]
@onny May I ask where the link points to in NixOS?

**Comment by onny** [comment]
> @onny May I ask where the link points to in NixOS?
> 
> EDIT: Reading a bit more about NixOS this is probably a stupid question. It points to `/nix/store/something` if I understand correctly.

Yep thats right.
```
namei -l /etc/hosts
f: /etc/hosts
drwxr-xr-x root root   /
drwxr-xr-x root root   etc
lrwxrwxrwx root root   hosts -> /etc/static/hosts
drwxr-xr-x root root     /
drwxr-xr-x root root     etc
lrwxrwxrwx root root     static -> /nix/store/6z9wz2j0cv06hxf5iqhlil421mmnnz32-etc/etc
drwxr-xr-x root root       /
drwxr-xr-x root root       nix
drwxrwxr-t root nixbld     store
dr-xr-xr-x root root       6z9wz2j0cv06hxf5iqhlil421mmnnz32-etc
dr-xr-xr-x root root       etc
lrwxrwxrwx root root     hosts -> /nix/store/ppbg1m59fsw5740fgi1kz3xaap2bvzgm-hosts
drwxr-xr-x root root       /
drwxr-xr-x root root       nix
drwxrwxr-t root nixbld     store
-r--r--r-- root root       ppbg1m59fsw5740fgi1kz3xaap2bvzgm-hosts
```

**Comment by Enteee** [comment]
@netblue30 : why was this closed. I think the issue is still relevant.

**Comment by rusty-snake** [comment]
Because #4560 was merged.

**Comment by Enteee** [comment]
I have not yet tested it. But I think before merging something that is more or less my suggested patch somebody should have falsified the following:

> Inside the jail the file /etc/hosts points to is actually changed to whatever you set as --hosts-file but it is not actually used by the system resolve. Don't really know why...

**Comment by earldouglas** [comment]
I also ran into this on NixOS.  In my case, the fix was simply to add a newline to the end of my hosts file.

**Comment by gleruzh** [comment]
Same issue

archlinux, my hosts file is ~empty (only commented string)
Newline at the end of the file does not fix the issue.
firejail version 0.9.74

Compile time support:
        - always force nonewprivs support is disabled
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file transfer support is enabled
        - IDS support is disabled
        - Landlock support is enabled
        - networking support is enabled
        - output logging is enabled
        - overlayfs support is disabled
        - private-home support is enabled
        - private-lib support is disabled
        - private-cache and tmpfs as user enabled
        - sandbox check is enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

**Comment by kmk3** [comment]
Note that this issue was closed years ago.

If something does not appear to work as intended, please open a new issue and
follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>
