### ISSUE TITLE
Unexpected behaviour of --whiltelist option when no whitelisted files exist

### ISSUE THREAD

**Issue by manevich** [netblue30/firejail#276]
How to reproduce:
```firejail --whitelist=/home/user/no-such-file-1 --whitelist=/home/user/no-such-file-2```

Result: intact `/home/user/` directory.
Expected result: same almost-empty `/home/user/` directory as with `firejail --private`.

If at least one of whitelisted files exist, everything works as excepted.

**Comment by netblue30** [comment]
Fixed!
