### ISSUE TITLE
Versions dont look right

### ISSUE THREAD

**Issue by tinmanx** [netblue30/firejail#2761]
![2019-06-12](https://user-images.githubusercontent.com/46136520/59333427-96b91200-8cf8-11e9-875e-064b507f1e11.png)
is this correct? why is the latest one a lower version than 0.9.60 ?

**Comment by rusty-snake** [comment]
@tinmanx because its the LTS version.
@netblue30 is the missing of `-LTS` wanted?

**Comment by netblue30** [comment]
All fixed, the new tag is 0.9.56,2-LTS. Thanks for the bug.
