### ISSUE TITLE
Symlink for newsboat

### ISSUE THREAD

**Issue by DocKDE** [netblue30/firejail#2762]
Greetings!

It seems, there have been several problems with symlinks already but even after consulting those and the man page, I wasn't able to figure out my problem so here goes. I want to run newsboat in firejail, however the config files stored in `~/.newsboat` reside in a separate folder `~/Documents/dotfiles/.newsboat` for which I created a symlink. 
In the config file I thus simpy added the latter folder to noblacklist and whitelist. I own both the symlink and the folder and they both reside in /home. However, firejail gives me

> Reading profile /etc/firejail/newsboat.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 16450, child pid 16463
Warning: skipping alternatives for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Warning: skipping terminfo for private /etc
Private /etc installed in 399.11 ms
1 program installed in 45.73 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 4442.22 ms
Starting newsboat 2.15.0...
Error: an instance of newsboat is already running (PID: 0)
Parent is shutting down, bye...`

I wasn't able to find out where the problem is, exactly. It definitely is connected to the symlink though since removing it "fixed" the problem.

I'd be grateful for some help

**Comment by rusty-snake** [comment]
@DocKDE can you paste your profile.
Has you add `noblacklist ${DOCUMENTS}`?

**Comment by DocKDE** [comment]
> Has you add `noblacklist ${DOCUMENTS}`?
Huh, that fixed it. I take it for some reason non-blacklisting the parent folder is necessary in addition to the subfolder which I already took care of?
Anyway thanks for your help!
