### ISSUE TITLE
qTox: hangs after launch in Arch Linux due to memory-deny-write-execute 

### ISSUE THREAD

**Issue by grizzlyuser** [netblue30/firejail#2767]
```
$ firejail --version
firejail version 0.9.60

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```
Linux Distributions: Arch Linux, Parabola GNU/Linux-libre

`firejail qtox` starts the process, but the main application window doesn't show up.

Works fine if `memory-deny-write-execute` is commented in `/etc/firejail/qtox.profile`. Seems to be related to issue #1803.

The problem didn't exist in the previous release of firejail. As I understood, that was due to addition of `memory-deny-write-execute` after it.

Tested in Gnome@Wayland and KDE Plasma@Xorg

**Comment by glitsj16** [comment]
@grizzlyuser Should be fixed now. Thanks for reporting it!
