### ISSUE TITLE
"private-cache" in aria2c.profile breaks lutris/winetricks installs

### ISSUE THREAD

**Issue by Ryujinra** [netblue30/firejail#2772]
Lutris/winetricks needs to access files it downloads with aria2c to `${HOME}/.cache/winetricks` during installations.

The default aria2c profile contains `private-cache` which prevents lutris from accessing the files after it uses aria2c to download them.

Commenting out `private-cache` fixes the issue. Noblacklisting the winetricks cache folder does not.

**Comment by glitsj16** [comment]
@Ryujinra Fixed, thanks for reporting this! Feel free to reopen if something is still not working as expected with aria2c.
