### ISSUE TITLE
x11 xorg doesn't seem to respect the quiet option

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#2787]
Recently I started to experiment/test profiles with `--audit` and trying to fix anything reported as `UGLY` or `MAYBE` in .local files. This has proven to work really well. One thing I've noticed though is that `x11 xorg` doesn't seem to follow the `quiet` option. E.g. with dig (which has the quiet option in its profile):

```
$ firejail --audit --x11=xorg /usr/bin/dig
Using authority file /tmp/.tmpXauth-H9Pmcp
authorization id is 1624
Writing authority file /tmp/.tmpXauth-H9Pmcp
---------------- Firejail Audit: the GOOD, the BAD and the UGLY ----------------
...
```

Explicitly calling the quiet option on a profile that doesn't have it (e.g. claws-mail) also shows the same behavior:

```
$ firejail --audit --quiet --x11=xorg /usr/bin/claws-mail
Using authority file /tmp/.tmpXauth-Z9n89F
authorization id is 1532
Writing authority file /tmp/.tmpXauth-Z9n89F
---------------- Firejail Audit: the GOOD, the BAD and the UGLY ----------------
...
```

Is this intended (with audit)?

**Comment by chiraag-nataraj** [comment]
Seems like those statements aren't inside a `if(arg_debug)`, so it seems like the intentions is for them to always be printed? I suppose that's up for debate though heh.

**Comment by glitsj16** [comment]
@chiraag-nataraj That indeed seems the intention, which I find counterintuitive in the case of `quiet`. I'll experiment with `(arg_debug)`, `(arg_quiet)` etcetera in the [code](https://github.com/netblue30/firejail/blob/master/src/firejail/x11.c) and try not to break anything.

**Comment by netblue30** [comment]
It shouldn't show anything on the screen, we have to clean it up. @glitsj16 give it a try.

**Comment by glitsj16** [comment]
@netblue30 Thanks for clearing that up. I'm in the middle of an annual dance, relocating the family now school responsibilities are suspended for a couple of months. In a day or two I should have a PR ready.

**Comment by netblue30** [comment]
No problem, take your time.

**Comment by glitsj16** [comment]
@netblue30 I left in the xauth output while using --debug (where it might be helpful). If this is not what you want, I can easily take out the relevant conditional in https://github.com/netblue30/firejail/blob/master/src/firejail/x11.c#L1135 and below. Hope this didn't break anything...
