### ISSUE TITLE
Thoughts on tightening SSH profiles with nodbus

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#2790]
After creating a [draft PR](https://github.com/netblue30/firejail/pull/2789) on the topic, I realized the question might get more exposure when filed as an issue. If any of the firejail users have an opinion as too why we can't/shouldn't add `nodbus` to the relevant profiles, that would be very welcome. Apologies for doing things backwards.

Cheers

**Comment by netblue30** [comment]
I did a short test, it seems to be fine. I would say let's put it in and deal with things breaking when we get somebody complaining.

**Comment by glitsj16** [comment]
Added `nodbus` to ssh{,-agent}.profile in https://github.com/netblue30/firejail/pull/2789. Closing this for now. As always, if someone encounters issues with the changes, feel fre to open.
