### ISSUE TITLE
Disable firetunnel support at build time?

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#2793]
Does such build-time option exist?  If not, could you please add it?

**Comment by glitsj16** [comment]
@laniakea64 Firetunnel isn't part of firejail, and has its own [repository](https://github.com/netblue30/firetunnel). Does your OS/distribution offer firetunnel in a firejail package?

**Comment by laniakea64** [comment]
Sorry, maybe I wasn't quite clear.

> Firetunnel isn't part of firejail, and has its own repository

Thanks but was already aware of this :slightly_smiling_face: By "firetunnel support" I mean whatever this statement in [firejail 0.9.56 changelog](https://firejail.wordpress.com/download-2/release-notes/) is referring to -
```
  * support for firetunnel utility
```

> Does your OS/distribution offer firetunnel in a firejail package?

I build firejail .deb straight from this repo source.

**Comment by rusty-snake** [comment]
@laniakea64 this commit: https://github.com/netblue30/firejail/commit/419d876d9fef926e183c0b3bc0961a9abe9e7ba5

**Comment by netblue30** [comment]
Use --disable-firetunnel, something like this:
`````
$ ./configure --disable-firetunnel
`````

**Comment by laniakea64** [comment]
Works well, Thanks @netblue30 ! :smiley:
