### ISSUE TITLE
Firefox cannot open mailto links

### ISSUE THREAD

**Issue by alexandre1985** [netblue30/firejail#2795]
My Firefox cannot open mailto: links to my Evolution email client.
Help?

**Comment by rusty-snake** [comment]
Try:
```
cat >> ${HOME}/.config/firejail/firefox.local << EOF
noblacklist /var/mail
noblacklist /var/spool/mail
noblacklist ${HOME}/.bogofilter
noblacklist ${HOME}/.cache/evolution
noblacklist ${HOME}/.config/evolution
noblacklist ${HOME}/.gnupg
noblacklist ${HOME}/.local/share/evolution

whitelist /var/mail
whitelist /var/spool/mail
whitelist ${HOME}/.bogofilter
whitelist ${HOME}/.cache/evolution
whitelist ${HOME}/.config/evolution
whitelist ${HOME}/.gnupg
whitelist ${HOME}/.local/share/evolutio
EOF
```

**Comment by SkewedZeppelin** [comment]
or https://github.com/netblue30/firejail/issues/1718#issuecomment-406819438

**Comment by alexandre1985** [comment]
I test it, and it isn't working still... @rusty-snake

**Comment by SkewedZeppelin** [comment]
@alexandre1985 can you fix the typo on the last line and try again?

**Comment by alexandre1985** [comment]
Yes, I didn't write the typo on my `firefox.local` @SkewedZeppelin

**Comment by alexandre1985** [comment]
If you give me the commands to create a firejail config file and test opening firefox and clicking on a mailto: link , I can do that on my system

**Comment by rusty-snake** [comment]
What is the terminal output?

Have you setup your FF to open in evolution by default or to ask?

**Comment by alexandre1985** [comment]
```
(evolution:312): dconf-WARNING **: 08:14:14.690: failed to commit changes to dconf: impossível ligar: Permission denied
```

**Comment by rusty-snake** [comment]
Try to add `ignore nodbus` and `ignore apparmor` to the `firefox.local` above.

**Comment by alexandre1985** [comment]
> Try to add `ignore nodbus` and `ignore apparmor` to the `firefox.local` above.

It works now @rusty-snake.
:wink:

**Comment by rusty-snake** [comment]
greate, if you want, you can try to findout if it works with only one `ignore` (is more secure).

**Comment by alexandre1985** [comment]
I only need `ignore nodbus`.
Thank you :1st_place_medal:
