### ISSUE TITLE
Firejail is almost broken on fedora silverblue

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#2798]
Don't know if that is fixable.

**Comment by Fred-Barclay** [comment]
@rusty-snake what bits are almost broken?

**Comment by rusty-snake** [comment]
Some examples:
 * `wget example.com/something` works
 * `firejail wget example.com/something`: Cannot write to 'something'  (Operation not permitted)
***
 * `firejail firefox`: no window are opening
***
 * `firejail epiphany`: `Fatal initialization error: Failed to create directory "/var/home/USER/.local/share/epiphany
***
 * `pwd`: /var/home/USER
 * `firejail bash`
     * `pwd`: /
***
 * `firejail dig @9.9.9.9 example.com`: works

**Comment by netblue30** [comment]
It is totally broken! They run a very unconventional filesystem, with /home and a lot of other directories as symbolic links inside /va, details here:

https://docs.fedoraproject.org/en-US/fedora-silverblue/technical-information/#filesystem-layout

We won't be able to support this distro. It is an enterprise distro anyway, something to do with containers.

**Comment by trochdewei** [comment]
better use SELinux on Fedora

**Comment by Vincent43** [comment]
It's not enterprise distro, it's more like alternative desktop platform focused on containerized apps like flatpak. Still firejail support for it is unlikely.
