### ISSUE TITLE
kdialog doesn't work with Firejail

### ISSUE THREAD

**Issue by travankor** [netblue30/firejail#2804]
Running firejail  + kdialog breaks most KDE applications on KDE. 
Repoduce by:

1. Install KDE+kdialog
2. Set up firejail
3. Most KDE applications like dolphin won't launch

**Comment by rusty-snake** [comment]
@travankor kdialog didn't has a firejail profiel so what do you mean with
> 2. Set up firejail

If you did `sudo ln -s /usr/bin/firejail /usr/local/bin/kdialog`, try `touch ~/.config/firejail/kdialog.profile` (maybe also `mkdir ~/.config/firejail`).

**Comment by rusty-snake** [comment]
@travankor I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
