### ISSUE TITLE
Document broken options order for appimage

### ISSUE THREAD

**Issue by zabbal** [netblue30/firejail#2807]
While trying to run appimage the order in which options are processed actually have an impact on the way appimage is executed:

`
firejail --private=~/tmp/test --net=none --appimage ~/.local/img
`
will execute an appimage as expected.

`
firejail --private=~/tmp/test --appimage ~/.local/img --net=none 
`
Will fail because the last option is given to appimage as-is instead of being processed by firejail itself.

This is highly counter-intuitive and should be at the very least documented in https://firejail.wordpress.com/documentation-2/appimage-support/ or, better yet, fixed so only the options after explicit mark (or options unsupported by firejail) are given to appimage.

**Comment by netblue30** [comment]
Add to man page:
`````
[...]
SYNOPSIS
       Start a sandbox:

              firejail [OPTIONS] [program and arguments]

       Start an AppImage program:

              firejail [OPTIONS] --appimage [appimage-file and arguments]

       File transfer from an existing sandbox

              firejail {--ls | --get | --put} dir_or_filename

[...]
`````
