### ISSUE TITLE
window title

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#281]
From wordpress:

However, I think 1ab4535fab9de3273a73e3d1002a8e4a4f546666 (changing the terminal title to “Firejail”) should be reverted. While I’m not against the suggestion of appending “[firejailed]” after the terminal title, the current solution also removes the information about the terminal program, which is much more valuable!
For example, if someone uses the following programs in three separate terminals:
firejail less aaa.txt
firejail less bbb.txt
firejail mpv song.mp3
I think it is undeniably easier to navigate the default titles: “less aaa.txt”, “less bbb.txt”, “mpv song.mp3”, than “Firejail”, “Firejail”, “Firejail”. As a user of many terminal programs, I can confirm that it is currently very difficult to select the correct window, whether from alt-tab or a list. Scripting based on window title (aside from “firejailed or not”) is also not possible right now.

**Comment by netblue30** [comment]
Fixed!

**Comment by rogshdo** [comment]
Was this fixed? I am running firejail 0.9.44. When I run, for instance `firejail mutt`, my window title is `firejail`. This isn't helpful when in tmux all my window names are firejail!

**Comment by rogshdo** [comment]
Looking further, this appears to be a tmux issue. If I run `$ firejail mutt` in a terminal without tmux, the window title is `firejail mutt`.

However, I run tmux in all my terminals. Tmux looks like it only takes the first word of the window name by default. So they all end up being named `firejail`.

Has anyone else encountered this?

#242 suggested just using asterisks around the name, so the result would be `*mutt*`. I like that much better. It would avoid this issue with tmux, and is nice a short which can be an issue with lots of windows open.

**Comment by netblue30** [comment]
Let's reopen it and make it a bug. Maybe somebody comes up with another idea. I'll look into detecting tmux. Calling all windows firejail is very bad.

**Comment by pigmonkey** [comment]
I also use firejails in tmux and experience the same issue. I frequently have the same things running in the same windows all the time, so I'll tend to just rename the window to `mutt` or whatever the program is.

I like the idea of wrapping the program name in asterisks or something along those lines to keep it short.

Does it make sense for this to be something that is configured in the profile? Something like:

    # I like the current default!
    windowtitle "firejail $program"
    # I want asterisks!
    windowtitle "*$program*"

Where `$program` is interpreted by firejail.

**Comment by chiraag-nataraj** [comment]
Let's move discussion to #1983.
