### ISSUE TITLE
firejail help for novice

### ISSUE THREAD

**Issue by Klaris69** [netblue30/firejail#2813]
Hi hi,
i am a newbie in linux and use in firejail :-P
I use: OS Linux Mint 19.1 Mate + firejail_0.9.56.2-LTS_1_amd64.deb
i want to use firejail only to block applications to access the internet.

I used the command: sudo firecfg
I misunderstood the command function,, (I thought it was a function to start the service automatically after the boot)
how can I disable or reset this setting?
when i run firefox and enter "firejail --top" (i see firefox is in firejail mode)

You can tell me how to proceed.
for example, I have a "ABC" folder on my desktop and I have a Double Commander application in it.
what do i do to keep this app running without internet access?

**Comment by Klaris69** [comment]
Ok, If I'm not mistaken for my first question, the answer is: firecfg --clean

**Comment by rusty-snake** [comment]
Hi @Klaris69 
> I misunderstood the command function,, (I thought it was a function to start the service automatically after the boot)

firejail isn't a service, undo with `sudo firecfg --clean`

> You can tell me how to proceed. for example, I have a "ABC" folder on my desktop and I have a Double Commander application in it.
what do i do to keep this app running without internet access?

Use `--net=none` on the command line or `net none` in profiles.
Example for mpv (media player):
Command line: `firejail --net=none mpv foo.mp4` (works always)
Profiles: add `net none` to `~/.config/firejail/mpv.local` and run `firejail mpv foo.mp4` (works only if the application has a firejail profile)

**Comment by rusty-snake** [comment]
You was faster :joy:

**Comment by rusty-snake** [comment]
FAQ about this: https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions#how-do-i-run-vlc-in-a-sandbox-without-network-access

**Comment by Klaris69** [comment]
Oki, thnaks :-)
