### ISSUE TITLE
fcopy size limit is not adjustable

### ISSUE THREAD

**Issue by maxhaslbeck** [netblue30/firejail#2820]
hi,

I add an folder to private-home that happens to be bigger than 500MB in

```
firejail --noprofile --private-home=MYFOLDER MYCOMMAND
```

i get the error message

```
Error fcopy: size limit of 500MB reached
```

is there a reason for the size limit in fcopy? can I increase it easily?
are large files in the private-home discouraged?
Is there a simple workaround to get MYFOLDER available within the jail?

cheers,
max

**Comment by rusty-snake** [comment]
limit is set [here](https://github.com/netblue30/firejail/blob/master/src/fcopy/main.c#L30)

> are large files in the private-home discouraged?

Becauce the fiels are copied, there are large performace losing while starting the programm.

> Is there a simple workaround to get MYFOLDER available within the jail?

I recommend to use `whitelist` and `overlayfs-tmpfs` instead of `private-home`, because it is faster.

**Comment by Vincent43** [comment]
Unlike `private-home`, `overlayfs-tmpfs` isn't persistent. More equivalent option is `overlay-named` but we have reports that [it may be broken in recent kernels](https://github.com/netblue30/firejail/issues/2799).

**Comment by rusty-snake** [comment]
> Unlike `private-home`, `overlayfs-tmpfs` isn't persistent.

> --private-home=file,directory
              Build  a  new user home in a temporary filesystem, and copy the files
              and directories in the list in the new home.  **All  modifications  are
              discarded when the sandbox is closed.**

**Comment by Vincent43** [comment]
@rusty-snake you are right, I confused `--private-home=` with `--private=`, the latter one is persistent, sorry.

**Comment by netblue30** [comment]
@maxhaslbeck

Load the latest from mainline and in /etc/firejail/firejail.config set file-copy-limit to whatever you need.
The files get copied in a temporary filesystem in RAM, and if you run out of memory the kernel will start swapping - this is why we put a limit on it.
