### ISSUE TITLE
Set niceness

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#283]
Hi!

If possible, I'd like an option to set a different niceness to processes e.g: `nice -20` and `--nice=-20`.

Thanks

**Comment by voidzero** [comment]
To add to this, maybe task scheduling `chrt(1)`, cpu affinity `taskset(1)`, IO scheduling `ionice(1)` would also be... nice to have. In addition to this, perhaps `setarch(8)` with which people can change personality flags among other things. For scheduling also see `sched(7)`. 

chrt is nice for different scheduling reasons: users can choose SCHED_BATCH and perhaps also SCHED_FIFO, SCHED_RR depending on /etc/security/limits.conf.

(Note for whom it may concern; words like `this(n)` refer to manual pages. Example: `man 1 chrt`.)

**Comment by netblue30** [comment]
Implemented in git!

**Comment by nick75e** [comment]
Thanks!
