### ISSUE TITLE
mpv: no-cache causes slow OSD

### ISSUE THREAD

**Issue by Artefact2** [netblue30/firejail#2838]
The `no-cache` in `mpv.profile` causes the OSD to load slowly the first time it is used (a couple of seconds), freezing video playback. `mpv -v` gives:

~~~
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.5.3 (COMPLEX)
[osd/libass] Setting up fonts... <-- this is where it hangs
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/noto/NotoSans-Medium.ttf, 0, NotoSans-Medium
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
~~~

Removing `private-cache` works as expected (libass can access fontconfig cache and the fonts load instantly, no OSD slowdown).

**Comment by glitsj16** [comment]
@Artefact2 Should be fixed in git master. Thanks for reporting this!
