### ISSUE TITLE
Duplicate directories in file dialog

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#2839]
A [Debian user reported](https://bugs.debian.org/930571) that the file loading/saving dialog shows duplicate entries when being used with firejail.
I was able to confirm/reproduce that.

[screenshot](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=930571;filename=Screenshot_20190615_193838-firejail.jpeg;msg=5)

**Comment by SkewedZeppelin** [comment]
https://github.com/netblue30/firejail/issues/2406#issuecomment-464501230

**Comment by reinerh** [comment]
@SkewedZeppelin thank you, that was helpful! :+1:
