### ISSUE TITLE
Cannot run lxterminal

### ISSUE THREAD

**Issue by liloman** [netblue30/firejail#284]
Hi, 

I just started to use this tool for firefox with vimperator.
Everything is working right but if I do:
:!pcmanfm 

I can launch a file explorer without restriction. :question: 

Is it a common issue? Cause if I understand right the child should have the same privileges as his parent.

Cheers and great tool :+1:

**Comment by brunonova** [comment]
I don't use PCManFM, but maybe when it's already running and you execute `pcmanfm`, the running instance of PCManFM "captures it" and opens a new window?

Some programs do this, like Firefox and Nautilus.

**Comment by liloman** [comment]
It possible, I was thinking on something related to dbus/Polkit.

PD: It seems that debugging is not working with journalctl so you have to up syslog??

**Comment by netblue30** [comment]
I think PCManFM listens on a regular Unix socket. The only thing is doing is opening a new file manager, it doesn't take any commands over the socket.

**Comment by liloman** [comment]
I've been testing and I can't launch a terminal for example but I can execute /bin commands inside the namespace.

I don't know why It isn't "totally" blacklisted. :grey_question: 

Btw my bad, to see the logs from journalctl:

```bash
journalctl  SYSLOG_IDENTIFIER=firejail
```

Nice tools both indeed .

**Comment by netblue30** [comment]
I have blacklisted some terminals in /etc/firejail/disable-common.inc. These programs listen on Unix sockets and unlike PCManFM accept commands coming on the socket. This effectively allow an intruder to break out of the sandbox. You can still start a terminal using --noblacklist:
`````
$ firejail --noblacklist=/usr/bin/lxterminal lxterminal
`````

**Comment by liloman** [comment]
Even launching it from a lxterminal: 

```bash
firejail --noblacklist=/usr/bin/lxterminal lxterminal
Reading profile /usr/local/etc/firejail/generic.profile
Reading profile /usr/local/etc/firejail/disable-mgmt.inc
Reading profile /usr/local/etc/firejail/disable-secret.inc
Reading profile /usr/local/etc/firejail/disable-common.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 10033, child pid 10034

Child process initialized
/bin/bash: /bin/lxterminal: Permiso denegado

parent is shutting down, bye...
```

I saw no tests with --noblacklist. Maybe when I have some time and make some test. 

PS: It's a fresh git installation.

**Comment by netblue30** [comment]
> /bin/bash: /bin/lxterminal: Permiso denegado

Start it like this:
`````
$ firejail --noblacklist=/bin/lxterminal lxterminal
`````

Probably you are running Arch Linux. Arch is merging /bin and /usr/bin directory into a single one.

**Comment by liloman** [comment]
You're right I'm running Fedora who was the impulsor (Lennart) of this merging. :)

```bash
firejail --noblacklist=/bin/lxterminal lxterminal
Reading profile /usr/local/etc/firejail/generic.profile
Reading profile /usr/local/etc/firejail/disable-mgmt.inc
Reading profile /usr/local/etc/firejail/disable-secret.inc
Reading profile /usr/local/etc/firejail/disable-common.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 10684, child pid 10685

Child process initialized
/bin/bash: /bin/lxterminal: Permiso denegado

parent is shutting down, bye...
```
It's often a susprise how things can work differently in one distro and another. :surfer:

**Comment by netblue30** [comment]
I'll have to fix it, thanks!

**Comment by netblue30** [comment]
Fixed! Try:
`````
$ firejail lxterminal
`````

**Comment by liloman** [comment]
Working!.

Nice. :)
