### ISSUE TITLE
Firefox and Thunderbird profiles not loaded in latest Firejail version in Ubuntu

### ISSUE THREAD

**Issue by brunonova** [netblue30/firejail#285]
I'm using Ubuntu 14.04 and I just upgraded Firejail to 0.9.38.

When starting Firefox and Thunderbird with Firejail, it loaded the generic profile instead of the correct profile.

After running `firejail` with the `--debug` option, I noticed that the "command name" was `firefox.sh` instead of `firefox` (same thing for Thunderbird).
In Ubuntu, `/usr/bin/firefox` is a symlink to `/usr/lib/firefox/firefox.sh`, so the new version of Firejail is following symlinks when determining the name of the program, and thus ends up trying to load the wrong profile.

A workaround is to create the `firefox.sh.profile` and `thunderbird.sh.profile` profiles as symlinks to the originals. Other programs and other distros may also be affected.

**Comment by netblue30** [comment]
Fixed! Workaround if you don't want to update to the version in git: start the sandbox as "firefail firefox", without specifying a full path:
`````
$ firejail --debug firefox
Command name #firefox#
Found firefox profile in /etc/firejail directory
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Using the local network stack
Parent pid 5798, child pid 5799
Initializing child process

[...]

Starting "firefox" 
execvp argument 0: /bin/bash
execvp argument 1: -c
execvp argument 2: "firefox" 
Child process initialized
`````

**Comment by brunonova** [comment]
Great!
Tested and it works!

**Comment by netblue30** [comment]
You're welcome!
