### ISSUE TITLE
I can not put fish or zsh as the default shell

### ISSUE THREAD

**Issue by GittyMejorado** [netblue30/firejail#2857]
I have a clean installation of Kubuntu 18.04, where mount the boot and root on an SSD and home on an HDD, I installed firejail, it was the first thing I installed, but when I install fish and zsh, I can not put fish or zsh as a shell default, when restarting I only see the empty black screen with the $ symbol and nothing else, if in this empty screen I write fish, zsh or bash if everything appears normal but not in a new terminal just opened.
Also when I open qBittorrent it only gives me access to the Home downloads folder and to no other home folder, when I open a torrent, nothing is downloaded.
With gimp, when I have it open but I want to add another file with right click and open with gimp, open another gimp gui and do not open that file in the already opened gui.
I have tried to fix it by uncommenting gimp, ssh and qbittorrent from the file /usr/lib/firejail/firecfg.config, but with the command firejail --top the uncommented programs are still running in the sandbox.
In what way can I solve this?
Thank you

**Comment by SkewedZeppelin** [comment]
> I can not put fish or zsh as a shell default

firejail probably isn't causing that. how are you changing shell?

> qBittorrent it only gives me access to the Home downloads folder and to no other home folder

the current profile only allows downloading to ~/Downloads and other drives.
if you want to whitelist another directory in home do
```
mkdir -p ~/.config/firejail
$ echo 'whitelist ${HOME}/torrents' >> ~/.config/firejail/qbittorrent.profile
```

> open another gimp gui and do not open that file in the already opened gui

this one is annoying, adding `join-or-start` to the profile should fix it, but doesn't seem to for some reason

> from the file /usr/lib/firejail/firecfg.config

after editing that you need to run `sudo firecfg` again. you can also just remove the program symlink from `/usr/local/bin`

> firejail --top

`firejail --list` is a more forward way of showing what is firejailed

**Comment by GittyMejorado** [comment]
Thanks for the reply.
I solved the problem with qBittorrent opened the configuration file in /etc/firejail/qbittorrent.profile and added to whitelist only the folders I had created dedicated to downloads on home and worked.
Regarding Gimp now I understand that Firejail opens a different interface if it is activated from another place different from the already opened application. To add a new file in this case in Gimp, it must be loaded from the same application already opened for it to open it there
What I could not solve is to change the default shell for the terminal, I do not know that etc / firejail / aplication.profile I need to edit so that it has access to the fish or zsh user's shell configurations.

**Comment by rusty-snake** [comment]
> I change shell manually, writing fish, zsh or bash and it changes without any problem.

Editing `/etc/passwd` or what? Suggestion: use `chsh`.

> What I could not solve is to change the default shell for the terminal, I do not know that etc / firejail / aplication.profile I need to edit so that it has access to the fish or zsh user's shell configurations

Do you firejail your terminal or your shell? :confused:

**Comment by GittyMejorado** [comment]
I wrote sudo chsh -s /usr/bin/fish, I rebooted the computer and when I enter again and open a new terminal from any launcher it appears only the symbol $ without user@computer at the prompt.
I must type fish, zsh or bash in the terminal to enter in fish, zsh or bash shell.
I mean when I launch a new terminal it gives me empty without any shell

**Comment by rusty-snake** [comment]
> I mean when I launch a new terminal it gives me empty without any shell

there must be a shell running otherwise you can't enter fish or bash

Output of `echo $SHELL`?

**Comment by GittyMejorado** [comment]
With sudo chsh -s /usr/bin/fish, I rebooted the computer. When I opened a new terminal, this appears

https://imgur.com/a/uPhb8t8

I must write fish, zsh or bash so that the interface of each shell appears to me as I have it configured

**Comment by rusty-snake** [comment]
I don't think that this is firejail related. (Direct link to image without js: https://i.imgur.com/nY8W4LA.png)

**Comment by GittyMejorado** [comment]
I can be wrong but I think that if it is related, I think fish can not access the configuration files that are in home, the same happens to me when I set the zsh shell as the default

**Comment by rusty-snake** [comment]
> I think fish can not access the configuration files that are in home

@GittyMejorado if you firejail your shell or your terminal then yes, but else not.

**Comment by GittyMejorado** [comment]
Setting bash as the default shell with chsh -s /bin/bash, I rebooted the computer is no problem and when I open a new terminal bash prompt appears as I have it configured.
I think zsh and fish can not access certain folders or files to run normally by firejail. I have looked for some fish or zsh firejail .profile but they do not exist

**Comment by rusty-snake** [comment]
firejail can only prevent fish (or what ever) if it runs under firejail. As a basic condition of sandboxing, it's that you can't escape it, if it works after `fish{ENTER}` it isn't firejail.

**Comment by rusty-snake** [comment]
>  I have looked for some fish or zsh firejail .profile but they do not exist

Because it makes no sense to firejail a shell by default.

> I think zsh and fish can not access certain folders or files to run normally by firejail.

Do you firejail they or not? firejail only jails what is said to it.

**Comment by GittyMejorado** [comment]
Being bash as a shell of the system and if down to the bash file I write fish I save the file and open a new terminal, instead of appearing the shell bash I get the shell fish.
I think that firejail has imprisoned the user, to usr, to home, all together, I know it's a firejail problem but I do not know what to modify so that everything goes normal with those shells

**Comment by rusty-snake** [comment]
@GittyMejorado full output of  `firejail echo 'Hello, World!'` when out have the wrong prompt.

**Comment by GittyMejorado** [comment]
Now I have bash as default shell but I wrote fish n the bash file, so open a fish shell, without problem.
I put:
firejail echo 'Hello, World!' 
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 20548, child pid 20549
Warning: cleaning all supplementary groups
Child process initialized in 66.72 ms
Hello, World!

Parent is shutting down, bye...

**Comment by rusty-snake** [comment]
> without problem

With the right prompt?
I sayed: > when out have the wrong prompt.
No matter.
to hold it:
if it is firejail related, you will see this:
```
firejail echo 'Hello, World!'
Warning: an existing sandbox was detected. echo will run without any additional sandboxing features
Hello, World!
```

**Comment by GittyMejorado** [comment]
The result
https://imgur.com/a/zXRf8ob

**Comment by rusty-snake** [comment]
still an issue?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
