### ISSUE TITLE
Where is private-home? LOL

### ISSUE THREAD

**Issue by Anoncheg1** [netblue30/firejail#286]
IT WAS: "build a new user home in a temporary filesystem, and copy the files and directories in the list in."
**What now?**
Why did you delete it? **WTF**

**Comment by Anoncheg1** [comment]
--private --private=new_private_dir

**Comment by prsarv** [comment]
@Anoncheg1 I am facing the same problem where the private.keep or private-home shows up as an invalid command. I was wondering if you found a way to remedy the situation?

I tried --private=list-of-files-and-directories, but the changes are persistant. For now I'm using a bash script which copies the files and deletes them promptly after the session is terminated.

**Comment by netblue30** [comment]
Build a small script and copy the necessary directories in a new directory, than user --private=new_directory to start the sandbox. Firefox example:
`````
#/bin/bash
rm -fr ~/tmpfirefox
mkdir ~/tmpfirefox
cp -a ~/.mozilla ~/tmpfirefox/.
firejaile --private=~/tmpfirefox firefox
`````

**Comment by prsarv** [comment]
Sure thanks for your response! I will do just that.
