### ISSUE TITLE
profiles not found in /etc/firejail

### ISSUE THREAD

**Issue by meliaas** [netblue30/firejail#2864]
I usually run `sudo firecfg` and then tweak the files in /etc/firejail but in my new linux mint instalation, I can't find the files in this directory. Curious because in my previous install this always worked as intended and it works as well in Manjaro Linux. 

The thing is I need to tweak the files because firecfg breaks programs like firefox, chromium and spotify. I can't seem to find the files tho... there are some files created in /usr/local/bin and /usr/bin but they are just shortcuts that point to the desktop files... I can't change the actual firejail profile.

Hope someone can help, Cheers.

**Comment by rusty-snake** [comment]
> Please note: if you are running Debian, Ubuntu, Linux Mint, or another related distribution and you installed firejail from your distro's repositories, please ensure that **both** of the following were installed: `firejail` and `firejail-profiles`. A common source of issues is that firejail-profiles was not installed when installing firejail.

https://github.com/netblue30/firejail/blob/master/CONTRIBUTING.md

**Comment by meliaas** [comment]
If you can help me to check if firejail-profiles is installed, would be appreciated. About the rest:

Firejail version 0.9.52
Linux Mint 19
I used this same version of firejail before and it worked, and it works in Manjaro as well right now on the same pc.
Running --no-profile fixes the issue.
