### ISSUE TITLE
How to work with symlinks?

### ISSUE THREAD

**Issue by voidzero** [netblue30/firejail#287]
Example: My .mozilla, .config/chromium, and .cache directories are symlinks that point to a zram (compressed memory) directory, for speed purposes and to reduce disk writes. On boot and shutdown those directories are synched from/to disk. So my home dir looks like this:

<pre>
.config/chomium -> /snc/voidzero/chromium
.mozilla -> /snc/voidzero/mozilla
.cache -> /snc/voidzero/cache
</pre>

When I try to launch `firejail firefox`:

<pre>
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 8167, child pid 8168
Error: invalid whitelist path /home/voidzero/.mozilla
Error: cannot establish communication with the parent, exiting...
</pre>

What is the recommended way to work with a setup like this? I know that a workaround is to bind-mount rather than symlink, but for boot purposes this is not ideal right now.

I'd appreciate some pointers, cheers.

**Comment by netblue30** [comment]
You need both the link and the original file in your home directory. You need to mount the zram somewhere in your home directory, /home/user/snc for example.

**Comment by voidzero** [comment]
Alright thanks. Perhaps this is useful for a FAQ entry?

**Comment by netblue30** [comment]
I put it in the man page.
