### ISSUE TITLE
silence --x11=xorg when using --quiet

### ISSUE THREAD

**Issue by adrelanos** [netblue30/firejail#2876]
`firejail --whitelist=/home/user/.secbrowser/secbrowser --profile=torbrowser-launcher --x11=xorg --quiet /home/user/.secbrowser/secbrowser/Browser/start-tor-browser --allow-remote file:///usr/share/secbrowser/secbrowser.html`

```
Using authority file /tmp/.tmpXauth-Q1LLXl
authorization id is 950
Writing authority file /tmp/.tmpXauth-Q1LLXl
```

Could that be silenced please when using `--quiet`?

**Comment by glitsj16** [comment]
@adrelanos This might already be fixed in https://github.com/netblue30/firejail/commit/c3e39d7c5999f200fa0ae86900ade30236ddcaff. To test this you'll need to build firejail from git.

**Comment by netblue30** [comment]
Yes,. all is fixed on mainline.
