### ISSUE TITLE
Discord fails to load using --profile=

### ISSUE THREAD

**Issue by BobMacpherson** [netblue30/firejail#2878]
I am using firejail commit 50fc318
I have copied the /etc/firejail/discord.profile to ~/.config/firejail and named it discord-2.profile
I changed the following in the profile
```
noblacklist ${HOME}/.config/discord-2
mkdir ${HOME}/.config/discord-2
whitelist ${HOME}/.config/discord-2
```
I copied my ~/.config/discord folder to ~/.config/discord-2
When i use
`firejail --profile=~/.config/firejail/discord-2.profile discord`
It launches but after about 5 seconds the screen just turnes grey and discord never loads
Using `discord` by its self loads
Using `firejail discord` by it self loads
But when pointing it to the discord-2 profile and ~/.config/discord-2 it never loads.

**Comment by rusty-snake** [comment]
@BobMacpherson how do you say discord that it has to load the config from `${HOME}/.config/discord-2`?

**Comment by BobMacpherson** [comment]
> how do you say discord that it has to load the config from ${HOME}/.config/discord-2?

In the profile have told firejail to point to the discord-2 folder.
```
noblacklist ${HOME}/.config/discord-2
mkdir ${HOME}/.config/discord-2
whitelist ${HOME}/.config/discord-2
```
>And what's your plan? Why do you need this?

I want to run discord with multiple profiles, but i do not want to maintain 2-3 different discord versions using canary or ptb. There should be no reason i cannot use firejail and discord to load a second profile in to a sandbox and load it from there using the same discord binary

>Output from touch ${HOME}/.config/discord?

There is no output, the folder already exists.

**Comment by rusty-snake** [comment]
> In the profile have told firejail to point to the discord-2 folder.

**????????**

I think you misunderstood something and should have a look at the documentations.

**Comment by rusty-snake** [comment]
If you want to discord profiles you need `--private` or a discord build in (don't know if exists).

**Comment by BobMacpherson** [comment]
As stated in the documentation, 
https://firejail.wordpress.com/documentation-2/building-custom-profiles/
https://firejail.wordpress.com/features-3/man-firejail-profile/
Changing the profile to load a whitelisted folder, should make this folder is exposed in the sandbox

**Comment by rusty-snake** [comment]
> Changing the profile to load a whitelisted folder, should make this folder is exposed in the sandbox

Yes, but how does discord know to use `.config/discord-2` instead of `.config/discord`?

**Comment by BobMacpherson** [comment]
Per the "Building Custom Profiles"
Whitelisting ~/.config/discord-2 should bootstarap it in the sandbox.

>--private

This does not inherit any themeing present in the host.

**Comment by SkewedZeppelin** [comment]
> Whitelisting ~/.config/discord-2 should bootstarap it in the sandbox.

yes, but discord won't ever use that path - making it useless

if your goal is to run multiple instances of discord at at time then you should use --private like @rusty-snake [said](https://github.com/netblue30/firejail/issues/2878#issuecomment-516114746)

something like
`$ firejail --private=/home/$user/discord-1 /usr/bin/discord`
and
`$ firejail --private=/home/$user/discord-2 /usr/bin/discord`

**Comment by BobMacpherson** [comment]
--private does not inherit anything from the host profile. All theme and scripting is lost.
Using the exact same config as running it without --private, inherits everything given in the profile

**Comment by rusty-snake** [comment]
> --private does not inherit anything from the host profile

profile: firejail profile or discord profile?

>  All theme and scripting is lost.

 You mean GTK+ themes, ...? Yes thats right
 Or do you mean themes/scripts inside from discord?

**Comment by rusty-snake** [comment]
@BobMacpherson I'm closing here due to inactivity, please fell free to reopen if you have more questions.
