### ISSUE TITLE
Man firejail-profile to disable default profile incorrect information "--noroot" instead of correct "--noprofile"

### ISSUE THREAD

**Issue by igor2x** [netblue30/firejail#288]
Hi,
I have installed firejail_0.9.38_1_i386.deb on Ubuntu 14.04.

man firejail-profile

It looks to me that there is a bug in the following man pages text: **"To disable default profile loading, use --noroot".**

According to my knowledge to disable default profile the "--noprofile" option should be used.

Regard

**Comment by netblue30** [comment]
Fixed, thanks!
