### ISSUE TITLE
What to do when executable is already in /usr/local/bin?

### ISSUE THREAD

**Issue by fluks** [netblue30/firejail#2880]
I wanted to run riot-web in Firejail, but there is already /usr/local/bin/riot-web, which is a symbolic link to /opt/Riot/riot-web. I installed it from the riot repo. What is the best way to deal with this problem? I also compiled Sylpheed from source and its executable is in /usr/local/bin too.

firejail version 0.9.58.2
Kubuntu 19.04

**Comment by rusty-snake** [comment]
There's a whole bunch of possibilities.
1. change the .desktop file `Exec=firejail  /opt/Riot/riot-web`
2. symlinking: dir_in_PATH_before_usr_local_bin/riot-web -> /usr/bin/firejail
3. Replacing /usr/local/bin/riot-web with a shell script `#!/usr/bin/env sh\nfirejail /opt/Riot/riot-web "$@"`
4. ...

The best: IDK
The easiest: edit XXX.desktop
My favorit: a shell script in /usr/local/bin

**Comment by Vincent43** [comment]
Maybe `sudo ln -s /usr/bin/firejail /usr/local/sbin/riot-web`

**Comment by fluks** [comment]
Thanks. I choose /usr/local/sbin. It and $HOME/bin are good choices, because I don't have to change them every time riot-web is updated.

**Comment by rusty-snake** [comment]
If you copy the .desktop to $HOME/.local/share/applications you need also no changes after an update.

**Comment by rusty-snake** [comment]
@fluks I'm closing here due to the question seem answered, please fell free to reopen if you have more questions.
