### ISSUE TITLE
firefox access to gpg-agent-browser.socket

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#2891]
If I am not mistaken, the default firefox profile allows access to /etc
There is a browser specific socket file for the gpg-agent in the following path 
/etc/systemd/user/sockets.target.wants/gpg-agent-browser.socket

The gpg-agent-browser.socket allows web browsers to access the gpg-agent daemon.

Worst case, if the user unlocked their gpg key, the browser can use the connection to the agent to sign or decrypt files with the users key without a password prompt (for a few minutes, depending on the config of gpg-agent)

Not sure how to test/use this access via browser.
Can someone please verify if this indeed the case?

**Comment by rusty-snake** [comment]
> If I am not mistaken, the default firefox profile allows access to /etc

Right, but you can use `private-etc` in firefox and firefox-common.

> There is a browser specific socket file for the gpg-agent in the following path
/etc/systemd/user/sockets.target.wants/gpg-agent-browser.socket

I doesn't have this file, this systemd socket-unit and it not in the repos (using Fedora), but I found this: https://wiki.archlinux.org/index.php/GnuPG

> The `gpg-agent-browser.socket` allows web browsers to access the gpg-agent daemon.

Probably we should add `blacklist /etc/systemd/user/sockets.target.wants/gpg-agent-browser.socket` into `disable-common.inc`.

**Comment by Vincent43** [comment]
`/etc/systemd/user/sockets.target.wants/gpg-agent-browser.socket` is symlink to socket config file, not a socket itself. The socket is in `/run/user/$UID/gnupg/S.gpg-agent.browser`.
