### ISSUE TITLE
clicking url in thunderbird email message launches firefox with non-default profile

### ISSUE THREAD

**Issue by jmcclelland** [netblue30/firejail#2892]
I noticed this change in behavior after ugprading from firejail 0.9.58.2 to 0.9.60 (as I upgraded from debian buster to debian bullseye). Before upgrading to 0.9.60, clicking on an URL opened a new tab in my running Firefox. Now, it opens a new window with a new profile.

May .mailcap files specifies /home/jamie/bin/firefox (a symlink to firejail) - so both thunderbird and firefox are run through firejail by default.

When I launch thunderbird directly, without firejail, clicking on a link opens a new tab in my existing browser. But when I run thunderbird through firejail, it launches a new browser window with a different profile.

Maybe this is a new security feature? Thanks for any tips you can provide!!

jamie

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/blob/073a5aa5764d8e885a609b2ff43b49cd136056fa/etc/thunderbird.profile#L17-L22

**Comment by jmcclelland** [comment]
Perfect, thank you!

**Comment by ericschdt** [comment]
As Dino has the same issues, I tried the same solution here, i.e. I added 
```
noblacklist ${HOME}/.cache/mozilla 
noblacklist ${HOME}/.mozilla 
whitelist ${HOME}/.cache/mozilla/firefox 
whitelist ${HOME}/.mozilla 
```
to `dino.profile`, but now I only see the Firefox Icon at the mouse cursor and after a few seconds it vanishes and that's it. 

Then I tried to add
`include firefox-common.profile` and `private-bin firefox` as well, but with no improvements overall. 

Any idea?
