### ISSUE TITLE
Using aria2c with firejail makes it fail to download anything:  -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MystesofEternity** [netblue30/firejail#2894]
firejail --seccomp aria2c -x 16 -k 1M https://nchc.dl.sourceforge.net/project/zorin-os/12/Zorin-OS-12.4-Lite-64.iso

08/08 08:37:46 [ERROR] CUID#7 - Download aborted. URI=https://nchc.dl.sourceforge.net/project/zorin-os/12/Zorin-OS-12.4-Lite-64.iso
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://nchc.dl.sourceforge.net/project/zorin-os/12/Zorin-OS-12.4-Lite-64.iso
  -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

Using fedora-30 for this and an aria2c I personally built myself from source code in the middle of June 2019

Things I've tried:
- noblacklist /etc/ssl/certs
- whitelist /etc/ssl/certs
- noblacklist /etc
- whitelist /etc
- noblacklist /etc/ssl
- whitelist /etc/ssl
=All of the above were lines I added to the aria2c.profile. I added them 2 by 2, commenting out the two lines that gave me a fail. Sadly all of it failed.=

**Comment by SkewedZeppelin** [comment]
those won't do anything for /etc

+ there is a `private-etc` line, try commenting it

**Comment by MystesofEternity** [comment]
Thanks! I'll try it out next week as I use it for work to download big resources for coding/developing apps

**Comment by MystesofEternity** [comment]
Thank you very much! It worked!
