### ISSUE TITLE
Command "firejail --seccomp skypeforlinux" used to work until skype's rpm update to 8.51.0.72-1.x86_64.rpm

### ISSUE THREAD

**Issue by MystesofEternity** [netblue30/firejail#2914]
Hi, I noticed that I can no longer run skypeforlinux in firejail after update to 8.51.0.72-1.x86_64.rpm
It works properly on 8.50.0.38-1.x86_64.rpm
https://repo.skype.com/rpm/stable/

**Comment by smitsohu** [comment]
Thank you @MystesofEternity for reporting this issue. There is a similar report already in #2912, let's keep track there.
