### ISSUE TITLE
private does not see my new folder

### ISSUE THREAD

**Issue by jisabe** [netblue30/firejail#2916]
Hi,

```bash
newHomeDir=/home/test99

sudo mkdir $newHomeDir

sudo chmod -R 777 $newHomeDir

sudo chown $USERNAME $newHomeDir

firejail --noprofile --read-write=$newHomeDir --read-only=/my_custom_dir --private=$newHomeDir opera
```

I got this error:

`Error mount bind: fs_home.c:239 fs_private_homedir: No such file or directory`

Thanks for your help

**Comment by jisabe** [comment]
I found it. With below change it worked:

newHomeDir=/home/myusername/test99

but why? Is there any way to use /home/$newHome ?

**Comment by rusty-snake** [comment]
@jsabe you need `--allusers`

> **--allusers**
 All directories under /home  are  visible  inside  the  sandbox.  By
default, only current user home directory is visible.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
