### ISSUE TITLE
Standalone firejail

### ISSUE THREAD

**Issue by jisabe** [netblue30/firejail#2917]
Is there any way to use firejail without install on system?

Example:
/home/my_user/firejail_stanadalone/firejail --noprofile firefox

Thank you

**Comment by FOSSONLY** [comment]
Anything is possible, but the meaning of it is not revealed to me. And in view of the fact that Firejail is ultimately supposed to increase security, it's almost criminal negligence to want to start something like this under /home. Here everything would be arbitrarily writable, and it should be very clear that Firejail is a SUID binary. You should set the file permissions accordingly to only allow root write permissions.

**Comment by rotaficat** [comment]
@FOSSONLY I think the command of @jisabe is only an exmaple. It can be chnage as:

`/firejail_stanadalone/firejail --noprofile firefox`

Many apps have official standalone versions. So why not for firejail...

I extract the deb package, and I execute the firejail binary but I get some errors. I think we problem is about dependencies which should be included inside standalone version (if a developer will package/create it).

**Comment by rusty-snake** [comment]
`./configure --prefix=/foo/bar` is possible. @Fred-Barclay actually look if it is possible to provide a appimage version of firejail #2849.

**Comment by rusty-snake** [comment]
```
./configure --prefix=/opt/firejail
make
sudo make install
sudo ln -s /opt/firejail/bin/firejail /usr/bin/firejail
```

Works

**Comment by rusty-snake** [comment]
@jisabe 
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
