### ISSUE TITLE
firemon --nowrap name

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#2922]
> --nowrap
Enable line wrapping in terminals. By default the lines are trimmed.

Why a option that _enable_ wrapping is called _no_ wrap?

**Comment by chiraag-nataraj** [comment]
lol okay, I'll fix this in a day or so...

**Comment by rusty-snake** [comment]
@chiraag-nataraj ping

**Comment by reinerh** [comment]
@chiraag-nataraj another gentle ping. do you still intend to work on this?

**Comment by netblue30** [comment]
Fixed!

**Comment by netblue30** [comment]
Commit: https://github.com/netblue30/firejail/commit/78e519f5108d327afb3341439fee9a49491534fe
