### ISSUE TITLE
include on the commandline

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#2923]
for debuging it would be usefull to have the opportunity to use `include` on the command line.
Example:

```
firejail --noprofile --include=disable-programs --include=disable-common bash
firejail --profile=firefox --include=$HOME/temp-firefox.local
```

**Comment by smitsohu** [comment]
I think you can use multiple `--profile` options, like

`firejail --profile=firefox --profile=$HOME/temp-firefox.local`

I couldn't find this documented though.

**Comment by rusty-snake** [comment]
Except of that I need absolut paths for *.inc it works, don't no why my last try with multible `--profile` has failed :confused: .

Should we close?

**Comment by smitsohu** [comment]
Intuitively most people probably first try `--include` on the command line. I recall myself trying this as well....

Parsing `--include` as `--profile` would be a trivial change. Maybe we could try to harmonize their behavior, if this is wanted. Are there any reasons why they behave differently with regards to profile extensions?

**Comment by rusty-snake** [comment]
Consider this:
Now: `firejail --profile=2048-qt --profile=/etc/firejail/disable-xdg.inc 2048-qt`
With `--include`: `firejail --include=disable-xdg.inc 2048-qt`
