### ISSUE TITLE
Can Firejail put a sandbox around TOR or can it help keep me secure online some other way?

### ISSUE THREAD

**Issue by JackMacack** [netblue30/firejail#2932]
Trying to secure my computer and my internet traffic in Ubuntu and have installed TOR and Firejail through the OS and can't find an option for TOR in Network in Firejail.  Any idea how to do this or and alternate way?  Thanks.

**Comment by rusty-snake** [comment]
You mean the TOR daemon and not the tor-browser, right.
There is a [tor profile](https://github.com/netblue30/firejail/blob/master/etc/tor.profile) with a usage section inside.

> or can it help keep me secure online some other way?

run `sudo firecfg` to firejail a lot of programs by default. Additional you can look in the profiles and the manpages to harden some profiles.

**Comment by rusty-snake** [comment]
TOR (the daemon) != tor-browser != TOR (the network)

> It's the TOR browser that is installed through Ubuntu Software service.

IDK how and where it is installed, so I can't help here.

>  I also downloaded the standalone TOR browser from the tor website, but I don't think I can't use that with firejail

Access to $HOME possible: https://github.com/netblue30/firejail/issues/2429#issuecomment-465545751
No access to $HOME possible: https://github.com/netblue30/firejail/wiki/Sandboxing-Binary-Software#tor-browser-home-install
My setup (tighter that firejail's default tor-browser profile): https://github.com/rusty-snake/firejailed-tor-browser

Additional:
X11 sandbox: https://firejail.wordpress.com/documentation-2/x11-guide/
chroot: https://firejail.wordpress.com/documentation-2/basic-usage/#chroot

> so I can prevent any access to the the rest of my computer files and hardware profile as well.

TOR + VM: Whonix
TOR + VM: TAILS
TOR + Live System: TAILS (Hardware access obviously possible)

**Comment by rusty-snake** [comment]
@JackMacack 
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
