### ISSUE TITLE
PPA for ubuntu/debian packages

### ISSUE THREAD

**Issue by fbis251** [netblue30/firejail#294]
Hi,

It's great that your project provides packages for many platforms, but having an easy way to automatically update to new releases through a PPA would be great.

Thank you for your hard work.

**Comment by reinerh** [comment]
It is available in Debian/Ubuntu repositories. What advantage would a PPA have?
Are the updates not fast enough?

**Comment by fbis251** [comment]
The current version for 15.10 is 0.9.28 at the time I wrote this:
http://packages.ubuntu.com/source/wily/firejail

According to the project's tags it was released before September 2015 (around 5 months ago)
https://github.com/netblue30/firejail/releases

It would be nice to try out features like --whitelist which was not supported by the version available on the official ubuntu repositories through an optional PPA. Although I can probably keep up with the releases of .deb packages on sourceforge, having a PPA allows users to use automatic updates

**Comment by reinerh** [comment]
Ah, you mean for already released Ubuntu versions.
For the current "unstable" version 0.9.38 is available:
 https://launchpad.net/ubuntu/+source/firejail
I think it should be possible to install this in 15.10.

**Comment by fbis251** [comment]
Although 15.10 is the latest "stable" version and I was wondering if there would be any way of having automatic updates through apt?

Would I be able to edit an apt sources.list file to install the xenial package in wily?

**Comment by reinerh** [comment]
I'm not that familiar with Ubuntu, but they also support apt pinning:
https://help.ubuntu.com/community/PinningHowto

**Comment by genodeftest** [comment]
apt pinning could work, but it won't work for long since libc and gcc get updates, so you probably shouldn't rely on that. If you want updates to old releases¹ you probably need a custom PPA or just use a distribution with less strict update policies.

¹: In Ubuntu terms every release is "old" a few months before it is being released because its packaging policy doesn't allow updates from that time on.

**Comment by reinerh** [comment]
If you are interested, I created a Firejail PPA for wily here:
https://launchpad.net/~deki/+archive/ubuntu/firejail

**Comment by reinerh** [comment]
@fbis251 You could also request a backport: https://wiki.ubuntu.com/UbuntuBackports

**Comment by fbis251** [comment]
@reinerh The PPA is working great! Thank you.

**Comment by netblue30** [comment]
Thanks @reinerh

**Comment by qazip** [comment]
@reinerh, have you stopped updating the ppa? Latest version of firejail was released almost 20 days ago. The ppa has still a version released 6 months ago.
