### ISSUE TITLE
gnome-schedule is broken

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#2941]
After recent changes to the `gnome-schedule` profile this app is now broken:

```
$ firejail /usr/bin/gnome-schedule
Reading profile /etc/firejail/gnome-schedule.profile
Reading profile /etc/firejail/globals.local
Reading profile /etc/firejail/allow-python2.inc
Reading profile /etc/firejail/allow-python3.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-common.local
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-passwdmgr.local
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-programs.local
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/disable-xdg.local
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 14462, child pid 14473

Error: invalid file type, /etc/at.deny.
Error: proc 14462 cannot sync with peer: unexpected EOF
Peer 14473 unexpectedly exited with status 1
```

I can only make it work by adding the following to `gnome-schedule.local`:

```
noblacklist /etc/at.allow
noblacklist /etc/at.deny
ignore private-etc
private-etc fonts,ld.so.preload,pam.d
```
Adding noblacklist /etc/at.{allow,deny} was changed in https://github.com/netblue30/firejail/pull/2886 (see https://github.com/netblue30/firejail/commit/2e9a23d30cbcd6357a061f208492382dda215e17#diff-3e7cec4e68d91d1d0d349532367d3659). Unsure what's the best way to fix this...

**Comment by rusty-snake** [comment]
@glitsj16 your right, probably it's the best to drop `private-etc`. But why do you need the `noblacklist`s, on my system `firejail --ignore=private-etc --profile=gnome-schedule cat /etc/at.deny` works?

```
ignore private-etc
private-etc …
```
Makes no sens, or?

```
noblacklist /etc/at.allow
noblacklist /etc/at.deny
```
Where we blacklist?

```
Error: invalid file type, /etc/shadow.
Error: proc 4600 cannot sync with peer: unexpected EOF
Peer 4601 unexpectedly exited with status 1
```
I get this error if `private-etc` contains files that I can't read.

**Comment by glitsj16** [comment]
@rusty-snake 

> But why do you need the noblacklists... ?

Turned out that on my system /etc/at.deny had 0640 permissions. After changing that to 0644 all that is needed to fix the profile is `ignore private-etc`. Thanks for making me look further than I did before :+1: .
