### ISSUE TITLE
firejail - Ubuntu 19.10 snap chromium incompatibility

### ISSUE THREAD

**Issue by mjhkqprt51** [netblue30/firejail#2943]
This Ubuntu version is still under development. Firejail package version is: 0.9.60-2: amd64.
The problem is that Ubuntu maintainers replaced the deb based chromium packaging to a snap based one which doesn't work well with firejail.

$ chromium-browser
Reading profile /etc/firejail/chromium-browser.profile
Reading profile /etc/firejail/chromium.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 32546, child pid 32547
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: Cannot confine the application using AppArmor.
Maybe firejail-default AppArmor profile is not loaded into the kernel.
As root, run "aa-enforce firejail-default" to load it.
Child process initialized in 133.61 ms
mv: '/home/mosomaci/.config/mimeapps.list.new'-t can not be moved here: '/home/mosomaci/.config/mimeapps.list': device or resource is busy
mv: '/home/mosomaci/.config/mimeapps.list.new'-t can not be moved here: '/home/mosomaci/.config/mimeapps.list': device or resource is busy

(process:50): dconf-CRITICAL **: 16:38:45.479: unable to create directory '/run/user/1001/dconf': Access denied.  dconf will not work properly.

(process:50): dconf-CRITICAL **: 16:38:45.479: unable to create directory '/run/user/1001/dconf': Access denied.  dconf will not work properly.
There is no „com.canonical.Unity.Launcher” scheme
internal error, please report: running "chromium" failed: cannot find installed snap "chromium" at revision 849: missing file /var/lib/snapd/snaps/chromium_849.snap

Parent is shutting down, bye...

Most of the texts were translate by me to English

Enforcing the apparmor firejail profile doesn't help.

**Comment by rusty-snake** [comment]
Hi,

Firejail doesn't support snap, it was droped in version 0.9.60. See #2397 for more informations.

**Comment by mjhkqprt51** [comment]
Hi, thanks, no problem. BTW thanks for firejail, it is a great security tool.
