### ISSUE TITLE
Syncthing

### ISSUE THREAD

**Issue by Tanath** [netblue30/firejail#295]
`$ firejail syncthing-gtk`
`Reading profile /etc/firejail/syncthing-gtk.profile`
`Reading profile /etc/firejail/disable-mgmt.inc`
`Reading profile /etc/firejail/disable-secret.inc`
`Error: cannot open profile file /etc/firejail/disable-common.inc syncthing`

`$ file /etc/firejail/disable-common.inc`
`/etc/firejail/disable-common.inc: ASCII text`

What's going on here, and how do I troubleshoot it?

**Comment by genodeftest** [comment]
Do you have permissions to open this file? What's the output of `ls -Al /etc/firejail/disable-common.inc`?

**Comment by Tanath** [comment]
Yes, I've looked at it in vim.
`-rw-r--r-- 1 root root 3659 Feb 13 21:50 /etc/firejail/disable-common.inc`

**Comment by netblue30** [comment]
I think you run into some feature I deprecated a few releases back. Pint here your /etc/firejail/syncthing-gtk.profile, I'll need to modify it.

**Comment by Tanath** [comment]
`# syncthing-gtk profile  

include /etc/firejail/disable-mgmt.inc  

include /etc/firejail/disable-secret.inc  

include /etc/firejail/disable-common.inc syncthing  

caps  

seccomp  

noroot`

**Comment by netblue30** [comment]
Try this:
`````
# syncthing-gtk profile
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc
caps
seccomp
noroot
`````

**Comment by Tanath** [comment]
Runs now, but isn't that basically just using generic profile then?

**Comment by netblue30** [comment]
Yes, you don't really need a special profile, the default one will do it.
