### ISSUE TITLE
Having some problems regarding sandboxing

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#2950]
Don't know how should I put it? But this is really nagging me, all the time. I do have enabled desktop integration for firejail. But, recently I noticed some apps are not being firejailed under certain circumstances. Such as Kate & dragonplayer get firejailed when run from menu but when I open video or text files, those programs don't get firejailed. 

Specs- 
Manjaro(KDE), kernel- 5.2.11
plasma ver: 5.16.4
kde framework ver: 5.61.0
Qt ver: 5.13.0

**Comment by rusty-snake** [comment]
@Neo00001 how do you see that they aren't firejailed?
***
dolphin is handelt by firecfg, so if you start dragon from dolphin it runs in the dolphin sandbox. What shows `firejail --tree` after starting from filemanager?

**Comment by Neo00001** [comment]
ok... I was checking firejail --list, so there wasn't anything in it. Now it makes sense.
