### ISSUE TITLE
Steam not running

### ISSUE THREAD

**Issue by StarPicard** [netblue30/firejail#2951]
firejail version 0.9.60 on Archlinux

When calling the following commands steam is not starting up:
```
firejail --profile=/etc/firejail/steam.profile steam-runtime
firejail steam
```
The error message is:
```
/usr/lib/steam/steam: Zeile 23:    29 Ungültiger Betriebssystemaufruf        (Speicherabzug geschrieben) pulseaudio --check &> /dev/null
/usr/lib/steam/steam: <HOME>/.local/share/Steam/steam.sh: /usr/bin/env: Defekter Interpreter: Keine Berechtigung
/usr/lib/steam/steam: Zeile 199: <HOME>/.local/share/Steam/steam.sh: Erfolg
```
When running `firejail --noprofile steam` it is working.

**Comment by rusty-snake** [comment]
Related to #2860?
Try with `--ignore=seccomp`.

**Comment by StarPicard** [comment]
No, same error. But got this new error message:
```
Error: cannot read UID_MIN and/or GID_MIN from /etc/login.defs, using 1000 by default
Error: cannot read UID_MIN and/or GID_MIN from /etc/login.defs, using 1000 by default
Warning: an existing sandbox was detected. /usr/bin/steam will run without any additional sandboxing features
```
The other two warnings are there too.

**Comment by rusty-snake** [comment]
Thats a other issue: #2877; add `--ignore=private-etc`.
To exclude #2765: add `--noblacklist=/usr/sbin`
Has you changes anything on the steam.profile?
Is there anything in the journal?

**Comment by rusty-snake** [comment]
@StarPicard 
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.

**Comment by StarPicard** [comment]
`ignore apparmor` in `steam.local` also solved this
