### ISSUE TITLE
Can access to localhost be allowed with net none

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#2954]
Can I allow specific app to access localhost while net none is enabled?

**Comment by rusty-snake** [comment]
IDK how. Alternative you can omit `net none` and set `protocol unix`.

**Comment by chiraag-nataraj** [comment]
See #108 for more info.

**Comment by rusty-snake** [comment]
@Neo00001 
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
