### ISSUE TITLE
Firejail sandbox can't access vulkan

### ISSUE THREAD

**Issue by trialism** [netblue30/firejail#2959]
I used 0.9.60:

`firejail --private=~/apps/Steam bash` and then ran `vulkaninfo`:

```
/build/vulkan-tools/src/Vulkan-Tools-1.1.121/vulkaninfo/vulkaninfo.c:1556: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by rusty-snake** [comment]
I cannot reproduce this.

`firejail vulkaninfo` works, even with `--private` and `bash` which shouldn't make any difference.

But with `firejail --no3d vulkaninfo` it doesnot work (as expected). So where do you set `no3d`?

**Comment by trialism** [comment]
@rusty-snake I'm on manjaro, I don't have any global setting and it doesn't work for me with `firejail vulkaninfo` either.

**Comment by rusty-snake** [comment]
Does it work with `firejail --noprofile vulkaninfo`?

**Comment by trialism** [comment]
It works with --noprofile, probably default.profile was the issue. Thanks!
