### ISSUE TITLE
firejail should follow symlinks for private-etc?

### ISSUE THREAD

**Issue by adrelanos** [netblue30/firejail#2966]
Had a difficult to debug issue with SecBrowser and firejail. (Using torbrowser-launcher profile since SecBrowser is a derivative of Tor Browser.)

This line in torbrowser-launcher was the cause:

> private-etc fonts,hostname,hosts,resolv.conf,pki,ssl,ca-certificates,crypto-policies,alsa,asound.conf,pulse,machine-id,ld.so.cache

/etc/resolv.conf was a symlink to /etc/resolv.conf.kicksecure

ls -la /etc/resolv.conf*
lrwxrwxrwx 1 root root  22 Sep 15 13:25 /etc/resolv.conf -> resolv.conf.kicksecure
-rw-r--r-- 1 root root 311 Sep 16 06:46 /etc/resolv.conf.kicksecure
-rw-rw-r-- 1 root root   0 Sep 15 13:24 /etc/resolv.conf.kicksecure-orig

Similar to `resolvconf` which also uses symlinks.

Appending `,resolv.conf.kicksecure` to that line fixed the issue.

Therefore DNS was broken.

Therefore would ti be good if firejail would follow symlinks?

**Comment by netblue30** [comment]
I'll add support for it. The requirement would be file linked should be owned by root and have the same attributes.

**Comment by adrelanos** [comment]
That sounds good!

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/blob/00cb236addce37b13ed7d30093c8d47fba70e787/RELNOTES#L56
Fixed?

**Comment by netblue30** [comment]
Yes, it was fixed. I forgot to close it.
