### ISSUE TITLE
Inkscape cannot export GIMP .xcf files

### ISSUE THREAD

**Issue by kmotoko** [netblue30/firejail#2967]
+ **Problem:** With the Inkscape profile, when you try to save as `GIMP .xcf File`, the following is returned from Inkscape:
```
Gimp must be installed and set in your path variable.
Traceback (most recent call last):
  File "gimp_xcf.py", line 284, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "gimp_xcf.py", line 253, in effect
    raise GimpXCFGimpNotInstalled
__main__.GimpXCFGimpNotInstalled
``` 

+ **Solution:** Add the following to the Inkscape profile before the `include disable-programs.inc` rule,
```
# Exporting GIMP .xcf requires:
noblacklist ${HOME}/.config/GIMP
noblacklist ${HOME}/.gimp*
```

+ **System Info:**
  + Firejail version: 0.9.58.2
  + Linux version: Debian 10, Linux kernel 4.19.0-6-amd64

**Note 1:** The mentioned solution rule does not exist in the latest Firejail version as well.
**Note 2:** In Firejail v0.9.58, the Inkscape profile did not have `noblacklist` rules for `Python interpreters`, which causes lots of problems. I already added the following to `inkscape.local`:
```
# Enable Python interpreters for Inkscape

# Python 2
noblacklist ${PATH}/python2*
noblacklist /usr/include/python2*
noblacklist /usr/lib/python2*
noblacklist /usr/local/lib/python2*
noblacklist /usr/share/python2*

# Python 3
noblacklist ${PATH}/python3*
noblacklist /usr/include/python3*
noblacklist /usr/lib/python3*
noblacklist /usr/local/lib/python3*
noblacklist /usr/share/python3*

```

**Comment by rusty-snake** [comment]
Good catch, +1.
IMHO we should bring this in.  @kmotoko only allowing `${HOME}/.gimp*` didn't work?
Works it with
```
noblacklist ${HOME}/.config/GIMP
noblacklist ${HOME}/.gimp*
read-only ${HOME}/.config/GIMP
read-only ${HOME}/.gimp*
```

**Comment by kmotoko** [comment]
@rusty-snake I get the same error when only `${HOME}/.gimp*` is allowed.

**Comment by netblue30** [comment]
@rusty-snake, put it in. We are already doing something similar with Thunderbird + Firefox.
