### ISSUE TITLE
ping broken

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#2970]
Moved from #2969.
```
$ ping -c1 github.com
# Works (without firejail)
$ firejail ping -c1 github.com
ping: socket: Die Operation ist nicht erlaubt
```

firejail: lastet git.

**Comment by rusty-snake** [comment]
Fix: `force-nonewprivs no` in firejail.config.

@blinux45 can you confirm?

**Comment by blinux45** [comment]
Uncommenting `force-nonewprivs no` in /etc/firejail/firejail.config did not resolve the ping issue.

**Comment by blinux45** [comment]
I would like to clarify that for me ping worked within firejail until I used "private-bin ping,....".

**Comment by blinux45** [comment]
> As @smitsohu say /bin is mounted `nosuid`.
To recap:
Without private-bin, ping works but when private-bin is enabled it doesn't.
Is the mounting of /bin different in both cases? Something else seems to be going on.
Also when ping is copied to /home/myuser/firejail, it doesn't work under firejail.
Outside firejail it works fine.
Is this a mounting problem as well?

**Comment by smitsohu** [comment]
@blinux45 
> Without private-bin, ping works but when private-bin is enabled it doesn't.
Is the mounting of /bin different in both cases?

Yes, without `private-bin` /bin is read-only, but not nosuid.

>  Also when ping is copied to /home/myuser/firejail, it doesn't work under firejail.

Did you try with `--noprofile`? The default profile will prevent any raising of privileges.

**Comment by blinux45** [comment]
To recap, there seems no way to get /bin/ping to work when private-bin is enabled even though ping is explicitly requested.
As in: "--private-bin ping"
Is there an absolute requirement for nosuid to be applied simultaneously with private-bin?
Could nosuid be applied independently (for example nosuid=/bin)?
Enabling/disabling specific commands within /bin seems a separate issue from nosuid.
This is breaking ping.


Regarding /home/myuser/firejail/ping, I use a custom profile --profile=myprofile.
The default profile shouldn't be used in this case. Or is it?
I don't see anything in the custom profile that would block ping from running in /home/myuser/firejail/ping.
In my test case scenario, I invoke a bash shell through firejail (using a custom profile).
if I call ping from within this shell, would the ping profile be used? I would assume a no answer, but it is better to be sure.

**Comment by Fred-Barclay** [comment]
Does `--private-bin sh,bash,ping` work for you? It's working for me on Arch.

Of course I'm not sure that allowing shell access within private-bin defeats the whole purpose of private-bin... we have to do it sometimes for profiles (it seems especially on Arch this is needed) but I suspect this is a less-than-ideal scenario.

**Comment by topimiettinen** [comment]
The problem with allowing setuid in general is that firejail also lets the unprivileged user to manipulate the file system and capabilities, and it could be possible use that to trick the setuid program to leak elevated privileges if there was no protection. It's not possible for firejail to know which changes to file system or capabilities is safe for a specific setuid program or to even know all possible setuid programs.

**Comment by Vincent43** [comment]
@topimiettinen as I understand this discussion, `nosuid` is only used for `private-bin` option so problem with setuid bins is only mitigated in this specific case.

**Comment by rusty-snake** [comment]
Closing here. Future discussion about `nosuid`+`private-bin` in #2969.
