### ISSUE TITLE
meld.profile missing access to dconf

### ISSUE THREAD

**Issue by felixwiemuth** [netblue30/firejail#2974]
Meld uses dconf to store its settings. I had to add
`noblacklist ${HOME}/.config/dconf` to `meld.local` so that settings can be applied and persisted.

**Comment by rusty-snake** [comment]
For my it's working without that fix. Normaly dconf is accessed over dbus.

which firejail version and distro are you on?

firejail: git, OS: Fedora 30.
meld.local:
```
ignore private-bin
ignore private-tmp

include whitelist-var-common.inc

net none
protocol unix
```

**Comment by felixwiemuth** [comment]
Arch Linux, firejail 0.9.60.

I guessed that dbus could be a problem as well, is it using /tmp to communicate? Because then one actually would nede the `ignore private-tmp`.

However, now it suddenly works even without additions in `meld.local`, even though before this change (`noblacklist ${HOME}/.config/dconf`) made it work...

**Comment by rusty-snake** [comment]
BTW: `grep "^blacklist \${HOME}/.config/dconf" /etc/firejail/* `, dconf is never blacklisted.

**Comment by Vincent43** [comment]
@felixwiemuth modern dbus is usually using `/run/user/$UID/bus` to communicate

**Comment by felixwiemuth** [comment]
Thanks for the comments, probably it is difficult to identify what the actual issue was here.

Some additional observations:
- Same issue in a `firejail --private` sandbox (this suggests that it actually could have been some sandboxing issue)
- When deleting `~/.config/dconf/user` the file is recreated when starting meld and changing settings

If there are no more ideas for now I guess this can be closed.
