### ISSUE TITLE
Opensuse Tumbleweed firejail Error: cannot create /run/firejail/profile/12562

### ISSUE THREAD

**Issue by bobafetthotmail** [netblue30/firejail#2975]
I just installed firejail (from the repositories) on OpenSUSE Tumbleweed
```
firejail mplayer
Error: cannot create /run/firejail/profile/12562
```
And I get this with any other application.

**Comment by Vincent43** [comment]
Please post output of `ls -al /usr/bin/firejail`.

**Comment by bobafetthotmail** [comment]
-rwxr-x--- 1 alby users 376552  9 lug 14.09 /usr/bin/firejail

**Comment by Vincent43** [comment]
So it seems missing suid bit on binary, please try `sudo chmod u+s /usr/bin/firejail`.

**Comment by bobafetthotmail** [comment]
Does not seem to set it.

I removed the package and installed again, and now it's set as root and firejail group, but I can't set suid bit.

`-rwsr-x--- 1 root firejail 376552  9 lug 14.09 /usr/bin/firejail`

now it fails with
```
firejail filezilla
bash: /usr/bin/firejail: Permission denied
```
while if run as root it kinda works (starts up but then errors out claiming DISPLAY is not set properly.

My user "alby" is not part of firejail group though.

**Comment by bobafetthotmail** [comment]
Hm, added my user to firejail group, logged out, logged in, and now it's working.

So it seems the installation does not add me to the user group.

**Comment by Vincent43** [comment]
Yes, opensuse requires users to manually add themselves to firejail group in order to use it, this is intentional and requirement to include firejail i their repos, see https://bugzilla.suse.com/show_bug.cgi?id=1059013
