### ISSUE TITLE
migrate from wordpress to hugo

### ISSUE THREAD

**Issue by KonoromiHimaries** [netblue30/firejail#2976]
use wordpress is very risk and hugo is the better alternative
```
https://gohugo.io/tools/migrations/#wordpress
```

suggested motive
```
https://hugo-architect-theme-demo.netlify.com/
```

**Comment by rusty-snake** [comment]
There is also the idea to migrate to GH-Pages (#2729 / previously: #2713).

**Comment by rusty-snake** [comment]
Since the main reason to move to GH-Pages is the easier maintenance. And hugo ha AFAIK the same problem, I'm closing this for now.
