### ISSUE TITLE
firejail --build=FILE output

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#2979]
For #2972 I often use `--build=FILE` and I noticed that there is often in long outputs something like: `=== tracelib init() [22`.
Example:
```
whitelist /usr/share/=== tracelib init() [22
private-etc foo,host=== tracelib init() [16,bar
```
Only point in source code where this string is:
https://github.com/netblue30/firejail/blob/b9888e6a388b7d2c17f0aa75b2ef5205b4b90720/src/libtrace/libtrace.c#L102

**Comment by netblue30** [comment]
I took it out, just some debug code.

https://github.com/netblue30/firejail/commit/ee5ab63cfb1b4e38db4bc83bd51678fa0f25284c
