### ISSUE TITLE
[spotify] When never run without being firejailed, “remember me” doesn't work (directories under $HOME on whitelist cannot be created when not existent)

### ISSUE THREAD

**Issue by blipp** [netblue30/firejail#298]
The Spotify profile includes the following whitelist entries:

```
whitelist ${HOME}/.config/spotify
whitelist ${HOME}/.local/share/spotify
whitelist ${HOME}/.cache/spotify
```
The first for example is needed to save user credentials when using the “remember me” function. However, if Spotify was never started without being firejailed, those directories don't exist and wont/can't be created. As a result, Spotify can't remember my user (and probably other stuff under the hood because of the other two directories).

Workaround: I created those directories manually. Now “remember me” works.

Any ideas how to solve this in general? (I would like to avoid “run it once without Firejail”, because of security reasons)

**Comment by blipp** [comment]
Maybe something like, just as a quick idea, without knowing the internals good enough: if a directory is whitelisted, the process should be allowed to create it persistently?

**Comment by netblue30** [comment]
I'll bring in a new command (mkdir) in profile files that will create the necessary directories.

**Comment by blipp** [comment]
Thanks!

**Comment by netblue30** [comment]
Fixed! I've also included mkdir in all whitelisting profiles.
