### ISSUE TITLE
k3b needs access to /usr/bin/cdrecord

### ISSUE THREAD

**Issue by bobafetthotmail** [netblue30/firejail#2989]
and if I try whitelisting this path in k3b.inc I get "invalid whitelist path".
Also if I add a noblacklist line with same path before the whitelist line

```
k3b
Reading profile /etc/firejail/k3b.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 6466, child pid 6467
Error: invalid whitelist path /usr/bin/cdrecord
Error: proc 6466 cannot sync with peer: unexpected EOF
Peer 6467 unexpectedly exited with status 1
```

**Comment by Vincent43** [comment]
For `/usr/bin/` paths you don't use whitelist but `private-bin` option however [k3b profile](https://github.com/netblue30/firejail/blob/master/etc/k3b.profile) doesn't restrict acces to /usr/bin so the problem is somewhere else. IIRC `cdrecord` may be installed as setuid binary so lack of privileges inside sandbox may be the problem.

**Comment by bobafetthotmail** [comment]
cdrecord does not seem to have setuid set

```
sudo ls -l /usr/bin/cdrecord
[sudo] password for root: 
-rwxr-xr-x 1 root root 400848 24 ago 14.00 /usr/bin/cdrecord
```

**Comment by rusty-snake** [comment]
Maybe capabilities. Can you try `firejail --profile=k3b bash` and then try if cdrecord can be executed.

**Comment by bobafetthotmail** [comment]
No it cannot be executed. I show the `ls -l` too here

```
alby@openSUSE-xeon:~> firejail --profile=k3b bash 
Reading profile /etc/firejail/k3b.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 28668, child pid 28669
Blacklist violations are logged to syslog
Warning: cleaning all supplementary groups
Child process initialized in 146.10 ms
alby@openSUSE-xeon:~> cdrecord
bash: /usr/bin/cdrecord: Operation not permitted
alby@openSUSE-xeon:~> ls -l /usr/bin/cdrecord 
-rwxr-xr-x 1 nobody nogroup 400848 24 ago 14.00 /usr/bin/cdrecord
```

**Comment by Vincent43** [comment]
Could you post `getcap /usr/bin/cdrecord` output?

**Comment by bobafetthotmail** [comment]
```
sudo getcap /usr/bin/cdrecord
[sudo] password for root: 
/usr/bin/cdrecord = cap_ipc_lock,cap_sys_rawio,cap_sys_nice,cap_sys_resource+ep
```

**Comment by rusty-snake** [comment]
Try replacing `caps.drop all` with
```
caps.keep ipc_lock,sys_rawio,sys_nice,sys_resource
```

possibly the list can be shortened.

**Comment by rusty-snake** [comment]
@bobafetthotmail 
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.

**Comment by Vincent43** [comment]
@rusty-snake I think even without feedback we should try to fix k3b profile, at least with rule you proposed.

**Comment by smitsohu** [comment]
Unfortunately I currently cannot test these things, but I wouldn't be surprised if Brasero had similar problem.

**Comment by rusty-snake** [comment]
Brasero works with firejail master.

**Comment by Vincent43** [comment]
As there is no feedback from reporter let's consider this one fixed and re-open when someone found otherwise.

**Comment by Neo00001** [comment]
`caps.keep chown,dac_override,ipc_lock,net_bind_service,sys_admin,sys_nice,sys_rawio,sys_resource` -tested on `Arch Linux`.

`net_bind_service` is odd one for me. I don't know why this one is needed.
