### ISSUE TITLE
zathura: printing not possible

### ISSUE THREAD

**Issue by nblock** [netblue30/firejail#2990]
Running with `firejail zathura <document>` and invoking `:print` fires up the print dialog and displays available printers. Selecting one of the available printers updates the status column with "Getting printer information failed". The `print` button is disabled.

With `firejail --noprofile ...` printing works as expected.

* Zathura: 0.4.3
* Firejail: 0.9.60
* OS: Arch

**Comment by rusty-snake** [comment]
I cannot reproduce this. 
```
zathura --version
zathura 0.4.3
girara 0.3.2 (runtime: 0.3.2)
(plugin) pdf-poppler (0.2.9) (/usr/lib64/zathura/libpdf-poppler.so)
```
firejail: git
os: Fedora 30

**Comment by rusty-snake** [comment]
@nblock 
I'm closing here due to inactivity, please fell free to request reopen if you still have this issue.
