### ISSUE TITLE
Electron+AppImage config directory whitelist by default?

### ISSUE THREAD

**Issue by esotericDisciple** [netblue30/firejail#2991]
I know that Rambox would exit because it's ~/.config/Rambox directory needed to not be blacklisted and/or whitelisted in the command line...I haven't figured out what other permissions Biscuit needs in order to run yet, but for now I'm formally requesting apps own config dirs not be denied to the app by default, please...

**Comment by rusty-snake** [comment]
If a app-dir is blacklisted / not whitelisted this is a bug in the Profile.

To Rambox: For me everythings looks fine.
https://github.com/netblue30/firejail/blob/master/etc/rambox.profile#L8
https://github.com/netblue30/firejail/blob/master/etc/rambox.profile#L21

**Comment by esotericDisciple** [comment]
Rambox, last I tried, doesn't have tabbed navigation per-"app" though...

**Comment by rusty-snake** [comment]
With which firejail version?

**Comment by rusty-snake** [comment]
@esotericDisciple 
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
