### ISSUE TITLE
Firefox certificate errors with Firejail 

### ISSUE THREAD

**Issue by clara2g** [netblue30/firejail#2994]
Hi.

Often when I launch Firefox with Firejail I get certificate errors and cannot connect with any HTTPS site:

> A software is preventing Firefox to connect safely to this site. This problem is caused by DigiCert Global Root CA, which is a program in your computer or network
(translation from Spanish, not exact wording)

- I have to close and re-launch Firefox (with Firejail) like 5-6 times and then it starts working fine without any warning or errors
- It happens specially after a reboot, but can happen any time when launching new instance of Firefox
- If I launch Firefox without Firejail I never get this problem
- I'm using Firefox 69.0.1 (64 bit) with Firejail 0.9.56 default Firefox profile under Fedora 30

Thank you :)

**Comment by rusty-snake** [comment]
0.9.56 is over one year old, can you test it with a newer version.

**Comment by clara2g** [comment]
Woops, sorry I didn't realize Fedora's Firejail package was so outdated. I upgraded to firejail-0.9.60-1 from SourceForge rpm  but I still having the same issue.

**Comment by rusty-snake** [comment]
What is the errorcode (`SSL_ERROR_*`)?

That's interesting, I'm also on Fedora 30 (with Firefox from the repos) and firejail-git but I don't have theses issues. Also I does not see any commits on that and I assume that your aren't the only person with Fedora 30 + Firejail 0.9.60.

**Comment by clara2g** [comment]
> What is the errorcode (`SSL_ERROR_*`)?
MOZILLA_PKIX_ERROR_MITM_DETECTED
I don't know, my Fedora 30 is pretty standard and is not very customized. Firefox is installed from Fedora repositories (the only non official repos I'm using are RPM Fusion, Monodevelop and VSCodium). It is Fedora KDE Plasma though.

**Comment by fkooman** [comment]
Also occurs without "Firejail" on Firefox 70 on Fedora 30. Also happens on Arch and Clearlinux if you search around. The thing is, it is not always. A browser restart helps (for a little while) and then it is back. It is only with one CA.

Search terms: "MOZILLA_PKIX_ERROR_MITM_DETECTED" "DigiCert Global Root CA" firefox

**Comment by rusty-snake** [comment]
@clara2g 
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
