### ISSUE TITLE
Epiphany needs bwrap

### ISSUE THREAD

**Issue by mkdy** [netblue30/firejail#2995]
A fresh version of Epiphany browser (3.34.1-1) uses bwrap for some purposes (have no idea why).
I've created `epiphany.local` and filled it with:
`noblacklist ${PATH}/bwrap`
However, it seems that `bwrap` itself needs some permissions such as internet access.

**Comment by Vincent43** [comment]
bwrap is very similar to firejail itself sandboxing tool (used by flatpak) and I guess Epiphany uses it for that. Perhaps we have to drop epiphany support as overlapping sandboxes can't work.

**Comment by rusty-snake** [comment]
Confirming. Fedora 31 BETA VM with firejail-git.
```
$ LC_ALL=C epiphany 
Reading profile /etc/firejail/epiphany.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 41676, child pid 41677
Child process initialized in 142.89 ms

** (epiphany:5): ERROR **: 17:02:33.800: Unable to fork a new child process: Failed to execute child process ?/usr/bin/bwrap? (Permission denied)

Parent is shutting down, bye...
$ LC_ALL=C firejail --noprofile epiphany 
Parent pid 41762, child pid 41763
Child process initialized in 11.65 ms
Warning: an existing sandbox was detected. /usr/bin/epiphany will run without any additional sandboxing features
bwrap: Can't mount proc on /newroot/proc: Operation not permitted

(epiphany:2): GLib-GObject-WARNING **: 17:02:50.308: ../gobject/gsignal.c:2647: instance '0x55c894894390' has no handler with id '2782'

Parent is shutting down, bye...
```

**Comment by FOSSONLY** [comment]
@Vincent43
In fact, Firejail had no support for the Epiphany browser so far. The existing profile called Epiphany refers to a game of the same name. You should better use the Firefox profile for Epiphany.

However, I'm not sure how good it is for programs to bring their own sandbox. So the security is in the hands of the developers, and the user loses any flexibility to define it, if you don't want to change the source code. Personally, I would always use Firejail, because I don't think any program should be able to control its own security. For me, this is something that has to be centrally enforced, to which every program has to subordinate itself. What do the others think about it?

**Comment by rusty-snake** [comment]
> The existing profile called Epiphany refers to a game of the same name.

IMHO we should say this explicit in the profile that is not for epiphany (aka GNOME Web) and remove it form `firecfg.config` since it cause name conflicts. Maybe also rename to `epiphany_game.profile` or similar.

**Comment by rusty-snake** [comment]
> What do the others think about it?

:+1: :100: IMHO a tight firejail sandbox is better, if possible. For `chromium` this would mean starting with `--no-sandbox` and hardening the FJ profile. Anyway the fox is better :innocent:

**Comment by SkewedZeppelin** [comment]
Whoa there
epiphany.profile is indeed for GNOME Web
Must've slipped through the cracks with the automated descriptions pull

**Comment by Vincent43** [comment]
@SkewedZeppelin nice, should we sunset it though, considering it's broken with 3.34+?

**Comment by rusty-snake** [comment]
Adding a note about broke for 3.34+ and removing form firecfg, but leaving for now for e.g. debian users.

**Comment by msva** [comment]
actually, it looks like it is possible (at least, for now) to kinda "mitigate" this problem by setting [WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS](https://github.com/WebKit/WebKit/blob/0678a98c864ee36f0114ea4e7d303fd07788a822/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp#L105) variable value to `1` in firejail profile

Or by creating one of this files inside "jail": https://github.com/WebKit/WebKit/blob/0678a98c864ee36f0114ea4e7d303fd07788a822/Source/WTF/wtf/glib/Sandbox.cpp#L42
https://github.com/WebKit/WebKit/blob/0678a98c864ee36f0114ea4e7d303fd07788a822/Source/WTF/wtf/glib/Sandbox.cpp#L35

**Comment by glitsj16** [comment]
@msva

> looks like it is possible ...by setting WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1

Very nice find! Can you open a PR to add this to our epiphany.profile?

Side note:

Going over the referenced [ProcessLauncherGlib.cpp](https://github.com/WebKit/WebKit/blob/0678a98c864ee36f0114ea4e7d303fd07788a822/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp#L117) file I noticed that this env var replaces the now deprecated `WEBKIT_FORCE_SANDBOX` env var. We set the latter in the `bijiben.profile`:

https://github.com/netblue30/firejail/blob/969e29b756e91e00b1b0b5f86f9f4d8801ad987b/etc/profile-a-l/bijiben.profile#L62

**Comment by rusty-snake** [comment]
> Can you open a PR to add this to our epiphany.profile?

No, we should not add this.

**Comment by glitsj16** [comment]
> No, we should not add this.

@rusty-snake Unsafe to do so?

**Comment by rusty-snake** [comment]
Yes

epiphany+bwrap is more secure than firejail+epiphany-bwrap. If people still want to do this against my/our advise, for the more-secure-felling-but-less-secure-in-reality, we could add a comment (I really do not want to promote those unsafe debugging hacks).

**Comment by glitsj16** [comment]
@rusty-snake

I totally agree. We already have a comment in epiphany.profile referring to this issue, so I think we're good as-is. Thanks for your explaining!
