### ISSUE TITLE
Last version of slack-desktop do not run anymore

### ISSUE THREAD

**Issue by daks** [netblue30/firejail#3003]
Hi,

I again have a problem with slack after upgrading it to 4.1.1 on Debian 9.
I use firejail version from Debian, and created a slack.local with the `private-etc` tip from #2866

I tried to add to it the parameters indicated above, without change.

update not sure about the following, it may be because i use fish as a shell

I tried also the command `firejail --ignore=nonewprivs --ignore=noroot --ignore=protocol --ignore=seccomp --ignore=caps.drop --caps.keep=sys_admin,sys_chroot slack` without success.

**Comment by rusty-snake** [comment]
Any errors? Does it work with `--noprofile`?

**Comment by daks** [comment]
Yes, with bash, it works with --noprofile.

**Comment by vutny** [comment]
I have Slack Desktop 4.1.1 basically working on Debian bullseye/sid with this profile:
https://github.com/netblue30/firejail/blob/b4b95785d2e404141948371ddccf91fd1908ef18/etc/slack.profile

Also, take a look at #3015 .

**Comment by rusty-snake** [comment]
@daks still an issue?

**Comment by vutny** [comment]
I'm using version 4.2.0 with current profile, everything's great.

**Comment by rusty-snake** [comment]
@daks  I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
