### ISSUE TITLE
Firecfg and Cinnamon desktop crashes apps

### ISSUE THREAD

**Issue by Prsman** [netblue30/firejail#3006]
I have two CPUs running Mint w/ Cinnamon desktop.  Mint 18.3 and 19.2.  Version of Firejail is 
9.60_amd64.deb.  Running firecfg causes apps to fail to launch, Firefox displays a not default browser message.  Cant change in firefox preferences.  Xreader and another PDF reader wont launch.  Firejail is running on the apps that do start.  Executing sudo firecfg `--clean` fixes the problems.  Firejail will run with the firejail (app) command in a launcher or terminal.  Firecfg installs the links in /usr/local/bin.  I know more info is needed,  I dont know what that is.  Thanks.

**Comment by rusty-snake** [comment]
> Firefox displays a not default browser message. Cant change in firefox preferences. 

Probably expected.

> Xreader and another PDF reader wont launch.

Are there any error mesage in the terminal?

---

IDK if I get you right, but your issue is that `firejail APP` works but `sudo firecfg && APP` is broken?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
