### ISSUE TITLE
KVM on Android Studio

### ISSUE THREAD

**Issue by saddy001** [netblue30/firejail#3008]
Android Studio throws permission denied on /dev/kvm. From the jail, here are the permissions:
```
ls -hla /dev/kvm 
crw-rw---- 1 nobody nogroup 10, 232 Okt 22 12:10 /dev/kvm
```
Outer permission is
```
ls -hla /dev/kvm
crw-rw---- 1 root kvm 10, 232 Okt 22 13:18 /dev/kvm
```
If we make it chown user:user from the outside, it works shortly but then the ownership changes itself (on start/use of the VM) again into the above. Also the VM crashes on some actions where it does not in normal use.
Is there any quick workaround?

**Comment by Vincent43** [comment]
Try `firejail --ignore=noroot android-studio` (or whatever this app is named)

**Comment by saddy001** [comment]
Thanks, in combination that helped. It might be useful to update the android_studio profile.

**Comment by Vincent43** [comment]
Theoretically on a modern distro access to `/dev/kvm` should be granted for logged in user through logind. In such case the profile should work out of the box. We use `noroot` + `nogroups` for [qemu](https://github.com/netblue30/firejail/blob/master/etc/qemu-system-x86_64.profile) and there were no complaints about that.

@saddy001 what distro do you use? Could you try adding: `/etc/udev/rules.d/99-kvm.rules` file with:
`SUBSYSTEM=="misc", KERNEL=="kvm", TAG+="uaccess"` line inside then reboot and try again with default profile?

**Comment by Vincent43** [comment]
I checked that on Ubuntu 19.10 `/dev/kvm` is accessible through `uaccess` by default. I think we can leave this as is and recommend users of older distros above workaround.
