### ISSUE TITLE
Franz 5.4.0 not working with seccomp

### ISSUE THREAD

**Issue by schferbe** [netblue30/firejail#3009]
I'm on Archlinux 
```
$ uname -a
Linux tinkerpad 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux
```
running firejail
```
$ yay -Qs firejail 
local/firejail 0.9.60-1
    Linux namespaces sandbox program
local/firetools 0.9.58-2
    Graphical user interface of Firejail
```
and franz from the AUR.
```
$ yay -Qs franz
local/franz-bin 5.4.0-1
    Franz is a free messaging app for services like WhatsApp, Slack, Messenger
    and many more
```
After the update of franz 5.4.0 it won't start with the provided profile. If I comment out the `seccomp` in `/etc/firejail/franz.profile` it works.

**Comment by rusty-snake** [comment]
Which syscall is blocked? ([syscalls.txt](https://github.com/netblue30/firejail/blob/master/etc/templates/syscalls.txt#L90), [firejail_seccomp_notify.sh](https://gist.github.com/rusty-snake/7ed6b2a5bed3a6a9709b0faf9fcc86ab))

**Comment by schferbe** [comment]
```
Okt 26 10:52:31 hostname kernel: audit: type=1326 audit(1572079951.745:79): auid=1000 uid=1000 gid=1000 ses=2 pid=2475 comm="franz" exe="/usr/lib/franz/franz" sig=31 arch=c000003e syscall=161 compat=0 ip=0x7f9da9d5ae9d code=0x0
```
```
$ firejail --debug-syscalls | grep 161
161	- chroot
```
But when I change `seccomp` to `seccomp !chroot` in `/etc/firejail/franz.profile` starting franz leads to the following error:
```
$ franz
Reading profile /etc/firejail/franz.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Error: invalid syscall list
```
Do I need the `firejail_seccomp_notify.sh` or is it just a script to automate the task from `syscalls.txt`?

**Comment by rusty-snake** [comment]
> Do I need the firejail_seccomp_notify.sh or is it just a script to automate the task from syscalls.txt?

Nope, just an automated debuging script from me that notify you if blocked syscalls are called.

> But when I change `seccomp` to `seccomp !chroot` in `/etc/firejail/franz.profile` starting franz leads to the following error:

The new seccomp exception syntax is only supported in git-master. For older version use this:

```diff
-seccomp
+seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice
```

**Comment by schferbe** [comment]
That works. The new syntax is definitely nicer.
