### ISSUE TITLE
Question: How do I launch a local command in user home when --private is used?

### ISSUE THREAD

**Issue by fourzerofour** [netblue30/firejail#301]
I was getting "No such file or directory" when I launched the command but I figured it's only logical because the new home dir is mounted so the command now cannot be found in the home dir.

My goal is I don't want the command has access to my files in the real home dir when I run it

**Comment by genodeftest** [comment]
This is by design.

Two possible workarounds:
1. install local command in /usr/local/bin (requires root privileges for installation)
2. copy local command to a tempdir, add tempdir to ${PATH}
