### ISSUE TITLE
'noroot' in dolphin.profile breaks mpv vulkan renderer

### ISSUE THREAD

**Issue by Ryujinra** [netblue30/firejail#3012]
When playing a video with mpv+vulkan from dolphin, the vulkan renderer is unavailable to mpv with the default dolphin.profile. `noroot` must be commented out for mpv to access vulkan from within the dolphin container.

To replicate, add `gpi-api=vulkan` to mpv.conf, and use dolphin to select something to play - mpv will quit immediately as long as dolphin is started with `noroot`. You may need to explicitly set `gpu-context` in mpv as well, if your wayland/x11 environment isn't properly detected.

**Comment by glitsj16** [comment]
Thanks for reporting the issue. I've put a comment inside the [dolphin.profile](https://github.com/netblue30/firejail/blob/master/etc/dolphin.profile#L28) to add 'ignore noroot' to dolphin.local in such case. I didn't want to drop 'noroot' from the default options, as this doesn't affect most users IMHO. If you can live with that, please test and comment/close this here.

**Comment by Ryujinra** [comment]
Yes, I think this is fine.
