### ISSUE TITLE
update waterfox profile

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#3013]
they are two versions of waterfox now
https://www.waterfox.net/blog/waterfox-2019.10-release-download/

rename waterfox.profile to waterfox-classic.profile (don't forget the include to waterfox-classic.local)
(this is the version with the XUL addons)

there's also waterfox-current (based from firefox quantum). I haven't installed that one. Its profile, is probably the same and just need a rename.

**Comment by glitsj16** [comment]
Thanks for informing us. Two days ago I tested waterfox-current, and that worked fine with the current profile. I just downloaded the classic version and its executable name is unchanged. So both versions should be covered with the current profile. IMO renaming/splitting out the existing profile into  `waterfox-classic` and `waterfox-current` would break firejails desktop integration - a.k.a `firecfg`. Is something not working as expected for you with the classic version?

**Comment by rusty-snake** [comment]
Just tested, waterfox-classic is based on a pre-quantum FFX, waterfox-current is quantum based. Both WFX use the same config directories, the executable names are also not changed. IMHO there is no need to rename the profiles.

**Comment by glitsj16** [comment]
@rusty-snake If both versions share the same config dir now - I suppose this is _${HOME}/.waterfox_ - we could in fact drop both _${HOME}/.cache/mozilla_ and _${HOME}/.mozilla_ from `noblacklist`, `mkdir` and `whitelist` options. What do you think? Should we proceed on that or is it to soon to do so?

**Comment by rusty-snake** [comment]
On my tests no mozilla dirs are created (using `--private`), except .mozilla is created by the current version but is empty. I haven't done a deeper test now, but for me it looks like mozilla dirs are not needed.

**Comment by pirate486743186** [comment]
mozilla directories are there for moving from firefox. There's an official wizard for that.

I installed using the unofficial repos. He changed the names....

**Comment by rusty-snake** [comment]
> mozilla directories are there for moving from firefox. There's an official wizard for that. Add a comment in the profile about this.

There are also wizards in FFX to import bookmarks (and some more) from chrome, in chrom to import from ...  but we don't support them. IMHO we should comment these lines, there is no need to have always access to the firefox dirs.

> I installed using the unofficial repos. He changed the names....

Also in the AUR.

**Comment by rusty-snake** [comment]
#3014
