### ISSUE TITLE
socket proxy 4/5 support

### ISSUE THREAD

**Issue by tailot** [netblue30/firejail#3017]
Hi, will there be support the proxy socket 4/5 ?

Thanks

**Comment by netblue30** [comment]
socks is an application level proxy. You have to configure it in the application. Not all applications support it. You can try it for example in Firefox.

Only TCP and UDP traffic goes trough the proxy - I don't know what happens to the DNS traffic. For the sandbox you can enable a network namespace (firejail --net=eth0 firefox) to isolate the interface, but that's the only thing you can do.

**Comment by netblue30** [comment]
socks is an application level proxy. You have to configure it in the application. Not all applications support it. You can try it for example in Firefox.

Only TCP and UDP traffic goes trough the proxy - I don't know what happens to the DNS traffic. For the sandbox you can enable a network namespace (firejail --net=eth0 firefox) to isolate the interface, but that's the only thing you can do.
