### ISSUE TITLE
Cannot start sandbox when installing Firejail with Stow

### ISSUE THREAD

**Issue by M83tUt3** [netblue30/firejail#3018]
I installed Firejail from a 0.9.60 git checkout like such

`$ ./configure --disable-apparmor --prefix=/usr/local/stow/firejail-0.9.60`
`$ make && sudo make install-strip`
`$ cd /usr/local/stow`
`$ sudo stow firejail-0.9.60`

which installs the files in /usr/local as symlinks to /usr/local/stow/firejail-0.9.60.

`$ ls -l /usr/local/bin/firejail`
`lrwxrwxrwx 1 root root 36 Oct 29 15:36 /usr/local/bin/firejail -> ../stow/firejail-0.9.60/bin/firejail`

Now when I'm trying to run some programs I'm getting the following error.

`$ firejail mpv`
`Reading profile /home/me/.config/firejail/mpv.profile`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/disable-common.inc`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/disable-devel.inc`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/disable-exec.inc`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/disable-interpreters.inc`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/disable-passwdmgr.inc`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/disable-programs.inc`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/disable-xdg.inc`
`Reading profile /usr/local/stow/firejail-0.9.60/etc/firejail/whitelist-var-common.inc`
`Parent pid 14609, child pid 14610`
`35 programs installed in 23.10 ms`
`Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.`
`Warning: cleaning all supplementary groups`
`Warning: cleaning all supplementary groups`
`Blacklist violations are logged to syslog`
`Child process initialized in 74.75 ms`
`Error: cannot find the program in the path`
`Parent is shutting down, bye...`

In this case mpv is installed in /usr/bin/mpv and there's a symlink in /usr/local/bin pointing to firejail.
`$ ls -l $(which mpv)`
`lrwxrwxrwx 1 root root 23 Oct 29 14:58 /usr/local/bin/mpv -> /usr/local/bin/firejail`

The issue does not occur when I install directly to /usr/local by doing
`./configure --prefix=/usr/local`
OR when commenting out a private-bin line in my mpv.profile
`$ grep private-bin mpv.profile`
`private-bin mpv,youtube-dl,python*,env`
I do not have to comment it out when I install without using Stow.

Any ideas what might be causing this?

**Comment by rusty-snake** [comment]
Referring to @glitsj16 idea in #3020: Have your tried to start with `firejail /usr/bin/mpv`?

**Comment by M83tUt3** [comment]
Trying that gives me the same error. Strangely enough, what does in fact work is removing the the mpv symlink and then starting the sandbox:
`$ sudo rm /usr/local/bin/mpv`
`$ firejail mpv`
works.

My PATH looks as follows
`/usr/local/bin:/home/nemu/.local/python/bin:/home/nemu/.local/bin:/home/nemu/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin`
and the full mpv config is here.
https://pastebin.com/raw/spS4Z22G

I switched to the git version by the way but everything's the same.
I've just got firejail installed the regular way now and I can't say I feel too strongly about not being able to use stow.

**Comment by M83tUt3** [comment]
Everything is working as expected again and the problem seems to have been resolved entirely by setting
`private-bin-no-local yes`
in my firejail.config. This is the more restrictive option, right? If so, I'll happily leave it like this and as far as I'm concerned the issue can be closed.

**Comment by rusty-snake** [comment]
OT: Why is there `whitelist /usr/share/libdrm`? Do you suggest to add it upstream?

---

> This is the more restrictive option, right?

IDK. Maybe just an option to fix such issues?

**Comment by M83tUt3** [comment]
> OT: Why is there `whitelist /usr/share/libdrm`? Do you suggest to add it upstream?
mpv said this when I didn't have it whitelisted
`/usr/share/libdrm/amdgpu.ids: No such file or directory`
It will output this at any log level. It doesn't seem to do any harm but I can't imagine whitelisting it can do any harm either. 
https://gitlab.freedesktop.org/mesa/drm/blob/master/data/amdgpu.ids
Could be upstreamed I guess.

**Comment by glitsj16** [comment]
@rusty-snake Perhaps we can add /usr/share/libdrm (which on my Arch Linux currently has that one file amdgpu.ids) to wusc to ensure support for AMD systems?

**Comment by glitsj16** [comment]
I'll re-close this when we have a decision on wusc and /usr/share/libdrm. I can't see what upstream can do about it honestly.

@M83tUt3 You can add whitelist /usr/share/libdrm to your mpv.local to get rid of those warnings. Just keep an eye out when we decide to add it to whitelist-usr-share-common.inc, that would make it redundant.

**Comment by rusty-snake** [comment]
If this is used by more than a few programs, we should move it to wusc.

**Comment by rusty-snake** [comment]
I already add it to mpv (IDK if you see it).

**Comment by rusty-snake** [comment]
```
$ dnf repoquery --alldeps  --whatrequires libdrm
Paketquelle fedora-modular-debuginfo wird aktiviert
Paketquelle updates-modular-debuginfo wird aktiviert
Paketquelle updates-debuginfo wird aktiviert
Paketquelle fedora-debuginfo wird aktiviert
Paketquelle rpmfusion-free-updates-debuginfo wird aktiviert
Paketquelle rpmfusion-free-debuginfo wird aktiviert
Paketquelle rpmfusion-nonfree-updates-debuginfo wird aktiviert
Paketquelle rpmfusion-nonfree-debuginfo wird aktiviert
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:17 am Mi 30 Okt 2019 22:13:07 CET.
cheese-libs-2:3.32.1-1.fc30.i686
cheese-libs-2:3.32.1-1.fc30.x86_64
clutter-0:1.26.2-8.fc30.i686
clutter-0:1.26.2-8.fc30.x86_64
clutter-gst3-0:3.0.27-1.fc30.i686
clutter-gst3-0:3.0.27-1.fc30.x86_64
clutter-gtk-0:1.8.4-5.fc30.i686
clutter-gtk-0:1.8.4-5.fc30.x86_64
cmrt-0:1.0.6-10.fc30.i686
cmrt-0:1.0.6-10.fc30.x86_64
cogl-0:1.22.2-12.fc30.i686
cogl-0:1.22.2-12.fc30.x86_64
cogl-0:1.22.4-1.fc30.i686
cogl-0:1.22.4-1.fc30.x86_64
deepin-mutter-0:3.20.38-2.fc30.i686
deepin-mutter-0:3.20.38-2.fc30.x86_64
deepin-wm-0:1.9.37-1.fc30.i686
deepin-wm-0:1.9.37-1.fc30.x86_64
deepin-wm-0:1.9.38-1.fc30.i686
deepin-wm-0:1.9.38-1.fc30.x86_64
drm-utils-0:2.4.97-2.fc30.x86_64
drm-utils-0:2.4.99-1.fc30.x86_64
efl-0:1.21.1-4.fc30.i686
efl-0:1.21.1-4.fc30.x86_64
eog-plugin-map-0:3.26.3-2.fc30.x86_64
eog-plugin-map-0:3.26.4-1.fc30.x86_64
fbida-0:2.14-6.fc30.x86_64
fbida-fbpdf-0:2.14-6.fc30.x86_64
ffmpeg-libs-0:4.1.3-2.fc30.i686
ffmpeg-libs-0:4.1.3-2.fc30.x86_64
ffmpeg-libs-0:4.1.4-2.fc30.i686
ffmpeg-libs-0:4.1.4-2.fc30.x86_64
glmark2-0:2017.07-2.20180717git0003eff.fc30.x86_64
gstreamer1-plugins-bad-free-0:1.15.2-1.fc30.i686
gstreamer1-plugins-bad-free-0:1.15.2-1.fc30.x86_64
gstreamer1-plugins-bad-free-0:1.16.0-2.fc30.i686
gstreamer1-plugins-bad-free-0:1.16.0-2.fc30.x86_64
gstreamer1-vaapi-0:1.15.2-1.fc30.i686
gstreamer1-vaapi-0:1.15.2-1.fc30.x86_64
gstreamer1-vaapi-0:1.16.0-1.fc30.i686
gstreamer1-vaapi-0:1.16.0-1.fc30.x86_64
igt-gpu-tools-0:1.24-1.20191008git869ed1e.fc30.i686
igt-gpu-tools-0:1.24-1.20191008git869ed1e.fc30.x86_64
intel-gpu-tools-0:2.99.917-41.20180618.fc30.x86_64
kodi-gbm-0:18.1-3.fc30.x86_64
kodi-gbm-0:18.4-1.fc30.x86_64
kwin-wayland-0:5.15.4-1.fc30.i686
kwin-wayland-0:5.15.4-1.fc30.x86_64
kwin-wayland-0:5.15.5-3.fc30.i686
kwin-wayland-0:5.15.5-3.fc30.x86_64
libavdevice-0:4.1.3-2.fc30.i686
libavdevice-0:4.1.3-2.fc30.x86_64
libavdevice-0:4.1.4-2.fc30.i686
libavdevice-0:4.1.4-2.fc30.x86_64
libdrm-armada-0:2.0.0-1.20190424git607c697.fc30.i686
libdrm-armada-0:2.0.0-1.20190424git607c697.fc30.x86_64
libdrm-devel-0:2.4.97-2.fc30.i686
libdrm-devel-0:2.4.97-2.fc30.x86_64
libdrm-devel-0:2.4.99-1.fc30.i686
libdrm-devel-0:2.4.99-1.fc30.x86_64
libmash-0:0.2.0-26.fc30.i686
libmash-0:0.2.0-26.fc30.x86_64
libva-0:2.4.1-1.fc30.i686
libva-0:2.4.1-1.fc30.x86_64
libva-intel-driver-0:2.3.0-3.fc30.i686
libva-intel-driver-0:2.3.0-3.fc30.x86_64
libva-intel-hybrid-driver-0:1.0.2-15.fc30.i686
libva-intel-hybrid-driver-0:1.0.2-15.fc30.x86_64
mesa-dri-drivers-0:19.0.2-3.fc30.i686
mesa-dri-drivers-0:19.0.2-3.fc30.x86_64
mesa-dri-drivers-0:19.1.7-1.fc30.i686
mesa-dri-drivers-0:19.1.7-1.fc30.x86_64
mesa-libEGL-0:19.0.2-3.fc30.i686
mesa-libEGL-0:19.0.2-3.fc30.x86_64
mesa-libEGL-0:19.1.7-1.fc30.i686
mesa-libEGL-0:19.1.7-1.fc30.x86_64
mesa-libGL-0:19.0.2-3.fc30.i686
mesa-libGL-0:19.0.2-3.fc30.x86_64
mesa-libGL-0:19.1.7-1.fc30.i686
mesa-libGL-0:19.1.7-1.fc30.x86_64
mesa-libOpenCL-0:19.0.2-3.fc30.i686
mesa-libOpenCL-0:19.0.2-3.fc30.x86_64
mesa-libOpenCL-0:19.1.7-1.fc30.i686
mesa-libOpenCL-0:19.1.7-1.fc30.x86_64
mesa-libd3d-0:19.0.2-3.fc30.i686
mesa-libd3d-0:19.0.2-3.fc30.x86_64
mesa-libd3d-0:19.1.7-1.fc30.i686
mesa-libd3d-0:19.1.7-1.fc30.x86_64
mesa-libgbm-0:19.0.2-3.fc30.i686
mesa-libgbm-0:19.0.2-3.fc30.x86_64
mesa-libgbm-0:19.1.7-1.fc30.i686
mesa-libgbm-0:19.1.7-1.fc30.x86_64
mesa-libxatracker-0:19.0.2-3.fc30.i686
mesa-libxatracker-0:19.0.2-3.fc30.x86_64
mesa-libxatracker-0:19.1.7-1.fc30.i686
mesa-libxatracker-0:19.1.7-1.fc30.x86_64
mesa-omx-drivers-0:19.0.2-3.fc30.x86_64
mesa-omx-drivers-0:19.1.7-1.fc30.x86_64
mesa-vdpau-drivers-0:19.0.2-3.fc30.i686
mesa-vdpau-drivers-0:19.0.2-3.fc30.x86_64
mesa-vdpau-drivers-0:19.1.7-1.fc30.i686
mesa-vdpau-drivers-0:19.1.7-1.fc30.x86_64
mesa-vulkan-drivers-0:19.0.2-3.fc30.i686
mesa-vulkan-drivers-0:19.0.2-3.fc30.x86_64
mesa-vulkan-drivers-0:19.1.7-1.fc30.i686
mesa-vulkan-drivers-0:19.1.7-1.fc30.x86_64
mir-server-libs-0:1.1.0-3.fc30.i686
mir-server-libs-0:1.1.0-3.fc30.x86_64
mir-server-libs-0:1.5.0-1.fc30.i686
mir-server-libs-0:1.5.0-1.fc30.x86_64
mpv-0:0.29.1-5.fc30.x86_64
mpv-0:0.30.0-1.fc30.x86_64
mpv-libs-0:0.29.1-5.fc30.i686
mpv-libs-0:0.29.1-5.fc30.x86_64
mpv-libs-0:0.30.0-1.fc30.i686
mpv-libs-0:0.30.0-1.fc30.x86_64
mutter-0:3.32.1-1.fc30.i686
mutter-0:3.32.1-1.fc30.x86_64
mutter-0:3.32.2-4.fc30.i686
mutter-0:3.32.2-4.fc30.x86_64
mutter328-libs-0:3.28.3-6.fc30.i686
mutter328-libs-0:3.28.3-6.fc30.x86_64
mutter328-libs-0:3.28.4-1.fc30.i686
mutter328-libs-0:3.28.4-1.fc30.x86_64
nemo-preview-0:4.0.0-3.fc30.x86_64
nemo-preview-0:4.2.0-1.fc30.x86_64
open-vm-tools-0:10.3.10-1.fc30.i686
open-vm-tools-0:10.3.10-1.fc30.x86_64
open-vm-tools-0:11.0.0-4.fc30.i686
open-vm-tools-0:11.0.0-4.fc30.x86_64
piglit-0:1.0.20171027-10.GIT65b4b197.fc30.x86_64
plymouth-graphics-libs-0:0.9.4-5.fc30.i686
plymouth-graphics-libs-0:0.9.4-5.fc30.x86_64
plymouth-graphics-libs-0:0.9.4-9.fc30.i686
plymouth-graphics-libs-0:0.9.4-9.fc30.x86_64
qt5-qtbase-gui-0:5.12.1-2.fc30.i686
qt5-qtbase-gui-0:5.12.1-2.fc30.x86_64
qt5-qtbase-gui-0:5.12.5-1.fc30.i686
qt5-qtbase-gui-0:5.12.5-1.fc30.x86_64
radeontop-0:1.2-0.2.20181031git7474f50.fc30.x86_64
radeontop-0:1.2-3.20191001git50cc248.fc30.x86_64
redshift-0:1.12-3.fc30.x86_64
spice-vdagent-0:0.19.0-1.fc30.x86_64
virglrenderer-0:0.7.0-3.20190424gitd1758cc09.fc30.i686
virglrenderer-0:0.7.0-3.20190424gitd1758cc09.fc30.x86_64
vkmark-0:2017.08-0.6.20180123git68b6f23.fc30.x86_64
weston-0:6.0.0-1.fc30.i686
weston-0:6.0.0-1.fc30.x86_64
weston-0:6.0.1-1.fc30.i686
weston-0:6.0.1-1.fc30.x86_64
weston-demo-0:6.0.1-1.fc30.x86_64
weston-libs-0:6.0.0-1.fc30.i686
weston-libs-0:6.0.0-1.fc30.x86_64
weston-libs-0:6.0.1-1.fc30.i686
weston-libs-0:6.0.1-1.fc30.x86_64
wlc-0:0.0.11-5.fc30.i686
wlc-0:0.0.11-5.fc30.x86_64
wlroots-0:0.7.0-1.module_f30+6136+9abe85a5.x86_64
xfdashboard-0:0.7.5-2.fc30.i686
xfdashboard-0:0.7.5-2.fc30.x86_64
xfdashboard-0:0.7.5-4.fc30.i686
xfdashboard-0:0.7.5-4.fc30.x86_64
xorg-x11-drv-amdgpu-0:19.0.0-1.fc30.x86_64
xorg-x11-drv-amdgpu-0:19.1.0-1.fc30.x86_64
xorg-x11-drv-armada-0:0.0.0-1.unstable.20180829git78e7116a5.fc30.x86_64
xorg-x11-drv-ati-0:19.0.1-1.fc30.x86_64
xorg-x11-drv-ati-0:19.0.1-2.fc30.x86_64
xorg-x11-drv-intel-0:2.99.917-41.20180618.fc30.i686
xorg-x11-drv-intel-0:2.99.917-41.20180618.fc30.x86_64
xorg-x11-drv-intel-0:2.99.917-42.20180618.fc30.i686
xorg-x11-drv-intel-0:2.99.917-42.20180618.fc30.x86_64
xorg-x11-drv-nouveau-1:1.0.15-7.fc30.x86_64
xorg-x11-drv-openchrome-0:0.6.0-7.fc30.i686
xorg-x11-drv-openchrome-0:0.6.0-7.fc30.x86_64
xorg-x11-drv-vmware-0:13.2.1-9.fc30.x86_64
xorg-x11-server-Xorg-0:1.20.4-3.fc30.x86_64
xorg-x11-server-Xorg-0:1.20.5-7.fc30.x86_64
xorg-x11-server-Xwayland-0:1.20.4-3.fc30.x86_64
xorg-x11-server-Xwayland-0:1.20.5-7.fc30.x86_64
```

IMHO we should move it to wusc.

**Comment by glitsj16** [comment]
Moved /usr/share/libdrm to wusc via https://github.com/netblue30/firejail/commit/591d66319fbd49339ccc0af36d702b463fd8d184. Also removed it from mpv.profile again via https://github.com/netblue30/firejail/commit/8822422e55a0be2ae4b50b57469c06c0783dca3f.
