### ISSUE TITLE
After Update Firejail cannot Launch Vivaldi Browser

### ISSUE THREAD

**Issue by KhalbahO** [netblue30/firejail#3022]
Hi everyone ! 

Before update, I used firetool app for with the tool "Configuration Wizard" and this commande line :

firejail -- vivaldi-stable --disk-cache-dir=/tmp/vivaldi-stable-cache

And Vivaldi Worked well, but now nothing !

Just this answer :

Reading profile /usr/share/defaults/firejail/vivaldi-stable.profile
Reading profile /usr/share/defaults/firejail/vivaldi.profile
Reading profile /usr/share/defaults/firejail/chromium-common.profile
Reading profile /usr/share/defaults/firejail/disable-common.inc
Reading profile /usr/share/defaults/firejail/disable-devel.inc
Reading profile /usr/share/defaults/firejail/disable-exec.inc
Reading profile /usr/share/defaults/firejail/disable-interpreters.inc
Reading profile /usr/share/defaults/firejail/disable-programs.inc
Reading profile /usr/share/defaults/firejail/whitelist-common.inc
Reading profile /usr/share/defaults/firejail/whitelist-var-common.inc
Parent pid 30641, child pid 30642
Child process initialized in 179.58 ms
/usr/bin/vivaldi-stable: ligne 174: /dev/fd/62: Aucun fichier ou dossier de ce type
/usr/bin/vivaldi-stable: ligne 175: /dev/fd/62: Aucun fichier ou dossier de ce type
/usr/bin/vivaldi-stable: ligne 178: /usr/share/vivaldi-stable/vivaldi-bin: Permission non accordée
/usr/bin/vivaldi-stable: ligne 178: /usr/share/vivaldi-stable/vivaldi-bin: Succès

Parent is shutting down, bye...

And when I made a "Firejail Vivaldi" the answer is :

Warning: an existing sandbox was detected. vivaldi will run without any additional sandboxing features
/bin/bash: vivaldi : commande introuvable

I'm on Solus OS, what's wrong with that ?

At soon !

**Comment by rusty-snake** [comment]
What is your old firejail version and what is the current version?

probably not the issue (#2383)
```
/usr/bin/vivaldi: line 169: /dev/fd/62: No such file or directory
/usr/bin/vivaldi: line 170: /dev/fd/62: No such file or directory
```

**Comment by KhalbahO** [comment]
My current firejail version is 0.9.60, i don't have watched the number of the older version  but i think that the problem is the new version of vivaldi browser "Perhaps not supported now" !

**Comment by rusty-snake** [comment]
`/usr/share/vivaldi-stable/vivaldi-bin` is the executale, right?
Try `firejail --profile=vivaldi /usr/share/vivaldi-stable/vivaldi-bin`

**Comment by KhalbahO** [comment]
firejail --profile=vivaldi /usr/share/vivaldi-stable/vivaldi-bin

Warning: an existing sandbox was detected. /usr/share/vivaldi-stable/vivaldi-bin will run without any additional sandboxing features
[8:8:1031/003133.352930:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
root@khalbaho ~ # ^C

**Comment by rusty-snake** [comment]
You start your Browser as root? serious?

**Comment by rusty-snake** [comment]
If you run `firejail echo` do you the the 'Warning: an existing sandbox was detected. …' message?

**Comment by KhalbahO** [comment]
Oups I try lot of thing i forgot unroot

**Comment by KhalbahO** [comment]
Reading profile /usr/share/defaults/firejail/default.profile
Reading profile /usr/share/defaults/firejail/disable-common.inc
Reading profile /usr/share/defaults/firejail/disable-passwdmgr.inc
Reading profile /usr/share/defaults/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 7301, child pid 7302
Child process initialized in 39.53 ms


Parent is shutting down, bye...

**Comment by KhalbahO** [comment]
Yeah, I can't understand why it detect that : "an existing sandbox..."
I try kill process / open config file with notepad ...  for find an anwser

**Comment by KhalbahO** [comment]
With opera no problem... It works well...

**Comment by KhalbahO** [comment]
I said that because it same engine lol !

**Comment by KhalbahO** [comment]
> Reading profile /usr/share/defaults/firejail/vivaldi.profile

Reading profile /usr/share/defaults/firejail/chromium-common.profile
Reading profile /usr/share/defaults/firejail/disable-common.inc
Reading profile /usr/share/defaults/firejail/disable-devel.inc
Reading profile /usr/share/defaults/firejail/disable-exec.inc
Reading profile /usr/share/defaults/firejail/disable-interpreters.inc
Reading profile /usr/share/defaults/firejail/disable-programs.inc
Reading profile /usr/share/defaults/firejail/whitelist-common.inc
Reading profile /usr/share/defaults/firejail/whitelist-var-common.inc
Parent pid 10017, child pid 10018
Child process initialized in 76.28 ms
Error: no suitable vivaldi executable found

Parent is shutting down, bye...

>

**Comment by rusty-snake** [comment]
Which cmd? Does `firejail --noprofile vivaldi` works at all?

**Comment by KhalbahO** [comment]
```
firejail --noprofile vivaldi

Parent pid 10370, child pid 10371
Child process initialized in 15.46 ms
/bin/bash: vivaldi : commande introuvable

Parent is shutting down, bye...
```

**Comment by KhalbahO** [comment]
I think really at a corruption lol

**Comment by rusty-snake** [comment]
But there is `vivaldi` command? (When trying without firejail).

`firejail --noprofile vivaldi-stable`

**Comment by KhalbahO** [comment]
Wow... ! OK ... no boot with vivaldi cmd

**Comment by KhalbahO** [comment]
What the ... ! Now this cmd "firejail --noprofile vivaldi-stable" works ...why I tryed that one thousand times lol ! What does't it mean "noprofile" It's mode no safe ?

**Comment by rusty-snake** [comment]
It disabled the usage of profiles. Now we know that it can be fixed by tweaking [vivaldi.profile](https://github.com/netblue30/firejail/blob/master/etc/vivaldi.profile) or more likely [chromium-common.profile](https://github.com/netblue30/firejail/blob/master/etc/google-chrome.profile)

**Comment by KhalbahO** [comment]
This is due to the update of vivaldi? The profile no longer supports the changes they added ?

**Comment by KhalbahO** [comment]
```
@~ $ firejail vivaldi-stable

Reading profile /usr/share/defaults/firejail/vivaldi-stable.profile
Reading profile /usr/share/defaults/firejail/vivaldi.profile
Reading profile /usr/share/defaults/firejail/chromium-common.profile
Reading profile /usr/share/defaults/firejail/disable-common.inc
Reading profile /usr/share/defaults/firejail/disable-devel.inc
Reading profile /usr/share/defaults/firejail/disable-exec.inc
Reading profile /usr/share/defaults/firejail/disable-interpreters.inc
Reading profile /usr/share/defaults/firejail/disable-programs.inc
Reading profile /usr/share/defaults/firejail/whitelist-common.inc
Reading profile /usr/share/defaults/firejail/whitelist-var-common.inc
Parent pid 3134, child pid 3135
Child process initialized in 118.25 ms
/usr/bin/vivaldi-stable: ligne 174: /dev/fd/62: Aucun fichier ou dossier de ce type
/usr/bin/vivaldi-stable: ligne 175: /dev/fd/62: Aucun fichier ou dossier de ce type
/usr/bin/vivaldi-stable: ligne 178: /usr/share/vivaldi-stable/vivaldi-bin: Permission non accordée
/usr/bin/vivaldi-stable: ligne 178: /usr/share/vivaldi-stable/vivaldi-bin: Succès

Parent is shutting down, bye...

@~ $ firejail --noprofile vivaldi-stable

Parent pid 4350, child pid 4351
Child process initialized in 10.12 ms
[2:2:1031/014637.884690:ERROR:chrome_content_client.cc(342)] Failed to locate and load the component updated flash plugin.
[2:2:1031/014639.649204:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: The message port closed before a response was received.", source: chrome-extension://mpognobbkildjkofajifpdfhcoklimli/browser.html (0)
[2:2:1031/014639.649291:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: The message port closed before a response was received.", source: chrome-extension://mpognobbkildjkofajifpdfhcoklimli/browser.html (0)


```

**Comment by rusty-snake** [comment]
Works `firejail --ignore=apparmor --ignore=netfilter --ignore=nogroups --ignore="shell none" --ignore=disable-mnt --ignore=private-dev --profile=vivaldi vivaldi-stable`? If so, try removing all `ignore`s that are not necessary to start vivaldi.

**Comment by KhalbahO** [comment]
That works ! With this command Vivaldi is still execute in sandbox or ... ? I feel that lot of firejail features are ignored ?

**Comment by rusty-snake** [comment]
> Works `firejail --ignore=apparmor --ignore=netfilter --ignore=nogroups --ignore="shell none" --ignore=disable-mnt --ignore=private-dev --profile=vivaldi vivaldi-stable`? **If so, try removing all `ignore`s that are not necessary to start vivaldi.**
