### ISSUE TITLE
--x11 not working with chroot

### ISSUE THREAD

**Issue by ichensky** [netblue30/firejail#3027]
Steps to reproduce. 
1. Install debian in chroot
```$ debootstrap --arch=amd64 sid /chroot/sid```
2. Try to execute: 
$ firejail --x11 --chroot=/chroot/sid 
---
Another related issue if for ex.   
On the host OS run `firefox`. Then run `firefox` in the chroot dir.
```
$ firejail --chroot=/chroot/sid
$ firefox 
```
chrooted `firefox` would contains the same bookmarks, tabs, history from the host OS `firefox`.

It would be good, maybe, if `firejail` by default sandboxing X server from applications.

**Comment by rusty-snake** [comment]
> It would be good, maybe, if firejail by default sandboxing X server from applications.

Surely it sounds good at first view, but I think its not good, because 
1. GTK+3 App run under Wayland if available. Then we must detect this.
2. It will break a lot of user workflows.
