### ISSUE TITLE
Drop legacy Skype profile

### ISSUE THREAD

**Issue by vutny** [netblue30/firejail#3029]
The file `etc/skype.profile` is outdated and not suitable for running current versions of Skype For Linux proprietary software.
Since the package provided by Microsoft sets the binary name to `skypeforlinux`, I think it is sufficient to keep only `skypeforlinux.profile`, which is up to date.

**Comment by Fred-Barclay** [comment]
I probably agree that it's useless -- but I wonder, what are the drawbacks of continuing to include it?

**Comment by vutny** [comment]
I think the only real drawback is not confusing users, and for future contributors it would be easier to determine where the changes need to be done.
If there is no objections, I will submit a PR for the profile removal. Thanks.
