### ISSUE TITLE
Cant run `firejail firefox`

### ISSUE THREAD

**Issue by nsauter** [netblue30/firejail#3039]
Hi,

maybe im just confused but i cant run a firejail-firefox instance on my computer. Can someone please tell me what i am doing wrong?
```

$ firejail firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 390181, child pid 390184
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: cleaning all supplementary groups
Error mount bind: fs_whitelist.c:297 whitelist_path: Permission denied
Error: proc 390181 cannot sync with peer: unexpected EOF
Peer 390184 unexpectedly exited with status 1
```

Even if i add --net remove unix from protocol set this wont work.

**Comment by rusty-snake** [comment]
distro, firejail version? output of `echo $HOME`.

**Comment by nsauter** [comment]
Fedora 31, but i tried it with every fedora version since 29. 

firejail version 0.9.57

$HOME is
/home/nsauter

**Comment by smitsohu** [comment]
Is /home/nsauter a symbolic link?

Could you run `firejail --debug-whitelists firefox`?

**Comment by nsauter** [comment]
Its a NFS Mounted Home. But i cant get the same error with local home.

https://pastebin.com/150z4HNQ

**Comment by Vincent43** [comment]
Can you show `ls -al /usr/bin/firejail` output?

**Comment by nsauter** [comment]
-rwsr-xr-x 1 root root 395928 29. Jul 10:50 /usr/bin/firejail
