### ISSUE TITLE
Need help for Waterofx.profile (Firejail)

### ISSUE THREAD

**Issue by trancemind65** [netblue30/firejail#3047]
Hi!

I created a Waterfox.profile for Firejail.

> include /etc/firejail/waterfox.profile.local
> include globals.local
> 
> include /etc/firejail/disable-common.inc
> include /etc/firejail/disable-devel.inc
> include /etc/firejail/disable-interpreters.inc
> include /etc/firejail/disable-passwdmgr.inc
> include /etc/firejail/disable-programs.inc
> 
> blacklist ${HOME}/.cache/waterfox
> blacklist ${HOME}/.waterfox
> 
> caps.drop all
> machine-id
> netfilter
> nodvd
> nogroups
> nonewprivs
> noroot
> notv
> protocol unix,inet
> #seccomp
> #shell none
> 
> private-bin bash,cp,dirname,env,expr,file,waterfox,waterfox-bin,getconf,gpg,grep,id,ln,mkdir,python*,readlink,rm,sed,sh,tail,test
> private-dev
> private-etc fonts
> private-tmp
> 
> noexec ${HOME}
> noexec /tmp

I run:
firejail --private --dns=84.200.69.80 --dns=84.200.70.40 --profile=/etc/firejail/waterfox.profile /home/unknown/waterfox/waterfox

Error:
Reading profile /etc/firejail/waterfox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 9202, child pid 9203

DNS server 84.200.69.80
DNS server 84.200.70.40

Private /etc installed in 23.16 ms
38 programs installed in 99.27 ms
Child process initialized in 199.59 ms
/bin/bash: /home/unknown/waterfox/waterfox: No such file or directory

Parent is shutting down, bye...

 /home/unknown/waterfox/waterfox: No such file or directory
How can I fix that?

The path to the exec of Waterfox works when I run it without Firejail command.

**Comment by rusty-snake** [comment]
Hi,

I thing the issue is `noexec ${HOME}` if `/home/unknown/waterfox/waterfox` is a elf-file. Or is it a symlink?
Also what against the waterfox-profile from firejail?
You use a old firejail version, right? Which version is it?

**Comment by rusty-snake** [comment]
Wait, you use `--private`.
> **--private**
> Mount _new_ /root and _/home/user_ directories in _temporary filesystems_. All modifications are discarded when the sandbox is closed.

"New /home/user in a temporary filesystem" means empty.

**Comment by trancemind65** [comment]
it was "noexec ${HOME}"... thanks for the help.

I moved the waterfox folder to another folder, now it works.

(SOLVED)
