### ISSUE TITLE
Opera FireJail-profile network problem

### ISSUE THREAD

**Issue by trancemind65** [netblue30/firejail#3050]
Hi!

How can I fix that here:

firejail --private --dns=84.200.69.80 --dns=84.200.70.40 opera

Reading profile /etc/firejail/opera.profile
Reading profile /etc/firejail/opera-base.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 19907, child pid 19908

DNS server 84.200.69.80
DNS server 84.200.70.40

Child process initialized in 151.94 ms

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

While handling crash: can't execute crash inspector.

Parent is shutting down, bye...

opera.profile:

```
caps.drop all
caps.keep sys_admin,sys_chroot
machine-id
netfilter

# nodbus
nodvd
nogroups
notv
?BROWSER_DISABLE_U2F: nou2f
shell none

disable-mnt
private-dev
#private-etc fonts
# private-tmp - problems with multiple browser sessions

# the file dialog needs to work without d-bus
?HAS_NODBUS: env NO_CHROME_KDE_FILE_DIALOG=1
```

What must I add to my profile to fix "Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted"?

---

EDIT by @rusty-snake: code-block for profile.

**Comment by rusty-snake** [comment]
Probably you need to drop `caps.drop all`.

**Comment by rusty-snake** [comment]
> **--caps.drop=capability,capability,capability**
Define a custom blacklist Linux capabilities filter.

> **--caps.keep=capability,capability,capability**
Define a custom whitelist Linux capabilities filter.

**Comment by rusty-snake** [comment]
`caps.keep CAPS` mean remove all caps except of the once listed in CAPS.

**Comment by trancemind65** [comment]
I have also problems to run a video-slot game on online casino.

The game opened but no connection to game server.

Is there a way to fix that in the Opera.profile, maybee CAPS?

**Comment by trancemind65** [comment]
without FireJail, the online game works.

**Comment by rusty-snake** [comment]
> maybee CAPS?

Try removing all `caps*` lines. Probably it is `--dns=...` maybe this site wants ISP-DNS. Does it work with `firejail --noprofile opera`? What firejail verison do you use?

**Comment by trancemind65** [comment]
firejail --noprofile --private --dns=84.200.69.80 --dns=84.200.70.40 opera

loads...
but same problem.

I suppose it could also be in connection with my Opera AppArmor profile.

Which CAPS do I need for network in my Opera FireJail profile? Idea?

 In Opera AppArmor profile:

	network tcp,
	network inet stream,

	network udp,
	network inet dgram,

Maybee I did a mistake or forgot to add something.

firejail version 0.9.58.2

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

**Comment by rusty-snake** [comment]
> Which CAPS do I need for network in my Opera FireJail profile? Idea?

see `man capabilities` for what caps are and which exists. but I don't think that caps are the issue here.

> In Opera AppArmor profile:

IPv6?

**Comment by trancemind65** [comment]
I don't use IPv6 so I deny it in Opera AppArmor profile:

	deny network inet6 stream,
	deny network inet6 dgram,

	audit deny "@{PROC}/[0-9]*/net/if_inet6" r,
	audit deny "@{PROC}/[0-9]*/net/ipv6_route" r,

**Comment by trancemind65** [comment]
I don't know what this error means:

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
While handling crash: can't execute crash inspector.

Must I add network protocol/network-caps to my Opera FireJail profile?

**Comment by rusty-snake** [comment]
The IPv6 idea was that the site maybe requires ipv6.

The error message looks like the opera (chromium) sandbox conflicts with AA or FJ.

**Comment by Vincent43** [comment]
> I suppose it could also be in connection with my Opera AppArmor profile.

Could you try disabling it? In general mixing external apparmor profile with firejail is not supported and usually leads to trouble. You can use `--apparmor` option to load generic apparmor profile as a companion to firejail. You may also use your external apparmor profile without firejail.

**Comment by trancemind65** [comment]
...I have it:

firejail --noprofile --nogroups --private=/path-to/ --private-dev --private-tmp --ipc-namespace --machine-id --noroot --caps.drop=all --seccomp --nosound --no3d opera --no-sandbox

Must be changed:

--private=/path-to/

Any path, for example:

/home/user/Opera-Jail/

Re-create the path first:

Example:

/home/user/Opera-Jail/

**Comment by rusty-snake** [comment]
@trancemind65 
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
