### ISSUE TITLE
security: wrong behaviour of firejail for an empty `whitelist`

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#306]
firejail does NOT enable its filesystem sandboxing mechanism if a `whitelist` filter does not correspond to already-existing files.

Steps to reproduce:
* create a profile with `whitelist ${HOME}/abcd1234`
* launch `firejail --profile=new.profile ls -al /home/user`
* observe all files being visible to the sandboxed process

Expected:
* the last command should only return .bashrc and .Xauthority. Because there are no matches between `whitelist` and files an the real FS, the expected behavior is to start with `--private`.

**Comment by manevich** [comment]
Looks like you are using old version, try one from git.
This behaviour already fixed, see issue #276.

**Comment by vn971** [comment]
Indeed, I'm using the last stable release (.38). Will update. Thanks!
