### ISSUE TITLE
Virtualbox "Effective UID is not root"

### ISSUE THREAD

**Issue by RedAtRareCandy** [netblue30/firejail#3063]
On Arch Linux, after installing Virtualbox package and Firejail, the only way I can "Start" a VM is if I run Virtualbox from Command Line using /usr/bin/virtualbox.

If I run it via Firejail, even with the --noprofile flag, the following prompt appears when pressing Start on a VM.

![Screenshot from 2019-11-26 10-55-15](https://user-images.githubusercontent.com/10075847/69596219-db353180-103c-11ea-9820-53cdcdafe516.png)

**Comment by rusty-snake** [comment]
Has you changed anything in `/etc/firejail/firejail.config`?
What is the output of `firejail --debug --noprofile virtualbox`?

**Comment by RedAtRareCandy** [comment]
Hi rusty-snake,

Wow, you nailed it in one. I had the force-nonewprivs flag enabled in /etc/firejail/firejail.config. Setting this back as the default (no/disabled) has resolved the issue.

Apologies for this - and thanks for pointing me in the right direction!
