### ISSUE TITLE
Monitor network connection attempts with firejail/firemon

### ISSUE THREAD

**Issue by curioustwo** [netblue30/firejail#3066]
Hi,
Is it possible to monitor outgoing network connections with either firejail or firemon? I would like to know which network connections an application is trying to make when it is "firejail'ed".

Thanks!

**Comment by netblue30** [comment]
It is quite easy, but you have to start the sandbox with a network namespace (--net). For example:
`````
$ firejail --name=mybrowser --net=eth0 firefox
`````
Then, you open a new terminal and join the network namespace with some network monitor such as tcpdump:
`````
$ sudo firejail --join-network=mybrowser tcpdump
`````
The command runs as root (sudo).

You can also try wireshark. It used to work for me on the old Debian, but on the new one it doesn't. I guess it has to do with the way they set up X11, so I get something like:
`````
~$ sudo firejail --join-network=mybrowser wireshark
Switching to pid 9548, the first child process inside the sandbox
Child process initialized in 8.57 ms
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0.0
Could not connect to any X display.
`````

**Comment by rusty-snake** [comment]
@curioustwo 
I'm closing here due to inactivity, please fell free to reopen if you have more questions.

**Comment by curioustwo** [comment]
I had a follow-up question. To do this without having the APP access Internet at all I would have to create a virtual eth interface or something? I want to monitor the attempts but not let it go through....
