### ISSUE TITLE
bin bash + not a directory - firejail is shutting down

### ISSUE THREAD

**Issue by trancemind65** [netblue30/firejail#3067]
Hi!

I can't run:

firejail --noprofile --nogroups --private=/path-to/ --private-dev --private-tmp --machine-id --noroot --caps.drop=all --seccomp --nosound --no3d /home/user/waterfox/waterfox

Output:
/bin/bash: /home/user/waterfox/waterfox: No such file or directory

This command works:
firejail --noprofile --dns=84.200.69.80 --dns=84.200.70.40 /home/user/waterfox/waterfox

What I've made wrong?

**Comment by smitsohu** [comment]
The likely reason is that you did not copy the waterfox binary inside the `/path-to/` directory. It needs to exist inside the sandbox.

**Comment by trancemind65** [comment]
ah ok

**Comment by trancemind65** [comment]
and why is that here working:

firejail --noprofile --dns=84.200.69.80 --dns=84.200.70.40 /home/user/waterfox/waterfox

**Comment by rusty-snake** [comment]
because there is no `--private=...`.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/issues/3047#issuecomment-556009503

**Comment by rusty-snake** [comment]
@trancemind65 
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
