### ISSUE TITLE
firejail firefox: Permission denied

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [netblue30/firejail#3069]
BTW,
```
~: ls /usr/bin/firejail
-rwsr-x---  1 root firejail
```
Is it normal?

**Comment by Vincent43** [comment]
On some distros firejail usage is restricted to `firejail` group. You have to add your user there and re-login:
`sudo gpasswd -a <user> firejail`.

What distro do you use?

**Comment by rusty-snake** [comment]
@GreatBigWhiteWorld 
I'm closing here due to inactivity, please fell free to reopen if you have more questions.

**Comment by GreatBigWhiteWorld** [comment]
Sorry, forgot to reply after making the change. Yeah I just had to add me in the firejail group.
