### ISSUE TITLE
do not allow to start with incompatible settings: `whitelist` and `private`

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#307]
The setting `whitelist ${HOME}/***` is absolutely incompatible with `private`.

Please do not allow starting firejail with such a profile, possibly explaining the error. Reasoning: it's better to fail/stop fast for a security tool than to provide an "wrong"/strange behavior.

**Comment by manevich** [comment]
I think there no incompatibility, just `--private` option takes precedence, as more restricting one.
For example, you can use stock profile with `whitelist`, and `--private` option together to temporary get more restricting jail without rewriting profile.
Or even write new profile like this
```
include /etc/firejail/app.profile
private
```
to get everything from standard profile, but empty $HOME

**Comment by vn971** [comment]
Hm. Ook, I think you're right, I was too quick with jumping to conclusions. The current behavior makes sense from that point of view.
