### ISSUE TITLE
make install-strip broken

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3070]
OS: Fedora 30
`sudo make install-strip` doesn't work, while `sudo make install` work.

Error:
```
strip src/firejail/firejail
strip:src/firejail/firejail[.gnu.build.attributes]: corrupt GNU build attribute note: wrong note type: bad value
make: *** [Makefile:165: install-strip] Fehler 1
```

If no one can confirm this, I assume that the issue is on my system. Just close in this case. If anyone can confirm this, we should consider to fix it or at least use `install-strip` in the README.

**Comment by M83tUt3** [comment]
I can't replicate this on F30. I'm doing the actual compiling inside a toolbox but running `make install-strip` works fine both from inside as well as outside the container ($HOME is shared between the two).

**Comment by rusty-snake** [comment]
OK, looks like the issue is on my system.

**Comment by Futureknows** [comment]
On my F32 this was due to the old firejail git download directory being already full. Deleted contents then it ran fine.
