### ISSUE TITLE
please either allow "$HOME" along with "${HOME}" in profiles or signal error

### ISSUE THREAD

**Issue by jonleivent** [netblue30/firejail#3071]
I have made this same error several times now:

`blacklist $HOME/something-private`

 silently doesn't blacklist anything.  No error is printed.  Of course:

`blacklist ${HOME}/something-private`

and

`blacklist ~/something-private`

both work.  I would greatly appreciate it if firejail either accepted $HOME in such contexts, or signaled an error.  Yes, I know everyone is entitled to their own DSL...

**Comment by netblue30** [comment]
Printing an error:
`````
$ cat p.profile
blacklist $HOME/.ssh

$ firejail --profile=p
Reading profile p
Parent pid 4893, child pid 4895
Error: $HOME is not allowed in profile files, please replace it with ${HOME}
Error: proc 4893 cannot sync with peer: unexpected EOF
Peer 4895 unexpectedly exited with status 1
