### ISSUE TITLE
KDE apps causing seccomp violations (name_to_handle_at)?

### ISSUE THREAD

**Issue by smitsohu** [netblue30/firejail#3074]
A while back there was a report about Qutebrowser issuing `name_to_handle_at` syscalls, which broke the app in sandboxes started with the default seccomp filter (#2302). 

On one system I have now many KDE apps (e.g. Gwenview, Dolphin, Baloo) that are also broken because of the blacklisted `name_to_handle_at` syscall, which seems to suggest that something in Qt changed recently.

Can someone confirm this?

The affected system is Debian Buster, kernel from backports (5.3.9-2~bpo10+1 (2019-11-13))
Qt 5.11.3, KDE Frameworks 5.54.0

**Comment by Vincent43** [comment]
I tested on gwenview and it works normal. Except kernel they rest of system spec you listed are pretty ancient so this doesn't look like change in qt/kde libs.

My system spec: Arch Linux, linux 5.4.2, Qt 5.13.2, KDE Frameworks 5.64.0.

**Comment by smitsohu** [comment]
> Except kernel they rest of system spec you listed are pretty ancient so this doesn't look like recent change in qt/kde libs.

Right! It is a Debian after all.

**Comment by FOSSONLY** [comment]
I'm using Debian-Testing myself and so far I've noticed that Qt or anything based on Qt is treated with seemingly little priority. KDE is very sensitive about this, and doesn't run smoothly or show strange bugs when Qt isn't up to date. I don't know why this always takes forever until there are updates, or what blocks it. Everything based on GTK behaves radially differently, and enjoys very timely updates.

**Comment by smitsohu** [comment]
Nothing relevant for the release. I caused it myself. These apps wanted access to /run/udev, which I didn't grant them, and as a result they started calling `name_to_handle_at`.
