### ISSUE TITLE
configure script breaks

### ISSUE THREAD

**Issue by matu3ba** [netblue30/firejail#3075]
Upon running `./configure`commit acd14b8f4f9055fea09997438ca733f9b7cdf14d broke master with

hecking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for ranlib... ranlib
./configure: line 3076: syntax error near unexpected token `newline'
./configure: line 3076: `AX_CHECK_COMPILE_FLAG('

Can anybody else reproduce?

Line 3021 looks edgy, but it might be easier to recreate the automake output.

**Comment by glitsj16** [comment]
@matu3ba I commented with the same issue in https://github.com/netblue30/firejail/commit/acd14b8f4f9055fea09997438ca733f9b7cdf14d. Until there's a proper fix you can unbreak git master by running `autoreconf -vfi` prior to configure.

**Comment by netblue30** [comment]
Thanks @glitsj16, @matu3ba. I've seen the comment. I have no idea what's going on. The script was generated on a Debian stable. I've seen the problem a few months ago, then it disappeared. To fix it locally I used to run"autoreconf -i --install".

I generated a new configure script on Debian 8 and checked it in (https://github.com/netblue30/firejail/commit/8c4a8801e4cc1904cf45a8ec05cbeef067856ffd)

**Comment by Fred-Barclay** [comment]
Just checked on Arch, all good now. :smile:

**Comment by matu3ba** [comment]
Thanks @netblue30 for the fast fix. On Manjaro it works for me now. I would suggest to close this bug after the proper fix was tested.

**Comment by glitsj16** [comment]
Fixed via https://github.com/netblue30/firejail/commit/8c4a8801e4cc1904cf45a8ec05cbeef067856ffd, closing.
