### ISSUE TITLE
--name option no longer works

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#308]
Looks like recent commits broke support for the --name option. I see the below both when using the --name option from cli and when setting name in a *.profile file under ~/.config/firejail:

$ firejail --name=firefox --private=$HOME firefox
Reading profile /home/dirkos/.config/firejail/firefox.profile
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-terminals.inc
Reading profile /etc/firejail/whitelist-common.inc
Error: cannot create /run/firejail/name/2197

$ firejail --version
firejail version 0.9.39

$ ls -l /run/firejail
dr-x------ 2 root root 40 Feb 19 22:28 firejail.ro.dir
-r-------- 1 root root  0 Feb 19 22:28 firejail.ro.file
drwxr-xr-x 2 root root 40 Feb 19 22:28 mnt

The above output is from a machine running Arch Linux, but I get the exact same error(s) on a Ubuntu machine, both running latest firejail from git.

**Comment by glitsj16** [comment]
EDIT: after updating to current git things are back to normal. Please regard the above as obsolete.

**Comment by netblue30** [comment]
No problem, I was moving things around lately!
