### ISSUE TITLE
commits/changes to backport/cherry-pick to 0.9.62

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3089]
https://github.com/netblue30/firejail/compare/release-0.9.62...master

- [x] 6552519
- [x] 37ac96c + d0b3e2b
- [x] 8199725
- [x] 2ec700c
- [x] 99dbf08

**Comment by netblue30** [comment]
Yes, check them in, and anything else you find. I'll start building on Dec 27 (Friday).

**Comment by glitsj16** [comment]
Added
- [x] https://github.com/netblue30/firejail/pull/3083
- [x] https://github.com/netblue30/firejail/pull/3088

**Comment by rusty-snake** [comment]
You was faster :grin:  20s :racing_car:

**Comment by glitsj16** [comment]
@rusty-snake Haha, that'll be a first! Keep up the great job you're doing here, thanks for adding this as an issue :+1:

**Comment by rusty-snake** [comment]
3343d89 + 7302908 ?

**Comment by glitsj16** [comment]
@rusty-snake Done. Those slipped under my radar. Thanks!
