### ISSUE TITLE
Error: line 2 in the custom profile is invalid

### ISSUE THREAD

**Issue by BCOH** [netblue30/firejail#309]
I just installed the new version of Firejail firejail_0.9.38_1_amd64.deb but now when I try to start Firefox I get the error: Error: 
   - Command name #firefox#
   - Found firefox profile in /etc/firejail directory
   - Reading profile /etc/firejail/firefox.profile
   - Error: line 2 in the custom profile is invalid

Here is the profile from the firejail directory in the error above. 

# Firejail profile for Mozilla Firefox (Iceweasel in Debian)
noblacklist ${HOME}/.mozilla
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
caps.drop all
seccomp
protocol unix,inet,inet6,netlink
netfilter
tracelog
noroot
whitelist ${DOWNLOADS}
whitelist ~/.mozilla
whitelist ~/.cache/mozilla/firefox
whitelist ~/dwhelper
whitelist ~/.zotero
whitelist ~/.lastpass
whitelist ~/.vimperatorrc
whitelist ~/.vimperator
whitelist ~/.pentadactylrc
whitelist ~/.pentadactyl
whitelist ~/.keysnail.js
whitelist ~/.config/gnome-mplayer
whitelist ~/.cache/gnome-mplayer/plugin
include /etc/firejail/whitelist-common.inc

# experimental features
#private-etc passwd,group,hostname,hosts,localtime,nsswitch.conf,resolv.conf,gtk-2.0,pango,fonts,iceweasel,firefox,adobe,mime.types,mailcap,asound.conf,pulse

I was unable to locate any information about the error. System spec. Kubuntu 15.10 & FF 44.0.2

Thanks in advance

**Comment by netblue30** [comment]
Can you please run "firejail --debug firefox" in a terminal and put the output here. Thanks.

**Comment by BCOH** [comment]
Output from firejail --debug firefox

firejail --debug firefox
Command name #firefox#
Found firefox profile in /etc/firejail directory
Reading profile /etc/firejail/firefox.profile
Error: line 2 in the custom profile is invalid
