### ISSUE TITLE
U2F not working

### ISSUE THREAD

**Issue by ibahnasy** [netblue30/firejail#3092]
U2F doesn't work if Firefox is launched with firejail.
Even `firejail --ignore=private-dev firefox` didn't solve the issue.
There should be a permanent fix in the firejail profile file for Firefox.

**Comment by rusty-snake** [comment]
`grep "browser-disable-u2f" /etc/firejail/firejail.config` #2531. Firejail version?

**Comment by ibahnasy** [comment]
I set it `browser-disable-u2f` to `no` and now it works.
Thanks a lot!

**Comment by ibahnasy** [comment]
But the u2f key has to be plugged first before launching Firefox! 
Any solution to this case?

**Comment by rusty-snake** [comment]
What happens with
- remove u2f key
- start firefox with `firejail --noprofile firefox`
- add u2f key
- test u2f

**Comment by ibahnasy** [comment]
In this scenario, the u2f works fine.

**Comment by SkewedZeppelin** [comment]
private-dev prevents any devices attached after sandbox creation to not be available.

**Comment by cockytrumpet** [comment]
I found this issue trying to solve the same problem with my Yubikey, but firefox would crash when I press the button to authenticate even with `browser-disable-u2f` set to no. 

The solution was to remove `sys_name_to_handle_at` from the seccomp list. 

I’m sure there’s a better way to do that, but adding `seccomp.keep sys_name_to_handle_at` to firefox.local didn’t work.

**Comment by Vincent43** [comment]
Did you added some custom rules to firefox profile? This sounds similar to https://github.com/netblue30/firejail/issues/3074#issuecomment-563013316

**Comment by rusty-snake** [comment]
> I’m sure there’s a better way to do that, but adding `seccomp.keep sys_name_to_handle_at` to firefox.local didn’t work. 

`seccomp.keep` "whitelist" syscall, this means every syscall not listed is blocked.

Replace `seccomp` with:
Firejail >=0.9.61: `seccomp !sys_name_to_handle_at`
Firejail <=0.9.60: `seccomp.drop @debug,@obsolete,@privileged,@resources,add_key,fanotify_init,i@cpu-emulation,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,ni_syscall,open_by_handle_at,remap_file_pages,request_key,syslog,umount,userfaultfd,vmsplice`

**Comment by cockytrumpet** [comment]
@Vincent43 The only other change I made to the profile was removing `#?BROWSER_DISABLE_U2F: nou2f` which i saw in https://github.com/netblue30/firejail/issues/2531.

- Gentoo kernel 5.4.6
- firejail 0.9.60-r1
- firefox 71.0-r1

@rusty-snake Thanks, I misunderstood what .keep was doing.

**Comment by rusty-snake** [comment]
@ibahnasy 
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.

**Comment by ibahnasy** [comment]
How does using no profile affects the security `firejail --noprofile firefox`?

**Comment by rusty-snake** [comment]
You have no seccomp, all caps, no disable-*, ...

**Comment by Vincent43** [comment]
`--noprofile` is very close to not using firejail at all.
