### ISSUE TITLE
sort.py breaks on older python3 versions

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3099]
After building firejail from git I always run the `sort.py` script from contrib to catch regressions. Usually I do this on my main Arch machine. That has python 3.8 and the script runs without issues. Recently I happened to run the checks on a Ubuntu 16.04 LTS machine, which has python 3.5 and saw it break:

```
$ /usr/lib/firejail/sort.py
File "/usr/lib/firejail/sort.py", line 77
    fixed_line = f"{line[:12]}{sort_alphabetical(line[12:])}"
                                                                                                     ^
SyntaxError: invalid syntax
```

@rusty-snake Perhaps we can support the handy script on older python versions?

**Comment by rusty-snake** [comment]
Yes, the only new python feature in this script are format-strings (3.6+)  replacing these with the "old" .format works with 3.4 and 3.5 (only tested these two).

[sort.py.patch.txt](https://github.com/netblue30/firejail/files/4006950/sort.py.patch.txt) _GitHub why is .patch denied? :scream_cat:_

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/blob/8cd87fb5d69006d7aa832b445b21a18f767c44dd/contrib/sort.py#L22-L23

**Comment by glitsj16** [comment]
@rusty-snake Thanks for the patch!
