### ISSUE TITLE
firejail gedit doesn´t work anymore

### ISSUE THREAD

**Issue by Rosika2** [netblue30/firejail#3104]
Hi altogether and a Happy New Year, 

today I got a firejail-update to version 0.9.62.

And suddenly **gedit** doesn´t work anymore:

```
rosika@rosika-Lenovo-H520e ~> firejail gedit
Reading profile /etc/firejail/gedit.profile
Reading profile /etc/firejail/allow-common-devel.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 4239, child pid 4240
Standard C library installed in 5964884344832.00 ms
Program libraries installed in 137.96 ms
GdkPixbuf installed in 83.61 ms
GTK3 installed in 50.74 ms
Pango installed in 0.01 ms
GIO installed in 6.20 ms
Enchant (speller) installed in 5.99 ms
Installed 131 libraries and 10 directories
Blacklist violations are logged to syslog
Child process initialized in 414.70 ms
gedit: error while loading shared libraries: libgtksourceview-3.0.so.1: cannot open shared object file: No such file or directory

Parent is shutting down, bye...


```

As a workaround I copied the **default.profile** to **~/.config/firejail** and renamed it **gedit.profile** so that this profile is used.
That way gedit works again.

Yet it would be nice if the gedit.profile could be fixed somehow.

Greetings.
Rosika

P.S.:
my system: Lubuntu 18.04.3 LTS, 64 bit

**Comment by rusty-snake** [comment]
Can you try adding `libgtksourceview-3.0.so.*´ to the `private-lib` line.

**Comment by Rosika2** [comment]
@rusty-snake:
Hi and thank you.
I did what you suggested and now I get a new error:
```
[...]
gedit: error while loading shared libraries: libpeas-gtk-1.0.so.0: cannot open shared object file: No such file or directory
```
Should I do the same with this one?

**Comment by Fred-Barclay** [comment]
Hi @Rosika2 
Yes, please add that to private-lib as well.

**Comment by Rosika2** [comment]
@rusty-snake :

Hooray it works. Thanks a lot for your help especially on a holiday.

The last line in the gedit.profile now looks like this:
`private-lib aspell,gconv,gedit,libgspell-1.so.*,libreadline.so.*,libtinfo.so.*,libgtksourceview-3.0.so.*,libpeas-gtk-1.0.so.*`
which turns out to be the correct setting, at least in my system.

Many greetings.
Rosika

**Comment by rusty-snake** [comment]
@glitsj16 If I do `ls -l /usr/lib64/libgtksourceview*` I get
```
/usr/lib64/libgtksourceview-2.0.so.0 -> libgtksourceview-2.0.so.0.0.0
/usr/lib64/libgtksourceview-2.0.so.0.0.0
/usr/lib64/libgtksourceview-3.0.so.1 -> libgtksourceview-3.0.so.1.8.0
/usr/lib64/libgtksourceview-3.0.so.1.8.0
/usr/lib64/libgtksourceview-4.so.0 -> libgtksourceview-4.so.0.0.0
/usr/lib64/libgtksourceview-4.so.0.0.0
```
should we already add `libgtksourceview-4` to be future-proof?

**Comment by glitsj16** [comment]
> should we already add libgtksourceview-4 to be future-proof?

@rusty-snake I guess for future-proofing we just might get away with adding `libgtksourceview-*`. Let's ask @Rosika2 if that is a workable solution too.

**Comment by Rosika2** [comment]
@glitsj16:
I´ve just tried it out.
When adding **only**  `libgtksourceview-*` to the _private-lib_-line it still doesn´t work.:

`[...] 
private-lib aspell,gconv,gedit,libgspell-1.so.*,libreadline.so.*,libtinfo.so.*,libgtksourceview-*` 
yields
```
[...]
gedit: error while loading shared libraries: libpeas-gtk-1.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by rusty-snake** [comment]
@Rosika2 I was not about dropping `libpeas-gtk-1.0.so.*`, the idea was to include also the upcoming version 4 of libgtksourceview.

```
private-lib aspell,gconv,gedit,libgspell-1.so.*,libgtksourceview-*,libpeas-gtk-1.0.so.*,libreadline.so.*,libtinfo.so.*
```

**Comment by Rosika2** [comment]
@rusty-snake:
Hi, sorry, I misunderstood.
I now replaced the _private-lib_ line with the entries you provided.
I can confirm that it works just fine. So adding` libgtksourceview-*`, as glitsj16 suggested, seems
to work flawlessly.

Thanks for all the help of yours.
Greetings.
Rosika

**Comment by glitsj16** [comment]
@Rosika2 @rusty-snake Thanks for confirming libgtksourceview-* works. Fixed.
