### ISSUE TITLE
whitelist-usr-share-common.inc breakage

### ISSUE THREAD

**Issue by polyzen** [netblue30/firejail#3107]
firejail 0.9.62

The `whitelist-usr-share-common.inc` inclusion is causing the following issues:

- mpv cannot use Vulkan (amdvlk)
```
[vo/gpu/vulkan/libplacebo] Failed creating instance: VK_ERROR_EXTENSION_NOT_PRESENT
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan instance
```

- WeeChat cannot use Perl.
```
perl: error: Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /usr/lib/perl5/5.30/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.30/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.30/core_perl /usr/share/perl5/core_perl)
```

**Comment by glitsj16** [comment]
> WeeChat cannot use Perl

You should be able to fix this easily by adding `whitelist /usr/share/perl5` to a _weechat.local_ file. Either in /etc/firejail or ${HOME}/.config/firejail. I'll add a fix in git master shortly. 

> mpv cannot use Vulkan (amdvlk)

A fix for this would be similar to the above (in _mpv.local_), but I haven't got a machine to quickly check what path(s) under /usr/share mpv needs access to with Vulkan. Can you check your system and report back please? In any case, thanks for reporting this here!

**Comment by glitsj16** [comment]
@polyzen This got auto-closed due to committing a fix for weechat. Reopening to try to do the same for your mpv/Vulkan issue.
