### ISSUE TITLE
mupdf profile not working for mupdf-gl

### ISSUE THREAD

**Issue by q3cpma** [netblue30/firejail#3110]
Hello,

I've found that the mupdf profile was probably made for the `mupdf-x11` only and didn't work with `mupdf-gl` one, which is becoming the standard. To "fix" it, you need to remove `private-etc alternatives,fonts`, otherwise I get:
```
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib64/dri)
libGL error: failed to load driver: radeonsi
libGL error: failed to open /dev/dri/card0: Permission denied
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib64/dri)
libGL error: failed to load driver: swrast
```
which is strange.

And `memory-deny-write-execute` just makes it freeze during loading.

I guess the profile should handle the whole different binary thing, but I'm not sure why that private-etc would break things like this.

**Comment by q3cpma** [comment]
Oh yeah, I'm using firejail 0.9.62 on Gentoo.

**Comment by rusty-snake** [comment]
Thx for the rerport


> And `memory-deny-write-execute` just makes it freeze during loading.

We should commentd mdwe and leave a note.

> To "fix" it, you need to remove `private-etc alternatives,fonts`

This is a very short private-etc line, we should extend it to fix it. Can you run `firejail --build mupdf-gl` and post the private-etc line from the output (it is at the end of this huge output).

**Comment by q3cpma** [comment]
On Fri, Jan 03, 2020 at 02:03:07AM -0800, rusty-snake wrote:
> Thx for the rerport
>
>
> > And `memory-deny-write-execute` just makes it freeze during loading.
>
> We should commentd mdwe and leave a note.
>
> > To "fix" it, you need to remove `private-etc alternatives,fonts`
>
> This is a very short private-etc line, we should extend it to fix it. Can you run `firejail --build mupdf-gl` and post the private-etc line from the output (it is at the end of this huge output).

It produces `private-etc passwd,drirc,`. Really don't know where it comes from, that problem existed with qtwebengine at some point because `/usr/lib/llvm/*` wasn't properly whitelisted.

**Comment by rusty-snake** [comment]
Can you try with `private-etc alternatives,fonts,drirc` and if this does not work add `passwd`. /etc/drirc contains infos/configs about "drivers".

https://github.com/netblue30/firejail/blob/08d99279428041f20f922c7df2c9df574ec34bda/etc/templates/profile.template#L169

**Comment by q3cpma** [comment]
On Fri, Jan 03, 2020 at 02:45:40AM -0800, rusty-snake wrote:
> Can you try with `private-etc alternatives,fonts,drirc` and if this does not work add `passwd`. /etc/drirc contains infos/configs about "drivers".

Doesn't work. By adding ld.so.cache to private-etc, it does. There's probably a mesa/opengl specific incl to use to get it, right?

**Comment by rusty-snake** [comment]
Does this work? `private-etc alternatives,fonts,drirc,glvnd,bumblebee,nvidia,ld.so.cache,ld.so.conf,ld.so.conf.d,ld.so.preload`

**Comment by q3cpma** [comment]
Yes, but like I said, I only needed `ld.so.cache` (should probably add ld.*). But it looks like a hack to specify it that way.

**Comment by q3cpma** [comment]
Ah, looks like there's no common file for it, indeed.

**Comment by q3cpma** [comment]
Now, the real problem is that firejail should use `$(basename -- "$(readlink -f -- "$1")")` as binary name to find the appropriate profile, then use the symlink name.

**Comment by rusty-snake** [comment]
> Yes, but like I said, I only needed `ld.so.cache` (should probably add ld.*). But it looks like a hack to specify it that way.

So for you it is `private-etc alternatives,fonts,ld.so.cache`, right?

**Comment by q3cpma** [comment]
On Fri, Jan 03, 2020 at 06:43:05AM -0800, rusty-snake wrote:
> > Yes, but like I said, I only needed `ld.so.cache` (should probably add ld.*). But it looks like a hack to specify it that way.
>
> So for you it is `private-etc alternatives,fonts,ld.so.cache`, right?

Yes, but I added the rest of ld.*. The .cache might disappear anytime.
