### ISSUE TITLE
celluloid: Failed to create DBus connection

### ISSUE THREAD

**Issue by reagentoo** [netblue30/firejail#3117]
It seem it's necessary to remove `nodbus` from the celluloid.profile:
Please see a log: https://gist.githubusercontent.com/reagentoo/674ff89cba8b2421ce25b3c0454df02c/raw/1ab28cef591939af53a982956c4b9bbe5a762fd9/firejail-celluloid-nodbus.log

**Comment by rusty-snake** [comment]
b7487015
