### ISSUE TITLE
Can't load libstdc++.so.6 due to private-etc (Gentoo)

### ISSUE THREAD

**Issue by reagentoo** [netblue30/firejail#3118]
`ERROR: ffmpeg: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`

Affected applications: celluloid, evince, youtube-dl

My temporary fix is to remove next lines:
celluloid.profile:
```
private-etc alternatives,ca-certificates,crypto-policies,dconf,drirc,fonts,gtk-3.0,hosts,libva.conf,localtime,machine-id,pkcs11,pki,resolv.conf,selinux,ssl,xdg
```
evince.profile:
```
private-etc alternatives,fonts,group,machine-id,passwd
private-lib evince,gconv,gdk-pixbuf-2.*,gio,gvfs/libgvfscommon.so,libdjvulibre.so.*,libgconf-2.so.*,libgraphite2.so.*,libpoppler-glib.so.*,librsvg-2.so.*,libspectre.so.*
```
youtube-dl.profile:
```
private-etc alternatives,ca-certificates,crypto-policies,hostname,hosts,mime.types,pki,resolv.conf,ssl,youtube-dl.conf
```

**Comment by reagentoo** [comment]
Adding `ld.so.cache` to `private-etc` solve this. But except for evince:
```
Warning fldd: cannot find libstdc++.so.6, skipping...
Warning fldd: cannot find libgcc_s.so.1, skipping...
```

**Comment by glitsj16** [comment]
> Adding `ld.so.cache` to private-etc solve this. But except for "evince":
Warning fldd: cannot find libstdc++.so.6, skipping...
Warning fldd: cannot find libgcc_s.so.1, skipping...

@reagentoo Hi, thanks for reporting. The evince profile also has `private-lib`. Can you try if that works when adding `libgcc_s.so.*,libstdc++.so.*` to it?

**Comment by reagentoo** [comment]
@glitsj16 Hi.
Adding `libgcc_s.so.*,libstdc++.so.*` to `private-lib` does not helps.
I've tried to add `,gcc` instead of them (This dir contains this libs). So I can see pdf images in the application after that, but I still see this warnings that I showed above.

**Comment by glitsj16** [comment]
@reagentoo Maybe evince needs more than ld.so.cache in private-etc on gentoo. Try adding `ld.so.*` to its _private-etc_ too (besides keeping either 'libgcc_s.so.*,libstdc++.so.*' or 'gcc' in _private-lib_). That should cover ld.so.cache, ld.so.conf, ld.so.conf.d and ld.so.preload.

**Comment by glitsj16** [comment]
I've gone ahead and merged https://github.com/netblue30/firejail/pull/3120. If you still have functional issues with evince on gentoo, please feel free to reopen. Thanks again for your cooperiation.
