### ISSUE TITLE
Strange pathname behaviour 

### ISSUE THREAD

**Issue by adrianlshaw** [netblue30/firejail#3119]
I've been trying to sandbox an application that looks for a file in ``${HOME}.local/foobar/``. Without any sandbox it finds the file. 

But within firejail (private-etc enabled in the profile and file path whitelisted) the application itself says it can't find the file in `/.local/foobar/`. Yes, that's a leading slash. It genuinely has no business looking for filenames in the root directory, so somewhere there must be a bug that misses out the "home/username" part of the path.

I'm unsure if this is a bug in the application or with firejail. Am I missing something obvious?

**Comment by rusty-snake** [comment]
Which applications? Also with --noprofile?

> I'm unsure if this is a bug in the application or with firejail.

Probably a bug the applications that occurs inside firejail because of some environment changes.

**Comment by adrianlshaw** [comment]
It's the "barrier" program. I've been further hardening it by giving its own private etc and limiting access to the home directory. I have the rules ready but this issue is stopping progress and it's a peculiar one.

Adding a dodgy symlink to the root filesystem sadly does make it work, but isn't a good solution. Firejail isn't (and probably shouldn't be) in the business of setting up symlinks in private filesystems. Guess the next step is for me to look through the barrier source code.

**Comment by rusty-snake** [comment]
still an issue?

**Comment by adrianlshaw** [comment]
Not made any progress. Closing for now until I can confirm if it's a firejail issue.

**Comment by Vincent43** [comment]
Did you tried without `private-etc` and/or whitelisted home or even with `--noprofile`?
