### ISSUE TITLE
name2pid does not handle spaces

### ISSUE THREAD

**Issue by Sidnioulz** [netblue30/firejail#312]
name2pid will automatically cut at the first space it encounters in a name, even though names are not checked for absence of spaces when the sandbox is launched.

I partially got around the issue by detecting if there is another option after the name, but there is no safe way to detect the name in situations like this: `firejail --name=some name firefox`. See https://github.com/Sidnioulz/firejail/commit/77428367aa413b706e5dac743417e3de8b6ba309

Some additional solutions to make it more robust:

- A more elaborate check could abort stating that the sandbox name is ambiguous when not followed by an option
- An empty `--` option could be used to delineate the firejail options and command
- Some additional strstr's could be used to detect short options (-h) if any is supported in the future

**Comment by netblue30** [comment]
Bug! Thanks.

**Comment by netblue30** [comment]
You need to put it into quotes:
`````
$ firejail --name="some name"
$ firejail --join="some name"
`````
or you can escape the blank space:
`````
$ firejail  --name=some\ name
$ firejail --join=some\ name
`````

**Comment by Sidnioulz** [comment]
There are a few situations where it's difficult to call Firejail that way, namely when using APIs like GDesktopAppInfo or GSpawn from the GLib, or when using any sort of desktop launchers that expect a full command line. In those situations, if you quote the name then Firejail will literally process the name as being `"Some name"` rather than `Some name`. Automatically unquoting arguments likely to have spaces would be another way to solve this issue.

**Comment by ivan** [comment]
FWIW `--name="some name"` in a shell is the same as passing `"--name=some name"`, maybe try that from GLib?

**Comment by Sidnioulz** [comment]
Brilliant, this syntax does the job. Nothing to fix then :-)

On 21 February 2016 at 17:44, Ivan Kozik <notifications@github.com> wrote:

> FWIW --name="some name" in a shell is the same as passing "--name=some
> name", maybe try that from GLib?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netblue30/firejail/issues/312#issuecomment-186870695>.
>



-- 
Steve Dodier-Lazaro
PhD Student
University College London
Free Software Developer
