### ISSUE TITLE
evince.profile issues (Gentoo)

### ISSUE THREAD

**Issue by reagentoo** [netblue30/firejail#3121]
@glitsj16 Hi.
I've tested again the profile after your commit (https://github.com/netblue30/firejail/pull/3120/commits/bd7394f6e5a23c6bf68b37b74c5f786ee16b4712). And as I said in our previous discussion (https://github.com/netblue30/firejail/issues/3118) `libgcc_s.so.*,libstdc++.so.*` does not solve.
I can view PDFs only if `,gcc` used in `private-lib`. But It's not properly way to fix I think (not removes warnings).

Also may be it's necessary to remove `nodbus` due to line in log:
```
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
```

**Comment by glitsj16** [comment]
> Also may be it's necessary to remove nodbus due to line in log:
> 
> Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
> 

@reagentoo Hi again. Let's tackle this one first. As the warning and the comment inside /etc/firejail/evince.profile states `net none` only has confirmed issues on Ubuntu with AppAmor. On Gentoo you can add `net none` to your evince.local. That should take care of the D-BUS warning. Firejail also has the `--audit` option to check/confirm that:
`
$ firejail --audit /usr/bin/evince
`

> I can view PDFs only if `,gcc` used in private-lib. But It's not properly way to fix I think (not removes warnings).

If adding `gcc` is the only way to get evince working on Gentoo, I'll happily add it. IMHO it shouldn't impact the strength of the profile. Besides that it doesn't remove the warnings, does evince work for you with all its functionalities if you add gcc to private-lib?

**Comment by rusty-snake** [comment]
IIRC you can do `private-lib gcc/something/libstdc++.so` which will add `/usr/lib/libstdc++.so` in the sandbox.

**Comment by reagentoo** [comment]
@glitsj16 
> As the warning and the comment inside /etc/firejail/evince.profile states net none only has confirmed issues on Ubuntu with AppAmor.

Actually I have both enabled sandboxes AppArmor and Firejail on Gentoo.

> On Gentoo you can add net none to your evince.local. That should take care of the D-BUS warning.

I've gotten log without DBus warning after adding this.

> Besides that it doesn't remove the warnings, does evince work for you with all its functionalities if you add gcc to private-lib?

Right.

**Comment by glitsj16** [comment]
@reagentoo OK, that leaves fixing `private-lib` as tight as possible. Did you test @rusty-snake's suggestion if it works when you add libstdc++.so.* and libgcc_s.so.* using the full sub-path under /usr/lib/gcc yet?

**Comment by reagentoo** [comment]
I've tested this lines:
```
gcc/x86_64-pc-linux-gnu/8.3.0/libstdc++.so.*,gcc/x86_64-pc-linux-gnu/8.3.0/libgcc_s.so.*

gcc/x86_64-pc-linux-gnu/*/libstdc++.so.*,gcc/x86_64-pc-linux-gnu/*/libgcc_s.so.*

gcc/*/*/libstdc++.so.*,gcc/*/*/libgcc_s.so.*
```
All of this is works for me. You need to decide which way is more acceptable.

**Comment by glitsj16** [comment]
@reagentoo The `gcc/*/*/libstdc++.so.*,gcc/*/*/libgcc_s.so.*` syntax should be the best one to future-proof the evince profile on Gentoo. Thanks again for your cooperation!
