### ISSUE TITLE
Digikam broken

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#3124]
Digikam 6.4.0 doesn't start here on Arch Linux. 

After modifying the profile it works again:

```
ignore seccomp
seccomp.keep access,arch_prctl,bind,brk,capget,capset,chdir,chmod,chroot,clock_getres,clock_gettime,clone,close,connect,creat,dup,dup2,epoll_create1,epoll_ctl,epoll_wait,eventfd2,execve,exit,exit_group,fadvise64,fallocate,fchmod,fcntl,fdatasync,flock,fstat,fstatfs,ftruncate,futex,getcwd,getdents64,getegid,geteuid,getgid,getpeername,getpgrp,getpid,getppid,getpriority,getrandom,getresgid,getresuid,getsockname,getsockopt,gettid,getuid,inotify_add_watch,inotify_init,inotify_init1,inotify_rm_watch,ioctl,kill,linkat,lseek,lstat,madvise,memfd_create,mkdir,mmap,mprotect,msync,munmap,nanosleep,newfstatat,openat,pipe,pipe2,poll,ppoll,prctl,pread64,prlimit64,pwrite64,read,readlink,readlinkat,recvfrom,recvmsg,rename,rmdir,rt_sigaction,rt_sigprocmask,rt_sigreturn,sched_getaffinity,sched_getparam,sched_get_priority_max,sched_get_priority_min,sched_getscheduler,sched_setaffinity,sched_setscheduler,seccomp,sendmsg,sendto,setpriority,set_robust_list,setsockopt,set_tid_address,shmat,shmctl,shmdt,shmget,shutdown,socket,socketpair,stat,statfs,statx,sysinfo,times,umask,uname,unlink,unshare,wait4,waitid,write,writev
```
Can someone reproduce?

**Comment by Vincent43** [comment]
Works for me.

**Comment by curiosity-seeker** [comment]
> Works for me.

What exactly? The original profile or my modifications?

**Comment by rusty-snake** [comment]
@curiosity-seeker which syscall is blocked with the original profile? `journalctl --grep=SECCOMP --reverse`

**Comment by curiosity-seeker** [comment]
Okay, checked again. 

`seccomp !chroot`

seems to work.

**Comment by Vincent43** [comment]
> What exactly? The original profile or my modifications?

Original profile works for me out of the box.

**Comment by smitsohu** [comment]
Seems that QtWebengine is a [dependency](https://www.archlinux.org/packages/extra/x86_64/digikam) via [marble-common](https://www.archlinux.org/packages/extra/x86_64/marble-common)

@Vincent43 Do you see an effect if you enable unprivileged user namespaces?

**Comment by Vincent43** [comment]
> Do you see an effect if you enable unprivileged user namespaces?

Yes, this is it. After enabling unprivileged user namespaces I can reproduce the results.
