### ISSUE TITLE
cannot combine --private with --private=

### ISSUE THREAD

**Issue by jonleivent** [netblue30/firejail#3126]
The options `--private` to remove all persistence and `--private=dir` to set the home dir could be combined.  Currently, regardless of their order on the command line, combining them results in the normal `--private=dir` behavior with persistence.  Furthermore, firejail does not currently print anything to stderr saying that the two settings are in conflict.  And the doc (man page) doesn't say anything about which private-like features can or cannot be combined.

**Comment by jonleivent** [comment]
Oops - forgot.  Firejail 0.9.58.2 in Debian buster.

**Comment by jonleivent** [comment]
Elaborating on the use case:  I've set up a home dir for an app, and typically run it with just --private=that-home-dir, but in some cases would like the same configuration without persistence.  In those cases, the jailed app should see the same home, with all of its config, but with no persistence.

**Comment by Vincent43** [comment]
The assumptions behind `--private` is that app won't know of any existing user data which prevent leaking it so it's not valid option for your usecase. I think what you want is `--overlay-tmpfs` however I'm not sure if it works alongside `--private=dir`, please try to test it.

I agree that incompatibility between `--private` and `--private=dir` should be documented.

**Comment by jonleivent** [comment]
I tried --overlay-tmpfs with --private=dir and got:
> Warning: private=directory feature is disabled in overlay
and it put me in an overlay without the private dir.

BTW: I was playing with --overlay-tmpfs to see if I could work with it in other ways, and noticed that it blocks out other mount points.  Specifically, I had something fuse mounted, and in the overlay, the mount point appeared empty.

**Comment by rusty-snake** [comment]
```patch
--- a/src/man/firejail.txt
+++ b/src/man/firejail.txt
@@ -1442,6 +1442,7 @@ $ firejail \-\-private firefox
 .TP
 \fB\-\-private=directory
 Use directory as user home.
+--private and --private=directory cannot be used together.
 .br
 
 .br
```
