### ISSUE TITLE
Failed to use AppImage binary with firejail: Cannot mount AppImage, please check your FUSE setup.

### ISSUE THREAD

**Issue by gcoimbra** [netblue30/firejail#3127]
**Describe the bug**
I'm unable to run AppImage binaries with firejail. The error is below:

```
***reading default rules**
Parent pid 18618, child pid 18619
Child process initialized in 12.24 ms
fusermount: mount failed: Operation not permitted

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory

Parent is shutting down, bye...

```

**To Reproduce**

Just run any AppImage with the default profile.

**Additional context**

We can fix this by not using the below line in the profile of AppImages:

`protocol unix,inet,inet6`

**Comment by rusty-snake** [comment]
Did you start it with `--appimage`?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
