### ISSUE TITLE
Firejail and libpng / setjmp(png_jmpbuf) (cannot save PNG)

### ISSUE THREAD

**Issue by Sidnioulz** [netblue30/firejail#313]
I cannot save PNG files from within a Firejail sandbox. Tested with xfce4-screenshooter, and with GIMP. The issue appears to be that the setjmp(png_jmpbuf) system call fails, inside gdk-pixbuf's implementation of PNG file saving (see io-png.c::real_save_png for the implementation).

**Comment by netblue30** [comment]
How do you run it? Are you starting GIMP/xfce4-screenshooter from Firefox?

**Comment by Sidnioulz** [comment]
I usually just firejail into a Bash session and work from there. The problem occurs with or without the generic profile, and regardless of whether I spawn a bash and work from the Bash or call the apps directly (e.g. firejail gimp).

**Comment by netblue30** [comment]
What distro are you running? I doesn't happen on on Debian 8. Also, what project is io-png.c::real_save_png  coming from, I'd like to take a look. Thanks!

**Comment by Sidnioulz** [comment]
I'm running ArchLinux,4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux.

https://git.gnome.org/browse/gdk-pixbuf/tree/gdk-pixbuf/io-png.c would contain said code. If you can't reproduce I can try and identify the faulty code lines in GIMP's xcf/jpg saving routines too, albeit not immediately.

**Comment by netblue30** [comment]
I'll look into it, thanks!

**Comment by Fred-Barclay** [comment]
I can create/save .png images with Gimp or mate-screenshot, using the gimp and default profiles, on 64-bit Arch running the 4.13 kernel. Let's close for now. 😄
