### ISSUE TITLE
Concise command output for documentation purpose

### ISSUE THREAD

**Issue by Ricky-Tigg** [netblue30/firejail#3135]
Using Linux, I attempt to document relevant functions I use into my project: `firejail --version` is one of them.

Enhancement suggestion: concise commands output:s

- Current output:
```
$ firejail --version
firejail version 0.9.57

Compile time support:
	- AppArmor support is disabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

$ 
```

- Concise  output 1:
```
$ firejail --version
firejail version 0.9.57 (<release_date>)

Compile time support:
 Disabled supports:
- AppArmor
 Enabled supports:
- AppImage 
- chroot 
- file and directory whitelisting 
- file transfer 
- networking 
- overlayfs 
- private-home 
- seccomp-bpf 
- user namespace 
- X11 sandboxing 
$ 
```
- Concise  output 2:
```
$ firejail --version
firejail version 0.9.57 (<release_date>)

Compile time support:
 Disabled supports: AppArmor
 Enabled supports: AppImage – chroot – file and directory whitelisting – file transfer – networking – overlayfs – private-home – seccomp-bpf – user namespace 
- X11 sandboxing 
$ 
```
Mention `Wayland sandboxing` is not present; would this mean that Wayland server is not detected thus not part of the compile time support?

**Comment by rusty-snake** [comment]
> Using Linux, I attempt to document relevant functions I use into my project: `firejail --version` is one of them.
> 
> Enhancement suggestion: concise commands output:s
> 
>     * Current output:
> 
> 
> ```
> $ firejail --version
> firejail version 0.9.57
> 
> Compile time support:
> 	- AppArmor support is disabled
> 	- AppImage support is enabled
> 	- chroot support is enabled
> 	- file and directory whitelisting support is enabled
> 	- file transfer support is enabled
> 	- networking support is enabled
> 	- overlayfs support is enabled
> 	- private-home support is enabled
> 	- seccomp-bpf support is enabled
> 	- user namespace support is enabled
> 	- X11 sandboxing support is enabled
> 
> $ 
> ```
> 
>     * Concise  output 1:
> 
> 
> ```
> $ firejail --version
> firejail version 0.9.57 (<release_date>)
> 
> Compile time support:
>  Disabled supports:
> - AppArmor
>  Enabled supports:
> - AppImage 
> - chroot 
> - file and directory whitelisting 
> - file transfer 
> - networking 
> - overlayfs 
> - private-home 
> - seccomp-bpf 
> - user namespace 
> - X11 sandboxing 
> $ 
> ```
> 
>     * Concise  output 2:
> 
> 
> ```
> $ firejail --version
> firejail version 0.9.57 (<release_date>)
> 
> Compile time support:
>  Disabled supports:
> AppArmor
>  Enabled supports:
> AppImage – chroot – file and directory whitelisting – file transfer – networking – overlayfs – private-home – seccomp-bpf – user namespace 
> Mention `Wayland sandboxing` is not present; would this mean that Wayland server is not detected thus not part of the compile time support?

Wayland is sandboxed by design.

**Comment by Ricky-Tigg** [comment]
On operating systems, such as Fedora, Red Hat, and Centos, Apparmor's counterpart, SELinux, does operate. Thus a mention related to support status regarding AppArmor is irrelevant then its presence as output appropriately not needed.. This is a suitable target for an enhancement

**Comment by Vincent43** [comment]
This is information if apparmor support was enabled during compiling firejail not if system had apparmor support.

**Comment by Ricky-Tigg** [comment]
Hey. Afterwards, I realise that "Compile time support:" was certainly explicit enough; I then interpreted it wrong since I understood it to cover components that are supported in user's OS. Is it then so that a component whose support was enabled during Firejail compile time will be supported as well in user's OS?

There is indeed no apprmor component on my system and appimage is supported.  Are those cases then coincidences?
```
$ dnf -q repoquery --archlist noarch,x86_64 list *apparmor*

$ firejail --appimage --private --noprofile ./arduino
Mounting appimage type 1
Parent pid 2958, child pid 2961

**     Warning: dropping all Linux capabilities     **
[...]
```
What could be then the context in firejail command lines regard Apparmor on Open(SUSE) systems , since those systems do have support for Apparmor?

**Comment by rusty-snake** [comment]
> There is indeed no apprmor component on my system and appimage is supported. Are those cases then coincidences?

Apparmor and appimage have absolutely no relation to each other (except that both are for linux)

**Comment by Vincent43** [comment]
> I then interpreted it wrong since I understood it as follow: listed components that may be supported in user's OS will have either support or not in firejail commands. Is it then so that a component whose support was enabled during Firejail compile time will be supported as well in user's OS?

 `firejail --version` doesn't show what user OS support. You can run `firejail --version` for the same binary on fedora and opensuse and the output will be the same.

**Comment by Ricky-Tigg** [comment]
Sure; However I meant regards to that `firejail --version` output 
 ```
	- AppArmor support is disabled
	- AppImage support is enabled
```
