### ISSUE TITLE
firejail firefox & spotify

### ISSUE THREAD

**Issue by nsauter** [netblue30/firejail#3137]
Hi,

even this is not sure a firejail problem im hoping somebody can help me a little bit. I startet firejail firefox with a new private directory `firejail --private=/var/tmp/firefox firefox`

This works pretty well overall but i cannot use the spotify web player. If i log in and install the DRM Plugin it seems ok, but if i try to play music the play button wont work and its logging me out every 30 sec. Youtube and Netflix are working. Do you guys have an idea? Plain Firefox with same Settings (Proxy) does work.

**Comment by Vincent43** [comment]
What distro and what firejail version?

**Comment by nsauter** [comment]
Fedora 31, firejail-0.9.56-9

Vincent43 <notifications@github.com> schrieb am Fr., 10. Jan. 2020, 17:34:

**Comment by Vincent43** [comment]
Is selinux enabled? Could you check if it blocks something?

**Comment by nsauter** [comment]
Selinux is completely disabled.

**Comment by rusty-snake** [comment]
`firejail --writable-var --keep-var-tmp --private=/var/tmp/firefox firefox`?

**Comment by nsauter** [comment]
Sounds good, doesn't work. WhatsApp Web wont load QR Code too with firefox, but if i use google-chrome Browser _everything_ works.

**Comment by rusty-snake** [comment]
`firejail --writable-var --keep-var-tmp --ignore='noexec ${HOME}' --ignore='noexec /var' --private=/var/tmp/firefox firefox`?

`firejail --private=/var/tmp/firefox --noprofile firefox`?

**Comment by domker** [comment]
DRM Widevine on Spotify (Firefox) doesn't work too when "private-etc" is uncommented in config files. 
I think it's the same bug.
In previous versions it worked correctly.

ArchLinux (linux-5.4.13), Firefox 72.0.1, Firejail 0.9.62

**Comment by Vincent43** [comment]
@domker could you try modifying private-etc [like this](https://github.com/netblue30/firejail/commit/bc337e2330730e8ed8f2673398b11f41b50ee04f#diff-383a52be2035d0d98dd5815c58689138R57)?

**Comment by rusty-snake** [comment]
@nsauter @domker still an issue?

**Comment by chiraag-nataraj** [comment]
> Sounds good, doesn't work. WhatsApp Web wont load QR Code too with firefox, but if i use google-chrome Browser _everything_ works.

QR code not working sounds like a `privacy.resistFingerprinting` problem to me. You can fix that by doing `privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts` to `false`.

**Comment by rusty-snake** [comment]
Or just allow it. Click on the icon left to `https:` in the urlbar.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
