### ISSUE TITLE
Problem with firefox nightly auto-update

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#3140]
On Manjaro(KDE) firefox-nightly & firefox-beta don't get auto update if running inside firejail. Can you suggest any work-around? Btw, without firejail, firefox can auto update.

[On Manjaro auto update looks like](https://imgur.com/1RAD6wm)

**Comment by rusty-snake** [comment]
https://i.imgur.com/1RAD6wm.jpg

How do you install firefox?

**Comment by Neo00001** [comment]
Downloaded d tar file from firefox & extracted it to /opt & made a launcher that's it. I have done same thing on debian also, same location & same profile.

**Comment by Neo00001** [comment]
Without apparmor, auto update works properly. So, when I have to update I use, 

`firejail --ignore=apprmor /path/firefox`

**Comment by Vincent43** [comment]
In general profiles are developed with assumption that apps are installed through package managers like apt. If you download binaries yourself and put it in some arbitrary directory then some things may stop working. I think we can't really help other than propose above workaround.

**Comment by rusty-snake** [comment]
@Vincent43 since your the AppArmor expert here, allows the apparmor profile writing in /opt?


@Neo00001 as @Vincent43 said, we can't do really more here.

**Comment by Vincent43** [comment]
AppArmor blocks writing in `/opt`. Usually files in `/opt` are owned & writable only by root but I guess in this case firefox folder was copied with user ownership and permissions. AppArmor profile also blocks execution from writable directories so allowing writing to `/opt` would violate this rule.

**Comment by Neo00001** [comment]
@rusty-snake  & @Vincent43 thanks for clarifying. & I was just looking for a work-around. blocking writing to /opt is preferable.
btw,I have omitted out debian related lines.If you don't have any problem, you may close this.
