### ISSUE TITLE
Keepass: synchronization broken

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#3141]
Keepass has a nice synchronization feature - an example is shown [here](https://keepass.info/help/kb/trigger_examples.html#dbsync). I'm using it to automatically save the newest version of the database on the drive of my email provider on order to synchro it with my iPhone.

Unfortunately, this doesn't work with the provided Firejail profile. But adding `netlink`to the protocol line did the trick:

`protocol unix,inet,inet6,netlink`

**Comment by rusty-snake** [comment]
Thanks for the report.
