### ISSUE TITLE
Handle "non-standard" login.defs paths better

### ISSUE THREAD

**Issue by danieru98** [netblue30/firejail#3145]
On function init_uid_gid_min firejail tries to open /etc/login.defs. But on opensuse for example they recently moved this file to /usr/etc/login.defs https://lizards.opensuse.org/2019/12/05/yast-sprint-90/
This means that firejail will fail in the case where /etc/login.defs is not found and a user with uid/gid other than 1000 attemps to run it.

pclinux might also be affected http://www.pclinuxos.com/forum/index.php?topic=146992.0

**Comment by glitsj16** [comment]
@danieru98 Great detective work, thank you for reporting this. I've tested a quick patch but that didn't pan out well. Let's hope that by marking this as a bug the main C collaborators can come up with a proper fix sooner rather than later.

**Comment by glitsj16** [comment]
@smitsohu Sorry to bother you (again), but have you seen this? Looks rather urgent and complicated, but I'm not the best to judge as I've never came close to an actual opensuse machine...

**Comment by smitsohu** [comment]
Creating a second /etc hierarchy inside /usr is a quite significant change. It's not only about `login.defs`, there is also an impact on `private-etc` and maybe other options.

@danieru98 Do I understand it right that if there is a file `/etc/login.defs` it will take precedence over `/usr/etc/login.defs`?

**Comment by smitsohu** [comment]
Thanks for the issue!
