### ISSUE TITLE
Immutable ~/.mozilla with persistent ~/Downloads

### ISSUE THREAD

**Issue by BreakfastSerial** [netblue30/firejail#3146]
I want to use firejail with Firefox, having a temporary home and an immutable Firefox but keep all Downloads. The use-case isn't for high-security operations, but for daily use, so `--ls`, `--get` and `--put` are not really viable.

I did come across the following related issues:

- https://github.com/netblue30/firejail/issues/3139
- https://github.com/netblue30/firejail/issues/1716

However none of these resulted in appropriate solutions.

I've tried the following

`firejail --read-only=~/.mozilla --whitelist=~/Downloads firefox`
This is also mentioned in the man page of firejail, but for me firefox isn't operable like this, as Firefox states `"Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system."`. Even if I use Firefox with the `-no-remote` parameter.

`firejail --private-home=~/.mozilla,~/Downloads --whitelist=~/Downloads firefox`
Doesn't allow persistent Downloads.

I've tried setting Firefox to use `/downloads` (in the root directory) for all downloads, which doesn't seem to be a sane solution, but doesn't work anyways, as downloads fail to said directory without error message.

Is there any way to have to have my downloads directory persistent but have all other modifications discarded when the sandbox is closed?

firejail version 0.9.58.2
Mozilla Firefox 72.0.1
Ubuntu 19.10

**Comment by rusty-snake** [comment]
> but for me firefox isn't operable like this, as Firefox states "Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system.". Even if I use Firefox with the -no-remote parameter.

With an ro profile this seems reasonable to me.

> Is there any way to have to have my downloads directory persistent but have all other modifications discarded when the sandbox is closed?

untested idea:
`firejail --profile=firefox --read-only='${HOME}/.mozilla' firefox --no-remote --ProfileManager`
Create a new profile in /tmp (`private-tmp`).

**Comment by BreakfastSerial** [comment]
Thank you for your input.

I've tried the following: `firejail --profile=firefox --read-only='${HOME}/.mozilla' firefox -P "custom-user"`. This resulted in persistent downloads (in ~/Downloads) but also in persistent changes for Firefox! The browser history was written and add-ons changes were stored.

**Comment by Vincent43** [comment]
I don't think firefox can function without being able to write into its config. You could use `firejail --overlay-tmpfs --ignore=private-tmp firefox`, download things to `/tmp` and move them somewhere else manually.

**Comment by BreakfastSerial** [comment]
That sounds like it would be a reasonable trade-off between usability and security! I'll give it a try, thank you!

**Comment by dpellegr** [comment]
Hello,

I am in a similar situation where I need a temporary folder and a persistent folder, both writable from the sandbox.

Unfortunately the workaround proposed by @Vincent43 does not work for me. Indeed am using `--private-tmp` to store stuff which should be isolated between multiple sandboxes. In addition, as the persistent folder is used for logs (which are continuously written), it would really be better to have them in place, instead of having to periodically synchronize them, with chances of loosing (part of) them.

It doesn't seem conceptually difficult, but I am lost in the myriad of options... Any idea?

**Comment by rusty-snake** [comment]
For now you maybe can use `--private-cache`, which makes ~/.cache a tmpfs. In the future: #3676.
