### ISSUE TITLE
ffmpeg.profile needs ld.so.cache on arch linux

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#3147]
Arch Linux needs `ld.so.cache` added to `private-etc` in `ffmpeg.profile`. Otherwise it gives:
```
$ ffmpeg
/usr/bin/ffmpeg: error while loading shared libraries: libmfx.so.1: cannot open shared object file: No such file or directory
```

**Comment by rusty-snake** [comment]
Fixed, Thanks.

**Comment by rusty-snake** [comment]
@glitsj16 I pinned this issue for now, so people see it (hopefully).

**Comment by Vincent43** [comment]
The problem should be fixed in Arch Linux soon without need for changes in firejail: https://bugs.archlinux.org/task/65238 although the workarounds would be still useful to keep for similar cases in future.

**Comment by florianbegusch** [comment]
> Arch Linux needs `ld.so.cache` added to `private-etc` in `ffmpeg.profile`. Otherwise it gives:
> 
> ```
> $ ffmpeg
> /usr/bin/ffmpeg: error while loading shared libraries: libmfx.so.1: cannot open shared object file: No such file or directory
> ```

For some reason the package changed the location to [/usr/lib](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/intel-media-sdk&id=79ee9971dc419ba02a249ee763866ad741538127) again.  
ffmpeg runs fine without ```ld.so.cache,ld.so.conf,ld.so.conf.d,ld.so.preload``` again. Probably any other program depending on it would too.
