### ISSUE TITLE
 firejail torbrowser - no videos on many websites

### ISSUE THREAD

**Issue by mq2yy9t33** [netblue30/firejail#3158]
firejail PATH/tor-browser_en-US/Browser/start-tor-browser launches TBB904 but videos (or the
player) are not loading properly. no timeline and play button, file download is offered instead of
playing OR no video file found. happens on many websites e.g. xhamster.com, pornhub.com -
youtube works.

same in --private or --overlay-tmpfs mode

firejail 0.9.62
tor browser bundle TBB 9.0.4
platform archlinux

**Comment by Vincent43** [comment]
I guess this is another victim of [ffmpeg changes in Arch](https://github.com/netblue30/firejail/issues/3147).

**Comment by Vincent43** [comment]
Should be fixed by https://github.com/netblue30/firejail/commit/bc337e2330730e8ed8f2673398b11f41b50ee04f . You may copy those changes to  `/etc/firejail/start-tor-browser.profile` manually until new firejail release.

**Comment by mq2yy9t33** [comment]
yes, another victim. workaround applied - tested - works.
thank you very much!
