### ISSUE TITLE
Creating folder copy

### ISSUE THREAD

**Issue by inflamous** [netblue30/firejail#316]
Is there an option that copies files/folders and discards them when the sandbox is closed?  I used to use "private-home" and copying the ".mozilla" and ".cache/mozilla/firefox" folder but I can't find a similar option now that its deprecated.

I also tried using "whitelist" followed by "read-only" for these folders but it just caused firefox to say that my profile is already in use.

**Comment by netblue30** [comment]
Witelist+read-only will not work. Run a script like this:
`````
#!/bin/bash
cd ~
rm -fr tmpfirefox
mkdir tmpfirefox
cp -a .mozilla tmpfirefox/.mozilla
firejail --private=tmpfirefox firefox
`````

**Comment by inflamous** [comment]
Thanks, it works great!
