### ISSUE TITLE
Bad quality audio with --noprofile and PCSX2

### ISSUE THREAD

**Issue by adrianlshaw** [netblue30/firejail#3165]
PCSX2 is a video game emulator. When running `firejail --noprofile PCSX2` the sound quality is a complete noisy mess. The application console is littered with many entries that say `ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred`

This doesn't happen outside firejail. Any ideas on how to further debug or fix this? Is ALSA running in some fallback or degraded mode?

**Comment by glitsj16** [comment]
> Any ideas on how to further debug or fix this? Is ALSA running in some fallback or degraded mode?

Firejail has several _debug_ options explained in more detail in the man page. But with --noprofile my guess is those won't show very much. AFAIK neither ALSA nor sound in general are crippled in any way, at least not with a default profile. Codebase does however seem to rely on / assumes usage of PulseAudio.

It might be more informative if you'd be able to supply logs/output of the commands you've tried. When using the --noprofile option, Firejail uses /etc/firejail/default.profile (and what gets included by that file. I'd try to test again by making a local copy of it in `${HOME}/.config/firejail/default.local` file in which you start out completely blank (so commenting out everything that is in `default.profile`). Keep enabling options one by one and report back if that changes anything, for the better hopefully... Also, can you show us what version of firejail you are seeing this on, and the OS?

**Comment by adrianlshaw** [comment]
Thanks for the tip! I actually misunderstood the —noprofile option because I thought it would use no profile at all, rather than default.profile. Will check that.

**Comment by Vincent43** [comment]
I think there was some misunderstanding here because `--noprofile` works as you thought and doesn't use `default.profile`.

**Comment by glitsj16** [comment]
@adrianlshaw I misinformed you here, my apologies. See @Vincent43's statement above.

**Comment by rusty-snake** [comment]
@adrianlshaw still need help?

**Comment by adrianlshaw** [comment]
Yes, what should I try next? I could try on a different distro that may have different versions of ALSA...

**Comment by Vincent43** [comment]
Maybe firejail [built-in blacklist](https://github.com/netblue30/firejail/blob/afb7e0363bd630f12773876d486afed4ad485ad7/src/firejail/fs.c#L623) block some alsa functionality on your system. Could you take a look if there is something alsa-related in `/sys/firmware`?

Maye try `firejail --noprofile --noblacklist=/sys/module PCSX2`

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.

**Comment by adrianlshaw** [comment]
Thanks for reminding me @rusty-snake . I tried @Vincent43's suggestion but that didn't make a difference. I can't re-open the issue due to lack of privileges :-)

**Comment by rusty-snake** [comment]
You cloud try my noprofile.profile, but I don't think that this works. Likely that there is a general incompatibility.
```
# - Make sure firejail.config has no changes.
# - The sandbox still have an own PID-namespace.

allow-debuggers
allusers
#keep-dev-shm
#keep-var-tmp
#noautopulse
writable-etc
writable-run-user
writable-var
writable-var-log

noblacklist /sys/fs
noblacklist /sys/module
```

**Comment by adrianlshaw** [comment]
I think this issue can be closed. These underruns and crackling only seem to occur before a game starts. The game I just tried seems fine after initial launch. I'll reopen if I see further issues.
