### ISSUE TITLE
Yubikey won't be detected if plugged in after launching Firefox

### ISSUE THREAD

**Issue by ibahnasy** [netblue30/firejail#3170]
If a yubikey is inserted after launching Firefox with firejail, it won't be detected as U2F device at all.
It has to be plugged in BEFORE launching the browser.
Also if the key is removed and re-inserted while the browser is running, it won't function too.

**Comment by rusty-snake** [comment]
Duplicate of #3092

**Comment by rusty-snake** [comment]
Remove `nou2f` and `private-dev` from your firejail profile.

```
echo "ignore private-dev" >> ~/.config/firejail/firefox.local
sudo sh -c "echo 'browser-disable-u2f no' >> /etc/firejail/firejail.config
```

**Comment by SkewedZeppelin** [comment]
I do not like 32c3669, exposes too much.
Either we should add another conditional or a comment.

**Comment by rusty-snake** [comment]
> I do not like 32c3669, exposes too much.

@SkewedZeppelin the default is no usf in browser => `private-dev` is set unless a user adds `browser-disable-u2f no`.

```
# Disable U2F in browsers, default enabled.
# browser-disable-u2f yes
```

**Comment by odkr** [comment]
I encountered that issue w/ firefail 0.9.76 on Void Linux. The solution was to add `ignore noinput` to firefox-common.local.
