### ISSUE TITLE
Directory read-only even after noblacklist/whitelist

### ISSUE THREAD

**Issue by q3cpma** [netblue30/firejail#3173]
Hello,

I'm trying to use emacs in qutebrowser, and to that end, I call qutebrowser that way:
```
exec firejail \
    --noblacklist=~/.config/mpv \
    --noblacklist=~/.emacs.d \
    --whitelist=~/.config/mpv \
    --whitelist=~/.emacs.d \
    --nodbus \
    qutebrowser "$@"
```
Everything works well until I try to close emacs, where it tells me that `~/.emacs.d/history` is read-only. Using an eshell, I can't even touch a file inside `~/.emacs.d` (I get `/usr/bin/touch: cannot touch 'a': Read-only file system`), but I can in my HOME. I tried adding a `--read-write=~/.emacs.d` to no avail.
What is even stranger is that `~/.config/mpv` isn't RO.

This is on Gentoo with firejail 0.9.62

**Comment by reinerh** [comment]
The qutebrowser profiles include disable-common.inc, which has this line:
```
read-only ${HOME}/.emacs.d
```

Does it work if you call it with `--ignore='read-only ${HOME}/.emacs.d'`?

**Comment by q3cpma** [comment]
It does, thanks. Strange that I was the first to be hit by this.

**Comment by reinerh** [comment]
I can imagine the number of users of qutebrowser AND emacs AND firejail is quite small. :-)

**Comment by q3cpma** [comment]
Well, it work on the command line, but not in the profile. And ideally, I don't want the history to be overwritten, but I don't know how to do it.

**Comment by reinerh** [comment]
Adding `ignore read-only ${HOME}/.emacs.d` into the profile does not work?

**Comment by rusty-snake** [comment]
Adding `ignore read-only ${HOME}/.emacs.d` **before** `read-only ${HOME}/.emacs.d` or `read-write ${HOME}/.emacs.d` **after** `read-only ${HOME}/.emacs.d` in the profile works.

To get this ordering on the command line you need to use `--profile`:

    firejail '--noblacklist=${HOME}/.emacs.d' --profile=qutebrowser '--read-write=${HOME}/.emacs.d' qutebrowser

**Comment by q3cpma** [comment]
Indeed, it works well, but my original goal was to make it read-write while not merging back the changes. Something like --private for ~/.emacs.d, basically.
For now, I can live with a shared history, though.

**Comment by rusty-snake** [comment]
Maybe emacs supports it to places the history file in a temp-dir such as `/tmp` (with `private-tmp`) or `~/.cache` (with `private-cache`).

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
