### ISSUE TITLE
firejail is losing shell special characters in args

### ISSUE THREAD

**Issue by dionorgua** [netblue30/firejail#318]
Imagine that we've firefox that can be invoked like:
`firefox "http://example.com/test?a=b&c=d"`
Now we decided to isolate it:
`firefox --join=firefox -- firefox "http://example.com/test?a=b&c=d"`
This will open url without c=d parameter.  

And even worse. If user puts 'firejail' wrapper
This opens a way to execute some shell commands in jail like:
"http://example.com/test?a=b&ls -la /"

**Comment by netblue30** [comment]
Yes, there seem to be a problem with --join command. I'll bring a fix in. Thanks.

**Comment by netblue30** [comment]
Fixed! Give it a try and I'll reopen the bug if necessary.
