### ISSUE TITLE
zathura fails without /etc/ld.so.cache

### ISSUE THREAD

**Issue by s-hamann** [netblue30/firejail#3192]
I tried opening a PDF file in zathura. Zathura started, but could not open the document. I got the following error message on the console:
```
error: Could not load plugin '/usr/lib64/zathura/libpdf-poppler.so' (libstdc++.so.6: cannot open shared object file: No such file or directory).
error: Unknown file type: 'application/pdf'
```

I was able to resolve this by adding `ld.so.cache` to the `private-tmp` directive.
Could this please be added to the default profile?

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/commit/22f74522156f67f26d6be5c8943e905a75a7f1ee

**Comment by glitsj16** [comment]
@s-hamann After seeing this I had a first-time look at our zathura profile. It could be considerably hardened IMHO. I installed zathura on Arch and did some testing with the profile changes in #3193. Would you be willing to test that profile please? You can leave your comments, remarks etcetera in the PR.
