### ISSUE TITLE
nano [ magic_load() failed: No such file or directory ]

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3198]
When using the nano profile I noticed that the application shows the below error message on each start:

`[ magic_load() failed: No such file or directory ]`

Not sure if this negatively affects usage, but it can be confusing. Looks like this is caused by wusc, more specifically by not whitelisting /usr/share/file. That directory - on Arch at least - has /usr/share/file/misc/magic.mgc, which nano tries to get at.

**Comment by rusty-snake** [comment]
We have `/usr/share/misc` (Fedora has `/usr/share/misc/magic.mgc` and `/usr/share/misc/magic` there. If `/usr/share/file` is just the Arch path for this, we should consider to add it into wusc.

**Comment by glitsj16** [comment]
@rusty-snake Just checked 2 Arch machines. On both /usr/share/misc is an empty dir and stat shows birth dating back to 2015 and 2017. To me that looks like somewhere along the way packages used to put files there, stopped doing so and maintainers forgot to use !emptydirs (which is a makepkg configuration option to remove empty directories from a package). I agree we better add /usr/share/file to wusc as you suggest. Will take care of it shortly.
