### ISSUE TITLE
mpd problems

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#320]
From wordpress:

I’m having some difficulty in getting mpd to background properly inside firejail. Using “mpd; sleep inf;” worked before, but it’s now responding with “mpd; sleep inf;: command not found”. What is the “official” way to get this working again? Thanks!

**Comment by chiraag-nataraj** [comment]
Fixed - it was not an issue with Firejail per se - I changed the profile from private to whitelisting certain files and directories and didn't move those directories back to my actual home folder.

**Comment by netblue30** [comment]
OK, thanks!
