### ISSUE TITLE
Firefox's KeepassXC browser addon: Key exchange not successfull

### ISSUE THREAD

**Issue by ericschdt** [netblue30/firejail#3200]
If I start the Firefox with Firejail and try to connect the KeepassXC browser addon to the KeepassXC app, the addon says "key exchange unsuccessfull". 

If however the Firefox is started outside of Firejail, everything is fine.

Any idea? 

#### Additional notes
The KDEconnect browser addon runs fine with default settings + the ignore nodebus "trick".

#### System
FF 72.0.2
firejail 0.9.62
KeePassXC 2.5.2
KeepassXC Browser Addon 1.5.4
Archlinux

**Comment by glitsj16** [comment]
@ericschdt I've installed keepassxc on Arch together with its browser addon and did some testing. With the firejail profiles from current git (which is what I use daily) I could reproduce. Editing the firejail options didn't do much in this context. And then I noticed this:

```
$ cat ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/local/bin/keepassxc-proxy",
    "type": "stdio"
}
```

On my system /usr/local/bin/keepassxc-proxy does not exist, /usr/bin/keepassxc-proxy does. As soon as I edited in the correct path and restarted Firefox the problem was gone. This was my first time ever using KeepassXC, so this might be beginners luck :)

**Comment by ericschdt** [comment]
> With the firejail profiles from current git (which is what I use daily) I could reproduce. 

That's good, however unfortunately

> On my system /usr/local/bin/keepassxc-proxy does not exist, /usr/bin/keepassxc-proxy does.

both exist on my system:

```
-rwxr-xr-x 1 root root 30624  4. Jan 23:00 /usr/bin/keepassxc-proxy*
lrwxrwxrwx 1 root root 17  2. Feb 15:03 /usr/local/bin/keepassxc-proxy -> /usr/bin/firejail*
```

and 

```
 diff ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
-   "path": "/usr/bin/keepassxc-proxy",
+   "path": "/usr/local/bin/keepassxc-proxy",
    "type": "stdio"
}
```
did not help me. :-( 

I also found out that the KeepassXC browser addon always says "unsuccessful key exchange", no matter if KeepassXC is running and/or unlocked in the background.

> This was my first time ever using KeepassXC, so this might be beginners luck :)

Definitely!

**Comment by ericschdt** [comment]
> With the firejail profiles from current git (which is what I use daily) I could reproduce. 

I replaced the profiles with their git counterparts and now it works! :)

**Comment by ericschdt** [comment]
Okay, now it no longer works. I don't know what's happening and I will have to investigate more later.

**Comment by glitsj16** [comment]
@ericschdt Feel free to re-open this if after additional investigation the issue persists.

**Comment by ericschdt** [comment]
> @ericschdt Feel free to re-open this if after additional investigation the issue persists.

I could resolve the issue by adding `keepassxc-proxy` to the private-bin line in the `firefox.profile` file:
```
private-bin bash,dbus-launch,dbus-send,env,firefox,sh,which,plasma-browser-integration-host,keepassxc-proxy
```

**Comment by saddy001** [comment]
For me this worked:

```
cat ~/.config/firejail/firefox.profile
private-bin bash,dbus-launch,dbus-send,env,firefox,sh,which,keepassxc-proxy
whitelist ${RUNUSER}/org.keepassxc.KeePassXC.BrowserServer
include /etc/firejail/firefox.profile
```
Then restart Firefox. Also see #3952

**Comment by rusty-snake** [comment]
Also see https://github.com/keepassxreboot/keepassxc/discussions/6741#discussioncomment-1154242.
