### ISSUE TITLE
Can applications still take a screenshot if the application is sanboxed?

### ISSUE THREAD

**Issue by Joe23232** [netblue30/firejail#3206]
If I sandbox an application, can the application take a screenshot of my desktop or something?

**Comment by jonleivent** [comment]
See:
[https://firejail.wordpress.com/documentation-2/x11-guide/](url)

The short answer is: this is not prevented by default settings, but it can be prevented.

**Comment by rusty-snake** [comment]
Wayland: #3148

**Comment by heinrich5991** [comment]
@jonleivent The link is named after the correct target, but if you click it, you go somewhere else.

**Comment by jonleivent** [comment]
@heinrich5991 That's a strange effect!  All I did was paste the link.  I'll try again with markdown:
[https://firejail.wordpress.com/documentation-2/x11-guide/](url)

**Comment by jonleivent** [comment]
It did it again.  That's truly strange.  Will it do it as quoted text?:

> https://firejail.wordpress.com/documentation-2/x11-guide/

**Comment by jonleivent** [comment]
OK - that worked.

**Comment by rusty-snake** [comment]
Without the `[` and the `](url)` it works. Original:
```
> See:
> [https://firejail.wordpress.com/documentation-2/x11-guide/](url)
> 
> The short answer is: this is not prevented by default settings, but it can be prevented.
```

**Comment by jonleivent** [comment]
BTW - I think --x11=xorg, when the app can handle it, is sufficent to screenshooting.  It doesn't prevent as much potential X spying as xephyr or xpra, though.  Also, an attempt to do screenshooting with --x11=xorg will generate an X11 error for the app, while with xephyr and xpra the app will take a picture of its restricted screen.

**Comment by rusty-snake** [comment]
I'm closing here because the question is answered.
