### ISSUE TITLE
EncFS integration

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#321]
From  wordpress:

When I have an encrypted folder mounted using cryptkeeper (which uses EncFS), when I blacklist the mount point for a specific program, the program can see into the directory anyway. The process works fine using the .profile files in HOME$/.config/firejail/firefox.profile for any other folder, it is just ineffective on the mounted path of the encrypted volume, and lets the program see right in there and access all contents. I have tested this every way and there must be a solution somewhere.

**Comment by chiraag-nataraj** [comment]
Tested with the following:
```
$ encfs ~/.crypt ~/crypt
$ firejail --blacklist=~/crypt
$ ls -lh ~/crypt
ls: cannot open directory 'crypt/': Permission denied
```

It seems that this issue has been resolved.
