### ISSUE TITLE
Cannot open /etc/firejail/kate.profile with kate

### ISSUE THREAD

**Issue by ericschdt** [netblue30/firejail#3212]
Kate's profile seems to be very restrict. However, I see no reason to not to be able to open any files e.g. under /etc if it's not restricted by the file mode setting (rwxrwxrwx). 

`kate /etc/firejail/kate.profile` shows me a blank file and going over the context menu of kate, I ain't see the firejail folder at all. 

Is this intended? How can I make it less restrict? I don't want to edit a file under /etc necessarily with Kate (I won't run it as root), but I would like to view it with this app at least. With `cat` it's absolutely working fine.

#### System
Manjaro KDE

**Comment by rusty-snake** [comment]
`firejail --profile=kate cat /etc/firejail/kate.profile` works for me. Have you enabled the `private-etc` line? If so add `firejail`.

**Comment by ericschdt** [comment]
> `firejail --profile=kate cat /etc/firejail/kate.profile` works for me. Have you enabled the `private-etc` line? If so add `firejail`.

I hadn't, but once I uncommented, removed `machine-id` as `whitelist /var/lib/dbus/machine-id` is the wrong path or changing it to `whitelist /var/lib/dbus` and addoing `firejail` made it working. Thanks!
