### ISSUE TITLE
[Question] How to use firejail only for certain apps?

### ISSUE THREAD

**Issue by ericschdt** [netblue30/firejail#3213]
As far as I see it, once installed, firejail will try to sandbox all programs for which it has profiles. However, on one of my systems I trust most of the programs, except a few, which I would like to sandbox only, like Spotify or Steam games. 

Is there easy way to achieve this without deleting manually all symlinks in `/usr/local/bin/`? 
I haven't found a command to unsandbox all and then to sandbox just certain apps.

**Comment by rusty-snake** [comment]
```
$ sudo firecfg --clean
$ sudo ln -s /usr/bin/firejail /usr/local/bin/PROGRAM
```

**Comment by ericschdt** [comment]
That seems to be too easy. Thanks!
