### ISSUE TITLE
[Question] How to disable firejail temporarily?

### ISSUE THREAD

**Issue by ericschdt** [netblue30/firejail#3214]
I would like to test something on my system but I am afraid firejail may interfere. Is there an easy way to disable firejail (after a reboot probably) and to reenable it later?
Something like `firejail --disable` or "systemctl disable firejail"? :) 

Simply uninstalling seems not to be the desired solution as I want to keep all settings etc.

**Comment by rusty-snake** [comment]
```
$ sudo firecfg --clean
$ reboot
$ sudo firecfg # enable
```


> Simply uninstalling seems not to be the desired solution as I want to keep all settings etc.

You .local files and profiles in ~/.config/firejail are not affected by this.

**Comment by ericschdt** [comment]
As `sudo firecfg --clean` removes all kind of symlinks and `sudo firecfg` adds symlinks for which firejail has profiles,
I would have to manually write a script which sets all symlinks again to the certain apps only, which I'd like to firejail.
It seems firejail does not remember those. 

Thanks!

**Comment by rusty-snake** [comment]
```bash
#!/usr/bin/env bash
PROGRAMS=("firefox" "thunderbird" "libreoffice")
for program in "${PROGRAMS[@]}"; do
        sudo ln -s /usr/bin/firejail /usr/local/bin/"$program"
done
```
