### ISSUE TITLE
Problem running Cura-4.4.1.appimage with Firejail

### ISSUE THREAD

**Issue by FlailAway** [netblue30/firejail#3216]
Hi All, I am trying to run Cura 4.4.1.appimage within firejail, but it balks with errors.

I need to contain Cura as it bullies all/any other open Serial ports and closes them all. My Arduino IoT stuff keeps dropping Serial connections and it is just plain irritating. I have disabled all of the Cura-Marketplace add-ons (as suggested by Cura Devs) items likely to mess with the Serial ports but still it happens about one minute after starting Cura or saving an .obj or .gcode file.

firejail --appimage --private /home/tester/desktop/Cura-4.4.1.appimage
OR
firejail --appimage --private --seccomp /home/tester/desktop/Cura-4.4.1.appimage

Gives me
"Dropping all Linux capabilities and enforcing default seccomp filter"
"Segmentation fault (core dumped)"
"Parent is shutting down, bye..."

This stops Cura.

Can someone please help me with this.

Thanks

**Comment by rusty-snake** [comment]
First off put --appimage as last firejail argument: firejail --private --appimage /home/tester/desktop/Cura-4.4.1.appimage. Works it with --noprofile to start it? Is anything in the journal that gives a hint? What is you firejail version?

**Comment by FlailAway** [comment]
I am using Mint 19.3, all up to date. Thanks you for your quick reply, very much appreciated. Firjail is Version 0.9.52. Moving --appimage to the last place for an option gave the same result as above.

Where will I find the "journal?" I looked in "etc/firejail" but nothing there looks like a Log.

Using --noprofile shows 3-errors and locks up with the Cura Splash screen showing.
  "Fontconfig error: "/etc/fonts/co"nf.d/10-scale-bitmap-fonts.conf Line 72: non-double matrix element
  "Fontconfig error: "/etc/fonts/co"nf.d/10-scale-bitmap-fonts.conf Line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown expected number

Cura can be downloaded from here if you need it.
https://github.com/Ultimaker/Cura/releases

**Comment by rusty-snake** [comment]
> Where will I find the "journal?"

`journalctl --pager-end`

**Comment by rusty-snake** [comment]
Has you tested --noprofile without future arguments (except --appimage)?

**Comment by FlailAway** [comment]
> Has you tested --noprofile without future arguments (except --appimage)?

Thanks again.

Yes, both ways when testing as you suggested above. When I use --noprofile that is when I got the fonts errors and Cura-freeze I mentioned above.

There may be typos in those error lines as I have to copy them from the 3D-printing PC that is not online. But, pretty sure I have them correct.

**Comment by rusty-snake** [comment]
I can start it with this command:
`firejail --noprofile --private --net=none --nodbus --appimage Cura-4.4.1.AppImage`

Fedora 31 + firejail git.

`seccomp` requires mbind.

```
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 84: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/25-unhint-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/25-unhint-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/25-unhint-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-sans.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-serif.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
qml: TableViewSelection: index out of range
qml: TableViewSelection: index out of range
```

**Comment by FlailAway** [comment]
Hi, thanks again. The 3D printer PC does not normally have Internet access so I downloaded the .deb version 0.9.62 from SourceForge as the Repo version I had (v0.9.52) did not understand --nodbus. The v0.9.62 ran OK, but it seems too restrictive as it start Cura from new every time and I have to configure the printer each time I use it.

I suspect I was expecting too much from FireJail as I had hoped I could configure it to allow everything (load files to print and save the .gcode files to SD/USB) as usual each time I run it, but it **must** prohibit all Cura access to the Serial ports. 

I was thinking that once a Sandbox hade been built around Cura, I could just restart that same sandbox each time.

There is some errant code in Cura that is closing all the Serial ports after about a minute of starting or some time after I save a file. The Cura-devs fixed it a few versions back but it has returned in 4.4.1 and so far the devs seem to have no interest in fixing it.

Unless I can stop Cura from **all access** to the Serial ports, I guess I will just have to put it with restarting put IoT stuff many times a day. Or, move Cura to it's own PC. I might try running Cura in a VM and see if that stops it messing with the Serial ports.

Thank you very much for your efforts to get this working for me.

**Comment by rusty-snake** [comment]
You need to drop `--private` so that cura can save it's settings. With --private is $HOME a tmpfs.

**Comment by FlailAway** [comment]
> You need to drop `--private` so that cura can save it's settings. With --private is $HOME a tmpfs.

Awesome, thank you, that seems to have solved it. I can use the existing setup for Cura and so far it has not shut down any Serial ports.
