### ISSUE TITLE
`openshot.profile` needs update for `openshot` 2.5.0

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#3221]
`openshot-qt` gives errors and is unable to present file selection dialog on arch linux with the current 2.5.0 version.
stdout/stderr:
```
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
      logger:ERROR Exception in thread
     version:ERROR Failed to get version from: http://www.openshot.org/version/json/
      logger:ERROR Thread-5
      logger:ERROR :
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      logger:ERROR self.run()
      logger:ERROR   File "/usr/lib/python3.8/site-packages/openshot_qt/classes/thumbnail.py", line 98, in run
files_listview:INFO currentChanged
      logger:ERROR self.server_address = ('127.0.0.1', self.find_free_port())
files_listview:INFO updateSelection
      logger:ERROR   File "/usr/lib/python3.8/site-packages/openshot_qt/classes/thumbnail.py", line 83, in find_free_port
 files_model:INFO updating files model.
      logger:ERROR s = socket.socket()
      logger:ERROR   File "/usr/lib/python3.8/socket.py", line 231, in __init__
      logger:ERROR _socket.socket.__init__(self, family, type, proto, fileno)
      logger:ERROR OSError
      logger:ERROR :
      logger:ERROR [Errno 95] Operation not supported

timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
..continues
```

**Comment by glitsj16** [comment]
> ...
> version:ERROR Failed to get version from: http://www.openshot.org/version/json/
> ...
> logger:ERROR self.server_address = ('127.0.0.1', self.find_free_port())
>

The default openshot profile currently disables network access. Can you try with `--ignore net none --netfilter --protocol unix,inet,inet6,netlink` and report back if that changes anything?

**Comment by jose1711** [comment]
@glitsj16 yes, this workaround works. thank you

**Comment by glitsj16** [comment]
@jose1711 I'll add those needed changes for openshot 2.5.0 in a minute. Thanks for reporting this here, much appreciated! If you install firejail using your OS' package manager, just remember to remove these options after a future update so your openshot.local file stays in-sync.

**Comment by rusty-snake** [comment]
Just one question works it with `net none` + `protocol unix,inet,inet6,netlink`?

**Comment by rusty-snake** [comment]
@jose1711 @glitsj16 the thumbnail-server is started by openshot on `127.0.0.1:high-random-port`. Openshot need `inet` to create this socket for `lo` but it does not need internet access. Can you confirm this?
`firejail --net=none --protocol=unix,inet openshot-qt`

**Comment by glitsj16** [comment]
> version:ERROR Failed to get version from: http://www.openshot.org/version/json/

The above was why I assumed openshot needed full internet access. I can't test right now, as I'm on a friend's machine during the weekend.

**Comment by rusty-snake** [comment]
@glitsj16 I know that openshot has some telemetry stuff. I looked into the code of openshot (https://github.com/OpenShot/openshot-qt/blob/develop/src/classes/version.py and https://github.com/OpenShot/openshot-qt/blob/develop/src/windows/main_window.py#L2317). Openshot displays an "update available" message. IMHO it is ok to drop this support in the profile, since update are installed with your packet-manager. Maybe we can add a note like "Uncomment (or at to openshot.local) if you want telemetry and update notifications.".

**Comment by jose1711** [comment]
Running `openshot` like this
```
firejail --net=none --protocol=unix,inet openshot-qt
```
seems to work fine.

**Comment by glitsj16** [comment]
@jose1711 Thanks for confirming!
