### ISSUE TITLE
youtube-dl abruptly terminates on firejail 0.9.60-1 without saying anything; works with --noprofile; Fedora 30; youtube-dl version 2020.01.24

### ISSUE THREAD

**Issue by MystesofEternity** [netblue30/firejail#3225]
Info:
Fedora 30
Firejail version 0.9.60-1
youtube-dl version 2020.01.24

Command executed:
firejail --seccomp --netfilter=/etc/firejail/nolocal.net youtube-dl --help

Command expectation:
Help text provided by youtube-dl will show.

Command result:
Command ended without any feedback.

--noprofile works for reasons I am incapable of identifying.

Previously, I used firejail-0.9.58.2-1 and it worked flawlessly with youtube-dl.
Installing firejail-0.9.60-1 caused this issue for me. However, firejail-0.9.60-1 works flawlessly with my Firefox 72

**Comment by rusty-snake** [comment]
What happens if you start it "normal" with `firejail youtube-dl --help`?
For me this is working. Fedora 31 ytdl 2020.01.24 firejail git.

**Comment by MystesofEternity** [comment]
The problem persists even if I use just `firejail youtube-dl --help`
It might be a Fedora 30-only problem at this version of firejail D:
As much as I'd like to upgrade to Fedora 31, the Fedora 31 template for the security-oriented Xen hypervisor that I am using is still in the middle of testing and I cannot upgrade yet RIP

I'm all game if ever you need more logs or stuff from me but I'm also fine with leaving this problem in the dark since I can pretty much live with --noprofile until the Fedora 31 template that I am waiting for graduates out of testing.

**Comment by rusty-snake** [comment]
I've three points:
1. To exclude self-made issuses: has you edited any profile or .local files?
2. If you watch `journalctl --follow` while trying ytdl, is there anything related logged?
3. If none of the above helps, you will need to comment everything and uncomment line for line to find the problematic line.

**Comment by MystesofEternity** [comment]
@rusty-snake I did as you said and here are the results:
1. Nope, I have no reason to do that as of yet
2. Tried to watch `journalctl --follow` but nothing came up when I executed the commands that caused this problem.
3. After commenting out one by one, I was able to narrow it down to this line:
`private-bin youtube-dl,python*,ffmpeg`

IDK why this line causes the problem, it's quite weird. Maybe cause I don't have ffmpeg installed?

**Comment by rusty-snake** [comment]
`firejail --build youtube-dl --help | grep private-bin`

**Comment by MystesofEternity** [comment]
Executed that and got this output:
private-bin python2.7,

**Comment by rusty-snake** [comment]
Looks you have the python2 version of ytdl, thats seems to be the reason. I have the python3 version.

**Comment by MystesofEternity** [comment]
Oh what, I don't even know if I'm getting the python2 version or the python3
All I do is go to the releases page and get the plain youtube-dl
https://github.com/ytdl-org/youtube-dl/releases/download/2020.02.16/youtube-dl

I tried getting the tar.gz archive and it contained two different youtube-dl binaries; one in the main directory of the extracted archive and one located within the bin folder.

How do I tell which is the python3 version?

**Comment by rusty-snake** [comment]
You have at least four ways to install ytdl:
1. with dnf (as I do)
2. with pip
3. manually from https://github.com/ytdl-org/youtube-dl/releases
4. with wget and https://yt-dl.org/downloads/latest/youtube-dl

https://ytdl-org.github.io/youtube-dl/download.html

**Comment by rusty-snake** [comment]
> Oh what, I don't even know if I'm getting the python2 version or the python3
> All I do is go to the releases page and get the plain youtube-dl
> https://github.com/ytdl-org/youtube-dl/releases/download/2020.02.16/youtube-dl

This file uses `#!/usr/bin/env python` as shebang.
/usr/bin/python is an symlink to python3 for Arch and Fedora 31, for Debian, Ubuntu, Fedora 30, .. it is still python2.

**Comment by MystesofEternity** [comment]
Thank you for this! I have totally forgotten about that change to python defaults so this really helped me realize things.

That should just about solve this case I believe, I am grateful for your close assistance in solving this mystery!
