### ISSUE TITLE
Firefox: libGL error

### ISSUE THREAD

**Issue by curiosityseeker** [netblue30/firejail#3227]
Regardless if I execute

`firejail firefox`

or

`firejail --noprofile firefox`

on Arch Linux I'm getting the following error:

```
[2020-02-15T14:25:39Z ERROR audio_thread_priority::rt_linux] setrlimit64: 1
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
```

This does ***not*** happen if I bypass Firejail by executing `/usr/bin/firefox`(which in turn means that AppArmor is not the culprit).

**Comment by chiraag-nataraj** [comment]
What is the output of `locate libGL.so`?

**Comment by curiosityseeker** [comment]
locate libGL.so gives
```
/usr/lib/libGL.so
/usr/lib/libGL.so.1
/usr/lib/libGL.so.1.7.0
```
However, after some more digging I found that it **was** an AppArmor problem (although I didn't get that error when starting Firefox unfirejailed - strange!). I found the following in journalctl:

```
AVC apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="firefox" name="dev/dri/card0" pid=7218 comm="Renderer" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```
After adding the following flag to the AA profile:
`profile firefox /usr/lib/firefox/firefox flags=(attach_disconnected)`

the error message regrading libGL is no longer shown. (The audio_thread_priority error is stlll there, though)
