### ISSUE TITLE
problems with chromium-browser in firejail after recent update

### ISSUE THREAD

**Issue by Rosika2** [netblue30/firejail#3228]
Hi altogether,

yesterday I received a chromium-browser update. Now my current version is 80.0.3987.87.

Yet I´ve got problems when running it in firejail (version 0.9.62) which I hadn´t encountered before.
I noticed that my extension "Just Read" doesn´t work any more. It should put the displayed page in read-mode.
(Description: A feature-packed, customizable reader extension.)

But when clicking on it now it hasn´t any effect at all.

By the way: I start chromium-browser with this command: `firejail --private=/home/rosika/Dokumente/work chromium-browser` .

So I decided to give the _default.profile_-option a try, but the result was even worse:

`firejail --profile=/etc/firejail/default.profile --private=/home/rosika/Dokumente/work chromium-browser
`

```
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 8800, child pid 8801
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Child process initialized in 72.28 ms

Parent is shutting down, bye...

```
So the browser didn´t start at all.

After that I looked up journalctl and encountered the following:

```
sudo journalctl -f
  
Feb 16 13:32:02 rosika-Lenovo-H520e audit[8572]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=8572 comm="chromium-browse" exe="/usr/lib/chromium-browser/chromium-browser" sig=31 arch=c000003e syscall=161 compat=0 ip=0x7f9d2da5d839 code=0x0

Feb 16 13:32:02 rosika-Lenovo-H520e kernel: audit: type=1326 audit(1581856322.170:346): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=8572 comm="chromium-browse" exe="/usr/lib/chromium-browser/chromium-browser" sig=31 arch=c000003e syscall=161 compat=0 ip=0x7f9d2da5d839 code=0x0

Feb 16 13:32:02 rosika-Lenovo-H520e kernel: traps: chromium-browse[8563] trap int3 ip:5601d40c119b sp:7ffd81f4a3f0 error:0 in chromium-browser[5601cefb4000+9044000]
```

As I said this problem is a new one and **seems** to be connected to the recent chromium update.

Can anybody help?

Thanks a lot in advance.
Greetings.
Rosika

**Comment by Vincent43** [comment]
The `default.profile` is incompatible with chromium.

**Comment by Rosika2** [comment]
@Vincent43 :
Hi and thanks a lot for the clarification.
I see. I´d say that´s okay but it leaves me with the original issue of the add-on "just read" not working anymore.
Do you have any ideas about that as well?

Greetings.
Rosika

**Comment by Rosika2** [comment]
It seems the problem isn´t related with firejail as I thought in the beginning.
On https://github.com/ZachSaucier/Just-Read/issues/297 ("Recently, it appears, the extension has stopped functioning .....")
It seems they are currently working on a fix.

Thanks for your help.

Geetings.
Rosika

**Comment by curiosityseeker** [comment]
Did you modify the chromium.profile or chromium-common.profile? Neither contains `seccomp`but it seems that syscall 161 (=chroot) is blocked for you.

**Comment by Vincent43** [comment]
@curiosityseeker the seccomp error comes from `default.profile` which OP tried to test.

**Comment by rusty-snake** [comment]
@Rosika2 still an issue?

**Comment by Rosika2** [comment]
@rusty-snake :
Sorry, it seems I forgot to close the thread. My apologies.
As it turned out the problem with the "Just Read" extension was in the source code itself which has been fixed by the author in the meantime.
For further information see https://github.com/ZachSaucier/Just-Read/issues/297 .

Thanks for your help and many greetings.
Rosika
