### ISSUE TITLE
Firejail stopped working with Opera.

### ISSUE THREAD

**Issue by Linux-Fan** [netblue30/firejail#3235]
Not sure what to do with that issue

```
firejail opera --disable-seccomp-filter-sandbox
Reading profile /etc/firejail/opera.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 5284, child pid 5285
Error: invalid whitelist path /home/zbyszek/.config/opera
Error: proc 5284 cannot sync with peer: unexpected EOF
Peer 5285 unexpectedly exited with status 1
```

**Comment by smitsohu** [comment]
> Error: invalid whitelist path /home/zbyszek/.config/opera

The last path element, is it a symbolic link?
If yes, could you go to /etc/firejail/firejail.config and change
`# follow-symlink-as-user yes`
to 
`follow-symlink-as-user no` ?

**Comment by Linux-Fan** [comment]
There was a symbolic link pointing to /dev/null. I removed it and now Opera starts but still with some errors

> firejail opera --disable-seccomp-filter-sandbox
> Reading profile /home/zbyszek/.config/firejail/opera.profile
> Reading profile /etc/firejail/chromium-common.profile
> Reading profile /etc/firejail/disable-common.inc
> Reading profile /etc/firejail/disable-devel.inc
> Reading profile /etc/firejail/disable-exec.inc
> Reading profile /etc/firejail/disable-interpreters.inc
> Reading profile /etc/firejail/disable-programs.inc
> Reading profile /etc/firejail/whitelist-common.inc
> Reading profile /etc/firejail/whitelist-var-common.inc
> Parent pid 8611, child pid 8612
> Warning: /sbin directory link was not blacklisted
> Warning: /usr/sbin directory link was not blacklisted
> Child process initialized in 83.68 ms
> [6:18:0228/185259.692700:ERROR:address_tracker_linux.cc(201)] Could not bind NETLINK socket: Adres jest już w użyciu (98)
> [6:26:0228/185259.789428:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 73: Brak dostępu (13)
> [6:26:0228/185259.790409:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 75: Brak dostępu (13)
> [6:26:0228/185259.887944:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 142: Brak dostępu (13)
> [6:26:0228/185259.888910:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 143: Brak dostępu (13)
> [6:26:0228/185259.895799:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 156: Brak dostępu (13)
> [6:26:0228/185259.921527:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 191: Brak dostępu (13)
> [6:26:0228/185259.923510:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 196: Brak dostępu (13)
> [6:26:0228/185259.924758:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 198: Brak dostępu (13)
> [6:26:0228/185259.954897:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 240: Brak dostępu (13)
> [6:26:0228/185300.025632:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 280: Brak dostępu (13)
> [280:1:0228/185300.034665:ERROR:child_thread_impl.cc(784)] Receiver for unknown Channel-associated interface: chrome.mojom.SearchBouncer

**Comment by smitsohu** [comment]
> but still with some errors

Please note that some messages also show up when browsers run unsandboxed.

In general these messages are considered harmless, even though admittedly some of them are not well understood currently. For an authoritative answer you will need to ask someone more familiar with the inner workings of Opera/Chromium.

> [6:18:0228/185259.692700:ERROR:address_tracker_linux.cc(201)] Could not bind NETLINK socket: Adres jest już w użyciu (98)

The address tracker seems to monitor your system's network configuration for changes. I'd say most users are unlikely to run into any hiccups.

> [6:26:0228/185259.789428:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 73: Brak dostępu (13)

Probably Opera wants to signal to the out-of-memory-killer that it believes it should be killed late if the systems runs out of memory, but this is not possible because the relevant file is blacklisted in the sandbox.

**Comment by smitsohu** [comment]
> Probably Opera wants to signal to the out-of-memory-killer that it believes it should be killed late if the systems runs out of memory, but this is not possible because the relevant file is blacklisted in the sandbox.

Actually it is not blacklisted, but there used to be restriction in the AppArmor profile.

**Comment by Vincent43** [comment]
`[6:18:0228/185259.692700:ERROR:address_tracker_linux.cc(201)] Could not bind NETLINK socket: Adres jest już w użyciu (98)`

Do you have multiple browsers running? Anyway this shouldn't cause problems

> [6:26:0228/185259.789428:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 73: Brak dostępu (13)

This is mostly harmless and will go away with next firejail release.

> [280:1:0228/185300.034665:ERROR:child_thread_impl.cc(784)] Receiver for unknown Channel-associated interface: chrome.mojom.SearchBouncer

No idea about this one. If things work normal for you then you may ignore it.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
