### ISSUE TITLE
kernel.yama.ptrace_scope = 2|3 breaks --build if strace is installed

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3237]
### STR

1. `sudo  sysctl kernel.yama.ptrace_scope=2` or 3.
2. make sure `strace` is installed
3. firejail --build true

### actual behavior

```
/usr/bin/strace: test_ptrace_get_syscall_info: PTRACE_TRACEME: Operation not permitted
/usr/bin/strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted
Error: cannot run the sandbox
```

### expected behavior

Firejail checks `kernel.yama.ptrace_scope` and skip strace if it is 2 or 3.

**Comment by reinerh** [comment]
Or instead of checking kernel.yama.ptrace_scope, it could check the ptrace result for EPERM.

**Comment by rusty-snake** [comment]
> Edit: oh, just noticed it's calling strace, not calling ptrace directly...

> If /usr/bin/strace is  installed  on  the  system,  it  also  builds  a whitelisted  seccomp profile.
