### ISSUE TITLE
Polari support

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#324]
From: https://github.com/netblue30/firejail/pull/302

Thanks, I didn't realize /usr/bin/polari was a symlink to /usr/share/polari/org.gnome.Polari. Unfortunately, it seems like Firejail discards everything after the first dot and only uses org as the command name. Do you think it's possible to have Firejail check for the full file name if org.profile doesn't exist? (If you want, I'll look into that this weekend when I have more time and open a pull request. This section seems to be the problem.)

**Comment by jrabe** [comment]
I have given up trying to isolate Polari as it uses three different executables to run (`/usr/share/polari/org.gnome.Polari`, `gapplication`, `gjs-console`) and integrates so tightly with `gnome-shell` that it's nearly impossible to add proper isolation without breaking some of Polari's features (like the _Settings_ menu in the GNOME top bar, which doesn't seem to work with the current profile).

**Comment by netblue30** [comment]
Polari profile is now available. I'll close the bug for now.
