### ISSUE TITLE
"firejail --appimage": does it really need to be executable?

### ISSUE THREAD

**Issue by Rosika2** [netblue30/firejail#3240]
----- not an issue per se, rather a question -----

Hello,

I´ve got a question concerning setting the executable bit in **appimages**.

I know firejail has appimage support and I´m glad to use it.
As far as appimages are concerned it says:

> Before you can run an AppImage, you need to make it executable. This is a Linux security feature [...]

(https://discourse.appimage.org/t/how-to-run-an-appimage/80 )

Yet I DIDN´T do this for Cool-Retro-Term-1.1.1-x86_64.AppImage (https://appimage.github.io/Cool_Retro_Term/ )

On this very site it says:

> If you want to restrict what Cool_Retro_Term can do on your system, you can run the AppImage in a sandbox like Firejail. This is entirely optional and currently needs to be configured by the user.

So I ran it in firejail using the command 
`firejail --appimage ./Cool-Retro-Term-1.1.1-x86_64.AppImage`
and the programme runs perfectly.

So has it something to do with firejail itself that I really don´t need to make the appimage executable?
And if so why is that?

Thanks in advance for your help.

Greetings.
Rosika 

P.S.:
system: Linux/Lubuntu 18.04.4 LTS, 64bit

**Comment by rusty-snake** [comment]
Usually you need to make it executable because you want to execute the .AppImage file. AFAIK firejail extract the appimage to /run/firejail/appimage and then execute the AppRun (entry-point of AI).

**Comment by Rosika2** [comment]
@rusty-snake:
Hi and thank you for pointing out that matter.
So you´re perfectly right. I just ran my `Cool-Retro-Term-1.1.1-x86_64.AppImage` and looked up the permissions:

```
rosika@rosika-Lenovo-H520e /r/f/a/.a/u/bin> pwd
/run/firejail/appimage/.appimage-3882/usr/bin
rosika@rosika-Lenovo-H520e /r/f/a/.a/u/bin> ll
insgesamt 1,7M
-rwxrwxr-x 1 root root 1,7M Jan 19  2019 cool-retro-term*
-rw-rw-r-- 1 root root  146 Jan 19  2019 qt.conf
```
So firejail sees to it that the respective appimage becomes executable in _/run/firejail/appimage/.appimage-3882/usr/bin_ . Very impressive.

So what it comes down to is that I don´t have to make the orignal appimage file executable when running it in firejail.

Thanks a lot for your help.
Greetings.
Rosika
