### ISSUE TITLE
discord 0.10 seccomp

### ISSUE THREAD

**Issue by arrowgent** [netblue30/firejail#3247]
latest discord update breaks the discord-common.profile

launching with
`firejail --ignore=seccomp discord`
fixes the issue...
however, this disables seccomp

this must be related to recent updates in chromium/electron releases....

it doesnt help i cant find any discord release notes anywhere....
not going to join their discord for a release note/changelog...

**Comment by oxplay2** [comment]
we have problem with Discord:
/usr/share/Modules/init/bash: linia 36: /usr/bin/tclsh: There is no such file or directory

Command: firejail --profile="Discord" --whitelist="/usr/bin/tclsh" /opt/Discord/Discord
Don't resolve problem.

**Comment by rusty-snake** [comment]
@arrowgent to find the blocked syscall: `journalctl --grep=SECCOMP`
Likely it is chroot (161), then try with `firejail '--seccomp=!chroot' discord`

@oxplay2 can you try `firejail --private-bin=tclsh discord`

**Comment by oxplay2** [comment]
@rusty-snake 

it helped with previous error. 

But it still doesnt work (with no specific error)

> ...
> Warning fcopy: skipping /etc/alternatives/print, cannot find inode
> Warning fcopy: skipping /etc/alternatives/nmap, cannot find inode
> Warning fcopy: skipping /etc/alternatives/mkisofs, cannot find inode
> Warning fcopy: skipping /etc/alternatives/mta-newaliases, cannot find inode
> Warning: skipping ca-certificates for private /etc
> Warning: skipping password for private /etc
> Private /etc installed in 17.37 ms
> Child process initialized in 344.47 ms
> 
> Parent is shutting down, bye...

**Comment by rusty-snake** [comment]
@oxplay2 anything in the journal? Does it work with `--noprofile`?

**Comment by oxplay2** [comment]
@rusty-snake still dont work

$ firejail --noprofile --private-bin=tclsh /opt/Discord/Discord
Parent pid 4176, child pid 4177
2 programs installed in 25.39 ms
Child process initialized in 40.03 ms
execvp: No such file or directory

Parent is shutting down, bye...

**Comment by rusty-snake** [comment]
I mean `firejail --noprofile /opt/Discord/Discord`, sorry.

**Comment by oxplay2** [comment]
@rusty-snake Thanks! it works fine, but does it make higher security risc without profile?

**Comment by rusty-snake** [comment]
Let me quote @Vincent43 https://github.com/netblue30/firejail/issues/3092#issuecomment-576336896
> `--noprofile` is very close to not using firejail at all.

---

Shows `journalctl --follow`/`journalctl --pager-end` anything like blocked syscall as reported by OP?

**Comment by arrowgent** [comment]
```
Mar  1 10:11:15 Origin-EON-17S kernel: [65777.405050] audit: type=1326 audit(1583086275.798:44): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=8324 comm="Discord" exe="/usr/share/discord/Discord" sig=31 arch=c000003e syscall=161 compat=0 ip=0x7f07778a2839 code=0x0
Mar  1 10:11:15 Origin-EON-17S kernel: [65777.406497] traps: Discord[8320] trap int3 ip:558b60edceaa sp:7fffd0088c90 error:0 in Discord[558b5d9cc000+53ad000]
```

testing
`firejail '--seccomp=!chroot' discord`
launches correctly.
