### ISSUE TITLE
Using Thunderbird with a profile location other than default

### ISSUE THREAD

**Issue by johncarterofmars** [netblue30/firejail#3248]
Linux Mint 19.3
Firejail 0.9.62_1

My thunderbird profile is stored in a veracrypt drive. I tried to launch thunderbird with:
firejail thunderbird --profile-path=/media/veracrypt1/thunderbird with this result:

$ firejail thunderbird --profile-path=/media/veracrypt1/thunderbird
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 32415, child pid 32416
Warning fseccomp: --protocol not supported on this platform
Warning: cleaning all supplementary groups
Child process initialized in 39.86 ms
Warning: an existing sandbox was detected. /usr/bin/thunderbird will run without any additional sandboxing features
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

How do I properly specify the path for thunderbird to launch correct?

Thank you.

**Comment by rusty-snake** [comment]
You need to allow /media:

`firejail --ignore=disable-mnt thunderbird --profile-path=/media/…`

**Comment by matu3ba** [comment]
@rusty-snake 
label `Q: wiki` and `Q:usage` ?
Explaining the common commands could be put into the wiki.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
