### ISSUE TITLE
Firejail and recording software

### ISSUE THREAD

**Issue by amarildojr** [netblue30/firejail#325]
This bug is related to https://github.com/netblue30/firejail/issues/69

It's not possible to record Steam games while using Firejail, all I get is a black screen. However, when I record without audio the recording works.

Steps to reproduce:

* Either Arch, Debian (Jessie, testing/sid), or openSUSE (the distros I tested);
* Firejail 0.36 or 0.38;
* Install obs-studio or simplescreenrecorder;
* Run Steam without Firejail and record a game (will work);
* Run SSR/OBS after running Steam with Firejail - recording programs won't recognize pulseaudio;
* Create the "client.conf" file in './config/pulse', with "enable-shm = no" inside;
* Run SSR/OBS again - they will recognize audio;
* Record a game - screen will be black;
* Recording with ALSA instead won't fix the problem;
* Disabling audio will cause the recording to work;

Arch Linux
Debian Jessie/Testing/Sid
openSUSE 42.1

**Comment by netblue30** [comment]
I'll try some recoding here, thanks.

**Comment by netblue30** [comment]
Give version 0.9.40 a try. There have been a number of fixes for the sound system. If you still have the problem I'll reopen the bug.
