### ISSUE TITLE
conky needs lua

### ISSUE THREAD

**Issue by curiosityseeker** [netblue30/firejail#3250]
Since a few days I've noticed that conky didn't start any more here on Arch Linux. Starting it in the console produced the error:

`/bin/conky: error while loading shared libraries: liblua.so.5.3: cannot open shared object file: Permission denied`

Adding `allow-lua.inc` to the profile solved the problem. (It just comes to my mind that I didn't check if `noblacklist /usr/lib/liblua*` would be sufficient ...)

**Comment by Vincent43** [comment]
Adding `allow-lua.inc` to the profile should be  ok. Feel free to open PR.

**Comment by rusty-snake** [comment]
> Adding `allow-lua.inc` to the profile solved the problem. (It just comes to my mind that I didn't check if `noblacklist /usr/lib/liblua*` would be sufficient ...)

I'm very sure that it solve the issue. Has you added it above the disable-* block?

**Comment by curiosityseeker** [comment]
> I'm very sure that it solve the issue. 

Yes, it does - I just tried it.

> Has you added it above the disable-* block?

I added it to my conky.profile in {HOME}/.config/firejail above `include /etc/firejail/conky.profile`
