### ISSUE TITLE
Thunderbird not opening pdf with jailed MasterpdfEditor

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3252]
MasterpdfEditor is jailed with masterpdfeditor5.profile
Thunderbird is not jailed.

When opening a pdf directly from Thunderbird, Masterpdfeditor says cannot read it from /tmp/mozilla...etc.

If i open the pdf directly from /tmp, it will open.

What do i need to do to allow it to open it from Thunderbird?

Please dont tell me that thats its intended purpose and that i should first save the file. There's already no network to masterpdfEditor, so saving the file and then opening it is just tedious.  How do i get around this to allow to open via /tmp ?

firejail - version 0.9.58.2

Log below:
```
Reading profile /usr/local/etc/firejail/masterpdfeditor5.profile
Reading profile /usr/local/etc/firejail/masterpdfeditor.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-passwdmgr.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 13143, child pid 13144
Private /etc installed in 4.71 ms
1 program installed in 2.59 ms
Blacklist violations are logged to syslog
]0;firejail /opt/master-pdf-editor-5/masterpdfeditor5 /tmp/mozilla_user0/about_io_en-3.pdf Child process initialized in 120.56 ms
Qt: Session management error: Could not open network socket
```

**Comment by Vincent43** [comment]
Add `ignore private-tmp` to `~/config/firejail/masterpdfeditor.local`

**Comment by svc88** [comment]
@Vincent43 thanks but can you tell me where to find masterpdfeditor.local ?  I dont have ~/config/firejail. Where are all the .local files sitting?

**Comment by rusty-snake** [comment]
Create it:
```bash
mkdir -p ~/.config/firejail
echo "ignore private-tmp" >> "~/.config/firejail/masterpdfeditor5.local"
```

**Comment by svc88** [comment]
Was not aware that you needed to create the config files, i thought they were already created but couldnt find them.
thank you!

**Comment by Vincent43** [comment]
@svc88 the `.local` ones are optional for users to create.
