### ISSUE TITLE
seccomp with filter based on flags argument of syscall

### ISSUE THREAD

**Issue by s3rj1k** [netblue30/firejail#3254]
Can firejail block `Open` syscall with only specific argument, like `O_RDWR`?

If not can you please suggest another approach, for testing purposes, that can block specific syscall argument when running arbitrarily elf?

**Comment by topimiettinen** [comment]
This would be doable with seccomp filters in general, as the filters have access to registers which contain system call parameters and then logical and arithmetic operations can be done with them. But Firejail constructs filters which can only block or allow system calls completely, finer control isn't available. You could modify Firejail to load your own seccomp filter to do that.

**Comment by s3rj1k** [comment]
Hmm, thanks @topimiettinen
