### ISSUE TITLE
Question: Whats the best way to update?

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3261]
I want to stay up to date with the constant additions and edits of all profiles, however i am wondering what the downside is in cloning and building the latest on Github on a weekly basis?

Is cloning better than using the official releases?
What is a safe frequency in cloning the repo? once a week?

**Comment by matu3ba** [comment]
Occasionally compiling/running breaks on development(2-3 times a year).
Sometimes due to software updates needing new/changed rules.

If you want a stable running system, go for stable/LTS releases of your distribution.
If you want bleeding edge software, use the latest master.
If you have a mix of both, you have to decide.

Safe for doing what?

**Comment by rusty-snake** [comment]
> i am wondering what the downside is in cloning and building the latest on Github on a weekly basis?

- broken build (see @matu3ba post)
- commits breaking firejail temporary (just checkout the lastet working commit, rebuild, report, wait)
- commits breaking profiles on some systems

Pros:
 - latet firejail features
 - new profiles
 - profile fixes from master

> Is cloning better than using the official releases?

If you want just a running firejail to sandbox a release is better. If you want to contribute (code, profile, testing) the git version is better.


Using firejail-release with git-profile:
works short after a release but allmost every firejail-release has some changes in firejail (the binary) against profiles.

Examples:
0.9.62:
 - allow-debuggers in profiles. No workaround
 - several seccomp enhancements: need to write an script that replace `seccomp` with `seccomp.drop` using the new groups + exceptions.
- whitelisting /usr/share: just profiles.
- new conditions: HAS_X11, HAS_NET: no workaround
0.9.60: 
- mdwe blocks memfd_create: script that adds `seccomp.drop memfd_create` to all profile with mdwe
- private-cwd: no workaround
- nodbus blocks systembus: `?HAS_NODBUS: blacklist /run/dbus`

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
