### ISSUE TITLE
Problem with keepassxc profile

### ISSUE THREAD

**Issue by freerunner** [netblue30/firejail#3262]
Profile issue with: keepassxc (maybe others as well, just started setting up Firejail)
Runs with --noprofile option: yes

Linux distribution: KDE Neon User Edition (Ubuntu 18.04)
Firejail version: 0.9.62 (from ppa)

My external NTFS data mount points, located in /storage are not visible within the jailed keepassxc.
However, if I comment the line
`private-etc alternatives,fonts,ld.so.cache,machine-id`
they're accessible again.

Mount options for the drives in fstab:
`UUID=[cut] /storage/Data     ntfs    defaults,umask=007,uid=1000,gid=100,noatime,big_writes 0       0`
/storage/Data is whitelisted in whitelist-common.local as well.

Can anybody help?

**Comment by rusty-snake** [comment]
> /storage/Data is whitelisted in whitelist-common.local as well.

whitelisting isn't supported for /storage, this hasn't any effect.

Can you run `firejail --build keepassxc | grep private-etc` and post the output (should only one `private-etc` line).

**Comment by freerunner** [comment]
Sure. 

This is with a stock profile:
`andy@X570DESKTOP:/etc/firejail$ firejail --build keepassxc | grep private-etc
private-etc drirc,fonts,gcrypt,kde5rc,login.defs,passwd,`

Wicked: After running `firejail --build keepassxc | grep private-etc` I can see all my mount points in /storage. If I simply run keepassxc from terminal they're gone.

**Comment by freerunner** [comment]
I'm back. :)

Okay, after adding the items to private-etc in the profile, there are more detailed error messages:
https://pastebin.com/RgT3sX7q

**Comment by glitsj16** [comment]
> Wicked: After running firejail --build keepassxc | grep private-etc I can see all my mount points in /storage. If I simply run keepassxc from terminal they're gone.

That is expected behaviour. The `--build` option creates a volatile profile, meaning that will be gone (not saved to disk) the next time you run without the '--build' parameter. We'll see what we can do to fix the default keepassxc profile. But for now you can use `--build=keepassxc.profile`, which will save keepassxc.profile to your ${HOME}/.config/firejail directory. Once that is done, you should be able to see your external NTFS data mount points when simply running 'keepassxc' or 'firejail /usr/bin/keepassxc' like before.

**Comment by rusty-snake** [comment]
@freerunner is there anything in the journal/syslog.

**Comment by freerunner** [comment]
Aha. I'm slowly beginning to understand. The --build parameter does not interfere with the normal exectution of the program, instead starts to monitor the behavior. Then a profile is created after the application has been closed. Is this correct?

Okay, created a custom profile. When run with it, firejail reports an invalid whitelisted filename path.
-> whitelist /var/run/samba/gencache_notrans.tdb
After removing that line, keepassxc runs, but all NTFS mountpoints are gone again.

This is the custom profile: https://pastebin.com/LW8KmVcP
This is the output in stderr after closing the app:

```
Reading profile /home/andy/.config/firejail/keepassxc.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 5687, child pid 5688
Warning: skipping exports for private /etc
Warning: skipping krb5.conf for private /etc
Warning: skipping drirc for private /etc
Warning: skipping gcrypt for private /etc
Warning: skipping kde5rc for private /etc
Private /etc installed in 8.63 ms
5 programs installed in 7.17 ms
Child process initialized in 41.96 ms
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
org.kde.solid.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf5.kservice.services: KServiceTypeTrader: serviceType "ThumbCreator" not found
kf5.kservice.services: KServiceTypeTrader: serviceType "ThumbCreator" not found
kf5.kservice.services: KServiceTypeTrader: serviceType "ThumbCreator" not found
kf5.kservice.services: KServiceTypeTrader: serviceType "ThumbCreator" not found
kf5.kservice.services: KServiceTypeTrader: serviceType "ThumbCreator" not found

Parent is shutting down, bye...
```

@rusty-snake 
With the custom profile, syslog is clean from messages. 
This is a recent syslog output with a stock profile:
https://pastebin.com/DdzZPRPH

**Comment by rusty-snake** [comment]
still need help?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
