### ISSUE TITLE
nosound should blacklist ${RUNUSER}/pulse

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3263]
I'm working a bit on templates for wru (`whitelist ${RUNUSER}/…`) and adding it to more profiles. I detected that /run/user/1000/pulse is accessible if `nosound` is in affect. Unfortunately there is also no `?HAS_NOSOUND:` or `?HAS_LINE(nosound)` connditions.

**Comment by glitsj16** [comment]
Until we have those conditionals it might be worthwhile to make ${RUNUSER}/pulse read-only. I have been running with this in my globals.local for a while now without issues:

```
...
#+ protect pulse sockets & pid file
read-only ${RUNUSER}/pulse
...
```

**Comment by smitsohu** [comment]
Just to mention it: This doesn't mean that `nosound` is broken. The socket inside `/run/user/<UID>/pulse` is the primary target and it _is_ blacklisted.

**Comment by smitsohu** [comment]
May I vote to adjust the `nodbus` option rather than the profiles?

**Comment by rusty-snake** [comment]
Actual:
```
$ firejail --noprofile --nosound ls -l /run/user/1000/pulse 
-r-------- root root … native
-rw------- rusty-snake rusty-snake … pid
```

What I suggest:
```
ls: cannot open directory '/run/user/1000/pulse': Permission denied
```

The mentioned conditions would allow a workaround until this is changed in the C-code.

**Comment by Vincent43** [comment]
Did you tested if apps behave normal when this permission is denied?

**Comment by rusty-snake** [comment]
Will do some testing, but I think that this would not break anything, since if you try operate on /run/user/1000/pulse/native you already get an permissions denied error and we use nosound for programs which do not use sound.

**Comment by smitsohu** [comment]
fwiw the relevant lines are here:
https://github.com/netblue30/firejail/blob/35443058b6539e8ed251c40bd342912a7e2c1484/src/firejail/pulseaudio.c#L41-L50

**Comment by netblue30** [comment]
I am going for "ls: cannot open directory '/run/user/1000/pulse': Permission denied"
`````
$ firejail --nosound
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 8846, child pid 8847
Child process initialized in 95.86 ms
[netblue@debian firejail]$ ls /run/user/1000/pulse
ls: cannot open directory '/run/user/1000/pulse': Permission denied
[netblue@debian firejail]$ 
`````
