### ISSUE TITLE
FIREJAIL_PROFILE_PATH or similar firejail.config setting

### ISSUE THREAD

**Issue by jonleivent** [netblue30/firejail#3264]
The current approach that limits profile and include file searches to `~/.config/firejail` and `/etc/firejail` prevents a local administrator from creating global .profiles and .incs somewhere that is visible to all users, but out of the way of `/etc/firejail`.  It would be nice to have a path env var like FIREJAIL_PROFILE_PATH that can be set to something like `"~/.config/firejail:/usr/local/etc/firejail:/etc/firejail"`  and that would be respected during searches for .profile and .inc files.  Another alternative would be a global path setting in `/etc/firejail/firejail.config`.

Why shouldn't the local administrator add/change profiles and includes in `/etc/firejail`?  One reason is to avoid clashes with firejail updates.  Another is that in some cases, the `/etc/firejail` profile might be preferred over the administrator-added one.

**Comment by rusty-snake** [comment]
Duplicate of #3103
