### ISSUE TITLE
Network namespace slows Firefox to a crawl

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#327]
I'm not entirely sure what's going on - maybe I just don't understand the way network namespaces work. When I try to run Firefox with the `--net=wlan0` option, it slows to a crawl. Thinking that it might be the `netfilter` in the default profile, I added `--ignore=netfilter`, but Firefox was still just as slow. I then used `--join-network=<pidof iceweasel>` and attempted to ping google.com, which failed. Frustrated, I did a simple `firejail --net=wlan0 --noprofile bash` and again tried `ping4 google.com` which again didn't work. I thought `--net=wlan0` (or an equivalent command) was not supposed to deny internet access? What's going on? I tested `ping4 google.com` on the regular system and it works fine.

[Note]: I'm using firejail 0.9.38.

**Comment by netblue30** [comment]
--net and --interface are not supported on wlan interfaces. The kernel cannot attach a macvlan driver to them, I'll have to add a note in the man page, thanks for pointing it out.

**Comment by chiraag-nataraj** [comment]
Ah okay thanks!
