### ISSUE TITLE
firejail netns netstat shows /tmp/.X11-unix/X0

### ISSUE THREAD

**Issue by alextrekov3307** [netblue30/firejail#3274]
firejail latest stable

`firejail --net=none  netstat -a | grep X11`

Displays nothing.

`firejail --netns=something  netstat -a | grep X11`

`unix  3      [ ]         STREAM     CONNECTED     15800928 /tmp/.X11-unix/X0`

The namespace contains lo and wg0.

Cannot use --net with --netns.

Is there a way to specify an interface within another network namespace to --net?

**Comment by rusty-snake** [comment]
Maybe you can use `ip netns something exec firejail --net=...`.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
