### ISSUE TITLE
Viber - how to disable clipboard?

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3283]
Using Viber Desktop on Ubuntu 18.04, but want to disable any clipboard activity it has access to.  How do i do that?

PS: Also, It would actually be nice if i could turn this on on-demand, but i doubt i can do that without restarting the app can i?

**Comment by rusty-snake** [comment]
https://firejail.wordpress.com/documentation-2/x11-guide/
looks like Xpra can do this at runtime.

**Comment by svc88** [comment]
@rusty-snake is there no other way to blacklist something else in its .local file?

**Comment by rusty-snake** [comment]
Unfortunately no, the clipboard is not implemented via files, it uses the X11/Wayland socket.

**Comment by svc88** [comment]
Ok so say i do as in example from the documentation you sent me:
$ firejail --x11=xpra --net=eth0 program-and-arguments
or
$ firejail --x11=xephyr --net=eth0 program-and-arguments

Is --net=eth0 necessary to use?  Wont it use the default network adapter if i dont specify?

**Comment by rusty-snake** [comment]
It is more comfortable to run a wm like openbox in the X server (as described below). but otherwise it is true so far.

> Is --net=eth0 necessary to use?

If you have an abstract X socket it would be still accessible, so a malicious program maybe could still access you clipboard (or firejail will give you an error about that).

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.

**Comment by milahu** [comment]
> want to disable any clipboard activity

> https://firejail.wordpress.com/documentation-2/x11-guide/
> looks like Xpra can do this at runtime.

jdownloader can escape this. it still has access to my clipboard
`firejail --profile=jdownloader --x11=xpra java -jar JDownloader.jar`

related https://github.com/netblue30/firejail/issues/875#issuecomment-257095247

> For xephyr you will have to run both applications on the same x11 server, I have an example for --x11=xephyr here: https://firejail.wordpress.com/documentation-2/x11-guide/#listing.
>
> X11 security extension disables the clipboard and drag&drop,

`firejail --x11=xorg` fails with `no authorization protocol specified` similar to #1741 #3627 #4105
