### ISSUE TITLE
nslookup apparmor denied

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3285]
Tested the newly introduced `nslookup` profile and seeing this in /var/log/audit/audit.log:

```
type=AVC msg=audit(1584599238.923:1362): apparmor="DENIED" operation="open" profile="firejail-default" name="/proc/10/task/11/comm" pid=46733 comm="nslookup" requested_mask="w" denied_mask="w" fsuid=1001 ouid=1001
```

Not sure if we need to adapt firejail-default or drop the apparmor option in the profile.

**Comment by Vincent43** [comment]
I've seen this before with qemu. For me it would be ok to add `/proc/@{PID}/task/@{PID}/comm w,` line to firejail-default.

**Comment by glitsj16** [comment]
@Vincent43 Thanks. I've added that to my firejail-local for now and it does the job. Let's keep this open for a while so others can chime in. Cheers!

**Comment by netblue30** [comment]
It does the same for dig and (bind9) host. "/proc/@{PID}/task/@{PID}/comm w" works fine. I'm putting it in git. I'll be adding lots of apparmor in the existing profiles.

8a820b48dec5684ace55b44ba0c041b37eaf021a
