### ISSUE TITLE
Audacious & Audacity freeze, works with "ignore memory-deny-write-execute"

### ISSUE THREAD

**Issue by 0x7969** [netblue30/firejail#3287]
Hey,
just started using Firejail (0.9.63) on Arch and noticed that audacious wouldn't start. There is no error message but the window never comes up. Top lists it as a zombie. Ignoring "memory-deny-write-execute" makes it work.
I noticed that Audacity behaves exactly the same way, so there might be more applications affected. Not sure if it's a general problem with my configuration or a problem of the applications profile files.

**Comment by rusty-snake** [comment]
It's not your config, see #1803 and #2840.

It is not known exactly what the cause is. one is the wayland implementation of gtk, it is broken with mdwe since firejail 0.9.60+ (memfd_create).

**Comment by rusty-snake** [comment]
779937d250d6d549e41465db3735f9688749e644

**Comment by glitsj16** [comment]
Closing: issue is fixed.
