### ISSUE TITLE
MPV fails with gpu/vdpau options (ADM gpu with mesa drivers)

### ISSUE THREAD

**Issue by gui-don** [netblue30/firejail#3288]
Hi!

Here is the options I use:
```
hwdec=vdpau-copy
vo=gpu
profile=gpu-hq
gpu-api=vulkan
gpu-context=x11vk
```
`firejail mpv "my_video.mp4"` output:
 ```
[vo/gpu/vulkan/libplacebo] Failed creating instance: VK_ERROR_EXTENSION_NOT_PRESENT
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan instance
[vo/gpu] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.
```
`mpv "my_video.mp4"` runs fine.

Notes:
- Removing the options makes `mpv` run fine within firejail too.
- Using openGL instead of vulkan *does not work* either, `mpv` runs indefinitly.

Thanks for your help!

EDIT: Vulkan gpu API works with @rusty-snake fix.
Still stuck without vulkan: see my other comment

**Comment by rusty-snake** [comment]
Duplicate of #3107? Try this fix: https://github.com/netblue30/firejail/commit/08061fb590acda23d9f8fff4eebdd1366caf65fa

**Comment by gui-don** [comment]
Thanks @rusty-snake;

So that solves the vulkan run. However, when using these options:
```
hwdec=vdpau-copy
vo=gpu
profile=gpu-hq
```
`mpv` runs indefinitly without video nor sound. I tried to strace without firejail to find the accessed files and did some adjustements but no luck so far.

**Comment by gui-don** [comment]
Alright, another quick research and test and I have to ignore `seccomp`, then mpv launches.

Thanks!

**Comment by rusty-snake** [comment]
mesa, amd, seccomp? #3219, #3267.

Try `seccomp !kcmp`
