### ISSUE TITLE
error "Firefox is already running but is not responding" when using firefox wayland

### ISSUE THREAD

**Issue by yory8** [netblue30/firejail#3290]
Firejail: 0.9.62
Archlinux (Sway WM)
Default Profile.

If I try to open a new firefox window when there's one already open, I get the "Firefox is already running but is not responding" error. 

This only happens when running from inside firejail, and only when using `export MOZ_ENABLE_WAYLAND=1` (that is, running firefox with wayland rather than xwayland).

**Comment by rusty-snake** [comment]
cause: `nodbus`

**Comment by yory8** [comment]
I can confirm that removing `nodbus` fixes the issue

**Comment by glitsj16** [comment]
Closing here, as the issue has been adressed.

**Comment by rusty-snake** [comment]
For the record: `dbus-user.own org.mozilla.firefox.*`
