### ISSUE TITLE
thunderbird.profile: Harden rules to allow Firefox to open links

### ISSUE THREAD

**Issue by curiosityseeker** [netblue30/firejail#3291]
The `thunderbird.profile` contains the following lines:

```
# Uncomment the next 4 lines or put them in your thunderbird.local to
# allow Firefox to load your profile when clicking a link in an email
#noblacklist ${HOME}/.cache/mozilla
#noblacklist ${HOME}/.mozilla
#whitelist ${HOME}/.cache/mozilla/firefox
#whitelist ${HOME}/.mozilla
```
These rules are more permissive than necessary, IMO. According to my tests the following modifications work:
```
noblacklist ${HOME}/.cache/mozilla
noblacklist ${HOME}/.mozilla
whitelist ${HOME}/.cache/mozilla/firefox
whitelist ${HOME}/.mozilla/firefox/profiles.ini
read-only ${HOME}/.mozilla/firefox/profiles.ini
```
These modifications restrict Thunderbird's access to `~/.mozilla/firefox` considerably as would be desirable. I think with these modifications those lines could be uncommented by default.

It would be nice if the whitelist rule for `${HOME}/.cache/mozilla/firefox` could be restricted to the relevant sub-folder therein. But since its name depends on the name of the respective Thunderbird profile I don't know how to do that.

**Comment by rusty-snake** [comment]
Open a PR ;)

**Comment by curiosityseeker** [comment]
Access to {HOME}/.cache/mozilla is actually not necessary.

https://github.com/netblue30/firejail/commit/6b8244dc86efe0a34c2033fa866c48578183f8cb
