### ISSUE TITLE
Firefox is broken on Ubuntu 20.04 Focal

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#3299]

**Comment by glitsj16** [comment]
@KOLANICH Please add some info how/where firefox broke exactly.

**Comment by KOLANICH** [comment]
Just doesn't start. I have tried strace, but with strace it stops, but without it just hangs. I have tried to `whitelist` some paths, but it results in even weirder errors. I have tried to disable features. Disabling apparmor changes the output but doesn't fix ff. IDK how should I debug it. How can I output all the violations into stdout instead of syslog?

**Comment by glitsj16** [comment]
Okay. Please post the output of the below command here (adjust the paths as necessary):

`firejail --ignore=quiet /usr/bin/firefox | tee -a ~/Downloads/firejail.firefox.log 2>&1`

Also, what firejail version are you using on Focal?

**Comment by rusty-snake** [comment]
I tested in a live VM with this image http://cdimage.ubuntu.com/daily-live/current/focal-desktop-amd64.iso and firejail git, and everything works fine.

configure: --enable-apparmor --prefix=/usr
apparmor_parser -r /etc/apparmor.d/firejail-default

**Comment by SkewedZeppelin** [comment]
I bet this is #3219

**Comment by KOLANICH** [comment]
@glitsj16 

```
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
]0;firejail /usr/bin/firefox 
```

@SkewedZeppelin You are completely right, your patch has helped.
