### ISSUE TITLE
Fedora 31 Silverblue

### ISSUE THREAD

**Issue by CdeMills** [netblue30/firejail#3307]
Hello,
I saw the previous posting on the diifculty of running firejail in Silverblue. I tried to get one step further understanding what went wrong. FYI this call works in Fedora 31 Workstation:
strace -o firejail.msg --profile=/etc/firejail/palemoon.profile --private=/home/padupuis/somedir /opt/palemoon/palemoon-bin -no-remote

The first time I get on stderr
Error mkdir: util.c:1022 create_empty_dir_as_root: Permission denied
Next time I get 
Error: cannot create /run/firejail/profile/11639

In the trace file, searching "No such file" gives
unlink("/run/firejail/bandwidth/11639-bandwidth") = -1 ENOENT (No such file or directory)
unlink("/run/firejail/network/11639-netmap") = -1 ENOENT (No such file or directory)
unlink("/run/firejail/name/11639")      = -1 ENOENT (No such file or directory)
unlink("/run/firejail/x11/11639")       = -1 ENOENT (No such file or directory)
unlink("/run/firejail/profile/11639")   = -1 ENOENT (No such file or directory)
unlink("/run/firejail/bandwidth/11639-bandwidth") = -1 ENOENT (No such file or directory)
unlink("/run/firejail/network/11639-netmap") = -1 ENOENT (No such file or directory)
unlink("/run/firejail/name/11639")      = -1 ENOENT (No such file or directory)
unlink("/run/firejail/x11/11639")       = -1 ENOENT (No such file or directory)
unlink("/run/firejail/profile/11639")   = -1 ENOENT (No such file or directory)

The directory /run/firejail exists and is populated by around 10 subdirs. Any idea how to investigate further ? IS it some race condition ?

Regards

Pascal

**Comment by netblue30** [comment]
We don't support Silverblue at the moment. They have a very unorthodox filesystem, with the real files stored under var and symlink from the regular filesystem entry points, something like this:
`````
    /home → /var/home
    /opt → /var/opt
    /srv → /var/srv
    /root → /var/roothome
    /usr/local → /var/usrlocal
    /mnt→ /var/mnt
    /tmp → /sysroot/tmp
`````
It would be a huge change in our code to support it.
