### ISSUE TITLE
[enhancement] Add private-lib option which limits the libraries available to the program

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#331]
It would be useful to have a private-lib option (like private-etc, private-bin, etc.) which only allows access to certain files in /usr/lib, /lib, /lib64, /usr/lib64, etc. Easiest way would be similar to how private-bin is implemented, where the same tmpfs is mounted across all of the library paths.

**Comment by netblue30** [comment]
Will do, thanks!

**Comment by netblue30** [comment]
Moving it here: https://github.com/netblue30/firejail/issues/627
