### ISSUE TITLE
Teams and Firefox

### ISSUE THREAD

**Issue by derba** [netblue30/firejail#3311]
I am using Firejail master of 31-03-2020, 4747e0ed7f1d9e39974a1c5a5900db47ab1423aa on Fedora 31.

**1. Joining meetings.**
I receive invitations to MS Teams-based meetings in mail. I read my mails in Firefox. When I click on a meeting link "Launch Application" dialog pops up with MS Teams as an option.
If I run Firefox in Firejail (with the profile shipped with Firejail), then I cannot join that meeting. Probably Teams app does not get the indication from Firefox. If I run Firefox without Firejail then that works.

**2. Opening links**
In Teams chat there may be links. If I run Teams in Firejail (with the profile shipped with Firejail) then a new Firefox instance is opened and that cannot reach the net. Probably cannot read its settings, including proxy settings. Actually it cannot open Preferences or about:config either.

Is there any kind of solution to these, even if just in theory?

**Comment by rusty-snake** [comment]
assuming you installed teams native (and not with flatpak) then you can try the profile below (merge of teams.profile, electron.profile, firefox.profile and firefox-common.profile). save it under ~/.config/firejail and change your teams/firefox.desktop files to `Exec`ute `firejail --profile=teams_and_firefox.profile teams/firefox`. Maybe you need to add join-or-start.

teams_and_firefox.profile
```
include globals.local

?BROWSER_ALLOW_DRM: ignore noexec ${HOME}

noblacklist ${HOME}/.cache/mozilla
noblacklist ${HOME}/.config/Microsoft
noblacklist ${HOME}/.config/teams
noblacklist ${HOME}/.local/share/pki
noblacklist ${HOME}/.mozilla
noblacklist ${HOME}/.pki

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-interpreters.inc
include disable-programs.inc

mkdir ${HOME}/.cache/mozilla/firefox
mkdir ${HOME}/.config/Microsoft
mkdir ${HOME}/.config/teams
mkdir ${HOME}/.local/share/pki
mkdir ${HOME}/.mozilla
mkdir ${HOME}/.pki
whitelist ${DOWNLOADS}
whitelist ${HOME}/.cache/mozilla/firefox
whitelist ${HOME}/.config/Microsoft
whitelist ${HOME}/.config/teams
whitelist ${HOME}/.local/share/pki
whitelist ${HOME}/.mozilla
whitelist ${HOME}/.pki
include whitelist-common.inc
include whitelist-var-common.inc

apparmor
caps.drop all
netfilter
nodbus
nodvd
nogroups
nonewprivs
noroot
notv
nou2f
protocol unix,inet,inet6,netlink
seccomp !chroot
shell none

disable-mnt
private-cache
private-dev
private-tmp
```

**Comment by derba** [comment]
@rusty-snake thank you. I just symlinked the new profile to teams/firefox.desktop. Works like charm.
The question arises what concept would be fine for Firejail, as the browser is like an OS, launching Teams, Zoom, LibreOffice, etc.

**Comment by rusty-snake** [comment]
In general you should prefer copying links/open document for file-managers.

**Comment by derba** [comment]
Yes, that is what I usually do.
And when I need to attach a document (e.g. odt) in a web app then I copy that to Downloads, so that Firefox be able to access it. (Hard linking is not that easy using GUI. I hope copy-on-write avoids real writes.) And then delete that copy.
