### ISSUE TITLE
join broken with seccomp since 88eadbf

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3313]
@topimiettinen 

STR:
```
term1$ firejail --noprofile --seccomp --name=test bash
% ls /run/firejail/mnt/seccomp/
seccomp.list  seccomp.postexec  seccomp.postexec32

term2$ firejail --join=test ls /run/firejail/mnt/seccomp
Error: cannot read /run/firejail/mnt/seccomp/seccomp.32
```

**Comment by topimiettinen** [comment]
Unfortunately --join has not worked for me for some time (several months) and I don't know why. Here's a strace:
```
nanosleep({tv_sec=0, tv_nsec=100000000}, NULL) = 0
getuid()                                = 1000
geteuid()                               = 1000
setresuid(-1, 0, -1)                    = 0
setresgid(-1, 0, -1)                    = 0
openat(AT_FDCWD, "/proc/12654/root/run/firejail/mnt/ready-for-join", O_RDONLY|O_
CLOEXEC) = -1 EACCES (Permission denied)
setresuid(-1, 1000, -1)                 = 0
setresgid(-1, 1000, -1)                 = 0
write(2, "Error: no valid sandbox\n", 24) = 24
```
The mode of the "ready-for-join" file is 0644. This happens with SELinux enforcing turned off, `sysctl kernel.yama.ptrace_scope = 0` and /proc is not mounted with hidepid=[1|2]. TOMOYO Linux is also enabled but it shouldn't do anything here. AppArmor is not enabled. Very annoying.

**Comment by glitsj16** [comment]
Confirming @rusty-snake's observations. Adding `seccomp.block-secondary` only changes the ls ourput and the error:

```
$ firejail --noprofile --seccomp.block-secondary --seccomp --name=test bash
% ls /run/firejail/mnt/seccomp/
seccomp.block_secondary  seccomp.list  seccomp.postexec  seccomp.postexec32

firejail --join=test ls /run/firejail/mnt/seccomp
Error: cannot read /run/firejail/mnt/seccomp/seccomp
```

Reverting https://github.com/netblue30/firejail/commit/88eadbf31fe25dcd7c224a5d92f71c79ccf6c9d3 brings back `join` functionality here.

**Comment by glitsj16** [comment]
@topimiettinen Is join broken for you with both `name` and `pid`? For the record, I always use the `name` option.

**Comment by topimiettinen** [comment]
Neither work here. --join=name seems to find the right pid.

**Comment by netblue30** [comment]
I have a fix in. We were deleting unused seccomp files from /run/firejail/mnt/seccomp directory during init, and we had a problem with "unused". So I let them all in. Give it a try.

https://github.com/netblue30/firejail/commit/9ba916d20d723f2515c2e084db3437a529b81c34

**Comment by rusty-snake** [comment]
BTW: https://travis-ci.org/github/netblue30/firejail/builds/668027727#L790

travis-ci is also broken since 88eadbf.

**Comment by glitsj16** [comment]
Confirming https://github.com/netblue30/firejail/commit/9ba916d20d723f2515c2e084db3437a529b81c34 does fix the join option :+1:.

**Comment by netblue30** [comment]
Travis fixed, compile problems on old distros.
