### ISSUE TITLE
Build fails on Ubuntu 16.04 LTS with commit ab62720

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3320]
Just noticed that building from git master breaks on Ubuntu 16.04 LTS. Not sure, but it looks as if older versions of `install` can't handle the syntax introduced in https://github.com/netblue30/firejail/commit/ab62720b38ffa766b1a51153d167df254148091b. I do realize 16.04 is dinosaurial by now, but it might be broken on other OS'es too.

```
$ install --version | head -n 1
install (GNU coreutils) 8.25

...
# etc files
install -m 0755 -d //etc/firejail
install -m 0644 -t //etc/firejail etc/{*.profile,*.inc,*.net,firejail.config}
install: cannot stat 'etc/{*.profile,*.inc,*.net,firejail.config}': No such file or directory
make[1]: *** [Makefile:125: realinstall] Error 1
make[1]: Leaving directory '/tmp/bz-dirkos/firejail-git'
make: *** [Makefile:164: install] Error 2
```

**Comment by netblue30** [comment]
Try now, I think I have a fix in.

**Comment by rusty-snake** [comment]
The globbing should be done by the your shell. Maybe the bash in 16.04 is too old for this syntax. The globing in fbec95c4 is also done by the shell, if it works can you try: 

    install -m 0644 -t $(DESTDIR)/$(sysconfdir)/firejail etc/*.profile etc/*.inc etc/*.net etc/firejail.config

**Comment by netblue30** [comment]
I'm seeing the same problem in debian stable. It's something very recent. TravisCi is fine (that's an Ubuntu 14.04) @rusty-snake what distro are you on?

**Comment by rusty-snake** [comment]
Fedora 31; bash 5.0; install/coreutils 8.31; make 4.2.1.

**Comment by netblue30** [comment]
cool!

**Comment by glitsj16** [comment]
@netblue30 Thanks, that worked.

> install -m 0644 -t $(DESTDIR)/$(sysconfdir)/firejail etc/*.profile etc/*.inc etc/*.net 
etc/firejail.config

 @rusty-snake seems a lot faster now doing it like that, it worked with bash from a xenial PPA (5.0-6ubuntu1~16.04.sav0) and the original xenial version (4.0).

**Comment by netblue30** [comment]
running a travis test with the version from @glitsj16 - fine on debian

**Comment by netblue30** [comment]
all fine, both travis and gitlab pipeline passing.
