### ISSUE TITLE
[enhancement] Better handle symlinks in /usr/bin

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#333]
Right now, private-bin's behavior when it comes to symlinked binaries is less than ideal - for example, firefox will refuse to start with "Unable to find Mozilla runtime" and libreoffice just doesn't start (not many error messages). Both of these issues have to do with the fact that when you whitelist symlinked binaries, the symlinks aren't copied as-is - instead, the linked binary itself is copied. Copying the symlink itself would solve the problem, at least with those two programs.

**Comment by chiraag-nataraj** [comment]
I understand that technically this may break the symlink (say, if the symlink is to a blacklisted directory), but that should be up to the user to figure out/manage (and shouldn't happen in the vast majority of cases anyway).

**Comment by netblue30** [comment]
Fixed!

**Comment by chiraag-nataraj** [comment]
Awesome! Thanks!
