### ISSUE TITLE
support mkdir in ${RUNUSER}

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3346]
Support mkdir in ${RUNUSER}.

Current behaviour:
test.profile: `mkdir ${RUNUSER}/foo`
`firejail --profile=test.profile`: `Error: only directories in user home or /tmp are supported by mkdir`

wruc will need it sometimes.

**Comment by netblue30** [comment]
I also added mkfile, you can try it out.

**Comment by rusty-snake** [comment]
manpage nitpick: it's `/run/user/<UID>` and not `<PID>`.
