### ISSUE TITLE
make whitelist file names a bit more permissive (allowed characters)

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#335]
Currently firejail `whitelist` fails with the following letters:
`[](){}`
Unfortunately though, these letters are often used by some cultures, like for example torrent video files. It'd be nice if firejail supported those [names].

This is a delicate topic though, suggestions or criticism welcome. For example, I personally would not include `&` or `$` as good file names. To be allowed in firejail or not - I don't know.

**Comment by netblue30** [comment]
moved to: https://github.com/netblue30/firejail/issues/216

**Comment by vn971** [comment]
Any update on this? The #216 ticket does not address special characters `[](){}`...

**Comment by netblue30** [comment]
None so far. I updated #216
