### ISSUE TITLE
Question: Environment variables

### ISSUE THREAD

**Issue by matu3ba** [netblue30/firejail#3350]
Currently the number of environment variables is restricted to 100 in `firejail.h`.
```
#define MAX_ENVS 100	// some sane maximum number of environment variables
```
For tmux or screen (or weird shell quirks) these however blow up to in my case 171. When I call from within tmux git push/pull, this fails with `fprintf(stderr, "Error: too many environment variables\n");`. Any standard shell uses ~80 environment variables (`printenv | wl -l`).  
What is the advisory for such programs? Do there exist techniques to drop the variables for the program call, so it has no access to the unnecessary environment information or is this still wild west-like?

**Comment by rusty-snake** [comment]
You can add somethingl like this to a .local:
```
rmenv FOO
rmenv BAR
rmenv DISPLAY
rmenv LC_ALL
rmenv XDG_SESSION_TYPE
rmenv XAUTHORITY
```

**Comment by topimiettinen** [comment]
I have 64 variables, so 100 seemed to have some safety margin. But 256 would be fine too.

If a variable is only used by a certain CLI program (for example LS_COLORS for ls), you can use bash aliases:
v=$(vivid)
alias ls="LS_COLORS=$v /bin/ls --color=auto"

GNU coreutils contain `env` program, which can be used for cleaning of the environment.

The environment variables could be used for a classic [stack smashing attack](https://insecure.org/stf/smashstack.html). Using 256 variables, each MAX_ENV_LEN (4096+32), totals a bit more than 1MB, which should not be enough for the attack on 64 bit system.

How do screen and tmux use the variables? Manual pages for [tmux](http://man.openbsd.org/OpenBSD-current/man1/tmux.1#ENVIRONMENT) and [screen](https://www.gnu.org/software/screen/manual/screen.html#Environment) don't mention anything special.

**Comment by matu3ba** [comment]
@topimiettinen I use tmux with a quirk to run in appimages.
I do use `oh my tmux`, but other enhancements usually are configured via environment variables.
`printenv | grep tmux | wc -l`
88

**Comment by matu3ba** [comment]
@topimiettinen 
`echo $LS_COLORS | fgrep -o "." | wc -l`
114
-_-

**Comment by matu3ba** [comment]
> You can add somethingl like this to a .local:
> 
> ```
> rmenv FOO
> rmenv BAR
> rmenv DISPLAY
> rmenv LC_ALL
> rmenv XDG_SESSION_TYPE
> rmenv XAUTHORITY
> ```

This does not seem to support globbing ie `rmenv tmux*` or `rmenv tmux.*, but `unset` does neither.

**Comment by Grinkers** [comment]
I normally have about 80 variables and after using byobu (tmux) I end up at about 105. It looks like it's used for things like color, window naming, etc sort of things.

For the time being, I've just set MAX_ENVS to 256.
