### ISSUE TITLE
Terminal control codes in progress messages should be optional

### ISSUE THREAD

**Issue by rdiez** [netblue30/firejail#3356]
Firejail outputs some terminal control codes when printing information:

------8<------8<------8<------
$ firejail --noprofile sh -c "echo a"

^[]0;firejail sh -c echo a ^Ga
Parent pid 21368, child pid 21369

Parent is shutting down, bye...
------8<------8<------8<------

Note the "^[]0;" at the beginning: Those are escape characters for some terminal. And the same with "^Ga" at the end.

I do not know what the codes are for. They do not seem to colourise the ouput, which is what applications usually do with such control codes.

Such "garbage" shows up in log files and is unsightly. The first reaction is suspicion of data corruption.

Firejail should at least check whether STDOUT is a terminal before outputting such colour or terminal codes.

Other tools like Git offer more control, see for example:
git -c color.ui=always status

I suggest implementing an option like command "ls" does:

------8<------8<------8<------

--color[=WHEN]
colorize the output; WHEN can be 'always' (default if omitted), 'auto', or 'never'; more info below

Using  color  to distinguish file types is disabled both by default and with --color=never.  With --color=auto, ls emits color codes only when standard output is connected to a
terminal.  The LS_COLORS environment variable can change the settings.  Use the dircolors command to set it.

------8<------8<------8<------

This issue was mentioned first in bug #3354.

I have tested this with the latest Firejail release version 0.9.62.

**Comment by smitsohu** [comment]
For some reason I cannot reproduce, but it has been reported before.

Suspect:
https://github.com/netblue30/firejail/blob/5014a434e5b0a735a7fcd4a1170408337fe4fc09/src/firejail/env.c#L160-L162

**Comment by rusty-snake** [comment]
@smitsohu If they are printed to the terminal your can't see they, try to `firejail --noprofile true | less` or `firejail --noprofile true > foo && vim foo`.

**Comment by smitsohu** [comment]
@rusty-snake Thanks, now I have it!

That code in env.c is indeed the reason for this artifact. As it doesn't make any sense to inject control characters if stdout is not a terminal, I agree that a minimal fix should check this first.

**Comment by smitsohu** [comment]
Thanks for reporting the bug!
