### ISSUE TITLE
Useless lines in disable-common.inc

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3358]
We `include disable-common.inc` before we set `nodbus`/`dbus-(user|system) none` and `x11 none`.

https://github.com/netblue30/firejail/blob/ed0c218e52bca9b0a4db8c420c1c8d9e405eaa71/etc/disable-common.inc#L67-L68

https://github.com/netblue30/firejail/blob/ed0c218e52bca9b0a4db8c420c1c8d9e405eaa71/etc/disable-common.inc#L139-L140

**Comment by glitsj16** [comment]
@rusty-snake Nice find. Should be safe to take out these useless lines IMO.
