### ISSUE TITLE
GUI option to keep files

### ISSUE THREAD

**Issue by HulaHoopWhonix** [netblue30/firejail#336]
For better usability oz sanbox are adding a feature to allow moving a file out of a container if a user wants to keep it in the GNOME GUI. Maybe you can implement a similar feature so users have a way to benefit from firejail's security while keeping things they download. This is a feature enhancement that makes sense for Firetools.

**Comment by netblue30** [comment]
Will do, thanks!

**Comment by netblue30** [comment]
Implemented --ls and --get options in firejail, I'll bring in something similar for firetools.

**Comment by HulaHoopWhonix** [comment]
You sir are awesome.
