### ISSUE TITLE
Dolphin: allow lua for playing videos with mpv

### ISSUE THREAD

**Issue by AloisJanicek** [netblue30/firejail#3363]
`mpv` video player launched from dolphin by clicking on video file will not start (will not appear on screen at all) unless `lua` is enabled in dolphin.profile.
Looks like some kind of lua repl for `mpv` input commands was introduced in [mpv v0.31.0](https://github.com/mpv-player/mpv/releases/tag/v0.31.0) released at the end of December 2019.
Prior to that playing videos in `mpv` launched from dolphin with click on the video file used to work without problems.

**Solution**
enabling lua interpreters with `include allow-lua.inc` in dolphin.profile

**Desktop**
 - Arch Linux
- Firejail  version 0.9.63 (AUR pkg firejail-git, r6095.cde87023-1)

**Comment by glitsj16** [comment]
Hi, thank you for reporting this issue. As it happens, I was looking into reworking all our file manager profiles to avoid issues like yours. It doesn't make much sense to block access to commonly used interpreters (like Lua, Perl, Python, ...) for that category of applications. I'll add a fix in the dolphin profile.

**Comment by rusty-snake** [comment]
@glitsj16 would you think removing `disable-interpreters.inc` makes more sense. With the current dolphin profile you can't start programs written in python, perl, ...

**Comment by glitsj16** [comment]
@rusty-snake Agreed. That's why I just opened #3365.
