### ISSUE TITLE
GitHub truncates the /etc/firejail dir

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3366]
Looks like we've hit a GitHub limit, as we have 1000+ files under /etc/firejail:

`Sorry, we had to truncate this directory to 1,000 files. 1 entry was omitted from the list.`

Unsure if there's anything we can do about it in the short run. @netblue30?

**Comment by rusty-snake** [comment]
You can press `t` to search.
There is also #2231, but 970 `*.profile`.

**Comment by glitsj16** [comment]
@rusty-snake Thanks for reminding me of #2231. I added a comment to it, building on your [proposal](https://github.com/netblue30/firejail/issues/2231#issuecomment-505788246), which seems to be the better place to discuss this.

**Comment by netblue30** [comment]
moved to #2231
