### ISSUE TITLE
Nicotine does not start

### ISSUE THREAD

**Issue by captaidman** [netblue30/firejail#3368]
**Describe the bug**
Nicotine does not run in firejail

**Behavior change on disabling firejail**
Nicotine runs outside of firejail

**To Reproduce**
Type nicotine in terminal, press enter

**Expected behavior**
Nicotine run in firejail

**Desktop (please complete the following information):**
Linux Mint 19.3 Tricia

firejail --version
firejail version 0.9.63

Compile time support:
	- AppArmor support is disabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

**Additional context**
$ nicotine
Reading profile /usr/local/etc/firejail/nicotine.profile
Reading profile /usr/local/etc/firejail/allow-python2.inc
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-exec.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-passwdmgr.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/disable-xdg.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-runuser-common.inc
Reading profile /usr/local/etc/firejail/whitelist-usr-share-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 15275, child pid 15276
8 programs installed in 22.20 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Blacklist violations are logged to syslog
Child process initialized in 157.77 ms

Parent is shutting down, bye...

**Comment by rusty-snake** [comment]
Anything in the syslog/journal?

**Comment by captaidman** [comment]
> Anything in the syslog/journal?

No changes at all

**Comment by matu3ba** [comment]
@captaidman Output of `firejail --debug nicotine` ?

**Comment by captaidman** [comment]
[debug.txt](https://github.com/netblue30/firejail/files/4521450/debug.txt)

**Comment by matu3ba** [comment]
Should be related to #3360 with the same workaround. Linux Mint loading of programs or PATH handling seems to be completely different from other distributions.

**Comment by rusty-snake** [comment]
@captaidman `echo $PATH`?

**Comment by captaidman** [comment]
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by rusty-snake** [comment]
Looks normal.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
