### ISSUE TITLE
Permission denied vs. Not found

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#338]
This isn't really an issue, it's just more of a question.
I use private-bin in both firefox and libreoffice, and in both cases, the filter is *extremely* limited. When I join the libreoffice jail, I get a `<such and such>: not found`. If, however, I join the firefox jail, I get a `<such and such>: Permission denied`. Why is there this difference?

For reference, here is my firefox profile:
````
# Blacklist/Whitelist

blacklist /usr/local/bin
blacklist /usr/local/sbin

whitelist ${HOME}/.mozilla
whitelist ${HOME}/Downloads/
whitelist ${HOME}/.pulse/
whitelist ${HOME}/.config/pulse/
whitelist ${HOME}/.config/gtk-3.0/
whitelist ${HOME}/.config/google-googletalkplugin/
whitelist ${HOME}/.gtkrc-2.0
whitelist ${HOME}/.gtkrc.mine
whitelist ${HOME}/.Xauthority
whitelist ${HOME}/PDF/

# Private directories

private-bin firefox.real,firefox,which,sh
private-etc hosts,passwd,mime.types,fonts/,mailcap,iceweasel/,xdg/,gtk-3.0/,resolv.conf,X11/,pulse/,adobe/,gcrypt/,alternatives/
private-tmp

# Miscellaneous options

shell none
seccomp
noroot
caps.drop all
protocol unix,inet,inet6
````
And here is my libreoffice profile:
````
whitelist ${HOME}/Documents
whitelist ${HOME}/.config/libreoffice
whitelist ${HOME}/.config/gtk-3.0
whitelist ${HOME}/.gtkrc-2.0
whitelist ${HOME}/.gtkrc.mine
private-dev
private-bin sh,libreoffice,dirname,grep,uname,ls,sed,pwd,basename
private-etc libreoffice,fonts,passwd
caps.drop all
noroot
nogroups
shell none
net none
seccomp
````

**Comment by netblue30** [comment]
Give me some examples (command and output). There could be something there, I'll take a look. Thanks.

**Comment by chiraag-nataraj** [comment]
````
firejail --join=`pidof iceweasel`
$ cat
/bin/sh: 1: cat: Permission denied
````
versus
````
firejail --join=`pidof soffice.bin`
$ cat
/bin/sh: 1: cat: not found
````

**Comment by netblue30** [comment]
It doesn't find /bin/cat, you need to add it to private-bin.

In your profiles, disable private-bin (comment it out with a #). Run "sudo firemon" in a different terminal. This will give you a list of all the programs the sandbox tries to run when you start the sandboxes. Then, you add all these programs to private-bin and enable it.

**Comment by chiraag-nataraj** [comment]
I know it doesn't find /bin/cat (I didn't want it to). My point is that cat is blacklisted in both of the profiles, but each gives a different error message.

**Comment by netblue30** [comment]
I guess they are used interchangeably in the code, or even in some system utilities firejail calls during sandbox init.
