### ISSUE TITLE
Error: too long environment variables in vifm's subshell

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#3383]
**Describe the bug**
I am getting `Error: too long environment variables` error in console for commands run inside `vifm`'s subshell. Here's one example:
```
wget https://some_url
Error: too long environment variables
```

**Behavior change on disabling firejail**
when `wget` is run w/ absolute path (hence without `firejail`) it runs normally.

**To Reproduce**
1. run `vifm`
2. <kbd>Esc</kbd> `:shell`
3. `wget`
4. observe the error

**Expected behavior**
It would be great if jailed programs work inside `vifm` session.  

**Desktop:**
 - Arch Linux, 64bit, current
 ```
firejail version 0.9.63

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

  firejail-git r6104.17b717ed-1
```

**Comment by rusty-snake** [comment]
FYI: #3325

**Comment by matu3ba** [comment]
> FYI: #3325 

Either making size of environment variables bigger on risk of stack smashing (I am unsure what is the minimum size for that though),
or clean up your `env`.

**Comment by jose1711** [comment]
Thanks for pointing this out.
inside `vifm`
```
$ env | awk -F= '(length-length($1)) > 4096 {print $1" variable has "(length-length($1))" chars!"}' 
PROMPT variable has 5953 chars!
```
in "normal" shell session:
```
PROMPT is not exported
```
On my system it's caused by a specific combination of oh-my-zsh and `vifm` customization so I changed it in the configuration. Thank you, closing.
