### ISSUE TITLE
scp / sftp does not work while firejail as a shell 

### ISSUE THREAD

**Issue by bobykus** [netblue30/firejail#339]
ssh works well

my@my:~/$ ssh    ssltest2@some
Last login: Mon Feb 29 11:47:32 2016 from from_host

46:bash:open /dev/tty:3
46:bash:open /etc/bash.bashrc:-1
46:bash:open /hsphere/local/home/ssltest2/.bashrc:3
46:bash:open /dev/tty:3
46:bash:fopen /etc/passwd:0x1891008
46:bash:open /etc/bash.bashrc:-1
46:bash:open /hsphere/local/home/ssltest2/.bashrc:3
46:bash:open /hsphere/local/home/ssltest2/.bash_history:-1
46:bash:open /hsphere/local/home/ssltest2/.bash_history:-1
46:bash:access /lib/terminfo/x/xterm-256color:0
46:bash:fopen /lib/terminfo/x/xterm-256color:0x1899808

Unfortunately neither scp or sftp works. F.ex. for scp

my@my:~/$ scp  -P 8080 os.sh   ssltest2@some:ssltest2.dk 
Error: cannot find the program in the path
lost connection

/etc/firejail/login.users looks like

ssltest2:--private-bin=bash,sed,ls,cat,less,scp,wget,top,ps,sftp,slogin,nano,cp,mv,rm --private-dev --private-etc=group,hostname,localtime,nsswitch.conf,passwd,resolv.conf --private-tmp --nosound --noroot  --seccomp   --quiet  --trace

Did I miss something  in configuration or is it by design?

**Comment by bobykus** [comment]
OS Debian 8 
uname -a
Linux wst1ssh 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

**Comment by netblue30** [comment]
All fixed, give it a try. If there are still problems I'll reopen the bug. Thanks!

**Comment by bobykus** [comment]
still an issue. here is what I did

git clone https://github.com/netblue30/firejail.git 
cd firejail
./configure --disable-x11 --prefix=/usr --disable-bind; make; make install

my@my:~/$ scp -P8080 p   ssltest1@IP:
Error: cannot find the program in the path
lost connection


here a logs

scp -vvv -P8080 p   ssltest1@HostIP:
Executing: program /usr/bin/ssh host HostIP, user ssltest1, command scp -v -t .
OpenSSH_6.9p1 Ubuntu-2ubuntu0.1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /home/ip/.ssh/config
debug1: /home/ip/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/home/ip/.ssh/master-ssltest1@HostIP:8080" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to HostIP [HostIP] port 8080.
debug1: Connection established.
debug1: identity file /home/ip/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_rsa-cert type -1
debug1: identity file /home/ip/.ssh/id_dsa type 2
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9p1 Ubuntu-2ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.7p1 Debian-5+deb8u1
debug1: match: OpenSSH_6.7p1 Debian-5+deb8u1 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to HostIP:8080 as 'ssltest1'
debug3: put_host_port: [HostIP]:8080
debug3: hostkeys_foreach: reading file "/home/ip/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/ip/.ssh/known_hosts:1688
debug3: load_hostkeys: loaded 1 keys from [HostIP]:8080
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-ed25519,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-sha1
debug2: kex_parse_kexinit: hmac-sha1
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HWoWrPi07WC8/ZffUbHR0p0mHsJRf4WJHd9NBzKSzn4
debug3: put_host_port: [HostIP]:8080
debug3: put_host_port: [HostIP]:8080
debug3: hostkeys_foreach: reading file "/home/ip/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/ip/.ssh/known_hosts:1688
debug3: load_hostkeys: loaded 1 keys from [HostIP]:8080
debug3: hostkeys_foreach: reading file "/home/ip/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/ip/.ssh/known_hosts:1688
debug3: load_hostkeys: loaded 1 keys from [HostIP]:8080
debug1: Host '[HostIP]:8080' is known and matches the ECDSA host key.
debug1: Found key in /home/ip/.ssh/known_hosts:1688
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/ip/.ssh/id_rsa (0x55ba4e8e0eb0),
debug2: key: /home/ip/.ssh/id_dsa (0x55ba4e8ee600),
debug2: key: /home/ip/.ssh/id_ecdsa ((nil)),
debug2: key: /home/ip/.ssh/id_ed25519 ((nil)),
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/ip/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug1: Offering DSA public key: /home/ip/.ssh/id_dsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /home/ip/.ssh/id_ecdsa
debug3: no such identity: /home/ip/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/ip/.ssh/id_ed25519
debug3: no such identity: /home/ip/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
ssltest1@HostIP's password: 
debug2: we sent a password packet, wait for reply
debug1: Authentication succeeded (password).
Authenticated to HostIP ([HostIP]:8080).
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /home/ip/.ssh/master-ssltest1@HostIP:8080.UEWVpISxIRWkkZN8
debug2: fd 5 setting O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug1: channel 0: new [/home/ip/.ssh/master-ssltest1@HostIP:8080]
debug3: muxserver_listen: mux listener channel 0 fd 5
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug1: control_persist_detach: backgrounding master process
debug2: control_persist_detach: background process is 16548
debug2: fd 5 setting O_NONBLOCK
debug1: forking to background
debug1: Entering interactive session.
debug2: set_control_persist_exit_time: schedule exit in 1500 seconds
debug1: multiplexing control connection
debug2: fd 6 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK
debug1: channel 1: new [mux-control]
debug3: channel_post_mux_listener: new mux channel 1 fd 6
debug3: mux_master_read_cb: channel 1: hello sent
debug2: set_control_persist_exit_time: cancel scheduled exit
debug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4
debug2: process_mux_master_hello: channel 1 slave version 4
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4
debug2: process_mux_alive_check: channel 1: alive check
debug3: mux_client_request_alive: done pid = 16550
debug3: mux_client_request_session: session request sent
debug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 81
debug2: process_mux_new_session: channel 1: request tty 0, X 0, agent 0, subsys 0, term "xterm-256color", cmd "scp -v -t .", env 1
debug3: process_mux_new_session: got fds stdin 7, stdout 8, stderr 9
debug2: fd 7 setting O_NONBLOCK
debug2: fd 8 setting O_NONBLOCK
debug1: channel 2: new [client-session]
debug2: process_mux_new_session: channel_new: 2 linked to control channel 1
debug2: channel 2: send open
debug2: callback start
debug2: client_session2_setup: id 2
debug1: Sending environment.
debug1: Sending env LANG = en_DK.UTF-8
debug2: channel 2: request env confirm 0
debug1: Sending command: scp -v -t .
debug2: channel 2: request exec confirm 1
debug3: mux_session_confirm: sending success reply
debug2: callback done
debug2: channel 2: open confirm rwindow 0 rmax 32768
debug1: mux_client_request_session: master session id: 2
debug2: channel 2: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 2
debug2: exec request accepted on channel 2
debug2: channel 2: rcvd ext data 43
debug2: channel 2: rcvd eof
debug2: channel 2: output open -> drain
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug3: mux_exit_message: channel 2: exit message, exitval 1
debug1: client_input_channel_req: channel 2 rtype eow@openssh.com reply 0
debug2: channel 2: rcvd eow
debug2: channel 2: close_read
debug2: channel 2: input open -> closed
debug2: channel 2: rcvd close
debug3: channel 2: will not send data after close
debug2: channel 2: obuf_empty delayed efd 9/(43)
Error: cannot find the program in the path
debug2: channel 2: written 43 to efd 9
debug3: channel 2: will not send data after close
debug2: channel 2: obuf empty
debug2: channel 2: close_write
debug2: channel 2: output drain -> closed
debug2: channel 2: send close
debug2: channel 2: is dead
debug2: channel 2: gc: notify user
debug3: mux_master_session_cleanup_cb: entering for channel 2
debug2: channel 1: rcvd close
debug2: channel 1: output open -> drain
debug2: channel 1: close_read
debug2: channel 1: input open -> closed
debug2: channel 2: gc: user detached
debug2: channel 2: is dead
debug2: channel 2: garbage collecting
debug1: channel 2: free: client-session, nchannels 3
debug3: channel 2: status: The following connections are open:
  #2 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

debug2: channel 1: obuf empty
debug2: channel 1: close_write
debug2: channel 1: output drain -> closed
debug2: channel 1: is dead (local)
debug2: channel 1: gc: notify user
debug3: mux_master_control_cleanup_cb: entering for channel 1
debug2: channel 1: gc: user detached
debug2: channel 1: is dead (local)
debug2: channel 1: garbage collecting
debug3: mux_client_read_packet: read header failed: Broken pipe
debug1: channel 1: free: mux-control, nchannels 2
debug3: channel 1: status: The following connections are open:

debug2: Received exit status from master 1
debug2: set_control_persist_exit_time: schedule exit in 1500 seconds
lost connection


on server


Mar  3 13:20:20 HostIP sshd[24413]: debug1: server_input_channel_open: ctype session rchan 2 win 2097152 max 32768
Mar  3 13:20:20 HostIP sshd[24413]: debug1: input_session_request
Mar  3 13:20:20 HostIP sshd[24413]: debug1: channel 0: new [server-session]
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_new: session 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_open: channel 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_open: session 0: link with channel 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: server_input_channel_open: confirm session
Mar  3 13:20:20 HostIP sshd[24413]: debug1: server_input_channel_req: channel 0 request env reply 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_by_channel: session 0 channel 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_input_channel_req: session 0 req env
Mar  3 13:20:20 HostIP sshd[24413]: debug1: server_input_channel_req: channel 0 request exec reply 1
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_by_channel: session 0 channel 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_input_channel_req: session 0 req exec
Mar  3 13:20:20 HostIP sshd[24413]: Starting session: command for ssltest1 from 212.97.132.13 port 56791
Mar  3 13:20:20 HostIP sshd[24413]: debug1: Received SIGCHLD.
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_by_pid: pid 24430
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_exit_message: session 0 channel 0 pid 24430
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_exit_message: release channel 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_by_channel: session 0 channel 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_close_by_channel: channel 0 child 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: session_close: session 0 pid 0
Mar  3 13:20:20 HostIP sshd[24413]: debug1: channel 0: free: server-session, nchannels 1

**Comment by netblue30** [comment]
If you remove private-bin from login.user, does it work?

**Comment by bobykus** [comment]
No, sorry, it does not work, even with a latest build

 cat /etc/firejail/login.users
....
ssltest2:--private-dev --private-etc=hostname,localtime,nsswitch.conf,resolv.conf --private-tmp --nosound --noroot  --seccomp   --quiet  --trace

scp -vvvv -P 8080 zfs  ssltest2@HostIP:
Executing: program /usr/bin/ssh host HostIP, user ssltest2, command scp -v -t .
OpenSSH_6.9p1 Ubuntu-2ubuntu0.1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /home/ip/.ssh/config
debug1: /home/ip/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/home/ip/.ssh/master-ssltest2@HostIP:8080" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to HostIP [HostIP] port 8080.
debug1: Connection established.
debug1: identity file /home/ip/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_rsa-cert type -1
debug1: identity file /home/ip/.ssh/id_dsa type 2
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ip/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9p1 Ubuntu-2ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.7p1 Debian-5+deb8u1
debug1: match: OpenSSH_6.7p1 Debian-5+deb8u1 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to HostIP:8080 as 'ssltest2'
debug3: put_host_port: [HostIP]:8080
debug3: hostkeys_foreach: reading file "/home/ip/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/ip/.ssh/known_hosts:1688
debug3: load_hostkeys: loaded 1 keys from [HostIP]:8080
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-ed25519,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-sha1
debug2: kex_parse_kexinit: hmac-sha1
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HWoWrPi07WC8/ZffUbHR0p0mHsJRf4WJHd9NBzKSzn4
debug3: put_host_port: [HostIP]:8080
debug3: put_host_port: [HostIP]:8080
debug3: hostkeys_foreach: reading file "/home/ip/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/ip/.ssh/known_hosts:1688
debug3: load_hostkeys: loaded 1 keys from [HostIP]:8080
debug3: hostkeys_foreach: reading file "/home/ip/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/ip/.ssh/known_hosts:1688
debug3: load_hostkeys: loaded 1 keys from [HostIP]:8080
debug1: Host '[HostIP]:8080' is known and matches the ECDSA host key.
debug1: Found key in /home/ip/.ssh/known_hosts:1688
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/ip/.ssh/id_dsa (0x560036690620),
debug2: key: /home/ip/.ssh/id_rsa (0x560036682ed0),
debug2: key: /home/ip/.ssh/id_ecdsa ((nil)),
debug2: key: /home/ip/.ssh/id_ed25519 ((nil)),
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering DSA public key: /home/ip/.ssh/id_dsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-dss blen 433
debug2: input_userauth_pk_ok: fp SHA256:9FduooRsuHFOHpOpSJeTtd0/DyGoD/rXvcpgXbqR0BE
debug3: sign_and_send_pubkey: DSA SHA256:9FduooRsuHFOHpOpSJeTtd0/DyGoD/rXvcpgXbqR0BE
debug1: Authentication succeeded (publickey).
Authenticated to HostIP ([HostIP]:8080).
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /home/ip/.ssh/master-ssltest2@HostIP:8080.1skalT8IXmmsOtXC
debug2: fd 5 setting O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug1: channel 0: new [/home/ip/.ssh/master-ssltest2@HostIP:8080]
debug3: muxserver_listen: mux listener channel 0 fd 5
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug1: control_persist_detach: backgrounding master process
debug2: control_persist_detach: background process is 8862
debug2: fd 5 setting O_NONBLOCK
debug1: forking to background
debug1: Entering interactive session.
debug2: set_control_persist_exit_time: schedule exit in 1500 seconds
debug1: multiplexing control connection
debug2: fd 6 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK
debug1: channel 1: new [mux-control]
debug3: channel_post_mux_listener: new mux channel 1 fd 6
debug3: mux_master_read_cb: channel 1: hello sent
debug2: set_control_persist_exit_time: cancel scheduled exit
debug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4
debug2: process_mux_master_hello: channel 1 slave version 4
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4
debug2: process_mux_alive_check: channel 1: alive check
debug3: mux_client_request_alive: done pid = 8864
debug3: mux_client_request_session: session request sent
debug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 81
debug2: process_mux_new_session: channel 1: request tty 0, X 0, agent 0, subsys 0, term "xterm-256color", cmd "scp -v -t .", env 1
debug3: process_mux_new_session: got fds stdin 7, stdout 8, stderr 9
debug2: fd 7 setting O_NONBLOCK
debug2: fd 8 setting O_NONBLOCK
debug1: channel 2: new [client-session]
debug2: process_mux_new_session: channel_new: 2 linked to control channel 1
debug2: channel 2: send open
debug2: callback start
debug2: client_session2_setup: id 2
debug1: Sending environment.
debug1: Sending env LANG = en_DK.UTF-8
debug2: channel 2: request env confirm 0
debug1: Sending command: scp -v -t .
debug2: channel 2: request exec confirm 1
debug3: mux_session_confirm: sending success reply
debug2: callback done
debug2: channel 2: open confirm rwindow 0 rmax 32768
debug1: mux_client_request_session: master session id: 2
debug2: channel 2: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 2
debug2: exec request accepted on channel 2
debug2: channel 2: rcvd ext data 43
Error: cannot find the program in the path
debug2: channel 2: written 43 to efd 9
debug2: channel 2: rcvd eof
debug2: channel 2: output open -> drain
debug2: channel 2: obuf empty
debug2: channel 2: close_write
debug2: channel 2: output drain -> closed
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug3: mux_exit_message: channel 2: exit message, exitval 1
debug1: client_input_channel_req: channel 2 rtype eow@openssh.com reply 0
debug2: channel 2: rcvd eow
debug2: channel 2: close_read
debug2: channel 2: input open -> closed
debug2: channel 2: rcvd close
debug3: channel 2: will not send data after close
debug2: channel 2: send close
debug2: channel 2: is dead
debug2: channel 2: gc: notify user
debug3: mux_master_session_cleanup_cb: entering for channel 2
debug2: channel 1: rcvd close
debug2: channel 1: output open -> drain
debug2: channel 1: close_read
debug2: channel 1: input open -> closed
debug2: channel 2: gc: user detached
debug2: channel 2: is dead
debug2: channel 2: garbage collecting
debug1: channel 2: free: client-session, nchannels 3
debug3: channel 2: status: The following connections are open:
  #2 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

debug2: channel 1: obuf empty
debug2: channel 1: close_write
debug2: channel 1: output drain -> closed
debug2: channel 1: is dead (local)
debug2: channel 1: gc: notify user
debug3: mux_master_control_cleanup_cb: entering for channel 1
debug2: channel 1: gc: user detached
debug2: channel 1: is dead (local)
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: channel 1: garbage collecting
debug1: channel 1: free: mux-control, nchannels 2
debug2: Received exit status from master 1
debug3: channel 1: status: The following connections are open:

debug2: set_control_persist_exit_time: schedule exit in 1500 seconds
lost connection

**Comment by netblue30** [comment]
I am on Debian 8, with default sshd configuration and it seems to be working fine.
`````
$ /usr/sbin/sshd --version
unknown option -- -
OpenSSH_6.7p1 Debian-5+deb8u1, OpenSSL 1.0.1k 8 Jan 2015
`````

Did you modify /etc/ssh/sshd_config? Can you run it if you remove everything from /etc/firejail/login.users?

**Comment by bobykus** [comment]
Yes, all is working fine. Thank you!
