### ISSUE TITLE
seccomp filter are generated multible times

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3393]
**Describe the bug**

The following block in the Makefile is called multiple times with `make` and `make install`.

https://github.com/netblue30/firejail/blob/8c69eab213556169ad5ea303e46fb0a80499b004/Makefile.in#L46-L58

**To Reproduce**
1. Add `@echo HELLO I AM CALLED` above
https://github.com/netblue30/firejail/blob/8c69eab213556169ad5ea303e46fb0a80499b004/Makefile.in#L49
2. Run `./configure && make && make install`
3. See `HELLO I AM CALLED` around 12 times

**Expected behavior**
seccomp filter are just generated once

cc @topimiettinen

**Comment by topimiettinen** [comment]
To me the Makefile looks just fine. Probably it isn't a bug in Make either. Running `make --debug=m` shows that rules don't work as expected though.

**Comment by rusty-snake** [comment]
> To me the Makefile looks just fine.

I'm to a makefile expert, I don't see what's wrong, just that something is wrong.

**Comment by topimiettinen** [comment]
I think the problem was with use of .PHONY.
