### ISSUE TITLE
Firefox save file dialog not showing

### ISSUE THREAD

**Issue by rr4444** [netblue30/firejail#3407]
Hi, all used to be well, but at some point file dialogs for saving downlaods, etc. no longer come and nothing can be saved on update. Presumably something changed. I am running KDE Neon, which is basically KDE team curated Plasma on Ubuntu 18.04

STOUT on firefox shows:
`
(firefox:9): Gtk-WARNING **: 16:39:45.695: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open /proc/11862/root`

out of curiosity, it might be relevant that stout also shows:

`(firefox:9): Gtk-CRITICAL **: 16:41:04.624: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed
`

syslog shows:
```

> 07/05/2020 16:25 ThinkPad-L480 dbus-daemon[1121] [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.8975' (uid=1000 pid=11862 comm="/usr/lib/firefox/firefox " label="unconfined")
> 07/05/2020 16:25 ThinkPad-L480 systemd[1] Starting Hostname Service...
> 07/05/2020 16:25 ThinkPad-L480 kernel [27040.845661] talpa-vfshook: Patching hugetlbfs
> 07/05/2020 16:25 ThinkPad-L480 kernel [27040.845680] talpa-vfshook: Patched hugetlbfs
> 07/05/2020 16:25 ThinkPad-L480 dbus-daemon[1121] [system] Successfully activated service 'org.freedesktop.hostname1'
> 07/05/2020 16:25 ThinkPad-L480 systemd[1] Started Hostname Service.
> seems to be the associated logs when no file dialog comes up
```

**Comment by rusty-snake** [comment]
To allow freedesktop portal access, you need to allow dbus (`ignore nodbus`) and IIRC noroot (`ignore noroot`). Alternative you could try to `rmenv GTK_USE_PORTAL`.

**Comment by rr4444** [comment]
Thanks, much appreciated. Sorry, I am fairly new to firejail. I can dig, but to direction my digging, are you talking about the config for the firejail 'container' that firefox is run in? 

Is it surprising that this is suddenly an issue and wasn't? (stupid question, unless it isn't!)

**Comment by rusty-snake** [comment]
> Sorry, I am fairly new to firejail. 

don't worry

> I can dig, but to direction my digging, are you talking about the config for the firejail 'container' that firefox is run in?

Yes, the easiest way is to create a file called `firefox.local` in `~/.config/firejail` and add there
```
ignore nodbus
ignore noroot
```

_This will no longer work with firejail>=0.9.63, due to changes in the dbus handling of firejail_

> Is it surprising that this is suddenly an issue and wasn't? (stupid question, unless it isn't!)

Likely that an update set `GTK_USE_PORTAL=1` as default.

**Comment by rr4444** [comment]
Many thanks - much appreciated
