### ISSUE TITLE
Allow --dbus-user=none on the command line for profiles with dbus-user filter

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3408]
I just tried to start firefox with `--private` and `--dbus-user=none` and it failed because firefox.profile sets `dbus-user filter` and firejail does not allow relaxing the policy. `Error: Cannot relax dbus-user policy, it is already set to block`. IMHO the must common case is that a user wants to deny dbus access per run or default and add `dbus-user none` to xxx.local or the command line and shouldn't need to also add `ignore dbus-user filter`.

**Comment by kris7t** [comment]
The idea was to prevent setting a weaker DBus policy without explicitly authorizing the weakening with `--ignore`. But it seems I was a bit overzealous, as this effectively prevents strengthening the policy (if the (`--dbus-user=` options are not in the right order) also.

I think it would be safe to downgrade this to a warning, and keep the stricter policy of the two specified. I'll add this to #3406.
