### ISSUE TITLE
rpmlint error "missing-call-to-setgroups-before-setuid"

### ISSUE THREAD

**Issue by HeikoAdams** [netblue30/firejail#341]
When running rpmlint on a rpm package build by using the specfile from this repo there is one error listed:
> E: missing-call-to-setgroups-before-setuid /usr/lib64/firejail/libtrace.so

Which is explained with:

> missing-call-to-setgroups-before-setuid:
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.

**Comment by netblue30** [comment]
libtrace.so is overloading a number of functions in glibc for tracing purposes. Calling setuid and setgid from this library is not necessary. This is the responsibility of the calling program.

I know it looks bad in rpmlint, but I don't know how to disable the error message. For Debian .deb files is usually done with a /lintian-overrides.
