### ISSUE TITLE
u2f key not detected in firejailed browser

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [netblue30/firejail#3413]
Hello, what's the status of firejail working with a u2f key (usb device)?
I see that the issue has been reported in #1990, #2723.

At the moment, I have added "whitelist /dev/hidraw*" to my browser profile, but then my browser would not launch.

Is there a solution to this problem yet or I have not found it?
Thanks.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/issues/3170#issuecomment-576266164 and the following.

**Comment by rusty-snake** [comment]
In firejail >= 0.9.63 is is enough to set `browser-disable-u2f no` in `/etc/firejail/firejail.config`.

**Comment by GreatBigWhiteWorld** [comment]
Sadly my provider has only 0.9.62 in the repo.
