### ISSUE TITLE
Unetbootin + Firejail ???

### ISSUE THREAD

**Issue by opqriu** [netblue30/firejail#3415]
https://unetbootin.github.io/linux_download.html

I run Unetbootin in Debian in the following way.
`~ $ sudo ./unetbootin-linux64-677.bin`

I want to use the Firejile sandbox.
Please Can you tell me how to do it?
Thank you.

**Comment by rusty-snake** [comment]
Works `sudo firejail --noprofile ./unetbootin-linux64-677.bin`?

**Comment by opqriu** [comment]
It's best.
That ’s cool.
thank you for telling me.

**Comment by glitsj16** [comment]
@opqriu A bit too soon to close this IMO. The `--noprofile` option suggested by @rusty-snake is only the beginning so to speak. It's looking good that it worked (at least I assume it did looking at your generous emoji response), but that offers only **very minimal** protection. We'll need to test if/how we can properly restrict a unetbootin sandbox before we can add a profile for it. With a bit of patience we'll get there ;-)

**Comment by rusty-snake** [comment]
As a next step, you could try `sudo firejail --ignore=noroot --ignore=nonewprivs --profile=default unetbootin`.

Note: we need `--profile=default` explicit because firejail will use server.profile if it is started as root.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
