### ISSUE TITLE
Busybox

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#3416]
I just saw and #3411 and remembered that BusyBox also has a built-in shell.
But in addition to that it also has a bunch of other programs (`busybox --list`).
So BusyBox might be used to run programs that would otherwise be blocked.
What about blocking it by default? In the case it is needed, one can unblock it again.

**Comment by glitsj16** [comment]
>  What about blocking it by default? In the case it is needed, one can unblock it again.

Nice catch. We could add it to `disable-common.inc`, which should provide broader blocking coverage than #3411 would IMO. Being a utility for rescue and embedded systems the impact of blocking busybox by default should be (very) minimal. Plus we can do that straight-away, no need to wait until @rusty-snake is ready to merge his disable-shell.inc work.

**Comment by reinerh** [comment]
Added in 5e2d5aa.

**Comment by xplshn** [comment]
> Nice catch. We could add it to disable-common.inc, which should provide broader blocking coverage than https://github.com/netblue30/firejail/pull/3411 would IMO. Being a utility for rescue and embedded systems the impact of blocking busybox by default should be (very) minimal. Plus we can do that straight-away, no need to wait until @rusty-snake is ready to merge his disable-shell.inc work.

... How can I build firejail in Alpine?

**Comment by kmk3** [comment]
> ... How can I build firejail in Alpine?

It's described in README.md:

* <https://github.com/netblue30/firejail?tab=readme-ov-file#other>

See also the alpine CI job:

* <https://github.com/netblue30/firejail/blob/2301ab23488b9db95eba40750f355a4439468b89/.gitlab-ci.yml#L95-L110>

**Comment by xplshn** [comment]
Sorry, didn't catch it. THanks!
