### ISSUE TITLE
seccomp is breaking wire-desktop

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#3423]
specs- Manjaro (KDE), Kernel: 5.6.x, Firejail ver: 0.9.62  wire: 3.17.2924

output of firejail --debug : https://gist.github.com/Neo00001/a77cc18994863c41327e7e0fa45e3554

**Comment by glitsj16** [comment]
Hi, looking at your debug log doesn't indicate conclusively this is a seccomp issue. It might be #2946 (which is fixed in git). There's an easy way to determine seccomp issues in firejail though, so if you can run the below after starting wire-desktop that would be helpful.

`$ sudo journalctl | grep syscall`

If you get output like ... syscall=123 ... you can determine which syscall is used although it was forbidden by the profile:

`$ firejail --debug-syscalls | grep 123`

If you don't get any output and you want to check if it's #2946, add the below in your wire-desktop.local:

```
ignore caps.drop all
caps.keep sys_admin,sys_chroot

ignore seccomp
seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice
```

**Comment by Neo00001** [comment]
output of firejail --debug-syscalls shows personality



> ignore caps.drop all
> caps.keep sys_admin,sys_chroot
> 
> ignore seccomp
> seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice


it doesn't launch wire.

`seccomp !chroot` fixes the problem. using `seccomp !chroot` only fixes it.



> BTW, can you post what's in your wire-desktop.local currently?

`ignore net`

`whitelist ~/Downloads/Wire/`

**Comment by glitsj16** [comment]
I forgot that the '!' syntax is actually supported in 0.9.62. As for your wire-desktop.local, I just wanted to make sure there wasn't anything there that might be interfering. The system-wide wire-desktop.profile already whitelists ${HOME}/Downloads, so the subdir reference shouldn't be strictly necessary. I'll fix the profile in git, so make a note that you can remove 'seccomp !chroot' from the .local on a future firejail upgrade. Thanks for reporting!

**Comment by Neo00001** [comment]
> The system-wide wire-desktop.profile already whitelists ${HOME}/Downloads, so the subdir reference shouldn't be strictly necessary.

I have commented out that in profile. & I use different directory for different apps.

**Comment by rusty-snake** [comment]
> I have commented out that in profile. & I use different directory for different apps.

I do the same (for firefox) you can add `nowhitelist ${HOME}/Downloads` to wire-desktop.local so you don't need to comment this after every update of firejail. Also you can add `blacklist ${HOME}/Downloads/Wire` to `disable-xdg.local` or so to block some blacklisting profiles from accessing it (if you want).
