### ISSUE TITLE
Feature request: Allow bind in non-root mode

### ISSUE THREAD

**Issue by howryu** [netblue30/firejail#3426]
It seems that currently firejail only allows --bind under root user. Is this design for security concern? Is it possible to add support for non root user case? Probably need some sanitize in source/target directory e.g. source directory must be owned by current user, target directory should place under home directory.

**Comment by rusty-snake** [comment]
>  Is this design for security concern?

Yes, consider `--bind=~/evil.sudoers,/etc/sudoers`

> Is it possible to add support for non root user case?

I think it is.

---

Closing as duplicated of #459 (that's realy old :woozy_face:)

**Comment by howryu** [comment]
@rusty-snake So is there plan to support binding in non-root case? Or how difficult it is to support that? Is sanitizing source/target directory's privilege good enough? 
My use case is that I had a subdirectory under `/opt`, e.g. `/opt/foo/bar`(bar is owned by non-root user who will start the firejail). I want to access `bar` directory inside jail without exposing directory tree of `/opt` (so `--private-opt` is not an option here). I am also looking at `--private-=` option (to mount `/opt/foo/bar` to the home directory), however I have multiple nested directory need to be accessed. so `--private=` is not viable either. :(

**Comment by glitsj16** [comment]
> So is there plan to support binding in non-root case?

There are no 'hidden' (non-public) plans in the firejail project. As long as there aren't any PR's specifically implementing this feature, it's safe to assume **no plans to do so**.

> Or how difficult it is to support that? Is sanitizing source/target directory's privilege good enough?

Hard to answer. At the very minimum a fair amount of C programming skills/experience and insight to the Linux kernel security infrastructure I'd say.

About your use case. If you can `mount --bind /opt/foo/bar /home/howryu/bar` _prior_ to starting firejail, it would be easy to control access to that location from inside the sandbox by way of all the regular firejail options (including private-opt none). Is there anything special to your use case that warrants the need for a bind mount _inside_ the sandbox?

**Comment by howryu** [comment]
@glitsj16 It seems that `mount` requires root privilege? I don't want to switch to root to do the mount.

**Comment by rusty-snake** [comment]
You could also do this at start by a systemd.service or fstab (https://serverfault.com/questions/613179/how-do-i-do-mount-bind-in-etc-fstab/613184#613184).
