### ISSUE TITLE
--blacklist=~/.mozilla warns of invalid file

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#343]
Firejail 0.9.38 on LMDE Betsy (closely related to Debian Jessie.)

I came across this while working on the profile for the Pale Moon browser. ~/.mozilla is viewable and read-write even when not whitelisted. Attempts to blacklist the directory, whether in the profile or in the startup arguments, fail with the warning that ~/.mozilla is an invalid file (which is half-way correct; it's a directory). However, blacklisting other directories, such as ~/.Downloads, succeeds.

`fred@aussie ~ $ firejail --blacklist=~/.mozilla --debug palemoon | grep mozilla`
`Reading profile /home/fred/.config/firejail/palemoon.profile`
`Reading profile /etc/firejail/disable-mgmt.inc`
`Reading profile /etc/firejail/disable-secret.inc`
`Reading profile /etc/firejail/disable-common.inc`
`Reading profile /etc/firejail/disable-devel.inc`
`Reading profile /etc/firejail/whitelist-common.inc`
`...`
`Debug 337: new_name #/home/fred/.themes#`
`Warning: /home/fred/.mozilla is an invalid file, skipping...`

When I blacklist a different directory such as Downloads:
`fred@aussie ~ $ firejail --blacklist=~/Downloads --debug palemoon | grep Downloads`
`Reading profile /home/fred/.config/firejail/palemoon.profile`
`Reading profile /etc/firejail/disable-mgmt.inc`
`Reading profile /etc/firejail/disable-secret.inc`
`Reading profile /etc/firejail/disable-common.inc`
`Reading profile /etc/firejail/disable-devel.inc`
`Reading profile /etc/firejail/whitelist-common.inc`
`...`
`Disable /home/fred/Downloads`

In case the profile is to blame:
`# Pale Moon Browser profile`
`include /etc/firejail/disable-mgmt.inc`
`include /etc/firejail/disable-secret.inc`
`include /etc/firejail/disable-common.inc`
`include /etc/firejail/disable-devel.inc`
`caps.drop all`
`seccomp`
`protocol unix,inet,inet6,netlink`
`netfilter`
`tracelog`
`noroot`
`whitelist ${DOWNLOADS}`
` `
`whitelist ~/.moonchild productions`
`whitelist ~/.cache/moonchild productions/pale moon`
` `
`# Uncommented in Firefox profile. If you run into trouble you may want to enable`
`# (some of) them.`
`#whitelist ~/dwhelper`
`#whitelist ~/.zotero`
`#whitelist ~/.lastpass`
`#whitelist ~/.vimperatorrc`
`#whitelist ~/.vimperator`
`#whitelist ~/.pentadactylrc`
`#whitelist ~/.pentadactyl`
`#whitelist ~/.keysnail.js`
`#whitelist ~/.config/gnome-mplayer`
`#whitelist ~/.cache/gnome-mplayer/plugin`
` `
`#blacklist ~/.mozilla/`
` `
` `
`include /etc/firejail/whitelist-common.inc`
` `
`# experimental features`
`#private-etc passwd,group,hostname,hosts,localtime,nsswitch.conf,resolv.conf,gtk-2.0,pango,fonts,adobe,mime.types,mailcap,asound.conf,pulse`

I'm not sure if this is actually a bug or whether I'm to blame. Hopefully someone with a better understanding of the situation can chime in. :)
Thanks!
Fred

**Comment by netblue30** [comment]
I put in some debug code to see where the message is coming from. Give it a try, thanks!

**Comment by Fred-Barclay** [comment]
Sorry--I'm missing something. Where's the debug code? :)

**Comment by netblue30** [comment]
I'll have a testing release coming in about one week.

**Comment by Fred-Barclay** [comment]
Sounds good. :)

I'm going to set up a testing VM and start building firejail from source too.
(I try to avoid compiling on my main machine. Just a personal preference.)
