### ISSUE TITLE
Version 0.9.62 forces Dropbox to load in firejail

### ISSUE THREAD

**Issue by bertradio** [netblue30/firejail#3431]
I just upgraded from 0.9.59 to 0.9.62 and now whenever I try and start Dropbox it tries to start in firejail and fails. The command dropbox start on the command line does not load Dropbox but acts as if I had typed firejail dropbox. This does not happen in 0.9.59.

**Comment by glitsj16** [comment]
It sounds as if you're using `firecfg`, which uses a symlinked /usr/local/bin/dropbox to provide desktop integration. If you don't want that, just remove the symlink. Or you can call Dropbox by its full path via `firejail /usr/bin/dropbox <arguments>`. Can you provide output of that command here so we can determine what might be the problem? What OS is this?

**Comment by bertradio** [comment]
Thanks for the speedy reply.

I am running Linux Mint 19.3 64-bit.

I had reverted ot 0.9.59 but for testing did the following:
 1. Uninstalled firejail
 2. Uninstalled Dropbox
 3. Reinstalled Dropbox - version 97.4.467
 4. Reinstalled firejail 0.9.62-1
 5. Changed the startup path for Dropbox to /usr/bin/dropbox
 6. Rebooted
With this setup both firejail and Dropbox work as expected, but look at the results of the following commands:

So there must be something on my system which tries to load Dropbox in firejail if I just type dropbox (rather than the full path). I do have a file /usr/bin/env but I have no idea what it is (see attached)

Any idea what might be going on?

Thanks

Bert

**Comment by rusty-snake** [comment]
@bertradio looks like github filters attachments. I can see your screenshots/log-files/… .

finds `grep -l dropbox ~/.local/share/applications` any files?

what shows `which dropbox`?

>  Changed the startup path for Dropbox to /usr/bin/dropbox

Where?

**Comment by bertradio** [comment]
/home/bert/.local/share/applications has no files named dropbox

**Comment by rusty-snake** [comment]
sorry, wrong command. I mean`grep -l dropbox ~/.local/share/applications/*`.

**Comment by bertradio** [comment]
Changed the startup path in Startup Applications (accessible from the Mint menu)

**Comment by bertradio** [comment]
Found the problem. There was a file named dropbox in /usr/local/bin which was running when I typed dropbox rather than the one in /usr/bin. That was the file which was causing dropbox to try to run in firejail. When I renamed this file, the problem went away. Not sure how this file got into /usr/local/bin but the date on the file was last December. Also don't understand why I did not have this problem with 0.9.59.

In any event, now all is working as it should with 0.9.62.

Thanks

Bert

**Comment by bertradio** [comment]
Looking further in my logs I see that I did at one time run firecfg and that's what probably put the link in /usr/local/bin along with links to a lot of other programs.

So it appears the fault was mine, not firejail's.

**Comment by rusty-snake** [comment]
still an issue?

**Comment by bertradio** [comment]
No. The problem was that at some time I had run firecfg which created a bunch of links.
