### ISSUE TITLE
apparmor breaks dbus-*=filter

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3432]
Ubuntu 20.04:

command: `firejail --dbus-user=filter --dbus-user.own=org.gnome.gedit --dbus-user.talk=ca.desrt.dconf --apparmor gedit`
note: settings are imutable

journal: `AVC apparmor="DENIED" operation="connect" profile="firejail-default" name="/run/firejail/dbus/1000/5813-user" pid=5819 comm="gedit" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000`

**Comment by Vincent43** [comment]
@rusty-snake try adding:

`owner /{,var/}run/firejail/dbus/[0-9]*/[0-9]*-user w,`

or 
`/{,var/}run/firejail/dbus/[0-9]*/[0-9]*-user w,`

**Comment by rusty-snake** [comment]
:100:

**Comment by curiosityseeker** [comment]
So shouldn't this rule added to `firejail-default` by default?

**Comment by Vincent43** [comment]
It should
