### ISSUE TITLE
Sound only working with one program at a time with ALSA

### ISSUE THREAD

**Issue by fareyozz** [netblue30/firejail#3436]
- Describe the bug.
When starting software with firejail, only one can output audio. Any other program will be completely silent, and fail to start audio playback.
- What did you expect to happen?
All software should be able to output audio at the same time.

- What changed calling `firejail --noprofile PROGRAM` in a shell?
The program successfully outputs audio.

1. Start a program (eg. Chromium) with the default profile and make it output audio
2. Start another program (eg. Steam) with the default profile and make it output audio
Audio coming from Chromium continues playing, while Steam is completely silent.
With debug output enabled, I get the message "ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave".

**Environment**
Artix Linux, kernel 5.6.14-zen1-1-zen
firejail version 0.9.62
No other program interact with the affected program.

**Additional context**
Pulseaudio isn't installed.
firecfg --fix-audio did not fix the issue (and failed to execute properly).
Issue seems simillar to #3282, except I am not using pulseaudio at all.

**Comment by rusty-snake** [comment]
- So this only happens if program A and B are firejailed or also if only A?
- If A is firejailed (with profile) and B without profile (=`--noprofile`) it works?
- You say default profile do you mean `default.profile` or `chromium.profile`?

**Comment by fareyozz** [comment]
> * So this only happens if program A and B are firejailed or also if only A?
It only happens if both are firejailed.

> * If A is firejailed (with profile) and B without profile (=`--noprofile`) it works?
Yes, B works properly with --noprofile.

> * You say default profile do you mean `default.profile` or `chromium.profile`?
I mean chromium.profile. Same with Steam, steam.profile was used (with more relaxed settings). 
It also happens when I'm using a custom profile (attached below) with other programs.
Oddly enough, VirtualBox (with virtualbox.profile) seems unaffected by the issue.

[custom.profile.txt](https://github.com/netblue30/firejail/files/4691124/custom.profile.txt)
[steam.profile.txt](https://github.com/netblue30/firejail/files/4691126/steam.profile.txt)

**Comment by rusty-snake** [comment]
Thats good news for you, because it can easily fixed. Can you try which option in steam.profile which is not in custom.profile cause this. (`nogroups`?)

**Comment by fareyozz** [comment]
Seems like the "ipc-namespace" option is the culprit! Removing it from the profiles fixes everything. Thanks!

**Comment by tostiheld** [comment]
I am having a very similar problem, but commenting "ipc-namespace" does not seem to resolve the issue. Running with --noprofile does fix it, but I have no idea what the culprit is exactly. I have tried commenting different things in steam.profile, but frankly, I have no idea what I'm doing. Any advice on other things to try would be appreciated.

**Comment by rusty-snake** [comment]
Comment everything in steam.profile (it should work then as `--noprofile` is effectively the same) and uncomment then line for line.
