### ISSUE TITLE
How to block all internet except 127.0.0.1 localhost

### ISSUE THREAD

**Issue by hiBrett** [netblue30/firejail#3439]
Is there any way to block a sandboxed program from all internet access except specifically allow access to 127.0.0.1 localhost?

I'm working on having a node.js server run side by side with a sandboxed program, and I want them to communicate.

The [documentation](https://firejail.wordpress.com/documentation-2/basic-usage/) mentions adding a bridge under 4.2 Routed Network Setup, but I don't understand how to make that work for this purpose, or if it would work for this purpose.

Relates to:

* #108

**Comment by glitsj16** [comment]
> Is there any way to block a sandboxed program from all internet access except specifically allow access to 127.0.0.1 localhost?

Have you tried the `--net=none` option? Or `--protocol=unix` if the former crashes the application. If either of those does what you want, you can put the relevant option into a foo.local file, which (1) you will have to create and which (2) uses a slightly different syntax: `net none` or `protocol unix`.

**Comment by rusty-snake** [comment]
FWIW: #108

There are two ways bridge (`net`) or iptables (`netfilter`).

@glitsj16 `net=none` has its own `lo` interface, and therefore its own 127.0.0.1. and `protocol unix` break IPv4/Ipv6 sockets.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.

**Comment by jGsch** [comment]
@rusty-snake 

> net=none has its own lo interface, and therefore its own 127.0.0.1

it means, for example, the adress `127.0.0.1:9095` does not point to the same thing if I am in a firejail or not? If yes, so I need to use `--netfilter` to make a bridge between `127.0.0.1:9095` (host) and `127.0.0.1:9095` (firejail) ?

**Comment by rusty-snake** [comment]
> it means, for example, the adress 127.0.0.1:9095 does not point to the same thing if I am in a firejail or not?

If you use `--net=none`, yes.

> If yes, so I need to use --netfilter to make a bridge between 127.0.0.1:9095 (host) and 127.0.0.1:9095 (firejail)?

Nope. `--netfilter` is use iptables. Depending on what you want use `--net=tap0`/`--net=br0` or  just drop all `--net=` commands.

**Comment by jGsch** [comment]
> just drop all --net= commands.

But if I do that, the process can communicate with the outside. 

My goal is the same as OP, I want to remove internet access to a process but it still need to update a redis database so I need to keep access to locahost. 

So from what a understand, there is two possibilities:
- use `--netfilter` with a iptables to restrict all network access except for localhost (no need of `--net` in this case)
-  create a virtual namespace which block everything except localhost and use it with `--net`

(I'm new with all this networking stuff and it's a little bit hard to assimilate all these new things)

**Comment by rusty-snake** [comment]
`--join-network=` could do the trick in your case. Run a second browser instance in the network namespace of your server.

**Comment by l8l** [comment]
I also need this feature. Running a local database that I want to query with a program that must otherwise be cut off from the internet.

**Comment by kmk3** [comment]
Re-closing as "not planned" since this is a duplicate of:

* #108

**Comment by keesj** [comment]
This appears to be such a basic question for a program called a jail (specially in these days of programs wanting to access the internet) .
