### ISSUE TITLE
Wiki: Using firejail from git

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3443]
Issue for discussions about https://github.com/netblue30/firejail/wiki/Using-firejail-from-git.

**Comment by glitsj16** [comment]
I added a routine to the Debian/Ubuntu section referring to our [update_deb.sh](https://github.com/netblue30/firejail/blob/master/contrib/update_deb.sh) script from contrib and opened #3450 for review. As mentioned there I don't exactly know how to patch firejail.config to accomodate https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916920. Or even whether we want that. Would be nice to get input on how to best proceed on the latter.

**Comment by curiosityseeker** [comment]
I added some more configuration options.

**Comment by rusty-snake** [comment]
> sudo sed -i 's/# force-nonewprivs no/force-nonewprivs yes/' /etc/firejail/firejail.config

1. We could add more (restrict-network, ...)
2. We should add a warning that `make install` overrides `/etc/firejail/firejail.config`.

**Comment by glitsj16** [comment]
I added the warning for (2) cfr. @rusty-snake's suggestion.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/discussions/4450
