### ISSUE TITLE
wine registry does not save changes

### ISSUE THREAD

**Issue by antsn** [netblue30/firejail#3446]
firejail version 0.9.62

I have no problems with modifying ``wine`` registry without ``firejail``. But with ``firejail`` all the changes are revert to default.
Here is my ``wine.profile``:
```
# Firejail profile for wine
# Description: A compatibility layer for running Windows programs
# This file is overwritten after every install/update
# Persistent local customizations
include wine.local
# Persistent global definitions
include globals.local

noblacklist ${HOME}/.Steam
noblacklist ${HOME}/.local/share/Steam
noblacklist ${HOME}/.local/share/steam
noblacklist ${HOME}/.steam

noblacklist ${HOME}/.wine
whitelist ${HOME}/.wine
noblacklist /tmp/.wine-*
whitelist /tmp/.wine-*

include disable-common.inc
include disable-devel.inc
include disable-interpreters.inc
include disable-passwdmgr.inc
include disable-programs.inc

# some applications don't need allow-debuggers, comment the next line
# if it is not necessary (or put 'ignore allow-debuggers' in your wine.local)
allow-debuggers
caps.drop all
netfilter
nodvd
nogroups
nonewprivs
noroot
notv
seccomp

private-dev

#############
blacklist /media
blacklist /mnt
```

**Comment by antsn** [comment]
It seems that changes actually wrote to disk, while modifying registry with ``regedit`` (with ``filejail``), I open another ``regedit``, and saw that data was modified.
But, after close ``regedit``, the registry is reset.

**Comment by rusty-snake** [comment]
Works it with `--noprofile`?

**Comment by antsn** [comment]
No, I've tested.
I've read somewhere that (for the case of running ``wine`` normally, without  ``firejail``) problem with ``wineserver`` can cause registry modification can't be save. But, I don't know how it relate with this case.
I checked, and ``/tmp/.wine-5555`` is accessible, my UID = 5555.

**Comment by rusty-snake** [comment]
> I checked, and /tmp/.wine-5555 is accessible

Where do you check this? Inside the sandbox?

> No, I've tested.

bad

Are there any lines uncommented in /etc/firejail/firejail.config?


What distro? Which wine version?

**Comment by antsn** [comment]
Yes, I checked inside the sandbox:
```firejail --profile=wine.profile ls -1na /tmp/.wine-5555```

I use Mageia 7.1, wine-5.7, and everything is untouched.

**Comment by antsn** [comment]
Update2:  
Registry's changes **actually** saved. But for entries that will not be permanently stored (that be reset if, for example run ``wineboot``), after ``regedit`` (with ``firejail``) is closed, those entries are reset to default.

Example:  
If I add a new ``String value`` entry called ``test``. The change is saved.  
If I modify ```HKEY_LOCAL_MACHINE>Hardware>Description>System>CentralProcessor>0>VendorIdentifier``` from ``AuthenticAMD`` to ``None``, it does not works with ``firejail``.  

Without ``firejail``, the change is saved, but if I run ``wineboot``, it reset to default.

**Comment by rusty-snake** [comment]
Any progress here?
