### ISSUE TITLE
Consider adding "Allow Python" to Steam.profile so Blender runs

### ISSUE THREAD

**Issue by amanda-santini** [netblue30/firejail#3449]
EDIT: Didn't really solve the problem, and there are already two identical lines in the profile.
I'll just use Blender without Steam until I find out more about this issue.

---------------------------

Hi there!

Let me apologize for the simple bug report. I'm a 3D artist who uses Blender via Steam on Linux and I don't have much time to go deep into this, but I believe there's no real need to do so. Here's why:

Steam just updated Blender to version 2.83, which was freezing my laptop then proceeding to crash itself (Blender). After a bit of experimentation, I found that Blender works fine with the default profile, so there could be something going on with the Steam profile.

The solution was simple, add the following two lines to Steam.profile:

```
# Allow python (blacklisted by disable-interpreters.inc)
include allow-python2.inc
include allow-python3.inc
```

These lines are in Blender's default profile, and they allow the program's addons to run (which AFAIK are all in Python).

Since Blender is an official product on Steam and is used by many people on Steam's community, I think it makes sense to add these two lines for the Steam.profile file.

Cheers!

**Comment by rusty-snake** [comment]
Hi, what is your firejail version? Can you create `~/.config/firejail/steam.local` with this content:
```
ignore private-etc

noblacklist ${HOME}/.config/blender
mkdir ${HOME}/.config/blender
whitelist ${HOME}/.config/blender

noblacklist /sys/module
whitelist /sys/module/amdgpu
read-only /sys/module/amdgpu
```
If you use firejail <0.9.63 remove the `whitelist ${HOME}/.config/blender`.

**Comment by amanda-santini** [comment]
Hi! I'm using 0.962-3.

If I create that file, Steam doesn't start.

```
amanda@amanda:~$ firejail steam
Reading profile /etc/firejail/steam.profile
Reading profile /home/amanda/.config/firejail/steam.local
Reading profile /etc/firejail/allow-java.inc
Reading profile /etc/firejail/allow-python2.inc
Reading profile /etc/firejail/allow-python3.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 18819, child pid 18820
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Child process initialized in 157.52 ms
/usr/games/steam: 74: /home/amanda/.steam/debian-installation/ubuntu12_32/steam: Permission denied
cat: '/home/amanda/.steam/debian-installation/ubuntu12_32/steam-runtime.tar.xz.part*': No such file or directory
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
find: ‘/home/amanda/.steam/debian-installation/ubuntu12_32/steam-runtime’: No such file or directory

Parent is shutting down, bye...
```

**Comment by amanda-santini** [comment]
I'd like to apologize for wasting everybody's time with this issue. It seems it's a Blender problem.

I tried a new download of the 2.83 build, ran it without firejail, and the problem happened as well but just took longer to happen.

I'll contact Blender's developers to see what's going on.

Thanks rusty-snake for trying to help.
