### ISSUE TITLE
firejail.config defaults for cgroup/restricted-network and Debian bug 916920

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3451]
While working on the Debian/Ubuntu [firejail-from-git wiki page](https://github.com/netblue30/firejail/wiki/Using-firejail-from-git#Debian) I remembered a [comment](https://github.com/netblue30/firejail/issues/3420#issuecomment-629850160) from @reinerh on Debian bug [916920](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916920).

If I'm not mistaken the firejail packages from the [PPA](https://launchpad.net/~deki/+archive/ubuntu/firejail) patch **firejail.config** to set `cgroup no` and `restricted-network yes`. If these are considered insecure (as the bug report suggests), I wonder why we keep `cgroup yes` and `restricted-network no` as our defaults. Thoughts?

**Comment by rusty-snake** [comment]
If we change "restricted-network" we should keep in mind that `net eth0` for example in `firefox.local` or so is silently ignored.

---

In general disabling firejail-features either in firejail.config or with configure reduces the risk that bugs in this code can be used for priv-esc. On the other hand sandboxes are not so tight when things like whitelist are disabled.

<details><summary>my firejail.config hardening </summary>

NOTE: I've disabled some of them also via `./configure --disable-*`.

```
#############
# Hardening #
#############

# Deny apparmor  -- using SELinux
apparmor no

# Deny bind -- I not use this
bind no

# Deny cgroup -- I not use this
cgroup no

# Deny chroot -- I not use this/was broken on last try
chroot no 

# Force disable-mnt -- moved to locals
#disable-mnt yes

# Disable file transfer -- I not use this
file-transfer no

# Force nonewprivs -- mitigation against several attacks with suid-bins
# NOTE: programs like wireshark or chrome are not usable anymore with firejail
# you need bubblewarp or something else.
force-nonewprivs yes

# Deny join
#join no

# Deny name
#name-change no

# Deny net netfilter and interface -- I not use this
network no

# Deny overlayfs -- I not use this
overlayfs no

# Deny private-home -- I not use this
private-home no

# Deny private-cache
#private-cache no

# Deny private-lib
#private-lib no

# Resrict network features to root only
restricted-network yes

# Deny seccomp
#seccomp no

# Deny noroot
#userns no

# Deny whitelist
#whitelist no

# Deny x11 -- X11 is dead, long live Wayland
x11 no
```

</details>

**Comment by glitsj16** [comment]
Let's close this and stay with current defaults. Users can always change preferences themselves.
