### ISSUE TITLE
need help using github-markdown on wiki page

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3452]
While working on the Debian/Ubuntu [firejail-from-git wiki page](https://github.com/netblue30/firejail/wiki/Using-firejail-from-git) I tried linking to the 'Arch Linux' and 'Debian/Ubuntu' sections in the TOC. My markdown skills didn't cut it though, and I had to use 'Arch' and 'Debian' anchors instead of 'Arch Linux' and 'Debian/Ubuntu' (wich would be more appropriate IMO). If someone could get those anchors straigthened out that would be awesome.

**Comment by SkewedZeppelin** [comment]
If you edit the titles first then click preview and hover over the link it'll show you to use.
Then go back and edit and update your link.
https://github.com/netblue30/firejail/wiki/Using-firejail-from-git/_compare/366998c5ec77229619b9e9e7010070cf3f8747f8...6df85209cc72bf7873ec09161003a9f166e8faea

**Comment by glitsj16** [comment]
@SkewedZeppelin Thanks for the explanation and the fix!
