### ISSUE TITLE
Thunderbird sandbox by Firejail remain active even after close/quit Thunderbird

### ISSUE THREAD

**Issue by Nokia808** [netblue30/firejail#3458]
As the title said exactly ! I tried both from terminal & from .desktop file, the same ! Is this normal or a bug ?  With Firefox & other applications like Transmission sandbox disappear from --list when application exited ...

I'm with version 0.9.62 on Fedora 32 X64 bit Cinnamon edition.

**Comment by rusty-snake** [comment]
Maybe it is #928. What shows `firejail --tree`?

**Comment by Nokia808** [comment]
@rusty-snake 
Yes it is #928 - see the following:

$ firejail --tree
2341:myusername::firejail thunderbird 
  2345:myusername::firejail thunderbird 
    2540:myusername::gpg-agent --homedir /home/myusername/.gnupg --use-standard-socket --daemon 

This is very bad & should be fixed !
This is what make me afraid from using "sudo fcg"

Feel free to close this bug & mark it as a duplicate ...

**Comment by Nokia808** [comment]
As long as it is duplicate, I will close it.

**Comment by Nokia808** [comment]
Hi all. It seem to be fixed - at least for Thunderbird ! No when I closed Thunderbird after launching it by "firejail thunderbird" I will receive at the end the following in the terminal:

**"Parent is shutting down, bye..."**

This is very good !
