### ISSUE TITLE
Joplin AppImage does not run with firejail

### ISSUE THREAD

**Issue by DanielKane19** [netblue30/firejail#3461]
Write clear, concise and in textual form.

**Bug and expected behavior**
- Describe the bug.
Running AppImage of Joplin with Firejail fails.

- What did you expect to happen?
Joplin to start correctly.

**No profile or disabling firejail**
- What changed calling `firejail --noprofile PROGRAM` in a shell?
Application starts correctly with --noprofile

**Reproduce**
1.  Run in bash `firejail --appimage ./Joplin-1.0.216.AppImage`
2. No Errors appear, just: Parent is shutting down, bye...
AppImage unmounted

**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`)
Manjaro
 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`)
0.9.62

**Checklist**
 - [ ] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [ ] The upstream profile exists (`find / -name 'firejail' 2>/dev/null`/`fd firejail` to locate profiles ie in `/usr/local/etc/firejail/PROGRAM.profile`)
 - [ ] Programs needed for interaction are listed.
 - [ ] Error was checked in search engine and on issue list without success.

<details><summary> debug output </summary>

```
There are no errors. It just dies silently.
```

</details>

**Comment by rusty-snake** [comment]
Joplin has no firejail profile, you need to write one or request it in #1139.

**Comment by glitsj16** [comment]
Joplin has been requested, see https://github.com/netblue30/firejail/issues/1139#issuecomment-583861367.

**Comment by DanielKane19** [comment]
I apologize. I thought that --appimage will suffice even for apps for which there are no specific profiles. I will close this request then.
