### ISSUE TITLE
[Question] About sandbox "X11"

### ISSUE THREAD

**Issue by Nokia808** [netblue30/firejail#3466]
Hi dears.

I discover a very powerful feature in Firejail specially useful for Browsers & WineHQ. It is sandbox "X11" server.

I'm on Fedora & available to me "xpra". 

I have only one query that confuse me. The needed command is:
$ firejail --x11 --net=eth0 program-and-arguments

My question is about "eth0". Is this always ? Or user need to select it's currently active network interface ?
On my system there is no "eth0" when I run "$ ip link show". This command show me other (one for LAN wire connection, other for WiFi, & 3rd one I do not know but may be for modem & I'm already disabled "ModemManager" & for that it appear to me of UNKNOWN state ...).

Kindly, appreciate that I'm not experience with network connections ...

**Comment by SkewedZeppelin** [comment]
Your 3rd NIC is probably the bridge for libvirtd enabled by default on Fedora Workstation.

-----Original Message-----

**Comment by Nokia808** [comment]
@SkewedZeppelin 
I did not understood ! What I have to type, "eth0" or other thing ?

The output of "ip link show" on my system is:

```
$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000
    link/ether xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3: wlp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I delete the addresses & replaced them by xxxxxxxx because I do not know if they have a security impact if become public ...

**Comment by Nokia808** [comment]
Note: I'm not on Fedora Workstation, but I'm on Fedora X64 bit Cinnamon edition.

I'm afraid now that this issue will converted from a "Question" into incompatibility issue with recent features of Fedora ...

**Comment by rusty-snake** [comment]
Use `--net=enp0s25` or `--net=wlp4s0` depending on your connection.

**Comment by Nokia808** [comment]
@rusty-snake 
This mean I should use:
firejail --x11 --net=wlp4s0 firefox
as long I'm using WiFi connection to connect to Internet. Issue fixed.

But please document this. I suggest on you to add the following: "the parameter that should used with --net= should be your ACTIVE network connection, that you using to connect to Internet. You can use ip link show to display your network interfaces & their states". Adding such explanation to your documentation on your site is useful.

Before closing this issue I need to know about the following:

1) I concluded from the above that sandbox X11 should done only for those applications that connect or can connect to Internet. Is this true ?
2) can I use sandbox of X11 while I'm disconnected from Internet, for example, while using Firefox to open a saved web page off-line ?

**Comment by rusty-snake** [comment]
> I concluded from the above that sandbox X11 should done only for those applications that connect or can connect to Internet. Is this true ?

No, you can/should sandbox everything you want. Programs with internet access have a higher attack surface, so you should first focus on them while hardening you system.

>  can I use sandbox of X11 while I'm disconnected from Internet, for example, while using Firefox to open a saved web page off-line ?

Sure, it is completely unrelated. However, if you connect later to the internet, you must restart the sandbox to have network access.

**Comment by Nokia808** [comment]
Thank you, though - because I'm not technician I can not understand how it utilizing network interface that used to connect to Internet, & being unrelated whether it is active or not !

Kindly, to add your statement "if you connect later to the internet, you must restart the sandbox to have network access." to site documentation with what I suggested to add before.
