### ISSUE TITLE
Interfering with Itch.io game

### ISSUE THREAD

**Issue by Tanath** [netblue30/firejail#3468]
**Bug and expected behavior**
I've been attempting to install a game in Itch, and even with firejail disabled by default (`sudo firejail --clean`) it still gets interfered with by firejail. The Itch client isn't running in firejail, and the developer of the game doesn't know what firejail is:
https://itch.io/t/832898/asks-for-root-authentication-on-linux

**Reproduce**
1. I installed the Itch client via AUR.
2. I got [this bundle](https://itch.io/b/520/bundle-for-racial-justice-and-equality), which got me the game.
3. Installed game via Itch client from the [bundle page](https://itch.io/my-purchases/bundles).
4. Got issue seen in [Itch thread](https://itch.io/t/832898/asks-for-root-authentication-on-linux) above.

**Environment**
 - Linux distribution and version: Manjaro
 - Firejail version: 0.9.62. Compile time support: all enabled.
 - What other programs interact with the affected program for the functionality? Unity3D.

---
Whatever it's running isn't listed in `firejail --list` when the pw request occurs.

**Comment by glitsj16** [comment]
Hi, I'm having lots of troubles trying to install this to check what might be going wrong. Used makepkg to build itch from AUR on my Arch Linux machine, but the itch-setup command keeps throwing this error:

> 2020/06/16 00:46:43 Fatal error: Warm-up error: while opening remote signature file: htfs.Open (initial request): htfs connect: Get https://broth.itch.ovh/itch/linux-amd64/25.4.0/signature/default?downloadSessionId=d90aa650-7f18-45df-ba1a-c28a8ca57928: unexpected EOF

At the moment I can't even get itch installed to try to reproduce. You mention using `sudo firejail --clean`, but I assume you meant `sudo firecfg --clean`, as firejail doesn't have a --clean option. To ensure firejail is disabled you can run the latter and remove any remaining symlinks in /usr/local/bin that point to /usr/bin/firejail. Any kind of log you can provide would be helpful.

**Comment by Tanath** [comment]
I see the [AUR package](https://aur.archlinux.org/packages/itch) has been flagged out of date `Flagged out-of-date (2020-06-07)`, and I haven't seen that error before. You could try downloading the file manually and putting it in the build directory, checking the hash, and updating it in the PKGBUILD if necessary.

Sorry, yes, I meant firecfg. And `/usr/local/bin` is empty. Itch is not running in firejail, which is confirmed with `firejail --list` and `firejail --top`.

**Comment by rusty-snake** [comment]
I really have no idea what's going on. However I've two debugging ideas:
1. You can do a trick to prevent programs started by itch with firejail to run in a restrictive sandbox. firejail does not support transition or nesting, so if you start itch with `firejail --noprofile` is maybe works (if you believe in it hard enough :rofl: )
2. `firejail --list` and `firejail --top` only show the sandboxes currently running, using `sudo firemon` does not clear the output, so you can also see very short living sandboxes (e.g. `firejail ls`).

**Comment by Tanath** [comment]
Running with `firejail --noprofile itch` still mentions firejail in the popup, I don't get the password prompt, but then it just fails silently and doesn't run the game.

When I try with firemon, the only new lines that appear are:
```04:21:38 exec 2783879 (root) NEW SANDBOX: ./firejail --noprofile -- whoami
04:21:38 exit 2783879 (root) EXIT SANDBOX
04:21:42 exit 2779931 (tanath)
```

**Comment by glitsj16** [comment]
I finally got itch installed and did some basic testing. Registering an account, downloading a game, running update checks, login etcetera all succeeded, even with a nicely hardened profile.

@Tanath Could you test this profile without having the firecfg-generated symlinks please?

<details>
<summary> $ cat ${HOME}/.config/firejail/itch.profile </summary>

```
# Firejail profile for itch
# Description: The best way to play itch.io games
# This file is overwritten after every install/update
# Persistent local customizations
include itch.local
# Persistent global definitions
include globals.local

blacklist /tmp/.X11-unix

noblacklist ${HOME}/.config/itch
noblacklist ${HOME}/.itch
noblacklist ${HOME}/.local/share/pki
noblacklist ${HOME}/.pki

ignore noexec ${HOME}

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-interpreters.inc
include disable-programs.inc
include disable-xdg.inc

mkdir ${HOME}/.config/itch
mkdir ${HOME}/.itch
mkdir ${HOME}/.local/share/pki
mkdir ${HOME}/.pki
whitelist ${HOME}/.config/itch
whitelist ${HOME}/.itch
whitelist ${HOME}/.local/share/pki
whitelist ${HOME}/.pki
whitelist ${DOWNLOADS}

include whitelist-common.inc
include whitelist-runuser-common.inc
include whitelist-usr-share-common.inc
include whitelist-var-common.inc

apparmor
caps.drop all
netfilter
nodvd
nogroups
nonewprivs
noroot
notv
nou2f
novideo
protocol unix,inet,inet6,netlink
seccomp
shell none
#tracelog - breaks on Arch

# For me this private-bin worked, but I only played one game - uncomment for more extensive testing.
# private-bin bash,itch,sh
private-cache
private-dev
private-etc alternatives,asound.conf,ca-certificates,crypto-policies,fonts,gtk-3.0,machine-id,nsswitch.conf,pki,pulse,resolv.conf,selinux,ssl,X11

# The D-Bus filtering syntax below is incompatible with 0.9.62, but it works with firejail from git.
# dbus-user filter
# dbus-user.talk org.freedesktop.Notifications
# dbus-system none
```

</details>

**Comment by glitsj16** [comment]
> Running with firejail --noprofile itch still mentions firejail in the popup, I don't get the password prompt, but then it just fails silently and doesn't run the game.

I still don't know what is happening on your end exactly. But a screenshot of that popup would be helpful.

**Comment by rusty-snake** [comment]
@glitsj16 
Link from OP: https://itch.io/t/832898/asks-for-root-authentication-on-linux
Screenshot in this thread: https://img.itch.zone/aW1nLzM2NDk5MTIucG5n/original/iZZzIb.png

**Comment by Tanath** [comment]
I should mention I don't have this issue with other Itch games yet. Just the one.

I tried the pasted profile and got:

```
Reading profile /home/tanath/.config/firejail/itch.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Error: cannot access profile file: whitelist-runuser-common.inc
```

**Comment by rusty-snake** [comment]
> Log says error while elevating, pkexec not found in path. I can't copy the text, and it'd be multiple pages to screenshot, so that's the gist of it. Here's the top:

pkexec is blocked by firejail (`--noblacklist='${PATH}/pkexec'` to allow it) and it is the programs that ask you for root-privs.

**Comment by Tanath** [comment]
Yeah. I'm more interested in testing with firejail out of the way, but the only way I can think to do that is by completely uninstalling it. However I'm using it.

**Comment by rusty-snake** [comment]
When you used firemon, did you start itch with `firejail --noprofile itch` or `/usr/bin/itch`?

**Comment by Tanath** [comment]
Without firejail. Here's with noprofile:

```
17:28:13 fork 3153138 (tanath) /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler --json daemon --transport tcp --keep-alive --dbpath /home/tanath/.config/itch/db/butler.db --address https://itch.io --user-agent itch/25.4.0 (linux) --destiny-pid 11
        child 3172671 /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler --json daemon --transport tcp --keep-alive --dbpath /home/tanath/.config/itch/db/butler.db --address https://itch.io --user-agent itch/25.4.0 (linux) --destiny-pid 11
17:28:13 exec 3172671 (tanath) ./firejail --version
17:28:15 exit 3172671 (tanath)
17:28:16 fork 3153138 (tanath) /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler --json daemon --transport tcp --keep-alive --dbpath /home/tanath/.config/itch/db/butler.db --address https://itch.io --user-agent itch/25.4.0 (linux) --destiny-pid 11
        child 3172673
17:28:16 exec 3172673 (tanath) /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler --json --elevate install-prereqs /tmp/butler-prereqs-plan.json208915775
17:28:16 fork 3172673 (tanath) /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler --json --elevate install-prereqs /tmp/butler-prereqs-plan.json208915775
        child 3172680 /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler --json --elevate install-prereqs /tmp/butler-prereqs-plan.json208915775
17:28:16 uid (1000:0) 3172680 (tanath)
17:28:16 exec 3172680 (tanath) pkexec /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler run --dir /home/tanath -- /home/tanath/.config/itch/broth/butler/versions/15.17.0/butler --json install-prereqs /tmp/butler-prereqs-plan.json208915775
17:28:16 exit 3172680 (tanath)
17:28:16 exit 3172673 (tanath)
```

**Comment by rusty-snake** [comment]
Does this game know about firejail? (`strings path/to/extracted/game/files | grep firejail`)

**Comment by Tanath** [comment]
No mention of firejail in game files.

**Comment by kortewegdevries** [comment]
I think you're confusing your global Firejail install with [Itch's local per-game Firejail based sandbox](https://itch.io/docs/itch/using/sandbox.html) (see in preference of the launcher and disable it). [Butler](https://github.com/itchio/butler) is how the Itch manages, downloads and selects the correct launch for every game, I suppose it needs root access for installing it's own sandbox hence it's asking for so.

Itch's own sandbox creates an `isolate-app.profile` in `/home/korte/.config/itch/apps/hidden-folks/.itch/isolate-app.profile` where `/home/Username/.config/itch/apps/GameName/` is folder for each game and `.itch` is a directory inside every game.

```
:~/.config/itch/apps/hidden-folks/.itch$ cat isolate-app.profile

include /etc/firejail/itch_game_/home/korte/.config/itch/apps/hidden-folks/Hidden Folks.x86_64.local
include /etc/firejail/itch_games_globals.local

noblacklist /home/korte/.config/itch/apps/hidden-folks/Hidden Folks.x86_64
noblacklist /home/korte/.config/itch/apps/hidden-folks
noblacklist /home/korte/.config/itch/apps/hidden-folks/.itch/temp
blacklist /home/korte/.config/itch/apps/hidden-folks/.itch

noblacklist ${HOME}/.config/itch/apps
blacklist   ${HOME}/.config/itch/*
blacklist   ${HOME}/.config/itch/apps/*

noblacklist ${HOME}/.config/kitch/apps
blacklist   ${HOME}/.config/kitch/*
blacklist   ${HOME}/.config/kitch/apps/*

blacklist ~/.config/chromium
blacklist ~/.config/chrome
blacklist ~/.mozilla
```
Itch's launcher executable is located in `/home/korte/.itch/itch`. I had to make some minor modifications to the profile given by @glitsj16, ran the launcher with it `$ :~/.itch$ firejail --profile=/home/korte/.config/firejail/itch.profile ./itch`, tested my library out and things work fine. As for the game in question, it also works fine. Note that itch's own sandbox needs to be disabled here.
 
[itch.profile](https://github.com/netblue30/firejail/files/4863525/itch.txt)
[Hidden Folks app log png](https://user-images.githubusercontent.com/62639087/86348708-8fd8a680-bc4f-11ea-9453-165347189605.png)

**Comment by Tanath** [comment]
Ah! Thank you. That solves my issue. I didn't know Itch came with firejail. The [password prompt is a one-time request coming from the Itch app](https://itch.io/docs/itch/using/sandbox/linux.html).
