### ISSUE TITLE
Cppcheck static code analysis

### ISSUE THREAD

**Issue by temporaryaccount** [netblue30/firejail#348]
Firejail being a security product written in C needs a very careful approach when programming. Errors are unavoidable, I'd like to know whether it is being routinely checked by static analyzers like Cppcheck or the one in CLANG. FYI, Cppcheck reports some (maybe) minor issues like "%u in format string (no. 1) requires 'unsigned int' but the argument type is 'int'." or "scanf without field width limits can crash with huge input data. Add a field width specifier to fix this problem: %s => %20s", etc.

Thank you for this program!

**Comment by netblue30** [comment]
It is already included into the build (make cppcheck in the main project directoy).
