### ISSUE TITLE
Lutris and steam issue

### ISSUE THREAD

**Issue by Desulate** [netblue30/firejail#3483]
How do you fix this?

]0;firejail /usr/bin/steam steam://rungameid/489830 Child process initialized in 137.34 ms
/usr/lib/steam/steam: /home/sn/.local/share/Steam/steam.sh: /usr/bin/env: bad interpreter: Permission denied

Its currently stopping steam from launching from lutris

**Comment by rusty-snake** [comment]
There is no profile for lutris. Either request on in #1139 or write it by yourself.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity.
