### ISSUE TITLE
Tutanota-desktop difficult to integrate

### ISSUE THREAD

**Issue by CocoR55** [netblue30/firejail#3495]
Bonjour,
**Tutanota** works with **Appimage** in a sandbox under **Firejail**. To launch this application, a command is used in the terminal.
`$ firejail --profile=tutanota-desktop-linux.AppImage.profile ./tutanota-desktop-linux.AppImage --appimage-extract-and-run.`
 Now the difficulty is to create a launch or shortcut on both desktop or in the menu. Indeed, the command for desktop integration `$ sudo firecfg` remains without effect because if I understood well, the application `tutanota-desktop-linux.AppImage` is **not** mentioned in the file` /usr/lib/firejail/firecfg.config.`
I tried to create launchers on the desktop but it fails. The launcher keeps trying and fails with the following error message: `./tutanota-desktop-linux.AppImage `no such file.
I tried to create a launcher from the directory of the file to get around a possible lack of authorization, without more success.

If you have any ideas, they are welcome.

Regards,
CocoR55

**Comment by glitsj16** [comment]
@CocoR55 Based on #3485 you need to create ${HOME}/.local/share/applications/tutanota.desktop with the below content. For this example to work you need to confirm the AppImage is in /home/michaou/Tuta/Tutanota-desktop-linux.AppImage. If not, adjust the path in the 'Exec=...' line. Furthermore, I don't know if Tutanota comes with an icon of its own, so the 'Icon=/home/michaou/Tuta/Tutanota-desktop-linux.png' line probably needs changing and is just an example.

```
[Desktop Entry]
Name=Tutanota Desktop
Exec=sh -c "firejail --profile=tutanota-desktop-linux.AppImage.profile /home/michaou/Tuta/Tutanota-desktop-linux.AppImage --appimage-extract-and-run"
Icon=/home/michaou/Tuta/Tutanota-desktop-linux.png
Type=Application
Categories=Utility;
```

**Comment by glitsj16** [comment]
@CocoR55 If this all works for you, would you be so kind to close #3485 please? Just so we can keep our issue-tracker a bit organized... Of course, do this only if you're tutanota-desktop appimage is now fully operational as expected.

**Comment by CocoR55** [comment]
**@glitsj16**  First, #3485 is close. Second, I did that you proposed above. Sorry, that do not work. Nevertheless, 
I used your command line to insert into a launcher on the desktop and it works.
I still have a problem. I don't get it. I use the Tutanota-Desktop as a launcher. The tutanota site looks **dark** or light. I chose the **dark look.** Until then, I think he had it in mind. That's a good thing. For the last few days, it's been clear to start with. I can change the appearance, but nothing can change it at startup. Every time I launch the application to open the tutanota site, it always looks clear.
I'm thinking that maybe you have a little idea where the appearance would be saved, in some files.
Do you have an idea how to keep the same appearance at the beginning?

Regards,
**CocoR55**

**Comment by CocoR55** [comment]
**Correction**;  It all depends on how I exit the application. If I click on "disconnect", no problem, the appearance remains, at reboot, in my case, dark. In all other ways of quitting, the appearance becomes clear on reboot.
It shows up quite easily. Just activate the terminal in the launcher properties with notpadd, for example. If you leave the site by clicking on "disconnect", the terminal window closes. Otherwise it remains open and still active.
