### ISSUE TITLE
Firefox thinks I'm in another timezone!

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#350]
This is pretty cool and a side-effect of strict whitelisting that I never would have guessed. Normally, Firefox (and thus every website you visit) knows what the time is on your computer. However, when using a very strict profile (`private-etc`, `private-bin`, and `private-tmp`, among other things), it apparently doesn't know what my timezone is!

It doesn't really matter to me (in the sense that I'd rather that websites *not* know what my timezone is), but I'm curious what exactly is causing this.

Here's my profile:

````
# Blacklist/Whitelist

blacklist /usr/local/bin
blacklist /usr/local/sbin

whitelist ${HOME}/.mozilla
whitelist ${HOME}/Downloads/
whitelist ${HOME}/.pulse/
whitelist ${HOME}/.config/pulse/
whitelist ${HOME}/.config/gtk-3.0/
whitelist ${HOME}/.config/google-googletalkplugin/
whitelist ${HOME}/.gtkrc-2.0
whitelist ${HOME}/.gtkrc.mine
whitelist ${HOME}/.Xauthority
whitelist ${HOME}/PDF/

# Private directories

private-bin firefox.real,firefox,which,sh
private-etc hosts,passwd,mime.types,fonts/,mailcap,iceweasel/,xdg/,gtk-3.0/,resolv.conf,X11/,pulse/,adobe/,gcrypt/,alternatives/
private-tmp

# Miscellaneous options

shell none
seccomp
noroot
caps.drop all
protocol unix,inet,inet6
````

**Comment by temporaryaccount** [comment]
Most likely it's because you've forgot to copy /etc/localtime into your private /etc.

**Comment by chiraag-nataraj** [comment]
Ahhh...that would be it!
