### ISSUE TITLE
private-dev breaks global /dev/pts mountpoint

### ISSUE THREAD

**Issue by stiell** [netblue30/firejail#351]
When starting firejail with --private-dev option, the mount options for /dev/pts change globally:
```
~ $ mount | grep /dev/pts
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620)
~ $ firejail --noprofile --private-dev
Parent pid 1050, child pid 1051

Child process initialized
~]$ exit

parent is shutting down, bye...
~ $ mount | grep /dev/pts
devpts on /dev/pts type devpts (rw,relatime,mode=600)
```

This causes e.g. urxvt to fail to start, even if run outside any sandbox:
```
~ $ urxvt
urxvt: can't initialize pseudo-tty, aborting.
```

`strace urxvt` shows:
```
chown("/dev/pts/42", 1000, 5)           = -1 EPERM (Operation not permitted)
```

It needs /dev/pts to be mounted with the options gid=5,mode=620, which firejail for some reason has changed. `mount -o remount,mode=620,gid=5 /dev/pts` reverts the breakage.

This is with firejail 0.9.38 on Gentoo.

**Comment by netblue30** [comment]
Thanks for the bug, I'll put a fix in soon.

**Comment by netblue30** [comment]
I think I have a fix for it. I'll reopen the bug if necessary.
