### ISSUE TITLE
Need a little help regarding vmware profile

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#3514]
```
include vmware.local

include disable-common.inc
include disable-exec.inc
include disable-interpreters.inc
include disable-passwdmgr.inc
include disable-programs.inc
include disable-xdg.inc

whitelist ~/.vmware
whitelist ~/.cache/vmware

include whitelist-common.inc

caps.drop all
ipc-namespace
netfilter
nodbus
nogroups
notv
shell none


private-etc asound.conf,ca-certificates,dconf,fonts,group,gtk-2.0,gtk-3.0,hostname,hosts,ld.so.cache,localtime,machine-id,conf.d,pulse,resolv.conf,ssl,X11,vmware,vmware-installer,vmware-vix
```

It's my current vmware profile. what else should I add or omit to harden it? 

>specs- Manjaro (KDE), Kernel: 5.7.x, Firejail ver: 0.9.62

**Comment by glitsj16** [comment]
You can use our [profile template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template) and test all the additional options you don't have yet.

**Comment by rusty-snake** [comment]
@Neo00001 if you have followed the notes in the template and did some detailed testing, feel free to open a PR with it so we can review it and bring it upstream.
