### ISSUE TITLE
[Reminder] Add xdg-dbus-proxy as dependency on next release

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3515]
```
$ pacman -Q firejail
firejail-git 0.9.63.r6272.ce462b6b-1

$ seahorse-tool --import foo.asc
Warning: /usr/bin/xdg-dbus-proxy was not found, downgrading dbus-user policy to allow.
To enable DBus filtering, install the xdg-dbus-proxy program.
Ignoring "dbus-user.own org.gnome.seahorse.Application" and 1 other dbus-user filter rule.
```

The recently introduced D-Bus filtering options rely on `xdg-dbus-proxy` being installed. Although the warning is very clear when it isn't, we should inform/remind distro packagers of this and advise to add that package as a dependency.

UPDATE: I asked the maintainer of the AUR [firejail-git](https://aur.archlinux.org/packages/firejail-git/) package to act accordingly.

**Comment by reinerh** [comment]
Thanks for thinking about this!

I would hope that package maintainers are also reading the RELNOTES (where it's already mentioned). :grin:

**Comment by glitsj16** [comment]
> I would hope that package maintainers are also reading the RELNOTES (where it's already mentioned).

Heh, true. RELNOTES can become rather long to sift true though and we're all fallible. As the D-Bus filtering is an important change (adding a dependency with a fallback that allows access) I even considered doing something in Makefile to stop the build when xdg-dbus-proxy isn't found. But that might be overkill... Perhaps we can move the item on D-Bus sandboxing to the very top of the RELNOTES when the next release gets cut.

**Comment by reinerh** [comment]
I agree that a build-time check would be a bit overkill.
I think a hard dependency is a bit too much, so I intend to only add it as a Recommendation in the Debian package, as firejail is still usable without it, and users might prefer to keep it uninstalled

**Comment by glitsj16** [comment]
@reinerh As I'm running both Arch Linux and Debian/Ubuntu I did notice the differences qua packaging on these distros. Sounds very reasonable to add it as Recommends on Debian. I expect lots of reports on our issue-trackers once the D-Bus sandboxing gets out there. Nothing much we can do but 'wait and see' I guess.

**Comment by netblue30** [comment]
The check is at run-time - we print a warning if the xdg-dbus-proxy is not in /usr/bin. There were some small fixes here and there, and also a fix in firetools GUI, I think we are ready to go!

**Comment by rusty-snake** [comment]
@odubaj a few recommendations for the fedora package:

1. add `Requires: xdg-dbus-proxy` or `Recommends: xdg-dbus-proxy` (depending on exact packaging-guidelines)
2. add `--enable-selinux` to %configure (which needs `BuildRequires: libselinux-devel`)

As a reference, my build script: https://gist.github.com/rusty-snake/95e40fb9449b6b36c8371d77e7048683

**Comment by odubaj** [comment]
> @odubaj a few recommendations for the fedora package:
> 
>     1. add `Requires: xdg-dbus-proxy` or `Recommends: xdg-dbus-proxy` (depending on exact packaging-guidelines)
> 
>     2. add `--enable-selinux` to %configure (which needs `BuildRequires: libselinux-devel`)
> 
> 
> As a reference, my build script: https://gist.github.com/rusty-snake/95e40fb9449b6b36c8371d77e7048683

Added, thanks!
