### ISSUE TITLE
Firefox High Security Mode + Pipelight

### ISSUE THREAD

**Issue by Gerii** [netblue30/firejail#352]
Is it possible to stop NPAPI plugins from starting with Firefox? I currently have Pipelight installed to use Silverlight in my normal Firefox installation. However when I use the High Security Mode it always tries to install Silverlight in the new user account. The installation seems to fail, causing the Pipelight installation wizard to stay open. Thus I always have to close the firejail process to get rid of the window, which is kind of annoying.

On another note, the same happened by just calling firejail firefox before I added the following items to my whitelist.
`whitelist ~/.wine-pipelight
whitelist ~/.wine-pipelight64
whitelist ~/.config/pipelight-widevine
whitelist /etc/pipelight-widevine
whitelist ~/.config/pipelight-silverlight5.1
whitelist /etc/pipelight-silverlight5.1`

**Comment by netblue30** [comment]
I'll add the whitelists to firefox profile, thanks!

**Comment by netblue30** [comment]
Fixed!
