### ISSUE TITLE
No more way to specify custom configure options when building deb?

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#3523]
Building firejail from https://github.com/netblue30/firejail/commit/9ecd3cad544c8a8b64d2d8e4acc0cede60d6c284 is not possible with `fj-mkdeb.py` -
```
$ ./contrib/fj-mkdeb.py --enable-apparmor --disable-firetunnel
Error: Could not find the firejail source tree.  Exiting.
```

This is probably as of 87e7b313997b1d2be6553cfb22fef71b74c84ea6 , where `mkdeb.sh` is now dynamically generated.  But running the build commands directly still doesn't pick up all configure arguments:
```
$ ./configure --enable-apparmor --disable-firetunnel
$ make deb
```
That produces a deb with firetunnel support **enabled**:
```
$ firejail --version
firejail version 0.9.63

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

```

Could the dynamic generation of `mkdeb.sh` please take custom configure options into account?
Or is that still not possible, so `fj-mkdeb.py` needs to be updated?

**Comment by rusty-snake** [comment]
> Could the dynamic generation of mkdeb.sh please take custom configure options into account?

It does. The error says something else. It should work with.

```
$ ./configure
$ ./contrib/fj-mkdeb.py --enable-apparmor --disable-firetunnel
```

**Comment by laniakea64** [comment]
Unfortunately that still doesn't work -
```
$ firejail --version
firejail version 0.9.63

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

```

**Comment by rusty-snake** [comment]
But the error is gone? If not try to use `--fj-src` to workaround.

**Comment by laniakea64** [comment]
> But the error is gone?

Yes it built without error.  But as the output above shows, my configure options were still ignored.

Maybe it would help clarify the problem to link the longer back story? - https://github.com/netblue30/firejail/issues/772

I still don't know the reasoning behind https://github.com/netblue30/firejail/issues/772#issuecomment-249189442 .  Now that `mkdeb.sh` is dynamically generated, does that reasoning still apply?

**Comment by rusty-snake** [comment]
I can't test it, because I have no debian, but this generates a mkdeb.sh with `./configure --prefix=/usr --enable-apparmor --disable-firetunnel`:
`./configure && ./contrib/fj-mkdeb.py --only-fix-mkdeb --enable-apparmor --disable-firetunnel`

**Comment by Fred-Barclay** [comment]
> I can't test it, because I have no debian...

Tested and it works on my end:
```
$ firejail --version
firejail version 0.9.63

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is disabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled
```

**Comment by laniakea64** [comment]
> I can't test it, because I have no debian, but this generates a mkdeb.sh with `./configure --prefix=/usr --enable-apparmor --disable-firetunnel`:
> `./configure && ./contrib/fj-mkdeb.py --only-fix-mkdeb --enable-apparmor --disable-firetunnel`

Thanks @rusty-snake for the workaround, it works for me too:
```
./configure && ./contrib/fj-mkdeb.py --only-fix-mkdeb --enable-apparmor --disable-firetunnel && make deb
```

**Comment by laniakea64** [comment]
So will there be first-class availability of custom configure options for .deb build?  Or does `fj-mkdeb.py` need to be patched based on the workaround above?

**Comment by laniakea64** [comment]
> So will there be first-class availability of custom configure options for .deb build? Or does `fj-mkdeb.py` need to be patched based on the workaround above?

I ask because if there still cannot be first-class availability of custom configure options for .deb build, I am the original author of `fj-mkdeb.py` and would try to look into updating it.
