### ISSUE TITLE
discord profile does not work when user is using the fish shell

### ISSUE THREAD

**Issue by 4e554c4c** [netblue30/firejail#3528]
### Bug
When running discord with `firejail discord` the error `execvp: No such file or directory` is reported.
When running with `--debug`, it seems that immediately before firejail is running the syscall `execvp("/usr/bin/fish", ["/usr/bin/fish", "-c", "'discord'"])` which then fails.

### Expected behavior
Command line is run under an allowed shell such as `bash` or `$SHELL` is added to the allowlist.

## Solution
Runs fine with `env SHELL=bash firejail discord`

## Reproduction
1. Install fish
2. Run `env SHELL=fish firejail --debug discord`

## Log
```
seccomp filter configured
Mounting read-only /run/firejail/mnt/seccomp
Dropping all capabilities
noroot user namespace installed
Dropping all capabilities
NO_NEW_PRIVS set
Drop privileges: pid 1, uid 1000, gid 1000, nogroups 1
No supplementary groups
starting application
LD_PRELOAD=(null)
Running 'discord'  command through /usr/bin/fish
execvp argument 0: /usr/bin/fish
execvp argument 1: -c
execvp argument 2: 'discord' 
Child process initialized in 226.40 ms
Installing /run/firejail/mnt/seccomp/seccomp seccomp filter
Installing /run/firejail/mnt/seccomp/seccomp.32 seccomp filter
Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter
execvp: No such file or directory
monitoring pid 34

Sandbox monitor: waitpid 34 retval 34 status 256

Parent is shutting down, bye...
```

**Comment by rusty-snake** [comment]
Should be fixed, thanks for the report.
