### ISSUE TITLE
mathematica profile

### ISSUE THREAD

**Issue by fugata** [netblue30/firejail#3531]
System:  Raspberry Pi 4, 8gb
OS:  current version of Raspberry 32 bit OS, kernel: 5.4.51-v71+
firejail:  version 0.9.58.2  (installed from sudo apt install)

When I typed
   firejail mathematica
I got
----------------
eading profile /etc/firejail/mathematica.profile
Reading profile /etc/firejail/Mathematica.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 4592, child pid 4593
Child process initialized
/usr/bin/mathematica: 1: /usr/bin/mathematica: lsb_release: Permission denied
/usr/bin/mathematica: 81: [: =: unexpected operator

Parent is shutting down, bye...

[1]+  Done                    firejail mathematica
-------------------
I have no issue running firejail along with chromium and other programs.

I'd be happy to provide additional logs.  Please let me know.  THANKS!

**Comment by fisiognomico** [comment]
The version of Mathematica that you're running is the one which is provided freely by Raspbian right?
Because I've tried Mathematica 11.3 and it works perfectly fine under firejail.
I would rather recommend you to check the launching script.

**Comment by kortewegdevries** [comment]
Is Raspberry firejail stuck to 0.9.58.2? Consider updating it too 0.9.62 if possible. I don't have a copy of mathematica to test since I am stuck at home.

>  /usr/bin/mathematica: 1: /usr/bin/mathematica: lsb_release: Permission denied

Add `lsb_release,os_release` to `private-etc` if it is there in the profile or try using the profile from master (https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/Mathematica.profile (this is free of private-etc, so no need to add/modify)

**Comment by rusty-snake** [comment]
@fugata can you paste `/usr/bin/mathematica` here.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
