### ISSUE TITLE
Custom/local applications doesn't start

### ISSUE THREAD

**Issue by tjerry** [netblue30/firejail#3536]
I'm trying to start some custom applications, which are not installed in the system.
For instance, I'd like to start an app in /home/user/Apps.
But firejails exists with an error.

```
$ firejail --net=none --private=/var/tmp/home /home/user/Apps/pencil/pencil
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 23389, child pid 23390
Child process initialized in 34.87 ms
/bin/bash: /home/user/Apps/pencil/pencil: No such file or directory

Parent is shutting down, bye...
```

Does firejail work with custom/local applications, or do they have to be installed in the system?

**Comment by rusty-snake** [comment]
> Does firejail work with custom/local applications

Yes. 
1. The default.profile works not with every program.
2. You need to allow `ignore noexec ${HOME}` if disbale-exec.in is `include`d.
3. The binary must be inside a `private` $HOME if `private` is used.

The last point is important for you now.

**Comment by tjerry** [comment]
OK.
So I copied an app to a private $HOME and another error came up.
I haven't been able to find anything about that error.

```
$ firejail --net=none --private=/var/tmp/home /var/tmp/home/edraw/EdrawMax 
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 3305, child pid 3306
Error opening private directory: fs_home.c:262 fs_private_homedir: No such file or directory
Error: proc 3305 cannot sync with peer: unexpected EOF
Peer 3306 unexpectedly exited with status 1
```

**Comment by rusty-snake** [comment]
> I haven't been able to find anything about that error.

`No such file or directory`: Did you created /var/tmp/home?

**Comment by tjerry** [comment]
Yes.
The directory structure is /var/tmp/home/edraw, where edraw contains all the necessary files to run the app.

**Comment by smitsohu** [comment]
By default, the sandbox /var is mounted read-only and noexec. You may want to disable that with `--writable-var`

**Comment by tjerry** [comment]
No, it's not it.
For the sake of simplicity I'll start it from my home directory.
So:

```
$ firejai --net=none /home/user/apps/Typora/Typora
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 27884, child pid 27885
Child process initialized in 30.20 ms

Parent is shutting down, bye...
```

**Comment by rusty-snake** [comment]
works this?

**Comment by tjerry** [comment]
> works this?

```
$ firejai --net=none /home/user/apps/Typora/Typora
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 27884, child pid 27885
Child process initialized in 30.20 ms

Parent is shutting down, bye...
```
There is no error. But the Typora doesn't start. Firejail just quits.

However, the following works.
`$ firejail --noprofile --net=none /home/static/Data/Software/Linux/Typora/Typora`

**Comment by rusty-snake** [comment]
Then you need to write a profile for it (or request one in #1139).

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
