### ISSUE TITLE
Font styles unreadable in dark themes

### ISSUE THREAD

**Issue by Hyphae-2029** [netblue30/firejail#3541]
As someone with ASD and photophobia I use dark window themes. 

I cannot read the text in dialogs the styles and colours override my default settings.

![image](https://user-images.githubusercontent.com/38636808/88346867-c1471c80-cd8c-11ea-8747-b9e31f0e4caa.png)
![image](https://user-images.githubusercontent.com/38636808/88346903-d9b73700-cd8c-11ea-8fd5-9da272aeb5c9.png)

**Comment by rusty-snake** [comment]
That's a firetools issue. See also https://github.com/netblue30/firetools/issues/38.
