### ISSUE TITLE
Firetools dark theme

### ISSUE THREAD

**Issue by medmedin2014** [netblue30/firejail#3544]
Firetools can't be used with dark themes
```
Firejail: 0.9.62-1
Firetools:  0.9.62-1
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.9-1-MANJARO
OS Type: 64-bit
```

![Screenshot_20200724_115847](https://user-images.githubusercontent.com/7027319/88384893-2e66ac00-cda5-11ea-9448-e72c60c8b2ee.png)

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/issues/3541#issuecomment-663377438
