### ISSUE TITLE
Help sealing VSCode spying

### ISSUE THREAD

**Issue by medmedin2014** [netblue30/firejail#3545]
I'm new to firejail, can anyone please help me find a strict profile that can stop VScode (with C# extension installed and using dotnet core) from connecting to internet and sent collected data, because even if I disable all telemetry/upgrade options and disabled extensions upgrades I still see established connections from the editor to the outside.
I know this is not a bug but I couldn't find any clear/reliable procedure to do it.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions#how-do-i-run-vlc-in-a-sandbox-without-network-access

So just add `net none` to code.local (not sure if code or vscodium or code-oss is used by you, but code.local should cover all)
```
mkdir -p ~/.config/firejail
echo "net none" >> ~/.config/firejail/code.local
```
```

**Comment by medmedin2014** [comment]
@rusty-snake Thanks for your kind and useful reply, I applied the modification and now I'm monitoring the editor. I really don't like the obsession of Microsoft to implement spying tools in every software they create. Thankfully we have a great tools like Firejail and Linux to avoid them from logging our privacy on internet.

**Comment by rusty-snake** [comment]
Established connections must not be spying, the can also be update.

**Comment by kortewegdevries** [comment]
@med ... Take a look at issue 54354 on their repo and the linked issues therein.

**Comment by SkewedZeppelin** [comment]
You can always use another editor/IDE :)

**Comment by medmedin2014** [comment]
@SkewedZeppelin The problem for us who want to debug C# code running on dotnet core on Linux, there is no solid/better alternative other than VSCode.

**Comment by medmedin2014** [comment]
@kortewegdevries Already done, but there is other parts not known (or cannot be controlled) that leak and sent data to M$, I suspect the C# extension created by M$ and which provide their property debugger for C# language. And there are also their dotnet core runtime which requires setting DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 to disable the telemetry, which I suspect if it's completely disabled.

**Comment by Fred-Barclay** [comment]
Side note: I personally don't mind a little bit of telemetry going back to MS because I believe VS Code keeps improving because of it... but definitely I'd recommend you look at vscodium/code-oss! I believe you can easily turn off all potential monitoring with these...
