### ISSUE TITLE
Error mounting appimage: No such device

### ISSUE THREAD

**Issue by tjerry** [netblue30/firejail#3546]
We use ClickUp at work. They have a desktop client. But I'd like to cut it's access to my home directory.

```
$ firejail --appimage --private=/home/user/Temp/private_home/clickup ~/Temp/private_home/clickup/clickup-desktop-2.0.13-x86_64.AppImage
Mounting appimage type 2
Error mounting appimage: appimage.c:122 appimage_set: No such device
```
```
$ firejail --private=/home/user/Temp/private_home/clickup ~/Temp/private_home/clickup/clickup-desktop-2.0.13-x86_64.AppImage
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 28648, child pid 28649
Child process initialized in 14.28 ms
/bin/bash: /home/user/Temp/private_home/clickup/clickup-desktop-2.0.13-x86_64.AppImage: No such file or directory

Parent is shutting down, bye...
```

This one is interesting. First time it started. Subsequent runs end up with the following error.
```
$ firejail --noprofile --private=/home/user/Temp/private_home/clickup ./clickup-desktop-2.0.13-x86_64.AppImage
Parent pid 28677, child pid 28678
Child process initialized in 1.92 ms
/bin/bash: /home/user/Temp/private_home/clickup/clickup-desktop-2.0.13-x86_64.AppImage: No such file or directory

Parent is shutting down, bye...
```

I'm new to firejail, but so far I have been able to run only spotify, which is installed in the system.
All other local apps failed to start - AppImage or simple binaries.
Could someone help me debug this?

**Comment by rusty-snake** [comment]
`--appimage` has to be the last firejail argument.

**Comment by rusty-snake** [comment]
> firejail --noprofile --private=/home/user/Temp/private_home/clickup ./clickup-desktop-2.0.13-x86_64.AppImage

Does it work w/o `--private`? (You need to use `private-cwd`)

**Comment by tjerry** [comment]
> `--appimage` has to be the last firejail argument.

```
$ cd ~/Temp/private_home/clickup
$ firejail --private=/home/static/Temp/private_home/clickup --appimage clickup-desktop-2.0.13-x86_64.AppImage
Error: cannot access AppImage file
```
```
$ firejail --private=/home/static/Temp/private_home/clickup --appimage ~/Temp/private_home/clickup/clickup-desktop-2.0.14-x86_64.AppImage
Mounting appimage type 2
Error mounting appimage: appimage.c:122 appimage_set: No such device
```


> > firejail --noprofile --private=/home/user/Temp/private_home/clickup ./clickup-desktop-2.0.13-x86_64.AppImage
> 
> Does it work w/o `--private`? (You need to use `private-cwd`)


This one works.
```
$ firejail --noprofile ~/Temp/private_home/clickup/clickup-desktop-2.0.14-x86_64.AppImage
```
```

$ firejail --private=/home/static/Temp/private_home/clickup --private-cwd --appimage ~/Temp/private_home/clickup/clickup-desktop-2.0.14-x86_64.AppImage
Mounting appimage type 2
Error mounting appimage: appimage.c:122 appimage_set: No such device
```

```
$ firejail --noprofile --private=/home/static/Temp/private_home/clickup --private-cwd --appimage ~/Temp/private_home/clickup/clickup-desktop-2.0.14-x86_64.AppImage
Mounting appimage type 2
Error mounting appimage: appimage.c:122 appimage_set: No such device
```

```
$ firejail --noprofile --private=/home/static/Temp/private_home/clickup --private-cwd ~/Temp/private_home/clickup/clickup-desktop-2.0.14-x86_64.AppImage
Parent pid 7730, child pid 7731
Child process initialized in 1.86 ms
/bin/bash: /home/static/Temp/private_home/clickup/clickup-desktop-2.0.14-x86_64.AppImage: No such file or directory

Parent is shutting down, bye...
```

**Comment by rusty-snake** [comment]
> firejail --noprofile --private=/home/user/Temp/private_home/clickup ./clickup-desktop-2.0.13-x86_64.AppImage

In which dir is the AI?

**Comment by tjerry** [comment]
> > firejail --noprofile --private=/home/user/Temp/private_home/clickup ./clickup-desktop-2.0.13-x86_64.AppImage
> 
> In which dir is the AI?

The AI is in the private dir, which is ~/Temp/private_home/clickup.

If I run it like this, it works.
`$ cd ~/Temp/private_home/clickup`
`$ firejail --noprofile --private=~/Temp/private_home/clickup ./clickup-desktop-2.0.14-x86_64.AppImage`

Without `--noprofile`, there is an error.
```
$ firejail --private=~/Temp/private_home/clickup ./clickup-desktop-2.0.14-x86_64.AppImage
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 14585, child pid 14586
Child process initialized in 13.52 ms
execv error: No such file or directory

Parent is shutting down, bye...
```

**Comment by rusty-snake** [comment]
Then you must write a profile for it or request one in #1139.

**Comment by tjerry** [comment]
OK, I think I've got it now.
The app didn't start, because the default profile was too restrictive.

I've created a simple profile in `~/.config/firejail/clickup.profile`.

```
#include disable-common.inc
#include disable-devel.inc
#include disable-exec.inc
include disable-interpreters.inc
include disable-passwdmgr.inc
include disable-programs.inc

disable-mnt
private ~/[my private dir]
#private-cwd

#seccomp
#nonewprivs
```
The appimage file has to be inside private directory.
And I run it like this:
`$ firejail --profile=clickup ./clickup.AppImage`

I would mark this thread as solved, however:
1) I'm wandering why the `--appimage` switch doesn't work?

The following two commands end in an error.
`$ firejail --profile=clickup --appimage ./clickup.AppImage`
or
`$ firejail --profile=clickup --appimage clickup.AppImage`

```
Reading profile /home/static/.config/firejail/clickup.profile
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Error: cannot access AppImage file
```

2) And what difference does the `--appimage` switch make.? Except for what is mentioned in the man page - "_If the sandbox is started as a regular user, nonewprivs and a default capabilities filter are enabled_".

**Comment by rusty-snake** [comment]
1. Because clickup.AppImage is not in `.`, you need to give it the full path.

**Comment by tjerry** [comment]
>     1. Because clickup.AppImage is not in `.`, you need to give it the full path.

Full private path:
```
$ firejail --profile=clickup --appimage /home/static/clickup.AppImage
Reading profile /home/static/.config/firejail/clickup.profile
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Error: cannot access AppImage file
```

Full real path:
```
$ firejail --profile=clickup --appimage /home/static/Temp/private_home/clickup/clickup.AppIage
Reading profile /home/static/.config/firejail/clickup.profile
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Mounting appimage type 2
Error mounting appimage: appimage.c:122 appimage_set: No such device
```

**Comment by rusty-snake** [comment]
> Full real path:
> Error mounting appimage: appimage.c:122 appimage_set: No such device

Can you try an other AI. If this happens with the other AI too, it is something with your systemconfig (modprobe blacklist?).

**Comment by tjerry** [comment]
> > Full real path:
> > Error mounting appimage: appimage.c:122 appimage_set: No such device
> 
> Can you try an other AI. If this happens with the other AI too, it is something with your systemconfig (modprobe blacklist?).

I had no squashfs compiled into the kernel and firejail was unable to mount the images.
Problem solved.
Thank you.
