### ISSUE TITLE
pavucontrol broken unless I run it within firejail

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#355]
This isn't really a big problem, since I just run pavucontrol with firejail. However, I thought I'd document it here since other people may be running into the same issue.

If I launch firefox and play a youtube video, for example, something very interesting happens. If I just launch `pavucontrol` (the mixer program to control pulseaudio), it fails. If I instead launch it as `firejail pavucontrol`, it works fine.

From what I can tell, there's some funny SHM business going on with pulseaudio. And yes, it's distinct from the older bug with pulseaudio just not working. I have pulseaudio version 8.0. Regardless, it seems that at least a workaround exists at present.

**Comment by netblue30** [comment]
PulseAudio is broken, it doesn't play nice with programs running in different PID namespaces. There is a workaround here:

https://firejail.wordpress.com/support/known-problems/

**Comment by chiraag-nataraj** [comment]
Ah okay, so it *is* the same old bug :P Oh well...as I mentioned, another workaround is just to launch everything that needs sound using firejail ;)
