### ISSUE TITLE
private-tmp in meld breaks diff view

### ISSUE THREAD

**Issue by kortewegdevries** [netblue30/firejail#3551]
`Firejail 0.9.62,0.9.63`
`Meld 3.20.2`
```
System:Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.14.2 
Distro: Ubuntu 20.04.1 LTS  
```
Seems like files are sourced from `/tmp` and `private-tmp` is creating problems in the diff view: https://imgur.com/SlIahe8. Not sure if this has something to with CLI/frontends using git. Other diff viewers seem to work.The repo is cloned in `/home/git/GitHub/`.
Maybe a comment should be written above it.

**Comment by rusty-snake** [comment]
With diffview you mean what? Which command or menu?

**Comment by kortewegdevries** [comment]
> With diffview you mean what? Which command or menu?

The comparison view you get when you change a file.

**Comment by rusty-snake** [comment]
For me it works, can you give more detailed steps.

**Comment by kortewegdevries** [comment]
It works in CLI I think,I checked but not in a frontend like git-cola. Set meld as diff tool in it, open a file in text editor through cola, change something, right click on unstaged chages, view using diff tool. 
 
Commenting `private-tmp` solves the issue.

**Comment by rusty-snake** [comment]
`git difftool file_with_changes`

**Comment by kortewegdevries** [comment]
Doesn't work without that patch, I had it commented already in another terminal when I said "CLI" works. Thanks,
