### ISSUE TITLE
firefox dbus restriction (not a bug but a question)

### ISSUE THREAD

**Issue by DyslexicAtheist** [netblue30/firejail#3557]
Hi,

I'm running version 0.9.62 which ships with Debian sid and have seen that the only way for me to allow Firefox access to dbus would be with `ignore nodebus` in Firefox local. Is there a way that I can have better control over what the application can access via dbus. I'm not so happy with granting it full access.

thanks,
~da

**Comment by rusty-snake** [comment]
Beginner: No (except `blacklist /run/dbus` for the system-bus socket). Wait for 0.9.64 or use flatpak.
Expert: Use compile firejail from git-master (https://github.com/netblue30/firejail/wiki/Using-firejail-from-git)

**Comment by DyslexicAtheist** [comment]
excellent thank you
