### ISSUE TITLE
Firejail cannot launch if ~/.asoundrc is a symlink

### ISSUE THREAD

**Issue by boltronics** [netblue30/firejail#356]
I use GNU Stow to have many of the configuration dotfiles in my home directory basically managed via symlinks, which point to another location (also under my home directory). This makes version control simple and allows me to load different configuration files on a per-machine basis. One of those managed files is ~/.asoundrc.

I see /etc/firejail/whitelist-common.inc has ```whitelist ~/.asoundrc```, but even with that line commented, the problem persists. I also tried adding ```ignore whitelist ~/.asoundrc``` without success. Lastly, I tried adding ```whitelist ~/.dotfiles/alsa/.asoundrc``` (which is where ~/.asoundrc is a symlink to), and that still didn't work.

Browsing through the source, it appears there are references to the file location hard-coded, so I'm assuming this is a bug in firejail and not my configuration. There could well be the same problem for some of the other locations that are hard-coded as well.

**Comment by netblue30** [comment]
BUG! Will fix soon!

**Comment by netblue30** [comment]
Fixed!
