### ISSUE TITLE
Allow gajim to access GPG keys

### ISSUE THREAD

**Issue by kortewegdevries** [netblue30/firejail#3562]
Current master for Gajim https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/gajim.profile doesn't allow to use GPG keys. And `gajim-pgp` is now installed alongside with `gajim` on Ubuntu. Add corresponding `noblacklist/whitelist, read-only .gnugpg`; `private-bin` needs to be commented to use GPG, because I can't figure out what it needs access to and throws this error with it: 

```
gajim.c.gnupg potential problem: FAILURE: sign <key>
gajim.c.gnupg gpg returned a non-zero error code: 2
```
Tried adding `gpg-agent,which` doesn't work. Using `firejail --build` doesn't show output on terminal,tried with `strace`, I can't find it. Looking at the raw output of `--build` from `/tmp` it is accessing `/usr/bin/gpg` and a bunch of files under `~/.gnugpg`,`/etc/gcrypt`.

Gajim 1.1.3.

Also like Gajim consider `whitelist ${DOWNLOADS}` in pidgin, account wide buddy icons are blocked.

**Comment by rusty-snake** [comment]
Open a PR :upside_down_face: :nerd_face: . The question is whether we want to make it opt-in, since PGP is not the easiest / common way to encrypt XMPP.

**Comment by kortewegdevries** [comment]
> Open a PR :upside_down_face: :nerd_face:.

Wanted opinions since idk of it's a hard dependancy on other distros.

**Comment by Fred-Barclay** [comment]
> The question is whether we want to make it opt-in, since PGP is not the easiest / common way to encrypt XMPP.

Let's do opt-in; someone who is using GPG is probably technically skilled enough that enabling it wouldn't be a big deal, and otherwise we don't expose any sensitive info unnecessarily.

**Comment by SkewedZeppelin** [comment]
> Let's do opt-in;

Yes, especially because OMEMO > PGP for XMPP

**Comment by kortewegdevries** [comment]
OMEMO > PGP

OMEMO is based on device trust,different than PGP. I don't need the extra features it gives. I'll add in a PR later once I test some other plug-ins like Latex.
