### ISSUE TITLE
/bin/bash: ./Telegram/Telegram: Permission denied

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3565]
Ive downloaded and tried the binary file for Telegram here: https://github.com/telegramdesktop/tdesktop/releases/download/v2.2.0/tsetup.2.2.0.tar.xz
The binary file is already executable.
It works with --no-profile

Im not sure why i get Permission denied. Is there something obvious im missing here?

firejail version 0.9.62

**Comment by kortewegdevries** [comment]
`ignore noexec ${HOME}` if you keep it there.
