### ISSUE TITLE
New release on Monday (Aug 10): CVE fixes

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#3575]
Details here: https://www.debian.org/security/2020/dsa-4742, thanks @reinerh 

The release is on branch relase-0.9.62 ($ git clone -b release-0.9.62 https://github.com/netblue30/firejail)

I included most of the patches from Debian (firejail 0.9.64-4 in Debian sid):  profile-fixes.patch, apparmor-include.patch, element-profile.patch,  usrsharedoc.patch, pathnames.patch, usr-share-firefox.patch. I'll check they are already in on mainline.

If you want to put other fixes in go right ahead, we can delay the release 2 or 3 days. Profile fixes, new app profiles, security hardening, etc. - no big features please!

Also LTS release next week (ping @startx2017)

CVE fixes already on mainline: https://github.com/netblue30/firejail/commit/34193604fed04cad2b7b6b0f1a3a0428afd9ed5b, https://github.com/netblue30/firejail/commit/2c734d6350ad321fccbefc5ef0382199ac331b37

**Comment by rusty-snake** [comment]
Until #3530 is fixed, we should not add `disable-shell.inc` to a profile since it breaks AppImages. We can (and maybe should) include the file itself in a release.

**Comment by netblue30** [comment]
Go for it, but make sure when you test you are on that branch, not on main.

**Comment by netblue30** [comment]
0.9.62.2 is up and running!

@rusty-snake:I think you are the Fedora guy here, can you build a Fedora packages? I'll loaded on sourceforge and here in the release section. Thanks!

LTS coming up in the next few days.

**Comment by FOSSONLY** [comment]
@netblue30 

0.9.62.2? Not 0.9.64? I'm confused.

**Comment by reinerh** [comment]
It's a small bugfix update on top of .62.
.64 will be the next release based on current master branch.

**Comment by startx2017** [comment]
We don't have output.c in LTS. No new release!

**Comment by rusty-snake** [comment]
Once  #3530 is fixed, we should release a 0.9.64 soon IMO. 0.9.62 is from December 2019, now we have August 2020. That is a long time, especially for profiles.


@netblue30 I tried with `./configure && make rpms` but it failed. I then build on using mock with  this [firejail.spec](https://github.com/netblue30/firejail/files/5064318/firejail.spec.txt): [firejail-0.9.62.2-1.fc32.x86_64.rpm](https://github.com/netblue30/firejail/files/5064306/firejail-0.9.62.2-1.fc32.x86_64.rpm.txt). It definitely do not work on OpenSUSE Leap. IDK if this is helpful. However I have unfortunately no time in the next week to do more on this.

**Comment by netblue30** [comment]
Thanks, it is good enough, I'll loaded on the sites. And yes, will go for a full release as you suggested.

**Comment by netblue30** [comment]
New release (0.9.62.4) at the end of the week, apparmor broken: https://github.com/netblue30/firejail/issues/3585

**Comment by netblue30** [comment]
All set, 0.9.62.4 is out.
