### ISSUE TITLE
Error: no suitable /path/JDownloader2 executable found

### ISSUE THREAD

**Issue by ihasaquesion** [netblue30/firejail#3578]
When I run `firejail --profile=~/.config/firejail/JDownloader.profile /path/JDownloader2/JDownloader2` I get this error:

```
Error: no suitable /path/JDownloader2/JDownloader2 executable found
```

The JDownloader.profile didn't work so for testing I copied its contents into ~/.config/firejail/JDownloader.profile and also added:

```
noblacklist /path/JDownloader2
whitelist /path/JDownloader2
```

(to the other noblacklist and whitelist in the profile.)

It only worked somewhere else when I ran `firejail --profile=~/.config/firejail/JDownloader.profile bash` from within /path/JDownloader2/JDownloader2 and then ran `./JDownloader2` as well as with the default.profile. I also tried it with the [latest JDownloader.profile](https://github.com/netblue30/firejail/blob/018d75775eab4a0f045949a9d069c57686ca2686/etc/profile-a-l/JDownloader.profile).

* How to get it running properly with the JDownloader profile?
* Isn't the JDownloader.profile incomplete or broken?

**Environment**
 firejail version 0.9.62

**Comment by ihasaquesion** [comment]
Solution was `firejail --profile=~/.config/firejail/JDownloader.profile bash /path/JDownloader2/JDownloader2`

Could this be deleted?

**Comment by rusty-snake** [comment]
> Could this be deleted?

No, GitHub does not support to delete issue.

> firejail --profile=~/.config/firejail/JDownloader.profile bash /path/JDownloader2/JDownloader2

If it need a shell, can you try `firejail "--ignore=shell none" --profile=JDownloader /path/JDownloader2/JDownloader2`.

**Comment by ihasaquesion** [comment]
> If it need a shell, can you try `firejail "--ignore=shell none" --profile=JDownloader /path/JDownloader2/JDownloader2`.

I get:
`/bin/bash: /path/JDownloader2/JDownloader2: no permissions`
