### ISSUE TITLE
Firejail discards exit code

### ISSUE THREAD

**Issue by ligthyear** [netblue30/firejail#358]
Hello,

we are using firejail to securely [run a compiler and linter](http://clippy.bashy.io/docs/clippy.html#section-4) in the [clippy-service](http://clippy.bashy.io/). First off, I wanted to thank you for this great project and the work you've put in it. It works great for us and allowed us to quickly setup a sandbox to allow third-party access without security risks. Thank you very much!

---

Coming to our specific problem: firejail currently **swallows the exit-code of the program it runs internally**. [As this gives us an indication whether the compiler exited successfully](https://github.com/ligthyear/clippy-service/issues/22) or whether there was a problem, this is a big problem for us.

I've identified that it would only require to keep the variable from the waitpid (instead of NULL) and forward that on process exit, but [that is currently not done](https://github.com/netblue30/firejail/blob/fca9d8e346cc4525159b9b2257387bf679a218a5/src/firejail/main.c#L1774-L1795). Would you accept a Pull-Request implementing this behavior? And/or do you want this new behavior be hidden behind a command-line option (like `--preserve-exit-code`)? I could prepare a PR about that but first wanted to make sure you'd want this, or maybe you had other good reasons to discard the exit code...

Highly appreciate you looking at this and all the work you've put in this already.
Thanks for your time!

**Comment by netblue30** [comment]
Sure, if you send a patch I'll merge it, thanks!

**Comment by zedniss** [comment]
I really need this feature. When will it be included in a stable release?

**Comment by netblue30** [comment]
It is already in the master branch, a testing release will follow shortly.
