### ISSUE TITLE
Blacklisting /media/ except for one folder

### ISSUE THREAD

**Issue by ihasaquesion** [netblue30/firejail#3581]
When I use a profile that has `noblacklist /media/directory/path` followed by a later `blacklist /media/` I keep getting blacklist violations in the syslog: `syscall opendir, path /media`. These errors only appear when I include  `blacklist /media/`.

How to blacklist all /media/ except for one directory?

And it also doesn't work when whitelisting the directory (next to the other whitelistings in the profile).

firejail version 0.9.62

**Comment by smitsohu** [comment]
It is easy, just do `--noblacklist=/media/dir --blacklist=/media/*`

**Comment by ihasaquesion** [comment]
Doesn't work.
I'd like to use a profile, not command-line parameters. The profile is:
```
...
noblacklist /media/veracrypt1/dir
...
blacklist /media/*
...
```

**Comment by smitsohu** [comment]
Ok, then it is
```
noblacklist /media/veracrypt
blacklist /media/*
noblacklist /media/veracrypt/dir
blacklist /media/veracrypt/*
```

Or just whitelist `/media/veracrypt/dir`. 

If the latter does not work, please post the output of `firejail --debug-whitelists --whitelist=/media/veracrypt/dir`. Redact the name of the directory if you like.

**Comment by ihasaquesion** [comment]
Thanks, whitelisting beneath the profile's blacklistings worked. Previously it didn't - probably because I kept the blacklistings.

**Comment by ihasaquesion** [comment]
It worked for one profile but not the other. I also put whitelist to the bottom of the profile before caps.drop all. I tried removing the noblacklist for the same directory. It's the profile for #3579

**Comment by smitsohu** [comment]
Is there a `disable-mnt` line in that other profile?

**Comment by ihasaquesion** [comment]
No, it's mostly the default JDownloader profile. I added `include chromium.profile`.

**Comment by rusty-snake** [comment]
> No, it's mostly the default JDownloader profile. I added include chromium.profile.

… which `include`s chromium-common.profile which sets `disable-mnt` :roll_eyes: .

**Comment by ihasaquesion** [comment]
I suspected this line to be the culprit. How to enable-mnt without having to modify this profile?

**Comment by rusty-snake** [comment]
Add `ignore disable-mnt` before you `include chromium.profile`.

**Comment by ihasaquesion** [comment]
Thank you!!
