### ISSUE TITLE
Disable the access to /run/firejail/mnt/devlog

### ISSUE THREAD

**Issue by sfc-gh-jdu** [netblue30/firejail#3584]
Hello, can we add an option to disable the access to syslog, i.e., /run/firejail/mnt/devlog? It seems now the firejail creates a mount (dev/log) agains devlog. 

(in src/firejail/fs_dev.c)
```
        // create DEVLOG_FILE
	int have_devlog = 0;
	struct stat s;
	if (stat("/dev/log", &s) == 0) {
		have_devlog = 1;
		FILE *fp = fopen(RUN_DEVLOG_FILE, "w");
		if (!fp)
			have_devlog = 0;
		else {
			fprintf(fp, "\n");
			fclose(fp);
			if (mount("/dev/log", RUN_DEVLOG_FILE, NULL, MS_BIND|MS_REC, NULL) < 0)
				errExit("mounting /dev/log");
		}
	}
```

Thanks!

**Comment by rusty-snake** [comment]
What about `blacklist /dev/log`?

**Comment by smitsohu** [comment]
Let's blacklist it always.

**Comment by smitsohu** [comment]
> Let's blacklist it always.

I meant the temporary location /run/firejail/mnt/devlog that was indicated in the issue title.

If you don't need /dev/log, you can just blacklist it as usual, as @rusty-snake said.
