### ISSUE TITLE
Discord wont open when executed outside the pkg manager one

### ISSUE THREAD

**Issue by YShow** [netblue30/firejail#3589]
**Bug and expected behavior**
- Describe the bug: open discord from a custom folder says archive or directory doesn't exist
- What did you expect to happen? Discord opening normally 

**No profile or disabling firejail**
- What changed calling `firejail --noprofile PROGRAM` in a shell?
Program executed fine

- What changed calling the program *by path*=without firejail (check `whereis PROGRAM`, `firejail --list`, `stat $programpath`)?
Program executed fine

**Reproduce**
1. Run in bash `firejail /home/name/DiscordFolder`
1.1  Run in bash `firejail --ignore=quiet --noblacklist=/home/yasser/opt/Discord /home/yasser/opt/Discord/Discord`

2. See error `Archive or directory not found`

**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`)
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20200810

 - Firejail version (output of `firejail --version`)
firejail version 0.9.62

**Additional context**
Since every discord update makes it impossible to use the older version and my distribution doesnt update right away i decided to use the tar.gz provided by discord but i can execute it with firejail anymore

**Checklist**
 - [X ] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [ X] The upstream profile exists (`find / -name 'firejail' 2>/dev/null`/`fd firejail` to locate profiles ie in `/usr/local/etc/firejail/PROGRAM.profile`)
 - [X ] Programs needed for interaction are listed.
 - [ X] Error was checked in search engine and on issue list without success.

<details><summary> debug output </summary>

[output.txt](https://github.com/netblue30/firejail/files/5078252/output.txt)

</details>

**Comment by kortewegdevries** [comment]
I have a different error but `whitelist ${HOME}/opt` and `firejail --ignore=quiet --noblacklist=/home/korte/opt/Discord /home/korte/opt/Discord/Discord` runs...

**Comment by kortewegdevries** [comment]
> i decided to use the tar.gz provided by discord but i can execute it with firejail anymore

I have a different error but `whitelist ${HOME}/opt` in your profile and `firejail --ignore=quiet /home/korte/opt/Discord/Discord` runs... or move the `opt` in home to Downloads...

**Comment by YShow** [comment]
> > i decided to use the tar.gz provided by discord but i can execute it with firejail anymore
> 
> I have a different error but `whitelist ${HOME}/opt` in your profile and `firejail --ignore=quiet /home/korte/opt/Discord/Discord` runs... or move the `opt` in home to Downloads...

Thank you, i tried with the flag '--whitelist' and now it opens normal, but shouldn't the noblacklist and whitelist basically do the same thing?

**Comment by kortewegdevries** [comment]
> but shouldn't the noblacklist and whitelist basically do the same thing?

No they are different, you can take a look at `man firejail-profile` to know how. You don't need to do a noblacklist since there is no blacklist `${HOME}/opt`.

**Comment by YShow** [comment]
> > but shouldn't the noblacklist and whitelist basically do the same thing?
> 
> No they are different, you can take a look at `man firejail-profile` to know how. You don't need to do a noblacklist since there is no blacklist "`${HOME}/opt`."

Thank you, ill take a look, im closing this issue since its working now
