### ISSUE TITLE
Firefox loses Firejail protection without notice when new session begins

### ISSUE THREAD

**Issue by RonCam** [netblue30/firejail#359]
System info: Linux Mint Rosa/17.3 / KDE
I recently thought to double-check to make sure Firefox was protected in the sandbox - opened Firejail Tools (the only way I know to verify this) - and saw the list was _empty_ - so Firefox had been running unprotected, and I didn't realize it.

Problem: Firejail was initially started along with Firefox by using one of the modified 'shortcuts', but then, when the computer was was shut down, and later restarted with _Session Management_ set to 'Restore' -- the software from the prior session was restarted, returning the system to the same state as as it was, when the computer was last turned off.  

That is, it returned to the same state with the exception of Firefox, which was now running 'outside' of the sandbox.    

Is there any way to set the operating system to automatically trigger Firejail to begin running, with Firefox 'inside' it, when the system is powered-up, causing the previous session to be restored?  

I generally keep the Session Restore feature active, for the convenience of just pushing the 'Power On' button and then knowing when I return to the computer I'll be seeing the Desktop just as I left it, the day before.  

If it can be avoided, I'd rather not lose this feature for the browser.  Any ideas?

**Comment by chiraag-nataraj** [comment]
Hmmm...depends on how exactly KDE is storing the session data. If, as I think, it stores links to the desktop files to invoke on login, you can modify the .desktop files in /usr/share/applications/ to launch firefox with firejail.

**Comment by RonCam** [comment]
That's a good idea.  
If you're not running KDE, it gives three choices for the type of Session Restoration:
1. Restore previous session
2. Restore manually saved session 
3. Start with an empty session

I opened the _applications_ directory in a text editor, went down to the first location where I saw the executable, in a section called **[Desktop Action NewWindow]**.  Then, editing that line, we now have this (showing both old, and new):
```
# Exec=firefox -new-window
Exec=firejail firefox -new-window
```
I'll begin using this, and see if firefox's behavior following Session Restoration has improved.  Any other ideas?

**Comment by chiraag-nataraj** [comment]
Let's see if that works. If it doesn't, I'll need more information about exactly where option 1) gets its data from (ostensibly from something in ~/.config/?).

**Comment by RonCam** [comment]
Unfortunately, Firefox still opens outside of the sandbox.

Let me look where you suggested and then will report on whether or not I can see a likely subdirectory or file.

**Comment by RonCam** [comment]
Hold the press: I just found line #147:
`program15=firefox`
I wonder if that's a static entry?
Unless you see anything else, let me try that during the day, tomorrow, when I'll be able to resume working on this problem.  
 :smiley: Many thanks for the progress so far, and please review what's been done and let me know if you discover going in a different direction might be more productive.

**Comment by chiraag-nataraj** [comment]
Hmmm...it seems when KDE saves its session, it doesn't realize the command was `firejail firefox` and not just `firefox`. Since the file is being automatically created, I'll have to think about how exactly you'd rectify this...

**Comment by RonCam** [comment]
Hold the press: I just found line #147:
`program15=firefox`
I wonder if that's a static entry?
Unless you see anything else, let me try that during the day, tomorrow, when I'll be able to resume working on this problem.  
 :smiley: Many thanks for the progress so far, and please review what's been done and let me know if you discover going in a different direction might be more productive.

**Comment by netblue30** [comment]
You can also make a symbolic link (ln -s) to /usr/bin/firejail under the name of the program you want to run, and put the link in /usr/local/bin):
`````
$ sudo ln -s /usr/bin/firejail /usr/local/bin/firefox
`````
This works in most of cases. It will trick the system to launch a jailed firefox instead of the regular firefox.

**Comment by RonCam** [comment]
> @netblue30 wrote:
> You can also make a symbolic link ...

This sounds interesting.  
Question: would this also make it unnecessary to individually and manually modify any and all other links on the system, pointing to _Firefox_?  This refers to links that may be on the Desktop, in the Application Launcher, etc., etc.

**Comment by chiraag-nataraj** [comment]
@netblue30 is right. Since these entries are automatically being created at logoff, the best bet is to modify what "firefox" refers to. The easiest way to do that is to create a symbolic link as suggested.

If it were linking to .desktop files, the matter would be completely different.

@netblue30, do you know why exactly it's not picking up on the command as `firejail firefox` instead of `firefox`? Or is it recording *both* and thus not properly launching the sandbox?

**Comment by netblue30** [comment]
I can see in my case (LXDE) the symbolic link fixes the places that use desktop files to launch the executable, for example in LXDE menu. However, the file manager is still broken, I assume it goes directly to /usr/bin/firefox.

**Comment by RonCam** [comment]
Just to make sure I'm understanding this discussion correctly -- is this summary correct?
By using a symbolic link, _.desktop_ files will now run a sandboxed copy of Firefox -- from anywhere on the system, as well as from the Start Menu/Application Launcher (KDE terminology).  Likewise, Session Restore will create a sandboxed copy of Firefox, whenever the system restarts.

The only time Firefox will start unsandboxed would be if one clicks directly on the executable in /usr/bin/firefox.   :satisfied: I can live with that, very easily.  That's not the usual way of starting a browser, anyway.  

@chiraag-nataraj: Is this all working, without 'glitches', on your VM?  If yes, then may I suggest this be documented as the default method for starting sandboxed programs?  Once set up, it seems unlikely for the user to have  :worried: moments, as I did when I suddenly realized Firefox had 'gotten out' of the box.

**Comment by chiraag-nataraj** [comment]
@RonCam: I'm not quite sure because KDE refuses to play well with my VM :stuck_out_tongue_closed_eyes:

**Comment by RonCam** [comment]
@chiraag-nataraj: Not to worry, I'll go ahead tomorrow, as _netblue30_ recommends, and observe Firejail's behavior, especially checking how it continues to protect Firefox during logoffs, shut-downs and restarts.

When you depend on something to protect the system, it's nice to have reassurance it's always there -- and it hasn't disappeared without notice, due to some unexpected 'glitch'.  With _Sandboxie_ I would always look for the yellow highlight (its color was configurable) framing the sandboxed window, and then I would know nothing had gone awry.

**Comment by RonCam** [comment]
@all following this thread, quoted from a previous post:
> Just to make sure I'm understanding this discussion correctly **-- is this summary correct?**
> By using a symbolic link, .desktop files will now run a sandboxed copy of Firefox -- from anywhere on the system, as well as from the Start Menu/Application Launcher (KDE terminology). Likewise, Session Restore will create a sandboxed copy of Firefox, whenever the system restarts.

Would I be correct in assuming the answer to the question, in the first line -- is a '_Yes_'?

That would be most helpful so I know exactly for what I should be looking, as I proceed.
I find that by restating, in one place, the 'bits' from posts of others who are better informed than I serves as a double-check to confirm I am following, without misunderstanding.
Thanks!

**Comment by netblue30** [comment]
@roncam - yes, your summary is correct.

**Comment by RonCam** [comment]
There is a problem -- firefox can't find its profile.

**Comment by RonCam** [comment]
I've started a new thread.
