### ISSUE TITLE
firejail breaks haskell development tools cabal and stack

### ISSUE THREAD

**Issue by hyiltiz** [netblue30/firejail#3591]
`cabal` and `stack` are like package managers for Haskell. They manage their *local database* for packages, which can be synced with `xxx update` commands, and they can install packages from *online* via `xxx install`. The Haskell community uses both tools. For a starter, it may be useful to base their `.profile` on something similar like `pip` or `npm`, then fine tune.

I'd give a full bug report, but profiles for them are missing and Haskell isn't even mentioned while `pip` `gems` `luarocks` etc. are mentioned, I'd wait until someone comes up with something. To start, maybe whitelist their database folders, give permissions to binaries that deal with project management for Haskell such as running parsers, compilers (GHC) etc., and also some network support (for Hackage and Stackage to download package from).

**Comment by kortewegdevries** [comment]
How are you running them, neither has a profile?

**Comment by hyiltiz** [comment]
This is a profile request. When I ran `stack setup` or `cabal install agda` for example, they failed; however, when I ran `/usr/bin/stack setup` it would succeed... I am guessing `stack` was just running a `/usr/local/bin/stack` link with some default profile, but not sure.

**Comment by kortewegdevries** [comment]
`which -a stack` or `which -a cabal`? If I'm not mistaken there's no profile for `pip,npm,yarn,cabal,stack,brew,apt` etc. in firejail repository.

**Comment by hyiltiz** [comment]
I have at least two binaries for each... And none seem relevant to firejail. Sorry for the trouble. Yes, there are no profiles for those, but they seem to be mentioned in `disable-common.inc`; I wasn't sure if that would globally disable all those stuff once firejail is installed, unless whitelisted by specific profiles.
