### ISSUE TITLE
Some errors in Telegram

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3593]
There are some errors when running Telegram.  I dont see any significant difference, but only want to question the errors..

firejail /opt/Telegram/Telegram 
```
Reading profile /usr/local/etc/firejail/Telegram.profile
Reading profile /usr/local/etc/firejail/telegram.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-exec.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Parent pid 23981, child pid 23982
Warning: cleaning all supplementary groups
Child process initialized in 114.95 ms
The databases in [/home/test/.local/share/applications/] could not be updated.
error: : cannot open
error: : cannot open
error: : cannot open
```

Specifically the last 4 lines.

firejail version 0.9.62
Xubuntu 18.04
Telegram binary version: v 2.2.0

**Comment by kortewegdevries** [comment]
Does telegram not open under firejail or do you want to know what the errors are about?

Also are you using the tarball?

**Comment by svc88** [comment]
@kortewegdevries 

It does open, it works fine so far.  I am just questioning the errors in the last 4 lines

I am using the binary [here](https://github.com/telegramdesktop/tdesktop/releases/download/v2.2.0/tsetup.2.2.0.tar.xz)

**Comment by kortewegdevries** [comment]
Probably trying to update or create a desktop entry because that directory is `read-only`; try adding `read-write ${HOME}/.local/share/applications` to your profile to see if it fixes.Likely it's harmless warning...

**Comment by chiraag-nataraj** [comment]
For what it's worth, I don't get any such errors when I use the `telegram-desktop` package from Debian with the Telegram profile [here](https://github.com/chiraag-nataraj/firejail-profiles).

**Comment by svc88** [comment]
@kortewegdevries i put that line in telegram.profile just after the line `include telegram.local`
Seems this `The databases in [/home/test/.local/share/applications/] could not be updated.` disappeared but i still get these after each run:
```
error: : cannot open
error: : cannot open
error: : cannot open
```

Although could be harmless warnings, i was wondering whats causing them.
However as @chiraag-nataraj mentioned, if they dont affect functionality then its fine. thanks
