### ISSUE TITLE
Telegram Question about the privacy of multiple accounts

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3599]
Telegram offers multiple accounts, so from a security/privacy point of view, can these accounts be linked back to the same user?  Is there any ID that can link all your accounts on one user?
I take it maybe none of us know whats sent back to the telegram servers.
This might sound far-fetched, but could Firejail do anything about this or separate traffic within the profile to different accounts?

(This taking into account that you are connecting via a VPN or connecting Telegram via TOR)

**Comment by smitsohu** [comment]
> Telegram offers multiple accounts, so from a security/privacy point of view, can these accounts be linked back to the same user? Is there any ID that can link all your accounts on one user? 
I take it maybe none of us know whats sent back to the telegram servers.

It is not impossible that Telegram power users or people familiar with their code base are around here, but I think for such very specific questions your chances will be best when asking them on a Telegram bug tracker. It looks like all clients are open source and hosted on Github: https://telegram.org/apps
