### ISSUE TITLE
is there virtual memory option ?

### ISSUE THREAD

**Issue by seisdr** [netblue30/firejail#3600]
like I want to use wine on specific amount of ram can I do that?

**Comment by smitsohu** [comment]
Yes, there is an `--rlimit-as` option.

You could also create a user owned cgroup and use Firejail's `--cgroup` option (but note there is no cgroup v2 support yet: #2896)

**Comment by seisdr** [comment]
```
root@localhost:~# firejail --rlimit-as 400 ls
Warning: an existing sandbox was detected. 400 will run without any additional sandboxing features
/bin/bash: 400: command not found
````
it keep telling me there's existing sandbox

**Comment by smitsohu** [comment]
> it keep telling me there's existing sandbox

It usually speaks the truth. Your shell is already sandboxed, and nesting Firejail sandboxes is not possible.

`exit` and try again. If necessary `exit` several times.

Two more remarks: You are executing application `400`, what you probably want is `firejail --rlimit-as=400 ls`.
Finally, the limit is given in bytes, and 400 will be much to little. You will need megabytes of address space just to execute bash or ls.

**Comment by seisdr** [comment]
well  I need 4gb to execute winehq and my device is 2gb the environment I'm into is qemu which means it's sandboxed is there any option I can use to force firejail to work ?

**Comment by smitsohu** [comment]
well I need 4gb to execute winehq and my device is 2gb 

That's ok because it is virtual memory. If you want a limit on physical memory (or something closely related at least) I think cgroups are the only solution right now.

**Comment by seisdr** [comment]
how do I do that I look up cgroups is package on Linux

**Comment by rusty-snake** [comment]
https://github.com/pshved/timeout

**Comment by seisdr** [comment]
yeah tmi remember that didn't work
I'm closing this

**Comment by rusty-snake** [comment]
There are some links in the README.md. Short summary: for services use systemd for anything else there is no good solution.
