### ISSUE TITLE
Toggle Network

### ISSUE THREAD

**Issue by nPHYN1T3** [netblue30/firejail#3610]
I've got a problematic application I jail. Predominantly I want its network access cut off but from time to time I do have to "unleash" the "_steam_ing" turd that it is. I've searched high and low as well as tried many things to "toggle" network access to no avail. Sadly steam will crash my X Session if I restart it so every time I restart it to switch net access it's a huge pain. Is there any way to toggle the network of/in a jail?

**Comment by rusty-snake** [comment]
TL;DR; Sadly, there is no such way.

Long story: You could use `--net=<bridge>` and control this bridge.

---

Possible workarounds: If you can not find the cause for the crash, it might not crash if you use X11 sandboxing (--x11=...). _I belief I remember some HW-accel issues with xephr or xpra._

**Comment by nPHYN1T3** [comment]
I haven't thought about bridges in a long time. Comically a bit ago I was thinking about installing a crappy wifi USB dongle and forcing it to use that so I can kill it without killing the host network. I'll poke around I suppose. Just had hoped maybe there was a solution that wasn't overtly documented or obvious. It wouldn't be such an issue it it wasn't for steam crashing things.
