### ISSUE TITLE
Disabling /dev/snd/ with private-dev?

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#3613]
Is it possible to blacklist /dev/snd/ along with private-dev? 
I've tried including `blacklist=/dev/snd/` but applications still see the sound system.
Pulseaudio exposes sound hardware UIDs to applications.
I saw that /snd/ was included in private-dev, it could be useful to have more granular control.

**Comment by rusty-snake** [comment]
Works for me.
```
# Without private-dev
$ firejail --noprofile --blacklist=/dev/snd ls /dev/snd -ld
$ firejail --noprofile --blacklist=/dev/snd/ ls /dev/snd -ld

# Whith private-dev before
$ firejail --noprofile --private-dev --blacklist=/dev/snd ls /dev/snd -ld
$ firejail --noprofile --private-dev --blacklist=/dev/snd/ ls /dev/snd -ld

# Whith private-dev after
$ firejail --noprofile --blacklist=/dev/snd --private-dev ls /dev/snd -ld
$ firejail --noprofile --blacklist=/dev/snd/ --private-dev ls /dev/snd -ld
```

You can use `nosound` (`firejail --noprofile --nosound ls /dev/snd -ld`) to hide /dev/snd. Using `blacklist` only makes it inaccessible, which also leaks nothing.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
