### ISSUE TITLE
telegram.profile needs netlink protocol

### ISSUE THREAD

**Issue by reagentoo** [netblue30/firejail#3614]
Since v2.3.0 the Telegram Desktop supports video calls.
https://github.com/telegramdesktop/tdesktop/releases/tag/v2.3.0
This feature does not work w/o netlink protocol in the profile. Tested on v2.3.2.
Please change the next [line](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/telegram.profile#L23)
`protocol unix,inet,inet6`
to
`protocol unix,inet,inet6,netlink`

**Comment by rusty-snake** [comment]
Fixed, Thanks.
