### ISSUE TITLE
Opening up x-terminal-emulator with --noprofile exits the jail

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3615]
When i try to open up `x-terminal-emulator` or even `xfce4-terminal` **from** `xfce4-terminal` like this:
`firejail --noprofile x-terminal-emulator`
or
`firejail --noprofile xfce4-terminal`

It opens up the terminal but it ends in the original terminal like this:
```
Parent pid 13574, child pid 13575
Child process initialized in 10.26 ms

Parent is shutting down, bye...
```

It exits the jail. Why? What am i doing wrong?

firejail version 0.9.62

PS:
I tried this in a VM of the same OS Xubuntu 18.04 but there it doesnt exit the jail and i dont know why

**Comment by svc88** [comment]
If i try this from `Konsole` from my own machine i dont get this unexpected exit.  Only from my `xfce4-terminal`

**Comment by rusty-snake** [comment]
They blacklisted in disable-common.inc, but this is not included if you use `--noprofile`. Do you have a xfce4-terminal symlink or use firejail as login-shell?

**Comment by svc88** [comment]
my xfce4-terminal opens up from the icon in the whisker menu - `exo-open --launch TerminalEmulator`

I dont know if i use firejail as login-shell, i just open up my terminal from the shortcut above and run the cmd `firejail --noprofile xfce4-terminal` and all it does is exit the jail and open up yet another xfce4-terminal

**Comment by svc88** [comment]
I even downloaded gnome-terminal and its doing the same thing.
I did more tests and noticed that it doesnt do it if i run this on a minimal Ubuntu Server 18.04 with Xfce4.  Seems like its only doing it on a Xubuntu 18.04 installation and not sure why.  Can you try reproduce?

**Comment by kortewegdevries** [comment]
> however the only time the jail exists unexpectedly is when running that cmd within xfce4-terminal itself

issue 240 here

**Comment by svc88** [comment]
@kortewegdevries makes sense thanks.   However i dont see that issue mentioning anything about this:
> BUT, if i try this on Ubuntu Server + xfce4, the jail runs fine from within `xfce4-terminal`
> So im not sure why this happens.

If i missed anything in there regarding why xfce4-terminal jail runs fine if xfce4-terminal is installed on a Ubuntu Server + xfce4 environment, please tell me

**Comment by kortewegdevries** [comment]
>  minimal Ubuntu Server 18.04 with Xfce4

Do you mean the MinimalCD (https://help.ubuntu.com/community/Installation/MinimalCD) + xfce4 or this one https://ubuntu.com/server?

**Comment by svc88** [comment]
The second one. More precisely this: http://www.cdimage.ubuntu.com/ubuntu-server/bionic/daily-live/current/bionic-live-server-amd64.iso

**Comment by kortewegdevries** [comment]
I tried with a Debian bullseye minimal cd+lxde, same behaviour; tried with the base 20.04 server+ubuntu-desktop meta package, still same. I don't know how server works but I can't think of a reason on why it'd be any different. Maybe some else can offer insights...

**Comment by rusty-snake** [comment]
still an issue?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
