### ISSUE TITLE
MAC Address --mac should be able to be changed/spoofed without the need for --net

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3617]
In short, im using VPN on the PC. So all i wanted was to change the MAC address on the app i run eg:
```
firejail --noprofile --mac=03:0A:DE:E8:A7:26 xterm
Error: no network device configured
```

It will only work if i explicitly put eg:
`firejail --noprofile --net=eth0 --mac=03:0A:DE:E8:A7:26 xterm`
or rather:
`firejail --noprofile --net=eth0 --dns=1.1.1.1 --mac=03:0A:DE:E8:A7:26 xterm`

But the problem is then i wont be connected to the VPN anymore, since i am forced to connect directly to the eth0 adapter.
Which brings me to the follow up issue of needing to specify a tun0 adapter, however i have read quite a lot on here that tun0 adapter isnt supported and ive been meaning to also voice my need for it.

But if i can specify a MAC address right now without needing to specify --net, that would be great. (this would be the easiest choice)
Is this at all a possibility?  
Im going to assume that your answer would be that the specified MAC needs to bind to a specific adapter, but cant you just specify the MAC and bind it to the default adapter that the jail is using.. which would be the default connection tun0 in my case?

Would appreciate some insight into this

**Comment by rusty-snake** [comment]
I don't think this is possible.
