### ISSUE TITLE
hedgewars crashes without access to liblua

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#3625]
`hedgewars.profile` causes game engine to crash with
```
The game engine died unexpectedly! (exit code 127)
```
This has been identified as an issue where `hwengine` needs access to lua interpreter which is blacklisted in the profile. The following line added to the profile fixed the condition on Arch Linux:
```
noblacklist /usr/lib/liblua*
```

**Comment by rusty-snake** [comment]
Thanks for reporting.
