### ISSUE TITLE
"Cannot alocate memory" error when trying to copy/paste in MPV

### ISSUE THREAD

**Issue by Unser395** [netblue30/firejail#3628]
**Bug and expected behavior**
- Describe the bug. Pasting a youtube link through a keyboard shorcut in MPV doesn't open the video. The keyboard shortcut was configured by a Lua user script.
- What did you expect to happen? To have the shortcut work and be able to watch the video

**No profile or disabling firejail**
- What changed calling `firejail --noprofile PROGRAM` in a shell? It works

**Reproduce**
1- `sudo firecfg`
2- Install user script "SmartCopyPaste_2_2 "https://github.com/Eisa01/mpv-scripts#smartcopypaste-ii-script"
3- Open MPV
4- Copy paste a youtube link into MPV with a keyboard shortcut
5. See error `[SmartCopyPaste_2_2] Lua error: /home/user/.config/mpv/scripts/SmartCopyPaste-2.2.lua:73: xclip -selection clipboard -o: Cannot allocate memory`

**Environment**
 - Linux distribution and version : Manjaro Linux 20.1
 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`) : firejail version 0.9.62.4
 - What other programs interact with the affected program for the functionality? SmartCopyPaste_2_2 user script
 - Are these listed in the profile? I've tried to whitelist the script folder but mpv couldn't be launched anymore

**Additional context**
Other context about the problem like related errors to understand the problem.

**Checklist**
 - [x] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [x] The upstream profile exists (`find / -name 'firejail' 2>/dev/null`/`fd firejail` to locate profiles ie in `/usr/local/etc/firejail/PROGRAM.profile`)
 - [x] Programs needed for interaction are listed.
 - [x] Error was checked in search engine and on issue list without success.

Thank you very much for all your work !

**Comment by rusty-snake** [comment]
> Programs needed for interaction are listed.

Likely not, the error message says something about xclip, which is not in mpv's private-bin.

Can you try `firejail --private-bin=xclip mpv ...`.

**Comment by Unser395** [comment]
Thank you for the quick answer !

I've tried to launch mpv through the command you gave me and still gives the same error.
Adding xclip in the config file didn't help either.

**Comment by rusty-snake** [comment]
Ok, played a bit with it. Seems like lua always uses a shell.
`firejail '--noblacklist=${PATH}/sh' --private-bin=xclip,sh mpv …`

**Comment by Unser395** [comment]
Thank you very much, it fixed the issue !
Have a nice day, rusty-snake
