### ISSUE TITLE
Problem Apparmor with Brave

### ISSUE THREAD

**Issue by Bundy01** [netblue30/firejail#3629]
Write clear, concise and in textual form.

**Bug and expected behavior**
I have an Apparmor warning popup when launching Brave Browser.

**No profile or disabling firejail**
It's OK.

**Environment**
 - Linux distribution: Arch
 - Firejail version: 0.9.62.4
 - What other programs interact with the affected program for the functionality? no
 - Are these listed in the profile?  yes

**Checklist**
 - [ ] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [x] The upstream profile exists (`find / -name 'firejail' 2>/dev/null`/`fd firejail` to locate profiles ie in `/usr/local/etc/firejail/PROGRAM.profile`)
 - [ ] Programs needed for interaction are listed.
 - [x] Error was checked in search engine and on issue list without success.

audit.log
<details><summary> debug output </summary>

`
type=AVC msg=audit(1599667022.015:665): apparmor="DENIED" operation="open" profile="firejail-default" name="/proc/87/clear_refs" pid=124712 comm="MemoryInfra" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
`

</details>

I disabled apparmor in the chromium-common profile and the bug stopped.
It's not really the best thing to do. Isn't the problem coming from the Firejail profile for Apparmor?

Regards.

**Comment by rusty-snake** [comment]
@Vincent43 your the apparmor expert here.

**Comment by Vincent43** [comment]
This should be fixed by this [commit](https://github.com/netblue30/firejail/commit/873a97a9b3442976a618333c1063da13d2a38025) which is only in master branch atm.

**Comment by Bundy01** [comment]
@Vincent43: Your patch seems to work after a reboot and reload of the apparmor service.

Thanks.

**Comment by Vincent43** [comment]
try adding:
`owner /home/**/.config/BraveSoftware/Brave-Browser/** ix,`

in `/etc/apparmor.d/local/firejail-local` then restart apparmor or reboot.

**Comment by Bundy01** [comment]
I copied your instruction in the file but the error comes back.

**Comment by Bundy01** [comment]
I'm coming back to this issue because Tor in Brave doesn't work anymore (no internet connection). This time it's not a problem with Apparmor. This one appeared on Arch with version 0.9.64rc1-2. With version 0.9.64-1, it's identical.

**Comment by Vincent43** [comment]
Are you sure it's not Apparmor? I heard that Arch Linux package update wiped local `/etc/apparmor.d/local/firejail-default` changes so your `owner /home/**/.config/BraveSoftware/Brave-Browser/** ix,` rule may be lost. If it's not apparmor problem then feel free to open new issue with more details and this one should be closed.

**Comment by Bundy01** [comment]
The problem doesn't come from apparmor this time (I commented the apparmor line in chromium-common.profile).
Indeed, /etc/apparmor.d/local/firejail-default was overwritten during updates, but it has been fixed with the latest version (.pacnew).
For `/home/**/.config/BraveSoftware/Brave-Browser/** ix,` are you thinking of doing a PR?

I can make another issue for the new problem, but I don't have much information because it appeared with the firejail-0.9.64rc1-2 package. I also have an 'execvp' error when running the Tor profile.

**Comment by Vincent43** [comment]
>  For /home/**/.config/BraveSoftware/Brave-Browser/** ix, are you thinking of doing a PR?

As a general policy we don't allow executing code from user home in global firejail appamor profile so changes like this belong to user own overrides.

> I can make another issue for the new problem, but I don't have much information because it appeared with the firejail-0.9.64rc1-2 package. I also have an 'execvp' error when running the Tor profile.

Please do and show all errors from console. As this issue is about apparmor I don't want to convolute it with unrelated problems.

**Comment by Bundy01** [comment]
Ok, no problem.
I ceate an hover issue for that.

This issue can be close.
