### ISSUE TITLE
transmission-daemon fills log with error

### ISSUE THREAD

**Issue by solsticedhiver** [netblue30/firejail#3636]
I had a perfectly fine *transmission-daemon* setup running on a *rpi3* (using *archlinux-arm*)

I changed it to use firejail with transmission-daemon. Then, transmission-daemon began to fill the system log with errors like:
```
Sep 20 01:10:06 tarvos transmission-daemon[30237]: Some torrent name here IPv4 DHT announce failed (firewalled, 237 nodes): Success (tr-dht.c:737)
Sep 20 01:10:12 tarvos transmission-daemon[30237]: Some torrent name here IPv4 DHT announce failed (firewalled, 237 nodes): Success (tr-dht.c:737)
Sep 20 01:10:21 tarvos transmission-daemon[30237]: Some torrent name here IPv4 DHT announce failed (firewalled, 239 nodes): Operation now in progress (tr-dht.c:737)
Sep 20 01:10:26 tarvos transmission-daemon[30237]: Some torrent name here IPv4 DHT announce failed (firewalled, 239 nodes): Resource temporarily unavailable (tr-dht.c:737)
Sep 20 01:10:34 tarvos transmission-daemon[30237]: Some torrent name here IPv4 DHT announce failed (firewalled, 239 nodes): Success (tr-dht.c:737)
Sep 20 01:10:40 tarvos transmission-daemon[30237]: Some torrent name here IPv4 DHT announce failed (firewalled, 239 nodes): Operation now in progress (tr-dht.c:737)
Sep 20 01:10:48 tarvos transmission-daemon[30237]: Some torrent name here IPv4 DHT announce failed (firewalled, 240 nodes): Success (tr-dht.c:737)
```

*transmission-daemon* seems to work fine but I am not an expert. I guess the error messages are not without reason.

Nonetheless, I fixed the log filling issue by adding `packet` to the list of protocol in a `.local` **override** file like:

    protocol unix,inet,inet6,packet

**Comment by rusty-snake** [comment]
`packet` is a quite power full socket. As long as nothing is broken, I'm not happy adding it. My question is: **Is** nothing broken? DHT is one way to get other peers, are there less peers in use if started w/o packet? DHT is also used _announce_ you as a peer.

**Comment by solsticedhiver** [comment]
I am not an expert either with firejail. May be there is a less permissive fix to that ?
