### ISSUE TITLE
PulseAudio Isolation

### ISSUE THREAD

**Issue by HulaHoopWhonix** [netblue30/firejail#364]
An interesting security feature planned in oz is the blocking of PulseAudio access for programs that have no legitimate need to access the microphone or other audio streams.

**Comment by chiraag-nataraj** [comment]
The --nosound flag for firejail should do something very similar. @netblue30, how exactly is --nosound implemented? Does it just disable access to Pulse or does it also disable access to the devices themselves?

**Comment by netblue30** [comment]
--nosound disables access to PulseAudio and ALSA
