### ISSUE TITLE
Gimp - add note how to enable scanning (xsane)

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#3640]
Default `gimp.profile` breaks scanning via `File - Create` menu. It would be nice if the profile lists what is needed (for `gimp.local`) to bring these feature back:
```
# to enable Xsane dialog (scanning via File - Create)
ignore seccomp
ignore dbus-system

# to enable Xsane scanning via network
protocol unix,inet,inet6
ignore net
```

**Comment by rusty-snake** [comment]
Looks good:
```
# to enable Xsane scanning via network
ignore net none
protocol unix,inet,inet6
```

The first one is very permissive. `seccomp` likely need only one or two syscalls (have a look at your syslog). The system bus also need a few name to allow.
```
dbus-system filter
dbus-system.talk xxx
ignore dbus-system none
```

**Comment by jose1711** [comment]
I don't see anything related to dbus in journal log, only GIMP complains in the console:
```
gui_dbus_name_lost: connection to the bus cannot be established.
```
How to find out which dbus services I need to allow?

**Comment by rusty-snake** [comment]
> How to find out which dbus services I need to allow?

ATM, there is no master-solution. (You need some knowledge and) you can use
- `dbus-monitor`, but this make much spam especially if use do not use a own bus for it.
- `--dbus-log`, but this requieres `--dbus-xxx=filter`
- `flatpak remote-info flathub -m APP-ID` 
- `d-feet`, `qtdbus-viewer`, `bustle`
- ...
