### ISSUE TITLE
Firejail profile preventing flameshot from starting

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#3643]
Hopefully someone else with Arch Linux can confirm this but for me `flameshot gui` in console does nothing (no window pops up) until I remove/comment the following two lines in `flameshot.profile`:
https://github.com/netblue30/firejail/blob/1a6a87675b027121d56aff764130fe2eb46b5889/etc/profile-a-l/flameshot.profile#L54-L55

DE used: Gnome (not sure if this is relevant)

**Comment by rusty-snake** [comment]
On Fedora:
```
$ grep flameshot /usr/share/dbus-1/services/*
/usr/share/dbus-1/services/org.flameshot.Flameshot.service:Name=org.flameshot.Flameshot
/usr/share/dbus-1/services/org.flameshot.Flameshot.service:Exec=/usr/bin/flameshot
```

:clap: :innocent: :yum: They [changed the APP-ID](https://github.com/flameshot-org/flameshot/commit/18f18ce7ef319ebedf1e0adfd4a87eb4cd798e81). :woozy_face: That's will be a fun if more projects do the same :zany_face: .
