### ISSUE TITLE
Waterfox-Current, (Ungoogled) Chromium browsers have no internet connect 

### ISSUE THREAD

**Issue by esotericDisciple** [netblue30/firejail#3646]
Write clear, concise and in textual form.

**Bug and expected behavior**
- Describe the bug.
Waterfox-Current and (ungoogled) Chromium can't reach any websites
- What did you expect to happen?
For this to not be an issue after I uninstalled expressvpn for being worse than mullvad to the point that it outweighs the pro of having fewer ip addresses that cloudflare and other sites block automatically....
**No profile or disabling firejail**
- What changed calling `firejail --noprofile PROGRAM` in a shell?
the issue goes away for both watherfox and chromium
- What changed calling the program *by path*=without firejail (check `whereis PROGRAM`, `firejail --list`, `stat $programpath`)?
the issue goes away, but i was spooked because waterfox opened a subdomain page of operatenewestheavilyapplication.icu which wanted me to download something under the pretext of a 'ugrade firefox' page (perhaps the addon chamelion partially protected me there), and I have no idea why...(that didn't happen with "`firejail --noprofile...` ")
**Reproduce**
1. Run in bash `firejail PROGRAM`
`firejail waterfox-current -no-remote -ProfileManager` | `firewarden chromium` | `firejail chromium`
2. See error `ERROR`
debug text was not printed in an ADHD-friendly way, so it remains and will remain unread. However chromium complained about not being able to lookup the ip of the url (I forget what waterfox said, but I'll forget to finish this if I have to do all that over again)
3. Click on '....'
N/A
4. Scroll down to '....'
N/A
**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`)
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.1
Codename:       Mikah
 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`)
firejail version 0.9.62.4

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

 - What other programs interact with the affected program for the functionality?
prime-run, nohup (run before firejail, IE `prime-run firejail` `nohup firejail`)
 - Are these listed in the profile? 
no because they aren't run inside of firejail
**Additional context**
Other context about the problem like related errors to understand the problem.
the issue happened right after uninstalling expressvpn-gui (AUR), expressvpn (and systemd services) and rebooting
waterfox-current.profile might be from the PKG firejail-extra-profiles, but the issue persisted with waterfox.profile (waterfox profiles can't be loaded using firejail's firefox.profile)....
**Checklist**
 - [ ] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [ ] The upstream profile exists (`find / -name 'firejail' 2>/dev/null`/`fd firejail` to locate profiles ie in `/usr/local/etc/firejail/PROGRAM.profile`)
 - [* ] Programs needed for interaction are listed.
 - [ *] Error was checked in search engine and on issue list without success.

<details><summary> debug output </summary>

```
OUTPUT OF `firejail --debug PROGRAM`
```

</details>

**Comment by rusty-snake** [comment]
Output of `ls -l /etc/resolv.conf`?

**Comment by esotericDisciple** [comment]
ah thanks. I didn't realize resolv.conf had that much influence over internet connectings...expressvpn had some leftover files and dirs after the uninstall that I had to remove manually, including a symlink to their resolv.conf...once I restored the old one the profiles worked again...
