### ISSUE TITLE
SlimJet Browser

### ISSUE THREAD

**Issue by Felemur** [netblue30/firejail#366]
Firejail works well with Chromium, FireFox and Pale Moon. However there seems to be a problem with SlimJet, a browser based on the Chromium project. The browser, when launched under Firejail, fails to show up in the panel of running programs or open a window, but does show up as a running process under the System Monitor. 

Linux Mint, Cinnamon, 17.3

**Comment by netblue30** [comment]
I added support for it on the master branch. The profile file is flashpeak-slimjet.profile in /etc/firejail directory.

https://github.com/netblue30/firejail/blob/master/etc/flashpeak-slimjet.profile

To start the browser, the command is:
`````
$ firejail flashpeak-slimjet --no-sandbox
`````

**Comment by Felemur** [comment]
Thank you for doing that. However, I think I'm doing something wrong (forgive me, I'm fairly new to Linux). I tried to run it in the GUI, and Slimjet would not start, so I tried running it from the Terminal and this is what I got:

**davidm@davidm-Satellite-L770D ~ $ firejail flashpeak-slimjet --no-sandbox
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 7179, child pid 7180

Child process initialized
[2:2:0316/132324:ERROR:browser_main_loop.cc(206)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[2:15:0316/132324:ERROR:address_tracker_linux.cc(153)] Could not create NETLINK socket: Operation not supported
[2:27:0316/132325:ERROR:nss_util.cc(738)] Error initializing NSS with a persistent database (sql:/home/davidm/.pki/nssdb): NSS error code: -8174
libudev: udev_monitor_new_from_netlink_fd: error getting socket: Operation not supported
[0316/132325:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

parent is shutting down, bye...
davidm@davidm-Satellite-L770D ~ $ 

**

**Comment by netblue30** [comment]
Without installing the new version, I think this should work:
`````
$ firejail --ignore=protocol flashpeak-slimjet --no-sandbox
`````

**Comment by Felemur** [comment]
Yes, that did work, thank you. I did get a warning from Slimjet when starting - see attached image:

![slimjet screenshot from 2016-03-16 17 50 37](https://cloud.githubusercontent.com/assets/17836628/13830908/5c7f2ee0-eba6-11e5-8960-40c3f6b87b7e.png)

I creatied a file in _/etc/firejail_ called **flashpeak-slimjet.profile** with the code provided (https://github.com/netblue30/firejail/blob/master/etc/flashpeak-slimjet.profile), but that did not work when I tried to launch the program - it did not launch. Again, I might be making a fundamental mistake due to ignorance. BTW, I tried launching with both **$ firejail --ignore=protocol flashpeak-slimjet --no-sandbox** and **$ firejail flashpeak-slimjet --no-sandbox**. When I removed the **flashpeak-slimjet.profile** from _/etc/firejail_ and retried **$ firejail --ignore=protocol flashpeak-slimjet --no-sandbox**, it did work again.

I will update to the new Firejail version with the new profile when out and let you know how it works - I have the 2016-02-04 version installed and will update as soon as the newer version is out with the Slimjet profile.

**Comment by netblue30** [comment]
Let's leave it open as an enhancement. I'll look into it, thanks!

**Comment by netblue30** [comment]
It will stay as is. SlimJet is a proprietary browser, no source code available. In order for them to use their own sandbox, they need root privileges. Since firejail take root privileges away, they end up showing the message you  posted above.
