### ISSUE TITLE
Unable to whitelist steamapps when using --private

### ISSUE THREAD

**Issue by S0PEX** [netblue30/firejail#3663]
**Bug and expected behavior**
When using --whitelist the jail should have access to the whitelisted folder. 

**No profile and disabling firejail**
I tried it with --noprofile and without

**Reproduce**
1. Run in bash `firejail --noprofile --private --whitelist=/home/artur/.local/share/Steam/steamapps/`
2. When launching a game the game has to be redownloaded as the jail has no access to the steamapps folder

**Environment**
 - Arch Linux Linux 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux
 - firejail version 0.9.62.4

**Additional context**
I am trying to launch two steam game instances to trade my items to my other account.
When I run `firejail steam` the steam instance start and I can run the game. To open a second instance I run `firejail --noprofile --private --whitelist=/home/artur/.local/share/Steam/steamapps/`, but this instance couldn't access the steamapps folder. 
Then I tried to create a folder and create a symbolic link to the steamapps folder
`/home/artur/jails/1/.local/share/Steam/steamapps -> /home/artur/.local/share/Steam/steamapps/` and provided firejail with the private `firejail --noprofile --private=/home/artur/jails/1 --whitelist=/home/artur/.local/share/Steam/steamapps/` without any luck.
I then ended up using `mount-bind` and mount the steamapps directory inside `/home/artur/jails/1/.local/share/Steam/steamapps` which then worked.

**So I was wondering if there is a better way without `mount-bind`.**

Regards Artur

**Comment by rusty-snake** [comment]
First, this is expected behaviour. `--private` make a new, empty, temporary private $HOME.

>  So I was wondering if there is a better way without mount-bind.

IDK what exactly you want to reach, but here are two ways:
1. `firejail --private=/home/user/foobar …` makes everything persistent under `/home/user/foobar/.local/share/Steam/steamapps` (which is inside the sandbox `/home/user/.local/share/Steam/steamapps` )
2. `firejail --whitelist=$HOME/home/artur/.local/share/Steam/steamapps …` makes only `$HOME/home/artur/.local/share/Steam/steamapps` appear in the sandbox.

**Comment by S0PEX** [comment]
I just want to run steam with the access to my local steam games library which is located under `home/artur/.local/share/Steam/steamapps/`. The only option that I found was working was to manually `mount-bind` that directory in my `--private /home/artur/jails/1/`. It would be nice if firejail could directly access `/home/artur/.local/share/Steam/steamapps/ ` without any restrictions.

**Comment by reinerh** [comment]
That should work by default. What is your intention with running firejail with `--private`? This creates a temporary home directory as @rusty-snake already mentioned.

What's the behavior/error when you just run `firejail steam`?

**Comment by S0PEX** [comment]
Well I though running jail with `--private=/home/artur/jails/1/` persists all data to the given folder. Also steam works without any issues when bind-mounting the steamapps folder into `/home/artur/jails/1/.local/share/Steam/steamapps`. Because otherwise the folder `/home/artur/.local/share/Steam/steamapps ` isn't visible to the jailed steam.

**Comment by rusty-snake** [comment]
Nope, I know no better way then manually bind-mounting.
