### ISSUE TITLE
Torbrowser-launcher.profile doesn't launch without certain flags disabled

### ISSUE THREAD

**Issue by johnhandcockandstuff** [netblue30/firejail#3666]
I've actually had this issue for a while, and decided I would post an issue about it on here even though I don't think it is that terrible of an issue(?) Essentially, with the default torbrowser-launcher.profile located in /etc/firejail/, it will only actually work if the following calls are commented out: "apparmor," "protocol unix,inet,inet6," and "seccomp !chroot."

Interestingly, when I launch torbrowser-launcher, and check aa-status, it says that Apparmor is actually actively protecting, but it doesn't work when literally calling it with firejail. As for the other calls, I just am not sure. I have played around a ton with the profile to get it to work with the most calls allowed, and this is basically the result I got after disabling and enabling a ton of things one-by-one. No clue why it's happening, however.

**Comment by rusty-snake** [comment]
The torbrowser-launcher.profile here has no `aaparmor`, what is your firejail version, distro, torbrowser-launcher version? If you keep `seccomp !chroot` which syscall is logged in the syslog (`journalctl --grep=SECCOMP`)?

**Comment by johnhandcockandstuff** [comment]
> The torbrowser-launcher.profile here has no `aaparmor`, what is your firejail version, distro, torbrowser-launcher version? If you keep `seccomp !chroot` which syscall is logged in the syslog (`journalctl --grep=SECCOMP`)?

Oops, I must've added the apparmor one in myself. My bad. 

I'm on Parabola, using firejail 0.9.62.4-1 and torbrowser-launcher 0.3.2-6. I actually use OpenRC, so I am not entirely sure how to view the syscalls on here.

**Comment by rusty-snake** [comment]
If your kernel has audit support, is is logged somewhere I think. (Mabye `grep SECCOMP /var/log/*` or `grep syscall /var/log/*`?).

Does this happen if you skip torbrowser-launcher?
```
$ cd ~/.local/share/torbrowser-launcher/...  (go in the directory where start-tor-browser.desktop is)
$ firejail --profile=torbrowser-launcher ./start-tor-browser.desktop
```

**Comment by johnhandcockandstuff** [comment]
Yeah I'm not sure what to tell you, I don't know how to view the logs. Just forget it.

**Comment by SjoerdV** [comment]
> If your kernel has audit support, is is logged somewhere I think. (Mabye `grep SECCOMP /var/log/*` or `grep syscall /var/log/*`?).
> 
> Does this happen if you skip torbrowser-launcher?
> 
> ```
> $ cd ~/.local/share/torbrowser-launcher/...  (go in the directory where start-tor-browser.desktop is)
> $ firejail --profile=torbrowser-launcher ./start-tor-browser.desktop
> ```

This actually did work for me. So what I end up doing was creating my own launch script and desktop file.

1. create a bash script `~/.local/share/torbrowser/tbb/x86_64/tor-browser/start-tor-browser-launcher.sh`
```
#!/bin/bash
cd ~/.local/share/torbrowser/tbb/x86_64/tor-browser
firejail --profile=torbrowser-launcher ./start-tor-browser.desktop
```

2. Create/Modify the desktop file `~/.local/share/applications/start-tor-browser-launcher.desktop`
```
[Desktop Entry]
Type=Application
Name=Tor Browser Launcher
GenericName=Web Browser
Comment=Tor Browser is +1 for privacy and −1 for mass surveillance
Categories=Network;WebBrowser;Security;
Exec=sh -c ~/.local/share/torbrowser/tbb/x86_64/tor-browser/start-tor-browser.sh
Icon=torbrowser
StartupWMClass=Tor Browser Launcher
Terminal=false
```
