### ISSUE TITLE
skypeforlinux logs out every time, even without profile

### ISSUE THREAD

**Issue by ScoreUnder** [netblue30/firejail#3669]
**Bug and expected behavior**

After logging into skypeforlinux, then exiting the program, relaunching it under firejail will cause it to show a notification saying "You've been signed out of Skype. Launch the app to sign back in.". This does not happen if firejail is not used.

The expected behaviour here is for skype to remain logged in whether relaunched under firejail or not.

This problem persists even with `--noprofile`.

**Reproduce**
1. Log into Skype for Linux
2. Exit without signing out
3. Run Skype for Linux again, either under firejail (if testing bug) or without firejail (if testing normal behaviour)

**Environment**
- Arch Linux (Linux 5.8.13)
- Firejail 0.9.62.4
- Skype for Linux 8.65.0.76 (stable)

**Checklist**
 - [X] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [X] The program has a profile. (If not, request one in [# 1139](https://github.com/netblue30/firejail/issues/1139))
 - N/A Programs needed for interaction are listed in the profile.
 - [X] A short search for duplicates was performed.
 - N/A If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.

<details><summary> debug output </summary>

Left it running for just long enough to sign itself in and sign itself out again:

```
score@kirisame ~/.config/firejail % firejail --noprofile --debug /usr/bin/skypeforlinux
Autoselecting /bin/zsh as shell
Building quoted command line: '/usr/bin/skypeforlinux' 
Command name #skypeforlinux#
DISPLAY=:0 parsed as 0
Using the local network stack
Parent pid 2253759, child pid 2253764
Initializing child process
Host network configured
PID namespace installed
Mounting tmpfs on /run/firejail/mnt directory
Creating empty /run/firejail/mnt/seccomp directory
Creating empty /run/firejail/mnt/seccomp/seccomp.protocol file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec file
IBUS_ADDRESS=unix:abstract=/home/score/.cache/ibus/dbus-B6EYTCRw,guid=56b1ea7dbada33740999f4405f76fc01
IBUS_DAEMON_PID=1801
Mounting /proc filesystem representing the PID namespace
Basic read-only filesystem:
Mounting read-only /etc
Mounting noexec /etc
Mounting read-only /var
Mounting noexec /var
Mounting read-only /bin
Mounting read-only /lib
Mounting read-only /usr
Mounting tmpfs on /var/lock
Mounting tmpfs on /var/tmp
Mounting tmpfs on /var/log
Create the new utmp file
Mount the new utmp file
Cleaning /home directory
Cleaning /run/user directory
Sanitizing /etc/passwd, UID_MIN 1000
Sanitizing /etc/group, GID_MIN 1000
Disable /home/score/.config/firejail
Disable /run/firejail/network
Disable /run/firejail/bandwidth
Disable /run/firejail/name
Disable /run/firejail/profile
Disable /run/firejail/x11
Mounting read-only /proc/sys
Remounting /sys directory
Disable /sys/firmware
Disable /sys/hypervisor
Disable /sys/power
Disable /sys/kernel/debug
Disable /sys/kernel/vmcoreinfo
Disable /proc/sys/fs/binfmt_misc
Disable /proc/sys/kernel/core_pattern
Disable /proc/sys/kernel/modprobe
Disable /proc/sysrq-trigger
Disable /proc/sys/vm/panic_on_oom
Disable /proc/irq
Disable /proc/bus
Disable /proc/sched_debug
Disable /proc/timer_list
Disable /proc/kcore
Disable /proc/kallsyms
Disable /usr/lib/modules/5.8.13-arch1-1/build (requested /usr/src/linux)
Disable /usr/lib/modules (requested /lib/modules)
Disable /usr/lib/debug
Disable /boot
Disable /dev/port
Disable /run/user/1000/gnupg
Disable /run/user/1000/systemd
Disable /dev/kmsg
Disable /proc/kmsg
Disable /sys/fs
Disable /sys/module
Mounting noexec /run/firejail/mnt/pulse
Mounting /run/firejail/mnt/pulse on /home/score/.config/pulse
1188 1161 0:129 /pulse /home/score/.config/pulse rw,nosuid,nodev,noexec - tmpfs tmpfs rw,mode=755
mountid=1188 fsname=/pulse dir=/home/score/.config/pulse fstype=tmpfs
Current directory: /home/score
DISPLAY=:0 parsed as 0
Mounting read-only /run/firejail/mnt/seccomp
Drop privileges: pid 1, uid 1000, gid 1000, nogroups 0
starting application
LD_PRELOAD=(null)
Running '/usr/bin/skypeforlinux'  command through /bin/zsh
execvp argument 0: /bin/zsh
execvp argument 1: -c
execvp argument 2: '/usr/bin/skypeforlinux' 
Child process initialized in 5.91 ms
monitoring pid 2

Sandbox monitor: waitpid 2 retval 2 status 0
Sandbox monitor: monitoring 7
monitoring pid 7

Sandbox monitor: waitpid 7 retval 7 status 0
Sandbox monitor: monitoring 12
monitoring pid 12

Sandbox monitor: waitpid 12 retval 12 status 0
Sandbox monitor: monitoring 35
monitoring pid 35

Sandbox monitor: waitpid 35 retval 35 status 15

Parent is shutting down, bye...
firejail --noprofile --debug /usr/bin/skypeforlinux  5.21s user 0.86s system 118% cpu 5.112 total
```

</details>

**Comment by rusty-snake** [comment]
If something is broken even with `--noprofile`, it is likely that it can not be fixed.
However, you can
- check if there are any background daemons from skype outside the sandbox.
- look for non-default/changed settings in /etc/firejail/firejail.config
- try my noprofile

`noprofile.profile`
```
allow-debuggers
allusers
#keep-dev-shm
#keep-var-tmp
#noautopulse
writable-etc
writable-run-user
writable-var
writable-var-log

noblacklist /sys/fs
noblacklist /sys/module
```

**Comment by ScoreUnder** [comment]
I can't find any background processes owned by skype, there are no uncommented lines in `firejail.config`, and I get the same results under `noprofile.profile`... I guess this isn't something that can be solved without disproportionately meticulous levels of investigation, so I'll close this for now under the assumption that it's not practical to fix.

**Comment by oliversturm** [comment]
No idea if this helps at all, but I have encountered this problem just now with Arch updates no more than a week old. Prior to that, Skype was working with firejail without any trouble.
