### ISSUE TITLE
Parse /etc/login.def for UID_MIN

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#367]
Maybe I'm misunderstanding what you mean by "sanitizing" /etc/passwd and /etc/group, but the files seem to be the same as they are outside the sandbox. What exactly does firejail do?

**Comment by netblue30** [comment]
Only the current user and group are left in the file. All other users/groups are removed. If you are the only user on the system, the files will be unchanged.

**Comment by chiraag-nataraj** [comment]
Ah okay, thanks!

**Comment by thomasjfox** [comment]
Also every uid < 1000 is kept, at least in firejail up to 0.9.42-rc1.
Later versions might parse /etc/login.defs for UID_MIN.

I stumbled upon this behaviour since the restricted /etc/passwd still contained an additional user account with UID 503.

**Comment by netblue30** [comment]
Fixed in git repository.

**Comment by thomasjfox** [comment]
On Friday, 29. July 2016 06:51:06 netblue30 wrote:
> Fixed in git repository.

pretty cool :) thanks!

**Comment by netblue30** [comment]
You're welcome!
