### ISSUE TITLE
Disable user-defined profile

### ISSUE THREAD

**Issue by johnwmail** [netblue30/firejail#3677]
Hi, is it possible disable user-define profile?
I don't want the user ignore the system rules/profile.
Thanks.

**Comment by rusty-snake** [comment]
It would be possible to add a option to e.g. firejail.config to disable ~/.config/firejail and commanline args. However firejail can not make sure a program is started in a sandbox (`/usr/bin/thunderbird` is still possible). So if your use-case is to force restrictions for some user-started programs, you should use a LSM such as SELinux or AppArmor.

**Comment by johnwmail** [comment]
> It would be possible to add a option to e.g. firejail.config to disable ~/.config/firejail and commanline args. 
Hi, it is what I am looking for, would you show me a example how? which option should I add it to /etc/firejail/firejail.config?
Thanks.

**Comment by rusty-snake** [comment]
I meant it would be possible to implement. ATM there is no such option. Though I'm still not sure if this is useful as running w/o firejail is still possible. What scenario do you target?

**Comment by johnwmail** [comment]
Yes, you are right, user can always override the parameter with command line, so I close this.
Thanks.
