### ISSUE TITLE
Firefox 82.0 does not work in firejail 0.9.62.4-1

### ISSUE THREAD

**Issue by Wolf-Italy** [netblue30/firejail#3680]
Sender: Gianpietro.
---
I would like to report this problem.
---
After updating to Firefox 82.0, this afternoon firejail 0.9.62.4-1 
does not start Firefox 82.0, in Linux Mint 19.3 Tricia.

This morning with Firefox 81.0.2 everything worked correctly.

See screenshots attached:

https://imgur.com/heTUXzK

https://imgur.com/OldLzLA

**Comment by SkewedZeppelin** [comment]
I've had FF82 in firejail for 3 days now, no issue.

Does
firejail /usr/bin/firefox
make any difference?

Do you have AMD graphics?

**Comment by Wolf-Italy** [comment]
Good morning SkewedZeppelin.
---
I am not an experienced user.
---
With the command firejail /usr/bin/firefox
this result screenshot:

https://imgur.com/1gPP7Ln
---
Yes I have a video card integrated in the Processor

Intel Core i7 8700T CPU 2.40 GHz CPU x 6

**Comment by reinerh** [comment]
Sounds like /usr/bin/firefox is just a wrapper script in Linux Mint, and it tries to invoke dpkg (as it tries to access `/var/lib/dpkg/status`).  
Is anyone else using Mint to confirm that?

**Comment by clefebvre** [comment]
Hi @reinerh,

Absolutely. This is a mistake on our side. We're sending an update to correct this ASAP.

**Comment by kinglike1337** [comment]
Yes, I can confirm that Linux Mint is using a wrapper script and calling dpkg-query.
This new behaviour was introduced after upgrading Firefox 81.0.2 to Firefox 82.0.
They changed the wrapper script to use some kind of version check using dpkg-query and appending "--purgecaches" to the firefox command line.

**Comment by bertradio** [comment]
I can confirm this problem on Linux Mint 19.3. Attached is what I get when I type firejail firefox on the command line.
[Firfox 82 issue.txt](https://github.com/netblue30/firejail/files/5410894/Firfox.82.issue.txt)
Also when I download and install the latest firejail firejail_0.9.64rc1_1_amd64.deb I still see 0.9.59 when I type firejail --version.

**Comment by kinglike1337** [comment]
They released a new update and Firefox can now be started using firejail again.
The script is still calling dpkg-query, but the error is now ignored and the version is defaulting to 0.

**Comment by bertradio** [comment]
Update of firejail or firefox?

**Comment by reinerh** [comment]
@bertradio Please update Firefox.
Closing this issue, as it has been fixed in Mint.

**Comment by bertradio** [comment]
Got it. Thanks.

**Comment by Wolf-Italy** [comment]
Sender: Gianpietro.
---
The problem has been solved.
---
I thank all the Users who contributed.
