### ISSUE TITLE
Widevine/DRM broken with firejail 0.9.64 in browsers

### ISSUE THREAD

**Issue by cjsthompson** [netblue30/firejail#3681]
Widevine (netflix) no longer works with Brave (1.15.75) after upgrading to firejail 0.9.64rc1-2 (arch linux). Works fine when starting brave without firejail or with firejail --noprofile /usr/bin/brave.

```
[242:1:1020/162026.705732:ERROR:cdm_module.cc(139)] CDM at /home/bla/.config/BraveSoftware/Brave-Browser/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so could not be loaded.
[242:1:1020/162026.705998:ERROR:cdm_module.cc(140)] Error: /home/bla/.config/BraveSoftware/Brave-Browser/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so: cannot open shared object file: Operation not permitted
```

**Comment by SkewedZeppelin** [comment]
Do you have
browser-allow-drm yes
in your
/etc/firejail/firejail.config ?

**Comment by cjsthompson** [comment]
Nope, and enabling that fixes the problem. Thanks for the hint.

**Comment by rusty-snake** [comment]
FYI: https://github.com/netblue30/firejail/pull/3390

**Comment by cjsthompson** [comment]
That explains why it was working until I upgraded I guess.

**Comment by toby63** [comment]
Is it also possible to activate this via a command flag?
(e.g. `firejail --browser-allow-drm PROGRAM`)

**Comment by rusty-snake** [comment]
```console
$ grep BROWSER_ALLOW_DRM /etc/firejail/*.profile
/etc/firejail/chromium-common.profile:?BROWSER_ALLOW_DRM: ignore noexec ${HOME}
/etc/firejail/ephemeral.profile:?BROWSER_ALLOW_DRM: ignore noexec ${HOME}
/etc/firejail/firefox-common.profile:?BROWSER_ALLOW_DRM: ignore noexec ${HOME}
/etc/firejail/midori.profile:?BROWSER_ALLOW_DRM: ignore noexec ${HOME}
/etc/firejail/otter-browser.profile:?BROWSER_ALLOW_DRM: ignore noexec ${HOME}
$ firejail --ignore='noexec ${HOME}' firefox
```

**Comment by toby63** [comment]
Interesting, thx.
Do I interpret this correctly that the DRM plugin wants to take a look in my home folder?

**Comment by rusty-snake** [comment]
It will get installed in your home folder, therefore you need to mount it `exec`.

**Comment by toby63** [comment]
> It will get installed in your home folder, therefore you need to mount it `exec`.

I see, and I guess it can't be further limited?

**Comment by rusty-snake** [comment]
Actaully you could `noexec` every directory in `firejail --ignore=private-bin --profile=firefox ls -a $HOME` except for `.mozilla`, however a `mkdir $HOME/this_dir_is_exec` inside the sandbox is possible.
