### ISSUE TITLE
mps-youtube needs lua

### ISSUE THREAD

**Issue by m0rr1gan** [netblue30/firejail#3686]
**Bug and expected behavior**
mpsyt errors out when starting

**No profile and disabling firejail**
mpsyt works file with `firejail --noprofile mpsyt`

**Reproduce**
1. Run in bash `firejail mpsyt`
2. See error `mpv: error while loading shared libraries: liblua5.2.so.5.2: cannot open sharefile: Permission denied` followed by python Traceback

**Environment**
Arch Linux: 5.9.1-arch1-1 
Firejail:
firejail version 0.9.64

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

**Additional context**
Adding "include allow-lua.inc" to /etc/firejail/mpsyt.profile fixes the issue.

**Checklist**
 - [x] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] Programs needed for interaction are listed in the profile.
 - [x] A short search for duplicates was performed.
 - [x] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.

**Comment by m0rr1gan** [comment]
Permission denied to make a PR, have one ready.

**Comment by glitsj16** [comment]
@m0rr1gan Can you confirm it works when adding the below to the profile:
```
# Allow lua (blacklisted by disable-interpreters.inc)
include allow-lua.inc
```

**Comment by rusty-snake** [comment]
> Permission denied to make a PR, have one ready.

You should be able to make a PR. How do you tried (app, comman-line, website)?

----

@glitsj16 

> **Additional context**
> Adding "include allow-lua.inc" to /etc/firejail/mpsyt.profile fixes the issue.

**Comment by m0rr1gan** [comment]
> @m0rr1gan Can you confirm it works when adding the below to the profile:
> 
> ```
> # Allow lua (blacklisted by disable-interpreters.inc)
> include allow-lua.inc
> ```

Yes, it works when adding those two lines.

**Comment by m0rr1gan** [comment]
> > Permission denied to make a PR, have one ready.
> 
> You should be able to make a PR. How do you tried (app, comman-line, website)?
> 
> @glitsj16
> 
> > **Additional context**
> > Adding "include allow-lua.inc" to /etc/firejail/mpsyt.profile fixes the issue.

I got permission denied when trying to push my branch.
