### ISSUE TITLE
DBus user socket not found Parabola OpenRC Iceweasel

### ISSUE THREAD

**Issue by RefinedAnarchy** [netblue30/firejail#3689]
**Bug and expected behavior**
- Describe the bug.
- What did you expect to happen?
Firejail would read profiles when launched then says DBus user socket not found (dbus-daemon is running) and no proxies specified

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal?
- What changed calling the program by path (check `which <program>` or `firejail --list` while the sandbox is running)?
Both launches fine

**Reproduce**
Launch Iceweasel
Fails to launch

**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`, `screenfetch` or `cat /etc/os-release`)
 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`) 
Parabola OpenRC with linux-libre-lts kernel, latest updates
Firejail 0.9.64

**Checklist**
 - [:white_check_mark:] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [:white_check_mark:] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [:white_check_mark:] Programs needed for interaction are listed in the profile.
 - [:white_check_mark:] A short search for duplicates was performed.
 - [N/A] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.

<details><summary> debug output </summary>

```
Found iceweasel.profile profile in /etc/firejail directory
Reading profile /etc/firejail/iceweasel.profile
Found firefox.profile profile in /etc/firejail directory
Reading profile /etc/firejail/firefox.profile
Found whitelist-usr-share-common.inc profile in /etc/firejail directory
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Found firefox-common.profile profile in /etc/firejail directory
Reading profile /etc/firejail/firefox-common.profile
Found disable-common.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-common.inc
Found disable-devel.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-devel.inc
Found disable-exec.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-exec.inc
Found disable-interpreters.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-interpreters.inc
Found disable-programs.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-programs.inc
Found whitelist-common.inc profile in /etc/firejail directory
Reading profile /etc/firejail/whitelist-common.inc
Found whitelist-var-common.inc profile in /etc/firejail directory
Reading profile /etc/firejail/whitelist-var-common.inc
conditional BROWSER_DISABLE_U2F, nou2f
conditional BROWSER_DISABLE_U2F, private-dev
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
DISPLAY=:0 parsed as 0
DBus user socket was not found.
starting xdg-dbus-proxy
sbox exec: /usr/bin/xdg-dbus-proxy --fd=8 --args=9
Dropping all capabilities
Drop privileges: pid 5403, uid 1000, gid 1000, nogroups 1
No supplementary groups
No proxies specified

```

</details>

**Comment by rusty-snake** [comment]
As a workaround `dbus-user none` might work.

What's the output of `echo $DBUS_SESSION_BUS_ADDRESS`?

**Comment by RefinedAnarchy** [comment]
> As a workaround `dbus-user none` might work.
It does
> What's the output of `echo $DBUS_SESSION_BUS_ADDRESS`?
Nothing

**Comment by rusty-snake** [comment]
Where does it listen? /run/user/<UID>/bus?

**Comment by rusty-snake** [comment]
@RefinedAnarchy does the solution from #3769 work for you too?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
