### ISSUE TITLE
src/man/firejail-config.txt is missing, causing a make error when building from git

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#369]
Hi, https://github.com/netblue30/firejail/commit/c07e4d109fecacfa96e0e14e2b470895d9629574 looks incomplete, causing a make error when building firejail from git:

$ make
...
./mkman.sh 0.9.39 src/man/firejail.txt firejail.1
./mkman.sh 0.9.39 src/man/firemon.txt firemon.1
./mkman.sh 0.9.39 src/man/firejail-profile.txt firejail-profile.5
./mkman.sh 0.9.39 src/man/firejail-login.txt firejail-login.5
make: *** No rule to make target 'src/man/firejail-config.txt', needed by 'firejail-config.5'.  Stop.

Please ignore if this is due to workflow timing and I got caught by building too soon when other commits are awaiting implementation... Just wanted to let you know.

**Comment by netblue30** [comment]
Fixed, thanks!
