### ISSUE TITLE
Ampersands are not handled correctly when passed to "bash -c"

### ISSUE THREAD

**Issue by blueyed** [netblue30/firejail#37]
The following should pass "http://example.com/?foo&bar" to firefox:

    % firejail --debug /usr/bin/firefox http://example.com/\?foo\&bar
    …
    Starting /usr/bin/firefox http://example.com/?foo&bar 
    execvp argument 0: /bin/bash
    execvp argument 1: -c
    execvp argument 2: /usr/bin/firefox http://example.com/?foo&bar 
    Child process initialized
    /bin/bash: bar: command not found

    parent is shutting down, bye...

**Comment by pmillerchip** [comment]
```
$ firejail --debug /usr/bin/firefox http://example.com/\\\?foo\\\&bar
...
Starting /usr/bin/firefox http://example.com/\?foo\&bar --new-instance 
execvp argument 0: /bin/bash
execvp argument 1: -c
execvp argument 2: /usr/bin/firefox http://example.com/\?foo\&bar --new-instance 
Child process initialized
```

**Comment by pmillerchip** [comment]
And if you don't like specifying three backslashes, you can do it with single backslashes (like your example) with this:

```
$ firejail --debug --shell=none /usr/bin/firefox firefox http://example.com/\?foo\&bar --new-instance
...
User namespace (noroot) installed
execvp argument 0: /usr/bin/firefox
execvp argument 1: firefox
execvp argument 2: http://example.com/?foo&bar
execvp argument 3: --new-instance
Child process initialized
```

**Comment by pmillerchip** [comment]
If you're using the latest version of firejail from Github, the command is now:
```
firejail --debug --shell=none /usr/bin/firefox http://example.com/\?foo\&bar
```

**Comment by netblue30** [comment]
Yes, --shell=none is the solution. It was suggested by a an user trying to pass all kind of arguments form a shell script.
