### ISSUE TITLE
Firefox can't find its profile after creating symlink for running sandboxed in new session

### ISSUE THREAD

**Issue by RonCam** [netblue30/firejail#370]
[In this thread](https://github.com/netblue30/firejail/issues/359), I got as far as creating symlinks by entering in terminal:

> $ sudo ln -s /usr/bin/firejail /usr/local/bin/firefox

But then, there was an error message on Firefox's first run -- can't find its profile, or something to that effect.  It came and went before I could select and copy its exact text.  

Then on the second run, Firefox appears to be reconfiguring itself. I think this is what's happening, but not really certain.

Is Firejail setting up a new Profile inside a sandbox?  If this is a yes, then might changes to the Profile be lost, whenever the box is 'dumped'?

What's considered normal operation for Firejail -- and how can I get back to the way it first worked, when I had to edit the command to run Firefox?

**Comment by chiraag-nataraj** [comment]
> What's considered normal operation for Firejail -- and how can I get back to the way it first worked, when I had to edit the command to run Firefox?
To get back the way it first worked (i.e. you had to explicitly invoke `firejail firefox`), simply remove the link in `/usr/local/bin`.

As for Firefox saying it can't find its profile and whether or not it's reconfiguring itself, there's an easy way to determine that:
1) Open Firefox within firejail
2) Edit the toolbar or menu or something and install an addon
3) Close and reopen Firefox and see if those changes stuck
If the changes stuck, there's some other issue going on. If they didn't stick, then Firefox is resetting each time you open it.

**Comment by netblue30** [comment]
Or add a new bookmark and if remains there.

**Comment by RonCam** [comment]
Thanks -- I just now saw that there had been replies, so please keep the thread open because I'd like have KDE restarting Firefox properly -- that is, to restart it with full sandbox protection.

**Comment by netblue30** [comment]
Sure, no problem.

**Comment by RonCam** [comment]
OK, I have some time now.  I've just renamed the firefox link in usr/local/bin to backuplink-firefox and will restart KDE and confirm that normal operation has returned, before going through the above troubleshooting procedures.

**Comment by RonCam** [comment]
Before trying the symbolic link again, I thought I would would approach KDE's 'Workspace' forum (Session Management falls into that category) with a link back to this thread showing what was suggested here, with the hope that the folks who are more closely acquainted with that particular environment might either tell me just to 'do' the link again, or come up with another idea.

[The resulting reply](https://forum.kde.org/viewtopic.php?f=66&t=131789&p=354082#p354037) raises two points: first, programs ideally inform the Session Manager how they are supposed to restart, and second, for those that do not, a work-around is offered.  

Take a look at the thread starting at the provided link, and see what you think.  If it works, this could be useful to other Firejail users.

**Comment by netblue30** [comment]
I just did a test on a CentOS 6 with KDE installed, and is working fine. Firefox is configured as a symbolic link in /usr/local/bin:
`````
$ ls -l /usr/local/bin
lrwxrwxrwx 1 root root     17 Mar 26 08:50 evince -> /usr/bin/firejail
lrwxrwxrwx 1 root root     17 Mar 26 08:50 fbreader -> /usr/bin/firejail
lrwxrwxrwx 1 root root     17 Mar 26 08:50 firefox -> /usr/bin/firejail
`````
I log out and log in again and Firefox is still there, running in a firejail sandbox.

**Comment by RonCam** [comment]
Thanks for going to the trouble of testing this on a working KDE installation.  I will give it another 'shot' tomorrow, because if it works for you, then I must have made some error.  I'll see if I can duplicate your listing on my setup, to make sure the link is going to the right spot.
