### ISSUE TITLE
Firefox native messaging regression in 0.9.62.4 -> 0.9.64rc1

### ISSUE THREAD

**Issue by cinnaboot** [netblue30/firejail#3701]
When upgrading to firejail 0.9.64rc1, the firefox extension https://github.com/woodruffw/ff2mpv breaks. 
It makes use of https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging to talk to other native applications.

In firefox.local, I have
`# Python 3`
`noblacklist ${PATH}/python3*`
`noblacklist /usr/include/python3*`
`noblacklist /usr/lib/python3*`
`noblacklist /usr/lib64/python3*`
`noblacklist /usr/local/lib/python3*`
`noblacklist /usr/share/python3*`

After upgrading to 1.9.64rc1 (and in 1.9.64), I get the following in strace:
`[pid   261] execve("/home/user/.mozilla/ff2mpv.py", ["/home/user/.mozilla/ff2mpv.py", "/home/user/.mozilla/native-mes"..., "ff2mpv@yossarian.net"], 0x7f9a121b4c00 /* 86 vars */) = -1 EACCES (Permission denied)`

firejail --noprofile does work too

Do I need to add some more options for the new DBus filtering maybe?

Forgot to add, this is on Arch Linux

**Comment by rusty-snake** [comment]
Add `ignore noexec ${HOME}` to your firefox.local.

In 0.9.62 was `ignore noexec ${HOME}` by default set even it shouldn't.

**Comment by cinnaboot** [comment]
Thanks, that helped.
I ended up needing to add a bunch of stuff from mpv.profile to make it go also:

```
ignore noexec ${HOME}

# copy firejail config parts from mpv.profile
noblacklist ${HOME}/.config/mpv
noblacklist ${HOME}/.config/youtube-dl
noblacklist ${HOME}/.netrc

include allow-lua.inc
include allow-python3.inc
mkdir ${HOME}/.config/mpv
mkdir ${HOME}/.config/youtube-dl
mkfile ${HOME}/.netrc
whitelist ${HOME}/.config/mpv
whitelist ${HOME}/.config/youtube-dl
whitelist ${HOME}/.netrc
whitelist /usr/share/lua
whitelist /usr/share/lua*
whitelist /usr/share/vulkan

private-bin env,mpv,python*,waf,youtube-dl
```
