### ISSUE TITLE
Does sandboxing with firejail works with spack package manager applications?

### ISSUE THREAD

**Issue by Joe23232** [netblue30/firejail#3706]
There is this [spack](https://spack.io/) package manager that is kinda like `flatpak` and `appimage` where the package manager is portable, and works on other Linux distros.

My question is would `firejail` work with `spack` applications?

**Comment by rusty-snake** [comment]
No one know. You need to try it. How does spack work?

**Comment by Joe23232** [comment]
I have no idea how `spack` works, I am sorry :(

**Comment by netblue30** [comment]
It should work, there is nothing in firejail to prevent a package manager from running.

Try to bring it in manually from git and compile it. Then try "firejail firefox" and take a look in the browser to "/home/username" directory, you should have there only Downloads and some config files.

**Comment by Joe23232** [comment]
Ok sure I will give it a trym thanks then :)

**Comment by rusty-snake** [comment]
Closing here. Fell free to post your findings.

**Comment by Joe23232** [comment]
Sure then :)
