### ISSUE TITLE
'make test' errors on tests not included in release tarball

### ISSUE THREAD

**Issue by hlein** [netblue30/firejail#3712]
**Bug and expected behavior**
- `make test` produces some errors because `Makefile.in`'s default `test` target includes `test-private-lib` and `test-fnetfilter`; the release tarball has no such subdirectories under `test/`.
- Those are present in the git repo, but not in the release tarballs; `Makefile.in`'s `DISTFILES_TEST=` enumerates `test/` dirs to package, excluding those two.
- The right/expected behavior would be some combination of 1) including more `test/` subdirs in release tarballs, 2) pruning the list of `test-*` targets included in the default `test:` target in `Makefile.in`, 3) checking for the presence of, and gracefully handling the lack of, individual `test/` subdirs.

**Reproduce**
1. unpack tarball such as `firejail-0.9.64.tar.xz`
2. configure and compile
3. run `make test`
4. Errors such as:
```
cd test/private-lib; ./private-lib.sh | grep TESTING
...
/bin/sh: line 0: cd: test/private-lib: No such file or directory
/bin/sh: ./private-lib.sh: No such file or directory
...
cd test/fnetfilter; ./fnetfilter.sh | grep TESTING
...
/bin/sh: line 0: cd: test/fnetfilter: No such file or directory
/bin/sh: ./fnetfilter.sh: No such file or directory
...
make: *** [Makefile:232: test-private-lib] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:265: test-fnetfilter] Error 1
```

**Environment**
 - Gentoo Linux
 - firejail-0.9.64

**Comment by netblue30** [comment]
Thanks for the bug, should be fixed now.

**Comment by hlein** [comment]
Awesome, thanks!
