### ISSUE TITLE
Filezilla profile does not allow to open HOME/.ssh folder for using keys in OpenSSH/SFTP connections

### ISSUE THREAD

**Issue by MiltosKoutsokeras** [netblue30/firejail#3722]
The Filezilla profile does not allow to open HOME/.ssh folder for using keys in OpenSSH/SFTP connections.

**Bug and expected behavior**
- The Filezilla profile in `/etc/firejail/filezilla.profile` does not allow the access to the OpenSSH client folder **HOME/.ssh**.
- What did you expect to happen? Since OpenSSH saves by default the client configuration and keys to **HOME/.ssh** I was expecting the profile of the program to have this path in the `noblacklist` section.

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal? Works as expected as the directory is not forbidden.
- What changed calling the program by path (check `which <program>` or `firejail --list` while the sandbox is running)? 
Running the program without any path wields:
```
<Process ID>:<User name>::/usr/bin/firejail /usr/bin/filezilla
```
`which filezilla` wields `/usr/local/bin/filezilla` as expected. 

**Reproduce**
1. Run in bash `firejail filezilla`
2. You cannot set keys from `HOME/.ssh` and also cannot create any new site as a popup is always thrown due to the access problem of your current sites. 

**Environment**
 - Arch Linux
 - Firejail version 0.9.64

**Additional context**
The problem can be worked around either by disabling the Filezilla profile or putiing `noblacklist ${HOME}/.ssh` to the profile.

**Checklist**
 - [x] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [ ] Programs needed for interaction are listed in the profile.
 - [x] A short search for duplicates was performed.
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.

<details><summary> debug output </summary>

```
Not available
```

</details>

**Comment by glitsj16** [comment]
@MiltosKoutsokeras Thanks for reporting this!

**Comment by MiltosKoutsokeras** [comment]
Glad I helped. I suppose the Filezilla profile is already updated in upstream.
