### ISSUE TITLE
Don't correct fonts and theme styles in openSUSE KDE

### ISSUE THREAD

**Issue by IlyaIndigo** [netblue30/firejail#3728]
Add please for correct display fonts and theme styles in openSUSE KDE.
whitelist-common.inc  ---> whitelist ${HOME}/.config/qtcurve
whitelist-usr-share-common.inc  ---> whitelist /usr/share/fonts-config

**Comment by rusty-snake** [comment]
thanks for reporting

**Comment by IlyaIndigo** [comment]
Please add more to fix directories in open/save dialogs.
whitelist-common.inc ---> whitelist ${HOME}/.config/QtProject.conf

**Comment by IlyaIndigo** [comment]
Thank you! :-)
