### ISSUE TITLE
"Process Tree"-tab in firetools is empty - firejail seems to be responsible

### ISSUE THREAD

**Issue by Rosika2** [netblue30/firejail#3729]
**Environment**
 - Linux distribution and version Lubuntu 18.04.5. LTS, 64 bit
 - firejail version 0.9.64
 - firetools --version 0.9.62

Hi altogether,

I posted this very problem on https://github.com/netblue30/firetools/issues/53 but it seems it has something to do with firejail rather than firetools.
Therefore I will try my luck here:

So this is basically a re-post but pretty much sums up what I came up with so far:

I´ve noticed that clicking on "Tools" in the firetools context-menu and then clicking on a certain PID
produces the overview of that process alright.
But when clicking on "Process Tree" the resulting window remains empty.

The other tabs seem to work alright; it´s just the "Process Tree" tab.

I assume this has something to do with the latest firejail update although I may be wrong there.

Currently I´m using firejail version 0.9.64. I updated only recently. The former firejail version didn´t display that behaviour.
Firetools version is 0.9.50-1

Any ideas what can be done done about it?

UPDATE

Hi again,

I just updated my firejail installation in my virtual machine (BodhiLinux).
Before doing that I checked how it dealt with the described "problem".

So now I can definitely say that firejail version 0.9.62.4 displayed all the processes in firetool´s "Process Tree" whereas
firejail version 0.9.64 leaves the tab completely empty.

So this has something to do with the new firejail version.

Hi once more,

I´ve just installed the latest firetools version 0.9.62 in order to find out whether this one works with firejail 0.9.64.
Result: the problem remains. Again firetool´s "Process Tree" tab remains empty. So it seems to be an issue with firejail rather than firetools.

Does anyone have any ideas?

Thanks a lot in advance.

Greetings
Rosika

**Comment by netblue30** [comment]
Changes in the latest version of firejail will prevent it from working. A new firetools version is coming out in a few days. The fix is already on github for firetools.

**Comment by Rosika2** [comment]
@netblue30:
Thanks for clarifying the matter.
Good to know the new firetools version will take care of the problem.

Many greetings
Rosika
