### ISSUE TITLE
Is it unsafe if I run Firejail with --no-sandbox?

### ISSUE THREAD

**Issue by jmtb28** [netblue30/firejail#3730]
Example: `$ firejail --noprofile --appimage app.AppImage --no-sandbox`

**Comment by rusty-snake** [comment]
You talk about the `--no-sandbox` of chrom*? AppImages have no sandbox.

Pros on disable internal sandboxes of programs:
- You can have tighter firejail options (e.g. disallow `chroot` (firefox), set `nonewprivs` (chrom* sometimes))
- You are able to use firejail (e.g. evolution or other software with bwrap sandboxes w/o firejail integration)

Cons of disable internal sandboxes of programs:
- A program can apply even more tight sandboxs to parts of it (e.g. web-content processes can be run w/o any file-system access while the config system needs write access to the filesystem)

My opinion: never disable internal sandboxes

**Comment by jmtb28** [comment]
> You talk about the `--no-sandbox` of chrom*? AppImages have no sandbox.

Yes I'm exactly referring to that and I forgot to specify that the AppImage application that I'm using is Electron-based. So my question is based around that type of AppImage application.
