### ISSUE TITLE
Is it possible through firejail to make available what the launched user is not available?

### ISSUE THREAD

**Issue by IlyaIndigo** [netblue30/firejail#3731]
Is it possible through firejail to make available what the launched user is not available?

The idea is to protect the profile with all firefox passwords "~ / .mozilla" from itself and any scripts and programs running from my user, but if I run firefox through firejail (suid is available) then firefox could access my profile which I do not have.

**Comment by IlyaIndigo** [comment]
A script immediately comes to mind that then the script can create a config and access any file on the computer.
But you can restrict such an option, or so that it is only in /etc, or the configuration file containing such an option must be owned by root with privileges 0600, otherwise it is ignored or the config is completely rejected.

**Comment by rusty-snake** [comment]
You could use firejail as login-shell and add such blacklist. You would then need a program outside this user-sandbox to start firefox. However, wayland does not use a shell and systemd/logind too IIRC.

I think SELinux would be good for that.

**Comment by IlyaIndigo** [comment]
Thank you, I see.
