### ISSUE TITLE
telegram.profile need netlink protocol

### ISSUE THREAD

**Issue by IlyaIndigo** [netblue30/firejail#3733]
When running telegram via firejail, it issues a warning.
Could not create AF_NETLINK socket (Operation not supported)
Please change telegram.profile to enable netlink protocol.

-protocol unix,inet,inet6
+protocol unix,inet,inet6,netlink

**Comment by glitsj16** [comment]
Duplicate of #3614.

You can make the needed change in a telegram.local file until your OS packages the firejail version that has that option.

**Comment by IlyaIndigo** [comment]
Thank you!
