### ISSUE TITLE
There is no sound in telegram via alsa (needs "alsa" and "group" for the "private-etc" option).

### ISSUE THREAD

**Issue by IlyaIndigo** [netblue30/firejail#3737]
Please add to your telegram profile, "alsa" and "group" for the "private-etc" option.
telegram.profile
-private-etc ca-certificates,crypto-policies,fonts,ld.so.cache,localtime,machine-id,pki,pulse,resolv.conf,ssl
+private-etc alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,pki,pulse,resolv.conf,ssl

Yes, oddly enough, but telegram via alsa needs /etc/group, presumably to make sure that the current user is a member of the audio group.
Without /etc/group, when trying to play sound, it gives an error:
ALSA lib pcm_direct.c:2014:(snd1_pcm_direct_parse_open_conf)
The field ipc_gid must be a valid group (create group audio)..

**Comment by glitsj16** [comment]
Thanks!

**Comment by IlyaIndigo** [comment]
:Thank you! :-)
