### ISSUE TITLE
Public gpg key & Signature

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3745]
Was wondering where is @netblue30 's public key so i can verify the files? or whoever is signing them?  Havent been able to find it.

Also, is it possible to also sign the source files tar.gz as well ?

**Comment by glitsj16** [comment]
That's indeed a bit burried. You can find it on the project site under the 'Downloads' section: https://firejail.wordpress.com/download-2/.

> Also, is it possible to also sign the source files tar.gz as well ?

Probably pinged the correct person on that one ;-)

**Comment by rusty-snake** [comment]
> Also, is it possible to also sign the source files tar.gz as well ?

"Source Code (zip)" and "Source Code (tar.gz)" are auto-generated by :octocat: . However there is a signed tar.xz.

**Comment by svc88** [comment]
> "Source Code (zip)" and "Source Code (tar.gz)" are auto-generated by :octocat: . However there is a signed tar.xz.

Ah ok, thank you

Also, would be better to show where to find the public key for other users on the Github page too.

**Comment by netblue30** [comment]
This guy has an interesting way of doing it: he grabs the public key form the MIT server and adds it to his keyring:

https://null-byte.wonderhowto.com/how-to/locking-down-linux-using-ubuntu-as-your-primary-os-part-3-application-hardening-sandboxing-0185710/

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
