### ISSUE TITLE
Arch Linux: firejail --x11 kills X server on exit

### ISSUE THREAD

**Issue by fd0** [netblue30/firejail#375]
Hi, thanks for writing firejail!

When using `--x11` to start a separate X server for a program, exiting the program also kills the normal X server so my session is terminated. This seems to be a bug.

I can reproduce this on Archlinux with firejail compiled from git (`r712.431d39d-1`) and `xpra-winswitch` version 0.16.2-1.

Is there anything I can do to help solving this bug?

**Comment by netblue30** [comment]
So far I couldn't get it to run at all with xpa-winswitch on my Arch box. I'll try to look into it.

Something to keep in mind: never run xpra as root, it will mess things up big time. After running xpra as root and before you log out from your session, make sure ~/.Xauthority file is still owned by your user. Somehow xpra makes it owned by root, and next time when you start your computer you won't be able to login.

**Comment by fd0** [comment]
Is there a reason you chose Xpra over Xephyr? Thinking about it, Xephyr seems to be the more obvious choice...

**Comment by netblue30** [comment]
You can use Xephyr right now:
`````
$ Xephyr -ac -br -noreset -screen 800x600 :22 &
$ DISPLAY=:22 firejail --net=eth0 --blacklist=/tmp/.X11-unix/x0 firefox
`````
I am running it on display :22, and I disable display :0 sockets. A nice touch would be to also start a light window manager such as OpenBox on display :22 in order to be able to move and resize the window.

I'll look into bringing Xephyr support in, thanks for the idea.

**Comment by netblue30** [comment]
I added support for Xephyr (--x11=xephyr)
