### ISSUE TITLE
[Feature] different profiles/behavior per user?

### ISSUE THREAD

**Issue by hlein** [netblue30/firejail#3753]
This is a request for advice that might turn into a feature request. I'm probably not the first to ask, but I couldn't find a previous discussion on this.

I would like firejail to behave differently for different users. Does the profile syntax have support for testing the current user or group memberships, and enabling/disabling things based on that? If not, what would be some options to accomplish that, and/or features that would need to be added to firejail?

For instance, on Gentoo, builds are done as user portage. In order for that to work, it needs various things that other system users (including myself!) do not need, such as, `wget` needs to be able to write to `/var/cache/distfiles/`, pass ridiculously large environment variables (which currently requires changing `firejail.h` and recompiling, but that's another matter ;), and a few other things I'm still discovering. Meanwhile, users that run certain services could have their profiles restricted still further. On some multiuser systems, I might want to restrict some regular users more than others, etc.

I see `/etc/firejail/login.users`, that's not what I'm after, but I suppose something similar that applied extra or alternate profile-files any time a named user ran a program via firejail might do it.

I can see some workarounds with alternate paths for firejail symlinks (created by `firecfg --bindir` or similar), that get added to different users' PATHs based on dotfiles, etc., and/or multiple compiled copies of firejail that look in different `/etc/firejail/*/` subdirs, but that'd be pretty messy and require custom upkeep.

**Comment by rusty-snake** [comment]
You can create profile overrides or add profiles to `$HOME/.config/firejail`.

**Comment by hlein** [comment]
> You can create profile overrides or add profiles to `$HOME/.config/firejail`.

Duh, good call, that's a good start anyway; will be back if I run into things it isn't sufficient for.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
