### ISSUE TITLE
signal-desktop no longer works with notify-send?

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#3755]
Write clear, concise and in textual form.

**Bug and expected behavior**

On latest version of (version 0.9.64-2 on Arch Linux) and probably the past recent versions as of ~1 month ago, I am no longer seeing texts on my computer via notify-send. I am using the default /etc/firejail/signal-desktop.profile. Using signal-desktop without firejail (i.e. /usr/bin/signal-desktop instead of /usr/local/bin/signal-desktop), notify-send works as expected and I see texts on the computer via notify-send. Of course, I continue to see texts on the signal-desktop window--I just no longer see them via notify-send.

**Comment by rusty-snake** [comment]
Add this to your `signal-desktop.local`.
```
dbus-user filter
dbus-user.talk org.freedesktop.Notifications
ignore dbus-user none
```
