### ISSUE TITLE
w3m with w3m-img installed does not display images when on virtual console/framebuffer

### ISSUE THREAD

**Issue by hedgehog29** [netblue30/firejail#3761]
w3m with w3m-img installed does not display images when on virtual console/framebuffer

In order to make it work i had to add those three lines to w3m.profile or w3m.local :

ignore nogroups
ignore private-dev
ignore private-etc

First two are easy to understand, the w3m must use the video group, and must access framebuffer device. I don't know why it needs access to other files in /etc/ and I don't know which file it is.

Could this be added to w3m.profile please? Thanks

It might be possible to restrict private-etc to a wider set of files including the needed ones.

**Comment by rusty-snake** [comment]
Hi, you can use `firejail --build=w3m.profile w3m && grep private-etc w3m.profile` to get a `private-etc` line containing all files accessed (open, openat, access, ...) by w3m.

**Comment by hedgehog29** [comment]
This command results in this line:
private-etc hosts,mime.types,mailcap,terminfo,w3m,w3mconfig,zsh,login.defs,passwd,selinux,

After merging it with the one from /etc/firejail/w3m.profile, which gives:
private-etc resolv.conf,ssl,pki,ca-certificates,crypto-policies,hosts,mime.types,mailcap,terminfo,w3m,w3mconfig,zsh,login.defs,passwd,selinux,

it still does not work. It seems that w3m for some reason needs access to whole /etc/ directory, and this is not a good idea for web browser right?
