### ISSUE TITLE
Spotify 1.1.42.622 Hangs on Arch Linux

### ISSUE THREAD

**Issue by njfox** [netblue30/firejail#3765]
Launching spotify via firejail on archlinux causes it to hang after the spotify window opens. I see the following warnings/errors related to libcurl-gnutls.so.4, although I'm not sure if it's related to the issue:

```
Child process initialized in 570.30 ms
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)

(spotify:32): Gtk-WARNING **: 19:05:48.088: Unable to locate theme engine in module_path: "adwaita",
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
```

Any ideas on how to troubleshoot? 

**update**: Looks like the same warnings happen when launching without firejail, so they appear to be irrelevant. I tried commenting out `private opt spotify` but that didn't change anything.

**Comment by rusty-snake** [comment]
First try `firejail --noprofile /opt/spotify/spotify`, if that fails it will be hard to fix (if it is possible to fix).

Try `firejal --private-etc=ld.so.cache,ld.so.conf,ld.so.conf.d,ld.so.preload /opt/spotify/spotify`. If this did not help, try `firejail --ignore=private-etc /opt/spotify/spotify`. If it's still broken, copy /etc/firejail/spoify.profile to your home, open it in  a text editor and comment everything. Then uncomment it line for line and try `firejail --profile=~/spotify.profile /opt/spotify/spotify` to find the line(s) which cause this.

**Comment by njfox** [comment]
Thanks, `--noprofile` works fine, but `firejail --private-etc=ld.so.cache,ld.so.conf,ld.so.conf.d,ld.so.preload /opt/spotify/spotify` does not. It seems to be an issue with the GUI not updating, as I can click on the play button and music will play, but nothing in the window will animate when mousing over/clicking.

**Comment by rusty-snake** [comment]
I see no lines in spotify.profile who smile at me and say it's me, so the good old trial-and-error solution is probably the best. Is something related in the syslog? I think the most hangs are caused by seccomp, so you could try `firejail --ignore=seccomp /opt/spotify/spotify`.

**Comment by njfox** [comment]
`firejail --ignore=seccomp` fixes the issue. What does that mean for tuning the profile?

**Comment by rusty-snake** [comment]
If you have a AMD-GPU it's #3219, add `seccomp !kcmp` to your spotify.local if that's the case.

If not, run `journalctl --grep=SECCOMP --reverse` and look for spotify (`comm="spotify"` or `exec="/opt/spotify/spotify"`) then scroll to `syscall=NUMBER` in that line and run `firejail --debug-syscalls | grep NUMBER`. Now you can run `firejail '--seccomp=!SYSCALL /opt/spotify/spotify` to test.

**Comment by njfox** [comment]
Thanks! I do have an AMD GPU and `seccomp !kcmp` fixed it.
