### ISSUE TITLE
zathura does not work with ipc-namespace

### ISSUE THREAD

**Issue by ScoreUnder** [netblue30/firejail#3775]
**Bug and expected behavior**
`ipc-namespace` does not allow zathura to run.

**No profile and disabling firejail**
`ignore ipc-namespace` is sufficient to fix the issue, but more minimal profiles work for the same reason.

**Reproduce**
1. Run zathura under firejail
2. Observe the failure to launch, and the error:

```
(org.pwmt.zathura:12): Gdk-ERROR **: 16:50:29.070: The program 'org.pwmt.zathura' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 294 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

This also occurs with `--x11=xpra`, `--x11=xvfb`, and `--x11=xephyr`. `--x11=none` will not work because it requires X11, and `--x11=xorg` has never worked on my machine.

**Environment**
- zathura 0.4.7-1
- nvidia-dkms 455.38-1
- linux 5.9.3.arch1-1
- firejail 0.9.64-2

Debug output available if necessary but it doesn't describe the actual issue (the difference between `ignore ipc-namespace` and not amounts to order of profile loading, whether ipc namespaces are reported as enabled, mountpoint IDs, and the error output seen above).

**Comment by rusty-snake** [comment]
Thanks for reporting. `ipc-namespace` breaks some X-extensions and causes frequently issues with gui programs. That's why it should not be used in graphical profiles at all. (Under Wayland it works fine)
