### ISSUE TITLE
Google Chrome (wayland ozone) is broken

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#3783]
Fedora 33 on Haswell CPU & iGPU

Compiled form master today (last done over a month ago) and google chrome is broken, videos aren't played correctly and desync from audio.

noprofile fixes the problem.

The command used:

`firejail --disable-mnt --netns=custom --dns=1.1.1.1 --private=~/jailed/google_chrome google-chrome-stable --disable-webgl --enable-features=UseOzonePlatform --ozone-platform=wayland
`

Prior to the recompilation today it worked fine.

**Comment by rusty-snake** [comment]
Likely a regression from 594300374dc15bd704bcb1f2a98b17faef80aa79. However, the only effective change for google-chrome.profile was private-cache :confused: .

**Comment by rusty-snake** [comment]
I played a bit with ozone in brave, chromium-browser-privacy and vivaldi. AV worked fine in brave. However, I needed to allow the kcmp syscall (I set `seccomp-error-action kill`). Works `firejail '--seccomp=!chroot,!kcmp' …`?

For the record: Fedora 32; Mesa 20.2.3; Intel GPU; `secomp.drop kcmp` is only violated when using ozone, but not with the default X11 backend.
