### ISSUE TITLE
Two firejail related scripts.

### ISSUE THREAD

**Issue by hedgehog29** [netblue30/firejail#3789]
Recently, I came across those two scripts:
https://codeberg.org/rps/fireinvoke
https://codeberg.org/rps/fire-install

Those are not mentioned in the external projects list on firejail website.

**Comment by rusty-snake** [comment]
My projects (fjp,firejailed-tor-browser,firecg.py) are missing too :scream: :sob: :angry: :roll_eyes: .

**Comment by netblue30** [comment]
Thanks @hedgehog29, all fixed.

@rusty-snake where do you keep them?

**Comment by rusty-snake** [comment]
[firejailed-tor-browser](https://github.com/rusty-snake/firejailed-tor-browser): A HowTo run tor-browser under firejail, using a own extra hardened profile and providing scripts to automate this.

[fjp](https://github.com/rusty-snake/fjp) (https://rusty-snake.github.io/fjp/): "A handy command line program to work fast and straightforward with firejail profiles." For me a big help when writing locals and debugging profile issues. I plan a new release with compiled binaries this month (or early january).

[firecfg.py](https://github.com/rusty-snake/firecfg.py): question worthy if it should be added. Code-quality leaves a lot to be desired and documentation simply don't exists. It is the current result from my firecfg prototyping and experimenting this year (I wrote 4-5 (partial) firecfg implements to see what can be done better to integrate firejal and how it can be done). It has better control which programs are firejailed and where (e.g. $PATH, dot-desktop, ...) over multiple conf file. It has it's own dir in $PATH which is easier to maintain. It can be applied system-wide or per user. It can fix the session bus (systemd units and system-bus are planed). And has a better GNOME support.


BTW: There are at least 404 in the list.

**Comment by netblue30** [comment]
The first two are in.

> firecfg.py: question worthy if it should be added. 

I would say  we should bring it in our contrib section (https://github.com/netblue30/firejail/tree/master/contrib) and open it for other people to play with it.
