### ISSUE TITLE
xfce4-screenshooter - profile broken by `memory-deny-write-execute` 

### ISSUE THREAD

**Issue by itoffshore** [netblue30/firejail#3790]
```
LSB Version:    1.4
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux (Arch Linux)
Release:        rolling
Codename:       n/a

firejail version 0.9.64

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled
```
This bug could be due to my restricted environment (`hidepid` + `linux-hardened + apparmor`) - i.e a kernel with:
________
`# CONFIG_USER_NS_UNPRIVILEGED is not set`
_________
I was able to fix it by creating `/etc/firejail/xfce4-screenshooter.local` & adding:

`ignore memory-deny-write-execute`

**Comment by rusty-snake** [comment]
Thanks for reporting. https://github.com/netblue30/firejail/commit/458e2ad6b04bd2b77cd93f3cecd0f95e72d47bfa.

MDWE commonly breaks GUIs. GTK/GDKs Wayland implementation and a few other.

**Comment by itoffshore** [comment]
@rusty-snake  - I think it should be removed from it's profile as it is a GUI app

**Comment by rusty-snake** [comment]
Why should it be removed?

**Comment by itoffshore** [comment]
commenting it out as has been done in https://github.com/netblue30/firejail/commit/458e2ad6b04bd2b77cd93f3cecd0f95e72d47bfa has the same effect

Otherwise the app runs like:
![firejail-screenshooter](https://user-images.githubusercontent.com/1141947/101356931-adf6a280-3890-11eb-9ef5-862aa05c3422.png)
