### ISSUE TITLE
Get ride of all these u2f and drm issues

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3797]
I'm becoming quite annoyed by all those issues about u2f and drm in browsers or other common and easy to solve issues.

**Proposal**

We should provide a setup-script for new users. Example: https://gist.github.com/rusty-snake/17494a3ad9366ce46a6b2bcc4c46149b.

Usage:
```
wget -O- https://gist.githubusercontent.com/rusty-snake/17494a3ad9366ce46a6b2bcc4c46149b/raw/da671d6fe92b38179904f9bb8428eab030088859/firejail-welcome.sh | sh
```

_well you know `wget | sh` is :bomb: :stopwatch: :boom: ._

Dependencies:

bash, sed, coreutils, sudo, zenity

**Comment by SkewedZeppelin** [comment]
> We should provide a setup-script for new users.

Awesome script!
Push it to contrib?

**Comment by Norcoen** [comment]
As a non-user of firejail, looking around and finding this I would wish for a bit more details on the implications of this.

As far a I can tell, this basically allows new users to easily allow access to u2f and drm among other options, but it does not tell, what can of worms this might open

**Comment by rusty-snake** [comment]
Added a example on how details can look to browser-allow-drm. But I'm not the person for writing detailed and easy descriptions, so it's up to the community for now.

> Push it to contrib?

Yes, but which newbies will find it there?

**Comment by rusty-snake** [comment]
ok, let's add it to contrib and add it to https://firejail.wordpress.com/documentation-2/ >> I’ve just installed Firejail, now what?!

_Ideally this would also be added to wikis (archlinux, ubuntuusers, gentoo, debian, ...) and blog posts. But they still use default.profile instead of profile.template._
