### ISSUE TITLE
Viber appimage pausing firejail execution asking to replace mimeapps.list 'overriding mode 0664'

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#3799]
**Bug and expected behavior**
In $HOME, when running:
`firejail --appimage --profile="/usr/local/etc/firejail/Viber.profile" viber.AppImage`
it executes and pauses on the following question:
```
Reading profile /usr/local/etc/firejail/Viber.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-exec.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-passwdmgr.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Mounting appimage type 2
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Parent pid 25942, child pid 25945

**     Warning: dropping all Linux capabilities     **

Warning fcopy: skipping /etc/alternatives/orbd, cannot find inode
Warning fcopy: skipping /etc/alternatives/servertool.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/servertool, cannot find inode
Warning fcopy: skipping /etc/alternatives/tnameserv.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/tnameserv, cannot find inode
Warning fcopy: skipping /etc/alternatives/orbd.1.gz, cannot find inode
Warning: skipping asound.conf for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Warning: skipping proxychains.conf for private /etc
Private /etc installed in 17.96 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: not remounting /run/user/1000/gvfs
Warning: cleaning all supplementary groups
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Child process initialized in 143.46 ms
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
mv: replace '/home/test/.config/mimeapps.list', overriding mode 0664 (rw-rw-r--)?
```
After which i press enter and then it continues with this:
```
[20:48:1209/010618.546329:ERROR:address_tracker_linux.cc(152)] Could not create NETLINK socket: Operation not supported (95)
[20:53:1209/010618.570619:ERROR:udev_watcher.cc(48)] Failed to initialize a udev monitor.
```
Then it opens up normally, without any issues it seems.
But my question is, what is this and why does it ask it?
`mv: replace '/home/test/.config/mimeapps.list', overriding mode 0664 (rw-rw-r--)?`

Please note, that the other errors that continue **after** this
`[20:53:1209/010618.570619:ERROR:udev_watcher.cc(48)] Failed to initialize a udev monitor.`
are only Viber related errors, so ignore those if you try to reproduce this.

Please reproduce with Viber appimage from https://download.cdn.viber.com/desktop/Linux/viber.AppImage

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal?  It runs without the question
- What changed calling the program by path (check `which <program>` or `firejail --list` while the sandbox is running)? Nothing

**Reproduce**
1. Run in bash `firejail --appimage --profile="/usr/local/etc/firejail/Viber.profile" viber.AppImage`
2. See error `mv: replace '/home/test/.config/mimeapps.list', overriding mode 0664 (rw-rw-r--)?`
3. Press enter, it will continue and open up the program.
4. See rest of errors in the terminal

**Environment**
 - Linux distribution and version: Xubuntu 18.04
 - firejail version 0.9.64

<details><summary> debug output </summary>

```
Reading profile /usr/local/etc/firejail/Viber.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-exec.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-passwdmgr.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Mounting appimage type 2
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Parent pid 27664, child pid 27667

**     Warning: dropping all Linux capabilities     **

Warning fcopy: skipping /etc/alternatives/orbd, cannot find inode
Warning fcopy: skipping /etc/alternatives/servertool.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/servertool, cannot find inode
Warning fcopy: skipping /etc/alternatives/tnameserv.1.gz, cannot find inode
Warning fcopy: skipping /etc/alternatives/tnameserv, cannot find inode
Warning fcopy: skipping /etc/alternatives/orbd.1.gz, cannot find inode
Warning: skipping asound.conf for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Warning: skipping proxychains.conf for private /etc
Private /etc installed in 18.68 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: not remounting /run/user/1000/gvfs
Warning: cleaning all supplementary groups
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Child process initialized in 132.57 ms
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
mv: replace '/home/test/.config/mimeapps.list', overriding mode 0644 (rw-r--r--)? 
[20:51:1209/010932.512256:ERROR:address_tracker_linux.cc(152)] Could not create NETLINK socket: Operation not supported (95)
[20:54:1209/010932.535963:ERROR:udev_watcher.cc(48)] Failed to initialize a udev monitor.
```

</details>

**Comment by svc88** [comment]
>     1. "mv: replace '/home/test/.config/mimeapps.list', overriding mode 0664 (rw-rw-r--)?"
>        Viber tries to at it has handler for some mimetypes, but `~/.config/mimeapps.list` is read-only for security reasons.

Tries to what?   Is it trying to override the permissions of mimeapps?  What does pressing enter to this cmd do?



>     2\. "[20:48:1209/010618.546329:ERROR:address_tracker_linux.cc(152)] Could not create NETLINK socket: Operation not supported (95)
>         [20:53:1209/010618.570619:ERROR:udev_watcher.cc(48)] Failed to initialize a udev monitor."
>         `firejail --appimage --protocol=unix,inet,inet6,netlink --profile="/usr/local/etc/firejail/Viber.profile" viber.AppImage`

seems only `netlink` is missing from Viber.profile. Since i havent noticed any functionality issues when using Viber, is `netlink` really needed?

**Comment by rusty-snake** [comment]
> What does pressing enter to this cmd do?

Likely nothing, as it is made ro by firejail and not by filesystem.

**Comment by rusty-snake** [comment]
> Tries to what? Is it trying to override the permissions of mimeapps?

No, it tries to replace it.

> What does pressing enter to this cmd do?

Likely nothing, or at least nothing which affects files outside the sandbox.

> is netlink really needed?

If the error says it … Anyway, if nothing is broken w/o it it must not be added (but how do you know nothing is broken?).

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
