### ISSUE TITLE
telegram-desktop launch browser for open URL problem in openSUSE

### ISSUE THREAD

**Issue by IlyaIndigo** [netblue30/firejail#3805]
Needed to start the browser correctly (tested on firefox and chromium) in openSUSE Tumbleweed.
/etc/firejail/telegram.profile
-private-etc ca-certificates,crypto-policies,fonts,ld.so.cache,localtime,machine-id,pki,pulse,resolv.conf,ssl
+private-etc alternatives,alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,os-release,pki,pulse,resolv.conf,ssl,xdg

**Comment by glitsj16** [comment]
Thank you for reporting this!
