### ISSUE TITLE
Relationship between disable-mnt and disable-write.inc

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#3809]
I am wondering if I understand the difference/relationship between `disable-mnt` and (including) `disable-write.inc` correctly. The former blacklists /media, /mnt, /run/media and /run/mount access, while the latter makes those exact same directories read-only. Shouldn't it make sense to ONLY include `disable-write.inc` in profiles that DO NOT have `disable-mnt`?

If so, we might have to look at a few profiles that mix them up non-sensically, at least for me:

- BAD:
  - dbus-send.profile
  - notify-send.profile
  - qrencode.profile

- GOOD
  - eo-common.profile

**Comment by rusty-snake** [comment]
>  I am wondering if I understand the difference/relationship between disable-mnt and (including) disable-write.inc correctly. The former blacklists /media, /mnt, /run/media and /run/mount access, while the latter makes those exact same directories read-only.

Yup, that's it.

> Shouldn't it make sense to ONLY include disable-write.inc in profiles that DO NOT have disable-mnt?

This makes the progiles easier, as disable-write-mnt has no effect.

**Comment by glitsj16** [comment]
> This makes the progiles easier, as disable-write-mnt has no effect.

Makes more sense now. Thanks!
