### ISSUE TITLE
disable-devel.inc missing in the generic.profile

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#381]
Is it missing accidentally or is there a specific reason why you didn't include it?

**Comment by netblue30** [comment]
It blacklists perl, ruby and probably more in the future. It will not work for some programs.

**Comment by curiosity-seeker** [comment]
Thanks, I understand. But isn't that also true for the other .inc files?

**Comment by netblue30** [comment]
Sort of... For example ~/.ssh is blacklisted by default, ssh client will not work. Maybe we need to make profiles for ssh and other programs disabled by the regular blacklists.

**Comment by curiosity-seeker** [comment]
Yes, I've seen that you created/modified the .inc files. I guess we can close this issue.
