### ISSUE TITLE
Question: AppImage trust

### ISSUE THREAD

**Issue by mid-kid** [netblue30/firejail#3815]
AppImages are essentially a binary with a disk image attached. The default way to unpack them is to just run and trust this "runtime" binary. This essentially puts trust into this binary to not do anything bad, and has a similar issue as running `ldd` to inspect a glibc binary.

My question is mostly: What does firejail with the `--appimage` option do? Is this bootstrap/runtime binary ran at all, if so, is it ran sandboxed or unsandboxed? Or does firejail reimplement this?

**Comment by smitsohu** [comment]
Firejail doesn't use the AppImage runtime, it uses a simple reimplementation.

All AppImage code is executed in the sandbox, and that's the only possible way; everything else would defeat the very idea of a sandbox.

**Comment by mid-kid** [comment]
Thanks, I was worried for a second, since everything about the format is really opaque.
