### ISSUE TITLE
links with "&" are truncated

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#382]
Hi!

When I try to open a link from Thunderbird in Firefox, everything that comes after an `&` is discarded.
I have both Thunderbird and Firefox sandboxed which may be the reason why.

Can you please look into it?

**Comment by boltronics** [comment]
I have a similar issue which only started showing up recently. I have icedove in one jail, and firefox-esr in another. Any URL with the & character in it becomes \& (has a leading backslash) which causes most URLs to fail.

However if I right-click on the URL and copy it, and then Paste and Go into the firefox-esr URL bar, there is no problem.

**Comment by netblue30** [comment]
Fixed! Give it a try and I'll reopen the bug if necessary.

**Comment by boltronics** [comment]
For reference, closed with commit https://github.com/netblue30/firejail/commit/834c420f2f97e4bfa48c528380f2c18b0261a6e5.
