### ISSUE TITLE
Firefox doesn't recognize when network settings have changed

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#383]
I'm trying to figure out which file(s) I need to whitelist in /etc/ to enable Firefox to detect that the network settings have changed. I've whitelisted resolv.conf, hosts, and nsswitch.conf (because I thought it might help). Other applications like Skype seem to not have a problem despite having similarly restrictive profiles.
Here's my Firefox profile:
````
# Blacklist/Whitelist

blacklist /usr/local/bin
blacklist /usr/local/sbin
blacklist /media
blacklist /mnt
blacklist /boot
blacklist /ae108

whitelist ${HOME}/.mozilla
whitelist ${HOME}/Downloads/
whitelist ${HOME}/.pulse/
whitelist ${HOME}/.config/pulse/
whitelist ${HOME}/.config/gtk-3.0/
whitelist ${HOME}/.config/google-googletalkplugin/
whitelist ${HOME}/.config/fcitx/
whitelist ${HOME}/.gtkrc-2.0
whitelist ${HOME}/.gtkrc.mine
whitelist ${HOME}/.Xauthority
whitelist ${HOME}/PDF/

# Private directories

private-bin firefox.real,firefox,which,sh,dbus-launch,dbus-send,fcitx-dbus-watcher
private-etc hosts,passwd,mime.types,fonts/,mailcap,iceweasel/,xdg/,gtk-3.0/,resolv.conf,X11/,pulse/,alternatives/,localtime,nsswitch.conf
private-tmp

# Miscellaneous options

shell none
seccomp
noroot
caps.drop all
protocol unix,inet,inet6
````

**Comment by netblue30** [comment]
Your profile looks fine, how do you change network settings?

**Comment by chiraag-nataraj** [comment]
I use wicd network manager to connect and disconnect from networks.

**Comment by netblue30** [comment]
Maybe one of the lines in the profile file disables this functionality. You can start by commenting all the lines in the profile and bringing them back one by one.

**Comment by chiraag-nataraj** [comment]
Hmmm....it's hard to do that just because I don't often change wireless networks :tongue: Most likely it has something to do with `private-etc` or `private-bin`, but I'm not sure.

**Comment by netblue30** [comment]
I would disable private-bin and private-etc from the profile file, and in a separate terminal I would run "sudo firemon". This will list all the programs running in firejail sandboxes as they are started. Than I would go and play with the network. In case the problem is private-bin you'll get there new programs listed.
