### ISSUE TITLE
Question to bug #2101

### ISSUE THREAD

**Issue by dx-0** [netblue30/firejail#3831]
It seems like in Ubuntu 20.04 I'm also affected by bug  #2101 (which is solved). However, due to my limited technical background, I'm not sure what I have to do exactly to enable printing in evince again. I've read the documentation but did not understand everything. Could you maybe provide an a little more detailed explanation how to solve the problem? Thanks!

**Comment by rusty-snake** [comment]
Options from #2101 (choose 1 or 2):

1. Use only AppArmor and remove the firecfg symlink: `sudo rm /usr/local/bin/evince` (you need to run it again if you run `sudo firecfg` again)
2. Use only firejail. I have no knowledge of AA and how to disable a profile, someone else will need to post a command.

**Comment by dx-0** [comment]
Thanks. Option 1 worked for me. Here is a link for option 2 if someone is interested: https://help.ubuntu.com/community/AppArmor
