### ISSUE TITLE
what about snap app ?

### ISSUE THREAD

**Issue by fpusersuggest** [netblue30/firejail#3836]
Hello, I have two or three snap app that I'd like to run under firejail but oviously it doesn't work.
Is there any tutorial or howto to use it or I need to just make a request to create a new profile ?
The following is an example of an app that I'd like to run with firejail:

```
8:~$ which electron-mail 
/snap/bin/electron-mail
8:~$ ls -l /snap/bin/electron-mail 
lrwxrwxrwx 1 root root 13 nov 26 16:38 /snap/bin/electron-mail -> /usr/bin/snap
8:~$ firejail --noprofile /snap/bin/electron-mail
Parent pid 10437, child pid 10438
Child process initialized in 10.08 ms
2020/12/18 04:32:21.847524 system_key.go:154: cannot determine cgroup version: cannot determine filesystem type: cannot statfs path: permission denied
cannot create cgroup hierarchy /sys/fs/cgroup/devices/snap.electron-mail.electron-mail/: No such file or directory

Parent is shutting down, bye...
```

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/blob/f4f6767458208a127084e4c0103fab88761d9056/RELNOTES#L105

Snap (and flatpak) has it's own sandbox.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
