### ISSUE TITLE
[typo]  src/man/firecfg.txt uses FIREMON instead of FIRECFG

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#385]
Hi, a minor typo in https://github.com/netblue30/firejail/commit/c7f7ce488796d93597ad9612ce9be0c40dad74bb ..

$ cat src/man/firecfg.txt
[line 1] .TH FIREMON 1 "MONTH YEAR" "VERSION" "firecfg man page"

I assume FIREMON should be replaced with FIRECFG

**Comment by netblue30** [comment]
Fixed, thanks!
