### ISSUE TITLE
[Question] Is it possible to modify the profile while firejail is running?

### ISSUE THREAD

**Issue by Nathoufresh** [netblue30/firejail#3857]
Sorry if this question has already been asked.

A neat feature would be: when an app requires a permission, firejail suspend the subprocess and then a dialog appears "appname wants to access this permission" then you could choose from allow this time, allow permanently, etc... But it would need firejail to be able to modify the profile while it's already running. Is it feasible?

**Comment by rusty-snake** [comment]
> But it would need firejail to be able to modify the profile while it's already running. Is it feasible?

For filesystem (e.g. whitelist) permissions yes, for others like nonoewprivs no.

**Comment by Nathoufresh** [comment]
Tanks for your prompt answer!

For the permissions that cannot be changed on the go we could tell the user that we need to restart the app.
What would be the disadvantages of such a GUI interface?

**Comment by rusty-snake** [comment]
> What would be the disadvantages/problems of such a GUI interface?

1. Not all systems has a GUI. However as long as there would be something like `--static-permissions` to disable such prompts everything is fine.
2. Suspending a program is critical if this programs communicates with others.
3. How can we detect that a program wants to access to a certain file?

**Comment by Nathoufresh** [comment]
> How can we detect that a program wants to access to a certain file?

I don't know how firejail works internally. I thought there would be an obvious way to get that information in firejail maybe I should create a new program from scratch.. Thanks for your time.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
