### ISSUE TITLE
`firejail --list` shows nothing

### ISSUE THREAD

**Issue by Self-Perfection** [netblue30/firejail#3861]
Write clear, concise and in textual form.

**Bug and expected behavior**
`firejail --list` shows nothing (no error messages, nothing at all) regardless of existence of running firejail sandboxes.
It used to work about a year ago, with firejail 0.9.60. But does not show anything with current 0.9.64

**Environment**
```
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
$ firejail --version 
firejail version 0.9.64

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled
```
**Additional context**
I don't know how firejail lists active sandboxes. I suppose it somehow interacts with `/run/firejail` but I could not spot any differences in this aspect with another Ubuntu 20.04 system where `firejail --list` works.

**Checklist**
 - [x] The upstream profile (and redirect profile if exists) have no changes fixing it.
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] A short search for duplicates was performed.
 - [x] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [x] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.

**Comment by SkewedZeppelin** [comment]
> firejail --list shows nothing

Are you using hidepid?

**Comment by Self-Perfection** [comment]
@SkewedZeppelin Hi
Indeed I do use hidepid. But I am quite sure half a year ago hidepid was already enabled and `firejail --list` worked.

**Comment by rusty-snake** [comment]
Maybe `sudo firejail --list`?

**Comment by Self-Perfection** [comment]
`sudo firejail --list` does not show anything either.

But searching for "hidepid" gave me #1927 which is very much related. It gave me advice to try `firemon --list` and this command works and shows list of sandboxes. At least I have workaround now.

**Comment by smitsohu** [comment]
> Indeed I do use hidepid. But I am quite sure half a year ago hidepid was already enabled and firejail --list worked.

yeah, it's caused by a change in the kernel. It should be fixed in git master.

**Comment by Self-Perfection** [comment]
With firejail 0.9.64.4 and kernel 5.11.2-arch1-1 I now get expected output from `firejail --list`. Firemon stopped showing list but gives useful hint:
```
$ firemon --list
Error: /proc is mounted hidepid, you would need to be root to run this command
```

Seems OK to me and this issue seems to be resolved.
