### ISSUE TITLE
Firejail profile for VsCodium doesn't work: vscodium was renamed to codium

### ISSUE THREAD

**Issue by mYnDstrEAm** [netblue30/firejail#3871]
I had a problem of not getting updates for the way to get Visual Studio Code on Debian via a repository instead of the GitHub releases: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/50

I did not get any error or alike and "solved" it by going through that repo's guide in the readme again which I installed VsCodium another time, now not called vscodium but "codium" and the latest version (now I have two VSCodiums installed).

However, when I run `firejail --profile=/etc/firejail/vscodium.profile codium` I now get this error message:

```
Unable to write program user data.

Please make sure the following directories are writeable:

/home/username/.config/VSCodium
/home/username/.vscode-oss/extensions
/run/user/1000
```

I already created a /home/username/.config/firejail/code.local with:

```
noblacklist ${HOME}/.config/VSCodium
noblacklist ${HOME}/.vscode-oss/extensions
```

At least two issues remain:

* The vscodium profile (that's /etc/firejail/code.profile and /etc/firejail/vscodium.profile) seems to be broken/outdated
* How to solve the problem with /run/user/1000?

`echo $DBUS_SESSION_BUS_ADDRESS` returns `unix:path=/run/user/1000/bus`

Also from the default vscodium profile it looks like it's not possible to install extensions. Is that correct? If so that should be changed too but it would be a separate issue.

System: Debian10/KDE
Firejail: 0.9.64 (latest from backports)

**Comment by rusty-snake** [comment]
> Please make sure the following directories are writeable:
> /run/user/1000

I did not read futher, but `firejail --writable-run-user …` shoulde solve at least this message.

**Comment by mYnDstrEAm** [comment]
Reopening because if the VsCodium is now called codium the profile's name needs to be changed to be used automatically when running `firejail codium`. One could also just copy the vscodium.profile to codium.profile.

**Comment by rusty-snake** [comment]
> `FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/codium/chrome-sandbox is owned by root and has mode 4755.`
> 
> See here for what seems to be the best improvised solution for this currently; I'm not sure how this could be implemented here and if it needs to be as it also runs without --no-sandbox when not adding any parameters. That part is probably unrelated to firejail but please comment if you know a way to make firejail work when using --new-window)

See PRs #3688 and  #3807. _My_ suggestion `sysctl kernel.unprivileged_userns_clone=1`.

**Comment by rusty-snake** [comment]
> Reopening because if the VsCodium is now called codium the profile's name needs to be changed to be used automatically when running firejail codium.

We should add a redirect/alias profile for it.

**Comment by mYnDstrEAm** [comment]
Sounds good! `writeable-run-user` wasn't required.
Don't know about kernel.unprivileged_userns_clone - [it seems to be disabled for security reasons](https://security.stackexchange.com/questions/209529/what-does-enabling-kernel-unprivileged-userns-clone-do) and I don't know how it would be useful here.

**Comment by rusty-snake** [comment]
> Don't know about kernel.unprivileged_userns_clone - it seems to be disabled for security reasons and I don't know how it would be useful here.

Maybe read #3754.

**Comment by mYnDstrEAm** [comment]
> Is `/usr/bin/codium` a wrapper script for `/usr/share/codium/codium`?

It points to /usr/share/codium/bin/codium which is a very short wrapper script. Strangely if I read it right that script should only run `/usr/share/codium/codium`. The relevant part is:
```
if [ ! -L "$0" ]; then
	# if path is not a symlink, find relatively
	VSCODE_PATH="$(dirname "$0")/.."
else
	if command -v readlink >/dev/null; then
		# if readlink exists, follow the symlink and find relatively
		VSCODE_PATH="$(dirname "$(readlink -f "$0")")/.."
	else
		# else use the standard install location
		VSCODE_PATH="/usr/share/codium"
	fi
fi

ELECTRON="$VSCODE_PATH/codium"
```

**Comment by mYnDstrEAm** [comment]
There's probably some permissions set that allows /usr/bin/ but not /usr/share - `firejail --profile=/etc/firejail/vscodium.profile /usr/share/codium/codium` should work with the profile too.

**Comment by rusty-snake** [comment]
Just to be sure, `firejail --noprofile /usr/share/codium/codium` works?

**Comment by rusty-snake** [comment]
Any progress here?

**Comment by kmk3** [comment]
@rusty-snake commented [on Apr 6](https://github.com/netblue30/firejail/issues/3871#issuecomment-814170488):

> Any progress here?

I think I got it; will submit a PR later.

**Comment by kmk3** [comment]
Quoting the first post of the following discussion (as a sort of +1):

* <https://github.com/VSCodium/vscodium/discussions/776>

@henrythebuilder [on Jul 26](https://github.com/VSCodium/vscodium/discussions/776#discussion-3477542):

> Hi,
>
> Following the latest problems detected with marketplace ( #746 ), I tried to
> use Firejail to increase security but in my computer the default profile does
> not work, so I tried to create a new local profile following
> information/instructions on how to manage Chromium/Electron applications.
> Referring especially on [firejail repo](https://github.com/netblue30/firejail) ([issue 2949](https://github.com/netblue30/firejail/issues/2946) > [netblue30/firejail#2946](https://github.com/netblue30/firejail/issues/2946) )
> I created the profile I attach stored locally at
> `~/.config/firejail/codium.profile`
>
> I use it from my shell through an alias for the executable `codium`
> (`./bin/codium`) as:
>
> `alias codium='firejail /my/local/installation/path/vscodium/bin/codium'`
>
> Not knowing how to share it I used this channel hoping to have help to
> correct/extend it to get best result
>
> Enrico
>
> **codium.profile:**
>
> ```
> # Firejail profile for codium
> # Description: main entry point for VSCodium from shell (./bin/codium)
>
> # Persistent local customizations
> include codium.local
>
> noblacklist ${HOME}/.VSCodium
> noblacklist ${HOME}/.config/VSCodium
> noblacklist ${HOME}/.vscode-oss
>
> ### from https://github.com/netblue30/firejail/issues/2946
> #seccomp !chroot
> #ignore seccomp
> seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice
>
> # Redirect
> include ${CFG}/code.profile
> ```

**Comment by kmk3** [comment]
> vscodium was renamed to codium

Potentially caused by:

* <https://github.com/VSCodium/vscodium/pull/176>

Kind of relates to:

* <https://github.com/VSCodium/vscodium/pull/293>
