### ISSUE TITLE
umask always 0002

### ISSUE THREAD

**Issue by SkewedZeppelin** [netblue30/firejail#3878]
umask is always set to 0002 in the sandbox.
I don't remember this in the past.
Noticed it appear a few months ago.
umask shouldn't be less restrictive then what the distro/user defaults to.
eg. umask shouldn't become 0002 if the distro sets 0022 or the user sets 0077.

**Environment**
- Fedora 33
- firejail from 7c3dd381a65281a2689def21f6d3633cfb7b800b

**Comment by smitsohu** [comment]
Try the following outside Firejail
```
[me@localhost ~]$ umask 123
[me@localhost ~]$ umask
0123
[me@localhost ~]$ bash
[me@localhost ~]$ umask
0002
[me@localhost ~]$
```
It's the default Fedora configuration (`/etc/bashrc` via `~/.bashrc`).

**Comment by smitsohu** [comment]
If it is considered useful we could probably have an option to set the umask per sandbox. All the machinery is in place already, it is just that Firejail does not expose it to the user.

**Comment by SkewedZeppelin** [comment]
@smitsohu

> It's the default Fedora configuration (`/etc/bashrc` via `~/.bashrc`).

Yep, you are correct.
I should've checked that.

Why isn't the existing umask persisted into the sandbox?

**Comment by smitsohu** [comment]
When Firejail is done with configuring the sandbox, and there was no `--shell=none` request, the last thing it does is either running `$SHELL`, or, if an application was specified, `$SHELL -c application`.

If no application was specified, what we get is an interactive shell. Assuming `$SHELL` is bash, it reads ~/.bashrc and executes the instructions. All descendent processes, basically the entire sandbox, then inherit the default `0002` umask.

If, however, an application was specified, the shell is not interactive, ~/.bashrc is ignored and the umask is passed through as expected:

```
[me@localhost firejail]$ umask 123
[me@localhost firejail]$ umask
0123
[me@localhost firejail]$ firejail --noprofile umask
Parent pid 39134, child pid 39135
Child process initialized in 23.80 ms
0123

Parent is shutting down, bye...
```

**Comment by SkewedZeppelin** [comment]
Yep, I see it now.
Thank you @smitsohu for the clarification.
