### ISSUE TITLE
Firetools is displaying a 'terminal' icon, to the right of the Firefox icon.  Any ideas as to why?

### ISSUE THREAD

**Issue by RonCam** [netblue30/firejail#388]
Originally, the top entry in Firejail was just the Firefox icon.  Then while I was working with suggestions to keep Firefox sandboxed in a new session, a terminal-emulator icon (Konsole, in the case of KDE) appeared alongside it.  I've lost track of what I was doing just before this happened.

Where should I look to restore Firejail to its default appearance?

**Comment by netblue30** [comment]
Firetools configuration is located in ~/.config/firetools directory. If you delete this directory (rm  ~/.config/firetools) and restart firetools, it will revert to its defaults.

**Comment by RonCam** [comment]
Thanks! It's still there after deleting the file, as directed, but perhaps it was always there and I just now took notice of it?

**Comment by netblue30** [comment]
You can take a screenshot with gimp or whatever, and post it here.
