### ISSUE TITLE
Appimage fails to run

### ISSUE THREAD

**Issue by Flashwalker** [netblue30/firejail#3898]
Write clear, concise and in textual form.

**Bug and expected behavior**
- Describe the bug.
🔸️Appimage fails to run in firejail (github build 0.9.65):🔸️
`$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ./Kotatogram.appimage`
```
Mounting appimage type 1
Error mounting appimage: appimage.c:117 appimage_set: Invalid argument
```
- What did you expect to happen?  
🔸️Running appimage🔸️

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal?
🔸️Fails🔸️
- What changed calling the program by path (check `which <program>` or `firejail --list` while the sandbox is running)?
🔸️Running. Run log:🔸️
`$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage `
```
Parent pid 6658, child pid 6659

**     Warning: dropping all Linux capabilities     **

Child process initialized in 22.05 ms
```
`$ ./Kotatogram.appimage`
```
qt5ct: using qt5ct plugin
error: : cannot open
error: : cannot open
error: : cannot open
bool DBusMenuExporterDBus::AboutToShow(int): Condition failed: menu
bool DBusMenuExporterDBus::AboutToShow(int): Condition failed: menu
bool DBusMenuExporterDBus::AboutToShow(int): Condition failed: menu
bool DBusMenuExporterDBus::AboutToShow(int): Condition failed: menu
bool DBusMenuExporterDBus::AboutToShow(int): Condition failed: menu
```

**Reproduce**
1. Run in bash `firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ./Kotatogram.appimage` or other appimage apps.
2. See error `Mounting appimage type 1
Error mounting appimage: appimage.c:117 appimage_set: Invalid argument`

**Environment**
 - Distributor ID: Ubuntu; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; kernel: 5.4 and 5.6
 - Firejail version (github build 0.9.65) 

**Additional context**
appimaged

**Checklist**
 - [*] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [?] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [*] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [-] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [*] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [*] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.

<details><summary> debug output </summary>

```
$ firejail --debug --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ./Kotatogram.appimage

Autoselecting /bin/bash as shell
Configuring appimage environment
AppImage ELF size 0
Mounting appimage type 1
Error mounting appimage: appimage.c:117 appimage_set: Invalid argument
```

</details>

**Comment by glitsj16** [comment]
I downloaded the latest stable Kotatogram [AppImage](https://github.com/kotatogram/kotatogram-desktop/releases/download/k1.3.5/1.3.5-appimage.tar.xz) to try to reproduce. Although I didn't actually use it for messaging, the app starts fine here (running Arch Linux/ firejail from git) when using --noprofile and even with a basic redirect to our telegram.profile (see below). Are you using the same appimage? If not, please provide a link so we can make sure we're on the same page.

 > $ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ./Kotatogram.appimage

Is this the actual file name? Usually this is application.`AppImage` instead of the lower-case version you seem to have. Just trying to rule out some potentially confusing stuff with this additional question.

$ cat ${HOME}/.config/firejail/Kotatogram.profile
```
# Firejail profile for Kotatogram
# This file is overwritten after every install/update
# Persistent local customizations
include Kotatogram.local
# Persistent global definitions
# added by included profile
#include globals.local

blacklist ${HOME}/.TelegramDesktop
blacklist ${HOME}/.local/share/TelegramDesktop
noblacklist ${HOME}/.local/share/KotatogramDesktop

# Redirect
include telegram.profile
```

**Comment by Flashwalker** [comment]
Thnx fo test.  
I just downloaded latest beta Kotatogram 1.3.9 and it starts in firejail ok. Previous version i tested was 1.3.3, so looks like it was bad.
