### ISSUE TITLE
Wine multiarch support

### ISSUE THREAD

**Issue by boltronics** [netblue30/firejail#39]
Trying to run a 32-bit application under Wine (```firejail --trace wine winecfg```) spits out a bunch of errors that look like this:
```
ERROR: ld.so: object '/usr/lib/firejail/libtrace.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

You can also observe crashes in some of Wine's services:
```
[wineboot.exe] <defunct>
[winemenubuilder] <defunct>
```

This has some negative side-effects. eg. run ```firejail wine winecfg``` change the operating system version, and click OK. Then run it again, and observe the operating system change was not saved.

/usr/lib/firejail/libtrace.so is an amd64 binary, but it looks like we need a 32-bit version for some Wine prefixes, so we need multiarch support. To support multiarch, I think these should be installed under /usr/lib/{x86_64,i386}-linux-gnu.

**Comment by netblue30** [comment]
I have no idea how to do it in this moment, I'll mark it as an enhancement. Also, --seccomp will not work, syscall numbers are different on 64/32 bit architecture.

**Comment by boltronics** [comment]
I'm aware about the seccomp issue. But as it stands, it's unsafe to run multi-arch Wine under firejail no matter the profile configuration.

I'm also aware it's most likely just a packaging issue. I'd be happy to help out, but first I've got to find the time. :)

**Comment by netblue30** [comment]
Discussion moved here: https://github.com/netblue30/firejail/issues/86

**Comment by l29ah** [comment]
Acutally here: https://github.com/netblue30/firejail/issues/971
