### ISSUE TITLE
VScode can't execute certain script when seccom is enabled

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [netblue30/firejail#3904]
**Bug and expected behavior**
Simple python code as the following would hang when executed:

```
import pandas as pd
df = pd.DataFrame({'name': ['A', 'B', 'C'], 'val': [10, 30, 20]})
chart = df.plot.bar(x='name', y='val')
```
It is expected to draw a simple bar chart but the execution would just hang there forever.
I tried to disable "seccom" in the /etc/firejail/code.profile and the script would then show the chart as expected.

**Reproduce**
1. Run in bash `firejail code`
2. Write the above python code to draw a chart with from a dataframe.
3. Right click the file to choose "execute script in interactive window" in VScode.
4. The interactive window hangs on there and can't finish the execution.

**Environment**
 - Linux distribution and version openSUSE Leap 15.2
 - firejail version 0.9.64

**Comment by rusty-snake** [comment]
If you replace the `seccomp` line in vscode with `seccomp !kcmp` or `seccomp !mbind`, does it work then? If not, run with `--seccomp-error-action=log` and watch your syslog for the violation.

**Comment by GreatBigWhiteWorld** [comment]
> If you replace the `seccomp` line in vscode with `seccomp !kcmp` or `seccomp !mbind`, does it work then? If not, run with `--seccomp-error-action=log` and watch your syslog for the violation.

Both !kcmp and !mbind work. Which one should I use?
Do you suggest that I make a code.local? If so, what content should I put in the file?

**Comment by rusty-snake** [comment]
> Both !kcmp and !mbind work. 

:question: :exclamation: :exploding_head:
Can you run with `--seccomp-error-action=log`.

**Comment by GreatBigWhiteWorld** [comment]
> > Both !kcmp and !mbind work.
> 
>   
> Can you run with `--seccomp-error-action=log`.

Where do I check its log? The terminal shows nothing new after running with `--seccomp-error-action=log`
In syslog when vscode is run has this:
`[system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.73' (uid=1000 pid=11351 comm="/usr/share/code/code --no-sandbox ")`

Why do vscode request bluetooth service??

When running with code.local which has "seccomp !kcmp" and `--seccomp-error-action=log` it's the same result except that the chart can show fine.

**Comment by rusty-snake** [comment]
> Where do I check its log?

Watch `journalctl --grep=SECCOMP --follow` while starting vscode.

> When running with code.local which has "seccomp !kcmp" and --seccomp-error-action=log it's the same result except that the chart can show fine.

Logging must be done without exceptions (e.g. `firejail --seccomp --seccomp-error-action=log --ignore=seccomp …`)

`seccomp-error-action=log ` is like SELinux in permissive mode or AppArmor in complaining mode.

**Comment by rusty-snake** [comment]
`!mbind` is definitely required, because numpy requires it and numpy is a dependency of pandas, see https://github.com/pandas-dev/pandas#dependencies.

`!kcmp` is required too if you have an AMD GPU.

**Comment by GreatBigWhiteWorld** [comment]
> `!mbind` is definitely required, because numpy requires it and numpy is a dependency of pandas, see https://github.com/pandas-dev/pandas#dependencies.
> 
> `!kcmp` is required too if you have an AMD GPU.

Alright, thanks.
