### ISSUE TITLE
telegram-desktop launch browser for open URL (after update to 0.9.64.2)

### ISSUE THREAD

**Issue by IlyaIndigo** [netblue30/firejail#3925]
After update to 0.9.64.2 (although I'm not sure if it has anything to do with the firejail update), telegram-desktop need reed /etc/passwd to start the browser correctly (tested on firefox in openSUSE Tumbleweed).
Otherwise it displays an error: Error getpwuid: main.c:236 init_cfg: No such file or directory.

/etc/firejail/telegram.profile
-private-etc alternatives,alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,os-release,pki,pulse,resolv.conf,ssl,xdg
+private-etc alternatives,alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,os-release,passwd,pki,pulse,resolv.conf,ssl,xdg

**Comment by rusty-snake** [comment]
Should be fixed, thanks for reporting.

FWIW: #2877 issue 1

----

BTW: You can use code-blocks for such diffs which look nicer.

Code:

````
```diff
-private-etc alternatives,alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,os-release,pki,pulse,resolv.conf,ssl,xdg
+private-etc alternatives,alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,os-release,passwd,pki,pulse,resolv.conf,ssl,xdg
```
````

Rendered:

```diff
-private-etc alternatives,alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,os-release,pki,pulse,resolv.conf,ssl,xdg
+private-etc alternatives,alsa,ca-certificates,crypto-policies,fonts,group,ld.so.cache,localtime,machine-id,os-release,passwd,pki,pulse,resolv.conf,ssl,xdg
```

**Comment by IlyaIndigo** [comment]
```diff
-delete
+add
```
Well.
