### ISSUE TITLE
Firejail with steam makes idle master python version non working

### ISSUE THREAD

**Issue by ekaris** [netblue30/firejail#393]
Firejail with steam makes idle master python version non working
Repo of idle master: https://github.com/jshackles/idle_master_py

**Comment by netblue30** [comment]
Is regular steam usage working? or is only when you try this idle_master_py?

**Comment by ekaris** [comment]
Steam works fine alone, Idle master accesses steam account and emulates a running game to drop cards automatically, when using firejail my steam doesn't mention that im in the game selected by idle master as it should

**Comment by netblue30** [comment]
Sorry, I guess my question is can you play a regular steam game in firejail?

**Comment by ekaris** [comment]
Yes and it changes my status to green meaning Im in game

**Comment by netblue30** [comment]
Something else you can try: when you start idle master use "firejail --noprofile". This disables the profile and you get just a basic sandbox. If it is working, we know there is something in the profile that disables it.

**Comment by ekaris** [comment]
The thing is with noprofile, normal profile or no firejail it seems to work but my steam account doesn't change to "ingame" and green so I think it doesn't work

**Comment by netblue30** [comment]
I have no idea what's going on. Anyway, as long as the game is sandboxed, Firejail does its job. Some programs just don't work in a sandbox.

**Comment by ekaris** [comment]
You could try the program..

**Comment by netblue30** [comment]
I don't have Steam installed, it will take some time.

**Comment by ekaris** [comment]
Any news?

**Comment by netblue30** [comment]
No, it is very low priority.

**Comment by ekaris** [comment]
I got this:
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.

**Comment by netblue30** [comment]
I also have problems with Stream on a Ubuntu 16.04. They changed something in the December release. For me it doesn't start at all.

**Comment by ekaris** [comment]
They released a new update this month, try again after uninstall and delete all folders
