### ISSUE TITLE
Starting KeepassXC through file browser

### ISSUE THREAD

**Issue by MrFrank17** [netblue30/firejail#3937]
Hi,

till now I was starting KeepassXC through the KDE start menu and everything worked as expected.
However, if I start it by opening an associated database file in the KDE file browser dolphin, the KeepassXC profile seems not be loaded (eg KeepassXC cannot access its own configuration files in .config). Also it is not listed in `firejail --list`.
Is this expected behavior when starting it within the scope of another application (dolphin in this case)?

Thanks
Frank

**Comment by rusty-snake** [comment]
> Is this expected behavior when starting it within the scope of another application (dolphin in this case)?

If this other application is firejailed too, yes.

**Comment by MrFrank17** [comment]
Ok, then I guess I can close this issue ...
Thanks for the quick reply!

**Comment by MrFrank17** [comment]
After closing this issue a question came to my mind, therefore I reopen it and hope @rusty-snake or someone still reads it.
To my understanding opening a program from another program still uses the profile of the first one, even if the second has its own.
How do you handle in this case file browsers with firejail? All opened files from the file browser (office, pdf, ...) would never use its designated profile. Is the solution to **not** firejail a file browser?

**Comment by rusty-snake** [comment]
> Is the solution to not firejail a file browser?

Yes. Dolphin is the only file browser in firecfg.config (for any reasons). If you disable thumbnails or sandbox the thumbnailers and don't use it for remote file access e.g. smb, there is no much risk left.

**Comment by MrFrank17** [comment]
Somehow I cannot find a firecfg.config on my system. Where is it supposed to be?

What is the best way to remove sandboxing of dolphin? I guess I could remove the symlink in /usr/local/bin or adapt the firecfg.conf once I find it. Or is there way to do this with a local file in my home dir, so I do not have to mess around with the official ones?

Do you (or someone else) know which program is doing the thumbnailing? This would really be my preferred option to sandbox this process.

Thanks

**Comment by rusty-snake** [comment]
Different thumbnail-programs are used depending on the file-format and installing new programs can add additional (krita, xournalpp and mypaint are example that I remember). So I suggest you to disable all thumbnailers expect for mp4,png,jpg,what else you need. IIRC has dolphin many settings for that.

**Comment by MrFrank17** [comment]
Yes, dolphin has many options to toggle thumb-nailing.
I guess this is more smooth than trying to sandbox the programs ...

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
