### ISSUE TITLE
Sorry I canHow do I enable u2f in browser

### ISSUE THREAD

**Issue by NightProwler-dc** [netblue30/firejail#3939]
Write clear, concise and in textual form.
U2F device doesn't work when use firejail to start brave-browser

**Bug and expected behavior**
- Describe the bug.
Plug in u2f device before starting the browser, having "BROWSER_DISABLE_U2F no" in brave-browser.local. but services can't detect my plugged in u2f device. If I don't use firejail to start brave-browser then u2f can work.

**Additional context**
Other context about the problem like related errors to understand the problem.

**Comment by SkewedZeppelin** [comment]
`browser-disable-u2f no` can only be specified in
`/etc/firejail/firejail.config`

**Comment by NightProwler-dc** [comment]
miss posted
