### ISSUE TITLE
Sorry I don't understand how I can enable u2f for brave-browser

### ISSUE THREAD

**Issue by NightProwler-dc** [netblue30/firejail#3940]
U2F device doesn't work when using firejail to start brave-browser

U2f device is plugged in before starting the browser, having "BROWSER_DISABLE_U2F no" in brave-browser.local. but services can't detect my plugged in u2f device. If I don't use firejail to start brave-browser then u2f can work.

It seems I missed something but I can't find how am I supposed to enable u2f devices. I also saw something like
`?BROWSER_DISABLE_U2F: nou2f `in chromium-common.profile but ain't it supposed to be 'no' instead of 'nou2f'?

Thanks for any help.

**Comment by SkewedZeppelin** [comment]
https://github.com/netblue30/firejail/issues/3939#issuecomment-770764222

**Comment by NightProwler-dc** [comment]
> [#3939 (comment)](https://github.com/netblue30/firejail/issues/3939#issuecomment-770764222)

It looks like this in firejail.config now:
```
# Disable U2F in browsers, default enabled.
# browser-disable-u2f yes
```

Should I change it to 
`browser-disable-u2f no`
?

What if I only want to enable U2F for a certain program like brave-browser?

**Comment by rusty-snake** [comment]
> Should I change it to
browser-disable-u2f no
?

yes

> What if I only want to enable U2F for a certain program like brave-browser?

`brave-browser.local`:
```
ignore nou2f
ignore private-dev
```

**Comment by NightProwler-dc** [comment]
Many thanks. I hope this question be added in FAQ maybe.

**Comment by NightProwler-dc** [comment]
> > Should I change it to
> > browser-disable-u2f no
> > ?
> 
> yes
> 
> > What if I only want to enable U2F for a certain program like brave-browser?
> 
> `brave-browser.local`:
> 
> ```
> ignore nou2f
> ignore private-dev
> ```
This actually doesn't work.

What I tested:
Keep the default firejail.config (comment on #browser-disable-u2f no)
add in brave-browser.local
```
ignore nou2f
ignore private-dev
```
connect u2f device and then start the browser

u2f device does not work

**Comment by rusty-snake** [comment]
Gotcha! We need `brave.local` my mistake.
