### ISSUE TITLE
It seems some capabilities are missing

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#3945]
`BPF`,`CHECKPOINT_RESTORE`,`PERFMON`- these are missing `capabilities` if I'm not wrong. btw `CHECKPOINT_RESTORE` got separated out from `SYS_ADMIN` in kernel 5.9 & rest of two got separated out from `SYS_ADMIN` in kernel 5.8. I have looked at [caps.c](https://github.com/netblue30/firejail/blob/master/src/firejail/caps.c) & firejail's [apparmor profile](https://github.com/netblue30/firejail/blob/master/etc/apparmor/firejail-default), but didn't find any of these three.

**Comment by smitsohu** [comment]
@Neo00001 Thanks!
