### ISSUE TITLE
Error: execute permission denied for /usr/local/bin/firefox

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firejail#3957]
Updating to latest Firejail from git (0.9.63) broke Firefox in Fedora. 

```
$ firejail firefox
...
Error: execute permission denied for /usr/local/bin/firefox
Error: no suitable firefox executable found
```
It's looking for /usr/local/bin/firefox.
When I specify the bin path from konsole:
`$ firejail  /usr/bin/firefox`
It appears to launch normally as with previous builds but the GUI never appears.

This appears similar to #2380.

**Comment by rusty-snake** [comment]
> latest Firejail from git (0.9.63) 

The latest is 0.9.65. Is this a typo? What shows `firejail --version`?

**Comment by glitsj16** [comment]
> Updating to latest Firejail from git (0.9.63) broke Firefox in Fedora.

How did you build firejail from git exactly?

**Comment by rusty-snake** [comment]
This reminds me of https://github.com/netblue30/firejail/issues/3333#issuecomment-612601102. @Futureknows does `firejail /usr/bin/firefox` work?

**Comment by Futureknows** [comment]
git clone https://github.com/netblue30/firejail.git
cd firejail
./configure && make && sudo make install-strip

**Comment by rusty-snake** [comment]
When did you the `git clone`? If it was in the last week it can not be 0.9.63.

**Comment by Futureknows** [comment]
Within the last few days.
I rolled back my system and now it is working as before git update, but
Firejail still reports 0.9.63.
I don't have Firejail installed from a package manager.

**Comment by Futureknows** [comment]
I noticed I have Firejail binaries in /usr/bin/ as well as /usr/local/bin/. I suspect they are conflicting.

**Comment by Futureknows** [comment]
After removing 0.9.63 binary from /usr/local/bin/, I updated from git and everything works again.
