### ISSUE TITLE
faccessat2 syscalls support required for glibc 2.33

### ISSUE THREAD

**Issue by mq2yy9t33** [netblue30/firejail#3959]
referring to https://bbs.archlinux.org/viewtopic.php?id=263376 firejail doesn't allow faccessat2 syscalls.

**Bug and expected behavior**
broken websites, no videos, ... 

**Environment**
 - archlinux
 - Firejail 0.9.64.2
 - Tor Browser 10.0.10

**Comment by glitsj16** [comment]
@mq2yy9t33 Thanks for reporting this. I made a PR to add support for faccessat2 syscalls but that's pending review. You could build firejail from git and add the PR patches to see if things work as expected, or wait until it get's into the official Arch Linux repo's.

**Comment by glitsj16** [comment]
Fixed via https://github.com/netblue30/firejail/commit/407c7b3bbdbdbceb93698d722f14a25be83b3b46.

**Comment by mq2yy9t33** [comment]
i've applied all changes in your PR and recompiled to firejail-0.9.64.4-2-x86_64.pkg.tar.zst
there is no difference, no videos, no mega, even this website is displayed like Page Style > No Style
