### ISSUE TITLE
ArchLinux - firejail 0.9.64.2-1 update - breaks firefox profiles 

### ISSUE THREAD

**Issue by qinohe** [netblue30/firejail#3962]
**Bug and expected behavior**
- After installing the newest version of firejail on ArchLinux (0.9.64.2-1)[repo] Firefox profiles become unusable.
- Expected was to be able to use FF without any issues.

**No profile and disabling firejail**
- After using Firefox without firejail-profiile I was able to use the old Firefox profiles (~/mozilla/firefox/*)
- I described the changes in a bugreport on Arch (see) https://bugs.archlinux.org/task/69523
- See additional context below

**Reproduce**
1. Install newest version of firejail on ArchLinux - firejail 0.9.64.2-1
2. Start Firefox or Firefox-developer (both current versions)
3. Previous Firefox-profile(~/.mozilla/firefox/*) is unusable
4. Create new profile & use browser
5. Reboot
6. Repeat step 2 - 5 (over & over)

**Environment**
 - ArchLinux (fully up to date)
 - Linux 5.10.14-hardened1
 - Firejail 0.9.64.2
 - Apparmor 3.0.1

**Additional context**

After 'git bisect' the latest 2 firejail versions there was one left leaving me with this issue (see)https://github.com/netblue30/firejail/commit/096d0de5f8bb253d0c1035796464bc5982f06f81
After a search which actual commit made me have this issue (see Arch bugreport above) it all boiled down to this commit on the 'firefox-common.profile' (see)https://github.com/netblue30/firejail/commit/096d0de5f8bb253d0c1035796464bc5982f06f81#diff-b5a95e2dc71807ecabe122bcec4b560e50780d571fa85892ea4872d7ef337d68
Disabling this ( include whitelist-runuser-common.inc ) commit made the old Firefox profiles available again and all is back to 'normal'.
Added 'ignore include whitelist-runuser-common.inc' to both firefox.local & firefox-developer-edition.local.

I already acknowledged in the Arch bug-report I may be the only one suffering from this issue, at least no one else has made him- / herself heard in the report!

It may / may not be related to the following issue being reported here, but I'm not able to make that judgement!
https://github.com/netblue30/firejail/issues/3952

**Checklist**
 - [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [x] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.

**Comment by rieje** [comment]
Sorry I'm not able to provide any additional info right now but I am also using Arch Linux and Firejail 0.9.64.2-1 results in mpv not using my config settings (presumably using the default settings instead). Downgrading to Firejail 0.9.64-2 fixes this.

**Comment by rusty-snake** [comment]
@qinohe What shows `ls -lR /run/user/$UID`?
@rieje open a new issue for it.

**Comment by qinohe** [comment]
@rusty-snake, Well, I decided to test everything again before I would post to your question.
The problem seems to be solved ,but, what caused it to be solved I have absolutely no idea.
Could be the kernel, I don't know.
For now we can close this issue if you agree, for I can't deliver anything of use anymore and reopen if the problem reoccurs.

**Comment by rusty-snake** [comment]
@qinohe https://github.com/netblue30/firejail/discussions is now up. And you can always ask in the forum of you distro (IIRC there are some firejail experienced user in the Arch Linux forum).
