### ISSUE TITLE
firejail fails to start if iBus is not in use, but .config/ibus/bus/* exists.

### ISSUE THREAD

**Issue by oranenj** [netblue30/firejail#3965]
I happened to have this in my .config:
```
cat .config/ibus/bus/75b2ea12f9fc4116ad6d2c56e1f24f6e-unix-0 
IBUS_ADDRESS=
IBUS_DAEMON_PID=
```
This causes firejail to exit immediately on startup with the following cryptic error message:
```
$ firejail --debug
Autoselecting /bin/bash as shell
Command name #/bin/bash#
Attempting to find default.profile...
Found default.profile profile in /etc/firejail directory
Reading profile /etc/firejail/default.profile
Found disable-common.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-common.inc
Found disable-passwdmgr.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-passwdmgr.inc
Found disable-programs.inc profile in /etc/firejail directory
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

DISPLAY=:0 parsed as 0
Using the local network stack
Parent pid 6162, child pid 6163
Initializing child process
Host network configured
PID namespace installed
Mounting tmpfs on /run/firejail/mnt directory
Creating empty /run/firejail/mnt/seccomp directory
Creating empty /run/firejail/mnt/seccomp/seccomp.protocol file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec32 file
IBUS_ADDRESS=
Error: invalid --env setting
Error: proc 6162 cannot sync with peer: unexpected EOF
Peer 6163 unexpectedly exited with status 1
```

My desktop environment does not use IBus and I'm not sure where those files came from, but removing them allows firejail to run normally. I'm assuming this code is the problem: https://github.com/netblue30/firejail/blob/06e6dfe31ab23f0ed4e56799efffc03dfb1e2c0e/src/firejail/sandbox.c#L778

firejail should probably ignore the environment variables in those files if they are malformed or empty.

**Comment by oranenj** [comment]
Looking at the code, the problem seems to be the `env_store` function is called with `SETENV` and not `SETENV_ALLOW_EMPTY`, causing it to fail.

**Comment by topimiettinen** [comment]
Current Firejail moves the environment variables away, so most of them are not used by the main setuid executable nor the unprivileged helper programs. The variables are restored for the final application. With this in mind, I think the checks for empty variables could be lifted.

**Comment by topimiettinen** [comment]
@oranenj Could you test #3974?

**Comment by oranenj** [comment]
@topimiettinen built and seems to work. Old version of firejail fails, the patched one runs fine. I tested running my sandboxed browser with it, and nothing obvious broke, so LGTM.

**Comment by topimiettinen** [comment]
Thanks for testing!
