### ISSUE TITLE
mpv no longer uses user config

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#3971]
**Bug and expected behavior**

mpv (with firejail) no longer uses user config config.

- What did you expect to happen?

It should use my mpv config.

**No profile and disabling firejail**

- What changed calling `firejail --noprofile /path/to/program` in a terminal?

It works as expected, no bug.

**Environment**

 - Arch Linux, linux kernel 5.1.14-arch1-1

**Additional context**

This bug is experienced is introduced on firejail-0.9.64.2-1 and also apparent on latest version 0.9.64.4-1. Downgrading back to firejail-0.9.64-2 fixes this bug. I have done no modification of any firejail or mpv settings or setup.

**Checklist**
 - [X] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [X] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [X] I have performed a short search for similar issues (to avoid opening a duplicate).

----------------------

[OUTPUT](https://pastebin.com/tdkDngr1) OF `firejail --debug PROGRAM`. I also have an [mpv.local](https://pastebin.com/1AzzzJJ).

**Comment by glitsj16** [comment]
Getting a 404 on your mpv.local from pastebin.com...

**Comment by glitsj16** [comment]
@rusty-snake Maybe we should consider adding a copy of all .local files used by the application when the --debug flag is used. Shouldn't add too much overhead I think and can make the debugging experience a bit more pleasant.

**Comment by rusty-snake** [comment]
... and all profiles/includes in ~/.config/firejail. Although it is still possible to modify the profile in /etc/firejail directly. 

@rieje it you configuration stored in the default location (~/.config/mpv) or somewhere else? And is it just mpv configuration such as `tls-verify=yes`/`hwdec=auto` or are (external) scripts involved?

https://github.com/netblue30/firejail/blob/f71db5299fd3bb9b06254a2e002b24ac7506518c/etc/profile-m-z/mpv.profile#L14-L25

**Comment by rieje** [comment]
@glitsj16 I installed xdg-dbus-proxy again and tried, same thing. Here's the [OUTPUT](https://pastebin.com/tMtLD68s) with it installed. Here's the added [mpv.local](https://pastebin.com/iTsZnkCY).

@rusty-snake Yea, my config is [basic](https://pastebin.com/vEwjNNGk) at ~/.config/mpv/mpv.conf.

**Comment by glitsj16** [comment]
> I installed xdg-dbus-proxy

Good, the debug log confirms that is working as expected. Keep it installed!

Your pastebin'ed mpv.local is a bit unexpected, there's your problem IMO. Why all the ignores? By ignoring all the whitelist options (and not including whitelist-common.inc) you basically turn the profile in what we call a 'blacklist' profile, which is less secure that the original 'whitelist' profile designed for mpv. That would explain why your mpv config(s) are not respected. I also see you're trying to work around some stuff from disable-exec.inc and disable-shell.inc. The reason why escapes me - please elaborate why you try to do this - but you're not making it easy on yourself by doing it like that in a mpv.local. May I suggest moving your existing mpv.local out of the way and retest with the below mpv.local instead:
```
ignore noexec ${HOME}
include allow-bin-sh.inc

dbus-user filter
dbus-user.talk org.freedesktop.Notifications
ignore dbus-user none

# for AMD gpu--'seccomp' by itself causes mpv not to play video--see https://github.com/netblue30/firejail/issues/3219
ignore seccomp
seccomp !kcmp

private-bin bash,dash,mkdir,sh;touch,notify-send,trash-put
```

**Comment by rusty-snake** [comment]
`s/ignore include whitelist-players.inc/ignore include whitelist-player-common.inc/g`

> ```
> ignore seccomp
> seccomp !kcmp
> ```

Your first line causes the second one to be ignored. IIRC it works even w/o `ignore seccomp`

> private-bin bash,dash,mkdir,sh **; -> ,** touch,notify-send,trash-put

> ignore whitelist /usr/share/lua
ignore whitelist /usr/share/lua*
ignore whitelist /usr/share/vulkan

Just more breaktage w/o `ignore include wusc`.

**Comment by rieje** [comment]
@glitsj16 @rusty-snake Ok, that works so I'll close the issue, thanks. But now I'm no longer able to use a [simple script](https://github.com/netblue30/firejail/issues/3635#issuecomment-696956153) bound to a hotkey. mpv gives the error `Starting subprocess failed: init` when using the hotkey. If I add just `ignore whitelist ${HOME}/.config/mpv` to new mpv.local, I get `[input] No key binding found for key 'Ctrl+DEL`.

For my old mpv.local, from trial and error, I needed those ignores for the script to work properly (not sure if I could be more restrictive with them). I also have a single lua script in ~/.config/mpv/scripts. I am currently trying to figure out how to allow the script to run with the new mpv.local. I attempted to merge the two mpv.local files but when I press to hotkey to execute the script, it does not execute and mpv still says `[input] No key binding found for key 'Ctrl+DEL'`.

To be clear, there's no issues with mpv running the script with my old mpv.local on firejail-0.9.64.2.

It seems I no longer need the ignores for lua/vulkan for whatever reason so now I'm just trying to work off of the new  mpv.local.

**Comment by glitsj16** [comment]
> But now I'm no longer able to use a simple script bound to a hotkey.

I took a quick look at https://github.com/netblue30/firejail/issues/3635 and came up with a fix that works for me. Try adding _one_ of the below snippets to your mpv.local. The first one should be used when your mpv-testme script resides in ${HOME}/bin and comes with the (unavoidable) side-effect of all scripts in there being executable inside the sandbox:

```
# allow running a subprocess
include allow-bin-sh.inc
private-bin bash,sh
# allow commands running in subprocess
ignore noexec ${HOME}
whitelist ${HOME}/bin
private-bin notify-send
# allow D-Bus notification
dbus-user filter
dbus-user.talk org.freedesktop.Notifications
ignore dbus-user none
```

On the contrary, if you place your mpv-testme in /usr/local/bin you can go with this:

```
# allow running a subprocess
include allow-bin-sh.inc
private-bin bash,sh
# allow commands running in subprocess
private-bin mpv-testme,notify-send
# allow D-Bus notification
dbus-user filter
dbus-user.talk org.freedesktop.Notifications
ignore dbus-user none
```

If you wonder why the second option needs mpv-testme to be referenced in private-bin while the first one works without it, join in. That bit escapes me and is just something I noticed during testing.

HTH

**Comment by rieje** [comment]
Works great and I should be able to easily adapt for more scripts in the future, thanks!
