### ISSUE TITLE
jitsi-meet-desktop not properly starting

### ISSUE THREAD

**Issue by byteme-git** [netblue30/firejail#3976]
When starting jitsi-meet-desktop after enabling firejail globally with 'firecfg' jitsi-meet-desktop would not start. 
Running it via Terminal using 'firejail --debug jitsi-meet-desktop' displayed an error message saying that sh was missing. Adding 
'private-bin sh' to jitsi-meet-desktop.local
fixed this error but now electron was missing so i added that as well.

Adding 'private-bin sh,electron' to jitsi-meet-desktop.local fixed the problem.

**Comment by glitsj16** [comment]
Thanks for your report. Looks like a bug indeed, nice catch.

Before fixing this in git I'd like you to confirm seeing this behavior on the latest stable firejail release, which would be 0.9.64.4 by the time of writing.

**Comment by rusty-snake** [comment]
From wire-desktop.profile for distro compatibility: `private-bin electron,electron[0-9],electron[0-9][0-9]`
