### ISSUE TITLE
Firejail + AppArmor Permanently Resets/Ignores/Breaks FIrefox Profile .mozilla

### ISSUE THREAD

**Issue by TomAshley303** [netblue30/firejail#398]
This is in reference to: https://github.com/netblue30/firejail/issues/357 . Is it now safe to load up the default apparmor profile for firefox and use firejail? Otherwise, this should be a bug. It was never marked as such.

**Comment by netblue30** [comment]
I have a fix in the master branch, but I would wait until Ubuntu 16.04 is out to try it again. Let's wait until they release it.

**Comment by netblue30** [comment]
Fixed in 0.9.40.
