### ISSUE TITLE
CodeQL warnings

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3986]
> 2 issues were detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results. Using on.push.paths-ignore can prevent Code Scanning annotating new alerts in your pull requests.

https://github.com/netblue30/firejail/actions/runs/562112874

Not sure how to processed.

**Comment by reinerh** [comment]
Thanks, I've synced the CodeQL yml file from Github. Now checking out `HEAD^2` seems to be no longer necessary. They dropped it in their yml file.

**Comment by reinerh** [comment]
It still complains about `Using on.push.paths-ignore can prevent Code Scanning annotating new alerts in your pull requests. `, but we are ignoring these paths intentionally...
