### ISSUE TITLE
cannot switch euid to root

### ISSUE THREAD

**Issue by FacundoAcevedo** [netblue30/firejail#399]
Hello, I've installed firejail on Fedora 23 using the copr repo.
When I run firejail ( even without an application) I get:

> Error: cannot switch euid to root
>Error: the sandbox is not setuid root

**Comment by FacundoAcevedo** [comment]
It happens when I run firejail as normal user.
As root works perfect!

**Comment by chiraag-nataraj** [comment]
Is the firejail binary suid?

**Comment by netblue30** [comment]
Yes, they install the executable without SUID. I guess they intend to use it for servers. This is how you fix it:
`````
$ sudo chmod u+s /usr/bin/firejail
`````
The good part is they track the master git, and they do builds every day.

**Comment by FacundoAcevedo** [comment]
It works, thanks :D
