### ISSUE TITLE
private-etc doesn't allow subdirs

### ISSUE THREAD

**Issue by g-v-egidy** [netblue30/firejail#3991]
**Bug and expected behavior**
I want to allow a program access to the directory /etc/pki/ca-trust/ and below, but not to /etc/pki/tls/private.
As the private keys are really sensitvie, I want not just rely on blacklisting, but remove the private keys fully from the mount with the private-etc option.

When I try to use this in a profile file:
```
private-etc alternatives,crypto-policies,hostname,hosts,ld.so.cache,resolv.conf,localtime,ssl,pki/ca-trust
```
I get the error:
```
Error: "pki/ca-trust" is an invalid filename
```

The manpage suggests that copying subdirs of /etc is allowed as the example given there:
```
Example:
              $ firejail --private-etc=group,hostname,localtime, \
              nsswitch.conf,passwd,resolv.conf,default/motd-news
```
uses default/motd-news.

**Environment**
 - CentOS 8.3 on x86_64.
 - firejail 0.9.64.4

**Comment by smitsohu** [comment]
A simple workaround for now would be to switch from `private-etc` to `whitelist`. It is about as secure as long as you don't add a `writable-etc` option.
```
whitelist /etc/alternatives
whitelist /etc/crypto-policies
whitelist /etc/hostname
whitelist /etc/hosts
whitelist /etc/ld.so.cache
whitelist /etc/resolv.conf
whitelist /etc/localtime
whitelist /etc/ssl
whitelist /etc/pki/ca-trust
```

**Comment by smitsohu** [comment]
Alternatively you can also layer `noblacklist` / `blacklist` on top of the private-etc:
```
noblacklist /etc/pki/ca-trust
blacklist /etc/pki/*
private-etc alternatives,crypto-policies,hostname,hosts,ld.so.cache,resolv.conf,localtime,ssl,pki
```

**Comment by g-v-egidy** [comment]
Thanks for your quick reply.

I'm already using the blacklist solution for now. But it would be nice if private-etc could be improved to also allow the subdirs, because I think this is more secure.

**Comment by brisad** [comment]
Hi! I recently found Firejail, and thought I'd start to help out a little. So I just took a look a this problem and wanted to see if I could fix it.

I am guessing here that the expected behavior would be that
```
private-etc pki/ca-trust
```
would yield `/etc/pki/ca-trust`.

`private-lib` on the other hand, which does support sub-directories, maps 
```
private-lib a/b/c
```
to `/lib/c` (not `/lib/a/b/c`). That is, it copies the target path to the top level `/lib` dir.

For consistency within Firejail, I would assume it should follow the `private-lib` implementation. But perhaps that won't solve @g-v-egidy 's problem. What is the right approach here?

**Comment by g-v-egidy** [comment]
For libs the exact path usually doesn't matter as long as it is within the configured ld.so.conf.
For /etc the exact path really matters and just copying files without preserving their path is useless.

So I think private-etc should work differently than private-lib in this regard.

**Comment by brisad** [comment]
Didn't think about that, but now that you say it, it's very true. Thanks :)

**Comment by rusty-snake** [comment]
#4045

**Comment by brisad** [comment]
Sorry for disappearing right after offering to help. It's been busy times. But I finally took a shot at this and attached a PR.
