### ISSUE TITLE
Have include directives in profiles understand ${HOME} and/or relative paths

### ISSUE THREAD

**Issue by boltronics** [netblue30/firejail#4]
Currently, it's possible to specify:
```blacklist ${HOME}/.ssh```

However, it's not possible to specify:
```include ${HOME}/.config/firejail/disable-mgmt.inc```
or (for a file in the same directory as the one doing the include):
```include disable-mgmt.inc```

Use case: I have all my dotfiles stored in git, and I use GNU Stow to deploy these on systems I use. eg.
```
~$ cd .dotfiles
~/.dotfiles$ git pull
~/.dotfiles$ stow firejail
```
I would rather not have my full home directory path hard-coded so I can deploy these same profiles to systems where my home directory is in a different location.

**Comment by netblue30** [comment]
I'll implement 

include ${HOME}/.config/firejail/file.inc

**Comment by boltronics** [comment]
Thanks!! Sounds awesome.

**Comment by netblue30** [comment]
Fixed!
