### ISSUE TITLE
Chromium Fails To Start When Chromium AppArmor Profile Is Enforced

### ISSUE THREAD

**Issue by TomAshley303** [netblue30/firejail#400]
When /etc/apparmor.d/usr.bin.chromium-browser is enabled/in enforce mode, attempting to start Chromium with firejail fails. The process starts and then crashes (No browser window becomes visible).

firejail version 0.9.38
Chromium Version 49.0.2623.108 Ubuntu 15.10 (64-bit)

**Comment by netblue30** [comment]
Same story as https://github.com/netblue30/firejail/issues/398
