### ISSUE TITLE
Installation problem: trying to overwrite '/etc/firejail/0ad.profile'

### ISSUE THREAD

**Issue by igor2x** [netblue30/firejail#4014]
I get error when installing firejail deb package.

**Bug and expected behavior**
- Problem: Firejail installation returns error
- Expecting behavior: successful installation of Firejail

**Reproduce**
1. Downloaded latest Firejail version on Ubuntu 20.04
2. Executing: `sudo dpkg -i firejail_0.9.64.4_1_amd64.deb`
   and the following output appears:
```
Reading database ... 212822 files and directories currently installed.)
Preparing to unpack firejail_0.9.64.4_1_amd64.deb ...
Unpacking firejail (0.9.64.4-1) over (0.9.62-3) ...
dpkg: error processing archive firejail_0.9.64.4_1_amd64.deb (--install):
 trying to overwrite '/etc/firejail/0ad.profile', which is also in package firejail-profiles 0.9.62-3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 firejail_0.9.64.4_1_amd64.deb
```

**Environment**
- Linux distribution:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

 - Firejail version
 (see above deb file)

**Comment by rusty-snake** [comment]
Looks like you have a firejail installation from the ubuntu packages (what shows `apt list --installed | grep firejail`). You need to uninstall this first (`sudo apt remove --autoremove --purge firejail firejail-profiles`).

**Comment by igor2x** [comment]
I executed your "apt list" command:
```
firejail-profiles/focal,focal,now 0.9.62-3 all [installed,automatic]
firejail/focal,now 0.9.62-3 amd64 [installed]
```
Then I have executed your "apt remove" command and installed firejail as described in my first post.

Command `firejail --version` outputs: `firejail version 0.9.64.4`
Problem solved. Thanks for help.
