### ISSUE TITLE
Add recursive read-only option

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#402]
Hi!

`read-only` is only effective for the indicated directory leaving all sub-directories and sub-files unprotected.
Can you create another option like `read-only.all <folder>` which would protect everything.

Thanks.

**Comment by netblue30** [comment]
This is how is working in this moment, read-only is recursive.

**Comment by nick75e** [comment]
> This is how is working in this moment, read-only is recursive. 

I didn't understand your statement until I tested again and yes you're right but only for the home directory.
It doesn't work like that with mounted hard drives. When I use `read-only /media` where all non-system disks are, directories are still writeable.
It'd work only if I did that for each and every directory!

**Comment by nick75e** [comment]
EDIT: It works if I `read-only` each mount-point which is better than nothing but a recursive option would be ideal.

**Comment by netblue30** [comment]
No problem.

**Comment by avoidr** [comment]
I think #158 is related and explains it.
