### ISSUE TITLE
Revisit profiles allowing netlink protocol

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#4020]
As recently pointed out by @kris7t [here](https://github.com/netblue30/firejail/issues/4013#issuecomment-786780504) the `netlink` protocol `potentially` exposes a huge kernel API sandbox escape surface. In that regard it might be wise to revisit our profiles containing that option.

I've been running several profiles without the netlink protocol via local overrides without issues for quite some time (e.g. aria2c, chromium-common-hardened, firefox-common, mocp, mpg123, mplayer, mpv, nodejs-common, qnapi, sqlitebrowser, sysprof) but that's always dependant on personal workflow and specific use-case. To be clear, I'm not aware of any real-world issues but wanted to file this more as a reminder here. A thorough check of all relevant profiles will certainly take considerable time. Still, IMO it's worth looking at it again.

**Comment by rusty-snake** [comment]
Removing `netlink` from chromium-common-hardened beaks WebRTC, likely the same for firefox-common. mpv has a lot of features, so it's likely needed (maybe for hw related streams), sysprof likely needs it for some features I guess. sqlitebrowser I can not thing any case where it is needed.

Quoting myself for the record (https://github.com/netblue30/firejail/issues/4013#issuecomment-786762799):

> It's always better to not add _/ remove `netlink`_ as long as nothing is broken. But how do you know that nothing is? If the program complains about it, it misses something it wants _and if the profile contains it, it's often for a reason._

**Comment by rusty-snake** [comment]
Should we close?
