### ISSUE TITLE
Any way to know we are inside Firejail or not?

### ISSUE THREAD

**Issue by Bilb** [netblue30/firejail#4034]
Hi,
This is not a bug report, but I did not find what I was looking in the wiki or the existing issues. 
I would like to recommend my users to run my app inside Firejail, but only if that's not the case. And I would like to do that inside my app.

Is there any way to know that the app is running inside Firejail, or not?
Thanks a lot

**Comment by glitsj16** [comment]
> Is there any way to know that the app is running inside Firejail, or not?

Maybe you could check `env,` IIRC there should be a `container` var that equals `firejail`.

**Comment by rusty-snake** [comment]
```
$ firejail --quiet printenv | grep container 
container=firejail
```

or you check `/run/firejail` (compare `ls -R /run/firejail` with `firejail ls -R /run/firejail` and choose a file).

**Comment by Bilb** [comment]
Thanks a lot, that should work
