### ISSUE TITLE
Wordpress connotations

### ISSUE THREAD

**Issue by tredondo** [netblue30/firejail#4046]
Let me start with a thank you for firejail! I've been using it for a week now, and it's an excellent sandboxing solution, far easier to use than Docker.

My feedback is about the Wordpress hosting. In 10+ years of using open source software, this is the first time I see a project hosted on Wordpress. To me, that conveys a sense of amateurishness, which is definitely not deserved. Also, the design isn't mobile-friendly.

Any possibility of hosting on GitHub Pages, for example?

**Comment by rusty-snake** [comment]
old: #2713
new: #2729 (https://github.com/netblue30/firejail/issues/2729#issuecomment-724811241)

WIP/DRAFT: https://rusty-snake.github.io/firejail/

**Comment by tredondo** [comment]
Nice! Small typo in the right sidebar: 
![image](https://user-images.githubusercontent.com/10043369/110053670-ee35b780-7cfd-11eb-891f-912b90067454.png)

**Comment by rusty-snake** [comment]
#2729
