### ISSUE TITLE
GitHub discussions

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#4047]
I just learned that Github has a [discussion](https://docs.github.com/en/discussions) feature.
Currently our issue tracker is also used for normal discussions and questions.

Is this something that we should also try out?

[example project with discussions](https://github.com/CleverRaven/Cataclysm-DDA/discussions)

**Comment by rusty-snake** [comment]
Example projects that you can spam if you want to test: https://github.com/rusty-snake/zufall/discussions

**Comment by netblue30** [comment]
all set!

**Comment by reinerh** [comment]
cool, thanks for setting it up! :-)
