### ISSUE TITLE
Remove link from Wordpress site

### ISSUE THREAD

**Issue by SkewedZeppelin** [netblue30/firejail#4054]
Someone has created an impostor GitHub account with one of my old user names.
And further created a repository that is linked from the Wordpress site.
hxxps://github.com/SpotComms/FirejailProfileGenerator

It was a valid repo of mine in the past, but that account is not in my control.

@netblue30 please remove the link from the site.
@ others please do not trust that account.
Thanks!

**Comment by netblue30** [comment]
all set!

**Comment by rusty-snake** [comment]
This was one of the 404 links I mentioned in December. The 404 link to https://aur.archlinux.org/packages/firejail-extras/ is still there. So if this guy want, he can upload such a AUR packages.
