### ISSUE TITLE
Wiki FAQ request: comparison with bubblewrap

### ISSUE THREAD

**Issue by tredondo** [netblue30/firejail#4055]
In light of #3046, I'd like to make a request for a comparison with Bubblewrap for [the FAQ](https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions).

Bubblewrap has their comparison with Firejail here,
https://github.com/containers/bubblewrap#related-project-comparison-firejail

**Comment by topimiettinen** [comment]
I added the comparison, wdyt?

**Comment by rusty-snake** [comment]
Awesome :tada: 

bubblewrap always has nnp set, while for firejail that's opt-in. Therefore you can use firejail to sandbox privileged programs too.

>  automatic profile generation with `firecfg`

* automatic profile generation with `--build`
* automatic desktop integration with `firecfg`

> easier seccomp filtering …`memory-deny-write-execute`

and `protocol`

**Comment by topimiettinen** [comment]
`protocol` is listed in the network part.
