### ISSUE TITLE
firejail.config not found after following git instructions on the source .tarball

### ISSUE THREAD

**Issue by tredondo** [netblue30/firejail#4059]
I followed the [Debian/Ubuntu](https://github.com/netblue30/firejail/wiki/Using-firejail-from-git#debianubuntu) -> "With AppArmor" instructions, but instead of waiting to clone the whole repo, I downloaded [the source tarball](https://github.com/netblue30/firejail/releases/download/0.9.64.4/firejail-0.9.64.4.tar.xz).

After following the build instructions when I run firejail, I get

> Error: Firejail configuration file /usr/local/etc/firejail/firejail.config not found

Now I don't know how to uninstall this so it won't conflict with the `firejail` from the Ubuntu packages :(

**Comment by rusty-snake** [comment]
> but instead of waiting to clone the whole repo

FYI: `git clone --depth=1 https://github.com/netblue30/firejail.git`

> Now I don't know how to uninstall this so it won't conflict with the firejail from the Ubuntu packages :(

If you have not delted you build dir yet: `sudo make uninstall`

**Comment by glitsj16** [comment]
> I followed the Debian/Ubuntu -> "With AppArmor" instructions
Error: Firejail configuration file /usr/local/etc/firejail/firejail.config not found

That's odd. Seeing /usr/local/etc/firejail suggests you didn't use the --prefix=/usr part of the instructions:
```
$ ./configure --enable-apparmor --prefix=/usr && make && sudo make install-strip
```

There is also a [PPA](https://launchpad.net/~deki/+archive/ubuntu/firejail) you can use that offers latest stable releases and which is maintained by one of our collaborators. That might be easier to keep up with than building from git.

**Comment by tredondo** [comment]
I'm 95% sure I copy-pasted that instruction line, because I was able to [build from git] using the same instructions, and it's working now.

**Comment by rusty-snake** [comment]
A uninstall instruction for https://github.com/netblue30/firejail/wiki/Using-firejail-from-git#makefile sound reasonable.

**Comment by rusty-snake** [comment]
Added `sudo make uninstall` to https://github.com/netblue30/firejail/wiki/Using-firejail-from-git#makefile.

**Comment by rusty-snake** [comment]
Added `sudo make uninstall` to https://github.com/netblue30/firejail/wiki/Using-firejail-from-git#makefile.
