### ISSUE TITLE
[profile bug] atril doesn't open comic archives

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#4066]
for cbz, the profile also needs
`private-bin zipnote,unzip`

didn't test for other archives, more entries in private-bin will be needed.

**Comment by reinerh** [comment]
Probably needs some additional tools as well (tar, unrar, 7zip) for the other comic book formats?
https://en.wikipedia.org/wiki/Comic_book_archive#Design

**Comment by pirate486743186** [comment]
yes i know, i haven't tested yet.

**Comment by pirate486743186** [comment]
merged
