### ISSUE TITLE
Created firejail ansible playbook

### ISSUE THREAD

**Issue by Andrew415** [netblue30/firejail#407]
This playbook https://bitbucket.org/aaaaaaaaaaaaaaaaaaaaa1/ansible-firejail/overview will install firejail automatically on an ansible managed system. It could be improved by being yum/apt neutral. 

It would be interesting to extend it such that it uses ansible's fact gathering mode to store a record of binaries syscall functions and use the stored facts to generate firejail profiles but that is more involved than what I have time for, hopefully someone else can take this up as a fun project!

Another advanced usage would be to use this for the basis of performing QA on firejail profiles on lists of programs that it is desired to jail. This can be achieved by using the result and register variables in ansible.

**Comment by netblue30** [comment]
Thanks, I put a link to it on the main project site: https://firejail.wordpress.com/
