### ISSUE TITLE
firecfg.config location

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#408]
In the header of firecfg.config you mention a location of /etc/firejail/firecfg.config.
But by default it is installed in $LIBDIR/firejail/firecfg.config.
Which is supposed to be the correct location (i.e., is is intended to be edited by the user?)?

**Comment by netblue30** [comment]
Sorry, it is in $LIBDIR/firejail/firecfg.config

**Comment by netblue30** [comment]
Fixed, thanks!

**Comment by Vincent43** [comment]
@netblue30 why it should be non-editable? I think that enabling/disabling specific apps from firecfg may solve https://github.com/netblue30/firejail/issues/2097 cc @chiraag-nataraj

**Comment by chiraag-nataraj** [comment]
Yes, it's odd that a configuration file is being stored in `$LIBDIR`...why was that chosen in the first place? Why not store it in `${CFG}` like `firejail.config`?

**Comment by Vincent43** [comment]
@netblue30 opinions?
