### ISSUE TITLE
[profile bug] eo-common and net none

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#4088]
with  eom, you can see an image from the web.
For example, this works:
`eom https://github.com/fluidicon.png`

"net none" breakes this feature.
maybe it should be removed?

I didn't test this, but i'm assuming eog and other eo clones do the same.

**Comment by rusty-snake** [comment]
1. This works without `protocol inet,inet6`??!
2. Has eom it's own support for https or does it use gvfsd-http?
3. If we go for it, we should do it like we did it for feh.

**Comment by pirate486743186** [comment]
i don't know about all these details, but there's "protocol unix,netlink" in eo-common

**Comment by pirate486743186** [comment]
> Warning: private-lib feature is currently available only on amd64 platforms

i'm on 32bit, so i'm assuming this is how it has access to the network with just "ignore net none"

i'm assuming, that  probably "include feh-network.profile"  would actually be needed on 64bits.
Then maybe rename feh-network.profile

**Comment by rusty-snake** [comment]
For eog on my system it works when I add 
```
ignore net none
netfilter
dbus-user.talk org.gtk.vfs.Daemon
dbus-user.talk org.gtk.vfs.mountpoint_http
```

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
