### ISSUE TITLE
INFO: Limitation of supported options on GRsec

### ISSUE THREAD

**Issue by HulaHoopWhonix** [netblue30/firejail#411]
Please add a brief note in documentation about what options are unavailable on GRsecurity kernels. Is this temporary or are GRsec chroots fundamentally incompatible with other programs?

In your testing did default profiles work out of the box?

**Comment by netblue30** [comment]
I'll write a full document for it. --chroot and --overlay will not be supported. Firetools is totally broken in this moment.

**Comment by NoAgendaIT** [comment]
I assume that, with "in this moment", you meant "when using this kernel", is that right?

Grsecurity provides similar options to firejail, so while chroot is not useful, I think that the networking options of firejail could still be made useful on Grsecurity kernels.

**Comment by netblue30** [comment]
I have the kernel from Debian sid as a reference, before moving to a more general kernel configuration. This is the status:

proc/pid hiding problem was solved on the master branch. Some command line options in firemon utility would need to be run as root. 

Chroot is stil broken - after chroot call I need to do some filesystem mounts, denied by Grsecurity. The story is similar to overlayfs - it uses chroot call at some point.

Firetools is mostly fixed. It will not show network statistics - also a problem with proc/pid hiding.

**Comment by netblue30** [comment]
I added some notes here: https://firejail.wordpress.com/documentation-2/grsecurity-notes/

**Comment by requiredregistration** [comment]
--overly in the notes
