### ISSUE TITLE
File Roller on the cinnamon desktop doesn't work

### ISSUE THREAD

**Issue by mystic-githuber** [netblue30/firejail#4113]
I have turned on firejail for the cinnamon desktop and it seems that file roller doesn't work, I am unable to compress files. I started using engrampa archive manager as an alternative.

Firejail - 0.9.64.4
Cinnamon - 4.8.6
File roller - 3.38

**Comment by rusty-snake** [comment]
Do you get an error? Or how does it show that it don't work? Is the output empty? Not present? Or does it crash? Does this happen for every format or only for a special one (e.g. lzma)? Does this happen for every file or file in specific locations?

**Comment by mystic-githuber** [comment]
Compression bar stops at 85 % percentage always and doesn't complete the task. It happens in all locations that I have tried so far.

**Comment by glitsj16** [comment]
> I have turned on firejail for the cinnamon desktop and it seems that file roller doesn't work, I am unable to compress files. I started using engrampa archive manager as an alternative.

When comparing both profiles, the major differences reside in private-bin + private-etc. Have you tried adding the below to a `file-roller.local` yet?
```
ignore private-bin
ignore private-etc
```

Also, if you might be able to start file-roller from a terminal and post any errors/warnings thrown in there while it compresses/extracts one of your archives that would be very helpful. For now we don't have that much info to go on to determine why file-roller isn't working as expected.

**Comment by rusty-snake** [comment]
For me (fedora 33; file-roller 3.38.0) it works = I could successfully create a tar.gz archive. I have not even had a compressionsbar, maybe because it where small files that was fast to compress.

Full diff:
```
$ fjp diff file-roller engrampa
The following commands are unique to file-roller.profile:
include file-roller.local
whitelist /usr/share/file-roller
include whitelist-runuser-common.inc
include whitelist-usr-share-common.inc
machine-id
seccomp.block-secondary
private-bin 7z,7za,7zr,ar,arj,bash,brotli,bzip2,compress,cpio,dpkg-deb,file-roller,gtar,gzip,isoinfo,lha,lrzip,lsar,lz4,lzip,lzma,lzop,p7zip,rar,rzip,sh,tar,unace,unalz,unar,uncompress,unrar,unsquashfs,unstuff,unzip,xz,zip,zoo
private-cache
private-etc dconf,fonts,gtk-3.0,xdg

The following commands are unique to engrampa.profile:
include engrampa.local
```

wusc: could break; but then it would break from start and not at 85%
wruc: should not break
machine-id: unlikely
seccomp.block-secondary: error will show up with `journalctl --boot --grep=SECCOMP --follow`
private-bin: could break a specific format or with a changed login shell
private-cache: maybe
private-etc: very short

private-{bin,etc} can be cheked with `firejail --build file-roller | grep -E "private-(bin|etc)"`.

**Comment by mystic-githuber** [comment]
@rusty-snake 
I am not good at using the command line, relatively new to linux sorry if am not helpful. Might be because I am using Manjaro and 
I also used `$ sudo aa-enforce firejail-default` too.

**Comment by rusty-snake** [comment]
I think I  can reproduce this now. @mystic-githuber can you confirm that adding `cp,mv,rm` to `private-bin` fixes this issue.

BTW: `zstd` is missing too.

**Comment by rusty-snake** [comment]
still an issue?
