### ISSUE TITLE
Nheko (matrix client) does not run properly with firejail

### ISSUE THREAD

**Issue by qazip** [netblue30/firejail#4115]
Hello,

Running nheko with firejail is not working properly. There is more discussion on nheko's repo, namely: https://github.com/Nheko-Reborn/nheko/issues/249?_pjax=%23js-repo-pjax-container

I found that, for some reason, nheko is not writing to ` ~/.cache/nheko/nheko` when firejailed. The profile used is:

```
# Firejail profile for nheko
# Description: Desktop IM client for the Matrix protocol
# This file is overwritten after every install/update
# Persistent local customizations
include nheko.local
# Persistent global definitions
include globals.local

noblacklist ${HOME}/.config/nheko
noblacklist ${HOME}/.cache/nheko

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-interpreters.inc
include disable-passwdmgr.inc
include disable-programs.inc
include disable-shell.inc
include disable-xdg.inc

mkdir ${HOME}/.config/nheko
mkdir ${HOME}/.cache/nheko/nheko
whitelist ${HOME}/.config/nheko
whitelist ${HOME}/.cache/nheko
whitelist ${DOWNLOADS}
include whitelist-common.inc
include whitelist-runuser-common.inc
include whitelist-usr-share-common.inc
include whitelist-var-common.inc

apparmor
caps.drop all
netfilter
nodvd
nogroups
nonewprivs
noroot
notv
protocol unix,inet,inet6
seccomp
shell none
tracelog

disable-mnt
private-bin nheko
private-cache
private-dev
private-etc alsa,alternatives,asound.conf,ca-certificates,crypto-policies,fonts,gtk-2.0,gtk-3.0,host.conf,hostname,hosts,ld.so.cache,ld.so.conf,ld.so.conf.d,ld.so.preload,locale,locale.alias,locale.conf,mime.types,nsswitch.conf,pki,pulse,resolv.conf,selinux,ssl,X11,xdg
private-tmp

dbus-user none
# Comment the above line and uncomment below lines for notification popups
# dbus-user filter
# dbus-user.talk org.freedesktop.Notifications
# dbus-user.talk org.kde.StatusNotifierWatcher
dbus-system none
```

Any idea what's happening?

**Comment by Neo00001** [comment]
> for some reason, nheko is not writing to ` ~/.cache/nheko/nheko` when firejailed

comment out `private-cache`



> Running nheko with firejail is not working properly

run with `firejail --debug --profile=yourprofile /path/nheko`

you may also run `firejail --build /path/nheko` to get a rough idea. for hardening you have to manually curate the profile

**Comment by glitsj16** [comment]
> nheko is not writing to ~/.cache/nheko/nheko when firejailed

I saw the thread you mentioned (https://github.com/Nheko-Reborn/nheko/issues/249) and someone stated that disabling private-cache didn't help. Looking at the profile I see this:

```
mkdir ${HOME}/.config/nheko
mkdir ${HOME}/.cache/nheko/nheko
whitelist ${HOME}/.config/nheko
whitelist ${HOME}/.cache/nheko
```

Is ${HOME}/.cache/nheko/nheko a `file` instead of a `dir`? In that case you'd need `mkfile` instead of `mkdir`. Have you tried that yet?

**Comment by qazip** [comment]
@Neo00001, I already commented private-cache and it didn't help.

Runnihg with --debug:

```
[2021-03-19 12:27:57.039] [crypto] [critical] failed to upload one time keys: One time key signed_curve25519:AAAAAQ already exists. Old key: {"key":"DTVo5pP/nFasdf213f/FnB5q52rf6O4FakZt542faX7BoLUw1+jFWS4","signatures":{"@blabla:matrix.org":{"ed25519:YSTfdaDAPFEDMVD":"781tb8/6/D2RdoGz/+QP8pagAifCfgagloN+r1fIaCNZHgWaNHDK7fdaSqcRIfwwTzBjeRiAp2psRQ2eP78tw34Q5vejrMBw"}}}; new key: {'key': 'iSt+q08f/FolnRCiNaQHnffMfzdWaa2C0aPMKIKsdYofgT4Xqoyc', 'signatures': {'@blabla:matrix.org': {'ed25519:YSTPFEXMAV': 'Y1ctg/xj/ubBgDR3loWHMgTO2Aj8lPeELs0Mr+k6qztRwfFbFp4MqQSS/z30E4H1hJQNaDyHdE2Nw9YzlfE2Ag'}}} 400
[2021-03-19 12:27:57.042] [ui] [info] dropping to the login page: Failed to setup encryption keys. Server response: One time key signed_curve25519:AAAAAQ already exists. Old key: {"key":"DTVo5pP/nQikGf/FnB5qrf6OkZt5aX7BoLUw1+jFWS4","signatures":{"@blabla:matrix.org":{"ed25519:YSTPFEXMAV":"781tb8/6/D2RdoGz/+QP8pgAifCggloN+r1ICNZHWNasda2fdaHDK7SqcRIfwwTzBjeRiAp2psRQ2eP78tw34Q5vejrMBw"}}}; new key: {'key': 'iSt+q08/FolnRCiNQHnMzdW2C0PMKIKfasdYogT4Xqoyc', 'signatures': {'@blabla:matrix.org': {'ed25519:YSTPFEXMAV': 'Y1ctg/xj/ubBgDfdsaR3loWHMgTO2Aj8lPeELs0Mr+k6qztRwfFbFp4MqQSS/z30E4H1hJQNaDyHdE2Nw9YzlfE2Ag'}}} 400. Please try again later.
shutdown: shutdown while in init
[2021-03-19 12:27:57.043] [qml] [warning] qrc:/qml/MessageInput.qml:254: TypeError: Cannot read property 'input' of null (qrc:/qml/MessageInput.qml:254, )
shutdown: shutdown while in init
[2021-03-19 12:27:57.043] [db] [info] deleted cache files from disk
```

**Comment by qazip** [comment]
@glitsj16, it is a folder, not a file, so it is fine.

**Comment by glitsj16** [comment]
> it is a folder, not a file, so it is fine.

disable-programs.inc --> blacklist ${HOME}/.cache/nheko
nheko.profile
- noblacklist ${HOME}/.cache/nheko
- mkdir ${HOME}/.cache/nheko/nheko
- whitelist ${HOME}/.cache/nheko

This doesn't feel right to me, we should whitelist ${HOME}/.cache/nheko/nheko no?

**Comment by qazip** [comment]
I commented out "include disable-programs.inc". Still having the error.

I changed whitelist ${HOME}/.cache/nheko to  `${HOME}/.cache/nheko/nheko`. Still having the same error.

**Comment by glitsj16** [comment]
Looks like a complex issue indeed. Alas, For the moment I'm unable to test nheko properly and cannot add anything actually useful here.

> EDIT: I am starting to wonder if it is me who is doing something wrong. I am editing /etc/firejail/nheko.profile directly (with sudo). It is that file that is ran when I call "firejail nheko", right?

That is correct. The only downside of doing it in /etc/firejail/nheko.profile is your changes will be overwritten by a future firejail upgrade. Firejail supports .local overrides too. You can use ${HOME}/.config/firejail for per-user overrides. Anything in there will get picked-up before parsing /etc/profile.

**Comment by rusty-snake** [comment]
@qazip what happens if you `whitelist ${HOME}/.cache`?

**Comment by rusty-snake** [comment]
Does this still happen if your profile only contains

```
mkdir ${HOME}/.config/nheko
mkdir ${HOME}/.cache/nheko
whitelist ${HOME}/.config/nheko
whitelist ${HOME}/.cache/nheko
whitelist ${DOWNLOADS}
include whitelist-common.inc
```

**Comment by qazip** [comment]
> @qazip what happens if you `whitelist ${HOME}/.cache`?

Added that line. Still same error.

**Comment by qazip** [comment]
> Does this still happen if your profile only contains
> 
> ```
> mkdir ${HOME}/.config/nheko
> mkdir ${HOME}/.cache/nheko
> whitelist ${HOME}/.config/nheko
> whitelist ${HOME}/.cache/nheko
> whitelist ${DOWNLOADS}
> include whitelist-common.inc
> ```

Same error still.

**Comment by qazip** [comment]
.cache  .config  .local  .Xauthority  .zshrc inside nhekohome.

**Comment by rusty-snake** [comment]
And in .cache .config .local/share (ignore .config/pulse)?

**Comment by qazip** [comment]
```
~/nhekohome 
❯ exa -a --tree
.
├── .cache
│  ├── gstreamer-1.0
│  │  └── registry.x86_64.bin
│  ├── mesa_shader_cache
│  │  ├── 1b
│  │  │  └── 39bd6cda70113abfd854630a307f76e4327de1
│  │  ├── 2e
│  │  │  └── c38a8d4fe00166c07d679f3048a4b9186c899b
│  │  ├── 3b
│  │  │  └── cb2506d7831c4c01e31bfc64aa20943f23511e
│  │  ├── 11
│  │  │  └── 6ff5c632f3178401ae51f32efbcb4a496d613a
│  │  ├── 15
│  │  │  └── 9d91147c361785d9184339213845dbe97c4821
│  │  ├── 22
│  │  │  └── e3fdf8e64af614081fcebdbcedb495114713ce
│  │  ├── 32
│  │  │  └── 69c6423ebd3e5884a3776db232cc9cd111c3d4
│  │  ├── 55
│  │  │  └── e8ed15662930dd564780ee011a8c9c95365334
│  │  ├── 64
│  │  │  ├── 8e71aadaddc8d52d27ac00ead2795df43df824
│  │  │  └── 1444861a73fd21fd2c3e20a908c89ca279439e
│  │  ├── 67
│  │  │  └── 2c19518f66a83c3189dd9c90241b29c8802b2e
│  │  ├── 77
│  │  │  └── 2ce43e3ce46ee96244961813618e157e841a60
│  │  ├── a1
│  │  │  └── 94e0ccdd94d96a34ec19b4aa1a00ea61477c67
│  │  ├── ac
│  │  │  └── bfde472bdaaeffb1c46c19ae1cdfbe1ee41759
│  │  ├── c2
│  │  │  └── 529a1be68b067ec399fd6a40f81dbd644e59b3
│  │  ├── c3
│  │  │  └── 081f3ac94407ca5672f76579316ffd08a1aa7a
│  │  ├── d2
│  │  │  └── cee1ac9a89af5721880dda60492dc632d66439
│  │  ├── d5
│  │  │  └── 6230f38070b8572c972345533bfc308c1b120c
│  │  ├── dd
│  │  │  └── 7ed87c847db186b053754106752453c3e9ee41
│  │  ├── eb
│  │  │  ├── 10501ecf0ec571e1ad229dbb19e37e27f37bb9
│  │  │  └── aa694377ee540b3526d375d9f14928ded51787
│  │  ├── ec
│  │  │  └── b89702b8438bb9c6865e7861b632161c01b8f1
│  │  ├── f5
│  │  │  └── cec05f56261155f09a67fc190085d44e94233e
│  │  ├── f8
│  │  │  └── 394ab0545b514857f1218fe53baf1b6cd8ab19
│  │  └── index
│  ├── nheko
│  │  └── nheko
│  │     └── nheko.log
│  └── qtshadercache-x86_64-little_endian-lp64
│     ├── 07aac9bdf60e1e078a2e04bad73cb456220c61b4
│     ├── 3c597a80b51a24c02510e986e8c27bdb62e99ba6
│     ├── 5cc098bc5354d98253495e89cc26ca4ba78a3a15
│     ├── 7d5f9fc417d36376dbfbebf864483aca3a25ac1a
│     ├── b9ec05f41810b130c38c3dc281312718d7eede5a
│     ├── cba8d1ceb9482bf7ad559bc702b71beca94f54a3
│     ├── d524b60ebe14b3342c6956c081215082a7ec73c0
│     └── e24592d8d235339875cae31851ad680a190a7cc6
├── .config
│  ├── nheko
│  │  └── nheko.conf
│  └── pulse
├── .local
│  └── share
│     └── nheko
│        └── nheko
│           └── 406d6d663a6d61747269782e6f7267
│              ├── data.mdb
│              └── lock.mdb
├── .Xauthority
└── .zshrc
```

**Comment by Neo00001** [comment]
@qazip  I tried with your profile with `private-cache` disabled on Arch.& with firejail there is `~/.cache/nheko/nheko/nheko.log` but without firejail `~/.cache/nheko/nheko` has `qmlcache` along with that `.log` file.  btw do you have anything in your `globals.local`?

**Comment by rusty-snake** [comment]
> ├── .local
│  └── share
│     └── nheko
│        └── nheko
│           └── 406d6d663a6d61747269782e6f7267
│              ├── data.mdb
│              └── lock.mdb

There are databases but no whitelist for them, so they are dropped when you close nheko => server state and client state differ.

**Comment by rusty-snake** [comment]
```
noblacklist ${HOME}/.local/share/nheko
mkdir ${HOME}/.local/share/nheko

**Comment by qazip** [comment]
> fix:
> 
> ```
> noblacklist ${HOME}/.local/share/nheko
> blacklist ${HOME}/.local/share/nheko
> mkdir ${HOME}/.local/share/nheko
> whitelist ${HOME}/.local/share/nheko
> ```

I added those lines (other than the one that says to blacklist something that you noblacklisted above? I suppose that was a typo) and it works! Thank you very much!

**Comment by rusty-snake** [comment]
> I suppose that was a typo

That are the lines we need to add, in the order they are read. Of course will this blacklist go to dp.

**Comment by qazip** [comment]
If I add all the 4 lines, it doesn't fix the error. However, if I only add the following 3, it does fix the error:

noblacklist ${HOME}/.local/share/nheko
mkdir ${HOME}/.local/share/nheko
whitelist ${HOME}/.local/share/nheko
