### ISSUE TITLE
How to allow access to other home directories?

### ISSUE THREAD

**Issue by muziker** [netblue30/firejail#4120]
Not a bug, but i couldn't find any information anywhere else. How do i allow a profile to access a /home/otheruser directory, assuming it is usually accessible? I've tried whitelist, but it looks like all other home directories are dropped.

**Comment by rusty-snake** [comment]
`allusers`

**Comment by muziker** [comment]
But only one specific directory, and to maintain the id:group ownership, since if it is nobody:nogroup, the user will not be able to access it.

**Comment by rusty-snake** [comment]
Sorry I don't fully get you, but If the files are owned by an other user and you have only access to it via group, your supplemetray groups needs to preserved and the other user must be present:
```
ignore noroot
ignore nogroups
```

**Comment by muziker** [comment]
Thanks that helps ! The noroot was ensuring only one user was on the system. ignore noroot allowed the traditional permissions model to work.
