### ISSUE TITLE
existing sandbox issue with tor-browser

### ISSUE THREAD

**Issue by suedi** [netblue30/firejail#413]
This was working OK with Firejail 0.9.8

Threw away that and built 0.9.40-rc1
Now trying to start tor-browser I get the "Warning: an existing sandbox was detected!" message

May be related to #401 but I don't have apparmor or grsec compiled kernel.
I am running kernel 4.1.6 with AUFS. Mounting /proc with hidepid=2 though.

The only thing I changed was Firejail so should work, right!?

It works with --force but I don't want to "run without any additional sandboxing features"
that is output in the warning, I want those additional features.

What gives?

**Comment by avoidr** [comment]
Try the profile with those includes instead:
```
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
```

**Comment by suedi** [comment]
Trying with your suggestions instead

```
#include /etc/firejail/disable-mgmt.inc
#include /etc/firejail/disable-secret.inc
#include /etc/firejail/disable-common.inc
#include /etc/firejail/disable-devel.inc

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
```

If I use --force it seems to work, without --force still the same

short explaination please

**Comment by avoidr** [comment]
No, I meant replacing the previous includes with the new ones.

I am only guessing here, but I remember having a similar problem. Unfortunately I don't remember what fixed it... but it could have been the new profiles, I don't remember.

**Comment by suedi** [comment]
Yeah, and thats what I did.

Just included what I had before, They are commented out
Sorry for not being obvious about it.

I thought they would be useful in discussing why your solution worked

**Comment by avoidr** [comment]
I am sorry, I have no solution for this right now. netblue will most likely be able to help you, though.

**Comment by netblue30** [comment]
I'll have to look into it, thanks!

**Comment by netblue30** [comment]
> Mounting /proc with hidepid=2 though.

I think this was already fixed for Grsecurity, where we have a similar situation with /proc entries unavailable for other users. The git version on the master branch should fix the problem. A temporary solution is to insert --force option on the command line: firejail --force program-and-arguments.

**Comment by suedi** [comment]
Confirm that git version works!

Good Job

**Comment by netblue30** [comment]
Thanks!
