### ISSUE TITLE
--shell=none does not work

### ISSUE THREAD

**Issue by vporton** [netblue30/firejail#4136]
**Bug and expected behavior**

```sh
firejail --noprofile --shell=none --private=. true
```
produces the files `.Xauthority`, `.asoundrc`, `.bashrc`, however it should not.

**Environment**
 - Ubuntu 20.10
 - firejail version 0.9.62.4

**Checklist**
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [x] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [x] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.

**Comment by Neo00001** [comment]
`--shell=none` tells the program to run directly without user shell.

& you got these three- `.Xauthority, .asoundrc, .bashrc` beacuse  you used `private` . you may check the [source code](https://github.com/netblue30/firejail/blob/master/src/firejail/fs_home.c). btw, `.asoundrc` is alsa related file & `.Xauthority` is xserver related file.

**Comment by Neo00001** [comment]
Closing this for now, feel free to reopen this if needed.
