### ISSUE TITLE
Feedreader not working properly with Firejail's Sandbox

### ISSUE THREAD

**Issue by g4njawizard** [netblue30/firejail#4142]
Today I installed Feedreader and I used the default feedreader profile provided by the firecfg.
It looks like it would work normal. I can select the type of RSS connection I want to use. After selecting all sites I want to read news from, It begins loading all newest topics, but it stops there and it's unable to load the full article. 
Closing Feedreader is causing the sandbox to freeze. Not only I have to "ctrl+c" the terminal, I have to kill the process manually.
When I open Feedreader again, it shows the state "offline". From this state, I am unable to make the application run normal, even when using -noprofile.

However, when I remove all saved data from feedreader and begin from new with "firejail --noprofile feedreader" I think It's able to write some of the needed settings, but this doesnt help. The sandbox is still freezing when closing. Reopening feedreader looks normal, but it's not loading any articles. 

This is an abnormal behaviour I haven't seen in any running application that uses firejail on my system.

After all my tries and errors I broke it so hard, that feedreader wont start with a clean config. Thats why I cant deliver any helpful debug logs.

**Comment by rusty-snake** [comment]
Feedreader is no longer maintained (https://github.com/jangernert/FeedReader#this-project-is-no-longer-activily-maintained) and one of the buggiest programs I used in the last years. I recommend you to use an other feedreader. 

---

What's your firejail version and distro? Is anything in the syslog?

> Today I installed Feedreader and I used the default feedreader profile provided by the ~firecfg~ firejail.

Have you ever tested if feedreader works without firejail?

> It begins loading all newest topics, but it stops there and it's unable to load the full article.

If you are on Arch or an other distro close to upstream, this is maybe #3647.

> Closing Feedreader is causing the sandbox to freeze.

The sandbox or feedreader? Meaning `firejail --list` still shows the process (but no window) or the window keeps open (in a frozen state).

> "firejail --noprofile feedreader"… The sandbox is still freezing when closing.

Does still still happen with [https://gist.github.com/rusty-snake/bb234cb3e50e1e4e7429f29a7931cc72](noprofile.profile)?

> When I open Feedreader again, it shows the state "offline".

> This is an abnormal behaviour I haven't seen in any running application that uses firejail on my system.

Had I said it's one of the buggiest programs I know (except of my own programs :rofl:).

**Comment by g4njawizard** [comment]
Hi Rusty-snake. Thanks for your time. So indeed, it would work without running firejail.

But I now decided to stick to fluent reader with Appimage. This works far better than with feedreader. 

So I think, as long no one else will try the same, we can close this story and go on for newer better working stuff. ;)
