### ISSUE TITLE
firejail doesn't work automatically with gnome-books

### ISSUE THREAD

**Issue by Tus1688** [netblue30/firejail#4145]
OS: Ubuntu 20.04.2 LTS
I am sorry if you found this question funny. I have been using firejail for a month, and I have never found any issue with app from apt repository. Today, I install gnome-books then do sudo firecfg to reconfigure, then relog. 

I open gnome-books, I did `firejail --list` and gnome-books didn't show up. but when I do `firejail gnome-books` it's work like usual. Before I open an issue here, I have read firejail wiki. Unfortunately, I don't understand what is symlink is. Thanks in advance for your kindly help

**Comment by rusty-snake** [comment]
If the symlink is properly configured, you should get something like
```
$ ls -l "$(command -v gnome-books)"
lrwxrwxrwx. 1 root root … /usr/local/bin/gnome-books -> /usr/bin/firejail
```

then it's likely duplicated of #2624.

**Comment by Tus1688** [comment]
Thank you for your reply. I tried it, it show same as your previous reply.

**Comment by rusty-snake** [comment]
Then try to create `/etc/firejail/Books.profile`:
```
# Firejail profile for gnome-books
# This file is overwritten after every install/update


# Temporary fix for https://github.com/netblue30/firejail/issues/2624
# Redirect
include gnome-books.profile
```

and add `Books` to `firecfg.config` (find it with `shopt -s globstar && ls /usr/lib*/**/firecfg.config`).

After running `sudo firecfg` again, it hopefully works (and we can add it).

**Comment by Tus1688** [comment]
it is working, thank you very much!
