### ISSUE TITLE
[Feature] Should rmenv GitHub auth tokens

### ISSUE THREAD

**Issue by matthew-cline** [netblue30/firejail#4157]
The [GitHub command line app (gh)](https://cli.github.com/) uses GitHub [personal access tokens](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).  These can be passed to `gh` via [environmental variables](https://cli.github.com/manual/gh_help_environment):

- `GH_TOKEN`
- `GITHUB_TOKEN`
- `GH_ENTERPRISE_TOKEN`
- `GITHUB_ENTERPRISE_TOKEN`

These should be `rmenv`'d somewhere.  Perhaps in `disable-passwdmgr.inc`?

**Comment by rusty-snake** [comment]
Keep in mind that even if you `rmenv` them, a sandbox can still read the file where they are set if this file is not `blacklist`ed or has no `whitelist` (in whitelisting profiles).

**Comment by kmk3** [comment]
For future reference, the `rmenv` entries were moved to [disable-common.inc][1]
on #4461.

[1]: https://github.com/netblue30/firejail/blob/master/etc/inc/disable-common.inc
