### ISSUE TITLE
Firejail blocks sound/music when using cmus

### ISSUE THREAD

**Issue by MRF316** [netblue30/firejail#4160]
I just re-installed Linux Mint, and everything worked great before re-installing, now I just finished transferring my music and I get this error...**Error: opening audio device: internal error**
I figured it might be FJ, so I temporarily uninstalled it, and tried cmus and my music plays fine! I never had this issue before???

**Comment by rusty-snake** [comment]
Is there anything in your syslog? Does it work with `--noprofile`? What's your firejail version? Do you have a globals.local?

**Comment by MRF316** [comment]
Firejail is the latest...the other questions are a bit over my head ://)

**Comment by rusty-snake** [comment]
> Firejail is the latest

latest from ubuntu repositories, latest release, latest LTS release, latest from git. There is not the single-one latest firejail. What version is shown by `firejail --version`? 0.9.64.4 is the latest release which is usually what "latest" means.

> Is there anything in your syslog?

Open a terminal and watch `journalctl --boot --pager-end --follow` while you reproduce this.

> Does it work with --noprofile?

Can you reproduce this with `firejail --noprofile cmus`?

**Comment by MRF316** [comment]
It works using  firejail --noprofile cmus

**Comment by MRF316** [comment]
version 0.9.52-2 from synaptics package manager

**Comment by rusty-snake** [comment]
0.9.52 is very old. Which version of Mint do you run (ubuntu 18.04 based)? And which version of pulseaudio? Maybe `firecfg --fix-sound` helps here.

**Comment by MRF316** [comment]
This did not help
firecfg --fix-sound

**Comment by MRF316** [comment]
https://sendvid.com/29735550

**Comment by rusty-snake** [comment]
0.9.52 is very old and misses the fixes from 3,5 years.
Try `sudo sh -c 'echo "private-etc machine-id" > /etc/firejail/cmus.local'`.

**Comment by MRF316** [comment]
It worked! What exactly did that command do?

**Comment by rusty-snake** [comment]
Filesystem: It creates `/etc/firejail/cmus.local` (which is `include`d at the top of cmus.profile) containing `private-etc machine-id`.
Firejail: It grants cmus access to `/etc/mchine-id` (which is required for PA).

**Comment by MRF316** [comment]
I have a ton to learn in Linux and Firejail!  I appreciate your help
If you watch one of the videos, i'm not able to install the latest version of FJ.

**Comment by rusty-snake** [comment]
You need to remove your old firejail-installation (`sudo apt remove --autoremove --purge firejail firejail-profiles`) first. Then you can install the new one (`sudo dpkg --install $HOME/Downloads/firejail*.deb`).

**Comment by MRF316** [comment]
Thanks! what is the latest version of Firetools?

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firetools/releases/tag/0.9.64

**Comment by MRF316** [comment]
> https://github.com/netblue30/firetools/releases/tag/0.9.64

Will this re-install the latest version of FJ?

**Comment by MRF316** [comment]
After installing Firetools, I rebooted and it wouldn't open at all. I had to un-install it, but I still have Firejail.
Should I uninstall Firejail first, then install Firetools?

**Comment by MRF316** [comment]
I am sorry for going off subject a bit...when I uninstalled the latest version of FJ, then installed the latest version of FT... thinking the latest version of Firejail and Firetools will be installed. I rebooted, and Firetools still wouldn't open, so at the moment I don't have either one installed.

**Comment by rusty-snake** [comment]
Sorry, I can't help you with firetools (never used it). Are there any error if you start it from a terminal?

**Comment by MRF316** [comment]
> Sorry, I can't help you with firetools (never used it). Are there any error if you start it from a terminal?

Nope

**Comment by MRF316** [comment]
> Sorry, I can't help you with firetools (never used it). Are there any error if you start it from a terminal?

firetools: /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5: version `Qt_5.11' not found (required by firetools)

**Comment by rusty-snake** [comment]
Looks like this firetools package requires Qt 5.11 but Ubuntu 18.04 has only 5.9.

**Comment by MRF316** [comment]
I don't use FT very often, so for now i'll just use the latest version of FJ.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
