### ISSUE TITLE
Cleanup environment variables

### ISSUE THREAD

**Issue by FedericoCeratto** [netblue30/firejail#417]
firejail should be able to unset environment variables on start, maybe with a way to whitelist some variables.

Steps to reproduce: 
`
export HELLO=WORLD; 
firejail env
`

**Comment by netblue30** [comment]
I'll bring in whitelisting for env variables.

**Comment by netblue30** [comment]
I added --rmenv=name to remove unwanted variables

**Comment by ndbroadbent** [comment]
I am running a web application where my secrets (e.g. API keys) are stored in environment variables. I wanted to use firejail to sandbox some shell commands, and they don't need access to any of these variables.

I figured out that you can do this with `env -i`:

```
firejail --force --noprofile -- env -i <command>
```

(Just posting a comment here in case someone else sees this.)
