### ISSUE TITLE
Firejail erases javascript whitelist in Chromium

### ISSUE THREAD

**Issue by MRF316** [netblue30/firejail#4171]
This whitelist is gone every time I create it and then open a sandboxed chromium.

https://i.imgur.com/U0bNVbo.png

**Comment by rusty-snake** [comment]
Only the JS whitelist, nothing else? Everything else is kept? Where/How does it save the whitelist?

**Comment by MRF316** [comment]
Please disregard this. It's working now, i'm not sure what the issue was.
