### ISSUE TITLE
gnome-calculator hangs with 100% CPU

### ISSUE THREAD

**Issue by dsprenkels** [netblue30/firejail#4173]
Write clear, concise and in textual form.

**Bug and expected behavior**

On my computer starting `gnome-calculator` with firejail on (i.e., `firejail --profile=/etc/firejail/gnome-calculator.profile /usr/bin/gnome-calculator`) results in no window appearing and `gnome-calculator` running in the background with 100% CPU, until terminated manually.

**No profile and disabling firejail**

Running `firejail --noprofile /usr/bin/gnome-calculator` results in the program working correctly.

**Reproduce**
1. Run in bash `firejail --profile=/etc/firejail/gnome-calculator.profile /usr/bin/gnome-calculator

**Environment**

```
# Output of lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

# Output of firejail --version
firejail version 0.9.64.4

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- networking support is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-cache and tmpfs as user enabled
	- SELinux support is disabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

**Additional context**

I started commenting out lines from the profile, and seeing if I could get it to work. The bug was fixed when commenting `include disable-shell.inc` and `private-bin gnome-calculator`.

The resulting (fixed) profile:

[gnome-calculator.profile.txt](https://github.com/netblue30/firejail/files/6279351/gnome-calculator.profile.txt)

I do not know *why* `gnome-calculator` seems to need a shell in my environment, and what is different in my setup that this bug is being triggered. Though I'm happy to provide extra information.

**Checklist**
 - [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile. (n/a)
 - [x] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [x] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

<details><summary> debug output </summary>

```
OUTPUT OF `firejail --profile=/etc/firejail/gnome-calculator.profile /usr/bin/gnome-calculator`

(gnome-calculator:7): dbind-WARNING **: 16:26:24.661: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-F2n3hxZVuD: No such file or directory

** (gnome-calculator:7): WARNING **: 16:26:24.670: currency-provider.vala:234: Failed to read exchange rates: Failed to open file “/home/daan/.cache/gnome-calculator/rms_five.xls”: No such file or directory

** (gnome-calculator:7): WARNING **: 16:26:24.670: currency-provider.vala:376: Cannot use ECB rates as don't have EUR rate
```

</details>

**Comment by rusty-snake** [comment]
Is `/usr/bin/gnome-calculator` a shell script in Arch?

Does it work with 

```
include allow-bin-sh.inc
include disable-shell.inc
private-bin gnome-calculator,sh
```




BTW: I read your title as "gnome-calculator does not (start with 100% CPU)" instead of "gnome-calculator does (not start) with 100% CPU". Maybe "gnome-calculator does not start, consuming 100% CPU" would be more clear.

**Comment by glitsj16** [comment]
I've reinstalled gnome-calculator on my Arch Linux box to test this. For now I cannot reproduce.

> ** (gnome-calculator:7): WARNING **: 16:26:24.670: currency-provider.vala:234: Failed to read exchange rates: Failed to open file “/home/daan/.cache/gnome-calculator/rms_five.xls”: No such file or directory
** (gnome-calculator:7): WARNING **: 16:26:24.670: currency-provider.vala:376: Cannot use ECB rates as don't have EUR rate

These warnings stem from gnome-calculator's 'Financial Mode', relying on currency exchange rates. As those rates fluctuate GC tries to cache them. It's not uncommon to see these warnings. They usually go away when caching succeeded until they are refreshed (controlled by a pref that comes with 'never', 'daily' or 'weekly'). This functionality is working fine for me with the current gnome-calculator.profile.

> I started commenting out lines from the profile, and seeing if I could get it to work. The bug was fixed when commenting include disable-shell.inc and private-bin gnome-calculator.

In your gnome-calculator.profile.txt I see `#caps.drop all` too. Is this a leftover from your attempt to fix whatever is happening to GC? Or do you actually need to have that commented too for the app to work?

**Comment by jose1711** [comment]
Arch Linux x86_64 here too + cannot reproduce the issue

**Comment by glitsj16** [comment]
Thanks for clearing things up and providing the logs. I can't immediately spot anything fishy in those. Do you have anything in your globals.local that might interfere? Also, the gnome-calculator package on Arch Linux contains two executables in /usr/bin: `gnome-calculator` and `gcalccmd.` The latter has its own separate firejail profile BTW. And then there's `gnome-calculator-search-provider` in /usr/lib. So here's another 'wild' guess to try:
```
include allow-bin-sh.inc
include disable-shell.inc
private-bin gcalccmd,gnome-calculato*,sh
```

**Comment by rusty-snake** [comment]
Does `firejail --build gnome-calculator` show anything interesting in the generated `private-bin` line?

**Comment by dsprenkels** [comment]
Ok. After adding this line:

```
private-bin gcalccmd,gnome-calculato*,sh
```

it worked. But when I started removing gcalccmd and other parts it kept working, until I had:

```
private-bin gnome-calculator,sh
```

When I looked at the line that I used previously: `private-bin gnome-calculator, sh, bash`.
I was unaware that the extra spaces after the commas would break this line.

Removing that single space before `sh` fixed the issue. Though I still do not know why on my setup `gnome-calculator` needs a shell.

**Comment by glitsj16** [comment]
> I was unaware that the extra spaces after the commas would break this line.

Extra spaces indeed break several of firejail's options. Too bad you had to discover this the hard way. I for one also missed it in trying to figure out what was happening on your system. Lesson learned all round I guess.

> Though I still do not know why on my setup gnome-calculator needs a shell.

Can't explain that either. Looking at your posted gnome-calculator.debug-with-profile.log once more, the only override we haven't looked at yet is `globals.local.` Anything in there that might be related?

**Comment by dsprenkels** [comment]
My `globals.local`'s content is only:

```
noblacklist /volume1/daan
```

I don't think that should matter.

**Comment by dsprenkels** [comment]
> > I was unaware that the extra spaces after the commas would break this line.
> 
> Extra spaces indeed break several of firejail's options. Too bad you had to discover this the hard way. I for one also missed it in trying to figure out what was happening on your system. Lesson learned all round I guess.

Would it maybe be an idea to add a warning when this occurs?

**Comment by glitsj16** [comment]
That one line globals.local is indeed irrelevant in this context, what keeps the hunt ongoing for why you need sh in the first place.

> Would it maybe be an idea to add a warning when this occurs?

That sure is a sound idea. I'll add the `enhancement` tag to this to attract more attention to such a feature. Fingers crossed and if you ever find out why your gnome-calculator needs sh, please add that here.

**Comment by rusty-snake** [comment]
FTR: Spaces in files/paths in firejail profiles need no escape because they are treated as any other char. Therefore `private-bin gnome-calculator, sh` tells firejail to create a private-bin with `gnome-calculator` and ` sh` (leading space). That's the expected and wanted behaviour (ATM). However files starting/ending with a space is very uncommon because you can see it depending on the display context. Showing an error for these case should not break any real existing case.

**Comment by dsprenkels** [comment]
Ok. I narrowed down the bug to https://github.com/libproxy/libproxy/blob/cd619d3e9d683237f6317f979d5c6a7290d7e429/libproxy/modules/config_gnome3.cpp#L128-L161, in particular this loop: https://github.com/libproxy/libproxy/blob/cd619d3e9d683237f6317f979d5c6a7290d7e429/libproxy/modules/config_gnome3.cpp#L158-L160

I may look into the cause of the bug a bit more; or just open an issue in the libproxy repo. In any case, feel free to close this issue.

**Comment by rusty-snake** [comment]
Call to `popen2`: https://github.com/libproxy/libproxy/blob/cd619d3e9d683237f6317f979d5c6a7290d7e429/libproxy/modules/config_gnome3.cpp#L147
`execl` `/bin/sh`: https://github.com/libproxy/libproxy/blob/cd619d3e9d683237f6317f979d5c6a7290d7e429/libproxy/modules/config_gnome3.cpp#L101

**Comment by dsprenkels** [comment]
My `gsettings list-recursively org.gnome.system.proxy` contents:

```
org.gnome.system.proxy ignore-hosts ['localhost', '127.0.0.0/8', '::1']
org.gnome.system.proxy use-same-proxy true
org.gnome.system.proxy mode 'none'
org.gnome.system.proxy autoconfig-url ''
org.gnome.system.proxy.http use-authentication false
org.gnome.system.proxy.http enabled false
org.gnome.system.proxy.http authentication-password ''
org.gnome.system.proxy.http port 8080
org.gnome.system.proxy.http host ''
org.gnome.system.proxy.http authentication-user ''
org.gnome.system.proxy.https port 0
org.gnome.system.proxy.https host ''
org.gnome.system.proxy.ftp port 0
org.gnome.system.proxy.ftp host ''
org.gnome.system.proxy.socks port 0
org.gnome.system.proxy.socks host ''
```

I patched libproxy to provide me with some output to actually test that it is actually that specific while loop that is breaking. It is.
However, when I run `gnome-calculator` outside of a sandbox, it never gets called.

I am currently starting `gnome-calculator` and then attaching to it with gdb from a different shell using root permissions. However, I am too late to debug the beginning of the program this way. Do some of you have any advice on how to run gdb directly inside firejail?

**Comment by dsprenkels** [comment]
Additionally: I checked that the call to `execl` actually fails (it does). So I guess adding a check in that file to see if `sh` exists, before executing it, should probably fix the 100% CPU error. Though it would still be unclear why (in my obscure case) `gnome-calculator` actually needs to start `/usr/libexec/pxgsettings`, while in other setups it doesn't.

**Comment by rusty-snake** [comment]
> Though it would still be unclear why (in my obscure case) gnome-calculator actually needs to start /usr/libexec/pxgsettings, while in other setups it doesn't.

I did not even have this file / libproxy insallted. @glitsj16 you?

**Comment by glitsj16** [comment]
> I did not even have this file / libproxy insallted. @glitsj16 you?

No trace of /usr/libexec/pxgsettings on my Arch. I do have libproxy installed as a dependency for qt5-base, but that package contains /usr/lib/pxgsettings, not that libexec path

```
$ pacman -Q libproxy
libproxy 0.4.17-1
```

@dsprenkels Are you sure you are running a fully updated Arch Linux?

**Comment by dsprenkels** [comment]
> @dsprenkels Are you sure you are running a fully updated Arch Linux?

I am sure I tested this using an updated Arch installation. It's weird.

```
12:36:41 [daan:~] 127 $ pacman -Qo /usr/libexec/pxgsettings
error: No package owns /usr/libexec/pxgsettings
```

Ok, this is probably a problem. Let me investigate this further.

**Comment by dsprenkels** [comment]
I will close this issue for now. I feel bad exhausting your time tracking down such an obscure bug.

I will try investigating further myself, and report back if I find a cause or fix.

**Comment by jserafim** [comment]
I'm having this exact issue, except that my environment is a bit different:
```
# Output of lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

# Output of firejail --version
firejail version 0.9.70

Compile time support:
	- always force nonewprivs support is disabled
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- IDS support is enabled
	- networking support is enabled
	- output logging is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-cache and tmpfs as user enabled
	- SELinux support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

The quick workaround I'm using to avoid this:
```
$ cat ~/.config/firejail/gnome-calculator.profile
private-bin gnome-calculator,sh
ignore include disable-shell.inc
include /etc/firejail/gnome-calculator.profile
```

**Comment by rusty-snake** [comment]
> ```
> $ cat ~/.config/firejail/gnome-calculator.profile
> private-bin gnome-calculator,sh
> ignore include disable-shell.inc
> include /etc/firejail/gnome-calculator.profile
> ```

OT: Use locals
