### ISSUE TITLE
Document how to enable browser access to native Gnome connector (extensions.gnome.org)

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#4177]
Default profile for Chrome/Firefox disables access to native Gnome connector and making extensions.gnome.org actions like listing extensions, installing, enabling etc impossible.

It would be great if profiles mentios what needs to be done in order to reenable this function for Gnome users. Here's a suggestion for Chrome:

into `chromium-common.profile`
```
# Add the next 3 lines to your chromium-common.local if you want Google Chrome/Chromium browser
# to have access to Gnome extensions (extensions.gnome.org) via browser connector
noblacklist ${PATH}/python3*
noblacklist /usr/lib/python3*
noblacklist /usr/lib64/python3*
```

And Firefox:

into `firefox.profile`:

```
# Add the next 7 lines to your firefox.local if you want Firefox to gain
# access to Gnome extensions (extensions.gnome.org) via browser connector
dbus-user.own org.gnome.ChromeGnomeShell
dbus-user.own org.gnome.Shell
dbus-user.own ca.desrt.dconf
dbus-user.own org.gtk.vfs.Daemon
noblacklist ${PATH}/python3*
noblacklist /usr/lib/python3*
noblacklist /usr/lib64/python3*
```

I have tested this on Arch Linux x86_64, rolling and current master.

**Comment by rusty-snake** [comment]
`talk` rules should be enough for all of them.
For cross-distro compatibility you should use `include allow-python3.inc`.

Fell free to open a PR with it.
