### ISSUE TITLE
Mumble does not start

### ISSUE THREAD

**Issue by byteme-git** [netblue30/firejail#4181]
Write clear, concise and in textual form.

**Bug and expected behavior**
Mumble crashes on start, without an error message or a window showing up. 

**No profile and disabling firejail**
This fixes the bug. Renaming the Profile as well as starting mumble with the --noprofile option.

**Reproduce**
1. Start Mumble with the up to date firejail profile
2. watch how nothing happens

**Environment**
Manjaro Linux 5.10.26 (KDE)
Apparmor 3.0.1 (apparmor firejail support is enabled)
Firejail version 0.9.64.4

**Logs**

<details><summary>terminal output</summary>

```
Reading profile /etc/firejail/mumble.profile
Reading profile /etc/firejail/globals.local
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-shell.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 18723, child pid 18724
1 program installed in 19.47 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: not remounting /run/user/1000/gvfs
Warning: cleaning all supplementary groups
Blacklist violations are logged to syslog
Child process initialized in 142.54 ms
<W>2021-04-11 19:47:31.904 JackAudioSystem: unable to open client due to 1 errors:
<W>2021-04-11 19:47:31.904 JackAudioSystem: JackFailure - overall operation failed
<W>2021-04-11 19:47:32.909 ALSAInit: No cards found, not initializing
<D>2021-04-11 19:47:32.910 libopus 1.3.1 from libopus.so.0
<W>2021-04-11 19:47:32.913 CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
<W>2021-04-11 19:47:32.914 CELT bitstream 80000010 from /usr/lib/mumble/libcelt0.so.0.11.0
<W>2021-04-11 19:47:32.914 Theme: "Mumble"
<W>2021-04-11 19:47:32.914 Style: "Dark"
<W>2021-04-11 19:47:32.914 --> qss: ":themes/Mumble/Dark.qss"
<W>2021-04-11 19:47:32.916 Locale is "en_US" (System: "en_US")
<W>2021-04-11 19:47:32.953 Database SQLite: "3.35.3"
<W>2021-04-11 19:47:32.970 Updating application palette
<W>2021-04-11 19:47:32.991 GlobalShortcutX: Using XI2 2.3
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: Keine Berechtigung
libGL error: failed to open /dev/dri/card0: Keine Berechtigung
libGL error: failed to load driver: iris

Parent is shutting down, bye... </summary>
```

</details>

The problem seems to be this error:

libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: Keine Berechtigung
libGL error: failed to open /dev/dri/card0: Keine Berechtigung
libGL error: failed to load driver: iris

Upon that point in loading the program the output is identical (with and without fj) and after this the program crashes.

**Fixes that didn't work**
- i looked up the permissions of /dev/dri/card0: crw-rw----+ the owner is root. 
- i whitelisted /dev/dri/card0 in the mumble.profile and as that did not solve it i tried "noblacklist" without any succes
- then i thought maybe firejail had no access to that 'file', so i added rw acces into the apparmor profile for firejail, but hat did not fix the problem.

---

**EDIT by @rusty-snake:** fix code-block

**Comment by rusty-snake** [comment]
> The problem seems to be this error:
> 
> ```
> libGL error: MESA-LOADER: failed to retrieve device information
> libGL error: Version 4 or later of flush extension not found
> libGL error: failed to load driver: i915
> libGL error: failed to open /dev/dri/card0: Keine Berechtigung
> libGL error: failed to open /dev/dri/card0: Keine Berechtigung
> libGL error: failed to load driver: iris
> ```

`/dev/dri` is blacklisted by `no3d`, does it work if you `ignore no3d`?

There are more program which show messages like this, especially under wayland, I'm not so sure that this is the cause.

> Reading profile /etc/firejail/globals.local

What's in it?

> - i looked up the permissions of /dev/dri/card0: crw-rw----+ the owner is root.
> - i whitelisted /dev/dri/card0 in the mumble.profile and as that did not solve it i tried "noblacklist" without any succes
> - then i thought maybe firejail had no access to that 'file', so i added rw acces into the apparmor profile for firejail, but hat did not fix the problem.

On system with systemd it is normal to have no DAC access to it as regular user. Owned by root it is on very system.

**Comment by byteme-git** [comment]
@rusty-snake **commenting out no3d in mumble.profile** worked. Program starts as expected and the error message is not shown in the log. Thank u!

**Comment by byteme-git** [comment]
@rusty-snake **commenting out no3d in mumble.profile** worked. The program starts and the error does not appear in the logs anymore. Thank u!
