### ISSUE TITLE
Splitting --no-sound into --no-speaker and --no-microphone

### ISSUE THREAD

**Issue by HulaHoopWhonix** [netblue30/firejail#419]
Oz is planning to make pulseaudio restrictions more fine-grained to allow more secure profiles.

Controlling speaker and microphone restrictions separately allows restricting microphone access to a browser (which it has no business accessing) while keeping speaker access for usability.

**Comment by netblue30** [comment]
Yes, these features are highly desirable. Do they have a description how they do it? How did you find out about it?

**Comment by HulaHoopWhonix** [comment]
Read it here:

https://github.com/subgraph/oz/issues/35

Unfortunately no details are given and nothing implemented yet to look at.

**Comment by netblue30** [comment]
Thanks, I'll keep an eye on it.

**Comment by netblue30** [comment]
The bad guy can still go directly to ALSA and bypass PulseAudio. The only way I can see it in this moment is to use private-dev and disable all the sound system.

**Comment by HulaHoopWhonix** [comment]
Orthogonal info:

As part of Flatpak's isolation efforts new low-level permission hooks were added to PulseAudio to allow the microphone vs speaker denial granularity:

Very useful resources linked from the ticket:

https://github.com/flatpak/xdg-desktop-portal/issues/27

I will tell them about the ALSA loophole you talk about.

**Comment by netblue30** [comment]
Thanks for the information. They still have the problem with ALSA. Quite a number of distributions install ALSA instead of PulseAudio (Lubuntu for example). And there are also users replacing Pulse with ALSA after installing a Linux distro.

I don't see how this will ever get solved without some heavy lifting inside the kernel.

**Comment by HulaHoopWhonix** [comment]
Flatpak devs share more on how they manage to lock down access to pulseaudio while dealing with ALSA.

Please check it out:

https://github.com/flatpak/xdg-desktop-portal/issues/27#issuecomment-233057825

**Comment by netblue30** [comment]
Let's wait for the to fix PulseAudio.
