### ISSUE TITLE
brave profile blocks Tor

### ISSUE THREAD

**Issue by loveshack** [netblue30/firejail#4190]
The Brave browser can open windows with Tor, but that's blocked by the firejail brave profile -- it just hangs trying to connect.  (It's OK for me without the profile, of course.)

I'm confused because it's presumably due to this (repeating) error
```
LaunchProcess: failed to execvp:
/home/****/.config/BraveSoftware/Brave-Browser/biahpgbdmdkfgndcmfiipgcebobojjkp/1.0.16/tor-0.4.5.7-linux-brave-1
[352:358:0413/215037.078723:ERROR:tor_launcher_impl.cc(203)] tor exit (127)
```
despite brave.profile containing
```
# TOR is installed in ${HOME}
ignore noexec ${HOME}
```
I'm happy to take suggestions for debugging if necessary.

Versions: firejail 0.9.64.4 (but it doesn't look as though there's any relevant profile change since) and brave 1.22.71 on Debian 10.

**Comment by glitsj16** [comment]
Might be the `apparmor` option in /etc/firejail/chromium-common.profile. A quick and dirty check would be adding `ignore apparmor` to a `chromium-common.local` file. Or in a `brave.local` file if you want to keep any other chromium-based browsers you might use with an intact profile.

_If_ the test confirms it is AppArmor that's the culprit, we can assist in designing a proper way to proceed that doesn't rely on disabling the apparmor option. That would involve making changes to your /etc/apparmor.d/local/firejail-default cfr. what the `torbrowser-launcher.profile` advises when you've got that installed under your ${HOME}. But let's confirm if disabling apparmor indeed makes TOR work before diving into that.

**Comment by glitsj16** [comment]
UPDATE:
In the mean time I've installed Brave and can reproduce this issue. As I suspected the `apparmor` option in the included chromium-common.profile is responsible for blocking access to tor. I'll prepare a PR to fix this but until that gets into a new release on your Debian box here's what you can do right now. In fact, you have two options: (1) either add a `brave.local` file containing `ignore apparmor` OR (2) allow access to the tor path used by Brave in /etc/apparmor.d/local/firejail-default. The latter route assumes you have a fully configured and enabled AppArmor setup on your machine - consult the Debian wiki for that if you need to double-check stuff.

If you decide to go for this second option, compare the below /etc/apparmor.d/local/firejail-default example. You might already have extra rules in there. Just make sure to add a line for the brave path (uncommented). Once that's done, remove any existing AppArmor cache from your system and reboot. I've done the same for testing and confirmed the Brave + Tor setup works as expected via https://check.torproject.org.

```
# Site-specific additions and overrides for 'firejail-default'.
# For more details, please see /etc/apparmor.d/local/README.

# Here are some examples to allow running programs from home directory.
# Don't enable all of these, just pick a specific one or write a custom rule
# instead as done below for torbrowser-launcher.
#owner @HOME/** ix,
#owner @HOME/bin/** ix
#owner @HOME/.local/bin/** ix

# Uncomment to support apparmor for brave's integrated Tor functionality
owner @{HOME}/.config/BraveSoftware/Brave-Browser/biahpgbdmdkfgndcmfiipgcebobojjkp/*/** ix,

# Uncomment to opt-in to apparmor for torbrowser-launcher
#owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/** ix,
```

HTH

**Comment by loveshack** [comment]
I had replied by mail to say thanks for the excellent response, but that hasn't got through for some reason. Anyway, thank you!

**Comment by glitsj16** [comment]
@loveshack No worries, it's not the first time I see differences between GitHub's web interface and mail correspondence. Glad to read this issue is fixed. It's thanks to your reporting that we became aware of the Brave + Tor + AppArmor situation, so thanks again for bringing it out here! Happy sandboxing.

I'll close this issue now, but feel free to reopen if you encounter other bumps on the road.
