### ISSUE TITLE
Bug: Keyboard input doesn't work in VS Code when configured with desktop integration via: "sudo firecfg". Works upon "sudo firecfg --clean".

### ISSUE THREAD

**Issue by NOVATechnocrat** [netblue30/firejail#4211]
Problem:

VS Code does not permit keyboard input in to the code editor when firejail is integrated in to the desktop via "sudo firecfg". When I do a "sudo firecfg --clean" it works again. It's directly related to firejail.

Reproduce:

1. Install firejail and then integrate it with the desktop via "sudo firecfg".
2. Then open VS Code through the DE (not via the terminal).
3. Try to type in the code editor. Can't. It will permit keyboard control if you select the file tree etc which is very peculiar.
4. Then try to open VS Code directly (outside of the jail) via terminal and keyboard then works.
5. Then do a  "sudo firecfg --clean" and restart the app through the DE, note it works.

System info:

lsb_release -a      
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy

cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 firejail --version                                                   127 ↵
firejail version 0.9.62.4

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled

**Comment by rusty-snake** [comment]
Does it work with `--noprofile`? Do you see any errors if you start if from a terminal? Are there any error in the syslog? Which XIM?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
