### ISSUE TITLE
Obsidian appimage wont start.

### ISSUE THREAD

**Issue by chomwitt** [netblue30/firejail#4214]
I downloaded from here :     https://obsidian.md/
System:   Kernel: 4.19.0-16-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 Desktop: KDE Plasma 5.14.5  Distro: Debian GNU/Linux 10 (buster) 

$ sudo sysctl kernel.unprivileged_userns_clone=1  
$ firejail --appimage ./Obsidian-0.11.3.AppImage 
Mounting appimage type 2
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file

** Note: you can use --noprofile to disable default.profile **

Parent pid 31946, child pid 31949

**     Warning: dropping all Linux capabilities     **
Child process initialized in 106.64 ms

Parent is shutting down, bye...
AppImage unmounted

**Comment by chomwitt** [comment]
$ firejail --noprofile --appimage ./Obsidian-0.11.3.AppImage 
Mounting appimage type 2
Parent pid 32678, child pid 32681

**     Warning: dropping all Linux capabilities     **
Child process initialized in 60.97 ms
2021-04-25 08:28:10 Loading updated app package /home/chomwitt/.config/obsidian/obsidian-0.11.13.asar
xdg-mime: application argument missing
Try 'xdg-mime --help' for more information.
.... gtk warnings ... app related messages and it starts.

I dont know what a profile is. What i lose if i start with **--noprofile**  ?

**Comment by rusty-snake** [comment]
Obsidian doesn't have a profile yet. Request one in #1139 (as already happen https://github.com/netblue30/firejail/issues/1139#issuecomment-761523388 and following) or write it yourself.

**Comment by rusty-snake** [comment]
> I dont know what a profile is. What i lose if i start with --noprofile ?

> `--noprofile` is close to not using firejail at all.

You stay with a pid-namespace and a minimal (hardcoded) blacklist (mostly /proc and /sys). And nnp / disable-mnt if you enforce them in firejail.config.
