### ISSUE TITLE
Digikam - unable to customize toolbars

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#4218]
Looks like with the current `digikam` profile it is unable to customize (add/remove icons) application toolbar. The following is shown in the console window:
```
kf.xmlgui: Could not write to "/home/USER/.local/share/kxmlgui5/digikam/digikamui5.rc"
kf.xmlgui: Unhandled container to remove :  Digikam::DigikamApp
```

**Reproduce**
1. Run `digikam`
2. Rightclick toolbar - Configure Toolbars - remove or add any action
3. Click Apply and or OK

**Environment**
 - Arch Linux x86_64, rolling
 - `firejail version 0.9.65`, `r7268.749c21afc-1`

**Additional context**
Other context about the problem like related errors to understand the problem.

**Checklist**
 - [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [x] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [x] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by rusty-snake** [comment]
Should be fixed. Thanks for reporting.

For reference: #3493 and 319f2dc8
