### ISSUE TITLE
private-bin doesn't use /usr/local/bin

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#422]
And that's a cool thing, except that it doesn't seem to should do this, because `/usr/local/bin` isn't in `fs_bin.c`'s paths array.

What I wanted to do is private-bin a program that only resides in my /usr/local/bin and not any of those in the paths array. So that program naturally wasn't found and firejail told me that it's ignoring private-bin for that reason.

So I added /usr/local/bin to the paths array and it worked.
At the same time I noticed something weird. I have another program in both /usr/bin and /usr/local/bin. Before I made any changes to the array, the program from /usr/local/bin was copied to the new bin dir. When I added /usr/local/bin, the version from /usr/bin was copied.

Again;
- no `/usr/local/bin` in paths, but `/usr/local/bin` version was used, while debug said `/usr/bin`. (woot)
- with `/usr/local/bin` appended, `/usr/bin` version was used, debug says `/usr/bin`. (correct)
- with `/usr/local/bin` prepended, `/usr/local/bin` version was used, debug says `/usr/local/bin`, too. (correct)

**Comment by avoidr** [comment]
Now I see that you already append paths from the PATH variable, but they are two different paths variables.

**Comment by avoidr** [comment]
And now I know why it copies `/usr/bin` and still uses the `/usr/local/bin` version. `/usr/local/bin` is not modified, except when I add `/usr/local/bin` to the paths variable, then it's the same as `/usr/bin`.
So now there are still both versions (and my $PATH prefers `/usr/local/bin`).

I hope this makes enough sense.

**Comment by netblue30** [comment]
I'll look into it, thanks.

**Comment by netblue30** [comment]
I added /usr/local/bin in the list in the first position. It will take precedence over /usr/bin or /bin.

**Comment by avoidr** [comment]
Main problem confirmed fixed.

What about `fs.c:504,509` and `paths.c:78`? Does anything need to be adjusted there, too? Just making sure nothing is forgotten.

Now, the fix is static priority. Would it be good to build the paths from $PATH, too? So that user's preferences are honored still.

**Comment by avoidr** [comment]
There is also /usr/local/sbin and that's why I think it would be good to use $PATH.

**Comment by netblue30** [comment]
Yes, I added /usr/local/sbin to the list. We cannot allow $PATH in this case, because this will let the user replace system executables with his own version, and take advantage of SUID to attack the system. We can allow only directories owned by root user.

**Comment by avoidr** [comment]
My main idea was to use $PATH to get the directory priorities as the user wishes, while ignoring $HOME binaries.

**Comment by netblue30** [comment]
We know about $HOME, but the user can sneak in files from some other places, and it is difficult to process correctly in a SUID executable. This is why I went for a fixed order, with /usr/local/bin before /usr/bin and /bin.

**Comment by avoidr** [comment]
Then how about using $PATH to only get the correct order of known paths (those we already have hardcoded), and not including new, foreign paths?

**Comment by netblue30** [comment]
Sure, I'll put it in.

**Comment by avoidr** [comment]
Awesome.
With /usr/local/bin in I can also contribute suckless.org tools profiles, since those are ideally compiled from source. That's how I found that issue, too.

**Comment by netblue30** [comment]
Sure, I'll put it in over the weekend.
