### ISSUE TITLE
Firecfg does not patch discord.desktop

### ISSUE THREAD

**Issue by sak96** [netblue30/firejail#4235]
In archlinux firecfg doesn't overwrite `/usr/share/applications/discord.desktop` **exec** field to `/usr/local/bin/discord`.
This is because the `/usr/share/applications/discord.desktop`  is symlink to `/opt/discord/discord.desktop`

**Bug and expected behavior**
- firecfg should update discord.desktop file
- firecfg did not update discord.desktop file

**No profile and disabling firejail**
N/A

**Reproduce**
1. installed discord and firejail in archlinux using pacman
1. run `i3-dmenu-desktop --dmenu "echo Discord"`. you should be able to use `xdg-open /usr/share/applications/discord.desktop` as well.
1. run `firejail --list`  and find discord is not running

**Environment**
 <details>
<summary>Linux distribution and version  Arch linux </summary>
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
</details>
<details>
<summary>Firejail version == 0.9.64.4</summary>

 ```
 firejail version 0.9.64.4

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- networking support is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-cache and tmpfs as user enabled
	- SELinux support is disabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

</details>

**Additional context**

- the firecfg patched binary is generated at `/usr/local/bin/discord`.
- the desktop file exec `/usr/bin/discord`.
- the desktop file is a link.
    ```zsh
    $ ls -l /usr/share/applications/discord.desktop
    lrwxrwxrwx root root 28 B Wed Mar 24 06:39:37 2021 /usr/share/applications/discord.desktop ⇒ /opt/discord/discord.desktop
    ```
- **IMPORTANT!!!** firecfg skips links as per [this](https://github.com/netblue30/firejail/blob/0bbbe2566a900073a52b7b12b607b368fadcfcac/src/firecfg/desktop_files.c#L171).

**Checklist**
 - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by sak96** [comment]
workaround 
```bash
cp /usr/share/applications/discord.desktop ~/.local/share/applications
sed -e "s%/usr/bin/discord%/usr/bin/local/discord%" -i ~/.local/share/applications/discord.desktop
```

**Comment by rusty-snake** [comment]
> workaround
> 
> ```shell
> cp /usr/share/applications/discord.desktop ~/.local/share/applications
> sed -e "s%/usr/bin/discord%/usr/bin/local/discord%" -i ~/.local/share/applications/discord.desktop
> ```

simpler: `sed "s;Exec=/usr/bin/discord;Exec=discord;" /usr/share/applications/discord.desktop > ~/.local/share/applications/discord.desktop`

**Comment by s-a-p-i-e-n-s** [comment]
Is there anything new on a fix for this being implemented. The issue persists. The workarounds posted here work, however a fix would be greatly preferable!

**Comment by rusty-snake** [comment]
I think desktop_files.c is the place for this and also for #4018 and #2624. The last commit (ignoring update copyright commits) to it was on 2 Apr 2019 (_in a time before masks and "[Querdenken](https://en.wikipedia.org/wiki/Querdenken)"_). Personally I give up firecfg.

**Comment by s-a-p-i-e-n-s** [comment]
Unfortunately C is no language I would put in a PR myself.

**Comment by netblue30** [comment]
Fixed, thanks for the bug. If you still have problems, let us know!
