### ISSUE TITLE
Discord doesn't detect webcam with firejail

### ISSUE THREAD

**Issue by YShow** [netblue30/firejail#4236]
**Bug and expected behavior**
- Describe the bug.
Opening discord with firejail doesn't let it access the webcam
- What did you expect to happen?
Discord working with webcam

**Reproduce**
1. Run discord with discord profile
2. Try to use Video button
3. Webcam is not detected

**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`, `screenfetch` or `cat /etc/os-release`)
 LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20210429
Codename:       n/a 
 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`)
 firejail version 0.9.64.4
Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is disabled
        - private-home support is enabled
        - private-cache and tmpfs as user enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

**Checklist**
 - [ X] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [X ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [ X] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [X ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ X] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [X ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ X] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by rusty-snake** [comment]
FTR: #3634

Add `ignore novideo` to your discord.local.

Still open: should we it to discord(-common).profile? (@ all)
