### ISSUE TITLE
how to start to use "firejail firefox"?

### ISSUE THREAD

**Issue by clw1834104694** [netblue30/firejail#4238]
![image](https://user-images.githubusercontent.com/38728739/116990188-5b1cfc00-ad05-11eb-8dc1-4e849bae04b7.png)

**Comment by rusty-snake** [comment]
YOU DON'T WANT TO START FIREFOX AS ROOT.

-----

What does `which firejail` show? What does `ls -l "$(which firejail)"` show?

Which firejail version and distro?

**Comment by chiraag-nataraj** [comment]
@clw1834104694 how did you install `firejail`?

**Comment by clw1834104694** [comment]
> @clw1834104694 how did you install `firejail`?
![image](https://user-images.githubusercontent.com/38728739/117091064-bd6d0f80-ad8c-11eb-8544-165d01c3fd98.png)
![image](https://user-images.githubusercontent.com/38728739/117091079-cbbb2b80-ad8c-11eb-94df-905ef93bed7a.png)
sudo apt-get install firejail

**Comment by clw1834104694** [comment]
> YOU DON'T WANT TO START FIREFOX AS ROOT.
> 
> What does `which firejail` show? What does `ls -l "$(which firejail)"` show?
> 
> Which firejail version and distro?

https://github.com/netblue30/firejail/issues/4238#issuecomment-832372903

**Comment by chiraag-nataraj** [comment]
@clw1834104694 Why are you running everything as root? Can you run `firejail --debug gedit` **as your user** (**not** root)?

**Comment by clw1834104694** [comment]
&nbsp;&nbsp;
***@***.***:~$ firejail --net=eth0 firefox
Error: networking feature is disabled in Firejail configuration file

how to start the networking?
it is important to read the configuration file of the firejail in order to learn the realization of the tech of sandbox?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "netblue30/firejail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netblue30/firejail] how to start to use "firejail firefox"? (#4238)





 
YOU DON'T WANT TO START FIREFOX AS ROOT.
 
 
What does which firejail show? What does ls -l "$(which firejail)" show?
 
Which firejail version and distro?

**Comment by clw1834104694** [comment]
how to Set&nbsp;restricted-network&nbsp;to&nbsp;no&nbsp;in&nbsp;the file?
the file is too long,where is the part of the network.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 晚上11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [netblue30/firejail] how to start to use &quot;firejail firefox&quot;? (#4238)





  
Error: networking feature is disabled in Firejail configuration file
  
Set restricted-network to no in /etc/firejail/firejail.config.

**Comment by rusty-snake** [comment]
> the file is too long,where is the part of the network

I'm sure your editor has a search function.
(And JK the file isn't long `grep -c "^#" /etc/dnsmasq.conf`: 550, `grep -c "^#" /etc/firejail.config`: 113)

OT: Configure your email software to use normal spaces or send plain-text responses.

**Comment by clw1834104694** [comment]
download firetool but do not download firejail
why does not it work?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "netblue30/firejail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netblue30/firejail] how to start to use "firejail firefox"? (#4238)





 
YOU DON'T WANT TO START FIREFOX AS ROOT.
 
 
What does which firejail show? What does ls -l "$(which firejail)" show?
 
Which firejail version and distro?

**Comment by clw1834104694** [comment]
PID&nbsp; &nbsp;User&nbsp; &nbsp; &nbsp; RES(KiB) SHR(KiB) CPU%&nbsp; Prcs Uptime&nbsp; &nbsp; Command
61851 clw&nbsp; &nbsp; &nbsp; &nbsp;940048&nbsp; &nbsp;631584&nbsp; &nbsp;0.0&nbsp; &nbsp;9&nbsp; &nbsp; 00:34:45&nbsp; firejail /usr/bin/firefox

what dose the PID mean? it is not the ID of the process&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "陈李蔚"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月22日(星期六) 凌晨2:59
***@***.***&gt;;

主题:&nbsp;回复： [netblue30/firejail] how to start to use "firejail firefox"? (#4238)



download firetool but do not download firejail
why does not it work?




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "netblue30/firejail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netblue30/firejail] how to start to use "firejail firefox"? (#4238)





 
YOU DON'T WANT TO START FIREFOX AS ROOT.
 
 
What does which firejail show? What does ls -l "$(which firejail)" show?
 
Which firejail version and distro?

**Comment by rusty-snake** [comment]
> **Configure your email software to use normal spaces or send plain-text responses.**

**Comment by clw1834104694** [comment]
what does the PID mean in the list of firetool?
it is not process ID






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "netblue30/firejail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月1日(星期二) 晚上11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netblue30/firejail] how to start to use "firejail firefox"? (#4238)





  
Configure your email software to use normal spaces or send plain-text responses.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
