### ISSUE TITLE
Security Implications for User namespaces

### ISSUE THREAD

**Issue by HulaHoopWhonix** [netblue30/firejail#425]
User namespaces are described as a particularly risky kernel feature that has allowed privilege escalation in the past. I think its useful to keep around but its probably best avoided in supported profiles.

https://github.com/subgraph/oz/issues/11

**Comment by netblue30** [comment]
User namespace is more like a baseball bat. Imperfect, with its own problems, but works very well in some cases.

Firejail has support to disable various sandboxing features the user might find undesirable. You can do it at compile time (./configure --help) or at run time (man firejail-config). You can disable user namespaces, chroot, and a number of other features. So far I've heard complains about user namespace and networking.

**Comment by curiosity-seeker** [comment]
FWIW, user namespaces are [not supported](https://bugs.archlinux.org/task/36969) by Arch Linux, either, because of security considerations.

**Comment by HulaHoopWhonix** [comment]
Ah OK. You're aware of this topic: and discussed implications: https://github.com/netblue30/firejail/issues/9#issuecomment-129494347

I'll search harder next time :)
