### ISSUE TITLE
Possibility to use files that aren't in /etc for --private-etc

### ISSUE THREAD

**Issue by kadogo** [netblue30/firejail#426]
Hello, I think it would be nice if we can use files that aren't in /etc for --private-etc options.

Cheers.

**Comment by netblue30** [comment]
This will create a lot of security problems. I can let only existing files in /etc.

**Comment by kadogo** [comment]
You have maybe a solution when I will use a file in etc but that I have modify ?
Exemple, I will test some repo with yum but I not will modify my yum.conf in /etc so I think to modify it before and pass it to firajail.

**Comment by netblue30** [comment]
Some of the files there are very dangerous, for example the user can modify /etc/shadow and put a new root password there.

If you are running as root, you could use "firejail --bind" and replace your /etc directory with a totally new one.

**Comment by kadogo** [comment]
I will give a chance at the --bind option.
I would ask too if --chroot option will himself create /proc and /dev in the futur (or if there is some security issue too ?)

**Comment by netblue30** [comment]
chroot mount under /dev the real /dev directory, it just needs a directory defined for the mount point. /proc is mounted with the special /proc from the namespace.
