### ISSUE TITLE
discord logs out if opens twice.

### ISSUE THREAD

**Issue by sak96** [netblue30/firejail#4263]
Opening discord twice open two instance. The second one seems to logout itself.

**Bug and expected behavior**
- Discord logs out if opened twice.
- Second instance should not have opened.

**No profile and disabling firejail**
N/A

**Reproduce**
1. run discord twice without closing.
1. See two instance of discord
1. Second instance doesn't recognize your account.

**Environment**
 <details>
<summary>Linux distribution and version  Arch linux </summary>
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
</details>
<details>
<summary>Firejail version == 0.9.64.4</summary>

 ```
 firejail version 0.9.64.4

Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- firetunnel support is enabled
	- networking support is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-cache and tmpfs as user enabled
	- SELinux support is disabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

</details>

**Additional context**
using following `~/.config/firejail/discord.local` solves the issue.
```firejail
join-or-start discord
```

**Checklist**
 - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

<details><summary> debug output </summary>
N/A
</details>

**Comment by rusty-snake** [comment]
I would say send a PR
