### ISSUE TITLE
Open file dialog in Telegram

### ISSUE THREAD

**Issue by dmitryvakulenko** [netblue30/firejail#4265]
This is my [Telegram profile](https://github.com/netblue30/firejail/files/6447235/Telegram.txt)
Recently I found out I can't open any file or directory selection window. There aren't any error message or anything to help detect trouble. 
"noroot" options disabling make windows opened but this make totally ignored "private" option - I can see all my home directory.

OS - Linux Mint 20.1 Ulyssa with Cinnamon DE.

**Comment by rusty-snake** [comment]
Looks like telegrams file-open dialog uses desktop portals (and you portal implementation is broken with `noroot`). (OT: Does anybody know how you can control this for Qt?).

But why does telegram have access to `org.freedesktop.portal.Desktop`? Which firejail version do you use?

**Comment by dmitryvakulenko** [comment]
> Which firejail version do you use?

The last one.  0.9.64.4-1.
But the same behaviour was in Mint repo's version - 0.9.62

**Comment by rusty-snake** [comment]
There were a lot changes on master since 0.9.64.4. What are the results with this [telegram.profile](https://raw.githubusercontent.com/netblue30/firejail/3d3ba1952ab6c9a9faabb9da495aa10146a4e169/etc/profile-m-z/telegram.profile)?

Which desktop portal implementation and version do you use?

**Comment by dmitryvakulenko** [comment]
Looks like this profile works fine. Even when I added "private" option.
Desktop portal version 1.6.0-1. From Ubuntu Focal Fossa repository.

Thank you!

**Comment by rusty-snake** [comment]
I think we can close here as we do not need to make any changes to telegram.profile.

**Comment by dmitryvakulenko** [comment]
I experimented with profile and found out the main option to fix trouble is "dbus-user filter".
