### ISSUE TITLE
Landlock support mainlined in 5.13

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#4267]
Here is first Distribution with kernel 5.13

Please test in VM and play with landlock. 

https://sypalo.com/how-to-upgrade-ubuntu

https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.13-Landlock-Lands

**Comment by reinerh** [comment]
This is already tracked in #3992. Please don't open duplicates.
If you want an open discussion about it, consider using the "discussions" feature.
