### ISSUE TITLE
Conflict with jailtest utility

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#4268]
The new `jailtest` utility conflicts with a utility of the same name included in `uml-utilities` (Debian), `uml_utilities` (Fedora, Arch AUR).
They are installed in the same location (`/usr/bin/jailtest`). This means for packaging, that a `Breaks` relationship needs to be declared, which means that firejail can not be co-installed with the uml-utilities package. This is very user-unfriendly and should be avoided if possible. As it has not been released yet, avoiding a conflict is still possible.

Is this tool actually needed globally? Or would it be sufficient to have it in a private directory (like `/usr/lib/firejail/`, where other helper tools like fldd are located)?

If the tool really is supposed to be invoked by users manually, could we think of a different name to avoid a conflict?

Alternatively I'm also considering not shipping it in the Debian package.

Any opinions?

Ping @netblue30

**Comment by netblue30** [comment]
Thanks, I'll move it to "jailcheck". How do we check for collisions?

**Comment by kmk3** [comment]
@glitsj16 commented 2 days ago:

> firejailtest, firetest, jailcheck - just a few ideas (didn't check for any
> name collisions)...

@netblue30 commented 3 hours ago:

> Thanks, I'll move it to "jailcheck". How do we check for collisions?

On Arch, it can be done with with `pacman -F`:

```console
$ pacman -F firejail
community/firejail 0.9.64.4-1
    usr/bin/firejail
    usr/share/bash-completion/completions/firejail
$ pacman -F jailtest firejailtest firetest jailcheck
```

I doesn't check the AUR though.

And according to the [Pacman Rosetta][1], on Debian this can be done with:

```sh
apt-file list
```

[1]: https://wiki.archlinux.org/title/Pacman/Rosetta#Querying_specific_packages

**Comment by rusty-snake** [comment]
And for Fedora it is `dnf provides <PROGRAM|PATH>`.

```
$ en_US-locale dnf provides jailcheck
Error: No Matches found
```

**Comment by reinerh** [comment]
> And according to the [Pacman Rosetta](https://wiki.archlinux.org/title/Pacman/Rosetta#Querying_specific_packages), on Debian this can be done with:
> 
> ```shell
> apt-file search
> ```

Yes, that's correct. There is also no conflict in Debian:
```
$ apt-file search jailcheck
$
```

**Comment by netblue30** [comment]
jailcheck all set!
