### ISSUE TITLE
Unable to open X display when running firejail chromium command

### ISSUE THREAD

**Issue by Xwang1976** [netblue30/firejail#4282]
**Bug and expected behavior**
When I run `firejail chromium`

I get the following messages: 

```
Reading profile /etc/firejail/chromium.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: Warning: NVIDIA card detected, nogroups command disabled
Parent pid 9083, child pid 9084
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: Cannot confine the application using AppArmor.
Maybe firejail-default AppArmor profile is not loaded into the kernel.
As root, run "aa-enforce firejail-default" to load it.
Child process initialized in 185.45 ms
No protocol specified
[6:6:0516/013812.224391:ERROR:browser_main_loop.cc(1386)] Unable to open X display.

Parent is shutting down, bye...
```

**No profile and disabling firejail**
Nothing changes calling `firejail /usr/bin/chromium`.

Calling `firejail --noprofile /usr/bin/chromium` opens the program correctly.

I've noted that executing `xhost +` before running `firejail chromium` solves the issue, but I'm not sure if it is safe to do.

**Environment**
I'm running archlinux, with rootless xorg using sddm-git and kde.
firejail version 0.9.64.4

**Additional context**
The same issue happens with other programs too.
It seems as the only way to have it working correctly is by setting `xhost +`

Edit: Formatting.

**Comment by Xwang1976** [comment]
Running xhost SI:localuser:myusername solves the issue too and maybe it is safer tha xhost +
The fact is that till yesterday everything was working correctly.
I've "only" removed GDM and installed SDDM.
With GDM Xorg was alredy runned rootlessy

**Comment by rusty-snake** [comment]
Where is your Xauthority file (`echo $XAUTHORITY`)?

**Comment by Xwang1976** [comment]
When using sddm, echo $XAUTHORITY gives /run/user/1000/c04e4bb9-0531-4ab3-86a8-caaa6f30a661 with the file name changingat every reboot
Using GDM echo $XAUTHORITY gives /run/user/1000/gdm/Xauthority

Moreover when I look at the Xorg process it is runned by sddm as:
/usr/lib/Xorg -nolisten tcp -background none -seat seat0 -noreset -keeptty -novtswitch -verbose 3 -auth /run/user/1000/c04e4bb9-0531-4ab3-86a8-caaa6f30a661 -displayfd 8 vt1 -logfile /dev/null

GDM instead runs Xorg in this way:
/usr/lib/Xorg vt2 -displayfd 3 -auth run run/user/1000/gdm/Xauthority -nolisten tcp -background none -noreset -keeptty -novtswitch -verbose  3

Finally running xauth when started by sddm I get:
access control enabled, only authorized clients can connect

Whereas running when uning GDM I get:
access control enabled, only authorized clients can connect
SI:localuser:andreak

**Comment by rusty-snake** [comment]
Can you try to add this line to `/etc/firejail/whitelist-runuser-common.inc`
```
whitelist ${RUNUSER}/[[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]]-[[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]]-[[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]]-[[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]]-[[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]]
```

**Comment by Xwang1976** [comment]
Adding that line solves the issue.
