### ISSUE TITLE
fshaper.sh syntax error when issued by firejail

### ISSUE THREAD

**Issue by NoAgendaIT** [netblue30/firejail#429]
This is currently not working on master as can be seen here:
<pre>
% firejail --bandwidth=22850 set eth0 80 20                    
Removing bandwith limit
Cannot find device "ingress"
Error: missing parameters
Usage:
     fshaper.sh --status
     fshaper.sh --clear device
     fshaper.sh --set device download-speed upload-speed
</pre>

However, When I run `fshaper.sh` on its own, as root, with `--set veth22853eth0 80 20`, the script will work as expected.

(By the way, if anyone is confused while reading this: that number 22850 is the PID of a jail, which could be found via `firejail --list`.)

**Comment by reinerh** [comment]
@NoAgendaIT Do you still have this issue?
For me it's working with 0.9.42-rc1.

**Comment by netblue30** [comment]
I could never reproduce it here also.
