### ISSUE TITLE
Firejail broke latest Bitwarden by blocking network access 

### ISSUE THREAD

**Issue by iandstanley** [netblue30/firejail#4294]
Not sure if this is the fault of firejail's default profiles or whether it is the packaging made for Debian 10 of the firejail-profiles

firejail/stable,stable 0.9.58.2-2+deb10u2 amd64

firejail-profiles/stable,stable 0.9.58.2-2+deb10u2 a

**Bug and expected behavior**
- Describe the bug.
Firejail fails to launch Bitwarden 1.24.6

Firejail complains that networking feature is disabled (which breaks the vault safe sync)

```
Warning: networking feature is disabled in Firejail configuration file
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
```

then complains about it's own config and then aborts.

```
Warning: not remounting /run/user/1000/gvfs
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Child process initialized in 1095.02 ms
[17:0522/205528.592544:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Bitwarden/chrome-sandbox is owned by root and has mode 4755.
```

I suspect that if u2f/yubikey/fido2 is enabled on the client this will break as well 

- What did you expect to happen?
Bitwarden to just load 

** ERROR LOG**
```
Warning: not remounting /run/user/1000/gvfs
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Child process initialized in 1095.02 ms
[17:0522/205528.592544:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Bitwarden/chrome-sandbox is owned by root and has mode 4755.
```

the chrome-sandbox is owned by root and is 4755 

I checked the chrome-sandbox 

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal?
bitwarden loads and runs normally and can sync to online vault.

- What changed calling the program by path (e.g. `/usr/bin/vlc`)?
/Bitwarden-1.24.6-amd64.deb

**Reproduce**

sudo apt install firejail firejail-profiles
sudo firecfg 

run bitwarden from either launch icon or command line 

**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`, `screenfetch` or `cat /etc/os-release`)
Debian 10 fully updated 

 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`)
 - firejail/stable,stable 0.9.58.2-2+deb10u2
 - Latest Bitwarden  .DEB downloaded from Bitwarden's own website Bitwarden-1.24.6-amd64.deb

**Additional context**
Other context about the problem like related errors to understand the problem.

**Checklist**
 - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [Y ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [ ] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [N/A ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [N/A ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

<details><summary> debug output </summary>

```
OUTPUT OF `firejail --debug PROGRAM`
```

</details>

**Additional context**
Other context about the problem like related errors to understand the problem.

**Checklist**
 - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [ ] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

<details><summary> debug output </summary>

```
OUTPUT OF `firejail --debug PROGRAM`
```

</details>

**Additional context**
Other context about the problem like related errors to understand the problem.

**Checklist**
 - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [ ] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

<details><summary> debug output </summary>

```
OUTPUT OF `firejail --debug PROGRAM`
```

</details>

**Comment by reinerh** [comment]
Can you please show your `/etc/firejail/firejail.config`?
It sounds like you have `network no` configured (which is not disabled by default).

**Comment by rusty-snake** [comment]
> - [x] The program has a profile.

Firejail 0.9.58.2 has no profile for bitwarden. 
https://github.com/netblue30/firejail/tree/0.9.58.2 (8 Feb 2019) but https://github.com/netblue30/firejail/commit/c813294e47fb9e65b42506125fd24aea760f1c40 (2 May 2019).

Can you post your profile.

> Firejail complains that networking feature is disabled (which breaks the vault safe sync)

How can this breaks the sync function of bitwarden?

> the chrome-sandbox is owned by root and is 4755

Inside or outside of the sandbox?

> [17:0522/205528.592544:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Bitwarden/chrome-sandbox is owned by root and has mode 4755.

Bitwarden uses electron. PR will come.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
