### ISSUE TITLE
private-dev customization

### ISSUE THREAD

**Issue by p1839251** [netblue30/firejail#4296]
Hello,
I was wondering if I could customize `private-dev`, because the program won't work with it:
`gawk: fatal: can't open source file `/dev/fd/63' for reading (No such file or directory)`
I assume it would work if /dev/fd were also included.

**Comment by smitsohu** [comment]
Which Firejail version do you use? I think this was fixed in 0.9.64.

If your version is older, can you try to upgrade?

**Comment by p1839251** [comment]
The error message did go away after an update
