### ISSUE TITLE
System sound quits after playing video w/ Firefox

### ISSUE THREAD

**Issue by Amii-Leigh601** [netblue30/firejail#430]
Hi netblue30. I've noticed a strange occurence when using Firefox and firejail: whenever I play a video in Firefox, my entire system sounds applet crashes and I have to reboot the computer to get the system sounds back. I can continue to play other sounds, such as those in Pidgin, but my system sounds are lost.

I am not using a custom Firefox profile, I'm using firejail 0.9.38, and I have used a fresh Firefox profile to ensure that this wasn't some incompatibility between a Firefox add-on and firejail. My OS is Linux Mint 17.3 64-bit with the Cinnamon desktop, using kernel 3.19.0-32. The precise command I use to launch Firefox is `firejail firefox`.
(When not using firejail, I can play videos normally in Firefox and not lose sound.)

This is the output I get:
`Reading profile /etc/firejail/firefox.profile`
`Reading profile /etc/firejail/disable-mgmt.inc`
`Reading profile /etc/firejail/disable-secret.inc`
`Reading profile /etc/firejail/disable-common.inc`
`Reading profile /etc/firejail/disable-devel.inc`
`Reading profile /etc/firejail/whitelist-common.inc`
`Parent pid 9133, child pid 9135`
`Blacklist violations are logged to syslog`
` `
`Child process initialized`
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`(firefox:2): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised`
` `
`(firefox:2): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised`
` `
`(firefox:2): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised`
` `
`(firefox:2): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised`
` `
`(firefox:2): GnomeUI-WARNING **: While connecting to session manager:`
`None of the authentication protocols specified are supported.`

This bit crops up when I attempt to play a video:
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`Vector smash protection is enabled.`
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib/i386-linux-gnu/firejail/libtracelog.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

I noticed in particular that `/usr/lib/i386-linux-gnu/firejail/libtracelog.so` can't be preloaded in any of these instances.

I [asked for help on the Linux mint forums first](https://forums.linuxmint.com/viewtopic. ... 8&t=219853) and, after some debugging, was advised to contact you directly on GitHub.

Thanks in advance!

**Comment by netblue30** [comment]
I think you have a firejail 32-bit installed on a 64-bit computer. I would uninstall it and put a amd64 version on from https://sourceforge.net/projects/firejail/files/firejail/

A possible workaround if you cannot install a new firejail: in a text editor open as root /etc/firejail/firefox.profile file (sudo vim /etc/firejail/firefox.profile or any other editor, but make sure you use sudo),  and comment out tracelog line. It should look something like this:
`````
# tracelog
`````
This should solve all the errors you get. Try it out and let me know, we'll take it from there if you still have problems.

**Comment by Amii-Leigh601** [comment]
I did just as you asked and my system sounds applet still crashed.
         I installed firejail_0.9.40-rc1_1_amd64.deb which I had no 
problems installing.

         I ran it in the terminal, after it was installed, and this is 
all that the terminal displayed:
amii@Crystal ~ $ firejail firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 24908, child pid 24909
Blacklist violations are logged to syslog

Child process initialized

(firefox:2): GLib-GObject-WARNING **: Attempt to add property 
GnomeProgram::sm-connect after class was initialised

(firefox:2): GLib-GObject-WARNING **: Attempt to add property 
GnomeProgram::show-crash-dialog after class was initialised

(firefox:2): GLib-GObject-WARNING **: Attempt to add property 
GnomeProgram::display after class was initialised

(firefox:2): GLib-GObject-WARNING **: Attempt to add property 
GnomeProgram::default-icon after class was initialised

(firefox:2): GnomeUI-WARNING **: While connecting to session manager:
None of the authentication protocols specified are supported.

parent is shutting down, bye...
amii@Crystal ~ $

On 16-04-13 08:10 AM, netblue30 wrote:
>
> I think you have a firejail 32-bit installed on a 64-bit computer. I 
> would uninstall it and put a amd64 version on from 
> https://sourceforge.net/projects/firejail/files/firejail/
>
> A possible workaround if you cannot install a new firejail: in a text 
> editor open as root /etc/firejail/firefox.profile file (sudo vim 
> /etc/firejail/firefox.profile or any other editor, but make sure you 
> use sudo), and comment out tracelog line. It should look something 
> like this:
>
> |# tracelog |
>
> This should solve all the errors you get. Try it out and let me know, 
> we'll take it from there if you still have problems.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/netblue30/firejail/issues/430#issuecomment-209432243>
>

-- 
Genuine love is rarely an emotional space where needs are
instantly gratified. To know love we have to invest time and
  commitment.

--Bell Hooks

**Comment by netblue30** [comment]
Ok, next step is to configure PulseAudio. It has a problem in the later versions due to some feature they started configuring by default. This will get us one step closer. I have a description of the problem and the fix here: https://firejail.wordpress.com/support/known-problems/

Look at "PulseAudio 7.0 issue"

**Comment by Amii-Leigh601** [comment]
Thank you very much :-)

-- 
Genuine love is rarely an emotional space where needs are
instantly gratified. To know love we have to invest time and
  commitment.

--Bell Hooks

**Comment by netblue30** [comment]
No problem.
