### ISSUE TITLE
Increase delay before issuing SIGKILL on shutdown?

### ISSUE THREAD

**Issue by pyther** [netblue30/firejail#431]
Would it be possible to increase the time that is waited before sending a SIGTERM on shutdown?

I have an application that may need to write data to disk when it receives a SIGTERM. The current value of 2 seconds seems low and may not give an application enough to gracefully shutdown. There does not appear to be a standard on how long to wait after sending a SIGTERM, but systemd waits 10 seconds after SIGTERM before issuing additional signals. 

```#define TIMEOUT_USEC (10 * USEC_PER_SEC)```
```until = now(CLOCK_MONOTONIC) + TIMEOUT_USEC;```
https://github.com/systemd/systemd/blob/master/src/core/killall.c#L36

Would it be possible to send a SIGTERM and then loop every 0.5 second or so checking to see if the children have died, sending a SIGTERM after 10 seconds?

https://stackoverflow.com/questions/27570302/how-much-time-before-sigkill

**Comment by netblue30** [comment]
I'll bring something in soon, thanks!

**Comment by netblue30** [comment]
Fixed in main branch.
