### ISSUE TITLE
Invalid whitelist path /local

### ISSUE THREAD

**Issue by vbooka1** [netblue30/firejail#4310]
**Bug and expected behavior**
- Describe the bug.
- What did you expect to happen?

I want to whitelist certain dirs in /local/ because a program needs a write access there.

**Reproduce**
1. create a profile containing "whitelist /local/path/to/dir"
2. See error `Error: invalid whitelist path /local/path/to/dir`

**Environment**

 firejail version 0.9.64.4

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - overlayfs support is disabled
        - private-home support is enabled
        - private-cache and tmpfs as user enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

**Additional context**
Other context about the problem like related errors to understand the problem.

on my system /local/ is not a separated partition nor a dedicated mount point but just a subdirectory of / (root partition)

**Checklist**
 - [v] I have performed a short search for similar issues (to avoid opening a duplicate).

after finding this: #739  I believe it is a limitation within firejail

 - [v] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [v] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by rusty-snake** [comment]
Manpage of 0.9.64.4:

> **--whitelist=dirname_or_filename**
> Whitelist directory or file. A temporary file system is mounted on the top directory, and the
> whitelisted files are mount-binded inside. Modifications to whitelisted files are persistent,
> everything else is discarded when the sandbox is closed. _The top directory could be_
> _user home, /dev, /etc, /media, /mnt, /opt, /run/user/$UID, /srv, /sys/module, /tmp, /usr/share and /var._

**Comment by vbooka1** [comment]
I'll try to move the program with all its bindings to /opt/, nevertheless please consider adding /local to the list of allowed top directories.

**Comment by rusty-snake** [comment]
Nope, /local will not be added ...  #4229
