### ISSUE TITLE
Access to CEC Adapter blocked by kodi.profile

### ISSUE THREAD

**Issue by lapseofreason** [netblue30/firejail#4324]
In order to use a CEC adapter in kodi (using [libcec](https://github.com/Pulse-Eight/libcec)), access to `/dev/ttyACM0` is required. However, this is blocked by `private-dev` in `kodi.profile`.

**Bug and expected behavior**
- Access to `/dev/ttyACM0` is required to use CEC adapter, but is denied by `kodi.profile`.

**No profile and disabling firejail**
- Access to `/dev/ttyACM0` works when running it without firejail.

**Reproduce**
1. Run in bash `firejail kodi`
2. Connect a CEC adapter to the USB port.
3. See the error in kodi (and in the log) about not being able to access the CEC adapter.

**Environment**
 - Fedora 34
 - firejail-0.9.64.4-1.fc34

**Additional context**
The profile can be overridden locally in `kodi.profile`, but I could not find a way to override `private-dev`. It seems to not be able to customize it (#1446). Suggestions for a workaround would be welcome.

**Checklist**
 - [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [x] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [x] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by rusty-snake** [comment]
> The profile can be overridden locally in kodi.profile, but I could not find a way to override private-dev. It seems to not be able to customize it (#1446). Suggestions for a workaround would be welcome.

`ignore private-dev` . . .

**Comment by lapseofreason** [comment]
@rusty-snake Thanks a log for the quick hint to the workaround!

**Comment by rusty-snake** [comment]
Would you say CEC adapters are common enough to be worth adding a note to kodi.profile?

```
# Add 'ignore private-dev' to your kodi.local if you use a CEC adapter.
```

**Comment by lapseofreason** [comment]
Hard to say, for the specific use case of a media center I suspect they are quite common as they allow you to control kodi with the TV remote. There is one on every RaspberryPI, for desktops they are a bit harder to get though.

I just tried the workaround, which did not work so I suspect there must be something else blocking access to `/dev/ttyACM0` too. I also tried commenting out `private-dev` in kodi.profile to make sure I didn't make any mistakes (which didn't work either).

Running `firejail --noprofile kodi` on the other hand works.

**Comment by rusty-snake** [comment]
Then it's either blacklisted
```
ignore no3d
ignore noinput
ignore nosound
ignore notv
ignore nou2f
ignore novideo
```
or requires group permissions
```
ignore nogroups
ignore noroot
```
I guess.

**Comment by lapseofreason** [comment]
Thanks! Adding the following to `kodi.local` works for me:

```
ignore private-dev
ignore nogroups
ignore noroot
```

Without any one of them it does not work.

I understand that it requires `nogroups` as `/dev/ttyACM0` is not world-readable, but I'm unsure why `noroot` is needed.

**Comment by rusty-snake** [comment]
`noroot` removes all groups except for `firejail`, `tty` (is `/dev/ttyACM0` not `tty`?), `audio`, `video`, `games`.

**Comment by lapseofreason** [comment]
`/dev/ttyACM0` is group `dialout` on Fedora.

**Comment by lapseofreason** [comment]
@rusty-snake Thanks a lot, seems like a good compromise to add it as a comment to the profile!
