### ISSUE TITLE
Some firejail output goes to stdout instead of stderr

### ISSUE THREAD

**Issue by slowpeek** [netblue30/firejail#4328]
**Bug and expected behavior**
- Some firejail output goes to stdout instead of stderr.

**Reproduce**
1. Run and see
    ```
    firejail --seccomp=\!name_to_handle_at pwd 2>/dev/null
    Seccomp list in: !name_to_handle_at, check list: @default-keep, prelist: unknown,
    Seccomp list in: !name_to_handle_at, check list: @default-keep, prelist: unknown,
    /etc/firejail
    ```
   It is not an artificial example btw. The seccomp filter comes from keepassxc profile inherited by keepassxc-cli hence the above lines are prepended to keepassxc-cli exported xml. `FIREJAIL_QUIET=yes` does suppress the lines but those are definitely debug information, it should not pollute stdout by default.

**Environment**
 - ubuntu focal
 - 0.9.64.4

**Additional context**
Source reference:
https://github.com/netblue30/firejail/blob/c50dd74f615aaa9d0ebd6a1c459c5b3268ba1b9d/src/lib/syscall.c#L1675-L1695

**Checklist**
 - [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [x] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [x] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [x] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by rusty-snake** [comment]
1. IMHO we should print these messages only with `arg_debug`. Normal users likely doesn't even know what all those seccomp is.
2. For stdout vs. stderr we have #3749/#4275

**Comment by netblue30** [comment]
I'm sending them to stderr for now, we'll have to rework it for #3749 and #4275.
