### ISSUE TITLE
unable to delete created symlink when closing Google Earth

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#435]
G'day netblue30 (and of course to the other blokes as well)! I'm working on a profile for Google Earth--it's been pretty straight-forward with one exception: GE creates a symlink `~./googleearth/instance-running-lock` which points to /proc/_subdir_ (so far it's been /proc/12 but I'm not willing to say it'll stay at /proc/12).  

Ordinarily, `~./googleearth/instance-running-lock` is deleted when closing GE, but when running in firejail, the symlink remains after closing. Hence, the next time GE is started (in firejail or not), we get the following jolly message:
_Google Earth appears to be running already. Please kill the
 existing process, or delete /home/fred/.googleearth/instance-running-lock if this is an error._

If I `mkdir ~./googleearth/instance-running-lock` in the profile, and then whitelist it, that defeats the purpose as GE sees the directory and refuses to start.

A quick-n-dirty hack might be to add `rmdir ~/.googleearth/instance-running-lock` to the profile, but firejail doesn't seem to support this option in profiles. Besides, I'm not really happy with doing this. There might be a one-in-a-hundred occurrence in which there was a legitimate use for `instance-running-lock` and I think it'd be better to let GE handle deleting the directory itself.  
But how? :-)

The profile I'm using is at (http://pastebin.com/KM6v9bJr). `firejail --noprofile google-earth` doesn't behave any better...

Cheers, mate!

**Comment by netblue30** [comment]
I think you should try firejail --private. It will get rid of the link.

**Comment by Fred-Barclay** [comment]
That will get rid of the symlink... but it will also not load any saved locations. :( 
I'm not sure if this is a quirk of google earth or firejail just yet. It's seeming that google earth loses read-write privileges in `~/.googleearth` just before it closes (though that's purely conjecture at this point).

**Comment by netblue30** [comment]
I'll install Google Earth here and give it a try, somehow we'll have to fix this.

**Comment by Fred-Barclay** [comment]
Sounds good.
BTW: I should have mentioned that this is on LMDE Betsy (close to Debian Jessie) with the 4.4.0-0.bpo.1-amd64 kernel.

**Comment by Fred-Barclay** [comment]
This doesn't seem to be an issue anymore after #1555
