### ISSUE TITLE
Sandboxed application can't find program in $PATH

### ISSUE THREAD

**Issue by asakura42** [netblue30/firejail#4351]
It seems that firejail looks for programs only in /usr/bin, /sbin etc. But what to do if I keep my browser binary in `~/.local/bin` and want to open it from `newsboat`? I use default profile now, when i try to open link, debug mode outputs `sh: line 1: localbrowser: command not found`. `localbrowser` is that binary that I keep in `~/.local/bin` and which I use as a link opener

**Comment by rusty-snake** [comment]
Does `--noprofile` work?

**Comment by asakura42** [comment]
Thank you!
