### ISSUE TITLE
minecraft-launcher not running with firejail

### ISSUE THREAD

**Issue by Martelleus** [netblue30/firejail#4363]
Running 0.9.64.4 in Manjaro

When I run firejail minecraft-launcher , it opens the updater and says it is inspecting the current version and preparing to update but then proceeds to shut down

firejail --noprofile minecraft-launcher works

**Comment by rusty-snake** [comment]
Is anything is the syslog? Did you made any modifications to it's profile/.locals? Are there any relevant messages if you run it from a terminal?

**Comment by Martelleus** [comment]
AVC apparmor="DENIED" operation="exec" profile="firejail-default" name="/home/(username)/.minecraft/launcher/minecraft-launcher" pid=3229 comm="minecraft-launc" requested_mask="x" denied_mask="x" fsuid=1000 ouid=1000

audit: type=1400 audit(1624124805.579:141): apparmor="DENIED" operation="exec" profile="firejail-default" name="/home/(username)/.minecraft/launcher/minecraft-launcher" pid=4205 comm="minecraft-launc" requested_mask="x" denied_mask="x" fsuid=1000 ouid=1000


qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 22070, resource id: 79691779, major code: 15 (QueryTree), minor code: 0

Didn't modify the profile

When I run it from the terminal, it runs into this error:

 Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

and then tries to update PistonComponent and then does a bunch of stuff with Sha1Cacher.cpp and NetQueue. After piston updates, NetQueue shut downs and it tries to start the launcher, but then it reads "Starting the sub-process failed: Permission denied" and fails to launch the launcher. In the next line it reads "No writable bootstrap found in game directory."

**Comment by rusty-snake** [comment]
> AVC apparmor="DENIED" operation="exec" profile="firejail-default" name="/home/(username)/.minecraft/launcher/minecraft-launcher" pid=3229 comm="minecraft-launc" requested_mask="x" denied_mask="x" fsuid=1000 ouid=1000

minecraft-launcher.profile already contains `ignore noexec ${HOME}` but it also contains `apparmor` which makes `${HOME}` `noexec` too.
