### ISSUE TITLE
Using mkdeb to build firejail 

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#437]
G'day netblue30. This isn't an issue per se, at least not yet--I just need more info on building a firejail.deb package.

After downloading the source code and cd-ing into the directory, how do I build the .deb? Do I immediately run `./mkdeb.sh`? Do I `./configure` first? Are there any intermediate steps?

When installing the .deb, is it prefixed to /usr/local? I noticed that building from source does this, but I'd definitely not prefer this behavior if I `dpkg -i firejail.deb`. (In another words, does it build a .deb that behaves the same as one I download from your repo on SourceForge? Ignoring changes/updates, of course.)

Thanks!
Fred

**Comment by netblue30** [comment]
First you configure it, than you do make deb:
`````
$ ./configure
$ sudo make deb
`````
The package is prefixed automatically to /usr.

**Comment by Fred-Barclay** [comment]
Thanks, mate.
Would it be possible to avoid prefixing to /usr? Or would this be a really bad idea?

**Comment by Fred-Barclay** [comment]
Thanks, mate. 
Would it be possible to avoid prefixing to /usr? Or is that a really bad idea?

**Comment by netblue30** [comment]
Usually packages you compile yourself end up in /usr/local/bin, and .deb or .rpm packages you download are placed under /usr/bin. These are old rules, you can get around them as you like, I don't think it matters.

You can modify mkdeb.sh, it is "./configure" line below:
`````
$ cat mkdeb.sh
[...]
tar -xjvf $CODE_ARCHIVE
#mkdir -p $INSTALL_DIR
cd $CODE_DIR
./configure --prefix=/usr
make
mkdir debian
DESTDIR=debian make install-strip
[...]
`````
You need to change "./configure --prefix=/usr" to "./configure".

**Comment by Fred-Barclay** [comment]
...which would explain why `./configure --prefix=` seemed to have no effect on the .deb. 
Thanks!
