### ISSUE TITLE
move noblacklist ${HOME}/.bogofilter to email-common.profile for claws-mail (and other mailers)

### ISSUE THREAD

**Issue by jonleivent** [netblue30/firejail#4383]
In a 0.9.58.2 claws-mail profile, the home .bogofilter subdirectory was not blacklisted.  In 0.9.64 it is, so I had to add a noblacklist ${HOME}/.bogofilter to my claws-mail.local profile.  Apparently, this was a change to the disable-programs.inc file that is compensated for my some other email profiles (notably evolution and mutt) doing their own noblacklist.  However, as bogofilter is applicable to many other email apps (such as claws-mail), I think the noblacklist ${HOME}/.bogofilter should be moved to email-common.profile.

**Comment by glitsj16** [comment]
Nice catch. Currently `email-common.profile` is only included by claws-mail and sylpheed profiles. So instead of rewriting all our email-related profiles to include that common file we can add it to email-common.profile to provide support for bogofilter in claws-mail.

Can you open a PR for this?

**Comment by rusty-snake** [comment]
Ping

**Comment by marek22k** [comment]
Shouldn't be there the same for bsfilter? `${HOME}/.bsfilter`?

**Comment by glitsj16** [comment]
> Shouldn't be there the same for bsfilter? ${HOME}/.bsfilter?

If that's the correct path bsfilter uses you can add it yes. I never used bsfilter so can you open a PR for this please? See https://github.com/netblue30/firejail/commit/f4b36e80321379c4917c7ab9c9b3bbcfad05899f.
