### ISSUE TITLE
Firejail rejects empty arguments

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#4395]
A Ubuntu user [reported](https://bugs.launchpad.net/ubuntu/+source/firejail/+bug/1934698) that firejail rejects arguments to the application if they are empty.
But for some applications empty arguments are actually valid use cases.
Even with the argument separator (`--`) firejail still rejects it.

Example:
```
$ echo ''

$ firejail -- echo ''
Error: too short arguments
$
```

This is the location of the check: https://github.com/netblue30/firejail/blob/e66ba7cc483df0de8060823ebd7ebaff9c7c61c2/src/firejail/main.c#L1027-L1030

**Comment by netblue30** [comment]
will do, thanks!

**Comment by rusty-snake** [comment]
> [fix bug: firejail rejects empty arguments](https://github.com/netblue30/firejail/commit/eba4af3be75f58cc6d27a368dcc53fe6461de033)

So we can close here?

**Comment by netblue30** [comment]
Yes, closing.
