### ISSUE TITLE
PulseAudio sandboxing

### ISSUE THREAD

**Issue by FedericoCeratto** [netblue30/firejail#44]
Thanks for developing firejail! Some profiles could be useful for desktop environments.
- play audio
- read from microphones
- read from webcam
- read contents from clipboards
- write to clipboards
- list X window titles, get current window focus
- send keystrokes/mouse clicks to other X windows

**Comment by netblue30** [comment]
Play audio, read from microphones, and read from webcam can be handled today with --private-dev if the sound system is set with ALSA. For PulseAudio things are out of control in this moment. It might be possible to control the access to the unix socket.

All the rest are covered by https://github.com/netblue30/firejail/issues/57

**Comment by netblue30** [comment]
I've impelmented --nosound option. It will go into the next release.
