### ISSUE TITLE
Add profile for Morty

### ISSUE THREAD

**Issue by asakura42** [netblue30/firejail#4402]
Hello. Help me create profile for Morty sanitizer (https://github.com/asciimoo/morty). Now I have these lines in `~/.config/firejail/morty.profile`:
```
blacklist ${HOME}
blacklist /root
blacklist /run/user
blacklist /boot
```

But when I blacklist `/etc`, Morty refuses to open any page. Maybe you know some tip how to blacklist anything but that files that program needs?

**Comment by netblue30** [comment]
Try first:

$ firejail your-program-name [arguments]

It should work in most cases. It uses /etc/firejail/default.profile

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
