### ISSUE TITLE
Add Microsoft Edge (Beta/Dev channels)  

### ISSUE THREAD

**Issue by Area51Kacz** [netblue30/firejail#4409]
Could we add an Edge profile >)
https://aur.archlinux.org/packages/microsoft-edge-dev-bin/
https://aur.archlinux.org/packages/microsoft-edge-beta-bin/

**Comment by Fred-Barclay** [comment]
Hi @Area51Kacz 

I've just added a profile for beta.

We did already have a profile for Dev - see https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/microsoft-edge-dev.profile

Cheers!
Fred
