### ISSUE TITLE
superuser in titlebar of various apps

### ISSUE THREAD

**Issue by MRF316** [netblue30/firejail#4411]
Could it be possible that running Firejail could cause apps to show **superuser** in the titlebar?

**Comment by glitsj16** [comment]
Might be related to #258, but we won't be sure until you provide some more context. What's your OS, firejail version, window manager etcetera?

**Comment by MRF316** [comment]
I figured it out. It is FJ, I disabled it, and no more superuser in titlebar.

**Comment by glitsj16** [comment]
Happy to read you've made some progress. Disabling Firejail is one way of dealing with the titlebar issue, but it's not something we'd advise. Firejail _should_ be able to cope with that, but it's up to you to be the final judge. Personally I'd prefer a mangled titlebar and run the affected apps in a sandbox, be it firejail or something similar. If you have the time to debug this further, we can help and try to reproduce. But like already mentioned above we'd need detailed info. Just voicing my personal view on this situation, I do understand it can become tedious to debug and time is precious.

Regards

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions#ive-noticed-the-title-bar-in-firefox-shows-as-superuser-is-this-normal

FWIW: Maybe `ignore noroot` stops those messages (at the price of a weaker sandbox).

**Comment by MRF316** [comment]
> Happy to read you've made some progress. Disabling Firejail is one way of dealing with the titlebar issue, but it's not something we'd advise. Firejail _should_ be able to cope with that, but it's up to you to be the final judge. Personally I'd prefer a mangled titlebar and run the affected apps in a sandbox, be it firejail or something similar. If you have the time to debug this further, we can help and try to reproduce. But like already mentioned above we'd need detailed info. Just voicing my personal view on this situation, I do understand it can become tedious to debug and time is precious.
> 
> Regards

No mangled titlebar...on the Debian forums they were trying to tell me I was running as root since alot of my apps says superuser in the titlebar. I ALWAYS forget about Firejail and it's usually the culprit with problems nobody can figure out.

**Comment by rusty-snake** [comment]
FWIW: https://github.com/netblue30/firejail/issues/3282#issuecomment-602252663, https://github.com/netblue30/firejail/issues/3360#issuecomment-615408728, https://github.com/netblue30/firejail/issues/1344, https://github.com/netblue30/firejail/issues/917, https://github.com/netblue30/firejail/issues/840, https://github.com/netblue30/firejail/issues/258

**Comment by smitsohu** [comment]
@MRF316 

See: https://github.com/mate-desktop/marco/issues/301
