### ISSUE TITLE
Brave stopped working

### ISSUE THREAD

**Issue by Area51Kacz** [netblue30/firejail#4417]
GPU RX560
Kernel 5.13.2
firejail version 0.9.66
Distro  Manjaro

Brave nightly  (or   brave 1.27+) aint working
But brave works on firejail --no3d --noprofile brave-nighly

**Comment by rusty-snake** [comment]
Any error? Maybe in the syslog.

Do you have a brave.local or globals.local?

**Comment by Area51Kacz** [comment]
brave.local  
And with default settings

**Comment by rusty-snake** [comment]
Are there any errors in the terminal or in the syslog?

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.

**Comment by bcvent** [comment]
@rusty-snake i cant get it to work on ubuntu, im getting not found when checking, how can i see any additional log?

**Comment by rusty-snake** [comment]
`firejail --debug` and your syslog (`journalctl`).
