### ISSUE TITLE
Fix new profiles after [no]deny / [no]allow revert

### ISSUE THREAD

**Issue by adgross** [netblue30/firejail#4421]
Files from the commit a25e4a101129471f3221df5471e2fc8fa6a1c4e6 still uses deny / nodeny and allow / noallow after merging the revert 8b50039a1fad123b90172fadc85bc232e97eb6d1.
The revert commit f43382f1e9707b4fd5e63c7bfe881912aa4ee994 is older than these profiles, while the merge itself happened later, so the revert missed the new files.

Affected files:
- io.github.lainsce.Notejot.profile [[L9-L10](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/io.github.lainsce.Notejot.profile#L9-L10), [L23-L25](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/io.github.lainsce.Notejot.profile#L23-L25)]
- lifeograph.profile [[L9-L11](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/lifeograph.profile#L9-L11), [L22-L23](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/lifeograph.profile#L22-L23)]
- rednotebook.profile [[L9-L10](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/rednotebook.profile#L9-L10), [L25-L33](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/rednotebook.profile#L25-L33)]
- zim.profile [[L9-L10](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/zim.profile#L9-L10), [L16](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/zim.profile#L16), [L29-L38](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/zim.profile#L29-L38)]

**Comment by rusty-snake** [comment]
And #4407.

**Comment by rusty-snake** [comment]
2e4d52ec60a677586decc62b0d1bc26757a2856a

**Comment by Fred-Barclay** [comment]
Ha I ran across the files by accident in that commit - thanks to @adgross for catching these as well!
