### ISSUE TITLE
firejail strace method for private-lib needed 

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#4424]
I need firejails buildin strace method for easy private-lib line creating. 

Example for firefox.

Thanks and

Best regards

**Comment by rusty-snake** [comment]
You mean you want to run `starce --some-args /usr/bin/firefox` to get a list of all files it opens in `/usr/lib`, `/usr/lib64`, ...?

**Comment by osevan** [comment]
> You mean you want to run `starce --some-args /usr/bin/firefox` to get a list of all files it opens in `/usr/lib`, `/usr/lib64`, ...?

Exactly

**Comment by osevan** [comment]
> You mean you want to run `starce --some-args /usr/bin/firefox` to get a list of all files it opens in `/usr/lib`, `/usr/lib64`, ...?

Or firejail buildin -trace option ro.figure out which librarys. 


But I need librarys list already sorted and ready for profile.

**Comment by netblue30** [comment]
We have --build command line option where we detect using strace all kind of things such as "private-bin" and "private-etc". Let me try to add support for private-lib to it.

For simple programs (probably not firefox), if you have a valid "private-bin" in your profile, add also "private-lib". We autodetect a lot of libraries by default.

**Comment by osevan** [comment]
> We have --build command line option where we detect using strace all kind of things such as "private-bin" and "private-etc". Let me try to add support for private-lib to it.
> 
> For simple programs (probably not firefox), if you have a valid "private-bin" in your profile, add also "private-lib". We autodetect a lot of libraries by default.

I have private-bin already in Firefox,.and works fine with my list,but not with private-lib.

private-lib didn't work

**Comment by rusty-snake** [comment]
```bash
strace --trace=%file --follow-forks --output=gnome-2048.strace /usr/bin/gnome-2048
grep -o '"/lib64/.*"' gnome-2048.strace | cut -d\" -f2 | cut -d/ -f3- | sort -u | tr '\n' ','
```

**Comment by osevan** [comment]
Thanks you very much .

I modified, because on old strace commands are different. 


But it works.

**Comment by osevan** [comment]
I tested this method for buster debian and works. 

But,for.two.other machines bullseye libs  from.above line arent enough

We need   detailed debug, --debug  isnt enough..

They cant spit out needed libs.  :-(
 

We need fixes for bullseye

**Comment by rusty-snake** [comment]
Closing as `private-lib` was never really finish, has some bugs, has major performance issues, is now disabled by default and a workaround is documented here.
