### ISSUE TITLE
steam-controller not working in steam.profile

### ISSUE THREAD

**Issue by DoPlJoe** [netblue30/firejail#4437]
As the title states, the steam-controller does not work with the steam.profile.

It does work with the --noprofile option. I've tried commenting out parts of the steam profile, but because I don't know what I'm doing that more often than not leads to steam not starting at all.

AFAIK these are the devices I need access to:
/dev/input/by-id/usb-Valve_Software_Steam_Controller-event-mouse
/dev/input/by-id/usb-Valve_Software_Steam_Controller-if01-event-joystick
/dev/input/by-id/usb-Valve_Software_Steam_Controller-if01-joystick
/dev/input/by-id/usb-Valve_Software_Steam_Controller-mouse
/dev/uinput

I've setup my udev-rules as recommended on the steam forums mapped to the group "input"  which my user is part of. I've also tried setting permissions to 0666, but that doesn't work either. Strangely enough other controllers are accessible in steam, as long as the private-dev option is present.

Running Manjaro with the default firejail and steam packages installed.

**Comment by rusty-snake** [comment]
Assuming you use firejail 0.9.66, `/dev/input` is allowed with steam.profile (check `firejail --profile=steam ls -l /dev/input`). If it is a permissions problem with group "input", try to `ignore nogroups` and `ignore noroot`.

**Comment by DoPlJoe** [comment]
From the looks of it that shows all inputs, which are part of the "input"-group on my system. However /dev/uinput remains unavailable even with both those ignore options.

**Comment by rusty-snake** [comment]
If it needs to emulate devices, `ignore private-dev`.

**Comment by DoPlJoe** [comment]
> If it needs to emulate devices, `ignore private-dev`.

That was the solution, now it works for both the steam-controller as well as regular ones. 

Weird that when I had the private-dev thing commented out, I got neither. Thanks for the help.
