### ISSUE TITLE
Add support for globbing in private-bin and private-etc

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#445]
According to man firejail-profile file globbing is supported. However, it seems that it doesn't work with all switches.

E.g., I tried to tighten wine.profile and added the following line:

`private-bin wine*,xdg-open,update-desktop-database`

When I started the Windows application with the --debug switch I got the following message:

`Warning: not all executables from --private-bin list were found. The current list is xdg-open,update-desktop-database`

After modifying that line to 

`private-bin wine,wineserver ....etc.`

I didn't get this warning. 

If file globbing not being supported with private-bin (and possibly private-etc) is the intentional behavior it should be mentioned in the man page, IMHO.

**Comment by netblue30** [comment]
I'll have to add support for it, thanks!

**Comment by chiraag-nataraj** [comment]
Globbing was added at some point.
