### ISSUE TITLE
whitelist and mkdir uncertainty

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#447]
man firejail-profile says:

```
whitelist file_or_directory

Build a new user home in a temporary filesystem, and mount-bind file_or_directory.
The modifications to file_or_directory are persistent, everything else is discarded
when the sandbox is closed.
```

and:

```
mkdir directory

Create a directory in user home. Use this command for whitelisted directories
you need to preserve when the sandbox is closed.
```

I'm afraid that from this description it will be unclear to many users why mkdir is actually necessary to preserve whitelisted directories although modifications to a whitelisted directory are "persistent". Aren't both sentences a bit contradictory? I think this should be clarified.

**Comment by netblue30** [comment]
Yes, I'll have to fix the description.

**Comment by netblue30** [comment]
Fixed, thanks.
