### ISSUE TITLE
Building on ARM

### ISSUE THREAD

**Issue by lepasserby** [netblue30/firejail#448]
Hi! 
I need to build firejail for Cubieboard 2 (CPU is A20, a dualcore Cortex A7) from source.
OS will likely be notoriously kvetchy Cubian (I could try Ubuntu but with GUI it's a mite too taxing the poor little ARM thing)

Is it possible? Should I look out for something in particular?

**Comment by reinerh** [comment]
Debian provides firejail also for armhf/armel/arm64 [1], so yes, it's possible.

[1]: https://packages.debian.org/unstable/firejail

**Comment by figue** [comment]
I'm running firejail in a Cubietruck (A20) with a mainline kernel 4.4.7:

```
[root@suntk ~]# uname -a
Linux suntk 4.4.7 #2 SMP Sun Apr 17 19:43:47 CEST 2016 armv7l GNU/Linux
```

Firejail works, but it seems that seccomp is not detected or can't be enabled for a reason I don't know:

`Warning: seccomp disabled, it requires a Linux kernel version 3.5 or newer.`

@netblue30 can you confirm if seccomp should work in an arm system? I have enabled this option in kernel config:

```
[root@suntk ~]# zgrep SECCOMP /proc/config.gz 
CONFIG_SECCOMP=y
```

**Comment by reinerh** [comment]
You are missing CONFIG_SECCOMP_FILTER.

**Comment by netblue30** [comment]
Yes, seccomp works fine on ARM. There seem to be another kernel setting, CONFIG_HAVE_ARCH_SECCOMP_FILTER=y:
`````
$ grep -i seccomp /boot/config-*
/boot/config-3.16.0-4-amd64:CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
/boot/config-3.16.0-4-amd64:CONFIG_SECCOMP_FILTER=y
/boot/config-3.16.0-4-amd64:CONFIG_SECCOMP=y
/boot/config-4.3.0-0.bpo.1-amd64:CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
/boot/config-4.3.0-0.bpo.1-amd64:CONFIG_SECCOMP_FILTER=y
/boot/config-4.3.0-0.bpo.1-amd64:CONFIG_SECCOMP=y
`````

**Comment by figue** [comment]
Thanks, I had to disable CONFIG_OABI_COMPAT to enable the other settings. It was a bit hard to figure it out. Now, warning message is gone and seccomp seems to work.

**Comment by netblue30** [comment]
CONFIG_OABI_COMPAT also seems to be disabled in Debian kernels.
