### ISSUE TITLE
It seems that 8d3d67e8960f87a7592bc3a1623f27b45a52edb5 breaks Firefox

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#4482]
**Bug and expected behavior**
Firefox cannot access internet after 8d3d67e8960f87a7592bc3a1623f27b45a52edb5

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal?: works
- What changed calling the program by path (e.g. `/usr/bin/vlc`)?: works

**Reproduce**
1. Run in bash `firejail firefox`
2. Open any networked website.
3. DNS is not available.

**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`, `screenfetch` or `cat /etc/os-release`)  Ubuntu 21.04 hirsute
 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`) 8d3d67e8960f87a7592bc3a1623f27b45a52edb5

**Additional context**

**Checklist**
 - [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [x] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.: n/a
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [x] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

Debug output contains nothing useful at the moments I try to open websites from Firefox.

UPD: after manually replacing the files from a good commit with the ones of f4b36e80321379c4917c7ab9c9b3bbcfad05899f it stopped breaking on f4b36e80321379c4917c7ab9c9b3bbcfad05899f. Now it breaks on 8d3d67e8960f87a7592bc3a1623f27b45a52edb5

**Comment by KOLANICH** [comment]
Thank you.

**Comment by mjanonis** [comment]
On Arch Linux, `/etc/resolv.conf` points to `/run/systemd/resolve/stub-resolv.conf` when systemd-resolved is used, so that needs to get added to the whitelist too. I had the same problem and doing that fixed it.
