### ISSUE TITLE
Use generic.profile by default

### ISSUE THREAD

**Issue by iiotx** [netblue30/firejail#45]
Hi netblue30 and contributors!

I'd like to see firejail parse generic.profile by default unless:
* Another profile is explicitly specified on the command line, or
* Another profile matches the extracted command name, or
* A flag is specified to disable it (ex. "--nodefault")

Don't get me wrong: I love the flexibility of firejail to specify all kinds of options.  The target here is the new/desktop user who wants to sandbox but may be getting less security than they expect from sandboxing a profile-less program.

Feel free to reject this suggestion if you think it is the wrong direction for the firejail project.  Otherwise, I'd be happy to make the change and submit a pull request.

**Comment by netblue30** [comment]
It is a good idea, send a pull request! Make the flag "--noprofile" instead of "--nodefault". Thanks!

**Comment by iiotx** [comment]
Awesome, will do sometime in the next week.
