### ISSUE TITLE
Nextcloud profile broken - needs 3D and system tray access

### ISSUE THREAD

**Issue by zarandya** [netblue30/firejail#4509]
The nextcloud client profile is broken: nextcloud crashes at startup as it is trying to use OpenGL for its gui. Also, it has no access to the system tray. 

I added this to `nextcloud.local` to fix it:
```
ignore no3d
dbus-user.talk org.freedesktop.StatusNotifierItem
dbus-user.talk org.kde.StatusNotifierWatcher
```

**Comment by rusty-snake** [comment]
Is enough to add this?
```
ignore no3d
dbus-user.talk org.kde.StatusNotifierWatcher
```

**Comment by zarandya** [comment]
> Is enough to add this?
> 
> ```
> ignore no3d
> dbus-user.talk org.kde.StatusNotifierWatcher
> ```

It indeed is.
