### ISSUE TITLE
Warning: failed to unmount /sys

### ISSUE THREAD

**Issue by requiredregistration** [netblue30/firejail#452]
does this mean that --overlay and --overlay-tmpfs will not work as expected?

**Comment by netblue30** [comment]
Don't worry about them for now, there is something strange with the way overlayfs kernel feature uses /sys. I will probably suppress the warnings.

**Comment by requiredregistration** [comment]
it might be an overlayfs bug. maybe we should report it to the kernel people.

**Comment by requiredregistration** [comment]
you closed it without explaining why.

when you say that something is strange with overlayfs, that means you do not understand it perfectly or there is a bug.

closing the issue does not answer the question of if there is a problem here because of your lack of knowledge or because there is a kernel bug.

**Comment by netblue30** [comment]
I cannot do anything about it, I think it has something to do with the kernel, so I am not going to carry it as a bug. I have it on my watch list, if ever some more information becomes available.

**Comment by requiredregistration** [comment]
by sending an e-mail to the LKML we can learn why.

**Comment by requiredregistration** [comment]
maybe the [overlayfs log](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/log/fs/overlayfs) can help you discover why you see unexpected and/or wrong behavior.

you labeled it 'information', but it might be a bug.

**Comment by tobwen** [comment]
Warning still appears on Debian GNU/Linux 9.4 (stretch).

**Comment by smitsohu** [comment]
Just for clarification: This warning was issued by firejail and not by the kernel or some system service. The reason is that were trying to unmount sysfs at a timepoint when it was not mounted.

This will be fixed in 0.9.56
