### ISSUE TITLE
Error: .asoundrc is a symbolic link pointing to a file outside home directory

### ISSUE THREAD

**Issue by crocket** [netblue30/firejail#4527]
`~/.asoundrc` is actually a symbolic link pointing to a file outside home directory.

Why does firejail refuse this?

Because of this issue, I can't execute librewolf and firefox with firejail.

I have lots of symbolic links that point to files outside home directory in home directory.

**Comment by crocket** [comment]
This seems like a question.

**Comment by kmk3** [comment]
@crocket commented [on Sep 11](https://github.com/netblue30/firejail/issues/4527#issuecomment-917404910):

> This seems like a question.

Link for reference: #4529
