### ISSUE TITLE
nogroups kills ALSA audio in mpv.profile and vlc.profile

### ISSUE THREAD

**Issue by crocket** [netblue30/firejail#4528]
### Bug

Only root and audio group can read from and write to files in /dev/snd.
My regular user account belongs to audio group which allows me to play audio.
`nogroups` option in mpv.profile and vlc.profile kills ALSA audio.

It seems that firefox-common.profile also contains `nogroup` option. This is going to break audio in firefox and librewolf, too.

### Environment

- Linux distribution and version // Gentoo Linux
- Firejail version
```
$ firejail --version
firejail version 0.9.66

Compile time support:
        - always force nonewprivs support is disabled
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is disabled
        - networking support is enabled
        - output logging is enabled
        - overlayfs support is disabled
        - private-home support is enabled
        - private-cache and tmpfs as user enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled
```

**Comment by crocket** [comment]
This seems to have been reported several times.... I should move this to discussion.

**Comment by kmk3** [comment]
@crocket commented [on Sep 11](https://github.com/netblue30/firejail/issues/4528#issuecomment-917416427):

> This seems to have been reported several times.... I should move this to
> discussion.

Link for reference: #4531
