### ISSUE TITLE
"--net=none" equivalent for profiles

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#458]
When starting a program from the command line, we have the option to disallow all network access: 
`firejail --net=none some_programme` 
But what if we wanted to integrate this with the programme profile so that networking was automatically disabled? Is there a option for this?
So for example:
`...`
`seccomp`
`caps.drop all`
`NO NETWORK`
`noroot`
`...`

Is this possible?

**Comment by nick75e** [comment]
Hi!

Simply use `net none`

**Comment by Fred-Barclay** [comment]
Thanks!
Where did you find that? I looked on the man page and poked around netblue's blog a little but couldn't find it.

**Comment by nick75e** [comment]
here: https://firejail.wordpress.com/features-3/man-firejail-profile/
