### ISSUE TITLE
Can't find libstdc++.so.6 due to private-etc and private-lib in aria2c.profile

### ISSUE THREAD

**Issue by crocket** [netblue30/firejail#4589]
### Description

This aria2c.local file works around the issue

```
private-etc ld.so.cache
ignore private-lib
```

private-lib eliminates /usr/lib/gcc by mounting tmpfs on /usr/lib.
/etc/ld.so.cache is necessary for finding libstdc++.so.6 in /usr/lib/gcc.

### Environment

- Linux distribution and version // Gentoo Linux
- Firejail version (`firejail --version`).
```
firejail --version
firejail version 0.9.66

Compile time support:
        - always force nonewprivs support is disabled
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is disabled
        - networking support is enabled
        - output logging is enabled
        - overlayfs support is disabled
        - private-home support is enabled
        - private-cache and tmpfs as user enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled
```

**Comment by rusty-snake** [comment]
> ignore private-lib

We have `private-lib …,gcc/*/*/libstdc++.so.*,…` already in other profiles, maybe we should just hardcode it?

> private-etc ld.so.cache

to sum up:
- _always_ necessary: `alternatives,ld.so.cache,ld.so.preload`
- _always_ necessary if there is no `net none`: `ca-certificates,crypto-policies,nsswitch.conf,pki,resolv.conf,ssl`
  - `crypto-policies,pki,ssl` can be future restricted to use subdirs

**Comment by crocket** [comment]
Perhaps, you could put those in something like /etc/firejail/globals.profile?

**Comment by rusty-snake** [comment]
Nope, because not every profiles uses `private-etc`. I solved this in my overrides with `include private-etc:net.inc`. Anyway we need private-etc groups like for seccomp (`private-etc @network,fonts,...`). _cloudn't find the issue for it_

**Comment by crocket** [comment]
Perhaps, something like this can work.

```
private-etc-optional alternatives,ld.so.cache,ld.so.preload
```

private-etc-optional kicks in only if private-etc is also provided.

**Comment by crocket** [comment]
I don't think testing profiles is the definite solution because people are going to have private profiles that are not subject to tests.
