### ISSUE TITLE
Feature Request: Logind conditional

### ISSUE THREAD

**Issue by crocket** [netblue30/firejail#4603]
### Is your feature request related to a problem? Please describe.

(e)udev attaches uaccess tag to devices.
systemd-logind and elogind grant logged-in users rights to devices with uaccess tag.
With logind, `noroot` and `nogroups` don't break device access.
Without logind, `noroot` or `nogroups` may break device access.

Some linux distributions like Void Linux and Gentoo Linux allow users to replace logind with other seat managers like seatd.

### Describe the solution you'd like

To support all linux distributions and all seat managers without any manual user configuration, a logind conditional like `?SEAT-ACL` is desirable. Then,

```
noroot
nogroups
```

can be replaced with

```
?SEAT-ACL: noroot
?SEAT-ACL: nogroups
```

**Comment by smitsohu** [comment]
@topimiettinen Right. This kind of fine grained control (`groups.drop`) won't be very helpful for upstream profiles. I was thinking from the perspective of an administrator, but a more dynamic solution would be clearly better.

**Comment by crocket** [comment]
It doesn't make much sense to put `ignore nogroups` in allow-audio.inc if allow-audio.inc is included in main profiles.

You should just remove `nogroups`.

**Comment by rusty-snake** [comment]
> If we keep adding stuff without eliminating lines, we may end up with something like `ignore ignore ignore nogroups`

`ignore nogroups` is enough.

----

What about `nogroups <all|auto|none>`?

- `nogroups all` (and alias `nogroups` for backward compatibility) will drop all supplementary groups. (and `noroot` will not change groups #3303)
- `nogroups none` will keep all groups (maybe we don't need this as it is the same as not using `nogroups` and just complicates things)
- `nogroups auto` will autodetect which groups it should keep (whitelisting)
   ```js
   if !arg_nosound:
       drop_group("audio")
   if !arg_novideo:
       drop_group("video")
   if !arg_nodvd:
       drop_group("cdrom")
   if !arg_noinput:
       drop_group("input")
   if !arg_no3d: // /dev/dri/card0 has group video
       drop_group("render")
   if !arg_noprinters: // yes I still need to write a ticket for it
       drop_group("lp")
   ```
   in case other groups names are used, we can provide mappings in firejail.config

**Comment by crocket** [comment]
I think I like `nogroups (all)` and `nogroups auto`.

**Comment by crocket** [comment]
> The users would gain access to this GID, which they didn't have before. Then they could make setgid binaries to keep the rights after Firejail exits.

Are you personally using firejail in public multi-seat computers?

**Comment by crocket** [comment]
Can this be considered fixed now?

**Comment by kmk3** [comment]
@crocket commented [on Jan 2](https://github.com/netblue30/firejail/issues/4603#issuecomment-1003698727):

> Can this be considered fixed now?

Yes; thanks for the reminder.
