### ISSUE TITLE
Unless netlink is added to protocol supertuxkart does not see my xbox360-compatible controller

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#4605]
If I want to be able to configure/use my SN30pro+ controller (wired mode) in `supertuxkart` I need to add `netlink` to

https://github.com/netblue30/firejail/blob/2164412bb54087b1c540893acf5384ef9bf03f1d/etc/profile-m-z/supertuxkart.profile#L46

This is probably `xpad` driver specific issue.

**Comment by netblue30** [comment]
Fixed, thanks!

**Comment by rusty-snake** [comment]
- supertuxkart.profile still lacks `protocol netlink`
- 39654d01661ea9310b9b886a572ee24b1e4c9cfb add a lot of duplicated code

**Comment by netblue30** [comment]
Something went very very wrong there, I just assumed if it is not in the man page is not implemented!

I added it to supertuxkart. Do you need it for any other games?

**Comment by kmk3** [comment]
@netblue30 commented [on Jan 22](https://github.com/netblue30/firejail/issues/4605#issuecomment-1019355976):

> Something went very very wrong there!

Please consider using `git revert` to revert commits whenever feasible, as it
undoes every change at once and also makes it clear in the log that the
original commit was reverted.

For example, in this case, `git revert 8b92ac3eb` would have been a clean
revert.

And if there were multiple commits to be reverted, the one thing to keep in
mind is that they have to be reverted in the opposite (topological) order that
they were committed.  For example, given the following commits:

```console
$ git log -n 4 --oneline --graph
* C bar 3
* B bar 2
* A bar 1
* X foo
```

To revert commits A, B and C, one would do:

```sh
git revert C
git revert B
git revert A
```

> I added it to supertuxkart.

Can this be closed then?

**Comment by rusty-snake** [comment]
> Can this be closed then?

I think so.
