### ISSUE TITLE
`noprinters`

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#4607]
### Describe the solution you'd like

`noprinters` command to disable printing. It should `blacklist /dev/lp*` stuff and `/run/cups/cups.sock`.

This idea is based on the observation that wrc has
- `/run/**/resolv.conf` which is either needed or useless because of `net none`
- `/run/dbus/system_bus_socket` which is further handled by `dbus-system`
- `/run/media` which is further handled by `disable-mnt`/`disable-write-mnt.inc`
- `/run/cups/cups.sock` which is not handled elsewhere.

**Comment by rusty-snake** [comment]
FTR: bd15e763eab8c07072f8ef495a17d387c26150c7

**Comment by WhyNotHugo** [comment]
How about disabling printers by default and having a `printers` command to enable them when desired?

It's a bit easier to think about permissions in terms of "profile doesn't allow anything, unless otherwise stated", rather than the other way around.

**Comment by rusty-snake** [comment]
While I generally agree with you to list everything that is required rather than listing everything which is not required (enumerating badness vs. goodness), I don't feel good about changing the logic how firejail works.
