### ISSUE TITLE
Allow apostrophe in whitelist (and blacklist)

### ISSUE THREAD

**Issue by crocket** [netblue30/firejail#4614]
### Is your feature request related to a problem? Please describe.

`--whitelist=/path/to/james' directory` and `--whitelist=/path/to/simpson's file` are not allowed.

### Describe the solution you'd like

Special character escaping?

**Comment by netblue30** [comment]
Fixed, thanks for the bug.

**Comment by crocket** [comment]
What is the reason for rejecting certain characters?
