### ISSUE TITLE
Tremulous and warsow profiles are broken on Arch

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#4616]
Neither `warsow` nor `tremulous` (and perhaps a few other apps) run with their stock profiles on Arch.
```
❯ warsow 
Cannot start application: No such file or directory
❯ tremulous
Cannot start application: No such file or directory
```
What both games have in common is usage of wrappers.
```
❯ cat /usr/bin/tremulous <(echo "=====") /usr/bin/warsow
#!/usr/bin/env sh

cd /opt/tremulous/
./tremulous "$@"
=====
#!/bin/bash

basepath="/opt/warsow"

${basepath}/warsow \
  +set fs_basepath ${basepath} \
  +set fs_usehomedir 1 "${@}"
```

In order to make them work the following is needed:
  - drop `include disable-shell.inc` (as wrappers are written in shell)
  - either drop `private-bin` completely or extend:
    `# warsow: private-bin warsow,bash,sh,dirname,uname,sed,basename`
    `# tremulous: private-bin tremded,tremulous,tremulous-wrapper,sh,env`

Interestingly despite both games having its data in `/opt` (as opposed to profile expecting it in `/usr/share`) I did not have to add a new `whitelist` for this directory.

I can raise a PR - just don't know maybe there's a better option to tackle apps using wrappers..

**Comment by rusty-snake** [comment]
I would say, use `include allow-bin-sh.inc` instead of dropping ds and open a PR.
