### ISSUE TITLE
Steam with apparmor doesn't launch

### ISSUE THREAD

**Issue by Froggy232** [netblue30/firejail#4619]
Hi,
I have a problem with steam, it won't launch.
The log says : 

Reading profile /etc/firejail/steam-runtime.profile
Reading profile /etc/firejail/steam.profile
Reading profile /etc/firejail/globals.local
Reading profile /etc/firejail/allow-java.inc
Reading profile /etc/firejail/allow-python2.inc
Reading profile /etc/firejail/allow-python3.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: cannot create /home/antheo/.steampath
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Seccomp list in: !ptrace, check list: @default-keep, prelist: unknown,
Parent pid 2164, child pid 2166
Warning: skipping alternatives for private /etc
Warning: skipping asound.conf for private /etc
Warning: skipping bumblebee for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping dbus-1 for private /etc
Warning: skipping drirc for private /etc
Warning fcopy: skipping /etc/fonts/conf.d/10-sub-pixel-rgb.conf, cannot find inode
Warning fcopy: skipping /etc/fonts/conf.d/11-lcdfilter-default.conf, cannot find inode
Warning fcopy: skipping /etc/fonts/conf.d/70-no-bitmaps.conf, cannot find inode
Warning: skipping nvidia for private /etc
Private /etc installed in 18.72 ms
Private /usr/etc installed in 0.00 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Seccomp list in: !ptrace, check list: @default-keep, prelist: unknown,
Child process initialized in 74.99 ms
/usr/lib/steam/steam: /home/antheo/.local/share/Steam/steam.sh : /usr/bin/env : mauvais interpréteur: Permission non accordée
/usr/lib/steam/steam: ligne 212: /home/antheo/.local/share/Steam/steam.sh: Succès

Parent is shutting down, bye...

Do you have an idea why?
Thanks you!

**Comment by jose1711** [comment]
This seems to have worked for me (but I have not tested playing the actual games):
```
echo 'whitelist ${HOME}/Steam' >> /etc/firejail/steam.local
echo 'protocol unix,inet,inet6,netlink,packet' >> /etc/firejail/steam.local
```
You may want to try the same and report back.

**Comment by rusty-snake** [comment]
Maybe steam just don't work with apparmor :thinking: .

First you would need to allow it to execute stuff in $HOME.
