### ISSUE TITLE
Is it possible to run a separate instance of pulseaudio inside the sandbox, using xpra to "hear its sounds"?

### ISSUE THREAD

**Issue by DamienGrand** [netblue30/firejail#462]
Hello!
It just crossed my mind that, given that Firejail now has X forwarding support and xpra specifically (which has good sound support) it should be possible to block access to host's pulseaudio while running a "local" pulseaudio entirely inside firejail's sandbox, thus achieving flexible sound isolation.

One thing this might be good for is separating microphone and playback access (Xpra has settings for that)

This would for instance allow to isolate Chrome in firejail in a manner that allows sound playback (for watching videos) while at the same time not allowing microphone access.

Possible?

P.S.:
Do I understand correctly that currently, one can't have firejail pass commands to xpra ?_(It's not critical for managing sound in the manner described above, but could be useful)_

**Comment by netblue30** [comment]
I'll investigate it, thanks.

**Comment by netblue30** [comment]
Unfortunately pulse audio runs as a single instance, so we cannot isolate it.
