### ISSUE TITLE
Strange issue with xonotic.profile on Arch

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#4626]
Can't wrap my head around this :disappointed:  Updated Arch Linux, `xonotic` installed from community repo, latest `firejail` from master. There are 3 binaries in `/usr/bin`:
```
/usr/bin/xonotic-dedicated: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7d9e228eb4389da867dbcb6d5c02674c2a375c0b, for GNU/Linux 3.2.0, stripped
/usr/bin/xonotic-glx:       ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e2f4d1533ef8c2b67aa6103485b12e42cbf9e9c2, for GNU/Linux 3.2.0, stripped
/usr/bin/xonotic-sdl:       ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=1726aef21639cca734120f22a8cfe094b46911d3, for GNU/Linux 3.2.0, stripped
```
The profile defines a `private-bin` as follows:
```
private-bin blind-id,darkplaces-glx,darkplaces-sdl,dirname,ldd,netstat,ps,readlink,sh,uname,xonotic*
```
If I run the game I get:
```
$ xonotic-sdl
Error: cannot find the program in the path
```
This is odd so I change `xonotic*` to `xonotic-sdl`. Now the game starts. I revert the change and run a bash inside the profile. Inside it I can see that all 3 files were copied as expected
```
$ firejail --profile=xonotic-sdl bash
bash-5.1$ echo /usr/bin/*xonotic*
/usr/bin/xonotic-dedicated /usr/bin/xonotic-glx /usr/bin/xonotic-sdl
```
So it looks like the globbing worked. Any idea where is this coming from?

**Comment by SkewedZeppelin** [comment]
I noticed this a few months ago on Fedora 34.
Had to revert the wildcard.
```
-rw-r--r--. 1 root root 1.4K Aug 20 11:31 /etc/firejail/xonotic.profile
```

**Comment by smitsohu** [comment]
Ok, that's strange.
You didn't by chance enable `private-bin-no-local` in the Firejail configuration file (`/etc/firejail/firejail.config`) ?

`firejail --private-bin=ls --profile=xonotic --quiet ls -l /usr/bin`
Does that show all of /usr/bin, or do you have a restricted view.
