### ISSUE TITLE
Impossible to inclure tutanota-desktop-linux.AppImage in a sandbox with firejail with Linux Mint 20.2

### ISSUE THREAD

**Issue by CocoR55** [netblue30/firejail#4627]
### Description

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Warning: skipping tutanota-desktop for private /opt
Private /opt installed in 2.54 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: skipping crypto-policies for private /etc
Private /etc installed in 225.95 ms
Private /usr/etc installed in 0.01 ms
Child process initialized in 704.99 ms
the monkey has been patched
(node:16) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.88.4
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

(tutanota-desktop:16): libappindicator-WARNING **: 13:30:31.453: Unable to get the session bus: Could not connect: Permission denied

(tutanota-desktop:16): LIBDBUSMENU-GLIB-WARNING **: 13:30:31.454: Unable to get session bus: Could not connect: Permission denied
config up to date
scheduling to check sse in 1 seconds
[ApplicationWindow] startFile:  file:///run/firejail/appimage/resources/app.asar/index-desktop.html
[DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop/dictionaries/
default mailto handler: false
[DownloadManager] spellcheck-dictionary-initialized fr
scheduling to check sse in 10 seconds
sse info not available, skip reconnect
Webapp ready
autoUpdater info:
 Checking for update
autoUpdater info:
 checking-for-update
**/home/leloup/.local/share/applications/tutanota-desktop.desktop does not exist**, checking for permission to ask for permission...
....
chmod 777 tutanota-desktop.desktop. Nevertheless, this is the same.

I found that:
leloup@leloup-VirtualBox:/etc/firejail$ cat disable-common.inc | grep -i .local/share/app
**read-only** ${HOME}/.local/share/applications.

**Question: How to fix?**

Regards,
CocoR55

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Run in bash `LC_ALL=C firejail PROGRAM` (`LC_ALL=C` to get a consistent output in English that can be understood by everybody)
4. See error `ERROR`

### Expected behavior

_What you expected to happen_

### Actual behavior

_What actually happened_

### Behavior without a profile

_What changed calling `LC_ALL=C firejail --noprofile /path/to/program` in a terminal?_

### Additional context

_Any other detail that may help to understand/debug the problem_

### Environment

- Linux distribution is Linux Mint Cinnamon 20.2
- Firejail version (`firejail --version`) **0.9.66**
- If you use a development version of firejail, also the commit from which it was compiled (`git rev-parse HEAD`).

### Checklist

- [ ] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [ ] I can reproduce the issue without custom modifications (e.g. globals.local).
- [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [ ] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
output goes here
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

```
output goes here
```

</p>
</details>

**Comment by CocoR55** [comment]
I am not convinced. There is no shortage of them to make it work

**Comment by CocoR55** [comment]
noblacklist ${HOME}/.config/  is to allow acces to .config.
read-only ${HOME}/.local/share/applications is to allow read-only file.
What command is to alllow read-write  ${HOME}/.local/share/applications?

**Comment by rusty-snake** [comment]
Just two FYIs (I still don't get what you are trying and what works and what not).

1. If you allow tutanota-desktop to write to `~/.local/share/applications` once, the resulting desktop file will run tutanota-desktop unsandboxed. (And if you allow it always, you've open one more hole in the sbox).
2. If you want it give it access to the gnome-keyring to save your password:
   ```
   ignore dbus-user none
   dbus-user filter
   dbus-user.talk org.freedesktop.secretservice
   ```

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
