### ISSUE TITLE
Is "--noroot" implicitly at odds with "--chroot"? 

### ISSUE THREAD

**Issue by ptoomey3** [netblue30/firejail#463]
I noticed that the docs state that `--noroot` can't be used when using `--chroot`. I am curious if there is something foundational that would prevent this from being implemented in the future? Using `--chroot` is nice in that is minimizes the amount of blacklisting/whitelisting that is necessary. But, it would be nice to prevent escalation to root inside the chroot as well.

**Comment by netblue30** [comment]
I have to revisit this, a long time ago when --noroot was implemented there were some problems on chroots. I'll take a look, thanks.

**Comment by ptoomey3** [comment]
If it is still roughly the same code I sent you last year, I'm probably to blame :smile:. I had never even tested that code with a chroot. Thanks for taking a look!

**Comment by netblue30** [comment]
I've found it! We have something like this:
`````
$ cat t.c
#include <stdio.h>
#include <unistd.h>
#include <linux/sched.h>
int main() {
	chroot("/tmp/chroot");
	perror("chroot");
	unshare(CLONE_NEWUSER);
	perror("unshare");
	return 0;
}
$ sudo ./a.out
chroot: Success
unshare: Operation not permitted
$
`````

unshare fails inside a chroot, and this is what they say in man 2 unshare:
`````
       EPERM (since Linux 3.9)
              CLONE_NEWUSER was specified in flags and  the  caller  is  in  a
              chroot  environment  (i.e., the caller's root directory does not
              match the root directory of the  mount  namespace  in  which  it
              resides).
`````
My guess is somebody figured out a way to escape chroot using a user namespace, and they disabled it in the kernel.

**Comment by ptoomey3** [comment]
Maybe this: https://lwn.net/Articles/543273/. It seems there is some shared state with the parent process when you call `chroot` that would be at odds with running in a separate user namespace. So, I guess they just disabled it all together.

**Comment by netblue30** [comment]
We'll keep an eye on it, maybe they change their mind a put a better fix in.

**Comment by ptoomey3** [comment]
😿 - But I understand it isn't in your control.
