### ISSUE TITLE
cherrytree.profile error

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#465]
cherrytree only launches on my system (Manjaro) after adding

```
noblacklist /usr/bin/python2*
noblacklist /usr/lib/python2*
```
to the profile.

**Comment by Fred-Barclay** [comment]
Sorry-that's my fault. I'll add the lines to the profile, thanks!

**Comment by curiosity-seeker** [comment]
I just tried it again and can confirm that on my system **both** entries are needed.

**Comment by netblue30** [comment]
Fixed, thanks!
