### ISSUE TITLE
Chasing SUID executables

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#4668]
I am looking for SUID executables still visible inside the sandbox. Most of them are cleaned up by disable-common.inc.  I added some more:
`````
 ssh-keysign (from openssh)
/usr/bin/passwd
Xorg.wrap
polkit-agent-helper-1
/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/usr/lib/eject/dmcrypt-get-device
`````
I'm not sure about some of them, so things could break!

Let's look for some more SUID (it kind of depends on what you have installed on your computer):

Start a browser (firejail --name=browser firefox) and join the sandbox from another terminal (firejail --join=browser). Then, run the find command and add them to the list:
`````
$ find / -perm -u=s -type f 2>/dev/null
`````
Thanks!

**Comment by rusty-snake** [comment]
Fedora 34:
```
$ firejail --profile=/etc/firejail/disable-common.inc find / -perm -u=s -type f 2>/dev/null
/home/rusty-snake/.local/share/containers/storage/overlay/<hash>/diff/usr/bin/*  <-- `blacklist ${HOME}/.local/share/containers` in OCI-Containers / Podman
/usr/bin/fusermount-glusterfs
/usr/bin/fusermount3
/usr/bin/passwd
/usr/bin/firejail
/usr/lib/polkit-1/polkit-agent-helper-1
/usr/libexec/dbus-1/dbus-daemon-launch-helper
/usr/libexec/spice-gtk-x86_64/spice-client-glib-usb-acl-helper
/usr/libexec/Xorg.wrap
/usr/libexec/qemu-bridge-helper
/usr/local/rootdir/bin/firejail  <-- just testing
```

TBH suid binaries are already mitigated by nnp.

**Comment by glitsj16** [comment]
Arch Linux

`$ firejail --profile=/etc/firejail/disable-common.inc find / -perm -u=s -type f 2>/dev/null | sort`
```
/usr/bin/firejail
/usr/bin/fusermount3
/usr/bin/mount.cifs
/usr/bin/passwd
/usr/bin/physlock
/usr/bin/suexec
/usr/bin/wshowkeys
/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/usr/lib/electron13/chrome-sandbox
/usr/lib/mail-dotlock
/usr/lib/polkit-1/polkit-agent-helper-1
/usr/lib/squid/basic_pam_auth
/usr/lib/ssh/ssh-keysign
/usr/lib/Xorg.wrap
```

**Comment by kmk3** [comment]
@glitsj16 commented [on Nov 4](https://github.com/netblue30/firejail/issues/4668#issuecomment-961468359):

> Arch Linux
> 
> `$ firejail --profile=/etc/firejail/disable-common.inc find / -perm -u=s -type f 2>/dev/null | sort`
> 
> ```
> /usr/bin/firejail
> /usr/bin/fusermount3
> /usr/bin/mount.cifs
> /usr/bin/passwd
> /usr/bin/physlock
> /usr/bin/suexec
> /usr/bin/wshowkeys
> /usr/lib/dbus-1.0/dbus-daemon-launch-helper
> /usr/lib/electron13/chrome-sandbox
> /usr/lib/mail-dotlock
> /usr/lib/polkit-1/polkit-agent-helper-1
> /usr/lib/squid/basic_pam_auth
> /usr/lib/ssh/ssh-keysign
> /usr/lib/Xorg.wrap
> ```

On Artix Linux, new paths compared to the above:

```
/usr/bin/slock
/usr/lib/qemu/qemu-bridge-helper
```

**Comment by topimiettinen** [comment]
Debian bookworm/sid. I added `-xdev` so `/home`, `/proc`, `/var` etc are not checked in vain:
```
# firejail --profile=/etc/firejail/disable-common.inc find / -xdev -perm -u=s -type f 2>/dev/null
/usr/share/code/chrome-sandbox
/usr/share/discord/chrome-sandbox
/usr/libexec/polkit-agent-helper-1
/usr/bin/schroot
/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-ptp-helper
/usr/lib/snapd/snap-confine
```

But none of the above SUID exes are actually able to change UIDs, because all file systems except `/setuid` are mounted with `nosuid` flag:
```
# mount | grep -v nosuid
/dev/mapper/levy-debian_setuid on /setuid type ext4 (ro,nodev,noatime,seclabel,discard,nodelalloc)
```
Then `/setuid` is blacklisted in Firejail to disable all SUID exes with one line.

I've used the awesome possibility in Debian to divert selected files elsewhere with `dpkg-divert`, so for example when I update `iputils-ping` package containing setuid (actually only setcap) `/bin/ping`, `/setuid/ping` gets smoothly updated. I've added a symlink from `/usr/bin/ping` to `/setuid/ping`. But I don't care about `gst-ptp-helper` etc. and nothing seems to be broken due to their lack of SUID either. Do any non .deb distros have also this feature?

**Comment by rusty-snake** [comment]
> Do any non .deb distros have also this feature?

Fedora:

- python3-dnf-plugin-post-transaction-actions can be used to code this (e.g. start with `*:in:dnf repoquery --list --installed ${name} | xargs …`)
- https://github.com/g7/rpm-divert

**Comment by reinerh** [comment]
```
/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/usr/lib/chromium/chrome-sandbox
/usr/lib/openssh/ssh-keysign
/usr/bin/pmount
/usr/bin/firejail
/usr/bin/passwd
/usr/bin/schroot
/usr/bin/pumount
```

**Comment by Sly-Little-Fox** [comment]
Xubuntu Focal (20.04):
```
$ firejail --profile=/etc/firejail/disable-common.inc find / -xdev -perm -u=s -type f 2>/dev/null
/usr/bin/passwd
/usr/bin/firejail
/usr/lib/xorg/Xorg.wrap
/usr/lib/policykit-1/polkit-agent-helper-1
/usr/lib/eject/dmcrypt-get-device
/usr/lib/openssh/ssh-keysign
/usr/lib/vmware/bin/vmware-vmx-debug
/usr/lib/vmware/bin/vmware-vmx
/usr/lib/vmware/bin/vmware-vmx-stats
/usr/lib/snapd/snap-confine
/usr/lib/spice-gtk/spice-client-glib-usb-acl-helper
/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/usr/share/discord/chrome-sandbox
/usr/share/atom/chrome-sandbox
```

**Comment by kmk3** [comment]
What if firejail always bind-mounted certain paths with `nosuid` by default?  I
think the base paths below would cover all suid paths posted here:

```
/usr/bin
/usr/lib
/usr/libexec
/usr/share
```

Currently, there is only `noexec`, which disables suid, but also exec.  There
could be a new `nosuid` option to only disable suid.

Then, the base paths could be added on disable-common.inc:

```firejail
nosuid /usr/bin
nosuid /usr/lib
nosuid /usr/libexec
nosuid /usr/share
```

And ignored on profiles with:

```firejail
ignore nosuid /usr/bin
ignore nosuid /usr/lib
ignore nosuid /usr/libexec
ignore nosuid /usr/share
```

This could be done in addition to blocking individual suid paths, as a sort of
fallback.

**Comment by topimiettinen** [comment]
> What if firejail always bind-mounted certain paths with `nosuid` by default? 

I suppose even `nosuid /` could be even default, at least when nnp is active. Though sadly SELinux uses `nosuid` to determine whether certain domain transitions are allowed (https://github.com/systemd/systemd/pull/19902), so `suid`/`nosuid` isn't so simple after all.

**Comment by rusty-snake** [comment]
@topimiettinen would `nosuid` make any difference with nnp?

**Comment by topimiettinen** [comment]
> @topimiettinen would `nosuid` make any difference with nnp?

Not really. There could be an obscure case where something without NNP gets access to the mount namespace and then it could be useful if also `nosuid` were used. It's also more or less free if mount namespaces are used anyway.

**Comment by raphaelr** [comment]
Debian testing (bookworm):

```
/usr/lib/openssh/ssh-keysign
/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/usr/lib/xorg/Xorg.wrap
/usr/bin/firejail
/usr/bin/nvidia-modprobe
/usr/bin/passwd
/usr/libexec/spice-client-glib-usb-acl-helper
/usr/libexec/polkit-agent-helper-1
/usr/share/teams/chrome-sandbox
```
