### ISSUE TITLE
keep sound with --private-dev

### ISSUE THREAD

**Issue by suedi** [netblue30/firejail#467]
Get no sound with icecat when using --private-dev

Guess icecat cannot find /dev/snd ?

can you whitelist devices somehow?

Also got error something like "gnu tls cannot get random" 

Does sound like it could effect security if random numbers cannot be generated?
Could you say something about that?

**Comment by netblue30** [comment]
The whole purpose of --private-dev is to disable sound, video cameras and other fancy user devices. Use it mainly for servers, pdf readers and such. Whitelisting is supported for /dev directory.

"gnu tls cannot get random": I have no idea where is coming from, --private-dev creates /dev/random and /dev/urandom.

**Comment by suedi** [comment]
Thanks for info

closing...
