### ISSUE TITLE
Can't start docker in firejail

### ISSUE THREAD

**Issue by jiafengjason** [netblue30/firejail#4671]
[root@ensbrain ~]# service docker start 
Redirecting to /bin/systemctl start docker.service

** (pkttyagent:95): WARNING **: 09:40:22.239: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine user of subject
Error registering authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine user of subject (polkit-error-quark, 0)

**Comment by rusty-snake** [comment]
#4582

**Comment by jiafengjason** [comment]
I start firejail with noprofile setting，but it still not work！
[root@ensbrain ~]# systemctl start docker
Failed to get D-Bus connection: Connection refused

**Comment by rusty-snake** [comment]
Closing as I don't think this is a issue in firejail.
