### ISSUE TITLE
Add openstego profile

### ISSUE THREAD

**Issue by Rult** [netblue30/firejail#4677]
UPD: Java-specific error was resolved.
All that's need now for OpenStego's profile is to deny Internet access.
_____
[OpenStego in AUR.](https://aur.archlinux.org/packages/openstego)
Currently gives this when run with `--net=none`:
```
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "tmplIS" is null
        at com.openstego.desktop.util.UserPreferences.init(UserPreferences.java:57)
        at com.openstego.desktop.OpenStego.main(OpenStego.java:429)
```
I suppose there are should be some Java paths whitelisted, but I don't know which ones are needed to be specified.

**Comment by jmetrius** [comment]
Hey,

I recently updated the OpenStego PKGBUILD since it has been terribly outdated. I tried to reproduce your issue by running `firejail --net=none openstego` and all seems fine.

Can you try again with the latest version and report if the issue persists?

**Comment by Rult** [comment]
@jmetrius hey, that's pretty neat! The program works as intended.

Though it would be nice if firejail would disable Internet access to it by default as it's not needed and the package comes precompiled on AUR.
