### ISSUE TITLE
A Viber.AppImage update broke firejail execution

### ISSUE THREAD

**Issue by svc88** [netblue30/firejail#4692]
If you download the latest viber.appimage from the official viber site and try simply to run it it doesnt run and and even without a profile:
`firejail --appimage --noprofile viber.AppImage`

I get:
```
Parent pid 6247, child pid 6250

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Child process initialized in 60.32 ms

Parent is shutting down, bye...
AppImage detached
```

I have an older viber.appimage version which still works however, im just not sure how to debug this new one?

Ubuntu 18.04
Firejail: v0.9.66
(There is no track of version numbers for the viber appimage that they release)

**Comment by rusty-snake** [comment]
Try to run it with the [noprofile.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/noprofile.profile).

Is Viber an electron program?
Does the new viber.appimage work without firejail?
Is there any error in your syslog?

**Comment by svc88** [comment]
I did some more tests and it seems that for some reason the new viber update executes normally on Ubuntu 20.04 but not on Ubuntu 18.04 and im not sure of the reason as there is nothing in the syslog about the failure.
Im also not sure if it is an electron program and what its dependencies are.
I guess the solution is to use Ubuntu 20.04 as i am guessing there are probably dependencies needed in order to run the newer versions.
thanks for the help. i am closing this issue.
