### ISSUE TITLE
Problem with Tor Browser Bundle and seccomp !chroot

### ISSUE THREAD

**Issue by bluefire8000** [netblue30/firejail#4699]
Hello mates,

I am using firejail with a custom profile for Tor Browser Bundle. The Tor Browser is running from ramdisk (/media/ramdisk/tor-browser_en). Everything worked well in the past.

Since I have updates TBB to the latest version 11, the Browser does not start with firejail. It works if I comment out this line in the firejail profile:

#seccomp !chroot

If I remove the "#", the browser does not start and the command line shows:
Post-exec seccomp protector enabled
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,

I am no expert and I don't really understand what "seccomp !chroot" is doing, i just copied it from the default firejail profile to my own profile (which basically is adjusted to allow TBB to run from ramdisk).

Any ideas what is going wrong? I would appreciate your help. Ty guys!

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/issues/4697#issuecomment-972594995
