### ISSUE TITLE
Arch non-issues and issues

### ISSUE THREAD

**Issue by iiotx** [netblue30/firejail#47]
First: I'm happy to report that the Arch warnings in the todo list are gone for me using the current git version!  Probably worth confirming with someone else though.

Second: I've been having an issue with getting "execvp: Permission denied" -- I've narrowed it down to (the profile or manually) blacklisting either /sbin or /usr/sbin
```
$ firejail --noprofile --blacklist=/mnt
Parent pid 1619, child pid 1620
Child process initialized
$ exit

parent is shutting down, bye...
$ firejail --noprofile --blacklist=/sbin
Parent pid 1630, child pid 1631
Child process initialized
execvp: Permission denied

parent is shutting down, bye...
$ 
```

The reason is because both /sbin and /usr/sbin are symlinks to /usr/bin and firejail is unable to execvp /usr/bin/bash, or most programs on my system for that matter, after blacklisting the folder.  The system defaulted these symlinks at some point.

Interestingly, this is not an issue with firejail-0.9.28, only the git head version.

Checking the --debug for both, the 0.9.28 version is actually failing to blacklist the symlink /sbin folder.  Of course I get the same error when I blacklist /usr/bin explictly.

It looks like in fixing symlinks during some commit, it actually broke systems that use symlinks for /sbin and /usr/sbin.  Note that I do think there are perfectly valid scenarios for blacklisting /usr/bin.

How do you want to proceed?  Check the symlink to see if it ends up blacklisting the command we're calling and ignore the blacklist it if it does?  Force explict, non-symlink paths to blacklist bin/sbin FHS-compliant folders?

**Comment by netblue30** [comment]
I'll look into it, thanks! There were lots of fixes for --blacklist going into the branch recently. I'll make it so it rejects the blacklist command if the file is a symlink.

**Comment by netblue30** [comment]
I have a fix, you can try it. Thanks for the bug!

**Comment by iiotx** [comment]
Looks beautiful now.  Thanks so much!

**Comment by netblue30** [comment]
You're welcome!
