### ISSUE TITLE
Open torrent in firefox

### ISSUE THREAD

**Issue by Froggy232** [netblue30/firejail#4702]
Hi,
Is it possible to open a torrent directly with firefox, instead of needing to download it then open it with a torrent app?
I use transmission.
Thanks you!

**Comment by SkewedZeppelin** [comment]
Transmission has an option to watch and automatically add all .torrent files in
a given directory.

**Comment by Froggy232** [comment]
Thanks, but it's still not the desired behaviour.
It's not a huge deal anyway, but I would like if it was possible.

**Comment by glitsj16** [comment]
You can check if the `BitTorrent handler` from https://github.com/glitsj16/firejail-handler-extra provides your desired behaviour. Just something I put together to use a firejailed Firefox/transmission-daemon in a more user-friendly way...

**Comment by Froggy232** [comment]
It's too complicated for me, I will continue to do it manually or try the first solution.
Thanks you!

**Comment by netblue30** [comment]
Look for something called "drag and drop". You drag a regular torrent file link or a magnet link from firefox window, and release it in the torrent window. Works for me in transmission-qt, but seems to be broken in transmission-gtk (Debian 10).

**Comment by Froggy232** [comment]
Thanks, I will try that.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
