### ISSUE TITLE
balena etcher profile

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#4704]
I was surprised to not find a profile already written for [Etcher](https://www.balena.io/etcher/), which is a popular AppImage that I see a lot of people recommending for the making of bootable USBs.

I read [here](https://github.com/netblue30/firejail/issues/1471#issue-250495355) that this lack of profile may be do to complications with pkexec.

I guess since Etcher actually writes images to USB drives, it is likely hard to contain it without disabling it completely?

Luckily, I came across a better solution after not finding a profile for Etcher: [Ventoy](https://www.ventoy.net/). While there's no profile for Ventoy either, the cool thing about Ventoy, is that once you put it on a USB, you don't have to run Ventoy again for that USB; you can simply drag and drop another ISO onto that same USB and that's all that is needed. When you boot from it, it will show a list of all the images you've moved onto the drive and ask you which one you want to boot.

Still, it would be nice if Etcher had a profile. I'm still learning about profiles and am not yet ready to create my own.

**Comment by rusty-snake** [comment]
> I read here that this lack of profile may be do to complications with pkexec.

`pkexec`/`sudo`/`su` will never work for AIs.

**Comment by kmk3** [comment]
@Lonniebiz commented [on Nov 21](https://github.com/netblue30/firejail/issues/4704#issue-1059456721):

> Still, it would be nice if Etcher had a profile. I'm still learning about
> profiles and am not yet ready to create my own.

It might help to look through the profiles of similar programs (if any) and
also the profile templates:

* [profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template)
* [redirect_alias-profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/redirect_alias-profile.template)

**Comment by svc88** [comment]
im a bit confused, is this issue completed? as in there is a profile for it. Since its nowhere to be found. Also its not under Profile requests either, as you mentioned that it it was mentioned there @rusty-snake 

Does this work with pkexec or not?


> `pkexec`/`sudo`/`su` will never work for AIs.

what do you mean by AI's ?

thanks in advance

**Comment by rusty-snake** [comment]
> Also its not under https://github.com/netblue30/firejail/issues/1139 either, as you mentioned that it it was mentioned there @rusty-snake

https://github.com/netblue30/firejail/issues/1139#issuecomment-974873801

And in OP:
> - [ ] etcher …

> what do you mean by AI's ?

**A**pp**I**mage
