### ISSUE TITLE
Implement Case Insensitive Sorting of Profiles on GitHub to Avoid Duplication

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#4706]
I downloaded an AppImage of discord from here:
https://www.appimagehub.com/p/1420323/

Debian 11 stable provides firejail version 0.9.64.4, which doesn't have a profile in /etc/firejail/ for discord.

At https://github.com/netblue30/firejail/tree/master/etc/profile-a-l , I located these profile files:

	Discord.profile
	discord.profile
	DiscordCanary.profile
	discord-canary.profile
	discord-common.profile

Notice that multiple similar files only differ by capitalization. This is probably a product of the poor sort-order offered by github here and such a "cause of redundancy" may be avoided in the future if it is possible to set github to do some type of case insensitive sorting of profiles that would group these files (above) next to each other and prevent people from overlooking when a profile already exists but has different capitalization.

Also, when I look inside these files I see includes to other (non-discord-named) files.

So, far, when I've found profiles on github, since they are not in my /etc/firejail/ already, I've considered them **custom** and I've been placing them at ~/.config/firejail/ instead of just placing them in the /etc/firejail/ folder that came with my distribution's installation of firejail.

However, in this case, I'm not sure what to do. I could manually follow all includes and put all dependencies files into ~/.config/firejail/, or I could just place the proper discord profiles into /etc/firejail/ where most of those non-discord includes within (like "include globals.local") will likely already reside at a resolvable relative path.

Or, I could just make one file that includes everything instead of including all the separate files in ~/.config/firejail/ .

So, I'm reporting this seeming redundancy located at https://github.com/netblue30/firejail/tree/master/etc/profile-a-l for discord, but I'd appreciate any advise regarding the proper location to start consuming the correct profile for discord.

**Comment by rusty-snake** [comment]
The easiest way to find a (pro)file on github (case insensitive): https://github.com/netblue30/firejail/find/master

---

Copying profiles from github (master) to an stable release of firejail can cause trouble because they are written for a newer firejail version.

> Debian 11 stable provides firejail version 0.9.64.4, which doesn't have a profile in /etc/firejail/ for discord.

um wait a minute, this pages says something else https://packages.debian.org/bullseye/all/firejail-profiles/filelist

**Comment by reinerh** [comment]
> Are the varying capitalizations of the discord profiles intentional?

Profile names are capitalized the same as the filenames of the binaries that are distributed (some packages might distribute it as `Discord` (maybe the official one?), others maybe as `discord`).
Firejail uses the filename of the application to find the profile that should be applied to it.

**Comment by rusty-snake** [comment]
See @reinerh's comment.
