### ISSUE TITLE
elinks on Arch complains about missing access to liblua

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#4707]
### Description

Getting the following error message when executing `elinks`:
```
$ elinks
fopen: Permission denied
/usr/bin/elinks: error while loading shared libraries: liblua.so.5.4: cannot open shared object file: Permission denied
```

### Steps to Reproduce

1. Run in bash `LC_ALL=C firejail elinks`
2. Receive the error message

### Expected behavior

Program should run normally.

### Actual behavior

Error appears.

### Behavior without a profile

Works fine.

### Additional context

Seems to be caused by disabling interpreters in `links-common.profile`. Placing the following links to `elinks.profile` resolves the situation:

```
ignore blacklist ${PATH}/lua*
ignore blacklist /usr/include/lua*
ignore blacklist /usr/lib/liblua*
ignore blacklist /usr/lib/lua
ignore blacklist /usr/lib64/liblua*
ignore blacklist /usr/lib64/lua
ignore blacklist /usr/share/lua*
```

### Environment

- Arch Linux x86_64 rolling
- firejail version 0.9.67 (a6672757d)

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

not required

**Comment by rusty-snake** [comment]
> Seems to be caused by disabling interpreters in links-common.profile. Placing the following links to elinks.profile resolves the situation:
> ```
> ignore blacklist ${PATH}/lua*
> ignore blacklist /usr/include/lua*
> ignore blacklist /usr/lib/liblua*
> ignore blacklist /usr/lib/lua
> ignore blacklist /usr/lib64/liblua*
> ignore blacklist /usr/lib64/lua
> ignore blacklist /usr/share/lua*
> ```

`include allow-lua.inc` :wink:

**Comment by jose1711** [comment]
> > Seems to be caused by disabling interpreters in links-common.profile. Placing the following links to elinks.profile resolves the situation:
> > ```
> > ignore blacklist ${PATH}/lua*
> > ignore blacklist /usr/include/lua*
> > ignore blacklist /usr/lib/liblua*
> > ignore blacklist /usr/lib/lua
> > ignore blacklist /usr/lib64/liblua*
> > ignore blacklist /usr/lib64/lua
> > ignore blacklist /usr/share/lua*
> > ```
> 
> `include allow-lua.inc` wink

aw.. :smile:

**Comment by glitsj16** [comment]
@rusty-snake Should we add `include allow-lua.inc` to our elinks.profile?

**Comment by kmk3** [comment]
@glitsj16 commented [on Nov 22](https://github.com/netblue30/firejail/issues/4707#issuecomment-975292101):

> @rusty-snake Should we add `include allow-lua.inc` to our elinks.profile?

I don't see why not.  Do you want to add it or do I add it?

**Comment by glitsj16** [comment]
> Do you want to add it or do I add it?

Feel free to add it :-)
