### ISSUE TITLE
When installing a software with wine, icons doesn't appear

### ISSUE THREAD

**Issue by Froggy232** [netblue30/firejail#4741]
Hi,
I use firejail on an archlinux + gnome system.
When installing a software with wine without firejail, the icons appear on the app drawer and in the $HOME/.local/share/applications/wine folder.
With firejail, there is no icons in the app drawer and no new files in $HOME/.local/share/applications/wine.
I have tried to add a noblacklist entry in wine.local, but it doesn't solve it.
Does someone have an idea on how to fix it?
Thanks you

**Comment by rusty-snake** [comment]
```
mkdir ${HOME}/.local/share/applications/wine
read-write ${HOME}/.local/share/applications/wine
```

**Comment by Froggy232** [comment]
Thanks you, but do I need to add that to the wine.local file?

**Comment by rusty-snake** [comment]
Yes.

If it does not work, use

```
mkdir ${HOME}/.local/share/applications/wine
read-only ${HOME}/.local/share/applications
read-write ${HOME}/.local/share/applications/wine
ignore read-only ${HOME}/.local/share/applications
```

**Comment by Froggy232** [comment]
It's worked!
Thanks you a lot

**Comment by kmk3** [comment]
@rusty-snake commented [on Dec 5](https://github.com/netblue30/firejail/issues/4741#issuecomment-986223292):

> Yes.
> 
> If it does not work, use
> 
> ```
> mkdir ${HOME}/.local/share/applications/wine
> read-only ${HOME}/.local/share/applications
> read-write ${HOME}/.local/share/applications/wine
> ignore read-only ${HOME}/.local/share/applications
> ```

Shouldn't that be added to the default wine.profile?

**Comment by rusty-snake** [comment]
It can be used to escape the sandbox, so maybe we should add it as a comment. On the other hand wine.profile is already open as fuck so I don't care if we add it enabled. Do what you want.
