### ISSUE TITLE
Allow running `firecfg` as non-root

### ISSUE THREAD

**Issue by WhyNotHugo** [netblue30/firejail#4753]
### Is your feature request related to a problem? Please describe.

`firecfg` creates per-user overrides for desktop files which point to a hardcoded binary in `/usr/bin/`.

I'd like non-sudo users to be able to run `firecfg` so as to create these symlinks for themselves too.

### Describe the solution you'd like

Allow running `firecfg` as non-root. This won't touch `/usr/local/bin`, but only write the per-user desktop overrides. Might make sense to require an extra flag to avoid accidentally running it when someone intends to use `sudo firecfg`.

### Describe alternatives you've considered

1. Have `firecfg` mutate files in `/usr/share/applications/`. Should work, but I'm personally reluctant of mutating package-owned files. I'm sure many others would have an issue with this too.

2. There's, regrettably, no local overrides for desktop files (e.g.: I don't think `/usr/local/share/applications` is a thing).

### Additional context

Using `sudo firecfg` works, but it needs to be run by each user, which means each local users needs to have `sudo` permissions, which isn't always viable.

**Comment by rusty-snake** [comment]
Could you describe the difference to `firecfg --bindir=$HOME/.local/bin` and `firecfg --fix`?

**Comment by WhyNotHugo** [comment]
Sorry, `firecfg --fix` seems to be exactly what I was looking for, not sure how I misinterpreted that (I swear I just went through the whole man page!).
