### ISSUE TITLE
Support for youtube-dl forks in e.g mpv

### ISSUE THREAD

**Issue by NetSysFire** [netblue30/firejail#4754]
### Description

youtube-dl was abandoned and yt-dlp is the most popular alternative, but there are loads of other forks but I do not know how relevant they are to us. Since youtube-dl has not got any updates since 4 months it might stop working very soon and another path is needed in `private-bin` so it can keep working with e.g yt-dlp. It might be counterproductive to just randomly add the 5 most popular (which is also hard to define) yt-dl forks into there, so what do we do? For now I got yt-dlp added into an override but it would be great if there would be some default solution since it will potentially affect many.

Potentially relevant: #4539

**Comment by kmk3** [comment]
@NetSysFire commented [on Dec 9](https://github.com/netblue30/firejail/issues/4754#issue-1075078474):

> ### Description
> 
> youtube-dl was abandoned and yt-dlp is the most popular alternative, but
> there are loads of other forks but I do not know how relevant they are to us.
> Since youtube-dl has not got any updates since 4 months it might stop working
> very soon and another path is needed in `private-bin` so it can keep working
> with e.g yt-dlp.

This is already the case since #4634.  The yt-dlp config paths are missing
though, so I'll add them.
