### ISSUE TITLE
Can session D-BUS and --net both available

### ISSUE THREAD

**Issue by lkunxyz** [netblue30/firejail#4769]
i using this cmd:
firejail --noprofile --net=eth0 --dbus-system=filter firefox

but when connect to dbus system,i got an error:
**`_Connection Error Failed to connect to socket /tmp/dbus-6HyK661YVi: Connection refused_`**

i have some request need dbus and --net work both of them at the same time

can anybody help me ?
thanks a lot!

**Comment by glitsj16** [comment]
Why are you using `--noprofile`? That option is for debugging purposes and shouldn't be used for anything else. Our [firefox.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/firefox.profile#L49) already has D-Bus user filtering for some adressess:
```
[...]
dbus-user filter
dbus-user.own org.mozilla.Firefox.*
dbus-user.own org.mozilla.firefox.*
dbus-user.own org.mpris.MediaPlayer2.firefox.*
ignore dbus-user none
[...]
```

If you need dbus-system filtering, use a similar syntax in a `firefox.local` file. You will have to create that if you don't use one yet. Besides **enabling** filtering you also need to supply the actual D-Bus **addressess** you want to **own** or **talk** to. In any case, having --net can be used together with D-Bus filtering yes.

What are you trying to achieve exactly?

**Comment by rusty-snake** [comment]
It's not possible to use `--net` when D-Bus is configured to use an abstract socket.

I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
