### ISSUE TITLE
Able to set negative niceness for a process as a regular user with firejail

### ISSUE THREAD

**Issue by dirtybytes** [netblue30/firejail#477]
Likely not a huge security issue, but still.
According to this: http://linux.die.net/man/2/nice
> Only the superuser may specify a negative increment, or priority increase.

And, indeed, `nice -n -20 /bin/bash` would start bash with 0 niceness value, informing you of the failure. However, a recently implemented `--nice` option allows you to bypass it, setting the initial niceness of a process to -20, probably because firejail is SUID root. It looks like it can't be done from within the jail itself, but it still allows a regular user to do something he shouldn't be able to using this program.

**Comment by netblue30** [comment]
Fixed, thank you for the bug.
