### ISSUE TITLE
Highlight profile blacklists lua which is required

### ISSUE THREAD

**Issue by michelesr** [netblue30/firejail#4775]
### Description

Highlight text formatter program fails to run due to lua libraries being [blacklisted](https://github.com/netblue30/firejail/blob/master/etc/inc/disable-interpreters.inc#L13).

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Run in bash `firejail highlight`

### Expected behavior

The program runs

### Actual behavior

The program fails with the following error:

```
/usr/bin/highlight: error while loading shared libraries: liblua.so.5.4: cannot open shared object file: Permission denied
```

### Behavior without a profile

_What changed calling `LC_ALL=C firejail --noprofile /path/to/program` in a terminal?_

The program works normally.

### Environment

- Arch Linux
- Firejail version 0.9.66

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).

**Comment by glitsj16** [comment]
@michelesr Can you confirm the app works when adding the below to your highlight.local:

```
# Allow lua (blacklisted by disable-interpreters.inc)
include allow-lua.inc
```

**Comment by michelesr** [comment]
> Can you confirm the app works when adding the below to your highlight.local:

Yes, it works.

**Comment by glitsj16** [comment]
@michelesr Thanks for reporting this and confirming the fix! I'll add a PR to get this ready for the next milestone.
