### ISSUE TITLE
VirtualBox not starting when clicking on it with newest firejail version

### ISSUE THREAD

**Issue by freedom4JA** [netblue30/firejail#4796]
(Linux Mint 20.2, 5.4.0-91-generic)
With LM firejail version all was fine, now when i switched to the latest  PPA version 0.9.66, when clicking on VirtualBox (Linux Mint Repo) to start it, it would do nothing. 

It only starts when I rightclick VB and press  "start Oracle VM Manager" or when I launch it in the terminal. 

Starting via Terminal:

_~$ firejail virtualbox --verbose
Reading profile /etc/firejail/virtualbox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 4270, child pid 4271
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: skipping asound.conf for private /etc
Warning: skipping conf.d for private /etc
Warning: skipping crypto-policies for private /etc
Warning fcopy: skipping /etc/pulse/client.conf.d/01-enable-autospawn.conf, cannot find inode
Private /etc installed in 44.56 ms
Private /usr/etc installed in 0.01 ms
Blacklist violations are logged to syslog
Child process initialized in 179.96 ms
Error getpwuid: main.c:236 init_cfg: No such file or directory

Parent is shutting down, bye..._

Thanks in advance, sorry when this was already been asking. But I really would like to understand this a bit more.

**Comment by rusty-snake** [comment]
Gotcha firejail-in-firejail. (#2877)

Does `firejail /path/to/virtualbox --verbose` (e.g. ` firejail /usr/bin/virtualbox --verbose`) work?

What changes if you add `private-etc passwd,login.defs,firejail` in virtualbox.local.

**Comment by freedom4JA** [comment]
firejail /usr/bin/virtualbox --verbose works with the same effect like the output of my post.
After copied private-etc... exactly like that in my /~/.config/firejail/VirtualBox.local file I get this output:

$ VirtualBox
Reading profile /etc/firejail/VirtualBox.profile
Reading profile /home/tony/.config/firejail/VirtualBox.local
Reading profile /etc/firejail/virtualbox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 10512, child pid 10513
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: skipping asound.conf for private /etc
Warning: skipping conf.d for private /etc
Warning: skipping crypto-policies for private /etc
Warning fcopy: skipping /etc/pulse/client.conf.d/01-enable-autospawn.conf, cannot find inode
Private /etc installed in 83.86 ms
Private /usr/etc installed in 0.01 ms
Blacklist violations are logged to syslog
Child process initialized in 218.83 ms
/usr/bin/VirtualBox: 1: awk: Permission denied
/home/tony/.gtkrc-2.0:1: Unable to find include file: ".gtkrc-xfce"

Parent is shutting down, bye...

Then its opening like before ( like I can say) . so opening via rightclick or via terminal till now, not so problematic for me

**Comment by freedom4JA** [comment]
> Gotcha firejail-in-firejail. (#2877)
> 
> Does `firejail /path/to/virtualbox --verbose` (e.g. ` firejail /usr/bin/virtualbox --verbose`) work?
> 
> What changes if you add `private-etc passwd,login.defs,firejail` in virtualbox.local.

I checked it again yes it was firejail in firejail. I removed in the VirtualBox starter before U% the firejail part and now it works. So only VLC mysteriously not want to start directly.
