### ISSUE TITLE
VLC Player can't open with doubleclick on icon with latest firejail

### ISSUE THREAD

**Issue by freedom4JA** [netblue30/firejail#4797]
(Linux Mint 20.2-5.4.0-91-generic)
Now when I installed the latest firejail version 0.9.66 I noticed that I can't anymore open VLC Player itself by doubleclick the icon.
I get the notification:
"Command >> usr/bin/vlc --started-from-file << couldn't executed. Child process >>usr/bin/vlc<< could not be executed ( File or directory couldn't be found)"    - but it's there ^^

For completion i added also a terminal command, maybe it's relevant also:
User $ vlc
Reading profile /etc/firejail/vlc.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-player-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 13339, child pid 13340
6 programs installed in 10.91 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: not remounting /run/user/1000/gvfs
Warning: cleaning all supplementary groups
Child process initialized in 119.09 ms
VLC media player 3.0.9.2 Vetinari (revision 3.0.9.2-0-gd4c1aefe4d)
[0000556a0ff965b0] main libvlc: VLC wird mit dem Standard-Interface ausgeführt. Benutzen Sie 'cvlc', um VLC ohne Interface zu verwenden.
qt5ct: using qt5ct plugin
/home/tony/.gtkrc-2.0:1: Include-File couldn't be found: ».gtkrc-xfce«
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: yes
[0000556a1002adc0] main playlist: playlist is empty
QObject::~QObject: Timers cannot be stopped from another thread

Parent is shutting down, bye...

**Comment by kmk3** [comment]
@freedom4JA Hello, I've edited the OP to use code fences to fix the formatting
(edit the post to see the source).

Example:

    ```console
    $ echo foo
    foo
    ```

Result:

```console
$ echo foo
foo
```

Please use code fences when posting code, to make it easier to read and to make
the GitHub quoting feature work properly.
