### ISSUE TITLE
private-dev breaks gpg?

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#482]
This seems really odd, since this didn't happen prior to gpg 2.1. Basically, when I go to use gpg with mutt, I have to disable `private-dev`. Otherwise, gpg fails to work and says "No private key found" or something similar to that. I'm just curious as to why `private-dev` affects gpg when the gpg man page, the gpg-agent man page, and the pinentry man page all don't mention /dev at all.

**Comment by netblue30** [comment]
Under /dev I allow /dev/random and /dev/urandom. Are you also using --private-etc?

**Comment by chiraag-nataraj** [comment]
Yeah, I'm also using --private-etc. Here's my complete profile:
````
# Necessary to get Mutt working
whitelist ${HOME}/.mutt
whitelist ${HOME}/.muttrc
whitelist ${HOME}/.signatures
whitelist ${HOME}/.mailcap
whitelist ${HOME}/sent
whitelist ${HOME}/.mutt_cache
whitelist ${HOME}/Mail
whitelist ${HOME}/.gnupg

# To store files
whitelist ${HOME}/Downloads

# Enhance security

private-bin sh,mutt,mutt_dotlock,bash,emacsclient,elinks,gpg,gpg-agent,pinentry
# private-dev
private-etc Muttrc.d/,Muttrc,alternatives/,resolv.conf,ssl/,mime.types
noroot
caps.drop all
seccomp.keep open,access,prctl,fstat,mmap,write,read,close,munmap,chown,unshare,fcntl,execve,brk,mprotect,arch_prctl,getpid,getuid,getgid,geteuid,getegid,rt_sigprocmask,rt_sigaction,uname,stat,getppid,getpgrp,getrlimit,getpeername,set_tid_address,set_robust_list,futex,getrusage,umask,ioctl,socket,connect,lseek,getsid,pipe,clone,dup2,wait4,openat,rt_sigreturn,getdents,exit_group,faccessat,lstat,pread64,pwrite64,ftruncate,select,unlink,mkdir,link,rmdir,alarm,readlink,sendto,fdatasync,recvfrom,chmod,getcwd,setrlimit,utime,mlock,clock_gettime,setresgid,chdir,fsync,nanosleep,poll,sendmmsg,bind,getsockname,recvmsg,writev,mremap,rename,truncate,sched_yield,sysinfo
nogroups
````

**Comment by netblue30** [comment]
Comment out private-etc and give it a try - maybe they keep some files over there.

**Comment by chiraag-nataraj** [comment]
Here's the exact output when I uncomment `private-dev` and comment `private-etc`:
````
Reading profile /home/chiraag/.config/firejail/mutt.profile
Parent pid 9687, child pid 9688

Child process initialized
gpg: encrypted with 4096-bit RSA key, ID 6B8E9623, created 2013-11-25
      "Chiraag Nataraj <chiraag.nataraj@gmail.com>"
gpg: public key decryption failed: Invalid IPC response
gpg: decryption failed: No secret key
Waiting for Emacs...
Mailbox is unchanged.

parent is shutting down, bye...
````

**Comment by netblue30** [comment]
Let's mark it as a bug, I'll try to look into it.

**Comment by chiraag-nataraj** [comment]
Okay it works with the latest firejail update. I'm going to go ahead and close this.

**Comment by chiraag-nataraj** [comment]
Never mind...I spoke too soon. It's still an issue with the latest rc.

**Comment by vn971** [comment]
Maybe it's just because of `private-bin` or `seccomp.keep` ?
How to reproduce the issue (the simplest way) ?

**Comment by chiraag-nataraj** [comment]
Nope. `private-bin` is not the issue (I've commented it out before with no change). `seccomp.keep` yields the same results.

**Comment by chiraag-nataraj** [comment]
Okay...this is interesting. Somewhere along the way, I ended up using a different `gpg-agent`. I don't know if it's a result of some change in `firejail` or the change in `gpg-agent`, but this works now. I'll go ahead and close it.
