### ISSUE TITLE
profile-request for metaless anonymized app session. 

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#4844]
https://getsession.org/

Opensource decentralized messenger metainformation free, per default onion nodes routing.

**Comment by kmk3** [comment]
@osevan commented [on Jan 11](https://github.com/netblue30/firejail/issues/4844#issue-1098763880):

> https://getsession.org/
> 
> Opensource decentralized messenger metainformation free, per default onion
> nodes routing.

Please stop opening new issues for requesting profiles.

This is the proper way to do so:

1. Check #1139 for an existing request for the program in question
2. If such a comment exists, upvote it
3. If not, add a new comment in there
