### ISSUE TITLE
Shellcheck crashes with firejail.

### ISSUE THREAD

**Issue by redxef** [netblue30/firejail#4875]
### Description

Running shellcheck results in the following error when using firejail

```
$ /usr/local/bin/shellcheck
/usr/bin/shellcheck: error while loading shared libraries: libHSrts-ghc9.0.2.so: cannot enable executable stack as shared object requires: Operation not permitted
```
But succeeds when running directly

```
$ /usr/bin/shellcheck
No files specified.

<usage output, etc.>
```

_shellcheck version_: `0.8.0`
_firejail version_: `0.9.66`

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Try to run shellcheck
2. observe crash

### Expected behavior

shellcheck should be able to run.

### Actual behavior

Shellcheck aborts with the error message `/usr/bin/shellcheck: error while loading shared libraries: libHSrts-ghc9.0.2.so: cannot enable executable stack as shared object requires: Operation not permitted`

### Behavior without a profile

_What changed calling `LC_ALL=C firejail --noprofile /path/to/program` in a terminal?_

The program runs as expected.

### Environment

- _Linux Distro_: Arch Linux, up to date as of `2022-01-21 10:42:38+0100`
- _Firejail version_: `0.9.66`
- _shellcheck version_: `0.8.0`

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
/usr/bin/shellcheck: error while loading shared libraries: libHSrts-ghc9.0.2.so: cannot enable executable stack as shared object requires: Operation not permitted
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

```
```

</p>
</details>

**Comment by rusty-snake** [comment]
Does `firejail --ignore=memory-deny-write-execute /usr/bin/shellcheck …` work?

**Comment by glitsj16** [comment]
On Arch Linux I cannot reproduce BUT I use [shellcheck-bin](https://aur.archlinux.org/packages/shellcheck-bin/) from AUR, which doesn't have the haskell dependencies. That version works as expected here, including with memory-deny-write-execute (a nice option to have in a sandbox). I'm assuming the referenced `libHSrts-ghc9.0.2.so` in your error is a haskell kib, correct?

There's not a trace of haskell in our repo currently. Maybe someone who has experience with it could create a allow-haskell.inc and its counterparts.

**Comment by redxef** [comment]
`firejail --ignore=memory-deny-write /usr/bin/shellcheck` doesn't work too and results in the same error.

**Comment by rusty-snake** [comment]
<code>firejail --ignore=memory-deny-write<b>-execute</b> /usr/bin/shellcheck</code>

**Comment by rusty-snake** [comment]
Is there any seccomp related error?

https://github.com/netblue30/firejail/blob/5356609ae972c55c699bb08acc6bb09fbb054216/etc/templates/syscalls.txt#L92-L99

Or anything else in you syslog?

If not, you have to comment the profile and uncomment it line for line.

**Comment by redxef** [comment]
Seccomp reported `mprotect`, since the last option in the shellcheck config was `memory-deny-write-execute` I disabled this option which solved it.

**Comment by MiltiadisKoutsokeras** [comment]
Confirmed in Arch Linux, Firejail 0.9.66 and shellcheck 0.8.0. Workaround `firejail --ignore=memory-deny-write-execute /usr/bin/shellcheck` works.
