### ISSUE TITLE
Hardware key not detected on keepassxc

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#4883]
@miragy69 at https://github.com/keepassxreboot/keepassxc/issues/7317#issue-1109477546:

> ## Summary
> 
> Keeppassxc can't detect any hardware key after get in the jail. Hardware serial number is detectable. (Edited) Please reassign the label if needed.
> ## Temporary solution
> 
> The issue can be solved by commented out these applications under `/usr/lib/firejail/firecfg.config`. Then `# firecfg --clean && firecfg` for recreate links again ![image](https://user-images.githubusercontent.com/75862210/150373591-e5763be4-eabd-4853-a8f7-68546ed9ff82.png) for commenting out the keepassxc-proxy can solve the issue [#6230](https://github.com/keepassxreboot/keepassxc/issues/6230), i.e. you don't have to manually click reload on browser plugin for password autoloading.
> ## Looking for future support on firejail
> 
> It will make safer for running keepassxc in the firejail, if the above issue can be solved. Many thanks.

----

Possible solutions:
1. Add a comment (`Put 'ignore nou2f' and 'ignore private-dev' in your keepassxc.local`).
2. Remove `nou2f` and a a comment for `private-dev` (`If you need to plugin devices while kpxc is running add ...`)
3. Remove both, `nou2f` and `private-dev`.

I'm not sure which one is the best, but I think we should fix this for 0.9.68.

_Originally posted by @rusty-snake in https://github.com/netblue30/firejail/discussions/4770#discussioncomment-2057394_

**Comment by kmk3** [comment]
@rusty-snake commented [on Jan 27](https://github.com/netblue30/firejail/issues/4883#issue-1116098223):

> @miragy69 at [keepassxreboot/keepassxc#7317 (comment)](https://github.com/keepassxreboot/keepassxc/issues/7317#issue-1109477546):
> 
> > ## Summary
> > 
> > Keeppassxc can't detect any hardware key after get in the jail. Hardware
> > serial number is detectable. (Edited) Please reassign the label if needed.

[...]

> Possible solutions:
> 
> 1. Add a comment (`Put 'ignore nou2f' and 'ignore private-dev' in your
>    keepassxc.local`).
> 2. Remove `nou2f` and a a comment for `private-dev` (`If you need to plugin
>    devices while kpxc is running add ...`)
> 3. Remove both, `nou2f` and `private-dev`.
> 
> I'm not sure which one is the best, but I think we should fix this for
> 0.9.68.

2 sounds good to me, so I went with that on #4903.

**Comment by rusty-snake** [comment]
Reopen to keep attention to 

1. > Does keepass and keepassx support hardware keys?
2. "ignore nou2f" // "ignore private-dev"

**Comment by kmk3** [comment]
@rusty-snake commented [on Feb 6](https://github.com/netblue30/firejail/issues/4883#issuecomment-1030823929):

> Reopen to keep attention to
> 
> 1. > Does keepass and keepassx support hardware keys?

Well, keepassx is unmaintained and seemingly has no docs and I can't really
tell the status from the docs of keepass (which to me appears to only claim to
work with keys that emulate a usb keyboard):

* <https://keepass.info/help/kb/yubikey.html>

If you don't see anything that confirms it either I'll revert both.

> 2. "ignore nou2f" // "ignore private-dev"

Fixed on commit 91b04172b ("keepass*: fix typo in private-dev note",
2022-02-06).

**Comment by rusty-snake** [comment]
The yubikey support in kpxc seems to be based on https://github.com/kylemanna/keepassx / https://github.com/keepassx/keepassx/pull/52 which was never merged. For me it looks like kpx never got official support for it.


keepass seems to support hw keys (via plugin).
