### ISSUE TITLE
Firejail reports error 'parent is shutting down, bye' when trying to run ubuntu-clock-app.clock snap package on Ubuntu 16.04

### ISSUE THREAD

**Issue by igor2x** [netblue30/firejail#489]
Hi,
Ubuntu 16.04 now supports snap packages. If I understand correctly snap packages are installed in some kind of isolation. But it looks like applications installed using snap can NOT also be used with firejail. See bellow.

1. Install firejail from official repository
sudo apt-get install firejail

2. Check firejail version
firejail --version

  Above command outputs: firejail version 0.9.38

3. Search the snap 'ubuntu clock' application
sudo snap find ubuntu-clock-app

4. Install 'ubuntu clock' application using snap
sudo snap install ubuntu-clock-app

5. Ubuntu snap packages are installed in /snap/<app_nam>/<version>/ directory and can be executed from /snap/bin/<app_name>
cd /snap/bin/
ls -l

  Note: We see application name is: ubuntu-clock-app.clock

6. Run application
/snap/bin/ubuntu-clock-app.clock 

  Note: Application starts-up without a problem and clock is displayed.

7. Close application using mouse.

8. Now try to firejail the application.
firejail /snap/bin/ubuntu-clock-app.clock 

  -------- Error message --------
  Reading profile /etc/firejail/generic.profile
  Reading profile /etc/firejail/disable-mgmt.inc
  Reading profile /etc/firejail/disable-secret.inc
  Reading profile /etc/firejail/disable-common.inc

  ** Note: you can use --noprofile to disable generic.profile **

  Parent pid 3770, child pid 3771

  Child process initialized
  need to run as root or suid

  parent is shutting down, bye...
  -------- End of Error message -------- 

9. Try running as root as message instructs. 
sudo firejail /snap/bin/ubuntu-clock-app.clock 
 
  -------- Error message -------- 
  Reading profile /etc/firejail/server.profile 
  Reading profile /etc/firejail/disable-mgmt.inc 
 
  ** Note: you can use --noprofile to disable server.profile ** 
 
  Parent pid 3777, child pid 3778 
  The new log directory is /proc/3778/root/var/log 
 
  Child process initialized 
  Bad system call 
 
  parent is shutting down, bye... 
  -------- End of Error message --------  
 
It looks some problem using firejail and snap applications.

It is going to be interesting how to jail applications using snap package. Mozilla has already announced that Firefox is going to be provided as snap package, see: 
https://blog.mozilla.org/futurereleases/2016/04/21/firefox-default-browser-for-linux-users-ubuntu-new-snap-format-coming-soon/

**Comment by netblue30** [comment]
I'll give it a try and let you know. "Bad system call" probably was generated because seccomp killed some process running inside the sandbox. I don't think it will work with the default profiles.

**Comment by netblue30** [comment]
For firejail version 0.9.38 use this profile:
`````
################################
# Generic Ubuntu snap application profile
################################
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc

whitelist ~/snap
include /etc/firejail/whitelist-common.inc

caps.keep chown,sys_admin
`````
Save it as snap.profile and start the application:
`````
$ firejail --profile=snap.profile  /snap/bin/ubuntu-clock-app.clock
`````

I also put a similar file in git on the master branch, it is installed in /etc/firejail/snap.profile

**Comment by igor2x** [comment]
1. I created file:  ~/.config/firejail/ubuntu-clock-app.clock.profile and saved above settings.
2. Run command: firejail ubuntu-clock-app.clock
3. Application starts fine in jail.

Thanks. Problem fixed.
