### ISSUE TITLE
LibreWolf - Can't launch additional WebPages into New Tabs via Firejail Command

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#4891]
firejail version 0.9.64.4
Debian 11
LibreWolf [v96.0.3-2](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v96.0.3-2)

This issue is similar to [one reported for Firefox](https://github.com/netblue30/firejail/issues/4670).

A list of LibreWolf AppImages can be found [here](https://gitlab.com/librewolf-community/browser/appimage/-/releases). Here's the command I'm using to run LibreWolf:
`firejail --appimage --profile=/etc/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage`

The problem occurs after first launch, when I'm trying to open additional web pages. For example, let's say LibreWolf is already running, and I want to open [Ebay](https://www.ebay.com) from the command line:
`firejail --appimage --profile=/etc/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage https://www.ebay.com`

Instead of opening Ebay into a new tab, I get this error:
![LW](https://user-images.githubusercontent.com/151919/152204433-8623598b-5dc9-42ed-9967-75af612cc128.png)

In a prior AppImage of LibreWolf, [version 96.0.2-1](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v96.0.2-1), I was able to get past this issue using a custom profile:

**~/.config/firejail/librewolf.profile**
```
# Firejail profile for Librewolf
# Description: Firefox fork based on privacy
# This file is overwritten after every install/update
# Persistent local customizations
include librewolf.local
# Persistent global definitions
include globals.local

noblacklist ${HOME}/.cache/librewolf
noblacklist ${HOME}/.librewolf

mkdir ${HOME}/.cache/librewolf
mkdir ${HOME}/.librewolf
whitelist ${HOME}/.cache/librewolf
whitelist ${HOME}/.librewolf

whitelist /usr/share/doc
whitelist /usr/share/gtk-doc/html
whitelist /usr/share/mozilla
whitelist /usr/share/webext
include whitelist-usr-share-common.inc

dbus-user filter
dbus-user.own org.mozilla.librewolf.*
ignore dbus-user none

# Redirect
include firefox-common.profile
```
Then, I'd launch [v96.0.2-1](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v96.0.2-1) using the custom profile above:
`firejail --appimage --profile=~/.config/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage`

Later, when I'd launch a URL (with LibreWolf already running), it would open that URL in a new tab with the following command:
`firejail --appimage --profile=~/.config/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage https://www.ebay.com`

However, in [LibreWolf version v96.0.3-2](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v96.0.3-2), the custom profile above doesn't succeed in launching URLs into new tabs.

Hopefully, the default LibreWolf profile can be modified to prevent this issue. In the meantime, I'd appreciate any suggestions of how I might modify the custom profile above to prevent the issue. Again, the custom profile above worked in [v96.0.2-1](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v96.0.2-1), but doesn't prevent the issue in [v96.0.3-2](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v96.0.3-2) .

**Comment by Lonniebiz** [comment]
I've also brought this issue to the attention of the LibreWolf AppImage maintainers:
https://gitlab.com/librewolf-community/browser/appimage/-/issues/32

I don't think they're at fault for this issue, but I was hoping that they may be able to offer insight that leads to us making a bullet proof profile for LibreWolf.

**Comment by rusty-snake** [comment]
```
dbus-user.talk io.gitlab.librewolf.*
```

**Comment by Lonniebiz** [comment]
In the custom profile, shown above. I changed the following line:
`dbus-user.own org.mozilla.librewolf.*`
to
`dbus-user.own io.gitlab.librewolf.*`

After closing LibreWolf, and relaunching LibreWolf  [v96.0.3-2](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v96.0.3-2), I again tried to open Ebay into a new tab with the following command line like this:
`firejail --appimage --profile=~/.config/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage https://www.ebay.com`

The error still occurred:
![LW](https://user-images.githubusercontent.com/151919/152219921-42b67568-7d43-46c9-809d-202a4a26450f.png)

**Comment by Lonniebiz** [comment]
I'm not sure why this issue is closed. So far, nothing I've tested solves the issue.

I'm using this profile:
https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/librewolf.profile

I'm using Version 97 of LibreWolf:
https://gitlab.com/librewolf-community/browser/appimage/-/releases/v97.0-1

I launch LibreWolf with this command:
`firejail --appimage --profile=~/.config/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage`

I attempt to launch additional pages into tabs like this (ebay in this example):
firejail --appimage --profile=~/.config/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage https://www.ebay.com

I still get the following error:
"LibreWolf is already running, but is not responding. To use LibreWolf, you must first close the existing LibreWolff process, restart your device, or use a different profile."

**Comment by Lonniebiz** [comment]
Last night I updated Debian 11 and noticed that the Firejail Profiles package got updated.

Today, this issue 4891 is happening again. It seems that the firejail profile has been updated in a manner that has forgotten about this issue.

**Comment by rusty-snake** [comment]
As I said in #5227 this is fixed!

If you run an old firejail version without the fix, cherry-pick it by hand into a .profile (in /etc/firejail) and update the packages, this is expect and not your bug.

If nobody can show that this is still an issue with firejail 0.9.68 I'm going to close this again (tomorrow).

**Comment by kmk3** [comment]
@Lonniebiz commented [on Jul 1](https://github.com/netblue30/firejail/issues/4891#issuecomment-1172476798):

> firejail version: 0.9.64.4 Debian 11 LibreWolf (AppImage):
> [v101.0.1-1](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v101.0.1-1)
> 
> Last night I updated Debian 11 and noticed that the Firejail Profiles package
> got updated.
> 
> Today, this issue 4891 is happening again. It seems that the firejail profile
> has been updated in a manner that has forgotten about this issue.
> 
> Please reopen this issue until it gets fixed again.

[Again][1], please follow the [bug report template][2].  The information in the
template might be needed for debugging, so if that is missing, your issue is
more likely to be ignored.

Also, checking the latest profile version is part of the checklist:

> - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).

If the latest version indeed solves the issue (as @rusty-snake mentioned), just
going through the checklist could have led you directly to the fix and avoided
reopening this issue.

Lastly, aside from the template, is LibreWolf running under wayland or Xorg?

[1]: https://github.com/netblue30/firejail/issues/4670#issuecomment-962522511
[2]: https://github.com/netblue30/firejail/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/issues/5227#issuecomment-1172703949

**Comment by kmk3** [comment]
@rusty-snake commented [on Jul 1](https://github.com/netblue30/firejail/issues/4891#issuecomment-1172716880):

> [#5227 (comment)](https://github.com/netblue30/firejail/issues/5227#issuecomment-1172703949)

For reference:

@Lonniebiz commented [on Jul 1](https://github.com/netblue30/firejail/issues/5227#issuecomment-1172703949):

> **In Debian 11, I opened this file:** /etc/apt/sources.list
> 
> **And added this line to it:** deb http://deb.debian.org/debian
> bullseye-backports main
> 
> **Then, I upgraded filejail to version 0.9.70 :** sudo apt update ; sudo apt
> install firejail/bullseye-backports firejail-profiles/bullseye-backports
> 
> After, this I relaunched the LibreWolf [AppImage](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v101.0.1-1)
> using firejail and now the issue is resolved; I can launch additional pages
> in new tabs.
