### ISSUE TITLE
Question: can firejail restrict the amount of RAM a program is using?

### ISSUE THREAD

**Issue by pitchforks** [netblue30/firejail#49]
subj

**Comment by netblue30** [comment]
You would need to set up a Linux control group (https://www.kernel.org/doc/Documentation/cgroups/cgroups.txt) and set a memory limit. Then, you pass the tasks file to firejail. Example, assuming your cgroup is in /sys/fs/cgroup/g1 you will run:

`````
$ firejail --cgroup=/sys/fs/cgroup/g1/tasks
`````

**Comment by pitchforks** [comment]
Thanks.

Adding for reference: Linux control groups support, --cgroup option was added in version 0.9.20.
