### ISSUE TITLE
`quiet` from mediainfo.profile does not suppress 'Reading profile...' message

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#4900]
### Description

`firejail mediainfo --quiet` correctly suppresses `Reading profile /etc/firejail/mediainfo.profile` from output, whereas `quiet` from `~/.config/firejail/mediainfo.local` does not.

### Expected behavior

The latter should also suppress that message.

### Actual behavior

It does not.

### Environment

- Arch Linux
- Firejail version 0.9.66

### Checklist

- [ ] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [ ] I can reproduce the issue without custom modifications (e.g. globals.local).
- [X] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [X] I have performed a short search for similar issues (to avoid opening a duplicate).
- [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

**Comment by rusty-snake** [comment]
This is expected behaviour, **`quiet` must be the first** (uncommented) **command** in a profile, before any other command (including `include`) because it only affects later commands.
