### ISSUE TITLE
[feature] create /etc/firejail/local

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#4926]
### Is your feature request related to a problem? Please describe.

/etc/firejail has too many files. If you add your own or edit them, you have difficulty keeping track of them.

### Describe the solution you'd like

create /etc/firejail/local . You put your files there. It will have greater priority then /etc/firejail and less priority then .config/firejail

### Describe alternatives you've considered

Keeping manual notes of your files and edited files and then fighting with the shell to find them.

### Additional context

they are 1000 files in /etc/firejail

**Comment by rusty-snake** [comment]
IMHO we can close here and consider the idea in #4871 too.

----

- Do you need systemwide profile additions? If not, you can use `~/.config/firejail`.
- You could use git in /etc/firejail or etckeeper. ;)
