### ISSUE TITLE
broken man.profile in 0.9.68 

### ISSUE THREAD

**Issue by hyder365** [netblue30/firejail#4927]
### Description

Using firejail 0.9.68 on Arch Linux with "firecfg" run after the upgrade, I'm no longer able to view man pages with the man command. The issue is likely that "man" can no longer spawn the PAGER process. "man ls" prints the man page all at once without piping it to more/less. Running "man ls | less" works fine.

### Steps to Reproduce

Install firejail, use the mandoc package (rather than GNU man, may be related) for the "man" command, and run it.

### Expected behavior

Paging through a man page.

### Actual behavior

Man page is printed all at once.

### Behavior without a profile

Works normally.

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).

**Comment by hyder365** [comment]
There's no "less" symlink in /usr/local/bin with the other firejailed programs, and "which less" returns /sbin/less.

Nothing in ~/.config/firejail is related to less or man.

I just confirmed the same problem on a separate but similar Arch laptop with mandoc and no ~/.config/firejail directory.

**Comment by hyder365** [comment]
> Ah, the man.profile has `read-only /tmp`. It looks like your man program tries to save a temporary file in `/tmp`. You can fix this by adding `ignore read-only /tmp` to man.local. But I'm wondering why this happens on your system and not on mine. I tested with mandoc 1.14.6 and man-db 2.10.0.

Thanks. It looks like mandoc creates files in /tmp by default, on OpenBSD as well as Linux.

**Comment by netblue30** [comment]
Bug/no bug? Would it be a good idea to remove man from firecfg.config, so it is not enabled by default?

**Comment by rusty-snake** [comment]
At least `read-only /tmp` should be remove.
