### ISSUE TITLE
freshly installed debian sid - firejail not working

### ISSUE THREAD

**Issue by Micha-Btz** [netblue30/firejail#493]
hi there,

i have to set up my pc completely and after i reinstall all packages. firejail not works.
https://gist.github.com/Micha-Btz/cb3fe464590ee838928e1c607f3be6d7

I search quite some time for the error, but i don't get it. debug doesn't tell me helpfull things and in journald there is also not usefull information.
a tip for me?

> 7:33 $ uname -a
Linux sysiphus 4.5.0-2-amd64 #1 SMP Debian 4.5.2-1 (2016-04-28) x86_64 GNU/Linux

> Mai 01 17:33:40 sysiphus firejail[7422]: exiting...
Mai 01 17:33:40 sysiphus firejail[7424]: sandbox 7422, execvp into "icedove"
Mai 01 17:33:40 sysiphus firejail[7422]: firejail --tracelog --debug icedove
Mai 01 17:33:29 sysiphus firejail[7369]: exiting...

**Comment by netblue30** [comment]
Moving the discussion here: https://github.com/netblue30/firejail/issues/494
