### ISSUE TITLE
w3m doesn´t work any more

### ISSUE THREAD

**Issue by Rosika2** [netblue30/firejail#4931]
Hi all,

after the latest update of firejail (version 0.9.68) the **w3m** command-line browser doesn´t work any more, at least not like it used to.

example:

```
firejail w3m "https://itsfoss.community/"
Error: cannot access profile file: disable-passwdmgr.inc
```

So **w3m** won´t open at all.

Can anybody help me?
Thanks a lot in advance.

Many greetings from Rosika

P.S.:

My system: Linux Lubuntu 20.04.3 LTS, 64 bit

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/blob/03395e10bfd597eff5e324be53e24eb44898db98/RELNOTES#L62

If you added `include disable-passwdmgr.inc` in any of your .locals, you must remove it:
```bash
sed "/^include disable-passwdmgr.inc/d" ~/.config/firejail/*.local
```

**Comment by glitsj16** [comment]
> Error: cannot access profile file: disable-passwdmgr.inc

The `disable-passwdmgr.inc` file doesn't seem to exist in current git. There are a few references to it in [etc-fixes/0.9.52](https://github.com/netblue30/firejail/tree/master/etc-fixes/0.9.52), [etc-fixes/0.9.58](https://github.com/netblue30/firejail/tree/master/etc-fixes/0.9.58) and [etc-fixes/0.9.60](https://github.com/netblue30/firejail/tree/master/etc-fixes/0.9.60) but those are pretty dated by now. Do you still have that file on your current firejail setup? Maybe something you added yourself in ~/.config/firejail? If so, can you show us the content here please?

**Comment by Rosika2** [comment]
Hi again and thanks for your replies.

@rusty-snake and @glitsj16 :

>  If you added include disable-passwdmgr.inc in any of your .locals, you must remove it:
Uh, that might be the case. Thanks for pointing that out.

Indeed I have a `w3m.profile` in `/home/rosika/.config/firejail/` and it contains 
`include disable-passwdmgr.inc`.

At present it looks like this:

```
# Firejail profile for w3m
# Description: WWW browsable pager with excellent tables/frames support
# This file is overwritten after every install/update
quiet
# Persistent local customizations
include w3m.local
# Persistent global definitions
include globals.local

# Add the next lines to your w3m.local if you want to use w3m-img on a vconsole.
#ignore nogroups
#ignore private-dev
#ignore private-etc

noblacklist ${HOME}/.w3m

blacklist /tmp/.X11-unix
blacklist ${RUNUSER}/wayland-*

# Allow /bin/sh (blacklisted by disable-shell.inc)
include allow-bin-sh.inc

# Allow perl (blacklisted by disable-interpreters.inc)
include allow-perl.inc

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-interpreters.inc
include disable-passwdmgr.inc
include disable-programs.inc
include disable-shell.inc
include disable-xdg.inc

mkdir ${HOME}/.w3m
whitelist /usr/share/w3m
whitelist ${DOWNLOADS}
whitelist ${HOME}/.w3m
include whitelist-runuser-common.inc
include whitelist-usr-share-common.inc
include whitelist-var-common.inc

caps.drop all
ipc-namespace
machine-id
netfilter
no3d
nodvd
nogroups
noinput
nonewprivs
noroot
nosound
notv
nou2f
novideo
protocol unix,inet,inet6
seccomp
shell none
tracelog

disable-mnt
#private-bin perl,sh,w3m
private-cache
private-dev
private-etc alternatives,ca-certificates,crypto-policies,mailcap,nsswitch.conf,pki,resolv.conf,ssl
private-tmp

dbus-user none
dbus-system none

memory-deny-write-execute
```
So would it be best to comment that line out?

Tnx a lot.
Many greetings
Rosika

**Comment by rusty-snake** [comment]
> So would it be best to comment that line out?

Just remove it, the include no longer exists.

> w3m.profile in /home/rosika/.config/firejail

This is the same as w3m.profile except for private-bin commented.
Maybe just delete it and create `w3m.local` with `ignore private-bin`.
