### ISSUE TITLE
cannot create an empty sandbox any more

### ISSUE THREAD

**Issue by Rosika2** [netblue30/firejail#4953]
Hi all,

I just updated my **BodhiLinux** (BL 5, 18.04, 32 bit, running in a VM) installation per 
`sudo apt update && sudo apt upgrade`
and thus the latest **firejail** version was installed. I´m now on "firejail version 0.9.68".

The thing is: When I try to create an empty sandbox by invoking just the "firejail" command I get this message:

```
firejail
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file

** Note: you can use --noprofile to disable default.profile **

Parent pid 890, child pid 891
Error: cannot write to /proc/891/gid_map: Invalid argument
Error: proc 1 cannot sync with peer: unexpected EOF
```

Hmm, that was´t the case before the update.

So I tried using the "--noprofile option", which worked:

```
firejail --noprofile
Parent pid 934, child pid 935
Child process initialized in 14.20 ms
Willkommen zu fish, der freundlichen interaktiven Shell
Type `help` for instructions on how to use fish
```

What might be the matter here? Any suggestions are certainly welcome.

Many thanks in advance.
Rosika

**Comment by rusty-snake** [comment]
As a workaround `firejail --ignore=noroot`.

**Comment by Rosika2** [comment]
@rusty-snake:

Thanks so much for your very quick answer.


Indeed `firejail --ignore=noroot` works as desired. That´s great.

Just for some additional info (because I´m curious about it): Was there a major change of some sort as far as firejail is concerned?
I mean: why has the workaround become necessary?

Tnx a lot.
Greetings from Rosika

**Comment by Rosika2** [comment]
@rusty-snake:

I see. Thanks for the feedback.
Well, the main thing is the workaround you provided works perfectly.

Thank you very much again for your kind hep.

Many greetings
Rosika
