### ISSUE TITLE
Can't run chromium snap

### ISSUE THREAD

**Issue by ibahnasy** [netblue30/firejail#4962]
Here is the output:

`$ firejail /snap/bin/chromium
Reading profile /etc/firejail/chromium.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Warning: Warning: NVIDIA card detected, nogroups command disabled
Parent pid 15814, child pid 15815
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 61.78 ms
panic: permission denied

goroutine 1 [running]:
github.com/snapcore/snapd/snapdtool.ExecInSnapdOrCoreSnap()
	/build/snapd-d8V3hw/snapd-2.54.3+21.10.1ubuntu0.1/snapdtool/tool_linux.go:205 +0x3ee
main.main()
	/build/snapd-d8V3hw/snapd-2.54.3+21.10.1ubuntu0.1/cmd/snap/main.go:443 +0x45

Parent is shutting down, bye...
`

**Comment by rusty-snake** [comment]
[You](https://github.com/netblue30/firejail/discussions/4810) [can](https://github.com/netblue30/firejail/discussions/4554) [not](https://github.com/netblue30/firejail/discussions/4253) [sandbox](https://github.com/netblue30/firejail/issues/4563) [snaps](https://github.com/netblue30/firejail/issues/3836) [with](https://github.com/netblue30/firejail/issues/4132) [firejail](https://github.com/netblue30/firejail/issues/2943).
