### ISSUE TITLE
rmenv looks broken

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#4973]
I have a few custom profiles that use the `rmenv` option for applications I don't use that often. Yesterday I did and noticed that the environment variables I wanted removed from the sandbox are still there. It happens with Firejail from master (my regular setup) and a quick test shows the same (broken) behaviour with 0.9.68 (installed via pacman from Arch Linux repo). See STR below. Can anyone reproduce?

```console

$ firejail --quiet --rmenv=XDG_CURRENT_DESKTOP echo "\$XDG_CURRENT_DESKTOP --> $XDG_CURRENT_DESKTOP"
$XDG_CURRENT_DESKTOP --> GNOME

```

```console

$ firejail --quiet --profile=noprofile --rmenv=XDG_CURRENT_DESKTOP echo "\$XDG_CURRENT_DESKTOP --> $XDG_CURRENT_DESKTOP"
$XDG_CURRENT_DESKTOP --> GNOME

```

Also seeing it with `DISPLAY`, although that has some special status in the codebase and I might be wrong here.

```console

$ grep -i "x11" /etc/firejail/firejail.config | grep -v Screen
# Enable or disable X11 sandboxing support, default enabled.
x11 no

```

```console

$ firejail --quiet --rmenv=DISPLAY echo "\$DISPLAY --> $DISPLAY"
$DISPLAY --> :0.0

```

```console

$ firejail --quiet --profile=noprofile --rmenv=DISPLAY echo "\$DISPLAY --> $DISPLAY"
$DISPLAY --> :0.0

```

**Comment by rusty-snake** [comment]
If you double-quote the string you want to echo the parameter and variable expansion is done by your interactive non-sandboxed shell.

**Comment by rusty-snake** [comment]
To inspect environment variables inside the sandbox (with an oneliner) you can use `printenv`:
```console
$ firejail --quiet printenv XDG_CURRENT_DESKTOP 
GNOME
$ firejail --quiet --rmenv=XDG_CURRENT_DESKTOP printenv XDG_CURRENT_DESKTOP
zsh: exit 1     firejail --quiet --rmenv=XDG_CURRENT_DESKTOP printenv XDG_CURRENT_DESKTOP
```

**Comment by rusty-snake** [comment]
> If you double-quote the string you want to echo the parameter and variable expansion is done by your interactive non-sandboxed shell.

```console
$ bash -x
% firejail --quiet --rmenv=XDG_CURRENT_DESKTOP echo "\$XDG_CURRENT_DESKTOP --> $XDG_CURRENT_DESKTOP"
+ firejail --quiet --rmenv=XDG_CURRENT_DESKTOP echo '$XDG_CURRENT_DESKTOP --> GNOME'
$XDG_CURRENT_DESKTOP --> GNOME
++ __vte_prompt_command stuff, ignore
```

**Comment by glitsj16** [comment]
@rusty-snake Thanks for the tips on printenv. I had put some things in default.local, forgot about doing so and confused myself :-) All good, closing here.
