### ISSUE TITLE
ffplay fails to play anything

### ISSUE THREAD

**Issue by alkim0** [netblue30/firejail#4978]
### Description

Playing any video fails with ffplay under firejail's current profile.

### Steps to Reproduce

Install ffmpeg and firejail and play a video file after running firecfg.

### Expected behavior

It should play the video.

### Actual behavior

Errors out with error code 139

### Behavior without a profile

Plays video just fine.

### Additional context

Adding:
```
ignore dbus-user
ignore dbus-system
```
to `ffplay.local` resolves the problem.

### Environment

- Linux distribution: Arch Linux
- Firejail version: 0.9.68

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

**Comment by rusty-snake** [comment]
I can not reproduce this (Fedora Linux 35).

**Comment by glitsj16** [comment]
Same here, ffplay works fine on my Arch Linux box.

```console
$ pacman -Q ffmpeg
ffmpeg 2:5.0-4
```

I remember seeing something on issues with ffmpeg 5.x and Firefox on the Arch Linux forums. Do you happen to have ffmpeg4.4 installed?

**Comment by alkim0** [comment]
I do in fact have both ffmpeg4.4 and ffmpeg 2:5.0-4 installed. I would appreciate a link to the Arch Linux forums if you still have it @glitsj16 .

**Comment by glitsj16** [comment]
> I do in fact have both ffmpeg4.4 and ffmpeg 2:5.0-4 installed. I would appreciate a link to the Arch Linux forums if you still have it @glitsj16 .

Having ffmpeg4.4 installed alongside ffmpeg is the correct 'fix' for firefox video play on Arch Linux. Here are the links I found:

https://bbs.archlinux.org/viewtopic.php?id=274229
https://bugs.archlinux.org/task/73841

**Comment by alkim0** [comment]
Looking through the forums, I did actually have the issue mentioned in the forums, but restarting firefox actually fixed it for me.

However, since no one can reproduce this issue, it seems to be a configuration-specific problem, so I'll close this issue.

Thanks for the help.
