### ISSUE TITLE
disable-xdg.inc weirdness with ${DESKTOP} [mupdf and directory whitelist]

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#4994]
### Discussed in https://github.com/netblue30/firejail/discussions/4975

<div type='discussions-op-text'>

<sup>Originally posted by **wonbug** February 24, 2022</sup>
I'm trying to open a PDF file with `mupdf` in `~/Desktop/`

I put all these directives into `~/.config/firejail/mupdf.local`:

```
whitelist ${HOME}/Desktop/
whitelist ${HOME}/Desktop
whitelist ~/Desktop/
whitelist ~/Desktop
```

Yet when I try to open the file, I get:

```
$ /usr/bin/firejail /usr/bin/mupdf ~/Desktop/file.pdf
...
error: cannot open /home/user/Desktop/file.pdf: Permission denied
mupdf: error: cannot open document
```

Am I missing something obvious?</div>

**Comment by glitsj16** [comment]
Users are reporting problems with `disable-xdg.inc` that might be a bug: https://github.com/netblue30/firejail/discussions/4975#discussioncomment-2269810.

**Comment by smitsohu** [comment]
I can reproduce this. Definitely a bug!

**Comment by smitsohu** [comment]
You guys don't have a `~/.config/user-dirs.dirs` right?

**Comment by glitsj16** [comment]
> You guys don't have a ~/.config/user-dirs.dirs right?

As stated in #4975 my ~/Desktop is symlinked to /mnt/foo/bar _and_ I have a one-liner disable-xdg.local containing `blacklist ${DESKTOP}`. I do have  ~/.config/user-dirs.dirs. The below command runs just fine here and output is exactly the same as without firejail:

```console
$ firejail --quiet --ignore='include disable-xdg.local' /usr/bin/mupdf ~/Desktop/file.pdf
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
[file.pdf is opened]
```

Curious to hear the OP's and @crocket's answers to your question.

**Comment by crocket** [comment]
> You guys don't have a ~/.config/user-dirs.dirs right?
I don't have it.

**Comment by smitsohu** [comment]
Adding security label as it is conceivable that this leads to whitelisting a wrong path. I don't think there are other real life security implications.

**Comment by crocket** [comment]
Is this really fixed?

**Comment by smitsohu** [comment]
@crocket I was under the impression. 

Do you still run into this issue? If yes, there is a second problem lurking (and we should reopen).

**Comment by crocket** [comment]
I tested it. The issue seems fixed.
