### ISSUE TITLE
Better control of blacklisting needed

### ISSUE THREAD

**Issue by sarneaud** [netblue30/firejail#50]
As an example of how things work now, the firefox profile contains this:

    include /etc/firejail/disable-common.inc .mozilla

The .mozilla makes the include skip this line:

    blacklist ${HOME}/.mozilla

This approach doesn't work too well when the blacklist uses globs, so better control is needed.

The obvious thing to do would be to create a "whitelist" command that somehow does the opposite of "blacklist", but I think this could end up being being confusing.  What if a directory is blacklisted and a file inside it is whitelisted?  What kind of access is allowed to the directory?  Different users could reasonably make different assumptions.

An alternative is a "noblacklist" command that doesn't explicitly whitelist, but blocks further explicit blacklisting of anything that matches its pattern.  E.g., the firefox profile would look like this:

    noblacklist ${HOME}/.mozilla
    include /etc/firejail/disable-common.inc

I'm happy to go ahead and implement this.

**Comment by netblue30** [comment]
You are right, in this moment it looks like hack, and it doesn't handle globs. If you implement it I'll definitely merge it. Thanks!
