### ISSUE TITLE
test/fs/private-whitelist.exp (ERROR 4)

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#500]
private-whitelist.exp is failing for me, because of a different file list than expected.
On my local system it sees the following files:
.  ..  .asoundrc  .bashrc  .config  .Xauthority
(6 instead of 5)

And in a clean/minimal test system it finds only
.  ..  .Xauthority  .bashrc
(4 instead of 5)

**Comment by netblue30** [comment]
Thanks, I'll fix it.

**Comment by netblue30** [comment]
Fixed.
