### ISSUE TITLE
Mounted partitions not invisible

### ISSUE THREAD

**Issue by Acromonkey** [netblue30/firejail#503]
I use Lubuntu 16.04. I start firefox with

`firejail firefox`

When I want to save a page in firefox, then I can only see my desk and the folder "Downloads". That is fine.

BUT I can also save files from firefox in other partitions where my other other operating systems are located. I guess, that should not be the case.

**Comment by netblue30** [comment]
Was done on purpose, so it will allow you to view html pages on mounted drives. You can blacklist it easily: 
`````
$ firejail --blacklist=/media --blacklist=/mnt firefox
`````

**Comment by Acromonkey** [comment]
ok, thank you, good to know!!
