### ISSUE TITLE
--ignore=net does not work. Should it?

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#506]
Currently, `--ignore=net` does not ignore a `--net` command. Should it, by design?

Steps to reproduce:
`firejail --noprofile --ignore=net --net=none --ignore=net ping 8.8.8.8`

Expected: successful ping. Actually: "network unreachable".

**Comment by pyamsoft** [comment]
Ignore only ignores options specified in profile files, not on the command line.

Because net is entered on the command line, it will not be ignored.

**Comment by netblue30** [comment]
Yes, it only ignores commands in profile files.

**Comment by vn971** [comment]
@pyamsoft @netblue30 oh, you're right.
I don't know how I would prefer things to be (ignore CLI arguments or not), but at least the current behavior is documented, and makes sense. (People rarely concatenate arguments in my experience, although I did.)
Closing for now.

**Comment by vn971** [comment]
Thanks.
