### ISSUE TITLE
Hugin profile requires shell and uname

### ISSUE THREAD

**Issue by jose1711** [netblue30/firejail#5068]
### Description

Hugin's component called PTBatcherGUI requires access to shell and uname binary, otherwise this error is shown during stitching process (`uname: error 12: Cannot allocate memory`)

![obrázok](https://user-images.githubusercontent.com/1406222/159810636-2b610b08-f6c0-451d-968d-1621e9b9c86c.png)

### Steps to Reproduce

1. Run in bash `LC_ALL=C firejail hugin`
2. Load any panorama images, align and create panorama...
3. Receive the error during the last step (`PTBatcherGUI` is being executed)

### Expected behavior

No error should be generated during the process.

### Behavior without a profile

No error is shown when running without profile. Another way to get rid of it is make the following modification to the profile:
```
noblacklist ${PATH}/sh
noblacklist ${PATH}/bash
# add uname,sh to private-bin section
```

Note that on my system `/usr/bin/sh` points to `bash`.

### Additional context

I don't think the actual panorama creation is affected, the error however should not really be there.

### Environment

- Arch Linux x86_64 rolling
- Firejail version 0.9.69
- `firejail-git r8235.11af0293d-1`

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [x] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

**Comment by rusty-snake** [comment]
Open a PR with it ;)

```
include allow-bin-sh.inc
private-bin uname,sh
```
