### ISSUE TITLE
Question on Thunderbird to open links by deafult browser

### ISSUE THREAD

**Issue by SaedAbdu** [netblue30/firejail#507]
Apology if i missed some part of the wiki.
I can't get Thunderbird to open-links with chromium being my default browser, whenever a link is clicked
i get this  `/usr/bin/env: ‘perl’: Permission denied`

Tried the following:
1- uncommenting '/etc/firejail/disable-common.inc' as described in '/etc/firejail/thunderbird.profile'
 ended up being asked byThunderbird to to create a new profile.

Appreciated

**Comment by netblue30** [comment]
Uncomment one by one all include commands in the profile, until you get the one that creates the problem. My guess would be disable-devel.inc.

**Comment by netblue30** [comment]
Yes, you need to comment out "include /etc/firejail/disable-devel.inc". On some distros, Chromium needs perl executable for some reasons.
