### ISSUE TITLE
Improve Icedove/Thunderbird profile to work with Unix Mailspool account (Unable to create lock file)

### ISSUE THREAD

**Issue by boite** [netblue30/firejail#508]
Icedove pops up the following message when configured with a Unix Mailspool (Movemail) account and when started with `$ firejail icedove`:-

> Unable to create lock file /var/spool/mail/some_username.lock. For movemail to work, it is necessary to create lock files in the mail spool directory. On many systems, this is best accomplished by making the spool directory be mode 01777.

Output with `--trace` contains:-

    2:icedove:open64 /var/spool/mail/some_username:36
    2:icedove:access /var/spool/mail:-1
    2:icedove:open64 /var/spool/mail/some_username:-1

Using firejail from the master branch @ HEAD.

    $ firejail --version
    firejail version 0.9.40~rc2
    $ uname -rvmo
    3.19.0-58-generic #64~14.04.1+7.0trisquel1 SMP Tue Apr 5 15:33:26 UTC 2016 x86_64 GNU/Linux

**Comment by netblue30** [comment]
Fixed! Use --writable-var:
`````
$ firejail --writable-var icedove
`````

**Comment by boite** [comment]
Thank you; works like a charm!
