### ISSUE TITLE
--trace creates /etc/ld.so.preload

### ISSUE THREAD

**Issue by boite** [netblue30/firejail#509]
Apparmor denial messages are seen after using `firejail --trace`. This is because:-

1. `--trace` creates an empty `/etc/ld.so.preload` if it doesn't already exist
2. All glibc linked programs will attempt to read from `/etc/ld.so.preload` if if exists
3. The programs concerned have apparmor profiles which deny `read` of  `/etc/ld.so.preload`

Ideally, firejail would not create the preload file. If it's absolutely necessary then the file should be removed as soon a practically possible iff firejail created it and it's still empty.

**Comment by netblue30** [comment]
I wish I had a solution to this problem. The file created by firejail is an empty file, used as a mount point by --trace feature. There is no way I can delete it, the mount point should stay there while the sandbox is running, and there could be multiple sandboxes running.

I will document the problem, the only impact is the message generated by AppArmor. AppArmor will prevent the linker from loading the file, but it will not crash the program.

**Comment by netblue30** [comment]
I'll be tracking the problem on the project webpage here:

https://firejail.wordpress.com/support/known-problems/#apparmor
