### ISSUE TITLE
[Website Text Amends] What is SUID, and how does it affect me?

### ISSUE THREAD

**Issue by Foemass** [netblue30/firejail#5107]
### Is your feature request related to a problem? Please describe.
The following line of text in [What is SUID, and how does it affect me](https://firejail.wordpress.com/documentation-2/basic-usage/#suid) could be misleading:

>  "If you are not using Chromium or a browser based on Chromium (Opera, etc.) turn on force-nonewprivs flag in /etc/firejail/firejail.config file."  

I'm informed (by this discussion here: https://github.com/netblue30/firejail/discussions/5106) that Chromium actually works fine with force-nonewprivs yes set.  UNLESS you've set `kernel.unprivileged_userns_clone=0` or are on one of the very few distros which have it configured like that by default.  So for many people there's no reason to be warned off simply because they use Chromium.

### Describe the solution you'd like

I don't really know what I'm talking about, but in the interest of trying to be helpful here's how I'd restructure the text.

> **3. Set force-nonewprivs flag**
> 
> Turn on force-nonewprivs flag in /etc/firejail/firejail.config file. As root, open the file in a text editor and add this line:
> > 
> `force-nonewprivs yes`
> 
> The flag prevents rising privileges after the sandbox was started. It is believed to clean most SUID problems that will ever be attributed to Firejail.
> 
> Note you should avoid doing this if you use a Chromium-based browser and have set kernel.unprivileged_userns_clone=0 (or are on one of the few distros which do this by default.)   Unfortunately, Chromium-based browsers need to rise privileges in order to install their own SUID sandbox.

### Describe alternatives you've considered

As previously mentioned I basically don't know what I'm talking about, so consider this with a HUGE handful of salt.  

But I'm getting the impression that for most users, setting `force-nonewprivs yes` provides a slither of extra security with no negative ramifications.  So maybe you could just make that the default?

**Comment by rusty-snake** [comment]
Suggestion for the last paragraph:

> Note that this breaks Chromium-based software on systems where `kernel.unprivileged_userns_clone=0` is set and other programs which need to raise privileges such as wireshark or virtualbox.

**Comment by rusty-snake** [comment]
> But I'm getting the impression that for most users, setting force-nonewprivs yes provides a slither of extra security with no negative ramifications. So maybe you could just make that the default?

We would need to remove programs like wireshark from firecfg.config and detect `ernel.unprivileged_userns_clone=0`.

If we do so we should use `force-nonewprivs auto-yes` for this detection and `force-nonewprivs yes` to set it unconditional.

**Comment by rusty-snake** [comment]
As a FYI, [firejail-welcome.sh](https://github.com/netblue30/firejail/blob/master/contrib/firejail-welcome.sh) ask to set `force-nonewprivs yes` when asking for "advanced options".

**Comment by netblue30** [comment]
Fixed on the web page, thanks!

**Comment by rusty-snake** [comment]
> ITurn on force-nonewprivs flag …

typo: remove leading `I`

**Comment by netblue30** [comment]
Found it, thanks!
