### ISSUE TITLE
Log blocked syscall

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#5110]
### Is your feature request related to a problem? Please describe.

By default (kernel default) only blocked syscall are only logged if `--seccomp-error-action` is `kill` or `log` but not `Errno(EPERM)`.

### Describe the solution you'd like

Load seccomp filter with `syscall(SYS_seccomp, SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_LOG, &fl->prog)` on supported kernels (>=4.14).

### Describe alternatives you've considered

N/A

### Additional context

https://man7.org/linux/man-pages/man2/seccomp.2.html

**Comment by netblue30** [comment]
I'll look into it!

**Comment by netblue30** [comment]
All set!

**Comment by rusty-snake** [comment]
FTR: c0d314f945b405f1e90a1a43719059cd22f55de7
