### ISSUE TITLE
Feature Request to change the oom_score_adj for a sandbox

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#5122]
### Describe the solution you'd like

```
choom 123
```
in the profile will write `123` into `/proc/<pid>/oom_score_adj`

### Additional context

- `man 1 choom` and `man 5 proc`
- This should be done unprivileged because writing negative numbers is a privileged task.

**Comment by reinerh** [comment]
I like the idea!

>     * This should be done unprivileged because writing negative numbers is a privileged task.

(except the jail is started by root, similar to `--nice`)

**Comment by netblue30** [comment]
Very good idea, try it out!

**Comment by rusty-snake** [comment]
> undefined reference to `oom_set'

@netblue30 looks like you forgot to commit `oom_set`.

Shell completions and vim syntax files need to be updated as well. And a profile command would be nice too.

**Comment by netblue30** [comment]
Fixed now, I forgot to check in a new file
