### ISSUE TITLE
Trying to get in contact for a security report

### ISSUE THREAD

**Issue by mgerstner** [netblue30/firejail#5139]
We have sent multiple e-mails to netblue30@protonmail.com for reporting a vulnerability in Firejail. The first one including the full report was sent on May 3rd. We did not receive back any reply yet. Please get in contact with us about how to continue the disclosure procedure.

If we do not hear back until 2022-05-17 then we will publish the issue without further notice.

Thanks!

**Comment by kmk3** [comment]
Cc: @netblue30

**Comment by rusty-snake** [comment]
IDK what kind of vulnerability it is but if there is still a need to develop a patch you can also contact on of the other developers like @smitsohu, @topimiettinen, @reinerh or me (email: take from `git log` or `rusty-snake+firejail () mailfence com`). However release coordination (i.e. write access to firejail.wordprees.com) has only @netblue30.

---

@netblue30 any progress with my report?

**Comment by kmk3** [comment]
(Offtopic)

@rusty-snake commented [on May 12](https://github.com/netblue30/firejail/issues/5139#issuecomment-1125273884):

> you can also contact on of the other developers [or me]  (email: take from
> `git log`

To be fair, I myself am not sure how I'd accomplish that given only the git
log, as your commits (and the commits of a handful of other committers) have an
"@users.noreply.github.com" email address listed.  And considering that it has
"noreply" on it, I would assume that sending emails to it does not work.

**Comment by rusty-snake** [comment]
I meand for the other I listed, they all have a email in firejails `git log` (but IDK if this address is outdated or not). For myself I know that I use githubs-noreply, that's why I listed my.

**Comment by glitsj16** [comment]
(Offtopic)

Personally I can see how all this could be confusing for people that want to report security issues. Currently, according to https://github.com/netblue30/firejail#security-vulnerabilities the project owner's email address is the only 'correct' one to use for such reports. That being said, I agree with @rusty-snake that several other colaborators would qualify as well. But IMO we should make that VERY transparent on that part of the README.md. Just my two cents.

**Comment by rusty-snake** [comment]
OT: GitHub should just implement confidential issues. GitLab has confidential issues for years now and every full-bugtracker system like bugzilla anyway. If GH wants to provide all service for developers (Git, Code search, Wiki, Project boards, Issues, CI/CD, ...) in one place, this is a clearly missing feature.

**Comment by mgerstner** [comment]
Yes a patch still needs to be developed. Also a non-trivial patch I fear.

I can of course send the details to other developers, could you please agree on a list of devs to send this to, or a single person that will take care of sharing it with the rest as needed? Thanks!

**Comment by mgerstner** [comment]
I have forwarded the report to @rusty-snake 41237666+rusty-snake@users.noreply.github.com now, since I will be unavailable for some days.

**Comment by jsegitz** [comment]
If this doesn't work ping me and I'll step in for @mgerstner until he's back

**Comment by rusty-snake** [comment]
@jsegitz @mgerstner The github-noreply address does not work, you can use the one in https://github.com/netblue30/firejail/issues/5139#issuecomment-1125273884. Also if the patch is non-trivial @smitsohu has probably the best knowledge of the code-base.

**Comment by smitsohu** [comment]
Could someone confirm successful email exchange?

(so we can close here)

**Comment by rusty-snake** [comment]
Yes, received.

I will forward it to you later unless someone says no.
