### ISSUE TITLE
make: --disable-ids

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#5155]
### Is your feature request related to a problem? Please describe.

- additional attack surface
- you can not build firejail with `--enable-fatal-warnings --enable-analyzer` which is very helpful during development

### Describe the solution you'd like

configure option `--disable-ids` to build firejail without it's IDS

**Comment by netblue30** [comment]
IDS feature makes more sense in a server setup, on a desktop files are changing all the time during software updates. I took it out from the default build. To enable it at compile time use --enable-ids.

https://github.com/netblue30/firejail/commit/880f2c98a1dee26228530875fc45d54db68ed1c8
