### ISSUE TITLE
build: seccomp filters and man pages are always being rebuilt

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#5156]
### Is your feature request related to a problem? Please describe.

`make` rebuilds the `seccomp*` targets always, this takes unnecessary time during development.

### Describe the solution you'd like

`make` should rebuild `seccomp*` targets only if any of their sources has changed.

### Describe alternatives you've considered

Use a better build system which does stuff like this for you.

**Comment by kmk3** [comment]
Related commits:

* 9e206b7f2 ("rework src/man Makefile", 2023-07-07)
* 2b34747db ("generate seccomp filters at install time", 2023-07-07)
* 1d5fff903 ("Makefile fix", 2023-07-10)
* 6fa19aab9 ("feature: use seccomp filters build at install time for
  --restrict-namespaces", 2023-07-12)
* a6172b725 ("build: remove extraneous blank lines in makefiles",
  2023-07-12)
* 80eb28483 ("build: restore seccomp filter targets", 2023-07-13) /
  PR #5898
* 76bd5ad0f ("build: simplify code related to man pages", 2023-07-12) /
  PR #5898
* 8e79f18cf ("build: add missing makefile dep", 2023-08-12) /
  PR #5956

Note: The issue with seccomp filters specifically was fixed on commit
80eb28483 ("build: restore seccomp filter targets", 2023-07-13) /
PR #5898.
