### ISSUE TITLE
Create empty private /etc?

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#516]
Is it possible to create a private /etc with no files at all? You can with tmpfs, but that works only as root.

Is `--private-etc` with no arguments what we want?

**Comment by netblue30** [comment]
If you give --private-etc a single file, and the file doesn't exist, your /etc directory will be a regular, empty tmpfs filesystem:
`````
$ firejail --private-etc=blablabla
`````

**Comment by avoidr** [comment]
I'm confirming this. Maybe this can be documented in the man pages.

**Comment by netblue30** [comment]
Will do, thanks!

**Comment by netblue30** [comment]
All set!

**Comment by avoidr** [comment]
I saw, awesome.
