### ISSUE TITLE
private-lib makes transmission-gtk very slow to start

### ISSUE THREAD

**Issue by sinner-** [netblue30/firejail#5162]
### Description

The presence of `private-lib` directive in `transmission-common.profile` causes jailed `transmission-gtk` to take a long time to start, seems to add an extra 10 seconds or so to the startup time.

### Steps to Reproduce

_Steps to reproduce the behavior_

```
$ firejail --noprofile --private-lib transmission-gtk
Parent pid 15113, child pid 15114
Standard C library installed in 2.13 ms
Firejail libraries installed in 5.82 ms
Program libraries installed in 31.40 ms
GdkPixbuf installed in 15.13 ms
GTK3 installed in 18.06 ms
Pango installed in 0.01 ms
GIO installed in 6.68 ms
Installed 159 libraries and 5 directories
Child process initialized in 102.13 ms
```

### Expected behavior

```
$ firejail --noprofile transmission-gtk
Parent pid 15158, child pid 15159
Child process initialized in 13.38 ms

Parent is shutting down, bye...
```

### Actual behavior

`transmission-gtk` taking way too long to start.

### Behavior without a profile

`transmission-gtk` starts at ~about the same speed as un-jailed `transmission-gtk`

### Additional context

Looks like `ignore private-lib` is already set for `transmission-qt.profile`. 

### Environment

- Fedora 36
- firejail 0.9.66

### Checklist
- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [x] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

**Comment by rusty-snake** [comment]
Do you have a slow driver (i.e. HDD)?

This slowdown in also the case for other `private-` options like `private-opt` because the copy the files (instead of bind mounting them).

**Comment by sinner-** [comment]
Nope, SSD

**Comment by rusty-snake** [comment]
Duplicated of #4742
