### ISSUE TITLE
Expand whitelisted folders in steam.profile to enable Paradox Interactive Lancher to function

### ISSUE THREAD

**Issue by swimik** [netblue30/firejail#5186]
### Is your feature request related to a problem? Please describe.

On Debian bullseye with Steam installed via Debian repo and a game installed that uses Paradox Interactive Launcher a folder is required to be whitelisted for the launcher to open.
Without the folder being whitelisted the Paradox Launcher will fail to load with a 'permission denied' error and it will ask to reinstall the launcher, which also fails.

### Describe the solution you'd like

add to the whitelist for steam.profile the following
whitelist ${HOME}/.paradoxlauncher

### Describe alternatives you've considered

There does not seem to be an alternative.

### Additional context

I am using firejail 0.9.64.4-2 with default steam.profile
the master steam.profile also lacks this folder in the whitelist

**Comment by rusty-snake** [comment]
Open a PR ;)

**Comment by kmk3** [comment]
Fixed by #5223.
