### ISSUE TITLE
Flood of seccomp audit log entries

### ISSUE THREAD

**Issue by EdiDD** [netblue30/firejail#5207]
There are many log entries like: audit: SECCOMP ... and kernel: audit: ... in journal probably because of (firejail 0.9.70):

* #5110

Is there a way to disable this or make these messages silently ignored ?

**Comment by netblue30** [comment]
Bug! I have it on my computer so far for whois, transmission, and Tor browser. Log example:

`````
Jun 17 07:50:36 debian kernel: [ 4566.037606] audit: type=1326 audit(1655466636.900:143): auid=1000 uid=1000 gid=1000 ses=2 subj==firejail-default (enforce) pid=7841 comm=517420626561726572207468726561 exe="/usr/bin/transmission-qt" sig=0 arch=c000003e syscall=41 compat=0 ip=0x7f83e851f477 code=0x50000
`````

Syscall 41 is "socket" (you can get the name by running "firejail --debug-syscalls"). In the profile I had to add "netlink" and "unix":
`````
protocol unix,inet,inet6,netlink
`````
Let's look in the logs for some more programs generating this kind of messages. Thanks for the bug!

**Comment by rusty-snake** [comment]
Previous discussion with suggested fix (and deleted comment :-1:): https://github.com/netblue30/firejail/discussions/5181#discussioncomment-2947406
Please link to previous discussion if you move them.

---

> ```diff
> -protocol inet,inet6
> +protocol unix,inet,inet6,netlink
> ```

Do we really need to open all this?

**Comment by glitsj16** [comment]
Personally I tend to agree with @rusty-snake's comment above. It seems overkill to allow a potentially insecure `netlink` protocol 'just' to keep cleaner logs IMO. Perhaps a comment would be more appropriate instead?

Besides, users can always provide their own audit filtering via `/etc/audit/rules.d` for log sanity (audit tends to be very verbose by default). See [this](https://wiki.archlinux.org/title/Audit_framework#Filter_unwanted_messages) for some examples.

**Comment by netblue30** [comment]
Good point! I'll add instead a configuration flag in /etc/firejail/firejail.config to shut down the automatic logging, enabled by default. Will this work?

**Comment by glitsj16** [comment]
> Good point! I'll add instead a configuration flag in /etc/firejail/firejail.config to shut down the automatic logging, enabled by default. Will this work?

It should work yes. I happen to have some extra time to test if you 'd like. Been doing some specific audit filtering lately in another context, that's why it occurred to me it might be a more appropriate way to deal with this. Thanks for looking into things!

**Comment by EdiDD** [comment]
> Let's look in the logs for some more programs generating this kind of messages. Thanks for the bug!

It also occurs in `curl`

**Comment by netblue30** [comment]
I added "seccomp-log no" in /etc/firejail/firejail.config

https://github.com/netblue30/firejail/commit/c7e4c8ed592fee7f1644152a23c3e1343b01b922

**Comment by EdiDD** [comment]
Great! , waiting for a patched release. Thank you.

**Comment by glitsj16** [comment]
@netblue30 https://github.com/netblue30/firejail/commit/c7e4c8ed592fee7f1644152a23c3e1343b01b922 works fine, thanks! Just one question: now this is 'fixed', can/should we revert https://github.com/netblue30/firejail/commit/17774ad5464feb83edbb8971fd51e029ae608a6d?

**Comment by kmk3** [comment]
@rusty-snake commented [on May 20](https://github.com/netblue30/firejail/issues/5110#issuecomment-1132866965):

> FTR: [c0d314f](https://github.com/netblue30/firejail/commit/c0d314f945b405f1e90a1a43719059cd22f55de7)

@SkewedZeppelin Can this be reverted as well?

**Comment by SkewedZeppelin** [comment]
@kmk3

did
