### ISSUE TITLE
Can profiles remember custom parameters?

### ISSUE THREAD

**Issue by HulaHoopWhonix** [netblue30/firejail#522]
Perhaps a silly question but generally, can profiles store custom command line settings so they are enforced when starting a program?

Storing the equivalent of this in the xterm profile for example:

> $ firejail --force --x11 --net=eth0 --no-daemon --exit-with-children xterm

A related question - can Firejail profiles contain settings for X11 isolation so they are applied automatically when programs are started? So "firejail --x11" is applied transparently when a user executes an app symlinked by firecfg?

**Comment by netblue30** [comment]
You have support for "net eth0" in the current version in git. Also, --exit-with-children is done by default. I'll bring all the others in after I release the current version.
