### ISSUE TITLE
LibreWolf Can't Launch New Tabs (Again)

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#5227]
Firejail Version:  0.9.64.4
Debian 11
LibreWolf (AppImage): [v101.0.1-1](https://gitlab.com/librewolf-community/browser/appimage/-/releases/v101.0.1-1)

This issue, that was previously fixed, is broken again after I updated Debian 11 early this morning:
https://github.com/netblue30/firejail/issues/4891

I noticed the firejail profiles package got updated and now this problem is back.

I was unable to open that "fixed" issue, so I created this new bug report to give it attention.

**Comment by rusty-snake** [comment]
If you edit a .profile in /etc/firejail (against your advise) it's expected that it get overridden during update. Your custom changes should always go into a .local.

**Comment by rusty-snake** [comment]
0.9.64.4 is out of date and does not contain the fix. Update firejail (e.g. install it from backports) and report again.

**Comment by kmk3** [comment]
Closing in favor of #4891.

**Comment by kmk3** [comment]
@Lonniebiz commented [on Jul 1](https://github.com/netblue30/firejail/issues/5227#issue-1291570016):

> I was unable to open that "fixed" issue, so I created this new bug report to
> give it attention.

That's weird; please post a screenshot of that if it happens again.

**Comment by rusty-snake** [comment]
@mkm3 Only the author of an issue and accounts with write access to the repo can close issues. An closed issue can always be reopened by accounts with write access or by the the author *if* the issue was closed by the author.

**Comment by kmk3** [comment]
@rusty-snake commented [on Jul 1](https://github.com/netblue30/firejail/issues/5227#issuecomment-1172667021):

> Only the author of an issue and accounts with write access to the repo can
> close issues. An closed issue can always be reopened by accounts with write
> access or by the the author _if_ the issue was closed by the author.

Interesting, I wasn't aware of the last part; thanks.

**Comment by Lonniebiz** [comment]
**In Debian 11, I opened this file:**
/etc/apt/sources.list

**And added this line to it:**
deb http://deb.debian.org/debian bullseye-backports main

**Then, I upgraded filejail to version 0.9.70 :**
sudo apt update ; sudo apt install firejail/bullseye-backports firejail-profiles/bullseye-backports

After, this I relaunched the LibreWolf and now the issue is resolved; I can launch additional pages in new tabs.
