### ISSUE TITLE
Crash Pulseaudio

### ISSUE THREAD

**Issue by ibahnasy** [netblue30/firejail#523]
Running the lates code from the repo.
Once running applications under firejail that has sound, pulseaudio crash and sound devices disappear from the sound settings in Gnome.

$ pulseaudio --kill will restore sound device in the settings and it's solved temporary until another crash happens the same way.

**Comment by netblue30** [comment]
What distro are you using? Also, run a "pulseaudio --version".

There is a known PulseAudio bug and a workaround described here: https://firejail.wordpress.com/support/known-problems/#pulseaudio

Try to see if this solves the problem.

**Comment by ibahnasy** [comment]
This happened in Arch and Ubuntu; pulseaudio 8.0
I have tried the workaround you mentioned and it seems not to crash so far.
