### ISSUE TITLE
Skype icon in gnome-shell top bar doesn't show status

### ISSUE THREAD

**Issue by ibahnasy** [netblue30/firejail#5233]
### Description

Skype icon in the gnome-shell top bar doesn't display the current status when started with firejail.

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Run in bash `firejail skypeforlinux %U`

### Expected behavior

Skype current status should be displayed in the notifications area like when started without firejail.

### Actual behavior

It just display 3 dots.

### Behavior without a profile

Works as expected.

### Environment

- Ubuntu 22.04
- Firejail version 0.9.70.

### Checklist

- [x ] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [ x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [ x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [ x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [ x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
Reading profile /etc/firejail/skypeforlinux.profile
Reading profile /etc/firejail/electron.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 33803, child pid 33806
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: not remounting /run/user/1000/gvfs
Warning: not remounting /run/user/1000/doc
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Child process initialized in 245.28 ms

```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

```
Output too long to post it here.
https://gist.github.com/ibahnasy/55fc62bbdafe2ac41c2ad62675fa64db
```

</p>
</details>

**Comment by rusty-snake** [comment]
Duplicated of #1137 I guess.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
