### ISSUE TITLE
[Feature request] Whitelisting/blacklisting paths while running

### ISSUE THREAD

**Issue by MuhammedZakir** [netblue30/firejail#5235]
Is it possible? Something like:
```
firejail --modify=<pid|name> [--whitelist-dir=dir1,dir2,...,dirN] [--whitelist-file=file1,file2,...,flleN]
```

It would even better if globbing is supported for those args.

---

I think this may have been asked in the past, but a quick search didn't yield any result. So created this.

**Comment by rusty-snake** [comment]
AFAIK this isn't possible. And my playing with `sudo nsenter --wd=/ --mount=/proc/${child_pid}/ns/mnt mount --bind ./$HOME/.foo /$HOME/.foo` "confirmed" that.

**Comment by rusty-snake** [comment]
Closing until somebody has an idea how to do this without reimplementing kernel code in the userspace.
