### ISSUE TITLE
`--read-only=~` does not work and does not fail-fast

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#525]
The command-line argument `--read-only=~` is being accepted by `firejail` but seemingly has no effect on the sandbox. Should it?

I'm not sure about the implementation details for this, but from the UX point of view, there should be some error. Thoughts?

**Comment by netblue30** [comment]
Bug! I just put a fix int, thanks!

**Comment by vn971** [comment]
Cool!

// for history, commit: https://github.com/netblue30/firejail/commit/2a57a24561e3382059e199cac8aa8bba1bab44a0

@netblue30 BTW, offtopic. If you want, you can close issues automatically by including "fix GH-525" or "fix #525" into your commit message. The issue will automatically be closed with a reference to the commit.

**Comment by vn971** [comment]
Offtopic2. Shouldn't the example be a bit different?:

`firejail --whitelist=~/work --read-only=~/ --read-only=~/work`
versus
`firejail --whitelist=~/ --read-only=~/ --whitelist=~/work`

**Comment by vn971** [comment]
I'll PR about the offtopic2. The example given in the current documentation does not make a lot of sense, since `--whitelist=~/work` disables any effect of `--read-only=~/`.

**Comment by vn971** [comment]
Cleaning up comments here. Discussion of "offtopic2" moved to the proper PR: https://github.com/netblue30/firejail/pull/526/files

**Comment by netblue30** [comment]
Thanks!
