### ISSUE TITLE
Steam profile creates a bunch of directories.

### ISSUE THREAD

**Issue by m00nwtchr** [netblue30/firejail#5257]
...Why?

I can't even get rid of it properly because of `Error: maximum 32 --ignore options are permitted`

**Comment by rusty-snake** [comment]
For questions we have Discussions (this is an issue tracker) and for bugs we have a template.



> ...Why?

Because steam.profile is a whitelisting profile and you can only whitelist existing files.

> I can't even get rid of it properly because of `Error: maximum 32 --ignore options are permitted`

`ignore mkdir`

**Comment by m00nwtchr** [comment]
1. Why can you only whitelist existing files?
2. Still, they shouldn't be in the profile by default, rather something the user can add if they use that game/application.

**Comment by rusty-snake** [comment]
1. Technical reasons. Whitelisting is implemented with bind-mounts.
2. There are two kinds of users, technical users who notice this hidden files and nontechnical users who do bit notice those hidden files (and don't know that hidden files exist on a computer). The first category can edit configuration files, the later don't and would only notice that game states are not saved and stop using a sandbox. The default configuration should cover the most use cases and should work for nontechnical users by default.
