### ISSUE TITLE
"Error: cannot open profile file" while building profile

### ISSUE THREAD

**Issue by earth-sense** [netblue30/firejail#5267]
1. Created directory ~/.config/firejail
2. User and group are root
3. Typed CLI: firejail --build=app.profile app in directory ~/.config/firejail

The error is returned "Error: cannot open profile file"

**Comment by glitsj16** [comment]
> 1. Created directory ~/config/firejail

Firejail expects user configurations to be under `~/.config/firejail` (mind the dot).

> 2. User and group are root

Why `root` instead of your regular user?

**Comment by earth-sense** [comment]
That was a typo but it was created with a dot. Modified the OP.

After modifying both to root (before both were regular user), the error message "Error: pkexec must be setuid root" went away.

/usr/bin/pkexec has the right SETUID as -rwsr

**Comment by rusty-snake** [comment]
> /usr/bin/pkexec has the right SETUID as -rws

What matters are permissions inside the sandbox, and there it can not escalat privileges.

For which app do you try to build a profile?

**Comment by rusty-snake** [comment]
And answer this question.

> Why `root` instead of your regular user?

**Comment by earth-sense** [comment]
The question was answered: 
After modifying both to root (before both were regular user), the error message error "pkexec must be setuid root" went away.

When reverting back to user, the the errors came back:
pkexec must be setuid root
Error: cannot run the sandbox

So what is the solution to make the privileges work in the sandbox?

It seems the pkexec is complaining about the graphics. What privileges would work with the graphics?

It's a graphics app.

**Comment by earth-sense** [comment]
Would you provide different settings to try so I could get this working? There may be other users that will run into this problem.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
