### ISSUE TITLE
security issues disclosure

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#528]
There is currently no official way to disclose security issues in firejail. Since firejail is SUID and is a security tool, a disclosure channel might become very appropriate in time.

The goal of a security disclosure channel is to make fixing patches closer in time to deployment time. (By removing the gap where an issue is publicly known but no patch exist yet.)

Example solution:
an official email and GPG public key so that people can send encrypted mails.

**Comment by netblue30** [comment]
Send an email to netblue30@yahoo.com , no GPG, just keep it simple. Maybe I can open an email list where I disclose important security fixes so people can update the software.

**Comment by vn971** [comment]
For the time being, OK. If firejail grows, I'd still advise to use GPG.:) It's the "Enigmail" plugin if you use thunderbird, for example.

Anyway, closing the ticket for now.

**Comment by vn971** [comment]
"Firejail-security mailing list" sounds good, especially if it's not a google one.

**Comment by netblue30** [comment]
Can you suggest a mailing list? The only one I used so far was google.

**Comment by reinerh** [comment]
Sourceforge has mailing lists. But I guess you no longer want to use it.

**Comment by netblue30** [comment]
For sure I can use it, it is already there, I just have to enable it. Thanks.

**Comment by vn971** [comment]
Offtopic: I did send a report to the official mail address, the same day this issue was opened.

**Comment by vn971** [comment]
Note that "disclosure" and "news announcement" are very different things.
In this issue I wanted to address "disclosure", meaning letting the main developer know about issues (but not letting others know, yet).

**Comment by requiredregistration** [comment]
there is no need for mailing lists and forums. we have the issues tracker here.

e-mail cryptography is important and it would be good to have your setup ready for it. you will still be able to receive non-encrypted e-mails.

in the 'release notes' we'll learn about solved security problems.

**Comment by vn971** [comment]
@netblue30 any updates on the security issue I wrote to netblue30@yahoo.com ?
I've had some inconveniences because of this today, will be happy to hear any news. Did you get the e-mail / acknowledged what I write?

**Comment by netblue30** [comment]
OOPS! I've just found it, sorry for that. The message is form May 20, with ~/deletme. Is this right?

**Comment by vn971** [comment]
@netblue30 Yup, that's the one.  ("deleteme".)

**Comment by netblue30** [comment]
I have no idea how I managed to miss it, I'll bring in a fix shortly, thanks!

**Comment by vn971** [comment]
@netblue30 no problem. I guess you have lots of tickets/comments each weak. Will be waiting, thanks.

**Comment by netblue30** [comment]
Fixed. It was the ugliest bug so far, thanks!

**Comment by vn971** [comment]
@netblue30 hey, I want a badge then: "found the ugliest bug so far". Just kiddin.:)
Thanks!

**Comment by vn971** [comment]
Or maybe "mails a new issue every friday". (I've created one other now.)

**Comment by netblue30** [comment]
> found the ugliest bug so far

Just take a look in the README file :)
