### ISSUE TITLE
Delimitate execution permissions for firejail.

### ISSUE THREAD

**Issue by emerajid** [netblue30/firejail#5288]
**Problem**: According to what I hear, firejail is targeted at single-user systems. Partly because of  not knowing this, many people complain about firejail being a huge bulk of suid code. Personally I think (and therefore write this issue) that single-user design is a pity, because even regular users may have situations where they need to share their laptop.

**Solution I'd like**: Do what sudo does. Simple accessible only by root file with declarative syntax defining which users are allowed to use firejail. I would even suggest allowing users to turn on authorization in case they feel something very unexpected might happen.

If I propose futile feature, I would dearly like to know why, since I'm not much of a developer.

**Comment by rusty-snake** [comment]
How is your suggestion different from [firejail.users](https://firejail.wordpress.com/features-3/man-firejail-users/) and [Create a special firejail group](https://firejail.wordpress.com/documentation-2/basic-usage/)?

**Comment by emerajid** [comment]
Thank you.

I think if you mention the file in _man firejail_ somewhere in top, it would be much easier no notice. But it's off topic, so closing the issue.
