### ISSUE TITLE
firecfg: where located/installed?

### ISSUE THREAD

**Issue by frank-github** [netblue30/firejail#529]
Hi, 
installed both deb-packages (for ubuntu) firejail + firetools (Version 0.9.38)
I can't find firecfg ?!? 
It's not inside of both packages. Where can I download this file?

**Comment by reinerh** [comment]
This is only available in the upcoming release (0.9.40) or the release candidate 0.9.40-rc1 (if you are using Debian, it's in experimental).

**Comment by frank-github** [comment]
any time frame for upcoming release? 
RC1 had source only :-(

**Comment by netblue30** [comment]
> any time frame for upcoming release? 

In the next few days.
