### ISSUE TITLE
Add electronapps-common

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#5297]
### Is your feature request related to a problem? Please describe.

electronmail can't open the file picker. by disabling noroot, it works again. It's an electron app. There's a profile named electron, i assume it's the SDK, noroot is not there.

I think i remember, there was a sticky about electron apps. In general, these are tricky to handle.

### Describe the solution you'd like

There should be a electronapps-common to minimize this kind of stuff.

### Describe alternatives you've considered

Maybe also use electronapps-common in chromium-common. That's used by a lot of web browsers. Technically, they are a category of electron apps.

So electron-common could be build as a cut down version of chromium-common. That should keep complexity manageable.

**Comment by rusty-snake** [comment]
Here it is: https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/electron.profile
it's just not named `-common`.

That electronmail needs to be refactored as electron redirect profile I said somewhere else already (but could not find it). 

---

Technical electron is chromium and not the other ways around.

---

chromium + file-chooser + noroot (i.e. portals with noroot) is tracked in #4716.

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)
