### ISSUE TITLE
Error mkdir:fs_private(324): File exists

### ISSUE THREAD

**Issue by frank-github** [netblue30/firejail#530]
what do I wrong? Which file exists?
Which do I have to delete?
Problem exists from beginning of installing firejail

frank@ubuntu:~/.config/firejail$ firejail --private midori
Reading profile /etc/firejail/midori.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Parent pid 13620, child pid 13621
**Error mkdir:fs_private(324): File exists**
Error: cannot establish communication with the parent, exiting...
frank@ubuntu:~/.config/firejail$ firejail --private 
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 13630, child pid 13631
**Error mkdir:fs_private(324): File exists**
Error: cannot establish communication with the parent, exiting...

**Comment by frank-github** [comment]
running with debug option don't give more informations   :-(
Which file was checked and is existing?

Mounting a new /home directory
Mounting a new /root directory
Create a new user directory
Error mkdir:fs_private(324): File exists
Error: cannot establish communication with the parent, exiting...

**Comment by netblue30** [comment]
This could happen only if your user home directory is not under /home. Where do you keep your home directory?

**Comment by frank-github** [comment]
you are right :-)

`user:x:1000:1000:User,,,,:/media/daten/frank:/bin/bash`

and /home has a softlink

`user@ubuntu:~$ ls -l /home
insgesamt 4
drwxr-xr-x 18 admin root 4096 Mär 13 14:52 admin
lrwxrwxrwx  1 root  root   31 Feb 15  2014 ecryptfs-mount-private -> /usr/bin/ecryptfs-mount-private
lrwxrwxrwx  1 root  root   18 Apr 27  2014 frank -> /media/daten/frank
`

**Comment by netblue30** [comment]
--private also disables all other users under /home, so in this case I don't know where the other users are. Maybe in a future version I'll manage to add support for this type of home directory.
