### ISSUE TITLE
silverblue vs. firejail: fs.c:476 fs_tmpfs: No such file or directory

### ISSUE THREAD

**Issue by jonleivent** [netblue30/firejail#5306]
On Fedora Silverblue, which is an ostree-version of Fedora with /home symlinked to /var/home, firejail (0.9.66) fails:
```
$ firejail --noprofile --private
...
Error while opening directory: fs.c:476 fs_tmpfs: No such file or directory
Error: proc 3677 cannot sync with peer: unexpected EOF
Peer 3678 unexpectedly exited with status 1
```
This problem does not occur on standard Fedora, which does not symlink /home.  It also does not occur in Silverblue when firejail is not provoked into trying to protect /home (via --private, --private=... etc.).  

I am able to get firejail to function within a toolbox (podman container) on Silverblue by removing the symlink and instead mounting /var/home on /home.  That probably is unsafe to do outside the toolbox, and is at least not the direction of Silverblue (and whatever other ostree-based distros will follow).

A suggestion to handle these cases would be for firejail to follow the symlink from /home to /var/home, and do whatever protecting/remounting there instead.  A general solution would be for firejail to determine where in the symlink-resolved home path for each user in /etc/passwd (a user could have a home anywhere) there is a directory that can be mounted over either to hide that user or to remount home for that user.

**Comment by rusty-snake** [comment]
Silverblue/Kinoite is not supported by firejail.

**Comment by rusty-snake** [comment]
#2798, #3025, #3307
