### ISSUE TITLE
When using --private=/home/tests mode

### ISSUE THREAD

**Issue by linqingping** [netblue30/firejail#5308]
### Is your feature request related to a problem? Please describe.
When using --private=/home/tests mode

### Describe the solution you'd like

When using --private=/home/tests mode I want to process that only the sandbox has permission to access the /home/test, but does not allow copy and move

**Comment by glitsj16** [comment]
> When using --private=/home/tests mode I want to process that only the sandbox has permission to access the /home/test, but does not allow copy and copy

Can you rephrase what you mean by `not allow copy and copy` please? Or give a more descriptive example...

**Comment by linqingping** [comment]
> > 使用--private=/home/tests模式时我想处理只有沙箱有权限访问/home/test，但不允许复制复制
> 
> 你能改写你的意思`not allow copy and copy`吗？或者举一个更具描述性的例子......

Thanks for the reply, I hope that my /home/test directory is only allowed to be used by the sandbox, and no other applications are allowed to open and access it

**Comment by rusty-snake** [comment]
I don't really get want you want to say. Anyway some notes to better understand.

1. (file) access permissions and encryption are two independent things. The one is enforced by an higher privileged actor (i.e. the Kernel) and the other by Mathematics.
2. Firejail has no encryption support at all.
3. The thread model of firejail (tries to) protect the OS from the code running inside the sandbox and not the other way around.
4. To give a sandboxed program access to an (non-tmpfs based) filesystem tree it have to be accessible by the user. Everything else would be an privileged escalation vulnerability.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you have more questions.
