### ISSUE TITLE
howto disable network share

### ISSUE THREAD

**Issue by frank-github** [netblue30/firejail#532]
maybe newbie question 
I want to hide a network share to an application, who is using internet, ex. firefox
how can I reach this?
tried to blacklist mountpoint, but this seems not to work. Or I do something wrong :-(
any hints and tips are welcome

**Comment by netblue30** [comment]
Network filesystems are not supported in this moment, Also not supported are encrypted filesystems, FUSE-based filesystems and probably some other types. I'll implement them at some point.
