### ISSUE TITLE
Can't get Firejail to work with Librewolf

### ISSUE THREAD

**Issue by S0yf00d-exe** [netblue30/firejail#5326]
## [Firejail not working with Librewolf]

So I installed Librewolf prior to installing Firejail. 

Librewolf was installed via the Debian Repo:

>https://librewolf.net/installation/debian/

Also I enabled firejail with system by doing `sudo firecfg`. Aswell as editing some of the profiles in `/etc/firejail` like *Firefox* as well as adding firejail at the begining of the execution path in `/etc/share/applications/firefox.desktop` and confirmed worked. Did the same for Libewolf (librewolfs desktop name is defferent explained later)  and wouldn't work so I changed it back to normal.

Librewolf works when fine launching without firejail. However When I do `firejail librewolf` it says something along the lines

>Warning: networking feature is disabled in Firejail configuration file

When looking at librewolf profile I never blacklisted Network acess I just did `blacklist /sys/*` to block directorys from being read just like firefox and firefox works and also blocks access.

Furthermore I looked at `/etc/share/applications` and librewolfs desktop file is named `start-librewolf.desktop` there is no `librewolf.desktop`.

This made me think I needed to make a profile in `/etc/firejail` named `start-librewolf.profile`
 
So thats what I did and pasted the same info/rules from the librewolf.profile into it.

This did not fix firejail in regards to *Librewolf*.

**What is the work around or what am I doing wrong?**

**Comment by glitsj16** [comment]
> Furthermore I looked at /etc/share/applications and librewolfs desktop file is named start-librewolf.desktop there is no librewolf.desktop.
This made me think I needed to make a profile in /etc/firejail named start-librewolf.profile

Firejail uses the name of the executable to pick the correct security profile. So, take a look inside your start-librewolf.desktop and tell us what it refers to on the Exec=... line. I'm assuming 'librewolf' to be the binary, so it would be helpful if you can post output of running the below command:
```
$ firejail --ignore=quiet /usr/bin/librewolf
```

**Comment by S0yf00d-exe** [comment]
@glitsj16 

When looking at `start-librewolf.desktop` the Exec I have:

`Exec=/usr/share/librewolf/librewolf%u`

Between the time I posted and now, I tried creating `start-librewolf.profile` again and copying `librewolf.profile` contents to it. Then deleted (`rm`) the `librewolf.profile` and tried `firejail librewolf`. 

This time I didn't get the network error but *Librewolf*, but gets stuck at selecting a firefox profile even though I never set profiles flag `-p` in the Exec path for librewolf.


Just saw your reply and running `firejail --ignore=quiet /usr/bin/librewolf` does the same thing it brings me to the profile selector screen. I have no Librewolf profiles set.

**Comment by S0yf00d-exe** [comment]
@glitsj16 

I don't have my ethernet plugged in right now (did earlier replying on differnet machine), but tried your command again this is what it says in terminal in background:

Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning:  networking feature is disbaled in Firejail configuration file


** Note: you can use --noprofile to disable default.profile **


parent pid 6730, child pid 67371
Warning:  cannot create a new user namespace, going forward without it...
child process initialized in 138.28 ms
Crash Annotation GraphicsCriticalError: | [0] [GFX1-]: glxtest: VA-API yest failed: failed to intitialize VAAPI connection.  (t=0.576573)  [GFX1-]: glxtest: VA-API yest failed: failed to intitialize VAAPI connection.
JavaScript error: resource://gre/modules/XULStore.jsm, line 68: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 68: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 68: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 68: Error: Can't find profile directory.

**Comment by glitsj16** [comment]
Is /usr/bin/librewolf a symlink to /usr/share/librewolf/librewolf?

```
$ stat /usr/bin/librewolf
```

> Reading profile /etc/firejail/default.profile
[...]

Oh it is using the wrong profile (default.profile). Try adding the librewolf one explicitly:
```
$ firejail --ignore=quiet --profile=librewolf /usr/share/librewolf/librewolf

```

**Comment by rusty-snake** [comment]
First, use the bug report template if you have a bug. Second, mention your firejail version.

We have fixes for librewolf.profile which might no be in Debian stable, so can you try to install firejail from backports.

**Comment by rusty-snake** [comment]
Also see #4899.

**Comment by S0yf00d-exe** [comment]
@rusty-snake

So I uninstalled and then reinstalled firejail. Still wouldn't work so I looked for the latest [`librewolf.profile`](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/librewolf.profile) and compared the profile obviously not the same. I have *Backports* repo enabled in apt sources not sure why it didn't pull/install from there? 

Anyway I just copied the [`.profile`](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/librewolf.profile) into mine with nano. Now Firejail is working with librewolf when launcing via commandline and by editing the `exec=` path in of the `librewolf.desktop` in applications.

**Comment by rusty-snake** [comment]
> I have Backports repo enabled in apt sources not sure why it didn't pull/install from there?

Because that's not how backports work. You need to explicitly tell it to use backports.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
