### ISSUE TITLE
bluez-alsa

### ISSUE THREAD

**Issue by imxade** [netblue30/firejail#5329]
### Discussed in https://github.com/netblue30/firejail/discussions/5328

<div type='discussions-op-text'>

<sup>Originally posted by **imxade** August 20, 2022</sup>
On **NixOS**,
im using **bluez-alsa** for bluetooth headset

```
firejail --noprofile firefox
```
plays audio through default Bluetooth device

but 
```
firejail firefox
```
doesn't play audio when default device is a Bluetooth one.

i've whitelisted $HOME & $XDG_RUNTIME_DIR but no luck.

In case of **pulseaudio, firejailed firefox** plays fine through bluetooth.

how can i get it working with bluez-alsa ?

**Comment by imxade** [comment]
> Try using PulseAudio or PipeWire instead of raw ALSA? PulseAudio has working firejail integration.

check the 2nd last line

**Comment by jaens** [comment]
If it works with PulseAudio, what's the point of using ALSA?

**Comment by imxade** [comment]
> granting sandboxed programs access to raw audio devices does not seem very security-minded either

Got it, but still is there any way to get it working ?

**Comment by kmk3** [comment]
@imxade commented [on Aug 21](https://github.com/netblue30/firejail/issues/5329#issue-1345409752):

> On **NixOS**, im using **bluez-alsa** for bluetooth headset
> 
> ```
> firejail --noprofile firefox
> ```
> 
> plays audio through default Bluetooth device
> 
> but
> 
> ```
> firejail firefox
> ```
> 
> doesn't play audio when default device is a Bluetooth one.
> 
> i've whitelisted $HOME & $XDG_RUNTIME_DIR but no luck.
> 
> In case of **pulseaudio, firejailed firefox** plays fine through bluetooth.
> 
> how can i get it working with bluez-alsa ?

What is the path to the headset in /dev?

`nou2f` might be blocking it if it shows up in a path matching `/dev/hidraw*`
and Firefox tries to access it through that.

Does adding `browser-disable-u2f no` to /etc/firejail/firejail.config fix it?

If not, try commenting out lines in firefox.profile and firefox-common.profile
to find out what command is blocking it.

**Comment by imxade** [comment]
@kmk3 
on commenting ```#dbus-system none``` bluetooth device is playing fine.

Is there any better way to achieve the same with touching profiles ?
