### ISSUE TITLE
Blacklisting symlink also blacklists the linked directory

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#5346]
From https://github.com/netblue30/firejail/pull/5344 (@birdie-github)

> For example, if ~/foo is blacklisted and it points to /bar, then /bar will also be blacklisted.

**Comment by rusty-snake** [comment]
We should keep the current behaviour IMHO. A symlink says that the directory/file is found somewhere else, so it's still the same directory/file (from a logical view). And programs usually just follow symlinks and write/read their config from the symlinked path.

**Comment by netblue30** [comment]
Yes, not a bug.

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)

**Comment by kmk3** [comment]
Relates to #5338.
