### ISSUE TITLE
firefox freez on ubuntu 16.04

### ISSUE THREAD

**Issue by deb75** [netblue30/firejail#535]
Hello,

On ubuntu 16.04, firefox suddenly freezes a short time after being launched with firejail, without any particular error message. It happens with the default firejail package and also with the latest one.

I saw an older thread with same issue, but advocated solutions did not work for me, firefox is not enforced by apparmor to my knowledge (aa-status)

Any suggestions ?

Regards and thanks for this useful application.

**Comment by netblue30** [comment]
Start it in a terminal (firejail firefox), maybe Firefox prints out some error messages.

**Comment by deb75** [comment]
Hello,

When running "firejail firefox" on command line (which is actually the only way I do it), I do not get meaningfull error messages. The only noticeable thing is that the freeze occurs very shortly after the message : 

1464254502696 addons.productaddons WARN Failed downloading XML, status: 0, reason: timeout

... though I have a working internet connexion.

Googling this message did not help, it seems harmless and it also occurs when I run firefox alone, but no freeze.

Before this message, firejail complains that it did not find the Download directory,  which would be harmless.

What can I do next ?

**Comment by netblue30** [comment]
Create a Downloads directory:
`````
$ mkdir ~/Downloads
`````
I think one of your addons is locking it up.

**Comment by deb75** [comment]
Hi,

This did not help. I tried with another web browser as  conkeror (powered by xulrunner), no freeze at all.

I do not know if someone else is able to reproduce this problem, could it be related to apparmor as suggested in another thread, in this case do you knwo how to disable it ?

Regards

**Comment by requiredregistration** [comment]
@deb75 try it outside of firejail also

**Comment by deb75** [comment]
Hello,

Tried everything, inside (freeze) and outside (neither freeze nor crashes) ... with latest firejail.
This only occur with firefox, no problem so far with icecat and conkeror

In the absence of meaningful error message, I have to give up, I wonder if someone with ubuntu 16.04 experiences similar issues, it could be due to some custom configurations ...

Many thanks for your help.
