### ISSUE TITLE
Displaying process info in Conky

### ISSUE THREAD

**Issue by vendion** [netblue30/firejail#5373]
I'm wanting to have my conky display process information (top N processes consuming CPU/RAM) but with the default conky.profile shipped with firejail 0.9.70 the processes visible to Conky is limited. Back in 2018 the following was posted by a contributor in a similar thread:

> `who` and `top` providing only limited information inside the sandbox is by design and currently not configurable. EDIT: It is possible though to allow `who` to read /var/log/wtmp with the `--writable-var-log` option, if that's considered an acceptable alternative.

_Originally posted by @smitsohu in https://github.com/netblue30/firejail/issues/1866#issuecomment-379757383_

Is the same still true where this is currently not configurable?

**Comment by rusty-snake** [comment]
Nothing changed.

**Comment by vendion** [comment]
Okay, thanks for that guess i'll just have conky run outside of firejail.

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)
