### ISSUE TITLE
Firefox ESR 102: needs rule for DBus names `org.mozilla.firefox_esr.*`

### ISSUE THREAD

**Issue by owenh000** [netblue30/firejail#5379]
### Description

Firefox ESR 102 needs access to session DBus names matching `org.mozilla.firefox_esr.*` to open a new tab/window when Firefox is already running.

I fixed this locally with this rule:

```sh
$ echo "dbus-user.own org.mozilla.firefox_esr.*" >> ~/.config/firejail/firefox.local
```

It looks to me like this rule should be added to `firefox.profile`.

### Steps to Reproduce

```sh
$ firejail firefox
(Firefox opens)
$ firejail firefox example.com
Fails with error dialog:
```

>Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.

### Expected behavior

```sh
$ firejail firefox
(Firefox opens)
$ firejail firefox example.com
(Firefox opens website)
```

### Environment

- Debian GNU/Linux 11 bullseye
- Debian `firefox-esr` package, `v102.3.0esr-1~deb11u1` (did not occur with `v91.13.0esr-1~deb11u1`)
- firejail version 0.9.70

**Comment by owenh000** [comment]
Please see pull request #5380, which adds the rule to `firefox.profile`. Thanks!

**Comment by netblue30** [comment]
Merged in https://github.com/netblue30/firejail/pull/5360, thanks!

**Comment by owenh000** [comment]
@netblue30, okay, and thank you!
