### ISSUE TITLE
Evince doesn't remember settings

### ISSUE THREAD

**Issue by Gertalitec** [netblue30/firejail#5392]
Hi,

When using Evince with firejail, I cannot store viewing settings, and Evince always starts in a very small window with zoom level set at 15,7%. Even if I check "remember present settings" in Evince, the window size and zoom level are reset every time. 

This is very inconvenient, what can I do to change this behavior ?

```
Arch linux 5.19.12-arch1-1
firejail version 0.9.70
```
`firejail --noprofile evince pdf` works as expected

Thanks very much

**Comment by rusty-snake** [comment]
First start with providing essential information. The easiest way is to follow the bug template.

**Comment by rusty-snake** [comment]
Likely you need to add `dbus-user.talk ca.desrt.dconf`. IIRC we decided against st it because it allows escapes and is only used to remember view settings, but maybe this was also in `nodbus` days.

**Comment by Gertalitec** [comment]
Thanks, i added info to the first post, sorry for that.

It's better with `dbus-user.talk ca.desrt.dconf`, zoom level is somewhat preserved, but Evince is still started in a small window. Launching with `--noprofile` launches full screen

**Comment by rusty-snake** [comment]
To narrow it down, does `firejail --ignore=dbus-user /usr/bin/evince path/to/document` work as expected?

What does `gsettings list-recursively org.gnome.Evince` list?

> full screen

Do you mean full screen or maximized window?

**Comment by Gertalitec** [comment]
```
$  gsettings list-recursively org.gnome.Evince
org.gnome.Evince allow-links-change-zoom true
org.gnome.Evince auto-reload true
org.gnome.Evince document-directory @ms nothing
org.gnome.Evince override-restrictions true
org.gnome.Evince page-cache-size uint32 50
org.gnome.Evince pictures-directory @ms nothing
org.gnome.Evince show-caret-navigation-message true
org.gnome.Evince.Default continuous true
org.gnome.Evince.Default dual-page false
org.gnome.Evince.Default dual-page-odd-left false
org.gnome.Evince.Default enable-spellchecking true
org.gnome.Evince.Default fullscreen false
org.gnome.Evince.Default inverted-colors false
org.gnome.Evince.Default show-sidebar false
org.gnome.Evince.Default show-toolbar true
org.gnome.Evince.Default sidebar-page 'thumbnails'
org.gnome.Evince.Default sidebar-size 132
org.gnome.Evince.Default sizing-mode 'free'
org.gnome.Evince.Default window-ratio (1.4536779601576097, 0.94774660350505069)
org.gnome.Evince.Default zoom 1.1798094559347589
```

`$ firejail --ignore=dbus-user /usr/bin/evince path/to/document` starts minimized as well (yes I meant maximized, not full-screen)

**Comment by rusty-snake** [comment]
Looks like you have to comment evince.profile line by line to find the problematic one.

**Comment by Gertalitec** [comment]
Alright, I managed to get it working by uncommenting the following lines : 

```
noblacklist ${HOME}/.local/share/gvfs-metadata
dbus-user.talk org.gtk.vfs.Daemon
```

**Comment by Gertalitec** [comment]
and the additional `dbus-user.talk org.gtk.vfs.Metadata` actually so that the page can be opened maximized.

This settings seems to be set per pdf though and not globally, but that's probably not related to firejail

**Comment by Gertalitec** [comment]
So, regarding `$ firejail --ignore=dbus-user /usr/bin/evince path/to/document` that you suggested above, the additional `noblacklist ${HOME}/.local/share/gvfs-metadata` was needed...

Thanks for your help ! Should I close this ?
