### ISSUE TITLE
add unikernel support to restrict attack surface

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#5403]
https://www.phoronix.com/news/Linux-Unikernel-RFC

https://github.com/unikernelLinux/ukl

Maybe in future we can start protect userspace apps inside unikernel.

More optimized and secure.

Thanks and

Best regards

**Comment by kmk3** [comment]
Hello, this seems more like a discussion topic than an actionable issue, so I'm
converting it into a discussion.
