### ISSUE TITLE
Allow firejail to use an anonymous bridge

### ISSUE THREAD

**Issue by c-MM** [netblue30/firejail#541]
I have an anonymous bridge on mys system which is in an different vlan used for testing deployments. This bridge has no IP address on my host.

`
root@ovid:~# firejail --noprofile --net=br1 --ip=10.0.1.233/23 --defaultgw=10.0.1.254 bash
Error: interface br1 is not configured`

`root@ovid:~# ip a s dev br1
5: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ac:22:0b:4e:59:c4 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ae22:bff:fe4e:59c4/64 scope link 
       valid_lft forever preferred_lft forever`

I don't want my host to have connectivity to the subnet, that's why I don't assign an IP address to the bridge. As soon as I assign an address to the bridge, it works.

Is there a reason why firejail requires an address on a bridge?

Thanks in advance and thanks for firejail!

**Comment by netblue30** [comment]
All done, you can try the version in git.

**Comment by c-MM** [comment]
Great, thanks a lot. I'll test it.
