### ISSUE TITLE
Firejail AppImage or Portable version of Firejail?

### ISSUE THREAD

**Issue by AmyMoriyama** [netblue30/firejail#5411]
The request:
To be able to run firejail from any folder/directory (portable).

Suggested method:
Either an AppImage of firejail or a static binary.

Why?
It would be greatly useful in situations relating to portable applications. One example, let's say you have a USB stick with some AppImage apps on it, but you want to maintain control over those apps when ran. Having a copy of firejail on the USB stick along with the other portable apps could do this.

**Comment by kmk3** [comment]
Duplicate of #2849
