### ISSUE TITLE
Start signing commits with GPG?

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#543]
G'day @netblue30 ! :) Seeing as how you sign the releases on SourceForge with your gpg key, could you do the same for your commits here on GitHub? I build from the code here quite frequently as I want to make sure my commits and pull requests mesh well, and gpg-signed commits would help me trust the code I'm installing on my computer. I'm sure this would help several others as well.

It's not difficult to do, either. GitHub has put out a really good guide: https://github.com/blog/2144-gpg-signature-verification. After uploading your public key here, all you have to do is sign your commits with the -S flag: `gpg commit -S -m "some random message"`

Thanks!
Fred

**Comment by reinerh** [comment]
Just out of interest, do you verify them on your local checkout after you pulled or do you trust github's UI?

**Comment by Fred-Barclay** [comment]
I would definitely verify them locally. 
It is nice, though, that github's UI does show at a glance which commits were signed. But it's not worthy of trust, IMHO.

**Comment by requiredregistration** [comment]
you should switch to a rsa4096 primary public key before that.

**Comment by chiraag-nataraj** [comment]
Adding on to what @Fred-Barclay said, you can also do `git config commit.gpgSign true` so that you don't have to remember to put `-S` as an argument.

**Comment by chiraag-nataraj** [comment]
Seems like whoever wants to do this is already signing their commits, and it's been documented here (and elsewhere) as to how to do so if one wants to start doing it. I don't think there's any point in keeping this issue open at this point.
