### ISSUE TITLE
--enable-apparmor in arch Linux not working anymore 

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#5433]
I installed already sudo pacman -Su apparmor-git

In my last arch installs it was enough to get libapparmor.so in libs directory.

Now, firejail  cant compile with apparmor support anymore.

Which pkg should i install additionaly via.pacman? 

Thanks and

Best regards

**Comment by glitsj16** [comment]
> sudo pacman -Su apparmor-git

That would work if there was an `apparmor-git` package in the arch linux repo's, which isn't the case.
Try installing `apparmor` instead.

**Comment by osevan** [comment]
Can anyone reproduce that?

**Comment by osevan** [comment]
> > sudo pacman -Su apparmor-git
> 
> That would work if there was an `apparmor-git` package in the arch linux repo's, which isn't the case. Try installing `apparmor` instead.

I installed already both. . Next time i will show you logs

**Comment by curiosityseeker** [comment]
> > sudo pacman -Su apparmor-git
> 
> That would work if there was an `apparmor-git` package in the arch linux repo's, which isn't the case. Try installing `apparmor` instead.

He probably has the unofficial Chaotic AUR repo enabled.

**Comment by glitsj16** [comment]
Regardless of how/what apparmor package you installed, you've got to [enable AppArmor](https://wiki.archlinux.org/title/Apparmor) yourself, firejail cannot do that. To use the `--enable-apparmor` option that's the only package one needs on Arch Linux (& derivatives). So at the moment I don't know what's going on exactly. Awaiting logs we could also look into this on our Libera IRC #firejail channel.
