### ISSUE TITLE
FreeTube: enable KDE plasma multimedia control

### ISSUE THREAD

**Issue by toby63** [netblue30/firejail#5437]
### Is your feature request related to a problem? Please describe.

KDE Plasma has a multimedia control applet, that I would like to use with FreeTube.
Without using firejail this works.

With Firefox and other applications it works also with firejail.
I think it has something to do with the dbus options.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by rusty-snake** [comment]
Can you try

```
ignore dbus-user none
dbus-user filter
dbus-user.own org.mpris.MediaPlayer2.chromium.*
dbus-user.own org.mpris.MediaPlayer2.freetube
```

**Comment by toby63** [comment]
> Can you try
> 
> ```
> ignore dbus-user none
> dbus-user filter
> dbus-user.own org.mpris.MediaPlayer2.chromium.*
> dbus-user.own org.mpris.MediaPlayer2.freetube
> ```

I added it below the rest of the config file; log now shows:
> Error: Cannot relax dbus-user policy, it is already set to block
Ignoring "dbus-user.own org.mpris.MediaPlayer2.chromium.*" and 1 other dbus-user filter rule.

**Comment by rusty-snake** [comment]
You should never edit the profiles in /etc.

Always use .locals.

https://github.com/netblue30/firejail/wiki/Creating-overrides
https://github.com/netblue30/firejail/wiki/Creating-Profiles
https://firejail.wordpress.com/features-3/man-firejail-profile/

**Comment by toby63** [comment]
I copied the profile to ~/.config/firejail, but will try locals now instead.

**Comment by toby63** [comment]
Now it works. Thx.

**Comment by rusty-snake** [comment]
Does it still work if you remove the `dbus-user.own org.mpris.MediaPlayer2.chromium.*` line?

**Comment by toby63** [comment]
> Does it still work if you remove the `dbus-user.own org.mpris.MediaPlayer2.chromium.*` line?

No doesn't work.
