### ISSUE TITLE
Firejail - Firefox 'Email link' Stopped Working

### ISSUE THREAD

**Issue by Shimergo** [netblue30/firejail#5438]
Asking Firefox to launch a new Thunderbird email to send a link suddenly stopped working a couple of weeks ago. No Thunderbird message window is opened, and after a few seconds I just get a wee window titled 'Profile Missing' with the warning text 'Your Thunderbird profile cannot be loaded. It may be missing or inaccessible'. It works fine if FF and TB are NOT Firejailed.

When I originally installed Firejail, I followed advice to get this working by putting these lines in ~/.config/firejail/firefox.local
noblacklist ${HOME}/.thunderbird
whitelist ${HOME}/.thunderbird/profiles.ini
read-only ${HOME}/.thunderbird/profiles.ini

I've tried updating Firejail from 0.9.64.4 to 0.9.70, but still the same issue.
Maybe something changed when Thunderbird updated, though I'm not sure when the last update was? Now at version 102.2.2.
And I'm on Linux Mint 20 Ulyana Xfce, and Firefox is 106.0.1
And it's the same symptoms when I click on a 'mail to' link in a webpage.

Any thoughts how to fix this? My IT skills are poor, so would appreciate novice-style instructions :D

Thanks in advance!

**Comment by rusty-snake** [comment]
Does it work if you start firefox like `firejail --ignore=dbus-user /usr/bin/firefox`?

**Comment by Shimergo** [comment]
Yes, that works!
(Am guessing that gives you clues rather than being a long-term solution?)

**Comment by Shimergo** [comment]
If it helps:
(Sorry, I tried embedding it all in lt,code,gt ... lt,/code,gt" but it just loses the end-of-line markers)

$ firejail --ignore=dbus-user /usr/bin/firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /home/rowellfamily/.config/firejail/firefox.local
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-proc.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Ignoring "dbus-user.own org.mozilla.Firefox.*" and 2 other dbus-user filter rules.
Parent pid 9371, child pid 9372
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Warning: cleaning all supplementary groups
Child process initialized in 232.65 ms
[2022-10-27T20:12:02Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update
libEGL warning: DRI2: failed to authenticate
ATTENTION: default value of option mesa_glthread overridden by environment.
libEGL warning: DRI2: failed to authenticate
ATTENTION: default value of option mesa_glthread overridden by environment.
[2022-10-27T20:58:07Z ERROR viaduct::backend::ffi] Missing HTTP status
[2022-10-27T20:58:07Z ERROR viaduct::backend::ffi] Missing HTTP status
[2022-10-27T20:58:07Z ERROR viaduct::backend::ffi] Missing HTTP status

Parent is shutting down, bye...
[1]+  Done                    gedit ~/.config/firejail/firefox.local
$

**Comment by rusty-snake** [comment]
> Am guessing that gives you clues rather than being a long-term solution?

Yes.

Can you try `firejail '--dbus-user.talk=org.mozilla.thunderbird.*' /usr/bin/firefox`.

If it does not work, try to find the name thunderbird uses. Start it and run `busctl --user --acquired | grep -i thunderbird`.

>  (Sorry, I tried embedding it all in lt,code,gt ... lt,/code,gt" but it just loses the end-of-line markers)

That's how html works. If you use html you need to use pre-tags around the code-tags. However on GH you usually use markdown - unless you want to use some speical styling - and there you use three backticks like

````markdown

```
my
multiline
code
```

````

**Comment by Shimergo** [comment]
Yep, that firejail line launches Firefox with working 'Email link' functionality
And ```busctl``` of course fills in your wildcard
And now I can find more *markdown* ......

**Comment by Shimergo** [comment]
Hi,
So is there a line I can put in ~/.config/firejail/firefox.local to fix this?
Or is your suggestion to use ```firejail '--dbus-user.talk=org.mozilla.thunderbird.*' /usr/bin/firefox``` in my session startup code in place of ```firejail firefox %u```?
Thanks!

**Comment by rusty-snake** [comment]
`dbus-user.talk org.mozilla.thunderbird.*`

**Comment by rusty-snake** [comment]
You can use (almost) every commandline option in profiles, just leave the `--` and replace `=` with ` `.

**Comment by Shimergo** [comment]
Perfect!

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)
