### ISSUE TITLE
make it clear that `--x11` does not block child processes from communicating with parent X server

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#544]
The current implementation of `firejail --x11` does not forbid sandboxed processes from communicating with the parent (main) X.
The documentation, however, could be read as if --x11 does some kind of protection. A suggest to make a **warning** on this option that it's only a convenience separation, not a security one.

Example on how to break out of `firejail --x11`:

* on host system start `firejail --x11=xephyr --private --noprofile xterm`
* observe Xephyr window is being opened with an xterm window inside
* type `DISPLAY=:0 xterm`  in this child xterm
* observe the last `xterm` being opened inside your main X system, with access to the cursor, keyboard etc.

**Comment by nick75e** [comment]
As indicated [here](https://firejail.wordpress.com/documentation-2/x11-guide/), you have to create a  network namespace, e.g.: `firejail --x11=xephyr --net=eth0 --private --noprofile xterm`

```
/tmp/.X11-unix/X0 is disabled using a temporary filesystem mounted on /tmp/.X11-unix
directory. The only way to disable the abstract socket @/tmp/.X11-unix/X0 is by using a
network namespace. If for any reasons you cannot use a network namespace, the ab-
stract socket will still be visible inside the sandbox. Hackers can attach keylogger and
screenshot programs to this socket.
```

**Comment by vn971** [comment]
@nick75e  Oops, sorry, I guess I've been a poor documentation reader.
The ticket should be closed, or maybe better deleted.
