### ISSUE TITLE
chafa profile seems to need 'shell none' for NixOS and/or Fish shell

### ISSUE THREAD

**Issue by revuwa** [netblue30/firejail#5445]
### Description

Thanks for the [chafa profile](https://github.com/netblue30/firejail/pull/5355).
Sadly I experienced `Cannot start application: No such file or directory` under NixOS (22.11pre) & Fish shell (v3.5.1) with that profile.

### Steps to Reproduce

Just use chafa with the new firejail profile (above) under NixOS with Fish shell.

### Expected behavior

If you would consider to add: `shell none` into the profile, it would work under NixOS and/or Fish, too.
Log snippet (after adding `shell none`):
```
Child process initialized in 166.32 ms
Installing /run/firejail/mnt/seccomp/seccomp seccomp filter
Installing /run/firejail/mnt/seccomp/seccomp.block_secondary seccomp filter
monitoring pid 7

***
*** The picture is shown here \o/
***

Sandbox monitor: waitpid 7 retval 7 status 0

Parent is shutting down, bye...
```
### Actual behavior

Log snippet:
```
Child process initialized in 151.36 ms
Installing /run/firejail/mnt/seccomp/seccomp seccomp filter
Installing /run/firejail/mnt/seccomp/seccomp.block_secondary seccomp filter
Cannot start application: No such file or directory
monitoring pid 7

Sandbox monitor: waitpid 7 retval 7 status 256

Parent is shutting down, bye...
```

### Behavior without a profile

Log snippet:
```
Child process initialized in 71.74 ms
Installing /run/firejail/mnt/seccomp/seccomp seccomp filter
Installing /run/firejail/mnt/seccomp/seccomp.32 seccomp filter
Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter
monitoring pid 6

fish: Unknown command: --
fish: 
--
^
Sandbox monitor: waitpid 6 retval 6 status 32512

Parent is shutting down, bye...

```
### Additional context

To be honest, I've no idea if the showstopper is NixOS or Fish; I just know `shell none` did the trick.

### Environment

- Linux distribution and version: NixOS (22.11pre)
- Firejail version: 0.9.70

### Checklist

- [X] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [X] I can reproduce the issue without custom modifications (e.g. globals.local).
- [X] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [X] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [X] I have performed a short search for similar issues (to avoid opening a duplicate).
- [X] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [X] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
Closing non-standard file descriptors
Starting application
LD_PRELOAD=(null)
Running '/nix/store/jqwb1hgky1s15hp72zchacwzz70277n9-chafa-1.12.3/bin/chafa' 'test.png'  command through /run/current-system/sw/bin/fish
execvp argument 0: /run/current-system/sw/bin/fish
execvp argument 1: -c
execvp argument 2: --
execvp argument 3: '/nix/store/jqwb1hgky1s15hp72zchacwzz70277n9-chafa-1.12.3/bin/chafa' 'test.png' 
Child process initialized in 147.21 ms
Installing /run/firejail/mnt/seccomp/seccomp seccomp filter
Installing /run/firejail/mnt/seccomp/seccomp.block_secondary seccomp filter
Cannot start application: No such file or directory
monitoring pid 7

Sandbox monitor: waitpid 7 retval 7 status 256

Parent is shutting down, bye...
```

</p>
</details>

**Comment by rusty-snake** [comment]
We had this error in the past already (ai could not find the issue). There are also more issue with fish.

Anyway, `shell none` is no the unconditional default, so unless you can reproduce this with firejail from git this is already fixed.

**Comment by rusty-snake** [comment]
Btw: using profiles from git with a stable firejail (I.e. firejail and profile release differ) isn't supported.

**Comment by revuwa** [comment]
> We had this error in the past already (ai could not find the issue). There are also more issue with fish.

Thanks for the info, that it has something to do with fish (not NixOS). I couln't find anything, so I made this issue.

> Anyway, `shell none` is no the unconditional default, so unless you can reproduce this with firejail from git this is already fixed.

Thanks a lot!

> Btw: using profiles from git with a stable firejail (I.e. firejail and profile release differ) isn't supported.

Oh boy, I have never thought about that before; good point.

**Comment by revuwa** [comment]
> > shell none is the new default.
> 
> Yes. It solved an entire class of bugs.

Well, thanks again. 
So I use `--shell=none` as my new default, until a new release will arrive.

**Comment by kmk3** [comment]
(Marking `notabug` since this was already fixed)

(Re-closing as "not planned" since nothing was changed in firejail)

**Comment by kmk3** [comment]
Relates to #5196.
