### ISSUE TITLE
--quiet flag not working?

### ISSUE THREAD

**Issue by aanderse** [netblue30/firejail#545]
I was under the impression the --quiet flag should suppress *all* output.

aaron@moya ~ $ uname -a
Linux moya 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
aaron@moya ~ $ firejail --version
firejail version 0.9.38
aaron@moya ~ $ firejail --profile=/etc/firejail/generic.profile --quiet
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc

This is causing me issues when trying to rsync into the box.

Thank you,
Aaron

**Comment by reinerh** [comment]
Works when you pass in --quiet first.

**Comment by aanderse** [comment]
Thank you.

**Comment by netblue30** [comment]
I'll have to fix is. or at least document it. Thanks.

**Comment by netblue30** [comment]
Fixed!

**Comment by rieje** [comment]
@netblue30 `quiet` in e.g. mediainfo.local does not supress `Reading profile /etc/firejail/mediainfo.profile`, whereas `--quiet` does.

**Comment by rusty-snake** [comment]
@rieje If you believe you found a bug, please open a new issues instead of commenting on a 6 year old issue. Furthermore you should add information like your firejail version and the mediainfo.profile you use (because mediainfo.profile does not contain quiet).

**Comment by rusty-snake** [comment]
FTR: #4900
