### ISSUE TITLE
Using both --net=none and --overlay-tmpfs => no access to X11

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#546]
firejail 0.9.38, Lubuntu 14.04

This command doesn't work:
```
$ firejail --net=none --overlay-tmpfs leafpad
Warning: default profile disabled by --overlay option
Parent pid 9615, child pid 9616
OverlayFS configured in /run/firejail/mnt directory
Warning: failed to unmount /sys

Child process initialized
leafpad: Cannot open display: 

parent is shutting down, bye...
```
Removing either `--net=none` or `--overlay-tmpfs` and it works:
```
$ firejail --overlay-tmpfs leafpad
Warning: default profile disabled by --overlay option
Parent pid 9728, child pid 9729
OverlayFS configured in /run/firejail/mnt directory
Warning: failed to unmount /sys

Child process initialized

```

```
$ firejail --net=none leafpad
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 9780, child pid 9781

Child process initialized

```

Is this a bug?  If not, how to use firejail to disable unnecessary Internet access and use `--overlay-tmpfs`, while keeping access to X11?

**Comment by chiraag-nataraj** [comment]
I think it has something to do with X11 having two sockets - one that listens on the network interface and one that listens through a unix socket in /tmp. `--net=none` creates a new network namespace and so disables access to the network socket. `--overlay-tmpfs` (or equivalently `--private-tmp`) disables access to the unix socket in /tmp. Thus the client cannot connect to the X11 server.

As for how to fix this, you could use `--x11` to spawn a new X server.

**Comment by chiraag-nataraj** [comment]
It seems that the problem is that the tmpfs is mounted *after* creating the new X server, which means the child can't find the server. @netblue30, could you instantiate the tmpfs before running xpra? That way, I think this would be solved (if you use `--x11` along with `--private-tmp` and `--net=none`).

**Comment by netblue30** [comment]
Bug! It happens also on Ubuntu 16.04

**Comment by laniakea64** [comment]
Thanks for the insights.  Is there a way to work around this without using X11 sandboxing?  For example, does using `--protocol=unix` (which does work in place of `--net=none`) completely disable network access?

**Comment by chiraag-nataraj** [comment]
I think so? It seems to work through a cursory test:
`firejail --noprofile --protocol=unix`
`ping google.com` => Operation not supported
`wget google.com` => Temporary failure in name resolution

**Comment by netblue30** [comment]
I put a fix in master branch here on github, now it should work fine.

--protocol=unix is similar to --net=none, unless you run into some DNS problems.

**Comment by laniakea64** [comment]
Confirmed fixed by https://github.com/netblue30/firejail/commit/a81568d4f03a12817ab2b0ad6d52159eb5a9eb10, thanks! :smiley:
