### ISSUE TITLE
The Ubuntu installation section in README.md is outdated

### ISSUE THREAD

**Issue by Frostbyte4664** [netblue30/firejail#5469]
Adding the PPA with `sudo add-apt-repository ppa:deki/firejail` stores the key in the legacy trusted.gpg keyring, which has been depreciated in favor of separating individual keys.

![image](https://user-images.githubusercontent.com/72130297/201266192-f90ca8d0-8f66-437e-a09e-81dfed44de2e.png)

I wrote a small bash script to download the key and add the repository properly.
Something like this should be used in place of of `add-apt-repository`.

~~~
# Get codename of distro for list entry
codename=$( awk -F= '/UBUNTU_CODENAME/{print $2}' /etc/os-release )

# Add gpg key
wget -qO- "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60537cdcf684460c" |\
gpg --dearmor |\
sudo tee /usr/share/keyrings/firejail-keyring.gpg > /dev/null

# Add repository
echo -e "deb [ signed-by=/usr/share/keyrings/firejail-keyring.gpg ] https://ppa.launchpadcontent.net/deki/firejail/ubuntu $codename main" |\
sudo tee /etc/apt/sources.list.d/firejail.list > /dev/null
~~~

**Comment by reinerh** [comment]
Thanks for the heads-up. Interestingly the `add-apt-repository` method is still the one recommended by [launchpad](https://launchpad.net/~deki/+archive/ubuntu/firejail)-

**Comment by Frostbyte4664** [comment]
I'm dumb. This problem is not present in the latest release of Ubuntu, but it is present in the latest release of Linux Mint.

**Comment by reinerh** [comment]
I'll close the issue then. It sounds like `add-apt-repository` is still the recommended way. I assume that it will fix itself once Mint updates their tools.

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)
