### ISSUE TITLE
Ubuntu 16.04 -- No sound

### ISSUE THREAD

**Issue by Anderath** [netblue30/firejail#547]
Whenever I attempt to use a program in firejail, no output/input devices are available after. I'm not quite sure what I could do to provide proof of this but I will spin up a test VM of a fresh install and report back whether I get the same result or not.

My feeling is that this is somehow related to #410 in that I get the same error messages and symptoms, then directly after I cannot use my regular applications(Clementine, VLC, whatever) with sound because my entire sound hardware appears to have disappeared.

**Comment by Fred-Barclay** [comment]
I wonder if this might be related to #430 or #523, which both deal with pulseaudio problems.

Could you try following https://firejail.wordpress.com/support/known-problems/#pulseaudio, rebooting, and seeing if that helps?

**Comment by netblue30** [comment]
Try the workaround from  https://firejail.wordpress.com/support/known-problems/#pulseaudio
