### ISSUE TITLE
Permission denied with Virtualbox sharedFolders

### ISSUE THREAD

**Issue by S1sirocks** [netblue30/firejail#5472]
### Description
Working in Ubuntu inside a VirtualBox machine where I have multiple shared folders shared from the host machine with the guest machine. Although I have whitelisted and noblacklisted several of those folders I get permission denied when trying to access them from programs such as Clementine or Digikam.

### Log

E.g. having:

noblacklist ${HOME}/sharedFolders/sharedFolder
whitelist ${HOME}/sharedFolders/sharedFolder

I get:

```
Mounting noexec /home/sam/sharedFolders/sharedFolder
3663 3658 0:50 / /home/sam/sharedFolders/sharedFolder rw,nosuid,nodev,noexec,relatime master:516 - vboxsf #sharedFolder rw,iocharset=utf8,uid=0,gid=999,dmode=0770,fmode=0770,tag=VBoxAutomounter
mountid=3663 fsname=/ dir=/home/sam/sharedFolders/sharedFolder fstype=vboxsf
...
Debug 599: dir: /home/sam
Debug 553: whitelist ${HOME}/sharedFolders/sharedFolder
Debug 574: expanded: /home/sam/sharedFolders/sharedFolder
Debug 585: new_name: /home/sam/sharedFolders/sharedFolder
Debug 599: dir: /home/sam
...
Whitelisting /home/sam/sharedFolders/sharedFolder
3025 3020 0:50 / /home/sam/sharedFolders/sharedFolder rw,nodev,relatime master:516 - vboxsf #sharedFolder rw,iocharset=utf8,uid=0,gid=999,dmode=0770,fmode=0770,tag=VBoxAutomounter
mountid=3025 fsname=/ dir=/home/sam/sharedFolders/sharedFolder fstype=vboxsf
...
Mounting noexec /home/sam/sharedFolders/sharedFolder
3253 3252 0:50 /digikamDB /home/sam/sharedFolders/sharedFolder/digikamDB rw,nodev,relatime master:516 - vboxsf #sharedFolder rw,iocharset=utf8,uid=0,gid=999,dmode=0770,fmode=0770,tag=VBoxAutomounter
...
inotify_add_watch(/home/sam/sharedFolders/sharedFolder) failed: (Permission denied)

```

#### What changed calling LC_ALL=C firejail --noprofile /path/to/program in a terminal?
Works like a charm!

### Environment

- Linux distribution and version: Ubuntu 22.04
- Firejail version: firejail version 0.9.66
 

### Checklist

The issues is caused by firejail (i.e. running the program by path (e.g. /usr/bin/vlc) "fixes" it). ✔
I can reproduce the issue without custom modifications (e.g. globals.local).⨯ Custom modifications en several profiles, e.g /etc/digikamDB.profile as shown in log.

### Other info:

- What owner and permission does it have inside and outside of the sandbox? Is it a FUSE filesystem? ⇒ Not sure, the problem is with several folders from the host machine mounted by virtualbox in a folder of the guest machine.
- Are they ever blacklisted? ⇒ NO

I guess it has something to do with Virtualbox shared folders but I may be wrong.
Thanks

**Comment by rusty-snake** [comment]
> uid=0,gid=999,dmode=0770,fmode=0770

What owner and permission does it have inside and outside of the sandbox? Is it a FUSE filesystem?

> noblacklist ${HOME}/sharedFolders/sharedFolder

Are they ever blacklisted?

**Comment by rusty-snake** [comment]
You should give more information about your environment and test cases.

> ### Behavior without a profile
>
> _What changed calling `LC_ALL=C firejail --noprofile /path/to/program` in a terminal?_
>
> ### Environment
>
> - Linux distribution and version (e.g. "Ubuntu 20.04" or "Arch Linux")
> - Firejail version (`firejail --version`).
> - If you use a development version of firejail, also the commit from which it was compiled (`git rev-parse HEAD`).
>
> ### Checklist
>
> - [ ] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
> - [ ] I can reproduce the issue without custom modifications (e.g. globals.local).

**Comment by S1sirocks** [comment]
Added the info to my original comment.
