### ISSUE TITLE
gedit failed to start while using ibus and dbproxy  with message "Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by wellcomez** [netblue30/firejail#5474]
### Description
As I know both ibus and firejail  has used ibus.portal to support IME for multi-language.
I make sure  both ibus and firejail version is right.
After  i tried firefox, chrome, input method work well. 
But  while I try  `gedit`,  after  an error appeared Failed to register: **GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown** , gedit will exit.

### Steps to Reproduce

1. no prole 
firejail --name=a --debug  --allusers  --env=GTK_IM_MODULE=ibus --dbus-user=filter --dbus-user.talk=org.freedesktop.portal.IBus --env=IBUS_USE_PORTAL=1 --noprofile gedit 
2. profile
firejail --name=a --debug  --allusers  --env=GTK_IM_MODULE=ibus --dbus-user=filter --dbus-user.talk=org.freedesktop.portal.IBus --env=IBUS_USE_PORTAL=1 - gedit 

### Expected behavior

gedit can be started and ime works well

### Actual behavior

gedit will exit during starup

### Behavior without a profile

`firejail --name=a --debug  --allusers  --env=GTK_IM_MODULE=ibus --dbus-user=filter --dbus-user.talk=org.freedesktop.portal.IBus --env=IBUS_USE_PORTAL=1 --noprofile gedit`

 

### Environment

- Ubuntu 20.04
- Firejail version (`firejail --version`).
0.9.64.5
### Checklist

- [X ] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [ ] I can reproduce the issue without custom modifications (e.g. globals.local).
- [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x ] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log
~~~
Running 'gedit'  command through /usr/bin/zsh
execvp argument 0: /usr/bin/zsh
execvp argument 1: -c
execvp argument 2: 'gedit' 
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.portal.IBus
C3: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.IBus
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
C4: -> org.freedesktop.DBus call org.freedesktop.DBus.RequestName at /org/freedesktop/DBus
Filtering message due to arg0 org.gnome.gedit, policy: 0 (required 3)
*HIDDEN* (ping)
B5: <- (no sender) return from C4
*REWRITTEN*
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
~~~

**Comment by rusty-snake** [comment]
> - [ ] I can reproduce the issue without custom modifications (e.g. globals.local).

The cause of your problem: ^^, your modifications => this isn't an issue, maybe an support request that should be asked in Discussions.

> C4: -> org.freedesktop.DBus call org.freedesktop.DBus.RequestName at /org/freedesktop/DBus
Filtering message due to arg0 org.gnome.gedit, policy: 0 (required 3)
*HIDDEN* (ping)
B5: <- (no sender) return from C4
*REWRITTEN*
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

So gedit fails after it tried to register `org.gnome.gedit`. Guess what you have to allow.

**Comment by wellcomez** [comment]
> org.gnome.gedit

which command argument  should be used to bypass it?
