### ISSUE TITLE
xephyr and keyboard layout

### ISSUE THREAD

**Issue by deb75** [netblue30/firejail#549]
Hello,

I use Xephyr with firejail, it works well except that the keyboard layout appears to be qwerty whereas I need azerty.

This issue is not just firejail related, if I use Xephyr alone, (e.g. Xephyr :3 && DISPLAY=:3 firefox), I get the same problem.

However, if Xephyr seems to have command line options to configure the keyboard, I did not find a way
to pass it through its call from firejail. To my knowledge, firejail only allows to modify the xephyr resolution in /etc/firejail/firejail.config.

Up to now, the workaround I tried is to grab the Xephyr display (say :3) and run "xkbcomp $DISPLAY :3".

It works, but it is a bit annoying as the Xephyr display seems to be randomly chosen from firejail.

So I would suggest : 
- either allow to provide more options for Xephyr from firejail,
- or find one easy way to grab the Xephyr display.

Regards

**Comment by netblue30** [comment]
I'll add support to pass more command line options to Xephyr.

**Comment by joedicastro** [comment]
Oh! that would be nice!

Also it would be nice too to add the `-resizeable` option of Xephyr to be able to resize the window easily and not to be limited to a specific resolution.

**Comment by netblue30** [comment]
Out of curiosity, what options do you need to pass on the command line to Xephyr? Would you use them for all programs, or change them from program to program?

**Comment by netblue30** [comment]
Fixed. Install the version from git and edit /etc/firejail/firejail.config file. Add "xephyr-extra-params your command line options" at the end of the file.
