### ISSUE TITLE
can't access microphone in firefox version 107 (possibly pipewire related)

### ISSUE THREAD

**Issue by jmcclelland** [netblue30/firejail#5500]
### Description

When running Firefox version 107 via firejail, I am unable to grant permission for the browser to use my microphone. I am able to hear sound through my speakers, but the microphone doesn't work.

### Steps to Reproduce

1. Run `LC_ALL=C firejail /usr/bin/firefox`
2. Visit https://meet.jit.si/my-test-meeting
3. Prompt to share mic (see list of built in and external mics)
4. Pick a mic
5. Click the microphone selection triangle (on the mute buttom)
6. Firefox again prompts me to pic a mic
7. In the Jitsi Meet microphone section, all mics get a red exclamation mark
8. No mic works

### Expected behavior

I expect to choose a mic and begin using it via firefox.

### Actual behavior

No mics work and Jitsi meet marks all mics as non-functioning.

### Behavior without a profile

When I run `LC_ALL=C firejail --noprofile firefox` it works as expected.

### Additional context

The breakage happened after an upgrade and reboot. I can't be 100% sure, but my system is now running pipewire and may not have been running pipewire before. Or it might have been an upgrade to firefox 107 that caused the problem.

Additional details: When running chromium via firejail, the microphones work. When running with firefox-esr (102.5) it works.

### Environment

- Debian bookworm
- firefox from experimental: 107.0
- firejail version 0.9.70

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
1 jamie@liberace:firejail$ LC_ALL=C firejail /usr/bin/firefox -no-remote -ProfileManager
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-proc.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Parent pid 560337, child pid 560340
Warning: not remounting /var/lib/docker/overlay2/25c229b7821d08328548155f497025c99793d0d833f27b6fa49d8e3d0147a656/merged
Warning: not remounting /var/lib/docker/overlay2/d1b4e57a40570f93986f4e2bef6a3484d464a66433ef61dc9be7dcf479c25fe6/merged
Warning: not remounting /var/lib/docker/overlay2/ac6674c11b009f7be49aa2d0adb622d6c66abd8db13c77985588f944a5a651a9/merged
Warning: not remounting /var/lib/docker/overlay2/c9cde5354c55e40529cf9d7a1fadd43eba6dc6f5a9fb4bbfd8d46dbf2d6a49f6/merged
Warning: not remounting /var/lib/docker/overlay2/28ba6b6a863a68e08e2d56748bc32186c381cf6607b86154b3ed861e42adb318/merged
Warning: not remounting /var/lib/docker/overlay2/cd1100fc1d7006e367f3b1da5955056a403c806f8bee78a31256784618a7f712/merged
Warning: not remounting /var/lib/docker/overlay2/25c229b7821d08328548155f497025c99793d0d833f27b6fa49d8e3d0147a656/merged
Warning: not remounting /var/lib/docker/overlay2/d1b4e57a40570f93986f4e2bef6a3484d464a66433ef61dc9be7dcf479c25fe6/merged
Warning: not remounting /var/lib/docker/overlay2/ac6674c11b009f7be49aa2d0adb622d6c66abd8db13c77985588f944a5a651a9/merged
Warning: not remounting /var/lib/docker/overlay2/c9cde5354c55e40529cf9d7a1fadd43eba6dc6f5a9fb4bbfd8d46dbf2d6a49f6/merged
Warning: not remounting /var/lib/docker/overlay2/28ba6b6a863a68e08e2d56748bc32186c381cf6607b86154b3ed861e42adb318/merged
Warning: not remounting /var/lib/docker/overlay2/cd1100fc1d7006e367f3b1da5955056a403c806f8bee78a31256784618a7f712/merged
Warning: not remounting /var/lib/docker/overlay2/25c229b7821d08328548155f497025c99793d0d833f27b6fa49d8e3d0147a656/merged
Warning: not remounting /var/lib/docker/overlay2/d1b4e57a40570f93986f4e2bef6a3484d464a66433ef61dc9be7dcf479c25fe6/merged
Warning: not remounting /var/lib/docker/overlay2/ac6674c11b009f7be49aa2d0adb622d6c66abd8db13c77985588f944a5a651a9/merged
Warning: not remounting /var/lib/docker/overlay2/c9cde5354c55e40529cf9d7a1fadd43eba6dc6f5a9fb4bbfd8d46dbf2d6a49f6/merged
Warning: not remounting /var/lib/docker/overlay2/28ba6b6a863a68e08e2d56748bc32186c381cf6607b86154b3ed861e42adb318/merged
Warning: not remounting /var/lib/docker/overlay2/cd1100fc1d7006e367f3b1da5955056a403c806f8bee78a31256784618a7f712/merged
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Warning: cleaning all supplementary groups
Child process initialized in 211.18 ms
Gdk-Message: 15:04:21.395: Unable to load split_h from the cursor theme
^C
Parent received signal 2, shutting down the child process...

Child received signal 2, shutting down the sandbox...

Parent is shutting down, bye...
130 jamie@liberace:firejail$
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>
  

https://gist.github.com/jmcclelland/f19dc5ec33e21af98cfcbdd2dfa70e68

</p>
</details>

---

EDIT by @rusty-snake: Fix markdown

**Comment by rusty-snake** [comment]
- Does FF has PW support? AFAIK no (for audio, screencapture is a different topic)
- Pipewire should be allowed
- If it is pipewire the must be an `about:config`/env-var workaround.
- What does `about:support` say about PW/PA?

**Comment by jmcclelland** [comment]
Thank you for the help!

>    Does FF has PW support? AFAIK no (for audio, screencapture is a different topic)

I believe that FF uses pulse audio, and that goes through `/usr/bin/pipewire-pulse` on a pipewire system

> What does about:support say about PW/PA?

Audio Backend	pulse-rust

> What's the name of the mic in the permission pop-up?

Built-in audio analog stereo

Thanks in advance for any suggestions on things to try.

**Comment by jmcclelland** [comment]
I'm beginning to think this is buggy firefox and/or jitsi meet behavior. I discovered that by clicking the microphone options in different orders I can get it to work. I don't think this is a firejail issue after all.

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)

Feel free to post any updates and to request to reopen if it seems that
firejail affects the issue.
