### ISSUE TITLE
midori - no gui after upgrade firejail 0.9.40

### ISSUE THREAD

**Issue by frank-github** [netblue30/firejail#551]
after upgrading firejail to 0.9.40 midori can started (process running), but has no GUI
no error message, nothing.....

any hints, tips, how to get more informations or better to start midori with GUI

**Comment by chiraag-nataraj** [comment]
Hmmm....seems to work. What happens if you do `firejail --debug --trace midori`?

**Comment by frank-github** [comment]
very long output, don't know what to look for :-(

[Uploading firejail.debug.midori.txt…]()

**Comment by netblue30** [comment]
It seems to be working fine in Ubuntu 14.04.

**Comment by frank-github** [comment]
not at my workstation with ubuntu 14.04  :-(
any hint how to find the solution, why I don't get GUI anymore? But process is running in background

**Comment by netblue30** [comment]
Does it work without any profile? Run "firejail --noprofile midori"

If it works, we can then go and debug the profile.

**Comment by frank-github** [comment]
okay, with --noprofile option midori starting with GUI  :-)

now I disabled and tried line by line in midori.profile
noroot line is the problem of mine, if I disabled it "#" midori is starting with GUI

why this didn't work for me, but others ????

**Comment by netblue30** [comment]
I've found a very old report from another Ubuntu 14.04 user complaining about the same thing. I have removed noroot from midori profile in git version. We have to assume it is something related to midori.
