### ISSUE TITLE
chdir error in sandbox.c | Missing details

### ISSUE THREAD

**Issue by gitsteff** [netblue30/firejail#5510]
Hi.
I started firejail using this command:

`firejail --debug --profile=~/.config/firejail/freeplane.profile /home/sl/Software/Freeplane/freeplane/freeplane.sh`

I get this Output, the error message is showing no hint at all which chdir failed. Where can I get this information from?

Creating empty /run/firejail/mnt/dns-etc/zsh directory
Mount-bind /run/firejail/mnt/dns-etc on top of /etc
Error chdir: sandbox.c:1117 sandbox: Permission denied
Error: proc 438162 cannot sync with peer: unexpected EOF
Peer 438163 unexpectedly exited with status 1

**Comment by rusty-snake** [comment]
As a first step you should provide necessary details like firejail version and the profile you use. The easiest way is to follow the bug template.

**Comment by gitsteff** [comment]
Hi.
I fixed it by myself, thanks for your effort.

Maybe you can make the log/messages a bit more verbose to see which dir is meant?

Thanks.

**Comment by kmk3** [comment]
@gitsteff [on Dec 9](https://github.com/netblue30/firejail/issues/5510#issuecomment-1344001235):

> Maybe you can make the log/messages a bit more verbose to see which dir is
> meant?
> 
> Thanks.

Good idea; done in commit f24a49a2c ("sandbox.c: print the dir on failed
chdir(cfg.homedir)", 2022-12-09).

**Comment by kmk3** [comment]
@gitsteff [on Dec 9](https://github.com/netblue30/firejail/issues/5510#issuecomment-1344001235):

> Hi. I fixed it by myself, thanks for your effort.

Alright, closing this.
