### ISSUE TITLE
audacity: network access and sandbox violation report

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#5539]
During another round of testing for work on #5538 I noticed a few things about our current profile.

The app scans the system for available plugins, including /lib/modules (which is a hard-coded no-no). That throws a `sandbox violation` which might confuse users. Adding the `allow-debuggers` option can take care of this and AFAICT shouldn't negatively affect the security of the sandbox. Due to our restrictive `private-bin audacity` there wouldn't actually be active support for debuggers, just silencing the blacklist violation.

A more difficult decision to make is whether we grant `network access` to Audacity. Currently we do not, although there's an inconsistency in our profile which we should fix. After testing I can only see the app going out on the internet to download 2 extra plugins:

- http://breakfastquay.com/rdf/lv2-rubberband#r3mono
- http://breakfastquay.com/rdf/lv2-rubberband#r3stereo

Besides using non-https URI's it's a bit of a pain to grant network access to an audio application for this sole purpose. There are plenty of built-in and installable (ladspa) filters/plugins already IMO. But that's an opinion nonetheless. Any thoughts on how we should proceed on this?

**Comment by netblue30** [comment]
Last year there were some discussions regarding the new privacy policy:

https://lifehacker.com/is-audacity-really-spyware-1847230028
https://www.pcmag.com/news/audacity-is-being-called-spyware-after-privacy-policy-update

Let's leave it the way you put it in https://github.com/netblue30/firejail/commit/6e67801a4592494d3d24e696f6fe06acc7856d88. If anybody needs live updates they can enable it in the profile.

**Comment by glitsj16** [comment]
@netblue30 Interesting info. Thanks for the heads-up!

**Comment by kmk3** [comment]
> The app scans the system for available plugins, including /lib/modules (which
> is a hard-coded no-no). That throws a `sandbox violation` which might confuse
> users. Adding the `allow-debuggers` option can take care of this and AFAICT
> shouldn't negatively affect the security of the sandbox. Due to our
> restrictive `private-bin audacity` there wouldn't actually be active support
> for debuggers, just silencing the blacklist violation.

Is this still an issue?

> A more difficult decision to make is whether we grant `network access` to
> Audacity. Currently we do not, although there's an inconsistency in our
> profile which we should fix. After testing I can only see the app going out
> on the internet to download 2 extra plugins:

Networking is enabled by default in the profile now:

* #6321

**Comment by glitsj16** [comment]
> Is this still an issue?

No, the issue is fixed by #6321. Closing...
