### ISSUE TITLE
/proc/config.gz blacklisted twice

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#5545]
Minor issue with blacklisting kernel configuration:

https://github.com/netblue30/firejail/blob/6e67801a4592494d3d24e696f6fe06acc7856d88/etc/inc/disable-common.inc#L624

https://github.com/netblue30/firejail/blob/6e67801a4592494d3d24e696f6fe06acc7856d88/etc/inc/disable-proc.inc#L11

Not sure which of these include files would be the better place for it. I've checked our profiles and there are _zero_ files that include disable-proc.inc without also including disable-common.inc, so it won't be a lot of work to remove it from one or the other. Or am I missing something here and it's supposed to be like this?

**Comment by kmk3** [comment]
Since disable-common.inc is the more, well, common include I'd leave it only
there.

Alternatively, put something like this in disable-proc.inc:

```firejail
blacklist /proc/config.gz # also in disable-common.inc
```

To make it clear that the duplication is intentional.

**Comment by rusty-snake** [comment]
>disable-common.inc is the more, well, common include 

Correct. But disable-proc should really disable proc and not depend on dc for full functionality.

I'd say dp must have it and we should keep it in dc as legacy blacklist for now.

OT: disable-proc can and should be used in much more profiles.

**Comment by glitsj16** [comment]
> disable-proc should really disable proc and not depend on dc for full functionality

Agreed. Now we just made it a bit more visible via the comment. Might avoid future mishaps if someone tries to remove it from dc.
