### ISSUE TITLE
When opened with Firejail, Thunderbird will not open links in default web browser.

### ISSUE THREAD

**Issue by marinecomm** [netblue30/firejail#555]
Just as the subject says. When I open Thunderbird using Firejail it refuses to open links in the default browser. Ive been searching around on the internet but can't seem to find much information regarding this issue. I did find this post: [https://github.com/netblue30/firejail/issues/507](url) but the fix that was suggested didn't work for me. An odd thing I noticed is if I click a link in an email, the process will show up in the Task Manager but won't open in the web browser.

I've tried commenting and uncommenting the following in the thunderbird.profile but to no avail.:

include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-common.inc thunderbird icedove

I'm not sure what else to do.

**Comment by netblue30** [comment]
Update to the latest 0.9.40 firejail version and give it a try. The profile files have totally changed, there are lots of fixes in. Are you using Chromium as the browser?

**Comment by marinecomm** [comment]
I am using Slimjet. I installed version 0.9.40 and I'm still having the same issue.

**Comment by laniakea64** [comment]
Here's a suggestion for investigating:
Open Thunderbird using firejail, then open a Terminal and join the Thunderbird firejail sandbox using the command `firejail --join=[pid]` (replacing '[pid]' with the existing firejail's PID).  This will get you a shell inside the Thunderbird's firejail sandbox.  From there, can you try to run Slimjet from that shell, does it work and if not do you get any relevant message(s)?
(If it hangs you can send interrupt with Ctrl+C in the Terminal but note that there is a potential risk of corruption by interrupting.)

**Comment by marinecomm** [comment]
I can't seem to find the pid for firejail. Whenever I use a command to find its pid it comes back with several pid's all of which belong to firejail thunderbird.

**Comment by laniakea64** [comment]
What command are you using to determine PID?
(Are you running multiple instances of Thunderbird under multiple firejails simultaneously?)

If you're running firejail in a Terminal, it should have output a line like,
```
Parent pid 10018, child pid 10019
```
That parent pid is the PID to use for `--join`.

**Comment by laniakea64** [comment]
Just looked up Slimjet and saw that it is a Chromium-based browser.
Does information in https://github.com/netblue30/firejail/issues/554 help?

**Comment by marinecomm** [comment]
Ok, I opened Thunderbird in Firejail. Then I opened a terminal and typed 'firejail'. It gave me back a parent pid and a child pid. In the terminal I typed `firejail --join=[pid]`. In place of the [pid] I entered the parent pid and it returned with: 

Switching to pid 2209, the first child process inside the sandbox

I then tried to open a link from an email in TB and still nothing. I don't see how the info in #554 would help as it's TB that's having the issue and not Slimjet. If I don't run TB in Firejail it will open links in Slimjet normally.

**Comment by laniakea64** [comment]
> it's TB that's having the issue and not Slimjet

This is not certain yet.  Only if Slimjet works fine run directly from the joined shell, then you'll know for a fact it's TB that's having the issue.  On the other hand, if Slimjet doesn't work from the shell any better than when run from TB, then the problem would be that Slimjet isn't compatible with your TB firejail sandbox, and the fix would be to adjust Slimjet flags and/or the firejail Thunderbird profile.

**Comment by laniakea64** [comment]
> Ok, I opened Thunderbird in Firejail. Then I opened a terminal and typed 'firejail'.

Sorry, didn't quite read this carefully.  You created and joined a totally different firejail instance than the Thunderbird firejail.  Here's yet another way to get firejail PID's: `firemon --list`
This is probably the easiest way if you're not running the Thunderbird firejail in a Terminal.
Sorry I didn't mention this before.

**Comment by netblue30** [comment]
What happens if you run slimjet with thunderbird profile? Make sure you don't already have slimjet running when you try it:
`````
$ firejail --profile=/etc/firejail/thunderbird.profile slimjet
`````
