### ISSUE TITLE
0.9.38-1~bpo: firejail cannot handle /etc/skel/.bashrc as symlink

### ISSUE THREAD

**Issue by Symbolis** [netblue30/firejail#556]
Was told to report this issue from distro downstream from Debian Jessie (jessie-backports).

Firejail whitelisting fails because /etc/skel/.bashrc is a symlink in their distro:

user@host:~$ firejail /usr/bin/iceweasel
Reading profile /home/user/.config/firejail/iceweasel.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 30345, child pid 30346
Error: invalid /etc/skel/.bashrc file
Error: cannot establish communication with the parent, exiting...

Issue goes away when /etc/skel/.bashrc is not a symlink (rm -f /etc/skel/.bashrc and copy original instead)

I can't check if fixed in 9.40 or not, sorry, but not finding tickets.

How to reproduce:

cp /etc/skel/.bashrc /etc/skel/.bashrc.orig
rm /etc/skel/.bashrc
ln -s /etc/skel/.bashrc.orig /etc/skel/.bashrc
firejail /usr/bin/iceweasel

**Comment by Symbolis** [comment]
How to reproduce: (probably, ymmv)
sudo -i
cp /etc/skel/.bashrc /etc/skel/.bashrc.orig
rm /etc/ske/bashrc
ln -s /etc/skel/.bashrc.orig /etc/skel/.bashrc
firejail /usr/bin/iceweasel

**Comment by Symbolis** [comment]
Also happens on 9.40 (attempted on another distro).

**Comment by netblue30** [comment]
I have a fix in git. The commit is https://github.com/netblue30/firejail/commit/c5ed2af102d72be6aa4edc473f50278013b10241

Thank you for the bug report.
