### ISSUE TITLE
firejail x11 app launched under i3  are not sandboxed

### ISSUE THREAD

**Issue by alexmaloteaux** [netblue30/firejail#5581]
When launching an X11 app for instance `firejail firefox` from i3  the app launches but is not sandboxed. `firejail --list ` doesnt show any X11 app neither.
Console apps , for instance top, are correctly sandboxed.

It is possible to launch i3 with a provided i3 profile, but what i would like to achieve is to launch i3 normally and then have all the per app profile applied from within i3. I tried from lxde on the same computer and it works flawless so it looks like i3 specific.

Does anybody have an idea if this is a normal feature, bug, misconfiguration or if this has to be addressed from within i3 only.

Best Regards

**Comment by alexmaloteaux** [comment]
here is a log of launching firefox : 

> firejail --apparmor  firefox
> Reading profile /etc/firejail/firefox.profile
> Reading profile /etc/firejail/whitelist-usr-share-common.inc
> Reading profile /etc/firejail/firefox-common.profile
> Reading profile /etc/firejail/disable-common.inc
> Reading profile /etc/firejail/disable-devel.inc
> Reading profile /etc/firejail/disable-exec.inc
> Reading profile /etc/firejail/disable-interpreters.inc
> Reading profile /etc/firejail/disable-proc.inc
> Reading profile /etc/firejail/disable-programs.inc
> Reading profile /etc/firejail/whitelist-common.inc
> Reading profile /etc/firejail/whitelist-run-common.inc
> Reading profile /etc/firejail/whitelist-runuser-common.inc
> Reading profile /etc/firejail/whitelist-var-common.inc
> Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
> Parent pid 125864, child pid 125867
> Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
> Warning: NVIDIA card detected, nogroups command ignored
> Warning: NVIDIA card detected, nogroups command ignored
> Warning: NVIDIA card detected, nogroups command ignored
> Warning: /sbin directory link was not blacklisted
> Warning: /usr/sbin directory link was not blacklisted
> Warning: NVIDIA card detected, nogroups command ignored
> Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
> Warning: NVIDIA card detected, nogroups command ignored
> Warning: NVIDIA card detected, nogroups command ignored
> Child process initialized in 346.80 ms
> 
> Parent is shutting down, bye...

**Comment by alexmaloteaux** [comment]
after some testing, it looks like it works when using "--dbus-system=none"  , notifications works too so i will just close this

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)

**Comment by kmk3** [comment]
(Offtopic)

Please see the following links for how to format code blocks in markdown:

* <https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks>
* <https://github.github.com/gfm/#fenced-code-blocks>

**Comment by kmk3** [comment]
@alexmaloteaux [on Jan 11](https://github.com/netblue30/firejail/issues/5581#issue-1528201496):

> When launching an X11 app for instance `firejail firefox` from i3 the app
> launches but is not sandboxed. `firejail --list ` doesnt show any X11 app
> neither. Console apps , for instance top, are correctly sandboxed.
> 
> It is possible to launch i3 with a provided i3 profile, but what i would like
> to achieve is to launch i3 normally and then have all the per app profile
> applied from within i3. I tried from lxde on the same computer and it works
> flawless so it looks like i3 specific.

There is a lot of debugging information missing; please follow the bug report
template:

* <https://github.com/netblue30/firejail/issues/new?assignees=&labels=&template=bug_report.md&title=>

Also, did you run `firecfg`?

What are the `Exec` lines in ~/.local/share/applications/firefox.desktop?

**Comment by rusty-snake** [comment]
OT: In general questions should be asked in Discussions.
