### ISSUE TITLE
Invalid --profile-path command line option

### ISSUE THREAD

**Issue by nya1** [netblue30/firejail#5585]
### Description

Any path provided to the CLI option `--profile-path` is returning an error.

### Steps to Reproduce

```bash
mkdir ~/.custom
LC_ALL=C firejail --profile-path="~/.custom" firefox
```

### Expected behavior

Load the provided profile path without returning an error ([like mentioned in the usage](https://github.com/netblue30/firejail/blob/0.9.70/src/firejail/usage.c#L208)]

### Actual behavior

An error is returned

```
Error: invalid --profile-path=~/.custom command line option
```

### Behavior without a profile

The same error is returned

### Additional context

It seems that the CLI option is not available as any path provided returns an error

### Environment

- Debian 11
- Firejail version 0.9.70

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [x] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail --profile-path="~/.custom" firefox</code></summary>
<p>

```
Error: invalid --profile-path=~/.custom command line option
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug --profile-path="~/.custom" firefox</code></summary>
<p>
  

```
Error: invalid --profile-path=~/.custom command line option
```

</p>
</details>

**Comment by rusty-snake** [comment]
> It seems that the CLI option is not available as any path provided returns an error

Correct. From firejail 0.9.52 RELNOTES:

https://github.com/netblue30/firejail/blob/ee89a263e28902f723a1ac322221f85d9eb2ad24/RELNOTES#L458

---

Also the error is greate

```console
$ firejail --qwertzuiop true                              # Does not exist
Error: invalid --qwertzuiop command line option
$ firejail --blacklist true                               # Requires arguments
Error: invalid --blacklist command line option
```

**Comment by nya1** [comment]
@rusty-snake thanks for the quick reply, is there an alternative CLI option that can be used to accomplish the same thing?

**Comment by rusty-snake** [comment]
The closet you have is `--profile` which specifies the profile by name or by path. Depending your use case, you can use it directly or through and wrapper.
