### ISSUE TITLE
cryptsetup issue

### ISSUE THREAD

**Issue by webslim** [netblue30/firejail#56]
I've run into the following issue:
1. open a LUKS device with cryptsetup and mount it
2. start firejail sandbox
3. unmount the drive
4. run "cryptsetup luksClose $device". (outside of the sandbox)
-> cryptsetup can't close the dm device and complains that it is still in use.

**Comment by pmillerchip** [comment]
The device might still be mounted in the firejail's context. Try joining the existing firejail using a `firejail --join` command and checking to see if it's still mounted in there.

**Comment by netblue30** [comment]
Each sandbox an independent mount table/mount namespace. This table starts as a copy of the main system mount table, and evolved independently after that. Your LUKS device has an entry in both the main mount table and in the sandbox mount table. You'll have to unmount it also in the sandbox.

**Comment by webslim** [comment]
Thank you!

**Comment by netblue30** [comment]
you're welcome
