### ISSUE TITLE
https://github.com/netblue30/firejail/projects/3#card-75760383

### ISSUE THREAD

**Issue by Valmirmiih** [netblue30/firejail#5603]
### Description

_Describe the bug_

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Run in bash `LC_ALL=C firejail PROGRAM` (`LC_ALL=C` to get a consistent output in English that can be understood by everybody)
4. See error `ERROR`

### Expected behavior

_What you expected to happen_

### Actual behavior

_What actually happened_

### Behavior without a profile

_What changed calling `LC_ALL=C firejail --noprofile /path/to/program` in a terminal?_

### Additional context

_Any other detail that may help to understand/debug the problem_

### Environment

- Linux distribution and version (e.g. "Ubuntu 20.04" or "Arch Linux")
- Firejail version (`firejail --version`).
- If you use a development version of firejail, also the commit from which it was compiled (`git rev-parse HEAD`).

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [x] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
output goes here
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>
  

```
output goes here
```

</p>
</details>

**Comment by smitsohu** [comment]
Hi @Valmirmiih. I think it is not clear at the moment (to me at least) which issue you are running into. Could you try to fill out the issue template, or alternatively describe the problem in free text?

**Comment by kmk3** [comment]
> https://github.com/netblue30/firejail/projects/3#card-75760383

Considering the nonsensical title and the lack of any information, I think that
this was opened by mistake, so I'm closing this.

If that's not the case, feel free to add more information and to ask to reopen.
