### ISSUE TITLE
private-etc rework broke profiles without resolv.conf in private-etc

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#5608]
After the private-etc rework from https://github.com/netblue30/firejail/commit/c2b6b6b1a348d70b776983051851e42ba66ab271 I noticed a few profiles are now in a broken state. When private-etc is enabled without including `resolv.conf` firejail exits with the below error:

```
Error mount: fs_etc.c:58 fs_resolvconf: No such file or directory
Error: proc xxxx cannot sync with peer: unexpected EOF
Peer yyyy unexpectedly exited with status 1
```

The fix is to add resolv.conf to private-etc. Relates to #5607.

**Comment by rusty-snake** [comment]
8377c54b1d803e2d4a282751652d824376fb371d
