### ISSUE TITLE
Can't launch LibreOffice with --net=none

### ISSUE THREAD

**Issue by GabrielH0we** [netblue30/firejail#562]
I'm trying to restrict LibreOffice from accessing internet.

Here is my config
```
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-passwdmgr.inc

noblacklist ${HOME}/.kde
#blacklist ${HOME}/.wine

caps.drop all
net none
netfilter
nonewprivs
noroot
protocol unix,inet,inet6
seccomp

whitelist ${HOME}/Documents/libredocs
whitelist ${HOME}/.config/libreoffice
```

And here is what I see in konsole:

`LibreOffice(19)/kdeui (kdelibs): Session bus not found 
To circumvent this problem try the following command (with Linux and bash) 
export $(dbus-launch) `

It starts fine without "net none" in .profile.

 I tried configurations from #379, but they don't work for me. I see  
`execvp: No such file or directory`
even if I start libreoffice from a symlink at /usr/local/bin/

Firejail version is 0.9.41 (cloned from git). 

UPD: it actually grsecurity, that kills libreoffice process for resource overstep. Tried to fix it with paxctl -cm, but it didn't work.

**Comment by netblue30** [comment]
When you use --net, the dbus socket is discarded by the network namespace, so there will not be any dbus support. It looks like libreoffice crashes - a very few programs do this. It is a libreoffice bug, or maybe a kdelibs bug.

**Comment by netblue30** [comment]
A workaround: comment out "net none" in your profile, and replace "protocol unix,inet,inet6" with "protocol unix". This should reject the network connections, but it will not interfere with dbus functionality.

**Comment by chiraag-nataraj** [comment]
Huh. I'm curious which version of libreoffice you're using. I'm using the latest development version which works fine with `--net=none`.

**Comment by GabrielH0we** [comment]
As I wrote in the original message, it's Grsecurity, that kills Libreoffice process for resource overstep. 

Workaround with "protocol unix" works fine with Grsecurity.
