### ISSUE TITLE
"Open destination folder" doesn't work in qBittorrent with private-bin

### ISSUE THREAD

**Issue by GabrielH0we** [netblue30/firejail#563]
Version: 0.9.41
Default qbittorrent.profile with whitelisted content folders (${HOME}/<folder>)
"Open destination folder" (for folders) and "Open" (for files) functionality don't work in firejailed qBittorrent.

```
MESA-LOADER: could not create udev device for fd 30
MESA-LOADER: could not create udev device for fd 33
MESA-LOADER: could not create udev device for fd 33
Unable to detect a launcher for 'file:///<file or folder>'
```

If you add xdg-open to private-bin, you can see this:

```
MESA-LOADER: could not create udev device for fd 29
MESA-LOADER: could not create udev device for fd 22
MESA-LOADER: could not create udev device for fd 22
Launch failed (/usr/local/bin/xdg-open file:///<file or folder>)
```

**Comment by netblue30** [comment]
I have disabled private-bin in qbittorrent for now, thanks for the bug.

**Comment by GabrielH0we** [comment]
Update. Please note, exo and Thunar below are XFCE applications.

Got it working with private-bin and "Open destination folder"

```
private-bin qbittorrent,xdg-open,sh,Thunar,exo-open,python2  
private-dev
private-etc X11,fonts,xdg,resolv.conf

```

What was important:
- use "xdg" in private-etc (doesn't work without that - helper.rc with reference to Thunar file manager is there),
- use sh,xdg-open,exo-open,Thunar in private-bin (Thunar with capital T - doesn't work like "thunar" on Slackware, but probably will on other Linux systems),
- use python2 in private-bin (to make Search Engine work),
- use resolv.conf (to allow Search engine to search online).

**Comment by GabrielH0we** [comment]
By the way, firemon was useless for debugging all of it. Or maybe I just use it wrong?

**Comment by netblue30** [comment]
Thanks for update, at some point I'll bring back private-bin.
