### ISSUE TITLE
Qutebrowser profile breaks userscripts

### ISSUE THREAD

**Issue by kjk11** [netblue30/firejail#5639]
As described [here](https://github.com/qutebrowser/qutebrowser/issues/7575) , one of the recent changes to the Qutebrowser profile, most likely this pull request https://github.com/netblue30/firejail/pull/5389, breaks the invocation of qutebrowser userscripts. I have been able to circumvent this problem by setting 

```
ignore apparmor
ignore noexec ${HOME}
```
in qutebrowser.local . I believe userscripts should work by default. Perhaps there is a more fine-grained way of getting the functionality back?

**Comment by glitsj16** [comment]
> I believe userscripts should work by default.

Thank you for reporting this. I agree.

> Perhaps there is a more fine-grained way of getting the functionality back?

There are several profiles that have `ignore noexec ${HOME}`. In general that loosens the sandbox obviously, but it still is dependend on what you have installed under ${HOME} that potentially could pose a threat. Not really a fine-grained tool though the `ignore noexec` option, but we'll need to add it to the profile regardless.

You could try to compensate for this `loss` via additional AppArmor rules, only allowing the owner of files under ${HOME}/.config/qutebrowser/userscripts to execute those and nothing else. Check your `/etc/apparmor.d/local/firejail-default`, there are interesting comments inside that can help achieve this.

OTOH, something like the below should limit what's allowed to be executed:

```
owner @{HOME}/.config/qutebrowser/userscripts/** ix,
```

Just remember to clear AA's rules cache (if you use that option) after editing the file and usually a reboot is also required for AA to enforce the changes. If you need help with that, feel free to ask.

**Comment by glitsj16** [comment]
@kjk11 Usual deal. Merging the PR auto-closes this. Feel free to reopen.
