### ISSUE TITLE
Allow running even when global config file is missing

### ISSUE THREAD

**Issue by fasterthanlime** [netblue30/firejail#567]
I'd like https://github.com/itchio/itch to ship its own firejail binary, and the only thing preventing me from doing so right now seems to be that firejail refuses to start if /usr/local/etc/firejail/firejail.config doesn't exist.

It's probably easy to patch from my side, but if upstream supported it, that would be even better!

**Comment by fasterthanlime** [comment]
The current behavior is:

```
fprintf(stderr, "Warning: Firejail configuration file %s not found\n", fname);
exit(1)
```

That's one hell of a warning!

**Comment by netblue30** [comment]
I added support to disable firejail.config enforcing at compile time. Configure the software as follows:
`````
$ ./configure --disable-globalcfg
`````
At runtime, if firejail.config is not present in the filesystem, firejail will use the defaults. Let me know if you need anything else.

**Comment by fasterthanlime** [comment]
That's exactly what I was looking for, thanks a lot for the change!

**Comment by fasterthanlime** [comment]
(Actually, having a tag that includes this commit would be great, if cutting a release isn't too much work for you!)

**Comment by netblue30** [comment]
All set, use disable-globalcfg tag.
