### ISSUE TITLE
uvm lightweight vm support 

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#5687]
Maybe supportable project with Firejail.

https://pointersgonewild.com/2023/02/24/building-a-minimalistic-virtual-machine/

Thanks and

Best regards

**Comment by rusty-snake** [comment]
It is a interesting project especially if you read the source and learn about how computers work. However I don't see a use case for firejail so unless someone can come up with one I close here.

FTR: It is a vm focused on API stability (the API of the ISA) and runs it's own instruction set. No x86. No Kernel. No File I/O (yet). No Network I/O (yet). No GUI. No real world programs for it.

**Comment by osevan** [comment]
Ok thank you very much for fast answer

**Comment by kmk3** [comment]
@osevan

Whenever you would like to request a feature but do not have a concrete
proposal for how to implement it, please open a discussion instead of an issue:

* <https://github.com/netblue30/firejail/discussions/categories/ideas>

This helps keep the issue tracker organized.
