### ISSUE TITLE
Is it possible to have proper support for systemd-resolved?

### ISSUE THREAD

**Issue by tomgar** [netblue30/firejail#569]
The point of systemd-resolved is that it has a DNS cache. 

I noticed that inside firejails if the system doesn't have a /etc/resolv.conf file and /etc/nsswitch.conf is just configured to use the nss-resolve, dns queries will fail. At the moment a resolv.conf file is added to /etc/ (like symlinking the one from systemd-resolved in /run/systemd/resolve/resolv.conf), dns queries will work but the DNS cache is bypassed completely.

**Comment by netblue30** [comment]
What seems to be the issue? I am reading from systemd-resolvd man page:

> In addition it maintains the /run/systemd/resolve/resolv.conf file for compatibility with traditional Linux programs. This file may be symlinked from /etc/resolv.conf.

systemd-resolvd should work just fine with the symlink. Also, according to nss-resolv man page, the library installed by systemd-resolvd, the host line in /etc/nsswitch,conf should look like this:

> hosts:          files resolve mymachines myhostname

What distro are you using?

**Comment by tomgar** [comment]
My installation is correct. I already had all of that. I'm using ArchLinux with the latest firejail. It's really easy to check what's happening with the command systemd-resolve --statistics. Run firefox and chromium inside a firejail, browse a bit and run the systemd-resolve --statistics before and after browsing: the cache size will remain the same. What's happening is that inside the firejail nss-resolve is falling back to nss-dns which just uses the /etc/resolv.conf file.

From the nss-resolve man page: 
_"Note that nss-resolve will chain-load nss-dns if systemd-resolved.service is not running, ensuring that basic DNS resolution continues to work if the service is down."_

Nss-resolve doesn't use /etc/resolv.conf at all (just to fill up its internal resolv.conf file found inside /run), so another way to check the problem is removing /etc/resolv.conf which makes impossible to run dns queries since nss-dns won't find the resolv.conf file. Another way is running systemd-resolve itself inside firejail which says "sd_bus_open_system: Permission denied".

My guess is that something needs to be done so the nss-resolve lib inside firejail can access outside's systemd-resolved service via dbus.

**Comment by netblue30** [comment]
How do you start firefox? Like "firejail firefox" or you add more options?

**Comment by tomgar** [comment]
Yep, that way and I don't have any custom firefox profile in ~/.config/firejail so I'm using the one coming from the firejail package.

**Comment by netblue30** [comment]
Ok, this is a bug, I'll look into it.

**Comment by chiraag-nataraj** [comment]
Huh, this seems to still be an issue (since I disabled `systemd-resolved'`s cache, I removed `resolv.conf` to test if `systemd-resolved` was accessible inside the sandbox). I'm going to investigate to try to figure out what's going on.

**Comment by chiraag-nataraj** [comment]
Huh, never mind. It works now (at least for me). The culprit in my case was not including specific libraries in my `private-lib` filter.

**Comment by chiraag-nataraj** [comment]
@tomgar Do you still have this issue? It seems to be fixed for me (with a fairly restrictive profile involving `private-lib`, no less).

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this. @tomgar If you still have this issue, please re-open.
