### ISSUE TITLE
X11 Sandboxing security

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#570]
I have a question regarding Firejail security. Does "X11 sandboxing" stop applications snooping on each other, if you run e.g.:

firejail --seccomp firefox

...and at the same time have a file manager open or a terminal running as root? Can isolated application running in Firejail still send fake input to other clients? Can it spot you have a file manager open or even worse, a terminal running as root, and send fake input?

**Comment by netblue30** [comment]
Run it this way:
`````
$ firejail --net=eth0 --x11 firefox
`````
seccomp in this case is done by default, so you don't need it to put it in.

I have more information on x11 here: https://firejail.wordpress.com/documentation-2/x11-guide/

It will stop applications running in a sandbox to snoop on applications running outside the sandbox.

**Comment by rekixex** [comment]
Ok, great. I found X11 guide shortly before. :)

`firejail --net=eth0 --x11 firefox`

...gives more security than...

`firejail --seccomp firefox`

...without loss of usability? Do you recommend it for day-to-day use, instead of generic command `firejail firefox`, or `firejail --seccomp firefox` command?

And how does Firejail security compare with AppArmor security (regardless of different implementation)? Does Firejail match AppArmor application isolation, in terms of security? I ask because I used AppArmor before, it is considered as pretty secure application isolation as far as I know.

**Comment by netblue30** [comment]
> Do you recommend it for day-to-day use, instead of generic command firejail firefox

The external xservers (xpra and  xephyr) I am using don't support hardware acceleration. Use them if you are in a hostile environment and you have reasons to believe you need this additional type of sandboxing. They also bring in their own bugs and problems. For regular browsing I wouldn't bother. 

> Does Firejail match AppArmor application isolation, in terms of security?

SELinux and AppArmor are as good as the security profiles you use to configure them. If you don't configure them, there will be no isolation. By default SELinux comes with 0 (zero) security profiles for desktop applications. AppArmor has 3 profiles: evince, firefox and chromium. Chromium profile is broken. I don't know how good firefox profile is.

**Comment by rekixex** [comment]
> Use them if you are in a hostile environment and you have reasons to believe you need this additional type of sandboxing.

Public wifi. :)

> Chromium profile is broken. I don't know how good firefox profile is.

Chromium generic profile has been broken for a long time. Evince and Firefox profiles work fine for everyday use.

**Comment by rekixex** [comment]
> It will stop applications running in a sandbox to snoop on applications running outside the sandbox.

What about interactions between applications running in a sandbox? For example, if I run:

firejail --net=eth0 --x11 firefox

...following...

firejail --net=eth0 --x11 transmission-gtk

...does it stop Firefox snooping on Transmission and vice versa?

**Comment by netblue30** [comment]
In your example firefox will not be able to snoop on transmission, and transmission will not be able to snoop on firefox. Both of them are isolated by a different xserver.

**Comment by rekixex** [comment]
Ok. Thanks for information. :)

**Comment by Sidnioulz** [comment]
For some reason, I can't seem to run git firejail with X11, but you can verify the security works as intended by first reading [this article on how to spy on keyboard input](http://theinvisiblethings.blogspot.co.at/2011/04/linux-security-circus-on-gui-isolation.html) and then doing this:

 * Open a Xterm instance with firejail --x11 and check if it gets the keyboard input when other windows have the focus
 * Open a sandboxed Firefox with --x11, and another sandboxed shell without --x11. In that shell, use the xinput test method and check if you get keyboard input for unsandboxed apps (normally yes), and for Firefox (according to @netblue30 , no, but I suspect the answer could be yes).

@netblue30  how do you manage X11 selections? Is the clipboard API functional inside sandboxed clients? It should normally not be at all, given how the X11 API works, since enabling it means sandboxed apps can read all the clipboard content continuously without user consent.

**Comment by rekixex** [comment]
@netblue30 According to @reinerh 

> x11 is not supported for profiles.

Which profile does Firejail use for Firefox with command `firejail --net=eth0 --x11 firefox`? Is it Firefox predifined profile, like when you use generic command `firejail firefox` or...?

**Comment by rekixex** [comment]
@netblue30 Does Firejail use **seccomp** by default in generic command `firejail firefox`?

**Comment by netblue30** [comment]
@Sidnioulz: You need to also configure a network namespace, you have all the details here: https://firejail.wordpress.com/documentation-2/x11-guide/

@rekixex: seccomp is enabled by default, you don't need to specify it in "firejail program_and_arguments"

**Comment by Sidnioulz** [comment]
@netblue30 ah, makes sense! May I suggest forbidding firejail --x11 without a --net argument, since that would be an incomplete form of X11 isolation?

**Comment by netblue30** [comment]
I'll look into it.

**Comment by netblue30** [comment]
I'll print a warning, just forbidding it would be very inconvenient for some users, thanks for the suggestion.
