### ISSUE TITLE
PulseAudio support is broken when client.conf is a link

### ISSUE THREAD

**Issue by j1r1k** [netblue30/firejail#571]
Currently there is a check in `firejail/pulseaudio.c` whether `/etc/pulse/client.conf` is a symbolic link (see https://github.com/netblue30/firejail/blob/master/src/firejail/pulseaudio.c#L107).

This breaks support for pulseaudio in firejail in NixOS (as client.conf is always symbolic link there).

It seems that removing this check fixes the problem (and pulseaudio works in firejail).

Is there any reason to keep it?

**Comment by netblue30** [comment]
You are right, there shouldn't be any reason for symlink checking there. I put a fix in git. Thanks for the bug.

**Comment by j1r1k** [comment]
@netblue30 Thanks a lot for a prompt fix.

**Comment by netblue30** [comment]
No problem.
