### ISSUE TITLE
strace new features relevant?

### ISSUE THREAD

**Issue by HulaHoopWhonix** [netblue30/firejail#572]
strace has a two new flags for displaying file and network names instead of numbers [0]. Subgraph-Oz was thinking of adding something similar for seccomp-bpf auditor to make profile creation simpler.

[0] http://jvns.ca/blog/2016/06/07/strace-y/
[1] https://twitter.com/attractr/status/742729551416025088

**Comment by netblue30** [comment]
Thanks for the info, but strace and ptrace syscall are disabled by the sandbox. Allowing them in the sandbox would be a huge mistake.
