### ISSUE TITLE
signal-desktop fails on startup

### ISSUE THREAD

**Issue by kmk3** [netblue30/firejail#5726]
### Discussed in https://github.com/netblue30/firejail/discussions/5725

<div type='discussions-op-text'>

<sup>Originally posted by **rieje** March  9, 2023</sup>
Anyone have a guess why signal-desktop fails on system startup? I run it as a systemd user service. It pretty much never starts on startup and I need to restart the service and then it will launch. On the rare occasion I think it might randomly crash but I'm not sure. If I don't run it without firejail it works fine without fail. Here's [systemd service status](https://0x0.st/HiAg.txt). I'm on Wayland (Sway).</div>

**Comment by kmk3** [comment]
Basic debugging information is missing; please follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>

**Comment by rieje** [comment]
I would think `firejail[1165]: Access error: uid 1000, last mount name:/ dir:/run/user/1000/gvfs type:fuse.gvfsd-fuse - invalid noexec mount` would be relevant. It doesn't seem straightforward to debug it since it only happens once on system startup but I'll give it another go if I have the time.

**Comment by kmk3** [comment]
@rieje

Sorry for the delay.

> please follow the bug report template

I realize now that since I opened this myself, you probably can't update
anything in the first comment.

GitHub's UX for converting a discussion into an issue is lacking.

Could you open a new issue yourself?

> Here's [systemd service status](https://0x0.st/HiAg.txt). I'm on Wayland
> (Sway).

Also, unless you want to avoid GitHub specifically, could you upload this file
in the new issue itself?

It should be possible to just drag and drop it in a comment.
