### ISSUE TITLE
Using Firejail by Default

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#573]
Can you force applications to always run sandboxed, regardless of how you launch them (or at least when you launch them from the menu / panel launchers / .desktop files)?

I would like to run `firejail --net=eth0 --x11 firefox` or `firejail --seccomp firefox` by default whenever I launch Firefox.

I found these guides:

https://wiki.archlinux.org/index.php/Firejail#Using_Firejail_by_Default

https://sites.google.com/site/easylinuxtipsproject/sandbox#TOC-Firefox-completely-in-the-sandbox-only-for-advanced-users-

**Comment by reinerh** [comment]
Try firecfg which is available since 0.9.40.
It creates symlinks for your profiles in /usr/local/bin, which causes them to get started with firejail automatically.

**Comment by rekixex** [comment]
https://firejail.wordpress.com/features-3/man-firecfg/

Is it installed by default in Firejail?

`sudo firecfg` is the way to go? That's all I need to accomplish this setup?

If I understood correctly, `sudo firecfg` will force all applications which have defined profiles to start sandboxed automatically whenever they are launched **from the menu / panel launchers / .desktop files**? For example, will Evince start sandboxed automatically when I open PDF file **from file manager**?

Sorry for asking too much. I can't wait to try it out, my PC is unavailable right now. :)

**Comment by reinerh** [comment]
Yes, it's installed by default.

It works when the tools are started by name (via menu/desktop files, etc.), not by absolute path.
When the absolute path is in the desktop file, firejail will not be called.

**Comment by rekixex** [comment]
Ok. How to run firejail --net=eth0 --x11 firefox this way? I would preffer X11 sandboxing as default setup to start with.

**Comment by reinerh** [comment]
You put your config like `net eth0` into your profile.
Calling firejail over a symlink is like starting firejail with the profile.

But I just see that x11 is not supported for profiles.

**Comment by rekixex** [comment]
Still I don't understand. Should I edit profile to add --net=eth0 --x11? There is no way to start Firefox with `firejail --net=eth0 --x11 firefox` automatically by default?

> But I just see that x11 is not supported for profiles.

How does it affect `firejail --net=eth0 --x11 firefox` command?

**Comment by reinerh** [comment]
The command line is not affected at all.
If you edit profile files (the default behavior of sandboxed applications in /etc/firejail), you can put `net eth0` in, but X11 sandboxing is currently not possible via profiles.

**Comment by rekixex** [comment]
Ok, it seems that running Firefox with X11 sandboxing automatically by default is not possible for now.

Anyway, if I run only `firejail --net=eth0 --x11 firefox`, it will not launch Firefox profile? Which profile will it choose for Firefox?

**Comment by reinerh** [comment]
When launching it with additional parameters you can still see `Reading profile /etc/firejail/firefox.profile`, so your profile will still be honored.

**Comment by rekixex** [comment]
Ok, but what did you mean by this:

> But I just see that x11 is not supported for profiles.

and

> X11 sandboxing is currently not possible via profiles.

...?

**Comment by reinerh** [comment]
It means that you can not configure X11 sandboxing in profiles, see also:
https://firejail.wordpress.com/features-3/man-firejail-profile/

**Comment by rekixex** [comment]
I see.

**Comment by rekixex** [comment]
@reinerh Have you seen this guide on Arch Linux Wiki:

https://wiki.archlinux.org/index.php/Firejail#Using_Firejail_by_Default

Is it possible to use X11 sandboxing by default this way:

Create the following file for firefox make it executable:

`/usr/local/bin/firefox`
`firejail --net=eth0 --x11 /usr/bin/firefox $@`

What do you think?

**Comment by reinerh** [comment]
Yes, that works too.
But I find the symlink solution more elegant (if X11 sandboxing is not important).

**Comment by rekixex** [comment]
I agree. Since I am on public wifi, I will probably try it initially with X11 sandboxing by default. :)

**Comment by rekixex** [comment]
@reinerh It would be great to launch supported applications sandboxed by default. For example, to force Evince to start sandboxed whenever PDF file is opened from file manager.

But that's probably too complex to implement. By the way, it is currently possible in **AppArmor** (command similar to `sudo firecfg`) and in **Sandboxie** in Windows (but only with paid version). AppArmor comes with only 3 profiles by default, Sandboxie has much more than that, similar to Firejail.

**Comment by reinerh** [comment]
It probably depends on the file manager and/or the .desktop files, but in general opening files sandboxed in Evince is possible with the symlink approach (assuming Evince is not started by absolute path).

**Comment by rekixex** [comment]
Regarding AppArmor, when you open PDF file in the file manager (Nautilus), Evince starts sandboxed.

**Comment by rekixex** [comment]
@reinerh Regarding AppArmor, when you open a PDF file from the file manager (Nautilus), Evince starts sandboxed. If you put Evince profile in enforce mode.

**Comment by rekixex** [comment]
@reinerh Regarding AppArmor, when you open a PDF file from the file manager (Nautilus), Evince starts sandboxed. If you put Evince profile in enforce mode. Is it possible with Firejail?

**Comment by netblue30** [comment]
We don't have support for file managers in this moment. They use full paths to start executables.

**Comment by rekixex** [comment]
@netblue30 Can I somehow force file manager to use symlink to start executable?

**Comment by netblue30** [comment]
It depends on the file manager. Some of them allow you to handle a specific file type with a specific executable. For example for .pdf files, it opens a window where you can choose the executable. In this window you would go an choose /usr/local/bin/evince instead of the regular /usr/bin/evince.

**Comment by avoidr** [comment]
I only skimmed this thread, but you can also put a bash alias with your firejail and options prepended to the program name, but that obviously only works for programs started from the shell. Just as another tip.
Or I have some symlinks to firejail in `~/.bin`. (Easier to set symlinks because no root perms are required and I use `~/.bin` anyway.)

**Comment by rekixex** [comment]
@netblue30 And it can be set as default in such a way. But it would be time consuming to do it for every executable. Alternative would be to edit `/usr/share/applications/defaults.list`, which is also manual solution.

**Comment by netblue30** [comment]
There is no clean solution at the moment, you will have to do it for each file type. What distro and desktop environment are you using?

**Comment by rekixex** [comment]
@netblue30 Ubuntu 15.10 at the moment, though I will have to switch to LTS (end of life date is July 2016).

**Comment by rekixex** [comment]
@netblue30 Ubuntu 15.10 at the moment, though I will have to switch to LTS (end of life date is July 2016). Is Firejail packaged by Ubuntu 16.04?

**Comment by netblue30** [comment]
Yes, do "sudo apt-get install firejail"
