### ISSUE TITLE
Workaround to allow user management with kernels prior to 3.18 when firejail running?

### ISSUE THREAD

**Issue by david-drinn** [netblue30/firejail#574]
For those stuck at kernels older than 3.18, is there a workaround to allow user management with `adduser` (and its various related user management commands) when firejail is running? For my use case, while a user is logged in to firejail in restricted shell mode, the user is allowed to do user management.

I tried these configuration options at the top of `/etc/firejail/generic.profile`, but it seems to make no difference.

```bash
noblacklist /etc/passwd
noblacklist /etc/shadow
noblacklist /etc/group
```

As a shot in the dark, I also tried disabling `chroot` and `userns` in `/etc/firejail/firejail.config`, with no luck.

I suspect these blacklisted files are tightly integrated with the security of firejail, and so cannot be reasonably whitelisted, but I wanted to ask to be sure. :-)

For reference, this relates to the issue described in the main page's known issues, as well as various issues posted on GitHub, such as [559](https://github.com/netblue30/firejail/issues/559).

**Comment by netblue30** [comment]
Unfortunately there is no workaround. The fix was deep inside the kernel.
