### ISSUE TITLE
strange things happens with php-fpm and --noprofile flag

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#5746]
Im running in my test environment php-fpm inside my favourite  fj container. Everything works great,  except internet functionality of cms software like wordpress. 

Even when i run with --noprofile flag internet connections for searching directory like for plugins didnt work.

Outside container everything works - even internet connection.

So i dunno what is wrong.

Apparmor ofc for this profile disabled, but i  havent internet connection for both: with --noprofile flag AND with profile. 

Hope someone can check this up.

Other containers have internet.

Thanks and

Best regards

**Comment by kmk3** [comment]
Basic debugging information is missing; please follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>

**Comment by osevan** [comment]
Debian bullseye
Firejail master branch from 30 days ago.

Application startpath /opt/php8.2/bin/php-fpm -nodamonize and config file in as arguments

Both tested: with --noorofile and wity profile. ..

Aplication starts well, but, no internet connection to outside - egress and ingres - traffic. 

Outside container imternet works.


Container running inside vps

**Comment by osevan** [comment]
I see now, etc/resolv.conf is flagged as default as blacklist. 

I did whitelist resolv.conf and added new dns inside config and my Problem gone.

Thanks and

Best regards

**Comment by kmk3** [comment]
(Re-closing as "not planned" since nothing was changed in firejail)
