### ISSUE TITLE
inside firejail running webserver, cant find latest live files

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#5750]
Live files for webserver needs Firejail restart. 

Directory refresh, or, remount after time period needed here.

Else, tech action needed with Firejail restarting webserver container.

Thanks and

Best regards.

**Comment by kmk3** [comment]
Basic debugging information is missing; please follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>
