### ISSUE TITLE
LibreOffice profile?

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#576]
Firejail already includes many profiles. Why there is no LibreOffice profile? Could you add it?

**Comment by Fred-Barclay** [comment]
That sounds like a good idea. I'm on it! :)

**Comment by netblue30** [comment]
Thanks @Fred-Barclay, let me know when you are done and I'll merge you in.

**Comment by Fred-Barclay** [comment]
Done!  #580

**Comment by netblue30** [comment]
I added profiles for loffice, lowriter, lodraw, etc. Try it out!
