### ISSUE TITLE
Add whitelist directoryname with single quotes

### ISSUE THREAD

**Issue by technout** [netblue30/firejail#5766]
Quick question:
I like to add a whitelist dir with:
whitelist /media/data/my video's

When running i get the error: * is an invalid filename

Is it possible to escape this? - I did try with backslash, but no success..
Is it not possible?

**Comment by rusty-snake** [comment]
Actually it should work. Looks like you use an older firejail version.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/commit/de879e88c9dcbd237ff45e5560ab631ad063c081

**Comment by rusty-snake** [comment]
Dupliacted of #4614

**Comment by rusty-snake** [comment]
So try to upgrade to firejail 0.9.68 vor newer.

**Comment by technout** [comment]
Thanks for the quick replay, i had installed the default repository version from Ubuntu 20.04 (which was 0.9.62)
Now i have installed 0.9.72
And now it is working! 👍
