### ISSUE TITLE
build: error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by huanghaiqing1** [netblue30/firejail#5778]
./configure has no warning, but make reports the following error:

```console
[root@singularity firejail]# make
make -C src/lib
make[1]: Entering directory `/root/patch/firejail/src/lib'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/patch/firejail/src/lib'
make -C src/man
make[1]: Entering directory `/root/patch/firejail/src/man'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/patch/firejail/src/man'
make -C src/zsh_completion
make[1]: Entering directory `/root/patch/firejail/src/zsh_completion'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/patch/firejail/src/zsh_completion'
make -C src/bash_completion
make[1]: Entering directory `/root/patch/firejail/src/bash_completion'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/patch/firejail/src/bash_completion'
make -C src/firecfg/
make[1]: Entering directory `/root/patch/firejail/src/firecfg'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/patch/firejail/src/firecfg'
make -C src/firejail/
make[1]: Entering directory `/root/patch/firejail/src/firejail'
gcc -ggdb  -O2 -DVERSION='"0.9.73"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fPIE -DPREFIX='"/usr/local"' -DSYSCONFDIR='"/usr/local/etc/firejail"' -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -DVARDIR='"/var/lib/firejail"'   -DHAVE_OUTPUT -DHAVE_X11 -DHAVE_PRIVATE_HOME     -DHAVE_USERTMPFS -DHAVE_DBUSPROXY  -DHAVE_GLOBALCFG -DHAVE_CHROOT -DHAVE_NETWORK -DHAVE_USERNS -DHAVE_FILE_TRANSFER  -DHAVE_SUID   -mindirect-branch=thunk -fstack-clash-protection -fstack-protector-strong -g -O2  -c env.c -o env.o
env.c: In function ‘env_apply_list’:
env.c:282:4: error: ‘for’ loop initial declarations are only allowed in C99 mode
    for (unsigned int i = 0; i < num_items; i++)
    ^
env.c:282:4: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [env.o] Error 1
make[1]: Leaving directory `/root/patch/firejail/src/firejail'
make: *** [src/firejail/firejail] Error 2
```

**Comment by kmk3** [comment]
(Offtopic)

Please see the following links for how to format code blocks in markdown:

* <https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks>
* <https://github.github.com/gfm/#fenced-code-blocks>

**Comment by kmk3** [comment]
> configure has no warning.

Please post the full output of that, including what arguments were passed to
`./configure`.

> ```
> make -C src/firejail/
> make[1]: Entering directory `/root/patch/firejail/src/firejail'
> gcc -ggdb  -O2 -DVERSION='"0.9.73"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fPIE -DPREFIX='"/usr/local"' -DSYSCONFDIR='"/usr/local/etc/firejail"' -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -DVARDIR='"/var/lib/firejail"'   -DHAVE_OUTPUT -DHAVE_X11 -DHAVE_PRIVATE_HOME     -DHAVE_USERTMPFS -DHAVE_DBUSPROXY  -DHAVE_GLOBALCFG -DHAVE_CHROOT -DHAVE_NETWORK -DHAVE_USERNS -DHAVE_FILE_TRANSFER  -DHAVE_SUID   -mindirect-branch=thunk -fstack-clash-protection -fstack-protector-strong -g -O2  -c env.c -o env.o
> env.c: In function ‘env_apply_list’:
> env.c:282:4: error: ‘for’ loop initial declarations are only allowed in C99 mode
>     for (unsigned int i = 0; i < num_items; i++)
>     ^
> env.c:282:4: note: use option -std=c99 or -std=gnu99 to compile your code
> make[1]: *** [env.o] Error 1
> ```

What is the output of `gcc --version`?

What is the distro and distro version?

**Comment by netblue30** [comment]
I'll fix them, thanks! I'll try to compile it with all -std=cXX versions.

**Comment by netblue30** [comment]
Also, what gcc version are you having there?

**Comment by netblue30** [comment]
Give it a try, should be fine now.

**Comment by kmk3** [comment]
I don't see any remaining obvious cases:

```console
$ git grep -I 'for *(int' -- '*.c'
$
$ git grep -I 'for *(unsigned' -- '*.c'
$
```

So closing as resolved.
