### ISSUE TITLE
running recoll in firejail

### ISSUE THREAD

**Issue by Rosika2** [netblue30/firejail#5807]
Hi all, :wave: 

I have a question about running `recoll` in firejail.

BTW: "whatis recoll" says: "user interface for the Recoll full text search system"

I see `firejail` doesn´t come with a dedicated recoll profile. So when running `recoll` in firejail it makes use of the _default profile_:

```
firejail recoll
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file

** Note: you can use --noprofile to disable default.profile **
[...]
```

O.K., that´s what I understand so far.

Now for my example:

I want `recoll` to search for a particular file. It finds it and comes up with the search result. It´s the text-file I was looking for. Here´s what the process tree looks like in `firetools`:

```
11823:rosika::firejail recoll 
    11824:rosika::firejail recoll 
        11827:rosika::/usr/bin/fish -c 'recoll' 
            11832:rosika::recoll 
```

Now: within the recoll GUI I have the chance of opening the text-file by double-clicking on "open".
In my case `gedit` opens the required text file, but _it doesn´t run within the firejail sandbox_:

 ```
ps aux | grep gedit
rosika     12739  9.3  1.4 761380 57600 ?        Sl   14:38   0:02 /usr/bin/gedit --gapplication-service
rosika     12874  0.0  0.0   9428  2284 pts/9    S+   14:38   0:00 grep --color=auto gedit
```

I was of the opinion that any process triggered by another process which is already running within firejail is also sandboxed. :thinking: 

Perhaps I´m missing something here. Can anybody help :question: 

Many thanks in advance and many greetings

Rosika :slightly_smiling_face: 

P.S.

my system: Linux Lite 6.2
firejail version 0.9.66

**Comment by kmk3** [comment]
> firejail version 0.9.66

Note that we do not maintain that version of firejail:

* <https://github.com/netblue30/firejail/blob/master/SECURITY.md>

Versions other than the latest usually have outdated profiles and may contain
bugs and security vulnerabilities that were fixed in later versions.

See also:

* <https://github.com/netblue30/firejail#installing>

**Comment by Rosika2** [comment]
@kmk3 : 

Thanks, Kelvin, for your answer.

Well, I installed firejail from the standard Ubuntu repositories, which Linux Lite makes use of, I guess.
I´ll add the firejail PPA in due course in order to get the latest version.

> Note that default.profile does not block dbus, which is one way to get around
> the sandbox restrictions.

Ah, that´s the explanation then.
Thanks for the link. I´ll try to create a profile for recoll with it. 

Many thanks for your help and many greetings
Rosika :slightly_smiling_face:
