### ISSUE TITLE
ssh: sftp fails in nautilus with GNOME gvfs 1.53+ (ControlMaster, ControlPath)

### ISSUE THREAD

**Issue by Saren-Arterius** [netblue30/firejail#5816]
### Description

Since GNOME gvfs 1.53+, the SSH client option `ControlMaster=auto` and `ControlPath=/run/user/$UID/gvfsd-sftp/%C` is used to mount SFTP. 

Since firejail did not whitelist `/run/user/$UID/gvfsd-sftp` by default, gvfs SFTP mount with nautilus will fail with a meaningless error message shown in UI, and gvfs binary spawned with `GVFS_DEBUG=1` will output the following log:

    sftp: Added new job source 0x5557c0a4a740 (GVfsBackendSftp)
    sftp: Queued new job 0x5557c0a54a40 (GVfsJobMount)
    sftp: spawn_ssh: ssh -oForwardX11 no -oForwardAgent no -oPermitLocalCommand no -oClearAllForwardings yes -protocol 2 -oNoHostAuthenticationForLocalhost yes -oControlMaster auto -oControlPath=/run/user/1000/gvfsd-sftp/%C -s {HOST} sftp 
    sftp: handle_login #1 initial_connection = 1 - user: (null), host: {HOST}, port: -1
    sftp: handle_login #1 - password_save: 0
    sftp: handle_login #1 - ret_val: 1
    sftp: stderr: Pseudo-terminal will not be allocated because stdin is not a terminal.
    sftp: stderr: unix_listener: cannot bind to path /run/user/1000/gvfsd-sftp/a1e578f57192356953828abeb0bb9df9b19ee10c.C5KhYALng3tYdUFE: No such file or directory
    sftp: send_reply(0x5557c0a54a40), failed=1 (Connection Failed)

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Prepare a SSH server or localhost
2. `ssh -o"ForwardX11 no" -o"ForwardAgent no" -o"PermitLocalCommand no" -o"ClearAllForwardings yes"  -o"NoHostAuthenticationForLocalhost yes" -o"ControlMaster auto" -o"ControlPath=/run/user/${UID}/gvfsd-sftp/test" -s {SSH_HOST} sftp`
3. The stderr gives `unix_listener: cannot bind to path /run/user/$UID/gvfsd-sftp/test.{RANDOM_STRING}: No such file or directory`, and SSH exits with error code 255

### Expected behavior

GVFS/SSHFS connects successfully

### Actual behavior

GVFS/SSHFS fail to connect because of firejail has not whitelisted the ControlPath specified by GVFS.

### Workaround/Solution
Create `/etc/firejail/ssh.local` with the following content

    whitelist ${RUNUSER}/gvfsd-sftp

**Comment by glitsj16** [comment]
Why not add it to `sftp.profile` instead?

**Comment by mirko** [comment]
> > Why not add it to `sftp.profile` instead?
> 
> Yes, that's probably better.

Tried adding it to `.config/firejail/sftp.local`-> doesn't work. Adding to `.config/firejail/ssh.local` does, though.

**Comment by phoenix-advance** [comment]
After trying out this elegant one liner solution, I get "Permission denied (publickey)." when SSHing via (gnome) terminal into another machine. Would regenerating keys fix this issue?
