### ISSUE TITLE
How to hide entire home directory except number of subdirectories

### ISSUE THREAD

**Issue by weeshy** [netblue30/firejail#583]
I'd like to hide from an application entire ${HOME} directory, but allow access to number of working directories, that lies inside the home, like ${HOME}/MyWorkDir and ${HOME}/MyCacheDir.

I've tried --private with --whitelist, but whitelist was ignored, I've got an empty home directory. I give another try to --blacklist=${HOME} and --whitelist=${HOME}/MyWorkDir, but whitelist was ignored again: I could not access specified directory that is inside a blacklisted path.

So, how it is supposed to configure firejail in that use case? Some of directories should be whitelisted as read-only weights a lot, so I could just copy them to another directory and go the way of full chroot.

**Comment by netblue30** [comment]
--whitelist does all the job by default. You don't need to add --blacklist or --private:
`````
$ firejail --whitelist=~/work --whitelist=~/bin
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 26261, child pid 26262

Child process initialized
$ ls -l
total 8
drwxr-xr-x  7 netblue netblue 4096 Apr  6 22:06 bin
drwxr-xr-x 20 netblue netblue 4096 Jun  9 21:57 work
$ 
`````

**Comment by weeshy** [comment]
That works fine, thanks for the information
