### ISSUE TITLE
Xephyr fails with chroot and net

### ISSUE THREAD

**Issue by h1z1** [netblue30/firejail#587]
I hope this is something silly I'm missing but for the life of me I cannot get Xephyr to properly start within a chroot and network isolation.  The server starts but nothing within the sandbox is able to run  just throws a generic error.   I fully expect it's something within the chroot I'm missing but I have no idea WHAT.   It works fine without --net.   Disabling the default profile, secomp, and everything else I could think of had no effect.   

This is what I'm trying:
firejail  --net=enp4s0 --x11=xephyr  --chroot=/srv/jails/desktop1 fluxbox

What doesn't really make sense is how the display variable is being set.  Shouldn't it be :0 if the display was truly isolated?

**Comment by netblue30** [comment]
Yes, that is a problem. Both --chroot and --net will result in no access to X11 socket. I'll have to fix it! Thanks for the bug.

> Shouldn't it be :0 if the display was truly isolated?

If you  see display :0, it means you  are running on the main X server without any isolation. For display I pick a number up to 1000.

**Comment by netblue30** [comment]
Fixed, give it a try.

**Comment by h1z1** [comment]
Bummer.. would that have any effect on sound as well (alsa)?  Anything I can do to help?   :)
