### ISSUE TITLE
"firecfg.conf" with list of disabled profiles

### ISSUE THREAD

**Issue by danielkrajnik** [netblue30/firejail#5874]
### Is your feature request related to a problem? Please describe.

Some programs [can't be made](https://github.com/netblue30/firejail/issues/4991) to work with firejail yet. Until a solution is found user needs to remove symlinks from `/usr/local/bin` to take them out of firejail. These symlinks however will be recreated on the next run of `fiirecfg --clean && firecfg`. If a list of "blacklisted" profiles stored in .config/firejail was read on each run of `firecfg` (to avoid creating them) instead that would be really helpful.

### Describe alternatives you've considered

[This script](https://github.com/netblue30/firejail/issues/3214#issuecomment-583841631) by rusty-snake could be used as a manual alternative, but it would be really helpful to have a native support.

**Comment by glitsj16** [comment]
Until someone implements such native support you can use [nojail](https://github.com/kugland/nojail). It is also available in the [AUR](https://aur.archlinux.org/packages/nojail/) for people who happen to run Arch Linux (based) OS.

**Comment by rusty-snake** [comment]
Related: #5874

There could be a `--no-user-profile-discovery` option.

If you start firecfg w/o sudo (e.g. pkexec) or use `sudo env -u SUDO_USER firecfg` you can get this behavior already because firecfg can then not discover your user (this will also affect firejail.login).

There are more alternatives from me 😁

**Comment by kmk3** [comment]
You're in luck, I started working on #2097 yesterday.

The implementation currently works, but there are some API considerations; I'll
post a draft PR later.

Closing in favor of #2097.

**Comment by danielkrajnik** [comment]
Oh wow, that's good to hear. Thank you for letting me know. I'm looking forward to see the PR.
