### ISSUE TITLE
VirtualBox profile does not work on Gentoo (with fix)

### ISSUE THREAD

**Issue by Frostbyte4664** [netblue30/firejail#5878]
### Description
VirtualBox prints `Could not find VirtualBox installation. Please reinstall.` and exits when run with the default profile on Gentoo.

### Steps to Reproduce
1. Install VirtualBox: `emerge app-emulation/virtualbox`
2. Run `firecfg`
3. Run `virtualbox`

### Expected behavior
VirtualBox launching and running normally.

### Actual behavior
Error message and exit.

### Behavior without a profile
VirtualBox launches correctly.

### Fix
This can be fixed by either appending `vbox` to the `private-etc` list or by running `INSTALL_DIR=/usr/lib64/virtualbox virtualbox`.

### Environment
- Gentoo GNU/Linux
- Firejail version 0.9.72

### Checklist
- [x] The issues is caused by firejail.
- [x] I can reproduce the issue without custom modifications.
- [x] The program has a profile.
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues.

**Comment by glitsj16** [comment]
Thank you for reporting this! I've opened #5880 so it will be fixed soonish in git and ready for the next release.
