### ISSUE TITLE
How do you unblacklist directories?

### ISSUE THREAD

**Issue by danielkrajnik** [netblue30/firejail#5889]
Apologies for not following the template again. How do you use `noblacklist` option? On my system it doesn't work at all - it does nothing whenever you point it to some folder. Programs keep complaining about programs not being available.

This is impossible to work with. Is there any simple or not so simple way to control this access?

Is there any way to tell you WHY a directory has been blacklisted? How do you debug this?

Sorry for sounding frustrated, but this always catches you in the middle of your everyday tasks.

Does firejail not work with btrfs? Or Archlinux?

**Comment by rusty-snake** [comment]
We have a lot arch userd, it is well tested there. For debugging you can use `--debug` and technical understanding.

For you noblacklist problem, start here: https://github.com/netblue30/firejail/wiki/Creating-Profiles#common-mistakes

**Comment by danielkrajnik** [comment]
Thanks, but sorry this doesn't work. As far as I remember noblacklist always gets overwritten - adding it to a local profile:

````
noblacklist /home/user/directory/to/pass
````
never works.

Is there no way to just say - please firejail pass through this path - don't let anything else override it. It's safe for programs to use it.

**Comment by danielkrajnik** [comment]
Sorry, I just saw your reply on the previous thread - the reason why noblacklist doesn't work may be, because it requires whitelist - however using whitelist blacklists everything else...

**Comment by danielkrajnik** [comment]
Thank you again for explaining. I finally started to be able to solve all problems with firejail.

The crucial command turned out to be for me `firejail --profile=<PROFILE-NAME>` . This accelerated debugging process tremendously.
