### ISSUE TITLE
xpra and private-dev

### ISSUE THREAD

**Issue by weeshy** [netblue30/firejail#589]
I've tried to run
`xpra --socket-dir=${HOME}/.firexpra start :39 --daemon=no --start=xterm` inside a firejail with `private-dev` and `private-etc passwd`

It stopped with following error:

> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> (EE) 
> Fatal server error:
> (EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
> (EE) 

Could I somehow add `/dev/tty0` to list of available `/dev` files or make xpra skip `parse_vt_settings phase`?

I've tried built-in `x11=xpra` feature, but it gives me some errors, so I decided to try start xpra manually

**Comment by weeshy** [comment]
The problems is that xpra really need /etc/xpra/xpra.conf, which is not duplicated as hardcoded default settings.

**Comment by netblue30** [comment]
You can whitelist /dev if you  need to:
`````
$ firejail --whitelist=/dev/tty0 --whitelist=/dev/null
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 11680, child pid 11681

Child process initialized
$ ls -l /dev
total 0
crw-rw-rw- 1 65534 65534 1, 3 Jun 17 11:39 null
crw--w---- 1 65534 tty   4, 0 Jun 17 11:39 tty0
$ 
`````
