### ISSUE TITLE
Support for File Managers

### ISSUE THREAD

**Issue by rekixex** [netblue30/firejail#590]
It would be convenient to have support for File Managers, which use full paths to start executables. Regarding AppArmor, when a PDF file is opened from the File Manager (Nautilus), Evince automatically starts sandboxed (if you put Evince profile in enforce mode). Firejail already includes profiles for many applications, which makes it very functional out-of-the-box. I think support for File Managers would make it more complete solution for application isolation. May I suggest to add it?

**Comment by reinerh** [comment]
One difference between apparmor and firejail is that apparmor is a kernel extension, while firejail runs completely in userspace. So for apparmor it is easy to isolate all applications automatically.
How should firejail do this, when the application is explicitely called directly (by absolute path) and no wrapper or symlink etc. is called?

**Comment by rekixex** [comment]
@reinerh I am aware of it. `sudo firecfg` is the closest we can get to isolate applications automatically.

**Comment by rekixex** [comment]
@reinerh I am aware of it. Probably difficult task, if at all possible. sudo firecfg is the closest we can get to isolate applications automatically.

**Comment by rekixex** [comment]
@reinerh I am aware of it. Probably difficult task, if at all possible. `sudo firecfg` is the closest we can get to isolate applications automatically.

**Comment by rekixex** [comment]
@reinerh I am aware of it. Probably a difficult task, if at all possible. `sudo firecfg` is the closest we can get to isolate applications automatically.

**Comment by rekixex** [comment]
@reinerh I am aware of that. Probably a difficult task, if at all possible. `sudo firecfg` is the closest we can get to isolate applications automatically.
