### ISSUE TITLE
With gocryptfs and securefs i don't can open any file with double-click in the mounted folder

### ISSUE THREAD

**Issue by KonoromiHimaries** [netblue30/firejail#5908]
### Description

With gocryptfs and securefs i don't can open any file with double-click on external program, like. mpv, ristretto, xarchiver and other in the mounted folder.

### Steps to Reproduce

_Steps to reproduce the behavior_

0. Install firejail, gocryptfs, yt-dlp and run `sudo firecfg`
1. Mount a folder with gocryptfs
2. Example. Run command `yt-dlp https://www.youtube.com/watch?v=aqz-KE-bpKQ` at the mounted directory
4. See error `cannot access profile file: yt-dlp.local`

### Expected behavior

Work

### Actual behavior

Not work

### Behavior without a profile

With `sudo firecfg --clean` work normally

### Additional context

https://github.com/rfjakob/gocryptfs/issues/767

### Environment

- Linux distribution and version arch fork latest
- Firejail version latest

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

Don't need

**Comment by rusty-snake** [comment]
Duplicated of #3798

**Comment by rusty-snake** [comment]
Summary of the workarounds: https://github.com/netblue30/firejail/issues/3798#issuecomment-1004031394
