### ISSUE TITLE
VLC does not appear in GNOME Settings app when trying to set default media player  

### ISSUE THREAD

**Issue by MrQvest** [netblue30/firejail#5925]
### Description

VLC, when configured with `sudo firecfg`, disappears from GNOME Settings app when trying to set a default media or music player

### Steps to Reproduce

1. Run `sudo firecfg` and leave its default configuration
2. Open GNOME Settings Default Apps panel 
3. VLC is nowhere to be found when trying to set it as default

### Expected behavior

1. Run `sudo firecfg` and leave its default configuration
2. Open GNOME Settings Default Apps panel
3. VLC should be listed together with other apps that also have a firejail configuration. E.g. Firefox
 
### Additional context

If the `.desktop` file located in `~/.local/share/applications/` is deleted, VLC appears normally in GNOME Settings App 

### Environment

- Fedora Linux 38
- firejail version 0.9.72

### Checklist

- [x] The issue is caused by firejail
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
- [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
LC_ALL=C firejail /usr/bin/vlc    
Reading profile /etc/firejail/vlc.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-player-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 14996, child pid 15000
6 programs installed in 83.05 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Child process initialized in 211.84 ms
VLC media player 3.0.19 Vetinari (revision )
[000056000a258400] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.

(vlc:13): dbind-WARNING **: 21:31:46.248: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[000056000a33b6b0] qt interface error: Unable to load extensions module
[000056000a2f3b00] main playlist: playlist is empty
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

https://gist.github.com/MrQvest/7b07fa02e99919980c2766c840892f37

</p>
</details>

**Comment by glitsj16** [comment]
Can you post both vlc.desktop files here please? Would be interesting to see what firecfg did to it exactly.

**Comment by MrQvest** [comment]
```
# converted by firecfg
[Desktop Entry]

[...]

Exec=vlc --started-from-file %U
TryExec=/usr/bin/vlc
Icon=vlc
Terminal=false
Type=Application
Categories=AudioVideo;Player;Recorder;
```

Removing `--started-from-file` does not seem to add it as an entry in GNOME Settings unfortunately

**Comment by rusty-snake** [comment]
Is this a firejail bug or  a GNOME bug? I.e. if you copy the .desktop from use/share to your home, does it work?



> There is a recent PR that implements https://github.com/netblue30/firejail/pull/5876 so you can create persistent overrides for problems like this.

#5245

**Comment by MrQvest** [comment]
I copied `vlc.desktop` from `/usr/share/applications/` over to `~/.local/share/applications/`
It results in the exact same outcome. Both files are exactly the same upon opening and comparing them

**Comment by rusty-snake** [comment]
Sounds like a GNOME issue. Did you tried to logout and login again?

**Comment by MrQvest** [comment]
Yeah. Just did that and it still does not appear in the settings

**Comment by MrQvest** [comment]
If this has nothing to do with firejail I guess I'll just delete the .desktop file for now. Do you know how I can open an issue to the GNOME team regarding this?

**Comment by rusty-snake** [comment]
The issue tracker for the GNOME settings UI can be found at https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues. However AFAIK GNOME recommends that you open issues downstream (https://bugzilla.redhat.com/bugzilla/) if you installed it from there.
