### ISSUE TITLE
Limit the memory size used by the jailed process

### ISSUE THREAD

**Issue by vporton** [netblue30/firejail#593]
We need to limit the memory size used by the jailed process, so that a hacked would not run out of memory and swap.

**Comment by reinerh** [comment]
`ulimit`?

**Comment by vporton** [comment]
On Fri, 2016-06-24 at 10:02 -0700, Reiner Herrmann wrote:
> ulimit?
> 
> 
> 
>   > 
>   > 

> 
> 

> 

I am aware about ulimit, but this will be probably a little more
efficient with single `firejail` executable than running `ulimit
firejail` composed from two commands.

**Comment by reinerh** [comment]
It's probably a bit more convenient, I agree, but duplicating functionality already provided by other means also increases the complexity of firejail.

**Comment by chiraag-nataraj** [comment]
Another way is to assign the process to a cgroup and set limits on the cgroup (which you might be able to do in a config file somewhere).

**Comment by netblue30** [comment]
Yes, cgroup is the way to go. Set up a control group and pass it to the sandbox using --cgroup.
