### ISSUE TITLE
gramps.profile: add the new (xdg) config directory

### ISSUE THREAD

**Issue by paolomi** [netblue30/firejail#5932]
In gramps.profile there is the "old" config dir ${HOME}/.gramps and it cannot open my db because it is in the "new" xdg config dir ${HOME}/.config/gramps

I've changed that in /etc/firejail/gramps.profile and my problem has been fixed.

I don't know if the old directory in the profile must remain for compatibility reasons, it's a discussion for you developers, but at least the new config directory should be added. Thanks a lot.

**Comment by glitsj16** [comment]
Thanks for the info! We'll keep the old one for now.

I'll open a PR to add the new location. If you don't want to see the old one anymore in a next release, you can add the below to a gramps.local:

```sh
$ cat ~/.config/firejail/gramps.local
ignore mkdir ${HOME}/.gramps
```

Cheers
