### ISSUE TITLE
Firejail needs root to display version(?!)

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#595]
Steps to reproduce:
1) `firejail bash`
2) `firejail --version`
Instead of getting the version, I get
````
Error: cannot switch euid to root
Error: cannot switch euid to root
Error: cannot switch euid to root
Error: the sandbox is not setuid root
````

**Comment by netblue30** [comment]
Did you install it SUID?
`````
$ ls -l /usr/bin/firejail
-rwsr-xr-x 1 root root 1338184 Jun 24 11:50 /usr/bin/firejail
`````

**Comment by chiraag-nataraj** [comment]
````
$ls -lh /usr/bin/firejail
-rwsr-xr-x 1 65534 65534 295K Jun 14 19:20 /usr/bin/firejail
````
Yup. (This is within the jail, hence the different UID and GID).

I think I wasn't clear - this is *within* the jail (not outside).

**Comment by netblue30** [comment]
Not a problem, the jail actually will prevent a new jail for starting - firejail is a SUID executable, and SUID executables are disabled.

**Comment by chiraag-nataraj** [comment]
Huh...okay. I realized that, but it's interesting that it would have to set the UID and GID to root before it even did the argument parsing (which would tell it that it just has to display the version).

**Comment by netblue30** [comment]
Good point! I'll have to fix it.

**Comment by chiraag-nataraj** [comment]
:smile:

**Comment by netblue30** [comment]
Fixed, thanks for the bug.
