### ISSUE TITLE
VSCodium: Opening code is not possible

### ISSUE THREAD

**Issue by marek22k** [netblue30/firejail#5990]
### Description

Opening code is not possible in VSCodium

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Run in bash `LC_ALL=C firejail /usr/bin/codium` (`LC_ALL=C` to get a consistent
   output in English that can be understood by everybody)
2. Open a file, e. g. `/home/marek/Arduino/xinetd/platformio.init`
3. Scroll down to `The editor could not be opened due to an unexpteted error: Unable to read file '/home/marek/Arduino/xinetd/platformio.init` (NoPermissions (FileSystemError): Error: EACCES: permission denied, stat '/home/marek/Arduino/xinetd/platformio.ini')`

### Expected behavior

File can be opened.

### Actual behavior

File cannot be opened.

### Behavior without a profile

File can be opened.

### Environment

- Parrot OS (Debian-based)

```
firejail version 0.9.72

Compile time support:
	- always force nonewprivs support is disabled
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file transfer support is enabled
	- firetunnel support is disabled
	- IDS support is enabled
	- networking support is enabled
	- output logging is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-cache and tmpfs as user enabled
	- SELinux support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /usr/bin/codium</code></summary>
<p>

```
$LC_ALL=C firejail /usr/bin/codium
Reading profile /etc/firejail/codium.profile
Reading profile /etc/firejail/vscodium.profile
Reading profile /etc/firejail/code.profile
Reading profile /etc/firejail/allow-common-devel.inc
Reading profile /etc/firejail/electron.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 23597, child pid 23598
Child process initialized in 49.94 ms

Parent is shutting down, bye...
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /usr/bin/codium</code></summary>
<p>

https://gist.github.com/marek22k/27d165ce082954678745178dcb7e2bad

</p>
</details>

**Comment by glitsj16** [comment]
Thank you for reporting.

Easy fix:

```sh
$ cat ~/.config/firejail/allow-common-devel.local
noblacklist ${HOME}/.arduino15
noblacklist ${HOME}/Arduino
```

If that indeed fixes it, can you open a PR?

**Comment by marek22k** [comment]
It works. I have created a PR.
