### ISSUE TITLE
Leave `pipewire` group along with `audio` group if logind is absent.

### ISSUE THREAD

**Issue by amano-kenji** [netblue30/firejail#5992]
### Description

Currently, if `noroot` and `nogroups` are present without `nosound` and logind is absent, `audio` group remains, but `pipewire` groups doesn't remain. `pipewire` group is important for giving realtime priority to pipewire clients.

**Comment by kmk3** [comment]
> Currently, if `noroot` and `nogroups` are present without `nosound` and
> logind is absent, `sound` group remains, but `pipewire` groups doesn't
> remain. `pipewire` group is important for giving realtime priority to
> pipewire clients.

What distribution and firejail version?

Do you mean the `audio` group or is there an actual `sound` group?

I don't think there is anything done for the latter in the code.

**Comment by amano-kenji** [comment]
I fixed the typos.
