### ISSUE TITLE
Cannot blacklist ${HOME}/.config/firejail

### ISSUE THREAD

**Issue by boltronics** [netblue30/firejail#6]
I was surprised there was no line in the default configuration like so:

```blacklist ${HOME}/.config/firejail```

Without that, an untrusted app could modify its own firejail profile and terminate. When it is relaunched (either automatically via a service management daemon or via user intervention), it could run with elevated privileges.

Even more surprising, manually adding the entry does nothing - the line is silently ignored.

**Comment by netblue30** [comment]
It seems to be working for me:

$ $ cat ttt
blacklist ${HOME}/.config/firejail
$ firejail --profile=ttt
Reading profile ttt
Parent pid 24098, child pid 24099
Child process initialized
$ ls ~/.config/firejail
ls: cannot open directory /home/netblue/.config/firejail: Permission denied
$

**Comment by boltronics** [comment]
I just tried with the latest from git, and this is still a problem for me, so I digged deeper.

Since I'm using GNU Stow to manage my dotfiles, ~/.config/firejail is actually a symlink. Apparently firejail doesn't support following symlinks, which means many of the default profiles aren't protecting my setup at all. This is a worry.

I believe firejail should be resolving the actual location and blocking that (where ```blacklist ${HOME}/.config/firejail``` would effectively be equivalent to ```blacklist $(readlink -f ${HOME}/.config/firejail)```.

Please see this link for more information on how it could be done in C:
https://stackoverflow.com/questions/7665/how-to-resolve-symbolic-links-in-a-shell-script

I think this can now be re-opened, or otherwise let me know if you would prefer me to open a new issue.

**Comment by pmillerchip** [comment]
@boltronics I currently can't reproduce this, I tried blacklisting a symlinked directory and it works fine. It follows the symlink and blocks what it points to. We'd need to know what you're seeing on your machine. Can you please let us know:

1. The command you run to test whether the blocking is working
2. The output you see from the command, that tells you firejail isn't blocking properly
3. What you would expect to see if firejail was working correctly.

**Comment by boltronics** [comment]
@pmillerchip 
Strange. I can't see any way to avoid it. :)

1 and 2 - commands and output:
```
boltron@laptop:~$ ls -ld .config/firejail
lrwxrwxrwx 1 boltron boltron 38 Aug 10 00:38 .config/firejail -> ../stow/firejail/.config/firejail
boltron@laptop:~$ cat ~/.config/firejail/bash.profile 
blacklist /home/boltron/.config/firejail
boltron@laptop:~$ firejail --profile=${HOME}/.config/firejail/bash.profile bash
Reading profile /home/boltron/.config/firejail/bash.profile
Parent pid 30569, child pid 30570
Child process initialized
[boltron@laptop ~]$ ls -l .config/firejail/bash.profile
-rw-r--r-- 1 boltron boltron 40 Aug 16 05:17 .config/firejail/bash.profile
[boltron@laptop ~]$
```

3 - expected output:
```
boltron@laptop:~$ ls -ld .config/firejail
lrwxrwxrwx 1 boltron boltron 38 Aug 10 00:38 .config/firejail -> ../stow/firejail/.config/firejail
boltron@laptop:~$ cat ~/.config/firejail/bash.profile 
blacklist /home/boltron/.config/firejail
boltron@laptop:~$ firejail --profile=${HOME}/.config/firejail/bash.profile bash
Reading profile /home/boltron/.config/firejail/bash.profile
Parent pid 30569, child pid 30570
Child process initialized
[boltron@laptop ~]$ ls -l .config/firejail/bash.profile
ls: cannot access .config/firejail/bash.profile: Permission denied
[boltron@laptop ~]$
```

**Comment by pmillerchip** [comment]
OK I found (and fixed) the problem! @boltronics had a relative symlink (i.e. it started with `../`) and firejail wasn't handling that right.

@netblue30 : I've made a pull request to fix this, it just calls the `realpath` standard library function to do all the hard work for us, and it fixes the problem.

@boltronics : Please compile firejail from the `symlink-bug` branch of my firejail repo here: https://github.com/pmillerchip/firejail.git ...and let me know if it fixes it for you.

**Comment by boltronics** [comment]
@pmillerchip Thanks for the quick patch! It's definitely making a difference, but not the right kind of difference. :)

Here's what I get:
```
abolte@ettin:~$ ls -ld .config/firejail
lrwxrwxrwx 1 abolte abolte 38 Aug 10 00:38 .config/firejail -> ../.dotfiles/firejail/.config/firejail
abolte@ettin:~$ cat ${HOME}/.config/firejail/bash.profile
blacklist /home/boltron/.config/firejail
abolte@ettin:~$ firejail --profile=${HOME}/.config/firejail/bash.profile bash
Reading profile /home/abolte/.config/firejail/bash.profile
Parent pid 10719, child pid 10720
Warning: /home/boltron/.config/firejail is an invalid file, skipping...
Child process initialized
[abolte@ettin ~]$ ls -l .config/firejail/bash.profile
-rw-r--r-- 1 abolte abolte 41 Aug 16 14:30 .config/firejail/bash.profile
[abolte@ettin ~]$ 
```

**Comment by pmillerchip** [comment]
That's great news, glad it works for you. The pull request is up, so hopefully @netblue30 will merge it soon.
