### ISSUE TITLE
Causes mate-volume-control to segfault and audio issues

### ISSUE THREAD

**Issue by Korons** [netblue30/firejail#600]
Edit: I'm running Ubuntu mate 16.04

Whenever I run a program in firejail `mate-volume-control` segfaults (unless ran with firejail) and all non-firejailed programs (Aside from mpv) lose the ability to play sound.

For example I started firefox in firejail and now running `mate-volume-control` outputs 

`shm_open() failed: No such file or directory
shm_open() failed: No such file or directory
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
(mate-volume-control:6721): libmatemixer-alsa-WARNING **: Failed to open ALSA control for default: Connection refused
(mate-volume-control:6721): GLib-CRITICAL **: g_source_remove_poll: assertion '!SOURCE_DESTROYED (source)' failed
Segmentation fault (core dumped)`

Trying to start VLC without firejail outputs

`shm_open() failed: No such file or directory
[0000000000845d18] pulse audio output error: PulseAudio server connection failure: Protocol error
[000000000076a148] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
shm_open() failed: No such file or directory
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
[0000000000845d18] alsa audio output error: cannot open ALSA device "default": Connection refused`

And trying to play a video in VLC outputs the following error

`Audio output failed:
The audio device "default" could not be used:
Connection refused.`

However all programs play audio fine if ran with firejail.

**Comment by Fred-Barclay** [comment]
G'day Korons. :) A couple of questions:

1. Did you ever run `firecfg`?
2. What distro and MATE version?
3. I noticed that Pulse Audio complains in both of your error messages. Have you tried [this](https://firejail.wordpress.com/support/known-problems/#pulseaudio)?

**Comment by Korons** [comment]
1) returns `firecfg: command not found` 
2) Ubuntu 16.04. The mate verison is 1.12.1
3) That fixed it. Thanks!

**Comment by Fred-Barclay** [comment]
No worries mate. :) LMDE MATE here myself.
firecfg was added in the last firejail release (0.9.40). If you're using the firejail from Ubuntu's repos then that's v. 0.9.38 (I think) and firecfg wasn't part of it.
