### ISSUE TITLE
text-editors: cannot access all text files in the user home

### ISSUE THREAD

**Issue by ilikenwf** [netblue30/firejail#6002]
Sometimes, packages require edits, sometimes those are larger than I'd prefer to use with vim.

I question the use in even firejailing geany at this point, though...

**Comment by glitsj16** [comment]
~/.cache/yay isn't blacklisted anywhere AFAICT, so a noblacklist on that path won't do anything. Probably the `private-cache` in geany.profile needs to be ignored to do what you want.

> I question the use in even firejailing geany at this point, though...

I can see why you'd question this, IMO rightly so. If memory serves we've discussed dropping GUI editors from being auto-firejailed via firecfg at some point. Can't track any references on the topic right now but we might have to reconsider it - again...

**Comment by kmk3** [comment]
Relates to:

* #504
