### ISSUE TITLE
add gomuks

### ISSUE THREAD

**Issue by jtrv** [netblue30/firejail#6010]
add a profile for https://github.com/tulir/gomuks

**Comment by rusty-snake** [comment]
You don't to to open issues before doing a PR just to have a issue.

If you have bigger changes (to the code) that needs discussion before implementing, then.

**Comment by kmk3** [comment]
> You don't to to open issues before doing a PR just to have a issue.

Yes, please avoid opening issues for new profile requests.

See also:

* <https://github.com/netblue30/firejail/blob/master/CONTRIBUTING.md>
