### ISSUE TITLE
whitelist ${HOME}/Documents is not working

### ISSUE THREAD

**Issue by rdbeni0** [netblue30/firejail#6011]
hi, 
i am trying to access file:

file:///home/rdbeni0/Documents/html/index.html

and i put in my ~/.config/firejail/brave.local :
```
whitelist ${HOME}/Documents/html
whitelist ${DOCUMENTS}/html
whitelist ${DOCUMENTS}

```

and nothing is working: `Your file couldn’t be accessed` via brave.

This is full command:
```
$ firejail brave
Reading profile /etc/firejail/brave.profile
Reading profile /home/rdbeni0/.config/firejail/brave.local
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 21783, child pid 21784
(...)

```
Please also note that when i have :
```
whitelist ${DOCUMENTS}/html
(or similar path with ${DOCUMENTS}/something/something )
```

then output is:

```
Reading profile /etc/firejail/brave.profile
Reading profile /home/rdbeni0/.config/firejail/brave.local
Error: "${DOCUMENTS}/html" is an invalid filename: rejected character: "{"
```

in that case, how can I add whitelist for **file:///home/rdbeni0/Documents/html/index.html**?

OS: latest Arch Linux with KDE and wayland

**Comment by rusty-snake** [comment]
> Error: "${DOCUMENTS}/html" is an invalid filename: rejected character: "{"

#2359

> how can I add whitelist for file:///home/rdbeni0/Documents/html/index.html?

1. Check `--debug` output.
2. Check `firejail --profile=brave ls ~/Documents`. What does it say. ENOENT or EACCES.

==> You have to `noblacklist ${DOCUMENTS}`

**Comment by rdbeni0** [comment]
> > Error: "${DOCUMENTS}/html" is an invalid filename: rejected character: "{"
> 
> #2359
> 
> > how can I add whitelist for file:///home/rdbeni0/Documents/html/index.html?
> 
> 1. Check `--debug` output.
> 2. Check `firejail --profile=brave ls ~/Documents`. What does it say. ENOENT or EACCES.
> 
> ==> You have to `noblacklist ${DOCUMENTS}`

i added to the ~/.config/firejail/brave.local :
```
noblacklist ${DOCUMENTS}
```
and 
```
rdbeni0 $ firejail --profile=brave ls ~/Documents
Reading profile /etc/firejail/brave.profile
Reading profile /home/rdbeni0/.config/firejail/brave.local
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 23966, child pid 23967
Warning: cleaning all supplementary groups
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Child process initialized in 133.78 ms
ls: cannot access '/home/rdbeni0/Documents': No such file or directory
```

via browser is the same - access denied

please also note that i am using apparmor (this integration with apparmor is enabled).

**Comment by rusty-snake** [comment]
Then check `--debug` output or post it (using details-summary).

**Comment by rdbeni0** [comment]
well, output is to big. Thanks for you help

I made workaround with combination of hard/soft, something like that:
```
ln -f ~/Documents/html/* ~/.local/share/html/
```
and i added rule **whitelist ${HOME}/.local/share/html**
and it started working

something somewhere is broken with **~/Documents/<here>**, but don't have time to manage it.
Let me close this topic
