### ISSUE TITLE
touch/mkfile profile option (like mkdir)

### ISSUE THREAD

**Issue by rahiel** [netblue30/firejail#604]
In reference to issue #188, I saw the handy "mkdir" profile command that creates directories if they don't exist. Would it be helpful to have an equivalent for files, like `touch`? Then firejail can create the files, whitelist them and then the sandboxed program can write to it.

**Comment by netblue30** [comment]
This is a very good idea, I'll put it in, thanks!

**Comment by rahiel** [comment]
This was added in https://github.com/netblue30/firejail/commit/0838606e623fc11fac5fd8db8b197d63f3e21f32, thanks.

**Comment by netblue30** [comment]
Yes, I put it in yesterday. I am still doing some tests on it, but it should be fine.
