### ISSUE TITLE
nosound causes private-dev

### ISSUE THREAD

**Issue by weeshy** [netblue30/firejail#609]
main.c, line number 1467

```
else if (strcmp(argv[i], "--nosound") == 0) {
     arg_nosound = 1;
     arg_private_dev = 1;
}
```

**Comment by netblue30** [comment]
I'll bring in a fix, thanks!

**Comment by weeshy** [comment]
The same is under profile.c so it seems like a feature not bug. But private-dev conflicts with whitelist, so I was forced to patch firejail to work with both nosound and whitelist.

**Comment by netblue30** [comment]
No, it was supposed to be temporary until I figured out what devices under /dev are sound devices. I'll bring in a fix shortly. I will also add the sound devices to --private-dev.

**Comment by netblue30** [comment]
/dev/snd included in private-dev list.
