### ISSUE TITLE
userspace driver proxy for kernel managed by firejail

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#6093]
https://www.usenix.org/legacy/event/atc10/tech/slides/boyd-wickizer.pdf

https://people.csail.mit.edu/nickolai/papers/boyd-wickizer-sud.pdf

This academic white paper is wonderful and a nice solution for reducing attack surface of drivers inside Linux.

Thanks and

Best regards

**Comment by rusty-snake** [comment]
Out of scope.
