### ISSUE TITLE
Sandbox missing from chromium-browser-privacy.profile

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#6097]
**firejail version:** 0.9.72
**OS:** Debian 12
**Profile:** [chromium-browser-privacy.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/chromium-browser-privacy.profile)

I'm using firejail to run an AppImage of Ungoogled Chromium, which can be downloaded here:
https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/

Specifically, I've download this is the exact file/version:
https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/119.0.6045.123-1

I'm running this AppImage with the following command:
firejail --appimage --profile=/etc/firejail/chromium-browser-privacy.profile /home/user/apps/ungoogled-chromium_119.0.6045.123-1.1.AppImage

Upon running this command, after the browser launches, press **ctrl-o**. A file dialog will appear, and **you can navigate to any file on your computer**.

I typically expect firejail profiles to sandbox web browsers, but this profile is not sand-boxed.

**Comment by rusty-snake** [comment]
> profile is not sand-boxed

It is. What you see is the file picker of your Desktop Environment (specifically the xdg-desktop-portal Documents portal implementation)

**Comment by Lonniebiz** [comment]
In Firefox, or LibreWolf, if you go to alt > File > Open, the sandbox doesn't even allow navigation outside of the sandbox.

In Ungoogled Chromium, you can navigate anywhere, but if you try to open a file outside of the sandbox it fails.

So, the reason for this is that Chromium doesn't have its own file picker? Hitting ctrl-o is using your desktop's file picker (which is not sandboxed). It can navigate anywhere, but cannot share with Chromium anything that's outside of the sandbox.

I guess LibreWolf has its own file picker built-in, and that one can't even navigate out of the sandbox.

Is this the correct understanding? @rusty-snake

**Comment by rusty-snake** [comment]
In short yes.

- You can configure Firefox and Firefox.profile to geht the same behaviuor.
- It fails to open because the Portal assumes it has access. If x-d-p would support firejail, it would work (dynamically grant permission like in firejail).

**Comment by Lonniebiz** [comment]
@rusty-snake You mentioned that the Firefox.profile can be configured to exhibit the same behavior. How?

I'd specifically like to try that in [LibreWolf](https://librewolf.net/) to address [this issue I have with its built-in file picker](https://gitlab.com/librewolf-community/browser/appimage/-/issues/18). Thanks for the information, and for being such a good shepherd of firejail. I really appreciate it.

**Comment by rusty-snake** [comment]
Allow dbus access to `org.freedesktop.Portal.*`, maybe ignore noroot and search on about:config for Portal to find the relevant pref.

**Comment by rusty-snake** [comment]
FF pref: `widget.use-xdg-desktop-portal.file-picker=1`
