### ISSUE TITLE
firejail: fs_lib.c:56: find_in_path: Assertion \`geteuid() != 0' failed

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#6113]
Several apps show breakage when running via firejail from git master. Here's an example using gsettings, but I've seen the same bug on several other profiles. Bisecting points to https://github.com/netblue30/firejail/commit/407c05ebefe23e725f858b6170b3e52659e044a2.

```sh
$ firejail --quiet /usr/bin/gsettings get org.gnome.shell disable-user-extensions
firejail: fs_lib.c:56: find_in_path: Assertion \`geteuid() != 0' failed
Error: proc 64096 cannot sync with peer: unexpected EOF
Peer 64097 unexpectedly killed (Segmentation fault)
```

 All's well again when I build firejail while reverting this commit:

```sh
$ firejail --quiet /usr/bin/gsettings get org.gnome.shell disable-user-extensions
false
```

Can anyone reproduce?

**Comment by kmk3** [comment]
> Several apps show breakage when running via firejail from git master. Here's
> an example using gsettings, but I've seen the same bug on several other
> profiles. Bisecting points to
> [407c05e](https://github.com/netblue30/firejail/commit/407c05ebefe23e725f858b6170b3e52659e044a2).
> 
> ```shell
> $ firejail --quiet /usr/bin/gsettings get org.gnome.shell disable-user-extensions
> firejail: fs_lib.c:56: find_in_path: Assertion \`geteuid() != 0' failed
> Error: proc 64096 cannot sync with peer: unexpected EOF
> Peer 64097 unexpectedly killed (Segmentation fault)
> ```

> Can anyone reproduce?

Cannot reproduce on 8f55f6c9a:

```console
$ firejail --quiet /usr/bin/gsettings get org.gnome.shell disable-user-extensions
No such schema “org.gnome.shell”
$ firejail --quiet /usr/bin/gsettings --version
2.78.1
```

Does it still happen when ignoring all .local files?

**Comment by rusty-snake** [comment]
We have private-lib disabled by default, correct?

**Comment by glitsj16** [comment]
> We have private-lib disabled by default, correct?

That's it, nice catch! I do enable `private-lib` in firejail.config. When I disable it, things no longer break with https://github.com/netblue30/firejail/commit/407c05ebefe23e725f858b6170b3e52659e044a2.

Even though I have a workaround now, it doesn't make much sense to allow users to override defaults (e.g. enabling private-lib) and subsequently break that. Slightly preoccupied with hardware changes right now, but I'll dig through the code and the xauth commit again later on. Would be nice if it could be implemented without breaking anything.

**Comment by chestnykh** [comment]
Should we perform the `geteuid() != 0` check? Why it is needed?

**Comment by rusty-snake** [comment]
Because search in path with elevated privileges would be a security vulnerability (information leak).

If you code in a suid binary you always have to ask your self "what evil could be done with it?". Even if it is a dead simple function like find_in_path or file_exists, ....

**Comment by glitsj16** [comment]
I have a patch that performs search in path with EUID_USER() instead of EUID_ASSERT() when private-lib is enabled:

```sh
$ cat 6113-bugfix.patch

--- a/src/firejail/fs_lib.c
+++ b/src/firejail/fs_lib.c
@@ -53,7 +53,11 @@
 }

 char *find_in_path(const char *program) {
+#ifdef HAVE_PRIVATE_LIB
+	EUID_USER();
+#else
 	EUID_ASSERT();
+#endif
 	if (arg_debug)
 		printf("Searching $PATH for %s\n", program);

@@ -78,6 +82,9 @@
 			free(dup);
 			return fname;
 		}
+#ifdef HAVE_PRIVATE_LIB
+	EUID_ROOT();
+#endif

 		free(fname);
 		tok = strtok(NULL, ":");

```

BIG DISCLAIMER: is it safe/wise to implement it like this?

**Comment by rusty-snake** [comment]
We disable private-lib via firejail.global by default, we don't?

**Comment by glitsj16** [comment]
> We disable private-lib via firejail.global by default, we don't?

@rusty-snake Correct, we do so via firejail.config yes. Personally I do enable it there, and during ./configure obviously. If that's a valid use case, we should fix the xauth commit IMO. You asked this before in this thread. Can you elaborate please?
