### ISSUE TITLE
Release Notes and/or Wiki 0.9.58.* & 0.9.56-LTS inconsistencies

### ISSUE THREAD

**Issue by peter-kehl** [netblue30/firejail#6114]
1. https://firejail.wordpress.com/download-2/release-notes is mostly in the most-recent-to-oldest order, except for:
 - firetools (0.9.58) baseline; urgency=low
 - firejail (0.9.56-LTS) baseline; urgency=low
 - firejail (0.9.58.2) baseline; urgency=low

2. The above > `firejail (0.9.56-LTS) baseline; urgency=low` reads: "command line options removed:" ..."--rlimit*". However, https://github.com/netblue30/firejail/wiki/Comparison-of-firejail-and-systemd's-hardening-options#resource-limits still lists "rlimit*".

3. Please clarify if "--rlimit*" and other removals apply to LTS only, or to any newer version.

**Comment by kmk3** [comment]
> Important
> 
> https://firejail.wordpress.com/ (accessed on 2023-12-02; News > June 2022 –
> released Firejail 0.9.70.)
> 
> > **Retired Firejail LTS version.** The latest LTS has the same –join
> > problem, and it will be replaced with something different in the near
> > future.

To add to that: The "LTSbase" branch hasn't been updated since commit c06212591
("0.9.56.2 released", 2019-06-05), which is also where the "0.9.56.2" tag
points to.

And since commit d1acb31c9 ("compile time: enable LTS", 2021-02-28) / version
0.9.66 there is the `--enable-lts` configure option.

So presumably the aforementioned replacement would be to build from the current
stable version (currently 0.9.72; see SECURITY.md) with `--enable-lts`.

**Comment by peter-kehl** [comment]
As a want-to-be user, I come across https://firejail.wordpress.com/download-2/release-notes and https://firejailtools.wordpress.com/release-notes and the facts number 1. - 3. reported in the 1st comment here, and I'm confused as to

- why are there those two "Release Notes", with the exact same titles,
- why a lower version `0.9.58.2` is released after a higher version `0.9.58`, with no comment about this
- why a parameter was removed in an LTS, yet it's documented in Wiki with no comment about its future/stability
- why would I have to dig in web archives for this
- why all the above would be left as-is, so that more people get confused.

**Comment by rusty-snake** [comment]
> why would I have to dig in web archives for this

Because it got retired and therefore removed from the website.

> why all the above would be left as-is, so that more people get confused.

Because @netblue30 is the only person with write rights on WordPress.

**Comment by peter-kehl** [comment]
As a workaround, would it be OK to append "(unstable feature)" or "(work-in-pogress feature)" (or whatever you suggest) to non-LTS features mentioned in Wiki? I'm willing to append those in my clone of the Wiki.

Any other such features other than `chroot|overlay|rlimit|cgroup|private-bin|private-lib`?

`grep -r -i -E "chroot|overlay|rlimit|cgroup|private-bin|private-lib"` reports them mostly/most standing out in https://github.com/netblue30/firejail/wiki/Comparison-of-firejail-and-systemd's-hardening-options#resource-limits and https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/commit/db09546f2946c921da1b07d9d3569c287238989b
