### ISSUE TITLE
cannot stat '.etc/Telegram.profile': No such file or directory

### ISSUE THREAD

**Issue by mmetak** [netblue30/firejail#612]
There are two lines for telegram in Makefile and my guess is that the other one shouldn't be there? ;)

**Comment by Fred-Barclay** [comment]
One is lower-cased, the other is upper-cased. I **think** they both belong, considering that there are also two (identical) telegram profiles in etc/, one which is lower-cased and the other which is (you guessed it!) upper-cased.

The two profiles in etc/ can probably be linked so thanks for pointing this out!

**Comment by netblue30** [comment]
All fixed, thanks @Fred-Barclay

**Comment by Fred-Barclay** [comment]
No worries mate. :smile:
