### ISSUE TITLE
whitelisting nc does not work with disable-common.inc

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#6135]
With whitelisting above nc path firejail doesnt start with default.profile like executing firejail.

Sandbox not starting. 

Only when i outcomment #whitelist fullpath/nc it will start.

Workaround is outcommenting

https://github.com/netblue30/firejail/blob/56391cf84fc6b4aaa2610deb32b31fc904ceb840/etc/inc/disable-common.inc#L536

I did whitelist fullpath after include disable-common.inc

And before i did 
noblacklist fullpath of nc
whitelist fullpath of nc

Soo bug appears.

**Comment by kmk3** [comment]
Basic debugging information is missing; please follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>

**Comment by kmk3** [comment]
Closing as abandoned.
