### ISSUE TITLE
private-etc exceeds 500MB limit due to large files symlinked in /etc/alternatives

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#6137]
I'm on Debian, i installed a soundfont (fluid-soundfont-gm), that is 150MB. That soundfont uses the update-alternatives system, so it shows up in the etc as a symlink, for compatibility reasons it's linked twice. private-etc copies both of them, that's 300MB... so the 500MB limit is often hit.

Then it seams that it simply ignores what ever exceeds the limit but still runs the app, so the end result is random chaos for any profile that uses private-etc.

At the very least, firejail should not try to run if it loads part of what it was expected to load.

**Comment by rusty-snake** [comment]
Note that there was recently a change that might fixes this in the next release. https://github.com/netblue30/firejail/pull/5957
