### ISSUE TITLE
PulseAudio 8.0 and Firejail do not work toghether

### ISSUE THREAD

**Issue by igor2x** [netblue30/firejail#615]
Hi,
I have a trouble of using Firejail with PulseAudio. Like I see if using e.g. Firefox in firejail and then I see in Ubuntu 16.04 in System Settings | Sound | Output tab gets empty.

I have reported a bug to pulseaudio at: https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1594570

and got response back that this is known issue with PulseAudio and Firejail and got the following reference: https://firejail.wordpress.com/support/known-problems/#pulseaudio I have followed instructions and now after two months having Ubuntu 16.04 problem is finally solved.

I know you can't probably do much, because it is probably bug in pulseaudio, but what you can do is update your web page that this problem also affects Ubuntu 16.04 where PulesAudio 8.0 is installed, returned info when executing: `pulseaudio --version`

My Firejail version currently installed:
`firejail --version`
firejail version 0.9.40

Thanks.

**Comment by netblue30** [comment]
Webpage fixed, thanks.

**Comment by igor2x** [comment]
Hi,
thanks for updating the web page. My I suggest to add additional info that this problem also affects PulseAudio 8.0 (as described in my previous post). You know someone executes: "pulseaudio --version" command and sees version 8.0 and may think it does not affect him/her, because of firejail web page is only PulseAudio 7.0 mentioned as a problem.
Thanks

**Comment by netblue30** [comment]
Will do, thanks.
