### ISSUE TITLE
Read profiles from /usr, in addition to /etc and ~/.config

### ISSUE THREAD

**Issue by gioele** [netblue30/firejail#6152]
### Problem description

Firejail profiles are currently stored in `/etc/firejail/` (or `/usr/local/etc/firejail/`) and `~/.config/firejail/`. This is not compatible with stateless systems and hermetic builds, in which distro-provided packages only ship files under `/usr/`, including default configuration files.

In addition, files in `/etc` are supposed to be owned by the system administrator and freely editable. [Firejail's wiki states that profiles should not be modified](https://github.com/netblue30/firejail/wiki/Creating-overrides#when-to-use-overrides)

> Modifying a profile file (.profile) in /etc/firejail is discouraged. Changes will be overwritten when you update Firejail

so it would make more sense to have the default profiles in `/usr`.

### Proposed solution

In addition to searching for profiles in `~/.config/firejail/` and `/etc/firejail/`, Firejail should also search in `/usr/lib/firejail/`.

Distribution packages will install their files in `/usr/lib/firejail/`, system administators in `/etc/firejail`, and non-admin users in `~/.config/firejail`.

**Comment by rusty-snake** [comment]
Duplicate of #4871

**Comment by gioele** [comment]
Thanks @rusty-snake for the pointer.
