### ISSUE TITLE
"Seccomp.keep chroot" exits with error

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#618]
I'm probably doing this wrong but whenever I try to use the seccomp filter but keep chroot, firejail exits with a warning. This is for profiles as well as starting a shell from the terminal:
`<user>@<redacted> ~ $ firejail --seccomp.keep=chroot`
`Reading profile /etc/firejail/default.profile`
`Reading profile /etc/firejail/disable-common.inc`
`Reading profile /etc/firejail/disable-programs.inc`
`Reading profile /etc/firejail/disable-passwdmgr.inc`
` `
`** Note: you can use --noprofile to disable default.profile **`
` `
`Parent pid 2531, child pid 2532`
` #`
`Error: cannot establish communication with the parent, exiting...`

Starting `firejail --seccomp` works fine (though of course no chroot), it's only with `seccomp.keep` that I have issues.

This is for the development version of firejail, built from source a few hours ago, running on LMDE Betsy (Debian Jessie base).

Thanks!

**Comment by manevich** [comment]
I have no expertise here, but if you run this command with `--debug` flag you see that you get only few syscalls whitelisted:
```
SECCOMP Filter:
  VALIDATE_ARCHITECTURE
  EXAMINE_SYSCAL
  WHITELIST 105 setuid
  WHITELIST 106 setgid
  WHITELIST 116 setgroups
  WHITELIST 32 dup
  WHITELIST 161 chroot
  KILL_PROCESS
Save seccomp filter, size 120 bytes
```
Too few to run something usefull, I think.

**Comment by netblue30** [comment]
@manevich is right, you need quite a long list there.

**Comment by Fred-Barclay** [comment]
So in other words, chroot needs more syscalls that are blacklisted by seccomp, so firejail exits. Is that correct?

**Comment by netblue30** [comment]
You would need to run strace on the application you want to sandbox. strace will give you the list of syscalls:

https://firejail.wordpress.com/documentation-2/seccomp-guide/

**Comment by Fred-Barclay** [comment]
Thank you @manevich and @netblue30. `strace` looks like it will do the trick, and I'm left scratching my head and wondering why I didn't think of it earlier. :)
Take care.
