### ISSUE TITLE
single files binding

### ISSUE THREAD

**Issue by eadmaster** [netblue30/firejail#619]
is it possible to setup single files binding like i used to do with [proot](https://github.com/proot-me/PRoot/)?

For instance

    proot -b $APPBASEDIR/App/usr/share/pixmaps/app.png:/usr/share/pixmaps/app.png $CMDLINE

**Comment by netblue30** [comment]
It is supported, but you need to be root to do it:

`````
      --bind=filename1,filename2
              Mount-bind  filename1  on  top of filename2. This option is only
              available when running as root.

              Example:
              # firejail --bind=/config/etc/passwd,/etc/passwd
`````

**Comment by eadmaster** [comment]
Alternatively, if i have to bind a lot of files, can i have an unionfs-like behavior? (merge the contents of 2 dirs instead of mounting one over another).
example:
firejail --???=$APPBASEDIR/App/usr/share/pixmaps,/usr/share/pixmaps

**Comment by netblue30** [comment]
I'll keep it in mind, however, you will still need to be root to do it.
