### ISSUE TITLE
Support for Ubuntu 23.04 (Lunar Lobster)

### ISSUE THREAD

**Issue by parselings** [netblue30/firejail#6199]
### Is your feature request related to a problem? Please describe.
It would be nice if you could support Ubuntu 23.04 (Lunar Lobster).

When [following instructions](https://github.com/netblue30/firejail?tab=readme-ov-file#ubuntu), `apt update` complain about a missing Release file.

I also looked at the [launchpad folders](http://ppa.launchpadcontent.net/deki/firejail/ubuntu/dists/), there is no lunar folder.

### Describe the solution you'd like
A official support, please ? Nothing urgent here, for me.

### Describe alternatives you've considered
Looking for the fixes and apply them locally (it's usually a missing line in the allow lists).

### Additional context
Nothing else. Thank you for this application !

**Comment by kmk3** [comment]
Cc: @reinerh

Relates to #6174.

**Comment by reinerh** [comment]
Sorry, it's no longer possible to create a repo/PPA for Lunar Lobster as it's out of support.
You should upgrade to Mantic or Noble.
