### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [netblue30/firejail#62]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [save_cgroup](https://github.com/netblue30/firejail/blob/b77a28737ecd9be3d202049a638db153299780d0/src/firejail/cgroup.c#L25)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [shm_write_bandwidth_file](https://github.com/netblue30/firejail/blob/b77a28737ecd9be3d202049a638db153299780d0/src/firejail/bandwidth.c#L251)

**Comment by netblue30** [comment]
fixed

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/netblue30/firejail/blob/491b8f2390c456d55ad49c333c1cc42cf7dd116e/src/firejail/cgroup.c#L35 "More return value checks?") left over?
