### ISSUE TITLE
mpv profile breaks thumbfast thumbnails

### ISSUE THREAD

**Issue by jtrv** [netblue30/firejail#6204]
### Description

Using the default mpv.profile with [uosc](https://github.com/tomasklaen/uosc) and [thumbfast](https://github.com/po5/thumbfast) breaks thumbfast's progress bar thumbnail previews.

### Steps to Reproduce

_Steps to reproduce the behavior_

```sh
paru -S firejail mpv mpv-uosc-git mpv-thumbfast-git
sudo firecfg
mpv video.mp4
```

### Expected behavior

Hovering over the progress bar at the bottom of the screen should show thumbnail previews for the corresponding time in the video that is hovered.

### Actual behavior

A single thumbnail is shown for the first point hovered over, but it won't update as you move across the progress bar.

### Behavior without a profile

Works as expected

### Additional context

https://github.com/po5/thumbfast/blob/master/thumbfast.lua

### Environment

- Arch Linux 6.7.2-zen1-2-zen
- Firejail version 0.9.72

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [x] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log
https://paste.rs/aJS4V.txt

**Comment by glitsj16** [comment]
Hello. As it happens I use [uosc](https://github.com/tomasklaen/uosc) myself with mpv thru firejail. Here are my observations.

For starters, there have been several changes to our [mpv.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/mpv.profile) compared to what's in the 0.9.72 release. Perhaps it's worthwhile to use the [firejail-git](https://aur.archlinux.org/packages/firejail-git) package from the AUR for a smoother experience.

That being written, I did experiment a bit with the `thumbfast` Lua script you referenced. It took some extra loosening of mpv's sandbox, as the Lua script also calls out other commands via subprocesses. Long story short, I couldn't put together a more restrictive `private-bin` (yet), but the below mpv.local worked for me:

```console
$ cat ~/.config/firejail/mpv.local
ignore noexec /tmp
include allow-bin-sh.inc
ignore apparmor
# the below private-bin is missing some items
# go over the thumbfast.lua script and try to improve it
#private-bin bash,chmod,echo,ps,sh,socat,uname
ignore private-bin

```

Whether or not you're willing to cripple mpv's sandbox for the thumbfast gain is up to you. Just wanted to point that out, even though it's a nice GUI addition.

**Comment by jtrv** [comment]
@glitsj16 thank you, all it needed was `tail`

```
include allow-bin-sh.inc

ignore noexec /tmp
ignore apparmor

private-bin bash,chmod,echo,ps,socat,tail,uname
private-tmp
```

**Comment by glitsj16** [comment]
@jtrv Oh that's a nice find. Having private-bin intact is alwats a plus. You're welcome. Feel free to close if there's nothing left actionable now.
