### ISSUE TITLE
x2goclient: no sound device

### ISSUE THREAD

**Issue by unix1984** [netblue30/firejail#6208]
### No sound device in firejail x2goclient.

Login to the remote linux (Ubuntu 22.04) machine is successful.
However, no audio device is displayed, it just says that it is connected to pulseaudio, but nothing happens.
I already tried adding "alsa" and "pulseaudio" to a custom x2goclient.profile, but it didn't help.
Anyone have an idea?

Thanks,
Matyi

**Comment by kmk3** [comment]
Basic debugging information is missing; please follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>

**Comment by unix1984** [comment]
I don't have that much time for that right now. I'd rather not use firejail if this was such a complicated question.

Regards

**Comment by kmk3** [comment]
> I don't have that much time for that right now. I'd rather not use firejail
> if this was such a complicated question. With x2goclient, it would have been
> expected that there was sound.
> 
> But it seems no one has tested this.

Profiles tend to bitrot as their relevant programs and the environment change
and it is up to the users of a given program to maintain its profile.

> Maybe I'll try again in a few years.
> 
> Regards

Alright, closing this as abandoned.

Feel free to open an issue with the missing information if/when you are able
to.
