### ISSUE TITLE
`protocol unix` makes `netfilter` useless... right?

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#623]
Just making sure... if I use `--protocol=unix` then all network (eth, wlan) access is disabled and there is no point in using a network filter such as netfilter or `--net=none`, right?

`--protocol=unix` is turning out to be very useful when I want to disable network access but still need a dbus connection (which net none seems to block), so I want to make sure I'm using it correctly.
Thanks!
Fred

**Comment by netblue30** [comment]
Yes, you are right. Some programs such as evince are just crashing with "--net=none", so I put --protocol=unix instead. It is almost the same thing. The difference is in one case you see the network but you cannot connect to it, and in the other case you don't see the network at all.

**Comment by Fred-Barclay** [comment]
Thanks mate. :)
