### ISSUE TITLE
Thunderbird Won't Open Full URL (Only Resource Name)

### ISSUE THREAD

**Issue by cabellicar123** [netblue30/firejail#625]
I created `/usr/local/bin/thunderbird` with the contents:

```
firejail /usr/bin/thunderbird $@
```

Everything works great, except that when I try to open links in thunderbird, firefox will open the correct resource name (e.g. amazon.com), but will not actually load the full URL. Running thunderbird directly (/usr/bin/thunderbird), opening links works fine. Is this expected behavior?

Note: firefox is also firejailed using an equivalent script as that for thunderbird (`/usr/local/bin/firefox`)

**Comment by netblue30** [comment]
Put symbolic links to firejail under /usr/local/bin instead of scripts:

$ sudo rm /usr/local/bin/thunderbird
$ sudo ln -s /usr/bin/firejail /usr/local/bin/thunderbird

Do the same for firefox and try it out.

**Comment by cabellicar123** [comment]
Seems to have resolved the issue. Is using symbolic links the preferred method?

**Comment by netblue30** [comment]
Yes. If you are running version 0.9.40 or the development one here, I have a utility, firecfg, that creates automatically the symbolic links under /usr/local/bin. Take a look at "man 1 firecfg".

**Comment by cabellicar123** [comment]
While this did make the issue better for some links I have recently found it not to work on all links. To test I created an email with the following HTML and sent it to myself.

    <a href="http://www.w3schools.com/html/action_page.php?foo=bar&test=test">Click Me!</a>

Clicking the link resulted in this opening http://www.w3schools.com/html/action_page.php?foo=bar, which is missing a piece.

Copying the link location in thunderbird does yield the right result: http://www.w3schools.com/html/action_page.php?foo=bar&test=test.

**Comment by netblue30** [comment]
I'll give it a try, thanks.

**Comment by netblue30** [comment]
Seems to be working fine in the git version.

**Comment by cabellicar123** [comment]
I can confirm the current git version does not have the same issue found in `0.9.40`. Thank you.
