### ISSUE TITLE
Expand the directories that are possible for whitelisting

### ISSUE THREAD

**Issue by pepa65** [netblue30/firejail#627]
Currently only $HOME, /dev, /media, /opt, /var, and /tmp can be used for whitelisting. It would be very helpful there could be an option to include other directories.

Or if that is too cumbersome, perhaps could you allow for /data/ to be whitelisted?? I noticed one other person wanting to use that particular directory.

**Comment by netblue30** [comment]
Some other directories are covered by --private options:

--private-bin: handles /bin, /sbin, /usr/bin, /usr/sbin, /usr/local/bin, /usr/local/sbin

--private-etc: /etc

What other directory do you have in mind?

**Comment by netblue30** [comment]
No problem, it can  definitely be done in a generic way. I also have a similar request for /lib and /usr/lib and such.

So, I will bring in a generic whitelist for any directory under /, and private-lib support.

**Comment by msva** [comment]
@netblue30,
> I will bring in a generic whitelist for any directory under /

I'd ***VERY*** like to finally see that ASAP (and same for `mkdir` too)! 😀

Is it something that blocks you from doing that? Or, will you, at least, accept a PR with such modifications?

**Comment by chiraag-nataraj** [comment]
Let's move this to #2041, since `private-lib` has been added, but generic whitelist has not (yet) made it in.
