### ISSUE TITLE
build: warning: "_FORTIFY_SOURCE" redefined (Arch Linux)

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#6282]
The arrival of [pacman 6.1](https://archlinux.org/packages/core/x86_64/pacman/) and related changes show some impact on Firejails build output when using `--enable-analyzer`. I'm seeing a large number of repeated output like the below:

```
[...]
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
[...]
```

Nothing breaks, so this isn't urgent IMO, more of a FYI.

Details that might help grokking this:

```sh
$ pacman -Q gcc pacman
gcc 13.2.1-5
pacman 6.1.0-3
```

[pacman 6.0] [Core]
https://archlinux.org/packages/core/x86_64/pacman/
https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/0486fd84165488f10bb3602b103692c70f8a2fb8/makepkg.conf
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

[pacman 6.1] [Core]
https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/main/makepkg.conf?ref_type=heads
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \
         -Wl,-z,pack-relative-relocs"

**Comment by kmk3** [comment]
Thanks for the the debugging!

Fixed in:

* #6283
