### ISSUE TITLE
Blacklisted by default!

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#63]
Thanks a lot for the new version, netblue30!

One suggestion: Doesn't it make sense to blacklist the various autostart folders to prevent their manipulation? Like this:

blacklist ${HOME}/.config/autostart
blacklist ${HOME}/.kde4/Autostart
blacklist ${HOME}/.kde/Autostart

Other DE's will have different autostart folders.

**Comment by netblue30** [comment]
This is a good idea, I'll put it in. Thanks.

**Comment by netblue30** [comment]
all done!

**Comment by curiosity-seeker** [comment]
Thank you very much! The list you added in disable-common.inc is already very comprehensive. Nevertheless, after thinking a bit more about this issue and further digging in the Arch Linux wiki I think there are more candidates worth being included:

~/.kde4/share/autostart
/var/spool/cron
/var/spool/anacron
/etc/cron.*
/etc/profile.d
/etc/rc.local
/etc/anacrontab
/usr/lib/systemd
/etc/systemd

Regarding the last 2 suggestions: I've firejailed dnsmasq, and blacklisting those directories didn't hurt when I restarted dnsmasq. Nevertheless it might be sifficient to make them read-only to prevent possible breakage.

**Comment by netblue30** [comment]
I'll put everything in, thanks. I'll make the last two read-only. I'll keep the discussion open, in case there are more suggestions.

**Comment by ajs124** [comment]
How about the user specific systemd folder: ~/.local/share/systemd ?

**Comment by netblue30** [comment]
/usr/lib/systemd and /etc/systemd are done by default - /usr and /etc are mounted read-only. I added everything else, including ~/.local/share/systemd. Thanks!

**Comment by curiosity-seeker** [comment]
Thank you very much, netblue30! 

I have some more suggestions:

blacklist {HOME}/.wine
This should prevent the unintentional execution of Windows malware.

blacklist {HOME}/.VirtualBox
Prevent manipulation of VMs.

blacklist {HOME}/.lastpass
blacklist {HOME}/.keepassx
for disable-secret.inc. A rule like
noblacklist ${HOME}/.lastpass
would be needed for the various browser profiles, of course.

**Comment by pigmonkey** [comment]
I'm not sure how far down the rabbit-hole of default blacklists you want to go (at some point it is easier to tell people just to use `--whitelist` or `--private`), but [pass](http://www.passwordstore.org/) defaults to `~/.password-store`. That may be worth considering if KeePass and LastPass stuff is also going to be added.

**Comment by netblue30** [comment]
`````
blacklist ${HOME}/.pki/nssdb
blacklist {HOME}/.lastpass
blacklist {HOME}/.keepassx
blacklist {HOME}/.password-store
````

went in all profiles for media players, pdf, and bittorrent apps.

Disabled .wine in all profiles with the exception of browsers and mail clients - some users run Microsoft Silverlight under wine in browsers.

Disabled VirtualBox in everything.

**Comment by curiosity-seeker** [comment]
Thanks, netblue30! However, wouldn't it be preferable to add the first 4 directories to disable-secret.inc and .wine to disable-common.inc and rather add noblacklist rules in the profiles where necessary? 
This would make sure that those important directories are protected if the user creates own profiles for other applications without the need to remember adding those blacklist rules manually.

**Comment by netblue30** [comment]
It's the same thing. I did include them in the generic.profile, so by default the blacklists are always enabled.

**Comment by curiosity-seeker** [comment]
Thanks, I see!
