### ISSUE TITLE
Core Infrastructure Initiative (CII) Best Practices

### ISSUE THREAD

**Issue by ypid** [netblue30/firejail#630]
#### Proposal

Someone closely involved with the project could go thought the criteria and keep them up-to-date.

#### References

* https://bestpractices.coreinfrastructure.org
* https://twit.tv/shows/floss-weekly/episodes/389

**Comment by netblue30** [comment]
We have no plans in this moment to apply for a badge. We'll do it by the time we release 1.0 - we cover most of the criteria anyway. Thanks for the links.

**Comment by ypid** [comment]
You are welcome :wink:

**Comment by ypid** [comment]
Umm, no need to close it? You could set it to milestone v1.0? Maybe someone else would like to add the project there even before v1.0.

**Comment by netblue30** [comment]
I'll add it to my todo list. I have quite a long one in this moment.

https://github.com/netblue30/firejail/blob/master/todo
