### ISSUE TITLE
failed to start xpra on Arch Linux

### ISSUE THREAD

**Issue by fkarl423** [netblue30/firejail#633]
When running with the --x11 option the folliwing error appears on arch linux:

Entering daemon mode; any further errors will be reported to:
  /home/user/.xpra/:294.log
Error: failed to start xpra

The log says:

/usr/lib/xorg-server/Xorg.wrap: Only console users are allowed to run the X server
could not connect to X server on display ':294' after 3 seconds

**Comment by netblue30** [comment]
If you are on Arch, the version of xpra they have is broken.

**Comment by fkarl423** [comment]
OK Thanks for the info. I will try with a different version

**Comment by netblue30** [comment]
If you find a way to run it on Arch, please let me know. Thanks.

**Comment by fkarl423** [comment]
I found the issue and how to solve it.

It seems recent versions of the x-server need the file /etc/X11/Xwrapper.config with the content allowed_users=anybody

This allows everyone to start the xserver. 
I don't really know if there are any security implications, maybe someone can verify that this is save to use.

**Comment by netblue30** [comment]
Just to make sure I understand what you have there: Arch Linux with xpra-winswitch package from AUR installed, you modify /etc/X11/Xwrapper.config "allowed_users=anybody", and is working! Is this right?

For security implications I would say if you are not running a server or a multiuser system you should be fine.

**Comment by fkarl423** [comment]
Yes, that is correct.

**Comment by netblue30** [comment]
I'll update the documentation, thanks!

**Comment by vn971** [comment]
Oh, that's interesting. `xpra` didn't work for me, too.
Actually, I don't even understand why xpra checks the config. Xephyr can launch itself without any questions.
Does it mean that Xephyr is emulating X as a normal user-space program while `xpra` communicates with parent X directly? (*Confused*.)

**Comment by netblue30** [comment]
Documentation updated, thanks.

> I don't even understand why xpra checks the config

Who knows what they are doing there. I guess you are correct, they emulate a user-space X11 server, while communicating with the parent server directly.
