### ISSUE TITLE
make read-write opposite of read-only

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#635]
Hi!

Is it possible to make `read-write` generic so that it can work with any top directory and counter the effect of `read-only` on subfolders, e.g.:
`read-only /media/user/*` and `read-write /media/user/foo/`
`read-only ~/` and `read-write ~/foo.bar`

Thanks.

**Comment by netblue30** [comment]
Sure, I'll put it in.

**Comment by netblue30** [comment]
Sorry, it is already done in git - somebody requested it a while back.
`````
      --read-write=dirname_or_filename
              By  default,  the  sandbox  mounts system directories read-only.
              These directories are  /etc,  /var,  /usr,  /bin,  /sbin,  /lib,
              /lib32, /libx32 and /lib64.  Use this option to mount read-write
              files or directories inside the system directories.

              This option is available only to root user.  It  has  no  effect
              when --chroot or --overlay are also set. In these cases the sys‐
              tem directories are mounted read-write.

`````

**Comment by nick75e** [comment]
The first part is misleading since it says `Use this option [...] inside the system directories`. I thought it was only for these directories.
Also can you remove the requirement to be root for directories owned by the user?

**Comment by netblue30** [comment]
Yes, it is kind of misleading. I'll allow the option in the user home directory.

**Comment by nick75e** [comment]
I personally need it for files under `/media/$USER` and from what I've read from other users `/data/` would also be useful.

**Comment by netblue30** [comment]
OK, let's do it this way: if the file or directory is owned by the user, I'll set it read/write.

**Comment by netblue30** [comment]
Fixed in git. The text in the man page is:
`````
       --read-write=dirname_or_filename
              Set  directory  or  file  read-write.  Only files or directories
              belonging to the current user are allowed  for  this  operation.
              Example:

              $ mkdir ~/test
              $ touch ~/test/a
              $ firejail --read-only=~/test --read-write=~/test/a
`````
