### ISSUE TITLE
Missing .gnomerc in disable-common.inc

### ISSUE THREAD

**Issue by PieroV** [netblue30/firejail#637]
Hi, I think that those lines should be added to disable-common.inc, in the "# X11 session autostart" section:
```
blacklist ${HOME}/.gnomerc
blacklist /etc/X11/Xsession.d/
```

Thank you very much, this project is fantastic.

**Comment by Fred-Barclay** [comment]
I've added a PR that implements this; now we just have to see if @netblue30 thinks it's a good idea. :smile_cat: 
Thanks!

**Comment by netblue30** [comment]
All fixed and merged, thanks!
