### ISSUE TITLE
claws-mail window doesn't paint / is unresponsive with "fancy" plugin

### ISSUE THREAD

**Issue by Dieterbe** [netblue30/firejail#6377]
### Description

Today I did some maintenance on my laptop, involving:
* upgrading claws-mail from 4.2.0-1 -> 4.3.0-1
* upgrading firejail 0.9.72-3 to firejail-git (from AUR, 0.9.72.r1051.g42bdb7880-1)
(✨ ✨ I use Arch, btw ✨ ✨)

All my apps etc seem to work fine still, except for claws-mail.
the app starts, but the window doesn't render properly (my window manager is i3). if claws-mail starts in a different workspace, then switching to it, doesn't show anything.
if i start claws-mail in the same workspace, you can see the rendered application, however it does not respond to any mouse clicks, like it is stuck / frozen. the mouse cursor keeps spinning

### Steps to Reproduce

I don't use any custom config for claws-mail (that i know of). my /etc/firejail/claws-mail.profile is identical to the file found in the current latest firejail git.

```
[root@xps17 ~]# grep -Ri claws /home/dieter/.config/firejail/
[root@xps17 ~]# 
[root@xps17 ~]# find /home/dieter/.config/firejail/ | grep claws
[root@xps17 ~]# 
[root@xps17 ~]# locate globals.local
[root@xps17 ~]# 
```

* `LC_ALL=C firejail claws-mail` triggers the problem (confirmed with both claws 4.2 and 4.3)
* `LC_ALL=C firejail --noprofile /usr/bin/claws-mail` does not have the problem. the app works fine (confirmed with both claws 4.2 and 4.3)

Here is the output of all 4 cases: https://gist.github.com/Dieterbe/04485d729c6d8fa31e3b61ef6dac4707

### Expected behavior

claws-mail renders, and responds to interactivity, i can use the app

### Actual behavior

app doesn't render / freezes

### Environment

- ✨ ✨ I use Arch, btw ✨ ✨
- firejail from git 42bdb78800d2be5dbd4b06b6fc1581420357bc99 
```
firejail --version
firejail version 0.9.73

Compile time support:
	- always force nonewprivs support is disabled
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file transfer support is enabled
	- IDS support is disabled
	- Landlock support is enabled
	- networking support is enabled
	- output logging is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-lib support is disabled
	- private-cache and tmpfs as user enabled
	- SELinux support is disabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

see link above

**Comment by kmk3** [comment]
It's hard to tell what the issue is from the logs.

I'd try commenting lines in claws-mail.profile until it works to narrow it
down.

**Comment by glitsj16** [comment]
Side note

https://gist.github.com/Dieterbe/04485d729c6d8fa31e3b61ef6dac4707#file-claws-4-2-0-1-via-firejail-txt-L27
https://gist.github.com/Dieterbe/04485d729c6d8fa31e3b61ef6dac4707#file-claws-4-3-0-1-via-firejail-txt-L27

Whenever you see this warning, it's a reminder to always use `absolute` paths. Firecfg places the symlinks in /usr/local/bin and that has precedence. I'm pretty sure this isn't related to your current issue. Still good practice though, so you're absolutely sure Firejail doesn't try to run the sandbox twice.

**Comment by glitsj16** [comment]
Some things to try:

- `temporarily downgrade` to claws-mail 4.2.0-1 and run that without firejail (just to rule out it's something CM-related, which isn't clear if you've tried that yet)
- check the comment in /etc/firejail/claws-mail.profile about `allowing python` (and test that in a claws-mail.local)
- use CM's `--debug` flag to get a more verbose log from the app

HTH

**Comment by glitsj16** [comment]
Experienced intermittent ISP networking troubles during IRC communication with @Dieterbe. Issue still unresolved after checking CM configuration/mail storage paths and whitelisting ~/.cache/claws-mail. Issue is still unresolved.

> I'd try commenting lines in claws-mail.profile until it works to narrow it down.

**Comment by kmk3** [comment]
@Dieterbe

Please consider reporting this issue to the plugin developers as well.

I'm not familiar with the plugin, but I'd expect html rendering in general to
work without needing hardware acceleration.

**Comment by Dieterbe** [comment]
they don't use github. i can't be bothered to sign up to their mailing list or bug tracker. if someone else wants to do that, feel free.
