### ISSUE TITLE
librewolf: cannot open new URLs into running instance 3

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#6413]
Firejail Version: 0.9.72
Debian 12
LibreWolf AppImage 128.0-2:

This issue was previously fixed in #4891 and #5227. Yet after upgrading to [LibreWolf AppImage 128.0-2](https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/128.0-2/LibreWolf.x86_64.AppImage) the problem has returned.

Here's the command I'm using to run LibreWolf:
`firejail --appimage --profile=/etc/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage`

The problem occurs after first launch, when I'm trying to open additional web pages. For example, let's say LibreWolf is already running, and I want to open Ebay from the command line:
`firejail --appimage --profile=/etc/firejail/librewolf.profile ~/AppImages/LibreWolf.x86_64.AppImage https://www.ebay.com`

Instead of opening Ebay into a new tab, I get this error:
`"Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile."`

**Comment by glitsj16** [comment]
FYI, Librewolf offers .deb files: https://librewolf.net/installation/debian/. Can you test if your issue changes when you don't use an AppImage?

**Comment by kmk3** [comment]
Basic debugging information is missing; please follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>

**Comment by kmk3** [comment]
Does it still happen with firejail-git?

What is the output in trace.txt in the following command?

```sh
firejail --trace=trace.txt --appimage \
  --profile=/etc/firejail/librewolf.profile \
  ~/AppImages/LibreWolf.x86_64.AppImage https://www.ebay.com
```

**Comment by stormtheory** [comment]
Why don't you try --name=sandyfox ? This works in firefox and I even wrote a python script wrapper for firejail to handle all this.

**Comment by Lonniebiz** [comment]
@stormtheory : I tried using `--name=sandyfox` and even `--join=sandyfox`, but same problem. Only the first command launches LibreWolf. Subsequent commands all get the same error I screenshot above.

**Comment by stormtheory** [comment]
@Lonniebiz  I just tried this and it worked in Firefox. In your librewolf.profile make sure of the following is set in order for it to talk on the dbus or it the instances won't be able to talk:

```
dbus-user filter
ignore dbus-user none
```


Run commands like this but with your profile and LibreWolf.
```
firejail --profile=/sandbox/firefox.profile --name=sandyfox firefox
firejail --profile=/sandbox/firefox.profile --name=sandyfox firefox --new-tab www.google.com
```

**Comment by Lonniebiz** [comment]
@stormtheory : My custom profile does indeed contain:

dbus-user filter
ignore dbus-user none

The difference is that I'm specifically trying to accomplish this using the latest **AppImage** of LibreWolf (version 129.0.2-1) which is located here:
https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/129.0.2-1/LibreWolf.x86_64.AppImage

So, when I try the arguments you're suggesting, with this exact AppImage, they look like this:
```
firejail --appimage --profile=/home/user1/.config/firejail/librewolf.profile --name=sandyfox ~/AppImage/LibreWolf.x86_64.AppImage

firejail --appimage --profile=/home/user1/.config/firejail/librewolf.profile --name=sandyfox ~/AppImage/LibreWolf.x86_64.AppImage --new-tab www.google.com
```

Yet, upon running the 2nd command, I'm getting the error I screen captured in a prior post. I simply can't launch new tabs from the command line.

Previously, in [LibreWolf v127.0-2](https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/127.0.2-2/LibreWolf.x86_64.AppImage), I was able to launch new tabs from the command line without getting that error (even without `--name=sandyfox`), but in [every version after v127.0-2](https://gitlab.com/librewolf-community/browser/appimage/-/releases), I've found no way to launch new tabs from the command line without error.

**Comment by kmk3** [comment]
#4897 added `io.gitlab.librewolf.*`; is that what Librewolf is currently using?

Does it work if you remove all dbus-related entries from all the relevant
.profile and .local files?

I'd try using something like busctl or d-feet to inspect what dbus commands
Librewolf is using.

**Comment by kmk3** [comment]
@Lonniebiz

What is the dbus name returned in the following?

```
busctl --user | grep librewolf
```

It appears as `io.gitlab.firefox.*` to me, which is different from what is in
librewolf.profile.

Does it work with the following in librewolf.local?

```
dbus-user.own io.gitlab.firefox.*
```

**Comment by Lonniebiz** [comment]
@kmk3 Thank you so much for taking the time to reproduce my issue and get to the bottom of it. I'm sorry I wasn't more prompt with your questions.

**Comment by kmk3** [comment]
> Thank you so much for taking the time to reproduce my issue and fix it.
> 
> I confirm that after adding `dbus-user.own io.gitlab.firefox.*`, to my custom
> profile, there after I was able to launch new tabs in the latest [LibreWolf
> AppImage
> v130.0-3](https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/130.0-3/LibreWolf.x86_64.AppImage).

All good, thanks for confirming.

> How long do you expect it will take before your changes land in Debian 12?
> Once there, I'll likely switch back to using the default profile.

Personally I'm working on a few fixes for new features before they ship.

Then the idea is to work on the release itself.

No ETA though.

**Comment by Lonniebiz** [comment]
@stormtheory @kmk3 

Do you have any advise on how to use firejail commands to open URLs into new tabs of a LibreWolf AppImage on Debian 13, which uses Firejail 0.9.74?

I'm having that same issue again; my old commands I learned here don't work now.

The latest AppImage for LibreWolf:
https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/142.0-1/LibreWolf.x86_64.AppImage

Intial Launch:
firejail --appimage --name=librewolf ~/AppImage/LibreWolf.x86_64.AppImage

Attempt to Launch a URL into a new tab of the Already Running Sandbox:
firejail --appimage --join=librewolf ~/AppImage/LibreWolf.x86_64.AppImage https://firejail.wordpress.com/

**Comment by kmk3** [comment]
> Do you have any advise on how to use firejail commands to open URLs into new
> tabs of a LibreWolf AppImage on Debian 13

Try to find if it changed the dbus name again (as per above) and post it here.

If that does not work, open a new issue.

> Firejail 0.9.74

Note that we do not maintain that version of firejail:

* <https://github.com/netblue30/firejail/blob/master/SECURITY.md>

Versions other than the latest usually have outdated profiles and may contain
bugs and security vulnerabilities that were fixed in later versions.

See also:

* <https://github.com/netblue30/firejail#installing>
