### ISSUE TITLE
build: error: ‘PROC_EVENT_COREDUMP’ undeclared (kernel version 3.8)

### ISSUE THREAD

**Issue by Zopolis4** [netblue30/firejail#6414]
### Steps to Reproduce

```sh
docker run --platform linux/386 --rm -it satmandu/crewbuild:386
```

Once in docker container:

```sh
# (optional, will speed up commands)
rm -f "$CREW_PREFIX/etc/bash.d/git" "$CREW_PREFIX/etc/bash.d/git-prompt.sh" &&
source ~/.bashrc

# build
cd
git clone https://github.com/netblue30/firejail
cd firejail
autoreconf -fvi
./configure
make
```

Errors:

```
gcc -ggdb -O2 -DVERSION='"0.9.73"' -Wall -Wextra  -Wformat -Wformat-security -fstack-protector-all -DPREFIX='"/usr/local"' -DSYSCONFDIR='"/usr/local/etc/firejail"' -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -DVARDIR='"/var/lib/firejail"'   -DHAVE_CHROOT -DHAVE_DBUSPROXY -DHAVE_FILE_TRANSFER  -DHAVE_GLOBALCFG   -DHAVE_NETWORK  -DHAVE_OUTPUT  -DHAVE_PRIVATE_HOME   -DHAVE_SUID -DHAVE_USERNS -DHAVE_USERTMPFS -DHAVE_X11 -D_FORTIFY_SOURCE=2 -mindirect-branch=thunk -fstack-clash-protection -fstack-protector-strong -MMD -MP -fPIE -march=i686  -c ../../src/firemon/procevent.c -o ../../src/firemon/procevent.o
../../src/firemon/procevent.c: In function ‘procevent_monitor’:
../../src/firemon/procevent.c:399:38: error: ‘PROC_EVENT_COREDUMP’ undeclared (first use in this function); did you mean ‘PROC_EVENT_COMM’?
  399 |                                 case PROC_EVENT_COREDUMP:
      |                                      ^~~~~~~~~~~~~~~~~~~
      |                                      PROC_EVENT_COMM
../../src/firemon/procevent.c:399:38: note: each undeclared identifier is reported only once for each function it appears in
../../src/firemon/procevent.c:400:66: error: ‘union <anonymous>’ has no member named ‘coredump’
  400 |                                         pid = proc_ev->event_data.coredump.process_tgid;
      |                                                                  ^
make[1]: *** [../../src/prog.mk:25: ../../src/firemon/procevent.o] Error 1
make[1]: Leaving directory '/home/chronos/user/firejail/src/firemon'
make: *** [Makefile:72: src/firemon/firemon] Error 2
```

### Additional context

All i686 chromebooks have a kernel version of 3.8, and it looks like `PROC_EVENT_COREDUMP` was only added in 3.10.

### Environment

- Linux distribution and version: ChromeOS M58

**Comment by kmk3** [comment]
What is the gcc version?

> ```
> gcc -ggdb -O2 -DVERSION='"0.9.73"' -Wall -Wextra  -Wformat -Wformat-security -fstack-protector-all -DPREFIX='"/usr/local"' -DSYSCONFDIR='"/usr/local/etc/firejail"' -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -DVARDIR='"/var/lib/firejail"'   -DHAVE_CHROOT -DHAVE_DBUSPROXY -DHAVE_FILE_TRANSFER  -DHAVE_GLOBALCFG   -DHAVE_NETWORK  -DHAVE_OUTPUT  -DHAVE_PRIVATE_HOME   -DHAVE_SUID -DHAVE_USERNS -DHAVE_USERTMPFS -DHAVE_X11 -D_FORTIFY_SOURCE=2 -mindirect-branch=thunk -fstack-clash-protection -fstack-protector-strong -MMD -MP -fPIE -march=i686  -c ../../src/firemon/procevent.c -o ../../src/firemon/procevent.o
> ../../src/firemon/procevent.c: In function ‘procevent_monitor’:
> ../../src/firemon/procevent.c:399:38: error: ‘PROC_EVENT_COREDUMP’ undeclared (first use in this function); did you mean ‘PROC_EVENT_COMM’?
>   399 |                                 case PROC_EVENT_COREDUMP:
> ```

Looks like this was added on commit e11949a71 ("add support for comm, coredump,
and prctl procevents in firemon", 2024-04-30).

Does it work if you revert the commit?

**Comment by Zopolis4** [comment]
> What are the versions of gcc and libc?

GCC 14.1.0, glibc 2.23

> Does it work if you revert the commit?

Yes. (although I had to gloss over some merge conflicts in RELNOTES, but that doesn't affect the actual code)
