### ISSUE TITLE
element-desktop: Unable to find Electron app at /usr/share/element/app

### ISSUE THREAD

**Issue by leukimi** [netblue30/firejail#6421]
### Description

`element-desktop.profile` on openSUSE Tumbleweed fails to start `/usr/bin/element-desktop`. Electron is located at `/usr/bin/electron`.

### Steps to Reproduce

1. [Install **`element-desktop`** from software.opensuse.org](https://software.opensuse.org/package/element-desktop?search_term=element-desktop)
2. Run in bash `LC_ALL=C firejail /usr/bin/element-desktop`

### Expected behavior

Application window should open.

### Actual behavior

Process exits without opening main window.

### Behavior without a profile

<details>
<summary>Output of <code>LC_ALL=C firejail --noprofile /usr/bin/element-desktop</code></summary>
<p>

```
Parent pid 15379, child pid 15380
Warning: cannot find /var/run/utmp
Child process initialized in 12.43 ms
/home/user/.config/Element exists: yes
/home/user/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
[2:0727/185125.147277:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018

<Window opens>
```

</p>
</details>

### Environment

- updated openSUSE Tumbleweed
- Firejail v0.9.72

### Checklist

- [x] The issues is caused by firejail.
- [x] I can reproduce the issue without custom modifications.
- [x] The program has a profile.
- [x] The profile hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues.

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /usr/bin/element-desktop</code></summary>
<p>

```
Reading profile /etc/firejail/element-desktop.profile
Reading profile /etc/firejail/riot-desktop.profile
Reading profile /etc/firejail/riot-web.profile
Reading profile /etc/firejail/electron.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 9532, child pid 9536
Warning: cannot find /var/run/utmp
Warning: skipping Element for private /opt
Private /opt installed in 0.10 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Child process initialized in 193.24 ms
[4:0727/183420.166497:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
Error launching app
Unable to find Electron app at /usr/share/element/app

Cannot find module '/usr/share/element/app'

Parent is shutting down, bye...

```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /usr/bin/element-desktop</code></summary>
<p>

[debug_log (link to log)](https://gist.github.com/leukimi/ebd60b4dba8c99000a7efddccdb7a66a)

</p>
</details>

**Comment by kmk3** [comment]
> ```
> Error launching app
> Unable to find Electron app at /usr/share/element/app
> 
> Cannot find module '/usr/share/element/app'
> ```

Does it work with the following in ~/.config/firejail/element-desktop.local?

```
whitelist /usr/share/element
```
