### ISSUE TITLE
weechat.profile - duplicate "netfilter" entires

### ISSUE THREAD

**Issue by amarildojr** [netblue30/firejail#644]
weechat.profile has two "netfilter" entries:

># Weechat IRC profile
noblacklist ${HOME}/.weechat
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
>
>caps.drop all
seccomp
protocol unix,inet,inet6
netfilter
nonewprivs
noroot
netfilter

**Comment by Fred-Barclay** [comment]
Thanks for the report, mate. 
That was actually already fixed in #542 but good catch! :+1:

**Comment by amarildojr** [comment]
No problem! :D Sorry for not seeting that, I wouldn't really open a "Varius" thread looking for this bug :P

**Comment by Fred-Barclay** [comment]
No worries mate, and it's still a good catch :smile:
