### ISSUE TITLE
Config directory like "include" that will fail if profile cannot be found

### ISSUE THREAD

**Issue by QUser534** [netblue30/firejail#6458]
### Is your feature request related to a problem? Please describe.

Currently "include" will ignore when it cannot find a profile. I have a situation where I want to guarantee custom profiles have been created and if the included file was not created, then it will fail to launch.

### Describe the solution you'd like

A new directive such as "require" that will include a profile if it exists and trigger an error if it does not exist.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/blob/897f12dd88c1add667ecb211b61b6126a49c7065/src/firejail/profile.c#L1801-L1811


Can you give details of your installation, firejail version etc.

**Comment by QUser534** [comment]
Thanks, I was not aware that the suffix changed the behavior. When I use non .local suffixes the behavior works.

**Comment by rusty-snake** [comment]
It's one of the few (maybe the only one?) cases where the suffix is more than convention.
