### ISSUE TITLE
Support for the latest VSCodium

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [netblue30/firejail#6461]
### Is your feature request related to a problem? Please describe.

Firejail does not contain a profile to support the latest [VSCodium](https://vscodium.com/) in the apt package of Debian 11.

### Describe the solution you'd like

I would like the Firejail installation to contain a profile that supports the latest VSCodium, as it does with past versions in files:

- /etc/firejail/code-oss.profile
- /etc/firejail/vscodium.profile

### Describe alternatives you've considered

It would be possible to create a local custom file for latest VSCodium version but the program details have changed from the previous versions (whitelisted direcotries, privileges, etc.).

**Comment by kmk3** [comment]
Basic debugging information is missing; please follow the bug report template:

* <https://github.com/netblue30/firejail/issues/new?template=bug_report.md>

**Comment by rusty-snake** [comment]
Moved

**Comment by kmk3** [comment]
> I would happily do that, but it is not a BUG. It is a feature request to
> provide a profile for the latest version of a program.

Profiles are generally not separated by program versions (with limited
exceptions for new major versions of certain programs), they are created based
on the name of the executable.

Is there a new executable name for vscodium?

If not, there already exists a profile for vscodium and it either works
properly or it doesn't.

If it doesn't work, it's a bug.

> the program details have changed from the previous versions (whitelisted
> direcotries, privileges, etc.).

Which directories and privileges?

In what version of vscodium did they change?

**Comment by rusty-snake** [comment]
> The executable is renamed to codium so none of the provided profiles match

https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/codium.profile added 3 years ago.

**Comment by kmk3** [comment]
> * Firejail version (`firejail --version`): 0.9.64.4

Note that we do not maintain that version of firejail:

* <https://github.com/netblue30/firejail/blob/master/SECURITY.md>

Versions other than the latest usually have outdated profiles and may contain
bugs and security vulnerabilities that were fixed in later versions.

> This is probably something the Debian maintainer should do, so please close
> the report.

I think it's unlikely to be upgraded on a stable Debian release.

See also:

* <https://github.com/netblue30/firejail#installing>

**Comment by kmk3** [comment]
Duplicate of #3871

**Comment by rusty-snake** [comment]
> I will try to copy the upstream ones.

Does not necessarily work, the profile may use commands unknown by your firejail version or include other profiles you don't have or with wrong content.
