### ISSUE TITLE
[0.9.42-rc1] build failure on non-x86

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#647]
src/faudit/syscall.c is using the header sys/io.h for ioperm/iopl, which is only available on x86 architectures.
Because of this the build is failing on other architectures:
https://buildd.debian.org/status/package.php?p=firejail&suite=experimental

Can you please perform the ioperm/iopl checks only on x86 targets?

**Comment by netblue30** [comment]
Fixed, thanks for the bug!
