### ISSUE TITLE
xpra persists after firejailed app is quit

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#648]
firejail version 0.9.42~rc1 ubuntu 16.04.1 amd64, same behavior in 0.9.40.1
running firejail like this,

    firejail --name=workbrowser --x11 --net=fj0 --dns=8.8.8.8,8.8.4.4 --private=~/firejail/workbrowser google-chrome

the xpra session persists after the jailed app is quit.

**Comment by netblue30** [comment]
moved to: https://github.com/netblue30/firejail/issues/648

**Comment by xahare** [comment]
Ubuntu 16.04.1 LTS
xpra v0.17.4

**Comment by netblue30** [comment]
It is possible it was fixed by this commit: https://github.com/netblue30/firejail/pull/679

There is more testing coming.

**Comment by xahare** [comment]
those changes only apply to xephyr.

**Comment by netblue30** [comment]
You are right, sorry.

**Comment by netblue30** [comment]
All fixed.
