### ISSUE TITLE
Copying Data out of Private Jails

### ISSUE THREAD

**Issue by pigmonkey** [netblue30/firejail#65]
I frequently use `firejail --private chromium` to launch a disposable Chromium session. Very rarely I find that I need to download a file and recover it from the private jail. Up till now this has only happened with text files, so I've been able to `--join` the jail, `cat` the file, and paste it into a file outside of the jail.

Is there any sort of canonical way to copy files from within a private jail (before the jail has closed)? It would be nice if I could to something like:

    $ firejail --copy-from [pid of jail] --destination /home/user/ /path/to/file/within/jail

**Comment by netblue30** [comment]
Unfortunately I cannot reliably detect when the sandbox is closed. The kernel can kill it at any time, or the admin will just do a "kill -9". In these cases I do a --join and copy the file under /tmp. I give the sandbox a name so I can join it easily. Example:
`````
$ firejail --name=browser --private firefox
[...]
`````
In another terminal:
`````
$ firejail --join=browser
$ cp ~/Downloads/file /tmp/.
`````
