### ISSUE TITLE
Cyberfox

### ISSUE THREAD

**Issue by hawkeye116477** [netblue30/firejail#650]
Welcome! When I try to run "firejail cyberfox", appears "/bin/bash: cyberfox: command not found."
I also tried run "firejail ~/Apps/Cyberfox/Cyberfox", shows "Error: Access was denied while trying to open files in your profile directory." Any ideas?

**Comment by fkarl423** [comment]
It seems that cyberfox is not in any of your PATH directories and  ~/Apps/Cyberfox/Cyberfox is likely not whitelisted in /etc/firejail/cyberfox.profile.

Either add the path of your cyberfox binary to the PATH variable or whitelist the path of your binary in cyberfox.profile.

**Comment by hawkeye116477** [comment]
I tried both solutions, but it didn't help.

**Comment by netblue30** [comment]
Do like this:

Create ~/.config/firejail directory:
`````
$ mkdir ~/.config/firejail
`````
Open a text editor and save this text into ~/.config/firejail/Cyberfox.profile file:
`````
# Firejail profile for Cyberfox (based on Mozilla Firefox)

noblacklist ~/.8pecxstudios/cyberfox
noblacklist ~/.cache/8pecxstudios
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc

caps.drop all
netfilter
nonewprivs
noroot
protocol unix,inet,inet6,netlink
seccomp
tracelog

whitelist ${DOWNLOADS}
mkdir ~/.8pecxstudios
whitelist ~/.8pecxstudios
mkdir ~/.cache
mkdir ~/.cache/8pecxstudios
mkdir ~/.cache/8pecxstudios/cyberfox
whitelist ~/.cache/8pecxstudios/cyberfox
whitelist ~/dwhelper
whitelist ~/.zotero
whitelist ~/.vimperatorrc
whitelist ~/.vimperator
whitelist ~/.pentadactylrc
whitelist ~/.pentadactyl
whitelist ~/.keysnail.js
whitelist ~/.config/gnome-mplayer
whitelist ~/.cache/gnome-mplayer/plugin
whitelist ~/.pki

# lastpass, keepassx
whitelist ~/.keepassx
whitelist ~/.config/keepassx
whitelist ~/keepassx.kdbx
whitelist ~/.lastpass
whitelist ~/.config/lastpass


#silverlight
whitelist ~/.wine-pipelight
whitelist ~/.wine-pipelight64
whitelist ~/.config/pipelight-widevine
whitelist ~/.config/pipelight-silverlight5.1
witelist ~/Apps
include /etc/firejail/whitelist-common.inc
`````
Run cyberfox:
`````
$ firejail ~/Apps/Cyberfox/Cyberfox
`````

**Comment by hawkeye116477** [comment]
Thanks, after this, displayed "Error access was denied...", but I fixed this by changing line: "noblacklist ~/.8pecxstudios/cyberfox" to "noblacklist ~/.8pecxstudios"

**Comment by netblue30** [comment]
Thanks, I put the "noblacklist" in git also.
