### ISSUE TITLE
allow "join sandbox_name" in .profile

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#651]
I want my app to join other app in named sandbox profile. Now I have to do:

`firejail --join=my_sandbox_name my_app`

I would prefer to setup this in myapp.profile file to automate this process. So the option would be:

`join sandbox_name(pid)`

It would be logical as name option is allowed in .profile and join isn't.

**Comment by netblue30** [comment]
I'll look into it, it depends how the code is in this moment. If it turns out to be an easy fix, I'll put it in.

**Comment by CrisBRM** [comment]
Any news on this?

**Comment by netblue30** [comment]
No, still open.

**Comment by chiraag-nataraj** [comment]
The option `join-or-start` should do what you want.
