### ISSUE TITLE
Comparison with minijail

### ISSUE THREAD

**Issue by fkarl423** [netblue30/firejail#655]
The chromium OS project seems to have developed something quite familiar to firejail that I would like to point out: It's called minijail and also applies seccomp filter to a process.
https://www.chromium.org/chromium-os/developer-guide/chromium-os-sandboxing

Maybe this provides some ideas on what to implement in firejail or maybe it would even be possible to work together and merge both project. No Idead how realistic this is just wanted to point it out.

**Comment by netblue30** [comment]
Thanks for the info.
