### ISSUE TITLE
Is it possible to avoid remounting /proc on an individual basis?

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#669]
...and if so, what security problems could this cause?

I've started back on #435 and I believe the problem all boils down to the symlink ~/.googleearth/instance-running-lock and its target, /proc/12. 
Even when using `firejail --noprofile --debug google-earth`, the /proc directory is remounted:
`Remounting /proc and /proc/sys filesystems`
`Remounting /sys directory`
`...`
`Disable /proc/sys/fs/binfmt_misc`
`Disable /proc/sys/kernel/core_pattern`
`Disable /proc/sys/kernel/modprobe`
`...`

If it were possible to avoid remounting /proc/12, or at the very least /proc,  then it's possible that #435 could be fixed.
So...
is there a command line option in firejail to keep /proc or /proc/12 from being remounted?

Thanks!
Fred

**Comment by manevich** [comment]
I think remounting is not related to this case.
`/proc/12` and other /proc/**_number_** are directories created for each process, and number is PID of process running on system.
From jail you can see only processes running inside (that's one of things we use jail for - to isolate processes).
Same process will have different PID if you look from outside. This is effect of process namespaces, not remounting.

I don't have googleearth installed nor intent to install it, so I can't help you further.

**Comment by netblue30** [comment]
> If it were possible to avoid remounting /proc/12

The kernel does it automatically, no way around it. Try a simple blacklist /proc in the profile, maybe googleearth doesn't crash and doesn't create the lock file.

**Comment by Fred-Barclay** [comment]
Thanks. Since my question is answered I'll close this and use #677 for the issues I'm having with blacklisting /proc. :)
