### ISSUE TITLE
--private fails on linux-ck kernel (Arch Linux)

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#67]
Imported form reddit: https://www.reddit.com/r/linux/comments/3lt0p1/firejail_a_security_sandbox_for_mozilla_firefox/cvb3qo1

**Comment by dosy4ev** [comment]
I use stock archlinux kernel (`4.1.6-1-ARCH` at this moment) and I have this bug too.
So this isn't ck kernel specific.

`--private` works fine for some other app i've tried (pcmanfm, mc).

Output of `firejail --noprofile --private firefox`:
```
Parent pid 30062, child pid 30063
Child process initialized

(process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

parent is shutting down, bye...
```

After that firefox just starts as usual.

Firefox version is `Mozilla Firefox 40.0.3`. Firejail version is `firejail version 0.9.30`.

**Comment by netblue30** [comment]
I think I know what's going on! It is Firefox imposing a single process instance in the system.

By default, the browser uses a single process to handle multiple windows. When you start the browser, if another Firefox process is already running, the existing process opens a new tab or a new window.

Make sure Firefox is not already running when you start it in Firejail sandbox, otherwise you end up with a new window running outside the sandbox. Chromium has the same problem, and quite a number of other programs, most notably file managers.

I'll close the bug for now, we can always reopen it if necessary.
