### ISSUE TITLE
`--audit` does not warn about `--x11` used without `--net`

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#670]
See subject. Since `--x11` is not secure without `--net`, a warning may be appropriate. Especially in `--audit` mode.

**Comment by netblue30** [comment]
I'll add a test to check if x11 socket is present. For --x11 and --net combination I don't know. How do you find out from inside a sandbox if you are in a different network namespace?

**Comment by vn971** [comment]
@netblue30 well, why not do as you said: check x11 socket availability? It's not a strict rule (is it?), but it should work in most cases.

(Actually, I thought --audit works by analyzing the combined commands. But it seems it's a separate executable. Well, OK, that has some advantages, too.)

**Comment by netblue30** [comment]
I made it a separate program so you can switch in your own test program (--audit=program_name)

**Comment by netblue30** [comment]
Fixed:
`````
$ firejail --x11 --audit xterm
Error: auditing x11 sandboxes is not supported
`````

**Comment by vn971** [comment]
@netblue30 eh, I wouldn't mind auditing an X11 app.. Well anyway, if that's the easiest approach, ok.

**Comment by netblue30** [comment]
@manevich just put a fix in, auditing x11 sandboxes is supported in this moment!
