### ISSUE TITLE
Software using libstdc++ breakage on Gentoo (and probably some another distros)

### ISSUE THREAD

**Issue by msva** [netblue30/firejail#674]
Hi there!
https://github.com/netblue30/firejail/commit/ba4ba53e509aebc054f547e3f08470e59e2a6cd4 introducing blacklisting of `/usr/lib/gcc` on line 4.
On gentoo, since there is "slotted" GCC (multiple versions allowed to be installed at the same time and user can select "active" one) there is gcc-libs like `libstdc++`, `libgo`, `libobjc`, `libatomic`, which some software is linked against.
So, with enabled "disable-devel" profile that software stopping to work after mentioned commit.

// By the way, full path to the libraries is `/usr/lib/gcc/x86_64-pc-linux-gnu/<gcc_version>/` and it is added to LD_PATH (to /etc/ld.so.conf, actually).

**Comment by netblue30** [comment]
Moved to https://github.com/netblue30/firejail/issues/824
