### ISSUE TITLE
Closing Xephyr window when exiting?

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#676]
Should firejail close its Xephyr window when exiting? The current version of firejail does NOT close the window (for me).

Behavior in question:
* start firejail with `firejail --noprofile --x11=xephyr xterm`
* close xterm by typing Ctrl+D  (`exit`)
* check out firejail processes. There should be none corresponding to the test
* observe the Xephyr window still active on the desktop, though it does not allocate anything in `/tmp/.X11-unix` anymore.

**Comment by manevich** [comment]
`-terminate` option of `Xephyr` solves this problem.
But, for some reason `-noreset` (opposite of it) was added by default.
[Here](https://github.com/manevich/firejail/commit/5ef59391e909ca4bdc1794b97bb9c829e30276e8) is quick fix.
I don't see negative consequences of this patch.
Please check it, and I will send pull request to upstream.

**Comment by vn971** [comment]
BTW, since we already raised a question on Xephyr parameters.. May it make sense to add a possibility to override firejail Xephyr parameters? Like `xephyr-params-override -fullscreen -terminate` in `firejail.config`.

**Comment by manevich** [comment]
We can just change order of arguments to make `xephyr-extra-params` be last arg before screen number, and they will override hardcoded. See https://github.com/manevich/firejail/commit/531c3401e4ead91118e33610c97128efdc786a53.

**Comment by netblue30** [comment]
all merged in, thanks.
