### ISSUE TITLE
`--blacklist=/proc` does not blacklist all of /proc

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#677]
When I try `firejail --blacklist=/proc` and then `ls /proc` there are still 58 files and directories visible inside the sandbox. It's certainly a lot fewer than the 244 files/directories that are visible outside the sandbox, but is this normal/expected?
Blacklisting practically any other directory hides the contents entirely, unless I blacklist something important like /bin which won't allow /bin/bash to run inside firejail.

**Comment by reinerh** [comment]
A lot of /proc files are actually needed by many programs to work correctly.

**Comment by netblue30** [comment]
Fixed. Keep an eye on closing the sandbox, my monitoring program depends on reading /proc to see if the sandbox is still alive. You'll get some error messages when you close the program, just disregard them for now.

**Comment by Fred-Barclay** [comment]
Forgot to say earlier... thanks, mate! :+1:

**Comment by netblue30** [comment]
No problem.
