### ISSUE TITLE
--private-bin does not warn for non-existing programmes

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#678]
G'day guys! I found this while trying to correct a mistake I had made with the warzone2100 profile: the line`private-bin warzone2100`

Now warzone2100 is **not** installed to /bin, /usr/bin, and so on; it's in /usr/games. 
`fred@<redacted> ~ $ which warzone2100`
`/usr/games/warzone2100`
When I realised this, I thought initially that `--private-bin` might include /usr/games as well, but after glancing over src/firejail/fs_bin.c it doesn't appear that this is the case, unless I missed something.

After checking gnome-chess, which is also in /usr/games/, `--private-bin` works without a hitch:
`firejail --debug --private-bin=gnome-chess --shell=none gnome-chess`

So my question is, shouldn't private-bin warn and/or exit with a warning for cases like this when there isn't a corresponding programme in a *bin directory?

**Comment by netblue30** [comment]
It is in fact a bug, I don't have /usr/games in the list, that's why it doesn't find warzone2100. This is the list in this moment:
`````
static char *paths[] = {
	"/usr/local/bin",
	"/usr/bin",
	"/bin",
	"/usr/local/sbin",
	"/usr/sbin",
	"/sbin",
	NULL
};
`````
There was also a warning at some point, but it is commented out for some reason. I'll bring back the warning.

**Comment by Fred-Barclay** [comment]
Would it be a good idea to add /usr/games to the list of private-bin? This would allow us to have the benefits of private-bin for many games.

**Comment by netblue30** [comment]
I added /usr/games and /usr/local/games. 

If you add --debug on the command line, you will get a warning if the program is not found. I cannot show the message by default, there are cases when you have a longer program list that covers multiple Linux distributions. It is the same for --private-etc, where each distro has a different set of files in /etc, and you are forced to have in your profile file a long list that covers all of them.
