### ISSUE TITLE
Warning: /sbin and /usr/sbin not blacklisted

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#68]
I just executed Firefox in the console and got this:

>firejail firefox
Reading profile /home/xxx/.config/firejail/firefox.profile
Reading profile /home/xxx/.config/firejail/myrules.inc
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-history.inc
Warning: user namespaces not available in the current kernel.
Parent pid 2318, child pid 2319
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted

I got the same problem when I executed any other firejailed application. (That user namespaces are not suuported is normal as I'm using Arch Linux). Something is wrong here ...

**Comment by bchretien** [comment]
On Arch, all the system bin directories point to `/usr/bin`:

`/bin -> /usr/bin`
`/sbin -> /usr/bin`
 `/usr/sbin -> /usr/bin`

And it seems to be the reason for this warning (cf. [here](https://github.com/netblue30/firejail/blob/491b8f2390c456d55ad49c333c1cc42cf7dd116e/src/firejail/fs.c#L157-L161)).

**Comment by netblue30** [comment]
Yes, I had to disable the blacklisting. It affects Arch, Fedora, RHEL.

**Comment by curiosity-seeker** [comment]
I understand. Thanks for this hint!
