### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by stelariusinfinitek** [netblue30/firejail#680]
I'm trying to build firejail-git from AUR and it gives me an error. It worked before, I don't think it's something wrong with the pkgbuild.  
  
Here are some details which can be useful : 

![2016-08-04-030235_1366x768_scrot](https://cloud.githubusercontent.com/assets/18717816/17386126/3a52e5e2-59f0-11e6-9976-ca75304b4168.png)

**Comment by netblue30** [comment]
I put a fix in, thank you for the bug.
