### ISSUE TITLE
`--overlay` creates files owned by root. Should it?

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#685]
see subj. It's a bit inconvenient because I can't delete files then.
Thoughts?

**Comment by netblue30** [comment]
I need it as root, otherwise overlayfs will not work. I put in a new command line option --overlay-clean that removes all the overlays in ~/.firejail

**Comment by vn971** [comment]
@netblue30 can firejail make all directory owners as `root:user`, and make the group able to modify the files (`chmod g+rw`)?

**Comment by netblue30** [comment]
I'll look into it, but is very unlikely. It has something to do with the way they implemented overlayfs.
