### ISSUE TITLE
detecting malware?

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#686]
Can firejail log policy violations or otherwise alert the user to bugs or malicious activity?

**Comment by manevich** [comment]
See `--tracelog` option. But note - this is implemented using `LD_PRELOAD` and it's not too hard to get round for malware, AFAIK.

**Comment by manevich** [comment]
> implemented using LD_PRELOAD
Actually `/etc/ld.so.preload`. (I was answering late at night)

**Comment by chiraag-nataraj** [comment]
@xahare it's easier to just whitelist the behaviors you want the program to have access to than to try to heuristically detect whether it's acting maliciously. For example, I quarantine my browser (Firefox) to my Downloads directory (and its configuration files) and a `private-tmp` as well as limit the binaries and files in /etc that it has access to. I also disable the root user and don't give it access to a shell (it doesn't need one). This is in addition to using addons like uMatrix to limit the number and scope of scripts that run on a page. Basically, my point is that it's easier (although quite tedious) to think about the behaviors you want and to whitelist them than to try to figure out if some specific behavior you saw is malicious (even if you're the one trawling through the logs - and `firejail` has pretty detailed logging).

**Comment by xahare** [comment]
@chiraag-nataraj that sounds awsome! can you gist your firefox setup? 

But, the point of this isn't better protection. its knowing when somethings wrong that you would otherwise miss.

**Comment by chiraag-nataraj** [comment]
So my profile is attached.

The list of privacy/security addons I use in Firefox (mainly for privacy, but they also provide some added security):
Decentraleyes (https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/)
Disconnect (https://addons.mozilla.org/en-US/firefox/addon/disconnect/)
RequestPolicy (https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/)
Self-Destructing Cookies (https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/)
uBlock Origin (https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)
uMatrix (https://addons.mozilla.org/en-US/firefox/addon/umatrix/)
[firefox.txt](https://github.com/netblue30/firejail/files/413401/firefox.txt)
