### ISSUE TITLE
Running docker via firejail 

### ISSUE THREAD

**Issue by agamdua** [netblue30/firejail#692]
This is not an "issue" - just trying to understand something and was directed here from the support page.

On the FAQ there's a [section](https://firejail.wordpress.com/support/frequently-asked-questions/#docker) mentioning that docker can be run under firejail, and with the below command I can definitely do that.

```shell
$ sudo firejail --private docker run hello-world
```
Is there a point to still use it this way if I have to use `sudo` to be root for docker anyway?

**Comment by netblue30** [comment]
It wouldn't make sense to run it this way. I've seen people doing the other way around: start docker, and inside docker, as root, they run the server programs under firejail. You can also use a docker filesystem and mount it in firejail using --chroot, but you still have to be root to do it and start programs in the jail.

**Comment by agamdua** [comment]
So I tried something which seems to suggest there is _some_ benefit:

```
# let's see whats currently in my /home
$ ls -al /home/
total 16
drwxr-xr-x  4 root    root    4096 Aug  8 01:51 .
drwxr-xr-x 23 root    root    4096 Aug  8 01:35 ..
drwxr-xr-x  4 vagrant vagrant 4096 Aug  8 01:50 vagrant
drwxr-xr-x  2 root    root    4096 Aug  8 01:59 workspace
```

Now I want to see what happens to root while in a firejail:
```
vagrant@vagrant:~$ sudo firejail --private --noprofile
Parent pid 8022, child pid 8023
The new log directory is /proc/8023/root/var/log

Child process initialized
[root@vagrant root]$ cd /home/
[root@vagrant home]$ ls
[root@vagrant home]$ mkdir dummy
[root@vagrant home]$ ls
dummy
[root@vagrant home]$ exit
exit

parent is shutting down, bye...
```

Apparently at this stage it cannot really see anything else apart from what is in the current firejail "session". That's odd, because above we see that `workspace` is owned by `root:root`.

If we switch to `root` and `ls` yet again:
```
vagrant@vagrant:~$ sudo su
root@vagrant:/home/vagrant# ls -al /home/
total 16
drwxr-xr-x  4 root    root    4096 Aug  8 01:51 .
drwxr-xr-x 23 root    root    4096 Aug  8 01:35 ..
drwxr-xr-x  4 vagrant vagrant 4096 Aug  8 01:50 vagrant
drwxr-xr-x  2 root    root    4096 Aug  8 01:59 workspace
root@vagrant:/home/vagrant# 
```

Interestingly enough,  it can see everything from before the "session", but the `dummy` dir never gets created.

**Comment by netblue30** [comment]
In your case, a tmpfs filesystem is mounted on top of /home in order to protect the existing user accounts. All new files you bring under /home will get lost when you close the sandbox.

**Comment by agamdua** [comment]
I am not extremely familiar with this vs the alternatives like app armor - I am looking these things up and reading into docker

**Comment by agamdua** [comment]
> tmpfs filesystem is mounted on top of /home

I see - I am able to create things in `/` that persist.

Would it be smarter to just build docker with seccomp and configure it via this: https://docs.docker.com/engine/security/seccomp/ ?

Thanks for answering the questions - its helped clear the confusion!

**Comment by netblue30** [comment]
It depends what you need it for. If you are looking for a visualization solution you stay with docker and configure seccomp, capabilities, SELinux or AppArmor and everything else they have available. Or you can start your server under firejail inside your docker container. Firejail is strictly a security solution.  it has some virtualization features but it doesn't come close to docker.
