### ISSUE TITLE
Firejail crashes pulseaudio / pavucontrol

### ISSUE THREAD

**Issue by Utini2000** [netblue30/firejail#70]
Hey there, I am on arch linux and whenever I run firejail (e.g. "firejail vlc") it will crash pulseaudio / pavucontrol. 

Is there anything I can do to provide more information?

Thanks !

**Comment by netblue30** [comment]
Duplicate of this bug:

https://github.com/netblue30/firejail/issues/69

The workaround for now is to put srbchannel=no into /etc/pulse/default.pa and restart the box.

**Comment by Utini2000** [comment]
Thanks !

**Comment by Utini2000** [comment]
writing srbchannel = no into the /etc/pulse/default.pa makes it impossible to start the daemon.
