### ISSUE TITLE
whitelisting /home/myuser not possible

### ISSUE THREAD

**Issue by frank-github** [netblue30/firejail#700]
firejail --noprofile --whitelist=/home/myuser bash
firejail --noprofile --noblacklist=/home/myuser bash

but /home is still empty and firejail has mount a tempory home

how can I config firejail to let /home untouched/readable?

**Comment by chiraag-nataraj** [comment]
The first gave me:
````
Parent pid 8797, child pid 8798
Error: file /home/chiraag is not in user home directory, exiting...
Error: cannot establish communication with the parent, exiting...
````
The second worked.
I'm using firejail 0.9.42~rc1

**Comment by frank-github** [comment]
hupps, forgot to write my used version :(

firejail version 0.9.40
maybe I have to wait for 0.9.42

**Comment by manevich** [comment]
@frank-github What you are trying to do?
If `/home/myuser` is your home directory, then `firejail --noprofile` gives you full access to files in your home.

**Comment by frank-github** [comment]
> is it your home?
yes and no   
/home/myuser is a symlink to another filesystem, where the real home-dir is located

fgrep myuser /etc/passwd
myuser:x:1000:1000:myuser,,,,:/media/daten/myuser:/bin/bash

/home$ ls -l
lrwxrwxrwx  1 root  root   18 Apr 27  2014 myuser -> /media/daten/myuser

I want to run my pdfviewer behind firejail. but I doesn't find anything, if it is called with a file like /home/myuser/example.pdf
firejail create a temporary /home, which is empty

**Comment by manevich** [comment]
> lrwxrwxrwx 1 root root 18 Apr 27 2014 myuser -> /media/daten/myuser

This is cause of problem. Firejail, for obvious reasons, is very strict when it comes to symlinks.
If I recall correctly, there was already some some talk about this matter.

**Comment by manevich** [comment]
Here is it https://github.com/netblue30/firejail/issues/277.

**Comment by netblue30** [comment]
Yes, at this time we don't support home directories as symlinks.

**Comment by frank-github** [comment]
if I would use a mountpoint for my home instead of a symlink, would this be supported by firejail?

**Comment by manevich** [comment]
>if I would use a mountpoint for my /home/myuser instead of a symlink, would this be supported by firejail?

This should work.

**Comment by frank-github** [comment]
mountpoint works  :+1: 

thanks for all the help
