### ISSUE TITLE
Login shells through FireJail - Interpreter initialization files are never read

### ISSUE THREAD

**Issue by nuxwin** [netblue30/firejail#704]
**Current behavior**

When using Firejail for login shells (login.users), interpreter initialization files ( /etc/profile or any of the personal initialization files ~/.bash_profile, ~/.bash_login, or ~/.profile), depending on the interpreter in use (Bash, Dash, ASH ...), are never read.

**Expected behavior**

Interpreter initialization files should be read.

**Comment by nuxwin** [comment]
@netblue30 

my workaround for now:

login.users
```
nuxwin:--chroot=/var/chroot/InstantSSH/shared_jail --name=nuxwin --shell=/bin/bash -- /bin/bash --login
```

But I would prefer see firejail to do the job.

**Comment by netblue30** [comment]
I think I have a fix, you can give it a try. Somehow it ends up calling both .bash_profile and .bashrc:
`````
l$ /usr/bin/ssh bingo@0
bingo@0's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Aug 14 15:30:53 2016 from localhost
I am inside .bash_profile
I am inside .bashrc
[bingo@debian ~]$ 

`````

**Comment by nuxwin** [comment]
@netblue30 

I'll check now. Hope that /etc/profile is read as well in case .bash_profile and .bashrc and missing.

**Comment by nuxwin** [comment]
@netblue30 

- Doesn't work with ASH (busybox). I think that you cannot mix `-c`  and `-l`. Anyway, in the context of a login_shell I think that we should discard additional argv (we should only allow firejail option in that context). This would also solve next point.
- You increased index size by 1 but you forgot to increment assert test and therefore, assert fail when adding additionnal command after double-dash. See below:

Current result:
```
nuxwin@dev:~$ ssh nuxwin@192.168.1.133
nuxwin@192.168.1.133's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

Last login: Mon Aug 15 00:01:28 2016 from 192.168.1.100
-firejail: sandbox.c:343: start_application: Assertion `index < 5' failed.
Connection to 192.168.1.133 closed.
```

**Expected behavior**

After fixing the assert:
```
nuxwin@dev:~$ ssh nuxwin@192.168.1.133
nuxwin@192.168.1.133's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

Last login: Mon Aug 15 00:02:07 2016 from 192.168.1.100
execvp argument 0: /bin/sh
execvp argument 1: -l
execvp argument 2: -c
execvp argument 3: --
execvp argument 4: '/bin/sh' '-l' 


BusyBox v1.22.1 (Debian 1:1.22.0-9+deb8u1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

nuxwin@srv01:/home/nuxwin$
```

I've a fix. I'll do a PR in few minutes with explanations here.

**Comment by nuxwin** [comment]
@netblue30 

See https://github.com/netblue30/firejail/pull/714

**Summary**

- In login shell context and if no `cfg.command_line` is passed in (either through SSH or in the login.users file), we start the shell with the `-l` option without further argument
- In case a command is passed-in (either through SSH or in the login.users file), we run that command through `cfg.shell` as usually, using the `-c` option

**Examples**

```
nuxwin@dev:~$ ssh nuxwin@192.168.1.133
nuxwin@192.168.1.133's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

Last login: Mon Aug 15 00:47:10 2016 from 192.168.1.100
Starting /bin/ash login shell
sandbox 31887, execvp into /bin/ash
execvp argument 0: /bin/ash
execvp argument 1: -l


BusyBox v1.22.1 (Debian 1:1.22.0-9+deb8u1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

nuxwin@srv01:/home/nuxwin$ exit

```
Note that here, the initialization files are read.

```
Connection to 192.168.1.133 closed.
nuxwin@dev:~$ ssh nuxwin@192.168.1.133 date
nuxwin@192.168.1.133's password: 
Running 'date'  command line through /bin/ash
sandbox 31904, execvp into 'date' 
execvp argument 0: /bin/ash
execvp argument 1: -c
execvp argument 2: 'date' 
Mon Aug 15 00:47:37 CEST 2016
nuxwin@dev:~$
```

Note that here, the initialization files are not read. This shouldn't be an issue since the shell will terminate immediately after running `cfg.command_line`.

**Comment by netblue30** [comment]
I think there is more to come, now it doesn't work for me, it goes directly to .bashrc. I'll look into it tomorrow.

**Comment by nuxwin** [comment]
@netblue30 

I'll have a look too.

**Comment by nuxwin** [comment]
@netblue30 

I've just tested with current master. For me, there is no problem.

First of all: `.bashrc` must be run only in case of non-login shell.

.bashrc:
```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
....
```

To simulate a non-login shell, I've set my `login.users` file as follow:

```
nuxwin:--chroot=/var/chroot/InstantSSH/shared_jail --rmenv=PROMPT_COMMAND date
```

Then, I get the following result:

```
nuxwin@dev:~$ ssh nuxwin@192.168.1.133
nuxwin@192.168.1.133's password: 

  ___           _              _     ____ ____  _   _
 |_ _|_ __  ___| |_ __ _ _ __ | |_  / ___/ ___|| | | |
  | || '_ \/ __| __/ _` | '_ \| __| \___ \___ \| |_| |
  | || | | \__ \ || (_| | | | | |_   ___) |__) |  _  |
 |___|_| |_|___/\__\__,_|_| |_|\__| |____/____/|_| |_|


Welcome to your shell.

If you need a specific command, get in contact with your reseller.

i-MSCP InstantSSH plugin v4.1.0
Copyright (c) 2014-2016 Laurent Declercq <l.declercq@nuxwin.com>

Last login: Mon Aug 15 16:36:55 2016 from 192.168.1.100
Running 'date'  command through /bin/bash
sandbox 26218, execvp into 'date' execvp argument 0: /bin/bash
execvp argument 1: -c
execvp argument 2: 'date' 
Reading /home/nuxwin/.bashrc
Mon Aug 15 16:40:12 CEST 2016
Connection to 192.168.1.133 closed.
nuxwin@dev:~$
```

As you can see here, only the `.bashrc` is read. The date command is run and the session terminate immediately. Here we are in a non-login context and therefore, `/etc/profile` and `/home/nuxwin/.profile` are not read. 

Now, if I don't put any command (true login shell context):
```
nuxwin:--chroot=/var/chroot/InstantSSH/shared_jail --rmenv=PROMPT_COMMAND
```

We get the following result:
```
nuxwin@192.168.1.133's password: 

  ___           _              _     ____ ____  _   _
 |_ _|_ __  ___| |_ __ _ _ __ | |_  / ___/ ___|| | | |
  | || '_ \/ __| __/ _` | '_ \| __| \___ \___ \| |_| |
  | || | | \__ \ || (_| | | | | |_   ___) |__) |  _  |
 |___|_| |_|___/\__\__,_|_| |_|\__| |____/____/|_| |_|


Welcome to your shell.

If you need a specific command, get in contact with your reseller.

i-MSCP InstantSSH plugin v4.1.0
Copyright (c) 2014-2016 Laurent Declercq <l.declercq@nuxwin.com>

Last login: Mon Aug 15 16:40:12 2016 from 192.168.1.100
Starting /bin/bash login shell
sandbox 26227, execvp into /bin/bashexecvp argument 0: /bin/bash
execvp argument 1: -l
reading /etc/profile
reading /home/nunxwin/.profile
nuxwin@srv01:~$
```

As you can see here, `.bashrc` is not read. That is expected because `.bashrc` must be read only in context of  non-login shells. However, since we are in login shell context, both `/etc/profile` and `/home/nuxwin/.profile` are read.

Implementation is simple here: If the `-c` option is used, we are not in login shell context. This is same as Bash (and other shells) implementations.

**Comment by nuxwin** [comment]
@netblue30 

If you want we can add a switch allowing to enforce login shell  (adding -i option). I can do that.

**Comment by netblue30** [comment]
I put in some fixes, also the green prompt was removed.

**Comment by netblue30** [comment]
Got your email, don't worry about it, it's not a problem. Let's reset and move to this thread: https://github.com/netblue30/firejail/issues/719
