### ISSUE TITLE
"make deb" fails

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#705]
I'm trying to compile a .deb from the latest source code from GitHub and `make deb` is failing:
`cp -a ""src etc platform configure configure.ac Makefile.in install.sh mkman.sh mketc.sh mkdeb.sh mkuid.sh COPYING README RELNOTES"" firejail-0.9.42~rc2`
`cp -a ""test/apps test/apps-x11 test/environment test/profiles test/utils test/compile test/dist-compile test/filters test/network test/fs test/sysutils"" firejail-0.9.42~rc2/test`
`cp: cannot stat ‘test/compile’: No such file or directory`
`Makefile:144: recipe for target 'dist' failed`
`make: *** [dist] Error 1`

The entire output is at https://gist.github.com/Fred-Barclay/6afe782f48fc22a6e639b006de7f7a16

I suspect, but don't know, that `make install` or `make <something>` will behave the same way; though a simple `make` does not throw this error.

**Comment by netblue30** [comment]
Fixed!

**Comment by Fred-Barclay** [comment]
Perfect, thanks mate. :)
