### ISSUE TITLE
Option to disable warnings/errors in production environments

### ISSUE THREAD

**Issue by nuxwin** [netblue30/firejail#708]
Hello,

We use FireJail to provide restricted login shells to our users with the `--chroot` option. When a user is connecting through SSH, the following warning is always shown:

```
Warning: default profile disabled by --chroot option
```

Also, other warnings (or errors) related to a misconfiguration (or any other problem) are always shown.

Those warnings (or errors) should be hidden in production environment where the end-users don't care about them (case of a shared hosting environment). Currently the only way to hide the warning shown above is to add the `--noprofile` option or by adding custom profile but this applies only to this warning.

Please add an option to hide any warning and or error in production environments. Note that the `--quiet` option has not effect.

Thank you for your interest.

**Comment by netblue30** [comment]
It is a bug, this warning should go under --quiet. I'll bring in a fix shortly.

Probably there are more like it. The idea is to have only catastrophic things escaping quiet. Let me know if you run into anything else.

**Comment by nuxwin** [comment]
Fixed in master. Thanks. I don't close that ticket because as you said, There is probably more issues like this. You're free to close that issue.

**Comment by netblue30** [comment]
All fixed, thanks for the bug.
