### ISSUE TITLE
GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

### ISSUE THREAD

**Issue by BCOH** [netblue30/firejail#71]
I am getting a the following error when I try to start firejail and firefox. I have replaced the firefox firejail profile with one copied from the word-press site. The new profile resolved an error about line 2 in the profile. Now I am getting the error below. I have reinstalled Firejail 0.9.30_1_amd64.deb with no resolution.

$ firejail firefox
Reading profile /etc/firejail/firefox.profile
Parent pid 77, child pid 78
Child process initialized

(process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

parent is shutting down, bye...
$

Thanks in advance

Brian

**Comment by netblue30** [comment]
I get "GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed" with or without firejail on my Debian machine. This is a Firefox problem. It is just a warning, disregard it.

> parent is shutting down, bye...

This means Firefox went down. By default, Firefox browser uses a single process to handle multiple windows. When you start the browser, if another Firefox process is already running, the existing process opens a new tab or a new window, and the new process exits. Make sure Firefox is not already running when you start it in Firejail sandbox.
