### ISSUE TITLE
Question about PS1 / PROMPT_COMMAND

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#710]
A user asked on the Debian BTS [1] why PS1 is forced when spawning a shell, and if it can be disabled (or made configurable), as it might be customized by the user to indicate something, which would be hidden by firejail.

Can you please explain why it is currently changed?

1: https://bugs.debian.org/834256

**Comment by nuxwin** [comment]
@reinerh 

See also https://github.com/netblue30/firejail/issues/704

@netblue30 Indirectly related ;)

**Comment by nuxwin** [comment]
@netblue30 

I think that you should not set the PROMPT_COMMAND environment variable in mainline. Instead, you should simply call interpreters with the `-` character as unique argument, excepted if the called firejail with argument that are not firejail options.

**Comment by netblue30** [comment]
I just needed some sort of indication I am in a sandbox, so I made the prompt green. I'll add a config option in /etc/firejail/firejail.config. I already have something similar to disable the title of x11 window when running xephyr.

**Comment by nuxwin** [comment]
@netblue30 

Well, hardocing the prompt with color in mainline is really a bad thing for many reasons:

- Normally, colored prompt should be set through interpreter initialization files. (Once #704 willl be fixed, you'll be able to set the prompt colors through the .profile file).
- Hard coding color in mainline involve that `tput` and `terminfo` are always available. That is not always the case.

**Comment by netblue30** [comment]
The prompt was removed!
