### ISSUE TITLE
forum for firejail? is this it?

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#715]
Would be nice to have a forum for firejail without cluttering up the issues. Or maybe issues is the best place. at least its unambiguous, already tracked (you get notifications), and theres only one place to look. 

otherwise, https://groups.google.com/ ? that one works as mailing list so you can use mutt, thunderbird etc and dont need a google account to participate, but if you like online forums you can use its nice web gui.

**Comment by netblue30** [comment]
I would say you can ask any questions here.
