### ISSUE TITLE
Restricted shell status

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#719]
Functionality:

1. sftp and scp - are started outside the sandbox
2. simple login: ssh test@0 - the session is started with "-l" flag
3. simple command: ssh test@0 date - the session is started with "-c" flag
4. multiple commands: ssh test@0 "date && date" - the session is started with "-c" flag
5. 1, 2, 3, 4 with or without an entry in /etc/firejail/login.users
6. 1, 2, 3, 4 with various --shell entries in /etc/firejail/login.users

1, 2, 3, 5 are working fine. I didn't test anything for 6 yet. Currently 4 is broken. It is broken even for regular firejail sessions, example:
`````
$ firejail -c "date && date"
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 4641, child pid 4642
Child process initialized
/bin/bash: date && date: command not found

Parent is shutting down, bye...
`````

**Comment by FOSSONLY** [comment]
Hello, what's the current status of that functionality? Is firejail nowdays save to use as restricted shell?

**Comment by netblue30** [comment]
yes, it should be fine.
