### ISSUE TITLE
Wishlist: easier way to allow additional system calls

### ISSUE THREAD

**Issue by lheckemann** [netblue30/firejail#730]
For debugging software within jails, I like to be able to use tools like strace and gdb, which use the `ptrace` system call. However, I currently don't know of a way of allowing ptrace while keeping seccomp enabled without copying the default list of blocked system calls and removing ptrace, which makes for extremely unwieldy command lines. Something like `--seccomp.blacklist=!ptrace` or `--seccomp.allow=ptrace` would be nice (as opposed to `--seccomp.keep=ptrace` which seems to allow nothing but ptrace...).

Or would it make more sense to use gdb on firejail and skip ahead to the `exec` system call when doing this?

**Comment by Fred-Barclay** [comment]
Would `--seccomp.keep=ptrace` do what you're looking for?

```
 --seccomp.keep=syscall,syscall,syscall
              Enable seccomp filter, and whitelist the syscalls specified by the command.

              Example:
              $ firejail --shell=none --seccomp.keep=poll,select,[...] transmission-gtk
```

**Comment by lheckemann** [comment]
That results in the following seccomp filter:
```
  VALIDATE_ARCHITECTURE
  EXAMINE_SYSCAL
  WHITELIST 105 setuid
  WHITELIST 106 setgid
  WHITELIST 116 setgroups
  WHITELIST 32 dup
  WHITELIST 101 ptrace
  KILL_PROCESS
```
Which allows nothing but ptrace, causing such things as executing a shell, opening a file, or even writing to a previously opened file to fail. I meant to write `--seccomp.keep`, not `--seccomp.whitelist` in the initial comment (fixed).

**Comment by netblue30** [comment]
Unfortunately, just allowing ptrace syscall will not be enough. It also needs to be able to run SUID binaries inside the sandbox - strace is SUID. This is how you can run it:
`````
$ sudo strace -f firejail --noprofile application
`````
Or you can just start a sandbox with --noprofile and run strace inside the sandbox:
`````
$ firejail --noprofile
Parent pid 9690, child pid 9691
Child process initialized
netblue@debian:~/work/github/firejail$ strace -f application
`````
I'll add a description in FAQ.

**Comment by lheckemann** [comment]
strace isn't SUID on my system, and I don't see any reason why it would need to be.
`firejail --ignore=seccomp --noblacklist=/usr/bin/strace strace echo hello` works just fine for me...

**Comment by netblue30** [comment]
You are right, I forgot about the blacklist! I'll bring a command line flag in, something like "firejail --debug-ptrace [...] application"

**Comment by lheckemann** [comment]
Wouldn't it be better to have a more generic option like `--seccomp.add=ptrace` so that we can make use of the standard blacklist, unblocking individual calls?

**Comment by netblue30** [comment]
> Wouldn't it be better to have a more generic option like --seccomp.add=ptrace so that we can make use of the standard blacklist, unblocking individual calls?

Probably, but it will complicate the code - we are still SUID, so we need to keep it as simple as possible.
OK, it will be --allow-debuggers

**Comment by netblue30** [comment]
All set, you can try it out.
`````
$ man firejail
[...]
      --allow-debuggers
              Allow tools such as strace and gdb inside the sandbox.

              Example:
              $  firejail  --allow-debuggers --profile=/etc/firejail/firefox.profile strace -f firefox
[...]
`````

**Comment by lheckemann** [comment]
Great, thanks!
