### ISSUE TITLE
Kernel fix found for known problem, "Cannot install new software while Firejail is running"

### ISSUE THREAD

**Issue by david-drinn** [netblue30/firejail#731]
This strikes me as exactly the kernel fix needed for the aforementioned firejail [known problem](https://firejail.wordpress.com/support/known-problems/#removeblacklisted):

> [vfs: Lazily remove mounts on unlinked files and directories.](https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?h=linux-3.18.y&id=8ed936b5671bfb33d89bc60bdcc7cf0470ba52fe)
>
>With the introduction of mount namespaces and bind mounts it became possible to access files and directories that on some paths are mount points but are not mount points on other paths.  It is very confusing when rm -rf somedir returns -EBUSY simply because somedir is mounted somewhere else.  With the addition of user namespaces allowing unprivileged mounts this condition has gone from annoying to allowing a DOS attack on other users in the system.
>
>The possibility for mischief is removed by updating the vfs to support rename, unlink and rmdir on a dentry that is a mountpoint and by lazily unmounting mountpoints on deleted dentries.
>
>...

I wanted to share the knowledge in case it helps you devise a tweak to the way firejail blacklists files, or at the very least so others know which patch they need to backport to older kernels.

**Comment by netblue30** [comment]
Thank you for the info, I'll modify known problem page.
