### ISSUE TITLE
how are unix sockets handled outside of the whitelist?

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#733]
can a firejailed with whitelists read from a unix socket outside its whitelists? for example, can firefox mess with /tmp/ssh-*

for now, my firefox profile looks like this. (i still call it with private, net, and x11)
```
blacklist /tmp/ssh-*
include /etc/firejail/firefox.profile
```

**Comment by netblue30** [comment]
I'll have to blacklist /tmp/ssh-* in all browser profiles, thanks for the idea. If you use firejail --net=... all unix sockets are disabled.

**Comment by xahare** [comment]
how about the top secret section of disable-common? wouldn't want the gimp in my ssh either.

**Comment by chiraag-nataraj** [comment]
> how about the top secret section of disable-common? wouldn't want the gimp in my ssh either.

re gimp specifically: just use `net none` in the profile - there's generally no reason gimp should have internet access :wink:

**Comment by xahare** [comment]
even without internet access, i dont that gimp in my sockets ;)

1. evil file opened by gimp (or evince, totem, libreoffice etc)
2. evil gimp extracts ssh key (some unknown vuln)
3. insert favorite covert channel here
4. all your base are belong to us

**Comment by chiraag-nataraj** [comment]
That's true, but they can't actually get anything out to the world though since gimp won't have internet access :wink:

**Comment by xahare** [comment]
3. insert favorite covert channel here

for example steganography. its a matter of least access required. 

so really, the gimp should have a private temp. o,r one shared by apps your using with it, like blender calling it for texture painting.

**Comment by chiraag-nataraj** [comment]
Oh man, interesting point - I didn't realize there are people who are more paranoid than me :laugh:

Just as a note, though, the biggest attack vectors are your email client and your web browser. Generally speaking, people don't normally go through images to steal information - they just hack in through an ssh back-door :wink:

**Comment by netblue30** [comment]
OK, we disable them all over the place in disable-common.inc

**Comment by netblue30** [comment]
I've disabled them in disable-programs.inc and modified ssh.profile.
