### ISSUE TITLE
lots of terms in disabled common. regexp?

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#737]
would this regexp work? you missed xterm and rxvt in the list.

```
# disable terminals running as server resulting in sandbox escape
blacklist ${PATH}/*term*
blacklist ${PATH}/*rxvt*

```

**Comment by Fred-Barclay** [comment]
G'day xahare! I was the one who blacklisted those terminals (so the blame for missing any belongs to me). I don't know anything about rxvt, but I do know that xterm did not escape the sandbox and thus doesn't need to be blacklisted in /etc/disable-common.inc. 

Here's a short test you can use to see if a terminal program is capable of escaping firejail and needs to be blacklisted:

`firejail <terminal-program>`
In the new terminal window that should come up, try the following:
`ls ~/.gnupg`

If you get a message `ls: cannot open directory .gnupg: Permission denied` then the terminal cannot escape the sandbox (at least not by this method) and it does not need to be blacklisted in etc/disable-common.inc. If on the other hand you can see the contents of .gnupg, then the terminal should be blacklisted. 

Hope this helps! :smile:

**Comment by xahare** [comment]
it seems blunt to make a list based on properties that can change out from under us or vary by distro. there must be a more programatic way. what causes those terminals to escape? maybe that can be blocked.

if nothing else, some automated test at boot could write those files.

**Comment by Fred-Barclay** [comment]
I agree, but unfortunately that seems to be the best way right now. These have been tested on multiple distros so I'm pretty confident that the patch works for all distros. 
You may be interested in #472 . If so, pay particular attention to what @netblue30 says. The real problem lies with these terminals, not firejail. The most we can do is patch bad behaviour, not prevent it.

**Comment by netblue30** [comment]
Some terminals allow the user to escape the sandbox, this is why we disabled some of them. xterm and rxvt are safe.
