### ISSUE TITLE
Invalid whitelist path

### ISSUE THREAD

**Issue by DDoubleU** [netblue30/firejail#739]
Hi,
I want to use Firejail for Spotify as well, but had to change the profile because I added some local files to it. These are located on an NTFS volume mounted to /mnt/Data.
After updating the profile I resulted in the following error:

`$ firejail spotify`
`Reading profile /etc/firejail/spotify.profile`
`Reading profile /etc/firejail/disable-common.inc`
`Reading profile /etc/firejail/disable-programs.inc`
`Reading profile /etc/firejail/disable-devel.inc`
`Reading profile /etc/firejail/disable-passwdmgr.inc`
`Reading profile /etc/firejail/whitelist-common.inc`
`Warning: user namespaces not available in the current kernel.`
`Parent pid 1257, child pid 1258`
`Error: invalid whitelist path /mnt/Data/Spotify-local`
`Error: cannot establish communication with the parent, exiting...`

The only thing I changed was this:

`whitelist ${HOME}/.config/spotify`
`whitelist ${HOME}/.local/share/spotify`
`whitelist ${HOME}/.cache/spotify`
`whitelist** /mnt/Data/Spotify-local`

Do you have any idea what might be the cause of this?
Thanks in advance!

**Comment by Fred-Barclay** [comment]
Hey mate! Could you post your entire spotify profile? I think I see what the problem is but I want to make sure. :)
Also, what version of firejail are you using? `firejail --version` if you're not sure.

**Comment by netblue30** [comment]
It could be because of NTFS, I'll have to give it a try.

**Comment by DDoubleU** [comment]
My apologies, I was a bit brief in my opening post. The entire spotify.profile file looks as following:

`# Spotify media player profile`
`noblacklist ${HOME}/.config/spotify`
`noblacklist ${HOME}/.cache/spotify`
`noblacklist ${HOME}/.local/share/spotify`
`include /etc/firejail/disable-common.inc`
`include /etc/firejail/disable-programs.inc`
`include /etc/firejail/disable-devel.inc`
`include /etc/firejail/disable-passwdmgr.inc`
` `
`# Whitelist the folders needed by Spotify - This is more restrictive `
`# than a blacklist though, but this is all spotify requires for `
`# streaming audio`
`mkdir ${HOME}/.config`
`mkdir ${HOME}/.config/spotify`
`whitelist ${HOME}/.config/spotify`
`mkdir ${HOME}/.local`
`mkdir ${HOME}/.local/share`
`mkdir ${HOME}/.local/share/spotify`
`whitelist ${HOME}/.local/share/spotify`
`mkdir ${HOME}/.cache`
`mkdir ${HOME}/.cache/spotify`
`whitelist ${HOME}/.cache/spotify`
`whitelist /mnt/Data/Spotify-local`
`include /etc/firejail/whitelist-common.inc`
` `
`caps.drop all`
`seccomp`
`protocol unix,inet,inet6,netlink`
`netfilter`
`nonewprivs`
`noroot`

The version of Firejail I'm using is 0.9.40.

I mount the NTFS volume using NTFS-3g (version 2016.2.22).

**Comment by netblue30** [comment]
> whitelist /mnt/Data/Spotify-local

The problem is /mnt is not yet supported for whitelisting. I was afraid it had something to do with NTFS. I added an entry on my todo list to bring in support for whitelisting /mnt.
