### ISSUE TITLE
Error: Access was denied while trying to open files in your profile directory.

### ISSUE THREAD

**Issue by Utini2000** [netblue30/firejail#74]
Hey there,

I am suddenly having troubles loading up Iceweasel with firejail. Without really doing any changes to my profiles I get the following error when running "firejail iceweasel":
```
Error: Access was denied while trying to open files in your profile directory.
```
This is my /home/sneida/.config/firejail/iceweasel.profile:
```
caps.drop all
seccomp
noroot
shell none
netfilter
#include ${HOME}/.config/firejail/mine.inc

############### disable-mgmt.inc########

# system directories
#blacklist /usr/bin
#blacklist /usr/sbin
#blacklist /bin
blacklist /sbin
blacklist /usr/sbin

# system management
blacklist ${PATH}/umount
blacklist ${PATH}/mount
blacklist ${PATH}/fusermount
blacklist ${PATH}/su
blacklist ${PATH}/sudo
blacklist ${PATH}/xinput
blacklist ${PATH}/evtest
blacklist ${PATH}/xev
blacklist ${PATH}/strace

# Prevent manipulation of firejail configuration
blacklist /etc/firejail
blacklist ${HOME}/.config/firejail

############disable-secret.inc##############

# HOME directory
blacklist ${HOME}/.ssh
tmpfs ${HOME}/.gnome2_private
blacklist ${HOME}/.gnome2/keyrings
blacklist ${HOME}/kde4/share/apps/kwallet
blacklist ${HOME}/kde/share/apps/kwallet
blacklist ${HOME}/.pki/nssdb
blacklist ${HOME}/.gnupg
blacklist ${HOME}/.local/share/recently-used.xbel

################ disable-common.inc###############
# HTTP / FTP / Mail
blacklist ${HOME}/.adobe
blacklist ${HOME}/.macromedia
blacklist ${HOME}/.icedove
blacklist ${HOME}/.thunderbird
blacklist ${HOME}/.config/midori
blacklist ${HOME}/.config/opera
blacklist ${HOME}/.config/chromium
blacklist ${HOME}/.config/google-chrome
blacklist ${HOME}/.filezilla
blacklist ${HOME}/.config/filezilla
blacklist ~/.wine
blacklist ${HOME}/.wine
include /etc/firejail/disable-common.inc

# Instant Messaging
blacklist ${HOME}/.purple
blacklist ${HOME}/.config/psi+

# VNC
blacklist ${HOME}/.remmina

# Other
blacklist ${HOME}/.tconn

#xfce..

############## disable-history.inc #################
# History files in $HOME
blacklist ${HOME}/.history
blacklist ${HOME}/.*_history
```

I am the owner of the file, it is in the group "users" and permissions are "-rw-r--r--".
Any ideas? 

Running e.g. VLC with the same profile content works fine.

Thanks !

**Comment by netblue30** [comment]
The error comes from Firefox, it seems to be quite a popular error. Probably ~/.mozilla directory in not owned by you as user. Try this:
`````
$ sudo chown -R yourname:yourname /home/yourname/.mozilla
`````

**Comment by Utini2000** [comment]
@netblue30 

Nope sorry, that didn't fix the problem. I already was owner of the folder (same es with everything in my home directory). The command didn't help :/

**Comment by netblue30** [comment]
I'll reopen it and mark it as a bug.  I'll try to reproduce it here. Make sure you don't have another Firefox instance already running already when you start the sandbox - Firefox runs a single instance of the process, so if another Firefox is already present in the system you might run into problems.

**Comment by Utini2000** [comment]
Nope, no other instance of firefox (or actually parabola iceweasel) is running :/

**Comment by Utini2000** [comment]
It is weird, firejail iceweasel has worked all the time and suddenly it broke. Firejailing any other app works fine but not with iceweasel.

**Comment by Utini2000** [comment]
@netblue30  I tried re-installing firejail but that didnt help :/

**Comment by Utini2000** [comment]
@netblue30  should I try re-installing iceweasel ?

**Comment by netblue30** [comment]
Maybe if you delete ~/.mozilla directory so you can start with a fresh iceweasel configuration. Take care, this will also delete all your addons and bookmarks.

**Comment by Utini2000** [comment]
@netblue30 

1. I deleted .mozilla, then ran iceweasel, then closed it, then tried "firejail iceweasel" ´, same error
2. I deleted .mozilla, then ran "firejail Iceweasel" which worked. I close Iceweasel, tried again, same error. 

So as long as .mozilla doesn't exist, I can run iceweasel. As soon as .mozilla exists I get the rror.

**Comment by Utini2000** [comment]
lool.. found the issue.. I included "disable-common.inc" which blacklists .mozilla :/ Sorry for this :S

**Comment by netblue30** [comment]
No problem!
