### ISSUE TITLE
X11 isolation in profile

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#740]
It would be great if I could enable X11 isolation in my profile instead of having to pass it as an argument through the command line.

**Comment by netblue30** [comment]
My first attempt to implement it failed miserably.

**Comment by chiraag-nataraj** [comment]
Interesting…what happened?

**Comment by netblue30** [comment]
I need to detect x11 long before loading the profile from the file. Today it works this way: detect x11, start xpra or xephyr, restart firejail this time without --x11, load profile, start sandbox.

A possible solution would be to keep in /etc/firejail/firejail.config a list of programs that are always started with --x11. It is not as nice a x11 command in a profile file, but it is much easier to implement.
