### ISSUE TITLE
Whitelisting symlink doesn't work

### ISSUE THREAD

**Issue by bryce-lynch** [netblue30/firejail#741]
It seems symlink support had already been added https://github.com/netblue30/firejail/issues/386
However, my /home/user/.cache/ is symlinked to a tmpfs volume and I receive the following messages when trying to execute Firefox:
Error: invalid whitelist path /home/user/.cache/mozilla/firefox
Error: cannot establish communication with the parent, exiting...

**Comment by chiraag-nataraj** [comment]
Just as an aside, you can do what I do and whitelist only the folders that should be permanent (~/.mozilla, various GTK config files, ~/Downloads). That way, everything else will automatically be stored on a tmpfs. This does become a pain though if you have a large number of folders to whitelist.

**Comment by bryce-lynch** [comment]
@chiraag-nataraj good idea, seems to work! Thought now Firefox complains it isn't "my default browser".

**Comment by chiraag-nataraj** [comment]
@bryce-lynch I sometimes get that. Usually I just uncheck "Always check if Firefox is your default browser" and that goes away (it's unchecked in my preferences).

**Comment by netblue30** [comment]
It seems to be working fine for me. I'll close the bug, if you are still having problems, I'll reopen it.
