### ISSUE TITLE
blocking the mic and webcam?

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#745]
so, outside of xpra, are either possible? how?

**Comment by Fred-Barclay** [comment]
If I'm not mistaken, `--nosound` and `--private-dev` will block the microphone/speakers and webcam, respectively. 

I *think* that `--private-dev` will block the microphone and webcam without disabling system sounds, but I might be wrong on that.

**Comment by xahare** [comment]
xpra has a menu to allow access to them. dont know how easy that would be for the app in question to get around.

**Comment by chiraag-nataraj** [comment]
From what I can tell, pretty easy (at least with PulseAudio). I "disabled" access to speakers and the microphone, yet Youtube can still play stuff and Hangouts can still access my mic. I don't know what exactly it's preventing - maybe direct access to the /dev files?

**Comment by netblue30** [comment]
> xpra has a menu to allow access to them. dont know how easy that would be for the app in question to get around.

Most applications go directly to /dev directory or PulseAudio and bypass xpra. Actually, I don't know any application using X11 sound settings.

**Comment by Fred-Barclay** [comment]
@netblue30, what is proper syntax for disabling the microphone and webcam? Would `--private-dev` be sufficient, or is `--nosound` needed as well?
Thanks!

**Comment by netblue30** [comment]
The webcam is disabled by --private-dev. We don't have independent control for speakers and microphone, both are disabled by --nosound.
