### ISSUE TITLE
strange xpra error.

### ISSUE THREAD

**Issue by xahare** [netblue30/firejail#746]
this stopped working earlier today in my main work vm. ~/.xpra does exist. in Vagrant, the same setup still works, so i dont know how to reproduce this. im using ubuntu 16.04. in vagrant, boxcutter/ubuntu1604-desktop

the strange error is  "socket path error: [Errno 2] No such file or directory: 'socket-dirs = ~/.xpra'"

this happens with the ppa release or compiling from todays source (git pull, make, sudo make install)

--x11=xephyr still works.

```
$ cat bin/workbrowser-google-chrome.bash 
#!/bin/bash
firejail --name=workbrowser-google-chrome --x11 --net=fj0 --dns=192.168.113.2 --private=~/firejail/workbrowser google-chrome

$ workbrowser-google-chrome.bash 
2016-08-26 22:13:18,062 Warning: xpra start from an existing 'ubuntu' desktop session
2016-08-26 22:13:18,062  pulseaudio forwarding may not work
2016-08-26 22:13:18,063  try using a clean environment, a dedicated user,
2016-08-26 22:13:18,063  or turn off pulseaudio
xpra initialization error:
 socket path error: [Errno 2] No such file or directory: 'socket-dirs = ~/.xpra'
Xpra server pid 17640, xpra client pid 17656, jail 17657

*** Attaching to xpra display 345 ***

Reading profile /usr/local/etc/firejail/google-chrome.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
2016-08-26 22:13:19,381 Xpra gtk2 client version 0.17.5-r13455
2016-08-26 22:13:19,382  running on Linux Ubuntu 16.04 xenial
2016-08-26 22:13:19,675 GStreamer version 1.8 for Python 2.7

got signal SIGTERM, exiting

```

**Comment by chiraag-nataraj** [comment]
Since you're using `--private=~/firejail/workbrowser`, I feel like `.xpra` should reside within that directory. That is, you should create the directory `~/firejail/workbrowser/.xpra`. Does that fix the issue?

**Comment by xahare** [comment]
didnt work. i think its a regression. having ~/.xpra in my real directory has worked fine for weeks.

**Comment by chiraag-nataraj** [comment]
I wonder which library that would even be...firejail only depends on libc6...and you're running the same version of firejail on both machines?

**Comment by xahare** [comment]
in vagrant, the ppa version. on the persistent vm, i tried both the ppa and compiled from github. doing an update in the vagrant box to see if it breaks it. 

ill try to get xpra working, but if it cant be done, then the only loss is some convenience, and maybe camera and microphone protection (another thread). i can live with xephyr until wayland takes over.

i also dont care what distro i use, cause all my apps live in firejail anyway. so open to changing. fedora is probably next because wayland. or maybe rebecca black. im not holding my breath for mir.

@netblue30 what works for you? have you played with wayland yet?

**Comment by netblue30** [comment]
I've seen xpra working on Debian and Ubuntu, didn't play with wayland yet.

**Comment by xahare** [comment]
found it. user error. in my ~/.xpra/xpra.conf

socket-dirs = socket-dirs = ~/.xpra

fixed.
