### ISSUE TITLE
DNS Rebinding protection?

### ISSUE THREAD

**Issue by TobiX** [netblue30/firejail#759]
Since it came up again recently (http://bouk.co/blog/hacking-developers/), would it be possible to provide DNS rebinding protection (basically deny access to 127.0.0.1 or kill "suspicious" DNS responses) by default in the browser profiles? Or would that break too many legitimate usecases?

**Comment by manevich** [comment]
I think `--net=eth0` option is what you need.

**Comment by manevich** [comment]
Adding this by as default may be difficult, though.
Local proxies, DNS servers, CUPS web interface, etc will be affected.

**Comment by TobiX** [comment]
I just realized that dnsmasq has --stop-dns-rebind, which rejects "local" IPs from upstream name servers. Basically my second idea... Now how to get this into default resolvers?

I just realized that DNSBL return 127.0.0.x too, so blocking DNS responses for that will break DNSBL :(

**Comment by manevich** [comment]
`--netfilter` option of firejail can be used to selectively block access to local IPs/ports.
Block ports browser never need connect to, leaving access to local services user may want access from browser.
While this is not complete protection this can reduce exposure, and may be acceptable in default profile.

**Comment by netblue30** [comment]
What happens if you pin down the DNS setting, something like "firejail --dns=8.8.8.8 firefox". In this case 8.8.8.8 goes directly in /etc/resolv.conf. Will firefox still do the rebinding?

**Comment by manevich** [comment]
This depends on configuration of DNS server.
Server may be configured to block private addresses (see [comment](https://github.com/netblue30/firejail/issues/759#issuecomment-244462702) of @TobiX on dnsmasq, for example).
But as 127.0.0.0/8 addresses are returned by DNSBL servers, it seems very unlikely that mainstream DNS servers will employ such protection.

**Comment by chiraag-nataraj** [comment]
This seems like something that should be addressed on the DNS server end, not firejail? On the `firejail` end, I think using a new network namespace is the right way to do this, but as @manevich said, this will break too many usecases. A proper solution should be implemented on the DNS server end, so I'm going to close this.
