### ISSUE TITLE
Invalid line in profile

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#760]
Somehow firejail thinks that firefox.profile contains an invalid line and exits.
This happens for example for firefox (and also for icedove; those are the only profiles where I noticed that).
(Note that it complains about a line number which doesn't exist.)

> $ rm -rf .mozilla .config
> $ wc -l /etc/firejail/firefox.profile 
> 50 /etc/firejail/firefox.profile
> $ firejail --debug firefox
> Autoselecting /bin/bash as shell
> Command name #firefox#
> Found firefox profile in /etc/firejail directory
> Reading profile /etc/firejail/firefox.profile
> Reading profile /etc/firejail/disable-common.inc
> Reading profile /etc/firejail/disable-programs.inc
> Reading profile /etc/firejail/disable-devel.inc
> Username test, groups 1000, 
> Reading profile /etc/firejail/whitelist-common.inc
> Username test, groups 1000, 
> Error: line 51 in /etc/firejail/firefox.profile is invalid

**Comment by netblue30** [comment]
I'm not able to reproduce it.

**Comment by reinerh** [comment]
Happens also with a newly created user.

> # adduser test
> ...
> # su - test
> $ firejail firefox

**Comment by Fred-Barclay** [comment]
@reinerh I can't reproduce it either on LMDE 2. What distro are you using?

**Comment by reinerh** [comment]
@Fred-Barclay Debian unstable.

**Comment by reinerh** [comment]
I just git-bisect'ed it, and the first commit where this issue occurs is 5a48bfcc404e7a49f5d9ad0f44bacff44910a102.

**Comment by netblue30** [comment]
Fixed: https://github.com/netblue30/firejail/commit/24f53cde1d2ae75e23b3f82a925592c0c10c789a

There are some obscure differences between ext() and _exit(), described here: http://www.unixguide.net/unix/programming/1.1.3.shtml. I ended up fixing this problem all over the place. Thanks for the bug.
