### ISSUE TITLE
firejail not exiting

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#762]
When running seccomp-ptrace.exp, firejail doesn't exit and continues running.
To reproduce:

> $ firejail --noprofile --seccomp
> ...
> $ strace ls
> ...
> $ exit

**Comment by netblue30** [comment]
What distro are you testing on?

**Comment by reinerh** [comment]
Debian unstable

**Comment by netblue30** [comment]
OK, I'll give it a try on sid.

**Comment by reinerh** [comment]
After strace is "killed" with "Bad system call", there is still a "strace ls" process listed in the process list.
When this is killed manually with SIGTERM, it's possible to leave the firejail normally.

**Comment by netblue30** [comment]
In a separate terminal I run "sudo firemon" - it tells me what processes are created inside the sandbox when I run "strace ls":
`````
09:24:12 fork 1228 (netblue) /bin/bash 
        child 1242 /bin/bash 
09:24:12 exec 1242 (netblue) strace ls 
09:24:12 fork 1242 (netblue) strace ls 
        child 1243 strace ls 
09:24:12 exit 1242 (netblue)
`````
strace (PID 1242) forks a child process (1243), then it is killed by seccomp. The child doesn't shut down.

I copied strace from jessie on my sid box, and tried with the old strace executable:
`````
09:23:55 fork 1228 (netblue) /bin/bash 
        child 1239 /bin/bash 
09:23:55 exec 1239 (netblue) ./jessie-strace ls 
09:23:55 fork 1239 (netblue) ./jessie-strace ls 
        child 1240 ./jessie-strace ls 
09:23:55 exit 1239 (netblue)
09:23:55 exit 1240 (netblue)
``````
When jessie-strace gets killed, the child process terminates. I would say it is a problem with strace. Somehow in the old strace the child closed automatically when the parent died.

**Comment by chiraag-nataraj** [comment]
Still an issue! But if it's a problem with `strace`, I guess we can close this?
