### ISSUE TITLE
--x11=xpra still has full access to host X server

### ISSUE THREAD

**Issue by klampworks** [netblue30/firejail#767]
If I run the following:

    firejail --x11=xpra xterm

And inside my sandboxed xterm do:

    DISPLAY=:0 xterm

Then a new xterm window pops up on the host X server.

I noticed that Firejail will not allow `/usr/bin/xinput` to be executed inside the sandbox. If we rename it to xinput2 for the sake of demonstration and then do the following (your device number may vary):

    DISPLAY=:0 xinput2 test 10

Then I can capture all keystrokes from the host X server from inside the sandbox. In other words, using Firejail with Xpra is providing no GUI isolation at all.

Is this intentional? I think this should merit at least a warning message to the user that malicious X11 applications can still steal all your internet banking passwords even if you "isolate" them with Firejail.

Or have I just not set up Firejail correctly?

Thanks.

**Comment by chiraag-nataraj** [comment]
I checked this with xephyr, and the same holds true there as well. One way, of course, is to completely prevent access to the sockets of the host X server (using `private-tmp` and `net=none`).

**Comment by chiraag-nataraj** [comment]
Okay. So it works with Xpra but not with Xephyr and prevents actual internet access. You could also disable the abstract socket, which would obviate the necessity of using `--net=none`. You can do so by adding the parameter `-nolisten local` in the command in `/etc/X11/xinit/xserverrc`.

**Comment by klampworks** [comment]
Starting X with `-nolisten local` fixes the problem.

I'm on Gentoo so this is entirely my fault for not configuring X correctly.

If this is the default behaviour for other distros it might be worth adding a word about it to the Firejail documentation though.

Thank you very much for your help.

**Comment by chiraag-nataraj** [comment]
The default is to enable the abstract socket in most distros (at least Debian and Ubuntu). @netblue30, you should add a note that you can disable the abstract socket using `-nolisten local` :)
