### ISSUE TITLE
xpra initialization error

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#768]
With xpra version 0.17.5 and firejail version 0.9.42-rc2, firejail fails to create an xpra instance. The exact output is attached [here](https://github.com/netblue30/firejail/files/457117/xpra.txt).

**Comment by manevich** [comment]
In [this pull request](https://github.com/netblue30/firejail/pull/769) I fixed error that, most likely, caused this bug.
Would like to hear if this fixes it for you.

**Comment by chiraag-nataraj** [comment]
Yup, that works!
