### ISSUE TITLE
[enhancement] Redesign of private-tmp

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#770]
I'm wondering if the following is feasible.

- Recommend (in the docs, etc) that users disable the abstract X11 socket by adding `-nolisten local` to the X initialization script (xserverrc, .desktop file of your favorite login manager). This takes care of the messy situation with X11 abstract sockets and reduces the problem to locking down the ordinary unix socket in `/tmp/.X11-unix`.
- Rewrite `--private-tmp` to whitelist `/tmp/.X11-unix` unless X11 isolation is being used so that X will continue to work even if you use `--net=none` and `--private-tmp`.

Thoughts?

**Comment by netblue30** [comment]
It is a good idea, I'll put it in, thanks.

**Comment by manevich** [comment]
It's also possible to block access to X11 without blocking sockets by removing everything from xhost access list, so `MIT-MAGIC-COOKIE-1` from `.Xauthority` file is used.  And blacklist `~/.Xauthority` file in jail.
```
$ xhost
access control enabled, only authorized clients can connect
$ firejail --blacklist=${HOME}/.Xauthority xclock
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 25502, child pid 25503
Child process initialized
No protocol specified
Error: Can't open display: :0.0

Parent is shutting down, bye...
```

**Comment by xahare** [comment]
@manevich what distro are you using?

tried the above, xclock still ran. also tried --blacklist=/tmp/.X11-unix xlock still ran. this is on ubunutu-16.04 any idea? id like to be able to disable x11 access for apps that dont need it.

**Comment by manevich** [comment]
@xahare 
I am using Debian Stable.
May be my explanation was not so clear.
By default result of `xhost` command on Debian Stable is
```
$ xhost 
access control enabled, only authorized clients can connect
SI:localuser:user
```
to remove entries from access list, run `xhost -something` command for each line, like this: 
```xhost -SI:localuser:user```
Everything should work after this.

**Comment by chiraag-nataraj** [comment]
@manevich Thanks for that - that's an interesting way to go about it! I guess I don't inherently trust X11's "security" model :wink:

**Comment by xahare** [comment]
is there a way to block an apps access to x11 without depending on x11s access control or giving it its own x server?

**Comment by chiraag-nataraj** [comment]
@xahare, you can do what I suggested be the default (i.e. look at the opening post). Basically, you have to disable the abstract socket and then blacklist the regular unix socket in order to make sure the program doesn't have access to X11. What I suggested above does that.

**Comment by chiraag-nataraj** [comment]
@netblue30, you may want to provide a `--blacklist-xsocket` or something so that people who really want to block access to X can do so if you implement this suggestion.

**Comment by manevich** [comment]
@chiraag-nataraj Welcome!
Well, I also don't trust it too much, but this is simple and works fine as addition or if blocking abstract sockets is not solution.

**Comment by xahare** [comment]
thought i knew how this worked. really glad this thread started! im missing something.

$ ss -lnt
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port              
LISTEN     0      5      192.168.122.1:53                       *:*                  
LISTEN     0      5      127.0.1.1:53                       *:*                  
LISTEN     0      128          *:22                       *:*                  
LISTEN     0      128         :::22                      :::*

didnt see anything on udp ports either.

yet, 
firejail --net=none --private-tmp xlogo
firejail --net=none --blacklist=/tmp/.X11-unix xlogo

are needed to disable x. leave not --net=none or one of the tmp blockers and xlogo runs.

**Comment by chiraag-nataraj** [comment]
@xahare Here's what's going on.
By default, there are two different sockets (most distributions disable the tcp socket by default). There's the abstract socket (which requires a network namespace to disable generally speaking) and the standard unix socket (usually located in `/tmp`).

With respect to X11, you can handle both of these without having to create a new network namespace. You can disable the abstract socket as I described above, obviating the necessity of a network namespace. You can disable the unix socket by blacklisting it. Does that make sense? :smile:

**Comment by xahare** [comment]
@chiraag-nataraj yes! somehow i missed the memo on abstract sockets.

**Comment by xahare** [comment]
The more i think about it, this change really belongs at the distro level, or maybe xorg itself as a default when installing to linux.

**Comment by xahare** [comment]
how do you do this? i tried adding -nolisten local to /etc/X11/xinit/xserverrc in debian, and seems to have to effect. also tried it in ~/.xserverrc

**Comment by chiraag-nataraj** [comment]
@xahare I agree that it should be a distro-level default, but apparently people don't seem to exactly care about this :sad: I think if distros started sandboxing programs by default (using firejail or apparmor or selinux or something), then you'd see a push to make this default.

**Comment by xahare** [comment]
I think this project cares about this, https://github.com/QubesOS/qubes-gui-agent-linux/compare/master...xahare:patch-1

**Comment by netblue30** [comment]
Modified --private-tmp as a whitelist of /tmp/.X11-unix directory. Now I  need to document how to disable the abstract x11 socket. Give it a try and if is breaking something else, let me know.

**Comment by chiraag-nataraj** [comment]
Awesome! I presume that if you *wanted* to blacklist /tmp/.X11-unix (as is currently the case), you could use the blacklist command?

**Comment by netblue30** [comment]
yes, so for a server you would do "--private-tmp --blacklist=/tmp/.X11-unix". I'll have to modify all server profiles there.

**Comment by chiraag-nataraj** [comment]
Perfect! Thanks @netblue30!
