### ISSUE TITLE
--enable-apparmor option is lost with make deb

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#772]
Hi!

Using `configure --prefix=/usr --enable-apparmor` shows this:
```
[...]
checking sys/apparmor.h usability... yes
checking sys/apparmor.h presence... yes
checking for sys/apparmor.h... yes
[...]
Configuration options:
   apparmor: -DHAVE_APPARMOR
```

But when I type `make deb` I get:
```
[...]
Configuration options:
   apparmor: 
```

The apparmor option is discarded at some point. _Everything is okay when using `make`_
Please fix.

**Comment by netblue30** [comment]
I'll have to implement it. For now, change "./configure --prefix=/usr" into "./configure --prefix=/usr --enable-apparmor" in mkdeb.sh.

**Comment by netblue30** [comment]
Fixed in git.

**Comment by netblue30** [comment]
I had to roll it back. Use the change in mkdeb.sh.

**Comment by laniakea64** [comment]
Was going to file a bug about this when I couldn't disable git-install in my .deb build of firejail.  After reading this issue, I wrote a Python 3 script to automate setting custom configure options in mkdeb.sh and then building.

Would it be useful for either of you?

**Comment by netblue30** [comment]
Sure, send a pull request. Put the file in https://github.com/netblue30/firejail/tree/master/contrib, I'll modify the install script to have it installed automatically.
