### ISSUE TITLE
Little inconsistencies in 0.9.43 release notes 

### ISSUE THREAD

**Issue by igor2x** [netblue30/firejail#775]
Hi,
I am reading 0.9.43 Release Notes and Release Announcement and I have found little inconsistencies. It would be nice if there are expressed more clearly.

Please see the following link for details: https://s10.postimg.io/6q6019bu1/info.png

P.S. This bug report can be marked as low priority "bug".
Thanks

**Comment by netblue30** [comment]
Fixed, thanks. The link to the release notes will have to wait for the next release.
