### ISSUE TITLE
Error: cannot switch euid to root

### ISSUE THREAD

**Issue by graywolf** [netblue30/firejail#780]
I'm having troubles getting firejail to work with vlc.

	$ firejail vlc
	Reading profile /etc/firejail/vlc.profile
	Reading profile /etc/firejail/disable-common.inc
	Reading profile /etc/firejail/disable-programs.inc
	Reading profile /etc/firejail/disable-devel.inc
	Reading profile /etc/firejail/disable-passwdmgr.inc
	Warning: user namespaces not available in the current kernel.
	Parent pid 6258, child pid 6259
	Warning: /sbin directory link was not blacklisted
	Warning: /usr/sbin directory link was not blacklisted

	Child process initialized
	Error: cannot switch euid to root
	Warning: an existing sandbox was detected. vlc  will run without any additional sandboxing features in a /bin/sh shell

Two last lines repeat until I stop it (CTRL+C). However, I do not belive that this is a duplicate of other two issues with similar error, because my firejail is SUID and in general it works:

	$ firejail --version
	firejail version 0.9.40

Also other program (like chromium and palemoon) DO work just fine, so this is something vlc (and probably few others?) specific.

Could you please help me with this problem? :)

PS: I've got the same error when I tried to launch `mupdf` (true, I tried to use evince profile since mupdf doesn't have one and hey, both view pdf).

**Comment by netblue30** [comment]
> Warning: an existing sandbox was detected.

When you start vlc, are you already in a sandbox? Do you have vlc defined as a symbolic link or as a script in /usr/local/bin?

**Comment by graywolf** [comment]
> Do you have vlc defined as a symbolic link or as a script in /usr/local/bin?

not exactly but on the right track, firejail was trying to recursively launch script starting firejail, thanks :)
