### ISSUE TITLE
Add copy command to Filesystem category in profile

### ISSUE THREAD

**Issue by graywolf** [netblue30/firejail#783]
I'm using browser with `private ~/.firejails/palemoon`. It would be nice to have ability to copy config files into that home automatically.

    private ~/.firejails/palemoon
    copy ~/.vim ~/.vim
    copy ~/.vimrc ~/.vimrc
    copy ~/.gvimrc ~/.gvimrc

**Comment by manevich** [comment]
Maybe `--private-home` that  brought back in 0.9.42 is what you need?

**Comment by chiraag-nataraj** [comment]
Yup, that's exactly what `--private-home` is for. Also, though, you can use `--whitelist` to only keep certain files and directories, `--blacklist` to hide certain files and directories, or, if the config files are unique to that application, you can give that application its own home directory and use `--private=/path/to/dir`.

**Comment by graywolf** [comment]
> All modifications are discarded when the sandbox is closed.

That means that all changes are thrown away right? Than it's not what I need.. or can I combine it like this?

    private ~/.firejails/palemoon
    private-home ~/.vim,~/.vimrc,~/.gvimrc

@chiraag-nataraj I tried to use `whitelist` but it doesn't seem to propage the whitelisted files inside `private` :/

**Comment by manevich** [comment]
Why no to copy all vim configs into `~/.firejails/palemoon` then?

**Comment by graywolf** [comment]
`~/.firejails/palemoon` is just home directory with palemoon user profile in it. I'm using three different profiles (home/work/etc..) so it seemed easiest to just have separate virtual homes for each one.

Hm I guess, I've kinda just migrated my setup from docker to firejail, so like this it was easiest, but that should probably work. Will try it.

**Comment by graywolf** [comment]
Seems to work fine :) but still, copy command would be nice.

**Comment by graywolf** [comment]
@manevich mainly to prevent maintance overhead. if I copied it manually, I would have original and 3 copies. and I woudl have  to remember to update them all :/

**Comment by chiraag-nataraj** [comment]
@graywolf @manevich Instead of copying, you can do hardlinks (which work well with individual files) or bind-mounts (which work well with directories). I used to do this before switching to whitelisting - I had a setup script that ran at login that bind-mounted a couple of directories (had to provide password of course).

**Comment by netblue30** [comment]
The easiest way is to build a small script to start your program:
`````
#/bin/bash

cp -a .vim ~/.firejails/palemoon/.
cp -a .vimrc ~/.firejails/palemoon/.
cp -a .gvimrc ~/.firejails/palemoon/.
firejail --private=~/.firejails/palemoon palemoon
`````

**Comment by graywolf** [comment]
I guess :) still, would be nice to be able to keep just the symlink `ln -s /usr/bin/firejail /usr/local/bin/palemoon` without a need to make a script there.
