### ISSUE TITLE
User is missing one of the groups

### ISSUE THREAD

**Issue by graywolf** [netblue30/firejail#785]
My user is missing one of his groups. This is what it looks outside

    $ groups
    video user1 secondary

this is what it looks inside

	$ firejail --profile=/etc/firejail/vlc.profile 
	Reading profile /etc/firejail/vlc.profile
	Reading profile /etc/firejail/disable-common.inc
	Reading profile /etc/firejail/disable-programs.inc
	Reading profile /etc/firejail/disable-devel.inc
	Reading profile /etc/firejail/disable-passwdmgr.inc
	Warning: user namespaces not available in the current kernel.
	Parent pid 6039, child pid 6040
	Warning: /sbin directory link was not blacklisted
	Warning: /usr/sbin directory link was not blacklisted

	Child process initialized

	   $ groups
	video user1

How can I get user inside to have all the group? I sadly cannot access my mounted samba drive due to missing group.

Thanks :)

**Comment by manevich** [comment]
`firejail --ignore=nogroups --profile=/etc/firejail/vlc.profile` should work

**Comment by netblue30** [comment]
What firejail version are you running?

**Comment by graywolf** [comment]
> firejail --ignore=nogroups --profile=/etc/firejail/vlc.profile

that sadly doesn't help

> version

0.9.40

**Comment by netblue30** [comment]
Update to the latest version in git, there were a lot of fixes since 0.9.40
