### ISSUE TITLE
configuration file should be owned by root

### ISSUE THREAD

**Issue by y1ds** [netblue30/firejail#786]
When I try to start firejail it gives me the error "Error: configuration file should be owned by root"

strace:
root@machine:~# /usr/local/bin/firejail 
Error: configuration file should be owned by root
......
getuid()                                = 0
open("/usr/local/etc/firejail/firejail.config", O_RDONLY) = 3
stat("/usr/local/etc/firejail/firejail.config", {st_mode=S_IFREG|0644, st_size=2885, ...}) = 0
write(2, "Error: configuration file should"..., 50) = 50
exit_group(1)                           = ?
+++ exited with 1 +++

config file:
-rw-r--r-- 1 root staff 2.9K Sep 15 10:25 /usr/local/etc/firejail/firejail.config

Im running debian jessie and firejail git head (commit 4e947d97bb3b2143c922f56c3814455162b103db)

**Comment by chiraag-nataraj** [comment]
I had the same problem. Change ownership to `root:root` and it should work I think?

**Comment by netblue30** [comment]
I put a fix in, thanks for the bug.
