### ISSUE TITLE
Whitelisted directory belongs to uid 65534 within jail

### ISSUE THREAD

**Issue by lheckemann** [netblue30/firejail#787]
```
$ ls -ld ~/.config/gajim
drwx------ 8 linus linus 4096 Sep 16 22:30 /home/linus/.config/gajim
$ firejail --whitelist=~/.config/gajim
jail$ ls -l ~/.config
total 0
dr-x------ 2 65534 65534 40 Sep 14 10:10 gajim
drwx------ 2 linus linus 60 Sep 16 22:57 pulse
```
I expected the directory to belong to linus:linus within the jail and be writable as well as readable.

I haven't been able to reproduce this with any other directories for some reason... What can I do to find out more?

**Comment by manevich** [comment]
This is result of strange interaction between `blacklist` (in profile) and `--whitelist` options.
Check `firejail --noprofile --whitelist=~/.config/gajim` and `firejail --noprofile --blacklist=~/.config/gajim --whitelist=~/.config/gajim`.
Will investigate it further latter.

**Comment by lheckemann** [comment]
Yep, that works, as does `firejail --noblacklist=~/.config/gajim --whitelist=~/.config/gajim`. Thanks!

**Comment by manevich** [comment]
I was wrong, fulled by permissions of `~/.config/gajim` and fell in conclusion that only owner was changed.
This is normal and intended behavior. `--whitelist` does not remove blacklisting from file, you need `--noblacklist` for that.
