### ISSUE TITLE
Support for scripting in firemon

### ISSUE THREAD

**Issue by netblue30** [netblue30/firejail#792]
From wordpress:

I would like to script using firejail (for example, to use `firejail –list` or `firejail –tree` to find the PID of a process in order to close it). However, I noticed during experimentation that those commands are truncated by the terminal width, so that the output is inconsistent (grepping the output in a full-sized terminal would find extra values compared to a half-size terminal!). To facilitate scripting, could you please prevent truncation of those commands’ outputs? Or, if there is some other method I should be using instead, please let me know!

**Comment by chiraag-nataraj** [comment]
`firejail --list` and `firejail --tree` wrap now as far as I can tell, so this shouldn't be an issue. If you're still seeing this, please reopen!
