### ISSUE TITLE
Tighter profiles

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#794]
So, inspired by SpotComms, I decided to upload my own profiles that I've found to work pretty well to my own repository. They can be found [here](https://github.com/chiraag-nataraj/firejail-profiles). Comments/complaints/suggestions/requests totally welcome!

One thing you'll notice is that they rely heavily on whitelisting rather than blacklisting and thus they are fairly restrictive. They also don't really rely on the profiles provided by @netblue30 since I personally prefer tighter profiles :wink:

**Comment by netblue30** [comment]
Thanks, let me look through them.

**Comment by netblue30** [comment]
I put a link to your git on the main project page here on github in "User submitted profile repositories" section. Some people will find them useful.

**Comment by chiraag-nataraj** [comment]
Oh man thanks! ^_^

**Comment by netblue30** [comment]
No problem.
