### ISSUE TITLE
Move away from SourceForge

### ISSUE THREAD

**Issue by pyther** [netblue30/firejail#80]
In the recent past, SourceForge has gained a really bad reputation (non-https downloads, adware-sprinkled installers). See [this](http://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/) and [this](http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/).

Due to these events, I can not trust any code and/or binaries served from sourceforge. I almost passed up a great piece of software because this github project did not show up in my search results for "firejail" and the firejail website links to sourceforge.

Action Items
  * update links in source code. PR #79
  * serve packages and binaries from github. [about-releases](https://help.github.com/articles/about-releases/)
  * update links on the firejail website (https://l3net.wordpress.com/projects/firejail)

**Comment by netblue30** [comment]
I know about the problems with SourceForge. Unfortunately for now the downloads will stay on SourceForge mirror system. Everything else on SourceForge is being phased out.

For each release I add a firejail-X.Y.Z.asc file with sha256 checksums for all downloads in the release. The .asc file is signed with GPG and can be checked by the user.
