### ISSUE TITLE
Add an upload command to add a file from the host to a container

### ISSUE THREAD

**Issue by kadogo** [netblue30/firejail#800]
Hello,

I just use firejail for my browser and I would share a file on facebook but it was not accessible from the container.

I saw the option --get to download a file from the container to the host, we cannot add an option to upload a file from the host to the container too ?

Cheers.

**Comment by chiraag-nataraj** [comment]
Just as an aside, I usually leave one directory (`$HOME/Downloads` comes to mind) as the "transfer" directory. If I want other programs to access a file, I stick it in Downloads.

**Comment by netblue30** [comment]
All set in git. Use "firejail--put=name|pid src-file dest-file"
