### ISSUE TITLE
Accessing home directory of another user

### ISSUE THREAD

**Issue by graywolf** [netblue30/firejail#806]
I'm in need of accessing home directory of another user (`/home/shared`), but I have no idea how to achieve that. Tried whitelisting, didn't help. from `--debug` I would guess connection to `Cleaning /home directory`, but I didn't find nothing like `--no-clean-home` or something to supress that :/

How can I achieve this?

I guess `mount --bind`ing it to `/media` or somewhere should work, but is it possible without it?

**Comment by Fred-Barclay** [comment]
It's an obvious question but needs asking anyways... 
You have system permissions to access that directory ordinarily, right?
If so, do you have to gain root permissions first? (`su` or `sudo`)

**Comment by graywolf** [comment]
I complete understand, sometimes it's really something dumb like this :) But not in this case. I have permissions to access that folder, yes. Issue here mostly is that I don't even see that folder. `/home` contains only folder for current user under which I'm running the firejail. This seems to be by design (it's reasonable default), I would like to know how to suppress this behaviour though.

**Comment by netblue30** [comment]
Will do!

**Comment by graywolf** [comment]
@netblue30 I'm not really sure if I will try to contribute to this project (let's say it outright, my C sucks), but from looking through the source code, should it suffice to add some argument to control if `sanitize_home` should be called (at https://github.com/netblue30/firejail/blob/0ecf71a884ac1424bd458df914aed0e837e3cfc0/src/firejail/restrict_users.c#L342 )?

So add something like `--nocleanhome` command line argument and propagate it in there?

**Comment by netblue30** [comment]
All set in git, use --allusers.

**Comment by graywolf** [comment]
that was quick, thank you :)
