### ISSUE TITLE
Support for custom veth interface names for --net=bridge_interface

### ISSUE THREAD

**Issue by naturalspringwater** [netblue30/firejail#807]
Hello,
I use the --net=bridge_interface option which works fine, but I cannot find a way to specify the name of the veth interface created. It is always auto-generated, e.g., "veth4772eth0" ($ ip addr).

I need custom names to enforce bridge port IPs using ebtables outside the sandbox, e.g. similar to what is done by libvirt, and for other mapping purposes as well.

Thank you for this software

**Comment by netblue30** [comment]
All done, use --veth-name=...
