### ISSUE TITLE
disable-common.inc noblacklist bug

### ISSUE THREAD

**Issue by Q3CPMA** [netblue30/firejail#810]
Hello, after updating from 0.9.38.2 to 0.9.42 (Gentoo), Firejail couldn't work even with the simplest program.
```
firejail echo a
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 6626, child pid 6627
Error: cannot establish communication with the parent, exiting...
```
When commenting
```
noblacklist ${PATH}/mount
noblacklist ${PATH}/umount
noblacklist ${PATH}/su
noblacklist ${PATH}/sudo
noblacklist ${PATH}/nc
```
in `/etc/firejail/disable-common.inc`, I get what I want
```
firejail echo a
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 6715, child pid 6716
Child process initialized
a

Parent is shutting down, bye...
```

Note that it only happens to my "sandbox" user, and only when using a separate X, not through su. This may have to do with the fact that this user is not in the wheel group.

**Comment by netblue30** [comment]
So basically you are saying that in order to do "echo a" you need /bin/sudo to be available in the filestystem? Try to find out which of the lines you commented out is creating the problem.

**Comment by Q3CPMA** [comment]
Maybe I've not been clear, but leaving any of these lines uncommented makes the failure appear (makes me think the noblacklist feature has a problem, actually). By the way, `--debug` brings nothing.

**Comment by Q3CPMA** [comment]
Managed to pinpoint even more. The lines are uncommented here (as shipped).
```
su -l sandbox
Password:
sandbox@gentoo ~ $ echo $PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3:/usr/games/bin
sandbox@gentoo ~ $ firejail echo a
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 333, child pid 334
Error: cannot establish communication with the parent, exiting...
sandbox@gentoo ~ $ PATH=/bin:/usr/bin firejail echo a
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 388, child pid 389
Child process initialized
a

Parent is shutting down, bye...
```

**Comment by netblue30** [comment]
There where two bugs reported by gentoo users:

https://github.com/netblue30/firejail/issues/804 - this one seems to  be fixed in git

https://github.com/netblue30/firejail/issues/674 - I think this one can be fixed by commenting out "include disable-devel.inc", but I see you don't have it in the profile.

I would say, update to the latest version in git and give it a try. I'll take a look at noblacklist.

**Comment by sakaki-** [comment]
I see the same thing as Q3CPMA (running Gentoo, firejail 0.9.42). Issue only happens with the `busybox` USE flag set (it is by default) which in turn enables `busybox-workaround` in firejail's .configure step (leading to the inclusion of the five problematic `noblacklist` lines at the head of `/etc/firejail/disable-common.inc`).
PS otherwise a very nice program, thank you.

**Comment by netblue30** [comment]
We have some special functionality for busybox, disabled by default. if you enable it on a non-busybox system, it will probably not work.

**Comment by sakaki-** [comment]
Sounds like the busybox USE flag shouldn't be set by default in the ebuild in that case. I'll file a bug report on Gentoo. Thanks for the response!
