### ISSUE TITLE
Support portals

### ISSUE THREAD

**Issue by probonopd** [netblue30/firejail#811]
The GTK+/GNOME/Flatpak camp has something called Portals which is not inherently married with Flatpak and could be interesting for the AppImage/firejail combination, too:

https://blogs.gnome.org/mclasen/2016/07/08/portals-using-gtk-in-a-flatpak/

> Portals are high-level (in the sense that they talk about concepts that are relevant to users) APIs that let sandboxed applications request access to resources outside. Portal calls will (almost) always involve user interaction (basically, a dialog).

https://github.com/flatpak/xdg-desktop-portal-gtk

Can we make use of them in the AppImage/firejail combination?

**Comment by netblue30** [comment]
I'll look nto it, thanks.

**Comment by chiraag-nataraj** [comment]
Seems like it uses D-Bus...not necessarily a good idea?

**Comment by chiraag-nataraj** [comment]
Yeah, the portal spec consists of a D-Bus service...that sounds like a terrible idea for something like firejail.

**Comment by chiraag-nataraj** [comment]
I'm going to close this for now. If there were a different way to interact with portals, this might be more interesting, but I don't think any of us are crazy about using D-Bus. @netblue30 or @probonopd, please feel free to re-open if you feel differently.
