### ISSUE TITLE
[Request] New profiles  

### ISSUE THREAD

**Issue by triceratops1** [netblue30/firejail#812]
Could firejail add some extra profiles    
1 LuminanceHDR

config files
~/.LuminanceHDR
~/.config/Luminance

2 Natron 
~/.Natron
~/.cache/INRIA/
~/.config./INRIA

3 QpdfView, a Poppler-based PDF viewer
~/.config/qpdfview

4 Synfigstudio, an opensource animation studio  
~/.config/synfig 

5 Otter browser
~/.config/otter 

6 Calligra profiles,  such as krita

**Comment by chiraag-nataraj** [comment]
I added a `qpdfview` profile to my repository (https://github.com/chiraag-nataraj/firejail-profiles). I will work on 1, 2, 4, and 5 as well :smiley: Let me know if you have problems!

**Comment by netblue30** [comment]
I'll start adding them on by one. qpdfview is in.

**Comment by triceratops1** [comment]
https://aur.archlinux.org/packages/natron-portable/                    @chiraag-nataraj

@netblue30 
I found natron binaries, nologin

**Comment by netblue30** [comment]
moved to https://github.com/netblue30/firejail/issues/825
