### ISSUE TITLE
Issue with private-bin option in version 0.9.42

### ISSUE THREAD

**Issue by phrackmod** [netblue30/firejail#814]
Applications fail to load after updating to version 0.9.42. 'private-bin' option in the profiles seem to be the issue. Manually changed a few profiles by uncommenting the option and it works.

**Comment by netblue30** [comment]
Give me an example, how are you starting the sandbox and what do you have in your profile under private-bin?

**Comment by phrackmod** [comment]
Applications which failed to load for me are 'evince' and 'transmission-gtk'.
uncommenting the "private-bin" option in both the profiles made the applications work. I tried to launch them from terminal to see if any errors would be reported. Nothing is reported and the process exits silently.

**Comment by phrackmod** [comment]
Profiles for both the apps were not modified. "private-bin" option causing the problem is
**private-bin evince,evince-previewer,evince-thumbnailer**
**private-bin transmission-gtk**

**Comment by netblue30** [comment]
Do like this:

In terminal, run "sudo firermon". In a separate terminal start the program: "firejail evince". In the first terminal you will get a list with all the programs the sandbox tries to start, something like this:
`````
14:10:10 exec 6758 (root) NEW SANDBOX: /usr/bin/firejail /usr/bin/evince 
14:10:10 uid  6758 (root) /usr/bin/firejail /usr/bin/evince 
14:10:10 uid  6758 (netblue) /usr/bin/firejail /usr/bin/evince 
14:10:10 gid  6758 (netblue) /usr/bin/firejail /usr/bin/evince 
14:10:10 fork 6760 (netblue) /usr/bin/firejail /usr/bin/evince 
	child 6766 /usr/bin/evince 
14:10:10 uid  6760 (netblue) /usr/bin/firejail /usr/bin/evince 
14:10:10 gid  6760 (netblue) /usr/bin/firejail /usr/bin/evince 
````
You look for "fork" entries.

**Comment by phrackmod** [comment]
'fork' entries for both the applications are similar to your output. I've attached the output of 'sudo firemon' for both the apps.

[evince.txt](https://github.com/netblue30/firejail/files/493853/evince.txt)
[transmission.txt](https://github.com/netblue30/firejail/files/493854/transmission.txt)

**Comment by netblue30** [comment]
`````
exec 15808 (root) /run/firejail/mnt/cp -a /usr/local/bin/evince /run/firejail/mnt/bin/evince 
`````
Firejail is picking up evince from /usr/local/bin directory, instead of /usr/bin. Do you have a script under the name "evince" in /usr/local/bin?

I guess for transmission you have the same problem. The trace looks like you run the sandbox with private-bin commented out.

**Comment by phrackmod** [comment]
I do have scripts under "/usr/local/bin" for all the apps which are invoked with firejail. 
It seems that the command **/run/firejail/mnt/cp -a** uses hardcoded PATH values to search for the executables and copy them. This was the cause of problem for me.
Is there an option to pass new environment variables (PATH in my case) to firejail which will be used to locate the executable?

**Comment by netblue30** [comment]
OK, I got it. My documentation is all messed up. I'll have to update the description under "DESKTOP INTEGRATION" in man firejail.

There are two ways to /usr/local/bin. You can use firecfg utility (man firecfg) to create symbolic links to /usr/bin/firejail in order to start your programs automatically, or you can place your own scripts in /usr/local/bin. If you go for your scripts, you need to set "private-bin-no-local yes" in /etc/firejail/firejail.config.

I'll leave this open until I fix the docs, just add  "private-bin-no-local yes" and it will work fine.

**Comment by phrackmod** [comment]
Adding **private-bin-no-local yes** to /etc/firejail/firejail.config reports it as an invalid line. I think it has something to do with the code in "src/firejail/checkcfg.c", but the code seems fair to me. 
For now, I recompiled the code by manually removing the "/usr/local" entries in "src/firejail/fs_bin.c" and it works fine.
Please let me know if I'm missing something.

**Comment by netblue30** [comment]
I think "private-bin-no-local" came in git after the release of 0.9.42. In /etc/firejail/firejail.config you should have the following two lines commented out:
`````
# Remove /usr/local directories from private-bin list, default disabled.
# private-bin-no-local no
`````

**Comment by mr-blobbyyy** [comment]
> # Remove /usr/local directories from private-bin list, default disabled.
> # private-bin-no-local no

Um, these lines are not even in 0.9.42's config? For me, I use firejail for vlc and it appears I only need to comment out `private-tmp` in the default profile in order for vlc to start up normally. Otherwise, libvlc came back with interface and X server errors. Hopefully not due to a luks encrypted filesystem I setup by default...and I also have a firejail symlink in /usr/local/bin for vlc...

**Comment by netblue30** [comment]
Yes, it got added in git after 0.9.42 was released - another user complained about it. I'll have the new 0.9.44 version coming up in October. For now just comment out private-bin in your profiles.
