### ISSUE TITLE
Cannot use mlocate within Firejail

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#817]
I use this profile for my terminal emulator
````
caps.drop all
seccomp
netfilter
private-dev
noroot
net none
protocol unix
whitelist /tmp/user/1000/
whitelist /tmp/.X11-unix/

noexec /tmp
````
If I try to use locate inside a jailed terminal, I get `locate: can not open '/var/lib/mlocate/mlocate.db': Permission denied`. I tried not using `noroot`, but locate still didn't work.

**Comment by chiraag-nataraj** [comment]
Huh. The issue goes away if I comment out `protocol unix`. Why would that be?

**Comment by netblue30** [comment]
I have no idea what is going on. I also tried to "strace locate some-program" without any sandboxing, and it would not work. I think they are doing something very unusual. Seccomp doesn't report anything in /var/log/audit/audit.log, so nothing is killed by seccomp.

**Comment by chiraag-nataraj** [comment]
I'm looking into whether GNU locate behaves like this.

**Comment by chiraag-nataraj** [comment]
GNU locate works fine even *with* `noroot` and `seccomp`. Weird.

**Comment by chiraag-nataraj** [comment]
So I'm looking at the mlocate source and it seems it's doing some setgid stuff...would that be blocked by firejail?

**Comment by netblue30** [comment]
Yes, if it results in rising privileges.

**Comment by chiraag-nataraj** [comment]
That might explain why it's not working if `seccomp` is in effect. Huh, interesting.
