### ISSUE TITLE
firefox: error while loading shared libraries: libstdc++.so.6

### ISSUE THREAD

**Issue by veelai** [netblue30/firejail#824]
On my hardened Gentoo ~amd64 machine I see the following error when invoking firefox.

<pre>
firefox: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
</pre>

This happens with commit b806f35192817e78b95a92dd658f1430bcc6fb56. Downgrading to version 0.9.42 causes segfaults, which probably is issue #804. Downgrading further to version 0.9.38.2 makes everything work again.

**Comment by netblue30** [comment]
It is possible this is the same as https://github.com/netblue30/firejail/issues/674

In a text editor open /etc/firejail/disable-devel.inc file and comment out (add a #) the following lines in GCC section.
`````
blacklist /usr/include
blacklist /usr/lib/gcc
blacklist /usr/bin/gcc*
blacklist /usr/bin/cpp*
blacklist /usr/bin/c9*
blacklist /usr/bin/c8*
blacklist /usr/bin/c++*
blacklist /usr/bin/as
blacklist /usr/bin/ld
blacklist /usr/bin/gdb
blacklist /usr/bin/g++*
#blacklist /usr/bin/x86_64-linux-gnu-g++*
#blacklist /usr/bin/x86_64-linux-gnu-gcc*
#blacklist /usr/bin/x86_64-unknown-linux-gnu-g++*
#blacklist /usr/bin/x86_64-unknown-linux-gnu-gcc*
`````

Where is libstdc++.so.6 located on Gentoo? Can you run "find / -name libstdc++.so.6 | less", thanks.

**Comment by kaskasbarakas** [comment]
same problem here on Gentoo it works for me if i comment gcc

 `#blacklist /usr/lib/gcc `

**Comment by kaskasbarakas** [comment]
`$ find / -name libstdc++.so.6 `
`/usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6`
`/usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/32/libstdc++.so.6`

**Comment by netblue30** [comment]
Thanks @kaskasbarakas, I just put a fix in git with /usr/lib/gcc commented out. If everybody's happy, I'll close the bug.

**Comment by msva** [comment]
yeah, latest commit, as expected, fixed the issue

**Comment by veelai** [comment]
I can confirm, that the issue is fixed. Closing. :)

**Comment by netblue30** [comment]
Then is closed, thanks guys!
