### ISSUE TITLE
new xpra version loads very slowly

### ISSUE THREAD

**Issue by vismir2** [netblue30/firejail#827]
the new version of xpra, available in arch linux, loads very slowly (10 seconds for) and shows some confusing errors.

among other things it says:

No module named pyopenc
OpenGL support is missing:
 cannot import name gdkgl

Error: no encryption libraries could be loaded
pycrypto is not available: No module named Crypto
python-cryptography is not available: No module named cryptography
Warning: zlib is the only compressor enabled
install and enable lzo or lz4 support for better performance

however all the mentioned packages are available and enabled on my system

**Comment by chiraag-nataraj** [comment]
Is this only within firejail or does this also happen if you launch xpra by itself?

**Comment by vismir2** [comment]
It seems this is related to firejail.
Using it normally there are no such errors and it starts fine

**Comment by chiraag-nataraj** [comment]
@netblue30 What exactly is the command you use to launch `xpra`?

**Comment by netblue30** [comment]
For installing Xpra on Arch I have a description here: https://firejail.wordpress.com/documentation-2/x11-guide/#arch 

Looking at the code, we first start the server:
`````
$ xpra start $DISPLAY --no-daemon
`````
Then, we start the client:
`````
$ xpra  --title="firejail x11 sandbox" attach $DISPLAY
`````
