### ISSUE TITLE
Best Way to Launch External Files from Firefox? (SPICE, javaws)

### ISSUE THREAD

**Issue by ilikenwf** [netblue30/firejail#83]
Currently opening any downloaded file, including those for SPICE/KVM or javaws doesn't work when running firefox under firejail.

Do I need to whitelist the javaws and spice paths, or is this just the need to whitelist /usr/bin?

**Comment by netblue30** [comment]
Try it first starting firefox with the default browser config ("firejail firefox").

--whitelist commands only work on /home/user directory, /usr/bin is untouched. If SPICE/KVM directories are in /home/user, you will need to whitelist them also.

**Comment by ilikenwf** [comment]
Spice is just a binary, I think it is known as virt-viewer as well on
Windows...  As I'm not at that machine right now, I can't investigate
further.
