### ISSUE TITLE
private-etc invalid

### ISSUE THREAD

**Issue by vismir2** [netblue30/firejail#831]
According to the manpage:

--private-etc=file,directory
              Build  a  new  /etc  in a temporary filesystem, and copy the files and directories in the
              list.  If no listed file is found, /etc directory will be empty.  All  modifications  are
              discarded when the sandbox is closed.

However when private-etc is used without additional files in the profile, executing the corresponding program leads to an error: "*.profile is invalid"

**Comment by chiraag-nataraj** [comment]
Yeah, I've noticed this too. @netblue30, would it be possible to allow *no* parameters for `private-etc`? That way, it would be easy to basically have a completely blank `/etc` directory.

**Comment by netblue30** [comment]
It is already implemented. Do "--private-etc=empty" on command line, or "private-etc empty" in a profile file. Failing to find /etc/empty file, Firejail will just mount an empty tmpfs on top of /etc.
