### ISSUE TITLE
private-tmp for sysutils

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#832]
In 9498f23, you added private-tmp to some sysutils (e.g. file, tar, unzip), which prevents using them on files in /tmp, which isn't an uncommon use case (at least I'm using them frequently on files downloaded to /tmp).
I don't think having a private tmp for them gains much security.
Could you consider reverting those changes?

**Comment by netblue30** [comment]
Sure, I'll fix it today.

**Comment by netblue30** [comment]
All set, if I missed something, let me know.
