### ISSUE TITLE
read-only behaves inconsistently

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#833]
Hi!

- `firejail --whitelist=${HOME}/foo --read-only=${HOME}/foo` works as expected,
- `firejail --whitelist=${HOME}/foo --read-only=${HOME}` only locks /home/$USER,
- `firejail --whitelist=${HOME}/foo --read-only=${HOME}/*` does nothing while e.g. `--read-only=/media/$USER/*` locks all subdirectories.

Is it possible to make `--read-only=${HOME}/*` lock all files and subdirectories?

**Comment by netblue30** [comment]
It is a known issue. It has something to do with the way the order directory mounts are stacked one on top of another - both whitelist and read-only are implemented as filesystem mounts. This is why in "man firejail" we have this description:
`````
      --read-only=dirname_or_filename
              Set directory or file read-only.

              Example:
              $ firejail --read-only=~/.mozilla firefox

              A  short  note about mixing --whitelist and --read-only options.
              Whitelisted directories should be made read-only  independently.
              Making a parent directory read-only, will not make the whitelist
              read-only. Example:

              $ firejail --whitelist=~/work --read-only=~ --read-only=~/work
`````

**Comment by nick75e** [comment]
Sorry, it didn't notice the warning.
_Closing..._
