### ISSUE TITLE
enhancement: support user wildcards in login.users

### ISSUE THREAD

**Issue by dahabakuk** [netblue30/firejail#834]
hi,

i would like to use firejail to restrict users logging on my systems. those users can come from different active directory domains and all have a certain schema:

DOMAIN1\\ABCuser1
DOMAIN2\\ABCadmin2

it would be great to be able to use wildcards in login.users like: DOMAIN\\* or even ABC*

the userlists change quite often and contain serveral hundred Users - so its not doable to add all users to the file... 

br

**Comment by netblue30** [comment]
All done, you can try it out. It is implemented based on fnmatch (http://www.gnu.org/software/libc/manual/html_node/Wildcard-Matching.html#Wildcard-Matching).

**Comment by dahabakuk** [comment]
great! seems to work - but got hit by #360 - thanks anyways!
