### ISSUE TITLE
relax ptrace + seccomp restrictions on 4.8 kernel?

### ISSUE THREAD

**Issue by the8472** [netblue30/firejail#837]
https://outflux.net/blog/archives/2016/10/04/security-things-in-linux-v4-8/

Aiui from 4.8 onwards ptrace from within jail should be ok. At least if tracing pid 1 in the jail (the firejail-child) is still blocked.

**Comment by netblue30** [comment]
You can build a seccomp filter allowing ptrace today. We disable it in the default configuration because it would allow tracing the processes running inside the jail.
