### ISSUE TITLE
Conflict with read-only and noexec

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#839]
When using read-only together with noexec, the later will override the former.

using a profile with:

read-only ${HOME}
noexec ${HOME}

the path will not be read only and the program can write in the home directory

using noexec and then read-only will lead to the directory being executable.

**Comment by nick75e** [comment]
Hi!

I think your problem is related to #833.
As for `noexec`, using `noexec ${HOME}/*` should solve your issue.

**Comment by valoq** [comment]
It does solve the issue, however it still is not the expected behavior.

The source of the problem seems to be the way fs_rdonly and fs_noexec remount the filesystem with their specific options only, without reapplying the existing options.

**Comment by valoq** [comment]
One way to solve this might be to get the already applied mount options using something like  _PATH_FSTAB (https://www.gnu.org/software/libc/manual/html_node/Mount-Information.html#Mount-Information)
I haven't found any way to remount without overriding the previous mount options.

**Comment by chiraag-nataraj** [comment]
Shouldn't the `remount` mount option work?

**Comment by netblue30** [comment]
Definitely a bug, I'll look into it.

**Comment by smitsohu** [comment]
As far as I can tell this is fixed in current Firejail. Please fell free to reopen if you encounter this again.
