### ISSUE TITLE
nvidia driver and noroot setting

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#841]
A Debian user reported that Steam was segfaulting when run with firejail after upgrading the nvidia driver to 367.44-2.
(Also glxgears behaves wrong with the steam profile)

The problematic line in the steam profile is the "noroot" setting, though I don't know why exactly this is causing issues.

The complete bug report is [here](https://bugs.debian.org/839868).

**Comment by netblue30** [comment]
I have a fix in https://github.com/netblue30/firejail/commit/40ed53c20b7a1a5569795a858c3bfe100083c666

I don't have a Nvidia card, but I think it will fix the issue. I added video and games to the groups allowed in the user namespace. I close the bug for now and reopen it if necessary. Thanks.

**Comment by kevinoid** [comment]
I'm seeing this same issue with Firejail 0.9.44.8-1 on Debian with an nVidia NVS 5400M.  It looks like 40ed53c either did not fix the issue or it has reappeared.

I compiled from the current master (22414ad) and captured the `strace` output for `glxgears` with and without `--noroot` and posted it as a gist:  https://gist.github.com/kevinoid/cb1c4ed6c8f073d41b1c4e1039e04e99#file-glxgears-strace-diff

Notably, when running with `--noroot` it tries and fails to `chmod` `/dev/nvidia-modeset`, `/dev/nvidia-modeset`, and `/dev/nvidia0` then forks a child which fails to `chmod` the device, then opens it (which succeeds, since the devices are still `root:root` `0666` which `stat` showed before `chmod`).  It also does not try to write anything to `~/.nv/GLCache` (although the train may have left the tracks before this point).  It doesn't make much sense to me.  Any ideas?

Thanks,
Kevin

**Comment by chiraag-nataraj** [comment]
I have an Nvidia card and have used `noroot` with with `nvidia` driver for a while now with no issues. Is anyone still seeing this issue?

**Comment by kevinoid** [comment]
I can confirm that this is still an issue for me on Debian with firejail 0.9.54-1, nvidia 390.77-1, and Linux 4.18.0 (from kernel.org, without Debian patches).  `firejail --noprofile glxgears` works fine, but `firejail --noprofile --noroot glxgears` shows a black window without the spinning gears.  I updated the gist at https://gist.github.com/kevinoid/cb1c4ed6c8f073d41b1c4e1039e04e99#file-glxgears-strace-diff with the `strace` differences between the two.

**Comment by chiraag-nataraj** [comment]
That's very interesting. I'm on Debian sid/experimental, with firejail 0.9.55 (from git), nvidia 396.51-1, and Linux 4.17.8 (custom-built from linux-source-4.17). Both `firejail --noprofile glxgears` and `firejail --noprofile --noroot glxgears` give me the normal window (spinning gears).

**Comment by chiraag-nataraj** [comment]
@kevinoid I'm curious to see if you run into the issue with a Debian stock kernel. Can you test and report back?

**Comment by kevinoid** [comment]
@chiraag-nataraj  Sure.  I can confirm that the same behavior occurs when running kernel 4.17.0-1-amd64 from the linux-image-4.17.0-1-amd64 package (version 4.17.8-1) with nVidia modules built using nvidia-kernel-dkms (version 390.77-1).

**Comment by chiraag-nataraj** [comment]
Damn, that's weird. So I have a newer version of `nvidia-driver`, but I've never had this issue, so I suspect that the driver version doesn't really matter too much.

**Comment by SkewedZeppelin** [comment]
Multiple monitors? Different outputs?

it has always been arbitrary when the driver calls its suid binary iirc

**Comment by kevinoid** [comment]
I agree.  I don't think it is version-specific.  I'm currently using the laptop screen.  I can test the VGA output soon.

If you run `firejail --noprofile --noroot strace -f -o glxgears.strace glxgears` do you see any `chmod("/dev/nvidiactl", 0666)` calls in `glxgears.strace`?  I'm curious whether it is making those calls and whether the call succeeds.

Also, for reference, my system has nVidia Optimus, so it has both an Intel graphics card and an nVidia card.  The problem does not occur when using Mesa on the Intel card.

**Comment by kevinoid** [comment]
I can confirm the same behavior occurs when using the VGA output with LVDS (the laptop screen) disabled.

**Comment by chiraag-nataraj** [comment]
> I agree. I don't think it is version-specific. I'm currently using the laptop screen. I can test the VGA output soon.

I doubt the output itself would matter, since the same driver would be driving whichever screen(s) you're using.

> If you run `firejail --noprofile --noroot strace -f -o glxgears.strace glxgears` do you see any `chmod("/dev/nvidiactl", 0666)` calls in `glxgears.strace`? I'm curious whether it is making those calls and whether the call succeeds.

I actually _do_ see those calls and they _do_ fail with `EPERM (Operation not permitted)` and `glxgears` works just fine regardless.

> Also, for reference, my system has nVidia Optimus, so it has both an Intel graphics card and an nVidia card. The problem does not occur when using Mesa on the Intel card.

Yup, I have Optimus as well.

**Comment by chiraag-nataraj** [comment]
Is this still an issue?

**Comment by kevinoid** [comment]
Thanks for checking in.  I can confirm that this is still an issue for me on Debian with firejail built from the current master branch (feae44c4), nvidia 390.116-1, and Linux 5.1.2 (from kernel.org, without Debian patches). `firejail --noprofile glxgears` works fine, but `firejail --noprofile --noroot glxgears` shows a black window without the spinning gears.

**Comment by chiraag-nataraj** [comment]
Hmm, I see. Is this an issue if you use the Debian-supplied kernel instead of the custom build?

**Comment by kevinoid** [comment]
Yep.  I can confirm that the same symptoms occur with firejail built from feae44c, nvidia 390.116-1, and Linux 4.19.0-5-amd64 (from the linux-image-4.19.0-5-amd64 Debian package version 4.19.37-3).

**Comment by chiraag-nataraj** [comment]
I'm wondering if it just has to do with something they changed on their end, since I'm on 418.74...

**Comment by chiraag-nataraj** [comment]
But looking back, that doesn't seem to matter...I'm stumped.

**Comment by chiraag-nataraj** [comment]
If you do `firejail --noroot --noprofile glxinfo`, what is the output?

**Comment by kevinoid** [comment]
I added the output of `firejail --noroot --noprofile glxinfo` to the gist with the strace outputs:  https://gist.github.com/kevinoid/cb1c4ed6c8f073d41b1c4e1039e04e99#file-glxinfo-noroot-txt

**Comment by chiraag-nataraj** [comment]
Hold on. Your `glxinfo` output is showing that `glxinfo` has no problem accessing your Nvidia card. Something's really screwy here, since you're reporting that `glxgears` has the problem, but your output shows that `glxinfo` does not.

**Comment by kevinoid** [comment]
That is correct.  On my system `glxinfo` appears to work fine with `--noroot`.  `glxgears` does not work with `--noroot`.

**Comment by chiraag-nataraj** [comment]
That's so odd...I would presume they'd both attempt to access the Nvidia driver the same way...

**Comment by czka** [comment]
For the record: similar thing with `nvidia` driver `390.132-32` on Arch Linux, trying to run Operation Flashpoint (aka Arma: Cold War Assult these days) on Steam `1.0.0.61-4` in Gnome `3.36.0`, `X11` mode.

With `noroot` disabled in `/etc/firejail/steam.profile` the game runs fine. When `noroot` is set (as per Firejail's default) game's video freezes as long as its full-screen "window" is focused. However, when I press `alt`+`tab` to switch windows, I can see the game's video unfreezed underneath the list of windows. And so forth - once I switch to game's window, the video gets stuck, and when I press `alt`+`tab` I can see the game actually runnig fine underneath the list of my active windows.

@netblue30 Maybe add a hint regarding `noroot` in `steam.profile` for people trying to run games on Linux+Steam+Nvidia? I took me a long moment to figure this out.

**Comment by rusty-snake** [comment]
@czka done.

**Comment by czka** [comment]
@rusty-snake Kewl!

**Comment by matu3ba** [comment]
@rusty-snake Could you close due fixed and no feedback?

**Comment by rusty-snake** [comment]
Maybe we want to keep it open until we have a better fix then adding a note that nvidia-users should add `ignore noroot` to some profiles. I'm not sure.

**Comment by netblue30** [comment]
Temporary fix in for the next release: I disable nogroups if /dev/nvidiactl is detected in the system. If it is working we go with it in the next release and find a better way to do it later.
