### ISSUE TITLE
LibreOffice doesn't start

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#845]
After the latest change for libreoffice.profile, LibreOffice (v. 5.1.5.2 on Fedora 24) doesn't start anymore. On the console I'm getting the error

`Failed to open display`

The problem is fixed after _uncommenting_

`# whitelist /tmp/.X11-unix/`

**Comment by netblue30** [comment]
I'll look into it, thanks.

**Comment by valoq** [comment]
Whitelisting /temp/.X11-unix only restricts the profile further. Therefore it shouldn't help. Am I missing something?

Also whitelisting this directory will prevent libreoffice from writing several temporary files, necessary for recovering documents after a crash.

Are you by any chance using additional firejail options?
I have seen that issue when using "net none" in a profile.

**Comment by valoq** [comment]
I tried to recreate the issue on a fresh fedora 24 system but libreoffice starts just fine.
Can you please provide more information about how you start libreoffice?

**Comment by curiosity-seeker** [comment]
Well, I created the necessary symlinks for Firejail as usual with sudo firecfg and start LibreOffice via the KDE start menu.

That error message mentioned in the first post was shown when I started it on the console.

**Comment by valoq** [comment]
Using the default fedora 24 system with gnome, Libreoffice 5.1.5.2 and firejail 0.9.43 from today, I was not able to recreate the issue.
Maybe netblue has an Idea why whitelisting could solve anything in the first place.

**Comment by chiraag-nataraj** [comment]
Can you post the full profile (or attach it)? I have a sneaking suspicion that there's a `private-tmp` there which, along with a `net none`, would completely disable access to `X11`. Hence you would need to whitelist the `X11` unix socket.

**Comment by curiosity-seeker** [comment]
Okay, I found the culprit. I had added the following rule 

`whitelist /tmp/mozilla_hank0/`

to my individual profile as without this rule LibreOffice wouldn't open attachments in Thunderbird mails. Now I've commented that rule and everything works as it should - even opening those attachments.

I don't fully understand the nexus but all is well - sorry for the trouble!
