### ISSUE TITLE
Cherrytree doesn't find its database anymore

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#850]
Due to the latest [latest](https://github.com/netblue30/firejail/commit/931f09d320dc7ab6f27ea5e724e9791eda2cec8b#diff-0c34fefae97615c28fbf9030e7bfeec9) change in cherrytree.profile, specifically the removal of whitelisting `~/.config/cherrytree`, Cherrytree doesn't find its database anymore. 

At least in my case the Cherrytree config.cfg file is saved in that directory, too, and if I create a new database that directory is offered as the default one. Hence, its removal is a bit, well, overzealous.

**Comment by netblue30** [comment]
Try it now, @valoq put in with a fix.

**Comment by curiosity-seeker** [comment]
Sorry, it doesn't work for me. That folder has to be whitelisted.

**Comment by netblue30** [comment]
I have removed the whitelisting for now, it is creating too many problems, thanks for letting me know.

**Comment by curiosity-seeker** [comment]
That's not a big deal for me since I can use my own modified profile. I was only surprised by the added

`noblacklist ${HOME}/.config/cherrytree/`

This has no effect, IMHO, because:

1. That folder is not blacklisted in any *.inc file.
2. Due to the included `/etc/firejail/whitelist-common.inc` it was a [whitelisted profile](https://firejail.wordpress.com/documentation-2/building-whitelisted-profiles/). Hence, without whitelisting that folder Cherrytree has no permission for it - noblacklist is not sufficient.

Please correct me if I'm misunderstanding something!

**Comment by netblue30** [comment]
You are right, I just put a blacklist in disable-progams.inc, thanks.

**Comment by curiosity-seeker** [comment]
Sorry for coming back! But the profile still contains an error:

The last slash in

`noblacklist ${HOME}/.config/cherrytree/`

is too much! It should be 

`noblacklist ${HOME}/.config/cherrytree`

**Comment by netblue30** [comment]
fixed, thanks.
