### ISSUE TITLE
What does "shell none" do

### ISSUE THREAD

**Issue by vismir2** [netblue30/firejail#858]
According to the Manpage:
--shell=none
              Run the program directly, without a user shell.

              Example:
              $ firejail --shell=none script.sh

This doesn't really explain much. What is it for. Why should or shouldn't I use it?

**Comment by netblue30** [comment]
By default it runs the program in a new shell. For example, if you start "firejail firefox", after setting the sandbox it actually runs "/bin/bash -c firefox". --shell=none runs the program directly.

**Comment by vismir2** [comment]
When do I need that option?
Are there any security implications with that option?

**Comment by chiraag-nataraj** [comment]
It's useful if you want to use `--private-bin` to limit the binaries available - not having access to a shell program if the program is hacked is a Really Good Thing (TM) :wink:

**Comment by netblue30** [comment]
Yes, is relevant for --private-bin. I don't think there are any security implications.
