### ISSUE TITLE
Wine profile (included in default Firejail installation) may be too restrictive

### ISSUE THREAD

**Issue by denizakcal** [netblue30/firejail#868]
When I try to run the 32-bit Windows version of Firefox ESR 45.4 via Wine (because I want to use Adobe's flash player to watch TV shows) using Firejail, the application/the 32-bit Windows version of Firefox hangs.

I remember errors along the lines of "error writing association file" in sixteen ≈"/home/user/.local/share/applications/wine-something.desktop" type files. I also recall the application working well without Firejail.

I'm not sure whether this means that the Wine profile included in the default Firejail installation should be amended, or if it's just something I should change in my particular system's Wine profile (but, for what it's worth, I remember reading online about someone else having such a use case, so it's probably not uncommon, especially now that Flash on Linux is not getting enough attention for such use cases).

Let me know what you think.

**Comment by netblue30** [comment]
Let's mark it as a bug. Probably one of the lines in /etc/firejail/wine.profile is creating the problem. Can you open that file and start commenting (add a #) the lines one by one andtry it, maybe we can find it, thanks.

**Comment by denizakcal** [comment]
Alright, so it seems that, when seccomp is not commented, (the Windows version of) Firefox hangs (but sometimes it seems to take several seconds to hang, as opposed to hanging instantaneously).

**Comment by netblue30** [comment]
The easiest way to handle it is to use your wine profile with seccomp disabled. You will still be covered by nonewprivs and noroot - the bad guy will not be able to become root in the sandbox. But use this only for TV viewing, for regular browsing do "firejail firefox", especially for internet banking and anything else confidential.
