### ISSUE TITLE
Use of systemcalls

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#873]
Analysing the systemcalls of mupdf and writing code which applies those syscalls with seccomp filter (using libseccomp) and the executing mupdf, I got a working application with only very few allowed syscalls.
However simply applying thoses syscalls to firejail with seccomp.keep does not work and it turns out that with firejail, mupdf needs a lot more syscalls. Why is that?

**Comment by netblue30** [comment]
After the filter is enabled, the sandbox still makes a small number of syscalls in order to configure and monitor the program running in the sandbox.
