### ISSUE TITLE
Question: why when running as root does it mount over /dev/shm

### ISSUE THREAD

**Issue by endymon** [netblue30/firejail#876]
More or less self explanatory.

When running firejail as root user why does it force a new clean /dev/shm/ to be mounted?
This does not occur when running as a non root user. (appears to be by spec)

What is the reasoning behind this behavior?

Is there any way to disable this behavior?
I've tried --noblacklist=/dev/shm to no avail

Thanks
-- Matthew Hively

**Comment by netblue30** [comment]
In fact is mounting an empty temporary filesystem on top of /dev/shm. It is a leftover from long time ago, thanks for bringing it up. All fixed in git.
