### ISSUE TITLE
"firejail --chroot=/" destroys resolv.conf

### ISSUE THREAD

**Issue by mcarpenter** [netblue30/firejail#877]
This is a silly use case but my broader concern is that this could happen anywhere that `copy_file()` has identical paths to source and destination arguments. In this case, the file in question is truncated to zero bytes:

    martin@ubuntu14:/tmp$ uname -a 
    Linux ubuntu14 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    martin@ubuntu14:/tmp$ firejail --version
    firejail version 0.9.45
    
    Compile time support:
    	- AppArmor support is disabled
    	- AppImage support is enabled
    	- bind support is enabled
    	- chroot support is enabled
    	- file and directory whitelisting support is enabled
    	- file transfer support is enabled
    	- networking support is enabled
    	- overlayfs support is enabled
    	- private-home support is enabled
    	- seccomp-bpf support is enabled
    	- user namespace support is enabled
    	- X11 sandboxing support is enabled
    
    martin@ubuntu14:/tmp$ ls -l /etc/resolv.conf
    -rw-r--r--. 1 root root 45 Oct 27 08:35 /etc/resolv.conf
    martin@ubuntu14:/tmp$ firejail --chroot=/
    Warning: default profile disabled by --chroot option
    Parent pid 13279, child pid 13280
    Dropping all Linux capabilities and enforcing default seccomp filter
    Warning: failed to mount /sys
    Warning: whitelist feature is disabled in chroot
    Child process initialized
    martin@ubuntu14:/tmp$ ls -l /etc/resolv.conf
    -rw-r--r--. 1 root root 0 Oct 27 08:35 /etc/resolv.conf
    martin@ubuntu14:/tmp$ exit
    
    Parent is shutting down, bye...
    martin@ubuntu14:/tmp$ ls -l /etc/resolv.conf
    -rw-r--r--. 1 root root 0 Oct 27 08:35 /etc/resolv.conf
    martin@ubuntu14:/tmp$

**Comment by netblue30** [comment]
Security problem! I have fixed copy_file(), if the destination already exists it return an error. I also put code in to reject --chroot=/. This is the commit: https://github.com/netblue30/firejail/commit/6144229605177764b7f3f3450c1a47f56595dc9e. Thanks.

**Comment by mcarpenter** [comment]
Thanks!
