### ISSUE TITLE
Can't run any OpenGL apps using nvidia drivers

### ISSUE THREAD

**Issue by bog-dan-ro** [netblue30/firejail#879]
Hi,

I'm trying to use firejail (from debian sid packages) to run some opengl games (0ad, openarena, etc.) but none of them seems to work. Not even the humble glxgears ...
It doesn't crash, just the window is black.

Is this a know problem, or the debian package is broken?

**Comment by valoq** [comment]
How do you start firejail?
Are you using any profiles, the default profiles or your own?
Are you using any additional options like --x11 to start the applications?

Can you verify that the applications run normally without firejail?

**Comment by netblue30** [comment]
What firejail version are you running? There have been some Nvidia fixes in 0.9.44. 

Also try "firejail --noprofile 0ad". If this works, we'll need to fix the profile file.

**Comment by bog-dan-ro** [comment]
@valoq 
> How do you start firejail?

```firejail 0ad```

> Are you using any profiles, the default profiles or your own?

default profiles

> Are you using any additional firejail options like --x11 to start the applications?

Nope

> Can you verify that the applications run normally without firejail?

It runs perfectly! 

@netblue30 

> What firejail version are you running? There have been some Nvidia fixes in 0.9.44.

0.9.44-1 from https://packages.debian.org/sid/firejail

> Also try "firejail --noprofile 0ad". If this works, we'll need to fix the profile file.

I'll try it when I get home.

I tried it on my laptop (intel video card) and everything works ok !

**Comment by bog-dan-ro** [comment]
@netblue30 ```firejail --noprofile any_open_gl_app``` works perfectly!
Let me know how can I help to fix the profile files.

**Comment by netblue30** [comment]
OK, you need to find in the profile file the line or the lines that are creating the problem.

For example, you open in a text editor /etc/0ad.profile and start commenting the lines one by one (add a '#' in front of the line). Then, you run "firejail 0ad". In a few iterations you'll find out what line or lines are creating the problem.

Also take a look at this issue: https://github.com/netblue30/firejail/issues/631

**Comment by bog-dan-ro** [comment]
I found it, it's ```noroot``` option from ```default.profile```

**Comment by bog-dan-ro** [comment]
For **0ad** there are a few more in **0ad.profile**

```
#caps.drop all
#nonewprivs
#noroot
#protocol unix,inet,inet6
#seccomp
```

**Comment by netblue30** [comment]
I think the driver uses some suid binary to start opengl, or maybe ptrace. Is this the opensource driver from Debian or some closed-source driver from Nvidia?

We have something similar with AMDGPU Pro drivers from AMD: https://firejail.wordpress.com/support/known-problems/#amdgpu - in this case they seem to be using ptrace for some reasons and they get killed by seccomp.

This is how you fix it: for all opengl programs you use, make a local copy of the profile file (example: /etc/firejail/0ad.profile) in  your home directory in ~/.config/firejail/ (example: ~/.config/firejail/0ad.profile). Then. you edit the local copy and disable the lines. For programs without a specific profile file in /etc/firejail, copy /etc/firejail/default.profile (example: cp /etc/firejail/default.profile ~/.config/firejail/openarena.profile).

**Comment by bog-dan-ro** [comment]
> I think the driver uses some suid binary to start opengl, or maybe ptrace. Is this the opensource driver from Debian or some closed-source driver from Nvidia?

I'm using NVidia proprietary drivers from debian packages  :(

I "fixed" it by changing the files from /etc/firejail/ but ... Isn't better to trace the problem and contact nvidia and request them to fix their drivers?

**Comment by netblue30** [comment]
> Isn't better to trace the problem and contact nvidia and request them to fix their drivers?

Good luck with that!
