### ISSUE TITLE
cp -a --parents with --private-etc 

### ISSUE THREAD

**Issue by githububub** [netblue30/firejail#882]
This is an issue with minimal cp (POSIX-compliant) versions including ones from suckless sbase and cp ported from Plan 9 as there is no --parents option. Rather than be absolutely tied down to GNU cp from coreutils, perhaps the cp string can be modified to suit even the most basic versions of cp.

**Comment by netblue30** [comment]
I'll fix it by providing my own version. Probably busybox has the same problem. Thank you for bringing it up.

**Comment by githububub** [comment]
Excellent. Toybox cp also exhibits the same behavior ( no --parents option).

**Comment by githububub** [comment]
Excellent. Toybox cp also exhibits the same problem (i.e. no --parents option).

**Comment by netblue30** [comment]
All done on mainline.
