### ISSUE TITLE
claws-mail.profile doesn't allow attaching to existing session

### ISSUE THREAD

**Issue by martin-schwenke** [netblue30/firejail#883]
If I already have an existing claws-mail session then running "firejail claws-mail" starts a new session instead of connecting to the existing one.  I'm running 0.9.44, packaged in Debian GNU/Linux.

What I'm really trying to do is create a custom firefox profile that allows me to cleanly use the "Email Link" feature.  If I can figure out how to make the claws-mail profile work as expected, then I can customise the firefox one to connect to my claws-mail session.

If I don't hear anything, I'll try to customise the profile(s) so that I can run strace.  That would help...  ;-)

Thanks...

**Comment by martin-schwenke** [comment]
OK, the one running under firejail uses a socket in a subdir of /tmp/ but my regular version uses a socket in a subdir of ~/tmp/.  So firejail must be cleaning the TMPDIR environment variable.

**Comment by martin-schwenke** [comment]
OK, if I use "env TMPDIR=..." to point to my private ~/tmp directory then I can make the default claws-mail.profile work.  So, that profile is fine and wasn't working because of my own customisation.

Sorry for the noise... please close this...

**Comment by chiraag-nataraj** [comment]
You can close it yourself 😃 (Right below the comment box, you should see a "Close" button)

**Comment by martin-schwenke** [comment]
Thanks... somehow I missed that.  :-)
