### ISSUE TITLE
Ability to turn off pid namespacing?

### ISSUE THREAD

**Issue by gi11es** [netblue30/firejail#892]
Related to #862 and my quest to manipulate cgroup assignment for subprocesses of a firejailed process, accessing the cgroup vfs is one thing, but in order to add a subprocess to a cgroup, one needs to know its true pid. But firejail namespaces the pids, which makes knowing the real pid impossible.

I couldn't find a way to turn off pid namespacing, did I miss something? Out of curiosity, is it a deliberate feature or a side-effect of some system folder/file being hidden by firejail?

Anyway, if you have any idea on how pid namespacing could be turned off, it would be greatly appreciated.

**Comment by netblue30** [comment]
You cannot turn off PID namespace, it is hardcoded deep inside the program. If you do "ps aux" outside of sandbox you can see the real PID for all sandboxed processes.
