### ISSUE TITLE
Firefox doesn't accept SSL certificates anymore

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#896]
Today on my Fedora system I got Firefox 49.0.2 and the newest Firejail version from the heikoada-firejail copr. After starting Firefox it would no longer accept **ANY** SSL certificates. The same happened in Thunderbird 45.4.0 - obviously because firefox.profile is included in its profile.

Only after commenting the `private-etc` line in firefox.profile everything worked again as expected. So something has changed - presumably in Firejail, as there was no new Thunderbird version, and Thunderbird should not be affected by changes in Firefox itself. 

If I'm not mistaken the `private-etc` line hasn't changed lately so it must be caused by something else.

EDIT: I should have mentioned that Firefox and Thunderbird started un-sandboxed didn't have any problems.

**Comment by curiosity-seeker** [comment]
It seems that I found the culprit: `alternatives` is missing in the `private-etc` line. After adding it all is well.

The funny thing is that I have such an entry in my individual firefox.profile in ~/.config/firejail with /etc/firejail/firefox.profile included. So far I had no problems  - doesn't it take precedence over the `private-etc` line in /etc/firejail/firefox.profile anymore?

**Comment by netblue30** [comment]
I took out private-bin from the profile, thanks.

**Comment by curiosity-seeker** [comment]
Yes, but how can taking out private-bin cause this problem?

**Comment by netblue30** [comment]
Sorry, I meant private-etc.
