### ISSUE TITLE
Wrong icons in Firefox when firejailed under KDE 4

### ISSUE THREAD

**Issue by fld** [netblue30/firejail#902]
Using: 
- Debian 8.6
- Firefox 49.0 (jessie-backports/debian-mozilla) (uses GTK3)
- KDE 4 plasma-desktop
- Widget style: Oxygen
- Icon theme: Breeze
- GTK2 Theme: Raleigh
- GTK3 Theme: oxygen-gtk

A different (wrong) set of icons is used in a firejailed firefox.

To get the icons working, I had to add:
`--whitelist=~/.kde/share/config/oxygenrc` 
`--whitelist=~/.kde/share/config/kdeglobals`

This also fixed "qpdfview" looking like crap when opened via firefox "Open with..."

Sidenote: I have my icon theme stored under /usr/share/icons/.... but some people might have them under ~/.kde/share/icons/..., so maybe that should be whitelisted as well?

**Comment by netblue30** [comment]
Fixed. I added them in whitelist-common.inc, so the icons will be available in all programs. I also added ~/.kde/share/icons. Thanks.
