### ISSUE TITLE
vlc segfault on debian jessie

### ISSUE THREAD

**Issue by fld** [netblue30/firejail#904]
On Debian Jessie, using latest package versions:
vlc 2.2.4-1\~deb8u1
firejail 0.9.44-1\~bpo8+1
and KDE 4 Plasma Desktop

VLC instantly segfaults when you press Ctrl+O (Media -> Open File...)

```
% firejail vlc
Reading profile /etc/firejail/vlc.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Parent pid 12051, child pid 12052
Child process initialized
VLC media player 2.2.4 Weatherwax (revision 2.2.3-37-g888b7e89)
[00000000008b9e88] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
libudev: udev_monitor_new_from_netlink_fd: error getting socket: Operation not supported
ERROR: Running KSycoca failed.

Parent is shutting down, bye...
```

dmesg:
`kernel: [169047.187662] vlc[12065]: segfault at 0 ip 00007fd63838cc3f sp 00007fd6441a0530 error 4 in libkio.so.5.14.2[7fd63819300
0+2c2000]`

**Comment by valoq** [comment]
Any message in the journal?
Using journalctl -f while pressing running firejail --tracelog vlc and pressing Crtl+O might give a hint

I suspect the respective grafic framework used by your vlc needs additional files whitelistet.

**Comment by fld** [comment]
nope, only the "kernel:" segfault message in journal

**Comment by netblue30** [comment]
This is kind of ugly. It is looking for a video capture card or a video camera, and it needs "protocol netlink" to be enabled. I put a fix in, thanks.
