### ISSUE TITLE
Thunderbird: Okular can't open PDF files

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#908]
A couple of days ago I noticed that Okular no longer opens attached PDF files in Thunderbird. Every time I get an error message like

`Can't open /tmp/mozilla_hank0/example.pdf`

After some investigation I found the culprit: The Thunderbird profile contains

`include /etc/firejail/firefox.profile`

and that one the rule

`private-tmp`

After commenting that rule everything works nicely. However, that rule certainly makes sense in the firefox.profile. So the question is if 

`include /etc/firejail/firefox.profile`

should be removed from thunderbird.profile. If I comment that entry and I click links in Thunderbird they are still opened in a firejailed Firefox. Even is Firefox is not yet open it is **not** started as a sub-process of the firejailed Thunderbird (according to firejail --tree) but as an own firejailed process. Perhaps because I'm using symlink invocation?

My suggestion is to rewrite the Thunderbord profile like this:
```noblacklist ~/.gnupg
mkdir ~/.gnupg
whitelist ~/.gnupg

noblacklist ~/.thunderbird
mkdir ~/.thunderbird
whitelist ~/.thunderbird

noblacklist ~/.cache/thunderbird
mkdir ~/.cache/thunderbird
whitelist ~/.cache/thunderbird

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-devel.inc

caps.drop all
netfilter
nonewprivs
noroot
protocol unix,inet,inet6,netlink
seccomp
tracelog

whitelist ${DOWNLOADS}

include /etc/firejail/whitelist-common.inc
```

**Comment by netblue30** [comment]
What happens if before "include /etc/firejail/firefox.profile" you add a "ignore private-tmp"?
`````
ignore private-tmp
include /etc/firejail/firefox.profile
`````
This should disable private-tmp in firefox.profile.

**Comment by curiosity-seeker** [comment]
Ah, yes - this works, indeed! I had completely forgotten about the `ignore` command - sorry!

Okular is now able to open PDF files.

**Comment by netblue30** [comment]
I pushed it in the profile file in git, thanks.
