### ISSUE TITLE
"--allow-debuggers" always fails

### ISSUE THREAD

**Issue by andijh92** [netblue30/firejail#909]
Hello!

If I execute firejail --debug --allow-debuggers gdb firefox
,I get the following Error: cannot establish communication with the parent, exiting...
and more > http://pastebin.com/jNFDEEF3

I'm using firejail 0.9.45 and xubuntu 16.04.
firejail --version > http://pastebin.com/b72Vzm6U 

Thanks,
Andi

**Comment by netblue30** [comment]
This is what I get on my system:
`````
$ firejail --allow-debuggers gdb /usr/lib/firefox-esr/firefox-esr
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 5811, child pid 5812
Child process initialized
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/firefox-esr/firefox-esr...(no debugging symbols found)...done.
(gdb) 

`````
Does it work if you use --noprofile?
`````
$ firejail --noprofile --allow debuggers gdb firefox
`````

**Comment by andijh92** [comment]
hello

i still have the same problem with --noprifile. i also reinstalled the os. still the same. but i have an error in my message above. i'm using ubuntu 16.10 not 16.04. sry.

**Comment by andijh92** [comment]
i tried now ubuntu 16.04. it also fails with version 0.9.44 and version 0.9.45

**Comment by netblue30** [comment]
I'll have to try it out, here on Debian Jessie seems to be fine.

**Comment by andijh92** [comment]
now it works on ubuntu-16-04 with 0.9.45. i did a reinstall of the os. maybe installing firejail with apt-get and then overwriting it with ./configure; make ; make install caused problems.

**Comment by netblue30** [comment]
There was a problem with ptrace code in Linux kernels prior to 4.8, so I had to disable --allow-debuggers if I detect an older kernel - this happened in the last two or three days.

**Comment by netblue30** [comment]
Closing... will reopen if necessary.
