### ISSUE TITLE
Support symlinks for --private-home

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#910]
Hi, after rebuilding firejail from git (including https://github.com/netblue30/firejail/commit/e75dfa59eb8e74b0f1bae2be6e4d981205edcda2) I'm seeing the issues raised in https://github.com/netblue30/firejail/issues/886 again. The committed fix simply doesn't work for me and seems to have broken usage of '--private=$HOME' ..

As I'm seeing the exact same outputs as in https://github.com/netblue30/firejail/issues/886 I left those out here for brevity.

On a side note, I tested all my firejail scripts with '--private' (which should be equivalent to --private=$HOME) once more, but that still doesn't work either. According to the man it's possible to use '--private-home=file,directory'. That doesn't seem to work when specifying symlinked dir(s) in $HOME as per the below. I take it this is by design, because this is showing on firejail built without commit e75dfa59eb8e74b0f1bae2be6e4d981205edcda2 ..

$ ls -l $HOME | grep claws
lrwxrwxrwx  1 dirkos dirkos     32 Nov 13 06:27 .clawsmail -> /mnt/lab16.sda3/user/.clawsmail/
lrwxrwxrwx  1 dirkos dirkos     33 Nov 13 06:27 .claws-mail -> /mnt/lab16.sda3/user/.claws-mail/

$ firejail --private-home=.claws-mail claws-mail
Error: invalid private directory

$ firejail --private-home=/home/dirkos/.claws-mail claws-mail
Error: file /home/dirkos/.claws-mail is not in user home directory

For now I omit the referenced commit in firejail to get '--private=$HOME' working again, but I considered it important enough to report this here.

Regards

**Comment by netblue30** [comment]
Currently --private-home does not allow symbolic links outside home directory. You do have it as a symbolic link. 
`````
$ ls -l $HOME | grep claws
lrwxrwxrwx 1 dirkos dirkos 32 Nov 13 06:27 .clawsmail -> /mnt/lab16.sda3/user/.clawsmail/
lrwxrwxrwx 1 dirkos dirkos 33 Nov 13 06:27 .claws-mail -> /mnt/lab16.sda3/user/.claws-mail/
`````

I'll add support for it, the only condition will be to have the directory  - /mnt/lab16.sda3/user/.clawsmail/ in your case - owned by the regular user.

**Comment by glitsj16** [comment]
That would be great, thanks. The condition you mention is something I rely on as well, so that would fit in nicely. In regards to commit https://github.com/netblue30/firejail/commit/e75dfa59eb8e74b0f1bae2be6e4d981205edcda2 breaking '--private=$HOME I'm going through some more testing right now. Will report back here on that.

**Comment by netblue30** [comment]
I think I have a fix on the main branch.

**Comment by glitsj16** [comment]
Sorry for the late reply. Your fix works great. Thanks!

**Comment by netblue30** [comment]
No problem.
