### ISSUE TITLE
launching non-existing command - should be verbose

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#913]
Easiest way to explain, consider this command:

    firejail --noprofile --shell=none abra-cadabra

Expected to see:
`command not found`, printed by firejail

Actual:
<pre>
firejail --noprofile --shell=none abracadabra
Parent pid 30929, child pid 30930
Child process initialized

Parent is shutting down, bye...
</pre>

Sorry for the rough description, I think it's the easiest way to explain what's desired.

**Comment by Fred-Barclay** [comment]
Fixed in 680b84b4490e88a6ec40c7648e5712eff5385e82, compare to the new output:
```
$ firejail --noprofile --shell=none abracadabra
Parent pid 15897, child pid 15898
Child process initialized in 24.05 ms
Error: no suitable abracadabra executable found

Parent is shutting down, bye...
```
