### ISSUE TITLE
--net=eth0 only works as root

### ISSUE THREAD

**Issue by Kalle72** [netblue30/firejail#915]
I am on gentoo hardened and have the problem that --net=eth0 (in my special case --net=enp4s0) only works as root, but not as regular user. 

Firejail claims: "Error: only --net=none is allowed to non-root users"

Therefore it is impossible to start firefox with a separate network-stack.

Thanks in advance 
Kalle

**Comment by kaskasbarakas** [comment]
You want to build without the useflag `network-restricted` then you can run --net= with a normal user.

**Comment by Kalle72** [comment]
Ahh, thanks a lot!
