### ISSUE TITLE
Applications opening as superuser mode

### ISSUE THREAD

**Issue by suknight** [netblue30/firejail#917]
When i open `firejai firefox`  `firejail vlc` the applications are opening as superuser mode.
 firefox as superuser mode [https://i.imgur.com/x8EazKR.png](url)
Same case for vlc,opera,deluge,chromium,thunderbird too.
This existed in the firejail version provided in distro repos. So i installed the latest deb(firejail_0.9.44_1_amd64.deb) and still facing the same problem. 
Firejail version: firejail version 0.9.44
Desktop: MATE 1.14.1  Distro: Linux Mint 18 Sarah
Kernel: 4.4.0-21-generic x86_64 (64 bit)

**Comment by valoq** [comment]
This is a known issue in mate: #258 
The applications are actually run as a normal user.
You can verify this by running ps -ef

**Comment by suknight** [comment]
@valoq thanks
