### ISSUE TITLE
Disable warning for disabled networking

### ISSUE THREAD

**Issue by peterzhu2118** [netblue30/firejail#919]
I have set Firejail to be quiet. If I set networking to be off in `firejail.config` I get the output `Warning: networking features are disabled in Firejail configuration file` every time I run something. How can I disable this?

**Comment by vn971** [comment]
Firejail does have a quiet mode `firejail --quiet --noprofile echo 123`, would that work for you? It won't print any firejail-specific warnings that way AFAIUnderstand.

In normal mode, firejail does consider the "networking features" thing to be serious enough for a warning.

**Comment by peterzhu2118** [comment]
Even when using the `--noprofile` flag the `firejail.config` file is still loaded right? Is there some way of not disabling the profile while not printing the warning?

**Comment by vn971** [comment]
Good question. I don't know (I've only contributed documentation and profiles so far). Could you just edit the system-wide profile `/etc/firejail/default.profile` ?

**Comment by vn971** [comment]
@peterzhu2118 the profile `/etc/firejail/default.profile` is NOT loaded when you use --noprofile. `firejail.config` is loaded in all cases.
Not that, if I understand it correctly, firejail prints a warning only when you try to use an unsopported feature. Just disabling "networking" and launching `firejail --noprofile` does not result in a warning on my system.

**Comment by peterzhu2118** [comment]
@vn971 So would it be possible to load that profile without outputting the warning? What do you mean by an "unsupported feature"? Does that mean disabling networking is an unsupported feature?

**Comment by netblue30** [comment]
It is a bug, --quiet should have disabled the message. I'll make sure it gets fixed in the next release.

**Comment by peterzhu2118** [comment]
@netblue30 When can I expect the next release? I wish I could fix this but unfortunately I don't know C.

**Comment by netblue30** [comment]
My plan is to have it out by the end of next week.

**Comment by peterzhu2118** [comment]
@netblue30 Thats great. Thank you so much!

**Comment by netblue30** [comment]
No problem. I'll let you know when is done.

**Comment by netblue30** [comment]
All fixed. I would suggest you move on the bugfix branch here: https://github.com/netblue30/firejail/tree/0.9.44-bugfixes - it is more stable, almost ready for a new release.
