### ISSUE TITLE
debian package build does'nt work

### ISSUE THREAD

**Issue by Micha-Btz** [netblue30/firejail#92]
hi,

i try to build a package on my debian sid, AMD64, but something went wrong.
https://gist.github.com/Micha-Btz/d52c9c075349e75479d6

Please see gist for detail.

Micha

**Comment by netblue30** [comment]
I usually run it as root (./mkdeb.sh or make debian). It is a huge hack. I will fix it so you can run it as a regular user.

**Comment by reinerh** [comment]
JFYI: Firejail 0.9.32 has just been uploaded to unstable: https://tracker.debian.org/pkg/firejail
It should be available in a couple of hours.

**Comment by netblue30** [comment]
Thanks! Also thanks for the Ubuntu package.

**Comment by netblue30** [comment]
Fixed. As regular user, run  "./configure && make deb"

**Comment by Micha-Btz** [comment]
thanks
