### ISSUE TITLE
mkdeb.sh fails

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#925]
When running mkdeb.sh the following error appears:  

dpkg-deb: error: failed to open package info file 'debian/DEBIAN/control' for reading: No such file or directory

**Comment by netblue30** [comment]
I usually run it as root after ./configure:
`````
$ ./configure --prefix=/usr
$ su
# make deb
`````
Just did a test this morning, it should work.

**Comment by valoq** [comment]
Sorry my mistake. I tried to run mkdeb.sh directly.

However you should not run "make deb" as root. Its also not necessary.
