### ISSUE TITLE
private-bin fails when executing binaries in /usr/lib

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#926]
On debian testing mupdf fails to start (using the git version from today)
The reason is private-bin mupdf

When investigating why the private-bin restriction prevents mupdf from starting it turned out that
on debian stetch (testing) /usr/bin/mupdf is only a helper binary executing /usr/lib/mupdf/mupdf-x11

however adding mupdf-x11 or /usr/lib/mupdf/mupdf-x11 to the private-bin list does not work likely because /usr/lib is not in the usual PATH variable

when executing "firejail --profile=mymupdf.profile /usr/lib/mupdf/mupdf-x11 testfile.pdf" the private-bin has no effect and mupdf works

I suspect there might be more applications executing binaries in /usr/lib/ which will fail if private-bin is used

Is there any other solution except to remove private-bin from all application profiles that execute binaries in /usr/lib

**Comment by chiraag-nataraj** [comment]
That's weird. I use Libreoffice every so often, and I use it within firejail (profile is in my repo: https://github.com/chiraag-nataraj/firejail-profiles). Libreoffice's actual binary is in /usr/lib/libreoffice/program/soffice, yet it manages to run. (And yes, I use private-bin in my profile). Could this be purely an issue with mupdf? You're using the default profile, right?

**Comment by valoq** [comment]
Thanks for the info, this solved it. Seems like it was not a PATH issue after all.

I wonder why debain has changed mupdf to use those programs. On other distributions mupdf runs fine without them

By the way, alternatives and X11 are not needed in private-etc, at least I did not have any issues without them.

**Comment by chiraag-nataraj** [comment]
I whitelist them because that's where cursors are stored :wink: But yes, strictly speaking, they're not *necessary* xD
