### ISSUE TITLE
have systemd apply firejail

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#927]
Is there a way to have systemd apply firejail
On gnome many applications are started by systemd and firejail has no effect even with symbolic links in PATH. I could not get any application automatically started with firejail.
It would be awesome to have a way to tell systemd to start apps with firejail.

**Comment by curiosity-seeker** [comment]
This is actually easy to do. See https://wiki.archlinux.org/index.php/Systemd#Editing_provided_units

Basically, you have to create a new unit file or a drop-in snippet in /etc/systemd/system and change the ExecStart= line to something like:

`ExecStart=/usr/bin/firejail /usr/sbin/dnsmasq -k --all-servers --user=nobody`

This is what I've been doing for dnsmasq and dnscrypt-proxy for some time on Arch and Fedora. Works well.

**Comment by valoq** [comment]
Thanks for the info.

It would be nice to find a way to have firejail do that automatically if possible
