### ISSUE TITLE
noroot missing in some profiles

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#929]
Some profiles like file and several compression tools are missing the noroot option as this has been remove from their profiles some time ago. 
Why is that? 
Especially "file" should have noroot if possible

**Comment by netblue30** [comment]
Yes, some applications are crashing on some of the platforms in the presence of noroot. For compression tools I had to leave it out because it modifies the file owners to a uid, of 65534 if the user is not found in the namespace.
