### ISSUE TITLE
Option to start new sandbox from another sandbox

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#931]
Hi!

I use [ANGRYsearch](https://github.com/DoTheEvo/ANGRYsearch) with firejail. When I open an mp4 file, vlc is opened within the same sandbox.
Is it possible to add an option e.g.: `outside vlc,evince,gedit` to specify which programs to be opened in their own sandbox with their profile?

Thanks.

**Comment by netblue30** [comment]
Once you set a sandbox, there is no way to start applications outside the sandbox.
