### ISSUE TITLE
Quiet-by-default seems to be broken

### ISSUE THREAD

**Issue by peterzhu2118** [netblue30/firejail#932]
I just followed the instructions to update my Firejail after an [issue](https://github.com/netblue30/firejail/issues/919). After installing the 0.9.44-bugfixes branch the line `quiet-by-default yes` seems to have stopped working (`--quiet` still works).  Master branch seems to be experiencing the same issues too. At first I thought I was going insane but after reverting to the 0.9.44 release the issue disappeared (but the previous issue came back of course) so I believe this is a bug.

**Comment by netblue30** [comment]
I think what happens  is /etc/firejail/firejail.config gets overwritten during software install, and quiet-by-default is disabled. Take a look in that file, it seems to be working fine for me on 0.9.44-bugfixes branch.

**Comment by peterzhu2118** [comment]
I checked the file at every step and the quiet option is always enabled. I used the same file for the 0.9.44-bugfixes branch and the release. But the 0.9.44-bugfixes branch prints out all the stuff at startup while the release does not.

**Comment by netblue30** [comment]
If you do a firejail --version should say version 0.9.44.1. I'll try again on my setup.

**Comment by peterzhu2118** [comment]
@netblue30 It is indeed 0.9.44.1.
