### ISSUE TITLE
firecfg options

### ISSUE THREAD

**Issue by valoq** [netblue30/firejail#935]
looking at the firecfg code I found this line https://github.com/netblue30/firejail/blob/master/src/firecfg/main.c#L458

Why the for loop? If any provided option is valid only that option is executed and then return takes effect. Any other options are ignored. Did I miss something or is this a bug and the intended purpose was to allow several options at once?

**Comment by netblue30** [comment]
It doesn't return from the loop on line https://github.com/netblue30/firejail/blob/master/src/firecfg/main.c#L465

**Comment by valoq** [comment]
Alright thanks
