### ISSUE TITLE
Whitelisted keepassx in web browser profiles

### ISSUE THREAD

**Issue by derekyerger** [netblue30/firejail#937]
In commit c3b33900177a67d052bd4451d54f78994e25131a all web browser profiles had `noblacklist` and `whitelist` lines for keepassx entries appended, like so:

```
noblacklist ~/keepassx.kdbx
```
...
```
# lastpass, keepassx
whitelist ~/.keepassx
whitelist ~/.config/keepassx
whitelist ~/keepassx.kdbx
whitelist ~/.lastpass
whitelist ~/.config/lastpass
```

These are appended to 15 browser profiles without a clear explanation.

Does this need to be in browser profiles? If anything, these locations should be blacklisted. There is no info about why this was added in the commit message, nor the release notes since 0.9.40.

**Comment by netblue30** [comment]
Lots of people are using keypass/lastpass with Firefox, so we had to enable them. You can easily build a custom profile with all these lines commented out. Copy /etc/firejail/firefox.profile in ~/.config/firejail/ directory and modify it.

**Comment by curiosity-seeker** [comment]
@derekyerger : I don't understand why this should be a problem. If you don't use those password managers, those directories don't exist. So whitelisting them doesn't do any harm. And if you're using any of them your browser needs access to those directories. It's that easy, IMHO.

**Comment by derekyerger** [comment]
Still not understanding it, I've only ever used KeePassX to auto-type login credentials into my browser. This only requires that KeePassX has access to its own data, as it handles the user-initiated hand-off of data to the browser through sending keystrokes.

Isn't this the point, over using password managers that are built into almost every major web browser?

**Comment by SYN-cook** [comment]
It is possible to use KeePass/KeePassX together with browser extensions, and if these files were not whitelisted, the extensions obviously wouldn't work any more. 

In your case it probably makes more sense to comment out these lines, as netblue30 has already suggested, in order to isolate browser and password manager as good as possible from each other.

**Comment by SYN-cook** [comment]
Either those KeePass/KeePassX users with KeeFox (or another browser extension) need to tamper with their browser.profile to have everything working, or those users without browser extension need to modify their browser.profile to have a better security. It looks we can't have both.

But why do we need these lines?

`whitelist ~/.keepassx`
`whitelist ~/.config/keepassx`

**Comment by SYN-cook** [comment]
#993
