### ISSUE TITLE
atom profile breaks git integration

### ISSUE THREAD

**Issue by raffomania** [netblue30/firejail#938]
When using the atom profile, atom doesn't hide files specified in the `.gitignore` file anymore. I'm not sure how this happens, atom definitely has access to the .gitignore file.

**Comment by netblue30** [comment]
Seems to be working fine for me, I can access .gitignore file:
`````
$ firejail --profile=/etc/firejail/atom.profile /bin/bash
Reading profile /etc/firejail/atom.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Parent pid 31080, child pid 31081
Child process initialized
[netblue@debian firejail]$ cat .gitignore
*.o
*.so
*~
*.swp
*.rpm
*.gcda
*.gcno
Makefile
config.log
config.status
firejail-login.5
[...]
`````

What exactly are you doing?

**Comment by raffomania** [comment]
Example `.gitignore`:
    
    test.txt

in a folder with `test.txt` and `.gitignore` present, I start atom with the firejail profile, making sure that `Settings->Packages->tree-view->Hide VCS Ignored Files` is enabled. Atom shouldn't show `test.txt` in the sidebar, but still does.
