### ISSUE TITLE
add an --ignore option

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#94]
Hi! 
I have this common profile:
> # block.inc
 include /etc/firejail/disable-mgmt.inc
 blacklist /media
netfilter
caps.drop all
seccomp
noroot
nogroups
shell none

I can't use this profile with Steam since it includes *seccomp* or with command line programs because of *shell none*. So like *noblacklist* ignores blacklisted files and/or folders, an *--ignore < option >* would ignore other options like *seccomp, shell* etc.
Thanks.

**Comment by netblue30** [comment]
I move the discussion here: https://github.com/netblue30/firejail/issues/86

I am pushing for a full fix, with a dual 32/64 filter. You'll be able to run steam, wine, or any other 32bit executable with default seccomp filter support.

**Comment by nick75e** [comment]
I think you misunderstood what I meant.
It's not about running Steam with seccomp but ignoring options from included profiles !

**Comment by netblue30** [comment]
Sorry! I'll implement it.

**Comment by netblue30** [comment]
All set! Example:
`````
$ firejail --ignore=seccomp --ignore=shell --profile=block.inc
`````

**Comment by nick75e** [comment]
Thanks! That was fast! 
Will it also be available in profiles like *noblacklist*?

**Comment by netblue30** [comment]
You're welcome. Sure, I can do that.

**Comment by netblue30** [comment]
All done.
