### ISSUE TITLE
If name of the sandbox isn't defined...

### ISSUE THREAD

**Issue by CrisBRM** [netblue30/firejail#942]
... it should be the name of the application by default.

**Comment by netblue30** [comment]
What happens if you have multiple instances of the same application sandboxed?

**Comment by CrisBRM** [comment]
That's precisely why I proposed this. To make it more hassle free to use --join=application.
Basically, yesterday I was playing around with firejail and trying to join an existing firefox sandbox, but couldn't even though the name matched. Later I read the documentation only to find out I had to name the sandbox beforehand. 
If there are extra instance of the same application sandboxed, then maybe the naming convention should be as follows:

First application: application1
Second application without explicitly issuing --join: application2
and so on

**Comment by CrisBRM** [comment]
Just found an odd behaviour. Firejail allows you to have two sandboxes with the exact same name.

I opened firefox with ```firejail --name=firefox firefox``` and launched mpv on youtube with the extension play with mpv. Firefox was then closed, but mpv, the child process, is still working, so, issuing ```firejail --list``` results in

```bash
λ desktop ~ → firejail --list
2311:desktop:firejail --name=firefox firefox 
5941:desktop:firejail --list 
```

Then I opened another instance of firefox, using the same ```firejail --name=firefox firefox``` command and issued the same command to list active sandboxes:

```bash
λ desktop ~ → firejail --list
2311:desktop:firejail --name=firefox firefox 
5998:desktop:firejail --name=firefox firefox 
6155:desktop:firejail --list 
```

**Comment by netblue30** [comment]
OK, I'll mark it as an enhancement and try to bring it in.

**Comment by CrisBRM** [comment]
Thanks!

**Comment by chiraag-nataraj** [comment]
As far as I know, this still isn't in. @netblue30 Is there an easy way to keep track of how many instances of an application are open? Or is it easier to just generate a random number and append it to the program's name?

**Comment by chiraag-nataraj** [comment]
This should be in...closing.
