### ISSUE TITLE
gajim.profile fix

### ISSUE THREAD

**Issue by ra1nb0w** [netblue30/firejail#948]
I added
noblacklist ${HOME}/.cache/gajim
noblacklist ${HOME}/.local/share/gajim
noblacklist ${HOME}/.config/gajim
above whitelist otherwise gajim doesn't start because .cache/gajim and others are root.
Is it the right fix?

thanks for your work!!

**Comment by valoq** [comment]
Looks good, than you for reporting.
I created a pull request to get this fixed.

@netblue30 shouldn't whitelist additionally have the same effect as noblacklist?

**Comment by netblue30** [comment]
all set in git, thanks!
