### ISSUE TITLE
mounted devices inaccessible

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#95]
Hi!
If I want a firejail session to access a device, I have to mount it before I launch the session otherwise I get this: 
![capture du 2015-10-24 17 40 20](https://cloud.githubusercontent.com/assets/10011516/10711411/918c8382-7a7a-11e5-9fe0-6bb4fdf7c90c.png)
*(This is from /media/$USER/, default location for temporary mounted devices in Ubuntu)*

firejail 0.9.32 on Linux Mint 17.2

**Comment by netblue30** [comment]
That's true. It is because of the mount namespace. No additional mounts will be visible in the sandbox once it is started. You'll have to mount the device before the sandbox is created.
