### ISSUE TITLE
Questions regarding inheritance

### ISSUE THREAD

**Issue by CrisBRM** [netblue30/firejail#954]
When you spawn a firejailed process like firefox, what happens when you spawn a child process from within it, like mpv? I tried to add ~/.config/mpv to the firefox.profile whitelist but mpv still cannot read mpv.conf and the scripts inside its configuration folder.
 
So my questions are:

- Do the children of the main process have access to the firejail profiles?

- When you spawn a process from within a sandbox, does that project inherit the profile of the parent process?

- If not, what profile does it use?

**Comment by netblue30** [comment]
> So by adding e.g. "include /etc/firejail/mpv.profile" in your firefox profile, it should be possible to start mpv within the firefox jail.

It would work if both profiles were whitelisted profiles. In this case, mpv is a blacklisted profile, so you wold have to copy /etc/firejail/firefox.profile in ~/.config/firejail ("cp  /etc/firejail/firefox.profile ~/.config/firejail) and edit it. At the end of the file add a whitelist statement as follows:
`````
whitelist ~/.config/mpv
`````

**Comment by valoq** [comment]
Shouldn't "noblacklist ~/.config/mpv" as in the mpv.profile file do the trick as well?
