### ISSUE TITLE
Spoof D-Bus machine-id

### ISSUE THREAD

**Issue by robotanarchy** [netblue30/firejail#955]
Hi there,

I've noticed that Tor Browser on Arch Linux requires `/etc/machine-id` to be present, or otherwise it will segfault.
D-Bus seems to generate this ID on the first installation and keeps it forever, to uniquely identify the machine.
http://0pointer.de/public/systemd-man/machine-id.html

How would I spoof that ID with a firejail profile in combination with `private-etc`?

Thanks for making firejail!

**Comment by valoq** [comment]
Not sure how to do that with firejail.

However please report that issue to the tor people as well.
This sounds like a potentially serious flaw.

**Comment by robotanarchy** [comment]
Tor Bugreport: https://trac.torproject.org/projects/tor/ticket/20884

**Comment by netblue30** [comment]
I'll put something in, and I'll ask you to try it. Will it still crash if we just put a different random number there?

**Comment by robotanarchy** [comment]
Okay, let's do that. It did not crash when I put a different number in the file.

**Comment by netblue30** [comment]
All set, give it a try. A new ID is generated by default. If you need to use the real machine-id in the sandbox, you would need to add --machine-id switch.

**Comment by robotanarchy** [comment]
Tested with the git version and works as expected - I get a random machine id every time I start the profile (verified by typing file:///etc/machine-id into the browser).
Thanks for the quick implementation!

**Comment by netblue30** [comment]
Cool, thanks.
