### ISSUE TITLE
Reverse scrolling not working in firejail

### ISSUE THREAD

**Issue by mesuutt** [netblue30/firejail#956]
Hi I am using reverse scrolling on my computer. So I want to use reverse scrolling with firejail too.  I am using firejail 0.9.44 on Arch linux.

I created a directory for private home and added my .Xmodmap file in the directory.

``` bash
firejail \
    --private=~/tmp/google_chrome \
    google-chrome-stable
```

When I open the google-chrome in firejail reverse scrolling not working.

My .Xmodmap file:

```
pointer = 1 2 3 5 4 7 6 8 9 10 11 12
```

How can I solve this?

**Comment by chiraag-nataraj** [comment]
Are you sure reverse scrolling works in Google Chrome if launched outside of firejail? Gnome 3 (and GTK 3) break the old way of doing some stuff, including reverse scrolling. I had reverse scrolling stop working in Firefox because I was using xmodmap and had to use xinput instead (which does work).

**Comment by mesuutt** [comment]
@chiraag-nataraj Sorry, I  though this is related to firejail and opened an issue but google chrome reverse scroll not working also outsite of firejail.

I  tried with `xinput` instead `xmodmap` show as below,  Scroll direction changed in firefox but not changed in google chrome outsite of firejail too.

```bash
xinput set-button-map 11 1 2 3 4 5 7 6 8 9 10 11 12
```

**Comment by chiraag-nataraj** [comment]
You should try `xinput list-props <device number>` (use `xinput list` to figure out what the number of your device is). My touchpad has a "Natural Scrolling" property that I can set, which seems to work across programs.
