### ISSUE TITLE
Whitelisting folder?

### ISSUE THREAD

**Issue by peterzhu2118** [netblue30/firejail#961]
How do I whitelist a folder under `/root`? Right now I added `whitelist /root/temp` to the profile file but if I do `firejail ls /root/temp` it says the folder doesn't exist. I want to disable everything else (other folders).

**Comment by netblue30** [comment]
I'll add support for it, currently only user home, /dev, /media, /mnt, /opt, /srv, /var, and /tmp are supported by whitelist.

**Comment by peterzhu2118** [comment]
@netblue30 But my home folder is `/root`. If I do `echo $HOME` I get `/root`. But the whitelisting doesn't allow the program to read the files inside that folder (program says file is not found).

**Comment by peterzhu2118** [comment]
It seems to be caused by the `private` flag in the profile file, if I remove the flag it all works. But I need the program to be isolated so it can only see one folder.

**Comment by netblue30** [comment]
Let me look into it, for now get rid of "private" in the profile.

**Comment by peterzhu2118** [comment]
@netblue30 I need a new filesystem to be mounted on top of `/root` but I need one folder to carry over from the actual system into the new mounted one. Getting rid of `private` causes a huge security hole in my software.

**Comment by netblue30** [comment]
No problem, I'll add proper whitelisting support for /root.

**Comment by peterzhu2118** [comment]
@netblue30 Ok thanks! Please let me know when you implement it!

**Comment by netblue30** [comment]
I would say by the end of the weekend it should be in.

**Comment by netblue30** [comment]
It looks like is already supported! The problem is "private" command in the default profile for running root sandboxes. The profile is /etc/firejail/server.profile. Start the sandbox as root this way:
`````
# firejail --ignore=private --whitelist=/root/Documents
`````

**Comment by peterzhu2118** [comment]
@netblue30 Thanks, that fixed the problem. But is there any way to place that in a config file so that I don't have to type all of that in every time?

**Comment by netblue30** [comment]
Create a custom profile (as root):
`````
# mkdir -p ~/.config/firejail
# cp /etc/firejail/server.profile ~/.config/firejail/.
`````
Open ~/.config/firejail/server.profile and comment out private line (add a #).
