### ISSUE TITLE
GTK 3 theme in Xephyr sandbox?

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#965]
Lubuntu 14.04
firejail 0.9.44.2

My GTK 3 theme is Greybird.  When running GTK 3 apps in a firejail x11 sandbox (Xephyr), they use the Raleigh GTK theme.  This happens even with `--noprofile` option.

GTK 2 apps and Qt apps don't have this problem.

How to get the system GTK 3 theme to apply inside the Xephyr sandbox too?

**Comment by netblue30** [comment]
You need to run a window manager in xephyr, one that supports GTK3 themes. I usually run it with Openbox, but this is a very simple one, without any GTK3 support:
`````
$ firejail --x11=xephyr openbox
`````

**Comment by laniakea64** [comment]
Thanks, that would explain it.  I too use Openbox, both inside the sandbox (run like you show) and outside the sandbox (where it's started by LXDE).

So how does LXDE appear to get GTK 3 support in Openbox?

**Comment by netblue30** [comment]
I am also using LXDE outside the sandbox. Try this:
`````
$ firejail --profile=/etc/firejail/openbox.profile --private --x11=xephyr startlxde
`````

**Comment by laniakea64** [comment]
I don't seem to have a `startlxde` command :confused:

**Comment by netblue30** [comment]
What distro are you using?

I got this working on a Debian stable:

Create a script, shell.sh, and make it executable:
`````
$ cat start.sh
#!/bin/bash

openbox &
pcmanfm --desktop --profile LXDE &
lxpanel --profile LXDE &

$ chmod +x start.sh
`````
and start it in the sandbox:
`````
$ firejail --profile=/etc/firejail/openbox.profile --x11=xephyr ./start.sh
`````

It will start xpehyr and LXDE inside the sandbox, and it will reuse your LXDE configuration

**Comment by netblue30** [comment]
Also, don't use Shutdown/Reboot buttons in Logout menu, in the sandbox instance of LXDE!

**Comment by laniakea64** [comment]
> What distro are you using?

Lubuntu 14.04

> Create a script, shell.sh, and make it executable...

Same problem. :slightly_frowning_face: 

I notice that the icon theme in the sandbox reverts to GNOME.  I don't mind that so much though.  Is that related to the GTK 3 theme problem?

> Also, don't use Shutdown/Reboot buttons in Logout menu, in the sandbox instance of LXDE!

Thanks, that's good advice, I already found out the hard way on the Logout button :open_mouth:

**Comment by netblue30** [comment]
I have no idea how the GTK3 theme is working, probably there is some socket the sandbox disables.

**Comment by laniakea64** [comment]
Actually I see the same problems in a Xephyr without firejail.  Sorry about this.

**Comment by laniakea64** [comment]
... and with that information, problem solved. :smiley: 

GTK themes in the Xephyrs are apparently controlled by KDE's GTK apperance settings.  GTK 2 was set to Greybird, but GTK 3 was set to oxygen-gtk.

Fixed the GTK 3 setting and bam, Greybird GTK 3 theme in Xephyr, with and without firejail.

Not going to worry too much about the 'why'.  It might have something to do with using Konsole as my terminal emulator.  But whatever the reason, it works now.

Thanks netblue30.

**Comment by netblue30** [comment]
No problem, you gave me some ideas. From now I'll also move to LXDE inside xephyr, instead of the regular Openbox.
