### ISSUE TITLE
--shell=none breaks program arguments

### ISSUE THREAD

**Issue by dewbasaur** [netblue30/firejail#97]
Just upgraded to 0.9.32 and noticed I could no longer use ```firejail "firefox -no-remote"```. Trying to do so would give the error:
```execvp: No such file or directory```

After reading through the changes and tickets, I commented out ```--shell=none``` in the profile and it works again.

**Comment by netblue30** [comment]
I'll have to take shell=none out, thanks for letting me know.

**Comment by netblue30** [comment]
Fixed!
