### ISSUE TITLE
Why not a profile for Tor Messenger 

### ISSUE THREAD

**Issue by merlinnusr** [netblue30/firejail#973]
If you don't know what is Tor Messenger 
https://blog.torproject.org/blog/tor-messenger-beta-chat-over-tor-easily

I think firejail need a profile for  Tor Messenger what do you think

**Comment by netblue30** [comment]
Sure, if you play with Tor Messanger and build a profile, send it here and I'll include it. Anyway, the default profile is also very good.

**Comment by netblue30** [comment]
moved to https://github.com/netblue30/firejail/issues/1139
