### ISSUE TITLE
Feature request: Integrate with kafel seccomp-bpf configuration language

### ISSUE THREAD

**Issue by robertswiecki** [netblue30/firejail#976]
The current seccomp-bpf configuration language is quite rudimentary. It, for example, doesn't seem to allow to allowing/blocking syscalls based on arguments provided to syscalls, or to invoke signal or return no error (ERRNO(0)) but also not execute the syscall.

The https://github.com/google/kafel project provides most of that, and it compile both strings and files into working seccomp-bpf policies.

Policy examples: https://github.com/google/kafel/tree/master/samples

**Comment by netblue30** [comment]
Thanks for the link, I'll look into it.
