### ISSUE TITLE
Build and publish binaries automatically using CI

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#981]

**Comment by liloman** [comment]
Yeah, I saw they have the spec files but don't use them. 

Truly It's growing so much for one man project, it's insane the amount of work. :+1:

**Comment by Fred-Barclay** [comment]
We're now using Travis CI to build each commit, but binaries are not being published (see [this discussion](https://github.com/netblue30/firejail/commit/9e2319c136030192bf4aa9a738518ab2dc9a8367#commitcomment-23741582) for the reason why). The build url after each commit can be found at the bottom of the page https://travis-ci.org/netblue30/firejail under "Job Log".
