### ISSUE TITLE
Consider using CMake as a build system

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#982]
Because it has
* own installation framework including the ones needed to create packages
* a bunch of scripts to detect presence of libraries in system
* own testing framework
* a gui configurator

All of this is now done via shell scripts and sometimes brokes. For example I was unable to build a .deb using the provided script on my machine.

**Comment by netblue30** [comment]
It is kind of late to move to cmake and introduce a new dependency. I will consider it for new projects.

To make a .deb, run "sudo make deb".

**Comment by KOLANICH** [comment]
>To make a .deb, run "sudo make deb".

Thank you, this have worked!
