### ISSUE TITLE
firejail-default is not added into .deb and is not installed with deb installation

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#987]

**Comment by netblue30** [comment]
Yes, by default the deb packages built by "make deb" is without AppAromr support. To enable it, open mkdeb.sh file and replace the line "./configure --prefix=/usr" with "./configure --prefix=/usr --enable-apparmor". This will add all the necessary support to your deb package.

**Comment by Fred-Barclay** [comment]
@netblue30 What would be the advantages and disadvantages of enabling AppArmor support by default with `make deb`? 
I would have thought it would be better to enable it by default IMHO.

**Comment by netblue30** [comment]
--enable-apparmor introduces dependencies on AppArmor librararies. Some distributions don't have AppArmor support (CentOS, Fedora), so we have to keep the default software configuration without AppArmor. Also, most people don't enable AppArmor even if they have it available.
