### ISSUE TITLE
Move profiles into a separate repo and use as submodule

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#989]
This is needed to keep commit history of firejail (significant changes) and commit history of profiles (far less important changes) separately.

**Comment by JulienPalard** [comment]
Some project are merging their repos while other are splitting their repos…: 

https://docs.ansible.com/ansible/dev_guide/repomerge.html

If you want to list firejail core changes: `git log src`, and profiles changes: `git log etc`, and that's it.

**Comment by netblue30** [comment]
It will stay as is, a split will brake Arch, Debian, Gentoo and all the other people following it.
