### ISSUE TITLE
Can't use firejail for Counter-Strike (CSGO)

### ISSUE THREAD

**Issue by HereForTux** [netblue30/firejail#997]
When I have one isntance of steam running normaly on my computer with CSGO (Counter-Strike: Global Offensive) running, I am able to open another instance of steam using "firejail steam" in terminal but when I go to launch another instance of CSGO, it gives me the error "Only one instance of the game can be running at one time" in a window titled "Source - Warning" 

I am on manjaro and have tried running "firejail --private steam" to see if that would work but I get the error "Coulnd't set up Steam data - please contact technical support"

Does anyone know a fix for this? Am I doing something wrong. I would assume this applies to all source games, not just CSGO.

**Comment by netblue30** [comment]
> Only one instance of the game can be running at one time

Some games, also main browsers like firefox and chrome always impose a single instance active in the system.

**Comment by 0xE232FE** [comment]
You have to delete /tmp/*.lock to run another CSGO!
